### ISSUE TITLE
The Process results generator generates an out of memory error: RuntimeError: std::bad_alloc

### ISSUE THREAD

**Issue by MMa321** [ultralytics/ultralytics#10006]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Traceback (most recent call last):
  File "/home/ictrek/label-studio-ml-backend/label-studio-video-backend/yolo2.py", line 20, in <module>
    for result in results:
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 228, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 589, in warmup
    self.forward(im)  # warmup
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 423, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 128, in _predict_once
    x = m(x)  # run
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/modules/conv.py", line 54, in forward_fuse
    return self.act(self.conv(x))
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ictrek/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: std::bad_alloc

### Environment

Ultralytics YOLOv8.1.45 🚀 Python-3.9.19 torch-1.13.1 CUDA:0 (GRID RTX6000-12Q, 12288MiB)
Setup complete ✅ (8 CPUs, 7.8 GB RAM, 89.8/96.3 GB disk)

OS                  Linux-5.4.0-174-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.9.19
Install             pip
RAM                 7.76 GB
CPU                 Common KVM processor
CUDA                11.6

matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 1.13.1>=1.8.0
torchvision         ✅ 0.14.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

import cv2
from ultralytics import YOLO

#Load the YOLOv8 model
model = YOLO("/home/ictrek/label-studio-ml-backend/label-studio-yolov8-backend/yolov8n.pt")

#Open the video file
video_path = "/home/ictrek/label-studio-ml-backend/cat.mp4"
cap = cv2.VideoCapture(video_path)

#Loop through the video frames
while cap.isOpened():
# Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model.predict(frame, stream=True)
        print("results", results)
        for result in results:
            boxes = result.boxes
        # Visualize the results on the frame
        #annotated_frame = results[0].plot()

        # Display the annotated frame
        #cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

#Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MMa321** [comment]
free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       921Mi       4.8Gi       1.0Mi       2.0Gi       6.6Gi
Swap:            0B          0B          0B

**Comment by MMa321** [comment]
How much memory do you need to run a video inference

**Comment by glenn-jocher** [comment]
The memory required for running video inference with YOLOv8 can vary based on the model size, video resolution, and batch size. Here's a quick guide to help you estimate:

- **Model Size:** Larger models (e.g., YOLOv8x) require more memory than smaller ones (e.g., YOLOv8n).
- **Video Resolution:** Lower resolutions (e.g., 640x480) consume less memory than higher resolutions.
- **Batch Size:** A smaller batch size reduces memory usage.

As a rough estimate, running a YOLOv8n model on a 640x480 video with a batch size of 1 can work comfortably on a system with 8GB of RAM. For more demanding setups, adjusting the `imgsz` parameter can help manage memory usage:

```python
model.predict(source, imgsz=320)  # Lowering the inference size to 320x320
```

Keep an eye on your system's memory and adjust these parameters as needed! 🚀

**Comment by MMa321** [comment]
Thanks for your answer, I have adjusted the imgsz to 256

**Comment by glenn-jocher** [comment]
@MMa321 great to hear you've adjusted the `imgsz` parameter! If you're still encountering any issues or have further questions, please don't hesitate to ask. Happy to help! 😊
