### ISSUE TITLE
Regarding the how  use of "yolov8-cls-resnet50.yaml" configuration file for object segmantation one

### ISSUE THREAD

**Issue by RamPraveen2710** [ultralytics/ultralytics#10104]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

!yolo
task=segment
mode=train
model='yolov8-cls-resnet50.yaml'
imgsz=640
data=trashcan_inst_material.yaml
epochs={8}
batch=16
name=yolov8_res_seg
exist_ok=True
amp=False

hey i was using the configuration file "yolov8-cls-resnet50.yaml" for my object segmentation dataset but i am getting the below error can u pls say

Traceback (most recent call last):
File "/usr/local/bin/yolo", line 8, in
sys.exit(entrypoint())
File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/init.py", line 582, in entrypoint
getattr(model, mode)(**overrides) # default args from model
File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 673, in train
self.trainer.train()
File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 198, in train
self._do_train(world_size)
File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 370, in _do_train
self.loss, self.loss_items = self.model(batch)
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 88, in forward
return self.loss(x, *args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 264, in loss
self.criterion = self.init_criterion()
File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 371, in init_criterion
return v8SegmentationLoss(self)
File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/loss.py", line 256, in init
super().init(model)
File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/loss.py", line 159, in init
self.stride = m.stride # model strides
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1688, in getattr
raise AttributeError(f"'{type(self).name}' object has no attribute '{name}'")
AttributeError: 'Classify' object has no attribute 'stride'
terminate called without an active exception

### Additional

can you please help me to run my code

**Comment by glenn-jocher** [comment]
@RamPraveen2710 hello! It appears you're encountering an issue because the configuration file `yolov8-cls-resnet50.yaml` is designed for classification tasks, not segmentation. For object segmentation, you need to make sure your configuration file aligns with a segmentation architecture.

You might want to use or modify a configuration that's tailored for segmentation tasks. If you don't have a specific segmentation configuration, you can start by adjusting a known configuration that supports segmentation, like `yolov8-seg.yaml` (note: this is just a placeholder name for illustration purposes, please search for the actual YAML file meant for segmentation in the YOLOv8 repository or documentation).

Additionally, ensure your dataset and annotations are properly formatted for segmentation tasks. YOLOv8 requires masks annotations for segmentation, not just bounding boxes.

Here's a corrected version of your command assuming a hypothetical segmentation config file:

```bash
!yolo
task=segment
mode=train
model='yolov8-seg.yaml'  # Hypothetical segmentation YAML file
imgsz=640
data=trashcan_inst_material.yaml
epochs=8
batch=16
name=yolov8_res_seg
exist_ok=True
amp=False
```
Please make sure you replace `'yolov8-seg.yaml'` with the actual name of the segmentation config file provided by Ultralytics for YOLOv8.

Should you have further issues or need more specific advice, don't hesitate to reach out. Happy coding! 😊

**Comment by RamPraveen2710** [comment]
Thanks for the reply. I was doing the detection task instead of segmentation out of the present detection models available in yolov8 , which one suits better for my project "Underwater trash Object  detection"

please tell one which performs well in underwater detection task

![Screenshot 2024-05-06 154841](https://github.com/ultralytics/ultralytics/assets/128894673/1f9931fb-e7ac-45ab-84ac-911570e83ee5)

**Comment by RamPraveen2710** [comment]
thanks for the reply. How about ghost models??
Sorry for more quetions
Another thing is can i use pretrained model of yolov8n.pt or should i go with .yaml .? How to  and what to change modifying  hyperparameters. also how to apply for data augmentation techniques
