### ISSUE TITLE
Training data with custom dataset(did the labelling with labellmg)

### ISSUE THREAD

**Issue by Enryuwashere** [ultralytics/ultralytics#10119]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have this error "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[14], line 8
      5 model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
      7 # Use the model
----> 8 model.train(data=r"C:\Users\MAI\dataset2\data.yaml", epochs=50)  # train the model

File ~\ultralytics\ultralytics\engine\model.py:338, in Model.train(self, trainer, **kwargs)
    336     self.model = self.trainer.model
    337 self.trainer.hub_session = self.session  # attach optional HUB session
--> 338 self.trainer.train()
    339 # Update model and cfg after training
    340 if RANK in (-1, 0):

File ~\ultralytics\ultralytics\engine\trainer.py:190, in BaseTrainer.train(self)
    187         ddp_cleanup(self, str(file))
    189 else:
--> 190     self._do_train(world_size)

File ~\ultralytics\ultralytics\engine\trainer.py:320, in BaseTrainer._do_train(self, world_size)
    318 self.tloss = None
    319 self.optimizer.zero_grad()
--> 320 for i, batch in pbar:
    321     self.run_callbacks('on_train_batch_start')
    322     # Warmup

File ~\anaconda3\envs\torch_env\Lib\site-packages\tqdm\std.py:1178, in tqdm.__iter__(self)
   1175 time = self._time
   1177 try:
-> 1178     for obj in iterable:
   1179         yield obj
   1180         # Update and possibly print the progressbar.
   1181         # Note: does not call self.update(1) for speed optimisation.

File ~\ultralytics\ultralytics\data\build.py:42, in InfiniteDataLoader.__iter__(self)
     40 """Creates a sampler that repeats indefinitely."""
     41 for _ in range(len(self)):
---> 42     yield next(self.iterator)

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\dataloader.py:631, in _BaseDataLoaderIter.__next__(self)
    628 if self._sampler_iter is None:
    629     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    630     self._reset()  # type: ignore[call-arg]
--> 631 data = self._next_data()
    632 self._num_yielded += 1
    633 if self._dataset_kind == _DatasetKind.Iterable and \
    634         self._IterableDataset_len_called is not None and \
    635         self._num_yielded > self._IterableDataset_len_called:

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\dataloader.py:1346, in _MultiProcessingDataLoaderIter._next_data(self)
   1344 else:
   1345     del self._task_info[idx]
-> 1346     return self._process_data(data)

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\dataloader.py:1372, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1370 self._try_put_index()
   1371 if isinstance(data, ExceptionWrapper):
-> 1372     data.reraise()
   1373 return data

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\_utils.py:722, in ExceptionWrapper.reraise(self)
    718 except TypeError:
    719     # If the exception takes multiple arguments, don't try to
    720     # instantiate since we don't know how to
    721     raise RuntimeError(msg) from None
--> 722 raise exception

AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\ultralytics\data\base.py", line 252, in __getitem__
    return self.transforms(self.get_image_and_label(index))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\ultralytics\data\base.py", line 265, in get_image_and_label
    return self.update_labels_info(label)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\ultralytics\data\dataset.py", line 219, in update_labels_info
    segment_resamples = 100 if self.use_obb else 1000
                               ^^^^^^^^^^^^
AttributeError: 'YOLODataset' object has no attribute 'use_obb'"                                                                                                                        

can someone help me to fix this error? I dont know whether it was because of my dataset or not. Im new to this



### Additional

_No response_

**Comment by glenn-jocher** [comment]
Hey there! It looks like you've encountered an issue with training your model. The error message suggests that there's something unexpected happening within the data loading or model training process, rather than an issue with your dataset directly.

One possible step to troubleshoot this issue is to make sure your `data.yaml` is correctly formatted and the paths inside it correctly point to your images and labels. Ensure that all required fields are specified, including `train`, `val`, `nc` (number of classes), and `names` (list of class names).

Here's a quick checklist:
- Verify the structure of your `data.yaml`.
- Ensure all file paths in the `data.yaml` are correct.
- Ensure your environment is set up correctly with all necessary dependencies.

Here's an example `data.yaml` for clarity:

```yaml
train: ../train/images
val: ../val/images

nc: 2
names: ['class1', 'class2']
```

If your `data.yaml` looks correct and you're still facing issues, it could be related to the specific model version or your environment setup. In such cases, updating Ultralytics YOLO to the latest version might help:

```bash
pip install --upgrade ultralytics
```

And then, try running your training command again. If the issue persists, providing more details about your setup (like versions of Ultralytics YOLO and PyTorch, and the structure of your dataset) might help diagnose the problem further. Don't hesitate to reach out for more assistance. Good luck! 🍀

**Comment by Enryuwashere** [comment]
this is inside my data.yaml file
train: ../Train/images
val: ../Val/images
test: ../Test/images

nc: 7
names: ['fastener_1', 'crack', 'fastener_2', 'sleeper_l', 'sleeper_r', 'missing_items', 'broken_sleeper']

and  I have done the pip install --upgrade ultralytics  too

The model can read my data but the error still same
``` from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, [64, 128, 256]]          
YOLOv8n summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

New https://pypi.org/project/ultralytics/8.2.1 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.227 🚀 Python-3.11.8 torch-2.2.1 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=C:\Users\MAI\ultralytics\dataset2\data.yaml, epochs=50, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train13, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train13
Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    752677  ultralytics.nn.modules.head.Detect           [7, [64, 128, 256]]           
Model summary: 225 layers, 3012213 parameters, 3012197 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs\detect\train13', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning C:\Users\MAI\ultralytics\dataset2\Train\labels.cache... 1651 images, 0 backgrounds, 0 corrupt: 100%|███
val: Scanning C:\Users\MAI\ultralytics\dataset2\Val\labels.cache... 346 images, 0 backgrounds, 0 corrupt: 100%|████████
Plotting labels to runs\detect\train13\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train13
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/104 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 8
      5 model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
      7 # Use the model
----> 8 model.train(data=r"C:\Users\MAI\ultralytics\dataset2\data.yaml", epochs=50)  # train the model

File ~\ultralytics\ultralytics\engine\model.py:338, in Model.train(self, trainer, **kwargs)
    336     self.model = self.trainer.model
    337 self.trainer.hub_session = self.session  # attach optional HUB session
--> 338 self.trainer.train()
    339 # Update model and cfg after training
    340 if RANK in (-1, 0):

File ~\ultralytics\ultralytics\engine\trainer.py:190, in BaseTrainer.train(self)
    187         ddp_cleanup(self, str(file))
    189 else:
--> 190     self._do_train(world_size)

File ~\ultralytics\ultralytics\engine\trainer.py:320, in BaseTrainer._do_train(self, world_size)
    318 self.tloss = None
    319 self.optimizer.zero_grad()
--> 320 for i, batch in pbar:
    321     self.run_callbacks('on_train_batch_start')
    322     # Warmup

File ~\anaconda3\envs\torch_env\Lib\site-packages\tqdm\std.py:1178, in tqdm.__iter__(self)
   1175 time = self._time
   1177 try:
-> 1178     for obj in iterable:
   1179         yield obj
   1180         # Update and possibly print the progressbar.
   1181         # Note: does not call self.update(1) for speed optimisation.

File ~\ultralytics\ultralytics\data\build.py:42, in InfiniteDataLoader.__iter__(self)
     40 """Creates a sampler that repeats indefinitely."""
     41 for _ in range(len(self)):
---> 42     yield next(self.iterator)

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\dataloader.py:631, in _BaseDataLoaderIter.__next__(self)
    628 if self._sampler_iter is None:
    629     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    630     self._reset()  # type: ignore[call-arg]
--> 631 data = self._next_data()
    632 self._num_yielded += 1
    633 if self._dataset_kind == _DatasetKind.Iterable and \
    634         self._IterableDataset_len_called is not None and \
    635         self._num_yielded > self._IterableDataset_len_called:

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\dataloader.py:1346, in _MultiProcessingDataLoaderIter._next_data(self)
   1344 else:
   1345     del self._task_info[idx]
-> 1346     return self._process_data(data)

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\dataloader.py:1372, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1370 self._try_put_index()
   1371 if isinstance(data, ExceptionWrapper):
-> 1372     data.reraise()
   1373 return data

File ~\anaconda3\envs\torch_env\Lib\site-packages\torch\_utils.py:722, in ExceptionWrapper.reraise(self)
    718 except TypeError:
    719     # If the exception takes multiple arguments, don't try to
    720     # instantiate since we don't know how to
    721     raise RuntimeError(msg) from None
--> 722 raise exception

AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\ultralytics\data\base.py", line 252, in __getitem__
    return self.transforms(self.get_image_and_label(index))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\ultralytics\data\base.py", line 265, in get_image_and_label
    return self.update_labels_info(label)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MAI\anaconda3\envs\torch_env\Lib\site-packages\ultralytics\data\dataset.py", line 219, in update_labels_info
    segment_resamples = 100 if self.use_obb else 1000
                               ^^^^^^^^^^^^
AttributeError: 'YOLODataset' object has no attribute 'use_obb'

**Comment by glenn-jocher** [comment]
@Enryuwashere hey there! It looks like you've done everything correctly in setting up your `data.yaml` and updating Ultralytics. The error you're encountering seems to stem from within the core code, specifically related to handling object bounding boxes (OBB).

Given the nature of the error, it doesn't seem to be directly related to your dataset. Instead, it might be an issue with the latest version of Ultralytics YOLO you're using, where an expected attribute (`use_obb`) is missing in the `YOLODataset` class. 

For immediate resolution, you could try reverting to an earlier version of Ultralytics YOLO where this issue might not be present. Alternatively, if you are comfortable with it, you could check the corresponding classes in the codebase (`ultralytics\data\dataset.py`) for the missing `use_obb` attribute and temporarily fix it until an official update is released.

If rolling back the version or tweaking the codebase isn't an optimal solution for you, I'd recommend reaching out on the Ultralytics GitHub issues page with this detailed traceback. The developers are incredibly responsive and could offer a more concrete solution or patch in upcoming updates.

Let's hope this helps get you back on track! 🛤️ Keep experimenting with your models, and don't hesitate to share any more issues or successes you encounter. The journey in AI is filled with learning at every step.

**Comment by Enryuwashere** [comment]
I tried to redownload the ultralytics folder and it works. Thank you for your helps!

**Comment by glenn-jocher** [comment]
That's fantastic news! 🎉 I'm glad to hear that redownloading the Ultralytics folder resolved the issue for you. If you have any more questions or run into other challenges, feel free to reach out. Happy coding! 🚀
