### ISSUE TITLE
yaml.scanner.ScannerError: while scanning a simple key   in "<unicode string>"

### ISSUE THREAD

**Issue by eeasel** [ultralytics/ultralytics#10126]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi,I used windows+anaconda+pycharm to run yolov8 model.And this is how the problem show:
Traceback (most recent call last):
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\runpy.py", line 194, in _run_module_as_main                         
    return _run_code(code, main_globals, None,                                                                        
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\runpy.py", line 87, in _run_code                                    
    exec(code, run_globals)                                                                                           
  File "D:\ProgramFiles\anaconda\envs\new_env\Scripts\yolo.exe\__main__.py", line 4, in <module>                      
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>    
    from .base import BaseDataset
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\ultralytics\data\base.py", line 17, in <module>       
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\ultralytics\utils\__init__.py", line 1071, in <module>
    SETTINGS = SettingsManager()  # initialize settings
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\ultralytics\utils\__init__.py", line 1003, in __init__
    self.load()
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\ultralytics\utils\__init__.py", line 1028, in load    
    super().update(yaml_load(self.file))
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\ultralytics\utils\__init__.py", line 379, in yaml_load
    data = yaml.safe_load(s) or {}  # always return a dict (yaml.safe_load() may return None for empty files)
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "D:\ProgramFiles\anaconda\envs\new_env\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 17, column 1:
    e
    ^
could not find expected ':'
  in "<unicode string>", line 18, column 1:

    ^

My virtualenvironment named new_env and is located in D:\ProgramFiles\anaconda\envs\new_env.My python interpretor is located in D:\ProgramFiles\anaconda\envs\new_env\python.exe and the version is 3.8.The anaconda's version is 2023.3.
After this I downloaded ultralytics by "pip install ultralytics".When I use "yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'" or try to train my own datasets,it all told me the same error.I also tried to use python script but it is no use.

### Additional

Packages&version

Jinja2 | 3.1.3 | 3.1.3
MarkupSafe | 2.1.5 | 2.1.5
PyYAML | 6.0.1 | 6.0.1
certifi | 2024.2.2 | 2024.2.2
charset-normalizer | 3.3.2 | 3.3.2
colorama | 0.4.6 | 0.4.6
contourpy | 1.1.1 | 1.2.1
cycler | 0.12.1 | 0.12.1
filelock | 3.13.4 | 3.13.4
fonttools | 4.51.0 | 4.51.0
fsspec | 2024.3.1 | 2024.3.1
idna | 3.7 | 3.7
importlib-resources | 6.4.0 | 6.4.0
kiwisolver | 1.4.5 | 1.4.5
matplotlib | 3.7.5 | 3.8.4
mpmath | 1.3.0 | 1.3.0
networkx | 3.1 | 3.3
numpy | 1.24.4 | 1.26.4
opencv-python | 4.9.0.80 | 4.9.0.80
packaging | 24.0 | 24.0
pandas | 2.0.3 | 2.2.2
pillow | 10.3.0 | 10.3.0
pip | 23.3.1 | 24.0
psutil | 5.9.8 | 5.9.8
py-cpuinfo | 9.0.0 | 9.0.0
pyparsing | 3.1.2 | 3.1.2
python-dateutil | 2.9.0.post0 | 2.9.0.post0
pytz | 2024.1 | 2024.1
requests | 2.31.0 | 2.31.0
scipy | 1.10.1 | 1.13.0
seaborn | 0.13.2 | 0.13.2
setuptools | 68.2.2 | 69.5.1
six | 1.16.0 | 1.16.0
sympy | 1.12 | 1.12
thop | 0.1.1.post2209072238 | 0.1.1.post2209072238
torch | 2.2.2 | 2.2.2
torchvision | 0.17.2 | 0.17.2
tqdm | 4.66.2 | 4.66.2
typing-extensions | 4.11.0 | 4.11.0
tzdata | 2024.1 | 2024.1
ultralytics | 8.2.0 | 8.2.0
urllib3 | 2.2.1 | 2.2.1
wheel | 0.41.2 | 0.43.0
zipp | 3.18.1 | 3.18.1

**Comment by glenn-jocher** [comment]
@eeasel hey there! It seems like you've encountered a YAML parsing error, which usually signifies an issue with your YAML configuration file's syntax. The error suggests a missing ':' on line 17 or an incorrectly formatted key-value pair.

Could you please double-check the YAML files you're using, especially around the lines mentioned in the error? Make sure each key-value pair is correctly formatted, like so:
```yaml
key: value
```
Errors in indentation or missing colons can often lead to such issues. If you've recently edited the file, a small syntax mistake could be the culprit. Correcting the syntax should resolve the error. 

If you're still stuck, could you share a snippet of your YAML file around the lines mentioned in the error message? That way, we might be able to help pinpoint the issue more accurately. 🛠️ 

And thanks for reaching out!

**Comment by Dazu0106** [comment]
@eeasel Hello! The error is caused by unintentional unicode creation in /.config/ultralytics/setting.yaml. The error seems to be caused by ctrl+c during training. I don't know the exact cause of the error, but it has occurred on other occasions...
