### ISSUE TITLE
Can't do inference on a batch on exported model

### ISSUE THREAD

**Issue by ngbusca** [ultralytics/ultralytics#10194]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

InvalidArgumentError                      Traceback (most recent call last)
/tmp/ipykernel_65753/688179043.py in <module>
      3 img = np.random.uniform(0, 1, size=(2,640,640,3)).astype(np.float32)
      4 
----> 5 p = model(img)
      6 print(p[0].shape, p[1].shape)

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py in __call__(self, *args, **kwargs)
   1472       TypeError: If the arguments do not match the function's signature.
   1473     """
-> 1474     return self._call_impl(args, kwargs)
   1475 
   1476   def _call_impl(self, args, kwargs, cancellation_manager=None):

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1481       if self._function_spec is not None:
   1482         try:
-> 1483           return self._call_with_structured_signature(args, kwargs,
   1484                                                       cancellation_manager)
   1485         except TypeError as structured_err:

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py in _call_with_structured_signature(self, args, kwargs, cancellation_manager)
   1562     self._structured_signature_check_unexpected_args(args, kwargs)
   1563     self._structured_signature_check_arg_types(args, kwargs)
-> 1564     return self._call_flat(
   1565         filtered_flat_args,
   1566         captured_inputs=self.captured_inputs,

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py in _call_flat(self, args, captured_inputs, cancellation_manager)
    136     else:  # cross-replica context
    137       captured_inputs = list(map(get_unused_handle, captured_inputs))
--> 138     return super(_WrapperFunction, self)._call_flat(args, captured_inputs,
    139                                                     cancellation_manager)
    140 

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1743         and executing_eagerly):
   1744       # No tape is watching; skip to running the function.
-> 1745       return self._build_call_outputs(self._inference_function.call(
   1746           ctx, args, cancellation_manager=cancellation_manager))
   1747     forward_backward = self._select_forward_and_backward_functions(

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py in call(self, ctx, args, cancellation_manager)
    376       with _InterpolateFunctionError(self):
    377         if cancellation_manager is None:
--> 378           outputs = execute.execute(
    379               str(self.signature.name),
    380               num_outputs=self._num_outputs,

~/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50   try:
     51     ctx.ensure_initialized()
---> 52     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                         inputs, attrs, num_outputs)
     54   except core._NotOkStatusException as e:

InvalidArgumentError: {{function_node __inference_<lambda>_33594}} Conv2DCustomBackpropInput: input and out_backprop must have the same batch size. Input batch: 1, outbackprop batch: 2, batch_dim: 0
	 [[{{node model_3/tf.nn.conv2d_transpose/conv2d_transpose}}]] [Op:__inference_<lambda>_33594]

### Environment

Ultralytics YOLOv8.2.2 🚀 Python-3.9.7 torch-2.2.2+cu121 CPU (Intel Xeon E5-2690 v3 2.60GHz)
Setup complete ✅ (48 CPUs, 125.8 GB RAM, 114.2/437.9 GB disk)

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO('yolov8n-seg.yaml')  # build a new model from YAML
model = YOLO('yolov8n-seg.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n-seg.yaml').load('yolov8n.pt')  # build from YAML and transfer weights

model.export(format="saved_model", keras=True)

import tensorflow as tf
import numpy as np

model = tf.keras.models.load_model("yolov8n-seg_saved_model/")

img = np.random.uniform(0, 1, size=(1,640,640,3)).astype(np.float32)

p = model(img)
print(p[0].shape, p[1].shape)
## prints: (1, 116, 8400) (1, 160, 160, 32)

img = np.random.uniform(0, 1, size=(2,640,640,3)).astype(np.float32) ## gives the error above
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! 😀 It seems like the issue is related to the batch size mismatch between your input and the model's expectation. When exporting your YOLOv8 model to TensorFlow SavedModel format and using it with TensorFlow/Keras, ensure that the model is compatible with batched inputs. 

As a quick workaround, you might want to try processing your images one at a time in a loop or adjusting the model to accept a batch size of 2. For batch inference, you'll want to ensure that the exported model is set up correctly to handle multiple images at once.

Here’s a simple loop example for individual predictions:

```python
import numpy as np
import tensorflow as tf

# Assuming model is already loaded

imgs = np.random.uniform(0, 1, size=(2, 640, 640, 3)).astype(np.float32)
results = []

for img in imgs:
    img = np.expand_dims(img, axis=0)  # Add batch dimension
    pred = model(img)
    results.append(pred)

# Now results contains the predictions for each image
```

This way, you're making sure each image is processed separately, which might help avoid the batch size mismatch issue. Let us know how it goes or if you need further assistance! 🚀

**Comment by ngbusca** [comment]
Hi @glenn-jocher, thanks for the quick response. I can run images one at a time, but I would need to be able to run in batches for performance reasons.

Is the exported model supposed to run with a batch size bigger than 1 or is it a feature that it doesn't?

**Comment by glenn-jocher** [comment]
@ngbusca hello there! 😊

Absolutely, the exported YOLOv8 model should theoretically support batched inputs for enhanced performance. If you're encountering issues with a specific batch size, it might be due to the export settings or how the model was initialized before exporting. 

To ensure your model supports batching, you might want to double-check the export process and the model configuration used during this step. Here's a basic outline for exporting a model that should support batching:

```python
from ultralytics import YOLO

# Load and export your model
model = YOLO('path/to/your/model.pt')
model.export(format="saved_model", keras=True, dynamic=True)
```

The key here is ensuring that your export command allows for dynamic input sizes, which can be crucial for batch processing. Do give this a try, and if the problem persists, we'd be more than happy to dive deeper into this issue together! 

Thanks for reaching out, and looking forward to getting this resolved for you! 🚀

**Comment by ngbusca** [comment]
Unfortunately when I try to export the model with `dynamic = True` I encounter another error:

Code:
```
from ultralytics import YOLO

model = YOLO('yolov8n-seg.yaml')  # build a new model from YAML
model = YOLO('yolov8n-seg.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n-seg.yaml').load('yolov8n.pt')  # build from YAML and transfer weights

model.export(format="saved_model", keras=True, dynamic=True)
```

Output:
```
Ultralytics YOLOv8.2.2 🚀 Python-3.9.7 torch-2.2.2+cu121 CPU (Intel Xeon E5-2690 v3 2.60GHz)
YOLOv8n-seg summary (fused): 195 layers, 3404320 parameters, 0 gradients, 12.6 GFLOPs

PyTorch: starting from 'yolov8n-seg.yaml' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 116, 8400), (1, 32, 160, 160)) (0.0 MB)

TensorFlow SavedModel: starting export with tensorflow 2.11.0...

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 1.8s, saved as 'yolov8n-seg.onnx' (13.1 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/ops/MaxPool.py", line 160, in make_node
    tf_pads = calc_tf_pooling_pads(
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 4307, in calc_tf_pooling_pads
    same_output_shape = math.floor((i - 1) / s) + 1
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

ERROR: input_onnx_file_path: yolov8n-seg.onnx
ERROR: onnx_op_name: /model.9/m/MaxPool
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
Traceback (most recent call last):
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/ops/MaxPool.py", line 160, in make_node
    tf_pads = calc_tf_pooling_pads(
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 4307, in calc_tf_pooling_pads
    same_output_shape = math.floor((i - 1) / s) + 1
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_388822/3002537938.py", line 1, in <module>
    model.export(format="saved_model", keras=True, dynamic=True)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/ultralytics/engine/model.py", line 601, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 296, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 135, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 808, in export_saved_model
    onnx2tf.convert(
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/onnx2tf.py", line 998, in convert
    op.make_node(
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 354, in print_wrapper_func
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/home/nicolas/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/nicolas/anaconda3/lib/python3.9/inspect.py", line 1541, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py in print_wrapper_func(*args, **kwargs)
    287         try:
--> 288             result = func(*args, **kwargs)
    289 

~/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py in inverted_operation_enable_disable_wrapper_func(*args, **kwargs)
    360     def inverted_operation_enable_disable_wrapper_func(*args, **kwargs):
--> 361         result = func(*args, **kwargs)
    362         """

~/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py in get_replacement_parameter_wrapper_func(*args, **kwargs)
     51             ]
---> 52         func(*args, **kwargs)
     53     return get_replacement_parameter_wrapper_func

~/anaconda3/lib/python3.9/site-packages/onnx2tf/ops/MaxPool.py in make_node(graph_node, tf_layers_dict, **kwargs)
    159 
--> 160     tf_pads = calc_tf_pooling_pads(
    161         input_shape=input_tensor_shape,

~/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py in calc_tf_pooling_pads(input_shape, kernel, strides)
   4306     for i, k, s in zip(input_shape[1:-1], kernel, strides):
-> 4307         same_output_shape = math.floor((i - 1) / s) + 1
   4308         axis_pads = np.max((same_output_shape - 1) * s + k - i, 0)

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

/tmp/ipykernel_388822/3002537938.py in <module>
----> 1 model.export(format="saved_model", keras=True, dynamic=True)

~/anaconda3/lib/python3.9/site-packages/ultralytics/engine/model.py in export(self, **kwargs)
    600         args = {**self.overrides, **custom, **kwargs, "mode": "export"}  # highest priority args on the right
--> 601         return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
    602 

~/anaconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py in decorate_context(*args, **kwargs)
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 

~/anaconda3/lib/python3.9/site-packages/ultralytics/engine/exporter.py in __call__(self, model)
    295             self.args.int8 |= edgetpu
--> 296             f[5], keras_model = self.export_saved_model()
    297             if pb or tfjs:  # pb prerequisite to tfjs

~/anaconda3/lib/python3.9/site-packages/ultralytics/engine/exporter.py in outer_func(*args, **kwargs)
    134             with Profile() as dt:
--> 135                 f, model = inner_func(*args, **kwargs)
    136             LOGGER.info(f"{prefix} export success ✅ {dt.t:.1f}s, saved as '{f}' ({file_size(f):.1f} MB)")

~/anaconda3/lib/python3.9/site-packages/ultralytics/engine/exporter.py in export_saved_model(self, prefix)
    807         LOGGER.info(f"{prefix} starting TFLite export with onnx2tf {onnx2tf.__version__}...")
--> 808         onnx2tf.convert(
    809             input_onnx_file_path=f_onnx,

~/anaconda3/lib/python3.9/site-packages/onnx2tf/onnx2tf.py in convert(input_onnx_file_path, onnx_graph, output_folder_path, output_signaturedefs, output_h5, output_keras_v3, output_tfv1_pb, output_weights, copy_onnx_input_output_names_to_tflite, output_integer_quantized_tflite, quant_type, custom_input_op_name_np_data_path, input_output_quant_dtype, not_use_onnxsim, not_use_opname_auto_generate, batch_size, overwrite_input_shape, no_large_tensor, output_nms_with_dynamic_tensor, keep_ncw_or_nchw_or_ncdhw_input_names, keep_nwc_or_nhwc_or_ndhwc_input_names, keep_shape_absolutely_input_names, output_names_to_interrupt_model_conversion, disable_group_convolution, enable_batchmatmul_unfold, enable_rnn_unroll, disable_suppression_flextranspose, disable_strict_mode, number_of_dimensions_after_flextranspose_compression, disable_suppression_flexstridedslice, number_of_dimensions_after_flexstridedslice_compression, optimization_for_gpu_delegate, replace_argmax_to_reducemax_and_indicies_is_int64, replace_argmax_to_reducemax_and_indicies_is_float32, replace_argmax_to_fused_argmax_and_indicies_is_int64, replace_argmax_to_fused_argmax_and_indicies_is_float32, fused_argmax_scale_ratio, replace_to_pseudo_operators, param_replacement_file, check_gpu_delegate_compatibility, check_onnx_tf_outputs_elementwise_close, check_onnx_tf_outputs_elementwise_close_full, check_onnx_tf_outputs_sample_data_normalization, check_onnx_tf_outputs_elementwise_close_rtol, check_onnx_tf_outputs_elementwise_close_atol, mvn_epsilon, disable_model_save, non_verbose, verbosity)
    997 
--> 998             op.make_node(
    999                 graph_node=graph_node,

~/anaconda3/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py in print_wrapper_func(*args, **kwargs)
    353             )
--> 354             sys.exit(1)
    355     return print_wrapper_func

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2055                     stb = ['An exception has occurred, use %tb to see '
   2056                            'the full traceback.\n']
-> 2057                     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2058                                                                      value))
   2059                 else:

~/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py in get_exception_only(self, etype, value)
    752         value : exception value
    753         """
--> 754         return ListTB.structured_traceback(self, etype, value)
    755 
    756     def show_exception_only(self, etype, evalue):

~/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    627             chained_exceptions_tb_offset = 0
    628             out_list = (
--> 629                 self.structured_traceback(
    630                     etype, evalue, (etb, chained_exc_ids),
    631                     chained_exceptions_tb_offset, context)

~/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1365         else:
   1366             self.tb = tb
-> 1367         return FormattedTB.structured_traceback(
   1368             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1369 

~/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1265         if mode in self.verbose_modes:
   1266             # Verbose modes need a full traceback
-> 1267             return VerboseTB.structured_traceback(
   1268                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1269             )

~/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1122         """Return a nice text document describing the traceback."""
   1123 
-> 1124         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1125                                                                tb_offset)
   1126 

~/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1080 
   1081 
-> 1082         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1083 
   1084         frames = self.format_records(records, last_unique, recursion_repeat)

~/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

**Comment by glenn-jocher** [comment]
Hey there! 😊 Thanks for providing the detailed error log. It looks like you encountered an issue with dynamic shapes when exporting the model to TensorFlow SavedModel format with dynamic input sizes.

The error related to `TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'` typically occurs when the model or the conversion process encounters an input size that it's unable to handle dynamically, possibly due to limitations in TensorFlow's handling of certain operations with dynamic shapes during the conversion.

A workaround might involve specifying fixed input dimensions instead of using `dynamic=True`, thereby avoiding this issue. However, I understand that having dynamic input sizes is crucial for your use case.

Let's take a closer look at your error, especially this part: `ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement`. It suggests that there might be specific operators in the ONNX model that require attention or alternative handling. 

One potential option is to dissect the model and see if you can identify any operations that do not support dynamic axes well and see if a static shape can be provided for those parts specifically, or if a model modification prior to export can circumvent this limitation.

Additionally, the final block of your output suggests potential issues with the `onnx2tf` conversion process, which might not be directly related to YOLOv8 but to the conversion library's handling of specific ONNX operations.

Since dealing with complex models can sometimes surface unique challenges, it could be beneficial to reach out to the `onnx2tf` community or relevant repositories for insights specific to these errors, especially for advice on handling dynamic dimensions more gracefully or identifying troublesome operations.

Apologies for the inconvenience here; dynamic batch sizes should be feasible, but implementation details can get quite complex depending on the model architecture and operations used. Continuing to seek community advice and investigating the model's specific operations might uncover more tailored solutions.

**Comment by ngbusca** [comment]
The onnx2tf community blames the architecture complexity for this error (https://github.com/PINTO0309/onnx2tf#parameter-replacement)... the yolo community blames the onnx2tf external package. 
It feels like a catch 22.
