### ISSUE TITLE
Not able to load cuda modules

### ISSUE THREAD

**Issue by EashanVytla** [ultralytics/ultralytics#10203]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I am having this issue. Does anyone have any ideas on how I can solve it?

The following have been reloaded with a version change:
  1) cuda/12.3.0 => cuda/11.8.0

Currently Loaded Modules:
  1) xalt/latest               4) mvapich2/2.3.3            7) cuda/11.8.0
  2) gcc-compatibility/8.4.0   5) modules/sp2020
  3) intel/19.0.5              6) miniconda3/23.3.1-py310

 

Python executable: /usr/local/miniconda3/23.3.1-py310/bin/python
2.2.2+cu118
Ultralytics YOLOv8.2.2 🚀 Python-3.10.10 torch-2.2.2+cu118 CUDA:0 (Tesla P100-PCIE-16GB, 16276MiB)
[34m[1mengine/trainer: [0mtask=detect, mode=train, model=yolov8m.pt, data=data.yaml, epochs=50, time=None, patience=5, batch=10, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=28, project=None, name=CharModel119, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.00269, lrf=0.01288, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/CharModel119
Overriding model.yaml nc=80 with nc=36

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   3796540  ultralytics.nn.modules.head.Detect           [36, [192, 384, 576]]         
Model summary: 295 layers, 25877164 parameters, 25877148 gradients, 79.2 GFLOPs

Transferred 469/475 items from pretrained weights
[34m[1mTensorBoard: [0mStart with 'tensorboard --logdir runs/detect/CharModel119', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
[34m[1mAMP: [0mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
[34m[1mAMP: [0mchecks passed ✅

[34m[1mtrain: [0mScanning /users/PAS2152/eashanvytla1/BuckeyeVerticalObjTraining/smallCharData/train/labels.cache... 100 images, 0 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]
[34m[1mtrain: [0mScanning /users/PAS2152/eashanvytla1/BuckeyeVerticalObjTraining/smallCharData/train/labels.cache... 100 images, 0 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]

[34m[1mval: [0mScanning /users/PAS2152/eashanvytla1/BuckeyeVerticalObjTraining/smallCharData/valid/labels.cache... 18 images, 0 backgrounds, 0 corrupt: 100%|██████████| 18/18 [00:00<?, ?it/s]
[34m[1mval: [0mScanning /users/PAS2152/eashanvytla1/BuckeyeVerticalObjTraining/smallCharData/valid/labels.cache... 18 images, 0 backgrounds, 0 corrupt: 100%|██████████| 18/18 [00:00<?, ?it/s]
Plotting labels to runs/detect/CharModel119/labels.jpg... 
[34m[1moptimizer:[0m 'optimizer=auto' found, ignoring 'lr0=0.00269' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
[34m[1moptimizer:[0m AdamW(lr=0.00025, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.00046875), 83 bias(decay=0.0)
[34m[1mTensorBoard: [0mmodel graph visualization added ✅
Image sizes 640 train, 640 val
Using 28 dataloader workers
Logging results to [1mruns/detect/CharModel119[0m
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

  0%|          | 0/10 [00:00<?, ?it/s]Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference
Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda/11.8.0/lib64/libcudnn_cnn_train.so.8: symbol _ZN10cask_cudnn2kr8isAmpereEPNS0_5spa_tERKi, version libcudnn_cnn_infer.so.8 not defined in file libcudnn_cnn_infer.so.8 with link time reference

  0%|          | 0/10 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/users/PAS2152/eashanvytla1/BuckeyeVerticalObjTraining/smallCharData/train.py", line 21, in <module>
    results = model.train(data = "data.yaml",
  File "/users/PAS2152/eashanvytla1/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 673, in train
    self.trainer.train()
  File "/users/PAS2152/eashanvytla1/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/users/PAS2152/eashanvytla1/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 379, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/users/PAS2152/eashanvytla1/.local/lib/python3.10/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/users/PAS2152/eashanvytla1/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: GET was unable to find an engine to execute this computation

### Environment

I am trying to train a model at the Ohio Supercomputer Center. I loaded Cuda 11.8 which was installed by OSC. I installed Pytorch for Cuda 11.8, then I installed Ultralytics. The node that I am running on is the OSC Owens node. This is a NVIDA P100 16 GB. I do not have sudo access so I can't install anything globally. I can only install packages locally using pip.

### Minimal Reproducible Example

Batch Script (job.sh):
'''
#!/bin/bash
#BATCH --job-name=CharDetect
#SBATCH --nodes=1 --ntasks-per-node=28 --gpus-per-node=1 --gpu_cmode=shared
#SBATCH --time=10:00:00
#SBATCH --account=PAS2152
#SBATCH --mail-type=ALL

cd $SLURM_SUBMIT_DIR

module load miniconda3/23.3.1-py310  cuda/11.8.0

module list

source activate pytorch2

echo "Python executable: $(which python)"

python3 train.py
'''

Python Script (train.py):
'''
from IPython.display import display, Image
import torch
from ultralytics import YOLO
import os

print(torch.__version__)

#load the model
model = YOLO("yolov8m.pt")#loads nano detection YOLO version 8 neural network

n_epochs = 50
bs = 10
gpu_id = 0
imgSize = 640
waitNum = 5
workerNum = os.cpu_count()
OptimizerChoice = 'auto'
validate = True

#Train
results = model.train(data = "data.yaml",
                      imgsz = imgSize,
                      pretrained = True,
                      name = "CharModel1",
                      cos_lr=True,
                      #lr0=0.00269,
                      #lrf=0.00288,
                      lr0=0.00269,
                      lrf=0.01288,
                      epochs = n_epochs,
                      batch = bs,
                      device = gpu_id,
                      patience = waitNum,
                      val = validate,
                      workers = workerNum,)
#config file draws in the path and training data along with the validation info
#epochs in number of training phases so more the better  Estimation = 100-300
'''

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there! 😊 It looks like you're encountering a CUDA library compatibility issue when trying to train with YOLOv8 on OSC Owens node. The error regarding `libcudnn_cnn_train.so.8` indicates a possible mismatch between the versions of CUDA and cuDNN.

Given the constraints at OSC and the fact that you've successfully run other PyTorch models, here's a suggestion to potentially solve the issue:

1. Ensure that the version of PyTorch you've installed is specifically compiled for CUDA 11.8. You can verify or install the correct version using Pip in your environment:
   ```bash
   pip install torch==2.2.2+cu118 -f https://download.pytorch.org/whl/torch_stable.html
   ```

2. It's also a good idea to check the cuDNN version installed on the system. Since you don't have sudo access and cannot update cuDNN directly if necessary, reaching out to the OSC support team for help on this might be necessary.

3. Another workaround involves checking if there are other CUDA versions available on the system that match the requirements of the cuDNN version you're using. Sometimes, loading an older or a different CUDA module (if available) can resolve the version mismatch. Use the module command to explore available versions:
   ```bash
   module avail cuda
   ```

4. Since this issue could arise from a specific environmental setup at OSC and considering you’re using PyTorch successfully on these nodes generally, verifying the installed cuDNN version and its compatibility with both CUDA and PyTorch might be crucial steps.

Please let us know if adjusting the CUDA version or confirming the cuDNN compatibility helps or if you need further assistance. 🚀
