### ISSUE TITLE
Getting error adding more Albumentation transformations for detection task

### ISSUE THREAD

**Issue by majnas** [ultralytics/ultralytics#1020]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I have dataset with single class. I need to add more Albumentation transformation to the pipeline as follows
```python
class Albumentations:
    # YOLOv8 Albumentations class (optional, only used if package is installed)
    def __init__(self, p=1.0):
        self.p = p
        self.transform = None
        prefix = colorstr("albumentations: ")
        try:
            import albumentations as A

            check_version(A.__version__, "1.0.3", hard=True)  # version requirement

            T = [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0),
                
                # More albumentation transform
                A.ElasticTransform(alpha=120, sigma=120 * 0.05, alpha_affine=120 * 0.03, p=1),
                ]  # transforms

```

This is my script to run the model
```python
# Ultralytics YOLO 🚀, GPL-3.0 license

from pathlib import Path

from ultralytics.yolo.cfg import get_cfg
from ultralytics.yolo.utils import DEFAULT_CFG, ROOT, SETTINGS
from ultralytics.yolo.v8 import classify, detect, segment

CFG = get_cfg(DEFAULT_CFG)
MODEL = Path(SETTINGS['weights_dir']) / 'yolov8n'
SOURCE = ROOT / "assets"


overrides = {"data": "23MixedACPOT+DCC2022+SU+AV+T2W-POT.yaml", 
             "model": "yolov8x.pt", 
             "imgsz": 640, 
             "epochs": 100, 
             "save": False,
             "workers": 32,
             "device": [0,1],
             "batch":26,
             "project":"../../runs/Y8",
             "name":"POT_23MixedACPOT+DCC2022+SU+AV+T2W-POT_Y8X_i1280x1280_b26",
             "degrees":15, 
             "shear":15,
             }

CFG.data = overrides["data"]

# Trainer
trainer = detect.DetectionTrainer(overrides=overrides)
trainer.train()

```

```shell
(av) s2@s2:~/avgit/defect_detection/code/ultralytics$ python y8.py 
Ultralytics YOLOv8.0.39 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (NVIDIA A40, 45434MiB)
                                                            CUDA:1 (NVIDIA A40, 45434MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8x.pt, data=23MixedACPOT+DCC2022+SU+AV+T2W-POT.yaml, epochs=100, patience=50, batch=26, imgsz=640, save=False, save_period=-1, cache=False, device=[0, 1], workers=32, project=../../runs/Y8, name=POT_23MixedACPOT+DCC2022+SU+AV+T2W-POT_Y8X_i1280x1280_b26, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, min_memory=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=15, translate=0.1, scale=0.5, shear=15, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort, tracker_cfg=None, save_dir=../../runs/Y8/POT_23MixedACPOT+DCC2022+SU+AV+T2W-POT_Y8X_i1280x1280_b2632
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
DDP settings: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
Overriding model.yaml nc=80 with nc=1
optimizer: SGD(lr=0.01) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.00040625000000000004), 103 bias
train: Scanning /home/s2/avgit/defect_detection/dataset/23MixedACPOT+DCC2022+SU+AV+T2W-POT/labels/train.cache... 2045 im
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8)), ElasticTransform(p=1, alpha=120, sigma=6.0, alpha_affine=3.5999999999999996, interpolation=1, border_mode=4, value=None, mask_value=None, approximate=False, same_dxdy=False)
val: Scanning /home/s2/avgit/defect_detection/dataset/23MixedACPOT+DCC2022+SU+AV+T2W-POT/labels/test.cache... 2045 image
Image sizes 640 train, 640 val
Using 26 dataloader workers
Logging results to ../../runs/Y8/POT_23MixedACPOT+DCC2022+SU+AV+T2W-POT_Y8X_i1280x1280_b2632
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/79 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "/home/s2/.config/Ultralytics/DDP/_temp_n1bql01j139759094292544.py", line 6, in <module>
    trainer.train()
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/yolo/engine/trainer.py", line 187, in train
    self._do_train(RANK, world_size)
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/yolo/engine/trainer.py", line 307, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/yolo/v8/detect/train.py", line 77, in criterion
    return self.compute_loss(preds, batch)
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/yolo/v8/detect/train.py", line 181, in __call__
    targets = torch.cat((batch["batch_idx"].view(-1, 1), batch["cls"].view(-1, 1), batch["bboxes"]), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 29 but got size 28 for tensor number 1 in the list.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 10802 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10801) of binary: /home/s2/.virtualenvs/av/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/s2/.config/Ultralytics/DDP/_temp_n1bql01j139759094292544.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-17_16:10:31
  host      : s2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10801)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Command '['/home/s2/.virtualenvs/av/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '56533', '/home/s2/.config/Ultralytics/DDP/_temp_n1bql01j139759094292544.py', 'task=detect', 'mode=train', 'model=yolov8x.pt', 'data=23MixedACPOT+DCC2022+SU+AV+T2W-POT.yaml', 'epochs=100', 'patience=50', 'batch=26', 'imgsz=640', 'save=False', 'save_period=-1', 'cache=False', 'device=[0, 1]', 'workers=32', 'project=../../runs/Y8', 'name=POT_23MixedACPOT+DCC2022+SU+AV+T2W-POT_Y8X_i1280x1280_b26', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'min_memory=False', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'hide_labels=False', 'hide_conf=False', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'fl_gamma=0.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=15', 'translate=0.1', 'scale=0.5', 'shear=15', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort', 'tracker_cfg=None']' returned non-zero exit status 1.
Ultralytics YOLOv8.0.39 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (NVIDIA A40, 45434MiB)
Traceback (most recent call last):
  File "y8.py", line 37, in <module>
    val(model=trainer.best)  # validate best.pt
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/yolo/engine/validator.py", line 98, in __call__
    model = AutoBackend(model, device=self.device, dnn=self.args.dnn, data=self.args.data, fp16=self.args.half)
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/nn/autobackend.py", line 86, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/nn/tasks.py", line 355, in attempt_load_weights
    ckpt = torch_safe_load(w)  # load ckpt
  File "/home/s2/avgit/defect_detection/code/ultralytics/ultralytics/nn/tasks.py", line 338, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/s2/.virtualenvs/av/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../../runs/Y8/POT_23MixedACPOT+DCC2022+SU+AV+T2W-POT_Y8X_i1280x1280_b2632/weights/best.pt'
```

### Environment

Ubuntu 22.04

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by chenghan1995** [comment]
I meet it now. How to solve it?

**Comment by Laughing-q** [comment]
@chenghan1995 thanks for the reporting! I believe this PR #1009 could solve the issue. :)  Then the detection training with detection labels should work properly. But still we haven't supported other augmentations from albumentation for segmentation yet.

**Comment by majnas** [comment]
> @chenghan1995 thanks for the reporting! I've reproduced and tested which I believe this PR #1009 could solve the issue. :)  Then the detection training with detection labels should work properly. But still we haven't supported other augmentations from albumentation for segmentation yet.

Actually I have tested the #1009, It doesn't works for detection in my code 😕

**Comment by Laughing-q** [comment]
@majnas strange...I tested with the same script you used except `model=yolov8n` and `data=coco128.yaml`.
before I manually added the line from #1009, I encountered the same error as yours:
![pic-full-230217-1738-41](https://user-images.githubusercontent.com/61612323/219608490-67f77021-59e8-49d4-bc16-1bb89fdf239d.png)
after:
![pic-full-230217-1737-55](https://user-images.githubusercontent.com/61612323/219608573-1ae559b5-323f-48cb-92ef-5cb4685e25a0.png)

**Comment by glenn-jocher** [comment]
@Laughing-q @majnas I'll merge #1009 and deploy 8.0.40 today including this fix.

**Comment by majnas** [comment]
Thanks for your time :+1: 
Have you added 
> ```python
>                 A.ElasticTransform(alpha=120, sigma=120 * 0.05, alpha_affine=120 * 0.03, p=1),
> ```

transformation? :confused:

**Comment by Laughing-q** [comment]
@majnas sure!😂 that's how I reproduced the error you encountered.(check the first screenshot in my above comment)
