### ISSUE TITLE
NoneType Error

### ISSUE THREAD

**Issue by meatius2456** [ultralytics/ultralytics#10219]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was using a trained model to do inference on an mp4 video i downloaded, but after the video played for a few seconds, it stopped and this popped up

xyxy: -======= [tensor(1259.), tensor(421.), tensor(1296.), tensor(447.)]
test: (1259, 421, 1296, 447)
[2024/04/22 17:41:29] ppocr WARNING: Since the angle classifier is not initialized, it will not be used during the forward process
[2024/04/22 17:41:29] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.08449554443359375
[2024/04/22 17:41:29] ppocr DEBUG: rec_res num  : 1, elapsed : 0.09851455688476562
Traceback (most recent call last):
  File "C:\Users\Ethan\Muhammad\yolov5\detect_bus(2).py", line 451, in <module>
    main(opt)
  File "C:\Users\Ethan\Muhammad\yolov5\detect_bus(2).py", line 446, in main
    run(**vars(opt))
  File "C:\Users\Ethan\anaconda3\envs\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Ethan\Muhammad\yolov5\detect_bus(2).py", line 271, in run
    for z in range(len(lis)):
TypeError: object of type 'NoneType' has no len()

### Additional
 
i tried running it a few more times but it always stops at the same timing.
it also works on my 2 of my friends pc but not my laptop.
Does anyone know how to resolve this issue?

**Comment by glenn-jocher** [comment]
It seems like the issue could be related to the variable `lis` being `None`, which can't be used with `len()`. This can happen if the expected data isn't loaded properly, leading to `lis` not being initialized as expected. Here's a quick fix you could try:

- Ensure that whatever `lis` is supposed to hold, is being loaded or assigned correctly.
- Add a check before the loop to see if `lis` is `None` and handle the case accordingly:
    ```python
    if lis is not None:
        for z in range(len(lis)):
            # Your code here
    else:
        print("Warning: 'lis' is None!")
    ```

If `lis` is expected to hold data from the video or another source, double-check the path and ensure that the data is accessible on your laptop in the same way it is on your friends' PCs. Also, ensure your environment setup matches that of your friends' where the code runs successfully. Hope this helps! 😊
