### ISSUE TITLE
cv2.error: could not find a writer for the specified extension in function 'imwrite_'

### ISSUE THREAD

**Issue by MohMak** [ultralytics/ultralytics#10242]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Traceback (most recent call last):
  File "/media/user/Storage/server.py", line 63, in <module>
    result = model(source=image, show=True, conf=0.4, save=True)
  File "/home/user/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/user/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/ultralytics/engine/model.py", line 452, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/user/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/user/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/user/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 268, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/home/user/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 348, in write_results
    self.save_predicted_images(str(self.save_dir / p.name), frame)
  File "/home/user/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 378, in save_predicted_images
    cv2.imwrite(save_path, im)
cv2.error: OpenCV(4.9.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:696: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'

### Minimal Reproducible Example

data = recvall(conn, msglen)

nparr = np.frombuffer(data, np.uint8)
image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
cv2.imshow('Received Image', image)
cv2.waitKey(0) 
cv2.destroyAllWindows()

model = YOLO("best.pt")
result = model(source=image, show=True, conf=0.4, save=True)

Also, using: image = Image.open(io.BytesIO(data), formats=None) produces the same issue.

### Additional

I trained YOLO on a custom data set and trying to use my trained model on images received over a TCP socket, the image data is received correctly and I can display it using cv2.imshow with no issues whatsoever. However, when I pass the image in:

model = YOLO("best.pt")
result = model(source=image, show=True, conf=0.4, save=True)

I get the mentioned error, any idea how to fix this?. Thanks in advance

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! 😊 It looks like the issue might be related to the `save=True` argument in your `model` call, which attempts to save the predicted image. The error suggests that OpenCV can't determine the file format to save the image because it lacks an extension. By default, `cv2.imwrite()` uses the file extension to determine the image format.

If you're saving the image directly in your script, ensure the `save_path` includes a proper file extension (e.g., `.jpg`, `.png`). Alternatively, to debug and bypass saving via the Ultralytics interface, you might try setting `save=False`.

For example, adjust your call to:

```python
result = model(source=image, show=True, conf=0.4, save=False)
```

And if you need to save the result separately, you can manually specify the filename with its extension:

```python
cv2.imwrite('result_image.jpg', cv2.cvtColor(result.render()[0], cv2.COLOR_RGB2BGR))
```

Remember to replace `'result_image.jpg'` with the desired path and filename. This manually saves the result image with the specified format, ensuring `cv2.imwrite()` recognizes the extension.

Hope this helps solve the issue! If it persists or you have further questions, please feel free to reach out.
