### ISSUE TITLE
Can't use Ultralytics, onnx2tf, sng4onnx, onnxsim, onnx_graphsurgeon, tflite_support packages not found

### ISSUE THREAD

**Issue by Notenlish** [ultralytics/ultralytics#10391]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I'm running this code: [benchmark example code](https://docs.ultralytics.com/modes/benchmark/?h=benchmark#usage-examples)
I have a windows 11 environment with RTX 3050 Ti laptop gpu
I have wsl2 installed with ubuntu distro and if I'm not mistaken it has the nvidia-cuda-toolkit installed
nvidia-smi output:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 552.22                 Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              5W /   85W |     130MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     16404    C+G   ...Brave-Browser\Application\brave.exe      N/A      |
+-----------------------------------------------------------------------------------------+
```

It cant find onnxsim, tries to install it itself and then fails when doing setup. I tried running the code both with and without the `device=0` optional argument.

output of running the code:
```
C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(

image 1/1 C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\assets\bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 124.4ms
Speed: 9.8ms preprocess, 124.4ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 480)
val: Scanning C:\Users\ihsan\npmbugsolve\UAV_teknofest\datasets\coco8\labels\val.cache... 4 images, 0 background
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [
                   all          4         17      0.865      0.893      0.921      0.638
Speed: 1.1ms preprocess, 97.1ms inference, 0.0ms loss, 2.1ms postprocess per image

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TorchScript: starting export with torch 2.2.0+cu118...
TorchScript: export success ✅ 1.4s, saved as 'yolov8n.torchscript' (12.4 MB)

Export complete (1.6s)
Results saved to C:\Users\ihsan\npmbugsolve\UAV_teknofest
Predict:         yolo predict task=detect model=yolov8n.torchscript imgsz=640
Validate:        yolo val task=detect model=yolov8n.torchscript imgsz=640 data=coco.yaml
Visualize:       https://netron.app
Loading yolov8n.torchscript for TorchScript inference...

image 1/1 C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\assets\bus.jpg: 640x640 4 persons, 1 bus, 185.7ms
Speed: 0.0ms preprocess, 185.7ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)
Loading yolov8n.torchscript for TorchScript inference...
val: Scanning C:\Users\ihsan\npmbugsolve\UAV_teknofest\datasets\coco8\labels\val.cache... 4 images, 0 background
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [ 
                   all          4         17      0.708      0.833      0.809      0.609
Speed: 0.5ms preprocess, 101.1ms inference, 0.0ms loss, 4.1ms postprocess per image

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: export success ✅ 0.6s, saved as 'yolov8n.onnx' (12.2 MB)

Export complete (0.8s)
Results saved to C:\Users\ihsan\npmbugsolve\UAV_teknofest
Predict:         yolo predict task=detect model=yolov8n.onnx imgsz=640
Validate:        yolo val task=detect model=yolov8n.onnx imgsz=640 data=coco.yaml
Visualize:       https://netron.app
Loading yolov8n.onnx for ONNX Runtime inference...

image 1/1 C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\assets\bus.jpg: 640x640 4 persons, 1 bus, 48.2ms
Speed: 5.5ms preprocess, 48.2ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)
Loading yolov8n.onnx for ONNX Runtime inference...
Forcing batch=1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning C:\Users\ihsan\npmbugsolve\UAV_teknofest\datasets\coco8\labels\val.cache... 4 images, 0 background 
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [ 
                   all          4         17      0.708      0.833      0.809      0.609
Speed: 0.5ms preprocess, 50.7ms inference, 0.0ms loss, 1.4ms postprocess per image

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: export success ✅ 0.5s, saved as 'yolov8n.onnx' (12.2 MB)

OpenVINO: starting export with openvino 2024.1.0-15008-f4afc983258-releases/2024/1...
OpenVINO: export success ✅ 1.2s, saved as 'yolov8n_openvino_model\' (12.3 MB)

Export complete (1.9s)
Results saved to C:\Users\ihsan\npmbugsolve\UAV_teknofest
Predict:         yolo predict task=detect model=yolov8n_openvino_model imgsz=640
Validate:        yolo val task=detect model=yolov8n_openvino_model imgsz=640 data=coco.yaml
Visualize:       https://netron.app
Loading yolov8n_openvino_model for OpenVINO inference...

image 1/1 C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\assets\bus.jpg: 640x640 4 persons, 1 bus, 70.2ms
Speed: 0.0ms preprocess, 70.2ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Loading yolov8n_openvino_model for OpenVINO inference...
Forcing batch=1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning C:\Users\ihsan\npmbugsolve\UAV_teknofest\datasets\coco8\labels\val.cache... 4 images, 0 background 
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [ 
                   all          4         17      0.708      0.833      0.809      0.609
Speed: 0.5ms preprocess, 46.0ms inference, 0.0ms loss, 0.8ms postprocess per image
ERROR ❌️ Benchmark failure for TensorRT: inference not supported on CPU
ERROR ❌️ Benchmark failure for CoreML: export only supported on macOS and Linux

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
requirements: Ultralytics requirements ['onnx2tf>=1.15.4,<=1.17.5', 'sng4onnx>=1.0.1', 'onnxsim>=0.4.33', 'onnx_graphsurgeon>=0.3.26', 'tflite_support'] not found, attempting AutoUpdate...
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [213 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      running create_version
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\model_checking.py -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\model_info.py -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\onnx_simplifier.py -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\version.py -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\__init__.py -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\__main__.py -> build\lib.win-amd64-cpython-312\onnxsim
      running egg_info
      writing onnxsim.egg-info\PKG-INFO
      writing dependency_links to onnxsim.egg-info\dependency_links.txt
      writing entry points to onnxsim.egg-info\entry_points.txt
      writing requirements to onnxsim.egg-info\requires.txt
      writing top-level names to onnxsim.egg-info\top_level.txt
      reading manifest file 'onnxsim.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c' under directory 'onnxsim'
      warning: no files found matching '*.proto' under directory 'onnxsim'
      warning: no previously-included files matching '*' found under directory 'third_party\onnxruntime'
      warning: no previously-included files matching '*' found under directory 'third_party\onnx-optimizer\build'
      warning: no previously-included files matching '*' found under directory 'third_party\onnx\build'
      warning: no previously-included files matching '*' found under directory 'third_party\onnx\onnx\backend'   
      adding license file 'LICENSE'
      writing manifest file 'onnxsim.egg-info\SOURCES.txt'
      C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'onnxsim.bin' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'onnxsim.bin' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'onnxsim.bin' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'onnxsim.bin' to be distributed and are
              already explicitly excluding 'onnxsim.bin' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying onnxsim\cpp2py_export.cc -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\cxxopts.hpp -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\onnxsim.cpp -> build\lib.win-amd64-cpython-312\onnxsim
      copying onnxsim\onnxsim.h -> build\lib.win-amd64-cpython-312\onnxsim
      creating build\lib.win-amd64-cpython-312\onnxsim\bin
      copying onnxsim\bin\onnxsim_bin.cpp -> build\lib.win-amd64-cpython-312\onnxsim\bin
      copying onnxsim\bin\onnxsim_option.cpp -> build\lib.win-amd64-cpython-312\onnxsim\bin
      copying onnxsim\bin\onnxsim_option.h -> build\lib.win-amd64-cpython-312\onnxsim\bin
      running build_ext
      running cmake_build
      Run command ['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPython_INCLUDE_DIR=C:\\Users\\İhsan\\AppData\\Local\\Programs\\Python\\Python312\\include', '-DPython_EXECUTABLE=C:\\Users\\İhsan\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-DPYTHON_EXECUTABLE=C:\\Users\\İhsan\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-DBUILD_ONNX_PYTHON=OFF', '-DONNXSIM_PYTHON=ON', '-DONNXSIM_BUILTIN_ORT=OFF', '-DONNX_USE_LITE_PROTO=OFF', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp312-win_amd64.pyd', '-DONNX_OPT_USE_SYSTEM_PROTOBUF=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.12', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\İhsan\\AppData\\Local\\Temp\\pip-install-5xjoum50\\onnxsim_6e806c5bf1a8479c991cc9ec6a931358']
      -- Building for: Visual Studio 17 2022
      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
      -- The CXX compiler identification is MSVC 19.39.33523.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- The C compiler identification is MSVC 19.39.33523.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      --
      -- 3.20.1.0
      -- Performing Test protobuf_HAVE_LD_VERSION_SCRIPT
      -- Performing Test protobuf_HAVE_LD_VERSION_SCRIPT - Success
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - not found
      -- Found Threads: TRUE
      -- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
      -- Found PythonInterp: C:/Users/Ä°hsan/AppData/Local/Programs/Python/Python312/python.exe (found suitable version "3.12.1", minimum required is "3.12")
      Generated: C:/Users/Ä°hsan/AppData/Local/Temp/pip-install-5xjoum50/onnxsim_6e806c5bf1a8479c991cc9ec6a931358/.setuptools-cmake-build/third_party/onnx-optimizer/third_party/onnx/onnx/onnx-ml.proto
      Generated: C:/Users/Ä°hsan/AppData/Local/Temp/pip-install-5xjoum50/onnxsim_6e806c5bf1a8479c991cc9ec6a931358/.setuptools-cmake-build/third_party/onnx-optimizer/third_party/onnx/onnx/onnx-operators-ml.proto
      Generated: C:/Users/Ä°hsan/AppData/Local/Temp/pip-install-5xjoum50/onnxsim_6e806c5bf1a8479c991cc9ec6a931358/.setuptools-cmake-build/third_party/onnx-optimizer/third_party/onnx/onnx/onnx-data.proto
      --
      -- ******** Summary ********
      --   CMake version                     : 3.26.4
      --   CMake command                     : C:/Program Files/CMake/bin/cmake.exe
      --   System                            : Windows
      --   C++ compiler                      : C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
      --   C++ compiler version              : 19.39.33523.0
      --   CXX flags                         : /DWIN32 /D_WINDOWS /EHsc /EHsc /wd26812
      --   Build type                        : Release
      --   Compile definitions               : NOMINMAX;__STDC_FORMAT_MACROS
      --   CMAKE_PREFIX_PATH                 :
      --   CMAKE_INSTALL_PREFIX              : C:/Program Files/onnxsim
      --   CMAKE_MODULE_PATH                 :
      --
      --   ONNX version                      : 1.17.0
      --   ONNX NAMESPACE                    : onnx
      --   ONNX_USE_LITE_PROTO               : OFF
      --   USE_PROTOBUF_SHARED_LIBS          : OFF
      --   Protobuf_USE_STATIC_LIBS          : ON
      --   ONNX_DISABLE_EXCEPTIONS           : OFF
      --   ONNX_DISABLE_STATIC_REGISTRATION  : OFF
      --   ONNX_WERROR                       : OFF
      --   ONNX_BUILD_TESTS                  : OFF
      --   ONNX_BUILD_BENCHMARKS             : OFF
      --   ONNX_BUILD_SHARED_LIBS            :
      --   BUILD_SHARED_LIBS                 :
      --
      --   Protobuf compiler                 :
      --   Protobuf includes                 :
      --   Protobuf libraries                :
      --   BUILD_ONNX_PYTHON                 : OFF
      -- pybind11 v2.9.2
      -- Found PythonInterp: C:/Users/Ä°hsan/AppData/Local/Programs/Python/Python312/python.exe (found version "3.12.1")
      CMake Error at third_party/pybind11/tools/FindPythonLibsNew.cmake:225 (message):
        Python libraries not found
      Call Stack (most recent call first):
        third_party/pybind11/tools/pybind11Tools.cmake:50 (find_package)
        third_party/pybind11/tools/pybind11Common.cmake:206 (include)
        third_party/pybind11/CMakeLists.txt:200 (include)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\İhsan\AppData\Local\Temp\pip-install-5xjoum50\onnxsim_6e806c5bf1a8479c991cc9ec6a931358\setup.py", line 279, in <module>
          setuptools.setup(
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\İhsan\AppData\Local\Temp\pip-install-5xjoum50\onnxsim_6e806c5bf1a8479c991cc9ec6a931358\setup.py", line 220, in run
          self.run_command('cmake_build')
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\İhsan\AppData\Local\Temp\pip-install-5xjoum50\onnxsim_6e806c5bf1a8479c991cc9ec6a931358\setup.py", line 194, in run
          subprocess.check_call(cmake_args)
        File "C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call 
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPython_INCLUDE_DIR=C:\\Users\\İhsan\\AppData\\Local\\Programs\\Python\\Python312\\include', '-DPython_EXECUTABLE=C:\\Users\\İhsan\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-DPYTHON_EXECUTABLE=C:\\Users\\İhsan\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-DBUILD_ONNX_PYTHON=OFF', '-DONNXSIM_PYTHON=ON', '-DONNXSIM_BUILTIN_ORT=OFF', '-DONNX_USE_LITE_PROTO=OFF', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp312-win_amd64.pyd', '-DONNX_OPT_USE_SYSTEM_PROTOBUF=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.12', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\İhsan\\AppData\\Local\\Temp\\pip-install-5xjoum50\\onnxsim_6e806c5bf1a8479c991cc9ec6a931358']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnxsim
```

### Environment

C:\Users\İhsan\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
Ultralytics YOLOv8.1.14 🚀 Python-3.12.1 torch-2.2.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096MiB)
Setup complete ✅ (16 CPUs, 15.8 GB RAM, 384.3/476.2 GB disk)

### Minimal Reproducible Example

```py

from ultralytics.utils.benchmarks import benchmark

# Benchmark on GPU
benchmark(model='yolov8n.pt', data='coco8.yaml', imgsz=640, half=False,
#device=0 
)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Notenlish hi there! It looks like you're having trouble with package dependencies when trying to run a benchmark script for YOLOv8. Here are a few steps that could help resolve your issue:

1. Ensure all necessary packages are installed. You might need to manually install the packages mentioned in the error logs. You can do this by running:
   ```bash
   pip install onnx2tf sng4onnx onnxsim onnx_graphsurgeon tflite_support
   ```
   Make sure you're using a Python environment where Ultralytics YOLOv8 is installed.

2. It seems like there's an issue with `onnxsim` installation based on the logs. If the above step doesn't resolve it, you might want to try reinstalling `onnxsim` specifically:
    ```bash
    pip install --upgrade onnxsim
    ```

3. The warning about Windows 11 not being supported by `onnxruntime` is slightly misleading, as ONNX Runtime does generally work on Windows 11. However, if you encounter specific issues related to this, consider setting up a virtual environment that mimics a supported setup or reach out to the `onnxruntime` community for more detailed advice.

4. Remember to activate your Python virtual environment before running the benchmark code to ensure all dependencies are recognized correctly.

5. Double-check to ensure you're running the latest Ultralytics YOLOv8 version to benefit from any fixes or enhancements that might address your issue.

If you've followed these steps and are still encountering issues, it might be helpful to share additional details like any specific error messages after trying these fixes. That way, the community can provide more targeted assistance. Thanks for reaching out for support, and don't hesitate to follow up if you need further assistance! 🌟

**Comment by Notenlish** [comment]
switching from 3.12 to 3.11 worked

thanks to `@skillnoob_` in discord for the tip
