### ISSUE TITLE
engine inference, AttributeError: module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by itsrealkk** [ultralytics/ultralytics#1128]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hi, while i'm doing inference with tensorrt, it shows "AttributeError: module 'numpy' has no attribute 'bool'."

Ultralytics YOLOv8.0.43 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12036MiB)
Loading best.engine for TensorRT inference...
[02/24/2023-09:53:17] [TRT] [I] Loaded engine size: 358 MiB
[02/24/2023-09:53:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1012, GPU +450, now: CPU 1880, GPU 1601 (MiB)
[02/24/2023-09:53:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +357, now: CPU 0, GPU 357 (MiB)
[02/24/2023-09:53:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +32, now: CPU 1522, GPU 1601 (MiB)
[02/24/2023-09:53:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +207, now: CPU 0, GPU 564 (MiB)
[02/24/2023-09:53:18] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorrt/__init__.py:166: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  bool: np.bool,
Traceback (most recent call last):
  File "/home/kk/miniconda3/envs/ultralytics/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 304, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 212, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 198, in predict
    self.predictor.setup_model(model=self.model)
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 219, in setup_model
    self.model = AutoBackend(model, device=device, dnn=self.args.dnn, data=self.args.data, fp16=self.args.half)
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 160, in __init__
    dtype = trt.nptype(model.get_binding_dtype(i))
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorrt/__init__.py", line 166, in nptype
    bool: np.bool,
  File "/home/kk/miniconda3/envs/ultralytics/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

### Environment

- YOLO: Ultralytics YOLOv8.0.43 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12036MiB)
- OS: Ubuntu 22.04.1 x64
- Python: 3.10.9
- numpy: 1.24.2
- ultralytics: 8.0.43

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by Marco-Nguyen** [comment]
I remember having this issue when using `numpy 1.24.2`. I had to downgrade to use tensorrt.

Reference: https://stackoverflow.com/questions/74893742/how-to-solve-attributeerror-module-numpy-has-no-attribute-bool

**Comment by itsrealkk** [comment]
> 

yes, changing to 1.23.5 will be okay

**Comment by pderrenger** [comment]
@itsrealkk glad to hear that you found a solution! Downgrading to numpy 1.23.5 should indeed address the `AttributeError: module 'numpy' has no attribute 'bool'` issue. If you encounter any further difficulties or have any more questions, feel free to ask! Good luck with your project!
