### ISSUE TITLE
Exceptions when training yolov8x segmentation with memory allocation on multiple GPU with plenty of space

### ISSUE THREAD

**Issue by benjivesterby** [ultralytics/ultralytics#1150]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I was able to get the segmentation models to train just fine for yolov8n-seg a couple days ago after uncommenting the multi-GPU gradient else branches. After successfully finishing a run I tried training the yolov8x-seg model and I get a CUDA out of memory error. I'm running Nvidia Tesla k80s x 4 (8 cores) and they have plenty of space and you can see in the exception logs that there was plenty of space on the GPUs. 

[output2.log](https://github.com/ultralytics/ultralytics/files/10831348/output2.log)

### Environment

- YOLO latest dev with multi-gpu comments removed
- Ubuntu 64 Server
- GPU 4x Nvidia K80s
- Python 3.10.6

### Minimal Reproducible Example

I'm using the vanilla yolo install with only the comments for multi-gpus removed for the gradients.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by benjivesterby** [comment]
I'll dig into the error more later to see if I can figure out where the issue is and submit a PR but I won't be able to until later this weekend.

**Comment by glenn-jocher** [comment]
@benjivesterby thanks for the bug report. We don't see any errors training DDP segmentation, but if you're seeing errors, since you're best placed to debug your DDP environment please submit a PR with any fixes that help and we can take a look there.

**Comment by thusinh1969** [comment]
I faced the same issue ! I tried batch=4 and it run through OK, but of course it took forever. WSL2 Ubuntu 22.04 with RTX3090 with plenty of 24G GPU RAM. Any hint ?

**Comment by lsch0lz** [comment]
I'm facing the same issue. 
Batch Size: 4
GPU: Tesla V100 with 16GB

If you train with batch=2, everything works. Although batch=4 does not use much more memory. Also there should be plenty of space left on the GPU.

After the first Epoch the training stops with the following exception:
```Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      3.98G     0.6285     0.9762      1.365          4        640: 100%|██████████| 339/339 [01:02<00:00,  5.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/21 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: unable to write to file </torch_116_4257383970_0>: No space left on device (28)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: unable to write to file </torch_112_2190742248_1>: No space left on device (28)
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   5%|▍         | 1/21 [01:55<38:23, 115.15s/it]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/opt/conda/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 118) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/lukasscholz/sylt_training/yolov8_training.py", line 5, in <module>
    model.train(data="/projects/lukasscholz/sylt_training/datasets/trucks/data.yaml", epochs=10, batch=4)
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 319, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 188, in train
    self._do_train(RANK, world_size)
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 349, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 445, in validate
    metrics = self.validator(self)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/validator.py", line 150, in __call__
    for batch_i, batch in enumerate(bar):
  File "/opt/conda/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1272, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 118) exited unexpectedly
```

**Comment by pderrenger** [comment]
@thusinh1969 hey there! It sounds like reducing the batch size helped to train the model without running into memory issues. This is a common workaround for out-of-memory errors. You might also consider adjusting the image size or using gradient accumulation if reducing the batch size significantly impacts training time. Let me know if you need further assistance!
