### ISSUE TITLE
YOLOv8m-pose AttributeError: 'Pose' object has no attribute 'detect'

### ISSUE THREAD

**Issue by KKopilka** [ultralytics/ultralytics#11691]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have trained a YOLOv8m-pose model and after running the model, I get an error:
`Traceback (most recent call last):
  File "D:\AI-Trainer\manual.py", line 140, in <module>
    main()
  File "D:\AI-Trainer\manual.py", line 54, in main
    results = model.predict(frame)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\model.py", line 451, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 228, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 589, in warmup
    self.forward(im)  # warmup
    ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 423, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\modules\head.py", line 165, in forward
    x = self.detect(self, x)
        ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Pose' object has no attribute 'detect'`

I ran the 'n' and 's' models and everything worked correctly. Can you please tell me what the problem might be? Why is the error appearing now? I also run the code in VS code, but everything works in Google Colab. My code looks like this:

`def main():

    model = YOLO('models/yolo3/best.pt')
    video_path = 'assets/left_side_cut.mp4'
    # video_path = 'assets/biceps.mp4'
    cap = cv2.VideoCapture(video_path)
    count = 0
    dirr = 1

    validFrames = {}

    while cap.isOpened():
        success, frame = cap.read()
        # h, w, _ = frame.shape
        # window_w = int(frame.shape[1] * w)
        # window_h = int(frame.shape[0] * h)
        # frame_size = int(cap.get(3)), int(cap.get(4))  # frame_w, frame_h
        # img_w, img_h = frame_size
        # cv2.resizeWindow("Video", window_w, window_h)
        frame = cv2.resize(frame, (800, 650), interpolation=cv2.INTER_AREA)

        if success:
            results = model(frame)
            # kps = results.xyxy[0]
            # kps = results[0].keypoints.data.cpu().numpy()[0]
            kps = results[0].keypoints.xy.cpu().numpy()[0]
            x, y, z = kps.T[:3]
            # x_img = x * img_w
            # y_img = y * img_h
            # pose_2d = np.column_stack((x_img, y_img))
            pose_3d = np.column_stack((x, y, z))
            if pose_3d.size <= 0:
                continue
            frame = draw_pose(
                image=frame,
                keypoints=pose_3d,
                disposition="coco",
                thickness=2,
            ) ...`

I want to add: I tried using predict(), but the error persists.
`if success:
            results = model.predict(frame)
            # kps = results.xyxy[0]
            # kps = results[0].keypoints.data.cpu().numpy()[0]
            kps = results[0].keypoints.xy.cpu().numpy()[0]
            x, y, z = kps.T[:3]
            # x_img = x * img_w
            # y_img = y * img_h
            # pose_2d = np.column_stack((x_img, y_img))
            pose_3d = np.column_stack((x, y, z))
`

`Traceback (most recent call last):
  File "D:\AI-Trainer\manual.py", line 140, in <module>
    main()
  File "D:\AI-Trainer\manual.py", line 54, in main
    results = model.predict(frame)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\model.py", line 451, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 228, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 589, in warmup
    self.forward(im)  # warmup
    ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 423, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\modules\head.py", line 165, in forward
    x = self.detect(self, x)
        ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Pose' object has no attribute 'detect'`

Thanks in advance!

**Comment by KKopilka** [comment]
I want to add: I tried using predict(), but the error persists.
`if success:
            results = model.predict(frame)
            # kps = results.xyxy[0]
            # kps = results[0].keypoints.data.cpu().numpy()[0]
            kps = results[0].keypoints.xy.cpu().numpy()[0]
            x, y, z = kps.T[:3]
            # x_img = x * img_w
            # y_img = y * img_h
            # pose_2d = np.column_stack((x_img, y_img))
            pose_3d = np.column_stack((x, y, z))`

`Traceback (most recent call last):
  File "D:\AI-Trainer\manual.py", line 140, in <module>
    main()
  File "D:\AI-Trainer\manual.py", line 54, in main
    results = model.predict(frame)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\model.py", line 451, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 228, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 589, in warmup
    self.forward(im)  # warmup
    ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 423, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\modules\head.py", line 165, in forward
    x = self.detect(self, x)
        ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Pose' object has no attribute 'detect'`

**Comment by glenn-jocher** [comment]
Hello! It looks like you encountered an `AttributeError` because the method you're trying to use isn't available in the `Pose` class of YOLOv8m-pose.

For the pose estimation model, you should use the `.predict()` method instead of `.detect()` which is typically used with detection models. From the snippets you've shown, it appears you're using `.predict()` correctly. However, to avoid any possible errors, ensure all your syntax matches exactly as it should be when employing the `.predict()` method.

Here's a simple usage example:

```python
results = model.predict(frame)
keypoints = results[0].keypoints.xy.cpu().numpy()
```

Ensure your installation is updated and correctly configured, particularly if transitioning between different environments like VS Code and Google Colab that might have different package versions.

If issues persist, verifying paths and ensuring that your environment aligns with the requirements of the Ultralytics library could help pinpoint discrepancies. If still unresolved, please provide further details or the specific line that continues to raise errors.

Thank you for reaching out!

**Comment by KKopilka** [comment]
@glenn-jocher OK, I tried changing the code to yours, but the error persists:
```
results = model.predict(frame)
kps = results[0].keypoints.xy.cpu().numpy()
```

```
Traceback (most recent call last):
  File "D:\AI-Trainer\manual.py", line 156, in <module>
    main()
  File "D:\AI-Trainer\manual.py", line 59, in main
    results = model.predict(frame)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\model.py", line 451, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 228, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 589, in warmup
    self.forward(im)  # warmup
    ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 423, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\nn\modules\head.py", line 165, in forward
    x = self.detect(self, x)
        ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Pose' object has no attribute 'detect'
```

**Comment by glenn-jocher** [comment]
Hello! It looks like there's a mix-up with the methods in use. The error `'Pose' object has no attribute 'detect'` suggests trying to access functionality that doesn't exist in the pose estimation model.

Here's how you should configure your predictor:
```python
results = model.predict(frame)  # Correct method for prediction
keypoints = results[0].keypoints.xy.cpu().numpy()  # Extracting keypoints
```
Ensure your model instantiation (`YOLO('path_to_model')`) is correctly referenced to the model you intend to use and that it's appropriately configured for pose detection, not object detection.

If the problem persists and all setups look correct, it might help to reinstall the Ultralytics library to ensure there are no corrupted or mismatched files. 👍 Let us know how it goes!

**Comment by oOvOio** [comment]
This may be due to inconsistencies between the version of Ultralytics used for inference and the version of Ultralytics used for training

**Comment by glenn-jocher** [comment]
Hello! It sounds like you might be right about the version inconsistency. Please make sure that both the training and inference environments are using the same version of Ultralytics YOLO. You can check the version in your environment with:

```bash
pip show ultralytics
```

If they differ, consider updating to the latest version using:

```bash
pip install --upgrade ultralytics
```

This should help maintain compatibility across your processes. Let us know how it goes! 😊

**Comment by KKopilka** [comment]
@glenn-jocher 
@oOvOio 
Good afternoon! Yes, I already realized that the problem was in the version update ultralytics :)
Thank u!

**Comment by glenn-jocher** [comment]
Hello! Great to hear that you figured out the issue with the version update! 🎉 If you have any more questions or run into any other issues, feel free to reach out. Happy coding with Ultralytics! 😊🚀

**Comment by yescine** [comment]
@glenn-jocher I trained model based on v8-pose with `ultralytics==8.2.40` in other older project with `ultralytics="8.0.200"` I run inference and got same error `AttributeError: 'Pose' object has no attribute 'detect'` (it did work after the upgrade)
will the the output training `weight.pt` be future proof, you know the last thing we won' t do is maintaining versioning compatibilities across projects 😁

**Comment by glenn-jocher** [comment]
Hello @yescine,

Thank you for your message! It's great to hear that upgrading resolved the issue for you. Regarding your question about future-proofing the training weights (`weight.pt`), Ultralytics aims to maintain backward compatibility as much as possible. However, to ensure smooth transitions and avoid versioning issues, here are a few best practices:

1. **Version Control**: Keep track of the Ultralytics version used for training and inference. This can help in troubleshooting and maintaining compatibility.
2. **Export Models**: Consider exporting your models to a more stable format like ONNX or TensorRT, which can be more resilient to changes in the underlying library.
3. **Regular Updates**: Periodically update your projects to the latest versions to benefit from improvements and bug fixes.

If you encounter any issues, providing a reproducible example can greatly help in diagnosing the problem. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy coding! 😊
