### ISSUE TITLE
Error at the end of a training task

### ISSUE THREAD

**Issue by aurelien-m** [ultralytics/ultralytics#1210]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I'm training with `yolo task=detect mode=train model=yolov8n.pt imgsz=512 data=dataset.yml epochs=50 batch=-1 name=Project` but I'm getting the following error at the end of my training task:

```
...
Validating runs/detect/Project4/weights/best.pt...
Ultralytics YOLOv8.0.48 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24265MiB)
Model summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
Traceback (most recent call last):
  File "/home/aurelien/Projects/Venvs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 313, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 319, in train
    self.trainer.train()
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 188, in train
    self._do_train(RANK, world_size)
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 376, in _do_train
    self.final_eval()
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 511, in final_eval
    self.metrics = self.validator(model=f)
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/validator.py", line 130, in __call__
    raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' for task={self.args.task} not found ❌"))
FileNotFoundError: Dataset 'dataset.yml' for task=detect not found ❌
```

### Environment

- Yolo: Ultralytics YOLOv8.0.48 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24265MiB)
- OS: Pop_OS 22.04
- Python: 3.10.6

### Minimal Reproducible Example

 `yolo task=detect mode=train model=yolov8n.pt imgsz=512 data=dataset.yml epochs=50 batch=-1 name=Project`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JustasBart** [comment]
Hi @aurelien-m is it perhaps because you have it as '**data=dataset.yml**' instead of '**data=dataset.yaml**'?

**Comment by aurelien-m** [comment]
Thanks @JustasBart, I had to change my file name to `dataset.yaml` and now it works fine.

**Comment by honzikv** [comment]
Jesus I've wasted around 6 hours on stupid "yml" extension issue 🤦

**Comment by JustasBart** [comment]
@honzikv Hey experience isn't always cheap, but when you know - you know :rocket:

**Comment by aurelien-m** [comment]
I think it could be nice to also accept `.yml` files, or return an error when using these files :)

**Comment by pderrenger** [comment]
Glad to hear that changing the file name to `dataset.yaml` resolved the issue for you, @aurelien-m! As for supporting `.yml` files, it's a great suggestion to improve the user experience. I'll pass your feedback on to the team for consideration.
