### ISSUE TITLE
오류 ㅠㅠ

### ISSUE THREAD

**Issue by kan12341234** [ultralytics/ultralytics#12289]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

오류 해결 방법좀... ㅠㅠ

2024-05-11 22:53:55,779 - AnimateDiff - INFO - Removing motion module from any memory
2024-05-11 22:54:09,613 - AnimateDiff - INFO - AnimateDiff process start.
2024-05-11 22:54:09,614 - AnimateDiff - INFO - Motion module already injected. Trying to restore.
*** Error running before_process: E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "E:\sd.webui\webui\modules\scripts.py", line 817, in before_process
        script.before_process(p, *script_args)
      File "E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 64, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 65, in inject
        self.restore(sd_model)
      File "E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 123, in restore
        inject_sdxl = sd_model.is_sdxl or self.mm.is_xl
    AttributeError: 'NoneType' object has no attribute 'is_xl'

---
*** Error completing request
*** Arguments: ('task(vthz9g0fphruqc6)', <gradio.routes.Request object at 0x000002256A47AB60>, 'kamado nezuko, 1girl, black hair, forehead, hair ribbon, japanese clothes, kimono, long hair, multicolored hair, open mouth, pink eyes, pink kimono, pink ribbon, ribbon, smile, very long hair, sky, ((masterpiece))  <lora:kamado_nezuko_offset:1>(masterpiece, best quality, extremely detailed CG, beautiful detailed eyes, ultra-detailed, intricate details, 8k wallpaper, elaborate features) ', '(worst quality, normal quality, low quality:1.4), lowres, blurry badhandv4 easynegative', [], 1, 1, 7, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 20, 'DPM++ 2M', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x000002256A49B0A0>, ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "E:\sd.webui\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\sd.webui\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\sd.webui\webui\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "E:\sd.webui\webui\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "E:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 48, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\sd.webui\webui\modules\processing.py", line 942, in process_images_inner
        p.rng = rng.ImageRNG((opt_C, p.height // opt_f, p.width // opt_f), p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, seed_resize_from_h=p.seed_resize_from_h, seed_resize_from_w=p.seed_resize_from_w)
      File "E:\sd.webui\webui\modules\rng.py", line 108, in __init__
        self.generators = [create_generator(seed) for seed in seeds]
      File "E:\sd.webui\webui\modules\rng.py", line 108, in <listcomp>
        self.generators = [create_generator(seed) for seed in seeds]
      File "E:\sd.webui\webui\modules\rng.py", line 80, in create_generator
        generator = torch.Generator(device).manual_seed(int(seed))
    RuntimeError: CUDA error: device-side assert triggered
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

---
Traceback (most recent call last):
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd.webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\sd.webui\webui\modules\call_queue.py", line 95, in f
    mem_stats = {k: -(v//-(1024*1024)) for k, v in shared.mem_mon.stop().items()}
  File "E:\sd.webui\webui\modules\memmon.py", line 92, in stop
    return self.read()
  File "E:\sd.webui\webui\modules\memmon.py", line 77, in read
    free, total = self.cuda_mem_get_info()
  File "E:\sd.webui\webui\modules\memmon.py", line 34, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "E:\sd.webui\webui\venv\lib\site-packages\torch\cuda\memory.py", line 663, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Additional

2024-05-11 22:53:55,779 - AnimateDiff - INFO - Removing motion module from any memory
2024-05-11 22:54:09,613 - AnimateDiff - INFO - AnimateDiff process start.
2024-05-11 22:54:09,614 - AnimateDiff - INFO - Motion module already injected. Trying to restore.
*** Error running before_process: E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "E:\sd.webui\webui\modules\scripts.py", line 817, in before_process
        script.before_process(p, *script_args)
      File "E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 64, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 65, in inject
        self.restore(sd_model)
      File "E:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 123, in restore
        inject_sdxl = sd_model.is_sdxl or self.mm.is_xl
    AttributeError: 'NoneType' object has no attribute 'is_xl'

---
*** Error completing request
*** Arguments: ('task(vthz9g0fphruqc6)', <gradio.routes.Request object at 0x000002256A47AB60>, 'kamado nezuko, 1girl, black hair, forehead, hair ribbon, japanese clothes, kimono, long hair, multicolored hair, open mouth, pink eyes, pink kimono, pink ribbon, ribbon, smile, very long hair, sky, ((masterpiece))  <lora:kamado_nezuko_offset:1>(masterpiece, best quality, extremely detailed CG, beautiful detailed eyes, ultra-detailed, intricate details, 8k wallpaper, elaborate features) ', '(worst quality, normal quality, low quality:1.4), lowres, blurry badhandv4 easynegative', [], 1, 1, 7, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 20, 'DPM++ 2M', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x000002256A49B0A0>, ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[]), False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "E:\sd.webui\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\sd.webui\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\sd.webui\webui\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "E:\sd.webui\webui\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "E:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 48, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "E:\sd.webui\webui\modules\processing.py", line 942, in process_images_inner
        p.rng = rng.ImageRNG((opt_C, p.height // opt_f, p.width // opt_f), p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, seed_resize_from_h=p.seed_resize_from_h, seed_resize_from_w=p.seed_resize_from_w)
      File "E:\sd.webui\webui\modules\rng.py", line 108, in __init__
        self.generators = [create_generator(seed) for seed in seeds]
      File "E:\sd.webui\webui\modules\rng.py", line 108, in <listcomp>
        self.generators = [create_generator(seed) for seed in seeds]
      File "E:\sd.webui\webui\modules\rng.py", line 80, in create_generator
        generator = torch.Generator(device).manual_seed(int(seed))
    RuntimeError: CUDA error: device-side assert triggered
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

---
Traceback (most recent call last):
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd.webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\sd.webui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\sd.webui\webui\modules\call_queue.py", line 95, in f
    mem_stats = {k: -(v//-(1024*1024)) for k, v in shared.mem_mon.stop().items()}
  File "E:\sd.webui\webui\modules\memmon.py", line 92, in stop
    return self.read()
  File "E:\sd.webui\webui\modules\memmon.py", line 77, in read
    free, total = self.cuda_mem_get_info()
  File "E:\sd.webui\webui\modules\memmon.py", line 34, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "E:\sd.webui\webui\venv\lib\site-packages\torch\cuda\memory.py", line 663, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by glenn-jocher** [comment]
@kan12341234 안녕하세요! 오류로 인해 어려움을 겪고 계신 것 같아 걱정이 되네요. 😟

제시된 에러 메시지를 살펴보니, `AttributeError: 'NoneType' object has no attribute 'is_xl'` 부분에서 문제가 발생하는 것 같습니다. 여기서 `NoneType` 오류는 대상 객체가 `None`일 때 발생하는데, 이는 `motion_module` 또는 `sd_model` 중 하나가 제대로 초기화되지 않았을 가능성이 있습니다.

처음으로 해볼 수 있는 몇 가지 사항은 다음과 같습니다:
1. 모든 관련 객체가 올바르게 초기화되었는지 확인해보세요.
2. CUDA 관련 에러를 해결하기 위해, 실행 환경에 `CUDA_LAUNCH_BLOCKING=1` 환경 변수를 설정하여 더 자세한 에러 로그를 얻을 수 있도록 해보세요.

또한, CUDA 관련 이슈로 보이는데, GPU와 관련된 설정(예: driver, CUDA 버전)이 적절히 설정되어 있는지도 점검해 보시기 바랍니다.

아래는 환경 변수 설정 방법 예시입니다:
```bash
export CUDA_LAUNCH_BLOCKING=1
python your_script.py
```

이러한 단계로도 문제가 해결되지 않는다면, 좀 더 자세한 상황을 알려주시면 추가적인 조언을 드리겠습니다!
