### ISSUE TITLE
No space left on device with plenty of space left on GPU

### ISSUE THREAD

**Issue by lsch0lz** [ultralytics/ultralytics#1238]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

```
Ultralytics YOLOv8.0.49 🚀 Python-3.9.12 torch-1.13.0 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
yolo/engine/trainer: task=detect, mode=train, model=/projects/lukasscholz/sylt_training/backbones/yolov8x.pt, data=/projects/lukasscholz/sylt_training/datasets/trucks/data.yaml, epochs=10, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, min_memory=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train5
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      2320  ultralytics.nn.modules.Conv                  [3, 80, 3, 2]
  1                  -1  1    115520  ultralytics.nn.modules.Conv                  [80, 160, 3, 2]
  2                  -1  3    436800  ultralytics.nn.modules.C2f                   [160, 160, 3, True]
  3                  -1  1    461440  ultralytics.nn.modules.Conv                  [160, 320, 3, 2]
  4                  -1  6   3281920  ultralytics.nn.modules.C2f                   [320, 320, 6, True]
  5                  -1  1   1844480  ultralytics.nn.modules.Conv                  [320, 640, 3, 2]
  6                  -1  6  13117440  ultralytics.nn.modules.C2f                   [640, 640, 6, True]
  7                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]
  8                  -1  3   6969600  ultralytics.nn.modules.C2f                   [640, 640, 3, True]
  9                  -1  1   1025920  ultralytics.nn.modules.SPPF                  [640, 640, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  3   1948800  ultralytics.nn.modules.C2f                   [960, 320, 3]
 16                  -1  1    922240  ultralytics.nn.modules.Conv                  [320, 320, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  3   7174400  ultralytics.nn.modules.C2f                   [960, 640, 3]
 19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]
 22        [15, 18, 21]  1   8718931  ultralytics.nn.modules.Detect                [1, [320, 640, 640]]
Model summary: 365 layers, 68153571 parameters, 68153555 gradients, 258.1 GFLOPs

Transferred 589/595 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005), 103 bias
train: Scanning /projects/lukasscholz/sylt_training/datasets/trucks/train/labels.cache... 1355 images, 0 backgrounds, 0 corrupt: 100%|████
val: Scanning /projects/lukasscholz/sylt_training/datasets/trucks/valid/labels.cache... 166 images, 0 backgrounds, 0 corrupt: 100%|███████
Plotting labels to runs/detect/train5/labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train5
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      3.98G     0.6285     0.9762      1.365          4        640: 100%|██████████| 339/339 [01:01<00:00,  5.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/21 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: unable to write to file </torch_722_783672312_1>: No space left on device (28)
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/21 [03:11<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/opt/conda/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 717) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/lukasscholz/sylt_training/yolov8_training.py", line 5, in <module>
    model.train(data="/projects/lukasscholz/sylt_training/datasets/trucks/data.yaml", epochs=10, batch=4)
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 319, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 188, in train
    self._do_train(RANK, world_size)
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 349, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 445, in validate
    metrics = self.validator(self)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/engine/validator.py", line 150, in __call__
    for batch_i, batch in enumerate(bar):
  File "/opt/conda/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1272, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 717) exited unexpectedly
```

### Environment

- Ultralytics YOLOv8.0.49 🚀 Python-3.9.12 torch-1.13.0 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
- Python: Python 3.9.12

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO("path/to/model/yolov8x.pt") 

# Use the model
model.train(data="path/to/data/data.yaml", epochs=10, batch=4)
```

### Additional

The model trains the first epoch, but then crashes with the mentioned exception.
When training with batch=2 everything works, even though not much more memory is used for training.

With batch=4 1/3 of the GPU memory is used:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   44C    P0    42W / 300W |   5077MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     18931      C   python                           5075MiB |
+-----------------------------------------------------------------------------+
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by limwenyao** [comment]
Don’t think this is a gpu memory issue, you would get a cuda OOM instead.

See if this [discussion](https://discuss.pytorch.org/t/training-crashes-due-to-insufficient-shared-memory-shm-nn-dataparallel/26396/2) helps

**Comment by glenn-jocher** [comment]
@lsch0lz if you can provide a reproducible example in a common environment like Colab please let us know, otherwise you may simply be out of system resources, as it doesn't appear to be CUDA related.

**Comment by lsch0lz** [comment]
I couldn't reproduce it on google colab, even though it's the same GPU. Setting ```workers=0``` solved the issue for me. Maybe it has something to do with the Docker-Container, where I run the training?

**Comment by limwenyao** [comment]
@lsch0lz ah. Assuming you are using docker with default configuration, shm size is 64MB. You will need to increase it by setting `--ipc=host` or `--shm_size=<desired size>` inside your docker run command. I think 1G is sufficient, also depends on how much system RAM you have.

**Comment by lsch0lz** [comment]
@limwenyao this fixed the issue!

**Comment by glenn-jocher** [comment]
@limwenyao thanks for the tip!

**Comment by hdnh2006** [comment]
> [@lsch0lz](https://github.com/lsch0lz) ah. Assuming you are using docker with default configuration, shm size is 64MB. You will need to increase it by setting `--ipc=host` or `--shm_size=<desired size>` inside your docker run command. I think 1G is sufficient, also depends on how much system RAM you have.

I can confirm `--ipc=host` solves the problem

**Comment by glenn-jocher** [comment]
@hdnh2006 great to hear another confirmation! As this thread shows, the `--ipc=host` or `--shm-size` Docker flags are the standard solution for shared memory issues during YOLO training in containers. Alternatively, setting `workers=0` can work around the issue by disabling multiprocessing, though at the cost of slower data loading performance.
