### ISSUE TITLE
Training issue with latest version of ultralytics

### ISSUE THREAD

**Issue by guiaugustoga987** [ultralytics/ultralytics#12668]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello,

I usually train yolov8 on my custom dataset using google colab with ultralytics 8.0.196 successfully with the line: 

`!yolo task=segment mode=train model=yolov8n-seg.pt data={dataset.location}/data.yaml epochs=300 imgsz=640`

Now I tried to switch to ultralytics latest version (YOLOv8.2.15). When I execute the same code I get the error : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 517, in get_dataset
    data = check_det_dataset(self.args.data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py", line 329, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError: 
Dataset '/content/datasets/pl-detections-v4-13/data.yaml' images not found ⚠️, missing path '/content/datasets/pl-detections-v4-13/pl-detections-v4-13/valid/images'
Note dataset download directory is '/content/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 583, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 655, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/segment/train.py", line 30, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 130, in __init__
    self.trainset, self.testset = self.get_dataset()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 521, in get_dataset
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset '/content/datasets/pl-detections-v4-13/data.yaml' error ❌ 
Dataset '/content/datasets/pl-detections-v4-13/data.yaml' images not found ⚠️, missing path '/content/datasets/pl-detections-v4-13/pl-detections-v4-13/valid/images'
Note dataset download directory is '/content/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml'
```

I think I understand what is causing the error. The program is looking for the dataset folder but the dataset directory (pl-detections-v4-13) is duplicated. I checked the data.yaml which is automatically generated by roboflow and this is the output : 

```
names:
- '0'
nc: 1
roboflow:
  license: CC BY 4.0
  project: pl-detections-v4
  url: https://universe.roboflow.com/pltdataset-cpx3u/pl-detections-v4/dataset/13
  version: 13
  workspace: pltdataset-cpx3u
test: ../test/images
train: pl-detections-v4-13/train/images
val: pl-detections-v4-13/valid/images
```

If I change the training and val folders to `../train/images` and `../valid/images` as it is in test I can execute the training with no issues. Not sure what is causing this, since this error did not occur with ultralytics 8.0.196.

Any help is appreciated.

### Environment

Ultralytics YOLOv8.2.15 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 29.8/78.2 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by guiaugustoga987** [comment]
It seems like if I install ultralytics 8.0.196 and then roboflow the data.yaml is generated correctlly : 

```
names:
- '0'
nc: 1
roboflow:
  license: CC BY 4.0
  project: pl-detections-v4
  url: https://universe.roboflow.com/pltdataset-cpx3u/pl-detections-v4/dataset/13
  version: 13
  workspace: pltdataset-cpx3u
test: test/images
train: train/images
val: valid/images
```

If I install ultralytics 8.2.15 and then roboflow the directories for training and validation will be duplicated as we can see : 

```
names:
- '0'
nc: 1
roboflow:
  license: CC BY 4.0
  project: pl-detections-v4
  url: https://universe.roboflow.com/pltdataset-cpx3u/pl-detections-v4/dataset/13
  version: 13
  workspace: pltdataset-cpx3u
test: ../test/images
train: pl-detections-v4-13/train/images
val: pl-detections-v4-13/valid/images
```

**Comment by reymarkolq** [comment]
Hi

I usually train yolov8 on my custom dataset using google colab with ultralytics 8.0.196 successfully with the line:
!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=10 imgsz=640 plots=True

How can I fix this error:

 Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0% 0/111 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 325, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/build.py", line 42, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py", line 242, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/augment.py", line 70, in __call__
    data = t(data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/augment.py", line 824, in __call__
    new = self.transform(image=im, bboxes=bboxes, class_labels=cls)  # transformed
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 334, in __call__
    self.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 368, in preprocess
    p.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 125, in preprocess
    data = self.add_label_fields_to_data(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 185, in add_label_fields_to_data
    encoded_labels = encoder.fit_transform(data[label_field])
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 60, in fit_transform
    self.fit(y)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 48, in fit
    unique_labels = sorted(set(y))
TypeError: unhashable type: 'numpy.ndarray'
