### ISSUE TITLE
KeyError: 'task' with YOLOv8.0.50

### ISSUE THREAD

**Issue by itsrealkk** [ultralytics/ultralytics#1301]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hi, I'm trying to predict an image with the exported onnx model. 
Command:
```
yolo task=detect predict source=test2.jpg model=best.onnx save conf=0.5 imgsz=1280
```
While using  YOLOv8.0.50, it will got an error:
```
Ultralytics YOLOv8.0.50 🚀 Python-3.10.9 torch-1.13.1 CPU
Loading best.onnx for ONNX Runtime inference...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/ultralytics/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 317, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/ubuntu/miniconda3/envs/ultralytics/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 218, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/ubuntu/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 227, in setup_model
    self.model = AutoBackend(model,
  File "/home/ubuntu/miniconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 264, in __init__
    task = metadata['task']
KeyError: 'task'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```
While using YOLOv8.0.43 with the same command, I can got a successful output

```
Ultralytics YOLOv8.0.43 🚀 Python-3.10.9 torch-1.13.1 CPU
Loading best.onnx for ONNX Runtime inference...

image 1/1 /home/ubuntu/test2.jpg: 1280x1280 1 person, 541.1ms
Speed: 8.8ms preprocess, 541.1ms inference, 2.3ms postprocess per image at shape (1, 3, 1280, 1280)
Results saved to runs/detect/predict9
```

### Environment

- YOLO: Ultralytics YOLOv8.0.50 🚀 Python-3.10.9 torch-1.13.1 CPU
- OS: Ubuntu 22.04 x64
- Python: 3.10.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@itsrealkk your ONNX model is out of date and not forward compatible with newer versions of ultralytics. You can revert to the version used to export it, or export your original PyTorch model to ONNX again using 8.0.50.

**Comment by itsrealkk** [comment]
> @itsrealkk your ONNX model is out of date and not forward compatible with newer versions of ultralytics. You can revert to the version used to export it, or export your original PyTorch model to ONNX again using 8.0.50.

Problem Solved, thx
