### ISSUE TITLE
Bug in function  `det.summary()` for `ultralytics>=8.2.10`: 

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/ultralytics#13023]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello!

It looks like some modifications of the last versions of `ultralytics` have affected an important function to get the results in "json format". To be specific, I am running this code for my webcam:
```
from ultralytics import YOLO
from ultralytics.data import load_inference_source

# Load model
model = YOLO('yolov8n.pt', task="detect")

dataset = load_inference_source(0)

results = model.predict(dataset, stream=True)

# Process results
for det in results:  # detections per image
    json_result = det.summary()
    # Do whatever...
``` 
When I cover my webcam in up to version `ultralytics==8.2.9` I got no problems:
``` 
python test_yolo.py 
1/1: 0... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)

0: 480x640 1 person, 320.1ms
0: 480x640 1 person, 4.9ms
0: 480x640 1 person, 4.3ms
0: 480x640 1 person, 4.7ms
0: 480x640 1 person, 4.1ms
0: 480x640 1 person, 4.3ms
0: 480x640 1 person, 4.2ms
0: 480x640 (no detections), 4.6ms # HERE I COVER MY WEBCAM AND CODE FOLLOWS...
0: 480x640 (no detections), 4.6ms
0: 480x640 (no detections), 4.6ms
0: 480x640 (no detections), 4.3ms
0: 480x640 (no detections), 4.1ms
0: 480x640 (no detections), 4.4ms
0: 480x640 (no detections), 4.7ms
0: 480x640 (no detections), 4.7ms
0: 480x640 (no detections), 6.0ms
0: 480x640 (no detections), 3.9ms
0: 480x640 (no detections), 4.7ms
...
``` 

But for versions of `ultralytics>=8.2.10`, the code fails when no detections (cover camera):
```
python test_yolo.py 
1/1: 0... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)


0: 480x640 1 person, 1 book, 311.2ms
0: 480x640 1 person, 4.4ms
0: 480x640 1 person, 4.2ms
0: 480x640 1 person, 3.9ms
0: 480x640 1 person, 3.8ms
0: 480x640 1 person, 3.8ms
0: 480x640 1 person, 3.8ms
0: 480x640 1 person, 4.0ms
0: 480x640 1 person, 4.1ms
0: 480x640 1 person, 4.0ms
0: 480x640 1 person, 3.9ms
0: 480x640 1 person, 4.2ms
0: 480x640 1 person, 4.1ms
0: 480x640 1 person, 3.7ms
0: 480x640 1 person, 3.8ms
0: 480x640 1 person, 3.5ms
0: 480x640 (no detections), 4.0ms # HERE I COVER MY WEBCAM
Traceback (most recent call last):
  File "/home/henry/.../yolo/test_yolo.py", line 23, in <module>
    json_result = det.summary()
  File "/home/henry/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/results.py", line 406, in summary
    for i, row in enumerate(data):  # xyxy, track_id if tracking, conf, class_id
TypeError: 'NoneType' object is not iterable
terminate called without an active exception
Aborted (core dumped)
```

So obviously, the code is failling when no object is detected. I have tried with all versions of `ultralytics>=8.2.10` and same results are gotten.

### Environment

Any version of `ultralytics>=8.2.10` fails.

```
Ultralytics YOLOv8.2.10 🚀 Python-3.10.12 torch-2.2.2+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 7940MiB)
Setup complete ✅ (16 CPUs, 14.9 GB RAM, 713.1/937.3 GB disk)
```

### Minimal Reproducible Example

``` 
from ultralytics import YOLO
from ultralytics.data import load_inference_source

# Load model
model = YOLO('yolov8n.pt', task="detect")

dataset = load_inference_source(0)

results = model.predict(dataset, stream=True)

# Process results
for det in results:  # detections per image
    json_result = det.summary()
    # Do whatever...
```

### Additional

In order to help you know where is the bug, I will check version `ultralytics==8.2.10` to know where are the changes that made this package fails.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by hdnh2006** [comment]
PR is opened:
https://github.com/ultralytics/ultralytics/pull/13024

**Comment by hdnh2006** [comment]
I close this issue, cause PR was merged

**Comment by glenn-jocher** [comment]
@hdnh2006 thanks for updating us and for your contribution to the YOLOv8 community! If you have any more issues or further contributions, feel free to reach out. Happy coding! 🚀
