### ISSUE TITLE
yolov8 when train,raise error OSError: [WinError 87] parameters error

### ISSUE THREAD

**Issue by lucieniorl** [ultralytics/ultralytics#13093]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

when i train my own datasets ,i hope use ray[tune] get best hyperparameters,but got OSError: [WinError 87] parameters error

### Environment

Ultralytics YOLOv8.2.19 🚀 Python-3.11.3 torch-2.3.0+cpu CPU (Intel Core(TM) i5-4570 3.20GHz)
Setup complete ✅ (4 CPUs, 15.9 GB RAM, 119.3/276.5 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.3
Install             pip
RAM                 15.87 GB
CPU                 Intel Core(TM) i5-4570 3.20GHz
CUDA                None

matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

> pip show ultralytics
Name: ultralytics
Version: 8.2.19
Summary: Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
Home-page:
Author: Glenn Jocher, Ayush Chaurasia, Jing Qiu
Author-email:
License: AGPL-3.0
Location: F:\Project\aidetect\aidetect_venv\Lib\site-packages
Requires: matplotlib, opencv-python, pandas, pillow, psutil, py-cpuinfo, pyyaml, requests, scipy, seaborn, thop, torch, torchvision, tqdm
Required-by:

### Minimal Reproducible Example

import os
os.environ["WANDB_API_KEY"] = 'my key'
print("Create a new YOLO model from scratch:count={c}".format(c=count))
model = YOLO('F:\\Project\\aidetect\\data\\ks\\yolov8n.yaml').load('yolov8n.pt')
print("Train the model using the 'coco128.yaml' dataset for 3 epochs:count={c}".format(c=count))
results = model.tune(data='F:\\Project\\aidetect\\data\\ks\\coco128.yaml', epochs=100, imgsz=640,use_ray=True)
print(results)

### Additional

ErrorMessage
Traceback (most recent call last):
  File "python\ray\_raylet.pyx", line 1887, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1828, in ray._raylet.execute_task.function_executor
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ray\tune\trainable\trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ray\air\_internal\util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ray\tune\trainable\function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ray\tune\trainable\function_trainable.py", line 248, in _trainable_func
    output = fn()
             ^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ultralytics\utils\tuner.py", line 104, in _tune
    results = model_to_train.train(**config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ultralytics\engine\model.py", line 655, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ultralytics\engine\trainer.py", line 101, in __init__
    self.device = select_device(self.args.device, self.args.batch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ultralytics\utils\torch_utils.py", line 164, in select_device
    s += f"CPU ({get_cpu_info()})\n"
                 ^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\ultralytics\utils\torch_utils.py", line 73, in get_cpu_info
    info = cpuinfo.get_cpu_info()  # info dict
           ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\cpuinfo\cpuinfo.py", line 2759, in get_cpu_info
    output = get_cpu_info_json()
             ^^^^^^^^^^^^^^^^^^^
  File "F:\Project\aidetect\aidetect_venv\Lib\site-packages\cpuinfo\cpuinfo.py", line 2741, in get_cpu_info_json
    p1 = Popen(command, stdout=PIPE, stderr=PIPE, stdin=PIPE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Program Files\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] parameters error。

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! It looks like you're encountering an `OSError: [WinError 87]` related to parameter errors when using Ray Tune with YOLOv8 on Windows. This error can sometimes occur due to compatibility issues or incorrect configurations.

Here are a couple of things you might try to resolve this issue:

1. **Check Path Formats:** Ensure that all file paths in your configuration are correctly formatted for Windows. Use double backslashes `\\` or raw string literals `r'path'` to avoid escape character issues.

2. **Environment Variables:** Sometimes, environment variables or system settings might interfere with Python subprocesses, which Ray Tune might be using. Ensure there are no conflicting settings.

3. **Update Packages:** Make sure all related packages are up-to-date, as there might be fixes in newer versions that resolve this issue.

If the problem persists, consider opening an issue on the [Ultralytics YOLOv8 GitHub page](https://github.com/ultralytics/ultralytics/issues) with detailed error logs and system information for further assistance. Also, since you're willing to submit a PR, you might want to look into the interaction between Ray Tune and the system subprocess calls in the YOLOv8 implementation for potential fixes. Thank you for your contribution to improving YOLOv8! 🚀

**Comment by QuodFinis** [comment]
I get a similar error when attempting to use ray tune in the exact same way on my own dataset with up to date ultralytics and python 3.11


Traceback (most recent call last):
  File "..\\site-packages\ray\air\execution\_internal\event_manager.py", line 110, in resolve_future
    result = ray.get(future)

  File "..\\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)

  File "..\\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)

  File "..\\site-packages\ray\_private\worker.py", line 2661, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
        
  File "..\\site-packages\ray\_private\worker.py", line 871, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OSError): ray::ImplicitFunc.train() (pid=17128, ip=127.0.0.1, actor_id=ca25258958a54455ced86f8d01000000, repr=_tune)
  File "python\ray\_raylet.pyx", line 1858, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1799, in ray._raylet.execute_task.function_executor
  File "..\\site-packages\ray\_private\function_manager.py", line 691, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)

  File "..\\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)

  File "..\\site-packages\ray\tune\trainable\trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "..\\site-packages\ray\air\_internal\util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
   
  File "..\\site-packages\ray\tune\trainable\function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),

  File "..\\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)

  File "..\\site-packages\ray\tune\trainable\function_trainable.py", line 250, in _trainable_func
    output = fn()

  File "..\\site-packages\ultralytics\utils\tuner.py", line 103, in _tune
    results = model_to_train.train(**config)
 
  File "..\\site-packages\ultralytics\engine\model.py", line 803, in train
    self.trainer.train()
  File "..\\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "..\\site-packages\ultralytics\engine\trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "..\\site-packages\ultralytics\engine\trainer.py", line 291, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=LOCAL_RANK, mode="train")

  File "..\\site-packages\ultralytics\models\yolo\detect\train.py", line 55, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader

  File "..\\site-packages\ultralytics\data\build.py", line 135, in build_dataloader
    return InfiniteDataLoader(

  File "..\\site-packages\ultralytics\data\build.py", line 39, in __init__
    self.iterator = super().__iter__()
       
  File "..\\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()

  File "..\\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)

  File "..\\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "..\\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
     
  File "..\\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "..\\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)

  File "..\\multiprocessing\popen_spawn_win32.py", line 74, in __init__
    hp, ht, pid, tid = _winapi.CreateProcess(

OSError: [WinError 87] The parameter is incorrect

**Comment by glenn-jocher** [comment]
@QuodFinis it seems you're encountering a parameter error with Ray Tune on Windows. This might be related to multiprocessing issues. Try setting the `num_workers` to 0 in your data loader configuration to see if it resolves the issue. If the problem persists, consider checking for compatibility updates or reaching out to the Ray community for further assistance.
