### ISSUE TITLE
Changing the feature extractor

### ISSUE THREAD

**Issue by MuhabHariri** [ultralytics/ultralytics#13243]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello,

When I try to change the backbone, I get the following error:
```
(objectdetection) C:\Users\muh\ultralytics_modified>yolo train data=coco8.yaml model=ultralytics/cfg/models/v8/yolov8.yaml epochs=2 lr0=0.01
WARNING  no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1       232  ultralytics.nn.modules.conv.Conv             [3, 8, 3, 2]
Traceback (most recent call last):
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\muh\anaconda3\envs\objectdetection\Scripts\yolo.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\ultralytics\cfg\__init__.py", line 420, in entrypoint
    model = YOLO(model, task=task)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\ultralytics\engine\model.py", line 95, in __init__
    self._new(model, task)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\ultralytics\engine\model.py", line 131, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\ultralytics\nn\tasks.py", line 232, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\ultralytics\nn\tasks.py", line 678, in parse_model
    m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
KeyError: 'Bottleneckblock'
```

Here are more details: 
I have edited the backbone in ultralytics\cfg\models\v8\yolov8 to be like this:

```
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [32, 3, 2]] # Initial Conv Layer, Output: 320x320x32
  - [-1, 1, Bottleneckblock, [16, 1, 1]] # Bottleneck 1, Output: 320x320x16
  - [-1, 1, Bottleneckblock, [24, 6, 2]] # Bottleneck 2, Output: 160x160x24
  - [-1, 1, Bottleneckblock, [24, 6, 1]] # Bottleneck 3, Output: 160x160x24
  - [-1, 1, Bottleneckblock, [32, 6, 2]] # Bottleneck 4, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 6, 1]] # Bottleneck 5, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 6, 1]] # Bottleneck 6, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [64, 6, 2]] # Bottleneck 7, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 6, 1]] # Bottleneck 8, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 6, 1]] # Bottleneck 9, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 6, 1]] # Bottleneck 10, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [96, 6, 1]] # Bottleneck 11, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 6, 1]] # Bottleneck 12, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 6, 1]] # Bottleneck 13, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [160, 6, 2]] # Bottleneck 14, Output: 20x20x160
  - [-1, 1, Bottleneckblock, [160, 6, 1]] # Bottleneck 15, Output: 20x20x160
  - [-1, 1, Bottleneckblock, [160, 6, 1]] # Bottleneck 16, Output: 20x20x160
  - [-1, 1, Bottleneckblock, [320, 6, 1]] # Bottleneck 17, Output: 20x20x320
  - [-1, 1, Conv, [1280, 1, 1]] # Final Conv Layer, Output: 20x20x1280
  - [6, 1, Conv, [256, 1, 1]] # Adjust dimension: 80x80x256
  - [13, 1, Conv, [512, 1, 1]] # Adjust dimension: 40x40x512
  - [17, 1, Conv, [512, 1, 1]] # Adjust dimension: 20x20x512
```

Additionally, I added the function Bottleneckblock to the ultralytics\nn\modules\block script and imported the function Bottleneckblock in ultralytics\nn\tasks.

here is how the function Bottleneckblock looks like inside ultralytics\nn\modules\block :

```
class Bottleneckblock(nn.Module):
    def __init__(self, in_channels, out_channels, expansion_factor, stride):
        super(Bottleneckblock, self).__init__()
        self.stride = stride
        hidden_dim = in_channels * expansion_factor
        self.use_residual = self.stride == 1 and in_channels == out_channels

        self.expand_conv = nn.Conv2d(in_channels, hidden_dim, kernel_size=1, padding=0, bias=False)
        self.bn1 = nn.BatchNorm2d(hidden_dim)
        self.relu = nn.ReLU6(inplace=True)

        self.depthwise_conv = nn.Conv2d(hidden_dim, hidden_dim, kernel_size=3, stride=stride, padding=1, groups=hidden_dim, bias=False)
        self.bn2 = nn.BatchNorm2d(hidden_dim)

        self.project_conv = nn.Conv2d(hidden_dim, out_channels, kernel_size=1, padding=0, bias=False)
        self.bn3 = nn.BatchNorm2d(out_channels)
    
    def forward(self, x):
        out = self.expand_conv(x)
        out = self.bn1(out)
        out = self.relu(out)
        
        out = self.depthwise_conv(out)
        out = self.bn2(out)
        out = self.relu(out)
        
        out = self.project_conv(out)
        out = self.bn3(out)
        
        if self.use_residual:
            out = x + out
        return out
```

Why doesn't the algorithm recognize "Bottleneckblock"?
I would appreciate any help to solve this problem.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello,

It looks like the issue arises from the model configuration not recognizing the custom `Bottleneckblock` class. Ensure that the `Bottleneckblock` is correctly imported and accessible in the context where your model configuration is parsed.

Here are a few steps you can take to troubleshoot and resolve the issue:
1. **Verify Import:** Ensure that the `Bottleneckblock` class is imported into the script where the model configuration is parsed. This might typically be in your `tasks.py` or wherever the `parse_model()` function is called.
2. **Check Class Registration:** If you are dynamically loading classes (like with `globals()`), ensure that `Bottleneckblock` is registered correctly in the global namespace.
3. **Module Initialization:** Double-check the initialization parameters and ensure they match the expected inputs in your model configuration.

If the problem persists, consider providing a minimal reproducible example in a new issue to get more specific guidance.

**Comment by MuhabHariri** [comment]
Thank you for your response. I solved the problem but encountered a different and unexpected issue. I modified the yolov8.yaml file to be like this:

```

# YOLOv8.0n backbone
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [32, 3, 2]] # Initial Conv Layer, Output: 320x320x32
  - [-1, 1, Bottleneckblock, [32, 16, 1, 1]] # Bottleneck 1, Output: 320x320x16
  - [-1, 1, Bottleneckblock, [16, 24, 6, 2]] # Bottleneck 2, Output: 160x160x24
  - [-1, 1, Bottleneckblock, [24, 24, 6, 1]] # Bottleneck 3, Output: 160x160x24
  - [-1, 1, Bottleneckblock, [24, 32, 6, 2]] # Bottleneck 4, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 32, 6, 1]] # Bottleneck 5, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 32, 6, 1]] # Bottleneck 6, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 64, 6, 2]] # Bottleneck 7, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 64, 6, 1]] # Bottleneck 8, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 64, 6, 1]] # Bottleneck 9, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 64, 6, 1]] # Bottleneck 10, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 96, 6, 1]] # Bottleneck 11, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 96, 6, 1]] # Bottleneck 12, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 96, 6, 1]] # Bottleneck 13, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 160, 6, 2]] # Bottleneck 14, Output: 20x20x160
  - [-1, 1, Bottleneckblock, [160, 160, 6, 1]] # Bottleneck 15, Output: 80x20x160
  - [-1, 1, Bottleneckblock, [160, 160, 6, 1]] # Bottleneck 16, Output: 40x20x160
  - [-1, 1, Bottleneckblock, [160, 320, 6, 1]] # Bottleneck 17, Output: 20x20x320
  - [-1, 1, Conv, [1280, 1, 1]] # Final Conv Layer, Output: 20x20x1280
  - [6, 1, Conv, [256, 1, 1]] # Adjust dimension: 80x80x256
  - [13, 1, Conv, [512, 1, 1]] # Adjust dimension: 40x40x512
  - [17, 1, Conv, [512, 1, 1]] # Adjust dimension: 20x20x512


# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]   # Upsample 20x20x512 to 40x40x512
  - [[-1, 20], 1, Concat, [1]]                # Concatenate with adjusted 40x40x512 feature map from backbone
  - [-1, 3, C2f, [512]]                       # Adjusted feature map, Output: 40x40x512

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]   # Upsample 40x40x512 to 80x80x512
  - [[-1, 19], 1, Concat, [1]]                # Concatenate with adjusted 80x80x256 feature map from backbone
  - [-1, 3, C2f, [256]]                       # Adjusted feature map, Output: 80x80x256

  - [-1, 1, Conv, [256, 3, 2]]                # Downsample 80x80x256 to 40x40x256
  - [[-1, 24], 1, Concat, [1]]                # Concatenate with adjusted 40x40x512 feature map from previous layers
  - [-1, 3, C2f, [512]]                       # Adjusted feature map, Output: 40x40x512

  - [-1, 1, Conv, [512, 3, 2]]                # Downsample 40x40x512 to 20x20x512
  - [[-1, 21], 1, Concat, [1]]                # Concatenate with adjusted 20x20x512 feature map from previous layers
  - [-1, 3, C2f, [512]]                       # Adjusted feature map, Output: 20x20x512

  - [[27, 30, 33], 1, Detect, [nc]]            # Detect head, using the 3 scales of feature maps

```

Additionally, I added the Bottleneckblock to the \ultralytics\ultralytics\nn\modules\block script. Here is how Bottleneckblock looks:


```

class Bottleneckblock(nn.Module):
    """Bottleneck layer used in MobileNetV2."""

    def __init__(self, in_channels, out_channels, expansion_factor, stride, from_=None, num_repeats=None):
        super(Bottleneckblock, self).__init__()
        self.stride = stride
        hidden_dim = in_channels * expansion_factor
        self.use_residual = self.stride == 1 and in_channels == out_channels

        self.expand_conv = nn.Conv2d(in_channels, hidden_dim, kernel_size=1, padding=0, bias=False)
        self.bn1 = nn.BatchNorm2d(hidden_dim)
        self.relu = nn.ReLU6(inplace=True)

        self.depthwise_conv = nn.Conv2d(hidden_dim, hidden_dim, kernel_size=3, stride=stride, padding=1,  groups=hidden_dim, bias=False)
        self.bn2 = nn.BatchNorm2d(hidden_dim)

        self.project_conv = nn.Conv2d(hidden_dim, out_channels, kernel_size=1, padding=0, bias=False)
        self.bn3 = nn.BatchNorm2d(out_channels)
    
    def forward(self, x):
        print(f"Input size: {x.size()}")
        out = self.expand_conv(x)
        print(f"After expand_conv: {out.size()}")
        out = self.bn1(out)
        print(f"After bn1: {out.size()}")
        out = self.relu(out)

        out = self.depthwise_conv(out)
        print(f"After depthwise_conv: {out.size()}")
        out = self.bn2(out)
        print(f"After bn2: {out.size()}")
        out = self.relu(out)

        out = self.project_conv(out)
        print(f"After project_conv: {out.size()}")
        out = self.bn3(out)
        print(f"After bn3: {out.size()}")

        if self.use_residual:
            out = x + out
        return out
```
        

However, after running the code:

I get this error:
```

(objectdetection) C:\Users\muh\ultralytics>yolo train data=coco8.yaml model=ultralytics/cfg/models/v8/yolov8.yaml epochs=2 lr0=0.01
WARNING ⚠️ no model scale passed. Assuming scale='n'.
Input size: torch.Size([1, 8, 128, 128])
After expand_conv: torch.Size([1, 8, 128, 128])
After bn1: torch.Size([1, 8, 128, 128])
After depthwise_conv: torch.Size([1, 8, 8, 8])
After bn2: torch.Size([1, 8, 8, 8])
After project_conv: torch.Size([1, 8, 8, 8])
After bn3: torch.Size([1, 8, 8, 8])
Input size: torch.Size([1, 8, 8, 8])
After expand_conv: torch.Size([1, 8, 8, 8])
After bn1: torch.Size([1, 8, 8, 8])
After depthwise_conv: torch.Size([1, 8, 1, 1])
Traceback (most recent call last):
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\muh\anaconda3\envs\objectdetection\Scripts\yolo.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "C:\Users\muh\ultralytics\ultralytics\cfg\__init__.py", line 556, in entrypoint
    model = YOLO(model, task=task)
  File "C:\Users\muh\ultralytics\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\muh\ultralytics\ultralytics\engine\model.py", line 150, in __init__
    self._new(model, task=task, verbose=verbose)
  File "C:\Users\muh\ultralytics\ultralytics\engine\model.py", line 219, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 298, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 297, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 90, in forward
    return self.predict(x, *args, **kwargs)
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 108, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 129, in _predict_once
    x = m(x)  # run
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\muh\ultralytics\ultralytics\nn\modules\block.py", line 75, in forward
    out = self.bn2(out)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\batchnorm.py", line 175, in forward
    return F.batch_norm(
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\functional.py", line 2507, in batch_norm
    _verify_batch_size(input.size())
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\functional.py", line 2475, in _verify_batch_size
    raise ValueError(f"Expected more than 1 value per channel when training, got input size {size}")
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 8, 1, 1])

```

I noticed that the input size becomes torch.Size([1, 8, 128, 128]). Shouldn't it be 640x640x3? I tried to add argument to previous code (imgsz=640) but get same error. I would appreciate any help to solve this problem.

**Comment by glenn-jocher** [comment]
Hello,

Great to hear you resolved the initial issue! Regarding the new error, it seems like the spatial dimensions of your feature maps are reducing too quickly due to the stride settings in your `Bottleneckblock` layers. This is causing the dimensions to become too small for batch normalization to process, which expects at least a size of 2 in each spatial dimension when training.

Here are a few suggestions to address this:

1. **Adjust Stride:** Review the stride parameters in your `Bottleneckblock` definitions. A stride of 2 will halve the dimensions of the feature map at each layer where it's applied. You might want to apply this less frequently or adjust the order of layers to maintain larger spatial dimensions deeper into the network.

2. **Layer Placement:** Ensure that downsampling (using stride > 1) isn't applied too early or too frequently in the network, which can rapidly reduce the spatial dimensions of the feature maps.

3. **Debugging Output:** It's good practice to print out the shape of the tensors at various points in your network (as you've done). This can help you understand how each layer transforms its input, and why you might be running into size issues.

4. **Input Size:** The initial input size should indeed match the expected size of the images your model is designed to process (e.g., 640x640x3). Ensure that the input size is correctly set at the beginning of your network and that no layer is unintentionally altering it in an undesired way.

If these adjustments don't resolve the issue, you might consider simplifying your model to identify exactly which layer configuration is causing the problem, and then gradually reintroduce complexity while monitoring the tensor sizes.

Keep up the great work, and don't hesitate to reach out if you have more questions! 🚀

**Comment by MuhabHariri** [comment]
Thank you for your reply.

In fact, the problem is that the input to the model is 256x256x3 instead of 640x640x3, which is very strange because I didn't edit any script in the repository. So, I didn't mistakenly change the input size. I tried deleting the repository and downloading it again, but I encountered the same problem where the input is 256x256x3. Please check the error and focus on the output of the first layer in the YAML file:

```
(objectdetection) C:\Users\muh\ultralytics>yolo train data=coco8.yaml model=ultralytics/cfg/models/v8/yolov8.yaml epochs=2 lr0=0.01
WARNING ⚠️ no model scale passed. Assuming scale='n'.
Input shape: torch.Size([1, 3, 256, 256])
Before initial_conv: torch.Size([1, 3, 256, 256])
After initial_conv: torch.Size([1, 32, 128, 128])
Input size: torch.Size([1, 32, 128, 128])
Traceback (most recent call last):
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\muh\anaconda3\envs\objectdetection\Scripts\yolo.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "C:\Users\muh\ultralytics\ultralytics\cfg\__init__.py", line 556, in entrypoint
    model = YOLO(model, task=task)
  File "C:\Users\muh\ultralytics\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\muh\ultralytics\ultralytics\engine\model.py", line 150, in __init__
    self._new(model, task=task, verbose=verbose)
  File "C:\Users\muh\ultralytics\ultralytics\engine\model.py", line 219, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 300, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 299, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 92, in forward
    return self.predict(x, *args, **kwargs)
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 110, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "C:\Users\muh\ultralytics\ultralytics\nn\tasks.py", line 131, in _predict_once
    x = m(x)  # run
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\muh\ultralytics\ultralytics\nn\modules\block.py", line 65, in forward
    out = self.expand_conv(x)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\muh\anaconda3\envs\objectdetection\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [48, 3, 1, 1], expected input[1, 32, 128, 128] to have 3 channels, but got 32 channels instead
```

Here is the ymal file:

```
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, ConvMobileNetV2, [3, 32, 3, 2]] # Initial Conv Layer, Output: 320x320x32
  - [-1, 1, Bottleneckblock, [32, 16, 1, 1]] # Bottleneck 1, Output: 320x320x16
  - [-1, 1, Bottleneckblock, [16, 24, 6, 2]] # Bottleneck 2, Output: 160x160x24
  - [-1, 1, Bottleneckblock, [24, 24, 6, 1]] # Bottleneck 3, Output: 160x160x24
  - [-1, 1, Bottleneckblock, [24, 32, 6, 2]] # Bottleneck 4, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 32, 6, 1]] # Bottleneck 5, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 32, 6, 1]] # Bottleneck 6, Output: 80x80x32
  - [-1, 1, Bottleneckblock, [32, 64, 6, 2]] # Bottleneck 7, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 64, 6, 1]] # Bottleneck 8, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 64, 6, 1]] # Bottleneck 9, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 64, 6, 1]] # Bottleneck 10, Output: 40x40x64
  - [-1, 1, Bottleneckblock, [64, 96, 6, 1]] # Bottleneck 11, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 96, 6, 1]] # Bottleneck 12, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 96, 6, 1]] # Bottleneck 13, Output: 40x40x96
  - [-1, 1, Bottleneckblock, [96, 160, 6, 2]] # Bottleneck 14, Output: 20x20x160
  - [-1, 1, Bottleneckblock, [160, 160, 6, 1]] # Bottleneck 15, Output: 80x20x160
  - [-1, 1, Bottleneckblock, [160, 160, 6, 1]] # Bottleneck 16, Output: 40x20x160
  - [-1, 1, Bottleneckblock, [160, 320, 6, 1]] # Bottleneck 17, Output: 20x20x320
  - [-1, 1, ConvMobileNetV2, [320, 1280, 1, 1]] # Final Conv Layer, Output: 20x20x1280
  - [6, 1, ConvMobileNetV2, [32, 256, 1, 1]] # Adjust dimension: 80x80x256
  - [13, 1, ConvMobileNetV2, [96, 512, 1, 1]] # Adjust dimension: 40x40x512
  - [17, 1, ConvMobileNetV2, [320, 512, 1, 1]] # Adjust dimension: 20x20x512
```

And here is the block of ConvMobileNetV2:


```
class ConvMobileNetV2(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        super(ConvMobileNetV2, self).__init__()
        
        # Initial Convolutional Layer
        self.initial_conv = nn.Sequential(
            nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU6(inplace=True)
        )

    def forward(self, x):
        print("Input shape:", x.shape)
        
        # Initial Convolutional Layer
        print("Before initial_conv:", x.shape)
        x = self.initial_conv(x)
        print("After initial_conv:", x.shape)
        
        return x
```

Could you please tell me why the model takes an input of 256x256x3 rather than 640x640x3? Are there any layers that work before the backbone?

Thanks for your help

**Comment by glenn-jocher** [comment]
@MuhabHariri hello,

Thank you for providing detailed information about the issue you're encountering.

It seems like the model is receiving an unexpected input size due to a possible misconfiguration or default setting in your setup. Here are a few steps to help resolve this:

1. **Check Data Configuration**: Ensure that the `imgsz` parameter in your `coco8.yaml` data configuration file is set to `640`. This parameter directly influences the input size for training.

2. **Inspect Default Settings**: Sometimes, default settings in the training script or the model configuration might override the expected input size. Verify if there are any hardcoded values or default parameters that set the input size to `256x256`.

3. **Review Model Initialization**: Before the training starts, check how the model is initialized in your script. Ensure that the input size passed to the model during initialization matches `640x640`.

4. **Debugging Output**: Add print statements at the beginning of the training script to confirm the input size right before it's passed to the model. This can help identify where the size might be getting altered.

If these steps do not resolve the issue, it might be helpful to manually set the input size in your training command as a temporary workaround:

```bash
yolo train data=coco8.yaml model=ultralytics/cfg/models/v8/yolov8.yaml epochs=2 lr0=0.01 imgsz=640
```

Please try these suggestions and let me know if the problem persists. We're here to help! 😊
