### ISSUE TITLE
Error when using track task

### ISSUE THREAD

**Issue by Drosscend** [ultralytics/ultralytics#1328]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Other

### Bug

Hello everyone,
I want to use the tracking proposed by yolov8 and I get an error during this attempt

Here is the error:
```
requirements: YOLOv8 requirement "lap" not found, attempting AutoUpdate...
  error: subprocess-exited-with-error

  × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Partial import of lap during the build process.
      C:\Users\user\AppData\Local\Temp\pip-install-sgqy8emk\lap_89774f47aeab407cb3f1c1646bd0f43f\setup.py:223: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        from numpy.distutils.core import setup
      Generating cython files
      running install
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "lap._lapjv" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\lap
      copying lap\lapmod.py -> build\lib.win-amd64-3.9\lap
      copying lap\__init__.py -> build\lib.win-amd64-3.9\lap
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1077] : testing flags (/O2)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\user\AppData\Local\Temp\pip-install-sgqy8emk\lap_89774f47aeab407cb3f1c1646bd0f43f\build\temp.win-amd64-3.9\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the 'C:\Users\user\Downloads\test\test\Scripts\python.exe -m pip install --upgrade pip' command.
requirements:  Command 'pip install "lap"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Downloads\test\test\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 317, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\yolo\engine\model.py", line 224, in track
    from ultralytics.tracker import register_tracker
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\__init__.py", line 3, in <module>
    from .track import register_tracker
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\track.py", line 10, in <module>
    from .trackers import BOTSORT, BYTETracker
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\trackers\__init__.py", line 3, in <module>
    from .bot_sort import BOTSORT
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\trackers\bot_sort.py", line 7, in <module>
    from ..utils import matching
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\utils\matching.py", line 3, in <module>
    import lap
ModuleNotFoundError: No module named 'lap'
```

### Environment

- Ultralytics YOLOv8.0.51  Python-3.9.13 torch-1.13.1+cpu CPU
- Setup complete  (8 CPUs, 7.8 GB RAM, 135.5/475.9 GB disk)
- Windows 11 22H2

### Minimal Reproducible Example

What I did:
```bash
py -m venv test
.\test\Scripts\activate
pip install ultralytics
yolo segment predict model=yolov8n-seg.pt source=0 show=true # work
yolo track model=yolov8n-seg.pt source=0 show=true # error
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Drosscend thanks for the bug report! `lap` is a track matching package dependency that tracking requires. It looks like there's some conflict with numpy and setuptools. 

I would raise an issue directly on their repo at https://github.com/gatagat/lap

Also you might want to try one of our verified environments above where tracking is tested and working correctly.

**Comment by glenn-jocher** [comment]
@Laughing-q would be nice to remove `lap` dependency due to these sorts of issues. I'll try to do some more tests.

**Comment by Drosscend** [comment]
Thanks for your quick answer, I indeed observed that the problem came from lap and numpy, so I looked on the lap github but the last activity is a while ago :/
I will see if I can use one of these environments but it would not be ideal for the project I want to do.
I'm still available for testing

**Comment by glenn-jocher** [comment]
@Drosscend one option is to try replacing lap with the built-in scipy lap function. We have a TODO to explore this here. You could try this and let us know if this works well for you:

https://github.com/ultralytics/ultralytics/blob/790f9c067c9a3548acf7c6925cea14de9ad77787/ultralytics/tracker/utils/matching.py#L39-L52

This is the only usage of `lap` in all places in the repo.

**Comment by Drosscend** [comment]
I'll see what I can do thanks!

**Comment by Drosscend** [comment]
Here is what I have currently achieved:

```python
def linear_assignment(cost_matrix, thresh):
    if cost_matrix.size == 0:
        return np.empty((0, 2), dtype=int), tuple(range(cost_matrix.shape[0])), tuple(range(cost_matrix.shape[1]))
    matches, unmatched_a, unmatched_b = [], [], []

    #transform matrix to biadjacency_matrix
    biadjacency_matrix = scipy.sparse.coo_matrix(cost_matrix)

    # Use scipy.sparse.csgraph.min_weight_full_bipartite_matching(biadjacency_matrix, maximize=False) from SciPy instead of lap.lapjv
    x, y = scipy.sparse.csgraph.min_weight_full_bipartite_matching(biadjacency_matrix, maximize=True)

    matches.extend([ix, mx] for ix, mx in enumerate(x) if mx >= 0)
    unmatched_a = np.where(x < 0)[0]
    unmatched_b = np.where(y < 0)[0]
    matches = np.asarray(matches)

    return matches, unmatched_a, unmatched_b
```

This works perfectly with an image :
yolo track model=yolov8n.pt source=zidane.jpg show=true
![image](https://user-images.githubusercontent.com/47970260/223843376-05d45816-139f-42d9-8902-9a7851b54e4b.png)

But with a video :
![image](https://user-images.githubusercontent.com/47970260/223843654-560fe1c7-4046-4143-aab4-d5157b38ea02.png)
(People exchange ids)

And every once in a while I get this mistake:
```
Traceback (most recent call last):
  File "C:\Dev\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Dev\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python\test\test\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "E:\Python\test\test\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 317, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "E:\Python\test\test\lib\site-packages\ultralytics\yolo\engine\model.py", line 230, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "E:\Python\test\test\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\Python\test\test\lib\site-packages\ultralytics\yolo\engine\model.py", line 221, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "E:\Python\test\test\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 114, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "E:\Python\test\test\lib\site-packages\torch\autograd\grad_mode.py", line 64, in generator_context
    response = gen.send(request)
  File "E:\Python\test\test\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 177, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "E:\Python\test\test\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 267, in run_callbacks
    callback(self)
  File "E:\Python\test\test\lib\site-packages\ultralytics\tracker\track.py", line 35, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  File "E:\Python\test\test\lib\site-packages\ultralytics\tracker\trackers\byte_tracker.py", line 220, in update
    det = detections[idet]
IndexError: list index out of range
```

**Comment by glenn-jocher** [comment]
@Drosscend I've tried to implement a replacement in #1332 using scipy. Anecdotal results on my webcam seem to show it working correctly and the speed is faster after the first frame (scipy linear assignment seems to maybe do some jit compiling before first usage which takes maybe 100ms).

@Laughing-q is there a statistical way we can compare #1332 with main, i.e. how can we return tracking validation to see if this change is reducing accuracy or maintaining it?

**Comment by Drosscend** [comment]
I also tested with my camera, by passing an object in front of it this same object gets my id and I lose mine but a few milliseconds later I get my id back but the object does not have it anymore

**Comment by Laughing-q** [comment]
@glenn-jocher @Drosscend I used a script to test if the two ways are producing the same matching results:
```python
import lap
from scipy.optimize import linear_sum_assignment
import numpy as np


test_round = 10

def linear_assignment_(cost_matrix, use_lap=True, thresh=0.0):
    if use_lap:
        _, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)
        return np.array([[y[i], i] for i in x if i >= 0])  #
    else:
        # try scipy implementation
        x, y = linear_sum_assignment(cost_matrix)
        return np.array(list(zip(x, y)))
        # return np.asarray([[i, x] for i, x in enumerate(x) if cost_matrix[i, x] < thresh])


for i in range(test_round):
    cost_matrix = np.random.rand(5, 6)
    results = []
    for thresh in np.arange(start=0.1, stop=1, step=0.1):
        lap_result = linear_assignment_(cost_matrix, use_lap=True, thresh=thresh)
        scipy_result = linear_assignment_(cost_matrix, use_lap=False, thresh=thresh)
        if lap_result.shape == scipy_result.shape:
            results.append((lap_result == scipy_result).all())
        else:
            results.append(False)
    print(results)
```
if we can find a way to make sure all the prints are `True` then we can replace `lap` by `scipy`.
refer to: [https://github.com/abewley/sort/blob/da0fe4d20ff3ca1c7bad3f746fa79e3c97421bf2/sort.py#L36-L44](https://github.com/abewley/sort/blob/da0fe4d20ff3ca1c7bad3f746fa79e3c97421bf2/sort.py#L36-L44)

**Comment by Drosscend** [comment]
I have made some changes, can you test this new code @Laughing-q 
```python
def linear_assignment(cost_matrix, thresh):
    if cost_matrix.size == 0:
        return np.empty((0, 2), dtype=int), tuple(range(cost_matrix.shape[0])), tuple(range(cost_matrix.shape[1]))
    matches, unmatched_a, unmatched_b = [], [], []

    cost_matrix[cost_matrix > thresh] = thresh + 1e-5
    indices = linear_sum_assignment(cost_matrix)
    for row, col in zip(*indices):
        if cost_matrix[row, col] > thresh:
            unmatched_a.append(row)
            unmatched_b.append(col)
        else:
            matches.append((row, col))

    return matches, unmatched_a, unmatched_b
```

**Comment by Laughing-q** [comment]
@Drosscend the result still looks different:
```python
import lap
from scipy.optimize import linear_sum_assignment
import numpy as np

test_round = 10

def compare_array(a, b):
    if a.shape == b.shape:
        return (a == b).all()
    else:
        return False

def linear_assignment_lap(cost_matrix, thresh=0.0):
    if cost_matrix.size == 0:
        return (
            np.empty((0, 2), dtype=int),
            tuple(range(cost_matrix.shape[0])),
            tuple(range(cost_matrix.shape[1])),
        )
    matches, unmatched_a, unmatched_b = [], [], []

    # TODO: investigate scipy.optimize.linear_sum_assignment() for lap.lapjv()
    _, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)

    matches.extend([ix, mx] for ix, mx in enumerate(x) if mx >= 0)
    unmatched_a = np.where(x < 0)[0]
    unmatched_b = np.where(y < 0)[0]
    matches = np.asarray(matches)
    return matches, unmatched_a, unmatched_b

def linear_assignment_scipy(cost_matrix, thresh):
    if cost_matrix.size == 0:
        return np.empty((0, 2), dtype=int), tuple(range(cost_matrix.shape[0])), tuple(range(cost_matrix.shape[1]))
    matches, unmatched_a, unmatched_b = [], [], []

    cost_matrix[cost_matrix > thresh] = thresh + 1e-5
    indices = linear_sum_assignment(cost_matrix)
    for row, col in zip(*indices):
        if cost_matrix[row, col] > thresh:
            unmatched_a.append(row)
            unmatched_b.append(col)
        else:
            matches.append((row, col))

    return np.asarray(matches), np.asarray(unmatched_a), np.asarray(unmatched_b)

for i in range(test_round):
    cost_matrix = np.random.random((5, 6))
    results = []
    for thresh in np.arange(start=0.1, stop=1, step=0.1):
        # print(f"-------{thresh}---------")
        match_lap, unmatch_a_lap, unmatch_b_lap = linear_assignment_lap(cost_matrix, thresh=thresh)
        match_scipy, unmatch_a_scipy, unmatch_b_scipy = linear_assignment_scipy(cost_matrix, thresh=thresh)
        results.append(
            all(
                [
                    compare_array(match_lap, match_scipy),
                    compare_array(unmatch_a_lap, unmatch_a_scipy),
                    compare_array(unmatch_b_lap, unmatch_b_scipy),
                ]
            )
        )
    print(results)
```
```bash
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False]
```

**Comment by Lihi-Gur-Arie** [comment]
@glenn-jocher @Drosscend @luislortega @Laughing-q

Hi guys,

Today I tried the Tracker and encountered the same bug. I attempted to use Scipy's 'linear_sum_assignment', but the performance was not satisfactory. Finally, I solved the issue by installing **numpy==1.18.5** on **Python 3.8**:

1. pip install numpy==1.18.5
2. pip install ultralytics

Now it works fine!

**Comment by Lihi-Gur-Arie** [comment]
@Drosscend
I'm using Python 3.8.10

**Comment by Samyarrahimi** [comment]
Hi @Drosscend,

I am using python 3.8.10 too and I encountered the same bug. did it work for you with python 3.8.10?

**Comment by Drosscend** [comment]
Hi @Samyarrahimi,
I will test this but I think the problem is that I don't have the necessary Microsoft Tools

**Comment by Lihi-Gur-Arie** [comment]
@Drosscend @Samyarrahim

I'm using linux, Ubuntu 20.04.
It didn't work for me on python 3.9, but it works on 3.8.10.
Good luck

**Comment by Drosscend** [comment]
@Lihi-Gur-Arie, @Samyarrahimi 
So the problem seems to be on windows only and is a problem with a version of Microsoft Tools

**Comment by s4ifbn** [comment]
thank u @Lihi-Gur-Arie Python 3.8 works for me, on Apple m1, macos Ventura
it wasn't working with python 3.10, 3.11

**Comment by shivag** [comment]
I had the same problem. 

I installed cython, then lap directly (per below at https://github.com/gatagat/lap) and it works. 

<img width="939" alt="Screenshot 2023-03-28 at 7 14 21 PM" src="https://user-images.githubusercontent.com/249378/228408867-993d23d8-1827-46e7-b0d7-bdbf1b2f82f7.png">

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. It's great to hear that installing cython and lap directly resolved the issue for you. If other users encounter the same problem, they can try following your steps to see if it works for them as well. If you have any other questions or concerns, please don't hesitate to ask. Additionally, you might find helpful resources at https://docs.ultralytics.com for further information on using YOLOv8.

**Comment by mehmet-engineer** [comment]
This worked for me:
``` conda install -c conda-forge lap ```

**Comment by glenn-jocher** [comment]
@mehmet-engineer installing lap via `conda-forge` is another way to resolve the issue encountered. If anyone else faces a similar issue, they can try installing lap via `conda-forge` as well. Additionally, users can find helpful resources at https://docs.ultralytics.com to learn more about YOLOv8 and its various components.

**Comment by IAlexEgorov** [comment]
I resolved it by installation package from anaconda from local:
conda install ~/Downloads/lap-0.4.0-py38h43a58ef_1004.tar.bz2

System: MacOS Ventura

**Comment by glenn-jocher** [comment]
@IAlexEgorov thank you for sharing your solution to the issue encountered. It's great to hear that you were able to install the package from conda and it resolved the issue for you. For other users experiencing similar issues, they might want to try to install the package from the local directory as well if they have one available. Additionally, users can find helpful resources and information about YOLOv8 components at https://docs.ultralytics.com/ to further their knowledge and understanding of the software.

**Comment by aasimaquatec** [comment]
@IAlexEgorov : For MacOS, 
pip install lapx
Worked for me.
