### ISSUE TITLE
Error handling metadata in validate exported coreml model

### ISSUE THREAD

**Issue by majnas** [ultralytics/ultralytics#1335]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hey :+1: 

#### I export the trained custom model in coreml and onnx format. to evaluate them I have used following codes. 
```python
from pathlib import Path
from ultralytics.yolo.cfg import get_cfg
from ultralytics.yolo.utils import DEFAULT_CFG, ROOT, SETTINGS
from ultralytics.yolo.v8 import classify, detect, segment

CFG = get_cfg(DEFAULT_CFG)
CFG.data = "/home/dev/avgit/defect_detection/code/ultralytics/T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR.yaml"
CFG.task = "detect"
CFG.mode = "val"
CFG.conf = 0.001
CFG.iou = 0.45
# CFG.half = True
# CFG.imgz = 1280*2

# Validator
model_path = '/home/dev/avgit/defect_detection/runs/Y8/POT_T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR_Y8M_i640_b8/weights/best.mlmodel'
#model_path = '/home/dev/avgit/defect_detection/runs/Y8/POT_T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR_Y8M_i640_b8/weights/best.onnx'
val = detect.DetectionValidator(args=CFG)
val(model=model_path)


```

#### When evaluating coreml I get error!

```bash
Ultralytics YOLOv8.0.51 🚀 Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3080 Laptop GPU, 7982MiB)
Loading /home/dev/avgit/defect_detection/runs/Y8/POT_T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR_Y8M_i640_b8/weights/best.mlmodel for CoreML inference...
Traceback (most recent call last):
  File "val_model.py", line 20, in <module>
    val(model=model_path)
  File "/home/dev/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dev/avgit/defect_detection/code/ultralytics/ultralytics/yolo/engine/validator.py", line 113, in __call__
    model = AutoBackend(model, device=self.device, dnn=self.args.dnn, data=self.args.data, fp16=self.args.half)
  File "/home/dev/avgit/defect_detection/code/ultralytics/ultralytics/nn/autobackend.py", line 270, in __init__
    metadata[k] = int(v)
TypeError: 32 has type int, but expected one of: bytes, unicode

```

#### When evaluating onnx it's correct.
```
Ultralytics YOLOv8.0.51 🚀 Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3080 Laptop GPU, 7982MiB)
Loading /home/dev/avgit/defect_detection/runs/Y8/POT_T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR_Y8M_i640_b8/weights/best.onnx for ONNX Runtime inference...
k names v {0: 'D40'} False True False
k imgsz v [640, 640] False True False
metadata {'names': {0: 'D40'}, 'task': 'detect', 'stride': 32, 'imgsz': [640, 640], 'batch': 1, 'version': '8.0.51', 'license': 'GPL-3.0 https://ultralytics.com/license', 'author': 'Ultralytics', 'description': 'Ultralytics best model trained on T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR.yaml'}
Forcing batch=1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning /home/dev/avgit/defect_detection/dataset/T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR/labels/test.cache... 2182 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2182/2182 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2182/2182 [01:08<00:00, 31.87it/s]
                   all       2182       2856      0.692      0.617      0.674      0.354
             non_small       2182       2137      0.681      0.726      0.773      0.415
Speed: 0.2ms preprocess, 11.9ms inference, 0.0ms loss, 0.6ms postprocess per image
Results saved to runs/detect/val34

```

#### I have changed this part of code to verbose more information
```python
        # Load external metadata YAML
        if isinstance(metadata, (str, Path)) and Path(metadata).exists():
            metadata = yaml_load(metadata)
        if metadata:
            for k, v in metadata.items():
                if k in ('stride', 'batch'):
                    metadata[k] = int(v)
                elif k in ('imgsz', 'names') and isinstance(v, str):
                    print("k", k, "v", v, isinstance(v, list), isinstance(v, str), isinstance(v, dict))
                    metadata[k] = eval(v)
            stride = metadata['stride']
            task = metadata['task']
            batch = metadata['batch']
            imgsz = metadata['imgsz']
            names = metadata['names']
            print("metadata", metadata)
            print("is names dict=", isinstance(names, dict))
        elif not (pt or triton or nn_module):
            LOGGER.warning(f"WARNING ⚠️ Metadata not found for 'model={weights}'")
```

#### This is my data file
```yaml

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
path: T2W+PP+DDC2022+SU+AV+VAN#23MX-POT-A5XR/images  # dataset root dir
train: train
val: test
test: test

# Classes
names:
  0: D40

```

### Environment

Ubuntu 22.04.1 LTS

### Additional

Also I have changed the code to give metrics for non small (area > 400 pixels) objects in this line 
```
non_small       2182       2137      0.681      0.726      0.773      0.415
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@majnas thanks for the detailed bug report! I've been updating exported model metadata and it appears CoreML was not outputting a dict like I expected, so I've fixed this in https://github.com/ultralytics/ultralytics/pull/1333/commits/18db4c75a337bcd3c22f2900ae264cc02dab3a16 which will be part of 8.0.52 today.

Please let me know if you spot any other problems, thank you!
