### ISSUE TITLE
Tensorflow GraphDef inference works once

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#13390]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

While working on #13113 I encountered an error with exported `.pb` models. If running inference in the same python session as the model was exported, inference will work fine. When reopening a new python session and attempting inference again with the exported model, an error is thrown.

### Environment

Tested on Ultralytics $\lambda$-server

```
Ultralytics YOLOv8.2.28 🚀 Python-3.10.12 torch-2.2.0+cu121 CUDA:0 (NVIDIA A100-SXM4-80GB, 81051MiB)
Setup complete ✅ (128 CPUs, 1007.7 GB RAM, 2998.3/3519.3 GB disk)

OS                  Linux-5.15.0-91-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 1007.71 GB
CPU                 AMD EPYC 7502 32-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.2.0+cu121>=1.8.0
torchvision         ✅ 0.17.0+cu121>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

## CLI 

```bash
yolo export model=yolov8n.pt format=pb
# export completes without issue

yolo predict task=detect model=yolov8n.pb source=ultralytics/assets/bus.jpg
# error is thrown
```

## Python

```py
from ultralytics import YOLO, ASSETS

im = ASSETS / "bus.jpg"
model = YOLO("yolov8n.pt")
out = model.export(format="pb")

pb_model = YOLO(out, task="detect")
result = pb_model.predict(im)

# inference once works

exit() # close python, then re-open

from ultralytics import YOLO, ASSETS

im = ASSETS / "bus.jpg"
model = YOLO("yolov8n.pb", task="detect")
result = model.predict(im)

# error thrown
```

### Additional

<details><summary>Detailed Error output</summary>
<p>

```
Ultralytics YOLOv8.2.28 🚀 Python-3.10.12 torch-2.2.0+cu121 CUDA:0 (NVIDIA A100-SXM4-80GB, 81051MiB)
Loading yolov8n.pb for TensorFlow GraphDef inference...
WARNING ⚠️ Metadata not found for 'model=yolov8n.pb'

error: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/function_type_utils.py", line 442, in bind_function_inputs
    bound_arguments = function_type.bind_with_defaults(
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/core/function/polymorphism/function_type.py", line 264, in bind_with_defaults
    bound_arguments = self.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'x'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1179, in _call_impl
    return self._call_with_structured_signature(args, kwargs)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1259, in _call_with_structured_signature
    function_type_utils.canonicalize_function_inputs(
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/function_type_utils.py", line 422, in canonicalize_function_inputs
    bound_arguments = bind_function_inputs(
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/function_type_utils.py", line 446, in bind_function_inputs
    raise TypeError(
TypeError: Binding inputs to tf.function failed due to `got an unexpected keyword argument 'x'`. Received args: () and kwargs: {'x': <tf.Tensor: shape=(1, 640, 640, 3), dtype=float32, numpy=
array([[[[    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         ...,
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706]],

        [[    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         ...,
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706]],

        [[    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         ...,
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706]],

        ...,

        [[    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         ...,
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706]],

        [[    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         ...,
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706]],

        [[    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         ...,
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706],
         [    0.44706,     0.44706,     0.44706]]]], dtype=float32)>} for signature: () -> List[TensorSpec(shape=(1, 84, 8400), dtype=tf.float32, name=None)].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/burhan/ultra_repo/.ultra/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/burhan/ultra_repo/ultralytics/ultralytics/cfg/__init__.py", line 583, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/burhan/ultra_repo/ultralytics/ultralytics/engine/model.py", line 453, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/burhan/ultra_repo/ultralytics/ultralytics/engine/predictor.py", line 177, in predict_cli
    for _ in gen:  # noqa, running CLI inference without accumulating any outputs (do not modify)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/burhan/ultra_repo/ultralytics/ultralytics/engine/predictor.py", line 248, in stream_inference
    preds = self.inference(im, *args, **kwargs)
  File "/home/burhan/ultra_repo/ultralytics/ultralytics/engine/predictor.py", line 142, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize, embed=self.args.embed, *args, **kwargs)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/burhan/ultra_repo/ultralytics/ultralytics/nn/autobackend.py", line 565, in forward
    y = self.frozen_func(x=self.tf.constant(im))
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1170, in __call__
    return self._call_impl(args, kwargs)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/wrap_function.py", line 253, in _call_impl
    return super()._call_impl(args, kwargs)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1182, in _call_impl
    return self._call_with_flat_signature(args, kwargs)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1242, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1322, in _call_flat
    return self._inference_function.call_preflattened(args)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 216, in call_preflattened
    flat_outputs = self.call_flat(*args)
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 251, in call_flat
    outputs = self._bound_context.call_function(
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 1500, in call_function
    outputs = execute.execute(
  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node PartitionedCall/model_21/tf.math.sigmoid/Sigmoid defined at (most recent call last):
  File "/home/burhan/ultra_repo/.ultra/bin/yolo", line 8, in <module>

  File "/home/burhan/ultra_repo/ultralytics/ultralytics/cfg/__init__.py", line 583, in entrypoint

  File "/home/burhan/ultra_repo/ultralytics/ultralytics/engine/model.py", line 446, in predict

  File "/home/burhan/ultra_repo/ultralytics/ultralytics/engine/predictor.py", line 297, in setup_model

  File "/home/burhan/ultra_repo/.ultra/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context

  File "/home/burhan/ultra_repo/ultralytics/ultralytics/nn/autobackend.py", line 322, in __init__

  File "/home/burhan/ultra_repo/ultralytics/ultralytics/nn/autobackend.py", line 317, in wrap_frozen_graph

JIT compilation failed.
         [[{{node PartitionedCall/model_21/tf.math.sigmoid/Sigmoid}}]] [Op:__inference_pruned_1567]
```

</p>
</details> 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
### From 13389 CI tests:

macos-14 + python-3.11 ✔️ [passes all GraphDef benchmarks](https://github.com/ultralytics/ultralytics/actions/runs/9387491195/job/25852380443?pr=13389#step:8:227)
ubuntu-latest + python-3.11 ❌ [failing at GraphDef `val` benchmark](https://github.com/ultralytics/ultralytics/actions/runs/9387491195/job/25864204316#step:8:225)

Not sure if this could mean there is a difference based on OS

**Comment by Burhan-Q** [comment]
[More evidence](https://github.com/ultralytics/ultralytics/pull/13389#issuecomment-2151289758) pointing to this being OS based. Issue observed on `Ubuntu 22.04.3 LTS` (Ultralytics $\lambda$ server) but **not** on `Pop!_OS 22.04 LTS`

```
Operating System: Ubuntu 22.04.3 LTS              
Kernel: Linux 5.15.0-91-generic
Architecture: x86-64

Operating System: Pop!_OS 22.04 LTS               
Kernel: Linux 6.6.10-76060610-generic
Architecture: x86-64
```

Ultralytics Docker container uses `Ubuntu 22.04.4 LTS` and is _not_ showing the same behavior.

**Comment by Burhan-Q** [comment]
Forcing `device='cpu'` for prediction seems to resolve this, but  **only** when using the CLI command.

```sh
yolo predict model=yolov8n.pb source=ultralytics/assets/bus.jpg  # <-- error
```
```sh
yolo predict model=yolov8n.pb source=ultralytics/assets/bus.jpg device=cpu  # <-- no error
```

When using python, it still throws an error. The problem is still _only_ on reproducible on the $\lambda$ server

```py
from ultralytics import YOLO, ASSETS

im = ASSETS / "bus.jpg"
model = YOLO("yolov8n.pb", task="detect")

result = model.predict(im)
# Throws error
result = model.predict(im, device="cpu")
# Also throws error
```
