### ISSUE TITLE
install project but can not run the train command line

### ISSUE THREAD

**Issue by xingyuezhiyun** [ultralytics/ultralytics#1340]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Detection

### Bug

in custom linux enviroment, i use pip install ultralytics , and then i use the command line 
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640 device=cpu

it doesn't work and getting wrong
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 5, in <module>
    from ultralytics.yolo.cfg import entrypoint
  File "/usr/local/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "/usr/local/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/usr/local/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/usr/local/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/usr/local/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/usr/local/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 34, in <module>
    import cv2
  File "/usr/local/lib64/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib64/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

what's the problem ?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xingyuezhiyun** [comment]
in Python 3.9.14

**Comment by pderrenger** [comment]
@xingyuezhiyun it seems like you're encountering an issue with the installation and running of the YOLOv8 train command on your custom Linux environment. The error message indicates a problem related to the "libGL.so.1" shared object file.

This error is usually associated with missing or incompatible graphics-related dependencies. To resolve this, you can try installing the "libgl1-mesa-glx" package or its equivalent on your Linux system, which should provide the necessary OpenGL libraries.

After ensuring that the required dependencies are in place, you can attempt running the train command again. If the issue persists, please let me know and we can further investigate the problem.

I hope this helps! If you need any further assistance, feel free to ask.
