### ISSUE TITLE
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'

### ISSUE THREAD

**Issue by JoaoLopesFerreira99** [ultralytics/ultralytics#13758]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Plotting labels to runs\detect\train8\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 87 weight(decay=0.0), 148 weight(decay=0.0005), 166 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train8
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/298 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\Users\JFerreira\Desktop\Models\_training\RTDETR\train.py", line 12, in <module>
    main()
  File "c:\Users\JFerreira\Desktop\Models\_training\RTDETR\train.py", line 9, in main
    results = model.train(data="C:/Users/JFerreira/Desktop/Models/_training/RTDETR/airsim.yaml", epochs=100, imgsz=640)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 674, in train
    self.trainer.train()
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\trainer.py", line 199, in train
    self._do_train(world_size)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\trainer.py", line 376, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\tasks.py", line 89, in forward
    return self.loss(x, *args, **kwargs)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\tasks.py", line 265, in loss
    self.criterion = self.init_criterion()
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\tasks.py", line 352, in init_criterion
    return v8DetectionLoss(self)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\utils\loss.py", line 159, in __init__
    self.stride = m.stride  # model strides
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'
PS C:\Users\JFerreira\Desktop\Models\_training\RTDETR> 

### Minimal Reproducible Example

import ultralytics
import torch

def main():
    # Your training setup and configurations here
    model = ultralytics.YOLO('rtdetr-l.pt')  # Initialize the model
    results = model.train(data="C:/Users/JFerreira/Desktop/Models/_training/RTDETR/airsim.yaml", epochs=100, imgsz=640)

if __name__ == '__main__':
    main()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
@JoaoLopesFerreira99 you have to use `ultralytics.RTDETR('rtdetr-l.pt')`

**Comment by nlcfdwr** [comment]
我在运行以下配置文件时遇到了错误，配置文件如下：
from ultralytics import YOLO
model = YOLO("ultralytics/cfg/models/v8/yolov8-rtdetr.yaml",task="detect")
model.train(data="/home/up/myproject/ultralytics/ultralytics/cfg/datasets/VisDrone.yaml", cfg="ultralytics/cfg/default.yaml") 
![2024-11-13 11-37-04 的屏幕截图](https://github.com/user-attachments/assets/0bbc5287-fca8-461e-876d-62d0f3220794)

**Comment by glenn-jocher** [comment]
@nlcfdwr it seems like you're using the YOLOv8 configuration for RT-DETR. Please ensure you're using the correct model and configuration files specific to RT-DETR, such as `ultralytics.RTDETR('rtdetr-l.pt')`. If the issue persists, please provide more details about the error message for further assistance.

**Comment by Nau3D** [comment]
Same problem here. Upgraded ultralytics recently (a few days ago). Have successfully  trained with YOLO V8 to V11. 

Tried to run RT_DETR with both 'l' and 'x' models using the same training code as for YOLO (changing the name of the model). It verifies the dataset, and when it starts training I get this error:

AttributeError: 'RTDETRDecoder' object has no attribute 'stride'

**Comment by james-imi** [comment]
i did this and it seems that it still gives the same error.

**Comment by glenn-jocher** [comment]
Thanks for trying that. Your traceback shows the generic YOLO loss path is still being used, which typically means an outdated or conflicting Ultralytics install. Please update to the latest Ultralytics and ensure there’s only one install on your PYTHONPATH; if it still errors, share ultralytics.__version__, the yolo checks output, and a minimal repro per the Creating a Minimal Reproducible Example guide so we can investigate further.
