### ISSUE TITLE
Tensor size mismatch with during validation

### ISSUE THREAD

**Issue by buzzysin** [ultralytics/ultralytics#1380]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation

### Bug

Similar to #897 except occurs during validation, when `save_json` and/or `save_hybrid` is set, I believe. The "bug" does not occur when these options are left unset.

```
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100     0.589G      2.114      4.271      1.431         92        512: 100%|██████████| 20/20 [00:03<00:00,  5.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/2 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\buzzysin\code-windows\y4\final-project\fyp\fyp\comet\train.py", line 77, in <module>
    main()
  File "c:\users\buzzysin\code-windows\y4\final-project\fyp\fyp\comet\train.py", line 73, in main
    train(args)
  File "c:\users\buzzysin\code-windows\y4\final-project\fyp\fyp\comet\train.py", line 47, in train
    raise e
  File "c:\users\buzzysin\code-windows\y4\final-project\fyp\fyp\comet\train.py", line 31, in train
    model.train(data=args.data,
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\ultralytics\yolo\engine\model.py", line 320, in train
    self.trainer.train()
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 186, in train
    self._do_train(RANK, world_size)
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 357, in _do_train
    self.metrics, self.fitness = self.validate()
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 453, in validate
    metrics = self.validator(self)
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\ultralytics\yolo\engine\validator.py", line 168, in __call__
    preds = self.postprocess(preds)
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\ultralytics\yolo\v8\detect\val.py", line 60, in postprocess
    preds = ops.non_max_suppression(preds,
  File "C:\Users\buzzysin\anaconda3\envs\final\lib\site-packages\ultralytics\yolo\utils\ops.py", line 212, in non_max_suppression
    x = torch.cat((x, v), 0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 8 but got size 9 for tensor number 1 in the list.
```

### Environment

- YOLO - `Ultralytics YOLOv8.0.53 Python-3.9.16 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 8192MiB)`
- OS: Windows 11 Home Version 10.0.22621 Build 22621
- Python: Conda Environment Python 3.9.16

### Minimal Reproducible Example

```py
from ultralytics import YOLO

# ... irrelevant setup code

model = YOLO(model=args.model) # yolov8n.pt

model.train(data=args.data, # custom dataset `circuits.yaml`
            epochs=args.epochs, # 100
            batch=args.batch, # 4
            imgsz=args.imgsz, # 512
            device=args.device, # 0, CUDA enabled GPU
            exist_ok=args.exist_ok, # True
            save=args.save, # True
            save_period=args.save_period, # 20
            # Offending options below
            save_json=True, # <-- here
            save_hybrid=True, # <-- and/or here
            # Other options
            project=project_name, # finalyearproject
            name=name) # baseline_v8
```

### Additional

In `ultralytics\yolo\utils\ops.py`, changing the following line (209):

![image](https://user-images.githubusercontent.com/41271986/224532507-072460dc-1c4f-4f50-bf6e-346a3fc8233f.png)

...to this:

![image](https://user-images.githubusercontent.com/41271986/224532533-d5b09d0d-5fee-4468-a1c4-98999aa86f04.png)

...based purely on assuming this:

![image](https://user-images.githubusercontent.com/41271986/224532666-d3e5870b-fb16-44b7-90af-d885c21f3103.png)

...seemed to stop the training run from crashing. I am unsure if this naive "fix" actually addresses the problem, or whether or not I've done something wrong somewhere and I'm the real problem.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@buzzysin the arguments you refer to are val arguments, not train arguments, and should not be passed during training. See https://docs.ultralytics.com/modes/train/#arguments

**Comment by buzzysin** [comment]
Got it, thanks

**Comment by pderrenger** [comment]
@buzzysin no worries! It's a common confusion. The validation arguments should be utilized during the separate validation phase. If you have any further questions or need assistance with anything else, feel free to ask!
