### ISSUE TITLE
Train with single gpu

### ISSUE THREAD

**Issue by TonightGo** [ultralytics/ultralytics#13834]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use single gpu to train model: 
`import sys
sys.path.insert(0, 'ultralytics')
import torch
import cv2
from ultralytics import YOLO

torch.set_num_threads(1)
cv2.setNumThreads(1)
NUM_THREADS = 2

import torch.multiprocessing as mp
mp.set_start_method('spawn', force=True)

model = YOLO("/content/drive/MyDrive/ultralytics/ultralytics/cfg/models/v8/test.yaml", verbose=True)
model.train(data="/content/drive/MyDrive/ultralytics/ultralytics/cfg/datasets/test.yaml", epochs=300, project='test', name='debug', device='0', imgsz=640, batch=2, exist_ok=True, workers=1, resume=False, optimizer='SGD') `

then, I encountered this error：

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/ultralytics/test/train.py", line 35, in <module>
    model.train(data="/content/drive/MyDrive/ultralytics/ultralytics/cfg/datasets/test.yaml", epochs=300, project='/content/drive/MyDrive/ultralytics/test', name='debug', device='0', imgsz=640, batch=2, exist_ok=True, workers=1, resume=False, optimizer='SGD') 
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/model.py", line 675, in train
    self.trainer.train()
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/trainer.py", line 314, in _do_train
    self._setup_train(world_size)
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/trainer.py", line 278, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
  File "/content/drive/MyDrive/ultralytics/ultralytics/models/yolo/detect/train.py", line 55, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/build.py", line 135, in build_dataloader
    return InfiniteDataLoader(
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/build.py", line 39, in __init__
    self.iterator = super().__iter__()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
val: Scanning /content/drive/MyDrive/Image/dataset/labels... 7 images, 0 backgrounds, 0 corrupt:  54% 7/13 [00:10<00:08,  1.49s/it]
Traceback (most recent call last):
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/dataset.py", line 140, in get_labels
    assert cache["hash"] == get_hash(self.label_files + self.im_files)  # identical hash
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 856, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/MyDrive/ultralytics/test/test.py", line 35, in <module>
    model.train(data="/content/drive/MyDrive/ultralytics/ultralytics/cfg/datasets/test.yaml", epochs=300, project='/content/drive/MyDrive/ultralytics/test', name='debug', device='0', imgsz=640, batch=2, exist_ok=True, workers=1, resume=False, optimizer='SGD') 
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/model.py", line 675, in train
    self.trainer.train()
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/trainer.py", line 314, in _do_train
    self._setup_train(world_size)
  File "/content/drive/MyDrive/ultralytics/ultralytics/engine/trainer.py", line 281, in _setup_train
    self.test_loader = self.get_dataloader(
  File "/content/drive/MyDrive/ultralytics/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/content/drive/MyDrive/ultralytics/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/build.py", line 87, in build_yolo_dataset
    return dataset(
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/dataset.py", line 64, in __init__
    super().__init__(*args, **kwargs)
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/base.py", line 74, in __init__
    self.labels = self.get_labels()
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/dataset.py", line 142, in get_labels
    cache, exists = self.cache_labels(cache_path), False  # run cache ops
  File "/content/drive/MyDrive/ultralytics/ultralytics/data/dataset.py", line 100, in cache_labels
    for im_file, lb, shape, segments, keypoint, nm_f, nf_f, ne_f, nc_f, msg in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 861, in next
    self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 6653) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

I debug the code, and when this code in the file "ultralytics/data/build.py" is run, it keeps creating threads in a loop until the program crashes.
![image](https://github.com/ultralytics/ultralytics/assets/20351057/a96b4955-e93b-4a9e-8513-b5490e37605d)

I wonder if it is a problem with my code or a bug in the program.

**Comment by glenn-jocher** [comment]
@TonightGo hi there,

Thank you for reaching out and providing a detailed description of the issue you're encountering. Let's work through this together.

First, to ensure we can effectively investigate and address the problem, please verify the following:

1. **Minimum Reproducible Example**: Could you provide a minimal code snippet that reproduces the issue? This helps us isolate the problem more efficiently. You can refer to our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on how to create one.

2. **Package Versions**: Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

Regarding the error you're encountering, it seems related to multiprocessing and data loading. Here are a few steps you can take to troubleshoot and potentially resolve the issue:

### Multiprocessing Setup
The error suggests an issue with the multiprocessing setup. Ensure that the multiprocessing code is protected by `if __name__ == "__main__":` to avoid issues with spawning new processes:
```python
if __name__ == "__main__":
    import sys
    sys.path.insert(0, 'ultralytics')
    import torch
    import cv2
    from ultralytics import YOLO

    torch.set_num_threads(1)
    cv2.setNumThreads(1)
    NUM_THREADS = 2

    import torch.multiprocessing as mp
    mp.set_start_method('spawn', force=True)

    model = YOLO("/content/drive/MyDrive/ultralytics/ultralytics/cfg/models/v8/test.yaml", verbose=True)
    model.train(data="/content/drive/MyDrive/ultralytics/ultralytics/cfg/datasets/test.yaml", epochs=300, project='test', name='debug', device='0', imgsz=640, batch=2, exist_ok=True, workers=1, resume=False, optimizer='SGD')
```

### DataLoader Workers
The error message suggests trying to rerun with `num_workers=0` for better error tracing. This can help identify if the issue is related to multiprocessing:
```python
model.train(data="/content/drive/MyDrive/ultralytics/ultralytics/cfg/datasets/test.yaml", epochs=300, project='test', name='debug', device='0', imgsz=640, batch=2, exist_ok=True, workers=0, resume=False, optimizer='SGD')
```

### Dataset and Cache
The assertion error in `get_labels` indicates a potential issue with the dataset cache. Try clearing the cache or ensuring that the dataset paths and annotations are correct:
```python
# Clear cache
import os
cache_path = "/content/drive/MyDrive/ultralytics/ultralytics/cfg/datasets/test.cache"
if os.path.exists(cache_path):
    os.remove(cache_path)
```

### Debugging
If the issue persists, consider running the training with a smaller dataset or fewer epochs to isolate the problem. Additionally, you can enable more verbose logging to get detailed insights into the training process.

Please try these steps and let us know if the issue persists. We're here to help!

**Comment by TonightGo** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/20351057/16f5d303-1adb-4c87-9d3f-bfff553be206)
I used the above code and it works. Thank you for your timely and effective reply.

**Comment by glenn-jocher** [comment]
Hi @TonightGo,

I'm glad to hear that the provided solution worked for you! 🎉 If you encounter any further issues or have additional questions, feel free to reach out. We're here to help!

Happy training! 🚀
