### ISSUE TITLE
KeyError When Customization to YOLOv8 Model: 

### ISSUE THREAD

**Issue by EngrNaeemRaza** [ultralytics/ultralytics#13866]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Whenever I want to introduce a new layer or module in YOLOv8 Model or CFG YAML File, upon training the model, it shows KeyError.

### Additional

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 564, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 150, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 219, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 309, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 894, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
KeyError: 'SimSPPF'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by glenn-jocher** [comment]
@EngrNaeemRaza hi there,

Thank you for reaching out and providing detailed information about the issue you're encountering. It seems like you're running into a `KeyError` when trying to introduce a new layer or module in the YOLOv8 model or its configuration YAML file.

To assist you effectively, could you please provide a minimum reproducible code example? This will help us understand the exact changes you're making and reproduce the issue on our end. You can find guidelines on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to investigate and resolve the problem efficiently.

Additionally, please ensure that you are using the latest versions of both `torch` and `ultralytics`. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

Once you've updated the packages, try running your code again to see if the issue persists.

If the problem continues, please share the specific modifications you made to the model or the YAML file, along with the relevant code snippets. This will help us pinpoint the issue more accurately.

Looking forward to your response!

**Comment by EngrNaeemRaza** [comment]
I have added new class definitions to block.py. but it's not accessible. I also tried your proposed approaches to similar issues but still my class definitions are not accessible as modules.

**Comment by glenn-jocher** [comment]
Hi @EngrNaeemRaza,

Thank you for your detailed report! It sounds like you're encountering issues with accessing new class definitions added to `block.py`.

To assist you better, could you please provide a minimum reproducible code example? This will help us understand the exact changes you're making and reproduce the issue on our end. You can find guidelines on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to investigate and resolve the problem efficiently.

Additionally, please ensure that you are using the latest versions of both `torch` and `ultralytics`. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

Once you've updated the packages, try running your code again to see if the issue persists.

If the problem continues, please share the specific modifications you made to the model or the YAML file, along with the relevant code snippets. This will help us pinpoint the issue more accurately.

Looking forward to your response!

**Comment by EngrNaeemRaza** [comment]
def parse_model(d, ch, verbose=True):  # model_dict, input_channels(3)
    """Parse a YOLO model.yaml dictionary into a PyTorch model."""
    import ast
    globals()['SimConv'] = SimConv
    globals()['SimSPPF'] = SimSPPF
    # Args
    max_channels = float("inf")
    nc, act, scales = (d.get(x) for x in ("nc", "activation", "scales"))
    depth, width, kpt_shape = (d.get(x, 1.0) for x in ("depth_multiple", "width_multiple", "kpt_shape"))
    if scales:
        scale = d.get("scale")
        if not scale:
            scale = tuple(scales.keys())[0]
            LOGGER.warning(f"WARNING ⚠️ no model scale passed. Assuming scale='{scale}'.")
        depth, width, max_channels = scales[scale]

    if act:
        Conv.default_act = eval(act)  # redefine default activation, i.e. Conv.default_act = nn.SiLU()
        if verbose:
            LOGGER.info(f"{colorstr('activation:')} {act}")  # print

    if verbose:
        LOGGER.info(f"\n{'':>3}{'from':>20}{'n':>3}{'params':>10}  {'module':<45}{'arguments':<30}")
    ch = [ch]
    layers, save, c2 = [], [], ch[-1]  # layers, savelist, ch out
    for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):  # from, number, module, args
        m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
        for j, a in enumerate(args):
            if isinstance(a, str):
                with contextlib.suppress(ValueError):
                    args[j] = locals()[a] if a in locals() else ast.literal_eval(a)

        n = n_ = max(round(n * depth), 1) if n > 1 else n  # depth gain
        if m in {
            Classify,
            Conv,
            ConvTranspose,
            GhostConv,
            Bottleneck,
            GhostBottleneck,
            SPP,
            SPPF,
            SimConv,
            SimSPPF,
            DWConv,
            Focus,
            BottleneckCSP,
            C1,
            C2,
            C2f,
            C3f,
            RepNCSPELAN4,
            ADown,
            SPPELAN,
            C2fAttn,
            C3,
            C3TR,
            C3Ghost,
            nn.ConvTranspose2d,
            DWConvTranspose2d,
            C3x,
            RepC3,
        }:
            c1, c2 = ch[f], args[0]
            if c2 != nc:  # if c2 not equal to number of classes (i.e. for Classify() output)
                c2 = make_divisible(min(c2, max_channels) * width, 8)
            if m is C2fAttn:
                args[1] = make_divisible(min(args[1], max_channels // 2) * width, 8)  # embed channels
                args[2] = int(
                    max(round(min(args[2], max_channels // 2 // 32)) * width, 1) if args[2] > 1 else args[2]
                )  # num heads

            args = [c1, c2, *args[1:]]
            if m in {BottleneckCSP, C1, C2, C2f, C2fAttn, C3, C3f, C3TR, C3Ghost, C3x, RepC3, SimConv, SimSPPF}:
                args.insert(2, n)  # number of repeats
                n = 1
        elif m is AIFI:
            args = [ch[f], *args]
        elif m in {HGStem, HGBlock}:
            c1, cm, c2 = ch[f], args[0], args[1]
            args = [c1, cm, c2, *args[2:]]
            if m is HGBlock:
                args.insert(4, n)  # number of repeats
                n = 1
        elif m is ResNetLayer:
            c2 = args[1] if args[3] else args[1] * 4
        elif m is nn.BatchNorm2d:
            args = [ch[f]]
        elif m is Concat:
            c2 = sum(ch[x] for x in f)
        elif m in {Detect, WorldDetect, Segment, Pose, OBB, ImagePoolingAttn}:
            args.append([ch[x] for x in f])
            if m is Segment:
                args[2] = make_divisible(min(args[2], max_channels) * width, 8)
        elif m is RTDETRDecoder:  # special case, channels arg must be passed in index 1
            args.insert(1, [ch[x] for x in f])
        elif m is CBLinear:
            c2 = args[0]
            c1 = ch[f]
            args = [c1, c2, *args[1:]]
        elif m is CBFuse:
            c2 = ch[f[-1]]
        else:
            c2 = ch[f]

        m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
        t = str(m)[8:-2].replace("__main__.", "")  # module type
        m.np = sum(x.numel() for x in m_.parameters())  # number params
        m_.i, m_.f, m_.type = i, f, t  # attach index, 'from' index, type
        if verbose:
            LOGGER.info(f"{i:>3}{str(f):>20}{n_:>3}{m.np:10.0f}  {t:<45}{str(args):<30}")  # print
        save.extend(x % i for x in ([f] if isinstance(f, int) else f) if x != -1)  # append to savelist
        layers.append(m_)
        if i == 0:
            ch = []
        ch.append(c2)
    return nn.Sequential(*layers), sorted(save)

**Comment by EngrNaeemRaza** [comment]
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 4                     # number of classes
depth_multiple: 0.33      # scales module repeats
width_multiple: 0.50      # scales convolution channelsa

  # scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  # n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  # s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  # m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  # l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  # x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SimSPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, Conv, [512, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, Conv, [256, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 14], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[17, 20, 23], 1, Detect, [nc]] # Detect(P3, P4, P5)

**Comment by EngrNaeemRaza** [comment]
class SimConv(nn.Module):
    """Normal Conv with ReLU activation"""
    def __init__(self, c1, c2, k, stride, groups=1, bias=False):
        super().__init__()
        padding = k // 2
        self.conv = nn.Conv2d(
            c1,
            c2,
            kernel_size=k,
            stride=stride,
            padding=padding,
            groups=groups,
            bias=bias,
        )
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.ReLU()

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

    def forward_fuse(self, x):
        return self.act(self.conv(x))
    
    torch.nn.SimConv = SimConv

class SimSPPF(nn.Module):
    """Simplified SPPF with ReLU activation"""
    def __init__(self, c1, c2, k=5):
        super().__init__()
        c2 = c1
        c_ = c1 // 2  # hidden channels
        self.cv1 = SimConv(c1, c_, 1, 1)
        self.cv2 = SimConv(c_ * 4, c2, 1, 1)
        self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2)

    def forward(self, x):
        x = self.cv1(x)
        #with warnings.catch_warnings():
        #warnings.simplefilter('ignore')
        y1 = self.m(x)
        y2 = self.m(y1)
        return self.cv2(torch.cat([x, y1, y2, self.m(y2)], 1))

        torch.nn.SimSPPF = SimSPPF

**Comment by EngrNaeemRaza** [comment]
I have provided all the necessary information for better understanding the issue.  I have also applied your suggestions to https://github.com/ultralytics/ultralytics/issues/13339, https://github.com/ultralytics/ultralytics/issues/12803, https://github.com/ultralytics/ultralytics/issues/13243, https://github.com/ultralytics/ultralytics/issues/13432. Problem still exists. Please help me to resolve the issue.

**Comment by glenn-jocher** [comment]
Hi @EngrNaeemRaza,

Thank you for providing the additional details and for trying out the suggested solutions. It looks like you've made significant progress, but the issue persists. Let's dive deeper to resolve this.

### Key Points to Check:

1. **Ensure Class Registration**: Make sure your new classes `SimConv` and `SimSPPF` are properly registered in the global scope. It looks like you have already done this, but let's double-check:

    ```python
    globals()['SimConv'] = SimConv
    globals()['SimSPPF'] = SimSPPF
    ```

2. **Update the YAML Configuration**: Ensure that your YAML configuration file correctly references the new modules. For example:

    ```yaml
    backbone:
      - [-1, 1, SimConv, [64, 3, 2]]
      - [-1, 1, SimSPPF, [128, 5]]
    ```

3. **Verify Module Import**: Ensure that the modules are imported correctly in the script where `parse_model` is defined. You might need to import `SimConv` and `SimSPPF` at the beginning of your script:

    ```python
    from your_module import SimConv, SimSPPF
    ```

4. **Check for Typos**: Double-check for any typos in the class names or YAML configuration.

### Example Code:

Here’s a concise example to ensure everything is set up correctly:

```python
import torch
import torch.nn as nn

class SimConv(nn.Module):
    def __init__(self, c1, c2, k, stride, groups=1, bias=False):
        super().__init__()
        padding = k // 2
        self.conv = nn.Conv2d(c1, c2, kernel_size=k, stride=stride, padding=padding, groups=groups, bias=bias)
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.ReLU()

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

class SimSPPF(nn.Module):
    def __init__(self, c1, c2, k=5):
        super().__init__()
        c2 = c1
        c_ = c1 // 2
        self.cv1 = SimConv(c1, c_, 1, 1)
        self.cv2 = SimConv(c_ * 4, c2, 1, 1)
        self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2)

    def forward(self, x):
        x = self.cv1(x)
        y1 = self.m(x)
        y2 = self.m(y1)
        return self.cv2(torch.cat([x, y1, y2, self.m(y2)], 1))

# Register classes globally
globals()['SimConv'] = SimConv
globals()['SimSPPF'] = SimSPPF

# Example YAML configuration
model_cfg = {
    'backbone': [
        [-1, 1, 'SimConv', [64, 3, 2]],
        [-1, 1, 'SimSPPF', [128, 5]]
    ],
    'head': []
}

# Example parse_model function call
def parse_model(d, ch, verbose=True):
    layers, save, c2 = [], [], ch[-1]
    for i, (f, n, m, args) in enumerate(d['backbone'] + d['head']):
        m = globals()[m]
        layers.append(m(*args))
    return nn.Sequential(*layers), sorted(save)

# Parse the model
model, _ = parse_model(model_cfg, [3])
print(model)
```

### Next Steps:

1. **Run the Example**: Try running the example code above to ensure that the new modules are correctly integrated.
2. **Check for Errors**: If any errors persist, please share the specific error messages and any additional context.

If the issue still exists, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us diagnose and resolve the issue more effectively.

Thank you for your patience and cooperation. Let's get this resolved! 🚀

**Comment by EngrNaeemRaza** [comment]
When I am importing SimConv and SimSPPF classes in Tasks.PY File. it's considering them as string, not as a class. What will be the issue?

**Comment by glenn-jocher** [comment]
Hi @EngrNaeemRaza,

Thank you for your detailed question! It sounds like you're encountering an issue where the `SimConv` and `SimSPPF` classes are being interpreted as strings rather than class objects when importing them in `tasks.py`.

To address this, please ensure the following steps:

1. **Register Classes Globally**: Make sure your new classes are registered in the global scope before they are used. This can be done by adding them to the `globals()` dictionary:

    ```python
    globals()['SimConv'] = SimConv
    globals()['SimSPPF'] = SimSPPF
    ```

2. **Correct YAML Configuration**: Ensure that your YAML configuration file correctly references these classes by their names as strings:

    ```yaml
    backbone:
      - [-1, 1, SimConv, [64, 3, 2]]
      - [-1, 1, SimSPPF, [128, 5]]
    ```

3. **Import Classes in `tasks.py`**: Ensure that `SimConv` and `SimSPPF` are imported correctly in `tasks.py`:

    ```python
    from your_module import SimConv, SimSPPF
    ```

4. **Modify `parse_model` Function**: Ensure that the `parse_model` function correctly retrieves the class objects from the `globals()` dictionary:

    ```python
    def parse_model(d, ch, verbose=True):
        layers, save, c2 = [], [], ch[-1]
        for i, (f, n, m, args) in enumerate(d['backbone'] + d['head']):
            m = globals()[m]  # Retrieve the class object
            layers.append(m(*args))
        return nn.Sequential(*layers), sorted(save)
    ```

Here’s a concise example to ensure everything is set up correctly:

```python
import torch
import torch.nn as nn

class SimConv(nn.Module):
    def __init__(self, c1, c2, k, stride, groups=1, bias=False):
        super().__init__()
        padding = k // 2
        self.conv = nn.Conv2d(c1, c2, kernel_size=k, stride=stride, padding=padding, groups=groups, bias=bias)
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.ReLU()

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

class SimSPPF(nn.Module):
    def __init__(self, c1, c2, k=5):
        super().__init__()
        c2 = c1
        c_ = c1 // 2
        self.cv1 = SimConv(c1, c_, 1, 1)
        self.cv2 = SimConv(c_ * 4, c2, 1, 1)
        self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2)

    def forward(self, x):
        x = self.cv1(x)
        y1 = self.m(x)
        y2 = self.m(y1)
        return self.cv2(torch.cat([x, y1, y2, self.m(y2)], 1))

# Register classes globally
globals()['SimConv'] = SimConv
globals()['SimSPPF'] = SimSPPF

# Example YAML configuration
model_cfg = {
    'backbone': [
        [-1, 1, 'SimConv', [64, 3, 2]],
        [-1, 1, 'SimSPPF', [128, 5]]
    ],
    'head': []
}

# Example parse_model function call
def parse_model(d, ch, verbose=True):
    layers, save, c2 = [], [], ch[-1]
    for i, (f, n, m, args) in enumerate(d['backbone'] + d['head']):
        m = globals()[m]
        layers.append(m(*args))
    return nn.Sequential(*layers), sorted(save)

# Parse the model
model, _ = parse_model(model_cfg, [3])
print(model)
```

If the issue persists, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us diagnose and resolve the issue more effectively.

Thank you for your patience and cooperation. Let's get this resolved! 🚀

**Comment by EngrNaeemRaza** [comment]
The problem still persists. We need more guidance to resolve the issue. I
am working on Google Colab and my code resides in Goodle Drive.
--
*With Profound Regards,*
*Naeem Raza*

**Comment by pderrenger** [comment]
Hi Naeem,

Thank you for your patience. Please ensure you are using the latest versions of both `torch` and `ultralytics` in your Google Colab environment. You can update them with the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

If the issue persists, please provide a minimum reproducible example, including the specific changes you made to the model or YAML file. This will help us diagnose and resolve the issue more effectively.

**Comment by mahisahu24** [comment]
I am also facing the same issue:

KeyError When Customization to YOLOv8 Model

i have updated 
1.yolov8/ultralytics/models/v8/yolov8.yaml
2.yolov8/ultralytics/nn/tasks.py
3.yolov8/ultralytics/nn/modules/conv.py
4.yolov8/ultralytics/nn/modules/block.py
5.yolov8/ultralytics/nn/modules/init.py

**Comment by glenn-jocher** [comment]
Thank you for sharing the details. It seems the issue persists due to improper registration or referencing of your custom modules. Ensure your custom classes are correctly imported into `tasks.py` and registered in `globals()` within the `parse_model` function. Double-check your YAML configuration for accuracy and ensure it matches the class names exactly. If the issue remains unresolved, please provide a reproducible example or open a focused issue for further assistance.

**Comment by Rizwanali324** [comment]
> Hi [@Rizwanali324](https://github.com/Rizwanali324),
> 
> Your error is different from the original issue. The `KeyError: 14` indicates that your model is detecting class index 14, but your `names` dictionary only contains class 0 ('Teeth'). This is an inference issue, not a model architecture issue.
> 
> To resolve this, check your model's class configuration by adding `model.names` after loading to see all expected classes, and ensure your model was trained with the correct number of classes. You can also override the names with `model.names = {0: 'Teeth'}` if you only expect one class.
> 
> For the original customization issue by [@EngrNaeemRaza](https://github.com/EngrNaeemRaza), the key is ensuring your custom classes are properly imported and registered in the `parse_model` function within `tasks.py` before the function processes the YAML configuration.

thanks its fixed by changes in task
