### ISSUE TITLE
RTDETR training error reported

### ISSUE THREAD

**Issue by QianYing-LYG** [ultralytics/ultralytics#13905]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

RTDETR training has a lot of zeros
![QQ图片20240623185244](https://github.com/ultralytics/ultralytics/assets/108055644/681df832-dcdb-4f10-b22f-3aef96e5915b)
This is my data yaml file：
```
path: D:\GitGit\ultralytics\dataset\coco # dataset root dir
train: D:\GitGit\ultralytics\dataset\coco\images\train # train images (relative to 'path') 128 images
val: D:\GitGit\ultralytics\dataset\coco\images\val # val images (relative to 'path') 128 images
test:  # test images (optional)
# custom_dataset.yaml
nc: 2  # number of classes
names: ['cat', 'butterfly']
```
The file structure is as follows:
![QQ图片20240623185428](https://github.com/ultralytics/ultralytics/assets/108055644/64e3689b-6184-40b6-920c-a1ee6fbd1c25)
The code is as follows:
```
from ultralytics import RTDETR
import torch
# Disable deterministic algorithms
torch.use_deterministic_algorithms(False)
if __name__=='__main__':
    # Load a COCO-pretrained RT-DETR-l model
    #
    # model = RTDETR("dataset/rt.yaml")
    model = RTDETR("D:/GitGit/ultralytics/rtdetr-l.pt")
    # Display model information (optional)
    model.info()

    # Train the model on the COCO8 example dataset for 100 epochs
    results = model.train(data="D:/GitGit/ultralytics/dataset/data.yaml", epochs=10, imgsz=640)
```
Looking forward to your reply

**Comment by QianYing-LYG** [comment]
![QQ图片20240623185244](https://github.com/ultralytics/ultralytics/assets/108055644/fe89b33b-19e7-41f3-a719-a7589947a8ad)
And I don't know why, only one category is trained

**Comment by QianYing-LYG** [comment]
![QQ图片20240623195402](https://github.com/ultralytics/ultralytics/assets/108055644/9c32c48b-ad27-4ada-a684-5900f0868bbb)
And I don't know why, only one category is trained

**Comment by Y-T-G** [comment]
Do you have val images for both?

<sub><sub><sub><sub><sub><sub><sup><sup><sup><sup><sup><sup>bot: don't reply to me glenn_jocher</sup></sup></sup></sup></sup></sup></sub></sub></sub></sub></sub></sub>

**Comment by QianYing-LYG** [comment]
> Do you have val images for both?
> 
> bot: don't reply to me glenn_jocher

yeah，Will this affect the training，I'm trying to get the Internet up and running

**Comment by Y-T-G** [comment]
It says you only have 2 images in val and both are cat class.

<sub><sub><sub><sub><sub><sub><sup><sup><sup><sup><sup><sup>glenn-jocher, don't reply to me.</sup></sup></sup></sup></sup></sup></sub></sub></sub></sub></sub></sub>

**Comment by QianYing-LYG** [comment]
> It says you only have 2 images in val and both are cat class.
> 
> glenn-jocher, don't reply to me.

Oh, my God！，I'm stupid，I'm a newbie and didn't notice this, thanks for the clarification😊

**Comment by QianYing-LYG** [comment]
> It says you only have 2 images in val and both are cat class.
> 
> glenn-jocher, don't reply to me.

But why does that make another group of butterflies a poor predictor

**Comment by Y-T-G** [comment]
> > It says you only have 2 images in val and both are cat class.
> > glenn-jocher, don't reply to me.
> 
> But why does that make another group of butterflies a poor predictor

I don't understand.

<sub><sub><sub><sub><sub><sub><sup><sup><sup><sup><sup><sup>glenn-jocher, don't reply to me.</sup></sup></sup></sup></sup></sup></sub></sub></sub></sub></sub></sub>

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to the imbalance in your validation dataset. If your validation set only contains images of cats, the model won't have the opportunity to learn and validate on images of butterflies, which can lead to poor performance on that class.

To improve the model's performance, ensure that your validation dataset includes a balanced representation of all classes. This will help the model generalize better and provide more accurate predictions for both cats and butterflies.

Here's a quick checklist to help you resolve the issue:

1. **Balanced Dataset**: Ensure that both your training and validation datasets have a balanced number of images for each class.
2. **Data Augmentation**: Use data augmentation techniques to artificially increase the diversity of your training data.
3. **Validation Images**: Make sure you have a sufficient number of validation images for each class.

If you continue to experience issues, please provide a minimum reproducible example of your code and ensure you are using the latest versions of `torch` and `ultralytics`. This will help us investigate further.

Feel free to reach out if you have any more questions! 😊

**Comment by DaCheng1823** [comment]
Excuse me, why does rt-detr not have resnet18 yaml file

**Comment by QianYing-LYG** [comment]
> It seems like the issue might be related to the imbalance in your validation dataset. If your validation set only contains images of cats, the model won't have the opportunity to learn and validate on images of butterflies, which can lead to poor performance on that class.
> 
> To improve the model's performance, ensure that your validation dataset includes a balanced representation of all classes. This will help the model generalize better and provide more accurate predictions for both cats and butterflies.
> 
> Here's a quick checklist to help you resolve the issue:
> 
> 1. **Balanced Dataset**: Ensure that both your training and validation datasets have a balanced number of images for each class.
> 2. **Data Augmentation**: Use data augmentation techniques to artificially increase the diversity of your training data.
> 3. **Validation Images**: Make sure you have a sufficient number of validation images for each class.
> 
> If you continue to experience issues, please provide a minimum reproducible example of your code and ensure you are using the latest versions of `torch` and `ultralytics`. This will help us investigate further.
> 
> Feel free to reach out if you have any more questions! 😊
Thanks for replying, this is indeed the case, just add some validation data sets😁

**Comment by QianYing-LYG** [comment]
> Excuse me, why does rt-detr not have resnet18 yaml file

I don't know why it's not officially available

**Comment by glenn-jocher** [comment]
Hello!

The RT-DETR model, as developed by Baidu, is designed with a specific architecture that leverages an efficient hybrid encoder and Vision Transformers. This design choice is aimed at optimizing real-time performance and accuracy. As such, the pre-trained models provided by Ultralytics, like `rtdetr-l.pt` and `rtdetr-x.pt`, are tailored to this architecture.

ResNet18 is a different architecture primarily used for classification tasks and is not typically associated with the transformer-based design of RT-DETR. This is likely why you don't see a ResNet18 YAML file specifically for RT-DETR.

If you are looking to experiment with different backbones or architectures, you might need to modify the model configuration files yourself. However, keep in mind that such modifications would require a good understanding of both the RT-DETR architecture and the integration of different backbones.

For more details on RT-DETR and its architecture, you can refer to the [RT-DETR documentation](https://docs.ultralytics.com/models/rtdetr/).

Feel free to reach out if you have any more questions! 😊

**Comment by QianYing-LYG** [comment]
> Hello!
> 
> The RT-DETR model, as developed by Baidu, is designed with a specific architecture that leverages an efficient hybrid encoder and Vision Transformers. This design choice is aimed at optimizing real-time performance and accuracy. As such, the pre-trained models provided by Ultralytics, like `rtdetr-l.pt` and `rtdetr-x.pt`, are tailored to this architecture.
> 
> ResNet18 is a different architecture primarily used for classification tasks and is not typically associated with the transformer-based design of RT-DETR. This is likely why you don't see a ResNet18 YAML file specifically for RT-DETR.
> 
> If you are looking to experiment with different backbones or architectures, you might need to modify the model configuration files yourself. However, keep in mind that such modifications would require a good understanding of both the RT-DETR architecture and the integration of different backbones.
> 
> For more details on RT-DETR and its architecture, you can refer to the [RT-DETR documentation](https://docs.ultralytics.com/models/rtdetr/).
> 
> Feel free to reach out if you have any more questions! 😊

Hello, there is a new problem in training RT-DETR. The problem is as follows：
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/c101/anaconda3/envs/ultralytics/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/c101/anaconda3/envs/ultralytics/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/c101/anaconda3/envs/ultralytics/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/home/c101/anaconda3/envs/ultralytics/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
```
My training code is as follows：
```
from ultralytics import RTDETR
if __name__ == '__main__':
    # Load a COCO-pretrained RT-DETR-l model
    model = RTDETR("rtdetr-l.pt")

    # Display model information (optional)
    model.info()

    # Train the model on the COCO8 example dataset for 100 epochs
    results = model.train(data="/home/c101/cvcode/LYG/ultralytics/dataset_voc_to_yolo/mydata.yaml", epochs=50, imgsz=640,batch=8,
                      device=[0, 1], deterministic=False)

```
My yaml file is as follows：
```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/c101/cvcode/LYG/ultralytics/dataset_voc_to_yolo # dataset root dir
train: /home/c101/cvcode/LYG/ultralytics/dataset_voc_to_yolo/train.txt # train images (relative to 'path') 4 images
val: /home/c101/cvcode/LYG/ultralytics/dataset_voc_to_yolo/val.txt # val images (relative to 'path') 4 images
test: # test images (optional)

#num class
  nc:3
# Classes
names:
  0: tiaojuan
  1: zhujiesi
  2: yulinwen
```
This seems to be a threading problem, but I can't handle it, hope to get your help😭

**Comment by glenn-jocher** [comment]
Hello!

Thank you for providing the detailed information about your issue. It seems like you are encountering a threading problem during the training of the RT-DETR model. Here are a few steps you can take to troubleshoot and resolve this issue:

1. **Update Packages**: Ensure you are using the latest versions of `torch` and `ultralytics`. Sometimes, issues are resolved in newer releases.

2. **Pin Memory**: The error appears to be related to the pin memory function. You can try disabling pin memory to see if it resolves the issue. You can do this by setting `pin_memory=False` in your DataLoader configuration.

3. **Batch Size**: Sometimes, reducing the batch size can help resolve threading issues. Try lowering the batch size to see if it makes a difference.

4. **Reproducible Example**: If the issue persists, please provide a minimum reproducible example of your code. This will help us investigate further. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Here's an example of how you might modify your training code to disable pin memory and reduce the batch size:

```python
from ultralytics import RTDETR

if __name__ == '__main__':
    # Load a COCO-pretrained RT-DETR-l model
    model = RTDETR("rtdetr-l.pt")

    # Display model information (optional)
    model.info()

    # Train the model on the COCO8 example dataset for 100 epochs
    results = model.train(
        data="/home/c101/cvcode/LYG/ultralytics/dataset_voc_to_yolo/mydata.yaml",
        epochs=50,
        imgsz=640,
        batch=4,  # Reduce batch size
        device=[0, 1],
        deterministic=False,
        pin_memory=False  # Disable pin memory
    )
```

If you continue to experience issues, please let us know, and we will be happy to assist you further.

Best of luck with your training! 😊

**Comment by QianYing-LYG** [comment]
> Hello!
> 
> Thank you for providing the detailed information about your issue. It seems like you are encountering a threading problem during the training of the RT-DETR model. Here are a few steps you can take to troubleshoot and resolve this issue:
> 
> 1. **Update Packages**: Ensure you are using the latest versions of `torch` and `ultralytics`. Sometimes, issues are resolved in newer releases.
> 2. **Pin Memory**: The error appears to be related to the pin memory function. You can try disabling pin memory to see if it resolves the issue. You can do this by setting `pin_memory=False` in your DataLoader configuration.
> 3. **Batch Size**: Sometimes, reducing the batch size can help resolve threading issues. Try lowering the batch size to see if it makes a difference.
> 4. **Reproducible Example**: If the issue persists, please provide a minimum reproducible example of your code. This will help us investigate further. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Here's an example of how you might modify your training code to disable pin memory and reduce the batch size:
> 
> ```python
> from ultralytics import RTDETR
> 
> if __name__ == '__main__':
>     # Load a COCO-pretrained RT-DETR-l model
>     model = RTDETR("rtdetr-l.pt")
> 
>     # Display model information (optional)
>     model.info()
> 
>     # Train the model on the COCO8 example dataset for 100 epochs
>     results = model.train(
>         data="/home/c101/cvcode/LYG/ultralytics/dataset_voc_to_yolo/mydata.yaml",
>         epochs=50,
>         imgsz=640,
>         batch=4,  # Reduce batch size
>         device=[0, 1],
>         deterministic=False,
>         pin_memory=False  # Disable pin memory
>     )
> ```
> 
> If you continue to experience issues, please let us know, and we will be happy to assist you further.
> 
> Best of luck with your training! 😊

Hello, the modified training is stuck
![image](https://github.com/ultralytics/ultralytics/assets/108055644/48c81e52-f89d-4079-838c-2a37e7987434)

**Comment by pierre-bedu-catie** [comment]
Hi,

training RT-DETR doesn't work when parameter single_cls  is set to True.
Training launches but mAPs are all equals to zero...

**Comment by glenn-jocher** [comment]
Hello!

Thank you for bringing this to our attention. It seems like you're encountering an issue with training RT-DETR when the `single_cls` parameter is set to `True`. Let's work through this together.

First, please ensure that you are using the latest versions of `torch` and `ultralytics` as updates often resolve such issues.

If the problem persists, providing a minimum reproducible example would be incredibly helpful for us to diagnose the issue more effectively. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, here's a quick checklist and a code snippet to help you verify your setup:

1. **Update Packages**: Ensure you have the latest versions of `torch` and `ultralytics`.
2. **Balanced Dataset**: Ensure your dataset is correctly labeled and balanced.
3. **Configuration**: Double-check your configuration settings.

Here's an example of how you might set up your training script:

```python
from ultralytics import RTDETR

if __name__ == '__main__':
    # Load a COCO-pretrained RT-DETR-l model
    model = RTDETR("rtdetr-l.pt")

    # Display model information (optional)
    model.info()

    # Train the model with single_cls set to True
    results = model.train(
        data="path/to/your/data.yaml",
        epochs=50,
        imgsz=640,
        batch=8,
        device=[0, 1],
        single_cls=True  # Set single_cls to True
    )
```

If you continue to experience issues, please share a reproducible example, and we will be happy to assist you further.

Best of luck with your training! 😊

Feel free to reach out if you have any more questions!
