### ISSUE TITLE
Flow of YOLOv8

### ISSUE THREAD

**Issue by CyrusAddy** [ultralytics/ultralytics#13944]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I am working with YOLOv8 currently but I can't seem to follow the code in repository with the model architecture, I am trying to understand the flow and logic between the two. What is the best way to go about that?

Also, I want to assess the functions of the various blocks by commenting them (# ...) and see how my results would look like. Is that possible?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@CyrusAddy hi there,

Thank you for reaching out! Understanding the flow and architecture of YOLOv8 can indeed be quite intricate, but it's a rewarding endeavor. Here are some steps to help you get started:

1. **Documentation and Tutorials**: Begin by reviewing the [Ultralytics YOLOv8 documentation](https://docs.ultralytics.com) which provides comprehensive details on the model architecture, training, and inference processes. This will give you a high-level overview of how everything fits together.

2. **Code Exploration**: Dive into the source code, starting with the `ultralytics/models` directory. The `yolo.py` file is a good entry point as it defines the model architecture. You can trace the flow from model initialization to the forward pass.

3. **Debugging and Experimentation**: To understand the functions of various blocks, you can indeed comment out sections of the code. However, a more efficient approach might be to use debugging tools such as `pdb` or IDEs like PyCharm or VSCode, which allow you to set breakpoints and step through the code.

4. **Reproducible Examples**: If you encounter specific issues or have questions about certain parts of the code, providing a minimum reproducible example can be very helpful. You can find guidelines on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

5. **Community and Updates**: Ensure you are using the latest version of the repository to benefit from recent updates and bug fixes. The community is also a great resource, so feel free to ask questions and share your findings.

Here’s a small code snippet to help you get started with commenting out parts of the model for experimentation:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')

# Example: Comment out a specific layer or block in the model
# You can modify the model architecture directly in the source code
# For instance, in ultralytics/models/yolo.py, you might see something like:
# self.layer = nn.Sequential(...)
# You can comment out this line and observe the effects

# Run inference to see the impact of your changes
results = model.predict('path/to/your/image.jpg')
results.show()
```

Feel free to experiment and observe how changes affect the model's performance. If you have any specific questions or run into issues, don't hesitate to ask!

Best of luck with your exploration! 🚀

**Comment by CyrusAddy** [comment]
@glenn-jocher I can't find the yolo.py in my development environment files after "pip install ultralytics". Can you give me the entire directory?

**Comment by glenn-jocher** [comment]
Hi @CyrusAddy,

Thank you for your question! When you install the Ultralytics package via `pip install ultralytics`, the source code, including `yolo.py`, is packaged and not directly visible in your environment. However, you can still explore the source code by cloning the repository directly from GitHub.

Here’s how you can do it:

1. **Clone the Repository**:
   ```bash
   git clone https://github.com/ultralytics/ultralytics.git
   cd ultralytics
   ```

2. **Navigate to the Model Directory**:
   ```bash
   cd ultralytics/models
   ```

3. **Explore the Code**:
   You will find `yolo.py` and other relevant files in this directory. This will allow you to inspect and modify the model architecture as needed.

If you encounter any issues or have further questions, feel free to ask! Also, if you’re running into specific problems, providing a minimum reproducible example can be very helpful. You can find guidelines on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Best of luck with your development! 🚀

**Comment by CyrusAddy** [comment]
@glenn-jocher After following the above procedure, there is no yolo.py. Attached is the content I see in the ultralytics/models  directory (folder).
![ultralytics](https://github.com/ultralytics/ultralytics/assets/120698887/7c86a797-7605-4181-98f5-611cd84cc3f1)

**Comment by glenn-jocher** [comment]
Hi @CyrusAddy,

Thank you for the update and the screenshot. It looks like you might be looking for the core model architecture files which are structured differently in the latest versions of the Ultralytics repository.

In the current structure, the model definitions and architectures are modularized and can be found across several files. Here’s a quick guide to help you navigate:

1. **Model Definitions**:
   - The core model definitions are located in `ultralytics/models/common.py` and `ultralytics/models/yolo.py`.
   - The `yolo.py` file contains the YOLO model class and its components.

2. **Exploring the Architecture**:
   - You can start by looking at `ultralytics/models/yolo.py` for the overall model structure.
   - The `common.py` file includes various building blocks used in the YOLO architecture, such as convolutional layers, bottlenecks, etc.

Here’s how you can navigate to these files:

```bash
cd ultralytics/models
```

You should see files like `common.py` and `yolo.py` which define the model architecture.

If you’re looking to modify specific parts of the model, you might want to start with these files. For example, to understand the model’s forward pass, you can look into the `forward` method in `yolo.py`.

If you encounter any specific issues or need further assistance, providing a minimum reproducible example can be very helpful. You can find guidelines on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to explore and experiment! If you have any more questions or need further clarification, don’t hesitate to ask. 😊

**Comment by CyrusAddy** [comment]
The yolo i have in my directory is not .py, what can I do to get that? All approach tried but still. I even updated the ultralytics but did not work.

![image](https://github.com/ultralytics/ultralytics/assets/120698887/cdb63774-bb7e-458e-8a7f-e2741980bdfb)

**Comment by glenn-jocher** [comment]
Hi @CyrusAddy,

Thank you for your patience and for providing the screenshot. It looks like you're having trouble locating the `yolo.py` file. The architecture and core functionalities of YOLOv8 are indeed spread across multiple files in the latest versions.

To help you navigate and understand the model architecture, here are the key files and their locations:

1. **Model Definitions**:
   - **`ultralytics/models/yolo.py`**: This file contains the YOLO model class and its components.
   - **`ultralytics/models/common.py`**: This file includes various building blocks used in the YOLO architecture, such as convolutional layers, bottlenecks, etc.

2. **Exploring the Architecture**:
   - **`yolo.py`**: Look into the `YOLO` class and its `forward` method for the overall model structure.
   - **`common.py`**: Contains the definitions for layers and modules used within the YOLO model.

Here’s how you can navigate to these files:

```bash
cd ultralytics/models
```

If you still can't find these files, it might be helpful to clone the repository directly from GitHub to ensure you have the latest version:

```bash
git clone https://github.com/ultralytics/ultralytics.git
cd ultralytics
```

If you encounter any specific issues or need further assistance, providing a minimum reproducible example can be very helpful. You can find guidelines on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to explore and experiment! If you have any more questions or need further clarification, don’t hesitate to ask. 😊

**Comment by CyrusAddy** [comment]
@glenn-jocher could you share a short video of this with my email cyrus.addy@yahoo.com? I would be grateful since I cannot seem to lay hold of it. Just a screen recording would do. Thank you.

**Comment by harshdhamecha** [comment]
@CyrusAddy The latest ultralytics repo has a slightly different folder structure than what @glenn-jocher has mentioned.

You should start following the code from the `ultralytics/models/` directory. Each model folder contains `model.py`. So, For YOLO, `ultralytics/models/yolo/model.py`. 

The `task_map` function in `model.py` defines the task-wise mode to class mapping as defined below.
https://github.com/ultralytics/ultralytics/blob/dcde8bd23d12bbb4867ebf45f936dd37c2445974/ultralytics/models/yolo/model.py#L26-L59


So, For loading a yolo detection model, `DetectionModel` will be called, located [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/tasks.py) . For training, 
`yolo.detect.DetectionTrainer` will be called, located [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/detect/train.py).

The `parse_model` function in `DetectionModel` parses model definition based on model yaml file. 
https://github.com/ultralytics/ultralytics/blob/dcde8bd23d12bbb4867ebf45f936dd37c2445974/ultralytics/nn/tasks.py#L309

This method parses different modules (or layers) like `Conv`, `BottleNeck`, etc. 

All `Conv` related layers are defined [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/conv.py), `head layers (Detect, Segment, etc.)` [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/head.py) and other `layers/blocks (BottleNeck, SPP, C2f, etc.)` [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/block.py).

You can play around with different layers at these locations.

**Comment by CyrusAddy** [comment]
@harshdhamecha Thank you for you help, this feedback is very helpful. 

Another question is, if I add new layers like DSConv in the conv.py file and do some other changes in other .py files. How do I train my new algorithm from scratch using my own dataset?

**Comment by CyrusAddy** [comment]
@harshdhamecha I wrote this code to try training the yolov8, but I am getting this error. How do I fix it?

from ultralytics import YOLO
from PIL import Image
import cv2

# step 1 -> step YOLO model initialization
model = YOLO("yolov8n.pt")
model = YOLO("./yolov8.yaml")
#print(model.model)
im1 = Image.open("C:/Users/ca8mc/Desktop/version8/v8_env/traindata/images/train")
results = model.train(source=im1, save=True)

error:


Users/ca8mc/Desktop/version8/v8_env/Lib/site-packages/ultralytics/mytest.py
WARNING ⚠️ no model scale passed. Assuming scale='n'.
Traceback (most recent call last):
  File "c:\Users\ca8mc\Desktop\version8\v8_env\Lib\site-packages\ultralytics\mytest.py", line 7, in <module>
    model = YOLO("./yolov8.yaml")
  File "C:\Users\ca8mc\Desktop\version8\v8_env\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\ca8mc\Desktop\version8\v8_env\lib\site-packages\ultralytics\engine\model.py", line 150, in __init__
    self._new(model, task=task, verbose=verbose)
  File "C:\Users\ca8mc\Desktop\version8\v8_env\lib\site-packages\ultralytics\engine\model.py", line 219, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "C:\Users\ca8mc\Desktop\version8\v8_env\lib\site-packages\ultralytics\nn\tasks.py", line 287, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "C:\Users\ca8mc\Desktop\version8\v8_env\lib\site-packages\ultralytics\nn\tasks.py", line 855, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
KeyError: 'DSConv'

**Comment by harshdhamecha** [comment]
You can not use a pre-compiled package when making code changes. So, don't follow the `from ultralytics import YOLO` way. 

Rather, use the cloned repo, make changes and follow the [docs](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#train-on-custom-data) to train from scratch.

You need to update the following files:

1. model.yaml - Create a new model.yaml file, which includes DSConv or whatever layer you want to include. 
2. dataset.yaml - Create a new dataset.yaml file. 
3. tasks.py - Update parse_model function.
4. conv.py - Create a class for DSConv layer.

Feel free to explore and experiment! If you have any more questions or need further clarification, don’t hesitate to ask. 😊

**Comment by pderrenger** [comment]
To train your modified YOLOv8 model with custom layers like DSConv, you should indeed work with the cloned repository rather than using the pre-compiled package. Here are the steps to follow:

1. Clone the Ultralytics repository and make your code changes directly in the cloned repo.
2. Update the `model.yaml` file to include your new DSConv layer.
3. Create or update your `dataset.yaml` file to define your custom dataset.
4. Modify the `parse_model` function in `tasks.py` to recognize and correctly parse your new DSConv layer.
5. Implement the DSConv class in `conv.py`.

Once these changes are made, you can train your model from scratch using the provided training scripts. If you encounter any issues or need further clarification, feel free to ask.

**Comment by CyrusAddy** [comment]
@pderrenger How do I run the train after making the changes? Do I need the pre-trained what or not? I am assuming its a new architecture so I would not need the pre-trained weight. Which code would I use to run this new model? Can you provide an example?

**Comment by pderrenger** [comment]
To run training after making changes to the model architecture, you don't need pre-trained weights if you're starting from scratch. Simply use the training script provided in the repository. Navigate to the cloned repository and run the training command with your custom model and dataset YAML files. For example, you can use:

```bash
python train.py --data path/to/your/dataset.yaml --cfg path/to/your/model.yaml --weights ''
```

This command initializes training without any pre-trained weights. If you encounter any issues, ensure you're using the latest version of the repository.

**Comment by CyrusAddy** [comment]
@harshdhamecha I tried as you advised but when I try to run "train" from my virtual environment it says no "train.py" in that directory, so I cd into the directory that contains "train.py" and run the code again. Then I get ModuleNotFoundError: No module named 'ultralytics'. Please see attached image and help me resolve this.



![image](https://github.com/user-attachments/assets/bbda35f1-5f49-4895-b65a-93a7de4c7736)

**Comment by harshdhamecha** [comment]
The docs link I mentioned above has been updated to be compatible with the latest Ultralytics release. The following command should start the training on your machine. Make sure to cd into the project directory (C:/Users/ca8mc/new8/ultralytics)
```
yolo detect train data=customdata.yaml cfg=C:/Users/ca8mc/Desktop/newv8/ultralytics/ultralytics/models/v8/yolov8-dsconv.yaml weights='' device=0
```

Feel free to explore and experiment! If you have any more questions or need further clarification, don’t hesitate to ask. 😊

**Comment by glenn-jocher** [comment]
Please ensure you are in the correct directory and use the following command to start the training:

```bash
yolo detect train data=customdata.yaml cfg=ultralytics/models/v8/yolov8-dsconv.yaml weights='' device=0
```

If you encounter any issues, please verify that you have the latest package version.

**Comment by CyrusAddy** [comment]
@harshdhamecha I am still getting an error for the running the code you sent.

![image](https://github.com/user-attachments/assets/a57815b6-5bb4-40ba-832b-60d372afe1aa)

**Comment by CyrusAddy** [comment]
@glenn-jocher how do I verify the version of YOLOv8 I have cloned unto my PC?

**Comment by glenn-jocher** [comment]
You can verify the YOLOv8 version by running the following command in your terminal:

```bash
yolo version
```

This will display the installed version of YOLOv8.

**Comment by CyrusAddy** [comment]
@glenn-jocher This is what I get when I try to check the version
![image](https://github.com/user-attachments/assets/bcc9add5-e53c-43e9-a90d-ae38488c09df)

**Comment by harshdhamecha** [comment]
Please install the latest version of `ultralytics` and rerun your code.

**Comment by CyrusAddy** [comment]
@harshdhamecha I run the code now its saying this, also the new "yolov8-dsconv.yaml" is marked U (Untracked). How do I fix that?
![image](https://github.com/user-attachments/assets/fdd7f409-467e-445b-b15b-9d448e05e5ce)
![image](https://github.com/user-attachments/assets/b0ca82d9-f58c-4aa1-af39-994ec4adb774)

**Comment by CyrusAddy** [comment]
@glenn-jocher I just found out that DSConv is actually coded in the conv.py file as LightConv. Is that true? If not let me know.

**Comment by glenn-jocher** [comment]
Yes, that's correct. DSConv is implemented as LightConv in the `conv.py` file. If you have any more questions, feel free to ask!

**Comment by CyrusAddy** [comment]
@glenn-jocher my new .yaml file I created for the layers with LightConv has this "U" there meaning untracked. How do I fix that? Thank you

![image](https://github.com/user-attachments/assets/49e4622b-932b-47fe-bc30-c70b7b66dc11)

**Comment by glenn-jocher** [comment]
To track your new `.yaml` file, use the command `git add yourfile.yaml` to stage it for commit. Let me know if you need further assistance!

**Comment by harshdhamecha** [comment]
newv8 folder is not initialised as a git repository. So, `cd ultralytics` followed by `git add path/to/yaml` should solve the problem.

**Comment by CyrusAddy** [comment]
@harshdhamecha it now says index added, I guess that is fixed.

**Comment by CyrusAddy** [comment]
@harshdhamecha when I try to train my yolov8-dsconv.yaml from scratch, I get this error
![image](https://github.com/user-attachments/assets/456ce59a-4ca8-4973-bcc2-13932bbb786c)

Check my yaml file and see if I am doing something wrong

![image](https://github.com/user-attachments/assets/5f04950a-3c62-4ab8-b830-b68f97090bb0)
I just changed the Conv to LightConv in the backbone and maintained everything else.

**Comment by harshdhamecha** [comment]
> @harshdhamecha it now says index added, I guess that is fixed.

Your yaml file is now staged, you can commit your changes using `git commit -m "added custom model file"`

Please refer git docs for further details .

**Comment by harshdhamecha** [comment]
> @harshdhamecha when I try to train my yolov8-dsconv.yaml from scratch, I get this error ![image](https://private-user-images.githubusercontent.com/120698887/368216673-456ce59a-4ca8-4973-bcc2-13932bbb786c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODY2NjgsIm5iZiI6MTcyNjU4NjM2OCwicGF0aCI6Ii8xMjA2OTg4ODcvMzY4MjE2NjczLTQ1NmNlNTlhLTRjYTgtNDk3My1iY2MyLTEzOTMyYmJiNzg2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNTE5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjQzMTU1NGIzMWE1ZjMxZWNmMzcxNTMwZGQxYjhmOGEzMzNkODY5YzdiN2Y4MGY1ZmUzZWJiOGU3N2QwODJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4rTSQ6CSLgKHKKOFKbo8WAAENcnC8ApzImITcOV_rII)
> 
> Check my yaml file and see if I am doing something wrong
> 
> ![image](https://private-user-images.githubusercontent.com/120698887/368217124-5f04950a-3c62-4ab8-b830-b68f97090bb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODY2NjgsIm5iZiI6MTcyNjU4NjM2OCwicGF0aCI6Ii8xMjA2OTg4ODcvMzY4MjE3MTI0LTVmMDQ5NTBhLTNjNjItNGFiOC1iODMwLWI2OGY5NzA5MGJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNTE5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDA3YzU0YTJmOTdjNjlmMWZmOGU4MjM2ZWQ0Y2Q2NGZmMzcxODI5ZWUxZDcyZDE2MzYxNTkwN2VkYmYxOWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HVIG_9TsFc7s0HYF62Vkowj6eNFQa2ShMA6DHRVPHm8) I just changed the Conv to LightConv in the backbone and maintained everything else.

Not sure why this occurs, run `pip install -e .` followed by your previous `yolo detect ...` command and let me know if it solve the problem or not.

**Comment by CyrusAddy** [comment]
@harshdhamecha I am still getting the same error after performing all the operations you mentioned above.
![image](https://github.com/user-attachments/assets/d829b98e-f68e-4ca9-8a06-5ec1ae7b6688)

**Comment by glenn-jocher** [comment]
You can verify the YOLOv8 version by running `git log -1` in the cloned directory to see the latest commit details.

**Comment by CyrusAddy** [comment]
@glenn-jocher This is the output I get 

![image](https://github.com/user-attachments/assets/de0a9562-7834-4caa-9e0a-a3275e81fd80)

**Comment by CyrusAddy** [comment]
@glenn-jocher when I try to run the LightConv, the model structure it gives as Conv instead of LightConv (see attached image). What could be the cause?

![image](https://github.com/user-attachments/assets/a17197fa-918a-4be9-8d55-2cd5c305cee1)

**Comment by glenn-jocher** [comment]
@CyrusAddy it seems like the model configuration might not be correctly referencing LightConv. Double-check your YAML file to ensure that all instances of Conv are replaced with LightConv.
