### ISSUE TITLE
yolov8 predict: 'DetectionModel' object has no attribute 'end2end'

### ISSUE THREAD

**Issue by kukushking** [ultralytics/ultralytics#14014]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

ultralytics                       8.2.43
ultralytics-thop                  2.0.0

Prediction works with yolov10s (see MRE) but doesn't work if I change back to yolov8s - there seems to be a regression as it used to work on v8 with older package version. There is a similar [issue](https://github.com/ultralytics/ultralytics/issues/13934) related to yolov10 that suggests `augment=False` but `augment=True` already supported on v10 and I would like consistency between the yolov8s and yolov10s predictions api.

Stack trace:
```
  File "/Volumes/.../modules/post-processing/yolo-object-detection/src/detect_objects.py", line 63, in <module>
    output_json, output_pandas = get_yolo_prediction(model, image, input_data_path)
  File "/Volumes/.../modules/post-processing/yolo-object-detection/src/detect_objects.py", line 33, in get_yolo_prediction
    results = model.predict(image, augment=True)[0]
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/engine/model.py", line 442, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/Volumes/.../.venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 254, in stream_inference
    preds = self.inference(im, *args, **kwargs)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 142, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize, embed=self.args.embed, *args, **kwargs)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 455, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 102, in forward
    return self.predict(x, *args, **kwargs)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 119, in predict
    return self._predict_augment(x)
  File "/Volumes/.../.venv/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 340, in _predict_augment
    if self.end2end:
  File "/Volumes/.../.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DetectionModel' object has no attribute 'end2end'

```

### Environment

OS                  macOS-14.4.1-x86_64-i386-64bit
Environment         Darwin
Python              3.10.8
Install             pip
RAM                 16.00 GB
CPU                 Intel Core(TM) i5-8257U 1.40GHz
CUDA                None

matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example
```
# model = YOLO("yolov10s") - works 
model = YOLO("yolov8s") # - doesn't work
results = model.predict(image, augment=True)[0]
```

### Additional

ultralytics                       8.2.43
ultralytics-thop                  2.0.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kukushking thank you, I can reproduce with this code. @Laughing-q it seems our fix introduced new issues for existing models. 

```
from ultralytics import YOLO, ASSETS
Backend MacOSX is interactive backend. Turning interactive mode on.
model = YOLO("yolov8s") # - doesn't work
results = model.predict(ASSETS / "bus.jpg", augment=True)[0]
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3614, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-f752035e825c>", line 2, in <module>
    results = model.predict(ASSETS / "bus.jpg", augment=True)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/model.py", line 442, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/predictor.py", line 254, in stream_inference
    preds = self.inference(im, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/predictor.py", line 142, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize, embed=self.args.embed, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/nn/autobackend.py", line 455, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/nn/tasks.py", line 102, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/nn/tasks.py", line 119, in predict
    return self._predict_augment(x)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/nn/tasks.py", line 340, in _predict_augment
    if self.end2end:
       ^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DetectionModel' object has no attribute 'end2end'
```

**Comment by Laughing-q** [comment]
@glenn-jocher @kukushking ...I think it'e because the `DetectionModel` we had embedded into pretrained weights does not include the attribute. Submitted a PR to fix it and also added `augment=True` inference in our tests. https://github.com/ultralytics/ultralytics/pull/14017

**Comment by kukushking** [comment]
Thanks for prompt action!

**Comment by glenn-jocher** [comment]
@kukushking you're welcome! 😊 We're glad to help. The issue you encountered with the `DetectionModel` object lacking the `end2end` attribute has been identified and a fix has been submitted. Please update to the latest version once the PR is merged and let us know if you encounter any further issues.

If you have any other questions or need additional assistance, feel free to ask. Happy coding! 🚀
