### ISSUE TITLE
Error reporting using VFL Loss

### ISSUE THREAD

**Issue by WuChuhan** [ultralytics/ultralytics#1414]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I would like to ask what is the specific meaning of target_labels in VFL. When I try to use VFL to calculate the classification loss, the following error occurs. The dimensions do not match. How can I solve it? I went to see the source code of VFL Loss and found that there is no target_labels parameter. How should I use VFL Loss correctly?（my num_classes=7）

Traceback (most recent call last):
  File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 241, in <module>
    train()
  File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 237, in train
    trainer.train()
  File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\engine\trainer.py", line 189, in train
    self._do_train(RANK, world_size)
  File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\engine\trainer.py", line 311, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 83, in criterion
    return self.compute_loss(preds, batch)
  File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 210, in __call__
    loss[1] = self.varifocal_loss(pred_scores, target_scores, target_labels) / target_scores_sum  # VFL way
  File "C:\Users\wuchu\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\utils\loss.py", line 17, in forward
    weight = alpha * pred_score.sigmoid().pow(gamma) * (1 - label) + gt_score * label
RuntimeError: The size of tensor a (7) must match the size of tensor b (8400) at non-singleton dimension 2

**Comment by WuChuhan** [comment]
No one knows how to use VFL way on yolov8？？？

**Comment by Laughing-q** [comment]
@WuChuhan closing this one as there's a same issue. :)
