### ISSUE TITLE
I still get this : ModuleNotFoundError: No module named 'numpy._core'  when I try all 3 ways mentioned above

### ISSUE THREAD

**Issue by mmschzs** [ultralytics/ultralytics#14160]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Bug description:
I still get this :
ModuleNotFoundError: No module named 'numpy._core'

when I try all 3 ways mentioned above

MRE:

ModuleNotFoundError: No module named 'numpy._core'

Error message:

ModuleNotFoundError: No module named 'numpy._core'
Dependencies:
Package Version

certifi 2024.6.2
charset-normalizer 3.3.2
contourpy 1.1.1
cycler 0.12.1
filelock 3.15.4
fonttools 4.53.0
fsspec 2024.6.1
idna 3.7
importlib_resources 6.4.0
Jinja2 3.1.4
kiwisolver 1.4.5
MarkupSafe 2.1.5
matplotlib 3.7.5
mpmath 1.3.0
networkx 3.1
numpy 1.24.4
nvidia-cublas-cu12 12.1.3.1
nvidia-cuda-cupti-cu12 12.1.105
nvidia-cuda-nvrtc-cu12 12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12 8.9.2.26
nvidia-cufft-cu12 11.0.2.54
nvidia-curand-cu12 10.3.2.106
nvidia-cusolver-cu12 11.4.5.107
nvidia-cusparse-cu12 12.1.0.106
nvidia-nccl-cu12 2.20.5
nvidia-nvjitlink-cu12 12.5.82
nvidia-nvtx-cu12 12.1.105
opencv-python 4.10.0.84
packaging 24.1
pandas 2.0.3
pillow 10.4.0
pip 24.0
psutil 6.0.0
py-cpuinfo 9.0.0
pyparsing 3.1.2
python-dateutil 2.9.0.post0
pytz 2024.1
PyYAML 6.0.1
requests 2.32.3
scipy 1.10.1
seaborn 0.13.2
setuptools 69.5.1
six 1.16.0
sympy 1.12.1
thop 0.1.1.post2209072238
torch 2.3.1+cu121
torchaudio 2.3.1+cu121
torchvision 0.18.1+cu121
tqdm 4.66.4
triton 2.3.1
typing_extensions 4.12.2
tzdata 2024.1
ultralytics 8.2.48
ultralytics-thop 2.0.0
urllib3 2.2.2
wheel 0.43.0
zipp 3.19.2

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for reaching out and providing the details of your issue. The `ModuleNotFoundError: No module named 'numpy._core'` error typically indicates an issue with the installation of the `numpy` package.

Here are a few steps you can take to resolve this:

1. **Reinstall Numpy**: Sometimes, reinstalling the package can resolve such issues. You can do this by running:
   ```bash
   pip uninstall numpy
   pip install numpy
   ```

2. **Check for Conflicting Packages**: Ensure there are no conflicting packages that might be causing this issue. You can create a new virtual environment and install only the necessary packages to see if the issue persists:
   ```bash
   python -m venv myenv
   source myenv/bin/activate  # On Windows, use `myenv\Scripts\activate`
   pip install numpy ultralytics
   ```

3. **Update Packages**: Make sure all your packages are up to date. You can update `numpy` and other dependencies by running:
   ```bash
   pip install --upgrade numpy
   pip install --upgrade ultralytics
   ```

4. **Verify Installation**: Sometimes, the installation might be corrupted. Verify that `numpy` is correctly installed by running:
   ```python
   import numpy
   print(numpy.__version__)
   ```

If the issue persists after trying the above steps, please provide a minimum reproducible example (MRE) as it helps us diagnose the problem more effectively. You can find more details on how to create an MRE here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, ensure you are using the latest versions of the packages to avoid any compatibility issues.

Feel free to reach out if you have any further questions or need additional assistance. 😊

**Comment by tangxiu1110** [comment]
您好，我也尝试了以上的方法，还是有报错。No module named 'numpy._core'
# Name                    Version                   Build  Channel
ca-certificates           2024.9.24            haa95532_0    defaults
certifi                   2024.8.30                pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
fonttools                 4.54.1                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_1    defaults
matplotlib                3.7.5                    pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   3.0.15               h827c3e9_0    defaults
packaging                 24.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2             py38haa95532_0    defaults
psutil                    6.0.0                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pyside6                   6.6.3.1                  pypi_0    pypi
pyside6-addons            6.6.3.1                  pypi_0    pypi
pyside6-essentials        6.6.3.1                  pypi_0    pypi
python                    3.8.20               h8205438_0    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setuptools                75.1.0           py38haa95532_0    defaults
shiboken6                 6.6.3.1                  pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    defaults
torch                     1.13.0+cu117             pypi_0    pypi
torchvision               0.14.0+cu117             pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
ultralytics               8.3.13                   pypi_0    pypi
ultralytics-thop          2.0.9                    pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
vc                        14.40                h2eaa2aa_1    defaults
vs2015_runtime            14.40.33807          h98bb1dd_1    defaults
wheel                     0.44.0           py38haa95532_0    defaults
zipp                      3.20.2                   pypi_0    pypi

**Comment by glenn-jocher** [comment]
@tangxiu1110 您好，感谢您的反馈。请尝试以下步骤：确保您在一个新的虚拟环境中重新安装`numpy`和`ultralytics`。如果问题仍然存在，请检查是否有任何冲突的包或考虑更新到最新版本。希望这能解决您的问题！

**Comment by ly27253** [comment]
Thanks to the author for giving and sharing！
I can use the official pre-trained model and can achieve correct inference, but after training on my own dataset, I get the following error 

result = unpickler.load()
File "/media/ly/AddDisk/Anaconda/envs/YOLOV8/lib/python3.8/site-packages/torch/serialization.py", line 1515, in find_class
return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'numpy._core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/media/ly/win_Disk/Win_Pro/uav_detect/yolov8/detect_yolo8_dmodels_1027V1.py", line 32, in <module>
model_s = YOLO("/media/ly/win_Disk/Win_Pro/uav_detect/train6/weights/best.pt").to(device)
File "/media/ly/win_Disk/Win_Pro/uav_detect/yolov8/ultralytics/models/yolo/model.py", line 23, in __init__
super().__init__(model=model, task=task, verbose=verbose)
File "/media/ly/win_Disk/Win_Pro/uav_detect/yolov8/ultralytics/engine/model.py", line 145, in __init__
self._load(model, task=task)
File "/media/ly/win_Disk/Win_Pro/uav_detect/yolov8/ultralytics/engine/model.py", line 285, in _load
self.model, self.ckpt = attempt_load_one_weight(weights)
File "/media/ly/win_Disk/Win_Pro/uav_detect/yolov8/ultralytics/nn/tasks.py", line 910, in attempt_load_one_weight
ckpt, weight = torch_safe_load(weight) # load ckpt
File "/media/ly/win_Disk/Win_Pro/uav_detect/yolov8/ultralytics/nn/tasks.py", line 857, in torch_safe_load
ckpt = torch.load(file, map_location="cpu")
File "/media/ly/win_Disk/Win_Pro/uav_detect/yolov8/ultralytics/utils/patches.py", line 86, in torch_load
return _torch_load(*args, **kwargs)
File "/media/ly/AddDisk/Anaconda/envs/YOLOV8/lib/python3.8/site-packages/torch/serialization.py", line 1097, in load
return _load(
File "/media/ly/AddDisk/Anaconda/envs/YOLOV8/lib/python3.8/site-packages/torch/serialization.py", line 1525, in _load
result = unpickler.load()
File "/media/ly/AddDisk/Anaconda/envs/YOLOV8/lib/python3.8/site-packages/torch/serialization.py", line 1515, in find_class
return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'numpy._core'

Process finished with exit code 1

######################################################################################
I've almost tried the solutions in the discussion forum but I still have this problem, but miraculously I can use the pre-trained models correctly and also some of the trained models such as “YOLOV8n.pt” and “YOLOV8s.pt” accurately. ”, but I get the above error when training “YOLOV8m.pt”.

**Comment by glenn-jocher** [comment]
It seems like there might be an issue with the `numpy` installation in your environment. Please try reinstalling `numpy` using `pip install --upgrade --force-reinstall numpy` in your YOLOv8 environment. If the issue persists, consider creating a new virtual environment and reinstalling the necessary packages.

**Comment by ly27253** [comment]
Thank you very much for your reply, I suspected the environment problem, but after I re-trained YOLOV8s and YOLOV8n, the re-trained model can be tested normally, but after re-training YOLOV8m, this problem occurs, I make sure that the training environment and the training parameter settings are the same as the training of YOLOV8s, and moreover, I noticed that the authors provide pre-training model The size is about 50MB, but after training my dataset the model becomes 100MB+, is this a normal situation?

**Comment by ly27253** [comment]
> Thank you very much for your reply, I suspected the environment problem, but after I re-trained YOLOV8s and YOLOV8n, the re-trained model can be tested normally, but after re-training YOLOV8m, this problem occurs, I make sure that the training environment and the training parameter settings are the same as the training of YOLOV8s, and moreover, I noticed that the authors provide pre-training model The size is about 50MB, but after training my dataset the model becomes 100MB+, is this a normal situation?

Thank you very much for your reply, I suspected the environment problem, but after I re-trained YOLOV8s and YOLOV8n, the re-trained model can be tested normally, but after re-training YOLOV8m, this problem occurs, I make sure that the training environment and the training parameter settings are the same as the training of YOLOV8s, and moreover, I noticed that the authors provide pre-training model The size is about 50MB, but after training my dataset the model becomes 100MB+, is this a normal situation?

**Comment by ly27253** [comment]
Thank you very much for your reply, I suspected the environment problem, but after I re-trained YOLOV8s and YOLOV8n, the re-trained model can be tested normally, but after re-training YOLOV8m, this problem occurs, I make sure that the training environment and the training parameter settings are the same as the training of YOLOV8s, and moreover, I noticed that the authors provide pre-training model The size is about 50MB, but after training my dataset the model becomes 100MB+, is this a normal situation?

**Comment by ly27253** [comment]
I redid the experiment with a smaller dataset (containing 1080 images) to train yolov8m and found that the model was working, the difference between this and the aforementioned model that didn't work properly was the difference in the amount of training dataset, which amounted to 42,321 images.

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to the size of the dataset affecting the model's training process. Consider checking your system's memory and storage capacity, as handling larger datasets can sometimes lead to resource constraints or issues during model saving.

**Comment by mmschzs** [comment]
Thanks all you guys, I gave up and I re-clone the ultralytics and restart a new env.

**Comment by ayun3738** [comment]
I experienced the same issue, and I think it was caused during the process of creating the train and val cache. Deleting the cache files in the label folder of the dataset and running it again solved the problem for me.

**Comment by shreeramsigdel77** [comment]
I came up with same issue of not being able to train custom data inside docker. 
My script was not able to write the .cache file because write permission was not available to that particular folder. So, atleast make sure you have write permission as well not just read and execute.

**Comment by glenn-jocher** [comment]
Thank you for sharing your insight. Ensuring appropriate write permissions in the dataset directory is indeed critical when using Docker, as the `.cache` files need to be created during training. Your suggestion will surely help others encountering similar issues.

**Comment by tahsinalamin** [comment]
> I experienced the same issue, and I think it was caused during the process of creating the train and val cache. Deleting the cache files in the label folder of the dataset and running it again solved the problem for me.

This worked for me as well.

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution! Ensuring proper cache management is indeed crucial, and deleting corrupted cache files often resolves dataset-related issues. For more details on how Ultralytics handles dataset caching, check out the [cache_labels documentation](https://docs.ultralytics.com/reference/data/dataset/#ultralytics.data.dataset.YOLODataset.cache_labels).

**Comment by Abbsalehi** [comment]
Installing numpy 1.26 worked for me.

`pip install numpy==1.26.4`

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution! This error can sometimes occur due to version compatibility issues, and we appreciate you reporting what worked in your environment. For others experiencing similar issues, we recommend following the [YOLO troubleshooting guide](https://docs.ultralytics.com/guides/yolo-common-issues/) which covers common dependency conflicts.

**Comment by ckragh** [comment]
As can be seen here, numpy renamed numpy.core to numpy._core:
https://numpy.org/doc/stable/release/2.0.0-notes.html

So could it be due to the fact that your are using numpy 1.x?

**Comment by gong223** [comment]
Hi all, I'm working on creating a new conda environment on the cluster, and there are some packages. I met this problem, and my Python version is 3.11.5, my numpy version is 2.14.4, and CUDA is 11.7. I tried to create the environment using different numpy and Python versions, like python=3.8.5 and numpy=1.XX.X, but they didn't work.

**Comment by glenn-jocher** [comment]
Hi @gong223, thanks for detailing the steps you've tried. This error usually points to an issue with the NumPy installation or version conflicts within your conda environment, especially tricky on cluster setups.

Could you try creating a fresh conda environment and installing PyTorch, CUDA, and a specific NumPy version together? This allows conda to resolve dependencies properly. For example, using NumPy 1.26.4 which worked for another user:

```bash
conda create --name myenv python=3.11 -y
conda activate myenv
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia -y
conda install numpy=1.26.4 -y
pip install ultralytics
```

Ensure no other conflicting NumPy versions are present. You can find more setup details in our [installation guide](https://docs.ultralytics.com/quickstart/). Let us know if this helps!

**Comment by mahakanakala** [comment]
Thanks @Abbsalehi! 

For me, installing numpy==1.26.4 resolved this issue. I experienced these specific dependency conflicts when upgrading to NumPy 2.x:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.1.1 requires numpy<2.0,>=1.16; python_version <= "3.11", but you have numpy 2.2.5 which is incompatible.
tensorflow-macos 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.2.5 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.2.5 which is incompatible.
scipy 1.11.3 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.2.5 which is incompatible.
```

As @ckragh correctly pointed out regarding the NumPy internal restructuring, these conflicts created the issue: NumPy 2.x changes module paths that older libraries depend on, while simultaneously those libraries explicitly restrict their compatibility to NumPy < 2.0.

The Ultralytics package can work with newer NumPy versions, and the ecosystem around it creates a web of dependencies. The documentation shows that it depends on numerous packages, including matplotlib, scipy, and others [Ultralytics](https://docs.ultralytics.com/quickstart/) - all of which have their own strict NumPy version requirements. However, even if you don't directly use these libraries in your code, they're installed as part of the Ultralytics dependency chain and need compatible NumPy versions to function properly. Downgrading to NumPy 1.26.4 works because it satisfies the version constraints of all these dependent libraries while using the module structure they expect. For anyone facing this error, I recommend checking your full dependency tree and installing a NumPy version compatible with your **entire** stack.

**Comment by wanghy1997** [comment]
I also encountered the same issue. Fortunately, I reconfigured the virtual environment with `python==3.10`, `numpy==2.2.6` and it eventually ran my own data normally.

**Comment by AbdelrahmanYousef9266** [comment]
> Installing numpy 1.26 worked for me.
> 
> `pip install numpy==1.26.4`

**Thank you So Much this one Worked for me After 10 hours trying to fix the issue**

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in PR #20904: Handle numpy._core error while loading cache.

Key improvements from this PR include enhanced error handling for missing modules and version mismatches during dataset cache and model weight loading. Specifically, the update now catches ModuleNotFoundError when loading dataset cache files, and provides clearer, more informative messages if NumPy is missing or outdated, including details about the required version. These changes aim to prevent crashes and make troubleshooting much easier, especially for issues related to NumPy dependencies.

Many thanks to the author and contributors for this helpful update!

To test if this resolves your issue, you can install the latest version directly from the main branch:
```
pip install git+https://github.com/ultralytics/ultralytics.git@main
```
Alternatively, you can wait for the next official PyPI release, which will include these changes.

Please let us know if this update resolves the issue for you! Thank you for reporting this, and feel free to share any further feedback if you encounter ongoing problems. 🙏
