### ISSUE TITLE
Can not export yolov10 model to paddlepaddle

### ISSUE THREAD

**Issue by GuoQuanhao** [ultralytics/ultralytics#14179]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

yolo_export.py
```
from ultralytics import YOLO

# Load a model
model = YOLO("./runs/order/yolov10n/train6/weights/best.pt")  # load an official model
# Export the model
model.export(format="paddle")
```

```
========= 2 OPs are not supported yet ===========
========== aten::topk ============
========== aten::amax ============
PaddlePaddle: export failure ❌ 4.1s: Model is not supported yet.
Traceback (most recent call last):
  File "/home/work/guoquanhao/ultralytics/yolo_export.py", line 6, in <module>
    model.export(format="paddle")
  File "/home/work/guoquanhao/ultralytics/ultralytics/engine/model.py", line 590, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/opt/anaconda3/envs/torch_gqh/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/work/guoquanhao/ultralytics/ultralytics/engine/exporter.py", line 323, in __call__
    f[10], _ = self.export_paddle()
  File "/home/work/guoquanhao/ultralytics/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/work/guoquanhao/ultralytics/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/work/guoquanhao/ultralytics/ultralytics/engine/exporter.py", line 530, in export_paddle
    pytorch2paddle(module=self.model, save_dir=f, jit_type="trace", input_examples=[self.im])  # export
  File "/home/opt/anaconda3/envs/torch_gqh/lib/python3.10/site-packages/x2paddle/convert.py", line 380, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "/home/opt/anaconda3/envs/torch_gqh/lib/python3.10/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 41, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by GuoQuanhao** [comment]
fixed by https://github.com/PaddlePaddle/X2Paddle/pull/1019/commits/222c3b3a48379d7f8aece2c3c08a272220d942ab

**Comment by glenn-jocher** [comment]
@GuoQuanhao thank you for the update! It's great to hear that the issue was resolved with the fix from the PaddlePaddle X2Paddle repository. If you encounter any further issues or have additional questions, feel free to reach out. Happy coding! 🚀
