### ISSUE TITLE
Question with YOLO RT-DETR

### ISSUE THREAD

**Issue by houSusan** [ultralytics/ultralytics#14219]
Hello, I tried  YOLO RT-DETR for detection and met the following question.  I used " yolo train data=mydata.yaml model=rtdetr-l.pt epochs=50 imgsz=640 device=0"  and it ran OK, but when I use "yolo predict source=mydata.yaml model=runs/detect/train/weights/best.pt", a keyerror will occur:
Ultralytics YOLOv8.2.48 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (NVIDIA RTX A4000, 16109MiB)
rt-detr-l summary: 494 layers, 32004290 parameters, 0 gradients, 103.5 GFLOPs

Traceback (most recent call last):
  File "/environment/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 442, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 183, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 334, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/results.py", line 329, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 180

And when I changed to the pre-trained rtdetr-l.pt model, as follows:" "yolo predict source=mydata.yaml model=rtdetr-l.pt"," it can run OK.  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar questions.
I want to know how to solve this question. Thanks!

**Comment by glenn-jocher** [comment]
@houSusan hello,

Thank you for reaching out and providing detailed information about the issue you're encountering with YOLO RT-DETR. It seems like the error is related to a `KeyError` when trying to access class names during prediction. This typically happens when the model's class indices do not match the class names defined in your dataset configuration.

Here are a few steps to help troubleshoot and resolve this issue:

1. **Verify Dataset Configuration**: Ensure that your `mydata.yaml` file correctly specifies the class names and indices. The class names should be listed under the `names` key, and their indices should match those used during training.

2. **Check Model Compatibility**: Since the pre-trained `rtdetr-l.pt` model works fine, the issue might be with the custom-trained model. Ensure that the custom model's class indices align with those in your dataset configuration. You can do this by inspecting the `best.pt` model's metadata.

3. **Update to Latest Version**: Make sure you are using the latest version of the Ultralytics package. Sometimes, bugs are fixed in newer releases. You can update the package using:
   ```bash
   pip install --upgrade ultralytics
   ```

4. **Reproduce the Issue**: If the issue persists, it would be helpful to have a minimum reproducible example. This will allow us to better understand the problem and provide a more accurate solution. You can find guidelines for creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

5. **Code Example**: To ensure the class names are correctly loaded during prediction, you can manually load the model and check the class names:
   ```python
   from ultralytics import YOLO

   # Load the custom-trained model
   model = YOLO('runs/detect/train/weights/best.pt')

   # Check the class names
   print(model.names)

   # Run prediction
   results = model.predict(source='path/to/your/image_or_video')
   ```

If you follow these steps and still encounter issues, please provide a reproducible example, and we will be happy to assist you further.

**Comment by houSusan** [comment]
@glenn-jocher Hello,
Thank you for your answer. I checked the steps you suggested and the question still encounter.
First, I updated my ultralytics as you given， and then I checked the class names manually as follows:

from ultralytics import YOLO
model = YOLO('best.pt')
print(model.names)
{0: 'airplane', 1: 'ship', 2: 'storage tank', 3: 'baseball diamond', 4: 'tennis court', 5: 'basketball court', 6: 'ground track field', 7: 'harbor', 8: 'bridge', 9: 'vehicle'}
results = model.predict(source='data/nwpu-10/test/images')


---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 results = model.predict(source='data/nwpu-10/test/images')

File /environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py:442, in Model.predict(self, source, stream, predictor, **kwargs)
    440 if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
    441     self.predictor.set_prompts(prompts)
--> 442 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File /environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py:168, in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    166     return self.stream_inference(source, model, *args, **kwargs)
    167 else:
--> 168     return list(self.stream_inference(source, model, *args, **kwargs))

File /environment/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py:35, in _wrap_generator.<locals>.generator_context(*args, **kwargs)
     32 try:
     33     # Issuing `None` to a generator fires it up
     34     with ctx_factory():
---> 35         response = gen.send(None)
     37     while True:
     38         try:
     39             # Forward the response to our caller and get its next request

File /environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py:274, in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
    268     self.results[i].speed = {
    269         "preprocess": profilers[0].dt * 1e3 / n,
    270         "inference": profilers[1].dt * 1e3 / n,
    271         "postprocess": profilers[2].dt * 1e3 / n,
    272     }
    273     if self.args.verbose or self.args.save or self.args.save_txt or self.args.show:
--> 274         s[i] += self.write_results(i, Path(paths[i]), im, s)
    276 # Print batch results
    277 if self.args.verbose:

File /environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py:334, in BasePredictor.write_results(self, i, p, im, s)
    332 result = self.results[i]
    333 result.save_dir = self.save_dir.__str__()  # used in other locations
--> 334 string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
    336 # Add predictions to image
    337 if self.args.save or self.args.show:

File /environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/results.py:329, in Results.verbose(self)
    327     for c in boxes.cls.unique():
    328         n = (boxes.cls == c).sum()  # detections per class
--> 329         log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
    330 return log_string

KeyError: 15

 The model's class matched with  mydata.yaml but question still occur.

**Comment by glenn-jocher** [comment]
Hello @houSusan,

Thank you for your detailed follow-up. It's great to see that you've verified the class names and updated the Ultralytics package. Given the persistent issue, let's delve deeper.

### Potential Issue:
The `KeyError: 15` suggests that the model is trying to access a class index that doesn't exist in your `model.names` dictionary. This can happen if there are discrepancies between the class indices used during training and those expected during prediction.

### Steps to Resolve:

1. **Check Class Indices Consistency**:
   Ensure that the class indices in your `mydata.yaml` file match exactly with those in the `model.names` dictionary. Here’s a quick way to verify:
   ```yaml
   # mydata.yaml
   names:
     0: 'airplane'
     1: 'ship'
     2: 'storage tank'
     3: 'baseball diamond'
     4: 'tennis court'
     5: 'basketball court'
     6: 'ground track field'
     7: 'harbor'
     8: 'bridge'
     9: 'vehicle'
   ```

2. **Inspect Training Data**:
   Ensure that your training data does not contain any annotations with class indices outside the range defined in `mydata.yaml`.

3. **Re-train with Verified Data**:
   If any discrepancies are found, correct them and re-train the model to ensure consistency.

4. **Debugging Prediction**:
   To further debug, you can add a print statement in the `results.py` file to check the class indices being accessed:
   ```python
   # In ultralytics/engine/results.py
   print(f"Class indices in results: {boxes.cls.unique()}")
   ```

### Example Code for Prediction:
Here’s a refined example to ensure everything is set correctly:
```python
from ultralytics import YOLO

# Load the custom-trained model
model = YOLO('runs/detect/train/weights/best.pt')

# Verify class names
print(model.names)

# Run prediction
results = model.predict(source='data/nwpu-10/test/images')

# Print results to debug
for result in results:
    print(result)
```

### Minimum Reproducible Example:
If the issue persists, providing a minimum reproducible example would be highly beneficial. This helps us replicate the issue on our end and provide a more accurate solution. You can find guidelines for creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Latest Version:
Lastly, ensure you are using the latest version of the Ultralytics package to benefit from recent fixes and improvements:
```bash
pip install --upgrade ultralytics
```

Feel free to share any additional details or updates. We're here to help! 😊

**Comment by houSusan** [comment]
@glenn-jocher , Hello,
     Thank you for your quick reply!
     I have done the following according to your suggestion：
1. First， I checked mydata.yaml , and here it is :
val: ../data/nwpu-10/images/val
train: ../data/nwpu-10/images/train
test: ../data/nwpu-10/images/test
names:
  0: 'airplane'
  1: 'ship'
  2: 'storage tank'
  3: 'baseball diamond'
  4: 'tennis court'
  5: 'basketball court'
  6: 'ground track field'
  7: 'harbor'
  8: 'bridge'
  9: 'vehicle'
nc: 10
2. I only kept 10 training images of the airplane and ensured the labels only has class indices "0"
3. I trained the model with the above data
4. I added the code print(f"Class indices in results: {boxes.cls.unique()}") to the results.py as you suggested, and predict  one image only has airplane with the model, and here is the output:
(base) ➜  ~ yolo predict model=runs/detect/train7/weights/best.pt source=data/nwpu-10/images/test/000006.jpg
Ultralytics YOLOv8.2.50 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (NVIDIA RTX A4000, 16109MiB)
rt-detr-l summary: 494 layers, 32004290 parameters, 0 gradients, 103.5 GFLOPs

Class indices in results: tensor([  0.,   4.,   8.,  89., 182., 185., 188., 210., 212., 222., 248., 249., 257.], device='cuda:0')
Class indices in results: tensor([  0.,   4.,   8.,  89., 182., 185., 188., 210., 212., 222., 248., 249., 257.], device='cuda:0')
Class indices in results: tensor([  0.,   4.,   8.,  89., 182., 185., 188., 210., 212., 222., 248., 249., 257.], device='cuda:0')
Class indices in results: tensor([  0.,   4.,   8.,  89., 182., 185., 188., 210., 212., 222., 248., 249., 257.], device='cuda:0')
Traceback (most recent call last):
  File "/environment/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 708, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 442, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 183, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 334, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/results.py", line 360, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 89

That's a puzzling question, I wonder what went wrong .

**Comment by glenn-jocher** [comment]
Hello @houSusan,

Thank you for the detailed follow-up and for providing the additional information. It's clear that you've taken thorough steps to diagnose the issue. The output indicates that there are unexpected class indices in the results, which suggests that the model might be predicting classes outside the defined range in your `mydata.yaml`.

### Potential Causes and Solutions:

1. **Model Training Artifacts**:
   - It seems like the model might have retained some artifacts or weights from a previous training session. To ensure a clean training process, you might want to start from scratch with a fresh model initialization.

2. **Class Mapping Issue**:
   - There might be an issue with how class indices are mapped during training and prediction. Ensure that the class indices are correctly mapped and consistent throughout the training and prediction phases.

3. **Data Verification**:
   - Double-check your training data to ensure there are no mislabeled or incorrectly indexed annotations. Even a single mislabel can cause such issues.

### Steps to Resolve:

1. **Reinitialize and Retrain**:
   - Reinitialize the model and retrain it with the verified dataset. This ensures that no residual weights or configurations affect the training process.
   ```python
   from ultralytics import YOLO

   # Initialize a new model
   model = YOLO('rtdetr-l.pt')

   # Train the model
   model.train(data='mydata.yaml', epochs=50, imgsz=640, device=0)
   ```

2. **Inspect and Clean Data**:
   - Verify that your dataset annotations are correct and consistent. Ensure that there are no outliers or incorrect class indices.
   ```python
   # Example code to inspect dataset annotations
   import os
   import json

   def inspect_annotations(data_path):
       for root, _, files in os.walk(data_path):
           for file in files:
               if file.endswith('.json'):
                   with open(os.path.join(root, file)) as f:
                       annotations = json.load(f)
                       for annotation in annotations:
                           if annotation['class'] not in range(10):
                               print(f"Invalid class index found: {annotation['class']} in file {file}")

   inspect_annotations('path/to/your/annotations')
   ```

3. **Debugging Prediction**:
   - Add more detailed logging to understand where the unexpected class indices are coming from.
   ```python
   from ultralytics import YOLO

   # Load the custom-trained model
   model = YOLO('runs/detect/train/weights/best.pt')

   # Run prediction with detailed logging
   results = model.predict(source='data/nwpu-10/test/images')

   # Print detailed results
   for result in results:
       print(f"Class indices in results: {result.boxes.cls.unique()}")
       print(result)
   ```

### Minimum Reproducible Example:
If the issue persists, providing a minimum reproducible example would be highly beneficial. This helps us replicate the issue on our end and provide a more accurate solution. You can find guidelines for creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Latest Version:
Lastly, ensure you are using the latest version of the Ultralytics package to benefit from recent fixes and improvements:
```bash
pip install --upgrade ultralytics
```

Feel free to share any additional details or updates. We're here to help! 😊

**Comment by qhdax6** [comment]
I have the same problem. I used RT-DETR for training and there were no issues. After RT-DETR training, the model also generated some renderings on the validation set. I have tried all the solutions you mentioned, but none of them have worked (whether it's updating versions or repeatedly checking for consistency in categories). In addition, what confuses me is that when I use the weight files generated by training other models for prediction, there is no problem, but when I use RT-DETR, there is a problem, always saying that the categories are different. What I can confirm is that the parameters set for training with YOLO series models and RT-DETR models are only different in the model configuration file, while everything else is the same (including any parameters, as well as the path and category of the dataset). Therefore, I believe that the impact of different categories should be minimal or even non-existent. So I don't know how to solve it, I hope someone can answer it.

**Comment by T-TXiaoRui** [comment]
Could the source of the error be that an unlabeled background image was added?

**Comment by T-TXiaoRui** [comment]
> Could the source of the error be that an unlabeled background image was added?

I did an experiment and confirmed that this is not the reason😟

**Comment by pderrenger** [comment]
Thanks for checking that! Given the unexpected class indices, it might be worth ensuring your dataset annotations are entirely consistent and there are no residual artifacts from previous trainings. Also, make sure you're using the latest version of the Ultralytics package to rule out any fixed bugs. If the issue persists, providing a minimal reproducible example could help us diagnose further.

**Comment by T-TXiaoRui** [comment]
Through debugging, I found that the postprocess in the predictor module of redetr calls the postprocess of yolo，I changed the postprocess to rtdetr and it works fine。

**Comment by pderrenger** [comment]
Thanks for the insight! It sounds like you've pinpointed the issue with the postprocess function. If you haven't already, please ensure you're using the latest version of the Ultralytics package to see if the issue persists. If it does, feel free to share more details, and we can look into it further. Great job on the debugging!

**Comment by houSusan** [comment]
Hello @T-TXiaoRui  
        Thank you for your work!  When  Mr. glenn-jocher suspected the wrong of class indices in the input datasets, I wrote a code to walk through my annotations and verified that the annotations are correct and consistent.  I also did the same  experiment with you and confirmed that unlabeled background images is not the reason. I think you have found the reason exists in  the postprocess in the predictor module of redetr , but my postprocess func in the predictor.py is different from yours. The screenshots is as follows, Please point out where the code should be changed again. Thank you !
![rtdetr-predict](https://github.com/user-attachments/assets/0d2c9bb2-b493-4d1a-b9e5-5ab3b6406398)

**Comment by houSusan** [comment]
@T-TXiaoRui  Hi, Thank you very much for your reply and help, After I modified the code in your way, the problem was solved and predictor works fine. Thanks again for your great work!
And I would also like to thank  [glenn-jocher](https://github.com/glenn-jocher) for his reply and help！

**Comment by sralvins** [comment]
from ultralytics import YOLO, RTDETR

model = YOLO('rtdetr-l.pt') ❌
model =  RTDETR('rtdetr-l.pt') -> use class `RTDETR` to init model not `YOLO`

**Comment by glenn-jocher** [comment]
Thank you for pointing that out! You are correct, for RT-DETR models, the `RTDETR` class should be used for initialization instead of `YOLO`. For example:  
```python
from ultralytics import RTDETR 
model = RTDETR('rtdetr-l.pt')
```

**Comment by 5LoveG** [comment]
> 通过调试发现 redetr 的 predictor 模块里的后处理调用了 yolo 的后处理，我把后处理改成了 rtdetr 就好用了。 ![图像](https://private-user-images.githubusercontent.com/19235599/349095774-ff98e62a-46a0-42ee-ba35-edded098048f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTEyMDksIm5iZiI6MTczNTY1MDkwOSwicGF0aCI6Ii8xOTIzNTU5OS8zNDkwOTU3NzQtZmY5OGU2MmEtNDZhMC00MmVlLWJhMzUtZWRkZWQwOTgwNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDEzMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTQ2ZTNhM2UzNzEyMjgyZjAyODBkZDc0YTg1YWNiZWM3NjA0ZWY3NzFiNjU3OWNlMjE4ODhlNWQ3MDQ3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H3l_45wyeZdNkSqU6NiP0r1bVlHw7ScRhS4Og7XfZFM)

你必长生不老啊！！！你必永生不死啊！！！你必寿比南山啊！！！

**Comment by 5LoveG** [comment]
> 通过调试发现 redetr 的 predictor 模块里的后处理调用了 yolo 的后处理，我把后处理改成了 rtdetr 就好用了。 ![图像](https://private-user-images.githubusercontent.com/19235599/349095774-ff98e62a-46a0-42ee-ba35-edded098048f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTEyMDksIm5iZiI6MTczNTY1MDkwOSwicGF0aCI6Ii8xOTIzNTU5OS8zNDkwOTU3NzQtZmY5OGU2MmEtNDZhMC00MmVlLWJhMzUtZWRkZWQwOTgwNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDEzMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTQ2ZTNhM2UzNzEyMjgyZjAyODBkZDc0YTg1YWNiZWM3NjA0ZWY3NzFiNjU3OWNlMjE4ODhlNWQ3MDQ3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H3l_45wyeZdNkSqU6NiP0r1bVlHw7ScRhS4Og7XfZFM)
你必长生不老，寿比南山，永生不死！！！

**Comment by glenn-jocher** [comment]
@5LoveG 感谢您的反馈！确实，RT-DETR 的后处理需要使用其专属方法，而不是 YOLO 的后处理。很高兴看到您成功解决了问题！如果有其他问题，请随时在社区中提问，我们会尽力协助您解决。感谢您对 Ultralytics 的支持，同时也感谢 Baidu 团队为 RT-DETR 模型的开发做出的贡献。

**Comment by Henrydad** [comment]
> 您好，我尝试了 YOLO RT-DETR 进行检测，并遇到了以下问题。我使用了“yolo train data=mydata.yaml model=rtdetr-l.pt epochs=50 imgsz=640 device=0”，它运行正常，但是当我使用“yolo predict source=mydata.yaml model=runs/detect/train/weights/best.pt”时，会出现关键错误： Ultralytics YOLOv8.2.48 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA：0 （NVIDIA RTX A4000， 16109MiB） rt-detr-l 总结：494 层，32004290 个参数，0 个梯度， 103.5 GFLOP
> 
> 回溯（最近一次调用最后）：文件 “/environment/miniconda3/bin/yolo”，第 8 行，在 sys.exit（entrypoint（）） 文件中 文件 “/environment/miniconda3/lib/python3.10/site-packages/ultralytics/cfg/**init**.py”，第 591 行，在入口点 getattr（model， mode）（**overrides） # 来自模型的默认参数 文件 “/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py”，第 442 行，在 predict 中如果 is_cli else，则返回 self.predictor.predict_cli（source=source） self.predictor（source=source， stream=stream） 文件 “/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py”，第 183 行，predict_cli for _ in gen： # sourcery skip： remove-empty-nested-block， noqa 文件 “/environment/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py”，第 35 行，generator_context响应 = gen.send（None）文件 “/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py”，第 274 行，stream_inference s[i] += self.write_results（i， Path（paths[i]）， im， s） 文件“/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py”，第 334 行，write_results字符串 += f“{result.verbose（）}{result.speed['inference']：.1f}ms”文件 “/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/results.py”，第 329 行，详细log_string += f“{n} {self.names[int（c）]}{'s' * （n > 1）}，” KeyError：180
> 
> 当我更改为预先训练的 rtdetr-l.pt 模型时，如下所示：“ ”yolo predict source=mydata.yaml model=rtdetr-l.pt“，它可以正常运行。我搜索了 YOLOv8 [问题](https://github.com/ultralytics/ultralytics/issues)，没有找到类似的问题。我想知道如何解决这个问题。谢谢！

Hello, I used “yolo train data=mydata.yaml model=rtdetr-l.pt epochs=50 imgsz=640 device=0” and during the training process, the loss often becomes zero, which severely affects the model’s performance. How did you resolve this issue?

**Comment by Henrydad** [comment]
> Hello, I tried YOLO RT-DETR for detection and met the following question. I used " yolo train data=mydata.yaml model=rtdetr-l.pt epochs=50 imgsz=640 device=0" and it ran OK, but when I use "yolo predict source=mydata.yaml model=runs/detect/train/weights/best.pt", a keyerror will occur: Ultralytics YOLOv8.2.48 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (NVIDIA RTX A4000, 16109MiB) rt-detr-l summary: 494 layers, 32004290 parameters, 0 gradients, 103.5 GFLOPs
> 
> Traceback (most recent call last): File "/environment/miniconda3/bin/yolo", line 8, in sys.exit(entrypoint()) File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/cfg/**init**.py", line 591, in entrypoint getattr(model, mode)(**overrides) # default args from model File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 442, in predict return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream) File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 183, in predict_cli for _ in gen: # sourcery skip: remove-empty-nested-block, noqa File "/environment/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context response = gen.send(None) File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 274, in stream_inference s[i] += self.write_results(i, Path(paths[i]), im, s) File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 334, in write_results string += f"{result.verbose()}{result.speed['inference']:.1f}ms" File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/results.py", line 329, in verbose log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, " KeyError: 180
> 
> And when I changed to the pre-trained rtdetr-l.pt model, as follows:" "yolo predict source=mydata.yaml model=rtdetr-l.pt"," it can run OK. I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar questions. I want to know how to solve this question. Thanks!

Hello, I used “yolo train data=mydata.yaml model=rtdetr-l.pt epochs=50 imgsz=640 device=0” and during the training process, the loss often becomes zero, which severely affects the model’s performance. How did you resolve this issue?

**Comment by glenn-jocher** [comment]
The issue of loss dropping to zero could indicate a problem with your dataset, such as incorrect or inconsistent labels, or a mismatch in the number of classes (`nc`) between your `mydata.yaml` file and the dataset. Verify your dataset annotations and ensure the `nc` value matches the number of classes. Additionally, make sure your images and labels are correctly paired and formatted. If the problem persists, consider reducing the learning rate or using a pre-trained model for better stability during training.
