### ISSUE TITLE
Problems with RT-DETR

### ISSUE THREAD

**Issue by houSusan** [ultralytics/ultralytics#14218]
Hello, I tried  YOLO RT-DETR for detection and met the following question.  I used " yolo train data=mydata.yaml model=rtdetr-l.pt epochs=50 imgsz=640 device=0"  and it ran OK, but when I use "yolo predict source=mydata.yaml model=runs/detect/train/weights/best.pt", a keyerror will occur:
Ultralytics YOLOv8.2.48 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (NVIDIA RTX A4000, 16109MiB)
rt-detr-l summary: 494 layers, 32004290 parameters, 0 gradients, 103.5 GFLOPs

Traceback (most recent call last):
  File "/environment/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 442, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 183, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 334, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "/environment/miniconda3/lib/python3.10/site-packages/ultralytics/engine/results.py", line 329, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 180

And when I changed to the pre-trained rtdetr-l.pt model, as follows:" "yolo predict source=mydata.yaml model=rtdetr-l.pt"," it can run OK.  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar questions.
I want to know how to solve this question. Thanks!

**Comment by glenn-jocher** [comment]
@houSusan hello,

Thank you for reaching out and providing detailed information about the issue you're encountering with RT-DETR.

The error you're seeing, `KeyError: 180`, typically indicates that the model is trying to access a class index that doesn't exist in the `names` dictionary. This can happen if the class indices in your custom dataset don't match those expected by the model.

To help diagnose and resolve this issue, please follow these steps:

1. **Verify Class Indices**: Ensure that the class indices in your `mydata.yaml` file match those used during training. The `names` dictionary should include all class indices used in your dataset.

2. **Check for Consistency**: Make sure that the `mydata.yaml` file used during training is the same one used during prediction. Any discrepancy in class names or indices can lead to such errors.

3. **Provide a Reproducible Example**: If the issue persists, it would be very helpful to have a minimum reproducible example. This will allow us to better understand the problem and provide a more accurate solution. You can find guidelines on how to create a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

4. **Update Packages**: Ensure you are using the latest versions of the Ultralytics YOLO package and its dependencies. Sometimes, issues are resolved in newer releases.

Here is a quick example of how you might check and update your class names:

```yaml
# mydata.yaml
train: path/to/train/images
val: path/to/val/images

nc: 3  # number of classes
names: ['class1', 'class2', 'class3']  # ensure these match your dataset
```

If you have verified that the class indices and names are consistent and the issue still occurs, please provide the relevant parts of your `mydata.yaml` file and any additional context that might help us reproduce the issue.

Thank you for your cooperation, and we look forward to helping you resolve this issue!

**Comment by Arthurwong77** [comment]
hi @houSusan 
I have the same problem and would like to ask how you solved it. Doing the detection directly with rtdetr-l.pt is fine, but not with the pt file that I trained myself. There is no problem with the dataset either.
Traceback (most recent call last):
  File "E:\anaconda\envs\v9\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "E:\anaconda\envs\v9\lib\site-packages\ultralytics\cfg\__init__.py", line 830, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "E:\anaconda\envs\v9\lib\site-packages\ultralytics\engine\model.py", line 562, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "E:\anaconda\envs\v9\lib\site-packages\ultralytics\engine\predictor.py", line 183, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "E:\anaconda\envs\v9\lib\site-packages\torch\autograd\grad_mode.py", line 45, in generator_context
    response = gen.send(None)
  File "E:\anaconda\envs\v9\lib\site-packages\ultralytics\engine\predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "E:\anaconda\envs\v9\lib\site-packages\ultralytics\engine\predictor.py", line 334, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "E:\anaconda\envs\v9\lib\site-packages\ultralytics\engine\results.py", line 633, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 153
The keyerror numbers may be a little different but the cause of the error is the same.

**Comment by Crotonix** [comment]
Have this issue resolved? This issue is faced when RTDETR is loaded with trained weights. Producing an MRE is difficult so elaborating the error.
`from ultralytics import RTDETR
model = RTDETR("./app/resources/best.pt")
result = model.predict("Image_1707372565447.jpg")`

Traceback:
`Traceback (most recent call last):
  File "/home/crotonix/rating/rating/try.py", line 5, in <module>
    result = model.predict(
  File "/home/crotonix/rating/rating/.venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/crotonix/rating/rating/.venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/crotonix/rating/rating/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/home/crotonix/rating/rating/.venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/home/crotonix/rating/rating/.venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 334, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "/home/crotonix/rating/rating/.venv/lib/python3.10/site-packages/ultralytics/engine/results.py", line 647, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 1995`

@glenn-jocher Not sure how the .yaml file with classes will affect the inference. Let's say I run the same code but with different weights of trained model YOLO.
`from ultralytics import YOLO
model = YOLO("./app/resources/best.pt")
result = model.predict("Image_1707372565447.jpg")`

This will run without errors and gives correct inference without even yaml file. I also checked by loading/printinh the .pt file using torch.load but found no metadata storing classes(not sure where classes are being stored in second case where it gave correct prediction). My only question - Was .yaml expected for inference for RTDETR but not for YOLO. If yes, why?

I also bypassed the error by `result = model.predict("Image_1707372565447.jpg", verbose=False)`. When i print `result[0].boxes.cls.tolist()` i get unexpected classes [8375.0, 6349.0, 8143.0, 8291.0, 6827.0, 7055.0, 8273.0, 8320.0, 3005.0, 7048.0]. This clearly means I need to provide .yaml which seems to be not consistent across all models.

**Comment by glenn-jocher** [comment]
@Crotonix thank you for your detailed report. Please ensure you're using the latest version of the Ultralytics package, as updates may resolve this issue. The `KeyError` typically indicates a mismatch in class indices. Verify that your `mydata.yaml` file is correctly referenced and consistent between training and inference. If the issue persists, please provide additional context or a minimal reproducible example.

**Comment by houSusan** [comment]
@Arthurwong77 Hi, My issue has resolved. The problem is that the postprocess in the predictor module of redetr calls the postprocess of yolo,  [T-TXiaoRui](https://github.com/T-TXiaoRui) has  solved this problem and provided the revised code. After I modify the code according to his method, RT-DETR predict works fine. Please refer to the details with  T-TXiaoRui‘s answer: https://github.com/ultralytics/ultralytics/issues/14219#
I would also like to thank everyone for their attention and help！

**Comment by bshakya77** [comment]
Hello @glenn-jocher,

I have trained `rtdetrv2_r50vd` model on `VisDrone2019` dataset. I saved the checkpoint for 50 epochs as `.pth`  format (by default). I do have `.onnx` format of the checkpoint. I would like to know if the `ultralytics` provide the way to `validate` and `predict` RT-DETRv2 model using `.onnx` or `.pth` format. I was trying to evaluate the inference time and GLOPs of the model.

Any feedback is appreciated.

Regards,
Bijay

**Comment by glenn-jocher** [comment]
Hello @bshakya77,

Thank you for your question. Currently, the Ultralytics framework supports validation and prediction using models in `.pt` format. For `.onnx` models, you can use the `yolo` CLI with the `--export` feature to convert supported formats and evaluate them. Unfortunately, `.pth` format is not directly supported by Ultralytics for RT-DETRv2 models. You may need to convert your `.pth` checkpoint to `.pt` format for compatibility.

For further details on export and supported formats, please refer to the [Export Documentation](https://docs.ultralytics.com/usage/cli/).

**Comment by bshakya77** [comment]
Hello @glenn-jocher,

Thank you for your quick response.

I converted the rtdetrv2 model from` .pth ` to` .pt` format using the following code

```
import torch

# Load the checkpoint file
checkpoint_path = "output/rtdetrv2_r50vd_6x_visdrone_50/last.pth"  # Replace with your file path
checkpoint = torch.load(checkpoint_path, map_location=torch.device("cpu"))

# Check the contents of "state_dict"
if "state_dict" in checkpoint:  # Check if 'state_dict' is a key in the checkpoint
    state_dict = checkpoint["state_dict"]
else:
    state_dict = checkpoint  # Directly use checkpoint if it is the state_dict

#model.load_state_dict(state_dict)
#device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#model = model.to(device).float()

torch.save(state_dict, 'rtdetrv2_r50_vd.pt')
```
It does save the model in` .pt` format.


But, I think it is not converted correctly. It gives following error when I load the .pt model 
as
```

from ultralytics import RTDETR
model = RTDETR('rtdetrv2_r50_vd.pt')
```

`AttributeError: 'dict' object has no attribute 'to'`

Keys in the `state_dict`:
```
date
last_epoch
model
criterion
postprocessor
ema
optimizer
lr_scheduler
lr_warmup_scheduler
```

Should I only load the `model ` key?

Your feedback is appreciated.

Regards,
Bijay

**Comment by glenn-jocher** [comment]
Hello @bshakya77,

The issue arises because the `.pt` file you saved contains only the `state_dict` and lacks the complete model architecture, which is necessary for loading it with the `RTDETR` class. Yes, you should isolate the `model` key from your checkpoint and save it properly, ensuring it includes both the architecture and weights. Alternatively, use the original framework’s tools to export the model in a format compatible with Ultralytics. Let me know if you need further clarification!

**Comment by bshakya77** [comment]
Hello @glenn-jocher,

The original RT-DETR repository only contains tools to export the model to `.onnx` format. I have either `.onnx` or `.yml` file of the model. If anyone of them is compatible with Ultralytics. I wanted to calculate the GFLOPs inference time of the model. If you can suggest any other alternative to calculate these metrics, that works too.

I appreciate your feedback.

Regards,
Bijay

**Comment by glenn-jocher** [comment]
Hello @bshakya77,

Currently, Ultralytics supports `.pt` and `.yaml` formats for RT-DETR models. To calculate GFLOPs and inference time, you can use tools like [torchinfo](https://github.com/TylerYep/torchinfo) for PyTorch models or [onnxruntime](https://onnxruntime.ai/) for `.onnx` models. If you're using `.onnx`, ensure the model is optimized and compatible with your framework for accurate benchmarking. Let us know if you need further assistance!

**Comment by bshakya77** [comment]
Hello @glenn-jocher,

I was training RT-DETRv2 model on DOTAv1.5 dataset. I converted the DOTAv1.5 dataset to COCO format in json files. 
I using  `NVIDIA A100 80GB PCIe` GPU.

I am using the following repository instructions:

https://github.com/lizhe1531/RT-DETRv2/tree/main

I am using the following model 
[rtdetrv2_r50vd_6x_coco.yml](https://github.com/lizhe1531/RT-DETRv2/blob/main/rtdetrv2_pytorch/configs/rtdetrv2/rtdetrv2_r50vd_6x_coco.yml)
 
When I trained the model. It starts the training and after certain time it gives me the following error:

`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.55 GiB. GPU 0 has a total capacity of 79.33 GiB of which 8.25 GiB is free. Including non-PyTorch memory, this process has 71.07 GiB memory in use. Of the allocated memory 59.19 GiB is allocated by PyTorch, and 10.26 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management `

`Test Cases:`
I tried to decrise batch size from 16 --> 8 --> 4. It works for 1 epochs and breaks again.
I tried to reduce the image size: 640 --> 320 --> 256. It gives the same error.

Could you please suggest what could be the issue?

Thank you.

Regards,
Bijay

**Comment by glenn-jocher** [comment]
Hi Bijay,

For CUDA memory issues with RT-DETRv2 training, please try these steps:

1. Set `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` as suggested in your error trace to reduce fragmentation
2. Use AMP (Automatic Mixed Precision) with `fp16=True` in your training config
3. Disable image caching in your dataset config with `cache=False`

Since you're using a third-party RT-DETRv2 implementation ([lizhe1531/RT-DETRv2](https://github.com/lizhe1531/RT-DETRv2)), we recommend consulting their repository's issues or maintainers for implementation-specific memory optimizations, as Ultralytics doesn't maintain this fork. 

For official RT-DETR support, see our [RT-DETR documentation](https://docs.ultralytics.com/models/rtdetr).

**Comment by bshakya77** [comment]
Hello @glenn-jocher,

Thank you for your response.

I will raise issue in their repository as well. I will definately try your suggestions. 

Thank you.

Regards,
Bijay

**Comment by glenn-jocher** [comment]
Hi Bijay,

For official Ultralytics RT-DETR models including RT-DETR-L and RT-DETR-X, you can download pretrained weights directly using either `RTDETR('rtdetr-l.pt')` in Python or `yolo predict model=rtdetr-l.pt` via CLI. These will auto-download from our repository. 

For third-party RT-DETRv2 implementations like [lizhe1531/RT-DETRv2](https://github.com/lizhe1531/RT-DETRv2), please contact that repository's maintainers directly as we don't host their checkpoints. Our official RT-DETR documentation is available at https://docs.ultralytics.com/models/rtdetr.

**Comment by bshakya77** [comment]
Hello @glenn-jocher,

I tried to train `RT-DETR-L` model on `DOTAv1.5 `dataset using `NVIDIA A100 80GB PCIe GPU`. It is working using `batch-size = 8`. But, when I used `batch-size=16`, it gives `torch.OutOfMemoryError: CUDA out of memory.`  I found that third-party RT-DETRv2 implementations like [lizhe1531/RT-DETRv2](https://github.com/lizhe1531/RT-DETRv2) has memory leak issue when using higher batch-size. Is it same issue with `ultralytics `model as well. Could you please check what could be the issue?

Thank you.

Regards,
Bijay

**Comment by glenn-jocher** [comment]
Hi Bijay,  
  
For Ultralytics RT-DETR models, we recommend:  
1. **Enable AMP** with `fp16=True` in training args  
2. Reduce image size (`imgsz`) if using >640  
3. Set `workers=0` to minimize RAM usage  
4. Check for background processes consuming GPU memory  

Our implementation doesn't have known memory leaks - see [RT-DETR training docs](https://docs.ultralytics.com/models/rtdetr) for optimization tips. For third-party implementations, please consult their maintainers. Let us know if these adjustments help! 🚀

**Comment by bshakya77** [comment]
Hello @glenn-jocher,

I tried your suggested hyperparameter arguments. However, it stills gives `torch.OutOfMemoryError: CUDA out of memory`  when I used batch-size=8 and batch-size=16. I used the following code for training.
Config: `NVIDIA A100 80GB PCIe GPU`

```
from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR("models/rtdetr-l.pt")

# Display model information (optional)
model.info()

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="DOTAv1.5.yaml", epochs=50, imgsz=640, batch=8, workers=0, amp=True, device=0)
```
Thank you.

Regards,
Bijay

**Comment by JiayuanWang-JW** [comment]
> Hi Bijay,
> 
> For Ultralytics RT-DETR models, we recommend:
> 
> 1. **Enable AMP** with `fp16=True` in training args
> 2. Reduce image size (`imgsz`) if using >640
> 3. Set `workers=0` to minimize RAM usage
> 4. Check for background processes consuming GPU memory
> 
> Our implementation doesn't have known memory leaks - see [RT-DETR training docs](https://docs.ultralytics.com/models/rtdetr) for optimization tips. For third-party implementations, please consult their maintainers. Let us know if these adjustments help! 🚀

Hi @glenn-jocher,

I met the same issue that I found the leak from the dataloader. After I set pin_memory=PIN_MEMORY to pin_memory=False, the problem was solved. However, this will slow the training, especially in large datasets. Do you have any suggestions? I am working with reduce the num_workers. I am not sure if this is work or not. You know it is really hard to find the issue because the procedure only collapses after 200 epochs because the RAM continuously increases. BTW, I do the DDP, not a single card to training.

Thanks

**Comment by glenn-jocher** [comment]
Hi @JiayuanWang-JW,

For DDP memory leaks in RT-DETR training, we recommend:  
1. Try our updated `ultralytics==8.2.51` with memory optimizations  
2. Monitor GPU memory trends using `watch -n 1 nvidia-smi` during training  
3. Consider using `persistent_workers=False` in dataloader config if using custom code  

There's an existing discussion and solution in [#14219](https://github.com/ultralytics/ultralytics/issues/14219) that resolved similar DDP memory issues. Please share a [Minimal Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) if this persists.

**Comment by JiayuanWang-JW** [comment]
> Hi [@JiayuanWang-JW](https://github.com/JiayuanWang-JW),
> 
> For DDP memory leaks in RT-DETR training, we recommend:
> 
> 1. Try our updated `ultralytics==8.2.51` with memory optimizations
> 2. Monitor GPU memory trends using `watch -n 1 nvidia-smi` during training
> 3. Consider using `persistent_workers=False` in dataloader config if using custom code
> 
> There's an existing discussion and solution in [#14219](https://github.com/ultralytics/ultralytics/issues/14219) that resolved similar DDP memory issues. Please share a [Minimal Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) if this persists.

Thanks for your information. However, I checked the #14219. However I didn't find any discussion and solution for DDP memory issue. Could you please let me know what solution is it?

For the potential solutions you mentioned:
1. My ultralytics version is YOLOv8.2.99. I checked the code, it includes _clear_memory function in trainer.py. 
2. GPU memory is stable. Only CPU RAM continuously increases.
3. I checked torch dataloader function, persistent_workers=False is the default. I didn't change build_dataset functions.

**Comment by glenn-jocher** [comment]
Hi @JiayuanWang-JW,

For DDP RAM leaks during training, please try adding `pin_memory=False` to your dataloader configuration. This resolves a known issue where pinned memory isn't properly released between epochs in distributed training. The solution was implemented in our latest memory management improvements but requires explicit configuration for DDP use cases.

If you continue experiencing RAM growth, please share a [Minimal Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) so we can investigate further. 

Thanks for your diligence in tracking this! 🚀

**Comment by JiayuanWang-JW** [comment]
> Hi [@JiayuanWang-JW](https://github.com/JiayuanWang-JW),
> 
> For DDP RAM leaks during training, please try adding `pin_memory=False` to your dataloader configuration. This resolves a known issue where pinned memory isn't properly released between epochs in distributed training. The solution was implemented in our latest memory management improvements but requires explicit configuration for DDP use cases.
> 
> If you continue experiencing RAM growth, please share a [Minimal Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) so we can investigate further.
> 
> Thanks for your diligence in tracking this! 🚀

Thanks for your reply. Yes, I did this operation before, and it successfully addressed the RAM growth issue. But it will slow the training. As I mentioned in my previous [reply ](https://github.com/ultralytics/ultralytics/issues/14218#issuecomment-2631925804)"I met the same issue that I found the leak from the dataloader. After I set pin_memory=PIN_MEMORY to pin_memory=False, the problem was solved. However, this will slow the training, especially in large datasets." 

I am looking for other potential solutions to avoid slowing the training.

**Comment by glenn-jocher** [comment]
Hi @JiayuanWang-JW,  

For DDP training speed optimization while maintaining memory stability, you could try:  
1. Keeping `pin_memory=True` but adding manual garbage collection via `gc.collect()` in your training loop  
2. Using `persistent_workers=True` with reduced `num_workers` as a middle ground  

These adjustments might help balance memory usage and performance. Let us know if you'd like help implementing either approach.

**Comment by JiayuanWang-JW** [comment]
> Hi [@JiayuanWang-JW](https://github.com/JiayuanWang-JW),
> 
> For DDP training speed optimization while maintaining memory stability, you could try:
> 
> 1. Keeping `pin_memory=True` but adding manual garbage collection via `gc.collect()` in your training loop
> 2. Using `persistent_workers=True` with reduced `num_workers` as a middle ground
> 
> These adjustments might help balance memory usage and performance. Let us know if you'd like help implementing either approach.

Hi @glenn-jocher,

After I carefully debugged, I found the problem was after close mosaic augmentation, the RAM would grow. 

So far, I tried below operation:
1. set ``pin_memory=False``, this works, but slow the training.
2. set ``pin_memory=True`` and reduce ``num_workers``, this doesn't work, and RAM still grows after a closed mosaic epoch.

Note: both above operations under ``persistent_workers=False``.

One more thing, the current ``ultralytics==8.2.99`` version includes the ``gc.collect()`` mechanism during the [training](https://github.com/ultralytics/ultralytics/blob/580b4766c52c1404b6ded6f88860b2ad13117236/ultralytics/engine/trainer.py#L454).

**Comment by glenn-jocher** [comment]
Hi @JiayuanWang-JW,

Thanks for the detailed analysis. We've observed similar mosaic-related memory patterns in DDP training. Our engineers are investigating a potential fix involving explicit dataset resets after mosaic closure. For now, you might try:

1. Adding explicit `gc.collect()` calls **after** mosaic closure in your training loop
2. Using `torch.cuda.empty_cache()` post-mosaic with `pin_memory=True`

These steps could help mitigate RAM growth while maintaining performance. We'll update you when we have a more robust solution in the pipeline. 🛠️
