### ISSUE TITLE
ultralytics/examples/YOLOv8-CPP-Inference/

### ISSUE THREAD

**Issue by rathorology** [ultralytics/ultralytics#14377]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

ultralytics/examples/YOLOv8-CPP-Inference/build$ ./Yolov8CPPInference 

Running on CPU
after blob
model shape width640
model shape height480
4    1,3,480,640,
[ERROR:0@0.071] global net_impl.cpp:1162 getLayerShapesRecursively OPENCV/DNN: [Reshape]:(onnx_node!/model.22/dfl/Reshape): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0@0.071] global net_impl.cpp:1168 getLayerShapesRecursively     input[0] = [ 1 64 6300 ]
[ERROR:0@0.071] global net_impl.cpp:1172 getLayerShapesRecursively     output[0] = [ ]
[ERROR:0@0.071] global net_impl.cpp:1178 getLayerShapesRecursively Exception message: OpenCV(4.10.0-dev) /home/ai/opencv/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.10.0-dev) /home/ai/opencv/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

Aborted (core dumped)

### Minimal Reproducible Example

Used :-
ultralytics/examples/YOLOv8-CPP-Inference/

### Additional

Using pretrained yolov8n.pt to converted it to onnx and trying to predict it on bus.jpg image provided by ultranalytics.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rathorology thank you for reporting this issue and providing detailed information. It seems like you're encountering an error related to the `Reshape` layer when running YOLOv8 inference using OpenCV's DNN module.

To help us diagnose the problem more effectively, could you please provide a minimal reproducible example? This will allow us to replicate the issue on our end and investigate further. You can find guidelines on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure that you are using the latest versions of all relevant packages, including OpenCV and the Ultralytics YOLOv8 repository. Sometimes, updating to the latest versions can resolve unexpected issues.

Here's a quick checklist to verify:
1. **Update OpenCV**: Ensure you are using the latest stable version of OpenCV. You can update it using pip:
   ```bash
   pip install --upgrade opencv-python-headless
   ```
2. **Update YOLOv8**: Make sure you have the latest version of the Ultralytics YOLOv8 repository:
   ```bash
   pip install --upgrade ultralytics
   ```

Additionally, if you have any custom modifications or specific configurations, please share those details as well.

Looking forward to your response so we can assist you further! 😊

**Comment by ouening** [comment]
ultralytics: 8.2.99 (from `yolo -v`)
opencv (c++): 4.10 (compiled from source using mingw 11.2 in Windows 10)
mingw64: 11.2.0

I have the same issue using example *YOLOv8-CPP-Inference*. The model is generated from : `yolo export model=yolov8s.pt imgsz=480,640 format=onnx opset=12`

Error message:
```html
Running on CUDA
[ WARN:0@0.165] global net_impl.cpp:178 setUpNet DNN module was not built with CUDA backend; switching to CPU
[ERROR:0@0.184] global net_impl.cpp:1162 getLayerShapesRecursively OPENCV/DNN: [Reshape]:(onnx_node!/model.22/dfl/Reshape): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0@0.185] global net_impl.cpp:1168 getLayerShapesRecursively     input[0] = [ 1 64 8400 ]
[ERROR:0@0.186] global net_impl.cpp:1172 getLayerShapesRecursively     output[0] = [ ]
[ERROR:0@0.188] global net_impl.cpp:1178 getLayerShapesRecursively Exception message: OpenCV(4.10.0) E:\ScienceComputing\opencv\sources\modules\dnn\src\layers\reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'
```

**Comment by ouening** [comment]
I also tried the opencv-onnx version. Same error occured when inferencing:
```html
E:\DeepLearning\ultralytics\examples\YOLOv8-CPP-Inference: python main.py --model yolov8s.onnx --img assets\bus.jpg
[ERROR:0@5.615] global net_impl.cpp:1165 cv::dnn::dnn4_v20240521::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Reshape]:(onnx_node!/model.22/dfl/Reshape): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0@5.636] global net_impl.cpp:1168 cv::dnn::dnn4_v20240521::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 64 8400 ]
[ERROR:0@5.640] global net_impl.cpp:1172 cv::dnn::dnn4_v20240521::Net::Impl::getLayerShapesRecursively     output[0] = [ ]
[ERROR:0@5.643] global net_impl.cpp:1178 cv::dnn::dnn4_v20240521::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'

Traceback (most recent call last):
  File "E:\DeepLearning\ultralytics\examples\YOLOv8-CPP-Inference\main.py", line 130, in <module>
    main(args.model, args.img)
  File "E:\DeepLearning\ultralytics\examples\YOLOv8-CPP-Inference\main.py", line 65, in main
    outputs = model.forward()
              ^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'
```

**Comment by ouening** [comment]
I solved the problem! We should use the default opset. Maybe the document in example is too old. The right way to export onnx file is:
```html
 yolo export model=yolov8s.pt format=onnx imgsz=640
Ultralytics YOLOv8.2.99 🚀 Python-3.12.3 torch-2.4.1+cpu CPU (Intel Core(TM) i5-9400F 2.90GHz)
YOLOv8s summary (fused): 168 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs

PyTorch: starting from 'yolov8s.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (21.5 MB)

ONNX: starting export with onnx 1.16.2 opset 19...
ONNX: export success ✅ 2.5s, saved as 'yolov8s.onnx' (42.8 MB)

Export complete (3.2s)
Results saved to E:\DeepLearning\ultralytics\examples\YOLOv8-CPP-Inference
Predict:         yolo predict task=detect model=yolov8s.onnx imgsz=640
Validate:        yolo val task=detect model=yolov8s.onnx imgsz=640 data=coco.yaml
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export
 ```

**Comment by glenn-jocher** [comment]
Great to hear you resolved the issue! Using the default opset is indeed the recommended approach. If you have any more questions or need further assistance, feel free to ask.
