### ISSUE TITLE
Unable to export RT-DETR model to TFLite or EdgeTPU

### ISSUE THREAD

**Issue by isuchy** [ultralytics/ultralytics#14398]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/rtdetr-l.pt to 'rtdetr-l.pt'...
100%|██████████| 63.4M/63.4M [00:00<00:00, 174MB/s]
Ultralytics YOLOv8.2.51 🚀 Python-3.10.12 torch-2.3.0+cu121 CPU (Intel Xeon 2.20GHz)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients, 103.8 GFLOPs

PyTorch: starting from '/content/rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)
requirements: Ultralytics requirements ['sng4onnx>=1.0.1', 'onnx_graphsurgeon>=0.3.26', 'onnx>=1.12.0', 'onnx2tf>1.17.5,<=1.22.3', 'onnxslim>=0.1.31', 'tflite_support', 'onnxruntime'] not found, attempting AutoUpdate...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting sng4onnx>=1.0.1
  Downloading sng4onnx-1.0.4-py3-none-any.whl (5.9 kB)
Collecting onnx_graphsurgeon>=0.3.26
  Downloading onnx_graphsurgeon-0.5.2-py2.py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 886.8 kB/s eta 0:00:00
Collecting onnx>=1.12.0
  Downloading onnx-1.16.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 95.3 MB/s eta 0:00:00
Collecting onnx2tf<=1.22.3,>1.17.5
  Downloading onnx2tf-1.22.3-py3-none-any.whl (435 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 435.0/435.0 kB 121.0 MB/s eta 0:00:00
Collecting onnxslim>=0.1.31
  Downloading onnxslim-0.1.31-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.4/128.4 kB 100.9 MB/s eta 0:00:00
Collecting tflite_support
  Downloading tflite_support-0.4.4-cp310-cp310-manylinux2014_x86_64.whl (60.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 MB 85.3 MB/s eta 0:00:00
Collecting onnxruntime
  Downloading onnxruntime-1.18.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 99.1 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from onnx_graphsurgeon>=0.3.26) (1.25.2)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx>=1.12.0) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxslim>=0.1.31) (1.13.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from onnxslim>=0.1.31) (24.1)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tflite_support) (1.4.0)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tflite_support) (24.3.25)
Collecting sounddevice>=0.4.4 (from tflite_support)
  Downloading sounddevice-0.4.7-py3-none-any.whl (32 kB)
Collecting pybind11>=2.6.0 (from tflite_support)
  Downloading pybind11-2.13.1-py3-none-any.whl (238 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.8/238.8 kB 126.5 MB/s eta 0:00:00
Collecting coloredlogs (from onnxruntime)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 134.1 MB/s eta 0:00:00
Requirement already satisfied: CFFI>=1.0 in /usr/local/lib/python3.10/dist-packages (from sounddevice>=0.4.4->tflite_support) (1.16.0)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 45.5 MB/s eta 0:00:00
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxslim>=0.1.31) (1.3.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from CFFI>=1.0->sounddevice>=0.4.4->tflite_support) (2.22)
Installing collected packages: sng4onnx, pybind11, onnx2tf, onnx, humanfriendly, sounddevice, onnxslim, onnx_graphsurgeon, coloredlogs, tflite_support, onnxruntime
Successfully installed coloredlogs-15.0.1 humanfriendly-10.0 onnx-1.16.1 onnx2tf-1.22.3 onnx_graphsurgeon-0.5.2 onnxruntime-1.18.1 onnxslim-0.1.31 pybind11-2.13.1 sng4onnx-1.0.4 sounddevice-0.4.7 tflite_support-0.4.4

requirements: AutoUpdate success ✅ 24.2s, installed 7 packages: ['sng4onnx>=1.0.1', 'onnx_graphsurgeon>=0.3.26', 'onnx>=1.12.0', 'onnx2tf>1.17.5,<=1.22.3', 'onnxslim>=0.1.31', 'tflite_support', 'onnxruntime']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

TensorFlow SavedModel: starting export with tensorflow 2.15.0...
Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100% 1.11M/1.11M [00:00<00:00, 18.9MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /content/calibration_image_sample_data_20x128x128x3_float32.npy...: 100% 1/1 [00:00<00:00, 28.21file/s]

ONNX: starting export with onnx 1.16.1 opset 17...
ONNX: slimming with onnxslim 0.1.31...
ONNX: export success ✅ 28.1s, saved as '/content/rtdetr-l.onnx' (125.6 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid model. Node input 'wa/model.0/Pad_output_0' is not a graph input, initializer, or output of a previous node.
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/MaxPool.py", line 65, in make_node
    input_tensor = tf_layers_dict[graph_node_input.name]['tf_node'] \
KeyError: 'wa/model.0/Pad_output_0'

ERROR: input_onnx_file_path: /content/rtdetr-l.onnx
ERROR: onnx_op_name: wa/model.0/pool/MaxPool
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

### Environment

Ultralytics YOLOv8.2.51 🚀 Python-3.10.12 torch-2.3.0+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 30.6/225.8 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.20GHz
CUDA                None

numpy               ✅ 1.25.2<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.3.0+cu121>=1.8.0
torchvision         ✅ 0.18.0+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

```
!pip install ultralytics==8.2.51

import torch
from ultralytics import YOLO
from ultralytics import RTDETR

model = RTDETR('rtdetr-l.pt')

!yolo export model=/content/rtdetr-l.pt format=edgetpu
```

### Additional

I searched Issues first and found some relevant Issues to the problem I'm facing, e.g. [here](https://github.com/ultralytics/ultralytics/issues/9226) or [here](https://github.com/ultralytics/ultralytics/issues/14235), but in none of them is there a working solution, or proven that it can't be solved that way.

I have tried with the latest version of Ultralytics to export the vanilla RT-DETR model to TFLite or EdgeTPU format. It crashes, as you can see in the attached listing above. I also tried exporting the model to ONNX, which worked fine, but ONNX to TFLite crashed again. 

Is this a bug in the export module, alternatively is there any workaround? Thank you.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@isuchy thank you for your detailed report and for providing a reproducible example. It’s very helpful! 🌟

It appears that the issue arises during the conversion from ONNX to TFLite, specifically with the `onnx2tf` tool. The error message suggests that there might be a problem with dynamic dimensions or unsupported operations in the model.

Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Static Shape Conversion**: Try converting the model with static shapes. You can use the `-b` or `-ois` options in `onnx2tf` to rewrite dynamic dimensions to static shapes. This might help in resolving the issue with the `MaxPool` operation.

2. **Parameter Replacement**: Follow the guidance provided in the error message to replace parameters. Refer to the [onnx2tf parameter replacement documentation](https://github.com/PINTO0309/onnx2tf#parameter-replacement) for detailed instructions.

3. **Model Input Format**: Ensure that the input format is consistent. If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the `-kt` or `-kat` options.

4. **NonMaxSuppression**: If your model includes NonMaxSuppression in the post-processing, try using the `-onwdt` option.

Here’s an example of how you might modify your conversion command:

```bash
onnx2tf -i /content/rtdetr-l.onnx -o /content/rtdetr-l_tflite --onnx2tf-params -b -kt
```

Additionally, please ensure you are using the latest versions of all relevant packages, as updates often include important bug fixes and improvements.

If the issue persists after trying these steps, it might be a limitation or bug within the `onnx2tf` tool itself. In such cases, reporting the issue to the `onnx2tf` repository with detailed logs can help the maintainers address it.

For more detailed guidance, you can refer to the [Ultralytics Export Documentation](https://docs.ultralytics.com/reference/engine/exporter/).

Thank you for your patience and understanding. If you have any further questions or need additional assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
@isuchy also for any type of export workflow I'd use YOLOv8. Faster and better than RTDETR.

**Comment by glenn-jocher** [comment]
For ONNX2TF-specific error messages too please raise an issue directly with https://github.com/PINTO0309/onnx2tf as these are probably outside the scope of what we can fix here.
