### ISSUE TITLE
got an unexpected keyword argument 'allow_empty

### ISSUE THREAD

**Issue by alikarimi120** [ultralytics/ultralytics#14410]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Ultralytics YOLOv8.2.55 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24257MiB)
engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=../my_data, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train17, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train17
train: /media/user/my_data/train... found 2458 images in 3 classes ✅ 
val: /media/user/val... found 694 images in 3 classes ✅ 
test: /media/user/test... found 694 images in 3 classes ✅ 
Overriding model.yaml nc=1000 with nc=3

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    334083  ultralytics.nn.modules.head.Classify         [256, 3]                      
YOLOv8n-cls summary: 99 layers, 1,442,131 parameters, 1,442,131 gradients, 3.4 GFLOPs
Transferred 156/158 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/classify/train17', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
Traceback (most recent call last):
  File "/media/user/train.py", line 9, in <module>
    results = model.train(data="../my_data", epochs=100, imgsz=640)
  File "/media/user/OtherDisk/venv/yolo8/lib/python3.10/site-packages/ultralytics/engine/model.py", line 650, in train
    self.trainer.train()
  File "/media/user/OtherDisk/venv/yolo8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 204, in train
    self._do_train(world_size)
  File "/media/user/OtherDisk/venv/yolo8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 323, in _do_train
    self._setup_train(world_size)
  File "/media/user/OtherDisk/venv/yolo8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 287, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
  File "/media/user/OtherDisk/venv/yolo8/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py", line 80, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode)
  File "/media/user/OtherDisk/venv/yolo8/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py", line 75, in build_dataset
    return ClassificationDataset(root=img_path, args=self.args, augment=mode == "train", prefix=mode)
  File "/media/user/OtherDisk/venv/yolo8/lib/python3.10/site-packages/ultralytics/data/dataset.py", line 421, in __init__
    self.base = torchvision.datasets.ImageFolder(root=root, allow_empty=True)
TypeError: ImageFolder.__init__() got an unexpected keyword argument 'allow_empty'

### Environment

Ultralytics YOLOv8.2.55 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24257MiB)
RAM=128

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model

model = YOLO("yolov8n-cls.pt")  # load a pretrained model (recommended for training)

# Train the model
results = model.train(data="../my_data", epochs=100, imgsz=640)

### Additional

my code:

from ultralytics import YOLO
model = YOLO("yolov8n-cls.pt")  # load a pretrained model (recommended for training)
results = model.train(data="../my_data", epochs=100, imgsz=640)

I got this error for image classification task :

self.base = torchvision.datasets.ImageFolder(root=root, allow_empty=True)
TypeError: ImageFolder.__init__() got an unexpected keyword argument 'allow_empty'

library version:
ultralytics-8.2.55
torch version = 2.0.1
torchvision version = 1.15.2

Solution:
downgrade ultralytics version => 8.1.18

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@alikarimi120 thank you for reporting this issue! It appears that the `allow_empty` argument is not recognized by the `torchvision.datasets.ImageFolder` class in your current setup.

To help us diagnose and resolve this issue more effectively, could you please provide a minimal reproducible example? This will allow us to replicate the problem on our end. You can find guidelines on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of the Ultralytics and torchvision packages. You can update them using the following commands:

```bash
pip install --upgrade ultralytics
pip install --upgrade torchvision
```

If the issue persists after updating, please let us know. Your feedback is invaluable in helping us improve the software. Thank you for your cooperation! 😊

**Comment by glenn-jocher** [comment]
@alikarimi120 after some more review I see this bug was introduced because the keyword is only available in torchvision 0.18 and later: https://pytorch.org/vision/0.18/generated/torchvision.datasets.ImageFolder.html?highlight=torchvision+datasets+imagefolder#torchvision.datasets.ImageFolder

I'll try to fix this ASAP, apologies for the inconvenience and thanks for letting us know!

**Comment by glenn-jocher** [comment]
Great news 😃! Your original issue may now be resolved ✅ in PR #14415. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
