### ISSUE TITLE
AttributeError: 'Pose' object has no attribute 'detect'

### ISSUE THREAD

**Issue by hhhzr** [ultralytics/ultralytics#14466]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Traceback (most recent call last):
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\v8detect_wx.py", line 230, in <module>
    frame = process_frame(frame)
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\v8detect_wx.py", line 68, in process_frame
    results = model(img_bgr, verbose=False)  # verbose设置为False，不单独打印每一帧预测结果
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\ultralytics\engine\model.py", line 98, in __call__
    return self.predict(source, stream, **kwargs)
  File "D:\Anaconda\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\ultralytics\engine\model.py", line 246, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\ultralytics\engine\predictor.py", line 197, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "D:\Anaconda\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\ultralytics\engine\predictor.py", line 237, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\ultralytics\nn\autobackend.py", line 465, in warmup
    self.forward(im)  # warmup
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\ultralytics\nn\autobackend.py", line 334, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "D:\Anaconda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Pycharm\Py_Projects\YOLOv8_cs-main\ultralytics\nn\tasks.py", line 45, in forward
    return self.predict(x, *args, **kwargs)
  File "D:\Pycharm\Py_Proje

### Environment

Ultralytic==8.2.56

### Minimal Reproducible Example

import cv2
import numpy as np
import time
import torch
from ultralytics import YOLO

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

model = YOLO("D:/Pycharm/Py_Projects/YOLOv8_cs-main/best.pt")

model.to(device)

# 获取摄像头，传入0表示获取系统默认摄像头
cap = cv2.VideoCapture(0)

def process_frame(img_bgr):

    string = ('Volt:' + str(round(read_result, 1))) # 写在画面上的字符串
    img_bgr = cv2.putText(img_bgr, string,(25, 60), cv2.FONT_HERSHEY_PLAIN, 1, (255, 0, 0), 2)
    #print(FPS)

    return img_bgr

cap.open(0)

while cap.isOpened():

    success, frame = cap.read()

    if not success:  # 如果获取画面不成功，则退出+
        print('获取画面不成功，退出')
        break

    frame = process_frame(frame)

    #frame = cv2.resize(frame, (1920, 1080))

    cv2.imshow('my_window', frame)

    key_pressed = cv2.waitKey(60)  # 每隔多少毫秒毫秒，获取键盘哪个键被按下
    # print('键盘上被按下的键：', key_pressed)

    if key_pressed in [ord('q'), 27]:  # 按键盘上的q或esc退出（在英文输入法下）
        break

cap.release()

cv2.destroyAllWindows()

### Additional

I have tried to upgrade to the latest version, but the problem persists, and it works successfully with yolov8n-pose

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@hhhzr it looks like you're encountering an `AttributeError` because the 'Pose' object does not have a 'detect' attribute. This issue might be related to how the model is being called. Since you've mentioned that it works with `yolov8n-pose`, it seems like the model type might be causing the issue.

First, ensure that you are using the latest version of the Ultralytics package. If the issue persists, double-check the model type you are loading. If you are using a custom model, make sure it is compatible with the `predict` or `track` methods.

If the problem continues, please provide more details about the custom model you are using, or try using a different model to see if the issue is specific to the model type. This will help narrow down the cause of the error.

**Comment by glenn-jocher** [comment]
@hhhzr it seems like you're encountering an issue because the `Pose` object does not have a `detect` attribute. Please ensure you are using the correct methods for pose estimation. If the issue persists, try updating to the latest version of the Ultralytics package. If you still face problems, please provide more details or consider submitting a PR. Thank you!
