### ISSUE TITLE
Export - Ultralytics YOLOv8 model to TFJS

### ISSUE THREAD

**Issue by Yiusing** [ultralytics/ultralytics#14493]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,I have installed all the necessary libraries according to the official documentation, but I still cannot successfully export yolov8.pt to tfjs format.

Am I missing any dependencies, or are the versions of certain dependency libraries incorrect?

Environment：
```
OS                  Windows10

- Python                        3.8.19   
- numpy                         1.24.1                  
- onnx                          1.16.1          
- onnx-graphsurgeon             0.5.2           
- onnx2tf                       1.20.0          
- onnxruntime                   1.18.1          
- onnxslim                      0.1.32          
- psutil                        6.0.0           
- tensorboard-data-server       0.7.2           
- tensorflow                    2.13.0          
- tensorflow-cpu                2.13.0          
- tensorflow-estimator          2.13.0          
- tensorflow-intel              2.13.0          
- tensorflow-io-gcs-filesystem  0.31.0       
- tf-keras                      2.15.0          
- torch                         2.3.1+cu118     
- torchaudio                    2.3.1+cu118     
- torchvision                   0.18.1+cu118    
- ultralytics                   8.2.58          
```

Code:
```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.export(format='tfjs')
```

Logs:
```
Ultralytics YOLOv8.2.58 🚀 Python-3.8.19 torch-2.3.1+cu118 CPU (12th Gen Intel Core(TM) i7-12700)
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.0...

ONNX: starting export with onnx 1.16.1 opset 17...
ONNX: slimming with onnxslim 0.1.32...
ONNX: export success ✅ 1.4s, saved as 'yolov8n.onnx' (12.2 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.20.0...

ERROR: The trace log is below.
Traceback (most recent call last):
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\onnx2tf\utils\common_functions.py", line 310, in print_wrapper_func        
    result = func(*args, **kwargs)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\onnx2tf\utils\common_functions.py", line 383, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\onnx2tf\utils\common_functions.py", line 53, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\onnx2tf\ops\Resize.py", line 417, in make_node
    resized_tensor = Lambda(
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1045, in __call__      
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\keras\layers\core.py", line 913, in call
    result = self.function(inputs, **kwargs)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\onnx2tf\utils\common_functions.py", line 1142, in upsampling2d_nearest     
    return tf.compat.v1.image.resize_nearest_neighbor(
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 4769, in resize_nearest_neighbor
    return gen_image_ops.resize_nearest_neighbor(
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\ops\gen_image_ops.py", line 4376, in resize_nearest_neighbor
    return resize_nearest_neighbor_eager_fallback(
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\ops\gen_image_ops.py", line 4414, in resize_nearest_neighbor_eager_fallback
    _attr_T, (images,) = _execute.args_to_matching_eager([images], ctx, [_dtypes.int8, _dtypes.uint8, _dtypes.int16, _dtypes.uint16, _dtypes.int32, _dtypes.int64, _dtypes.half, _dtypes.float32, _dtypes.float64, _dtypes.bfloat16, ])
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\eager\execute.py", line 251, in args_to_matching_eager   
    tensor = tensor_conversion_registry.convert(t)
nvert
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\framework\constant_op.py", line 324, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\framework\constant_op.py", line 263, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\framework\constant_op.py", line 275, in _constant_impl   
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\framework\constant_op.py", line 285, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\tensorflow\python\framework\constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
  File "C:\Users\yiusing\miniconda3\envs\newTest3.8\lib\site-packages\keras\src\engine\keras_tensor.py", line 285, in __array__
    raise TypeError(
TypeError: You are passing KerasTensor(type_spec=TensorSpec(shape=(1, 20, 20, 256), dtype=tf.float32, name=None), name='tf.math.multiply_119/Mul:0', description="created by layer 'tf.math.multiply_119'"), an intermediate Keras symbolic input/output, to a TF API that does not allow registering custom dispatchers, such as `tf.cond`, `tf.function`, gradient tapes, or `tf.map_fn`. Keras Functional model construction only supports TF API calls that *do* support dispatching, such as `tf.math.add` or `tf.reshape`. Other APIs cannot be called directly on symbolic Kerasinputs/outputs. You can work around this limitation by putting the operation in a custom Keras layer `call` and calling that layer on this symbolic input/output.
```

**Comment by pderrenger** [comment]
@Yiusing hi there! It looks like you're encountering an issue during the export process to TensorFlow.js. Given the error trace, it seems to be related to the `onnx2tf` conversion step. 

First, ensure you're using the latest versions of all dependencies, especially `onnx2tf` and `tensorflow`. Sometimes, compatibility issues arise from version mismatches. Additionally, you might want to try running the export on a different environment or machine to rule out any local configuration issues.

If the problem persists, please try updating your TensorFlow to the latest version and re-run the export process. If the issue still occurs, it might be worth checking the `onnx2tf` GitHub repository for any similar issues or updates.

For more detailed guidance, you can refer to our [TF.js integration documentation](https://docs.ultralytics.com/integrations/tfjs/). Let us know how it goes!

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301
