### ISSUE TITLE
Application of SAHI in YOLOV8-OBB mission

### ISSUE THREAD

**Issue by 050603** [ultralytics/ultralytics#14494]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask how to apply SAHI on yolov8x-obb model to improve detection? I don't see SAHI tutorials in the ultralytics community  covering x-size models or OBB tasks.

I used one of these methods and reported an error after performing the experiment.
`
from sahi import AutoDetectionModel

detection_model = AutoDetectionModel.from_pretrained(
    model_type="yolov8",
    model_path="/root/autodl-tmp/code/ultralytics/runs/obb/train/weights/best.pt",
    confidence_threshold=0.3,
    device="cuda:0"  
)

from sahi.predict import get_prediction
from sahi.utils.cv import read_image

from sahi.predict import get_sliced_prediction

result = get_sliced_prediction(
    "/root/autodl-tmp/DOTA/images/test/P0006.png",
    detection_model,
    slice_height=256,
    slice_width=256,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2,
)

result.export_visuals(export_dir="/root/autodl-tmp/code/obb/SAHI/")

`

`Performing prediction on 40 slices.
Traceback (most recent call last):
  File "/root/autodl-tmp/code/obb/SAHI.py", line 21, in <module>
    result = get_sliced_prediction(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/sahi/predict.py", line 249, in get_sliced_prediction
    prediction_result = get_prediction(
                        ^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/sahi/predict.py", line 93, in get_prediction
    detection_model.perform_inference(np.ascontiguousarray(image_as_pil))
  File "/root/miniconda3/lib/python3.12/site-packages/sahi/models/yolov8.py", line 92, in perform_inference
    prediction_result = [result.boxes.data for result in prediction_result]
                         ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'`

**Comment by Y-T-G** [comment]
It's the a SAHI problem. You can create an issue in their repo.
