### ISSUE TITLE
Error in TensorFlow Lite export for YOLOv8 model 

### ISSUE THREAD

**Issue by mondiriariana** [ultralytics/ultralytics#14509]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export, Integrations, Other

### Bug

I'm encountering an issue while trying to export my YOLOv8 model to TensorFlow Lite format.

I am following the tutorial provided in the documentation: https://docs.ultralytics.com/integrations/tflite/#usage

```
Ultralytics YOLOv8.1.34 🚀 Python-3.10.12 torch-2.3.0+cu121 CPU (Intel Xeon 2.00GHz)
YOLOv10n summary (fused): 285 layers, 2694806 parameters, 0 gradients, 8.2 GFLOPs

PyTorch: starting from '/content/drive/MyDrive/save/yolo/ball_ainex2/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (5.5 MB)
requirements: Ultralytics requirement ['onnxruntime-gpu'] not found, attempting AutoUpdate...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Collecting onnxruntime-gpu
  Downloading onnxruntime_gpu-1.18.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (200.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.8/200.8 MB 348.7 MB/s eta 0:00:00
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.10/dist-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime-gpu) (24.3.25)
Requirement already satisfied: numpy<2.0,>=1.21.6 in /usr/local/lib/python3.10/dist-packages (from onnxruntime-gpu) (1.25.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from onnxruntime-gpu) (24.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime-gpu) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime-gpu) (1.13.0)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.10/dist-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime-gpu) (1.3.0)
Installing collected packages: onnxruntime-gpu
Successfully installed onnxruntime-gpu-1.18.1 ```

requirements: AutoUpdate success ✅ 12.0s, installed 1 package: ['onnxruntime-gpu']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


TensorFlow SavedModel: starting export with tensorflow 2.15.0...
WARNING ⚠️ tensorflow<=2.13.1 is required, but tensorflow==2.15.0 is currently installed https://github.com/ultralytics/ultralytics/issues/5161

ONNX: starting export with onnx 1.16.1 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 1.4s, saved as '/content/drive/MyDrive/save/yolo/ball_ainex2/weights/best.onnx' (8.9 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Tile.py", line 257, in make_node
    define_tile(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Tile.py", line 144, in define_tile
    tf.tile(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 12032, in tile
    _result = _dispatch.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 167, in dispatch
    result = dispatcher.handle(op, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 1020, in _create_c_op
    raise ValueError(e.message)
ValueError: Exception encountered when calling layer "tf.tile_36" (type TFOpLambda).

Shape must be rank 3 but is rank 1 for '{{node tf.tile_36/Tile}} = Tile[T=DT_INT64, Tmultiples=DT_INT64](Placeholder, tf.tile_36/Tile/multiples)' with input shapes: [1,300,1], [1].

Call arguments received by layer "tf.tile_36" (type TFOpLambda):
  • input=tf.Tensor(shape=(1, 300, 1), dtype=int64)
  • multiples=array([1])
  • name='/model.23/Tile'

ERROR: input_onnx_file_path: /content/drive/MyDrive/save/yolo/ball_ainex2/weights/best.onnx
ERROR: onnx_op_name: /model.23/Tile
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Tile.py", line 257, in make_node
    define_tile(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Tile.py", line 144, in define_tile
    tf.tile(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 12032, in tile
    _result = _dispatch.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 167, in dispatch
    result = dispatcher.handle(op, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 1020, in _create_c_op
    raise ValueError(e.message)
ValueError: Exception encountered when calling layer "tf.tile_36" (type TFOpLambda).

Shape must be rank 3 but is rank 1 for '{{node tf.tile_36/Tile}} = Tile[T=DT_INT64, Tmultiples=DT_INT64](Placeholder, tf.tile_36/Tile/multiples)' with input shapes: [1,300,1], [1].

Call arguments received by layer "tf.tile_36" (type TFOpLambda):
  • input=tf.Tensor(shape=(1, 300, 1), dtype=int64)
  • multiples=array([1])
  • name='/model.23/Tile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-9bf609a4696d>", line 7, in <cell line: 7>
    model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 590, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 297, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 133, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 802, in export_saved_model
    onnx2tf.convert(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/onnx2tf.py", line 998, in convert
    op.make_node(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 354, in print_wrapper_func
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py](https://localhost:8080/#) in print_wrapper_func(*args, **kwargs)
    287         try:
--> 288             result = func(*args, **kwargs)
    289 

24 frames
ValueError: Exception encountered when calling layer "tf.tile_36" (type TFOpLambda).

Shape must be rank 3 but is rank 1 for '{{node tf.tile_36/Tile}} = Tile[T=DT_INT64, Tmultiples=DT_INT64](Placeholder, tf.tile_36/Tile/multiples)' with input shapes: [1,300,1], [1].

Call arguments received by layer "tf.tile_36" (type TFOpLambda):
  • input=tf.Tensor(shape=(1, 300, 1), dtype=int64)
  • multiples=array([1])
  • name='/model.23/Tile'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py](https://localhost:8080/#) in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()

### Environment

Python version: 3.10.12
Ultralytics YOLOv8 version: 1.34
TensorFlow version: 2.15.0
Operating system: McOs
ENvironment: Google Collab with T4 GPU

### Minimal Reproducible Example

```from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('/content/drive/MyDrive/save/yolo/ball_ainex2/weights/best.pt')

# Export the model to TFLite format
model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
```

Additional Context:

I have already installed onnxruntime-gpu as suggested by Ultralytics documentation.
The model was successfully exported to ONNX format (best.onnx), but encounters issues during the conversion to TensorFlow Lite using onnx2tf.
I have tried restarting the runtime environment and rerunning the export command, but the issue persists.
Expected Behavior:

I expect the YOLOv8 model to be successfully exported to TensorFlow Lite format without encountering the tf.tile error.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
It looks like you're encountering an issue with the TensorFlow Lite export due to a shape mismatch in the `tf.tile` operation. First, ensure you're using the latest versions of all relevant packages, including `ultralytics`, `onnx2tf`, and `tensorflow`. The error message suggests that TensorFlow 2.15.0 is installed, but the required version is <=2.13.1. Downgrading TensorFlow to 2.13.1 might resolve the issue. If the problem persists, please try the suggested parameter replacements in the [onnx2tf documentation](https://github.com/PINTO0309/onnx2tf#parameter-replacement). Let me know if you need further assistance!

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by mondiriariana** [comment]
Thank you! The resource you provided was helpful.

 I downgraded to TensorFlow 2.13.1 but it did not help. I still encountered difficulties converting my YOLOv8 weights directly to TensorFlow Lite (TFLite) format using Ultralytics' code.  The code created an intermediate onnx weight than crashed when trying to convert it to tflite.

To overcome this, I manually converted the intermediate onnxmodel to TFLite using [ onnx2tf documentaion](https://github.com/PINTO0309/onnx2tf#parameter-replacement) and did parameter replacement

best

**Comment by pderrenger** [comment]
Thank you for the update. It's good to hear that you found the resource helpful. If you're still encountering issues, please ensure you're using the latest versions of all relevant packages, including `ultralytics`, `onnx2tf`, and `tensorflow`. If the problem persists, you might want to check the onnx2tf documentation for any additional parameter adjustments that could be necessary. If you need further assistance, feel free to ask here.

**Comment by flutter-painter** [comment]
Hi @mondiriariana,

Would you be a code-saver and shard your environment set-up and commands?

I ran into a whole bunch of errors trying to export a finetuned yolo 8 model to tensorflow lite. 

Managed to export to onnx but from onnx to tf python would always complain about something 😬
