### ISSUE TITLE
Prediction model setup: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by LaurensVanDamme** [ultralytics/ultralytics#14569]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Most similar issue I found was: https://github.com/ultralytics/ultralytics/issues/4984
This issue is stale, was not reproducable and was related to training.

When running prediction with half precision True, during the setup of the model an error occurs when the model is fused.

Traceback (most recent call last):
  File "path\min_yolo.py", line 11, in <module>
    detections = model(img, verbose=False, half=True)
  File "path\venv2\lib\site-packages\ultralytics\engine\model.py", line 169, in __call__
    return self.predict(source, stream, **kwargs)
  File "path\venv2\lib\site-packages\ultralytics\engine\model.py", line 432, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "path\venv2\lib\site-packages\ultralytics\engine\predictor.py", line 297, in setup_model
    self.model = AutoBackend(
  File "path\venv2\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "path\venv2\lib\site-packages\ultralytics\nn\autobackend.py", line 143, in __init__
    model = model.fuse(verbose=verbose) if fuse else model
  File "path\venv2\lib\site-packages\ultralytics\nn\tasks.py", line 184, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "path\venv2\lib\site-packages\ultralytics\utils\torch_utils.py", line 196, in fuse_conv_and_bn
    fusedconv.bias.copy_(torch.mm(w_bn, b_conv.reshape(-1, 1)).reshape(-1) + b_bn)
RuntimeError: expected scalar type Half but found Float

### Environment

Ultralytics YOLOv8.1.30 🚀 Python-3.8.0 torch-1.11.0+cu113 CUDA:0 (GeForce RTX 2070 SUPER, 8192MiB)
Setup complete ✅ (12 CPUs, 31.9 GB RAM, 637.5/930.8 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.8.0
Install             git
RAM                 31.95 GB
CPU                 AMD Ryzen 5 3600X 6-Core Processor
CUDA                11.3

matplotlib          ✅ 3.5.2>=3.3.0
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 9.1.1>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.27.1>=2.23.0
scipy               ✅ 1.8.1>=1.4.1
torch               ✅ 1.11.0+cu113>=1.8.0
torchvision         ✅ 0.12.0+cu113>=0.9.0
tqdm                ✅ 4.64.0>=4.64.0
psutil              ✅ 5.9.2
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 1.4.2>=1.1.4
seaborn             ✅ 0.11.2>=0.11.0

### Minimal Reproducible Example

import ultralytics
import numpy as np

model = ultralytics.YOLO('yolov8l.pt')
model.to('cuda:0')
model.half()

img = np.zeros((128, 128, 3), dtype=np.uint8)

detections = model(img, verbose=False, half=True)

### Additional

I have fixed it in my case by editing a line in the "torch_utils.py" file:
![image](https://github.com/user-attachments/assets/16097481-7895-4121-b906-21af3a362467)

I don't know if this only happens on my machine, therefore I did not perform a pull request.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You shouldn't be doing this:

```python
model.to('cuda:0')
model.half()
```

`half=True` handles FP16 inference.

**Comment by LaurensVanDamme** [comment]
@Y-T-G thanks for your reply. This does avoid the error. However, I'm confused why this does (or should?) cause an error? What is the use of the half function?

Extra question: If the half parameter in the predict function handles the FP16 inference, does this mean that every time the function is called the model is adapted/reloaded?
With YOLOv5 the half() function was called once and all inference was with FP16. That is also the reason why I called it.

**Comment by Y-T-G** [comment]
Because the model has a setup phase which involves float prediction.
