### ISSUE TITLE
getaddrinfo failed

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#14628]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
Traceback (most recent call last):
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\anaconda3\envs\yolov38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002AC96198580>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda3\envs\yolov38\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\anaconda3\envs\yolov38\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/assets/releases/tags/v8.2.0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002AC96198580>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\V2.py", line 4053, in ai_kaishi
  File "D:\anaconda3\envs\yolov38\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\ultralytics\engine\model.py", line 149, in __init__
    self._load(model, task=task)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\ultralytics\engine\model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "D:\anaconda3\envs\yolov38\lib\site-packages\ultralytics\nn\tasks.py", line 768, in torch_safe_load
    file = attempt_download_asset(weight)  # search online if missing locally
  File "D:\anaconda3\envs\yolov38\lib\site-packages\ultralytics\utils\downloads.py", line 457, in attempt_download_asset
    tag, assets = get_github_assets(repo, release)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\ultralytics\utils\downloads.py", line 402, in get_github_assets
    r = requests.get(url)  # github api
  File "D:\anaconda3\envs\yolov38\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\yolov38\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/assets/releases/tags/v8.2.0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002AC96198580>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)"))
```

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
