### ISSUE TITLE
RuntimeError: Couldn't open shared file mapping

### ISSUE THREAD

**Issue by CharisWg** [ultralytics/ultralytics#14645]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

It worked well for the first two groups (group0 and group1) but did not work for group2.

RuntimeError: Couldn't open shared file mapping: <torch_28076_1033928186_0>, error code: <1455>
Traceback (most recent call last):
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\multiprocessing\queues.py", line 264, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\multiprocessing\reductions.py", line 557, in reduce_storage
    metadata = storage._share_filename_cpu_()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\storage.py", line 304, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\storage.py", line 378, in _share_filename_cpu_
    return super()._share_filename_cpu_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Couldn't open shared file mapping: <torch_19624_3912367028_0>, error code: <1455>
Traceback (most recent call last):
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\multiprocessing\queues.py", line 264, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\multiprocessing\reductions.py", line 557, in reduce_storage
    metadata = storage._share_filename_cpu_()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\storage.py", line 304, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\storage.py", line 378, in _share_filename_cpu_
    return super()._share_filename_cpu_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Couldn't open shared file mapping: <torch_11660_3556692848_4>, error code: <1455>

Logging results to D:\Charis\SSL-yolo8\lightly-master\runs\Tico\freezebackbone-coca_team1_group2-TiCo_coca_alldcm_SimCLRTransform
Starting training for 2 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/2      4.87G      5.133      77.47      3.196         25        640: 100%|██████████| 92/92 [00:16<00:00,  5.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/12 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Charis\SSL-yolo8\freezebackbone_FT\freezebackboneFT_Tico.py", line 91, in <module>
    trainval_results = model.train(data=yamlFile, epochs=opt.epochs, imgsz=opt.imgsz, batch=opt.batch_size,project=ckpt_dir, name=name, workers=0)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\ultralytics\engine\model.py", line 810, in train
    self.trainer.train()
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\ultralytics\engine\trainer.py", line 204, in train
    self._do_train(world_size)
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\ultralytics\engine\trainer.py", line 429, in _do_train
    self.metrics, self.fitness = self.validate()
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\ultralytics\engine\trainer.py", line 570, in validate
    metrics = self.validator(self)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\ultralytics\engine\validator.py", line 169, in __call__
    for batch_i, batch in enumerate(bar):
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\ultralytics\data\build.py", line 48, in __iter__
    yield next(self.iterator)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 1285, in _get_data
    success, data = self._try_get_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LocalAdmin\anaconda3\envs\SSLyolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 1146, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 6560, 28392, 11688) exited unexpectedly

### Environment

python:3.12.4
torch:2.3.1+cu118

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@CharisWg it appears that you're encountering a `RuntimeError` related to shared file mapping when using multiprocessing with PyTorch. This issue can sometimes occur due to resource limitations or conflicts in the multiprocessing environment.

First, ensure you are using the latest versions of the Ultralytics and PyTorch packages. You can update them using:
```bash
pip install --upgrade ultralytics torch
```

If the issue persists, try reducing the number of workers by setting the `workers` parameter to 0 or 1 in your training script. This can help mitigate issues related to multiprocessing.

Additionally, check your system's available memory and resources, as the error code 1455 indicates insufficient system resources. Closing unnecessary applications or increasing system resources might help.

If you continue to face issues, please provide more details about your environment and setup. This will help in diagnosing the problem more accurately. Thank you for your patience and willingness to contribute!
