### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found - Issue with torch library

### ISSUE THREAD

**Issue by mrortach** [ultralytics/ultralytics#14663]
### Search before asking

- [X] I have searched the YOLOv10 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am trying to run YOLOv10 model using ultralytics with the torch library. However, I am encountering the following error when I run my script:

Traceback (most recent call last):
  File "***\yolov10x_tek_camera.py", line 3, in <module>
    from ultralytics import YOLO
  File "***\.conda\envs\yolov10x_derin\Lib\site-packages\ultralytics\__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "***\.conda\envs\yolov10x_derin\Lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "***\.conda\envs\yolov10x_derin\Lib\site-packages\ultralytics\data\base.py", line 15, in <module>
    from torch.utils.data import Dataset
  File "***\.conda\envs\yolov10x_derin\Lib\site-packages\torch\__init__.py", line 148, in <module>   
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "***\.conda\envs\yolov10x_derin\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### Minimal Reproducible Example

```Python
import` numpy as np
import cv2
from ultralytics import YOLO

# Load a pre-trained YOLOv10x model
model = YOLO("yolov10x.pt")

# Perform object detection on an image or video (0 for webcam)
results = model.track(0, save=True, show=True, conf=0.2)

# Display the results
results[0].show()

**Comment by Y-T-G** [comment]
Downgrade torch

**Comment by mrortach** [comment]
Which version should it be?

**Comment by Y-T-G** [comment]
<2.4

**Comment by mrortach** [comment]
Now it gives an error like this.
OSError: [WinError 126] Belirtilen modül bulunamadı. Error loading "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by pderrenger** [comment]
It seems like you're encountering a dependency issue with the PyTorch library. Please ensure you have the latest versions of both `ultralytics` and `torch` installed. You can update them using `pip install --upgrade ultralytics torch`. If the issue persists, try reinstalling PyTorch with the appropriate CUDA version for your system from the official PyTorch website. This often resolves DLL-related errors.

**Comment by pderrenger** [comment]
You're welcome! I'm glad to hear it worked for you. If you have any more questions or run into any other issues, feel free to ask. Happy coding!

**Comment by GiampaoloCuozzo** [comment]
I have the same issue and the above solutions don't work.

Python: 3.10
ultralytics: 8.2.71
torch: 2.4.0

I have tried different downgrade combinations but it doesn't work. I am using yolov8

**Comment by Y-T-G** [comment]
Downgrade to torch 2.3.1

**Comment by GiampaoloCuozzo** [comment]
It still doesn't work

**Comment by Y-T-G** [comment]
Post output of `yolo checks`

**Comment by GiampaoloCuozzo** [comment]
Here you are:

_Traceback (most recent call last):
  File "C:\Users\giamp\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\giamp\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\giamp\Codici\progetto_lvng\venv\Scripts\yolo.exe\__main__.py", line 4, in <module>
    from ultralytics.yolo.cfg import entrypoint
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\__init__.py", line 3, in <module>
    from . import v8
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\v8\__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\v8\classify\__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\v8\classify\predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 35, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 15, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\utils\__init__.py", line 629, in <module>
    SETTINGS = get_settings()
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\utils\__init__.py", line 575, in get_settings
    from ultralytics.yolo.utils.checks import check_version
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\ultralytics\yolo\utils\checks.py", line 21, in <module>
    from matplotlib import font_manager
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\giamp\Codici\progetto_lvng\venv\lib\site-packages\matplotlib\cbook.py", line 32, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: DLL load failed while importing _c_internal_utils: Impossibile trovare il modulo specification._

I am now using:

ultralytics: 8.0.33
torch: 2.3.0
matplotlib: 3.9.1
numpy: 1.26.4

**Comment by GiampaoloCuozzo** [comment]
I have solved the issue by downgrading matplotlib to 3.9.0. The I faced another problem with torchvision and I had to downgrade it to 0.18.0

**Comment by pderrenger** [comment]
Thank you for sharing your solution. It's great to hear that downgrading matplotlib and torchvision resolved your issue. If you encounter any further problems, please ensure you're using the latest versions of Ultralytics and PyTorch, as updates often include important fixes and improvements. If the issue persists, feel free to reach out again.

**Comment by abiyyudaffa10** [comment]
Requirement already satisfied: torch in c:\yolo\etle\lib\site-packages (2.4.0)
Requirement already satisfied: torchvision in c:\yolo\etle\lib\site-packages (0.19.0)
Requirement already satisfied: torchaudio in c:\yolo\etle\lib\site-packages (2.4.0)
Requirement already satisfied: filelock in c:\yolo\etle\lib\site-packages (from torch) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\yolo\etle\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in c:\yolo\etle\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: networkx in c:\yolo\etle\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\yolo\etle\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in c:\yolo\etle\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: numpy<2 in c:\yolo\etle\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\yolo\etle\lib\site-packages (from torchvision) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\yolo\etle\lib\site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\yolo\etle\lib\site-packages (from sympy->torch) (1.3.0)
i have the same problem with fbgemm.dll and its dependencies, what should I do?

**Comment by Y-T-G** [comment]
Follow this:

https://github.com/ultralytics/ultralytics/issues/15049

**Comment by abiyyudaffa10** [comment]
Thankyou for your help

**Comment by pderrenger** [comment]
@abiyyudaffa10 you're welcome! If you encounter any further issues, please ensure you're using the latest versions of Ultralytics and PyTorch. If the problem persists, feel free to reach out again.
