### ISSUE TITLE
Unable to export trained yolov8 model to tflite

### ISSUE THREAD

**Issue by Grn2Npz** [ultralytics/ultralytics#14671]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Hi! I am currently training a YoloV8 model with Ultralytics in a Kaggle notebook. I have trained multiple models just recently without errors.

However, I am currently encountering an error when exporting my best.pt model to tflite when doing the !yolo export command. 

Is there any fixes on my side for this issue? Thanks in advance!

This is the error that I get:

PyTorch: starting from '/kaggle/working/runs/detect/train/weights/best.pt' with input shape (1, 3, 160, 160) BCHW and output shape(s) (1, 14, 525) (520.8 MB)
requirements: Ultralytics requirements ['onnx2tf>=1.9.1', 'sng4onnx>=1.0.1', 'onnxsim>=0.4.17', 'onnx_graphsurgeon>=0.3.26', 'tflite_support', 'onnxruntime'] not found, attempting AutoUpdate...
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.8; 0.0.10 Requires-Python >=3.8; 0.0.11 Requires-Python >=3.8; 0.0.12 Requires-Python >=3.8; 0.0.13 Requires-Python >=3.8; 0.0.14 Requires-Python >=3.8; 0.0.15 Requires-Python >=3.8; 0.0.16 Requires-Python >=3.8; 0.0.17 Requires-Python >=3.8; 0.0.18 Requires-Python >=3.8; 0.0.19 Requires-Python >=3.8; 0.0.2 Requires-Python >=3.8; 0.0.20 Requires-Python >=3.8; 0.0.21 Requires-Python >=3.8; 0.0.22 Requires-Python >=3.8; 0.0.23 Requires-Python >=3.8; 0.0.24 Requires-Python >=3.8; 0.0.25 Requires-Python >=3.8; 0.0.26 Requires-Python >=3.8; 0.0.27 Requires-Python >=3.8; 0.0.28 Requires-Python >=3.8; 0.0.29 Requires-Python >=3.8; 0.0.3 Requires-Python >=3.8; 0.0.30 Requires-Python >=3.8; 0.0.31 Requires-Python >=3.8; 0.0.32 Requires-Python >=3.8; 0.0.33 Requires-Python >=3.8; 0.0.4 Requires-Python >=3.8; 0.0.5 Requires-Python >=3.8; 0.0.6 Requires-Python >=3.8; 0.0.7 Requires-Python >=3.8; 0.0.8 Requires-Python >=3.8; 0.0.9 Requires-Python >=3.8; 1.0.0 Requires-Python >=3.8; 1.0.1 Requires-Python >=3.8; 1.0.10 Requires-Python >=3.8; 1.0.11 Requires-Python >=3.8; 1.0.12 Requires-Python >=3.8; 1.0.13 Requires-Python >=3.8; 1.0.14 Requires-Python >=3.8; 1.0.15 Requires-Python >=3.8; 1.0.16 Requires-Python >=3.8; 1.0.17 Requires-Python >=3.8; 1.0.18 Requires-Python >=3.8; 1.0.19 Requires-Python >=3.8; 1.0.2 Requires-Python >=3.8; 1.0.20 Requires-Python >=3.8; 1.0.21 Requires-Python >=3.8; 1.0.22 Requires-Python >=3.8; 1.0.23 Requires-Python >=3.8; 1.0.24 Requires-Python >=3.8; 1.0.25 Requires-Python >=3.8; 1.0.26 Requires-Python >=3.8; 1.0.27 Requires-Python >=3.8; 1.0.28 Requires-Python >=3.8; 1.0.29 Requires-Python >=3.8; 1.0.3 Requires-Python >=3.8; 1.0.30 Requires-Python >=3.8; 1.0.31 Requires-Python >=3.8; 1.0.32 Requires-Python >=3.8; 1.0.33 Requires-Python >=3.8; 1.0.34 Requires-Python >=3.8; 1.0.35 Requires-Python >=3.8; 1.0.36 Requires-Python >=3.8; 1.0.37 Requires-Python >=3.8; 1.0.38 Requires-Python >=3.8; 1.0.39 Requires-Python >=3.8; 1.0.4 Requires-Python >=3.8; 1.0.40 Requires-Python >=3.8; 1.0.41 Requires-Python >=3.8; 1.0.42 Requires-Python >=3.8; 1.0.43 Requires-Python >=3.8; 1.0.44 Requires-Python >=3.8; 1.0.45 Requires-Python >=3.8; 1.0.46 Requires-Python >=3.8; 1.0.47 Requires-Python >=3.8; 1.0.48 Requires-Python >=3.8; 1.0.49 Requires-Python >=3.8; 1.0.5 Requires-Python >=3.8; 1.0.6 Requires-Python >=3.8; 1.0.7 Requires-Python >=3.8; 1.0.8 Requires-Python >=3.8; 1.0.9 Requires-Python >=3.8; 1.1.0 Requires-Python >=3.8; 1.1.1 Requires-Python >=3.8; 1.1.10 Requires-Python >=3.8; 1.1.11 Requires-Python >=3.8; 1.1.12 Requires-Python >=3.8; 1.1.13 Requires-Python >=3.8; 1.1.14 Requires-Python >=3.8; 1.1.15 Requires-Python >=3.8; 1.1.16 Requires-Python >=3.8; 1.1.17 Requires-Python >=3.8; 1.1.18 Requires-Python >=3.8; 1.1.19 Requires-Python >=3.8; 1.1.2 Requires-Python >=3.8; 1.1.20 Requires-Python >=3.8; 1.1.21 Requires-Python >=3.8; 1.1.22 Requires-Python >=3.8; 1.1.23 Requires-Python >=3.8; 1.1.24 Requires-Python >=3.8; 1.1.25 Requires-Python >=3.8; 1.1.26 Requires-Python >=3.8; 1.1.27 Requires-Python >=3.8; 1.1.28 Requires-Python >=3.8; 1.1.29 Requires-Python >=3.8; 1.1.3 Requires-Python >=3.8; 1.1.30 Requires-Python >=3.8; 1.1.31 Requires-Python >=3.8; 1.1.32 Requires-Python >=3.8; 1.1.33 Requires-Python >=3.8; 1.1.34 Requires-Python >=3.8; 1.1.35 Requires-Python >=3.8; 1.1.36 Requires-Python >=3.8; 1.1.37 Requires-Python >=3.8; 1.1.38 Requires-Python >=3.8; 1.1.39 Requires-Python >=3.8; 1.1.4 Requires-Python >=3.8; 1.1.40 Requires-Python >=3.8; 1.1.41 Requires-Python >=3.8; 1.1.42 Requires-Python >=3.8; 1.1.43 Requires-Python >=3.8; 1.1.44 Requires-Python >=3.8; 1.1.45 Requires-Python >=3.8; 1.1.46 Requires-Python >=3.8; 1.1.5 Requires-Python >=3.8; 1.1.6 Requires-Python >=3.8; 1.1.7 Requires-Python >=3.8; 1.1.8 Requires-Python >=3.8; 1.1.9 Requires-Python >=3.8; 1.10.0 Requires-Python >=3.8; 1.10.1 Requires-Python >=3.8; 1.10.2 Requires-Python >=3.8; 1.10.3 Requires-Python >=3.8; 1.11.0 Requires-Python >=3.8; 1.11.1 Requires-Python >=3.8; 1.11.10 Requires-Python >=3.8; 1.11.11 Requires-Python >=3.8; 1.11.2 Requires-Python >=3.8; 1.11.3 Requires-Python >=3.8; 1.11.4 Requires-Python >=3.8; 1.11.5 Requires-Python >=3.8; 1.11.6 Requires-Python >=3.8; 1.11.7 Requires-Python >=3.8; 1.11.8 Requires-Python >=3.8; 1.11.9 Requires-Python >=3.8; 1.12.0 Requires-Python >=3.8; 1.12.1 Requires-Python >=3.8; 1.12.2 Requires-Python >=3.8; 1.12.3 Requires-Python >=3.8; 1.12.4 Requires-Python >=3.8; 1.12.5 Requires-Python >=3.8; 1.12.6 Requires-Python >=3.8; 1.12.7 Requires-Python >=3.8; 1.13.0 Requires-Python >=3.8; 1.13.1 Requires-Python >=3.8; 1.13.10 Requires-Python >=3.8; 1.13.11 Requires-Python >=3.8; 1.13.12 Requires-Python >=3.8; 1.13.13 Requires-Python >=3.8; 1.13.2 Requires-Python >=3.8; 1.13.3 Requires-Python >=3.8; 1.13.4 Requires-Python >=3.8; 1.13.5 Requires-Python >=3.8; 1.13.6 Requires-Python >=3.8; 1.13.7 Requires-Python >=3.8; 1.13.8 Requires-Python >=3.8; 1.13.9 Requires-Python >=3.8; 1.14.0 Requires-Python >=3.8; 1.14.1 Requires-Python >=3.8; 1.14.2 Requires-Python >=3.8; 1.14.3 Requires-Python >=3.8; 1.14.4 Requires-Python >=3.8; 1.14.5 Requires-Python >=3.8; 1.14.6 Requires-Python >=3.8; 1.14.7 Requires-Python >=3.8; 1.15.0 Requires-Python >=3.8; 1.15.1 Requires-Python >=3.8; 1.15.10 Requires-Python >=3.8; 1.15.11 Requires-Python >=3.8; 1.15.12 Requires-Python >=3.8; 1.15.13 Requires-Python >=3.8; 1.15.14 Requires-Python >=3.8; 1.15.15 Requires-Python >=3.8; 1.15.16 Requires-Python >=3.8; 1.15.17 Requires-Python >=3.8; 1.15.18 Requires-Python >=3.8; 1.15.2 Requires-Python >=3.8; 1.15.3 Requires-Python >=3.8; 1.15.4 Requires-Python >=3.8; 1.15.5 Requires-Python >=3.8; 1.15.6 Requires-Python >=3.8; 1.15.7 Requires-Python >=3.8; 1.15.8 Requires-Python >=3.8; 1.15.9 Requires-Python >=3.8; 1.16.0 Requires-Python >=3.8; 1.16.1 Requires-Python >=3.8; 1.16.10 Requires-Python >=3.8; 1.16.11 Requires-Python >=3.8; 1.16.12 Requires-Python >=3.8; 1.16.13 Requires-Python >=3.8; 1.16.14 Requires-Python >=3.8; 1.16.15 Requires-Python >=3.8; 1.16.16 Requires-Python >=3.8; 1.16.17 Requires-Python >=3.8; 1.16.18 Requires-Python >=3.8; 1.16.19 Requires-Python >=3.8; 1.16.2 Requires-Python >=3.8; 1.16.20 Requires-Python >=3.8; 1.16.21 Requires-Python >=3.8; 1.16.22 Requires-Python >=3.8; 1.16.23 Requires-Python >=3.8; 1.16.24 Requires-Python >=3.8; 1.16.25 Requires-Python >=3.8; 1.16.26 Requires-Python >=3.8; 1.16.27 Requires-Python >=3.8; 1.16.28 Requires-Python >=3.8; 1.16.29 Requires-Python >=3.8; 1.16.3 Requires-Python >=3.8; 1.16.30 Requires-Python >=3.8; 1.16.31 Requires-Python >=3.8; 1.16.4 Requires-Python >=3.8; 1.16.5 Requires-Python >=3.8; 1.16.6 Requires-Python >=3.8; 1.16.7 Requires-Python >=3.8; 1.16.8 Requires-Python >=3.8; 1.16.9 Requires-Python >=3.8; 1.17.0 Requires-Python >=3.8; 1.17.1 Requires-Python >=3.8; 1.17.2 Requires-Python >=3.8; 1.17.3 Requires-Python >=3.8; 1.17.4 Requires-Python >=3.8; 1.17.5 Requires-Python >=3.8; 1.17.6 Requires-Python >=3.8; 1.17.7 Requires-Python >=3.8; 1.17.8 Requires-Python >=3.8; 1.17.9 Requires-Python >=3.8; 1.18.0 Requires-Python >=3.8; 1.18.1 Requires-Python >=3.8; 1.18.10 Requires-Python >=3.8; 1.18.11 Requires-Python >=3.8; 1.18.12 Requires-Python >=3.8; 1.18.13 Requires-Python >=3.8; 1.18.14 Requires-Python >=3.8; 1.18.15 Requires-Python >=3.8; 1.18.2 Requires-Python >=3.8; 1.18.3 Requires-Python >=3.8; 1.18.4 Requires-Python >=3.8; 1.18.5 Requires-Python >=3.8; 1.18.6 Requires-Python >=3.8; 1.18.7 Requires-Python >=3.8; 1.18.8 Requires-Python >=3.8; 1.18.9 Requires-Python >=3.8; 1.19.0 Requires-Python >=3.8; 1.19.1 Requires-Python >=3.8; 1.19.10 Requires-Python >=3.8; 1.19.11 Requires-Python >=3.8; 1.19.12 Requires-Python >=3.8; 1.19.13 Requires-Python >=3.8; 1.19.14 Requires-Python >=3.8; 1.19.15 Requires-Python >=3.8; 1.19.16 Requires-Python >=3.8; 1.19.2 Requires-Python >=3.8; 1.19.3 Requires-Python >=3.8; 1.19.4 Requires-Python >=3.8; 1.19.5 Requires-Python >=3.8; 1.19.6 Requires-Python >=3.8; 1.19.7 Requires-Python >=3.8; 1.19.8 Requires-Python >=3.8; 1.19.9 Requires-Python >=3.8; 1.2.0 Requires-Python >=3.8; 1.2.1 Requires-Python >=3.8; 1.2.10 Requires-Python >=3.8; 1.2.11 Requires-Python >=3.8; 1.2.12 Requires-Python >=3.8; 1.2.13 Requires-Python >=3.8; 1.2.14 Requires-Python >=3.8; 1.2.15 Requires-Python >=3.8; 1.2.16 Requires-Python >=3.8; 1.2.17 Requires-Python >=3.8; 1.2.18 Requires-Python >=3.8; 1.2.19 Requires-Python >=3.8; 1.2.2 Requires-Python >=3.8; 1.2.20 Requires-Python >=3.8; 1.2.21 Requires-Python >=3.8; 1.2.22 Requires-Python >=3.8; 1.2.23 Requires-Python >=3.8; 1.2.24 Requires-Python >=3.8; 1.2.25 Requires-Python >=3.8; 1.2.26 Requires-Python >=3.8; 1.2.3 Requires-Python >=3.8; 1.2.4 Requires-Python >=3.8; 1.2.5 Requires-Python >=3.8; 1.2.6 Requires-Python >=3.8; 1.2.7 Requires-Python >=3.8; 1.2.8 Requires-Python >=3.8; 1.2.9 Requires-Python >=3.8; 1.20.0 Requires-Python >=3.8; 1.20.1 Requires-Python >=3.10; 1.20.10 Requires-Python >=3.10; 1.20.2 Requires-Python >=3.10; 1.20.3 Requires-Python >=3.10; 1.20.4 Requires-Python >=3.10; 1.20.5 Requires-Python >=3.10; 1.20.6 Requires-Python >=3.10; 1.20.7 Requires-Python >=3.10; 1.20.8 Requires-Python >=3.10; 1.20.9 Requires-Python >=3.10; 1.21.0 Requires-Python >=3.10; 1.21.1 Requires-Python >=3.10; 1.21.2 Requires-Python >=3.10; 1.21.3 Requires-Python >=3.10; 1.21.4 Requires-Python >=3.10; 1.21.5 Requires-Python >=3.10; 1.21.6 Requires-Python >=3.10; 1.22.0 Requires-Python >=3.10; 1.22.3 Requires-Python >=3.10; 1.22.4 Requires-Python >=3.10; 1.22.5 Requires-Python >=3.10; 1.22.6 Requires-Python >=3.10; 1.23.0 Requires-Python >=3.10; 1.23.1 Requires-Python >=3.10; 1.23.2 Requires-Python >=3.10; 1.23.3 Requires-Python >=3.10; 1.24.0 Requires-Python >=3.10; 1.24.1 Requires-Python >=3.10; 1.25.0 Requires-Python >=3.10; 1.25.1 Requires-Python >=3.10; 1.25.2 Requires-Python >=3.10; 1.25.3 Requires-Python >=3.10; 1.25.4 Requires-Python >=3.10; 1.25.5 Requires-Python >=3.10; 1.25.6 Requires-Python >=3.10; 1.3.0 Requires-Python >=3.8; 1.3.1 Requires-Python >=3.8; 1.3.10 Requires-Python >=3.8; 1.3.11 Requires-Python >=3.8; 1.3.12 Requires-Python >=3.8; 1.3.13 Requires-Python >=3.8; 1.3.14 Requires-Python >=3.8; 1.3.15 Requires-Python >=3.8; 1.3.16 Requires-Python >=3.8; 1.3.17 Requires-Python >=3.8; 1.3.18 Requires-Python >=3.8; 1.3.19 Requires-Python >=3.8; 1.3.2 Requires-Python >=3.8; 1.3.3 Requires-Python >=3.8; 1.3.4 Requires-Python >=3.8; 1.3.5 Requires-Python >=3.8; 1.3.6 Requires-Python >=3.8; 1.3.7 Requires-Python >=3.8; 1.3.8 Requires-Python >=3.8; 1.3.9 Requires-Python >=3.8; 1.4.0 Requires-Python >=3.8; 1.4.1 Requires-Python >=3.8; 1.4.2 Requires-Python >=3.8; 1.5.0 Requires-Python >=3.8; 1.5.1 Requires-Python >=3.8; 1.5.10 Requires-Python >=3.8; 1.5.11 Requires-Python >=3.8; 1.5.12 Requires-Python >=3.8; 1.5.13 Requires-Python >=3.8; 1.5.14 Requires-Python >=3.8; 1.5.15 Requires-Python >=3.8; 1.5.16 Requires-Python >=3.8; 1.5.17 Requires-Python >=3.8; 1.5.18 Requires-Python >=3.8; 1.5.19 Requires-Python >=3.8; 1.5.2 Requires-Python >=3.8; 1.5.20 Requires-Python >=3.8; 1.5.21 Requires-Python >=3.8; 1.5.22 Requires-Python >=3.8; 1.5.23 Requires-Python >=3.8; 1.5.24 Requires-Python >=3.8; 1.5.25 Requires-Python >=3.8; 1.5.26 Requires-Python >=3.8; 1.5.27 Requires-Python >=3.8; 1.5.28 Requires-Python >=3.8; 1.5.29 Requires-Python >=3.8; 1.5.3 Requires-Python >=3.8; 1.5.30 Requires-Python >=3.8; 1.5.31 Requires-Python >=3.8; 1.5.32 Requires-Python >=3.8; 1.5.33 Requires-Python >=3.8; 1.5.34 Requires-Python >=3.8; 1.5.35 Requires-Python >=3.8; 1.5.36 Requires-Python >=3.8; 1.5.37 Requires-Python >=3.8; 1.5.39 Requires-Python >=3.8; 1.5.4 Requires-Python >=3.8; 1.5.40 Requires-Python >=3.8; 1.5.41 Requires-Python >=3.8; 1.5.42 Requires-Python >=3.8; 1.5.43 Requires-Python >=3.8; 1.5.44 Requires-Python >=3.8; 1.5.45 Requires-Python >=3.8; 1.5.5 Requires-Python >=3.8; 1.5.6 Requires-Python >=3.8; 1.5.7 Requires-Python >=3.8; 1.5.8 Requires-Python >=3.8; 1.5.9 Requires-Python >=3.8; 1.6.0 Requires-Python >=3.8; 1.6.1 Requires-Python >=3.8; 1.6.2 Requires-Python >=3.8; 1.6.3 Requires-Python >=3.8; 1.6.4 Requires-Python >=3.8; 1.6.5 Requires-Python >=3.8; 1.6.6 Requires-Python >=3.8; 1.6.7 Requires-Python >=3.8; 1.7.0 Requires-Python >=3.8; 1.7.1 Requires-Python >=3.8; 1.7.10 Requires-Python >=3.8; 1.7.11 Requires-Python >=3.8; 1.7.12 Requires-Python >=3.8; 1.7.13 Requires-Python >=3.8; 1.7.14 Requires-Python >=3.8; 1.7.15 Requires-Python >=3.8; 1.7.16 Requires-Python >=3.8; 1.7.17 Requires-Python >=3.8; 1.7.18 Requires-Python >=3.8; 1.7.19 Requires-Python >=3.8; 1.7.2 Requires-Python >=3.8; 1.7.20 Requires-Python >=3.8; 1.7.21 Requires-Python >=3.8; 1.7.22 Requires-Python >=3.8; 1.7.23 Requires-Python >=3.8; 1.7.24 Requires-Python >=3.8; 1.7.25 Requires-Python >=3.8; 1.7.26 Requires-Python >=3.8; 1.7.27 Requires-Python >=3.8; 1.7.28 Requires-Python >=3.8; 1.7.29 Requires-Python >=3.8; 1.7.3 Requires-Python >=3.8; 1.7.30 Requires-Python >=3.8; 1.7.31 Requires-Python >=3.8; 1.7.32 Requires-Python >=3.8; 1.7.33 Requires-Python >=3.8; 1.7.34 Requires-Python >=3.8; 1.7.35 Requires-Python >=3.8; 1.7.4 Requires-Python >=3.8; 1.7.5 Requires-Python >=3.8; 1.7.6 Requires-Python >=3.8; 1.7.7 Requires-Python >=3.8; 1.7.8 Requires-Python >=3.8; 1.7.9 Requires-Python >=3.8; 1.8.0 Requires-Python >=3.8; 1.8.1 Requires-Python >=3.8; 1.8.10 Requires-Python >=3.8; 1.8.11 Requires-Python >=3.8; 1.8.12 Requires-Python >=3.8; 1.8.13 Requires-Python >=3.8; 1.8.14 Requires-Python >=3.8; 1.8.15 Requires-Python >=3.8; 1.8.16 Requires-Python >=3.8; 1.8.17 Requires-Python >=3.8; 1.8.18 Requires-Python >=3.8; 1.8.19 Requires-Python >=3.8; 1.8.2 Requires-Python >=3.8; 1.8.20 Requires-Python >=3.8; 1.8.21 Requires-Python >=3.8; 1.8.22 Requires-Python >=3.8; 1.8.23 Requires-Python >=3.8; 1.8.24 Requires-Python >=3.8; 1.8.25 Requires-Python >=3.8; 1.8.3 Requires-Python >=3.8; 1.8.4 Requires-Python >=3.8; 1.8.5 Requires-Python >=3.8; 1.8.6 Requires-Python >=3.8; 1.8.7 Requires-Python >=3.8; 1.8.8 Requires-Python >=3.8; 1.8.9 Requires-Python >=3.8; 1.9.0 Requires-Python >=3.8; 1.9.1 Requires-Python >=3.8; 1.9.10 Requires-Python >=3.8; 1.9.11 Requires-Python >=3.8; 1.9.12 Requires-Python >=3.8; 1.9.13 Requires-Python >=3.8; 1.9.14 Requires-Python >=3.8; 1.9.15 Requires-Python >=3.8; 1.9.16 Requires-Python >=3.8; 1.9.17 Requires-Python >=3.8; 1.9.18 Requires-Python >=3.8; 1.9.19 Requires-Python >=3.8; 1.9.2 Requires-Python >=3.8; 1.9.3 Requires-Python >=3.8; 1.9.4 Requires-Python >=3.8; 1.9.5 Requires-Python >=3.8; 1.9.6 Requires-Python >=3.8; 1.9.7 Requires-Python >=3.8; 1.9.8 Requires-Python >=3.8; 1.9.9 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement onnx2tf>=1.9.1 (from versions: none)
ERROR: No matching distribution found for onnx2tf>=1.9.1
requirements: ❌ Command 'pip install --no-cache "onnx2tf>=1.9.1" "sng4onnx>=1.0.1" "onnxsim>=0.4.17" "onnx_graphsurgeon>=0.3.26" "tflite_support" "onnxruntime"  --extra-index-url https://pypi.ngc.nvidia.com/' returned non-zero exit status 1.

TensorFlow SavedModel: starting export with tensorflow 2.6.4...
requirements: Ultralytics requirements ['onnxsim>=0.4.17', 'onnxruntime'] not found, attempting AutoUpdate...
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: [https://pip.pypa.io/warnings/venv](https://pip.pypa.io/warnings/venv%3C/span%3E%3Cspan) class="ansi-yellow-fg">
Collecting onnxsim>=0.4.17
  Downloading onnxsim-0.4.36-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 51.1 MB/s eta 0:00:00
Collecting onnxruntime
  Downloading onnxruntime-1.14.1-cp37-cp37m-manylinux_2_27_x86_64.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 43.2 MB/s eta 0:00:00
Requirement already satisfied: rich in /opt/conda/lib/python3.7/site-packages (from onnxsim>=0.4.17) (12.6.0)
Requirement already satisfied: onnx in /opt/conda/lib/python3.7/site-packages (from onnxsim>=0.4.17) (1.13.0)
Requirement already satisfied: protobuf in /opt/conda/lib/python3.7/site-packages (from onnxruntime) (3.20.3)
Requirement already satisfied: packaging in /opt/conda/lib/python3.7/site-packages (from onnxruntime) (22.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.7/site-packages (from onnxruntime) (1.10.1)
Collecting coloredlogs
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 160.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.6 in /opt/conda/lib/python3.7/site-packages (from onnxruntime) (1.21.6)
Requirement already satisfied: flatbuffers in /opt/conda/lib/python3.7/site-packages (from onnxruntime) (1.12)
Collecting humanfriendly>=9.1
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 174.6 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.6.2.1 in /opt/conda/lib/python3.7/site-packages (from onnx->onnxsim>=0.4.17) (4.1.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /opt/conda/lib/python3.7/site-packages (from rich->onnxsim>=0.4.17) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /opt/conda/lib/python3.7/site-packages (from rich->onnxsim>=0.4.17) (2.12.0)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.7/site-packages (from sympy->onnxruntime) (1.2.1)
Installing collected packages: humanfriendly, onnxsim, coloredlogs, onnxruntime
Successfully installed coloredlogs-15.0.1 humanfriendly-10.0 onnxruntime-1.14.1 onnxsim-0.4.36

requirements: AutoUpdate success ✅ 12.1s, installed 2 packages: ['onnxsim>=0.4.17', 'onnxruntime']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

ONNX: starting export with onnx 1.13.0 opset 14...
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 36.7s, saved as '/kaggle/working/runs/detect/train/weights/best.onnx' (260.0 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/kaggle/working/runs/detect/train/weights/best.onnx" -o "/kaggle/working/runs/detect/train/weights/best_saved_model" -nuo --non_verbose'
/bin/sh: 1: onnx2tf: not found
TensorFlow SavedModel: export failure ❌ 44.0s: SavedModel file does not exist at: /kaggle/working/runs/detect/train/weights/best_saved_model/{saved_model.pbtxt|saved_model.pb}
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/cfg/__init__.py", line 423, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/engine/model.py", line 344, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/engine/exporter.py", line 250, in __call__
    f[5], s_model = self.export_saved_model()
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/engine/exporter.py", line 119, in outer_func
    raise e
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/engine/exporter.py", line 114, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/engine/exporter.py", line 643, in export_saved_model
    keras_model = tf.saved_model.load(f, tags=None, options=None)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 878, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 60, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 121, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: /kaggle/working/runs/detect/train/weights/best_saved_model/{saved_model.pbtxt|saved_model.pb}
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

### Environment

Ultralytics YOLOv8.0.145 🚀 Python-3.7.12 torch-1.11.0 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5771.9/8062.4 GB disk)

### Minimal Reproducible Example

`%pip install ultralytics`
`import ultralytics`
`ultralytics.checks()`

_When training: _
`from ultralytics import YOLO`
`model = YOLO("yolov8x.pt")`
`results = model.train(data="/kaggle/input/kibonakaw/data.yaml", epochs=150, imgsz=160, batch=6, patience=40)`

_When exporting the model to tflite_
`!yolo export model=/kaggle/working/runs/detect/train/weights/best.pt format=tflite`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@Grn2Npz it looks like the issue you're encountering is related to missing dependencies required for the TFLite export process. Specifically, the error indicates that the `onnx2tf` tool is not found, which is essential for converting ONNX models to TensorFlow formats before exporting to TFLite.

To resolve this, please ensure that all required dependencies are installed. You can do this by running the following command in your Kaggle notebook:

```python
!pip install onnx2tf sng4onnx onnxsim onnx_graphsurgeon tflite_support onnxruntime
```

After installing these dependencies, try exporting your model again using the `!yolo export` command. If the issue persists, please ensure you are using the latest version of the Ultralytics package by running:

```python
!pip install --upgrade ultralytics
```

If you continue to face issues, please let us know. Your feedback helps improve the tools and documentation for everyone. Thank you for your patience and understanding.

**Comment by Burhan-Q** [comment]
`Ultralytics YOLOv8.0.145 🚀` This is a _very_ old version of the Ultralytics library.
`Python-3.7.12`  In the [Readme on our repo](https://github.com/ultralytics/ultralytics#documentation), you can see that Python 3.8 or higher is supported

You should update to a newer Python version and update your version of Ultralytics. According to the error you posted, the dependency `onnx2tf` is also looking for a newer version of Python and so you will not be able to export in your current environment.
