### ISSUE TITLE
This problem occurs every time I train, and it was fine before.

### ISSUE THREAD

**Issue by anmc-mch** [ultralytics/ultralytics#14705]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     1/1000      6.83G     0.8689     0.8998      1.167         60        640:  82%|████████▏ | 1891/2295 [05:15<01:07,  6.00it/s]
Traceback (most recent call last):
  File "/home/xxx/work/work/coco-api/yolo.py", line 7, in <module>
    results = model.train(data="/home/xxx/work/work/coco-api/person.yaml", epochs=1000,
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/ultralytics/engine/model.py", line 811, in train
    self.trainer.train()
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 205, in train
    self._do_train(world_size)
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 390, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function ToCopyBackward0 returned an invalid gradient at index 0 - expected device cuda:0 but got cpu
```
### Environment

Ultralytics YOLOv8.2.66 🚀 Python-3.10.14 torch-2.4.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4080, 16071MiB)

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO("yolov8x.pt")

model.info()

results = model.train(data="xxx.yaml", epochs=1000,
                      imgsz=640, batch=8, workers=32)

model.export(format='onnx')
```

### Additional

I tried n, m, and x and all had similar problems.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by anmc-mch** [comment]
Traceback (most recent call last):
  File "/home/xxx/work/work/coco-api/yolo.py", line 7, in <module>
    results = model.train(data="/home/xxx/work/work/coco-api/person.yaml", epochs=1000,
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/ultralytics/engine/model.py", line 811, in train
    self.trainer.train()
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 205, in train
    self._do_train(world_size)
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 390, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/home/xxx/miniconda3/envs/coco/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: d.is_cuda() INTERNAL ASSERT FAILED at "../c10/cuda/impl/CUDAGuardImpl.h":34, please report a bug to PyTorch

**Comment by pderrenger** [comment]
@anmc-mch thank you for reporting this issue. It appears to be related to a CUDA device mismatch during the backward pass. Please ensure you are using the latest versions of Ultralytics YOLOv8 and PyTorch. If the problem persists, try reducing the number of workers or batch size to see if it alleviates the issue. Additionally, verify that your CUDA installation is correctly configured. If the issue continues, consider reporting it to the PyTorch repository as suggested by the error message.

**Comment by ambitious-octopus** [comment]
Hey @anmc-mch, I am unable to reproduce your bug. This is my `yolo check` output:

```
Ultralytics YOLOv8.2.65 🚀 Python-3.12.2 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 4GB Laptop GPU, 3808MiB)
Setup complete ✅ (16 CPUs, 15.3 GB RAM, 192.2/383.3 GB disk)

OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.12.2
Install             git
RAM                 15.29 GB
CPU                 12th Gen Intel Core(TM) i7-12650H
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.82>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

**Comment by anmc-mch** [comment]
I found that it might be the problem of the CPU. My CPU is 14900kf, and then I changed it to 12900kf and everything was normal.
