### ISSUE TITLE
Not compatible with Mac AMD64

### ISSUE THREAD

**Issue by duguyixiaono1** [ultralytics/ultralytics#14805]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Integrations

### Bug

`!!! Exception during processing!!! py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
Traceback (most recent call last):
  File "/Users/jamson/code_opensource/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/detectors.py", line 243, in doit
    return SimpleDetectorForEach.detect(bbox_detector, image, bbox_threshold, bbox_dilation, crop_factor, drop_size,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/detectors.py", line 224, in detect
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, crop_factor, drop_size, detailer_hook=detailer_hook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 127, in detect
    detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 33, in inference_bbox
    pred = model(image, conf=confidence, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 556, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 305, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/torch_utils.py", line 204, in select_device
    s += f"CPU ({get_cpu_info()})\n"
                 ^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/torch_utils.py", line 104, in get_cpu_info
    import cpuinfo  # pip install py-cpuinfo
    ^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/__init__.py", line 7, in <module>
    from cpuinfo.cpuinfo import *
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1842, in <module>
    _check_arch()
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1798, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.`

### Environment

output with yolo checks :

`Traceback (most recent call last):
  File "/Users/jamson/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 750, in entrypoint
    special[a.lower()]()
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/checks.py", line 592, in collect_system_info
    check_yolo()
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/checks.py", line 579, in check_yolo
    select_device(device=device, newline=False)
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/torch_utils.py", line 204, in select_device
    s += f"CPU ({get_cpu_info()})\n"
                 ^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/torch_utils.py", line 104, in get_cpu_info
    import cpuinfo  # pip install py-cpuinfo
    ^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/__init__.py", line 7, in <module>
    from cpuinfo.cpuinfo import *
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1842, in <module>
    _check_arch()
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1798, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit`

### Minimal Reproducible Example

python -m cpuinfo
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/__init__.py", line 7, in <module>
    from cpuinfo.cpuinfo import *
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1842, in <module>
    _check_arch()
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1798, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
Thank you for reporting this issue. The error you're encountering is due to the `py-cpuinfo` package, which currently only supports X86, PPC, and ARM CPUs. Unfortunately, it does not support Mac AMD64 architecture.

To address this, you can try the following steps:
1. Ensure you are using the latest version of the Ultralytics package and `py-cpuinfo` by updating them.
2. If the issue persists, you might consider modifying the code to bypass the `py-cpuinfo` dependency or use an alternative method to gather CPU information.

If the problem continues, please let us know, and we can explore further solutions.

**Comment by duguyixiaono1** [comment]
1. I'm sure it is the latest version
2. good idea，i solve it

**Comment by glenn-jocher** [comment]
@duguyixiaono1 interesting. What hardware are you using?

**Comment by glenn-jocher** [comment]
Great news 😃! Your original issue may now be resolved ✅ in PR #14814. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by duguyixiaono1** [comment]
> @duguyixiaono1 interesting. What hardware are you using?

![b730cd89ba1343da4132f213609d2cf2](https://github.com/user-attachments/assets/738efd02-e1fb-4ff6-ae72-71ba1b57007a)

**Comment by glenn-jocher** [comment]
Oh, so strange. Ok well #14814 will work correctly now, ignoring any errors in pycpuinfo and returning "unknown" for CPU type.
