### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found - Issue with torch library

### ISSUE THREAD

**Issue by khanh-blue** [ultralytics/ultralytics#14803]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLOv5 Component
Bug
I am trying to run YOLOv5 model using ultralytics with the torch library. However, I am encountering the following error when I run my script:
Traceback (most recent call last):
  File "D:\thuctap\code\yolov5\detect_person.py", line 1, in <module>
    import torch
  File "D:\ung dung\visual studio\python\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\ung dung\visual studio\python\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### Additional

import torch

**Comment by Y-T-G** [comment]
You could either downgrade the PyTorch to 2.3.1

or

use [this](https://github.com/Acly/krita-ai-diffusion/issues/965#issuecomment-2254625267)
