### ISSUE TITLE
Loading Pre-Trained Own Detect Model to Segmentation Checkpoint (strict = False)

### ISSUE THREAD

**Issue by james-imi** [ultralytics/ultralytics#14922]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a **detect** model with X classes. Now, I have a new dataset for **instance segmentation** that has the same size as previously trained detect model (yolov8m and yolov8m-seg). I want to load the backbone of the pretrained `yolov8m` to `yolov8m-seg` with the same number of X classes and save it into `pretrained-yolov8m-seg.pt`. 

What is the best way to do this? Just using `load_state_dict(..., strict=False)` does not really work.

**Comment by Y-T-G** [comment]
`YOLO("yolov8m-seg.yaml").load("yolov8m.pt")`

You will have to modify the `nc` in the yaml to match your model first.

**Comment by james-imi** [comment]
@Y-T-G Thanks. How do you save it?

**Comment by Y-T-G** [comment]
```python
model.ckpt.update(dict(model=model.model))
del model.ckpt["ema"]
model.save("saved.pt")
```

**Comment by james-imi** [comment]
Thanks. But i am getting this error @Y-T-G 
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/13 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/fantasia/yl/ultralytics/train_opt.py", line 119, in <module>
    fire.Fire(train_opt)
  File "/opt/conda/envs/yolov9/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/yolov9/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/yolov9/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/fantasia/yl/ultralytics/train_opt.py", line 106, in train_opt
    optimizer.maximize(
  File "/opt/conda/envs/yolov9/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 310, in maximize
    self.probe(x_probe, lazy=False)
  File "/opt/conda/envs/yolov9/lib/python3.10/site-packages/bayes_opt/bayesian_optimization.py", line 208, in probe
    self._space.probe(params)
  File "/opt/conda/envs/yolov9/lib/python3.10/site-packages/bayes_opt/target_space.py", line 236, in probe
    target = self.target_func(**params)
  File "/home/ubuntu/fantasia/yl/ultralytics/train_opt.py", line 88, in optimize
    results = model.train(
  File "/home/ubuntu/fantasia/yl/ultralytics/ultralytics/engine/model.py", line 674, in train
    self.trainer.train()
  File "/home/ubuntu/fantasia/yl/ultralytics/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/home/ubuntu/fantasia/yl/ultralytics/ultralytics/engine/trainer.py", line 376, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/opt/conda/envs/yolov9/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/fantasia/yl/ultralytics/ultralytics/nn/tasks.py", line 89, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/ubuntu/fantasia/yl/ultralytics/ultralytics/nn/tasks.py", line 268, in loss
    return self.criterion(preds, batch)
  File "/home/ubuntu/fantasia/yl/ultralytics/ultralytics/utils/loss.py", line 211, in __call__
    anchor_points, stride_tensor = make_anchors(feats, self.stride, 0.5)
  File "/home/ubuntu/fantasia/yl/ultralytics/ultralytics/utils/tal.py", line 300, in make_anchors
    _, _, h, w = feats[i].shape
ValueError: not enough values to unpack (expected 4, got 2)
```

with these values
```
{'lr0': 0.00029014795410535975, 'lrf': 0.7340145479840027, 'momentum': 0.8145355053449916, 'weight_decay': 8.666486408992003e-05, 'warmup_epochs': 1.2721056292993964, 'warmup_momentum': 0.0540406898185942, 'warmup_bias_lr': 0.1604094237257333, 'box': 1.3053819647284528, 'cls': 3.2407994267576665, 'dfl': 0.8334774104649707, 'hsv_h': 0.11542781116222796, 'hsv_s': 0.6084393691165885, 'hsv_v': 0.4829586385137167, 'freeze': 2, 'label_smoothing': 0.08117433184251056}
New https://pypi.org/project/ultralytics/8.2.71 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.36 🚀 Python-3.10.14 torch-2.0.1+cu117 CUDA:0 (NVIDIA A10G, 22592MiB)
engine/trainer: task=segment, mode=train, model=yolov8m-seg-pt-by-bwpa-crops.pt, data=opg-tn-orig-data.yaml, epochs=25, time=None, patience=0, batch=8, imgsz=1280, save=True, save_period=-1, cache=False, device=None, workers=8, project=yolov8-seg-opt-tn, name=8a06274d-e431-401a-8137-ca10e22d8acb, exist_ok=False, pretrained=True, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, freeze=2, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=0.25, iou=0.5, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.00029014795410535975, lrf=0.7340145479840027, momentum=0.8145355053449916, weight_decay=8.666486408992003e-05, warmup_epochs=1.2721056292993964, warmup_momentum=0.0540406898185942, warmup_bias_lr=0.1604094237257333, box=1.3053819647284528, cls=3.2407994267576665, dfl=0.8334774104649707, pose=12.0, kobj=1.0, label_smoothing=0.08117433184251056, nbs=64, hsv_h=0.11542781116222796, hsv_s=0.6084393691165885, hsv_v=0.4829586385137167, degrees=0.0, translate=0.0, scale=0.075, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.0, bgr=0.0, mosaic=0.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=opg-tn-orig-tr.yaml, tracker=botsort.yaml, save_dir=yolov8-seg-opt-tn/8a06274d-e431-401a-8137-ca10e22d8acb

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   5177552  ultralytics.nn.modules.head.Segment          [32, 32, 192, [192, 384, 576]]
YOLOv8m-seg summary: 331 layers, 27258176 parameters, 27258160 gradients, 110.5 GFLOPs

Transferred 537/537 items from pretrained weights
COMET INFO: Experiment is live on comet.com https://www.comet.com/james-adra/yolov8-seg-opt-tn/40ac123f83fd4bfa99c9d42138f44194

Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
```

**Comment by james-imi** [comment]
When I remove this
```
del model.ckpt["ema"]
```

when using the saved model, it works. Any idea why?

**Comment by Y-T-G** [comment]
What's the full code you used to load and save?

**Comment by Y-T-G** [comment]
> When I remove this
> 
> ```
> del model.ckpt["ema"]
> ```
> 
> when using the saved model, it works. Any idea why?

That will just save the original segment model, not the loaded one.

**Comment by james-imi** [comment]
@Y-T-G like this
```
from ultralytics import YOLO

model = YOLO('yolov8l-seg.yaml').load('my_proj/weights/last.pt')
model.ckpt['model'] = model.ckpt["ema"]
model.ckpt.update(dict(model=model.model))
del model.ckpt["ema"]
model.save("yolov8l-seg-pt-my-proj.pt")
```

**Comment by james-imi** [comment]
I have already changed the nc inside yolov8-seg.yaml

**Comment by james-imi** [comment]
both loaded model and the yaml has the same X number of classes

**Comment by Y-T-G** [comment]
Why are you doing this `model.ckpt['model'] = model.ckpt["ema"]`?

**Comment by Y-T-G** [comment]
```python
model.ckpt.update(dict(model=model.model))
del model.ckpt["ema"]
model.ckpt["train_args"]["task"] = "segment"
model.save("saved.pt")
```
