### ISSUE TITLE
Yolov5 Segmentation with SAHI

### ISSUE THREAD

**Issue by Isaac94b** [ultralytics/ultralytics#14944]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey, i have implemented a script with SAHI for bounding box inference, and it worked very well, now i've tried to use the same script for my trained segmentation model, it didn't work with sahi implementation is there any possibilty to use segmentation model with sahi and exporting the results in JSON.

the script im using for SAHI with bounding box

          `import os
          import json
          import torch
          from sahi import AutoDetectionModel
          from sahi.utils.cv import read_image
          from sahi.utils.file import download_from_url
          from sahi.predict import get_prediction, get_sliced_prediction, predict
          from IPython.display import Image
          
          def predict_with_sahi(image_path, model_path, slice_size=672, overlap_ratio=0.2, conf_thres=0.25, iou_thres=0.2):
              # Load the YOLOv5 model using SAHI
              detection_model = AutoDetectionModel.from_pretrained(
                  model_type='yolov5',
                  model_path=model_path,
                  confidence_threshold=conf_thres,
                  device="cuda" if torch.cuda.is_available() else "cpu"
              )
    
    result = get_sliced_prediction(
        image_path,
        detection_model,
        slice_height=slice_size,
        slice_width=slice_size,
        overlap_height_ratio=overlap_ratio,
        overlap_width_ratio=overlap_ratio
    )
    
    return result

      def convert_detections_to_json_serializable(detections):
          serializable_detections = []
          for detection in detections:
              bbox = [float(coord) for coord in detection.bbox.to_xyxy()]  # Convert bbox coordinates to float
              serializable_detections.append({
                  "bbox": bbox,
                  "score": float(detection.score.value),  # Convert score to float
                  "category": detection.category.name
              })
          return serializable_detections
      
      def process_folder(input_folder, output_folder, model_path, slice_size=672, overlap_ratio=0.2, conf_thres=0.25, iou_thres=0.2):
          if not os.path.exists(output_folder):
              os.makedirs(output_folder)
    
    all_detections = []
    
    for image_name in os.listdir(input_folder):
        image_path = os.path.join(input_folder, image_name)
        if not image_path.lower().endswith(('.png', '.jpg', '.jpeg')):
            continue
        
        result = predict_with_sahi(image_path, model_path, slice_size, overlap_ratio, conf_thres, iou_thres)
        
        #export = os.path.join(output_folder, os.path.splitext(image_name)[0])
        export = output_folder
        if not os.path.exists(export):
            os.makedirs(export)

        # Generate a unique file name for the exported image
        export_file_name = f"{os.path.splitext(image_name)[0]}"
        
        result.export_visuals(export_dir=export, text_size= 5, rect_th = 0,  file_name = export_file_name)
        
        serializable_detections = convert_detections_to_json_serializable(result.object_prediction_list)
        detection_info = {
            "image_id": image_name,
            "detections": serializable_detections
        }
        all_detections.append(detection_info)
        
        print(f"Processed and saved result for {image_name}")

    # Save detections to a JSON file
    json_path = os.path.join(output_folder, 'detections.json')
    with open(json_path, 'w') as json_file:
        json.dump(all_detections, json_file, indent=4)

    print(f"All results saved to {output_folder}")
    print(f"Detections JSON saved to {json_path}")

              if __name__ == "__main__":
                  input_folder = "../../imgs/25-31 janvier 2024"
                  output_folder = "result_sahi_2531/detections"
                  # model_path = "runs/train/exp4/weights/best.pt"
                  model_path = "experiments/architecture/YOLOv5/yolo896_spp_p25s50/weights/best.pt"
              
                  process_folder(input_folder, output_folder, model_path, 672)
`

thanks for the help

**Comment by pderrenger** [comment]
@Isaac94b thank you for your detailed question. SAHI does support segmentation models, but the implementation differs slightly from bounding box detection. To use SAHI with your YOLOv5 segmentation model, ensure you are using the correct model type and adjust the prediction functions accordingly. You can refer to the SAHI documentation for specific details on handling segmentation models. If you continue to face issues, please verify that you are using the latest versions of both the SAHI and Ultralytics packages. For further guidance, you can visit the [SAHI Tiled Inference Guide](https://docs.ultralytics.com/guides/sahi-tiled-inference/).

**Comment by Y-T-G** [comment]
If it's a YOLOv5 model you trained using the `ultralytics` library, then you can change `model_type` to `yolov8` and it would work. You again have to fix your script to convert to JSON correctly.

**Comment by Isaac94b** [comment]
> If it's a YOLOv5 model you trained using the `ultralytics` library, then you can change `model_type` to `yolov8` and instance segmentation would work. You again have to fix your script to convert to JSON correctly.
> 
> But if it wasn't trained with Ultralytics but with the original YOLOv5 repo, that wouldn't work and SAHI doesn't support instance segmentation with that.

thanks for your reply, i've trained the model on original YOLOv5 repo, ive tried with changing model_type to yolov8
and im having the following error:

`Performing prediction on 150 slices.
Traceback (most recent call last):
  File "predict_with_sahi_json_seg.py", line 85, in <module>
    process_folder(input_folder, output_folder, model_path, 672)
  File "predict_with_sahi_json_seg.py", line 52, in process_folder
    result = predict_with_sahi(image_path, model_path, slice_size, overlap_ratio, conf_thres, iou_thres)
  File "predict_with_sahi_json_seg.py", line 19, in predict_with_sahi
    result = get_sliced_prediction(
  File "/home/barkati/.local/lib/python3.8/site-packages/sahi/predict.py", line 249, in get_sliced_prediction
    prediction_result = get_prediction(
  File "/home/barkati/.local/lib/python3.8/site-packages/sahi/predict.py", line 93, in get_prediction
    detection_model.perform_inference(np.ascontiguousarray(image_as_pil))
  File "/home/barkati/.local/lib/python3.8/site-packages/sahi/models/yolov8.py", line 73, in perform_inference
    prediction_result = self.model(image[:, :, ::-1], **kwargs)  # YOLOv8 expects numpy arrays to have BGR
  File "/home/barkati/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/barkati/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 556, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/barkati/.local/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 303, in setup_model
    self.model = AutoBackend(
  File "/home/barkati/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/barkati/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 144, in __init__
    model = model.fuse(verbose=verbose)
TypeError: fuse() got an unexpected keyword argument 'verbose'`

**Comment by Y-T-G** [comment]
It wouldn't work if you trained with YOLOv5 repo.
