### ISSUE TITLE
ONNX error on threading "consider passing CUDA_LAUNCH_BLOCKING=1"

### ISSUE THREAD

**Issue by sourabCV** [ultralytics/ultralytics#14969]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have 2 ONNX models i want to run them on threading 
My device has tesla T4 GPU 

One rtsp camera URL i have 
and its sending 15 fps continuous 

so in a while loop i am reading every frame using cv2.videocapture 
to maintain 15 fps during show time i used Threading with queue 
but its showing ERROR
```
File "C:\all_codes\venv\Lib\site-packages\ultralytics\utils\ops.py", line 47, in __enter__
    self.start = self.time()
    torch.cuda.synchronize(self.device)
                 ^^^^^^^^^^^
  File "C:\all_codes\venv\Lib\site-packages\ultralytics\utils\ops.py", line 62, in time
  File "C:\all_codes\venv\Lib\site-packages\torch\cuda\__init__.py", line 892, in synchronize
    torch.cuda.synchronize(self.device)
  File "C:\all_codes\venv\Lib\site-packages\torch\cuda\__init__.py", line 892, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: operation not permitted when stream is capturing
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.      
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

RuntimeError: CUDA error: operation not permitted when stream is capturing
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.      

Exception in thread Thread-47 (function):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-48 (function):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
Exception in thread Thread-49 (function):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
```
How to solve this ?

```
model = YOLO('models/best_mcb_29_6_24_640.onnx', task="detect")
results = model.predict(
        frame, conf=0.5, iou=0.6, imgsz=640, verbose=False,device = [0])
```

### Additional

I have CUDA 12.6
cuDNN : 8.9.7

Code :
```
import torch

# Check if CUDA is available
print(f"CUDA available: {torch.cuda.is_available()}")
```
Output:  CUDA available: True

Code:
```
import torch
import onnxruntime as ort

try:
    providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
    sess = ort.InferenceSession('models/yolov8n-pose.onnx', providers=providers)
    print("Available providers:", sess.get_providers())
    print("Using provider:", sess.get_provider_options())
except Exception as e:
    print("Error:", e)
```
Output :
```
Available providers: ['CUDAExecutionProvider', 'CPUExecutionProvider']
Using provider: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1'}, 'CPUExecutionProvider': {}}
```

**Comment by pderrenger** [comment]
@sourabCV it appears you're encountering a threading issue with ONNX models on a Tesla T4 GPU. The error suggests that CUDA operations are not permitted when the stream is capturing, which is a common issue when using threading with CUDA.

To address this, you can try setting the `CUDA_LAUNCH_BLOCKING` environment variable to `1`, which forces synchronous execution of CUDA operations and can help with debugging. You can set this environment variable in your Python script before running your model inference:

```python
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
```

Additionally, ensure that each thread has its own model instance to avoid concurrency issues. Instantiate the YOLO model within each thread rather than sharing a single instance across threads. This approach helps prevent race conditions and ensures thread safety.

If the issue persists, please verify that you are using the latest versions of the Ultralytics package and ONNX runtime. Updating to the latest versions can sometimes resolve unexpected issues.

For more detailed guidance on thread-safe inference, you can refer to our documentation: https://docs.ultralytics.com/guides/yolo-thread-safe-inference/.

**Comment by sourabCV** [comment]
I used 
```
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
```

and in thread function I added 
`model = YOLO('models/best_mcb_29_6_24_640.onnx', task="detect")`
so now its load yolo model every time to ensure thread safety 

but now error is on loading 
```
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run      
Loading models\yolov8n-pose.onnx for ONNX Runtime inference...
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
  File "c:\all_codes\codeV3.py", line 301, in frameInf
****************************************
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
2024-08-05 16:45:36.8983378 [E:onnxruntime:Default, cuda_call.cc:118 onnxruntime::CudaCall] CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data);     
2024-08-05 16:45:36.9816712 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/model.0/conv/Conv' Status Message: CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data); 
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-45 (function):
Loading models\yolov8n-pose.onnx for ONNX Runtime inference...
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run      
Exception in thread Thread-55 (function):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-54 (function):
    response = gen.send(None)
    self.run()
    self._target(*self._args, **self._kwargs)
    self.result = target(*args, **kwargs)
    self.run()
2024-08-05 16:45:37.2058867 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code rLoading models\yolov8n-pose.onnx for ONNX Runtime inference...
eturned while running Conv node.   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
Name:'/model.0/conv/Conv' Status Message: CUDA error cudaErrorStreamCaptureUnsupported:operation not permitted when stream is capturing
2024-08-05 16:45:37.2153195 [E:onnxruntime:Default, cuda_call.cc:118 onnxruntime::CudaCall] CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data);     
2024-08-05 16:45:37.2883496 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/model.0/conv/Conv' Status Message: CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data); 
Exception in thread Thread-51 (function):
Traceback (most recent call last):
    self.result = target(*args, **kwargs)
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "c:\all_codes\codeV3.py", line 82, in function
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run      
Exception in thread Thread-53 (function):
Traceback (most recent call last):
Loading models\yolov8n-pose.onnx for ONNX Runtime inference...
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run      
Exception in thread Thread-52 (function):
Exception in thread Thread-57 (function):
    self.result = target(*args, **kwargs)
    self.run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "C:\all_codes\venv\Lib\site-packages\torch\utils\_contextlib.py", line 36, in generator_context
Loading models\yolov8n-pose.onnx for ONNX Runtime inference...
Exception in thread Thread-61 (function):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run      
  File "c:\all_codes\codeV3.py", line 82, in function
2024-08-05 16:45:37.5146380 [E:onnxruntime:Default, cuda_call.cc:118 onnxruntime::CudaCall] CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data);     
2024-08-05 16:45:37.5235226 [E:onnxruntime:Default, cuda_call.cc:118 onnxruntime::CudaCall] CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data);     
2024-08-05 16:45:37.5246677 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/model.6/m.0/cv1/conv/Conv' Status Message: CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data); 
2024-08-05 16:45:37.5429866 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/model.1/conv/Conv' Status Message: CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data); 
2024-08-05 16:45:37.6790785 [E:onnxruntime:, inference_session.cc:2045 onnxruntime::InferenceSession::Initialize::<lambda_ac1b736d24ef6ddd1d25cf2738b937a9>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:116 onnxruntime::CudaCall CUDNN failure 4000: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=VMgpu ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=181 ; expr=cudnnCreate(&cudnn_handle_);         


Exception in thread Thread-41 (function):
Exception in thread Thread-49 (function):
Loading models\yolov8n-pose.onnx for ONNX Runtime inference...
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner

```

I solve this error previously by installing onnxruntime-gpu with this command 
`pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple`

and in additional details I show that onnx loading properly 
Now how to solve this ?

**Comment by Y-T-G** [comment]
What's your actual code?

**Comment by sourabCV** [comment]
I can't share my code 
sharing logic 

```
def frameInf(frame):
      model = YOLO('models/best_mcb_29_6_24_640.onnx', task="detect")
      model2 = YOLO('models/best_mcb_21_6_24_640.onnx', task="detect")
      results = model.predict(
                     frame, conf=0.5, iou=0.6, imgsz=640, verbose=False,device = [0])
      results_ = model2.predict(
                     frame, conf=0.5, iou=0.6, imgsz=640, verbose=False,device = [0])

def videocap():
      from here we are capturing videos each frame and sending that frame to frameInf with threading to maintain high 
      FPS
```

**Comment by Y-T-G** [comment]
Why are loading the model inside the function everytime?

**Comment by sourabCV** [comment]
@Y-T-G  to ensures thread safety, is that not require ? 
and how to solve that onnx GPU use issue on thread ?

**Comment by Y-T-G** [comment]
What's the point of thread? It's not going to make your inference faster. If your stream FPS is more than inference, then you should be dropping frames. You can't avoid that.

**Comment by sourabCV** [comment]
i dont want to drop frame my cam sending 30fps and inference time is total with some other calculation 0.06 sec 
so, its allow 15 to 16 frame but  It need to support 30frame, for that reason i used thread.
Because in normal without thread its used 40% of my GPU so if i thread frame its going to use my rest GPU + give me some better FPS.

**Comment by Y-T-G** [comment]
How will you get the frames before the inference is complete? If it takes 0.06s, then it will still take 0.06s with threading, so you either have to wait for the frame results, or you have to skip certain frames.

**Comment by sourabCV** [comment]
let 1 st frame take 10 sec  then if 2nd frame enter in thread within 1 sec then that also consumes 10 sec but 2 frames  I will receive in 11 sec as its started calculation after 1 sec of first frame as per parallel processing.
So this threading will help me to get 30 fps

**Comment by Y-T-G** [comment]
If 1 frame take 10 seconds, then the GPU is already under load, so sending a second frame for inference during that time will make both inference take longer than 10 seconds because now GPU will have to distribute the load to multiple frames.

**Comment by sourabCV** [comment]
1 frame may consume GPU 10%, but rest 90% is left for other use using threading we can use that by parallel processing

**Comment by Y-T-G** [comment]
You can use threading with Queue.

**Comment by Y-T-G** [comment]
When infer one frame, the inference time is not the same as inferring a batch of two frames. Two frames will always take more time. You can try it by using `model.predict([frame_1, frame_2])`. The more frames you add, the longer the inference will take. And this is batched. What you're doing is sequential inference which takes even longer than batched inference.

**Comment by sourabCV** [comment]
but for batch if i wait for 5 frame then In show area also I need to wait. That looks like it sticking on one frame and then instantly after inference it will show 5 frame at first speed. It looks odd.

 pls tell me some ways by what I can boost up fps with realtime view

**Comment by pderrenger** [comment]
To boost FPS with real-time view, consider using a combination of threading and batching. While threading can help utilize more GPU resources, batching can reduce the overhead of processing each frame individually. Ensure you are using the latest versions of the Ultralytics package and ONNX runtime for optimal performance. If the issue persists, you may need to balance between batch size and frame latency to achieve smoother real-time performance.

**Comment by pderrenger** [comment]
Running two ONNX models in separate threads can be challenging due to potential concurrency issues with GPU resources. Ensure you are using the latest versions of the Ultralytics package and ONNX runtime. If the problem persists, consider using process-based parallelism with Python's `multiprocessing` module instead of threading to avoid these issues. This approach can help isolate the models and prevent resource conflicts.

**Comment by narugo1992** [comment]
Following up on the "use multiprocessing" suggestion: that does work but adds IPC overhead per frame, which is the opposite of what you want at 30 FPS in a real-time camera pipeline. The reason shared-session multithreading actually hangs (or throws CUDA failure 700 / CUDNN_STATUS_INTERNAL_ERROR depending on the GPU) is a race in ORT's CUDA EP `Softmax` operator — the cuDNN softmax handle is shared across worker threads of a single `InferenceSession`. It's not specific to your two-model setup; every ult-exported YOLO ONNX has the same race because `Detect._inference()` emits a `Softmax(axis=...)` node for DFL decode, and v11/v12 add several more for attention.

Patching those `Softmax` nodes in the ONNX with the math-equivalent 5-op subgraph removes the race at the graph level, so a single shared session is safe across as many threads as you want — no `CUDA_LAUNCH_BLOCKING=1`, no `multiprocessing`, no model reloading per frame. One-file patcher: https://github.com/deepghs/yolo-onnx-thread-safe . Confirmed on every v3..v12 family × size (COCO128 mAP unchanged, ~430 imgs/s @ 32 workers on yolov8n / H200). Might be a simpler fit for the 30 FPS T4 pipeline than restructuring around processes.

**Comment by glenn-jocher** [comment]
Thanks for sharing that investigation; since this is a closed stale issue and your comment points to a more specific ONNX Runtime CUDA/`Softmax` concurrency bug, please open a new issue with a minimal reproducible example on the latest `ultralytics` and `onnxruntime-gpu` so we can track it properly, and for currently supported usage please follow our [thread-safe inference guide](https://docs.ultralytics.com/guides/yolo-thread-safe-inference) and avoid sharing one GPU ONNX session across threads.

**Comment by narugo1992** [comment]
Opened #24520 with the standalone MRE on latest `ultralytics 8.3.105` + `onnxruntime-gpu 1.23.2` you asked for, plus the bisect down to the single `Softmax` node and the raw ORT crash trace. Happy to add anything else there if more context helps triage.

**Comment by glenn-jocher** [comment]
Thanks for opening #24520 with the MRE, bisect, and raw trace; that’s the right place to track this, so please keep any further updates there and we’ll continue triage on that issue.
