### ISSUE TITLE
workers>0 will error about Multiprocess

### ISSUE THREAD

**Issue by zhu709654396** [ultralytics/ultralytics#1498]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

workers>0 will error about Multiprocess

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Please provide a reproducible example. Our official models have been trained on DDP (multiprocessing) mode with 8 workers per node and we didn't see this problem.

**Comment by zhu709654396** [comment]
> Please provide a reproducible example. Our official models have been trained on DDP (multiprocessing) mode with 8 workers per node and we didn't see this problem.

error：
  Starting training for 299 epochs...                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                  
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size                                                                                                                                                                                                     
  0%|          | 0/20209 [00:00<?, ?it/s]Process Process-2:                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                                
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap                                                                                                                                                                    
    self.run()                                                                                                                                                                                                                                                                    
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/process.py", line 108, in run                                                                                                                                                                           
    self._target(*self._args, **self._kwargs)                                                                                                                                                                                                                                     
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 275, in _worker_loop                                                                                                                                             
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)                                                                                                                                                                                                                           File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/queues.py", line 112, in get r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)                                                                                                                                                                                                              [1926/1973]
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/queues.py", line 112, in get                                                                                                                                                                            
    self._sem.release()                                                                                                                                                                                                                                                           
ValueError: semaphore or lock released too many times                                                                                                                                                                                                                             
Exception in thread Thread-5:                                                                                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                                                                                
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                                                                                                                                            
    self.run()                                                                                                                                                                                                                                                                    
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/threading.py", line 870, in run                                                                                                                                                                                         
    self._target(*self._args, **self._kwargs)                                                                                                                                                                                                                                     
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop                                                                                                                                      
    do_one_step()                                                                                                                                                                                                                                                                 
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step                                                                                                                                           
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)                                                                                                                                                                                                                            
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/queues.py", line 116, in get                                                                                                                                                                            
    return _ForkingPickler.loads(res)                                                                                                                                                                                                                                             
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd                                                                                                                                     
    fd = df.detach()                                                                                                                                                                                                                                                              
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach                                                                                                                                                                 
    return reduction.recv_handle(conn)                                                                                                                                                                                                                                            
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle                                                                                                                                                                 
    return recvfds(s, 1)[0]                                                                                                                                                                                                                                                       
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/reduction.py", line 157, in recvfds                                                                                                                                                                     
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))                                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                                                                
BlockingIOError: [Errno 11] Resource temporarily unavailable                                                                                                                                                                                                                      
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/resource_sharer.py", line 149, in _serve                                                                                                                                                                
    send(conn, destination_pid)                                                                                                                                                                                                                                                   
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/resource_sharer.py", line 50, in send                                                                                                                                                                   
    reduction.send_handle(conn, new_fd, pid)                                                                                                                                                                                                                                      
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/reduction.py", line 184, in send_handle                                                                                                                                                                 
    sendfds(s, [handle])                                                                                                                                                                                                                                                          
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/reduction.py", line 149, in sendfds                                                                                                                                                                     
    sock.sendmsg([msg], [(socket.SOL_SOCKET, socket.SCM_RIGHTS, fds)])                                                                                                                                                                                                            
BrokenPipeError: [Errno 32] Broken pipe                                                                                                                                                                                                                                           
Exception in thread Thread-4:                                                                                                                                                                                                                                                     
Exception in thread Thread-4:                                                                                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                                                                                
Traceback (most recent call last):                                                                                                                                                                                                                                                
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/queues.py", line 108, in get                                                                                                                                                                            
  File "/home/yjauto/miniconda3/envs/yolov8/lib/python3.8/multiprocessing/queues.py", line 108, in get                                                                                                                                                                            
    raise Empty                                                                                                                                                                                                                                                                   
    raise Empty                                                                                                                                                                                                                                                                   
_queue.Empty                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                  
During handling of the above exception, another exception occurred:                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                                                                                                _queue.Empty

**Comment by Laughing-q** [comment]
@zhu709654396 hi, I only saw your error log. Reproducible example means a least provide your training command and package version.

**Comment by zhu709654396** [comment]
> @zhu709654396你好，我只看到了你的错误日志。可重现的例子意味着至少提供你的训练命令和包版本。:)

Training Command：
   from ultralytics import YOLO
        model = YOLO(path_cfg_dic['yolov8s.pt'])
        results = model.train(data="my_data.yaml", epochs=299, device=1, workers=0,batch=32)
包版本我是git官方代码，然后"pip install -e '.[dev]'"

**Comment by Laughing-q** [comment]
@zhu709654396 请问你可以使用coco128.yaml数据复现这个问题吗

**Comment by zhu709654396** [comment]
> @zhu709654396 请问你可以使用coco128.yaml数据复现这个问题吗



> @zhu709654396请问你可以使用coco128.yaml数据恢复这个问题吗



I just tried, but I still reported the above error

**Comment by Laughing-q** [comment]
@zhu709654396 无法复现你的问题，我设置`workers=8`正常训练，可能是你的本地环境有些问题
![image](https://user-images.githubusercontent.com/61612323/226304932-5cc9c978-5e63-4d40-a7d7-952eb93dcca6.png)

**Comment by zhu709654396** [comment]
好的感谢



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 20, 2023 17:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] workers&gt;0 will error about Multiprocess (Issue #1498)




 
@zhu709654396 无法复现你的问题，我设置workers=8正常训练，可能是你的本地环境有些问题

**Comment by Laughing-q** [comment]
@zhu709654396 我先关闭这个issue了，因为workers在我们的测试中正常工作，如果你之后还有相关的问题请随时重新打开。

**Comment by zhu709654396** [comment]
好的



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 20, 2023 18:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] workers&gt;0 will error about Multiprocess(Issue #1498)




 
@zhu709654396 我先关闭这个issue了，因为workers在我们的测试中正常工作，如果你之后还有相关的问题请随时重新打开。
