### ISSUE TITLE
new yolo install errors out, both CLI and Python 

### ISSUE THREAD

**Issue by gschlossnagle** [ultralytics/ultralytics#15001]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Fresh install of ultralytics via pip on MacOS.

Running sample detect on the cli returns the following error

> % yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'                               
Ultralytics YOLOv8.2.74 🚀 Python-3.12.2 torch-2.4.0 CPU (Apple M2 Max)
Traceback (most recent call last):
  File "/Users/george/miniconda3/bin//yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 834, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 556, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 303, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 124, in __init__
    ) = self._model_type(w)
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 656, in _model_type
    sf = list(export_formats().Suffix)  # export suffixes
              ^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/engine/exporter.py", line 116, in export_formats
    return pandas.DataFrame(x, columns=["Format", "Argument", "Suffix", "CPU", "GPU"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 850, in __init__
    columns = ensure_index(columns)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7647, in ensure_index
    return Index(index_like, copy=copy, tupleize_cols=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 565, in __new__
    arr = sanitize_array(data, None, dtype=dtype, copy=copy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/construction.py", line 654, in sanitize_array
    subarr = maybe_convert_platform(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/dtypes/cast.py", line 139, in maybe_convert_platform
    arr = lib.maybe_convert_objects(arr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2538, in pandas._libs.lib.maybe_convert_objects
TypeError: Cannot convert numpy.ndarray to numpy.ndarray
>

I get the same backtrace when using python as well:

```
from ultralytics import YOLO
model = YOLO("yolov8m.pt")
results = model.predict("/Users/george/PycharmProjects/sharpnessDetection/samples/cat_dog.jpg")
```

>
/Users/george/miniconda3/bin/python /Users/george/PycharmProjects/sharpnessDetection/test.py 
Traceback (most recent call last):
  File "/Users/george/PycharmProjects/sharpnessDetection/test.py", line 20, in <module>
    results = model.predict("/Users/george/PycharmProjects/sharpnessDetection/samples/cat_dog.jpg")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 556, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 303, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 124, in __init__
    ) = self._model_type(w)
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 656, in _model_type
    sf = list(export_formats().Suffix)  # export suffixes
              ^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/ultralytics/engine/exporter.py", line 116, in export_formats
    return pandas.DataFrame(x, columns=["Format", "Argument", "Suffix", "CPU", "GPU"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 850, in __init__
    columns = ensure_index(columns)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7647, in ensure_index
    return Index(index_like, copy=copy, tupleize_cols=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 565, in __new__
    arr = sanitize_array(data, None, dtype=dtype, copy=copy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/construction.py", line 654, in sanitize_array
    subarr = maybe_convert_platform(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/george/miniconda3/lib/python3.12/site-packages/pandas/core/dtypes/cast.py", line 139, in maybe_convert_platform
    arr = lib.maybe_convert_objects(arr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2538, in pandas._libs.lib.maybe_convert_objects
TypeError: Cannot convert numpy.ndarray to numpy.ndarray

Process finished with exit code 1
>

### Environment

```george@Georges-MBP sharpnessDetection % yolo checks
Ultralytics YOLOv8.2.74 🚀 Python-3.12.2 torch-2.4.0 CPU (Apple M2 Max)
Setup complete ✅ (12 CPUs, 32.0 GB RAM, 3110.6/3721.9 GB disk)

OS                  macOS-14.5-arm64-arm-64bit
Environment         Darwin
Python              3.12.2
Install             pip
RAM                 32.00 GB
CPU                 Apple M2 Max
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
george@Georges-MBP sharpnessDetection % ```

### Minimal Reproducible Example

`yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'`

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@gschlossnagle thank you for reporting this issue. It appears to be related to the conversion of numpy arrays within the pandas DataFrame during the model setup. To help us diagnose and resolve this, please ensure you are using the latest versions of all relevant packages, including `ultralytics`, `torch`, and `pandas`. You can update them using:

```bash
pip install --upgrade ultralytics torch pandas
```

If the issue persists after updating, please let us know. Additionally, it would be helpful to know if this error occurs with other models or datasets. This information will assist us in pinpointing the problem more effectively. Thank you for your cooperation.

**Comment by Y-T-G** [comment]
https://pandas.pydata.org/docs/whatsnew/v2.2.2.html#pandas-2-2-2-is-now-compatible-with-numpy-2-0

Try `pip install pandas==2.2.1`

**Comment by Y-T-G** [comment]
https://stackoverflow.com/a/78756422
