### ISSUE TITLE
Errors in the conversion RT-DETR to TFLITE

### ISSUE THREAD

**Issue by gfernandezAIVIDEX** [ultralytics/ultralytics#15026]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Ultralytics YOLOv8.2.74 🚀 Python-3.10.12 torch-2.2.0+cu121 CPU (Intel Core(TM) i9-10900K 3.70GHz)
rt-detr-l summary: 494 layers, 32,004,290 parameters, 0 gradients, 103.5 GFLOPs

PyTorch: starting from 'pp.pt' with input shape (1, 3, 512, 512) BCHW and output shape(s) (1, 300, 14) (63.1 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.16.2 opset 16...
ONNX: slimming with onnxslim 0.1.32...
ONNX: export success ✅ 8.5s, saved as 'pp.onnx' (125.3 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/guillermo/.local/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/guillermo/.local/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/guillermo/.local/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/guillermo/.local/lib/python3.10/site-packages/onnx2tf/ops/MaxPool.py", line 65, in make_node
    input_tensor = tf_layers_dict[graph_node_input.name]['tf_node'] \
KeyError: '/model.0/Pad_output_0'

ERROR: input_onnx_file_path: pp.onnx
ERROR: onnx_op_name: /model.0/pool/MaxPool
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

### Environment

Ultralytics YOLOv8.2.74 🚀 Python-3.10.12 torch-2.4.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3090, 24226MiB)
Setup complete ✅ (20 CPUs, 62.7 GB RAM, 708.8/913.8 GB disk)

OS                  Linux-6.5.0-44-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 62.65 GB
CPU                 Intel Core(TM) i9-10900K 3.70GHz
CUDA                12.1

numpy               ✅ 1.24.3<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.2>=3.3.0
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.11.2>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

I have also tried the following configuration: (using torch==2.2.1 and tensorflow-cpu==2.13.1 as discussed at https://github.com/ultralytics/ultralytics/issues/8599.)
Ultralytics YOLOv8.2.74 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3090, 24226MiB)
Setup complete ✅ (20 CPUs, 62.7 GB RAM, 708.0/913.8 GB disk)

OS                  Linux-6.5.0-44-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 62.65 GB
CPU                 Intel Core(TM) i9-10900K 3.70GHz
CUDA                12.1

numpy               ✅ 1.24.3<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.2>=3.3.0
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.11.2>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

from ultralytics import RTDETR

# Load a model
model = RTDETR("pp.pt")

# Export the model
#model.export(format="tflite",imgsz=512,dynamic=False,nms=False,half=True,opset=16 )
model.export(format="tflite")

### Additional

The onnx intermediate format is generated. If I try to verify the onnx model I get the following error:

Traceback (most recent call last):
  File "/home/guillermo/Projects/work_folder/model/verify.py", line 7, in <module>
    onnx.checker.check_model(model)
  File "/home/guillermo/.local/lib/python3.10/site-packages/onnx/checker.py", line 179, in check_model
    C.check_model(
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '/model.0/Pad_output_0' of node: 
name: /model.0/pool/MaxPool OpType: MaxPool
 is not output of any previous nodes.

###################################################
The code used for the onnx verification is as follows:
import onnx

# Load the ONNX model
model = onnx.load("pp.onnx")

# Check that the IR is well formed
onnx.checker.check_model(model)

# Print a Human readable representation of the graph
onnx.helper.printable_graph(model.graph)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@gfernandezAIVIDEX thank you for reporting this issue. It appears that the error occurs during the conversion of the RT-DETR model to TFLite Edge TPU format, specifically related to the `MaxPool` operation in the ONNX model. 

To address this, please ensure you are using the latest versions of all relevant packages. If the issue persists, consider the following steps:

1. Verify the ONNX model: Ensure the ONNX model is valid and correctly formatted before conversion. You can use the `onnx.checker.check_model` function to validate the model.
2. Adjust ONNX2TF parameters: Try using the `-b` or `-ois` options to rewrite dynamic dimensions to static shapes, or the `-kt` or `-kat` options if the input OP has an irregular channel arrangement.
3. Update ONNX2TF: Make sure you are using the latest version of the `onnx2tf` package, as updates may include fixes for such issues.

For more detailed guidance, please refer to the [ONNX2TF documentation](https://github.com/PINTO0309/onnx2tf#parameter-replacement).

If the problem continues, please let us know, and we can further investigate. For additional resources, you can visit our [Edge TPU integration guide](https://docs.ultralytics.com/integrations/edge-tpu/).

**Comment by Y-T-G** [comment]
Try this:

https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by gfernandezAIVIDEX** [comment]
> Try this:
> 
> [#14235 (comment)](https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301)

I have tried with the exact configuration given in the post after running yolo checks and modifying the versions given in the solution tensorflow(2.16.1), tf-keras(2.16.0) and onnx2tf(1.22.3), but the result is exactly the same

**Comment by gfernandezAIVIDEX** [comment]
> @gfernandezAIVIDEX thank you for reporting this issue. It appears that the error occurs during the conversion of the RT-DETR model to TFLite Edge TPU format, specifically related to the `MaxPool` operation in the ONNX model.
> 
> To address this, please ensure you are using the latest versions of all relevant packages. If the issue persists, consider the following steps:
> 
>     1. Verify the ONNX model: Ensure the ONNX model is valid and correctly formatted before conversion. You can use the `onnx.checker.check_model` function to validate the model.
> 
>     2. Adjust ONNX2TF parameters: Try using the `-b` or `-ois` options to rewrite dynamic dimensions to static shapes, or the `-kt` or `-kat` options if the input OP has an irregular channel arrangement.
> 
>     3. Update ONNX2TF: Make sure you are using the latest version of the `onnx2tf` package, as updates may include fixes for such issues.
> 
> 
> For more detailed guidance, please refer to the [ONNX2TF documentation](https://github.com/PINTO0309/onnx2tf#parameter-replacement).
> 
> If the problem continues, please let us know, and we can further investigate. For additional resources, you can visit our [Edge TPU integration guide](https://docs.ultralytics.com/integrations/edge-tpu/).

Thank you very much for the quick response.
Using the latest onnx2tf version supported by ultralytics (onnx2tf 1.22.3) the result is the same. As indicated in the description of the problem, running model.export generates the ONNX model, but if I run onnx.checker.check_model on this model I get the following error:

onnx.checker.check_model(model)
File "/home/guillermo/.local/lib/python3.10/site-packages/onnx/checker.py", line 179, in check_model
C.check_model(onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '/model.0/Pad_output_0' of node:
name: /model.0/pool/MaxPool OpType: MaxPool is not output of any previous nodes.

So it seems that the conversion to ONNX is not being performed correctly. For this conversion I am using model.export(format="tflite"). 

I would be very grateful for new comments to solve the problem.

Thank you.
Best regards

**Comment by pderrenger** [comment]
Thank you for the detailed follow-up. Given that the ONNX model itself is not passing validation, it seems the issue originates during the conversion to ONNX. Please ensure you are using the latest versions of all relevant packages, including PyTorch and ONNX. If the issue persists, you might want to try simplifying the model before conversion or using different export parameters. Additionally, consider checking for any updates or patches in the Ultralytics repository that might address this issue. If the problem continues, please let us know, and we can further investigate.

**Comment by gfernandezAIVIDEX** [comment]
We have not been able to generate the TFLITE model of RT-DETR but we have managed to generate the ONNX model that passes verification.
To speed up the model execution, we would like to use the GPU, but we are getting problems with the int64 data type. Is it possible to change within the model int64 to float32 operations? If so, where is the model code hosted?

Thank you in advance.
Best regards.
