### ISSUE TITLE
Unsuccessful Conversion of Yolo-V10S FP32-TFlite to  RKNN

### ISSUE THREAD

**Issue by aayushb-95** [ultralytics/ultralytics#15039]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Everybody,
I am trying to convert the Yolo-V10S FP32-TFlite model to RKNN. However, I am encountering the following error:

```
/home/aayush/miniconda3/envs/rknn_toolkit_1.7.5/bin/python 
/home/aayush/yolo_create_rknn.py 
W rknn-toolkit version: 1.7.5
--> Config model
--> Loading model
TFLite Model Loaded /home/aayush/v10s.tflite
--> Building model
E Catch exception when loading tflite model: /home/aayush/v10s.tflite!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/tflite_loader.py", line 573, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser.parse
E   File "rknn/base/RKNNlib/converter/tflite_loader.py", line 503, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser._build_layers
E   File "rknn/base/RKNNlib/converter/tflite_loader.py", line 338, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser._get_layer_RKNN_op
E   File "rknn/base/RKNNlib/converter/lite/RKNN_map_op.py", line 844, in rknn.base.RKNNlib.converter.lite.RKNN_map_op.RKNNMapOp.map_RKNN_ops
E   File "rknn/base/RKNNlib/converter/lite/RKNN_map_op.py", line 811, in rknn.base.RKNNlib.converter.lite.RKNN_map_op._cast
E AttributeError: 'NoneType' object has no attribute 'InDataType'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Traceback (most recent call last):
  File "/home/aayush/yolo_create_rknn.py", line 49, in <module>
    ret = rknn.build(do_quantization=True, dataset='/home/aayush/img_list.txt', pre_compile=False, rknn_batch_size=1)
  File "/home/aayush/miniconda3/envs/rknn_toolkit_1.7.5/lib/python3.8/site-packages/rknn/api/rknn.py", line 272, in build
    inputs = self.rknn_base.net.get_input_layers()
AttributeError: 'NoneType' object has no attribute 'get_input_layers'
```

This error generally occurs when the RKNN cannot read the input layer of the model. There may be an issue when converting Pytorch to TFLite. 

Packages used-

```
Package                      Version
---------------------------- -----------
absl-py                      2.1.0
astunparse                   1.6.3
certifi                      2024.7.4
cffi                         1.16.0
charset-normalizer           3.3.2
coloredlogs                  15.0.1
contourpy                    1.2.1
cycler                       0.12.1
filelock                     3.15.4
flatbuffers                  24.3.25
fonttools                    4.53.1
fsspec                       2024.6.1
gast                         0.6.0
google-pasta                 0.2.0
grpcio                       1.65.4
h5py                         3.11.0
humanfriendly                10.0
idna                         3.7
Jinja2                       3.1.4
keras                        3.4.1
kiwisolver                   1.4.5
libclang                     18.1.1
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.0
mdurl                        0.1.2
ml-dtypes                    0.4.0
mpmath                       1.3.0
namex                        0.0.8
networkx                     3.3
numpy                        1.26.4
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu12            9.1.0.70
nvidia-cufft-cu12            11.0.2.54
nvidia-curand-cu12           10.3.2.106
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu12             2.20.5
nvidia-nvjitlink-cu12        12.6.20
nvidia-nvtx-cu12             12.1.105
onnx                         1.16.2
onnx-graphsurgeon            0.5.2
onnx2tf                      1.22.3
onnxruntime                  1.18.1
onnxslim                     0.1.32
opencv-python                4.10.0.84
opt-einsum                   3.3.0
optree                       0.12.1
packaging                    24.1
pandas                       2.2.2
pillow                       10.4.0
pip                          24.0
protobuf                     3.20.3
psutil                       6.0.0
py-cpuinfo                   9.0.0
pybind11                     2.13.1
pycparser                    2.22
Pygments                     2.18.0
pyparsing                    3.1.2
python-dateutil              2.9.0.post0
pytz                         2024.1
PyYAML                       6.0.1
requests                     2.32.3
rich                         13.7.1
scipy                        1.14.0
seaborn                      0.13.2
setuptools                   69.5.1
six                          1.16.0
sng4onnx                     1.0.4
sounddevice                  0.4.7
sympy                        1.13.1
tensorboard                  2.17.0
tensorboard-data-server      0.7.2
tensorflow                   2.17.0
tensorflow-cpu               2.17.0
tensorflow-io-gcs-filesystem 0.37.1
termcolor                    2.4.0
tf_keras                     2.17.0
tflite-support               0.4.4
torch                        2.4.0
torchvision                  0.19.0
tqdm                         4.66.5
triton                       3.0.0
typing_extensions            4.12.2
tzdata                       2024.1
ultralytics                  8.2.73
ultralytics-thop             2.0.0
urllib3                      2.2.2
Werkzeug                     3.0.3
wheel                        0.43.0
wrapt                        1.16.0
```

**Comment by pderrenger** [comment]
@aayushb-95 it appears that the error you're encountering is related to the RKNN toolkit's inability to read the input layer of the TFLite model. This issue might stem from the conversion process from PyTorch to TFLite. To troubleshoot, please ensure you are using the latest versions of the Ultralytics and TensorFlow packages. Additionally, verify that the model conversion steps are correctly followed as per the [Ultralytics TFLite export guide](https://docs.ultralytics.com/integrations/tflite/). If the issue persists, consider reaching out to the RKNN toolkit development team with the detailed log file for further assistance.

**Comment by aayushb-95** [comment]
Hi @pderrenger ,
Thank you for getting back to me. I am using the export guide and it seems there is an issue with the RKNN toolkit not able to parse the input layer. I will get back to the RKNN guys.

**Comment by pderrenger** [comment]
Hi @aayushb-95,

Thanks for the update. It sounds like a good plan to reach out to the RKNN team for further assistance. In the meantime, please ensure you are using the latest versions of the Ultralytics and TensorFlow packages to rule out any compatibility issues. If you encounter any other issues or need further assistance, feel free to ask.
