### ISSUE TITLE
CUDA out of memory for running segmentation predictions with `retina_masks=True`

### ISSUE THREAD

**Issue by dh031200** [ultralytics/ultralytics#1504]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

If I do 'retina_masks=True' to get a high resolution result video, out of memory comes out.
Memory is constantly increasing while running prediction.
```bash
...
...
video 1/1 (174/600) /mnt/e/DH/Research/ultralytics/sample.mp4: 384x640 2 sidewalks, 2 broken_sidewalks, 2 roads, 38.2ms
video 1/1 (175/600) /mnt/e/DH/Research/ultralytics/sample.mp4: 384x640 2 sidewalks, 2 broken_sidewalks, 2 roads, 12.6ms
Traceback (most recent call last):
  File "/mnt/e/DH/Research/ultralytics/test.py", line 5, in <module>
    results = model("sample.mp4", save=True, half=True, project='segmentation-results', name='yolov8-l', boxes=False, retina_masks=True)
  File "/mnt/e/DH/Research/ultralytics/ultralytics/yolo/engine/model.py", line 99, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/dh/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/e/DH/Research/ultralytics/ultralytics/yolo/engine/model.py", line 227, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/mnt/e/DH/Research/ultralytics/ultralytics/yolo/engine/predictor.py", line 114, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/home/dh/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/mnt/e/DH/Research/ultralytics/ultralytics/yolo/engine/predictor.py", line 193, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/mnt/e/DH/Research/ultralytics/ultralytics/yolo/v8/segment/predict.py", line 75, in write_results
    self.annotator.masks(masks=mask.masks, colors=[colors(x, True) for x in det.cls], im_gpu=im_gpu)
  File "/mnt/e/DH/Research/ultralytics/ultralytics/yolo/utils/plotting.py", line 123, in masks
    mcs = (masks_color * inv_alph_masks).sum(0) * 2  # mask color summand shape(n,h,w,3)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 12.00 GiB total capacity; 9.67 GiB already allocated; 0 bytes free; 11.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
  

I found this issue.
[#1413](https://github.com/ultralytics/ultralytics/issues/1413#issuecomment-1467446276)

When I add `stream=True`
The program ended without any work.

So, I added some code for debugging. But, I can't reached `stream_inference`  method
```
(yolov8) dh@DHBS:/mnt/e/DH/Research/ultralytics$ python test.py
reached: ultralytics/yolo/engine/model.py | __call__
reached: ultralytics/yolo/engine/predictor.py | BasePredictor.__call__
stream: True
if stream - True branch

(yolov8) dh@DHBS:/mnt/e/DH/Research/ultralytics$ python test.py
reached: ultralytics/yolo/engine/model.py | __call__
reached: ultralytics/yolo/engine/predictor.py | BasePredictor.__call__
stream: False
if stream - False branch
reached: ultralytics/yolo/engine/predictor.py | BasePredictor.stream_inference
```

### Environment

ENV1. 
- YOLO: Ultralytics YOLOv8.0.53 🚀 Python-3.10.9 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
- OS: Ubuntu 22.04
- Python: 3.10.9

ENV2.
- YOLO: Ultralytics YOLOv8.0.54 🚀 Python-3.10.9 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
- OS: Ubuntu 22.04(WSL)
- Python: 3.10.9

### Minimal Reproducible Example

```Python
from ultralytics import YOLO

model = YOLO('road-seg-epoch3.pt')

results = model("sample.mp4", save=True, half=True, project='segmentation-results', name='yolov8-l', boxes=False, retina_masks=True)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dh031200 yes this is because inference results (including masks that take a lot of memory) are being accumulated in your results. You should use `stream=True` argument and handle your results one at a time. See https://docs.ultralytics.com/modes/predict/
