### ISSUE TITLE
Training a Model on ClearML Worker returns the Help section on how to start training. 

### ISSUE THREAD

**Issue by ChaseDDevelopment** [ultralytics/ultralytics#1551]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Integrations

### Bug

 Hey Guys, 
 
 When I start training a model locally, with the following command:
 
```
yolo detect train data={PATH_TO_DATASET}/data.yaml  model=yolov8s.pt epochs=2000 imgsz=640 batch=-1 cache=true/ram
```

The command executes without issues, and begins logging to my ClearML instance. 

When I try to run it with:

```yolo detect train data=clearml://5fc7358d024d41f38e88ca443b973904  model=yolov8s.pt epochs=2000 imgsz=640 batch=-1 cache=true/ram  model=yolov8s.pt epochs=2000 imgsz=640 batch=-1 cache=true/ram```

I get 

```yolo/engine/trainer: task=detect, mode=train, model=yolov8s.pt, data=clearml://5fc7358d024d41f38e88ca443b973904, epochs=2000, patience=50, batch=-1, imgsz=640, save=True, save_period=-1, cache=true/ram, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train
Traceback (most recent call last):
  File "/home/{USER}/.local/share/virtualenvs/{PROJECRT}-NfKJM7jZ/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 123, in __init__
    self.data = check_det_dataset(self.args.data)
  File "/home/{USER}/.local/share/virtualenvs/{PROJECT}-NfKJM7jZ/lib/python3.8/site-packages/ultralytics/yolo/data/utils.py", line 196, in check_det_dataset
    data = check_file(dataset)
  File "/home/{USER}/.local/share/virtualenvs/{PORJECT}-NfKJM7jZ/lib/python3.8/site-packages/ultralytics/yolo/utils/checks.py", line 281, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'clearml://5fc7358d024d41f38e88ca443b973904' does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/{USER}/.local/share/virtualenvs/{project}-NfKJM7jZ/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/{USER}/.local/share/virtualenvs/{PROJECT}-NfKJM7jZ/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 318, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/{USER}/.local/share/virtualenvs/{PROJECT}-NfKJM7jZ/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 321, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides)
  File "/home/{USER}/.local/share/virtualenvs/{PROJECT}-NfKJM7jZ/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{self.args.data}' error ❌ {e}")) from e
RuntimeError: Dataset 'clearml://5fc7358d024d41f38e88ca443b973904' error ❌ 'clearml://5fc7358d024d41f38e88ca443b973904' does not exist
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
```

So my dataset cannot be found with clearml in the training command, but when i use:

```clearml-data get --id 5fc7358d024d41f38e88ca443b973904```

The dataset downloads properly. and clearly does exist within my ClearML instance. 

And finally when trying to Run a training task on one of my ClearML worker's, the task installs the correct dependencies and finishes with this:

```Environment setup completed successfully

Starting Task Execution:


    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of [detect, segment, classify]
                MODE (required) is one of [train, val, predict, export, track]
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
    
```

The above task in ClearML is a "Cloned" job of the original command that works properly, and reports metrics to my clearml server. I've tried searching the Yolov8 Docs for more information on the ClearML integration to no avail - Or I missed it. So I then started using the same commands I would use to train a model on ClearML with Yolov5. If there are updated ways to do this with V8, where in the Documentation can I find this?

Thanks so much for taking a look!

### Environment

-- LOCAL Ultralytics YOLOv8.0.55 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24212MiB)
-- Local OS: Ubuntu 22.04
-- ClearML Server Instance: Ubuntu 22.04
-- ClearML Worker Instance: Ubuntu 22.04
-- Python 3.8.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ChaseDDevelopment hi there! Sorry, we don't have training directly from ClearML dataset in place as a feature, this is why you are getting this error.

**Comment by ChaseDDevelopment** [comment]
> @ChaseDDevelopment hi there! Sorry, we don't have training directly from ClearML dataset in place as a feature, this is why you are getting this error.

No problem, Glad to know why It's happening. That would presumably also be why the training on a ClearML Worker is getting hung up on the training command. 

```Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of [detect, segment, classify]
                MODE (required) is one of [train, val, predict, export, track]
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'
```

Thanks for your time!
