### ISSUE TITLE
Problem Loading Custom Pretrained Weights in YOLO Model

### ISSUE THREAD

**Issue by BattleOfDance** [ultralytics/ultralytics#15609]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am encountering an issue when trying to load and use a custom pretrained weight file (pretrained.pt) in my YOLO model during training. The code does not seem to correctly apply the pretrained weights, and I am unsure if the problem is with the file path, the format of the weights, or the way the weights are being integrated into the model. I need help troubleshooting this issue.
following are codes causing problems    model = YOLO('pretrained.pt')  # 使用预训练权重训练
and bug reports are 
D:\Anaconda\envs\torch1121-py38\python.exe C:/Users/user/Desktop/TDNC/TDNC/ultralytics/ultralytics/yolov5s_train.py
Traceback (most recent call last):
  File "C:/Users/user/Desktop/TDNC/TDNC/ultralytics/ultralytics/yolov5s_train.py", line 9, in <module>
    model = YOLO('pretrained.pt')  # 使用预训练权重训练
  File "C:\Users\user\Desktop\TDNC\TDNC\ultralytics\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\user\Desktop\TDNC\TDNC\ultralytics\ultralytics\engine\model.py", line 142, in __init__
    self._load(model, task=task)
  File "C:\Users\user\Desktop\TDNC\TDNC\ultralytics\ultralytics\engine\model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\user\Desktop\TDNC\TDNC\ultralytics\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "C:\Users\user\Desktop\TDNC\TDNC\ultralytics\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "C:\Users\user\Desktop\TDNC\TDNC\ultralytics\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "D:\Anaconda\envs\torch1121-py38\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\Anaconda\envs\torch1121-py38\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "D:\Anaconda\envs\torch1121-py38\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'Model' on <module 'models.yolo' from 'C:\\Users\\user\\Desktop\\TDNC\\TDNC\\ultralytics\\ultralytics\\models\\yolo\\__init__.py'>

Process finished with exit code 1

**Comment by Y-T-G** [comment]
How did you train it? Did you use ultralytics?
