### ISSUE TITLE
Student Model: Yolov8 Knowledge Distillation Implementation

### ISSUE THREAD

**Issue by Murtazaabidi1** [ultralytics/ultralytics#15679]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Everyone!!

Seeking advice on how to effectively train the student model just need the structure guideline for the student model training script. Need assistance with calculating the distillation loss during the training process

Objective: Implement Knowledge Distillation on YOLOv8.
Teacher Model:
Modified YOLOv8 by replacing the backbone with ResNet50.
Trained the teacher model using a CLI command.
Obtained the trained model weights (t_best.pt and last_weights).
Dataset: RGB

Student Model:
Modified YOLOv8n by replacing the backbone with ResNet50 and call it in the default model architecture from ultralytics > cfg > default.yaml.
Loading the teacher model weights (t_best.pt).
Loaded the dataset using data.yaml(IR).
Dataset: IR images

**Comment by Murtazaabidi1** [comment]
Thank you for the suggestions and guidance on implementing knowledge distillation with YOLOv8. I wanted to let you know that I have already trained the student model using a script I wrote, which calculates the losses by combining the standard YOLO loss with a distillation term. For the initial process, I used the LLVIP dataset with 500 images, focusing on a single class, "person," for both the teacher and student models.
This is the student model result 
![student_result](https://github.com/user-attachments/assets/13d3d20c-100f-4903-af9f-4a69bc77062d)

**Comment by glenn-jocher** [comment]
@Murtazaabidi1 great to hear that you've successfully trained the student model using knowledge distillation with YOLOv8! If you have any further questions or need additional assistance, feel free to ask. Keep up the good work!

**Comment by Murtazaabidi1** [comment]
@glenn-jocher Thanks for the information. I'm currently facing an issue where the RGB model (acting as the teacher) is experiencing mis-detections in dark scenarios, while the student model is performing well. I believe that if I switch the roles, using IR images as the teacher and RGB as the student, the prediction accuracy could be improved. By leveraging the logits or soft labels from the IR model, this approach might reduce mis-detections and enhance the overall performance of the RGB model.

**Comment by glenn-jocher** [comment]
Thank you for sharing your observations. Switching the roles and using the IR model as the teacher while the RGB model acts as the student could indeed help improve prediction accuracy in dark scenarios. Leveraging the logits or soft labels from the IR model may reduce mis-detections and enhance the overall performance of the RGB model. If you encounter any issues during this process, feel free to reach out.

**Comment by Murtazaabidi1** [comment]
@glenn-jocher  When I trying to trainied the student model its working fine but for printing the distallition loss or combine loss its some errors.. If you know how to get the  distallition loss or combine loss after compeleting training let me know I will paste my code and error 

CODE:
import torch
import torch.nn as nn
import torch.optim as optim
from ultralytics import YOLO

# Load teacher and student models
teacher_model = YOLO("/home/murtaza/Desktop/Work/YOLOv8/ultralytics/t_ir_best.pt")  # Pre-trained teacher model
student_model = YOLO("yolov8n.pt")  # Initialize student model (or load a different pretrained model)

# Put teacher model in evaluation mode
teacher_model.model.eval()

# Define distillation loss function (e.g., KL divergence loss for logits)
distillation_loss_fn = nn.KLDivLoss(reduction="batchmean")

# Function to perform a single training step with distillation
def training_step(student_model, teacher_model, images, targets, optimizer, alpha=0.5, temperature=2.0):
    # Forward pass through teacher model
    with torch.no_grad():
        teacher_output = teacher_model.model(images)

    # Forward pass through student model
    student_output = student_model.model(images)

    # Compute distillation loss
    student_logits = student_output['output']
    teacher_logits = teacher_output['output']
    
    # Adjust teacher logits using temperature
    teacher_logits = teacher_logits / temperature
    student_logits = student_logits / temperature

    distillation_loss = distillation_loss_fn(
        nn.functional.log_softmax(student_logits, dim=-1),
        nn.functional.softmax(teacher_logits, dim=-1)
    )

    # Compute standard loss (e.g., YOLO loss)
    loss = student_model.loss_fn(student_output, targets)

    # Combine standard loss and distillation loss
    total_loss = alpha * distillation_loss + (1 - alpha) * loss

    # Backward pass and optimization
    optimizer.zero_grad()
    total_loss.backward()
    optimizer.step()

    return total_loss.item()

# Train the student model with knowledge distillation and save losses
def train_student_with_distillation(student_model, teacher_model, data_yaml, epochs=100, imgsz=640, alpha=0.5, temperature=2.0):
    # Prepare optimizer
    optimizer = optim.Adam(student_model.model.parameters(), lr=1e-3)
    
    # List to store losses
    losses = []

    # Begin training
    results = student_model.train(data=data_yaml, epochs=epochs, imgsz=imgsz, device=student_model.device)

    for epoch in range(epochs):
        epoch_loss = 0.0

        # Iterate through batches within each epoch
        for batch in results['dataloader']:
            images, targets = batch['img'].to(student_model.device), batch['label'].to(student_model.device)

            # Perform a training step with distillation
            loss = training_step(student_model, teacher_model, images, targets, optimizer, alpha, temperature)
            epoch_loss += loss

        # Store the loss for this epoch
        losses.append(epoch_loss)
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {epoch_loss}")

    # Save losses to a text file after all epochs
    with open("training_losses.txt", "w") as f:
        for epoch, loss in enumerate(losses, 1):
            f.write(f"Epoch {epoch}: Loss = {loss}\n")

    # Save the trained student model
    student_model.save("/home/murtaza/Desktop/Work/YOLOv8/ultralytics/s_best.pt")

# Start training the student model with knowledge distillation
train_student_with_distillation(
    student_model,
    teacher_model,
    data_yaml="/home/murtaza/Desktop/Work/YOLOv8/datasets/CMKD_rgb/rgb_dataset.yaml",
    epochs=100,
    imgsz=640,
    alpha=0.5,  # Balance between distillation and standard loss
    temperature=2.0  # Temperature for distillation
)

after training getting this error how to handle this? 

ERROR:
Traceback (most recent call last):
  File "new_std.py", line 93, in <module>
    train_student_with_distillation(
  File "new_std.py", line 73, in train_student_with_distillation
    for batch in results['dataloader']:
TypeError: 'DetMetrics' object is not subscriptable

**Comment by glenn-jocher** [comment]
It looks like the error is due to trying to subscript a `DetMetrics` object. Instead of accessing `results['dataloader']`, you should iterate over your dataset directly. Modify your training loop to use the dataloader from your dataset. If you need further assistance, please provide more details about your dataset loading process.

**Comment by MounikaThatikond** [comment]
did it solve the issue ? if yes , could you please upload the code for reference , i am also trying to do similar work with yolov9

**Comment by glenn-jocher** [comment]
If the issue was resolved, please share your solution here for others to benefit. For YOLOv9, you can refer to the Ultralytics documentation for guidance.

**Comment by Murtazaabidi1** [comment]
@MounikaThatikond  I am still working on it. Once it done I will share the perference code.

**Comment by MounikaThatikond** [comment]
also , i tried to perform quantization for yolov8n (INT8) for which i tried converting pytorch to tflite and was successful . but i want to know if i could perform INT8 quantization in pytorch itself without changing it to tflitr ? if not can i convert the quantized tflite to pytorch back , without changing the INT8 quantization ? I will attach my code from ultralytics import YOLO

# Load your pruned model
model = YOLO("/content/datasets/runs/detect/yolov8n_v8_50e_hybridpruned.pt")

# Export to TFLite with INT8 quantization using RHNP dataset for calibration
results = model.export(
    format="tflite",
    int8=True,
    data="/content/datasets/data_v8.yaml"  # Provide the path to your RHNP dataset YAML
)
 This worked ... but 
import os
import torch
from ultralytics import YOLO

# Disable W&B logging to prevent unintended behavior
os.environ["WANDB_MODE"] = "disabled"

# Load the original pruned YOLOv8n model
model = YOLO('/content/datasets/runs/detect/yolov8n_v8_50e_hybridpruned.pt')

# Ensure all layers switch to evaluation mode
for module in model.modules():
    module.eval()  # Set each layer to eval mode

# Check for any layers still in training mode
for name, module in model.named_modules():
    if module.training:
        print(f"Warning: {name} is still in training mode!")

# Apply dynamic quantization to reduce model size
quantized_model = torch.quantization.quantize_dynamic(
    model, {torch.nn.Linear}, dtype=torch.qint8
)

# Save the quantized model
torch.save(quantized_model, '/content/yolov8n_quantized.pt')
print("Quantized model saved as yolov8n_quantized.pt")
 doesnt work why ?

**Comment by glenn-jocher** [comment]
INT8 quantization in PyTorch is typically done using static quantization rather than dynamic. Dynamic quantization is more suited for models with linear layers. For full INT8 quantization, you might need to use PyTorch's static quantization workflow, which involves calibration with a representative dataset. Unfortunately, converting a quantized TFLite model back to PyTorch while retaining INT8 quantization isn't supported. If you have further questions, feel free to ask!

**Comment by MounikaThatikond** [comment]
i tried doing this and this is how i changed the yaml and have added shuuflenet.py and ghostnet.py in "/content/datasets/ultralytics/ultralytics/nn/modules" afyter cloning that ... but i am still getting error
Image
Image
Image
Image
Image

**Comment by glenn-jocher** [comment]
It seems like there might be an issue with the integration of your custom modules. Please ensure that the paths and imports in your code are correctly set up to recognize `shufflenet.py` and `ghostnet.py`. If the error persists, double-check the modifications in your YAML file for any inconsistencies.
