### ISSUE TITLE
train crop_fraction  ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#15721]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`results = model.train(data=  "/media/mm/1", imgsz=512 , epochs=100, batch = 50 ,  flipud = 0.5, fliplr = 0.5 ,hsv_h = 0.0 ,hsv_s=0.0 ,hsv_v=0.2,erasing= 0.0 , crop_fraction=0.0 ,auto_augment=None )  `

`crop_fraction=0.0`

```python

Traceback (most recent call last):
  File "/home/mm/1.py", line 25, in <module>
    results = model.train(data=  "/media/mm/1", imgsz=512 , epochs=100, batch = 50 ,  flipud = 0.5, fliplr = 0.5 ,hsv_h = 0.0 ,hsv_s=0.0 ,hsv_v=0.2,erasing= 0.0 , crop_fraction=0.0 ,auto_augment=None )  
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/model.py", line 650, in train
    self.trainer.train()
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 204, in train
    self._do_train(world_size)
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 323, in _do_train
    self._setup_train(world_size)
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 290, in _setup_train
    self.test_loader = self.get_dataloader(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/models/yolo/classify/train.py", line 80, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/models/yolo/classify/train.py", line 75, in build_dataset
    return ClassificationDataset(root=img_path, args=self.args, augment=mode == "train", prefix=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/data/dataset.py", line 449, in __init__
    else classify_transforms(size=args.imgsz, crop_fraction=args.crop_fraction)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mm/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/data/augment.py", line 1216, in classify_transforms
    scale_size = math.floor(size / crop_fraction)
                            ~~~~~^~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```

**Comment by venkatram-dev** [comment]
As I understand , crop_fraction  must be greater than 0.


Reference doc  https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml#L120

`crop_fraction: 1.0 # (float) image crop fraction for classification (0.1-1), 1.0 means no crop, must be greater than 0.`

**Comment by monkeycc** [comment]
1.0 means no crop

i see
I thought 0.0 meant no cropping

**Comment by glenn-jocher** [comment]
You're right, a `crop_fraction` of 1.0 means no cropping. Please set `crop_fraction` to a value greater than 0 to avoid the ZeroDivisionError.
