### ISSUE TITLE
YOLOv8 against adversarial attacks

### ISSUE THREAD

**Issue by wntic** [ultralytics/ultralytics#15745]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!

I am interested in the question of the robustness of image segmentation models to adversarial attacks such as FGSM, PGD etc. To perform adversarial attacks I use [torchattacks ](https://github.com/Harry24k/adversarial-attacks-pytorch) library. Is it possible to apply any adversarial attack to YOLOv8?

To perform the attack, it was necessary for the model to return only the tensor containing the segmentation mask. To do this, I used the following code:

```python
from ultralytics import YOLO
import torch


class YOLOv8:
    def __init__(self):
        self.model = YOLO("yolov8l-seg.pt")
        
    def forward(self, x):
        result = self.model.predict(source=x, save=True, conf=0.5)
        masks = result[0].masks.data
        final_mask = torch.zeros_like(masks[0], dtype=torch.int)
        for i, mask in enumerate(masks):
            final_mask[mask.bool()] = i + 1
        return final_mask

```

Now if I try to apply the attack to YOLOv8 using the code below, the model starts loading the dataset and goes into training mode. The torchattacks documentation states that when applying the attack, the model is automatically put into evaluation mode, i.e. `model.eval()`. In YOLO, does the `eval()` method put it into training mode?

I also tried to apply FGSM attack without torchattacks. For this I used the following attack code:

```python
from models import YOLOv8
from utils.image_preprocessing import preprocess_image
import torch


def fgsm_attack(model, eps, image: torch.Tensor, labels: torch.Tensor, targeted=False) -> torch.Tensor:
        loss = torch.nn.CrossEntropyLoss()
        device = next(model.parameters()).device

        image.to(device)
        image.requires_grad = True
        labels.to(device)

        outputs = model(image)

        model.zero_grad()
        cost = loss(outputs, labels)
        cost.backward()

        if targeted:
            adv_image = image - eps * image.grad.sign()
        else:
            adv_image = image + eps * image.grad.sign()

        adv_image = torch.clamp(adv_image, 0, 1)
        return adv_image


if __name__ == "__main__":
    model = YOLOv8()

    image_path = "input/bus.jpg"
    image_tensor = preprocess_image(image_path)

    image_tensor.requires_grad = True
    mask = model(image_tensor)
    pred_labels = torch.argmax(mask, dim=1)

    eps = 0.125
    adv_image = fgsm_attack(model, eps, image_tensor, pred_labels)
    adv_output = model(adv_image)

```

At the output I got the following error:

```
Traceback (most recent call last):
  File "/home/wntic/adversarial-segmentation-toolkit/y.py", line 41, in <module>
    adv_image = fgsm_attack(model, eps, image_tensor, pred_labels)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wntic/adversarial-segmentation-toolkit/y.py", line 18, in fgsm_attack
    cost = loss(outputs, labels)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wntic/adversarial-segmentation-toolkit/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wntic/adversarial-segmentation-toolkit/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wntic/adversarial-segmentation-toolkit/.venv/lib/python3.12/site-packages/torch/nn/modules/loss.py", line 1188, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wntic/adversarial-segmentation-toolkit/.venv/lib/python3.12/site-packages/torch/nn/functional.py", line 3104, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "host_softmax" not implemented for 'Int'
```

So, is it possible to somehow create a adversarial example (image) and test the model's robustness on it? Or is it impossible due to the YOLO's architecture?

I would also like to note that the above implementations of attacks were tested and work well on the DeepLabV3 and FCN architectures.

I will be glad to any feedback.

**Comment by Y-T-G** [comment]
It's a `YOLO` model object and not a `torch` model object, so your code wouldn't work since your code is meant for `torch` model object.

**Comment by wntic** [comment]
@Y-T-G, thanks for your response!
