### ISSUE TITLE
Why is YOLOv10n's mAP lower than YOLOv8n?

### ISSUE THREAD

**Issue by dsnsabari** [ultralytics/ultralytics#15744]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained both YOLOv8n and YOLOv10n models for person and face detection. Attached are the plots showing the metrics/mAP50-95 (YOLOv10n) and metrics/mAP50 (YOLOv8n).
The YOLOv8n metrics/mAP50-95 value reaches 0.7 during training, while the YOLOv10n metrics/mAP50-95 value only reaches a maximum of 0.66.

Could you please help me understand why YOLOv10n's mAP is lower compared to YOLOv8n?

### Additional

![image](https://github.com/user-attachments/assets/7cfb978d-0218-4b0a-b01a-7c66655c9de6)
![image](https://github.com/user-attachments/assets/4c6e26aa-f770-44ac-85a5-fdbda08d30a8)

![image](https://github.com/user-attachments/assets/a3c1a108-45de-4cd1-add2-9b98c7bf9079)
![image](https://github.com/user-attachments/assets/74a2a462-63fb-482e-ab25-3984dcef3eff)

**Comment by glenn-jocher** [comment]
@dsnsabari thank you for your question. The difference in mAP between YOLOv8n and YOLOv10n could be due to various factors such as model architecture changes, training settings, or dataset variations. YOLOv10 introduces new features like NMS-free training, which might affect performance differently. Ensure you are using the latest version of the Ultralytics package and consider experimenting with hyperparameters to optimize YOLOv10n's performance. For more details, please refer to the [YOLOv10 documentation](https://docs.ultralytics.com/models/yolov10/).

**Comment by dsnsabari** [comment]
@glenn-jocher , Thank you. When I trained the YOLOv10n model with an input shape of 640x640x3 and then exported the model to 320x320x3, the mAP dropped significantly. To address this, I retrained the model using the 320x320x3 input shape directly. Has anyone else encountered a similar issue?

**Comment by glenn-jocher** [comment]
@dsnsabari it's common to see a drop in mAP when changing the input shape. Training directly with the desired input shape, as you did with 320x320x3, is the correct approach to maintain performance. If the issue persists, ensure you're using the latest Ultralytics package version.

**Comment by dsnsabari** [comment]
@glenn-jocher , thank you, when i am trying to export the model into onnx . I am getting the below error. I am using the latest ultralytics.

```
  File "C:\Users\sabar\anaconda3\lib\site-packages\ultralytics\engine\exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "C:\Users\sabar\anaconda3\lib\site-packages\ultralytics\engine\exporter.py", line 393, in export_onnx
    import onnx  # noqa
  File "C:\Users\sabar\anaconda3\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

```

**Comment by glenn-jocher** [comment]
It looks like you're encountering a DLL load failure when importing ONNX. This issue is often related to environment conflicts. Please ensure your environment is clean and try reinstalling ONNX and its dependencies. If the problem persists, consider using a virtual environment or Docker container to isolate dependencies.

**Comment by dsnsabari** [comment]
@glenn-jocher, Thank you so much. I created the new conda env, and I can convert the yolovn10 to one, but I am getting the error while e exporting the model into the openvino.

````
requirements: AutoUpdate success ✅ 4.9s, installed 1 package: ['openvino>=2024.0.0']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

OpenVINO: export failure ❌ 4.9s: DLL load failed while importing _pyopenvino: The specified module could not be found.
Traceback (most recent call last):
  File "D:\objectdetection\yolo_format\yolo_model_conversion.py", line 21, in <module>
    model.export(format="openvino",imgsz=320)# dynamic=True, half=True)
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\ultralytics\engine\model.py", line 745, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\ultralytics\engine\exporter.py", line 308, in __call__
    f[3], _ = self.export_openvino()
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\ultralytics\engine\exporter.py", line 142, in outer_func
    raise e
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\ultralytics\engine\exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\ultralytics\engine\exporter.py", line 452, in export_openvino
    import openvino as ov
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\openvino\__init__.py", line 21, in <module>
    from openvino import runtime as runtime
  File "C:\Users\sabar\anaconda3\envs\new_object_env\lib\site-packages\openvino\runtime\__init__.py", line 8, in <module>
    from openvino._pyopenvino import get_version
ImportError: DLL load failed while importing _pyopenvino: The specified module could not be found.

````

**Comment by glenn-jocher** [comment]
It looks like you're encountering a DLL load failure with OpenVINO. Please ensure that OpenVINO is correctly installed and that your environment is properly configured. Restarting your runtime or rerunning the command may help. If the issue persists, consider checking the OpenVINO installation documentation for further troubleshooting steps.

**Comment by dsnsabari** [comment]
@glenn-jocher , Thank you. I resolved the issue. I noticed that in YOLOv10n, the val_dfl_loss is increasing as the number of epochs increases, whereas in YOLOv8n, the val_dfl_loss decreased with the increase in epochs.

![results](https://github.com/user-attachments/assets/95911653-749f-4a49-9725-568e74c0d3f3)

**Comment by glenn-jocher** [comment]
Glad to hear you resolved the issue. The increasing `val_dfl_loss` in YOLOv10n could indicate overfitting or a need for hyperparameter tuning. Consider adjusting learning rates or other training parameters to address this.

**Comment by dsnsabari** [comment]
@glenn-jocher , Thank you. I am training the YOLOv10 model to detect both persons and faces. In some cases, partial persons are being detected with high probability. I have cross-checked the annotations of the dataset, and I don't have any such examples in the data. I didn't face this issue with YOLOv8n. Do you have any suggestions for fixing this?

**Comment by glenn-jocher** [comment]
You're welcome. To address the issue of partial detections, consider augmenting your dataset with more diverse examples or adjusting the model's confidence threshold. Fine-tuning the model with additional data that includes partial views might also help improve accuracy.
