### ISSUE TITLE
YAML Parsing Error in YOLOv8 During Model Training

### ISSUE THREAD

**Issue by Duck017017** [ultralytics/ultralytics#15761]
### Question

Hello everyone,

I'm currently working on a project using YOLOv8 for segmentation, and I've encountered an issue when trying to train my model. Here's the command I used:
```yolo task=segment mode=train epochs=100 data="D:/YOLOv8_seg/dataset.yaml model=yolov8m-seg.pt imgsz=640 batch=8```

However, I keep running into the following error:
```
Traceback (most recent call last):
...
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 2, column 1:
    datasets_dir:'D:\YOLOv8practice\ ...
    ^
could not find expected ':'
  in "<unicode string>", line 3, column 1:
    weights_dir: weights
```

Initially, I thought the issue was related to the "YOLOv8practice" directory mentioned in the error, but I’ve already removed that directory and updated my "dataset.yaml" to point to the correct location "D:/YOLOv8_seg". Unfortunately, the error persists.

Here are the steps I’ve taken so far:

1.Checked the YAML syntax to ensure all keys are followed by a colon : and a space.
2.Verified that the paths in dataset.yaml are correct.
3.Cleared any potential cache related to Python and Conda.

Despite these trying, the error continues to appear. Could anyone provide insight into what might be causing this or suggest further troubleshooting steps?

Thanks in advance for your help!

**Comment by glenn-jocher** [comment]
@Duck017017 it looks like there might be a syntax error in your `dataset.yaml` file. Ensure that all keys and values are correctly formatted with a space after each colon. If the issue persists, please verify with the latest package version. For further details, you can refer to our [YOLO Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/).

**Comment by Duck017017** [comment]
> @Duck017017 it looks like there might be a syntax error in your `dataset.yaml` file. Ensure that all keys and values are correctly formatted with a space after each colon. If the issue persists, please verify with the latest package version. For further details, you can refer to our [YOLO Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/).

Hello, I have checked my `dataset.yaml` as below:
```
train: D:/YOLOv8_seg/train
test: D:/YOLOv8_seg/test

nc: 1

names: ['object']
```
Besides, I have installed the latest package and viewed the Common YOLO Issues page, the problem still exist.
I will keep trying, thanks.

**Comment by glenn-jocher** [comment]
@Duck017017 thank you for verifying the `dataset.yaml` file and updating to the latest package. Please ensure there are no hidden characters or formatting issues in the file. If the problem persists, consider sharing the complete error traceback for further assistance.

**Comment by Duck017017** [comment]
> @Duck017017 thank you for verifying the `dataset.yaml` file and updating to the latest package. Please ensure there are no hidden characters or formatting issues in the file. If the problem persists, consider sharing the complete error traceback for further assistance.

Sorry for replying late, below is my error massege :
```
(seg) D:\Segmentation\dataset>yolo segment train data=data.yaml model=yolov8.yaml epochs=100 imgsz=640
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\.conda\envs\seg\Scripts\yolo.exe\__main__.py", line 4, in <module>
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\data\base.py", line 17, in <module>
    from ultralytics.data.utils import FORMATS_HELP_MSG, HELP_URL, IMG_FORMATS
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\data\utils.py", line 19, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\nn\__init__.py", line 3, in <module>
    from .tasks import (
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\nn\tasks.py", line 10, in <module>
    from ultralytics.nn.modules import (
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\nn\modules\__init__.py", line 20, in <module>
    from .block import (
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\nn\modules\block.py", line 8, in <module>
    from ultralytics.utils.torch_utils import fuse_conv_and_bn
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\utils\__init__.py", line 1057, in <module>
    SETTINGS = SettingsManager()  # initialize settings
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\utils\__init__.py", line 991, in __init__
    self.load()
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\utils\__init__.py", line 1011, in load
    super().update(yaml_load(self.file))
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\ultralytics\utils\__init__.py", line 381, in yaml_load
    data = yaml.safe_load(s) or {}  # always return a dict (yaml.safe_load() may return None for empty files)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\admin\.conda\envs\seg\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 2, column 1:
    datasets_dir:'D:\YOLOv8practice\ ...
    ^
could not find expected ':'
  in "<unicode string>", line 3, column 1:
    weights_dir: weights
```

**Comment by glenn-jocher** [comment]
Thank you for sharing the error message. It seems there might be an issue with the `settings.yaml` file. Please ensure there are no hidden characters or formatting issues, especially around colons and spaces. If the problem persists, try deleting the `settings.yaml` file to allow it to regenerate.
