### ISSUE TITLE
The yolov8-p2.pt model cannot export the engine int8 model.

### ISSUE THREAD

**Issue by ZJDATY** [ultralytics/ultralytics#15908]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I tested YOLOV8N, YOLOV8N-P2, and YOLOV8X, YOLOV8X-P2. The results showed that the -P2 model could not export the engine INT8 quantization model.

> log

```
(pytorch-gpu) zhang@zhang-ubuntu:~/pythonworkspace/YOLOv8$ python export.py
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.2.83 🚀 Python-3.8.16 torch-2.0.0 CUDA:0 (NVIDIA TITAN V, 12050MiB)
WARNING ⚠️ imgsz=[360, 640] must be multiple of max stride 32, updating to [384, 640]
YOLOv8n-p2 summary (fused): 207 layers, 2,921,304 parameters, 0 gradients, 12.2 GFLOPs

PyTorch: starting from 'runs/detect/train14/weights/best.pt' with input shape (1, 3, 384, 640) BCHW and output shape(s) (1, 6, 20400) (5.9 MB)

ONNX: starting export with onnx 1.16.1 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: slimming with onnxslim 0.1.31...
ONNX: export success ✅ 20.8s, saved as 'runs/detect/train14/weights/best.onnx' (11.3 MB)

TensorRT: starting export with TensorRT 8.6.0...
[08/30/2024-10:36:30] [TRT] [I] [MemUsageChange] Init CUDA: CPU +1, GPU +0, now: CPU 2454, GPU 2257 (MiB)
[08/30/2024-10:36:35] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +429, GPU +72, now: CPU 2960, GPU 2329 (MiB)
[08/30/2024-10:36:35] [TRT] [I] ----------------------------------------------------------------
[08/30/2024-10:36:35] [TRT] [I] Input filename:   runs/detect/train14/weights/best.onnx
[08/30/2024-10:36:35] [TRT] [I] ONNX IR version:  0.0.10
[08/30/2024-10:36:35] [TRT] [I] Opset version:    17
[08/30/2024-10:36:35] [TRT] [I] Producer name:    pytorch
[08/30/2024-10:36:35] [TRT] [I] Producer version: 2.0.0
[08/30/2024-10:36:35] [TRT] [I] Domain:           
[08/30/2024-10:36:35] [TRT] [I] Model version:    0
[08/30/2024-10:36:35] [TRT] [I] Doc string:       
[08/30/2024-10:36:35] [TRT] [I] ----------------------------------------------------------------
[08/30/2024-10:36:35] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 6, -1) DataType.FLOAT
TensorRT: WARNING ⚠️ 'dynamic=True' model requires max batch size, i.e. 'batch=16'
TensorRT: building INT8 engine as runs/detect/train14/weights/best.engine
TensorRT: collecting INT8 calibration images from 'data=./car.yaml'
Scanning /home/zhang/pythonworkspace/YOLOv8/datasets/cardata/new/val/labels.cache... 432 images, 14 backgrounds, 0 corrupt: 100%|████
[08/30/2024-10:36:36] [TRT] [I] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[08/30/2024-10:36:36] [TRT] [I] Graph optimization time: 0.00647938 seconds.
[08/30/2024-10:36:36] [TRT] [W] BuilderFlag::kENABLE_TACTIC_HEURISTIC has been ignored in this builder run. This feature is only supported on Ampere and beyond.
[08/30/2024-10:36:36] [TRT] [I] Timing cache disabled. Turning it on will improve builder speed.
[08/30/2024-10:36:43] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[08/30/2024-10:36:43] [TRT] [I] Detected 1 inputs and 3 output network tensors.
[08/30/2024-10:36:44] [TRT] [I] Total Host Persistent Memory: 379120
[08/30/2024-10:36:44] [TRT] [I] Total Device Persistent Memory: 2930176
[08/30/2024-10:36:44] [TRT] [I] Total Scratch Memory: 0
[08/30/2024-10:36:44] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 1 MiB, GPU 30 MiB
[08/30/2024-10:36:44] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 428 steps to complete.
[08/30/2024-10:36:44] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 174.385ms to assign 36 blocks to 428 nodes requiring 22778368 bytes.
[08/30/2024-10:36:44] [TRT] [I] Total Activation Memory: 22778368
[08/30/2024-10:36:44] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +25, now: CPU 0, GPU 39 (MiB)
[08/30/2024-10:36:44] [TRT] [I] Starting Calibration.
[08/30/2024-10:36:45] [TRT] [I]   Calibrated batch 0 in 0.83843 seconds.
[08/30/2024-10:36:46] [TRT] [I]   Calibrated batch 1 in 0.874531 seconds.
.....
[08/30/2024-10:39:28] [TRT] [I]   Calibrated batch 215 in 0.722346 seconds.
[08/30/2024-10:40:10] [TRT] [I]   Post Processing Calibration data in 41.4021 seconds.
[08/30/2024-10:40:10] [TRT] [I] Calibration completed in 214.256 seconds.
[08/30/2024-10:40:10] [TRT] [I] Writing Calibration Cache for calibrator: TRT-8600-EntropyCalibration2
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 260) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 261) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 271) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 272) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 285) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 288) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 302) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 388) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 389) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 399) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 400) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 412) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 415) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 429) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 515) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 516) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 526) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 527) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 539) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 542) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 556) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 632) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 633) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 643) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 644) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 657) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 660) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 678) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor /model.28/dfl/Softmax_output_0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 792) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[08/30/2024-10:40:10] [TRT] [I] Graph optimization time: 0.0421503 seconds.
[08/30/2024-10:40:10] [TRT] [I] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[08/30/2024-10:40:10] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[08/30/2024-10:45:05] [TRT] [E] 2: Assertion getter(i) != 0 failed. 
[08/30/2024-10:45:05] [TRT] [E] 2: [weightConvertors.cpp::quantizeBiasCommon::310] Error Code 2: Internal Error (Assertion getter(i) != 0 failed. )
TensorRT: export failure ❌ 535.9s: __enter__
Traceback (most recent call last):
  File "export.py", line 9, in <module>
    model.export(data='./car.yaml',format='engine',simplify=True,int8=True,imgsz=[360,640]) #dynamic=False, ,batch=1
  File "/home/zhang/anaconda3/envs/pytorch-gpu/lib/python3.8/site-packages/ultralytics/engine/model.py", line 745, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/zhang/anaconda3/envs/pytorch-gpu/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhang/anaconda3/envs/pytorch-gpu/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 304, in __call__
    f[1], _ = self.export_engine()
  File "/home/zhang/anaconda3/envs/pytorch-gpu/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/zhang/anaconda3/envs/pytorch-gpu/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/zhang/anaconda3/envs/pytorch-gpu/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 801, in export_engine
    with build(network, config) as engine, open(f, "wb") as t:
AttributeError: __enter__

```

### Environment

(pytorch-gpu) zhang@zhang-ubuntu:~/pythonworkspace/YOLOv8$ yolo checks
Ultralytics YOLOv8.2.83 🚀 Python-3.8.16 torch-2.0.0 CUDA:0 (NVIDIA TITAN V, 12050MiB)
Setup complete ✅ (8 CPUs, 31.3 GB RAM, 35.4/93.3 GB disk)

OS                  Linux-6.8.0-40-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.16
Install             pip
RAM                 31.27 GB
CPU                 Intel Core(TM) i7-9700 3.00GHz
CUDA                11.7

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.4.3>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.0>=1.8.0
torchvision         ✅ 0.15.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO('yolov8n-p2.yaml').load('yolov8n.pt')
if __name__ == '__main__':
    results = model.train(data='./car.yaml', epochs=50, optimizer ='NAdam',lr0=0.0001,batch=8,cos_lr=True,cache =True,device =0 ,workers =8,imgsz=640)
```

```

from ultralytics import YOLO
model = YOLO('runs/detect/train13/weights/best.pt')
model.export(data='./car.yaml',format='engine',simplify=True,int8=True,imgsz=[360,640])
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ZJDATY thank you for reporting this issue. It appears that the YOLOv8-P2 model is encountering problems during the INT8 quantization export to TensorRT. Please ensure you are using the latest version of the Ultralytics package. If the issue persists, consider opening a detailed issue on the GitHub repository with your environment details and logs for further investigation. For more information on TensorRT export, you can refer to our [documentation](https://docs.ultralytics.com/integrations/tensorrt/).

**Comment by ZJDATY** [comment]
> @ZJDATY thank you for reporting this issue. It appears that the YOLOv8-P2 model is encountering problems during the INT8 quantization export to TensorRT. Please ensure you are using the latest version of the Ultralytics package. If the issue persists, consider opening a detailed issue on the GitHub repository with your environment details and logs for further investigation. For more information on TensorRT export, you can refer to our [documentation](https://docs.ultralytics.com/integrations/tensorrt/).

Thank you for your reply. I have attached my environment configuration in the question, and I am using the latest Ultralytics YOLOv8.2.83 without any modifications.
I carefully reviewed the document and did not find any configuration issues. I am using my own dataset, which includes two categories. There are no problems with training or reasoning, and the above errors only occur when using the YOLOV8-P2 model and exporting the INT8 engine model. Have you tested quantifying the P2 model as an int8 model? What more information do you need me to provide? Please let me know.

**Comment by ZJDATY** [comment]
@glenn-jocher   
```
(pytorch-gpu) zhang@zhang-ubuntu:~/pythonworkspace/YOLOv8$ pip list
Package                       Version
----------------------------- --------------------
about-time                    4.2.1
absl-py                       1.4.0
addict                        2.4.0
alive-progress                3.1.5
altair                        5.3.0
altgraph                      0.17.4
asttokens                     2.2.1
attrs                         23.2.0
autograd                      1.6.2
backcall                      0.2.0
backports.functools-lru-cache 1.6.5
backports.tarfile             1.2.0
blinker                       1.8.2
brotlipy                      0.7.0
build                         1.2.1
cachetools                    5.3.0
certifi                       2024.2.2
cffi                          1.15.1
charset-normalizer            2.0.4
click                         8.1.3
cma                           3.2.2
coloredlogs                   15.0.1
comm                          0.1.4
cryptography                  39.0.1
cycler                        0.11.0
Cython                        0.29.34
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.14
dill                          0.3.8
docutils                      0.20.1
e                             1.4.5
entrypoints                   0.4
executing                     1.2.0
fast_ctc_decode               0.3.5
filelock                      3.9.0
filterpy                      1.4.5
flatbuffers                   23.3.3
fsspec                        2023.4.0
future                        1.0.0
gitdb                         4.0.11
GitPython                     3.1.43
gmpy2                         2.1.2
google-auth                   2.17.3
google-auth-oauthlib          1.0.0
grapheme                      0.6.0
graphsurgeon                  0.4.6
grpcio                        1.54.0
h5py                          2.10.0
huggingface-hub               0.14.1
humanfriendly                 10.0
idna                          3.4
imagecodecs                   2023.3.16
imageio                       2.28.1
imgviz                        1.5.0
importlib-metadata            6.6.0
importlib-resources           5.12.0
ipykernel                     6.25.1
ipython                       8.12.0
jaraco.classes                3.4.0
jaraco.context                5.3.0
jaraco.functools              4.0.1
jedi                          0.19.0
jeepney                       0.8.0
Jinja2                        3.1.2
joblib                        1.2.0
jsonschema                    4.22.0
jsonschema-specifications     2023.12.1
jstyleson                     0.0.2
jupyter-client                7.3.4
jupyter_core                  4.12.0
keyring                       25.2.1
kiwisolver                    1.4.4
lapx                          0.5.5
lmdb                          1.4.1
Markdown                      3.4.3
markdown-it-py                2.2.0
MarkupSafe                    2.1.1
matplotlib                    3.4.3
matplotlib-inline             0.1.6
mdurl                         0.1.2
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
more-itertools                10.3.0
mpmath                        1.2.1
natsort                       8.1.0
nest-asyncio                  1.5.6
networkx                      2.8.4
nh3                           0.2.17
nibabel                       5.1.0
ninja                         1.11.1.1
nltk                          3.8.1
nncf                          2.11.0
numpy                         1.23.5
oauthlib                      3.2.2
onnx                          1.16.1
onnx-graphsurgeon             0.3.12
onnxruntime-gpu               1.18.1
onnxsim                       0.4.33
onnxslim                      0.1.31
opencv-python                 4.10.0.84
openvino                      2024.2.0
openvino-dev                  2024.2.0
openvino-telemetry            2024.1.0
packaging                     23.1
pandas                        2.0.3
parasail                      1.3.4
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           23.0.1
pkginfo                       1.10.0
pkgutil_resolve_name          1.3.10
progress                      1.6
prompt-toolkit                3.0.39
protobuf                      3.20.3
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       16.1.0
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pyclipper                     1.3.0.post4
pycocotools                   2.0.7
pycparser                     2.21
pydeck                        0.9.1
pydicom                       2.3.1
pydot                         2.0.0
Pygments                      2.16.1
pyinstaller                   6.8.0
pyinstaller-hooks-contrib     2024.7
pymoo                         0.6.1.1
pyOpenSSL                     23.0.0
pyparsing                     3.0.9
pyproject_hooks               1.1.0
PyQt5                         5.12
PyQt5_sip                     4.19.19
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2023.3
PyWavelets                    1.4.1
PyYAML                        6.0
pyzmq                         25.1.0
qimage2ndarray                1.10.0
rawpy                         0.18.1
readme_renderer               43.0
referencing                   0.35.1
regex                         2023.5.4
requests                      2.28.1
requests-oauthlib             1.3.1
requests-toolbelt             1.0.0
rfc3986                       2.0.0
rich                          13.7.1
rpds-py                       0.18.1
rsa                           4.9
sacremoses                    0.0.53
scikit-image                  0.19.3
scikit-learn                  0.24.2
scipy                         1.10.1
seaborn                       0.12.2
SecretStorage                 3.3.3
sentencepiece                 0.1.99
setuptools                    66.0.0
shapely                       2.0.1
six                           1.16.0
smmap                         5.0.1
stack-data                    0.6.2
style                         1.1.0
sympy                         1.11.1
tabulate                      0.9.0
tenacity                      8.5.0
tensorboard                   2.12.2
tensorboard-data-server       0.7.0
tensorboard-plugin-wit        1.8.1
tensorrt                      8.6.0
termcolor                     1.1.0
texttable                     1.6.7
thop                          0.1.1.post2209072238
threadpoolctl                 3.1.0
tifffile                      2023.4.12
tokenizers                    0.10.3
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.1
torch                         2.0.0
torchaudio                    2.0.0
torchsummary                  1.5.1
torchvision                   0.15.0
tornado                       6.1
tqdm                          4.66.1
traitlets                     5.9.0
transformers                  4.16.2
triton                        2.0.0
twine                         5.1.1
typing_extensions             4.5.0
tzdata                        2024.1
ultralytics                   8.2.83
ultralytics-thop              2.0.0
urllib3                       1.26.15
watchdog                      4.0.1
wcwidth                       0.2.6
Werkzeug                      2.2.3
wheel                         0.38.4
wrapt                         1.16.0
zipp                          3.15.0

```

**Comment by ambitious-octopus** [comment]
Hey @ZJDATY, I cannot reproduce your error! please check your dataset or model.

```python
from ultralytics import YOLO
model = YOLO('yolov8n-p2.yaml').load('yolov8n.pt')
model.export(format="engine", data='coco8.yaml', int8=True, simplify=True,imgsz=[360,640])
```

**Comment by ZJDATY** [comment]
> Hey @ZJDATY, I cannot reproduce your error! please check your dataset or model.
> 
> ```python
> from ultralytics import YOLO
> model = YOLO('yolov8n-p2.yaml').load('yolov8n.pt')
> model.export(format="engine", data='coco8.yaml', int8=True, simplify=True,imgsz=[360,640])
> ```

@ambitious-octopus Thank you for your reply. I guess it's because you haven't really trained. You can start training first and then load the trained P2 model for testing everywhere.

**Comment by ZJDATY** [comment]
I have verified my hypothesis and exported the YOLOV8n-p2 inference model using the official YOLOV8n.pt without any problem. However, if I train YOLOV8n-p2.pt first and then export it, errors will occur.

**Comment by ZJDATY** [comment]
> Thank you for the additional information. It appears the issue arises after training the YOLOv8n-p2 model. Please ensure you are using the latest version of the Ultralytics package. If the problem persists, consider sharing your training configuration and dataset details for further investigation.

Yes, thank you for your reply. I am using the latest version, and the minimum test cases have been provided, including the description of the dataset, which has been clearly stated in the above question.

**Comment by glenn-jocher** [comment]
Thank you for confirming. Given that you're using the latest version and have provided the necessary details, we recommend opening an issue on our GitHub repository with your training configuration and dataset specifics for further investigation.

**Comment by ZJDATY** [comment]
@ambitious-octopus  Can you reproduce my results? Also, my tensorrt version is 10.3.0, is it related to this?

**Comment by ZJDATY** [comment]
@ambitious-octopus Can we remove non-reproducible labels? In order to attract attention and solve problems. We should not ignore this requirement.
