### ISSUE TITLE
Significant drop in accuracy after conversion from ONNX to TFLite

### ISSUE THREAD

**Issue by isuchy** [ultralytics/ultralytics#15965]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to ask what I am doing wrong, that my model accuracy dropped drastically after YOLOv10 -> ONNX ->TFLite conversion.

I trained YOLO on custom dataset and I used this Google Colab notebook as a baseline [https://colab.research.google.com/github/roboflow/notebooks/blob/main/notebooks/train-yolov10-object-detection-on-custom-dataset.ipynb](https://colab.research.google.com/github/roboflow/notebooks/blob/main/notebooks/train-yolov10-object-detection-on-custom-dataset.ipynb)

After training, I converted the YOLO model into an ONNX graph
```
import torch
from ultralytics import YOLOv10

model = YOLOv10("/content/best.pt")
model.model.eval()
model.export(format="onnx", dynamic=True, nms=True)
```

In the end I made a conversion to TFLite. To convert to TFLite I used `onnx2tf` tool with default settings. (NT8 quantization was not applied)
`!onnx2tf -i yolov10_best.onnx`

and model validation in order to calculate metrics 
```
yolo_model = YOLOv10('/content/saved_model/best_float32.tflite')
metrics = yolo_model.val(data='/content/yolo/data.yaml')
print(metrics.box.map)  # Print mAP50-95
print(metrics.box.map50)  # Print mAP50
print(metrics.box.map75)  # Print mAP75
```

Here's a table of how the mAP quality metrics have decreased in value.
|             | YOLOv10 |    ONNX | TFLite |
|----------|---------|---------|--------|
| mAP50_95 |    0.61 |   0.571 |  0.023 |
| mAP50    |    0.87 |   0.891 |  0.055 |
| mAP75    |    0.71 |   0.630 |  0.015 |

What else can I do so that the precision of the model does not drop so dramatically after conversion to TFLite float32/float16?

**Comment by isuchy** [comment]
If I used the Ultralytics export function to "directly" convert to TFLite in this way

```
from ultralytics import YOLOv10

model = YOLOv10('/content/best.pt')
model.model.eval()
model.export(format='tflite', dynamic=True)
```

The conversion to ONNX as an intermediate step is done successfully and then it crashes with this error message

```
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Conv.py", line 246, in make_node
    input_tensor = get_padding_as_op(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 2009, in get_padding_as_op
    return tf.pad(x, padding)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend/common/keras_tensor.py", line 91, in __tf_tensor__
    raise ValueError(
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:


x = Input(...)
...
tf_fn(x)  # Invalid.


What you should do instead is wrap `tf_fn` in a layer:


class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)



ERROR: input_onnx_file_path: /content/best.onnx
ERROR: onnx_op_name: /model.0/conv/Conv
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Conv.py", line 246, in make_node
    input_tensor = get_padding_as_op(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 2009, in get_padding_as_op
    return tf.pad(x, padding)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend/common/keras_tensor.py", line 91, in __tf_tensor__
    raise ValueError(
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:


x = Input(...)
...
tf_fn(x)  # Invalid.


What you should do instead is wrap `tf_fn` in a layer:


class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-88364a75ca3b>", line 8, in <cell line: 8>
    model.export(format='tflite', dynamic=True)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 590, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 297, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 133, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 803, in export_saved_model
    onnx2tf.convert(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/onnx2tf.py", line 998, in convert
    op.make_node(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 354, in print_wrapper_func
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py](https://localhost:8080/#) in print_wrapper_func(*args, **kwargs)
    287         try:
--> 288             result = func(*args, **kwargs)
    289 

20 frames
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:


x = Input(...)
...
tf_fn(x)  # Invalid.


What you should do instead is wrap `tf_fn` in a layer:


class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)



During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py](https://localhost:8080/#) in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()

**Comment by Y-T-G** [comment]
Can you provide the output of running `yolo checks` in terminal?

From your code, it seems like you're using the code from YOLO v10 repo, and not official ultralytics.

Install official ultralytics by running `pip install -U ultralytics`. Note that you will have to retrain your YOLOv10 model if you switch from the unofficial YOLOv10 ultralytics to official ultralytics.

**Comment by isuchy** [comment]
Hi @Y-T-G,

thanks for your response. Please find the output of `yolo check`

Ultralytics YOLOv8.1.34 🚀 Python-3.10.12 torch-2.4.0+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 32.8/225.8 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.20GHz
CUDA                None

matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.0+cu121>=1.8.0
torchvision         ✅ 0.19.0+cu121>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0 

As far as I know, there is no official Ultralytics distribution of YOLOv10, so I installed from this source `!pip install -q git+https://github.com/THU-MIG/yolov10.git`

So I'll try to update the Ultralytics package as you suggested and retrain the model.
