### ISSUE TITLE
Error when trying to export yolo_worldv2 to tflite

### ISSUE THREAD

**Issue by revu94** [ultralytics/ultralytics#15967]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have been facing the below error when trying to export yolov8m-worldv2.pt to .tflite file. It gets converted to .onnx file but facing error when getting converted to .tflite. Can anyone help with the error

Ultralytics YOLOv8.2.86 🚀 Python-3.10.12 torch-2.4.0+cu121 CPU (Intel Xeon 2.20GHz)
WARNING ⚠️ YOLOWorld (original version) export is not supported to any format.
WARNING ⚠️ YOLOWorldv2 models (i.e. 'yolov8s-worldv2.pt') only support export to (torchscript, onnx, openvino, engine, coreml) formats. See https://docs.ultralytics.com/models/yolo-world for details.
YOLOv8s-worldv2 summary: 422 layers, 164,026,601 parameters, 0 gradients, 32.3 GFLOPs

PyTorch: starting from 'yolov8s-worldv2.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 6, 8400) (24.7 MB)

TensorFlow SavedModel: starting export with tensorflow 2.17.0...

ONNX: starting export with onnx 1.16.2 opset 19...
ONNX: slimming with onnxslim 0.1.32...
ONNX: export success ✅ 3.5s, saved as 'yolov8s-worldv2.onnx' (47.8 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...
2024-09-02 16:15:11,486 - root - ERROR - Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Concat.py", line 261, in make_node
    tf.concat(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.concat_19" (type TFOpLambda).

Dimension 1 in both shapes must be equal, but are 128 and 40. Shapes are [40,128] and [40,40]. for '{{node tf.concat_19/concat}} = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, Placeholder_2, Placeholder_3, tf.concat_19/concat/axis)' with input shapes: [1,40,40,128], [1,40,40,128], [1,40,40,128], [1,128,40,40], [] and with computed input tensors: input[4] = <1>.

Call arguments received by layer "tf.concat_19" (type TFOpLambda):
  • values=['tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 128, 40, 40), dtype=float32)']
  • axis=1
  • name='/model.12/Concat'

ERROR: input_onnx_file_path: yolov8s-worldv2.onnx
ERROR: onnx_op_name: /model.12/Concat
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Concat.py", line 261, in make_node
    tf.concat(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.concat_19" (type TFOpLambda).

Dimension 1 in both shapes must be equal, but are 128 and 40. Shapes are [40,128] and [40,40]. for '{{node tf.concat_19/concat}} = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, Placeholder_2, Placeholder_3, tf.concat_19/concat/axis)' with input shapes: [1,40,40,128], [1,40,40,128], [1,40,40,128], [1,128,40,40], [] and with computed input tensors: input[4] = <1>.

Call arguments received by layer "tf.concat_19" (type TFOpLambda):
  • values=['tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 128, 40, 40), dtype=float32)']
  • axis=1
  • name='/model.12/Concat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-02915937caa1>", line 1, in <cell line: 1>
    model.export(format="tflite")
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 747, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 314, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 873, in export_saved_model
    onnx2tf.convert(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/onnx2tf.py", line 1049, in convert
    op.make_node(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 378, in print_wrapper_func
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py](https://localhost:8080/#) in print_wrapper_func(*args, **kwargs)
    311         try:
--> 312             result = func(*args, **kwargs)
    313 

21 frames
ValueError: Exception encountered when calling layer "tf.concat_19" (type TFOpLambda).

Dimension 1 in both shapes must be equal, but are 128 and 40. Shapes are [40,128] and [40,40]. for '{{node tf.concat_19/concat}} = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, Placeholder_1, Placeholder_2, Placeholder_3, tf.concat_19/concat/axis)' with input shapes: [1,40,40,128], [1,40,40,128], [1,40,40,128], [1,128,40,40], [] and with computed input tensors: input[4] = <1>.

Call arguments received by layer "tf.concat_19" (type TFOpLambda):
  • values=['tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 40, 40, 128), dtype=float32)', 'tf.Tensor(shape=(1, 128, 40, 40), dtype=float32)']
  • axis=1
  • name='/model.12/Concat'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py](https://localhost:8080/#) in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()

**Comment by Y-T-G** [comment]
You can try with these versions:

https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by revu94** [comment]
Hey @Y-T-G , 
Thank you.
I tried with python 3.11 version and it seems to work.

**Comment by revu94** [comment]
Hi

**Comment by revu94** [comment]
Hi,
     It seems like the issue is not fixed. I tried to export the yolov8m-worldv2 model to .tflite and  it shows a warning  as below
     
   WARNING  YOLOWorld (original version) export is not supported to any format.
    WARNING  YOLOWorldv2 models (i.e. '[yolov8s-worldv2.pt](http://yolov8s-worldv2.pt/)') only support export to (torchscript, onnx, openvino, engine, coreml) formats. See https://docs.ultralytics.com/models/yolo-world for details.

It doesn't mention supporting(in the warning) .tflite file even thought the file got created for both yolov8s-worldv2 and yolov8m-worldv2 models. With yolov8l-worldv2 model I am getting error though. I wanted to export this model to be used in android. If there is any other way please let me know that too.

**Comment by glenn-jocher** [comment]
The YOLOv8-worldv2 models currently support export to torchscript, onnx, openvino, engine, and coreml formats only. For Android deployment, consider using one of these supported formats. If you need further assistance, please check the documentation or update to the latest version to see if there are any changes.
