### ISSUE TITLE
TypeError: 'weights_only'

### ISSUE THREAD

**Issue by hakanbarin** [ultralytics/ultralytics#16000]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Integrations

### Bug

Hello,

I am using the Jetson Xavier NX A203 carrier board, which requires me to use JetPack 5.0.2. Because of this, I installed PyTorch 1.13.0 and torchvision v0.13.0 (I have CUDA 11.4) from the PyTorch for Jetson page after installing the ultralytics library. However, when I try to run the YOLO model, I encounter the following error and have been unable to find a solution. This is a very important project for me, and I am at the final stage of running it on the Xavier. I would be very grateful if you could support me. Thank you!

device = 'cuda'

model = YOLO("calisan_v4.pt").to(device)

### Environment

>>> ultralytics.checks()
Ultralytics YOLOv8.2.87 🚀 Python-3.8.10 torch-1.13.0a0+d0d6b1f2.nv22.10 CUDA:0 (Xavier, 14899MiB)
Setup complete ✅ (6 CPUs, 14.5 GB RAM, 30.8/234.3 GB disk)

### Minimal Reproducible Example

'''
Traceback (most recent call last):
  File "yolodeneme.py", line 9, in <module>
    model = YOLO("calisan_v4.pt")
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 145, in __init__
    self._load(model, task=task)
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 297, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 857, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 784, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/home/aura/.local/lib/python3.8/site-packages/torch/serialization.py", line 734, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/aura/.local/lib/python3.8/site-packages/torch/serialization.py", line 1069, in _load
    unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
TypeError: 'weights_only' is an invalid keyword argument for Unpickler()
'''

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hakanbarin** [comment]
Thanks for support. You save my day. It's solution.

**Comment by glenn-jocher** [comment]
@hakanbarin you're welcome! If you have any more questions, feel free to ask.
