### ISSUE TITLE
“TypeError: Argument 'thickness' is required to be an integer ” when running predict task using yolov8-obb.pt

### ISSUE THREAD

**Issue by nyj-ocean** [ultralytics/ultralytics#16012]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

I can run `train` and `val` task using `yolov8m-obb.yaml` on my own dataset.
However, when I try to run `predict` task with the generated best.pt , errors have occurred.
`predict.py` is like: 

> from ultralytics import YOLO
> 
> model = YOLO("F:/UserData2/ultralytics-main/runs/obb/yolov8m-obb/weights/best.pt")
> 
> source = "F:/UserData2/images/test/"
> 
> model.predict(source, save=True)

`errors` are following:
```
Traceback (most recent call last):
  File "predict.py", line 4, in <module>
    model.predict(source, save=True)
  File "F:\UserData2\ultralytics-main\ultralytics\engine\model.py", line 567, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "F:\UserData2\ultralytics-main\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "F:\ProgramData\Anaconda3\envs\yolov8\lib\site-packages\torch\autograd\grad_mode.py", line 65, in generator_context
    response = gen.send(request)
  File "F:\UserData2\ultralytics-main\ultralytics\engine\predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "F:\UserData2\ultralytics-main\ultralytics\engine\predictor.py", line 338, in write_results
    self.plotted_img = result.plot(
  File "F:\UserData2\ultralytics-main\ultralytics\engine\results.py", line 535, in plot
    annotator.box_label(
  File "F:\UserData2\ultralytics-main\ultralytics\utils\plotting.py", line 320, in box_label
    cv2.rectangle(self.im, p1, p2, color, -1, cv2.LINE_AA)  
TypeError: Argument 'thickness' is required to be an integer
```
When I commented out the line of code that caused the problem, the predict.py script can be run and the prediction results can be generated, but there is no rectangular box for the category on the predicted image

1. commented out the `line 320` in `ultralytics\utils\plotting.py`

> #cv2.rectangle(self.im, p1, p2, color, -1, cv2.LINE_AA) 

2. the generated prediction image
![00683](https://github.com/user-attachments/assets/55841c01-5705-48c1-8daf-3d7f113d77bc)

I also try to run `predict.py` using the [yolov8n.pt](https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt)  without commenting out the `line 320` in `ultralytics\utils\plotting.py`
it can run with no error and generate prediction image successfuly.
![bus](https://github.com/user-attachments/assets/e2e59486-7e3d-4a25-a275-3639f59fe921)

### Environment

Ultralytics YOLOv8.2.86 🚀 Python-3.8.8 torch-1.8.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24575MiB)
Setup complete ✅ (24 CPUs, 63.9 GB RAM, 4762.6/4956.4 GB disk)

OS                  Windows-10-
Environment         Windows
Python              3.8.8
Install             pip
RAM                 63.94 GB
CPU                 unknown
CUDA                11.1

### Minimal Reproducible Example

[ultralytics-8.2.86.zip](https://github.com/user-attachments/files/16871962/ultralytics-8.2.86.zip)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Can you post the output of running `yolo checks` in terminal?

**Comment by Y-T-G** [comment]
You still need to do `pip install -e .` inside the cloned folder.
