### ISSUE TITLE
yolov8  ImportError: cannot import name 'YOLO'

### ISSUE THREAD

**Issue by mcyhaha** [ultralytics/ultralytics#16011]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

C:\Users\mcy\anaconda3\envs\face_env\python.exe D:/dlcode/STF-YOLO-main/ultralytics/models/yolo/pose/train.py
Traceback (most recent call last):
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\pose\train.py", line 5, in <module>
    from ultralytics.models import yolo
  File "D:\dlcode\STF-YOLO-main\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\rtdetr\model.py", line 9, in <module>
    from .train import RTDETRTrainer
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\rtdetr\train.py", line 7, in <module>
    from ultralytics.models.yolo.detect import DetectionTrainer
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\__init__.py", line 3, in <module>
    from ultralytics.models.yolo import classify, detect, pose, segment
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\pose\__init__.py", line 4, in <module>
    from .train import PoseTrainer
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\pose\train.py", line 74, in <module>
    from ultralytics import YOLO
ImportError: cannot import name 'YOLO' from partially initialized module 'ultralytics' (most likely due to a circular import) (D:\dlcode\STF-YOLO-main\ultralytics\__init__.py)

进程已结束,退出代码1

### Additional

How is this supposed to work? It's been bothering me for so long

**Comment by wandson88** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Y-T-G** [comment]
It seems like you modified the code and broke it. This is not there in the official ultralytics:
> File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\pose\train.py", line 74, in
from ultralytics import YOLO

There's no `from ultralytics import YOLO` at that line.

**Comment by mcyhaha** [comment]
I added this myself. Will deleting this sentence fix it?

**Comment by mcyhaha** [comment]
C:\Users\mcy\anaconda3\envs\face_env\python.exe D:/dlcode/STF-YOLO-main/ultralytics/models/yolo/pose/train.py
Traceback (most recent call last):
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\pose\train.py", line 5, in <module>
    from ultralytics import YOLO
  File "D:\dlcode\STF-YOLO-main\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\rtdetr\model.py", line 9, in <module>
    from .train import RTDETRTrainer
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\rtdetr\train.py", line 7, in <module>
    from ultralytics.models.yolo.detect import DetectionTrainer
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\__init__.py", line 3, in <module>
    from ultralytics.models.yolo import classify, detect, pose, segment
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\pose\__init__.py", line 4, in <module>
    from .train import PoseTrainer
  File "D:\dlcode\STF-YOLO-main\ultralytics\models\yolo\pose\train.py", line 5, in <module>
    from ultralytics import YOLO
ImportError: cannot import name 'YOLO' from partially initialized module 'ultralytics' (most likely due to a circular import) (D:\dlcode\STF-YOLO-main\ultralytics\__init__.py)

进程已结束,退出代码1
I deleted 74 lines of code, and there are errors in other lines
How can this be solved?

**Comment by Y-T-G** [comment]
Why did you add that code there? It's broken. You still have the code in line 5.

**Comment by mcyhaha** [comment]
from ultralytics import YOLO  This line of code, if not added, YOLO reports an error

**Comment by glenn-jocher** [comment]
It seems like there's a circular import issue. Ensure you're using the latest version of the package and check your import structure to avoid conflicts.

**Comment by mcyhaha** [comment]
Traceback (most recent call last):
  File "D:\dlcode\ultralytics-main\ultralytics-main\ultralytics\models\yolo\pose\train.py", line 85, in <module>
    model = YOLO('D:\\dlcode\\ultralytics-main\\ultralytics-main\\ultralytics\\cfg\\models\\v8\\yolov8n-ghost-pose.yaml').load('D:\\dlcode\\ultralytics-main\\yolov8n-pose.pt')  # 从YAML构建并传输权重
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\ultralytics\engine\model.py", line 143, in __init__
    self._new(model, task=task, verbose=verbose)
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\ultralytics\engine\model.py", line 263, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\ultralytics\nn\tasks.py", line 423, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\ultralytics\nn\tasks.py", line 313, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\ultralytics\nn\tasks.py", line 906, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
                                                    ~~~~~~~~~^^^
KeyError: 'pose'

Hello, I am now using the new version, after adding ghost module running this error, how to solve it?

**Comment by glenn-jocher** [comment]
It seems like there's a KeyError related to the 'pose' module. Please ensure your custom module is correctly defined and integrated into the codebase. Also, verify that you're using the latest version of the Ultralytics package. If the issue persists, consider checking the module's implementation for any discrepancies.

**Comment by wuxie12345** [comment]
How did you end up solving this? I'm also encountering the same error

**Comment by glenn-jocher** [comment]
@wuxie12345 the KeyError 'pose' typically occurs when custom modules aren't properly registered. For pose estimation models, ensure you: 

1. Use the official YOLO11-pose architecture from our latest release
2. Properly define keypoint parameters in your YAML configuration
3. Avoid mixing incompatible modules (Ghost convs require careful integration)

We recommend starting from an unmodified pose config like yolov8n-pose.yaml and gradually adding your modifications while verifying at each step. For direct support implementing custom architectures, explore our Enterprise License which includes technical support.
