### ISSUE TITLE
Exporting YOLOv10n to CoreML not functional

### ISSUE THREAD

**Issue by nicspect** [ultralytics/ultralytics#16045]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Exporting yolov10n to CoreML is giving `RuntimeError: split_with_sizes expects split_sizes to sum exactly to 300 (input tensor's size at dimension 1), but got split_sizes=[4, 80]`

Here is the detailed terminal output:

`Ultralytics YOLOv8.2.87 🚀 Python-3.10.13 torch-2.4.0 CPU (Apple M2 Max)
Setup complete ✅ (12 CPUs, 96.0 GB RAM, 550.1/1858.2 GB disk)
Ultralytics YOLOv8.2.87 🚀 Python-3.10.13 torch-2.4.0 CPU (Apple M2 Max)
YOLOv10n summary (fused): 285 layers, 2,762,608 parameters, 0 gradients, 8.6 GFLOPs

PyTorch: starting from 'yolov10n.yaml' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (0.0 MB)
scikit-learn version 1.4.1.post1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
Torch version 2.4.0 has not been tested with coremltools. You may run into unexpected errors. Torch 2.2.0 is the most recent version that has been tested.

CoreML: starting export with coremltools 7.2...
CoreML: export failure ❌ 1.4s: split_with_sizes expects split_sizes to sum exactly to 300 (input tensor's size at dimension 1), but got split_sizes=[4, 80]
Traceback (most recent call last):
  File "/Users/nic-spect/code/algodev/common/Sagemaker_YOLO/local/train_local.py", line 24, in <module>
    model.export(format="coreml", nms=True)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/model.py", line 747, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 311, in __call__
    f[4], _ = self.export_coreml()
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 628, in export_coreml
    ts = torch.jit.trace(model.eval(), self.im, strict=False)  # TorchScript model
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/jit/_trace.py", line 1000, in trace
    traced_func = _trace_impl(
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/jit/_trace.py", line 695, in _trace_impl
    return trace_module(
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/jit/_trace.py", line 1275, in trace_module
    module._c._create_method_from_trace(
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 1194, in forward
    xywh, cls = self.model(x)[0].transpose(0, 1).split((4, self.nc), 1)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_tensor.py", line 917, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 300 (input tensor's size at dimension 1), but got split_sizes=[4, 80]`

[environment.txt](https://github.com/user-attachments/files/16898343/environment.txt)

### Environment

Ultralytics YOLOv8.2.87 🚀 Python-3.10.13 torch-2.4.0 CPU (Apple M2 Max)
Setup complete ✅ (12 CPUs, 96.0 GB RAM, 550.1/1858.2 GB disk)
Ultralytics YOLOv8.2.87 🚀 Python-3.10.13 torch-2.4.0 CPU (Apple M2 Max)
YOLOv10n summary (fused): 285 layers, 2,762,608 parameters, 0 gradients, 8.6 GFLOPs

### Minimal Reproducible Example

`import ultralytics 
ultralytics.checks()
model = ultralytics.YOLO("yolov10n.yaml")
model.export(format="coreml", nms=True)
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nicspect thank you for reporting this issue. Please ensure you're using the latest version of the Ultralytics package. If the problem persists, it might be related to compatibility with Torch 2.4.0. Consider downgrading to Torch 2.2.0, which is tested with coremltools. Let us know if this resolves the issue.

**Comment by nicspect** [comment]
@glenn-jocher, I tried downgrading to Torch 2.2.0. This also meant that I downgraded torchvision from 0.19.0 to 0.17.0. However, I got the same error.

`Ultralytics YOLOv8.2.88 🚀 Python-3.10.13 torch-2.2.0 CPU (Apple M2 Max)
Setup complete ✅ (12 CPUs, 96.0 GB RAM, 550.3/1858.2 GB disk)
Ultralytics YOLOv8.2.88 🚀 Python-3.10.13 torch-2.2.0 CPU (Apple M2 Max)
YOLOv10n summary (fused): 285 layers, 2,762,608 parameters, 0 gradients, 8.6 GFLOPs

PyTorch: starting from 'yolov10n.yaml' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (0.0 MB)
scikit-learn version 1.4.1.post1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.

CoreML: starting export with coremltools 7.2...
CoreML: export failure ❌ 3.4s: split_with_sizes expects split_sizes to sum exactly to 300 (input tensor's size at dimension 1), but got split_sizes=[4, 80]
Traceback (most recent call last):
  File "/Users/nic-spect/code/algodev/common/Sagemaker_YOLO/local/train_local.py", line 24, in <module>
    model.export(format="coreml", nms=True)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/model.py", line 747, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 311, in __call__
    f[4], _ = self.export_coreml()
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 628, in export_coreml
    ts = torch.jit.trace(model.eval(), self.im, strict=False)  # TorchScript model
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/jit/_trace.py", line 806, in trace
    return trace_module(
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/jit/_trace.py", line 1074, in trace_module
    module._c._create_method_from_trace(
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 1194, in forward
    xywh, cls = self.model(x)[0].transpose(0, 1).split((4, self.nc), 1)
  File "/Users/nic-spect/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_tensor.py", line 896, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 300 (input tensor's size at dimension 1), but got split_sizes=[4, 80]`

**Comment by glenn-jocher** [comment]
@nicspect it seems the issue persists despite downgrading. This might be related to the model configuration or export process. Please ensure your model configuration aligns with the expected input and output dimensions. If the problem continues, consider checking for any updates or fixes in the Ultralytics repository.

**Comment by ambitious-octopus** [comment]
Hey @nicspect, for now you can try exporting without nms with this code:
```
from ultralytics import YOLO
model = YOLO("yolov10n.pt")
model.export(
    format="coreml", nms=False
)
```
This obviously requires using post-processing. In case you are interested, our [Open Source YOLO iOS app](https://github.com/ultralytics/yolo-ios-app) implements NMS in swift.

**Comment by nicspect** [comment]
Hey @ambitious-octopus, thank you for this! I want to point out for people who will find themselves looking for an answer on this thread, this fix also works for custom models.

However, I'm using the model in a custom app, so is there a timeline of when the nms feature will work?
