### ISSUE TITLE
Cannot export to Tensorflow JS

### ISSUE THREAD

**Issue by shahrin014** [ultralytics/ultralytics#16052]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Integrations

### Bug

```sh
Ultralytics YOLOv8.2.88 🚀 Python-3.11.1 torch-2.1.2+cu121 CPU (12th Gen Intel Core(TM) i7-1250U)
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)    

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.16.2 opset 17...
ONNX: slimming with onnxslim 0.1.32...
ONNX: export success ✅ 5.8s, saved as 'yolov8n.onnx' (12.2 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/mnt/c/Users/shahr/Documents/Development/yolo/yolo/venv/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/shahr/Documents/Development/yolo/yolo/venv/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/shahr/Documents/Development/yolo/yolo/venv/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/mnt/c/Users/shahr/Documents/Development/yolo/yolo/venv/lib/python3.11/site-packages/onnx2tf/ops/Sigmoid.py", line 81, in make_node
    tf.nn.sigmoid(
  File "/mnt/c/Users/shahr/Documents/Development/yolo/yolo/venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/lina/.asdf/installs/python/3.11.1/lib/python3.11/contextlib.py", line 138, in __enter__
    except StopIteration:
ValueError: '/model.0/act/Sigmoid' is not a valid root scope name. A root scope name has to match the following pattern: ^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$

ERROR: input_onnx_file_path: yolov8n.onnx
ERROR: onnx_op_name: /model.0/act/Sigmoid
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

### Environment

```sh
Ultralytics YOLOv8.2.88 🚀 Python-3.11.1 torch-2.1.2+cu121 CPU (12th Gen Intel Core(TM) i7-1250U)
Setup complete ✅ (12 CPUs, 7.6 GB RAM, 208.9/1006.9 GB disk)
```

### Minimal Reproducible Example

```python
# Must do before importing ultralytics
import os
os.environ["YOLO_CONFIG_DIR"] = os.path.abspath('./yolocfg')

# To fix 
# TypeError: You are passing KerasTensor(type_spec=TensorSpec(shape=(1, 20, 20, 256),
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

import logging
logging.basicConfig(level=logging.DEBUG)

# pylint: disable=import-error
# pylint: disable=wrong-import-position
from ultralytics import YOLO, checks

# model = YOLO("runs/detect/yolov8n_custom/weights/best.pt")
model = YOLO("yolov8n.pt")

print("\n\nChecks...\n")
checks()

print("\nExporting...\n")
model.export(
    format="tfjs" #, imgsz=640, half=False, int8=False
)
```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Try this: 

https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by ambitious-octopus** [comment]
Non-reproducible on my side:

```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.export(format="tfjs")
```

This is my `yolo checks`:
```
Ultralytics YOLOv8.2.88 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5741MiB)
Setup complete ✅ (6 CPUs, 31.3 GB RAM, 458.1/574.7 GB disk)

OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.0
Install             git
RAM                 31.29 GB
CPU                 Intel Core(TM) i5-8600K 3.60GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

**Comment by shahrin014** [comment]
I tried https://github.com/ultralytics/ultralytics/issues/16052#issuecomment-2333143754
with the same results.
```sh
...
ValueError: '/model.0/act/Sigmoid' is not a valid root scope name. A root scope name has to match the following pattern: ^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$

ERROR: input_onnx_file_path: yolov8n.onnx
ERROR: onnx_op_name: /model.0/act/Sigmoid
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
(venv) user@user:/mnt/c/Users/user/Documents/Development/yolo/yolo$ pip freeze
absl-py==2.1.0
astunparse==1.6.3
cachetools==5.5.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
coloredlogs==15.0.1
contourpy==1.2.1
cycler==0.12.1
filelock==3.15.4
flatbuffers==24.3.25
fonttools==4.53.1
fsspec==2024.6.1
gast==0.4.0
google-auth==2.34.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.65.5
h5py==3.11.0
humanfriendly==10.0
idna==3.7
Jinja2==3.1.4
keras==3.5.0
kiwisolver==1.4.5
libclang==18.1.1
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mdurl==0.1.2
ml-dtypes==0.3.2
mpmath==1.3.0
namex==0.0.8
networkx==3.3
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
onnx==1.16.2
onnx-graphsurgeon==0.5.2
onnx2tf==1.22.3
onnxruntime==1.19.0
onnxslim==0.1.32
opencv-python==4.7.0.72
opt-einsum==3.3.0
optree==0.12.1
packaging==20.9
pandas==2.2.2
pillow==10.4.0
protobuf==3.20.3
psutil==6.0.0
py-cpuinfo==9.0.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pybind11==2.13.4
pycparser==2.22
Pygments==2.18.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.2
requests==2.32.3
requests-oauthlib==2.0.0
rich==13.7.1
rsa==4.9
scipy==1.13.1
seaborn==0.13.2
six==1.16.0
sng4onnx==1.0.4
sounddevice==0.5.0
sympy==1.13.2
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.1
tensorflow-cpu==2.16.2
tensorflow-estimator==2.13.0
tensorflow-hub==0.12.0
tensorflow-io-gcs-filesystem==0.37.1
tensorflowjs==3.18.0
termcolor==2.4.0
tf_keras==2.16.0
tflite-support==0.4.4
torch==2.1.2
torchvision==0.16.2
tqdm==4.66.5
triton==2.1.0
typing_extensions==4.5.0
tzdata==2024.1
ultralytics==8.2.88
ultralytics-thop==2.0.5
urllib3==2.2.2
Werkzeug==3.0.3
wrapt==1.16.0
```

I am running on HP Envy Windows, but also using WSL Ubuntu.

**Comment by Y-T-G** [comment]
Remove the `disable_eagee_execution()` line

**Comment by shahrin014** [comment]
Now I faced this error.
```
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more d
```

My workaround for this was to downgrade numpy to 1.23.4, but this version of numpy is not compatible with the tensorflow version suggested by https://github.com/ultralytics/ultralytics/issues/16052#issuecomment-2333143754

**Comment by Y-T-G** [comment]
You can try 1.2.35

**Comment by shahrin014** [comment]
Now I face 
```
AttributeError: module 'tensorflow.compat.v1' has no attribute 'estimator'
```
Tried with `tensorflow-estimator` `2.13.0` and `2.15.0`

**Comment by Y-T-G** [comment]
Install tensirflow-hub 0.16.1

**Comment by yll1** [comment]
> Non-reproducible on my side:
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> model.export(format="tfjs")
> ```
> 
> This is my `yolo checks`:
> 
> ```
> Ultralytics YOLOv8.2.88 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5741MiB)
> Setup complete ✅ (6 CPUs, 31.3 GB RAM, 458.1/574.7 GB disk)
> 
> OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
> Environment         Linux
> Python              3.10.0
> Install             git
> RAM                 31.29 GB
> CPU                 Intel Core(TM) i5-8600K 3.60GHz
> CUDA                12.1
> 
> numpy               ✅ 1.26.4<2.0.0,>=1.23.0
> matplotlib          ✅ 3.9.0>=3.3.0
> opencv-python       ✅ 4.10.0.84>=4.6.0
> pillow              ✅ 10.3.0>=7.1.2
> pyyaml              ✅ 6.0.1>=5.3.1
> requests            ✅ 2.32.2>=2.23.0
> scipy               ✅ 1.13.0>=1.4.1
> torch               ✅ 2.3.0>=1.8.0
> torchvision         ✅ 0.18.0>=0.9.0
> tqdm                ✅ 4.66.4>=4.64.0
> psutil              ✅ 5.9.8
> py-cpuinfo          ✅ 9.0.0
> pandas              ✅ 2.2.2>=1.1.4
> seaborn             ✅ 0.13.2>=0.11.0
> ultralytics-thop    ✅ 2.0.0>=2.0.0
> ```
@ambitious-octopus 
hi ，There is no version number for tensorflow, onnx2tf, or ultralytics, would you like to post them ,or  post your pip list ?thank you very much ! I  will appreciate it !
