### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

### ISSUE THREAD

**Issue by hakanbarin** [ultralytics/ultralytics#16050]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export, Multi-GPU, Integrations

### Bug

To convert my model to TensorRT, I am using the following code:

model = YOLO("yolov8n.pt")

model.export(format="engine")  # creates 'yolov8n.engine'

trt_model = YOLO("yolov8n.engine")

However, I encounter the following error:

ONNX: export failure ❌ 9.7s: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
TensorRT: export failure ❌ 9.7s: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
Traceback (most recent call last):
  File "yolodeneme.py", line 16, in <module>
    model.export(format="engine").setType() 
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 747, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/aura/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 305, in __call__
    f[1], _ = self.export_engine()
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 678, in export_engine
    f_onnx, _ = self.export_onnx()  # run before TRT import https://github.com/ultralytics/ultralytics/issues/7016
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/aura/.local/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 412, in export_onnx
    torch.onnx.export(
  File "/home/aura/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 319, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/aura/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/aura/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
    params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

I have tried various models from the internet, but I have not succeeded. How can I resolve this issue? Thank you for your feedback.

### Environment

ultralytics.checks()
Ultralytics YOLOv8.2.87 🚀 Python-3.8.10 torch-1.13.0a0+d0d6b1f2.nv22.10 CUDA:0 (Xavier, 14899MiB)
Setup complete ✅ (6 CPUs, 14.5 GB RAM, 30.8/234.3 GB disk)

### Minimal Reproducible Example

model = YOLO("yolov8n.pt")

model.export(format="engine")  # creates 'yolov8n.engine'

trt_model = YOLO("yolov8n.engine")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
It seems like an issue with PyTorch 1.13 in Jetson.

https://github.com/pytorch/pytorch/issues/72175#issuecomment-1439570177

**Comment by Y-T-G** [comment]
Try passing `dynamic=True` in `model.export()`

**Comment by ambitious-octopus** [comment]
@hakanbarin also try to pass `device=0` during export.

**Comment by hakanbarin** [comment]
> Try passing `dynamic=True` in `model.export()`

It's working for my issue. Thanks for response. Have a good day.

**Comment by glenn-jocher** [comment]
Glad to hear it worked! If you have any more questions, feel free to ask. Have a great day!
