### ISSUE TITLE
About DDP training

### ISSUE THREAD

**Issue by super-song-sir** [ultralytics/ultralytics#16069]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Excuse me. When I training Yolov8 model on kaggle using Tesla T4*2,some errors occur. When I only training model with 'yolov8s.yaml',the training is going on as normal.But  when I use the yaml model file that I modified，errors happen as follow:
"CalledProcessError: Command '['/opt/conda/bin/python3.10', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '40605', "
So,I try this yaml file with one GPU，the training is runing normal.Why do I get an error with my modified network structure when training with multiple GPUs, but no issues with training with a single GPU?

**Comment by Y-T-G** [comment]
You need to provide the full error.

**Comment by super-song-sir** [comment]
> 您需要提供完整的错误。
full error as follow:
DDP: debug command /opt/conda/bin/python3.10 -m torch.distributed.run --nproc_per_node 2 --master_port 37311 /root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py
WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update. 
View settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics YOLOv8.2.89 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15095MiB)
                                                      CUDA:1 (Tesla T4, 15095MiB)
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py", line 12, in <module>
    results = trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 234, in _setup_train
    ckpt = self.setup_model()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 555, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/obb/train.py", line 33, in get_model
    model = OBBModel(cfg, ch=3, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 391, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 300, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 1009, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 525, in check_yaml
    return check_file(file, suffix, hard=hard)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 517, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'yolov8s-obb-SFS.yaml' does not exist
[2024-09-06 16:39:39,939] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 119 closing signal SIGTERM
[2024-09-06 16:39:40,003] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 120) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-06_16:39:39
  host      : 501f7738d553
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 120)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[6], line 13
     10 model.info()
     12 # Train the model on the COCO8 example dataset for 100 epochs
---> 13 results = model.train(data='data_yaml/ssdd-obb.yaml', batch=32,epochs=20,imgsz=640,workers=4,device="0,1")
     16 # Run inference with the RT-DETR-l model on the 'bus.jpg' image
     17 # results = model('path/to/bus.jpg')

File /kaggle/working/yolo-obb/ultralytics/engine/model.py:674, in Model.train(self, trainer, **kwargs)
    671             pass
    673 self.trainer.hub_session = self.session  # attach optional HUB session
--> 674 self.trainer.train()
    675 # Update model and cfg after training
    676 if RANK in {-1, 0}:

File /kaggle/working/yolo-obb/ultralytics/engine/trainer.py:194, in BaseTrainer.train(self)
    192     subprocess.run(cmd, check=True)
    193 except Exception as e:
--> 194     raise e
    195 finally:
    196     ddp_cleanup(self, str(file))

File /kaggle/working/yolo-obb/ultralytics/engine/trainer.py:192, in BaseTrainer.train(self)
    190 try:
    191     LOGGER.info(f'{colorstr("DDP:")} debug command {" ".join(cmd)}')
--> 192     subprocess.run(cmd, check=True)
    193 except Exception as e:
    194     raise e

File /opt/conda/lib/python3.10/subprocess.py:526, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524     retcode = process.poll()
    525     if check and retcode:
--> 526         raise CalledProcessError(retcode, process.args,
    527                                  output=stdout, stderr=stderr)
    528 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['/opt/conda/bin/python3.10', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '37311', '/root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py']' returned non-zero exit status 1.

**Comment by super-song-sir** [comment]
> You need to provide the full error.

full error as follow:
DDP: debug command /opt/conda/bin/python3.10 -m torch.distributed.run --nproc_per_node 2 --master_port 37311 /root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py
WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update. 
View settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics YOLOv8.2.89 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15095MiB)
                                                      CUDA:1 (Tesla T4, 15095MiB)
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py", line 12, in <module>
    results = trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 234, in _setup_train
    ckpt = self.setup_model()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 555, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/obb/train.py", line 33, in get_model
    model = OBBModel(cfg, ch=3, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 391, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 300, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 1009, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 525, in check_yaml
    return check_file(file, suffix, hard=hard)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 517, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'yolov8s-obb-SFS.yaml' does not exist
[2024-09-06 16:39:39,939] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 119 closing signal SIGTERM
[2024-09-06 16:39:40,003] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 120) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
/root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py FAILED

Failures:
  <NO_OTHER_FAILURES>

Root Cause (first observed failure):
[0]:
  time      : 2024-09-06_16:39:39
  host      : 501f7738d553
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 120)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

CalledProcessError                        Traceback (most recent call last)
Cell In[6], line 13
     10 model.info()
     12 # Train the model on the COCO8 example dataset for 100 epochs
---> 13 results = model.train(data='data_yaml/ssdd-obb.yaml', batch=32,epochs=20,imgsz=640,workers=4,device="0,1")
     16 # Run inference with the RT-DETR-l model on the 'bus.jpg' image
     17 # results = model('path/to/bus.jpg')

File /kaggle/working/yolo-obb/ultralytics/engine/model.py:674, in Model.train(self, trainer, **kwargs)
    671             pass
    673 self.trainer.hub_session = self.session  # attach optional HUB session
--> 674 self.trainer.train()
    675 # Update model and cfg after training
    676 if RANK in {-1, 0}:

File /kaggle/working/yolo-obb/ultralytics/engine/trainer.py:194, in BaseTrainer.train(self)
    192     subprocess.run(cmd, check=True)
    193 except Exception as e:
--> 194     raise e
    195 finally:
    196     ddp_cleanup(self, str(file))

File /kaggle/working/yolo-obb/ultralytics/engine/trainer.py:192, in BaseTrainer.train(self)
    190 try:
    191     LOGGER.info(f'{colorstr("DDP:")} debug command {" ".join(cmd)}')
--> 192     subprocess.run(cmd, check=True)
    193 except Exception as e:
    194     raise e

File /opt/conda/lib/python3.10/subprocess.py:526, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524     retcode = process.poll()
    525     if check and retcode:
--> 526         raise CalledProcessError(retcode, process.args,
    527                                  output=stdout, stderr=stderr)
    528 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['/opt/conda/bin/python3.10', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '37311', '/root/.config/Ultralytics/DDP/_temp_ev5c4s3n133179397350416.py']' returned non-zero exit status 1.

**Comment by Y-T-G** [comment]
What's the training command? Use full path to the file.

**Comment by super-song-sir** [comment]
> What's the training command? Use full path to the file.
`
Thank you for your reply!The training code is  :
from ultralytics import YOLO

model = YOLO('yolov8s-obb-SFS.yaml')
model.info()
results = model.train(data='data_yaml/ssdd-obb.yaml', batch=32,epochs=200,imgsz=640,workers=4,device="0,1")
`
when i delete "device='0,1'",the training code will run normally.But when i use two GPU,the error will happen.Specially,When I change 'yolov8s-obb-SFS.yaml'(I modified ) into 'yolov8s-obb.yaml'.Two GPU's training can run smoothly.
Could you please tell me If I change the network structure, how should I modify the code to accommodate DDP training?

**Comment by super-song-sir** [comment]
> What's the training command? Use full path to the file.

Thank you for your reply! The training code is:
`
from ultralytics import YOLO

model = YOLO('yolov8s-obb-SFS.yaml')
model.info()
results = model.train(data='data_yaml/ssdd-obb.yaml', batch=32,epochs=200,imgsz=640,workers=4,device="0,1")
`
This code will report an error as above.When I delete "device="0,1"",the training code can run normally. And when I change 'yolov8s-obb-SFS.yaml'(I modified) into 'yolov8s-obb.yaml',the training code runs smoothly with two GPU.Could you please tell me If I change the network structure, how should I modify the code to accommodate DDP training?

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to your modified YAML file. Ensure the file path is correct and the structure is compatible with DDP. Double-check any custom layers or parameters for compatibility with multi-GPU setups. If the problem persists, try updating to the latest version of the package.

**Comment by Y-T-G** [comment]
Use full path to the yaml file to load the model.

**Comment by super-song-sir** [comment]
> It seems like the issue might be related to your modified YAML file. Ensure the file path is correct and the structure is compatible with DDP. Double-check any custom layers or parameters for compatibility with multi-GPU setups. If the problem persists, try updating to the latest version of the package.

But when I training 'yolov8s-obb-SFS.yaml' with two GPU,it can recognize the network structure as follow:
engine\trainer: task=obb, mode=train, model=yolov8s-obb-SFS.yaml, data=D:/project/ultralytics-main/data_yaml/RSDD.yaml, epochs=300, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=4, project=None, name=train37, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=20, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\obb\train37
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     43680  ultralytics.nn.modules.block.C2f_SFS         [64, 64, True]                
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 22        [15, 18, 21]  1   2402614  ultralytics.nn.modules.head.OBB              [1, 1, [128, 256, 512]]       
YOLOv8s-obb-SFS summary: 276 layers, 11436790 parameters, 11436774 gradients, 30.2 GFLOPs
So, It  probably has nothing to do with the path，How do I check if custom layers or parameters for compatibility with multi-GPU setups?

**Comment by super-song-sir** [comment]
> Use full path to the yaml file to load the model.
But when I training 'yolov8s-obb-SFS.yaml' with two GPU,it can recognize the network structure as follow:

0 -1 1 928 ultralytics.nn.modules.conv.Conv [3, 32, 3, 2]
1 -1 1 18560 ultralytics.nn.modules.conv.Conv [32, 64, 3, 2]
2 -1 1 43680 ultralytics.nn.modules.block.C2f_SFS [64, 64, True]
3 -1 1 73984 ultralytics.nn.modules.conv.Conv [64, 128, 3, 2]
4 -1 2 197632 ultralytics.nn.modules.block.C2f [128, 128, 2, True]
5 -1 1 295424 ultralytics.nn.modules.conv.Conv [128, 256, 3, 2]
6 -1 2 788480 ultralytics.nn.modules.block.C2f [256, 256, 2, True]
7 -1 1 1180672 ultralytics.nn.modules.conv.Conv [256, 512, 3, 2]
8 -1 1 1838080 ultralytics.nn.modules.block.C2f [512, 512, 1, True]
9 -1 1 656896 ultralytics.nn.modules.block.SPPF [512, 512, 5]
10 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest']
11 [-1, 6] 1 0 ultralytics.nn.modules.conv.Concat [1]
12 -1 1 591360 ultralytics.nn.modules.block.C2f [768, 256, 1]
13 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest']
14 [-1, 4] 1 0 ultralytics.nn.modules.conv.Concat [1]
15 -1 1 148224 ultralytics.nn.modules.block.C2f [384, 128, 1]
16 -1 1 147712 ultralytics.nn.modules.conv.Conv [128, 128, 3, 2]
17 [-1, 12] 1 0 ultralytics.nn.modules.conv.Concat [1]
18 -1 1 493056 ultralytics.nn.modules.block.C2f [384, 256, 1]
19 -1 1 590336 ultralytics.nn.modules.conv.Conv [256, 256, 3, 2]
20 [-1, 9] 1 0 ultralytics.nn.modules.conv.Concat [1]
21 -1 1 1969152 ultralytics.nn.modules.block.C2f [768, 512, 1]
22 [15, 18, 21] 1 2402614 ultralytics.nn.modules.head.OBB [1, 1, [128, 256, 512]]
YOLOv8s-obb-SFS summary: 276 layers, 11436790 parameters, 11436774 gradients, 30.2 GFLOPs

So, It probably has nothing to do with the path，How do I check if custom layers or parameters for compatibility with multi-GPU setups?

**Comment by super-song-sir** [comment]
> 问题似乎与您修改的 YAML 文件有关。确保文件路径正确且结构与 DDP 兼容。仔细检查任何自定义图层或参数是否与多 GPU 设置兼容。如果问题仍然存在，请尝试更新到软件包的最新版本。

The error probably happen within   \ultralytics-main\ultralytics\engine\trainer.py .The error points to this code:
   
 def train(self):
        """Allow device='', device=None on Multi-GPU systems to default to device=0."""
        if isinstance(self.args.device, str) and len(self.args.device):  # i.e. device='0' or device='0,1,2,3'
            world_size = len(self.args.device.split(","))
        elif isinstance(self.args.device, (tuple, list)):  # i.e. device=[0, 1, 2, 3] (multi-GPU from CLI is list)
            world_size = len(self.args.device)
        elif torch.cuda.is_available():  # i.e. device=None or device='' or device=number
            world_size = 1  # default to device 0
        else:  # i.e. device='cpu' or 'mps'
            world_size = 0

        # Run subprocess if DDP training, else train normally
        if world_size > 1 and "LOCAL_RANK" not in os.environ:
            # Argument checks
            if self.args.rect:
                LOGGER.warning("WARNING ⚠️ 'rect=True' is incompatible with Multi-GPU training, setting 'rect=False'")
                self.args.rect = False
            if self.args.batch < 1.0:
                LOGGER.warning(
                    "WARNING ⚠️ 'batch<1' for AutoBatch is incompatible with Multi-GPU training, setting "
                    "default 'batch=16'"
                )
                self.args.batch = 16

            # Command
            cmd, file = generate_ddp_command(world_size, self)
            try:
                LOGGER.info(f'{colorstr("DDP:")} debug command {" ".join(cmd)}')
                subprocess.run(cmd, check=True)
            except Exception as e:
                raise e
            finally:
                ddp_cleanup(self, str(file))

        else:
            self._do_train(world_size)

what should i do to make the modifid yaml file adapt to Multi-GPU？The modifid yaml can run smoothly with single GPU

**Comment by Y-T-G** [comment]
Read the error:

> FileNotFoundError: 'yolov8s-obb-SFS.yaml' does not exist

which means you need to provide full path to your yaml file

**Comment by super-song-sir** [comment]
> Read the error:
> 
> > FileNotFoundError: 'yolov8s-obb-SFS.yaml' does not exist
> 
> which means you need to provide full path to your yaml file

Thank for your reply.But I have a question, why is it that a single GPU can train and multiple GPUs produce this error when I am not using the full path?

**Comment by Y-T-G** [comment]
Multi-GPU training uses DDP which launches a separate process so the file has to be loaded again.

https://github.com/ultralytics/ultralytics/blob/a2993108e98f74c4820a8d974a83704d5a861567/ultralytics/utils/dist.py#L25

**Comment by super-song-sir** [comment]
> 多 GPU 训练使用 DDP，DDP 会启动一个单独的进程，因此必须再次加载文件。
> 
> https://github.com/ultralytics/ultralytics/blob/a2993108e98f74c4820a8d974a83704d5a861567/ultralytics/utils/dist.py#L25

Thank you for your reply. I use the full path,but another error occurs:
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_i3do3pq8133898576813632.py", line 12, in <module>
    results = trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 234, in _setup_train
    ckpt = self.setup_model()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 555, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/obb/train.py", line 33, in get_model
    model = OBBModel(cfg, ch=3, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 391, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 313, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 903, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
KeyError: 'C2f_SFS'
[2024-09-07 15:18:13,880] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 141 closing signal SIGTERM
[2024-09-07 15:18:13,944] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 142) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

/root/.config/Ultralytics/DDP/_temp_i3do3pq8133898576813632.py FAILED

Failures:
  <NO_OTHER_FAILURES>

Root Cause (first observed failure):
[0]:
  time      : 2024-09-07_15:18:13
  host      : 8b225eef4c15
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 142)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

CalledProcessError                        Traceback (most recent call last)
Cell In[5], line 13
     10 model.info()
     12 # Train the model on the COCO8 example dataset for 100 epochs
---> 13 results = model.train(data='data_yaml/RSDD.yaml', batch=96,epochs=500,imgsz=640,workers=24,device="0,1")
     16 # Run inference with the RT-DETR-l model on the 'bus.jpg' image
     17 # results = model('path/to/bus.jpg')

File /kaggle/working/yolo-obb/ultralytics/engine/model.py:674, in Model.train(self, trainer, **kwargs)
    671             pass
    673 self.trainer.hub_session = self.session  # attach optional HUB session
--> 674 self.trainer.train()
    675 # Update model and cfg after training
    676 if RANK in {-1, 0}:

File /kaggle/working/yolo-obb/ultralytics/engine/trainer.py:194, in BaseTrainer.train(self)
    192     subprocess.run(cmd, check=True)
    193 except Exception as e:
--> 194     raise e
    195 finally:
    196     ddp_cleanup(self, str(file))

File /kaggle/working/yolo-obb/ultralytics/engine/trainer.py:192, in BaseTrainer.train(self)
    190 try:
    191     LOGGER.info(f'{colorstr("DDP:")} debug command {" ".join(cmd)}')
--> 192     subprocess.run(cmd, check=True)
    193 except Exception as e:
    194     raise e

File /opt/conda/lib/python3.10/subprocess.py:526, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524     retcode = process.poll()
    525     if check and retcode:
--> 526         raise CalledProcessError(retcode, process.args,
    527                                  output=stdout, stderr=stderr)
    528 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['/opt/conda/bin/python3.10', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '35837', '/root/.config/Ultralytics/DDP/_temp_i3do3pq8133898576813632.py']' returned non-zero exit status 1.

It shows :
[2024-09-07 15:18:13,880] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 141 closing signal SIGTERM
[2024-09-07 15:18:13,944] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 142) of binary: /opt/conda/bin/python3.10 instead of FileNotFoundError：“yolov8s-obb-SFS.yaml”.Could you please help me?

**Comment by Y-T-G** [comment]
You didn't install your modified version with `pip install -e .`

**Comment by super-song-sir** [comment]
> You didn't install your modified version with `pip install -e .`

Thank you.I'm very sorry to trouble you again. Could you please tell me how to install my modified version with `pip install -e`? I'm a novice has just started to get started with yolov8. And I don't quite understand why it's not needed to install modified version when training with a single GPU.But got a error with two GPU when I didn't install modified version.

**Comment by Y-T-G** [comment]
You just run `pip install -e .` inside the `ultralytics` folder that you're using for modifications
