### ISSUE TITLE
Exporting yolov10n.pt int8 does not appear to fully quantize, so when compiling for edgetpu, very few operations are mapped to TPU.

### ISSUE THREAD

**Issue by jaylenetriton** [ultralytics/ultralytics#16074]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Hello-
I've been trying to compile our object detection models for edgetpu with the new export support for yolov10. In troubleshooting, I've tried to simplify and use yolov10n.pt as the model. I suspect the model is not getting fully quantized upon export, and therefore very few operations are mapped to the TPU. Here is my process and results. Perhaps the export is supported (I did see another [github issue ](https://github.com/ultralytics/ultralytics/issues/15873)regarding it) but the quantizations are not happening. I am also attaching a text file of the tensor details for the full_integer_quant.tflite file that is the product of the export, and then the edgetpu.log file. 
Thank you for any help!

[yolov10n_full_integer_quant_edgetpu.log](https://github.com/user-attachments/files/16912727/yolov10n_full_integer_quant_edgetpu.log)
[tensor_details_output_yolo10.txt](https://github.com/user-attachments/files/16912739/tensor_details_output_yolo10.txt)

**export output:**
(yolov10) da@da167:/mnt/raid0/jaylene/yolov10_testing$ yolo export model=yolov10n.pt format=tflite int8
Ultralytics YOLOv8.2.87 🚀 Python-3.9.19 torch-2.4.1+cu121 CPU (Intel Core(TM) i9-9820X 3.30GHz)
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
YOLOv10n summary (fused): 285 layers, 2,762,608 parameters, 0 gradients, 8.6 GFLOPs

PyTorch: starting from 'yolov10n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (5.6 MB)

TensorFlow SavedModel: starting export with tensorflow 2.17.0...

ONNX: starting export with onnx 1.16.2 opset 19...
ONNX: slimming with onnxslim 0.1.32...
ONNX: export success ✅ 1.3s, saved as 'yolov10n.onnx' (9.1 MB)
TensorFlow SavedModel: collecting INT8 calibration images from 'data=coco8.yaml'

Dataset 'coco8.yaml' images not found ⚠️, missing path '/mnt/raid0/jaylene/yolov10_testing/datasets/coco8/images/val'
Downloading https://ultralytics.com/assets/coco8.zip to '/mnt/raid0/jaylene/yolov10_testing/datasets/coco8.zip'...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 433k/433k [00:00<00:00, 5.40MB/s]
Unzipping /mnt/raid0/jaylene/yolov10_testing/datasets/coco8.zip to /mnt/raid0/jaylene/yolov10_testing/datasets/coco8...: 100%|██████████| 25/25 [00:00<00:00, 2537.88file/s]
Dataset download success ✅ (0.8s), saved to /mnt/raid0/jaylene/yolov10_testing/datasets

Scanning /mnt/raid0/jaylene/yolov10_testing/datasets/coco8/labels/val... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<00:00, 265.31it/s]
New cache created: /mnt/raid0/jaylene/yolov10_testing/datasets/coco8/labels/val.cache
TensorFlow SavedModel: WARNING ⚠️ >300 images recommended for INT8 calibration, found 4 images.
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.20.0...

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
saved_model output started ==========================================================
saved_model output complete!
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1725651435.903531 2938881 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1725651436.696119 2938881 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1725651436.696156 2938881 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
Float32 tflite output complete!
I0000 00:00:1725651439.103743 2938881 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
W0000 00:00:1725651439.835335 2938881 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1725651439.835363 2938881 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
Float16 tflite output complete!
Input signature information for quantization
signature_name: serving_default
input_name.0: images shape: (1, 640, 640, 3) dtype: <dtype: 'float32'>
W0000 00:00:1725651444.495439 2938881 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1725651444.495462 2938881 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
Dynamic Range Quantization tflite output complete!
W0000 00:00:1725651447.682303 2938881 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1725651447.682327 2938881 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
INT8 Quantization tflite output complete!
W0000 00:00:1725651456.090253 2938881 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1725651456.090274 2938881 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
Full INT8 Quantization tflite output complete!
W0000 00:00:1725651464.208907 2938881 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1725651464.208930 2938881 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/onnx2tf/onnx2tf.py", line 1520, in convert
    tflite_model = converter.convert()
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1231, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1183, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1562, in convert
    return self._convert_from_saved_model(graph_def)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1424, in _convert_from_saved_model
    return self._optimize_tflite_model(
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1127, in _optimize_tflite_model
    model = self._quantize(
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 767, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 194, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

WARNING: INT8 Quantization with int16 activations tflite output failed.
W0000 00:00:1725651472.279723 2938881 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1725651472.279744 2938881 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/onnx2tf/onnx2tf.py", line 1551, in convert
    tflite_model = converter.convert()
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1231, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1183, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1562, in convert
    return self._convert_from_saved_model(graph_def)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1424, in _convert_from_saved_model
    return self._optimize_tflite_model(
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1127, in _optimize_tflite_model
    model = self._quantize(
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 767, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/da/anaconda3/envs/yolov10/lib/python3.9/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 194, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

WARNING: Full INT8 Quantization with int16 activations tflite output failed.
TensorFlow SavedModel: export success ✅ 175.7s, saved as 'yolov10n_saved_model' (84.6 MB)

TensorFlow Lite: starting export with tensorflow 2.17.0...
TensorFlow Lite: export success ✅ 0.0s, saved as 'yolov10n_saved_model/yolov10n_int8.tflite' (3.2 MB)

**compiler output:**
(yolov10) da@da167:/mnt/raid0/jaylene/yolov10_testing$ edgetpu_compiler /mnt/raid0/jaylene/yolov10_testing/yolov10n_saved_model/yolov10n_full_integer_quant.tflite --out_dir="/mnt/raid0/jaylene/yolov10_testing/yolov10n_saved_model"
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 249 ms.

Input model: /mnt/raid0/jaylene/yolov10_testing/yolov10n_saved_model/yolov10n_full_integer_quant.tflite
Input size: 27.96MiB
Output model: /mnt/raid0/jaylene/yolov10_testing/yolov10n_saved_model/yolov10n_full_integer_quant_edgetpu.tflite
Output size: 27.99MiB
On-chip memory used for caching model parameters: 2.50KiB
On-chip memory remaining for caching model parameters: 7.91MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 2105
Operation log: /mnt/raid0/jaylene/yolov10_testing/yolov10n_saved_model/yolov10n_full_integer_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 3
Number of operations that will run on CPU: 2102
See the operation log file for individual operation details.
Compilation child process completed within timeout period.
Compilation succeeded! 

### Environment

Ultralytics YOLOv8.2.87 🚀 Python-3.9.19 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
Setup complete ✅ (20 CPUs, 125.5 GB RAM, 999.4/1729.0 GB disk)

OS                  Linux-6.5.0-25-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.9.19
Install             pip
RAM                 125.47 GB
CPU                 Intel Core(TM) i9-9820X 3.30GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.1<2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

`yolo export model=yolov10n.pt format=tflite int8`

`edgetpu_compiler /your_path/yolov10n_saved_model/yolov10n_full_integer_quant.tflite --out_dir="/your_path/yolov10n_saved_model"
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for your detailed report. It seems the INT8 quantization might not be fully supported for all operations on the Edge TPU. Please ensure you're using a sufficient dataset for calibration, as the warning suggests more than 300 images. Additionally, verify that the latest version of the package is installed. If the issue persists, consider checking the model architecture for unsupported operations. For further guidance, please visit our documentation on Edge TPU deployment.

**Comment by Skillnoob** [comment]
Add the `imgsz=512` argument when exportin and running prediction. The Coral TPU has issues with image sizes above 512 and tends to map a lot of the OP's to the CPU if its higher than that.

**Comment by Curid** [comment]
Why is edgetpu export listed as supported✅  if the model architecture is fundamentally incompatible?

**Comment by glenn-jocher** [comment]
@Curid thank you for bringing this up. While Edge TPU export is supported, certain model architectures or operations may still be incompatible with the TPU hardware due to its limited operator support. You can review compatibility details in the [Edge TPU documentation](https://coral.ai/docs/edgetpu/models-intro/) for further clarity.
