### ISSUE TITLE
Error with stream url ['subtype' is not recognized]

### ISSUE THREAD

**Issue by mriamnobody** [ultralytics/ultralytics#1611]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm running command  `yolo predict model=yolov8n.pt --source='rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0'`. 

 Error

```
WARNING  '--source='rtsp://username:password@IP:PORT/cam/realmonitor?channel=1' does not require leading dashes '--', updating to 'source='rtsp://username:password@IP:PORT/cam/realmonitor?channel=1'.
Ultralytics YOLOv8.0.57  Python-3.10.7 torch-2.0.0+cpu CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

Traceback (most recent call last):
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 318, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\ultralytics\yolo\engine\model.py", line 228, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 119, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 146, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 128, in setup_source
    self.dataset = load_inference_source(source=source,
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\ultralytics\yolo\data\build.py", line 186, in load_inference_source
    dataset = LoadImages(source,
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 188, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: C:\Users\rosha\Downloads\Compressed\ultralytics-main\'rtsp://username:password@IP:PORT/cam/realmonitor?channel=1 does not exist
'subtype' is not recognized as an internal or external command,
operable program or batch file.
```

The URL of the IP camera is `rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0`. 

### Environment

Ultralytics YOLOv8.0.57  Python-3.10.7 torch-2.0.0+cpu CPU
-OS = Windows 11
-Python = 3.10.7

### Minimal Reproducible Example

yolo predict model=yolov8n.pt --source='rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mriamnobody** [comment]
Also, please add more documentation to use predict on streams. The current guides for stream are difficult to understand for beginner's.

**Comment by mriamnobody** [comment]
I have tried using the aforementioned url to play the live stream of the IP camera in VLC and it works fine. The brand of IP camera is Honeywell

**Comment by mriamnobody** [comment]
It seems I found the issue with the command I was using. The following command works for me:

`yolo predict model=yolov8n.pt --source "rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0"`

The key was to enclose the RTSP stream URL in double quotes, like this: `"rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0"`

Previously, I was using single quotes `yolo predict model=yolov8n.pt --source='rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0'`, which caused problems. By replacing the single quotes with double quotes, I successfully connected to the RTSP stream.

**Comment by mriamnobody** [comment]
@plashchynski @glenn-jocher . I have created a  PR to add documentation for the same.

**Comment by Laughing-q** [comment]
@mriamnobody hi, you should use `source=` instead of `--source=`.

**Comment by mriamnobody** [comment]
> @mriamnobody hi, you should use `source=` instead of `--source=`.

Thank you @Laughing-q for pointing this out. I have experimented with both `--source=` and `source=`, and both options function properly. The script automatically converts `--source=` to `source=` and utilizes it accordingly.

**Comment by Laughing-q** [comment]
@mriamnobody yeah but actually we don't want to support usage with extra `--`.😂 We'd like to unify the interface to `source=...`, `model=...`. :)
![image](https://user-images.githubusercontent.com/61612323/227710085-3b0b3643-09ac-4a6b-95d0-28cd7f493b7f.png)

**Comment by mriamnobody** [comment]
> @mriamnobody yeah but actually we don't want to support usage with extra `--`.😂 We'd like to unify the interface to `source=...`, `model=...`. :) ![image](https://user-images.githubusercontent.com/61612323/227710085-3b0b3643-09ac-4a6b-95d0-28cd7f493b7f.png)

That's great. It will avoid unnecessary confusion.
