### ISSUE TITLE
TensorRT Export Method Restricts Workspace Memory to 4GB

### ISSUE THREAD

**Issue by Mkhgkk** [ultralytics/ultralytics#16162]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When exporting a YOLOv8 model to TensorRT using the `export` method, I noticed that the `workspace` parameter seems to be limited to 4GB, even though my GPU (NVIDIA GeForce RTX 3060) has sufficient memory (12GB). Attempting to set the `workspace` parameter higher than 4GB causes the export process to fail or automatically reverts back to a default of 4GB. The issue persists even when my available memory is above 8GB during the export process.

Here is a summary of the memory :

```
| GPU          | Memory Usage | Total Memory |
| ------------ | ------------ | ------------ |
| NVIDIA RTX 3060 | 2MiB       | 12288MiB      |
```
Despite the available memory, setting the workspace parameter above 4GB results in failures or defaulting to 4GB.

Here's the error message that I get:

```
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.2.90 🚀 Python-3.9.19 torch-2.4.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3060, 11940MiB)
WARNING ⚠️ half=True and int8=True are mutually exclusive, setting half=False.
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
YOLOv8l summary (fused): 268 layers, 43,610,463 parameters, 0 gradients, 164.8 GFLOPs

PyTorch: starting from 'PPEbest.pt' with input shape (8, 3, 640, 640) BCHW and output shape(s) (8, 9, 8400) (83.6 MB)

ONNX: starting export with onnx 1.16.2 opset 19...
ONNX: export success ✅ 15.2s, saved as 'PPEbest.onnx' (166.5 MB)

TensorRT: starting export with TensorRT 10.4.0...
[09/10/2024-11:28:54] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 930, GPU 1351 (MiB)
[09/10/2024-11:28:56] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2132, GPU +394, now: CPU 3218, GPU 1745 (MiB)
[09/10/2024-11:28:56] [TRT] [I] ----------------------------------------------------------------
[09/10/2024-11:28:56] [TRT] [I] Input filename:   PPEbest.onnx
[09/10/2024-11:28:56] [TRT] [I] ONNX IR version:  0.0.9
[09/10/2024-11:28:56] [TRT] [I] Opset version:    19
[09/10/2024-11:28:56] [TRT] [I] Producer name:    pytorch
[09/10/2024-11:28:56] [TRT] [I] Producer version: 2.4.0
[09/10/2024-11:28:56] [TRT] [I] Domain:           
[09/10/2024-11:28:56] [TRT] [I] Model version:    0
[09/10/2024-11:28:56] [TRT] [I] Doc string:       
[09/10/2024-11:28:56] [TRT] [I] ----------------------------------------------------------------
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 9, -1) DataType.FLOAT
TensorRT: building INT8 engine as PPEbest.engine
TensorRT: collecting INT8 calibration images from 'data=coco8.yaml'
Scanning /home/Mkhgkk/Projects/Monitoring/models/datasets/coco8/labels/val.cache... 4 images, 0 
TensorRT: WARNING ⚠️ >300 images recommended for INT8 calibration, found 4 images.
[09/10/2024-11:28:56] [TRT] [I] Perform graph optimization on calibration graph.
[09/10/2024-11:28:56] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[09/10/2024-11:28:56] [TRT] [I] Compiler backend is used during engine build.
[09/10/2024-11:29:00] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[09/10/2024-11:29:00] [TRT] [I] Detected 1 inputs and 3 output network tensors.
[09/10/2024-11:29:01] [TRT] [I] Total Host Persistent Memory: 402848 bytes
[09/10/2024-11:29:01] [TRT] [I] Total Device Persistent Memory: 617472 bytes
[09/10/2024-11:29:01] [TRT] [I] Max Scratch Memory: 0 bytes
[09/10/2024-11:29:01] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 453 steps to complete.
[09/10/2024-11:29:02] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 72.4471ms to assign 28 blocks to 453 nodes requiring 983105024 bytes.
[09/10/2024-11:29:02] [TRT] [I] Total Activation Memory: 983105024 bytes
[09/10/2024-11:29:02] [TRT] [I] Total Weights Memory: 266779140 bytes
[09/10/2024-11:29:02] [TRT] [I] Compiler backend is used during engine execution.
[09/10/2024-11:29:02] [TRT] [I] Engine generation completed in 5.48889 seconds.
[09/10/2024-11:29:02] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +938, now: CPU 0, GPU 1193 (MiB)
[09/10/2024-11:29:02] [TRT] [I] Starting Calibration.
[09/10/2024-11:29:04] [TRT] [I]   Calibrated batch 0 in 2.44139 seconds.
[09/10/2024-11:29:47] [TRT] [I]   Post Processing Calibration data in 43.0597 seconds.
[09/10/2024-11:29:47] [TRT] [I] Calibration completed in 51.0919 seconds.
[09/10/2024-11:29:47] [TRT] [I] Writing Calibration Cache for calibrator: TRT-100400-EntropyCalibration2
[09/10/2024-11:29:47] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[09/10/2024-11:29:47] [TRT] [E] IBuilder::buildSerializedNetwork: Error Code 10: Internal Error (Could not find any implementation for node /model.0/conv/Conv + PWN(PWN(/model.0/act/Sigmoid), PWN(/model.0/act/Mul)).)
TensorRT: export failure ❌ 68.9s: __enter__
Traceback (most recent call last):
  File "/home/Mkhgkk/Projects/Monitoring/models/convert.py", line 19, in <module>
    model.export(
  File "/home/Mkhgkk/.conda/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/model.py", line 747, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/Mkhgkk/.conda/envs/yolov8/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/Mkhgkk/.conda/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 305, in __call__
    f[1], _ = self.export_engine()
  File "/home/Mkhgkk/.conda/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/Mkhgkk/.conda/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/Mkhgkk/.conda/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 801, in export_engine
    with build(network, config) as engine, open(f, "wb") as t:
AttributeError: __enter__
```

**Comment by Y-T-G** [comment]
Can you provide the output after running this command in terminal: `yolo checks`?

And also the command you used to export.

**Comment by Mkhgkk** [comment]
> Can you provide the output after running this command in terminal: `yolo checks`?
> 
> And also the command you used to export.

```
$ yolo checks

Setup complete ✅ (8 CPUs, 31.2 GB RAM, 83.2/464.2 GB disk)

OS                  Linux-6.10.6-200.fc40.x86_64-x86_64-with-glibc2.39
Environment         Linux
Python              3.9.19
Install             pip
RAM                 31.18 GB
CPU                 Intel Core(TM) i7-9700K 3.60GHz
CUDA                11.8

numpy               ✅ 1.24.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.4.0+cu118>=1.8.0
torchvision         ✅ 0.19.0+cu118>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.0+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"
```

I used the following script to export:

```
from ultralytics import YOLO

model = YOLO("yolov8_model.pt", task="detect")

 model.export(
     format="engine",
     dynamic=True,  
     batch=8,  
     workspace=8,  # only 4 works
     int8=True,
)
```

**Comment by Y-T-G** [comment]
What version of Ultralytics is it? I don't know why you removed that from the output.

**Comment by Y-T-G** [comment]
Try exporting with no arguments except `format` and then them one by one until it errors.

**Comment by Maradowei** [comment]
same problem

**Comment by glenn-jocher** [comment]
Please ensure you're using the latest version of the Ultralytics package and try exporting without additional arguments to identify the issue. If the problem persists, consider checking the TensorRT installation and compatibility with your GPU.
