### ISSUE TITLE
how to read from live youtube stream ?

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#16206]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i want to know how to do detection from live YouTube stream ?

**Comment by Y-T-G** [comment]
You can get the frame like [here](https://stackoverflow.com/a/67085893/8061030) and then run your model on it.

**Comment by VYRION-Ai** [comment]
@Y-T-G this gives error 

```
`ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\pafy\backend_youtube_dl.py", line 40, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Python\neehal\main2.py", line 4, in <module>
    video = pafy.new(url)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\pafy\pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\pafy\backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\pafy\backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "C:\Users\Mariam\AppData\Local\Programs\Python\Python310\lib\site-packages\pafy\backend_youtube_dl.py", line 43, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
```


and this code work for me 
```

`import cv2
import yt_dlp
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('s.pt')

# YouTube video URL
video_url = "https://www.youtube.com/watch?v=EuOZeHQmg-4"

# Configure yt-dlp
ydl_opts = {
    'format': 'best[ext=mp4]',
}

# Extract video info
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(video_url, download=False)
    url = info['url']

# Create a video capture object
cap = cv2.VideoCapture(url)

# Get video properties
fps = int(cap.get(cv2.CAP_PROP_FPS))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('output.mp4', fourcc, fps, (width, height))

while True:
    # Read a frame from the video
    success, frame = cap.read()

    if not success:
        break

    # Run YOLOv8 inference on the frame
    results = model(frame, classes=[3, 4, 5, 6, 7, 8, 9, 10])

    # Visualize the results on the frame
    annotated_frame = results[0].plot()

    # Write the frame to the output video
    out.write(annotated_frame)

    # Display the annotated frameq
    cv2.imshow("YOLOv8 Inference", annotated_frame)

    # Break the loop if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

# Release the video capture object, writer, and close the display window
cap.release()
out.release()
cv2.destroyAllWindows()`
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @VYRION-Ai, thank you for submitting a `ultralytics/ultralytics` 🚀 Issue. This is an automated response, but an Ultralytics engineer will also assist you soon.

To perform detection from a live YouTube stream, you can follow these general steps:

1. **Obtain the Stream URL:**
   - You can use tools like `youtube-dl` to extract the live stream URL. Install it via pip with `pip install youtube-dl`.
   - Example command to get the stream URL:
     ```bash
     youtube-dl -g "https://www.youtube.com/watch?v=your_video_id"
     ```

2. **Set Up Video Capture:**
   - Use OpenCV to read the stream in Python.
   - Example code to capture the stream:
     ```python
     import cv2

     stream_url = 'your_extracted_stream_url'
     cap = cv2.VideoCapture(stream_url)

     while cap.isOpened():
         ret, frame = cap.read()
         if not ret:
             break
         # Add your detection code here

         cv2.imshow('frame', frame)
         if cv2.waitKey(1) & 0xFF == ord('q'):
             break

     cap.release()
     cv2.destroyAllWindows()
     ```

3. **Run YOLO Detection:**
   - Call the Ultralytics YOLO model within the loop to process each frame.
   - Example integration:
     ```python
     from ultralytics import YOLO

     model = YOLO('yolov8n.pt')  # Load a pre-trained model

     while cap.isOpened():
         ret, frame = cap.read()
         if not ret:
             break

         # Perform detection
         results = model(frame)
         # Optional: visualize results
         results.show()

         if cv2.waitKey(1) & 0xFF == ord('q'):
             break
     ```

Make sure you've checked our [documentation](https://docs.ultralytics.com) for more details about model usage and customization.

If you encounter any issues or need further help, feel free to update this issue with more information. Thank you for your contribution to improving our project! 🌟
