### ISSUE TITLE
yolov8_pose

### ISSUE THREAD

**Issue by mcyhaha** [ultralytics/ultralytics#16248]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "D:\yolov8_pose\train_yolo.py", line 12, in <module>
    model = YOLO('D:\\yolov8_pose\\ultralytics\\cfg\\models\\v8\\yolov8n-SPDConv.yaml')#.load('D:\\dlcode\\ultralytics-main\\yolov8n-pose.pt')  # 从YAML构建并传输权重
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "D:\yolov8_pose\ultralytics\engine\model.py", line 149, in __init__
    self._new(model, task=task, verbose=verbose)
  File "D:\yolov8_pose\ultralytics\engine\model.py", line 218, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 424, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 337, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in _forward(torch.zeros(1, ch, s, s))])  # forward
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 335, in _forward
    return self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
           ^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 113, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 131, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 152, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\modules\conv.py", line 360, in forward
    return torch.cat(x, self.d)
           ^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 8 for tensor number 1 in the list.

进程已结束,退出代码1

### Additional

doyouhelp

**Comment by Skillnoob** [comment]
change it to `model = YOLO('D:\yolov8_pose\ultralytics\cfg\models\v8\yolov8n-SPDConv.yaml', task='pose')#.load('D:\dlcode\ultralytics-main\yolov8n-pose.pt')`. You're not loading it as a pose model

**Comment by mcyhaha** [comment]
Traceback (most recent call last):
  File "D:\yolov8_pose\train_yolo.py", line 12, in <module>
    model = YOLO('D:\\yolov8_pose\\ultralytics\\cfg\\models\\v8\\yolov8n-SPDConv.yaml', task='pose')#.load('D:\\dlcode\\ultralytics-main\\yolov8n-pose.pt')  # 从YAML构建并传输权重
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "D:\yolov8_pose\ultralytics\engine\model.py", line 149, in __init__
    self._new(model, task=task, verbose=verbose)
  File "D:\yolov8_pose\ultralytics\engine\model.py", line 218, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 424, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 337, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in _forward(torch.zeros(1, ch, s, s))])  # forward
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 335, in _forward
    return self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
                                                                          ^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 113, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 131, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\tasks.py", line 152, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcy\anaconda3\envs\face_env\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov8_pose\ultralytics\nn\modules\conv.py", line 360, in forward
    return torch.cat(x, self.d)
           ^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 8 for tensor number 1 in the list.

进程已结束,退出代码1
Hello, I have added it, but this problem still occurs. How can I solve it?

**Comment by Y-T-G** [comment]
It's a problem with your yaml
