### ISSUE TITLE
yolov8 shows error while saving pridiction result

### ISSUE THREAD

**Issue by deepanshusharmaindore** [ultralytics/ultralytics#1630]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

yolov8 shows error while save=true in pridiction result
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/content/ultralytics/ultralytics/yolo/cfg/__init__.py", line 318, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/ultralytics/ultralytics/yolo/engine/model.py", line 228, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/content/ultralytics/ultralytics/yolo/engine/predictor.py", line 119, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 64, in generator_context
    response = gen.send(request)
  File "/content/ultralytics/ultralytics/yolo/engine/predictor.py", line 193, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/content/ultralytics/ultralytics/yolo/v8/detect/predict.py", line 72, in write_results
    name = ('' if id is None else f'id:{id} ') + self.model.names[c]
TypeError: can only concatenate str (not "bool") to str

### Minimal Reproducible Example

!yolo task=detect mode=predict model=/content/last.pt conf=0.70 source=/content/1.mp4 save=True

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@deepanshusharmaindore I'm not able to reproduce any issues using predict with a video using a pretrained YOLOv8n model.

Do your classes names contain booleans, i.e. True or False?

**Comment by glenn-jocher** [comment]
@glenn-jocher I'm able to reproduce now with class as booleans, working on a fix.

**Comment by glenn-jocher** [comment]
@deepanshusharmaindore should be fixed in PR #1633 which will merge into main branch and deploy in the next pip package release soon. Thank you for letting us know about this problem and please let us know if you spot any other issues!
