### ISSUE TITLE
Issues related to modifying the v8/segment/train.py file

### ISSUE THREAD

**Issue by PiBigStar5712** [ultralytics/ultralytics#1635]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train custom datasets through the v8/segment/train.py file.And I created a new segment.yaml file to replace default.yaml.
Here is the content of segment.yaml
```
task: segment  # inference task, i.e. detect, segment, classify
mode: train  # YOLO mode, i.e. train, val, predict, export

# Train settings -------------------------------------------------------------------------------------------------------
model: 'F:/yolov8_official/weights/yolov8s-seg.pt' # path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: 'F:/yolov8_official/ultralytics/datasets/mydata_seg.yaml' # path to data file, i.e. coco128.yaml
epochs: 100  # number of epochs to train for
patience: 50  # epochs to wait for no observable improvement for early stopping of training
batch: 4  # number of images per batch (-1 for AutoBatch)
imgsz: 640  # size of input images as integer or w,h
save: True  # save train checkpoints and predict results
save_period: -1 # Save checkpoint every x epochs (disabled if < 1)
cache: False  # True/ram, disk or False. Use cache for data loading
device: 0 # device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 1  # number of worker threads for data loading (per RANK if DDP)
project:  # project name
name:  # experiment name, results saved to 'project/name' directory
exist_ok: False  # whether to overwrite existing experiment
pretrained: False  # whether to use a pretrained model
optimizer: SGD  # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
verbose: True  # whether to print verbose output
seed: 0  # random seed for reproducibility
deterministic: True  # whether to enable deterministic mode
single_cls: False  # train multi-class data as single-class
image_weights: False  # use weighted image selection for training
rect: False  # support rectangular training if mode='train', support rectangular evaluation if mode='val'
cos_lr: False  # use cosine learning rate scheduler
close_mosaic: 10  # disable mosaic augmentation for final 10 epochs
resume: False  # resume training from last checkpoint
# Segmentation
overlap_mask: True  # masks should overlap during training (segment train only)
mask_ratio: 4  # mask downsample ratio (segment train only)
# Classification
dropout: 0.0  # use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True  # validate/test during training
split: val  # dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # save results to JSON file
save_hybrid: False  # save hybrid version of labels (labels + additional predictions)
conf:  # object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7  # intersection over union (IoU) threshold for NMS
max_det: 300  # maximum number of detections per image
half: False  # use half precision (FP16)
dnn: False  # use OpenCV DNN for ONNX inference
plots: True  # save plots during train/val

# Prediction settings --------------------------------------------------------------------------------------------------
source:  # source directory for images or videos
show: False  # show results if possible
save_txt: False  # save results as .txt file
save_conf: False  # save results with confidence scores
save_crop: False  # save cropped images with results
hide_labels: False  # hide labels
hide_conf: False  # hide confidence scores
vid_stride: 1  # video frame-rate stride
line_thickness: 3  # bounding box thickness (pixels)
visualize: False  # visualize model features
augment: False  # apply image augmentation to prediction sources
agnostic_nms: False  # class-agnostic NMS
classes:  # filter results by class, i.e. class=0, or class=[0,2,3]
retina_masks: False  # use high-resolution segmentation masks
boxes: True  # Show boxes in segmentation predictions

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript  # format to export to
keras: False  # use Keras
optimize: False  # TorchScript: optimize for mobile
int8: False  # CoreML/TF INT8 quantization
dynamic: False  # ONNX/TF/TensorRT: dynamic axes
simplify: False  # ONNX: simplify model
opset:  # ONNX: opset version (optional)
workspace: 4  # TensorRT: workspace size (GB)
nms: False  # CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # final learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 3.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr
box: 7.5  # box loss gain
cls: 0.5  # cls loss gain (scale with pixels)
dfl: 1.5  # dfl loss gain
fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
label_smoothing: 0.0  # label smoothing (fraction)
nbs: 64  # nominal batch size
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability)

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # for overriding defaults.yaml

# Debug, do not modify -------------------------------------------------------------------------------------------------
v5loader: False  # use legacy YOLOv5 dataloader

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: bytetrack.yaml  # tracker type, ['botsort.yaml', 'bytetrack.yaml']
```
I checked the content of train() in v8/segment/train.py, and I wanted to use segment. yaml as the value of cfg, so I modified the main() code.
`train(cfg='F:/yolov8_official/ultralytics/yolo/cfg/segment.yaml', use_python=True)`

When I ran train.py, an error occurred.
```
Traceback (most recent call last):
  File "F:\yolov8_official\ultralytics\yolo\v8\segment\train.py", line 164, in <module>
    train(cfg='F:/yolov8_official/ultralytics/yolo/cfg/segment.yaml', use_python=True)
  File "F:\yolov8_official\ultralytics\yolo\v8\segment\train.py", line 150, in train
    model = cfg.model or 'yolov8n-seg.pt'
AttributeError: 'str' object has no attribute 'model'
```

I guess the content I entered into cfg is incorrect. I looked at the code and found that it was actually the function IterableSimpleNamespace that assigned the value to cfg. The only thing I actually need to modify is DEFAULT_ CFG_ PATH content, but this part of the code is in yolo/utils/__ init__.py, I can't go there every time to modify the path. So what should I do?

**Comment by glenn-jocher** [comment]
@PiBigStar5712 we haven't actually established Python usage examples for cfg I believe (@AyushExel or @Laughing-q do you guys know of any?)

The existing usage is CLI-based, i.e. create a custom.yaml file and then:

```bash
yolo custom.yaml
```

<img width="1441" alt="Screenshot 2023-03-26 at 15 25 21" src="https://user-images.githubusercontent.com/26833433/227785493-92f2ddbf-f69c-4efb-85ba-944896c0c036.png">

**Comment by AyushExel** [comment]
Yeah that's right, the official interfaces are:
* CLI (using `yolo` command)
* And Python

**Comment by PiBigStar5712** [comment]
> 'F:/yolov8_official/ultralytics/yolo/cfg/segment.yaml'

Considering that I may use both segment and detect modes in the future, I may need to create a demo.py file myself, in which I run the segment task and detect task through two threads.Or does the current V8 already integrate such a pattern? Please let me know if it is.
I hope to complete my idea above by calling the predict function in the predict. py file under different mode folders at the same time.But their cfg seems to point to the same DEFAULT_ CFG like this `def predict(cfg=DEFAULT_CFG, use_python=False):`
So I modified some codes in `ultralytics/yolo/utils/__init__.py`.The following has been added.

```
CLASSIFY_CFG_PATH = ROOT / 'yolo/cfg/classify.yaml'
DETECT_CFG_PATH = ROOT / 'yolo/cfg/detect.yaml'
SEGMENT_CFG_PATH = ROOT / 'yolo/cfg/segment.yaml'

# Classify configuration
CLASSIFY_CFG_DICT = yaml_load(CLASSIFY_CFG_PATH)
for k, v in CLASSIFY_CFG_DICT.items():
    if isinstance(v, str) and v.lower() == 'none':
        CLASSIFY_CFG_DICT[k] = None
CLASSIFY_CFG_KEYS = CLASSIFY_CFG_DICT.keys()
CLASSIFY_CFG = IterableSimpleNamespace(**CLASSIFY_CFG_DICT)

# Detect configuration
DETECT_CFG_DICT = yaml_load(DETECT_CFG_PATH)
for k, v in DETECT_CFG_DICT.items():
    if isinstance(v, str) and v.lower() == 'none':
        DETECT_CFG_DICT[k] = None
DETECT_CFG_KEYS = DETECT_CFG_DICT.keys()
DETECT_CFG = IterableSimpleNamespace(**DETECT_CFG_DICT)

# Segment configuration
SEGMENT_CFG_DICT = yaml_load(SEGMENT_CFG_PATH)
for k, v in SEGMENT_CFG_DICT.items():
    if isinstance(v, str) and v.lower() == 'none':
        SEGMENT_CFG_DICT[k] = None
SEGMENT_CFG_KEYS = SEGMENT_CFG_DICT.keys()
SEGMENT_CFG = IterableSimpleNamespace(**SEGMENT_CFG_DICT)
```

In addition, I have also modified the relevant codes of all files under the three directories: `ultralytics/yolo/v8/classify` ,`ultralytics/yolo/v8/detect` and `ultralytics/yolo/v8/segment`.
So, when I run `ultratics/yolo/v8/segment/train.py`, it's already able to start training.But there are still some problems.The following is the operation log.

```
New https://pypi.org/project/ultralytics/8.0.58 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.55  Python-3.10.9 torch-1.11.0 CUDA:0 (NVIDIA GeForce RTX 2060, 6144MiB)
yolo\engine\trainer: task=segment, mode=train, model=F:/yolov8_official/weights/yolov8s-seg.pt, data=F:/yolov8_official/ultralytics/datasets/mydata_seg.yaml, epochs=100, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=1, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=bytetrack.yaml, save_dir=runs\segment\train
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.Conv                  [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.C2f                   [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.C2f                   [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.C2f                   [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.C2f                   [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.C2f                   [768, 512, 1]                 
 22        [15, 18, 21]  1   2771705  ultralytics.nn.modules.Segment               [3, 32, 128, [128, 256, 512]] 
YOLOv8s-seg summary: 261 layers, 11791257 parameters, 11791241 gradients, 42.7 GFLOPs

Transferred 411/417 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs\segment\train', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
fatal: not a git repository (or any of the parent directories): .git
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%|██████████| 6.23M/6.23M [00:01<00:00, 3.96MB/s]
WARNING  NMS time limit 0.550s exceeded
AMP: checks passed 
optimizer: SGD(lr=0.01) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias
train: Scanning F:\yolov8_official\MyDataSets\segement\my_final_datasets\labels\train... 2940 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2940/2940 [01:00<00:00, 48.88it/s]
train: New cache created: F:\yolov8_official\MyDataSets\segement\my_final_datasets\labels\train.cache
val: Scanning F:\yolov8_official\MyDataSets\segement\my_final_datasets\labels\val... 420 images, 0 backgrounds, 0 corrupt: 100%|██████████| 420/420 [00:04<00:00, 92.07it/s] 
val: New cache created: F:\yolov8_official\MyDataSets\segement\my_final_datasets\labels\val.cache
Plotting labels to runs\segment\train\labels.jpg... 
Image sizes 640 train, 640 val
Using 1 dataloader workers
Logging results to runs\segment\train
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/735 [00:00<?, ?it/s]Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x0000016D62722C20>
Traceback (most recent call last):
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "G:\Anaconda\envs\deeplearning_pytorch\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
      1/100      2.06G      0.393     0.5637     0.6628     0.8827         60        640: 100%|██████████| 735/735 [03:29<00:00,  4.00it/s]Exception ignored in: <function StorageWeakRef.__del__ at 0x00000165BB0E2C20>
```

As you can see, it reported an ERROR. But this ERROR doesn't seem to affect its training.When I Google it, it seems that this problem has occurred in YOLOV5, and when someone else's solution is modified, num_ workers parameter.I will try this method later.
This log also contains another problem. There was an error reading the weight file.I have already set `model=F:/yolov8_ Official/weights/yolov8s seg.pt`, but at runtime, it still performs `Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...`.
Is it because I only modified the source code, but when it actually runs, it is still running the ultralytics package?The issue of invalid source code modification seems to have occurred in ultrametrics==8.0.20 or earlier versions.
Sorry to take up your time！

**Comment by stphtan94117** [comment]
I very much agree that a photo can detect the effect of bbox and segment. 
I really hope that detect.py and predict.py can be combined into one file. During training, the dataset can be combined with bbox and segmentation.
For example, in a photo of my roof, I want to display the roof tiles in bbox mode, and the cracks in the roof tiles are displayed in segment mode.

One photo shows two effects at the same time.

**Comment by glenn-jocher** [comment]
Thank you for your suggestion. Currently, the `detect.py` script performs object detection using bounding boxes and `segment.py` script performs instance segmentation using masks. We understand the usefulness of being able to perform both tasks on the same image and will consider this for future updates to the codebase. Meanwhile, you can try modifying the code to suit your needs. You can refer to the `detect.py` and `segment.py` scripts as examples and edit the code to perform both tasks on the same image. If you have any specific questions or issues, feel free to ask and I'll be happy to assist you.
