### ISSUE TITLE
export tflite,error No module named 'keras.src.engine

### ISSUE THREAD

**Issue by fansangg** [ultralytics/ultralytics#16365]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Ultralytics YOLOv8.2.97 🚀 Python-3.11.9 torch-2.4.1+cpu CPU (11th Gen Intel Core(TM) i5-1135G7 2.40GHz)
Model summary (fused): 218 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs

PyTorch: starting from 'runs\detect\train2\weights\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (49.6 MB)

TensorFlow SavedModel: starting export with tensorflow 2.16.1...
WARNING:tensorflow:From C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\tensorflow_probability\python\internal\backend\numpy\_utils.py:48: The name tf.logging.TaskLevelStatusMessage is deprecated. Please use tf.compat.v1.logging.TaskLevelStatusMessage instead.

WARNING:tensorflow:From C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\tensorflow_probability\python\internal\backend\numpy\_utils.py:48: The name tf.control_flow_v2_enabled is deprecated. Please use tf.compat.v1.control_flow_v2_enabled instead.

Traceback (most recent call last):
  File "F:\yolov8\toONNX.py", line 4, in <module>
    model.export(format='tflite')
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\model.py", line 735, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\exporter.py", line 314, in __call__
    f[5], keras_model = self.export_saved_model()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\exporter.py", line 142, in outer_func
    raise e
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\exporter.py", line 846, in export_saved_model
    import onnx2tf
  File "F:\yolov8\onnx2tf.py", line 1, in <module>
    from onnx_tf.backend import prepare
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\onnx_tf\__init__.py", line 1, in <module>
    from . import backend
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\onnx_tf\backend.py", line 28, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\onnx_tf\common\handler_helper.py", line 3, in <module>
    from onnx_tf.handlers.backend import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\onnx_tf\handlers\backend\hardmax.py", line 3, in <module>
    import tensorflow_addons as tfa
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\tensorflow_addons\__init__.py", line 23, in <module>
    from tensorflow_addons import activations
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\tensorflow_addons\activations\__init__.py", line 17, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\tensorflow_addons\activations\gelu.py", line 19, in <module>
    from tensorflow_addons.utils.types import TensorLike
  File "C:\Users\KCST\.conda\envs\yolo\Lib\site-packages\tensorflow_addons\utils\types.py", line 29, in <module>
    from keras.src.engine import keras_tensor
ModuleNotFoundError: No module named 'keras.src.engine'
TensorFlow SavedModel: export failure ❌ 10.0s: No module named 'keras.src.engine'

### Environment

Ultralytics YOLOv8.2.97 🚀 Python-3.11.9 torch-2.4.1+cpu CPU (11th Gen Intel Core(TM) i5-1135G7 2.40GHz)
Setup complete ✅ (8 CPUs, 15.8 GB RAM, 59.8/113.0 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.78 GB
CPU                 11th Gen Intel Core(TM) i5-1135G7 2.40GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("runs/detect/train2/weights/best.pt")
model.export(format='tflite')

### Additional

help me,thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @fansangg, thank you for reaching out and using Ultralytics 🚀! This is an automated response. An Ultralytics engineer will assist you soon.

For now, if this is a 🐛 Bug Report, you've made a great start by including an MRE. Ensure your environment is correctly set up with the required dependencies. It seems like there might be a missing Keras module, so please verify your Keras and TensorFlow installations.

For a complete check, you may want to upgrade your environment to the latest `ultralytics` package along with all requirements in a **Python>=3.8** environment:

```bash
pip install -U ultralytics
```

For more support:
- Visit our [Docs](https://docs.ultralytics.com) for guidance.
- Check out real-time discussions on [Discord](https://ultralytics.com/discord) 🎧.
- Engage in forum discussions on [Discourse](https://community.ultralytics.com).

## Environments

YOLOv8 can be run in any of the following up-to-date verified environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**, **AWS**, and **Docker** – see environment quickstart guides in our docs.

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all CI tests are passing. CI tests verify correct operation on macOS, Windows, and Ubuntu every 24 hours and on every commit.

Thank you for your patience!
