### ISSUE TITLE
DDP: multi node training erro

### ISSUE THREAD

**Issue by ljwweb** [ultralytics/ultralytics#16406]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

This is my train code:
```shell
import time
import ultralytics
from ultralytics.utils import RANK, LOCAL_RANK
import torch.distributed as dist
if __name__ == "__main__":
    print(f"{RANK=} -- {LOCAL_RANK=}")
    dist.init_process_group(
        backend="nccl",
        init_method="env://",
        world_size=1,
        rank=RANK,
    )
    yaml_file = "/mnt/shanhs/shanhs-ai/ddp_train/label_studio_project_7118e7e0d0_10948/data.yaml"
    max_epochs = 2
    batch_size = 2
    imgsz = 640
    name = "DDP"
    model = ultralytics.models.YOLO('yolov9t.yaml')
    start = time.perf_counter()
    results = model.train(
        data=yaml_file,
        epochs=max_epochs,
        batch=batch_size,
        name=name,
        # device=[LOCAL_RANK],
        device=0,
    )
    print(f"Training took {time.perf_counter() - start:.5f} seconds to run")
```

Server environment:
```shell
ultralytics              8.2.98
Python                   3.10.14

(ddp1) [root@pro-gpu-a10-1 ddp_train]# python 
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.version.cuda)
12.1
>>> torch.cuda.nccl.version()
(2, 20, 5)
```
I have two nodes,Same environment

master  cmd:
```shell
torchrun --nproc_per_node 1 --nnodes 2 --node_rank 0 --master_addr "172.18.240.208" --master_port 8456 --local_addr "172.18.240.208" train.py
```

node  cmd:
```shell
torchrun --nproc_per_node 1 --nnodes 2 --node_rank 1 --master_addr "172.18.240.208" --master_port 8456 --local_addr "172.18.16.16" train.py
```
master log: 
```shell
RANK=0 -- LOCAL_RANK=0
Ultralytics YOLOv8.2.98 🚀 Python-3.10.14 torch-2.4.1+cu121 CUDA:0 (NVIDIA A10, 22516MiB)
NCCL version 2.20.5+cuda12.4
Overriding model.yaml nc=80 with nc=8
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /mnt/shanhs/shanhs-ai/ddp_train/label_studio_project_7118e7e0d0_10948/labels/2726.cache... 960 images, 701 backgrounds, 0 corrupt: 100%|██████████| 1661/1
val: Scanning /mnt/shanhs/shanhs-ai/ddp_train/label_studio_project_7118e7e0d0_10948/images_val.cache... 106 images, 0 backgrounds, 0 corrupt: 100%|██████████| 106/106 [00
Plotting labels to runs/detect/DDP23/labels.jpg... 
/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/utils/plotting.py:921: UserWarning: Glyph 22806 (\N{CJK UNIFIED IDEOGRAPH-5916}) missing from font(s) DejaVu Sans.
  plt.savefig(fname, dpi=200)
/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/utils/plotting.py:921: UserWarning: Glyph 22771 (\N{CJK UNIFIED IDEOGRAPH-58F3}) missing from font(s) DejaVu Sans.
  plt.savefig(fname, dpi=200)
/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/utils/plotting.py:921: UserWarning: Glyph 21010 (\N{CJK UNIFIED IDEOGRAPH-5212}) missing from font(s) DejaVu Sans.
  plt.savefig(fname, dpi=200)
/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/utils/plotting.py:921: UserWarning: Glyph 30165 (\N{CJK UNIFIED IDEOGRAPH-75D5}) missing from font(s) DejaVu Sans.
  plt.savefig(fname, dpi=200)
/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/utils/plotting.py:921: UserWarning: Glyph 21051 (\N{CJK UNIFIED IDEOGRAPH-523B}) missing from font(s) DejaVu Sans.
......
```

master Everything looks normal

node log:
```shell
RANK=1 -- LOCAL_RANK=0
[rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/shanhs/shanhs-ai/ddp_train/train.py", line 20, in <module>
[rank1]:     results = model.train(
[rank1]:   File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/engine/model.py", line 797, in train
[rank1]:     self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
[rank1]:   File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 132, in __init__
[rank1]:     with torch_distributed_zero_first(LOCAL_RANK):  # avoid auto-downloading dataset multiple times
[rank1]:   File "/root/miniconda3/envs/ddp1/lib/python3.10/contextlib.py", line 142, in __exit__
[rank1]:     next(self.gen)
[rank1]:   File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py", line 64, in torch_distributed_zero_first
[rank1]:     dist.barrier(device_ids=[local_rank])
[rank1]:   File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3936, in barrier
[rank1]:     work = default_pg.barrier(opts=opts)
[rank1]: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:275, invalid argument (run with NCCL_DEBUG=WARN for details), NCCL version 2.20.5
[rank1]: ncclInvalidArgument: Invalid value for an argument.
[rank1]: Last error:
[rank1]: Invalid rank requested : 1/1
[rank1]:[W921 15:34:55.363793818 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0921 15:34:56.200000 139872377438656 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 40500) of binary: /root/miniconda3/envs/ddp1/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/ddp1/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/ddp1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-21_15:34:56
  host      : pro-gpu-a10-2
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 40500)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
I don't know why there was an error

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ljwweb, thank you for your interest in Ultralytics 🚀!

This is an automated response to help get you started. An Ultralytics engineer will also assist you soon.

If you're encountering a 🐛 bug, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug the issue better. Your current setup details are very informative—thank you for including them!

For multi-node Distributed Data Parallel (DDP) setups, check the following:
1. Ensure all nodes have the same version of both PyTorch and the `ultralytics` package installed.
2. Confirm that the NCCL backend is properly configured. If you haven't already, try setting `NCCL_DEBUG=WARN` to get more details on the NCCL error.
3. Double-check network connectivity and firewall settings between your nodes.

💡 While you wait, you might find it helpful to review our [Model Training Tips](https://docs.ultralytics.com/guides/model-training-tips/) for any insights that could enhance your setup.

👥 Join the Ultralytics community for more support and insights:
- [Discord](https://ultralytics.com/discord) 🎧 for real-time chat.
- [Discourse](https://community.ultralytics.com) for detailed discussions.
- [Subreddit](https://reddit.com/r/ultralytics) for community knowledge sharing.

## Upgrade

Please ensure you are using the latest `ultralytics` package with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [Python>=3.8](https://www.python.org/) environment with [PyTorch>=1.8](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLOv8 can be run in verified environments such as:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon**: See our [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: See our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml) tests are currently passing.

Stay tuned for further assistance from our team!

**Comment by glenn-jocher** [comment]
@ljwweb it seems like the issue might be related to the NCCL setup for multi-node training. Please ensure that the `world_size` is set correctly to the total number of processes across all nodes, and verify that the `rank` and `node_rank` are appropriately configured for each node. Additionally, check the network connectivity between nodes and ensure that the `master_addr` and `master_port` are accessible from all nodes. For further details, you can refer to the PyTorch distributed training documentation.
