### ISSUE TITLE
Tuner occasionally locks up waiting on a completed training run

### ISSUE THREAD

**Issue by Drise13** [ultralytics/ultralytics#16400]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When running the tuner, at the end a train after the validation, the tuner can get stuck waiting for the subprocess to complete. I noticed that there was a trainer thread using a full cpu core. I'm not sure what it was doing, but it seemed stuck. I was able to kill it `kill -9` and that iteration failed but tuning resumed.

### Environment

Ultralytics YOLOv8.2.95 🚀 Python-3.8.10 torch-2.2.2+cu121 CUDA:0 (NVIDIA L40S, 45596MiB)
Setup complete ✅ (64 CPUs, 377.5 GB RAM, 577.6/878.1 GB disk)

OS                  Linux-5.4.0-193-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 377.48 GB
CPU                 AMD EPYC 9354P 32-Core Processor
CUDA                12.1

numpy               ✅ 1.24.3<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 5.3.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.2.2!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO('yolov8n-pose.yaml')

model.tune(data=...)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Drise13, thanks for raising this issue with Ultralytics 🚀! We're glad to have your input.

It seems like you've encountered a potential bug when running the tuner. To assist our team in diagnosing the problem, please ensure you provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). This will help us debug more effectively.

While you're waiting, please check if you are using the latest `ultralytics` package version and all dependencies are up-to-date. You can upgrade with the following command:

```bash
pip install -U ultralytics
```

Our systems are verified in multiple environments including Google Colab, Kaggle, and Docker. You might want to try running your code in one of these to see if the issue persists. For more details, refer to our [environment documentation](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/).

If you haven't already, feel free to join our community discussions on [Discord](https://ultralytics.com/discord) 🎧 or engage with the community on [Discourse](https://community.ultralytics.com).

This is an automated response to ensure we quickly gather all necessary information. An Ultralytics engineer will assist you soon. Thank you for your patience and understanding!

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all CI tests have successfully passed, confirming the correct functioning of YOLOv8 across various systems.

**Comment by Y-T-G** [comment]
You can use `kill -2` when that happens and it should print a traceback of where it was stuck. You can post that traceback here if you get it.

**Comment by Y-T-G** [comment]
Could be related to this.

https://github.com/pytorch/pytorch/issues/33296

**Comment by Drise13** [comment]
I will post the trackback when it happens. Its blocked me 3 times now this weekend so I'm certain it will happen again.

**Comment by glenn-jocher** [comment]
Thank you for your patience. Please share the traceback when it occurs, and we'll assist you further.

**Comment by Drise13** [comment]
Killed via -2, it did not report any traceback and considered it a successful run. I'm fairly confused by this result.

**Comment by Drise13** [comment]
Confirmed. Killing the "stuck" thread via -2 considers the run a success and tuning continues normally.

**Comment by glenn-jocher** [comment]
It seems like the issue resolves itself when you use `kill -2`, allowing tuning to continue. If the problem persists, consider checking for updates or trying a different environment. Let us know if you need further assistance!

**Comment by Drise13** [comment]
@glenn-jocher This requires manual intervention which is counterintuitive to the "fire and forget" concept of the tuning process which can take many days to complete. Manually killing the process is not a solution.

**Comment by glenn-jocher** [comment]
@Drise13 thank you for your feedback. We'll investigate this issue further to improve the tuning process. Please ensure you're using the latest version, and we'll update you with any developments.

**Comment by mpperez3** [comment]
I have the same sporadic problem but instead of using 100% of the CPU, in my case it uses 100% of one GPU, because I use the GPUs for training. My research tells me that it is related to the torch dataloader (the trace points here when killing the process), threads and with the following that @Y-T-G  has also shared.
https://github.com/pytorch/pytorch/issues/33296

In my case I am using: 
```
“torch==2.5.1”,
“torchvision==0.20.1”,
“ultralytics==8.3.28”,
```

I have tried setting the number of ultralytics train workers to 1 minimised the problem, but it is not sure because it is a sporadic problem :(

**Comment by mpperez3** [comment]
@Y-T-G sorry for the delay. The problem is so random that it has taken until today to fail. 

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
[rank0]:     data = self._data_queue.get(timeout=timeout)
[rank0]:   File "/envs/my_env/lib/python3.10/queue.py", line 180, in get
[rank0]:     self.not_empty.wait(remaining)
[rank0]:   File "/envs/my_env/lib/python3.10/threading.py", line 324, in wait
[rank0]:     gotit = waiter.acquire(True, timeout)
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
[rank0]:     _error_if_any_worker_fails()
[rank0]: RuntimeError: DataLoader worker (pid 3349014) is killed by signal: Terminated. 

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File ".config/Ultralytics/DDP/_temp_wiuhsqe7139481954782128.py", line 13, in <module>
[rank0]:     results = trainer.train()
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
[rank0]:     self._do_train(world_size)
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 367, in _do_train
[rank0]:     for i, batch in pbar:
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
[rank0]:     for obj in iterable:
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/ultralytics/data/build.py", line 48, in __iter__
[rank0]:     yield next(self.iterator)
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
[rank0]:     idx, data = self._get_data()
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1285, in _get_data
[rank0]:     success, data = self._try_get_data()
[rank0]:   File "/envs/my_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1146, in _try_get_data
[rank0]:     raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
[rank0]: RuntimeError: DataLoader worker (pid(s) 3349014) exited unexpectedly

Exception ignored in atexit callback: <function _exit_function at 0x71eb675300d0>
Traceback (most recent call last):
  File "/envs/my_env/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/envs/my_env/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/envs/my_env/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/envs/my_env/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/envs/my_env/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()

RuntimeError: DataLoader worker (pid 3350244) is killed by signal: Terminated. 
E1202 10:10:42.330000 136385142073152 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -9) local_rank: 1 (pid: 3348903) of binary: /envs/my_env/bin/python
Traceback (most recent call last):
  File "/envs/my_env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/envs/my_env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/envs/my_env/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in <module>
    main()
  File "/envs/my_env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/envs/my_env/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/envs/my_env/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/envs/my_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/envs/my_env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
.config/Ultralytics/DDP/_temp_wiuhsqe7139481954782128.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-02_10:10:39
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 3348903)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 3348903

```
