### ISSUE TITLE
Error while training on a dataset that I have trained earlier

### ISSUE THREAD

**Issue by prajsri99** [ultralytics/ultralytics#16471]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
Below is a error that I am encountering while training a segmentation model. I have trained the model earlier and it trained fine without any errors. Now, when I added images and respective labels and trained again from the previous last.pt file, I am encountering the below error. Could you please help me with that?

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 394, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 370, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 306, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 706, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 220, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/augment.py", line 56, in __call__
    data = t(data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/augment.py", line 615, in __call__
    new = self.transform(image=im, bboxes=bboxes, class_labels=cls)  # transformed
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 334, in __call__
    self.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 368, in preprocess
    p.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 125, in preprocess
    data = self.add_label_fields_to_data(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 185, in add_label_fields_to_data
    encoded_labels = encoder.fit_transform(data[label_field])
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 60, in fit_transform
    self.fit(y)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 48, in fit
    unique_labels = sorted(set(y))
TypeError: unhashable type: 'numpy.ndarray'

Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by UltralyticsAssistant** [comment]
👋 Hello @prajsri99, thank you for reaching out and for using Ultralytics 🚀!

It seems you're encountering an error while retraining your segmentation model. Let's get it sorted out! If this is a 🐛 Bug Report, please include a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us diagnose the issue effectively.

In the meantime, ensure you've upgraded to the latest version of Ultralytics with:

```bash
pip install -U ultralytics
```

This will make sure your issue isn't due to an already resolved bug.

If you're diving into custom training ❓, providing additional details such as dataset image examples and training logs could be very helpful. Also, double-check that you're following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Explore solutions within our supportive community:
- Get real-time assistance on [Discord](https://ultralytics.com/discord) 🎧.
- Engage in more detailed discussions on [Discourse](https://community.ultralytics.com).
- Explore or share insights with fellow users on our [Subreddit](https://reddit.com/r/ultralytics).

This is an automated response, but no worries, an Ultralytics engineer will review your issue soon.

Thank you for your patience and happy training! 🌟

**Comment by Y-T-G** [comment]
Post the training code and also check the training logs to see if there are any warnings. Delete the `labels.cache` file inside the `train` and `val` folders of your dataset.

**Comment by ZYF-fmg** [comment]
I also met the same question, after I added new images and labels in my own datasets. I deleted the added images and labels, then the model can be trained. After ensuring that the images and labels correspond one-to-one, I added them into my dataset. And the question didn't occur again.

**Comment by glenn-jocher** [comment]
It sounds like the issue was due to mismatched images and labels. Ensuring they correspond one-to-one is crucial for successful training. If you encounter further issues, feel free to reach out.

**Comment by prajsri99** [comment]
I checked the images and labels and they were fine. I upgraded the ultralytics version from 8.0.98 to 8.2.101 and it worked fine and trained. So I have 3 models out of which 2 are performing well after upgrading and updating. Now I upgraded ultralytics and trained another 3rd model, it got trained but the performance has decreased which means the detection is not happening as to how it was happening with the previous weight file. Can you help me with this as to why this is happening? I am unable to understand the reason behind this

**Comment by glenn-jocher** [comment]
It sounds like the model's performance might be affected by changes in hyperparameters or dataset variations. Consider reviewing your training settings and dataset consistency. If the issue persists, experimenting with different hyperparameters or reverting to previous settings could help.

**Comment by prajsri99** [comment]
This is the previous training settings. I got this from the args.yaml file after training.
task: segment
mode: train
model: /content/drive/MyDrive/CEAT_2024/runs/segment/train3/weights/last.pt
data: /content/drive/MyDrive/CEAT_2024/data.yaml
epochs: 50
patience: 0
batch: 16
imgsz: 1024
save: true
save_period: -1
cache: false
device: 0
workers: 8
project: null
name: null
exist_ok: false
pretrained: false
optimizer: Adam
verbose: true
seed: 0
deterministic: true
single_cls: false
rect: false
cos_lr: false
close_mosaic: 0
resume: false
amp: true
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
show: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
vid_stride: 1
line_width: null
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
boxes: true
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
cfg: null
v5loader: false
tracker: botsort.yaml
save_dir: runs/segment/train4

This is the args.yaml file that I have trained recently after upgrading ultralytics.
task: segment
mode: train
model: /content/drive/MyDrive/CEAT_2024/runs/segment/train4/weights/last.pt
data: /content/drive/MyDrive/CEAT_2024/runs/data.yaml
epochs: 50
time: null
patience: 0
batch: 16
imgsz: 1024
save: true
save_period: -1
cache: false
device: 0
workers: 8
project: /content/drive/MyDrive/CEAT_2024/runs/segment
name: train5
exist_ok: false
pretrained: true
optimizer: Adam
verbose: true
seed: 0
deterministic: true
single_cls: false
rect: false
cos_lr: false
close_mosaic: 10
resume: false
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
vid_stride: 1
stream_buffer: false
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
embed: null
show: false
save_frames: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
show_boxes: true
line_width: null
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: true
opset: null
workspace: 4
nms: false
lr0: 0.0001
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
cfg: null
tracker: botsort.yaml
save_dir: /content/drive/MyDrive/CEAT_2024/runs/segment/train5

**Comment by prajsri99** [comment]
Can I train without upgrading the ultralytics version from 8.0.98? When I try training with 8.0.98 version, it throws an error as what I had posted in the beginning of this discussion

**Comment by prajsri99** [comment]
But when I am installing 8.0.98 and training, why is it throwing the below
error?

Navigation Menu

Code
Issues
916
Jump to bottom
Error while training on a dataset that I have trained earlier #16471
Open
1 task done
prajsri99 opened this issue last week · 9 comments
Open
1 task done
Error while training on a dataset that I have trained earlier
#16471
prajsri99 opened this issue last week · 9 comments
Labels
question
segment
Comments
prajsri99 commented last week
Search before asking
I have searched the Ultralytics YOLO issues and discussions and found no
similar questions.
Question
Hi,
Below is a error that I am encountering while training a segmentation
model. I have trained the model earlier and it trained fine without any
errors. Now, when I added images and respective labels and trained again
from the previous last.pt file, I am encountering the below error. Could
you please help me with that?

Traceback (most recent call last):
File "/usr/local/bin/yolo", line 8, in
sys.exit(entrypoint())
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/init.py",
line 394, in entrypoint
getattr(model, mode)(**overrides) # default args from model
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py",
line 370, in train
self.trainer.train()
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py",
line 191, in train
self._do_train(world_size)
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py",
line 306, in _do_train
for i, batch in pbar:
File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in
iter
for obj in iterable:
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/build.py",
line 38, in iter
yield next(self.iterator)
File
"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py",
line 630, in next
data = self._next_data()
File
"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py",
line 1344, in _next_data
return self._process_data(data)
File
"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py",
line 1370, in _process_data
data.reraise()
File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 706,
in reraise
raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File
"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py",
line 309, in _worker_loop
data = fetcher.fetch(index) # type: ignore[possibly-undefined]
File
"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py",
line 52, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File
"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py",
line 52, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py",
line 220, in getitem
return self.transforms(self.get_label_info(index))
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/augment.py",
line 56, in call
data = t(data)
File
"/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/augment.py",
line 615, in call
new = self.transform(image=im, bboxes=bboxes, class_labels=cls) #
transformed
File
"/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py",
line 334, in call
self.preprocess(data)
File
"/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py",
line 368, in preprocess
p.preprocess(data)
File
"/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py",
line 125, in preprocess
data = self.add_label_fields_to_data(data)
File
"/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py",
line 185, in add_label_fields_to_data
encoded_labels = encoder.fit_transform(data[label_field])
File
"/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py",
line 60, in fit_transform
self.fit(y)
File
"/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py",
line 48, in fit
unique_labels = sorted(set(y))
TypeError: unhashable type: 'numpy.ndarray'

Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

There is no problem with the dataset. I have checked that as well.

**Comment by prajsri99** [comment]
pip install ultralytics==8.0.98
Collecting ultralytics==8.0.98
  Downloading ultralytics-8.0.98-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (3.7.1)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (4.10.0.84)
Requirement already satisfied: Pillow>=7.1.2 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (10.4.0)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (1.13.1)
Requirement already satisfied: torch>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (2.4.1+cu121)
Requirement already satisfied: torchvision>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (0.19.1+cu121)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (4.66.5)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (2.1.4)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (0.13.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ultralytics==8.0.98) (5.9.5)
Collecting thop>=0.1.1 (from ultralytics==8.0.98)
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Collecting sentry-sdk (from ultralytics==8.0.98)
  Downloading sentry_sdk-2.14.0-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (1.4.7)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.2.2->ultralytics==8.0.98) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->ultralytics==8.0.98) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->ultralytics==8.0.98) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics==8.0.98) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics==8.0.98) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics==8.0.98) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics==8.0.98) (2024.8.30)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics==8.0.98) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics==8.0.98) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics==8.0.98) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics==8.0.98) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics==8.0.98) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.7.0->ultralytics==8.0.98) (2024.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->ultralytics==8.0.98) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.7.0->ultralytics==8.0.98) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.7.0->ultralytics==8.0.98) (1.3.0)
Downloading ultralytics-8.0.98-py3-none-any.whl (584 kB)
[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m584.2/584.2 kB[0m [31m34.3 MB/s[0m eta [36m0:00:00[0m
[?25hDownloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Downloading sentry_sdk-2.14.0-py2.py3-none-any.whl (311 kB)
[2K   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m311.4/311.4 kB[0m [31m27.6 MB/s[0m eta [36m0:00:00[0m
[?25hInstalling collected packages: sentry-sdk, thop, ultralytics
Successfully installed sentry-sdk-2.14.0 thop-0.1.1.post2209072238 ultralytics-8.0.98

These are the dependencies that have been installed as well

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to compatibility between the dataset and the version you're using. Ensure your dataset format aligns with the requirements for version 8.0.98. If the error persists, upgrading to the latest version is recommended for improved stability and support.

**Comment by prajsri99** [comment]
Dataset compatibility should not be a problem as I last trained this model
a few months back using 8.0.98 and then I again wanted to retrain but I am
not able to.
I have upgrade the version and now the mask precision,recall,
map50,map50-95 and val/seg_loss metrics has dropped down to zero and nan

**Comment by glenn-jocher** [comment]
@prajsri99 it sounds like there might be an issue with the dataset or training configuration after upgrading. Please ensure your dataset is correctly formatted and consider re-evaluating your training settings. If the problem persists, using the latest version with updated dependencies is advisable.
