### ISSUE TITLE
Can't use ultralytics with bazel because of the jaraco.text dependency

### ISSUE THREAD

**Issue by leah-at-lovelace** [ultralytics/ultralytics#16473]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

I'm trying to use Bazel to manage my dependencies, and currently unable to incorporate Ultralytics because of a jaraco.text/setuptools conflict. The main error is `FileNotFoundError: [Errno 2] No such file or directory: '/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/setuptools/_vendor/jaraco/text/Lorem ipsum.txt'`. This seems to be a known problem with bazel not playing well with files with spaces in them. This [setuptools issue](https://github.com/pypa/setuptools/issues/3072) has a more complete discussion. I realize this isn't really the fault of the Ultralytics package, but I wonder if there's a minor change you could make to eliminate the problem, or if anyone else has hit this and found a workaround.

Full trace:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/PATH/.config/Ultralytics/DDP/_temp_88sk_l2t140515615497120.py", line 13, in <module>
[rank0]:     results = trainer.train()
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
[rank0]:     self._do_train(world_size)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
[rank0]:     self._setup_train(world_size)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 264, in _setup_train
[rank0]:     self.amp = torch.tensor(check_amp(self.model), device=self.device)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 673, in check_amp
[rank0]:     assert amp_allclose(YOLO("yolov8n.pt"), im)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 660, in amp_allclose
[rank0]:     a = m(batch, imgsz=128, device=device, verbose=False)[0].boxes.data  # FP32 inference
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 176, in __call__
[rank0]:     return self.predict(source, stream, **kwargs)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 567, in predict
[rank0]:     return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
[rank0]:     return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
[rank0]:     response = gen.send(None)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 234, in stream_inference
[rank0]:     self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 633, in warmup
[rank0]:     import torchvision  # noqa (import here so torchvision import time not recorded in postprocess time)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torchvision/__init__.py", line 10, in <module>
[rank0]:     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>
[rank0]:     from .convnext import *
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>
[rank0]:     from ..ops.misc import Conv2dNormActivation, Permute
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 23, in <module>
[rank0]:     from .poolers import MultiScaleRoIAlign
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torchvision/ops/poolers.py", line 10, in <module>
[rank0]:     from .roi_align import roi_align
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torchvision/ops/roi_align.py", line 7, in <module>
[rank0]:     from torch._dynamo.utils import is_compile_supported
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
[rank0]:     from . import convert_frame, eval_frame, resume_execution
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 48, in <module>
[rank0]:     from . import config, exc, trace_rules
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 12, in <module>
[rank0]:     from .utils import counters
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1063, in <module>
[rank0]:     if has_triton_package():
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/torch/utils/_triton.py", line 9, in has_triton_package
[rank0]:     import triton
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/__init__.py", line 8, in <module>
[rank0]:     from .runtime import (
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/runtime/__init__.py", line 1, in <module>
[rank0]:     from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 9, in <module>
[rank0]:     from ..testing import do_bench, do_bench_cudagraph
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/testing.py", line 7, in <module>
[rank0]:     from . import language as tl
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/language/__init__.py", line 4, in <module>
[rank0]:     from . import math
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/language/math.py", line 1, in <module>
[rank0]:     from . import core
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/language/core.py", line 10, in <module>
[rank0]:     from ..runtime.jit import jit
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/runtime/jit.py", line 12, in <module>
[rank0]:     from ..runtime.driver import driver
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/runtime/driver.py", line 1, in <module>
[rank0]:     from ..backends import backends
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/backends/__init__.py", line 50, in <module>
[rank0]:     backends = _discover_backends()
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/backends/__init__.py", line 44, in _discover_backends
[rank0]:     driver = _load_module(name, os.path.join(root, name, 'driver.py'))
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/backends/__init__.py", line 12, in _load_module
[rank0]:     spec.loader.exec_module(module)
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 7, in <module>
[rank0]:     from triton.runtime.build import _build
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/triton/runtime/build.py", line 8, in <module>
[rank0]:     import setuptools
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 27, in <module>
[rank0]:     from .dist import Distribution
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/setuptools/dist.py", line 18, in <module>
[rank0]:     from . import (
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/setuptools/_entry_points.py", line 6, in <module>
[rank0]:     from jaraco.text import yield_lines
[rank0]:   File "/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 231, in <module>
[rank0]:     files(__name__).joinpath('Lorem ipsum.txt').read_text(encoding='utf-8')
[rank0]:   File "/PATH/.cache/bazel/_bazel_user/c1ed43d4bcd5a3ccb9dd5d020cf0c85c/external/rules_python~~python~python_3_10_x86_64-unknown-linux-gnu/lib/python3.10/pathlib.py", line 1134, in read_text
[rank0]:     with self.open(mode='r', encoding=encoding, errors=errors) as f:
[rank0]:   File "/PATH/.cache/bazel/_bazel_user/c1ed43d4bcd5a3ccb9dd5d020cf0c85c/external/rules_python~~python~python_3_10_x86_64-unknown-linux-gnu/lib/python3.10/pathlib.py", line 1119, in open
[rank0]:     return self._accessor.open(self, mode, buffering, encoding, errors,
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: '/PATH/bazel-out/k8-fastbuild/bin/driver/dispatch.runfiles/.dispatch.venv/lib/python3.10/site-packages/setuptools/_vendor/jaraco/text/Lorem ipsum.txt'
```

### Environment

`Ultralytics YOLOv8.2.99 🚀 Python-3.10.8 torch-2.4.1+cu121 CUDA:0 (NVIDIA RTX 6000 Ada Generation, 45586MiB)
Setup complete ✅ (96 CPUs, 503.7 GB RAM, 481.9/867.3 GB disk)`

### Minimal Reproducible Example

Simple model training code runs, but trying to run it with bazel fails.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @leah-at-lovelace, thanks for reaching out and sharing your issue with Ultralytics 🚀! This is an automated response, but please rest assured that an Ultralytics engineer will also assist you soon. 😊

For now, here are some things you can try or provide to help us address the issue:

1. **Bug Report Details** 🐛: If this is a bug report, we recommend providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug the issue.

2. **Documentation** 📚: If you're unfamiliar with Ultralytics, visiting the [Docs](https://docs.ultralytics.com) could be beneficial. You'll find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples there.

3. **Community Support** 💬: Join the Ultralytics community for more interactive discussions:
   - [Discord](https://ultralytics.com/discord) 🎧 for real-time chat.
   - [Discourse](https://community.ultralytics.com) for in-depth exchanges.
   - [Subreddit](https://reddit.com/r/ultralytics) for community knowledge sharing.

4. **Upgrade Instructions** 🔄: Please ensure you are using the latest version of the `ultralytics` package with all requirements met in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

   ```bash
   pip install -U ultralytics
   ```

5. **Verified Environments** 🌐: YOLOv8 can be run in the following environments, which are pre-configured with the necessary dependencies:
   - Notebooks with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
   - Google Cloud, Amazon AMI, and Docker: Check our detailed guides in the docs.

6. **Current Status** ✅: 
   <a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>
   This badge reflects the CI status. All tests verify correct operations across various platforms every 24 hours and on every commit.

Thank you again for your interest and support. If you have any additional information or a workaround to share, please do so. We'll get back to you with more details shortly! 🚀

**Comment by glenn-jocher** [comment]
@leah-at-lovelace thank you for bringing this to our attention. Unfortunately, we cannot make changes to third-party dependencies like `jaraco.text`. You might consider reaching out to the Bazel community for potential workarounds or exploring alternative dependency management solutions.
