### ISSUE TITLE
No result.png is generated after training, and it cannot be validated with the trained best.pt

### ISSUE THREAD

**Issue by qingchengleiqing** [ultralytics/ultralytics#16484]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

No result.png is generated after training, and it cannot be validated with the trained best.pt
Error：
300 epochs completed in 3.788 hours.
WARNING ⚠️ Skipping runs/train/yolov8-FreqFFPN-300/weights/last.pt, not a valid Ultralytics model: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>
WARNING ⚠️ Skipping runs/train/yolov8-FreqFFPN-300/weights/best.pt, not a valid Ultralytics model: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>

Validating runs/train/yolov8-FreqFFPN-300/weights/best.pt...
Ultralytics YOLOv8.2.50 🚀 Python-3.9.19 torch-2.2.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 10002MiB)
Traceback (most recent call last):
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/train.py", line 36, in <module>
    model.train(data='/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/dataset24-09-20/data.yaml',
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/model.py", line 650, in train
    self.trainer.train()
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/trainer.py", line 205, in train
    self._do_train(world_size)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/trainer.py", line 474, in _do_train
    self.final_eval()
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/trainer.py", line 671, in final_eval
    self.metrics = self.validator(model=f)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/validator.py", line 125, in __call__
    model = AutoBackend(
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/autobackend.py", line 157, in __init__
    model = attempt_load_weights(
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 911, in attempt_load_weights
    ckpt, w = torch_safe_load(w)  # load ckpt
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 873, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>
(myolo) root@autodl-container-97b611a952-993ff2b3:~/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20# python val.py
Traceback (most recent call last):
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/val.py", line 27, in <module>
    model = YOLO('/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/train/yolov8-FreqFFPN-300/weights/best.pt')
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/model.py", line 149, in __init__
    self._load(model, task=task)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 947, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 873, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>

**Comment by UltralyticsAssistant** [comment]
👋 Hello @qingchengleiqing, thank you for bringing this to our attention! 🚀

It looks like you're encountering an issue with model validation after training. If this is a 🐛 Bug Report, we kindly ask you to provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us accurately diagnose the problem.

In the meantime, please ensure your development environment is up to date. Upgrade to the latest `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment using:

```bash
pip install -U ultralytics
```

You can also check our [YOLOv8 Environment Guide](https://docs.ultralytics.com/yolov5/environments/) to verify your setup.

For further assistance, you might want to:
- Visit our [Docs](https://docs.ultralytics.com) for guidance, and check out [Python Usage](https://docs.ultralytics.com/usage/python/) and [CLI Usage](https://docs.ultralytics.com/usage/cli/) sections.
- Join discussions on [Discord](https://ultralytics.com/discord) 🎧, [Discourse](https://community.ultralytics.com), or our [Subreddit](https://reddit.com/r/ultralytics).

This is an automated response, and an Ultralytics engineer will also assist you soon. Thank you for your patience! 😊

**Comment by qingchengleiqing** [comment]
import torch

from ultralytics import YOLO

# Load the model
model = YOLO("/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/train/yolov8-FreqFFPN-300/weights/best.pt")

# Load a 0-channel image
image = torch.rand(1, 0, 640, 640)

# Run the model
results = model(image)


(myolo) root@autodl-container-97b611a952-993ff2b3:~/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20# python /root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/ceshi.py
Traceback (most recent call last):
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/ceshi.py", line 6, in <module>
    model = YOLO("/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/train/yolov8-FreqFFPN-300/weights/best.pt")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/engine/model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>

**Comment by Y-T-G** [comment]
It's a problem with your custom model. Not related to ultraltytics.

**Comment by qingchengleiqing** [comment]
Do you mean it's due to the structure of the model you define? If so, why don't you make mistakes during training? Could it be due to the environment?

**Comment by Y-T-G** [comment]
It's similar to this 

https://github.com/ultralytics/ultralytics/issues/16443#issue-2543105115
