### ISSUE TITLE
No result.png is generated after training, and it cannot be validated with the trained best.pt

### ISSUE THREAD

**Issue by qingchengleiqing** [ultralytics/ultralytics#16486]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Error：
300 epochs completed in 3.788 hours.
WARNING ⚠️ Skipping runs/train/yolov8-FreqFFPN-300/weights/last.pt, not a valid Ultralytics model: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>
WARNING ⚠️ Skipping runs/train/yolov8-FreqFFPN-300/weights/best.pt, not a valid Ultralytics model: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>

Validating runs/train/yolov8-FreqFFPN-300/weights/best.pt...
Ultralytics YOLOv8.2.50 🚀 Python-3.9.19 torch-2.2.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 10002MiB)
Traceback (most recent call last):
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/train.py", line 36, in <module>
    model.train(data='/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/dataset24-09-20/data.yaml',
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/model.py", line 650, in train
    self.trainer.train()
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/trainer.py", line 205, in train
    self._do_train(world_size)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/trainer.py", line 474, in _do_train
    self.final_eval()
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/trainer.py", line 671, in final_eval
    self.metrics = self.validator(model=f)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/validator.py", line 125, in __call__
    model = AutoBackend(
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/autobackend.py", line 157, in __init__
    model = attempt_load_weights(
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 911, in attempt_load_weights
    ckpt, w = torch_safe_load(w)  # load ckpt
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 873, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>
(myolo) root@autodl-container-97b611a952-993ff2b3:~/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20# python val.py
Traceback (most recent call last):
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/val.py", line 27, in <module>
    model = YOLO('/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/train/yolov8-FreqFFPN-300/weights/best.pt')
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/model.py", line 149, in __init__
    self._load(model, task=task)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/engine/model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 947, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/ultralytics/nn/tasks.py", line 873, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>

yolov8 environment:
python: 3.9.19
torch: 2.2.2+cu121
torchvision: 0.17.2+cu121
timm: 1.0.7
mmcv: 2.2.0
mmengine: 0.10.4
GPU   RTX 3080(10GB) * 1

**Comment by UltralyticsAssistant** [comment]
👋 Hello @qingchengleiqing, thank you for reaching out and for using Ultralytics 🚀! This is an automated response to assist you while an Ultralytics engineer reviews your issue.

From your description, it seems you're having trouble generating `result.png` and encountering validation errors with your model. Here are some steps and resources that might help:

### For 🐛 Bug Reports
Please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that demonstrates the issue. This will greatly assist us in diagnosing and resolving the problem.

### Troubleshooting
- Make sure you are using the latest version of the `ultralytics` package. You can upgrade with the following command:

  ```bash
  pip install -U ultralytics
  ```

- Double-check that all your dependencies are up-to-date using both [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/get-started/locally/).

### Environment Setup
- Try running your training and validation in one of our verified environments:
  - **Notebooks**: <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
  - **Docker**: See our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)

### Community and Support
Feel free to engage with our community:
- [Discord](https://ultralytics.com/discord) 🎧 for real-time chat.
- [Discourse](https://community.ultralytics.com) for in-depth discussions.
- [Subreddit](https://reddit.com/r/ultralytics) for community knowledge sharing.

We hope these resources help you navigate your issue, and an engineer will be in touch soon to provide further assistance. Thank you for your patience! 😊

**Comment by ambitious-octopus** [comment]
Duplicate, closing in favor of #16484

**Comment by qingchengleiqing** [comment]
import torch

from ultralytics import YOLO

# Load the model
model = YOLO("/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/train/yolov8-FreqFFPN-300/weights/best.pt")

# Load a 0-channel image
image = torch.rand(1, 0, 640, 640)

# Run the model
results = model(image)




moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/ceshi.py
Traceback (most recent call last):
  File "/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/ceshi.py", line 6, in <module>
    model = YOLO("/root/autodl-tmp/moguiyolo/road-24-09-20/ultralytics-main-24-09-20/runs/train/yolov8-FreqFFPN-300/weights/best.pt")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/engine/model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/myolo/lib/python3.9/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>
>

**Comment by glenn-jocher** [comment]
It seems you're encountering an issue with loading the model. The error suggests a problem with the model file. Please ensure the `
