### ISSUE TITLE
Error when training a YOLO detection model 

### ISSUE THREAD

**Issue by TanJingXuan-06** [ultralytics/ultralytics#16509]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I've actually found a similar issue however I'm still unable to solve it. The error I'm getting is: 
Transferred 349/355 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.001), 63 bias
train: Scanning /content/drive/MyDrive/4078/YoloV8/data/train/labels... 400 images, 0 backgrounds, 0 corrupt: 100% 400/400 [04:35<00:00,  1.45it/s]
train: New cache created: /content/drive/MyDrive/4078/YoloV8/data/train/labels.cache
/usr/local/lib/python3.10/dist-packages/albumentations/__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.16 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py:191: UserWarning: Got processor for bboxes, but no transform to process it.
  self._set_keys()
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /content/drive/MyDrive/4078/YoloV8/data/val/labels... 50 images, 0 backgrounds, 0 corrupt: 100% 50/50 [00:50<00:00,  1.02s/it]
val: New cache created: /content/drive/MyDrive/4078/YoloV8/data/val/labels.cache
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/detect/train9
Starting training for 25 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0% 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 249, in entrypoint
    getattr(model, mode)(verbose=True, **overrides)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 207, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 183, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 284, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 706, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 180, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/augment.py", line 48, in __call__
    data = t(data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/augment.py", line 569, in __call__
    new = self.transform(image=im, bboxes=bboxes, class_labels=cls)  # transformed
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 334, in __call__
    self.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 368, in preprocess
    p.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 125, in preprocess
    data = self.add_label_fields_to_data(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 185, in add_label_fields_to_data
    encoded_labels = encoder.fit_transform(data[label_field])
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 60, in fit_transform
    self.fit(y)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/utils.py", line 48, in fit
    unique_labels = sorted(set(y))
TypeError: unhashable type: 'numpy.ndarray'

Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

The code that I'm using is directly copied from a YouTuber. This is the code: 
[ObjectDetection.ipynb - Colab.pdf](https://github.com/user-attachments/files/17161428/ObjectDetection.ipynb.-.Colab.pdf)

Can anyone help? Thanks a lot !

**Comment by UltralyticsAssistant** [comment]
👋 Hello @TanJingXuan-06, thank you for sharing your issue with Ultralytics 🚀! This is an automated response. An Ultralytics engineer will assist you soon.

We recommend checking our [Docs](https://docs.ultralytics.com) for usage examples, especially if you're new to the platform. For both [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/), you might find many answers already there.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us simulate and understand your issue.

If your inquiry is a custom training ❓ Question, could you share more information? This includes dataset samples and detailed training logs. Ensure you're following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Feel free to join our community channels! For real-time support, check our [Discord](https://ultralytics.com/discord) 🎧. For discussions and in-depth queries, [Discourse](https://community.ultralytics.com) and our [Subreddit](https://reddit.com/r/ultralytics) are great places to connect with other users.

## Upgrade

Ensure you're on the latest version by upgrading the `ultralytics` package and all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

You can try running YOLOv8 in any of these verified environments, which are preconfigured with all necessary dependencies including [CUDA](https://developer.nvidia.com/cuda), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. Our [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/) can help
- **Docker Image**. Follow our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all our [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing. Our CI checks ensure that YOLOv8 [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) run smoothly on macOS, Windows, and Ubuntu every 24 hours and with every commit. 

Thank you for your patience! 😊

**Comment by Y-T-G** [comment]
That's a really old version of ultralytics.

Update it:
pip install -U ultralytics

**Comment by TanJingXuan-06** [comment]
Omg thank you so much! It works ! 
![image](https://github.com/user-attachments/assets/898a29aa-9620-4ba0-8bed-64355402cc30)
