### ISSUE TITLE
Does this code correctly implement the post-processing of the YOLOv8n pose model?

### ISSUE THREAD

**Issue by CGAAG** [ultralytics/ultralytics#16516]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on running the YOLOv8n pose model on a Khadas VIM3 board. The environment I am using includes:

torch==1.8.0
torchvision==0.9.0
numpy==1.21.6
onnx==1.8.0
ultralytics==8.0.86
In this environment, I modified the modules and task files to output all outputs from each grid (1, 116, 80, 80 / 1, 116, 40, 40 / 1, 116, 20, 20) and converted them to ONNX. I then used a tool called aml_npu_sdk to convert the model for execution in the NPU environment of the Khadas VIM3 board. I am now working on implementing the post-processing of the model, which was omitted during the ONNX conversion, but I lack sufficient understanding of the model and need some advice.
This code was written by me.
```

import numpy as np
import cv2 as cv
from ksnn.api import KSNN
from ksnn.types import output_format

# Constants
GRID0, GRID1, GRID2 = 80, 40, 20  # Grid sizes for each output
LISTSIZE = 116
NUM_POINTS = 17  # Number of keypoints
IMG_SIZE = 640  # Input image size for the model
THRESHOLD = 0.5  # Confidence threshold for keypoints
NUM_CLS = 1  # Adjust the number of classes for the model

# COCO format keypoint connections (Skeleton structure)
SKELETON = [
    [0, 1], [0, 2], [1, 3], [2, 4],       # Face connections
    [5, 6],                               # Shoulders connection
    [5, 7], [7, 9], [6, 8], [8, 10],      # Arm connections
    [11, 12],                             # Hip connection
    [11, 13], [13, 15], [12, 14], [14, 16] # Leg connections
]

# Function to preprocess the input image
def preprocess_image(image_path):
    orig_img = cv.imread(image_path)  # Read the original image
    img = cv.resize(orig_img, (IMG_SIZE, IMG_SIZE)).astype(np.float32)  # Resize and change data type
    img = img / 255.0  # Normalize the image (scale between 0 and 1)
    img = img.transpose(2, 0, 1)  # Convert the image to NCHW format (Channel-first)

    print(f'Original image shape: {orig_img.shape}')
    print(f'Processed image shape: {img.shape}, dtype: {img.dtype}')
    return orig_img, img  # Return the original and preprocessed images

# Sigmoid function (to compress values between 0 and 1)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Softmax function (for calculating class probabilities)
def softmax(x, axis=-1):
    x = np.exp(x)
    return x / x.sum(axis=axis, keepdims=True)

# Function to decode the boxes and keypoints from the model output
def decode_boxes_and_keypoints(outputs, orig_img):
    # Reshape each output array into the correct format
    input0_data = np.array(outputs[0]).reshape((1, LISTSIZE, GRID0, GRID0))
    input1_data = np.array(outputs[1]).reshape((1, LISTSIZE, GRID1, GRID1))
    input2_data = np.array(outputs[2]).reshape((1, LISTSIZE, GRID2, GRID2))

    input_data = [
        np.transpose(input0_data, (2, 3, 0, 1)),  # First output
        np.transpose(input1_data, (2, 3, 0, 1)),  # Second output
        np.transpose(input2_data, (2, 3, 0, 1))   # Third output
    ]

    strides = [IMG_SIZE / GRID0, IMG_SIZE / GRID1, IMG_SIZE / GRID2]  # Strides corresponding to each grid size
    box_keypoints_pairs = []  # List to store box and keypoint pairs

    # Iterate over each grid cell to decode boxes and keypoints
    for idx, data in enumerate(input_data):
        stride_x = stride_y = strides[idx]
        for grid_y in range(data.shape[0]):
            for grid_x in range(data.shape[1]):
                box_conf = sigmoid(data[grid_y, grid_x, 0, 0])  # Confidence score for the box
                if box_conf < THRESHOLD:
                    continue

                # Calculate the bounding box coordinates
                box_0 = softmax(data[grid_y, grid_x, 0, NUM_CLS: NUM_CLS + 16], -1)
                box_1 = softmax(data[grid_y, grid_x, 0, NUM_CLS + 16:NUM_CLS + 32], -1)
                box_2 = softmax(data[grid_y, grid_x, 0, NUM_CLS + 32:NUM_CLS + 48], -1)
                box_3 = softmax(data[grid_y, grid_x, 0, NUM_CLS + 48:NUM_CLS + 64], -1)

                constant_matrix = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]]).T
                result_xmin = np.dot(box_0, constant_matrix)
                result_ymin = np.dot(box_1, constant_matrix)
                result_xmax = np.dot(box_2, constant_matrix)
                result_ymax = np.dot(box_3, constant_matrix)

                xmin = (0.5 - result_xmin + grid_x) / stride_x
                ymin = (0.5 - result_ymin + grid_y) / stride_y
                xmax = (0.5 + result_xmax + grid_x) / stride_x
                ymax = (0.5 + result_ymax + grid_y) / stride_y
                box = [xmin, ymin, xmax, ymax, box_conf]  # Save the bounding box coordinates

                # Decode the keypoints
                kpts = data[grid_y, grid_x, 0, 65:116].reshape((17, 3))  # Extract keypoint data
                keypoints = []
                for kp_x, kp_y, conf in kpts:
                    kp_x = (2 * kp_x + grid_x) * stride_x / IMG_SIZE * orig_img.shape[1]  # Transform x coordinate
                    kp_y = (2 * kp_y + grid_y) * stride_y / IMG_SIZE * orig_img.shape[0]  # Transform y coordinate
                    conf = sigmoid(conf)  # Apply confidence value
                    keypoints.append((kp_x, kp_y, conf))  # Save keypoint

                # Save the box and keypoint pair
                box_keypoints_pairs.append((box, keypoints))

    return box_keypoints_pairs  # Return box and keypoint pairs

# Non-Maximum Suppression (NMS) function to filter out overlapping boxes
def nms(box_keypoints_pairs, threshold):
    box_keypoints_pairs = sorted(box_keypoints_pairs, key=lambda x: x[0][4], reverse=True)  # Sort by box confidence score
    final_pairs = []
    
    while box_keypoints_pairs:
        best_pair = box_keypoints_pairs.pop(0)  # Select the box with the highest confidence
        final_pairs.append(best_pair)
        box_keypoints_pairs = [pair for pair in box_keypoints_pairs if iou(best_pair[0], pair[0]) < threshold]  # Remove overlapping boxes
    
    return final_pairs  # Return the final selected boxes and keypoints

# Function to compute the Intersection over Union (IoU) between two boxes
def iou(box1, box2):
    x1, y1, w1, h1 = box1[:4]
    x2, y2, w2, h2 = box2[:4]

    inter_x1 = max(x1, x2)  # x coordinate of the top-left corner of the intersection
    inter_y1 = max(y1, y2)  # y coordinate of the top-left corner of the intersection
    inter_x2 = min(x1 + w1, x2 + w2)  # x coordinate of the bottom-right corner of the intersection
    inter_y2 = min(y1 + h1, y2 + h2)  # y coordinate of the bottom-right corner of the intersection

    inter_area = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)  # Calculate the intersection area
    box1_area = w1 * h1  # Area of the first box
    box2_area = w2 * h2  # Area of the second box

    iou_value = inter_area / (box1_area + box2_area - inter_area)  # Calculate IoU value
    return iou_value  # Return the IoU value

# Post-processing function to draw boxes, keypoints, and skeleton
def postprocess_output(outputs, orig_img):
    box_keypoints_pairs = decode_boxes_and_keypoints(outputs, orig_img)
    final_pairs = nms(box_keypoints_pairs, 0.5)  # Apply NMS

    # Draw keypoints and skeleton
    for box, keypoints in final_pairs:
        # Draw keypoints
        for x, y, conf in keypoints:
            if conf > THRESHOLD:  # Only draw keypoints with confidence greater than the threshold
                cv.circle(orig_img, (int(x), int(y)), 3, (0, 255, 0), -1)

        # Draw skeleton
        for joint in SKELETON:
            pt1 = keypoints[joint[0]]
            pt2 = keypoints[joint[1]]
            if pt1[2] > THRESHOLD and pt2[2] > THRESHOLD:  # Only connect points with high confidence
                cv.line(orig_img, (int(pt1[0]), int(pt1[1])), (int(pt2[0]), int(pt2[1])), (0, 255, 0), 2)

    return orig_img  # Return the processed image

# Function to run the model
def run_model(library_path, model_path, image_path):
    model = KSNN('VIM3')
    model.nn_init(library=library_path, model=model_path, level=1)  # Initialize the model

    orig_img, img = preprocess_image(image_path)  # Preprocess the image

    img = [img]  # Prepare input image array

    # Run inference with nn_inference
    outputs = model.nn_inference(img, platform='ONNX', reorder='2 1 0', input_tensor=1, output_tensor=3, output_format=output_format.OUT_FORMAT_FLOAT32)

    result_img = postprocess_output(outputs, orig_img)  # Post-process the inference results
    output_path = "/home/khadas/test/result_pose.jpg"  # Path to save the result image
    cv.imwrite(output_path, result_img)  # Save the result image
    print(f"Pose estimation result saved to {output_path}")

# Main function
if __name__ == '__main__':
    library_path = "/home/khadas/test/yolov8n_pose_onnx_uint8/libnn_yolov8n_pose_onnx.so"  # Path to the library
    model_path = "/home/khadas/test/yolov8n_pose_onnx_uint8/yolov8n_pose_onnx.nb"  # Path to the model
    image_path = "/home/khadas/test/Screenshot.png"  # Path to the input image

    run_model(library_path, model_path, image_path)  # Run the model
```

This is the result of the execution.
![image](https://github.com/user-attachments/assets/69a55b0b-dbf4-4aa4-9c02-b2c1923f39fe)
Additionally, I would appreciate it if you could share information about the structure of the pose model.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @CGAAG, thank you for reaching out and for your interest in Ultralytics 🚀! This is an automated response to acknowledge your issue, and an Ultralytics engineer will assist you soon.

For a detailed exploration of YOLOv8, please visit our [Docs](https://docs.ultralytics.com). You'll find an abundance of [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples to guide you. If this is a 🐛 Bug Report, providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) would greatly assist us in diagnosing the issue.

If your query relates to custom training, please give us all the relevant details such as dataset image examples and training logs. Also, ensure you're aligning with our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Get involved with our vibrant Ultralytics community in whichever space suits you best. For instantaneous chat, join us on [Discord](https://ultralytics.com/discord) 🎧. Prefer a more in-depth discussion? Check out our [Discourse](https://community.ultralytics.com). Dive into shared interactions on our [Subreddit](https://reddit.com/r/ultralytics) and learn from the collective knowledge.

## Upgrade

Please upgrade to the latest `ultralytics` package, ensuring that all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) are met in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/), to ascertain if your issue persists in the current version:

```bash
pip install -U ultralytics
```

## Environments

You can operate YOLOv8 in any of the following up-to-date verified environments, which come pre-installed with all dependencies including [CUDA](https://developer.nvidia.com/cuda), [CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/):

- **Notebooks** with complimentary GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. Refer to the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. Refer to the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. Refer to the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

When this badge is green, Ultralytics CI tests are passing, which certify the correct function of all YOLOv8 [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours, as well as on each commit. 🚀

Thank you for your patience and support in improving Ultralytics!

**Comment by Y-T-G** [comment]
> to output all outputs from each grid (1, 116, 80, 80 / 1, 116, 40, 40 / 1, 116, 20, 20) and converted them to ONNX

These are supposed to go through the final module of the head. You're missing a whole module.

**Comment by Y-T-G** [comment]
Ultralytics already provides a way to convert the model to ONNX.

https://docs.ultralytics.com/modes/export/

> output all outputs from each grid (1, 116, 80, 80 / 1, 116, 40, 40 / 1, 116, 20, 20) and converted them to ONNX

These are not the outputs you should be processing. They are for feature map visualization. If you exported using the ultralytics export function, you would get the correct output to process which would be of shape `[1, 56, 8400]` for the default model.

**Comment by CGAAG** [comment]
Since Khadas does not support the final output values of various models, I need to implement a process in the code that gathers all the outputs from each grid before they are combined. Therefore, I need advice on whether the implementation in my current code is done correctly

**Comment by Y-T-G** [comment]
Did you try it without the workaround first?

**Comment by CGAAG** [comment]
Yes, but according to the Khadas team, the Amlogic NPU software development kit does not support the output structure of all models, so this process is necessary.

**Comment by Y-T-G** [comment]
What's the error you get if you use the default one?

**Comment by CGAAG** [comment]
The conversion is not progressing in the aml_npu_sdk.

**Comment by glenn-jocher** [comment]
It seems like the issue might be with the aml_npu_sdk. Please ensure you're following their guidelines for model conversion. If the problem persists, reaching out to their support might be helpful.

**Comment by CGAAG** [comment]
What I’m curious about is whether the layers that were omitted when converting the model to ONNX are properly implemented in that code.

**Comment by glenn-jocher** [comment]
It looks like your code is on the right track, but without specific details on the omitted layers, it's hard to confirm. Ensure your implementation aligns with the original model's architecture.

**Comment by CGAAG** [comment]
[modules_tasks_file.zip](https://github.com/user-attachments/files/17187456/modules_tasks_file.zip)
```
from ultralytics import YOLO
model = YOLO("yolov8n-pose.pt")
results = model.export(format="onnx")
```
```
ss@ss-System-Product-Name:~/yolov8_env$ python3 export1.py
/home/ss/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py:357: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu'), file  # load
WARNING ⚠️ yolov8n-pose.pt appears to require 'ultralytics.nn.modules.conv', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.nn.modules.conv' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ultralytics.nn.modules.conv (from versions: none)
ERROR: No matching distribution found for ultralytics.nn.modules.conv
requirements: ❌ Command 'pip install --no-cache "ultralytics.nn.modules.conv"  ' returned non-zero exit status 1.
/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py:372: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu'), file  # load
Traceback (most recent call last):
  File "/home/ss/yolov8_env/export1.py", line 2, in <module>
    model = YOLO("yolov8n-pose.pt")
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 107, in __init__
    self._load(model, task)
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 156, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 417, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 372, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/ss/.local/lib/python3.10/site-packages/torch/serialization.py", line 1097, in load
    return _load(
  File "/home/ss/.local/lib/python3.10/site-packages/torch/serialization.py", line 1525, in _load
    result = unpickler.load()
  File "/home/ss/.local/lib/python3.10/site-packages/torch/serialization.py", line 1515, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package
ss@ss-System-Product-Name:~/yolov8_env$ 
```
I am currently trying to convert to ONNX by modifying the modules and tasks files as shown in the attached file, but an error occurs. What should I do?

**Comment by glenn-jocher** [comment]
It seems like the error is due to a missing module. Please ensure you're using the latest version of the `ultralytics` package and try re-exporting the model without modifying the files. If the issue persists, consider training a new model with the latest package.

**Comment by CGAAG** [comment]
Could you provide the yolov8n pose.pt file from the Ultralytics 8.0.86 version?

**Comment by glenn-jocher** [comment]
I'm sorry, but we can't provide specific model files. Please ensure you're using the latest version of the Ultralytics package to access the models.

**Comment by CGAAG** [comment]
I absolutely must use version 8.0.86, is there any way to do this?

**Comment by glenn-jocher** [comment]
To use version 8.0.86, you can specify it during installation with `pip install ultralytics==8.0.86`.

**Comment by CGAAG** [comment]
I downloaded ultralytics version 8.0.86, and when I ran the following code:
```
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n-pose.pt")

results = model.export(format="onnx")
```
it automatically converted the downloaded model. However, when I ran the script, I got the following error:
```
ss@ss-System-Product-Name:~/yolov8_env$ python3 export1.py
/home/ss/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py:357: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu'), file  # load
WARNING ⚠️ yolov8n-pose.pt appears to require 'ultralytics.nn.modules.conv', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.nn.modules.conv' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ultralytics.nn.modules.conv (from versions: none)
ERROR: No matching distribution found for ultralytics.nn.modules.conv
requirements: ❌ Command 'pip install --no-cache "ultralytics.nn.modules.conv"  ' returned non-zero exit status 1.
/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py:372: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu'), file  # load
Traceback (most recent call last):
  File "/home/ss/yolov8_env/export1.py", line 2, in <module>
    model = YOLO("yolov8n-pose.pt")
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 107, in __init__
    self._load(model, task)
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 156, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 417, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/ss/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 372, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/ss/.local/lib/python3.10/site-packages/torch/serialization.py", line 1097, in load
    return _load(
  File "/home/ss/.local/lib/python3.10/site-packages/torch/serialization.py", line 1525, in _load
    result = unpickler.load()
  File "/home/ss/.local/lib/python3.10/site-packages/torch/serialization.py", line 1515, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package
ss@ss-System-Product-Name:~/yolov8_env$ 
```

This error occurred. I need to convert the model using version 8.0.86. Could you please help me solve this problem?

**Comment by glenn-jocher** [comment]
It seems you're encountering a module issue. Please ensure you're using the correct version of the `ultralytics` package. If the problem persists, consider updating to the latest version or retraining the model with the current package to resolve compatibility issues.
