### ISSUE TITLE
Using Yolov8 face detection model in OpenVino code

### ISSUE THREAD

**Issue by DarsithSPillai** [ultralytics/ultralytics#16580]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using OpenVino code for face detection and face recognition right now. For improving the face detection part, I'm tried to use the Yolov8 face detection model "yolov8n-face.pt". For using Yolo model in OpenVino code I conerted the model to OpenVino XML format. While using the model in that code I facing an error related to the output shape.
OpenVino code : [https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/face_recognition_demo/python/face_recognition_demo.py](url)

Error : 
`Traceback (most recent call last):
  File "/home/asterbyte/Videos/open_model_zoo/demos/face_recognition_demo/python/./face_recognition_demo_frame_saving.py", line 369, in <module>
    sys.exit(main() or 0)
             ^^^^^^
  File "/home/asterbyte/Videos/open_model_zoo/demos/face_recognition_demo/python/./face_recognition_demo_frame_saving.py", line 255, in main
    frame_processor = FrameProcessor(args)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/asterbyte/Videos/open_model_zoo/demos/face_recognition_demo/python/./face_recognition_demo_frame_saving.py", line 132, in __init__
    self.face_detector = FaceDetector(core, args.m_fd,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asterbyte/Videos/open_model_zoo/demos/face_recognition_demo/python/face_detector_original.py", line 70, in __init__
    raise RuntimeError("The model expects output shape with {} outputs".format(self.Result.OUTPUT_SIZE))
RuntimeError: The model expects output shape with 7 outputs`

The output value of OpenVino model I used 1st as,
`[[[[0.         1.         0.31167766 ... 0.152929   0.41998446
    0.20784329]
   [0.         1.         0.08194327 ... 0.8129342  0.534616
    0.91132575]
   [0.         1.         0.06824689 ... 0.43941033 0.24598789
    0.49328107]
   ...
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]]]]`
    
For `for output in outputs[0][0]:
            result = FaceDetector.Result(output)` the output shows `[0.         1.         0.31167766 0.3891974  0.152929   0.41998446
 0.20784329]`
 
 While I using Yolov8, the output values I gets,
 `[[[6.2803469e+00 1.0864115e+01 1.9497246e+01 ... 5.7112329e+02
   5.9245386e+02 6.1301752e+02]
  [9.1400337e+00 7.3855333e+00 5.9132323e+00 ... 5.4523407e+02
   5.3433722e+02 5.3973499e+02]
  [9.3310413e+00 1.1603077e+01 9.0798912e+00 ... 1.3131665e+02
   9.2732727e+01 5.3294312e+01]
  [1.8616257e+01 1.3993429e+01 1.1625447e+01 ... 1.8886108e+02
   2.1067654e+02 2.0000330e+02]
  [6.5797274e-03 2.1085069e-02 2.3727523e-02 ... 3.5897465e-05
   3.8176800e-05 1.2775027e-04]]]`
   
For `for output in outputs[0][0]:
            result = FaceDetector.Result(output)` the output shows `6.280347`
            

How to get these values from Yolo outputs for this OpenVino code which I'm using
`self.image_id = output[0]
            self.label = int(output[1])
            self.confidence = output[2]
            self.position = np.array((output[3], output[4])) # (x, y)
            self.size = np.array((output[5], output[6])) # (w, h)`

Please give me a response

**Comment by UltralyticsAssistant** [comment]
👋 Hello @DarsithSPillai, thank you for reaching out to Ultralytics with your question! 🚀 

We recommend checking out our [Docs](https://docs.ultralytics.com) for an understanding of how the YOLOv8 models work. Specifically, the [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) sections might provide you with additional insights.

If this is a 🐛 Bug Report, please ensure you provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug the issue.

It seems you're having trouble integrating YOLOv8 with OpenVino. If this involves custom training or integration questions, please give us more details, such as dataset examples or specific configuration details, to better assist you.

Feel free to join our community for more interactive support. You can join discussions on [Discord](https://ultralytics.com/discord) 🎧 or engage with us on [Discourse](https://community.ultralytics.com). For more community-driven discussions, check out our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Make sure to upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

Run YOLOv8 in any of the following environments with all dependencies preinstalled:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud VMs**: [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/), [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

If the [CI badge](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg) is green, all tests are currently passing, verifying the functionality across various platforms.

This is an automated response. One of our Ultralytics engineers will assist you soon. 😊

**Comment by ambitious-octopus** [comment]
Hey @DarsithSPillai can you provide a reproducible example please?

**Comment by DarsithSPillai** [comment]
This is the working sample
`cd openvino/demos/face_recognition_demo/python`
Then run the file "face_recognition_demo_original.py"
`python ./face_recognition_demo.py \
  -i <path_to_video>/input_video.mp4 \
  -m_fd intel/face-detection-retail-0005/FP32/face-detection-retail-0005.xml \
  -m_lm intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml \
  -m_reid intel/face-reidentification-retail-0095/FP32/face-reidentification-retail-0095.xml \
  --verbose \
  -fg face_gallery \
  -o output_video/output_video.mp4`

[openvino.zip](https://github.com/user-attachments/files/17258619/openvino.zip)

**Comment by DarsithSPillai** [comment]
@ambitious-octopus  Any updates?

**Comment by ambitious-octopus** [comment]
Hey @DarsithSPillai, 
I can't figure out what code you're using. To use a Ultralytics YOLO to do face recognition and inference with Openvino you should:
1. Find a dataset of faces.
2. Train a YOLO to recognize faces.
3. Export the YOLO model to Openvino.
