### ISSUE TITLE
Question about custom models need to use multi-threaded commands

### ISSUE THREAD

**Issue by Aebestach** [ultralytics/ultralytics#16605]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. I encountered a very interesting problem. After looking through the previous issues and other modules, I didn't seem to find the answer, so I asked here.

I cloned the source code of ultralytics from GitHub and modified it based on it.
**_Modification:_** Based on `yolov10n.yaml`, a BiFPN module was added, and a new `yolov10nBiFPN.yaml` file was formed.
Use the new yaml file to train the WIDER FACE dataset. When I only use one GPU, the following error will not be reported, but when I use multiple GPUs, it will tell me to run the program with a command in the form of `python -m torch.distributed.run --nproc_per_node 2 train.py`.
Currently, I can use this form of command for training, but I am curious, why when using the official ultralytics code to train the WIDER FACE dataset, it will not let me enter the command of *enable multithreading xx* for training, and it only appears when there is a custom module?

Faced with this problem, is there any solution to avoid artificially typing `python -m torch.distributed.run --nproc_per_node 2 train.py`?
Thank you so much.

**Environment:**
- Ubuntu 16.04.7 LTS
- PyTorch 2.4.1
- CUDA 11.0
- CUDA Toolkit 11.8
- ultralytics v8.3.2 cloned from GitHub
- P100 16GB * 4
- Python 3.9.19

**Code:**
```python
from ultralytics import YOLO
model = YOLO('yolov10nBiFPN.yaml')
results = model.train(data='Project/datasets/widerface/widerface.yaml', epochs=100, imgsz=640,
                        device=[1, 2, 3], batch=18, pretrained=False, amp=False)
```

**Error:**
```
DDP: debug command /Data/username/anaconda3/envs/newFeatureFD/bin/python3 -m torch.distributed.run --nproc_per_node 3 --master_port 40787 /Data/username/.config/Ultralytics/DDP/_temp_ake12fpe140110742584528.py
Traceback (most recent call last):
  File "/Data/username/.config/Ultralytics/DDP/_temp_ake12fpe140110742584528.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/Data/username/.config/Ultralytics/DDP/_temp_ake12fpe140110742584528.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/Data/username/.config/Ultralytics/DDP/_temp_ake12fpe140110742584528.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
E1002 02:04:56.278203 140654135056128 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 19480) of binary: /Data/username/anaconda3/envs/newFeatureFD/bin/python3
Traceback (most recent call last):
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/Data/username/.config/Ultralytics/DDP/_temp_ake12fpe140110742584528.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-02_02:04:56
  host      : user-node172
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 19481)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-02_02:04:56
  host      : user-node172
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 19482)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-02_02:04:56
  host      : user-node172
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 19480)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/Data/username/Project/ultralytics-8.3.2/train.py", line 8, in <module>
    results = model.train(data='Project/datasets/widerface/widerface.yaml', epochs=100, imgsz=640,
  File "/Data/username/Project/ultralytics-8.3.2/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/Data/username/Project/ultralytics-8.3.2/ultralytics/engine/trainer.py", line 202, in train
    raise e
  File "/Data/username/Project/ultralytics-8.3.2/ultralytics/engine/trainer.py", line 200, in train
    subprocess.run(cmd, check=True)
  File "/Data/username/anaconda3/envs/newFeatureFD/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Data/username/anaconda3/envs/newFeatureFD/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '3', '--master_port', '40787', '/Data/username/.config/Ultralytics/DDP/_temp_ake12fpe140110742584528.py']' returned non-zero exit status 1.
```

**Comment by Y-T-G** [comment]
Are you asking about multi-threading or multi-GPU? The error is because you didn't install ultralytics as package. You're supposed to run `pip install .` (dot at the end) inside the cloned folder.

**Comment by Aebestach** [comment]
OK, thank you very much, the problem has been solved

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.
