### ISSUE TITLE
the program is stoped after 2 epochs training

### ISSUE THREAD

**Issue by wufeng1314** [ultralytics/ultralytics#1662]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_m7cet2gz2525071434128.py", line 6, in <module>
    trainer.train()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 186, in train
    self._do_train(RANK, world_size)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 297, in _do_train
    pbar = tqdm(enumerate(self.train_loader), total=nb, bar_format=TQDM_BAR_FORMAT)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
MemoryError
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1352 closing signal CTRL_C_EVENT
WARNING:torch.distributed.elastic.multiprocessing.api:Unable to shutdown process 1352 via 0, forcefully exitting via 0
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\nn\parallel\distributed.py", line 1621, in _sync_buffers
    self._sync_module_buffers(authoritative_rank)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\nn\parallel\distributed.py", line 1625, in _sync_module_buffers
    self._default_broadcast_coalesced(authoritative_rank=authoritative_rank)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\nn\parallel\distributed.py", line 1646, in _default_broadcast_coalesced
    self._distributed_broadcast_coalesced(
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\nn\parallel\distributed.py", line 1562, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: [C:\cb\pytorch_1000000000000\work\third_party\gloo\gloo\transport\uv\unbound_buffer.cc:67] Timed out waiting 1800000ms for recv operation to complete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_m7cet2gz2525071434128.py", line 6, in <module>
    trainer.train()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 186, in train
    self._do_train(RANK, world_size)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 317, in _do_train
    preds = self.model(batch['img'])
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\nn\parallel\distributed.py", line 1034, in forward
    self._sync_buffers()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\nn\parallel\distributed.py", line 1621, in _sync_buffers
    self._sync_module_buffers(authoritative_rank)
KeyboardInterrupt
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\run.py", line 766, in <module>
    main()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\run.py", line 762, in main
    run(args)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\run.py", line 753, in run
    elastic_launch(
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\launcher\api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\launcher\api.py", line 237, in launch_agent
    result = agent.run()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 709, in run
    result = self._invoke_run(role)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 851, in _invoke_run
    run_result = self._monitor_workers(self._worker_group)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\agent\server\local_elastic_agent.py", line 306, in _monitor_workers
    result = self._pcontext.wait(0)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 289, in wait
    return self._poll()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 665, in _poll
    self.close()  # terminate all running procs
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 332, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 720, in _close
    handler.proc.wait()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\subprocess.py", line 1361, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 9224 got signal: 2
Traceback (most recent call last):
  File "G:\wufeng\yolov8_person_detect\train.py", line 10, in <module>
    model.train(data=f'{name}.yaml', epochs=100, device=[0, 1], batch=32, resume=True, workers=4,
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\ultralytics\yolo\engine\model.py", line 326, in train
    self.trainer.train()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 180, in train
    subprocess.run(cmd, check=True)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\subprocess.py", line 1020, in communicate
    self.wait()
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\Administrator\anaconda3\envs\pytorch_wf\lib\subprocess.py", line 1361, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
KeyboardInterrupt

when I training yolov8m from scratch，the program is stoped after 2 epochs. I had try worker 8 or 4, bacth 32 , the problem still happen.  when trining 20g memory are used, total memory are 32g, and 7g GPU memory  used, total GPU memory are 11g. so, i am confused because my resources have not been used up, but the training is stoped.

### Environment

YOLO: Ultralytics YOLOv8.0.54  Python-3.8.15 torch-1.13.1 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11264MiB)
                                                      CUDA:1 (NVIDIA GeForce GTX 1080 Ti, 11264MiB)
OS: Windows 10
python:3.8.15
CPU: i9-10900X

### Minimal Reproducible Example

from ultralytics import YOLO

if __name__ == '__main__':
    # Load a model
    model = YOLO("yolov8m.yaml")
    model.train(data=coco.yaml, epochs=100, device=[0, 1], batch=32,
                project='yolov8m', name=model, verbose=False)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
How long have you waited before your keyboard interrupted the code? I'm seeing some reports of long waiting times between epochs and I think these are isolated on windows OS. So, I think your process is not stuck forever, it's just that it's taking longer time than expected between epochs.

**Comment by wufeng1314** [comment]
> How long have you waited before your keyboard interrupted the code? I'm seeing some reports of long waiting times between epochs and I think these are isolated on windows OS. So, I think your process is not stuck forever, it's just that it's taking longer time than expected between epochs.
I did noting, the keyboard interrupted is raised by program. In fact, when training was started, i did something else. After about ten hours, i saw this error and keyboard interrupted
