### ISSUE TITLE
yolo11-obb Multiprocessing [WinError 5] Access is denied

### ISSUE THREAD

**Issue by quitmeyer** [ultralytics/ultralytics#16676]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

I've been wrestling with this bug, and haven't found techniques to fix it? I just updated all the torch and python and ultralytics today too. 

It is a similar error to what is described here https://github.com/ultralytics/ultralytics/issues/10475

and other places, but i did the thing where i wrapped it in if==main stuff already and that didn't fix it

I run the training example and it starts going and doing the scanning thing and then it pops up a ton of 

```
PS C:\Users\andre> & C:/Users/andre/AppData/Local/Programs/Python/Python312/python.exe c:/Users/andre/Documents/GitHub/Mothbox/AI/Mothbox_YoloTrain.py
True
now start training~~~~~~~~~~~~~~~~~~~
Ultralytics 8.3.4 🚀 Python-3.12.7 torch-2.4.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: task=obb, mode=train, model=yolo11s-obb.yaml, data=moths.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=1024, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train34, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\obb\train34
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1   1105974  ultralytics.nn.modules.head.OBB              [1, 1, [128, 256, 512]]       
YOLO11s-obb summary: 344 layers, 9,714,358 parameters, 9,714,342 gradients, 22.5 GFLOPs

Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLO11n...
AMP: checks passed ✅
train: Scanning C:\Users\andre\Desktop\moths25\labels\train.cache... 12 images, 3 backgrounds, 0 corrupt: 100%|██████████| 14/14 [00:00<?, ?it/s]
True
True
True
True
True
True
True
True
val: Scanning C:\Users\andre\Desktop\moths25\labels\val.cache... 6 images, 2 backgrounds, 0 corrupt: 100%|██████████| 8/8 [00:00<?, ?it/s]
True
True
True
True
True
True
True
True
True
True
True
True
PS C:\Users\andre> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
    handle = dh.detach()
             ^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
```

### Environment

Ultralytics 8.3.4 🚀 Python-3.12.7 torch-2.4.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
Setup complete ✅ (12 CPUs, 15.7 GB RAM, 216.1/1860.0 GB disk)

OS                  Windows-11-10.0.22631-SP0
Environment         Windows
Python              3.12.7
Install             pip
RAM                 15.68 GB
CPU                 12th Gen Intel Core(TM) i5-12450H
CUDA                11.8

numpy               ✅ 1.26.4>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1+cu118>=1.8.0
torchvision         ✅ 0.19.1+cu118>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.5>=2.0.0
torch               ✅ 2.4.1+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```
import torch
import torch.multiprocessing
torch.multiprocessing.set_start_method('spawn', force=True)
print(torch.cuda.is_available())
from ultralytics import YOLO

if __name__ == '__main__':
    # Load a model
    model = YOLO("yolo11s-obb.yaml")  # build a new model from YAML using ORIENTED BOUNDING BOXES
    #model = YOLO("yolov8s.yaml")  # build a new model from YAML using regular  rectangle YOLO

    #model = YOLO("mothsn-obb.pt")  # load a pretrained model (recommended for training)

    #model = YOLO("yolov8n-obb.pt")  # load a pretrained model (recommended for training)
    #model = YOLO("yolov8n-obb.yaml").load("yolov8n.pt")  # build from YAML and transfer weights
    print("now start training~~~~~~~~~~~~~~~~~~~")
    # Train the model
    results = model.train(data="moths.yaml", epochs=100, imgsz=1024)

```

### Additional

Thanks for your help!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @quitmeyer, thank you for reaching out and using Ultralytics 🚀! This is an automated response, but an Ultralytics engineer will assist you soon.

We understand you're encountering a 🐛 bug related to multiprocessing on Windows. To assist you better, you've already provided a great [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) which is really helpful. 

Please make sure you've wrapped your training script in a main guard (`if __name__ == '__main__':`) and verified your environment setup. 

To rule out package version issues, ensure you’re using the latest version of `ultralytics` and all required dependencies. You can upgrade with:

```bash
pip install -U ultralytics
```

🔧 For further insights, review other setups:
- **Notebooks** with GPUs: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**, **Amazon**, and **Docker** environments as detailed in our [Docs](https://docs.ultralytics.com/yolov5/environments/).

💬 For real-time discussions, you can join our [Discord](https://ultralytics.com/discord) 🎧, or engage with the Ultralytics community on [Discourse](https://community.ultralytics.com) and [Subreddit](https://reddit.com/r/ultralytics).

To check if the continuous integration (CI) tests are passing for all YOLO modes and tasks, refer to the status badge below:

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Thanks for your patience and collaboration! 😊

**Comment by quitmeyer** [comment]
BTW the `moths.yaml` referenced looks like this

```
# Mothbox example YAML for Ultralytics YOLO 🚀, AGPL-3.0 license

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: C:\Users\andre\Desktop\moths25\ # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/val # val images (relative to 'path') 4 images
test: images/test

# Classes for Moths
nc: 1 #define number of class = 1
names:
  0: creature

```

**Comment by Y-T-G** [comment]
Try downgrading to Python 3.11

**Comment by Y-T-G** [comment]
Why did you add this?

`torch.multiprocessing.set_start_method('spawn', force=True)|

**Comment by quitmeyer** [comment]
> Why did you add this?

Oh that was something i saw on some stackoverflow when i searched part of that error with the multiprocessing thing. It didn't do anything, and i get the same error with or without it.

**Comment by quitmeyer** [comment]
> Try downgrading to Python 3.11

Downgrading to python 3.11 did the trick! Thanks so much!!

**Comment by quitmeyer** [comment]
Thanks @glenn-jocher , it's really impressive how much you all help and respond to people's needs here! really appreciate it! it's helping our scientific project speed along!

**Comment by glenn-jocher** [comment]
Thank you for your kind words! We're glad to hear that Ultralytics is helping your project progress. If you have any questions, feel free to ask!
