### ISSUE TITLE
Failed YOLOv9 train

### ISSUE THREAD

**Issue by xeeetu** [ultralytics/ultralytics#16683]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

I want to run a workout with yolov9t.pt pre-training weights, but I get an error:

C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe C:\DP\ultralytics\yolo_train.py 
C:\DP\ultralytics\ultralytics\nn\tasks.py:732: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
Traceback (most recent call last):
  File "C:\DP\ultralytics\yolo_train.py", line 7, in <module>
    model = YOLO("yolov9t.pt")  # load a pretrained model (recommended for training)
            ^^^^^^^^^^^^^^^^^^
  File "C:\DP\ultralytics\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\DP\ultralytics\ultralytics\engine\model.py", line 152, in __init__
    self._load(model, task=task)
  File "C:\DP\ultralytics\ultralytics\engine\model.py", line 241, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DP\ultralytics\ultralytics\nn\tasks.py", line 806, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DP\ultralytics\ultralytics\nn\tasks.py", line 732, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 1097, in load
    return _load(
           ^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 1525, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 1515, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'ELAN1' on <module 'ultralytics.nn.modules.block' from 'C:\\DP\\ultralytics\\ultralytics\\nn\\modules\\block.py'>

### Environment

Ultralytics 8.3.4 🚀 Python-3.11.5 torch-2.4.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3070 Ti, 8192MiB)
Setup complete ✅ (16 CPUs, 31.9 GB RAM, 332.2/465.1 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.5
Install             pip
RAM                 31.89 GB
CPU                 AMD Ryzen 7 3800X 8-Core Processor
CUDA                11.8

numpy               ✅ 1.25.2>=1.23.0
matplotlib          ✅ 3.8.0>=3.3.0
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 10.0.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.2>=1.4.1
torch               ✅ 2.4.1+cu118>=1.8.0
torchvision         ✅ 0.19.1+cu118>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.1.0>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.8>=2.0.0
torch               ✅ 2.4.1+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

model = YOLO("yolov9t.pt")
results = model.train(...)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @xeeetu, thank you for your interest in Ultralytics 🚀! This is an automated response to let you know that an Ultralytics engineer will assist you soon.

For now, we recommend visiting our [Docs](https://docs.ultralytics.com) where you might find relevant guidance for your YOLO training tasks.

It appears you are encountering a 🐛 bug. Could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) if not already included? This will greatly help us in diagnosing the issue.

Have you tried upgrading to the latest version? Ensure that your environment meets the following requirements and update with:

```bash
pip install -U ultralytics
```

## Communities and Support

Connect with our amazing community for support and discussions:
- [Discord](https://ultralytics.com/discord) 🎧: Engage in real-time chat.
- [Discourse](https://community.ultralytics.com): Participate in in-depth discussions.
- [Subreddit](https://reddit.com/r/ultralytics): Share and learn from community threads.

## Running Environments

YOLO can be deployed across various platforms with pre-installed dependencies:
- **Free GPU Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud VMs**: [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **AWS Deep Learning AMI**: [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Images**: [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a> If this badge is green, all Ultralytics CI tests are passing, ensuring functionality across macOS, Windows, and Ubuntu.

Thanks again for reaching out. Your issue is important, and we are here to help! 😊

**Comment by Skillnoob** [comment]
Something seems wrong with your ultralytics installation. Please reinstall with
`pip uninstall ultralytics`
`pip install -U ultralytics --no-cache-dir`

**Comment by xeeetu** [comment]
> Кажется, что-то не так с вашей установкой Ultralytics. Пожалуйста, переустановите с помощью `pip uninstall ultralytics` `pip install -U ultralytics --no-cache-dir`

I tried that, it didn't work

**Comment by Y-T-G** [comment]
> "C:\DP\ultralytics\yolo_train.py

You're running from inside an `ultralytics` folder which is outdated or broken.

Move the script to a different folder.
