### ISSUE TITLE
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading

### ISSUE THREAD

**Issue by TanJingXuan-06** [ultralytics/ultralytics#16692]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I was trying to train a model at command prompt on my laptop using:

yolo task=detect mode=train model=yolov8s.pt data= data.yaml epochs=25 imgsz=640 plots=True

I have roughly 15k data for training. I tried running nvidia-smi and this is what I got :

C:\Users\user\Downloads>nvidia-smi
![image](https://github.com/user-attachments/assets/bc84b92b-e765-44ba-8416-df6325ad51f3)

However, when I run the bash code, after it creates the cache file, I got this error:

AMP: checks passed ✅.22.dfl.conv.weight'
train: Scanning C:\SOHAI BOT\ECE4078 Lab Student\ECE4078Project\yolo\yolov8\data\train\labels... 15000 images, 8 backgrounds, 0 corrupt: 100%|██████████| 15000/15000 [00:46<00:00, 323.73it/s]
train: New cache created: C:\SOHAI BOT\ECE4078 Lab Student\ECE4078Project\yolo\yolov8\data\train\labels.cache
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
exitcode = _main(fd, parent_sentinel)
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in main
self = reduction.pickle.load(from_parent)
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\torch_init.py", line 122, in
raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\cufft64_10.dll" or one of its dependencies.

Anyone knows any solution to this ?

I tried reducing my sample to 10k. It is still the same.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @TanJingXuan-06, thank you for your interest in Ultralytics 🚀!

For issues like this, a common first step is to ensure your system environment is correctly set up. Please visit our [Docs](https://docs.ultralytics.com) for guidance, including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples, which often have solutions for similar issues.

Since this appears to be a 🐛 Bug Report, we kindly ask you to provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us understand the problem better. Ensure your setup adheres to our [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), including running in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

If you're facing custom training ❓ questions, please provide detailed information, including dataset examples and training logs. Be sure you’re following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join our community for additional support:
- [Discord](https://ultralytics.com/discord) 🎧 for real-time chat
- [Discourse](https://community.ultralytics.com) for in-depth discussions
- [Subreddit](https://reddit.com/r/ultralytics) for community knowledge sharing

## Upgrade

Please upgrade to the latest `ultralytics` package to verify if the issue is already resolved:

```bash
pip install -U ultralytics
```

## Environments

You can run YOLO in any supported environment:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon AWS**: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Our CI tests verify correct operation on various platforms, and all tests are currently passing if the badge is green.

This is an automated response, but don't worry 😊, an Ultralytics engineer will be with you soon to assist further.

**Comment by TanJingXuan-06** [comment]
I've already tried pip install -U ultralytics

**Comment by TanJingXuan-06** [comment]
Hi, issued solved. Apparently I just don't have enough space on my C drive

**Comment by glenn-jocher** [comment]
Great to hear you resolved it! If you have any more questions, feel free to ask.

**Comment by TanJingXuan-06** [comment]
Hi, I faced this issue after 31/40 epoch, 

.70it/s]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\SOHAI BOT\ECE4078 Lab Student\ECE4078Project\yolo\yolov8\myenv\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\SOHAI BOT\ECE4078 Lab Student\ECE4078Project\yolo\yolov8\myenv\lib\site-packages\ultralytics\cfg\__init__.py", line 831, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\SOHAI BOT\ECE4078 Lab Student\ECE4078Project\yolo\yolov8\myenv\lib\site-packages\ultralytics\engine\model.py", line 802, in train
    self.trainer.train()
  File "C:\SOHAI BOT\ECE4078 Lab Student\ECE4078Project\yolo\yolov8\myenv\lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "C:\SOHAI BOT\ECE4078 Lab Student\ECE4078Project\yolo\yolov8\myenv\lib\site-packages\ultralytics\engine\trainer.py", line 414, in _do_train
    ("%11s" * 2 + "%11.4g" * (2 + loss_length))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Any idea what went wrong? My C drive still have sufficient space though. Thanks a lot !
