### ISSUE TITLE
error when resume training

### ISSUE THREAD

**Issue by icklerly1** [ultralytics/ultralytics#1672]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hey guys,

I want to resume an old training. 
If I don't give a model file of my custom training it won't even start but also with the following command it is not working. 
The model file exists.

Can you please give me a hint what I might be doing wrong?
Thanks in advance!

Command:
`yolo task=detect mode=train model=/opt/3tbdrive1/datasets/model_files/5f46520ec41e9dcc9389338b_training_1680001623.70567/model_files/weights/epoch2.pt data=/opt/3tbdrive1/datasets/model_files/5f46520ec41e9dcc9389338b_training_1680001623.70567/rebotnix_training.yaml epochs=4 imgsz=416 name=model_files project=/opt/3tbdrive1/datasets/model_files/5f46520ec41e9dcc9389338b_training_1680001623.70567 batch=8 lr0=0.00013 verbose=True save_period=1 resume=True
`

Error:
```
Starting training for 3 epochs...
Traceback (most recent call last):
  File "/opt/3tbdrive1/products/visiontools/fast_venv37/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/3tbdrive1/products/visiontools/fast_venv37/lib/python3.7/site-packages/ultralytics/yolo/cfg/__init__.py", line 318, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/3tbdrive1/products/visiontools/fast_venv37/lib/python3.7/site-packages/ultralytics/yolo/engine/model.py", line 329, in train
    self.trainer.train()
  File "/opt/3tbdrive1/products/visiontools/fast_venv37/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/opt/3tbdrive1/products/visiontools/fast_venv37/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 384, in _do_train
    LOGGER.info(f'\n{epoch - self.start_epoch + 1} epochs completed in '
UnboundLocalError: local variable 'epoch' referenced before assignment

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HornGate** [comment]
Just do:
'yolo detect train model=XXX.pt resume=True'
the XXX.pt is the last epoch model.
