### ISSUE TITLE
yolo export model=yolo11n.pt task=detect format=tfjs out:ERROR

### ISSUE THREAD

**Issue by hktalent** [ultralytics/ultralytics#16758]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
 yolo export model=/Users/51pwn/Downloads/YOLO11/yolo11n.pt task=detect format=tfjs 
Ultralytics 8.3.6 🚀 Python-3.8.20 torch-2.2.2 CPU (Intel Core(TM) i7-1068NG7 2.30GHz)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from '/Users/51pwn/Downloads/YOLO11/yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.17.0 opset 17...
ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 2.3s, saved as '/Users/51pwn/Downloads/YOLO11/yolo11n.onnx' (10.2 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.20.0...
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 310, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 383, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 53, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/onnx2tf/ops/Resize.py", line 417, in make_node
    resized_tensor = Lambda(
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1045, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 913, in call
    result = self.function(inputs, **kwargs)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 1142, in upsampling2d_nearest
    return tf.compat.v1.image.resize_nearest_neighbor(
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/ops/image_ops_impl.py", line 4769, in resize_nearest_neighbor
    return gen_image_ops.resize_nearest_neighbor(
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/ops/gen_image_ops.py", line 3858, in resize_nearest_neighbor
    return resize_nearest_neighbor_eager_fallback(
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/ops/gen_image_ops.py", line 3896, in resize_nearest_neighbor_eager_fallback
    _attr_T, (images,) = _execute.args_to_matching_eager([images], ctx, [_dtypes.int8, _dtypes.uint8, _dtypes.int16, _dtypes.uint16, _dtypes.int32, _dtypes.int64, _dtypes.half, _dtypes.float32, _dtypes.float64, _dtypes.bfloat16, ])
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 251, in args_to_matching_eager
    tensor = tensor_conversion_registry.convert(t)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 234, in convert
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 324, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 263, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 285, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
  File "/Users/51pwn/anaconda3/envs/YOLOv11/lib/python3.8/site-packages/keras/src/engine/keras_tensor.py", line 285, in __array__
    raise TypeError(
TypeError: You are passing KerasTensor(type_spec=TensorSpec(shape=(1, 20, 20, 256), dtype=tf.float32, name=None), name='tf.math.multiply_163/Mul:0', description="created by layer 'tf.math.multiply_163'"), an intermediate Keras symbolic input/output, to a TF API that does not allow registering custom dispatchers, such as `tf.cond`, `tf.function`, gradient tapes, or `tf.map_fn`. Keras Functional model construction only supports TF API calls that *do* support dispatching, such as `tf.math.add` or `tf.reshape`. Other APIs cannot be called directly on symbolic Kerasinputs/outputs. You can work around this limitation by putting the operation in a custom Keras layer `call` and calling that layer on this symbolic input/output.

ERROR: input_onnx_file_path: /Users/51pwn/Downloads/YOLO11/yolo11n.onnx
ERROR: onnx_op_name: /model.11/Resize
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

### Additional

but yolov8n is ok
```
yolo export model=yolov8n.pt format=tfjs
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @hktalent, thank you for reaching out and sharing your issue with Ultralytics 🚀!

For troubleshooting the error during model export to TensorFlow.js, please ensure you've searched through our [Ultralytics YOLO issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) as similar issues might have solutions.

If this is a 🐛 Bug Report, providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) would greatly assist us in diagnosing the problem. Please include the steps and environment details needed to replicate the issue.

In the meantime, consider upgrading to the latest version of the `ultralytics` package with all dependencies:

```bash
pip install -U ultralytics
```

Check that your environment is supported, as YOLO can run in various verified setups, often with preinstalled dependencies:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

For further help, you can join our community:

- Real-time chat: [Discord](https://ultralytics.com/discord) 🎧
- In-depth discussions: [Discourse](https://community.ultralytics.com)
- Community sharing: [Subreddit](https://reddit.com/r/ultralytics)

An Ultralytics engineer will review your issue soon. Please stay tuned! 😊

**Comment by Y-T-G** [comment]
Try using this:

https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by hktalent** [comment]
```
yolo export model=yolo11n.pt task=detect format=tfjs

pip install tensorflow_probability
onnx-tf convert -i yolo11n.onnx -o yolo11n_saved_model
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model --weight_shard_size_bytes=4194304 yolo11n_saved_model/ tfjs_model/

```
