### ISSUE TITLE
yolo obb map

### ISSUE THREAD

**Issue by liu15509348793** [ultralytics/ultralytics#16799]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is the map of yolov11obb on Dota 1.0 given in ReadMe obtained from the test set submitted to the official Dota website? Or was it obtained in the validation set? If it is submitted to the official website to obtain, can you give me detailed steps, I have trained the yoloobb model now, I don't know how to package it into a format accepted by the official website, is there a ready-made script to use?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @liu15509348793, thank you for reaching out and showing interest in Ultralytics 🚀! This is an automated response to help guide you, and an Ultralytics engineer will also assist soon.

For your question regarding YOLO OBB maps on Dota 1.0, it's a great idea to explore the related [Docs](https://docs.ultralytics.com), which might already have relevant information. If you're inquiring about specific formats or scripts, you might find useful tips in sections related to model outputs or exporting.

If this issue pertains to a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us in debugging.

For custom training ❓ Questions, kindly include detailed information, such as dataset samples and training logs, ensuring you follow our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Engage with the Ultralytics community through your preferred platform:
- Join real-time discussions on [Discord](https://ultralytics.com/discord) 🎧.
- Participate in in-depth discussions on our [Discourse](https://community.ultralytics.com).
- Connect and share experiences on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure your `ultralytics` package is up to date, along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

Run YOLO in verified up-to-date environments:
- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon**: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all our [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing, verifying correct operation on macOS, Windows, and Ubuntu.

**Comment by Y-T-G** [comment]
Yes, it's on the test set.

You will have to run `model.val(data="DOTAv1.yaml" split="test", save_json=True)` which will automatically save the category wise txt files which you can submit to the server.

https://github.com/ultralytics/ultralytics/blob/06adc476a18bb3d5da57ce9407d799de91e08b43/ultralytics/models/yolo/obb/val.py#L159

**Comment by liu15509348793** [comment]
> Yes, it's on the test set.
> 
> You will have to run which will automatically save the category wise txt files which you can submit to the server.`model.val(data="DOTAv1.yaml" split="test", save_json=True)`
> 
> https://github.com/ultralytics/ultralytics/blob/06adc476a18bb3d5da57ce9407d799de91e08b43/ultralytics/models/yolo/obb/val.py#L159

Thank you for your reply, the result obtained through the val function does not seem to be the format required by the official DOTA, is there a conversion script, looking forward to your answer

**Comment by Y-T-G** [comment]
It should automatically save the txt files if you use `save_json=True`

**Comment by liu15509348793** [comment]
> It should automatically save the txt files if you use `save_json=True`

I can already get the results normally according to your method, thank you very much, and I would like to ask if I should use the original image size of the DOTA dataset or the cut image size of the test set here? If the result is also cut if it is used, will I get the correct result by submitting it to the DOTA evaluation system?

**Comment by liu15509348793** [comment]
> It should automatically save the txt files if you use `save_json=True`

I see the result of the combination, no more problems, sorry

**Comment by glenn-jocher** [comment]
Great to hear everything's working now! If you have any more questions, feel free to ask.

**Comment by liu15509348793** [comment]
> Great to hear everything's working now! If you have any more questions, feel free to ask.

I want to use the data of the train and val parts to train together, and use the val part to verify the progress, how should I set it? I need to modify the parameters of yaml or train, I am using the yolov11obb model, and my yaml file is as follows:
path: datasets/DOTA1.0_YOLO_Split # dataset root dir
train: images/train
val: images/val
test: images/test

nc: 15
names:
0: plane
1: baseball-diamond
2: bridge
3: ground-track-field
4: small-vehicle
5: large-vehicle
6: ship
7: tennis-court
8: basketball-court
9: storage-tank
10: soccer-ball-field
11: roundabout
12: harbor
13: swimming-pool
14: helicopter

**Comment by Y-T-G** [comment]
You can add multiple train folders
```
train: 
- images/train
- images/val
```

The rest is the same.

**Comment by glenn-jocher** [comment]
@liu15509348793 to train on both train and val datasets, you can combine them into a single directory and update the `train` path in your YAML file accordingly. For validation, you can use a subset of the val data or split it manually. Adjust the `train` parameter in your YAML to point to the combined dataset.

**Comment by oahnah** [comment]
> > It should automatically save the txt files if you use `save_json=True`
> 
> I can already get the results normally according to your method, thank you very much, and I would like to ask if I should use the original image size of the DOTA dataset or the cut image size of the test set here? If the result is also cut if it is used, will I get the correct result by submitting it to the DOTA evaluation system?

Hello, I have the same problem. I used to use a part of split DOTA dataset. If I want train the whole DOTA and upload the result to   websit, do I split the dataset or do I just use the content in DOTAv1.yaml.
你好，我也有同样的问题。我之前使用分割后的部分DOTA数据集。如果我想训练整个DOTA并将结果上传到网站，我是分割数据集还是直接使用DOTAv1.yaml中的内容？

**Comment by liu15509348793** [comment]
> > > It should automatically save the txt files if you use `save_json=True`
> > 
> > 
> > I can already get the results normally according to your method, thank you very much, and I would like to ask if I should use the original image size of the DOTA dataset or the cut image size of the test set here? If the result is also cut if it is used, will I get the correct result by submitting it to the DOTA evaluation system?
> 
> Hello, I have the same problem. I used to use a part of split DOTA dataset. If I want train the whole DOTA and upload the result to websit, do I split the dataset or do I just use the content in DOTAv1.yaml. 你好，我也有同样的问题。我之前使用分割后的部分DOTA数据集。如果我想训练整个DOTA并将结果上传到网站，我是分割数据集还是直接使用DOTAv1.yaml中的内容？

都可以吧，但是使用分割后的可能效果好一点？

**Comment by oahnah** [comment]
> > > > It should automatically save the txt files if you use `save_json=True`
> > > 
> > > 
> > > I can already get the results normally according to your method, thank you very much, and I would like to ask if I should use the original image size of the DOTA dataset or the cut image size of the test set here? If the result is also cut if it is used, will I get the correct result by submitting it to the DOTA evaluation system?
> > 
> > 
> > Hello, I have the same problem. I used to use a part of split DOTA dataset. If I want train the whole DOTA and upload the result to websit, do I split the dataset or do I just use the content in DOTAv1.yaml. 你好，我也有同样的问题。我之前使用分割后的部分DOTA数据集。如果我想训练整个DOTA并将结果上传到网站，我是分割数据集还是直接使用DOTAv1.yaml中的内容？
> 
> 都可以吧，但是使用分割后的可能效果好一点？

请问分割之后用save_json=True也可以输出txt文件夹吗？
我用原始DOTAv1的配置文件试了下了，直接就训练了，在save_json=True的时候还报了这个错: 
Traceback (most recent call last):
  File "/root/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 824, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/engine/model.py", line 635, in val
    validator(model=self.model)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/engine/validator.py", line 216, in __call__
    stats = self.eval_json(stats)  # update stats
  File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/models/yolo/obb/val.py", line 177, in eval_json
    x, y = (int(c) for c in re.findall(pattern, d["image_id"])[0].split("___"))
IndexError: list index out of range，然后生成的predictions_txt有txt文件，predictions_merged_txt里没内容，您遇到这个情况吗

**Comment by oahnah** [comment]
> predictions_merged

好的谢谢，我再试试

**Comment by oahnah** [comment]
好的，非常谢谢

**Comment by yangershuai627** [comment]
> Yes, it's on the test set.
> 
> You will have to run `model.val(data="DOTAv1.yaml" split="test", save_json=True)` which will automatically save the category wise txt files which you can submit to the server.
> 
> https://github.com/ultralytics/ultralytics/blob/06adc476a18bb3d5da57ce9407d799de91e08b43/ultralytics/models/yolo/obb/val.py#L159

I want to use this method to predict and merge images of the cropped test set of other data sets to get a folder that can be submitted to the server. What do I need to change? I tried to change the names in the dataset configuration file, but without success.

**Comment by glenn-jocher** [comment]
To adapt this method for another dataset, ensure your dataset is properly configured in its YAML file, including paths and class names. If predictions are not merging correctly, confirm the test set images are split in a similar manner to DOTA. You may need to adjust the `image_id` parsing logic in the relevant code to match your dataset's naming convention. For more on dataset preparation, refer to the [documentation here](https://docs.ultralytics.com/datasets/obb/dota-v2/).

**Comment by yangershuai627** [comment]
> To adapt this method for another dataset, ensure your dataset is properly configured in its YAML file, including paths and class names. If predictions are not merging correctly, confirm the test set images are split in a similar manner to DOTA. You may need to adjust the `image_id` parsing logic in the relevant code to match your dataset's naming convention. For more on dataset preparation, refer to the [documentation here](https://docs.ultralytics.com/datasets/obb/dota-v2/).

The configuration file for the dataset points to the correct path, and the class name has been changed. The cropping and naming of the data set is done using methods in the document.

Here is my dataset configuration file, FAIR1M.yaml
path: .../yolo_FAIR1M1.0_split # dataset root dir
train: images/train # train images (relative to 'path') 1411 images
val: images/val # val images (relative to 'path') 458 images
test: images/test # test images (optional) 937 images

# Classes for FAIR1M1.0
names:
  0: Boeing737
  1: Boeing747
  2: Boeing777
  3: Boeing787
  4: C919
  5: A220
  6: A321
  7: A330
  8: A350
  9: ARJ21
  10: other-airplane
  11: Passenger Ship
  12: Motorboat
  13: Fishing Boat
  14: Tugboat
  15: Engineering Ship
  16: Liquid Cargo Ship
  17: Dry Cargo Ship
  18: Warship
  19: other-ship
  20: Small Car
  21: Bus
  22: Cargo Truck
  23: Dump Truck
  24: Van
  25: Trailer
  26: Tractor
  27: Excavator
  28: Truck Tractor
  29: other-vehicle
  30: Basketball Court
  31: Tennis Court
  32: Football Field
  33: Baseball Field
  34: Intersection
  35: Roundabout
  36: Bridge

This is the cropped image.
![微信图片_20250109232024](https://github.com/user-attachments/assets/1017f2f4-c882-49e6-b8fd-305d370c230e)

**Comment by glenn-jocher** [comment]
It seems your configuration and dataset cropping setup are correct. To ensure proper merging of predictions for submission, verify that your cropped images follow the same naming convention as in the DOTA dataset. If issues persist, you may need to adjust the merging logic in the `val.py` script to align with your dataset's naming structure. For more details on splitting and merging, refer to the [official documentation here](https://docs.ultralytics.com/datasets/obb/dota-v2/).

**Comment by yangershuai627** [comment]
@glenn-jocher I have found the cause of the problem. If another dataset is plotted using the model.val method, self.is_dota = False, so you will not get a folder containing txt files.
We need to add self.is_dota = True at the beginning of even_json so that we can successfully get the merged txt file.

![Image](https://github.com/user-attachments/assets/80fee670-8ca3-4616-92e3-4b8131ec8c99)

**Comment by glenn-jocher** [comment]
@yangershuai627 thank you for identifying the issue and sharing your solution! Yes, setting `self.is_dota = True` explicitly for other datasets following the DOTA format is a valid approach to ensure the merged TXT files are generated correctly. This adjustment is necessary when working with datasets not automatically recognized as DOTA.
