### ISSUE TITLE
export structure pruned model to onnx

### ISSUE THREAD

**Issue by Christian-lyc** [ultralytics/ultralytics#16806]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, sorry to bother you again, I have used structure pruning to prune a model, and I clearly see the model become smaller, but after I export it to onnx, the model size is still same as before. I couldn't find the reason. could you help me with it? Thank you so much. Best

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Christian-lyc, thank you for your interest in Ultralytics 🚀! We recommend checking out the [Docs](https://docs.ultralytics.com) where you can find many relevant resources and answers to common questions.

For your issue with exporting a pruned model to ONNX, please ensure you're using the latest version of our library. To update, run:

```bash
pip install -U ultralytics
```

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it more effectively.

Meanwhile, if this is a general ❓ Question, kindly share more details about the steps you've taken during pruning and exporting, along with any logs or outputs you've encountered.

Engage with the Ultralytics community where it suits you best:
- [Discord](https://ultralytics.com/discord) 🎧 for chats
- [Discourse](https://community.ultralytics.com) for in-depth discussions
- [Subreddit](https://reddit.com/r/ultralytics) for community interactions

## Environments

You can run YOLO in verified environments with all dependencies pre-installed. Explore options such as:

- **Notebooks** with free GPUs: [Gradient](https://console.paperspace.com/github/ultralytics/ultralytics) <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud platforms**: [GCP](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/), [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

A green badge indicates passing [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests, ensuring correct operations across all platforms.

👉 Please note this is an automated response. An Ultralytics engineer will be with you shortly to assist further.

**Comment by Y-T-G** [comment]
> I clearly see the model become smaller

How did you see it?

**Comment by Christian-lyc** [comment]
> > I clearly see the model become smaller
> 
> How did you see it?

From the module structure, I can see it changes in pycharm debug mode

**Comment by Y-T-G** [comment]
Is the speed faster?

**Comment by Christian-lyc** [comment]
> Is the speed faster?

No,because the saved onnx model has same size with unpruned model, I don’t think it will be faster. I think the pruned channels become 0 in onnx model

**Comment by Y-T-G** [comment]
What did you prune? `model.model`?

You can try:
```python
model.ckpt.update(dict(model=model.model))
del model.ckpt["ema"]
model.save("pruned.pt")
```

And then loading `pruned.pt` and exporting it.

**Comment by Christian-lyc** [comment]
> What did you prune? `model.model`?
> 
> You can try:
> 
> ```python
> model.ckpt.update(dict(model=model.model))
> del model.ckpt["ema"]
> model.save("pruned.pt")
> ```
> 
> And then loading `pruned.pt` and exporting it.

Thank you so much, it works, but a weird thing is that, if I want to finetune the pruned model, the saved onnx model back to original size again. Sorry, do you know how to fix it? Thank you again.

**Comment by Y-T-G** [comment]
While training, it will rebuild using yaml.

You will have to change this:
https://github.com/ultralytics/ultralytics/blob/50497218c25682458ea35b02dcc5d8a364f34591/ultralytics/engine/model.py#L798

to

`self.trainer.model = self.model`

**Comment by Christian-lyc** [comment]
> While training, it will rebuild using yaml.
> 
> You will have to change this:
> 
> https://github.com/ultralytics/ultralytics/blob/50497218c25682458ea35b02dcc5d8a364f34591/ultralytics/engine/model.py#L798
> 
> to
> 
> `self.trainer.model = self.model`

Thank you so much! And this means if I want to validate the pruned model, I need to do some modification as well? I got another error,

`Traceback (most recent call last):
  File "/export/home/yliu/object_detection/str_unstr_pruning/str_unstr_pruning.py", line 205, in <module>
    results = model.train(data="/export/data/yliu/robotflow/data.yaml", epochs=1,batch=32,device=4,project='finetune',name='pruning40_remove')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/engine/model.py", line 803, in train
    self.trainer.train()
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 476, in _do_train
    self.final_eval()
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 681, in final_eval
    self.metrics = self.validator(model=f)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/engine/validator.py", line 123, in __call__
    model = AutoBackend(
            ^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 157, in __init__
    model = attempt_load_weights(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/nn/tasks.py", line 882, in attempt_load_weights
    ensemble.append(model.fuse().eval() if fuse and hasattr(model, "fuse") else model.eval())  # model in eval mode
                    ^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/nn/tasks.py", line 203, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/home/yliu/miniconda3/envs/ticks/lib/python3.12/site-packages/ultralytics/utils/torch_utils.py", line 254, in fuse_conv_and_bn
    w_conv = conv.weight.view(conv.out_channels, -1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[5, -1]' is invalid for input of size 1508`

**Comment by Christian-lyc** [comment]
I solved it by changing https://github.com/ultralytics/ultralytics/blob/50497218c25682458ea35b02dcc5d8a364f34591/ultralytics/nn/autobackend.py#158 to `from ultralytics.nn.tasks import attempt_load_weights,attempt_load_one_weight
            model, _ = attempt_load_one_weight(weights if isinstance(weights, list) else w,device=device)` and comment https://github.com/ultralytics/ultralytics/blob/50497218c25682458ea35b02dcc5d8a364f34591/ultralytics/nn/autobackend.py#L144 and next line

**Comment by glenn-jocher** [comment]
@Christian-lyc great to hear you found a solution! If you have any more questions or need further assistance, feel free to ask.
