### ISSUE TITLE
Who exported tflite format successfully?

### ISSUE THREAD

**Issue by 13501714030** [ultralytics/ultralytics#16876]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have tried many times according to the official documentation, but none of them have been successful

i have updated the  ultralytics ( pip install -U ultralytics )

i just input the simple command as below:

yolo export model=.\tk11s_150eps_lrf0.3_mxp_640x640.pt format=tflite

WARNING ⚠️ Python>=3.10 is required, but Python==3.8.0 is currently installed
Ultralytics 8.3.11 🚀 Python-3.8.0 torch-2.0.1+cu117 CPU (12th Gen Intel Core(TM) i7-12700H)
YOLO11s summary (fused): 238 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

PyTorch: starting from 'tk11s_150eps_lrf0.3_mxp_640x640.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (18.3 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.0...

ONNX: starting export with onnx 1.16.2 opset 17...
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 2.0s, saved as 'tk11s_150eps_lrf0.3_mxp_640x640.onnx' (36.3 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.20.0...
ERROR: The trace log is below.
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\onnx2tf\utils\common_functions.py", line 310, in print_wrapper_func
    result = func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\onnx2tf\utils\common_functions.py", line 383, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\onnx2tf\utils\common_functions.py", line 53, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\onnx2tf\ops\Add.py", line 248, in make_node
    merge_two_consecutive_identical_ops_into_one(
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\onnx2tf\utils\common_functions.py", line 5384, in merge_two_consecutive_identical_ops_into_one
    tf.math.add(
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\keras\src\layers\core\tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\p4d_v11\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.math.add_5" (type TFOpLambda).

Dimensions must be equal, but are 64 and 32 for '{{node tf.math.add_5/Add}} = AddV2[T=DT_FLOAT](Placeholder, Placeholder_1)' with input shapes: [1,80,160,64], [1,80,160,32].

Call arguments received by layer "tf.math.add_5" (type TFOpLambda):
  • x=tf.Tensor(shape=(1, 80, 160, 64), dtype=float32)
  • y=tf.Tensor(shape=(1, 80, 160, 32), dtype=float32)
  • name='/model.2/m.0/Add'

ERROR: input_onnx_file_path: tk11s_150eps_lrf0.3_mxp_640x640.onnx
ERROR: onnx_op_name: /model.2/m.0/Add
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

same command can be worked fine on YOLOV8 , anyone knows?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @13501714030, thank you for reaching out to Ultralytics 🚀! This is an automated response, and an Ultralytics engineer will assist you shortly.

We recommend checking out the [Docs](https://docs.ultralytics.com) for guidance on exporting models to TFLite format. It seems you might be encountering a compatibility issue, so ensuring your Python and dependency versions align with our requirements is a good starting point.

For 🐛 bug reports, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist in debugging the issue.

In the meantime, ensure that your environment setup meets the necessary specifications:

## Upgrade

Make sure to update your `ultralytics` package and verify all dependencies:

```bash
pip install -U ultralytics
```

## Python Version

It looks like you might need to upgrade Python:

- Recommended: [**Python>=3.10**](https://www.python.org/)

## Environments

YOLO models can be run in these environments:

- **Notebooks** with free GPU: [Gradient](https://console.paperspace.com/github/ultralytics/ultralytics) <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> [Kaggle](https://www.kaggle.com/ultralytics/yolov8)
- **Cloud VMs**: [GCP Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/), [AWS Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: [Docker Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker"></a>

## Community

Join our community channels for more help:

- [Discord](https://ultralytics.com/discord) 🎧
- [Discourse](https://community.ultralytics.com)
- [Subreddit](https://reddit.com/r/ultralytics)

We'll work together to find a solution. Thank you for your patience 🤝!

**Comment by Y-T-G** [comment]
Try this:

https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by Y-T-G** [comment]
What model are you exporting? You can try exporting in Colab.

**Comment by 13501714030** [comment]
> What model are you exporting? You can try exporting in Colab.

i trained my own model by yolov11, the model file is .pt format

**Comment by glenn-jocher** [comment]
You can try exporting your YOLO11 model to TFLite using Google Colab, which often resolves local environment issues. If you continue to face problems, please ensure your dependencies are up to date.

**Comment by DoychinDoychev** [comment]
@13501714030 
My environment is Apple M1 + conda. The below environment worked for me for yolo11n, with a 2-step process outlined afterwards.
```yaml
# a working version
name: yolo_tfjs_env_macos_v2
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.9.24=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - cyrus-sasl=2.1.28=h9131b1a_1
  - eigen=3.4.0=h48ca7d4_0
  - expat=2.6.3=h313beb8_0
  - ffmpeg=4.2.2=h04105a8_0
  - fontconfig=2.14.1=h6402c1e_3
  - freetype=2.12.1=h1192e45_0
  - gettext=0.21.0=hbdbcc25_2
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gmp=6.2.1=hc377ac9_3
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - harfbuzz=4.3.0=he9eebac_2
  - hdf5=1.12.1=h05c076b_3
  - icu=73.1=h313beb8_0
  - jpeg=9e=h80987f9_3
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lerc=3.0=hc377ac9_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.9.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.4=h80987f9_0
  - libllvm14=14.0.6=h19fdd8a_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.39=h80987f9_0
  - libpq=17.0=h02f6b3c_0
  - libprotobuf=4.25.3=h514c7bf_0
  - libssh2=1.11.0=h3e2b118_0
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.1=h0b34f26_2
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - mysql=8.4.0=h3a6587f_1
  - ncurses=6.4=h313beb8_0
  - nettle=3.7.3=h84b5d62_1
  - numpy=1.26.4=py310h3b2db8e_0
  - numpy-base=1.26.4=py310ha9811e2_0
  - opencv=4.10.0=py310h69cb8f9_0
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.5.2=h54b8e55_0
  - openldap=2.6.4=he7ef289_0
  - openssl=3.0.15=h80987f9_0
  - pcre2=10.42=hb066dcc_1
  - pip=24.2=py310hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - python=3.10.15=hb885b13_1
  - qt-main=5.15.2=h0917680_11
  - readline=8.2=h1a28f6b_0
  - setuptools=75.1.0=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.44.0=py310hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - chex==0.1.87
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - etils==1.10.0
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - flax==0.10.1
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.0
      - h5py==3.12.1
      - humanfriendly==10.0
      - humanize==4.11.0
      - idna==3.10
      - importlib-resources==6.4.5
      - jax==0.4.34
      - jaxlib==0.4.34
      - jinja2==3.1.4
      - keras==3.6.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - namex==0.0.8
      - nest-asyncio==1.6.0
      - netron==8.0.2
      - networkx==3.4.2
      - onnx==1.17.0
      - onnx-graphsurgeon==0.5.2
      - onnx-tf==1.10.0
      - onnx2tf==1.26.2
      - onnxruntime==1.20.0
      - onnxslim==0.1.39
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.13.1
      - orbax-checkpoint==0.9.1
      - packaging==23.2
      - pandas==2.2.3
      - pillow==11.0.0
      - protobuf==4.25.5
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pybind11==2.13.6
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      - scipy==1.14.1
      - seaborn==0.13.2
      - six==1.16.0
      - sng4onnx==1.0.4
      - sympy==1.13.1
      - tensorboard==2.16.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-addons==0.23.0
      - tensorflow-decision-forests==1.9.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.16.1
      - tensorflow-metal==1.1.0
      - tensorflowjs==4.22.0
      - tensorstore==0.1.68
      - termcolor==2.5.0
      - tf-keras==2.16.0
      - tflite-support==0.1.0a1
      - toolz==1.0.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.0
      - typeguard==2.13.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - ultralytics==8.3.32
      - ultralytics-thop==2.0.11
      - urllib3==2.2.3
      - werkzeug==3.1.3
      - wrapt==1.16.0
      - wurlitzer==3.1.1
      - zipp==3.21.0
prefix: /opt/anaconda3/envs/yolo_tfjs_env_macos
```


step 1
```python
from ultralytics import YOLO

# Load the YOLOv11 model
# model = YOLO('yolo11-best.pt')  # Replace with your model file
model = YOLO('yolo11n.pt')  # Replace with your model file

# Export the model to TensorFlow format
# Ensure image size matches your training configuration
model.export(format='saved_model', imgsz=640)
```

step 2
```bash
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    yolo11n_saved_model/ \
    tfjs_model/
```
```

**Comment by glenn-jocher** [comment]
@DoychinDoychev it seems you're working with an Apple M1 environment, which can sometimes present compatibility issues. Make sure your `onnx2tf` and TensorFlow libraries are up to date as these can affect the export process. Additionally, using Google Colab or a Linux-based environment might help bypass some platform-specific issues. If problems persist, please check the [Ultralytics documentation on TFLite export](https://docs.ultralytics.com/integrations/tflite/) for any additional troubleshooting tips.
