### ISSUE TITLE
Predict script reports an error when using args 'cfg=***.yaml'

### ISSUE THREAD

**Issue by panp4n** [ultralytics/ultralytics#16885]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

ultralytics version:8.3.12
My python CLI
yolo cfg=test.yaml

test.taml:
```
task: segment 
mode: predict 
model: F:\v8test\test11\weights\last.pt
source: F:\ultralytics-main\datasets\test11\images\val
vid_stride: 1 
stream_buffer: False 
visualize: False 
augment: False 
agnostic_nms: False 
classes: 
retina_masks: True 
embed: 
...
```
Error:
```
Overriding D:\Anaconda3\envs\v8\Lib\site-packages\ultralytics\cfg\default.yaml with F:\v8test\test.yaml

Traceback (most recent call last):
  File "D:\Anaconda3\envs\v8\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\v8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\v8\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda3\envs\v8\lib\site-packages\ultralytics\cfg\__init__.py", line 832, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "D:\Anaconda3\envs\v8\lib\site-packages\ultralytics\engine\model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "D:\Anaconda3\envs\v8\lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "D:\Anaconda3\envs\v8\lib\site-packages\torch\autograd\grad_mode.py", line 44, in generator_context
    response = gen.send(None)
  File "D:\Anaconda3\envs\v8\lib\site-packages\ultralytics\engine\predictor.py", line 226, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "D:\Anaconda3\envs\v8\lib\site-packages\ultralytics\engine\predictor.py", line 208, in setup_source
    or len(self.dataset) > 1000  # many images
ValueError: __len__() should return >= 0
```
It works on ultralytics 8.1

**Comment by UltralyticsAssistant** [comment]
👋 Hi @panp4n, thank you for reaching out and for your interest in Ultralytics 🚀! This is an automated response to help guide you further, and an Ultralytics engineer will be along shortly to assist.

We suggest checking out the [Ultralytics Docs](https://docs.ultralytics.com) for guidance. You'll find detailed [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples that might address your issue.

### Bug Report 🐛

If this is a bug, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so that we can better diagnose the issue. Make sure to include relevant code snippets and configurations.

### Upgrade

Ensure you are using the latest `ultralytics` package. Upgrade with:

```bash
pip install -U ultralytics
```

### Environments

You can run YOLO in verified environments with pre-installed dependencies such as:

- **Notebooks** with GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg"/></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg"/></a>

### Community Support

Join the Ultralytics community:
- For real-time chat, visit [Discord](https://ultralytics.com/discord) 🎧
- For discussions, check out [Discourse](https://community.ultralytics.com)
- Share insights on our [Subreddit](https://reddit.com/r/ultralytics)

### Status

Check the [CI status](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) to ensure all systems are up and running efficiently.

Thank you for your patience, and we'll help resolve your issue shortly!

**Comment by panp4n** [comment]
It works with CLI `yolo predict model: F:\v8test\test11\weights\last.pt source: F:\ultralytics-main\datasets\test11\images\val retina_masks: True `
How can I use yaml config to predict?

**Comment by panp4n** [comment]
8.0 and 8.1 version are fine. The yaml path is correct.

**Comment by Y-T-G** [comment]
You can try:

```
model: "F:/v8test/test11/weights/last.pt"
source: "F:/ultralytics-main/datasets/test11/images/val"
```

**Comment by Y-T-G** [comment]
You can try copying the newer `default.yaml` and updating it with your custom arguments.

https://github.com/ultralytics/ultralytics/blob/b89d6f407044276b1f54753ef98c719e89928631/ultralytics/cfg/default.yaml#L4

**Comment by panp4n** [comment]
The same as newer `default.yaml`. and it works on 8.0.1.6. Is there any changes in the predict code?
Train and export is fine with this CLI.

**Comment by Y-T-G** [comment]
Does it work if you provide path to an image in `source:` instead of directory?

**Comment by panp4n** [comment]
Path to an image is the same error. The path is correct.

**Comment by Y-T-G** [comment]
I can't reproduce this. It works for me on Windows.

Can you provide output of `yolo checks`?

**Comment by panp4n** [comment]
There are two desktops which have this problem.
1:
```
WARNING ⚠️ Python>=3.10 is required, but Python==3.8.17 is currently installed
Ultralytics 8.3.12 🚀 Python-3.8.17 torch-1.8.2+cu111 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Setup complete ✅ (12 CPUs, 31.8 GB RAM, 1621.3/1863.0 GB disk)

OS                  Windows-10-10.0.19042-SP0
Environment         Windows
Python              3.8.17
Install             pip
RAM                 31.83 GB
Disk                1621.3/1863.0 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CPU count           12
GPU                 NVIDIA GeForce RTX 3060, 12288MiB
GPU count           1
CUDA                11.1

numpy               ✅ 1.24.4>=1.23.0
matplotlib          ✅ 3.7.2>=3.3.0
opencv-python       ✅ 4.8.0.74>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 1.8.2+cu111>=1.8.0
torchvision         ✅ 0.9.2+cu111>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
torch               ✅ 1.8.2+cu111!=2.4.0,>=1.8.0; sys_platform == "win32"
```
2:
```
WARNING ⚠️ Python>=3.10 is required, but Python==3.8.20 is currently installed
Ultralytics 8.3.10 🚀 Python-3.8.20 torch-1.8.2+cu111 CUDA:0 (NVIDIA GeForce RTX 4080, 16376MiB)
Setup complete ✅ (12 CPUs, 63.8 GB RAM, 514.3/1007.4 GB disk)

OS                  Windows-10-10.0.22635-SP0
Environment         Windows
Python              3.8.20
Install             pip
RAM                 63.84 GB
Disk                514.3/1007.4 GB
CPU                 13th Gen Intel Core(TM) i5-13600KF
CPU count           12
GPU                 NVIDIA GeForce RTX 4080, 16376MiB
GPU count           1
CUDA                11.1

numpy               ✅ 1.24.4>=1.23.0
matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 1.8.2+cu111>=1.8.0
torchvision         ✅ 0.9.2+cu111>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 1.8.2+cu111!=2.4.0,>=1.8.0; sys_platform == "win32"
```

**Comment by Y-T-G** [comment]
You can try upgrading Python

**Comment by Y-T-G** [comment]
I think there's something wrong with your `yaml` modifications. Did you try copying the `default.yaml` and only modifying `mode:` and `source:` and keeping everything the same?

**Comment by panp4n** [comment]
CLI: `yolo cfg=test.yaml`
test.yaml:
```
task: segment # (str) YOLO task, i.e. detect, segment, classify, pose
mode: predict # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model: D:\github_pro\v8test\xirui\weights\last.pt # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: xirui.yaml # (str, optional) path to data file, i.e. coco128.yaml
epochs: 150 # (int) number of epochs to train for
time: # (float, optional) number of hours to train for, overrides epochs if supplied
patience: 100 # (int) epochs to wait for no observable improvement for early stopping of training
batch: -1 # (int) number of images per batch (-1 for AutoBatch)
imgsz: 1280 # (int | list) input images size as int for train and val modes, or list[w,h] for predict and export modes
save: True # (bool) save train checkpoints and predict results
save_period: 0 # (int) Save checkpoint every x epochs (disabled if < 1)
cache: False # (bool) True/ram, disk or False. Use cache for data loading
device:  # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 1 # (int) number of worker threads for data loading (per RANK if DDP)
project: D:\github_pro\v8test # (str, optional) project name
name: xirui # (str, optional) experiment name, results saved to 'project/name' directory
exist_ok: True # (bool) whether to overwrite existing experiment
pretrained: True # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: auto # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True # (bool) whether to print verbose output
seed: 0 # (int) random seed for reproducibility
deterministic: True # (bool) whether to enable deterministic mode
single_cls: False # (bool) train multi-class data as single-class
rect: False # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False # (bool) use cosine learning rate scheduler
close_mosaic: 10 # (int) disable mosaic augmentation for final epochs (0 to disable)
resume: False # (bool) resume training from last checkpoint
amp: True # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
fraction: 1.0 # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: False # (bool) profile ONNX and TensorRT speeds during training for loggers
freeze: None # (int | list, optional) freeze first n layers, or freeze list of layer indices during training
multi_scale: False # (bool) Whether to use multi-scale during training
# Segmentation
overlap_mask: True # (bool) masks should overlap during training (segment train only)
mask_ratio: 4 # (int) mask downsample ratio (segment train only)
# Classification
dropout: 0.0 # (float) use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True # (bool) validate/test during training
split: val # (str) dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False # (bool) save results to JSON file
save_hybrid: False # (bool) save hybrid version of labels (labels + additional predictions)
conf: # (float, optional) object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7 # (float) intersection over union (IoU) threshold for NMS
max_det: 300 # (int) maximum number of detections per image
half: False # (bool) use half precision (FP16)
dnn: False # (bool) use OpenCV DNN for ONNX inference
plots: False # (bool) save plots and images during train/val

# Predict settings -----------------------------------------------------------------------------------------------------
source: D:\github_pro\ultralytics\datasets\xirui\images\val # (str, optional) source directory for images or videos
vid_stride: 1 # (int) video frame-rate stride
stream_buffer: False # (bool) buffer all streaming frames (True) or return the most recent frame (False)
visualize: False # (bool) visualize model features
augment: False # (bool) apply image augmentation to prediction sources
agnostic_nms: False # (bool) class-agnostic NMS
classes: # (int | list[int], optional) filter results by class, i.e. classes=0, or classes=[0,2,3]
retina_masks: True # (bool) use high-resolution segmentation masks
embed: # (list[int], optional) return feature vectors/embeddings from given layers

# Visualize settings ---------------------------------------------------------------------------------------------------
show: False # (bool) show predicted images and videos if environment allows
save_frames: False # (bool) save predicted individual video frames
save_txt: False # (bool) save results as .txt file
save_conf: False # (bool) save results with confidence scores
save_crop: False # (bool) save cropped images with results
show_labels: False # (bool) show prediction labels, i.e. 'person'
show_conf: False # (bool) show prediction confidence, i.e. '0.99'
show_boxes: False # (bool) show prediction boxes
line_width: # (int, optional) line width of the bounding boxes. Scaled to image size if None.

# Export settings ------------------------------------------------------------------------------------------------------
format: onnx # (str) format to export to, choices at https://docs.ultralytics.com/modes/export/#export-formats
keras: False # (bool) use Keras
optimize: False # (bool) TorchScript: optimize for mobile
int8: False # (bool) CoreML/TF INT8 quantization
dynamic: False # (bool) ONNX/TF/TensorRT: dynamic axes
simplify: True # (bool) ONNX: simplify model
opset: 12 # (int, optional) ONNX: opset version
workspace: 4 # (int) TensorRT: workspace size (GB)
nms: False # (bool) CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01 # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01 # (float) final learning rate (lr0 * lrf)
momentum: 0.937 # (float) SGD momentum/Adam beta1
weight_decay: 0.0005 # (float) optimizer weight decay 5e-4
warmup_epochs: 50.0 # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8 # (float) warmup initial momentum
warmup_bias_lr: 0.1 # (float) warmup initial bias lr
box: 7.5 # (float) box loss gain
cls: 0.5 # (float) cls loss gain (scale with pixels)
dfl: 1.5 # (float) dfl loss gain
pose: 12.0 # (float) pose loss gain
kobj: 1.0 # (float) keypoint obj loss gain
label_smoothing: 0.0 # (float) label smoothing (fraction)
nbs: 64 # (int) nominal batch size
hsv_h: 0.015 # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7 # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4 # (float) image HSV-Value augmentation (fraction)
degrees: 60.0 # (float) image rotation (+/- deg)
translate: 0.1 # (float) image translation (+/- fraction)
scale: 0.5 # (float) image scale (+/- gain)
shear: 0.0 # (float) image shear (+/- deg)
perspective: 0.0 # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.5 # (float) image flip up-down (probability)
fliplr: 0.5 # (float) image flip left-right (probability)
mosaic: 0.0 # (float) image mosaic (probability)
mixup: 0.0 # (float) image mixup (probability)
copy_paste: 0.0 # (float) segment copy-paste (probability)
copy_paste_mode: "flip" # (str) the method to do copy_paste augmentation (flip, mixup)
auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
erasing: 0.0 # (float) probability of random erasing during classification training (0-1)
crop_fraction: 1.0 # (float) image crop fraction for classification evaluation/inference (0-1)

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg: # (str, optional) for overriding defaults.yaml

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml # (str) tracker type, choices=[botsort.yaml, bytetrack.yaml]

```

**Comment by panp4n** [comment]
I tried a lot of methods. I am familiar with this configuration file. I tried this on older version YOLOv8-seg.It is fine. This problem only occurs since the new version was updated

**Comment by Y-T-G** [comment]
Only change `mode:` and `source:`

**Comment by panp4n** [comment]
> Only change `mode:` and `source:`

It works.But use the default model

**Comment by Y-T-G** [comment]
Only change `mode:`, `source:`, `model:`, `task:`

**Comment by panp4n** [comment]
Thank you so much!
-1 isn't for AutoBatch? It used to be possible.

**Comment by panp4n** [comment]
> AutoBatch only works during training.

Thank you very much. It helps me a lot.

**Comment by glenn-jocher** [comment]
@panp4n you're welcome! If you have any more questions, feel free to ask.
