### ISSUE TITLE
Issue with relative paths in data.yaml file when trying to train yolo custom model 

### ISSUE THREAD

**Issue by bruhbot-dev** [ultralytics/ultralytics#16911]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to create a training pipeline to train a custom yolov9 model with user inputted labeled images.

I am having an issue where if I make my data.yaml file use relative paths, I get the error:
```
RuntimeError: Dataset 'OIT_model/customOIT/customdatasetyolo/data.yaml' error
  Dataset 'OIT_model/customOIT/customdatasetyolo/data.yaml' images not found , missing path 'C:\GitHub\Anomaly_detection_combine\OIT_model\Anomaly_detection_combine\OIT_model\customOIT\customdatasetyolo\Anomaly_detection_combine\OIT_model\customOIT\customdatasetyolo\val'
```
What is even more odd, is that the path the error mentions,
```
'C:\\GitHub\\Anomaly_detection_combine\\OIT_model\\Anomaly_detection_combine\\OIT_model\\customOIT\\customdatasetyolo\\Anomaly_detection_combine\\OIT_model\\customOIT\\customdatasetyolo\\val'
```
is not a path that exists or is being requested anywhere. The actual path is
```
'C:\\GitHub\\Anomaly_detection_combine\\OIT_model\\customOIT\\customdatasetyolo\\val' 
```
for some reason it is repeating the first part of the path 3 times.

This is the data.yaml file:
```
    path: OIT_model/customOIT/customdatasetyolo
    train: OIT_model/customOIT/customdatasetyolo/train
    val: OIT_model/customOIT/customdatasetyolo/val
    nc: 1
    names: ['5']
```
and this is the code that is starting training:
```
    def train_custom_dataset_yolo(data_path, epochs=100, imgsz=64, verbose=True):
        model = YOLO("OIT_model/yolov9c.pt")
        # Specify the save directory for training runs
        save_dir = 'OIT_model/customOIT/yolocustomtrainoutput'
        if os.path.exists(save_dir):
            for file in os.listdir(save_dir):
                file_path = os.path.join(save_dir, file)
                if os.path.isfile(file_path) or os.path.islink(file_path):
                    os.unlink(file_path)
                elif os.path.isdir(file_path):
                    shutil.rmtree(file_path)
        os.makedirs(save_dir, exist_ok=True)
        model.train(data=data_path, epochs=epochs, imgsz=imgsz, verbose=verbose, save_dir=save_dir)
        return
    train_custom_dataset_yolo('OIT_model/customOIT/customdatasetyolo/data.yaml', epochs=1,imgsz=64, verbose=True)
```
Very strangely however, when I replace the relative paths with absolute paths, like so:
```
    path: C:/GitHub/fix/Anomaly_detection_combine/OIT_model/customOIT/customdatasetyolo
    train: C:/GitHub/fix/Anomaly_detection_combine/OIT_model/customOIT/customdatasetyolo/train
    val: C:/GitHub/fix/Anomaly_detection_combine/OIT_model/customOIT/customdatasetyolo/val
    nc: 1
    names: ['5']
```
training works without issue. Using absolute pathing is not an option for me, as this application needs to be reproductible on others machines.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @bruhbot-dev, thank you for reaching out to us about this issue with relative paths in your `data.yaml` file. We’re here to help! 🚀

Please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so our team can better understand and diagnose the problem. This can greatly assist in debugging the issue.

For new users, we recommend reviewing the [Docs](https://docs.ultralytics.com) where you can find guidance on [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage. You might find the solution you’re looking for there.

Join our vibrant community for even more support:
- Chat with us on [Discord](https://ultralytics.com/discord) 🎧
- Engage in discussions on [Discourse](https://community.ultralytics.com)
- Explore topics on our [Subreddit](https://reddit.com/r/ultralytics)

## Upgrade

Ensure you are on the latest version of `ultralytics` as updates may have resolved your issue:

```bash
pip install -U ultralytics
```

## Environments

Need a different environment? YOLO can be run in these verified environments:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Google Cloud**: [Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon**: [Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: [Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a> Check this badge status to verify all continuous integration tests are passing for correct operation.

This is an automated response. An Ultralytics engineer will be with you soon to assist further. Thank you for your patience! 😊

**Comment by Y-T-G** [comment]
You should be omitting the part you included in `path`

```
    path: OIT_model/customOIT
    train: customdatasetyolo/train
    val: customdatasetyolo/val
    nc: 1
    names: ['5']
```

**Comment by bruhbot-dev** [comment]
> You should be omitting the part you included in `path`
> 
> ```
>     path: OIT_model/customOIT
>     train: customdatasetyolo/train
>     val: customdatasetyolo/val
>     nc: 1
>     names: ['5']
> ```

just tried this, same error as before.

**Comment by Y-T-G** [comment]
What's the error?

**Comment by Y-T-G** [comment]
Try

```
    path: .
    train: OIT_model/customOIT/customdatasetyolo/train
    val: OIT_model/customOIT/customdatasetyolo/val
    nc: 1
    names: ['5']
```

**Comment by bruhbot-dev** [comment]
```
Traceback (most recent call last):
  File "C:\GitHub\fix\Anomaly_detection_combine\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 557, in get_dataset
    data = check_det_dataset(self.args.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\fix\Anomaly_detection_combine\.venv\Lib\site-packages\ultralytics\data\utils.py", line 329, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError:
Dataset 'OIT_model/customOIT/customdatasetyolo/data.yaml' images not found ⚠️, missing path 'C:\GitHub\fiix\Anomaly_detection_combine\OIT_model\customOIT\customdatasetyolo\OIT_model\customOIT\customdatasetyolo\val'
Note dataset download directory is 'OIT_model\customOIT\customdatasetyolo'. You can update this in 'C:\Users\SESA775098\AppData\Roaming\Ultralytics\settings.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\GitHub\fix\Anomaly_detection_combine\OIT_model\customOIT\train_custom_data.py", line 76, in <module>
    train_custom_dataset_yolo('OIT_model/customOIT/customdatasetyolo/data.yaml', epochs=1, imgsz=64, verbose=True)
  File "c:\GitHub\fix\Anomaly_detection_combine\OIT_model\customOIT\train_custom_data.py", line 74, in train_custom_dataset_yolo
    model.train(data=data_path, epochs=epochs, imgsz=imgsz, verbose=verbose, project=project_dir, name=project_name)
  File "C:\GitHub\fix\Anomaly_detection_combine\.venv\Lib\site-packages\ultralytics\engine\model.py", line 796, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)   
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "C:\GitHub\fix\Anomaly_detection_combine\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 133, in __init__
    self.trainset, self.testset = self.get_dataset()
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\fix\Anomaly_detection_combine\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 561, in get_dataset
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'OIT_model/customOIT/customdatasetyolo/data.yaml' error
Dataset 'OIT_model/customOIT/customdatasetyolo/data.yaml' images not found , missing path 'C:\GitHub\fix\Anomaly_detection_combine\OIT_model\customOIT\customdatasetyolo\OIT_model\customOIT\customdatasetyolo\val'
Note dataset download directory is 'OIT_model\customOIT\customdatasetyolo'. You can update this in 'C:\Users\SESA775098\AppData\Roaming\Ultralytics\settings.json'
```

**Comment by bruhbot-dev** [comment]
tried both of those, same error for each

**Comment by Y-T-G** [comment]
You can try running this in terminal:

`yolo settings datasets_dir='.'`

And then try again

**Comment by bruhbot-dev** [comment]
That seems to have solved the issue! Thank you for your help.

I am trying to make a dockerisable webapp that allows me to send the docker app to other users, and have them train a yolo model on their custom dataset. Is this something I would need to include in the instructions for set up? Or would it be possible to package my webapp in a way that this setting is set this way by default. Apologies if this is out of scope.

**Comment by Y-T-G** [comment]
It's possible to update the settings through code too.

```python
>>> from ultralytics import SETTINGS
>>> SETTINGS.update(datasets_dir = '.')
```

The change persists.

**Comment by bruhbot-dev** [comment]
Thank you very much for your assistance, I've been trying to solve this problem since last week!
