### ISSUE TITLE
Keyerror：‘C3k2’

### ISSUE THREAD

**Issue by asd13723654042** [ultralytics/ultralytics#16928]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I train myself model, it happends a bug called:Traceback (most recent call last):
  File "D:\Anaconda\envs\yolo8\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\yolo8\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\yolo8\Scripts\yolo.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\cfg\__init__.py", line 564, in entrypoint
    model = YOLO(model, task=task)
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\engine\model.py", line 147, in __init__
    self._new(model, task=task, verbose=verbose)
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\engine\model.py", line 208, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\nn\tasks.py", line 312, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\nn\tasks.py", line 901, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
KeyError: 'C3k2'
What's the matter?

**Comment by asd13723654042** [comment]
I have download the last code.zip

**Comment by Y-T-G** [comment]
You didn't install it.
