### ISSUE TITLE
Batch error with TensorRT Inference

### ISSUE THREAD

**Issue by ambitious-octopus** [ultralytics/ultralytics#16931]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict, Export

### Bug

Exporting a model to tensort with an arbitrary batch size does not take the batch size into account during inference, resulting in a not-so-understandable error. Probably we should check the metadata from the exported model to ensure every argument is correct before actually doing the inference, in case users encounter the unreadable error.

### Environment

```
Ultralytics 8.3.13 🚀 Python-3.10.0 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 11938MiB)
Setup complete ✅ (6 CPUs, 31.3 GB RAM, 516.3/574.7 GB disk)

OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.0
Install             git
RAM                 31.29 GB
Disk                516.3/574.7 GB
CPU                 Intel Core(TM) i5-8600K 3.60GHz
CPU count           6
GPU                 NVIDIA GeForce RTX 3060, 11938MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

Export:
`yolo export model=yolo11n.pt format=engine batch=2`
Inference 
`yolo predict model=yolo11n.engine batch=1`

### Additional

unreadable error from tensorrt package:
```bash
Loading yolo11n.engine for TensorRT inference...
[10/15/2024-16:56:56] [TRT] [I] Loaded engine size: 16 MiB
[10/15/2024-16:56:56] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +36, now: CPU 0, GPU 48 (MiB)

[10/15/2024-16:56:56] [TRT] [E] IExecutionContext::setInputShape: Error Code 3: API Usage Error (Parameter check failed, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape for images. Set dimensions are [1,3,640,640]. Expected dimensions are [2,3,640,640].)
[10/15/2024-16:56:56] [TRT] [E] IExecutionContext::executeV2: Error Code 1: Cuda Runtime (an illegal memory access was encountered)
Traceback (most recent call last):
  File "/home/laughing/anaconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/cfg/__init__.py", line 799, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/predictor.py", line 184, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/predictor.py", line 250, in stream_inference
    with profilers[0]:
  File "/home/laughing/codes/ultralytics/ultralytics/utils/ops.py", line 46, in __enter__
    self.start = self.time()
                 ^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/utils/ops.py", line 61, in time
    torch.cuda.synchronize(self.device)
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 892, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
There's also this error when you run `model.val()` with TensorRT and `batch` > 1 but the number of images in val split is not divisible by it, so it errors out in the last iteration (when the last batch doesn't have enough images to complete the batch).

https://github.com/ultralytics/ultralytics/issues/16920#issuecomment-2413067388
