### ISSUE TITLE
Track script reports an error when using args tracker="botsort.yaml"

### ISSUE THREAD

**Issue by eddyli5** [ultralytics/ultralytics#17001]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

When using tracker="botsort.yaml" to set botsort as tracker it reports an error as blow. But if change to tracker="bytetrack.yaml" it works normally.  Both botsort.yaml and bytetrack.yaml are default cfg.

```
Traceback (most recent call last):
  File "/home/lx/VideoTest/run.py", line 79, in select_video_source
    self.start_video_process(file_name)
  File "/home/lx/VideoTest/run.py", line 88, in start_video_process
    self.process_frame()
  File "/home/lx/VideoTest/run.py", line 99, in process_frame
    results = self.model.track(frames, persist=True, verbose=False, save=True, tracker="botsort.yaml")
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/engine/model.py", line 601, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 262, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 399, in run_callbacks
    callback(self)
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/trackers/track.py", line 80, in on_predict_postprocess_end
    tracks = tracker.update(det, im0s[i])
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/trackers/byte_tracker.py", line 333, in update
    warp = self.gmc.apply(img, dets)
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/trackers/utils/gmc.py", line 115, in apply
    return self.applySparseOptFlow(raw_frame)
  File "/home/lx/venv/tracking_env/lib/python3.10/site-packages/ultralytics/trackers/utils/gmc.py", line 325, in applySparseOptFlow
    frame = cv2.cvtColor(raw_frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src' 
```

### Environment

Ultralytics 8.3.15 🚀 Python-3.10.12 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2080, 8192MiB)
Setup complete ✅ (8 CPUs, 7.6 GB RAM, 83.9/1006.9 GB disk)

OS                  Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 7.65 GB
Disk                83.9/1006.9 GB
CPU                 Intel Core(TM) i7-9700 3.00GHz
CPU count           8
GPU                 NVIDIA GeForce RTX 2080, 8192MiB
GPU count           1
CUDA                12.1

### Minimal Reproducible Example

`def process_frame(self):
        if not self.pipeline:
            return

        output = self.pipeline.run()
        frames = torch.as_tensor(output[0][0], device='cuda')
        
        with torch.no_grad():
            results = self.model.track(frames, persist=True, verbose=False, save=True, tracker="botsort.yaml")
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Try passing the frame as numpy.

**Comment by tychedelia** [comment]
Switching to tracker="bytetrack.yaml" also worked for me.

**Comment by glenn-jocher** [comment]
@tychedelia thank you for confirming that the switch to `tracker="bytetrack.yaml"` resolved the issue. If you need further assistance, feel free to ask, and we'll be happy to help!

**Comment by tychedelia** [comment]
This is still a bug.

**Comment by glenn-jocher** [comment]
Thank you for reporting this. We'll investigate the issue further. In the meantime, you can track progress or contribute fixes by visiting the relevant [Ultralytics GitHub repo](https://github.com/ultralytics/ultralytics).
