### ISSUE TITLE
When attempting detection using YOLOv11, which I upgraded from YOLOv9, I encountered an error: "Can't get attribute 'C3k2' on <module 'ultralytics.nn.modules.block'."

### ISSUE THREAD

**Issue by anaduaa** [ultralytics/ultralytics#17063]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I successfully trained the model using YOLOv11 on Kaggle, but encountered an issue during detection. The error message was: "Can't get attribute 'C3k2' on <module 'ultralytics.nn.modules.block'." Initially, I was using YOLOv9 before switching to YOLOv11. I attempted to upgrade Ultralytics, but it didn't resolve the problem.

**Comment by Y-T-G** [comment]
You're either using outdated `ultralytics` or you're running from an outdated local clone of the `ultralytics` repo.

Provide the full error.

**Comment by anaduaa** [comment]
This is the full error message. I already had the project working locally on YOLOv9. Then, I attempted to upgrade Ultralytics using the command: pip install --upgrade ultralytics.
C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\nn\tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
Traceback (most recent call last):
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\track_and_count.py", line 373, in <module>
    item_counter = ItemCounter(args.weights, args.video, args.output, db_manager)
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\track_and_count.py", line 25, in __init__
    self.model = YOLO(self.weights_path)
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\models\yolo\model.py", line 28, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\engine\model.py", line 141, in __init__
    self._load(model, task=task)
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\engine\model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\nn\tasks.py", line 807, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\nn\tasks.py", line 733, in torch_safe_load       
    ckpt = torch.load(file, map_location="cpu")
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\grocery_item\lib\site-packages\torch\serialization.py", line 1360, in load
    return _load(
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\grocery_item\lib\site-packages\torch\serialization.py", line 1848, in _load
    result = unpickler.load()
  File "C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\grocery_item\lib\site-packages\torch\serialization.py", line 1837, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'C3k2' on <module 'ultralytics.nn.modules.block' from 'C:\\Users\\Duaa.Aqel\\PycharmProjects\\pythonProject1\\exalt-ai-stream-detectors\\GroceryStore\\ultralytics\\nn\\modules\\block.py'>
This the full error message I already have the project working locally on yolov9 then I tried to upgrade the ultralytics using this command : pip install --upgrade ultralytics

**Comment by akachammile** [comment]
I encountered this error as well. I suggest searching the path 'C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\nn\modules\block.py' to check if the file contains 'C3k2'. If it does not, performing a git pull to update your local project might resolve the issue.

**Comment by anaduaa** [comment]
yes the file does not contain 'C3k2' but how to perform git pull for the local project is there a specific command ?

**Comment by glenn-jocher** [comment]
To update your local project, navigate to the project directory in your terminal and run the command `git pull`. This will fetch the latest updates from the repository.

**Comment by Y-T-G** [comment]
> C:\Users\Duaa.Aqel\PycharmProjects\pythonProject1\exalt-ai-stream-detectors\GroceryStore\ultralytics\nn\tasks.py

Like the error shows, you have an `ultralytics`  folder inside. Python is using this folder instead of your installed package. The folder contains outdated `ultralytics`  code. You have to either update the folder, delete it or use a different folder to run your scripts that doesn't contain `ultralytics` folder.

**Comment by anaduaa** [comment]
Thanks a lot, you've really saved me time!

**Comment by glenn-jocher** [comment]
I'm glad I could help! If you have more questions, feel free to ask the YOLO community or check the Ultralytics documentation for further guidance.
