### ISSUE TITLE
RuntimeError:         An attempt has been made to start a new process before the         current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by jiqibuaixuexi** [ultralytics/ultralytics#17096]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Here is my code:
```
from ultralytics import YOLO

model = YOLO('yolov8n-seg.pt')  # load a pretrained model (recommended for training)

model.train(data='config.yaml', epochs=1, imgsz=640)
```

Here is my config.yaml:
```
path: D:\\000.lihao\\02.骨盆Seg\\image-segmentation-yolov8\\tmp
train: images\\train 
val: images\\val  

nc: 1
names: ["femur"]
```

And here is the error which I can't fix:
```
D:\Anaconda\envs\DL\lib\site-packages\ultralytics\nn\tasks.py:332: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu')  # load
Ultralytics YOLOv8.0.23  Python-3.9.20 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce RTX 4090 D, 24564MiB)
yolo\engine\trainer: task=segment, mode=train, model=yolov8n-seg.yaml, data=config.yaml, epochs=1, patience=50, batch=16, imgsz=640, save=True, cache=False, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs\segment\train
D:\Anaconda\envs\DL\lib\site-packages\ultralytics\yolo\engine\trainer.py:113: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.amp)
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1   1004275  ultralytics.nn.modules.Segment               [1, 32, 64, [64, 128, 256]]   
YOLOv8n-seg summary: 261 layers, 3263811 parameters, 3263795 gradients, 12.1 GFLOPs

Transferred 381/417 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.001), 76 bias
train: Scanning D:\000.lihao\02.骨盆Seg\image-segmentation-yolov8\tmp\labels\train.cache... 5000 images, 0 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning D:\000.lihao\02.骨盆Seg\image-segmentation-yolov8\tmp\labels\val.cache... 387 images, 0 backgrounds, 0 corrupt: 100%|██████████| 387/387 [00:00<?, ?it/s]
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\segment\train
Starting training for 1 epochs...
D:\Anaconda\envs\DL\lib\site-packages\ultralytics\nn\tasks.py:332: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu')  # load
Ultralytics YOLOv8.0.23  Python-3.9.20 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce RTX 4090 D, 24564MiB)
yolo\engine\trainer: task=segment, mode=train, model=yolov8n-seg.yaml, data=config.yaml, epochs=1, patience=50, batch=16, imgsz=640, save=True, cache=False, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs\segment\train2
D:\Anaconda\envs\DL\lib\site-packages\ultralytics\yolo\engine\trainer.py:113: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.amp)
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1   1004275  ultralytics.nn.modules.Segment               [1, 32, 64, [64, 128, 256]]
YOLOv8n-seg summary: 261 layers, 3263811 parameters, 3263795 gradients, 12.1 GFLOPs

Transferred 381/417 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.001), 76 bias
train: Scanning D:\000.lihao\02.骨盆Seg\image-segmentation-yolov8\tmp\labels\train.cache... 5000 images, 0 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
val: Scanning D:\000.lihao\02.骨盆Seg\image-segmentation-yolov8\tmp\labels\val.cache... 387 images, 0 backgrounds, 0 corrupt: 100%|██████████| 387/387 [00:00<?, ?it/s]
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\segment\train2
Starting training for 1 epochs...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\envs\DL\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Anaconda\envs\DL\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Anaconda\envs\DL\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda\envs\DL\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Anaconda\envs\DL\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Anaconda\envs\DL\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Anaconda\envs\DL\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\000.lihao\02.骨盆Seg\image-segmentation-yolov8\train.py", line 5, in <module>
    model.train(data='config.yaml', epochs=1, imgsz=640)
  File "D:\Anaconda\envs\DL\lib\site-packages\ultralytics\yolo\engine\model.py", line 206, in train
    self.trainer.train()
  File "D:\Anaconda\envs\DL\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "D:\Anaconda\envs\DL\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 269, in _do_train
    pbar = enumerate(self.train_loader)
  File "D:\Anaconda\envs\DL\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "D:\Anaconda\envs\DL\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda\envs\DL\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "D:\Anaconda\envs\DL\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\envs\DL\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\envs\DL\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\envs\DL\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda\envs\DL\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\Anaconda\envs\DL\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @jiqibuaixuexi, thank you for bringing this to our attention 🚀! This looks like a multiprocessing issue commonly encountered when running scripts on Windows. To help us diagnose the problem, could you please provide a minimum reproducible example (MRE)? This will greatly assist us in identifying the source of the error more efficiently.

Make sure you're using the latest version of the `ultralytics` package and all necessary dependencies. You can try upgrading them directly in your environment to see if the issue persists.

Also, ensure that your script uses the proper multiprocessing idiom on Windows by placing your script's execution code under:

```python
if __name__ == '__main__':
    # Your code here
```

This is an automated response, but rest assured, an Ultralytics engineer will take a closer look at your issue soon.

For any further questions or discussion, feel free to join the Ultralytics community on platforms where you feel most comfortable. Whether you prefer real-time chat, in-depth discussions, or sharing knowledge on forums, there's something for everyone. 😊

**Comment by Y-T-G** [comment]
The `ultralytics` version is outdated. Update it.

And your code under

```
if __name__ == '__main__':
    # Your training code
```

**Comment by glenn-jocher** [comment]
Yes, this code is extremely outdated @jiqibuaixuexi, you need to update with `pip install -U ultralytics`

**Comment by jiqibuaixuexi** [comment]
@glenn-jocher @Y-T-G ，Thanks, problem was solved. But I have a little confuse with the result "Confusion Matrix Normalized" as show below:
![image](https://github.com/user-attachments/assets/4ba36baa-e012-4d8c-995f-48f921ff4414)
Based on my understanding, the upper left and lower right parts of this image should be 1, but according to the result of running the code, it turns out like this. I wonder if there is an issue with the code or if there is another explanation.

**Comment by Y-T-G** [comment]
The confusion matrix is not a typical confusion matrix.

You can read an explanation here:
https://github.com/ultralytics/ultralytics/issues/16695#issuecomment-2394795256

**Comment by jiqibuaixuexi** [comment]
@glenn-jocher @Y-T-G Thanks, Using Ultralytics is really convenient. Currently, I have a requirement to use Ultralytics' object detection model to identify bounding boxes, and then crop the bounding boxes for further downstream tasks. I would like to know if there is a method to implement this?

**Comment by jiqibuaixuexi** [comment]
And I wanna learn how to add some explanation method like GradCAM in test phase.

**Comment by jiqibuaixuexi** [comment]
@glenn-jocher @Y-T-G  Or some times, like in medical domain, I need to input a lot of images from one patients as input to train the model, so that I can get patient-level's metrics other than image-level's. But I don't know how to use ultralytics to do that. Could you give me some tips about customize data input and train the custom model?

**Comment by Y-T-G** [comment]
@jiqibuaixuexi There isn't a method to return crops. You can write your code to crop it.

`ultralytics` has `visualize` argument for feature visualizations. It visualizes the activations.

**Comment by Y-T-G** [comment]
There's a way to get object-level embeddings. But it requires customization.

https://y-t-g.github.io/tutorials/yolo-object-features/
