### ISSUE TITLE
CUDA version problems

### ISSUE THREAD

**Issue by 1yuechu1** [ultralytics/ultralytics#17109]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I would like to fine-tune YOLOv11, but my CUDA version is 11.7. When I download the corresponding versions of PyTorch (1.13.0) and torchvision (0.14.0), the version of NumPy automatically updates to 2.1.2. When I manually adjust it to 1.23.5, I encounter an error with numpy._core. Is it not possible to fine-tune YOLOv11 with CUDA version 11.7?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @1yuechu1, thank you for your interest in Ultralytics 🚀! This is an automated response, but rest assured that an Ultralytics engineer will also assist you soon.

If this is a 🐛 Bug Report, we kindly ask you to provide a minimum reproducible example to help us debug it. 

If this is a custom training ❓ Question, please provide as much detail as possible, including dataset image examples and training logs, and verify that you are following our tips for best training results, which can be found in our guides.

To help ensure your environment is set up correctly, please upgrade to the latest `ultralytics` package:

```bash
pip install -U ultralytics
```

Make sure you are running this in a Python>=3.8 environment with PyTorch>=1.8. Also, ensure that your CUDA installation and PYTORCH are compatible with one another.

Join the Ultralytics community where it suits you best. For real-time chat, head to Discord 🎧. Prefer in-depth discussions? Check out Discourse. Or dive into threads on our Subreddit to share knowledge with the community.

If this badge is green, all our CI tests are currently passing. Our CI tests verify correct operation of all YOLO modes and tasks on macOS, Windows, and Ubuntu regularly and on every commit.

🚀 Don't worry, we'll help you get YOLO up and running smoothly! If there are straightforward solutions outside of the information already provided, we'll get back to you as soon as we can.

**Comment by Y-T-G** [comment]
Provide the full error.

You should create a fresh environment and install PyTorch first and then `ultralytics`

**Comment by 1yuechu1** [comment]
> Provide the full error.
> 
> You should create a fresh environment and install PyTorch first and then `ultralytics`

I have tried this method, but it sets up a CPU environment, and I want to use a GPU for training.

**Comment by Y-T-G** [comment]
How are you installing PyTorch? You should be using the command from their website to install with CUDA.

https://pytorch.org/get-started/previous-versions/

Search PyTorch 2.0.1 supports CUDA 11.7

`pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2`

**Comment by 1yuechu1** [comment]
> How are you installing PyTorch? You should be using the command from their website to install with CUDA.
> 
> https://pytorch.org/get-started/previous-versions/
> 
> Search PyTorch 2.0.1 supports CUDA 11.7
> 
> `pip install torch==2.0.1 torchvision==0.15.2`

Yes, I followed this method to set up the environment, but when I run the example code for training, I encounter an error related to numpy._core.

**Comment by Y-T-G** [comment]
Create a new environment and install PyTorch first and then `ultralytics`

**Comment by 1yuechu1** [comment]
> Create a new environment and install PyTorch first and then `ultralytics`
I follow this step
```Python
conda create -n yolo python=3.10
conda activate yolo
# 安装pytoch版本为2.0.1 
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
# 安装ultralytics
pip install -U ultralytics
# 降低numpy版本使其对应
pip install numpy==1.23.5
```
and run this code
```Python
from ultralytics import YOLO

# Load a model
model = YOLO("yolo11n.pt")

# Train the model
train_results = model.train(
    data="coco8.yaml",  # path to dataset YAML
    epochs=100,  # number of training epochs
    imgsz=640,  # training image size
    device=1,  # device to run on, i.e. device=0 or device=0,1,2,3 or device=cpu
)

# Evaluate model performance on the validation set
metrics = model.val()

# Perform object detection on an image
results = model("2.png")
results[0].show()
```
but end up with `    array = pickle.load(fp, **pickle_kwargs)
ModuleNotFoundError: No module named 'numpy._core'`

**Comment by Y-T-G** [comment]
> pip install -U ultralytics
Don't use `-U` and don't change `numpy` version.

Create a new environment and do it again.

**Comment by Y-T-G** [comment]
Create new environment and try this:

`conda install ultralytics numpy pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia`

**Comment by Y-T-G** [comment]
Try

`conda install numpy pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia`

`conda install ultralytics`

**Comment by 1yuechu1** [comment]
> Try
> 
> `conda install numpy pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia`
> 
> `conda install ultralytics -c conda-forge`
when i use this command `conda install numpy pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia` numpy version is   numpy   pkgs/main/linux-64::numpy-2.0.1-py310h5f9d8c6_1 
when i use the next command it just failed with initial frozen solve

**Comment by Y-T-G** [comment]
Try `pip install ultralytics` after the conda install

**Comment by 1yuechu1** [comment]
> pip install ultralytics

again it comes up with ` Numpy is not available`

**Comment by Y-T-G** [comment]
Provide full error.  Not just the last line.

**Comment by 1yuechu1** [comment]
`A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/mnt/home/Code/2DDetection/ultralytics/test.py", line 1, in <module>
    from ultralytics import YOLO
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/models/__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/models/fastsam/__init__.py", line 3, in <module>
    from .model import FastSAM
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/models/fastsam/model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/model.py", line 12, in <module>
    from ultralytics.engine.results import Results
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/results.py", line 15, in <module>
    from ultralytics.data.augment import LetterBox
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/data/base.py", line 17, in <module>
    from ultralytics.data.utils import FORMATS_HELP_MSG, HELP_URL, IMG_FORMATS
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/data/utils.py", line 18, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/__init__.py", line 3, in <module>
    from .tasks import (
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/tasks.py", line 13, in <module>
    from ultralytics.nn.modules import (
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/__init__.py", line 75, in <module>
    from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, v10Detect
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/head.py", line 21, in <module>
    class Detect(nn.Module):
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/head.py", line 29, in Detect
    anchors = torch.empty(0)  # init
/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/head.py:29: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /opt/conda/conda-bld/pytorch_1682343967769/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  anchors = torch.empty(0)  # init

Traceback (most recent call last):
  File "/mnt/home/Code/2DDetection/ultralytics/test.py", line 19, in <module>
    results = model("2.png")
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/mnt/home/anaconda3/envs/yolo1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/predictor.py", line 250, in stream_inference
    im = self.preprocess(im0s)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/predictor.py", line 127, in preprocess
    im = torch.from_numpy(im)
RuntimeError: Numpy is not available`

**Comment by 1yuechu1** [comment]
`A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/mnt/home/Code/2DDetection/ultralytics/test.py", line 1, in <module>
    from ultralytics import YOLO
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/models/__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/models/fastsam/__init__.py", line 3, in <module>
    from .model import FastSAM
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/models/fastsam/model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/model.py", line 12, in <module>
    from ultralytics.engine.results import Results
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/results.py", line 15, in <module>
    from ultralytics.data.augment import LetterBox
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/data/base.py", line 17, in <module>
    from ultralytics.data.utils import FORMATS_HELP_MSG, HELP_URL, IMG_FORMATS
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/data/utils.py", line 18, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/__init__.py", line 3, in <module>
    from .tasks import (
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/tasks.py", line 13, in <module>
    from ultralytics.nn.modules import (
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/__init__.py", line 75, in <module>
    from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, v10Detect
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/head.py", line 21, in <module>
    class Detect(nn.Module):
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/head.py", line 29, in Detect
    anchors = torch.empty(0)  # init
/mnt/home/Code/2DDetection/ultralytics/ultralytics/nn/modules/head.py:29: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /opt/conda/conda-bld/pytorch_1682343967769/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  anchors = torch.empty(0)  # init

Traceback (most recent call last):
  File "/mnt/home/Code/2DDetection/ultralytics/test.py", line 19, in <module>
    results = model("2.png")
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/mnt/home/anaconda3/envs/yolo1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/predictor.py", line 250, in stream_inference
    im = self.preprocess(im0s)
  File "/mnt/home/Code/2DDetection/ultralytics/ultralytics/engine/predictor.py", line 127, in preprocess
    im = torch.from_numpy(im)
RuntimeError: Numpy is not available`

**Comment by Y-T-G** [comment]
Try `pip install  "numpy<2"`

**Comment by 1yuechu1** [comment]
> pip install "numpy<2"
It has been resolved. Thank you very much!

**Comment by glenn-jocher** [comment]
Great to hear it's resolved! If you have more questions, feel free to ask.
