### ISSUE TITLE
Custom dataset classify on edgeTPU

### ISSUE THREAD

**Issue by mmr689** [ultralytics/ultralytics#17100]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Export

### Bug

Hello,

I'm trying to train a model to use in my Coral EdgeTPU device.

My code is

```
# Load a model
model = YOLO("results/yolov8_trap-colour-insects/yolov8n-cls.pt")
# Train the model
model = model.train(data=output_folder, epochs=5)
# Export the model
model.export(format="edgetpu")
```

But I get this message:

```
Traceback (most recent call last):
  File "/local_path/04_yolov8-CLS_custom_dataset.py", line 48, in <module>
    model.export(format="edgetpu")
    ^^^^^^^^^^^^
  File "/ultralytics/ultralytics/utils/__init__.py", line 219, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'ClassifyMetrics' object has no attribute 'export'. See valid attributes below.

    Class for computing classification metrics including top-1 and top-5 accuracy.

    Attributes:
        top1 (float): The top-1 accuracy.
        top5 (float): The top-5 accuracy.
        speed (Dict[str, float]): A dictionary containing the time taken for each step in the pipeline.
        fitness (float): The fitness of the model, which is equal to top-5 accuracy.
        results_dict (Dict[str, Union[float, str]]): A dictionary containing the classification metrics and fitness.
        keys (List[str]): A list of keys for the results_dict.

    Methods:
        process(targets, pred): Processes the targets and predictions to compute classification metrics.
```

What am I doing wrong? I'm using your Docker `ultralytics/ultralytics`.

Thank you very much!

The full output is

```
root@39145d86455a:/local_path# python 04_yolov8-CLS_custom_dataset.py 
New https://pypi.org/project/ultralytics/8.3.20 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.19 🚀 Python-3.11.9 torch-2.4.1+cu121 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
engine/trainer: task=classify, mode=train, model=results/yolov8_trap-colour-insects/yolov8n-cls.pt, data=data/TMP_trap-colour-insects-dataset-yolo, epochs=5, time=None, patience=100, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train5, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/ultralytics/runs/classify/train5
train: /local_path/data/TMP_trap-colour-insects-dataset-yolo/train... found 6943 images in 2 classes ✅ 
val: /local_path/data/TMP_trap-colour-insects-dataset-yolo/val... found 1737 images in 2 classes ✅ 
test: None...
Overriding model.yaml nc=1000 with nc=2

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    332802  ultralytics.nn.modules.head.Classify         [256, 2]                      
YOLOv8n-cls summary: 99 layers, 1,440,850 parameters, 1,440,850 gradients, 3.4 GFLOPs
Transferred 156/158 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /ultralytics/runs/classify/train5', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Scanning /local_path/data/TMP_trap-colour-insects-dataset-yolo/train... 6943 images, 0 corrupt: 100%|██████████| 6943/6943 [00:00<?, ?it/s]
val: Scanning /local_path/data/TMP_trap-colour-insects-dataset-yolo/val... 1737 images, 0 corrupt: 100%|██████████| 1737/1737 [00:00<?, ?it/s]
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to /ultralytics/runs/classify/train5
Starting training for 5 epochs...

      Epoch    GPU_mem       loss  Instances       Size
        1/5     0.264G     0.5532         15        224: 100%|██████████| 434/434 [00:16<00:00, 26.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 55/55 [00:00<00:00, 85.70it/s] 
                   all      0.845          1

      Epoch    GPU_mem       loss  Instances       Size
        2/5     0.264G      0.373         15        224: 100%|██████████| 434/434 [00:13<00:00, 31.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 55/55 [00:00<00:00, 102.85it/s]
                   all      0.919          1

      Epoch    GPU_mem       loss  Instances       Size
        3/5     0.264G     0.3316         15        224: 100%|██████████| 434/434 [00:13<00:00, 32.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 55/55 [00:00<00:00, 98.73it/s] 
                   all      0.925          1

      Epoch    GPU_mem       loss  Instances       Size
        4/5     0.264G     0.3044         15        224: 100%|██████████| 434/434 [00:13<00:00, 33.37it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 55/55 [00:00<00:00, 88.96it/s] 
                   all      0.949          1

      Epoch    GPU_mem       loss  Instances       Size
        5/5     0.264G     0.2716         15        224: 100%|██████████| 434/434 [00:13<00:00, 31.41it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 55/55 [00:00<00:00, 90.38it/s] 
                   all      0.946          1

5 epochs completed in 0.022 hours.
Optimizer stripped from /ultralytics/runs/classify/train5/weights/last.pt, 3.0MB
Optimizer stripped from /ultralytics/runs/classify/train5/weights/best.pt, 3.0MB

Validating /ultralytics/runs/classify/train5/weights/best.pt...
Ultralytics 8.3.19 🚀 Python-3.11.9 torch-2.4.1+cu121 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
YOLOv8n-cls summary (fused): 73 layers, 1,437,442 parameters, 0 gradients, 3.3 GFLOPs
train: /local_path/data/TMP_trap-colour-insects-dataset-yolo/train... found 6943 images in 2 classes ✅ 
val: /local_path/data/TMP_trap-colour-insects-dataset-yolo/val... found 1737 images in 2 classes ✅ 
test: None...
               classes   top1_acc   top5_acc: 100%|██████████| 55/55 [00:00<00:00, 60.90it/s]
                   all      0.949          1
Speed: 0.0ms preprocess, 0.3ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /ultralytics/runs/classify/train5
Traceback (most recent call last):
  File "/local_path/04_yolov8-CLS_custom_dataset.py", line 48, in <module>
    model.export(format="edgetpu")
    ^^^^^^^^^^^^
  File "/ultralytics/ultralytics/utils/__init__.py", line 219, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'ClassifyMetrics' object has no attribute 'export'. See valid attributes below.

    Class for computing classification metrics including top-1 and top-5 accuracy.

    Attributes:
        top1 (float): The top-1 accuracy.
        top5 (float): The top-5 accuracy.
        speed (Dict[str, float]): A dictionary containing the time taken for each step in the pipeline.
        fitness (float): The fitness of the model, which is equal to top-5 accuracy.
        results_dict (Dict[str, Union[float, str]]): A dictionary containing the classification metrics and fitness.
        keys (List[str]): A list of keys for the results_dict.

    Methods:
        process(targets, pred): Processes the targets and predictions to compute classification metrics.
```

### Environment

With `print(ultralytics.checks())` the output is:

```
Ultralytics 8.3.19 🚀 Python-3.11.9 torch-2.4.1+cu121 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
Setup complete ✅ (48 CPUs, 251.4 GB RAM, 1698.7/1758.3 GB disk)
None
```

I'm using your Docker `ultralytics/ultralytics`.

### Minimal Reproducible Example

```
# Load a model
model = YOLO("results/yolov8_trap-colour-insects/yolov8n-cls.pt")
# Train the model
model = model.train(data=output_folder, epochs=5)
# Export the model
model.export(format="edgetpu")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @mmr689, thank you for sharing your experience with Ultralytics 🚀! This is an automated response to acknowledge your issue. An Ultralytics engineer will assist you soon.

From your description, it seems like you are encountering an issue when trying to export your model to EdgeTPU format. To help us understand and diagnose the problem better, could you please provide a minimum reproducible example (MRE)? This will allow us to replicate the issue on our end and investigate further. 

Additionally, please ensure you're using the latest version of the `ultralytics` package. You can easily upgrade to the latest version by running `pip install -U ultralytics`.

If you're working with custom datasets, providing dataset image examples and training logs would be very helpful. Also, ensure that your environment matches the Python and PyTorch versions specified in our documentation.

For real-time support and community interactions, you might want to join our Discord server 🎧. Alternatively, for more detailed discussions, our Ultralytics community platforms like Discourse and Reddit might be useful for engaging with other users or reading similar cases.

Thank you for your patience and understanding, and we look forward to helping you resolve this issue!

**Comment by Y-T-G** [comment]
You're replacing the `model` with output of training results.

> 
```# Train the model
model = model.train(data=output_folder, epochs=5)
```

Change it to `results =`
