### ISSUE TITLE
SAM2Predictor  prompt_inference(predictor.im, points =points)  got 'NoneType' object has no attribute 'shape‘’

### ISSUE THREAD

**Issue by Duan-Zengqiang** [ultralytics/ultralytics#17146]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi dears.

from ultralytics.models.sam import  SAM2Predictor

#SAMmodel = SAM("sam2_l.pt")
overrides = dict(conf=0.25, task="segment", mode="predict", model="sam2_l.pt", save=False, imgsz=1024) 
predictor = SAM2Predictor(overrides=overrides)
print('got predictor')
predictor.set_image("LAND.jpg")
print('set image ok')
points =[[561,608],[574,512],[570,653],[567,525]]
labels = [1,0,1,0]
bboxes = [100, 100, 200, 200]
rlts= predictor.prompt_inference(predictor.im, points =points) 

I got:
got predictor
Ultralytics 8.3.22 🚀 Python-3.10.11 torch-2.5.0+cpu CPU (11th Gen Intel Core(TM) i7-1165G7 2.80GHz)
set image ok
Traceback (most recent call last):
  File "D:\FLASK\FlaskServerSide\SAM2Predictor2.py", line 17, in <module>
    rlts= predictor.prompt_inference(predictor.im, points =points)  #
  File "D:\PyVE\lib\site-packages\ultralytics\models\sam\predict.py", line 715, in prompt_inference
    bboxes, points, labels, masks = self._prepare_prompts(im.shape[2:], bboxes, points, labels, masks)
AttributeError: 'NoneType' object has no attribute 'shape'

How to use predictor.prompt_inference after set_image?

Thanks

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Duan-Zengqiang, thank you for reaching out and for your interest in Ultralytics 🚀! This is an automated response to help guide you, and an Ultralytics engineer will be with you soon to provide further assistance.

It seems like you're encountering an issue with the `SAM2Predictor` class. To help us debug this 🐛 bug report, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This will allow us to replicate the error on our end and assist you more effectively.

While we wait to resolve this, ensure you are using the latest `ultralytics` package. You can upgrade your environment with:

```bash
pip install -U ultralytics
```

Make sure your Python environment is compatible, which requires [**Python>=3.8**](https://www.python.org/) with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

In the meantime, you might find our [Documentation](https://docs.ultralytics.com) helpful for understanding usage specifics. For real-time help, you can join our [Discord community](https://ultralytics.com/discord) 🎧, or for detailed discussions, check out our [Discourse](https://community.ultralytics.com) and [Subreddit](https://reddit.com/r/ultralytics).

Here are some environments where you can test YOLO with ease:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Stay tuned, and thank you for being a part of the Ultralytics community! 😊

**Comment by Y-T-G** [comment]
Your image path is probably wrong.

**Comment by Duan-Zengqiang** [comment]
> Your image path is probably wrong.

Both LAND.jpg and the py file are in the same folder, so no problem with the  image path.

**Comment by Y-T-G** [comment]
Tru providing full path to the image

**Comment by Duan-Zengqiang** [comment]
> Tru providing full path to the image

I tried full path to the image.  still the same error.

**Comment by glenn-jocher** [comment]
Ensure the image is correctly loaded by checking if `predictor.im` is not `None` after `set_image()`. If the issue persists, verify the image format and try using a different image.

**Comment by Duan-Zengqiang** [comment]
Sam2 work well with that jpg image. I will try again with other images.



---Original---
From: "Glenn ***@***.***&gt;
Date: Fri, Oct 25, 2024 16:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] SAM2Predictor  prompt_inference(predictor.im, points =points)  got 'NoneType' object has no attribute 'shape‘’ (Issue #17146)




 
Ensure the image is correctly loaded by checking if predictor.im is not None after set_image(). If the issue persists, verify the image format and try using a different image.

**Comment by glenn-jocher** [comment]
Great to hear it worked with that image. If you encounter any more issues, feel free to reach out.

**Comment by Duan-Zengqiang** [comment]
No，I mean the same image works in model(....). But when in predictor....,after predictor.set_image(), predictor.im is nonetype.&nbsp;



---Original---
From: "Glenn ***@***.***&gt;
Date: Sat, Oct 26, 2024 04:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] SAM2Predictor  prompt_inference(predictor.im, points =points)  got 'NoneType' object has no attribute 'shape‘’ (Issue #17146)




 
Great to hear it worked with that image. If you encounter any more issues, feel free to reach out.

**Comment by Y-T-G** [comment]
The docs don't say to call `prompt_inference` like you're doing

https://docs.ultralytics.com/models/sam/#sam-prediction-example

**Comment by Duan-Zengqiang** [comment]
> The docs don't say to call `prompt_inference`. It's different for the latest version.
> 
> https://docs.ultralytics.com/models/sam/#sam-prediction-example

!
![image](https://github.com/user-attachments/assets/8c3681d4-bae5-44fc-b278-46edd55605b7)

**Comment by Duan-Zengqiang** [comment]
In fact, I just want to set up images for the model, and then input prompts interactively multiple times to get the predicted results for each prompt. This would save time spent on each interactive predictions。 （i know this could done in SAMPredictor, but i want to do that with SAM2 model or SAM2Predictor...）

**Comment by Duan-Zengqiang** [comment]
OK it works:

from ultralytics.models.sam import  SAM2Predictor
import torch
import json



source = "./images/LAND.jpg"
overrides = dict(conf=0.25, task="segment", mode="predict", model="./Checkpoints/sam2_l.pt", save=False, imgsz=1024) 
predictor = SAM2Predictor(overrides=overrides)
print('##########load model\n\n')
predictor.set_image(source)  # set with image file
print('##########set image\n\n')


points = [[117, 243]]
labels = [1]
results = predictor(points=points, labels=labels)
results[0].show()

print('2222222222222222222222222222222222222222222222222222222222222222222')
points =[[561,608],[574,512],[570,653],[567,525]]
labels = [1,0,1,0]
results = predictor(points=points, labels=labels)
results[0].show()

**Comment by glenn-jocher** [comment]
Glad to hear it's working! If you have any more questions or need further assistance, feel free to ask.
