### ISSUE TITLE
export  yolov10 checkpoint to  onnx or  tensorrt , raise error "AttributeError: 'Conv' object has no attribute 'bn'"

### ISSUE THREAD

**Issue by apple2333cream** [ultralytics/ultralytics#17143]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

env:
ultralytics==8.3.2 
tensorrt==10.5.0
onnx==1.17.0
python3.10
 ubuntu22.04  

my  export  code 

from ultralytics import YOLOv10

model = YOLOv10("/home/wangzp/form_extract_pytrt/doclayout_yolo_docstructbench_imgsz1024.pt")
model.fuse()
model.export(format="engine",half=True)

detail  error:

Traceback (most recent call last):
  File "/home/wangzp/form_extract_pytrt/yolov10/export_yolo2trt.py", line 73, in <module>
    model.export(format="engine",half=True)
  File "/home/wangzp/form_extract_pytrt/yolov10/ultralytics/engine/model.py", line 590, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/wangzp/form_extract_pytrt/yolov10/ultralytics/engine/exporter.py", line 241, in __call__
    y = model(im)  # dry runs
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/tasks.py", line 96, in forward
    return self.predict(x, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/tasks.py", line 114, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/tasks.py", line 136, in _predict_once
    x = m(x)  # run
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/modules/g2l_crm.py", line 115, in forward
    y.append(m(y[-1]))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/modules/g2l_crm.py", line 78, in forward
    return x + self.cv2(self.dilated_block(self.cv1(x))) if self.add else self.cv2(self.dilated_block(self.cv1(x)))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/modules/g2l_crm.py", line 44, in forward
    dx = [self.dilated_conv(x, d) for d in self.dilation]
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/modules/g2l_crm.py", line 44, in <listcomp>
    dx = [self.dilated_conv(x, d) for d in self.dilation]
  File "/usr/local/lib/python3.10/dist-packages/doclayout_yolo/nn/modules/g2l_crm.py", line 37, in dilated_conv
    bn = self.dcv.bn
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'Conv' object has no attribute 'bn'

**Comment by UltralyticsAssistant** [comment]
👋 Hello @apple2333cream, thank you for reaching out to the Ultralytics community 🚀! An error you're encountering during the export of your YOLOv10 model to ONNX or TensorRT is certainly something we can help with. 

To help us understand the bug better, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This will greatly aid in debugging the issue.

In the meantime, please verify that you're using the latest version of our package to ensure the issue hasn't been resolved in a recent update. You can upgrade with the following command:

```bash
pip install -U ultralytics
```

For more information, you can also explore our [Python Usage Guide](https://docs.ultralytics.com/usage/python/) and [CLI Usage Guide](https://docs.ultralytics.com/usage/cli/) which contain numerous examples that might help clarify usage.

Join the Ultralytics community where it suits you best. For real-time chat, check out our [Discord](https://ultralytics.com/discord) 🎧. Prefer in-depth discussions? Visit [Discourse](https://community.ultralytics.com). Or dive into threads on our [Subreddit](https://reddit.com/r/ultralytics) to share insights with fellow users.

Once again, this is an automated response to assist you quickly, but rest assured that an Ultralytics engineer will be here soon to assist you further. Your patience is appreciated 😊!

**Comment by Y-T-G** [comment]
This is not `ultralytics` code.

Install the latest `ultralytics` package through `pip install ultralytics` and run it in a different folder. Not in the YOLOv10 cloned repo folder.

**Comment by Y-T-G** [comment]
Follow the `ultralytics` docs to run YOLOv10.

https://docs.ultralytics.com/models/yolov10/

There's no `YOLOv10` function in `ultralytics`. It's loaded using `YOLO()`
