### ISSUE TITLE
Unable to load any of {libcudnn_engines_precompiled.so.9.4.0..} and RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed 

### ISSUE THREAD

**Issue by mpiercy** [ultralytics/ultralytics#17170]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When running:
yolo train data=coco8.yaml model=yolo11n.pt epochs=10 lr0=0.01
I get:
...standard output, no errors and then:

AMP: running Automatic Mixed Precision (AMP) checks with YOLO11n...
Unable to load any of {libcudnn_engines_precompiled.so.9.4.0, libcudnn_engines_precompiled.so.9.4, libcudnn_engines_precompiled.so.9, libcudnn_engines_precompiled.so}
Traceback (most recent call last):
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 798, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 264, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/utils/checks.py", line 696, in check_amp
    assert amp_allclose(YOLO("yolo11n.pt"), im)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/utils/checks.py", line 683, in amp_allclose
    a = m(batch, imgsz=imgsz, device=device, verbose=False)[0].boxes.data  # FP32 inference
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 234, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 644, in warmup
    self.forward(im)  # warmup
    ^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 461, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/nn/tasks.py", line 112, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/nn/tasks.py", line 130, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/nn/tasks.py", line 151, in _predict_once
    x = m(x)  # run
        ^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-ultralytics/8.3.14_py312/lib/python3.12/site-packages/ultralytics/nn/modules/conv.py", line 54, in forward_fuse
    return self.act(self.conv(x))
                    ^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 459, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/software/user/open/py-pytorch/2.4.1_py312/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 455, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_SUBLIBRARY_LOADING_FAILED

### Environment

Ultralytics 8.3.14 🚀 Python-3.12.1 torch-2.4.0a0 CUDA:0 (NVIDIA A30 MIG 1g.6gb, 5952MiB)
Setup complete ✅ (32 CPUs, 251.5 GB RAM, 12.9/24.0 GB disk)
OS                  Linux-3.10.0-1160.119.1.el7.tuxcare.els2.x86_64-x86_64-with-glibc2.17
Environment         Linux
Python              3.12.1
Install             pip
RAM                 251.54 GB
Disk                12.9/24.0 GB
CPU                 Intel Xeon E5-2620 v4 2.10GHz
CPU count           32
GPU                 NVIDIA A30 MIG 1g.6gb, 5952MiB
GPU count           1
CUDA                12.6
numpy               ✅ 1.26.3>=1.23.0
matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0.post0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.4.0a0+gitunknown>=1.8.0
torchvision         ✅ 0.19.1a0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.4.0a0+gitunknown!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

yolo train data=coco8.yaml model=yolo11n.pt epochs=10 lr0=0.01

### Additional

This is on an HPC cluster using an LMOD installed version of Ultralytics. OS is CentOS:

Linux  3.10.0-1160.119.1.el7.tuxcare.els2.x86_64 #1 SMP Mon Jul 15 12:09:18 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

The libraries it complains about are all in /share/software/user/open/cudnn/9.4.0/lib/, and the cudnn/9.4.0 is automatically loaded as a dependency when our ultralytics is loaded.

Our dependencies loaded with Ultralytics are:
 ml py-ultralytics/8.3.14_py312
 ml list
Currently Loaded Modules:
  1) devel         (S)   6) tcltk/8.6.6    11) python/3.12.1          16) gcc/12.4.0       21) openmpi/5.0.5  (g,m)  26) cudnn/9.4.0            (g)    31) libjpeg-turbo/2.1.4          36) py-ultralytics/8.3.14_py312 (g)
  2) math          (S)   7) ncurses/6.4    12) py-numpy/1.26.3_py312  17) cuda/12.6.1 (g)  22) hdf5/1.14.4    (m)    27) opencv/4.10.0          (g)    32) py-pillow-simd/10.2.0_py312
  3) system              8) readline/8.2   13) py-pandas/2.2.1_py312  18) ucx/1.17.0  (g)  23) eigen/3.4.0           28) py-pytorch/2.4.1_py312 (g,m)  33) py-torchvision/0.19.1_py312
  4) zlib/1.2.11         9) sqlite/3.44.2  14) py-scipy/1.12.0_py312  19) nccl/2.23.4 (g)  24) java/1.8.0_131        29) libpng/1.6.44                 34) py-matplotlib/3.8.3_py312
  5) openssl/3.0.7      10) libffi/3.2.1   15) openblas/0.3.28        20) ucc/1.3.0   (g)  25) ant/1.10.1            30) viz                           35) libglvnd/1.2.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @mpiercy, thank you for reaching out to Ultralytics 🚀! We appreciate your detailed report. It seems like you're encountering a 🐛 bug related to CUDA and CUDNN libraries.

To help us diagnose the problem more effectively, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) if you haven't already? This would greatly assist our team in pinpointing the exact issue.

In the meantime, please ensure that your environment is correctly set up with all necessary dependencies. You can check out our [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) and try upgrading to the latest `ultralytics` package in a [Python>=3.8](https://www.python.org/) environment with [PyTorch>=1.8](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

For real-time support, you may join our [Discord](https://ultralytics.com/discord) community 🎧, participate in discussions on [Discourse](https://community.ultralytics.com), or engage with other users on our [Subreddit](https://reddit.com/r/ultralytics).

Don't worry, an Ultralytics engineer will also be reviewing your issue soon to provide further assistance. Thank you for your patience and cooperation! 😊

## Environments

Ensure you are running YOLO in an up-to-date verified environment, such as:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, which helps verify correct operation across various systems.

**Comment by Y-T-G** [comment]
You should remove any external cuDNN. PyTorch comes with cuDNN. Also it seems like the installed PyTorch was built locally so it could be a problem with that too.

**Comment by JacksonsonMars** [comment]
i meet the same issue. how to adress it finally?

**Comment by glenn-jocher** [comment]
@JacksonsonMars This is typically caused by conflicting cuDNN libraries on HPC systems. Try unloading the external cuDNN module before running YOLO11:

```bash
module unload cudnn/9.4.0
yolo train data=coco8.yaml model=yolo11n.pt epochs=10 lr0=0.01
```

PyTorch 2.4.0 includes its own cuDNN libraries, so the external module can interfere. If you still need the cuDNN module for other applications, you can also try setting `CUDA_VISIBLE_DEVICES` and ensuring PyTorch uses its bundled libraries by checking `torch.cuda.is_available()` returns `True` after unloading the external cuDNN.
