### ISSUE TITLE
YOLOv8-ONNXRuntime-Rust  Failed to initialize ORT API

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#17309]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-Rust

```rust
cargo run --release -- --cuda --model  E:/yolo/yolov8-640.onnx --source e:/demo/123.jpg --plot --height 640 --width 640
    Finished `release` profile [optimized] target(s) in 0.20s
     Running `target\release\yolov8-rs.exe --cuda --model E:/yolo/yolov8-640.onnx --source e:/demo/123.jpg --plot --height 640 --width 640`
The given version [19] is not supported, only version 1 to 10 is supported in this build.
thread 'main' panicked at C:\Users\mm\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\ort-2.0.0-rc.8\src/lib.rs:225:57:
Failed to initialize ORT API
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\yolov8-rs.exe --cuda --model E:/yolo/yolov8-640.onnx --source e:/demo/123.jpg --plot --height 640 --width 640` (exit code: 101)
```

In a Windows environment, any setting environment should be required

@yawnBright 
@jamjamjon

**Comment by UltralyticsAssistant** [comment]
👋 Hello @monkeycc, thank you for bringing this to our attention! 🚀 This is an automated response, but rest assured, an Ultralytics engineer will assist you soon.

We recommend checking out the [Ultralytics Docs](https://docs.ultralytics.com) for helpful information. For ONNX and deployment examples, you can visit our [example tutorials](https://github.com/ultralytics/ultralytics/tree/main/examples).

If this is a 🐛 Bug Report related to the ONNXRuntime-Rust example, please ensure you've provided a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). This will greatly aid in diagnosing the issue. If you haven't already, try to include any debugging output and configuration details specific to your environment.

To ensure compatibility, verify that all dependencies and environment settings meet our outlined requirements. You might want to look into upgrading to the latest version of the `ultralytics` package to see if that resolves the issue:

```bash
pip install -U ultralytics
```

For those who prefer real-time support, chat with the community on [Discord](https://ultralytics.com/discord) 🎧 or join discussions on [Discourse](https://community.ultralytics.com). You can also engage on our [Subreddit](https://reddit.com/r/ultralytics) for community advice and insights.

## Environments

You can experiment with YOLO in various environments that have all dependencies preconfigured:

- **Notebooks** with free GPU options available: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**, **AWS**, and **Docker Image** setups are detailed in the Ultralytics documentation.

## Status

Stay informed with our CI pipeline:

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

This badge will indicate if the latest builds are passing. It ensures all YOLO modes and tasks are functioning correctly across different platforms. 

Thank you again for your contribution and patience! 😊

**Comment by yawnBright** [comment]
It just works in my computer. Maybe  your ort-2.0.0-rc.8 is too high, I use ort-2.0.0-rc.5
```bash
cargo run --release --  --cuda --model "X:\Projects\python\ultralytics-main\yolo11n.onnx" --source "C:\Users
\apple tree\Desktop\test.jpg" --plot --profile
    Finished `release` profile [optimized] target(s) in 0.16s
     Running `target\release\yolov8-rs.exe --cuda --model X:\Projects\python\ultralytics-main\yolo11n.onnx --source "C:\Users\apple tree\Des
ktop\test.jpg" --plot --profile`

Summary:
> Task: Detect (Ultralytics 8.3.8)
> EP: CUDA(0) (May still fall back to CPU)
> Dtype: Float32
> Batch: 1 (Const), Height: 640 (Const), Width: 640 (Const)
> nc: 80 nk: 0, nm: 0, conf: 0.3, kconf: 0.55, iou: 0.45

[Model Preprocess]: 16.7457ms
[ORT H2D]: 0ns
[ORT Inference]: 35.1211ms
[ORT D2H]: 487.4µs
[Model Inference]: 36.4669ms
[Model Postprocess]: 1.544ms
[YOLOResult { Probs(top5): None, Bboxes: Some([Bbox { xmin: 1.4434586, ymin: 50.219833, width: 251.87436, height: 331.46985, id: 0, confiden
ce: 0.95547354 }]), Keypoints: None, Masks: None }]
```

**Comment by jamjamjon** [comment]
@monkeycc It seems that on your Windows system, there may be multiple versions of the `onnxruntime.dll` file, leading to a version mismatch. You should copy the matching version of `onnxruntime.dll` to the same directory as the current executable file(.exe).
 
I noticed that the current example Rust code is not the original code I uploaded—it has been updated by someone else. You can directly use the `usls` library to do `YOLO` inference which support YOLOv5-11. Reference: [https://github.com/jamjamjon/usls/tree/main/examples/yolo](https://github.com/jamjamjon/usls/tree/main/examples/yolo). 

I will try to update the Rust example code in this repository.

**Comment by monkeycc** [comment]
Thank you very much for your help

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.

**Comment by monkeycc** [comment]
https://github.com/ultralytics/ultralytics/pull/17311
https://github.com/ultralytics/ultralytics/tree/3248e277e3d24f2caa29285929bcd3974d3252d8/examples/YOLOv8-ONNXRuntime-Rust

```
ort-2.0.0-rc.8
onnxruntime-win-x64-gpu-1.19.0
```

`An error occurred while attempting to load the ONNX Runtime binary at `D:\onnxruntime-win-x64-gpu-1.19.0\lib`: LoadLibraryExW failed`

```
thread 'main' panicked at C:\Users\mm\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\ort-2.0.0-rc.8\src/lib.rs:132:33:
An error occurred while attempting to load the ONNX Runtime binary at `D:\onnxruntime-win-x64-gpu-1.19.0\lib`: LoadLibraryExW failed
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: std::sync::once::Once::call_once_force::{{closure}}
   3: std::sys::sync::once::futex::Once::call
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\sync\once\futex.rs:168
   4: std::sync::once_lock::OnceLock<T>::initialize
   5: std::sync::once::Once::call_once_force::{{closure}}
   6: std::sys::sync::once::futex::Once::call
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\sync\once\futex.rs:168
   7: std::sync::once_lock::OnceLock<T>::initialize
   8: ort::session::builder::SessionBuilder::new
   9: yolov8_rs::ort_backend::OrtBackend::build
  10: yolov8_rs::model::YOLOv8::new
  11: <crossbeam_deque::deque::Injector<T> as core::ops::drop::Drop>::drop
```

@jamjamjon

**Comment by jamjamjon** [comment]
Yes, the part about onnxruntime linking in the readme has not been updated.

I submitted a PR that is pending review; this will make the inference of the YOLOv5-v11 model more straightforward and efficient.

**Comment by glenn-jocher** [comment]
Thank you for your contribution! We'll review your PR soon to ensure the improvements are integrated effectively.
