### ISSUE TITLE
Yolo11 : TensorRT export fails in orin-nano

### ISSUE THREAD

**Issue by ashish-roopan** [ultralytics/ultralytics#17338]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I am trying to export a custom yolo11 pose model in jetson orin nano 4gb , and followed this doc to set everthing up  : https://docs.ultralytics.com/guides/nvidia-jetson/

**This is the output of jetson_release**
```
Software part of jetson-stats 4.2.6 - (c) 2024, Raffaello Bonghi
Model: NVIDIA Jetson Orin NX Engineering Reference Developer Kit - Jetpack 6.0 DP [L4T 36.2.0]
NV Power Mode[0]: 10W
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3767-0004
 - Module: NVIDIA Jetson Orin Nano (4GB ram)
Platform:
 - Distribution: Ubuntu 22.04 Jammy Jellyfish
 - Release: 5.15.122-tegra
jtop:
 - Version: 4.2.6
 - Service: Active
Libraries:
 - CUDA: 12.2.140
 - cuDNN: 8.9.4.25
 - TensorRT: 8.6.2.3
 - VPI: 3.0.10
 - Vulkan: 1.3.204
 - OpenCV: 4.8.0 - with CUDA: NO
```

Here is my script for trt conversion
```
from ultralytics import YOLO
import argparse
import os


def rename(current_file_name, new_file_name):
	print('\n\n Moving file from {} to {}'.format(current_file_name, new_file_name))
	try:
		os.rename(current_file_name, new_file_name)
		print(f"File renamed from {current_file_name} to {new_file_name}")
	except FileNotFoundError:
		print(f"The file '{current_file_name}' does not exist.")
	except PermissionError:
		print("Permission denied. Please check your file permissions.")
	except Exception as e:
		print(f"An error occurred: {e}")


def parse_args():
        parser = argparse.ArgumentParser()
        parser.add_argument("-w", "--weights", default='weights/yolo11l-facepose-161024b.pt', help="weights Path")
        args = parser.parse_args()
        return args

args = parse_args()
model = YOLO(args.weights, task="pose")

imgsz = 640
batch = 8
workspace = 2

# TensorRT FP32
out = model.export(format="engine",
                   imgsz=imgsz,
                   dynamic=True,
                   verbose=False,
                   batch=batch,
                   workspace=workspace,
                   device="cuda:0")
rename(out, args.weights.replace(".pt", "-640x640-fp32.engine"))
```

**But after running this script, I am getting this error.** 
Note: The same script is working in a rtx3090 machine. And official tensorrt onnx parsing script is also working fine in the jetson nano.

```
Ultralytics 8.3.27 🚀 Python-3.10.12 torch-2.3.0 CUDA:0 (Orin, 3602MiB)
YOLO11l-face-pose summary (fused): 483 layers, 26,172,448 parameters, 0 gradients, 90.5 GFLOPs

PyTorch: starting from 'weights/yolo11l-facepose-161024b.pt' with input shape (8, 3, 640, 640) BCHW and output shape(s) (8, 72, 8400) (50.5 MB)

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: slimming with onnxslim 0.1.36...
ONNX: export success ✅ 125.2s, saved as 'weights/yolo11l-facepose-161024b.onnx' (100.1 MB)

TensorRT: starting export with TensorRT 8.6.2...
[11/04/2024-19:10:08] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 1360, GPU 3388 (MiB)
[11/04/2024-19:10:21] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1154, GPU +175, now: CPU 2550, GPU 3571 (MiB)
[11/04/2024-19:10:22] [TRT] [I] ----------------------------------------------------------------
[11/04/2024-19:10:22] [TRT] [I] Input filename:   weights/yolo11l-facepose-161024b.onnx
[11/04/2024-19:10:22] [TRT] [I] ONNX IR version:  0.0.10
[11/04/2024-19:10:22] [TRT] [I] Opset version:    17
[11/04/2024-19:10:22] [TRT] [I] Producer name:    pytorch
[11/04/2024-19:10:22] [TRT] [I] Producer version: 2.3.0
[11/04/2024-19:10:22] [TRT] [I] Domain:           
[11/04/2024-19:10:22] [TRT] [I] Model version:    0
[11/04/2024-19:10:22] [TRT] [I] Doc string:       
[11/04/2024-19:10:22] [TRT] [I] ----------------------------------------------------------------
[11/04/2024-19:10:23] [TRT] [W] onnx2trt_utils.cpp:372: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 72, -1) DataType.FLOAT
TensorRT: building FP32 engine as weights/yolo11l-facepose-161024b.engine
[11/04/2024-19:10:25] [TRT] [W] DLA requests all profiles have same min, max, and opt value. All dla layers are falling back to GPU
[11/04/2024-19:10:26] [TRT] [I] Graph optimization time: 0.217285 seconds.
[11/04/2024-19:10:26] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 952MB Available: 694MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 952MB Available: 693MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 952MB Available: 693MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 693MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 693MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 692MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 692MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 691MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 691MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 690MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 690MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 952MB Available: 690MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 689MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 689MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 689MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 689MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 689MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 689MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 952MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 952MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 688MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 687MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 687MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 687MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 687MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 686MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 685MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 685MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 685MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 685MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 950MB Available: 685MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 685MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 685MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 684MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 683MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 682MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 681MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 680MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 679MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 678MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 677MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 677MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 677MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 677MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 677MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 677MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 677MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [W] Tactic Device request: 1000MB Available: 676MB. Device memory is insufficient to use tactic.
[11/04/2024-19:10:27] [TRT] [E] 10: Could not find any implementation for node /model.0/conv/Conv.
[11/04/2024-19:10:27] [TRT] [E] 10: [optimizer.cpp::computeCosts::3869] Error Code 10: Internal Error (Could not find any implementation for node /model.0/conv/Conv.)
TensorRT: export failure ❌ 145.1s: __enter__
Traceback (most recent call last):
  File "/home/nvidia/code/yoloV11_test/common_utils/trt_export.py", line 34, in <module>
    out = model.export(format="engine",
  File "/home/nvidia/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/nvidia/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nvidia/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 324, in __call__
    f[1], _ = self.export_engine(dla=dla)
  File "/home/nvidia/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 144, in outer_func
    raise e
  File "/home/nvidia/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 139, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/nvidia/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 863, in export_engine
    with build(network, config) as engine, open(f, "wb") as t:
AttributeError: __enter__
```

Let me know if you need any more information regarding this issue. 

### Environment

Ultralytics 8.3.27 🚀 Python-3.10.12 torch-2.3.0 CUDA:0 (Orin, 3602MiB)
Setup complete ✅ (6 CPUs, 3.5 GB RAM, 106.3/115.4 GB disk)

### Minimal Reproducible Example

```from ultralytics import YOLO
import argparse
import os


def rename(current_file_name, new_file_name):
	print('\n\n Moving file from {} to {}'.format(current_file_name, new_file_name))
	try:
		os.rename(current_file_name, new_file_name)
		print(f"File renamed from {current_file_name} to {new_file_name}")
	except FileNotFoundError:
		print(f"The file '{current_file_name}' does not exist.")
	except PermissionError:
		print("Permission denied. Please check your file permissions.")
	except Exception as e:
		print(f"An error occurred: {e}")


def parse_args():
        parser = argparse.ArgumentParser()
        parser.add_argument("-w", "--weights", default='weights/yolo11l-facepose-161024b.pt', help="weights Path")
        args = parser.parse_args()
        return args

args = parse_args()
model = YOLO(args.weights, task="pose")

imgsz = 640
batch = 8
workspace = 2

# TensorRT FP32
out = model.export(format="engine",
                   imgsz=imgsz,
                   dynamic=True,
                   verbose=False,
                   batch=batch,
                   workspace=workspace,
                   device="cuda:0")
rename(out, args.weights.replace(".pt", "-640x640-fp32.engine"))
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ashish-roopan, thank you for your interest in Ultralytics 🚀! 

We recommend checking out the [Docs](https://docs.ultralytics.com) where you can find a wealth of information, including guidance on [exporting models](https://docs.ultralytics.com/modes/export/) which might help with your Jetson Orin Nano setup.

As this seems to be a 🐛 Bug Report, we'd greatly appreciate if you could provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us diagnose the issue. This will assist in replicating the error you're encountering during TensorRT export on your Jetson Orin Nano device.

In the meantime, make sure your Ultralytics environment is up-to-date to rule out any resolved issues:

```bash
pip install -U ultralytics
```

For additional context or peer support, consider joining the Ultralytics community. You can engage in real-time conversation on [Discord](https://ultralytics.com/discord) 🎧, explore discussions on our [Subreddit](https://reddit.com/r/ultralytics), or dive into more detailed threads at [Discourse](https://community.ultralytics.com).

## Environments

YOLO might work smoothly in one of our tested environments, which you can review or leverage:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM is available. Review our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. Check out our [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. Refer to the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

An Ultralytics engineer will assist you soon, and we appreciate your patience and contribution! 😊

**Comment by Y-T-G** [comment]
Try with `workspace=1`

**Comment by ambitious-octopus** [comment]
@lakshanthad can you help here?

**Comment by ashish-roopan** [comment]
> Try with `workspace=1`

I'm currently using 2gb as workspace. By reducing the workspace will if affect the performance of the model?

**Comment by Y-T-G** [comment]
It doesn't have enough free memory to use 2GB like the warning shows

**Comment by ashish-roopan** [comment]
> use 2GB like the warning shows

That makes sense. Thank you. I'll try that

**Comment by lakshanthad** [comment]
@ashish-roopan FYI the NVIDIA Jetson doc was verified with Jetson Orin NX 16GB which has enough RAM. But for Orin Nano 4GB, you might want to do ``workspace=1` as @Y-T-G mentioned.

**Comment by ashish-roopan** [comment]
> @ashish-roopan FYI the NVIDIA Jetson doc was verified with Jetson Orin NX 16GB which has enough RAM. But for Orin Nano 4GB, you might want to do `workspace=1` as @Y-T-G mentioned.

Hi @lakshanthad . I tried workspace=1 but still I am seeing the same issue

**Comment by Y-T-G** [comment]
Can you try with `dynamic=False` and `half=True`?

**Comment by ashish-roopan** [comment]
> Can you try with `dynamic=False` and `half=True`?

Acutally I need to get int8 model with dynamic shapes, If I try these values I will get a fp16 model with fixed shapes right?

**Comment by Y-T-G** [comment]
Yeah, but we need to know if it works with that.
