### ISSUE TITLE
max_shape Error with dynamic=True in TensorRT export

### ISSUE THREAD

**Issue by softJM** [ultralytics/ultralytics#17350]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Hello, ultralytics

When converting to TensorRT with dynamic=True, the following error occurs:

**Execution Script**
```
from ultralytics import YOLO

model = YOLO('yolo11l-seg.pt')

model.export(format='engine',
             dynamic=True,
             half=True,
             workspace=2.0)
```

**Error Message**
```
Invoked with: <tensorrt_bindings.tensorrt.IOptimizationProfile object at 0x759771716a70>, 
'images'; kwargs: min=(1, 3, 32, 32), opt=torch.Size([1, 3, 640, 640]), max=(1, 3, 1280.0, 1280.0)
```

It seems that the **max_shape** parameter receives a float value. Could you please help resolve this issue?
The code that calculates max_shape appears to be located here:

https://github.com/ultralytics/ultralytics/blob/603fa84774376b10d8783ffa9017f6b9b9b84861/ultralytics/engine/exporter.py#L794

Thank you!

### Environment

docker : `ultralytics/ultralytics:latest`

### Minimal Reproducible Example

**MRE :**
```
from ultralytics import YOLO

model = YOLO('yolo11l-seg.pt')

model.export(format='engine',
             dynamic=True,
             half=True,
             workspace=2.0)
```

**Error Message**
```
Traceback (most recent call last):
  File "/home/program/export.py", line 8, in <module>
    model.export(format='engine',
  File "/ultralytics/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 324, in __call__
    f[1], _ = self.export_engine(dla=dla)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 144, in outer_func
    raise e
  File "/ultralytics/ultralytics/engine/exporter.py", line 139, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 796, in export_engine
    profile.set_shape(inp.name, min=min_shape, opt=shape, max=max_shape)
TypeError: set_shape(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt_bindings.tensorrt.IOptimizationProfile, input: str, min: tensorrt_bindings.tensorrt.Dims, opt: tensorrt_bindings.tensorrt.Dims, max: tensorrt_bindings.tensorrt.Dims) -> None

Invoked with: <tensorrt_bindings.tensorrt.IOptimizationProfile object at 0x7f02fc605370>, 'images'; kwargs: min=(1, 3, 32, 32), opt=torch.Size([1, 3, 640, 640]), max=(1, 3, 1280.0, 1280.0)
```

**Dependencies:**
docker : `ultralytics/ultralytics:latest`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @softJM, thank you for reporting this issue with Ultralytics 🚀! An Ultralytics engineer will be with you soon to assist further.

In the meantime, we suggest checking if any updates could resolve your issue. You can upgrade to the latest `ultralytics` package with all requirements in a **Python>=3.8** environment with **PyTorch>=1.8** using the following command:

```bash
pip install -U ultralytics
```

Your issue pertains to the TensorRT export with `dynamic=True`, which might have variations in the shape parameter handling. Thank you for providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/); it will greatly assist in identifying the problem.

If you wish to engage further and explore solutions collectively, please join our supportive community:
- Chat with us in real time on [Discord](https://ultralytics.com/discord) 🎧.
- Engage in more detailed discussions on [Discourse](https://community.ultralytics.com).
- Dive into our [Subreddit](https://reddit.com/r/ultralytics) to share insights and experiences.

## Verified Environments

As you explore solutions, consider running YOLO in any of these verified environments with preinstalled dependencies:

- **Notebooks** with free GPU access: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM, see the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/).
- **Amazon** Deep Learning AMI, see the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).
- **Docker Image**, see the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

## Status

Check our [CI Status](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule). If this badge is green, all tests are passing:

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Thanks for bringing this to our attention, and we appreciate your patience while we work on a solution!

**Comment by Y-T-G** [comment]
Can you post the full error?

**Comment by softJM** [comment]
@Y-T-G 

```
PyTorch: starting from 'yolo11l-seg.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 116, 8400), (1, 32, 160, 160)) (53.5 MB)

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.36...
ONNX: export success ✅ 38.0s, saved as 'yolo11l-seg.onnx' (105.7 MB)

TensorRT: starting export with TensorRT 10.6.0...
[11/05/2024-02:59:26] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 828, GPU 526 (MiB)
[11/05/2024-02:59:33] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +962, GPU +194, now: CPU 1946, GPU 720 (MiB)
[11/05/2024-02:59:33] [TRT] [I] ----------------------------------------------------------------
[11/05/2024-02:59:33] [TRT] [I] Input filename:   yolo11l-seg.onnx
[11/05/2024-02:59:33] [TRT] [I] ONNX IR version:  0.0.10
[11/05/2024-02:59:33] [TRT] [I] Opset version:    19
[11/05/2024-02:59:33] [TRT] [I] Producer name:    pytorch
[11/05/2024-02:59:33] [TRT] [I] Producer version: 2.5.0
[11/05/2024-02:59:33] [TRT] [I] Domain:
[11/05/2024-02:59:33] [TRT] [I] Model version:    0
[11/05/2024-02:59:33] [TRT] [I] Doc string:
[11/05/2024-02:59:33] [TRT] [I] ----------------------------------------------------------------
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 116, -1) DataType.FLOAT
TensorRT: output "output1" with shape(-1, 32, -1, -1) DataType.FLOAT
TensorRT: WARNING ⚠️ 'dynamic=True' model requires max batch size, i.e. 'batch=16'
TensorRT: export failure ❌ 45.8s: set_shape(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt_bindings.tensorrt.IOptimizationProfile, input: str, min: tensorrt_bindings.tensorrt.Dims, opt: tensorrt_bindings.tensorrt.Dims, max: tensorrt_bindings.tensorrt.Dims) -> None

Invoked with: <tensorrt_bindings.tensorrt.IOptimizationProfile object at 0x7f02fc605370>, 'images'; kwargs: min=(1, 3, 32, 32), opt=torch.Size([1, 3, 640, 640]), max=(1, 3, 1280.0, 1280.0)
Traceback (most recent call last):
  File "/home/program/export.py", line 8, in <module>
    model.export(format='engine',
  File "/ultralytics/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 324, in __call__
    f[1], _ = self.export_engine(dla=dla)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 144, in outer_func
    raise e
  File "/ultralytics/ultralytics/engine/exporter.py", line 139, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 796, in export_engine
    profile.set_shape(inp.name, min=min_shape, opt=shape, max=max_shape)
TypeError: set_shape(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt_bindings.tensorrt.IOptimizationProfile, input: str, min: tensorrt_bindings.tensorrt.Dims, opt: tensorrt_bindings.tensorrt.Dims, max: tensorrt_bindings.tensorrt.Dims) -> None

Invoked with: <tensorrt_bindings.tensorrt.IOptimizationProfile object at 0x7f02fc605370>, 'images'; kwargs: min=(1, 3, 32, 32), opt=torch.Size([1, 3, 640, 640]), max=(1, 3, 1280.0, 1280.0)
```

**Comment by Y-T-G** [comment]
Does it work if you use `workspace=2` instead of `2.0`?

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear the issue is resolved. If you have any more questions, feel free to reach out.

**Comment by BraveYQY** [comment]
我在导出的时候也遇到了这个问题，大家可以检查一下 model.export 中的dynamic参数，它的值必须为False

**Comment by glenn-jocher** [comment]
感谢分享您的经验！确实，将 `dynamic` 参数设置为 `False` 是一种解决方法，但如果需要动态输入大小，可以检查输入值是否符合 TensorRT 的要求，例如确保 `min`、`opt` 和 `max` 形状都是整数并正确设置。如需进一步参考，请查看 [export 文档](https://docs.ultralytics.com/modes/export/)。

**Comment by liongliong** [comment]
您好，我在运行代码的时候也遇到了这个问题，并且我的workspace也正确设置了，请问你们遇到过这种类似的问题吗，我的tensorrt==8.6.1，ultralytics==8.3.146

!yolo export \
  model=moldet_yolo11l_960_doc.pt \
  format=engine \
  imgsz=960 \
  workspace=4 \
  batch=50 \
  dynamic=True


这个export代码执行报错：

  WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.146 🚀 Python-3.10.6 torch-2.7.0+cu126 CUDA:0 (Tesla V100-SXM2-32GB, 32501MiB)
YOLO11l summary (fused): 190 layers, 25,280,083 parameters, 0 gradients, 86.6 GFLOPs

PyTorch: starting from 'moldet_yolo11l_960_doc.pt' with input shape (50, 3, 960, 960) BCHW and output shape(s) (50, 5, 18900) (48.9 MB)

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.69...
ONNX: export success ✅ 7.2s, saved as 'moldet_yolo11l_960_doc.onnx' (97.0 MB)

TensorRT: starting export with TensorRT 8.6.1...
[09/29/2025-23:45:45] [TRT] [I] [MemUsageChange] Init CUDA: CPU +1, GPU +0, now: CPU 965, GPU 31188 (MiB)
[09/29/2025-23:45:53] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +424, GPU +72, now: CPU 1466, GPU 31260 (MiB)
[09/29/2025-23:45:53] [TRT] [I] ----------------------------------------------------------------
[09/29/2025-23:45:53] [TRT] [I] Input filename:   moldet_yolo11l_960_doc.onnx
[09/29/2025-23:45:53] [TRT] [I] ONNX IR version:  0.0.9
[09/29/2025-23:45:53] [TRT] [I] Opset version:    19
[09/29/2025-23:45:53] [TRT] [I] Producer name:    pytorch
[09/29/2025-23:45:53] [TRT] [I] Producer version: 2.7.0
[09/29/2025-23:45:53] [TRT] [I] Domain:           
[09/29/2025-23:45:53] [TRT] [I] Model version:    0
[09/29/2025-23:45:53] [TRT] [I] Doc string:       
[09/29/2025-23:45:53] [TRT] [I] ----------------------------------------------------------------
[09/29/2025-23:45:53] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 5, -1) DataType.FLOAT
ERROR ❌ TensorRT: export failure 15.0s: set_shape(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt_bindings.tensorrt.IOptimizationProfile, input: str, min: tensorrt_bindings.tensorrt.Dims, opt: tensorrt_bindings.tensorrt.Dims, max: tensorrt_bindings.tensorrt.Dims) -> None

Invoked with: <tensorrt_bindings.tensorrt.IOptimizationProfile object at 0x7fa0924b6ab0>, 'images'; kwargs: min=(1, 3, 32, 32), opt=torch.Size([50, 3, 960, 960]), max=(50, 3, 4123168604160, 4123168604160)
Traceback (most recent call last):
  File "/opt/mamba/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/mamba/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 983, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/mamba/lib/python3.10/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/opt/mamba/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 500, in __call__
    f[1], _ = self.export_engine(dla=dla)
  File "/opt/mamba/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 197, in outer_func
    raise e
  File "/opt/mamba/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 192, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 938, in export_engine
    export_engine(
  File "/opt/mamba/lib/python3.10/site-packages/ultralytics/utils/export.py", line 144, in export_engine
    profile.set_shape(inp.name, min=min_shape, opt=shape, max=max_shape)
TypeError: set_shape(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt_bindings.tensorrt.IOptimizationProfile, input: str, min: tensorrt_bindings.tensorrt.Dims, opt: tensorrt_bindings.tensorrt.Dims, max: tensorrt_bindings.tensorrt.Dims) -> None

Invoked with: <tensorrt_bindings.tensorrt.IOptimizationProfile object at 0x7fa0924b6ab0>, 'images'; kwargs: min=(1, 3, 32, 32), opt=torch.Size([50, 3, 960, 960]), max=(50, 3, 4123168604160, 4123168604160)

**Comment by Y-T-G** [comment]
You should update to latest Ultralytics. It's fixed.
