### ISSUE TITLE
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'

### ISSUE THREAD

**Issue by nlcfdwr** [ultralytics/ultralytics#17511]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

配置文件以及错误信息如下：from ultralytics import YOLO
model = YOLO("ultralytics/cfg/models/v8/yolov8-rtdetr.yaml",task="detect")
model.train(data="/home/up/myproject/ultralytics/ultralytics/cfg/datasets/VisDrone.yaml", cfg="ultralytics/cfg/default.yaml")  # train the model
![2024-11-13 11-37-04 的屏幕截图](https://github.com/user-attachments/assets/94eb4acb-5f5b-4007-86d1-18ccf34e23b7)

### Environment

Traceback (most recent call last):
  File "/home/up/anaconda3/envs/DL/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/up/anaconda3/envs/DL/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 894, in entrypoint
    check_dict_alignment(full_args_dict, {a: ""})
  File "/home/up/anaconda3/envs/DL/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 481, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'tests' is not a valid YOLO argument. 

    Arguments received: ['yolo', 'tests']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of {'pose', 'obb', 'segment', 'classify', 'detect'}
                MODE (required) is one of {'predict', 'track', 'export', 'val', 'train', 'benchmark'}
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco8.yaml model=yolo11n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolo11n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolo11n.pt data=coco8.yaml batch=1 imgsz=640

    4. Export a YOLO11n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolo11n-cls.pt format=onnx imgsz=224,128

    5. Streamlit real-time webcam inference GUI
        yolo streamlit-predict

    6. Ultralytics solutions usage
        yolo solutions count or in ['count', 'heatmap', 'queue', 'speed', 'workout', 'analytics', 'help'] source="path/to/video/file.mp4"

    7. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg
        yolo solutions help

    Docs: https://docs.ultralytics.com
    Solutions: https://docs.ultralytics.com/solutions/
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics

### Minimal Reproducible Example

from ultralytics import YOLO
model = YOLO("ultralytics/cfg/models/v8/yolov8-rtdetr.yaml",task="detect")
model.train(data="/home/up/myproject/ultralytics/ultralytics/cfg/datasets/VisDrone.yaml", cfg="ultralytics/cfg/default.yaml")  # train the model

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @nlcfdwr, thank you for bringing this to our attention 🚀! We understand that you're encountering an AttributeError related to 'RTDETRDecoder'. To assist us in diagnosing the issue more effectively, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)?

We recommend checking our [documentation](https://docs.ultralytics.com) for additional insights into the `YOLO` commands or any arguments you may be using. You might find useful examples in both [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage sections.

Please ensure your environment is updated. You can upgrade to the latest `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) setup:

```bash
pip install -U ultralytics
```

For environment setups, you can explore various verified setups like running on [Google Colab](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) or [Gradient](https://console.paperspace.com/github/ultralytics/ultralytics).

Join the Ultralytics community for further support or discussions. You can always catch up with real-time chats on [Discord](https://ultralytics.com/discord) 🎧. For more structured discussions, consider our [Discourse](https://community.ultralytics.com) or share your journey on [Reddit](https://reddit.com/r/ultralytics).

Although this is an automated response to guide you initially, an Ultralytics engineer will review your issue and assist you further soon. Your willingness to contribute with a PR is much appreciated too!

Thank you for your patience and cooperation 🙌!

**Comment by Y-T-G** [comment]
Can you provide the output after running this command in terminal: `yolo checks`?

**Comment by nlcfdwr** [comment]
@Y-T-G 
(DL) (base) up@UP:~/myproject/ultralytics$ yolo checks
Ultralytics 8.3.29 🚀 Python-3.8.19 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 4060 Ti, 7828MiB)
Setup complete ✅ (16 CPUs, 31.2 GB RAM, 56.2/139.7 GB disk)

OS                  Linux-5.15.0-125-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.19
Install             pip
RAM                 31.18 GB
Disk                56.2/139.7 GB
CPU                 12th Gen Intel Core(TM) i5-12600KF
CPU count           16
GPU                 NVIDIA GeForce RTX 4060 Ti, 7828MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.24.3>=1.23.0
matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.8>=2.0.0
numpy               ✅ 1.24.3<2.0.0; sys_platform == "darwin"
torch               ✅ 2.3.1!=2.4.0,>=1.8.0; sys_platform == "win32"

**Comment by nlcfdwr** [comment]
@Y-T-G Thank you very much for your answer, the problem has been solved

**Comment by wwowrd** [comment]
https://github.com/ultralytics/ultralytics/issues/17511#issue-2654048839
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'
Hello, I also encountered the same problem as you during training. If you have solved it, would you like to share the solution? thank you.
