### ISSUE TITLE
PermissionError on Windows 10

### ISSUE THREAD

**Issue by Arielfoever** [ultralytics/ultralytics#17539]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

```
E:\yolo\test>python
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from ultralytics import YOLO
>>> import os
>>> os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
>>> model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # 从YAML建立并转移权重
Transferred 355/355 items from pretrained weights
>>> torch.save(model, 'model.pt')
>>> results = model.train(data="dataset.yaml", epochs=5, imgsz=640, save=True, save_period=1)
Ultralytics 8.3.31 🚀 Python-3.12.7 torch-2.5.1+cu124 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
engine\trainer: task=detect, mode=train, model=yolov8n.yaml, data=dataset.yaml, epochs=5, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=1, cache=False, device=None, workers=8, project=None, name=train5, exist_ok=False, pretrained=yolov8n.pt, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train5

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, [64, 128, 256]]
YOLOv8n summary: 225 layers, 3,157,200 parameters, 3,157,184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Scanning E:\yolo\test\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 1
val: Scanning E:\yolo\test\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
    handle = dh.detach()
             ^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
    handle = dh.detach()
             ^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
    handle = dh.detach()
             ^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
  File "<string>", line 1, in <module>
    self = reduction.pickle.load(from_parent)
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    handle = dh.detach()
    self = reduction.pickle.load(from_parent)
             ^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach

  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
    return _winapi.DuplicateHandle(
    handle = dh.detach()
E:\yolo\test>           ^^^^^^^^^^^^^^^^^^^^^^^^
             ^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
    handle = dh.detach()
             ^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
Traceback (most recent call last):
    exitcode = _main(fd, parent_sentinel)
  File "<string>", line 1, in <module>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    exitcode = _main(fd, parent_sentinel)
    self = reduction.pickle.load(from_parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
Traceback (most recent call last):
    self = reduction.pickle.load(from_parent)
    handle = dh.detach()
  File "<string>", line 1, in <module>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    exitcode = _main(fd, parent_sentinel)
    handle = dh.detach()
    return _winapi.DuplicateHandle(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
             ^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
PermissionError: [WinError 5] 拒绝访问。
    self = reduction.pickle.load(from_parent)
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
PermissionError: [WinError 5] 拒绝访问。
    handle = dh.detach()
             ^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1167, in rebuild_pipe_connection
    handle = dh.detach()
             ^^^^^^^^^^^
  File "C:\Users\Ariel\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\reduction.py", line 131, in detach
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。
```

### Environment

```
E:\yolo\test>yolo checks
Ultralytics 8.3.31 🚀 Python-3.12.7 torch-2.5.1+cu124 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
Setup complete ✅ (20 CPUs, 63.8 GB RAM, 245.1/465.8 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.12.7
Install             pip
RAM                 63.80 GB
Disk                245.1/465.8 GB
CPU                 12th Gen Intel Core(TM) i9-12900H
CPU count           20
GPU                 NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB
GPU count           1
CUDA                12.4

numpy               ✅ 1.26.4>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.1+cu124>=1.8.0
torchvision         ✅ 0.20.1+cu124>=0.9.0
tqdm                ✅ 4.67.0>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.11>=2.0.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
torch               ✅ 2.5.1+cu124!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

```
import torch
from ultralytics import YOLO
import os  


def main():
    
    # Load a model
    # model = YOLO("yolo8n.yaml")  # build from YAML and transfer weights
    model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # 从YAML建立并转移权重
    # Train the model
    results = model.train(data="dataset.yaml", epochs=5, imgsz=640, save=True, save_period=1, workers=0)

    torch.save(model, 'model.pt')



if __name__ == '__main__':
    os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
    main()

```

### Additional

I thought it is related to https://github.com/ultralytics/yolov5/issues/8626 however this solution doesn't work.

If you use this python script, you will get something lijke this and no pt file will be created.

```
Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Scanning E:\yolo\test\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 1
val: Scanning E:\yolo\test\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Arielfoever, thank you for your interest in Ultralytics 🚀! We're sorry to hear you're experiencing this issue. An Ultralytics engineer will assist you soon.

In the meantime, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) of the problem? This will help us debug more effectively.

For reference, make sure you have upgraded to the latest version of the `ultralytics` package and all its [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml). You can do so in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

### Environments

YOLO can be run in the following verified environments, which come pre-installed with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See our [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

### Community and Support

Connect with the Ultralytics community for additional support:
- Chat on [Discord](https://ultralytics.com/discord) 🎧
- Join in-depth discussions on [Discourse](https://community.ultralytics.com)
- Share knowledge on our [Subreddit](https://reddit.com/r/ultralytics) 

Keep an eye on your issue for a response from our team and thank you for your patience! 😊

**Comment by Arielfoever** [comment]
This problem has nothing to do with whether you run the program as an administrator. I tried both of them.

**Comment by Y-T-G** [comment]
You can try creating a new env and reinstalling ultralytics and torch again.

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/16676#issuecomment-2392743356

**Comment by Arielfoever** [comment]
> [#16676 (comment)](https://github.com/ultralytics/ultralytics/issues/16676#issuecomment-2392743356)

I get python 11 and it works. thanks very much.

However, maybe we should somehow solve this problem while we have python 13 (x

**Comment by Y-T-G** [comment]
It's a bug with Python. Not really Ultralytics.
