### ISSUE TITLE
I ran into problem when training VisDrone with YOLOv11

### ISSUE THREAD

**Issue by Zhiyehhh** [ultralytics/ultralytics#17536]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using YOLOv11 to train the pre-downloaded VisDrone dataset, but every time the first training finishes, it throws the following error:

> `Traceback (most recent call last):
  File "train.py", line 14, in <module>
    model.train(
  File "/hy-tmp/yolo/ultralytics/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/hy-tmp/yolo/ultralytics/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/hy-tmp/yolo/ultralytics/ultralytics/engine/trainer.py", line 432, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/hy-tmp/yolo/ultralytics/ultralytics/engine/trainer.py", line 605, in validate
    metrics = self.validator(self)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/hy-tmp/yolo/ultralytics/ultralytics/engine/validator.py", line 197, in __call__
    stats = self.get_stats()
  File "/hy-tmp/yolo/ultralytics/ultralytics/models/yolo/detect/val.py", line 181, in get_stats
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
  File "/hy-tmp/yolo/ultralytics/ultralytics/models/yolo/detect/val.py", line 181, in <dictcomp>
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
RuntimeError: torch.cat(): expected a non-empty list of Tensors`

This is the code for my training model:

> `from ultralytics import YOLO

if __name__ == '__main__':

  model = YOLO('/hy-tmp/yolo/ultralytics/ultralytics/cfg/models/11/yolo11.yaml', task="detect") # 不使用预训练权重训练 | detect, segment, classify, pose, obb

  model.train(

    data='/hy-tmp/yolo/ultralytics/ultralytics/cfg/datasets/VisDrone.yaml',

    epochs=20, # (int) 训练的周期数

    patience=15, # (int) 等待无明显改善以进行早期停止的周期数

    batch=32, # (int) 每批次的图像数量（-1 为自动批处理）

    imgsz=640, # (int) 输入图像的大小，整数或w，h

    save=True, # (bool) 保存训练检查点和预测结果

    save_period=-1, # (int) 每x周期保存检查点（如果小于1则禁用）

    cache=True, # (bool) True/ram、磁盘或False。使用缓存加载数据

    device='', # (int | str | list, optional) 运行的设备，例如 cuda device=0 或 device=0,1,2,3 或 device=cpu

    workers=8, # (int) 数据加载的工作线程数（每个DDP进程）

    project='runs/train', # (str, optional) 项目名称

    name='exp', # (str, optional) 实验名称，结果保存在'project/name'目录下

    pretrained=True, # (bool | str) 是否使用预训练模型（bool），或从中加载权重的模型（str）

    optimizer='SGD', # (str) 要使用的优化器，选择=[SGD，Adam，Adamax，AdamW，NAdam，RAdam，RMSProp，auto]

    verbose=True, # (bool) 是否打印详细输出

    seed=0, # (int) 用于可重复性的随机种子

    close_mosaic=0, # (int) 在最后几个周期禁用马赛克增强

    resume=False, # (bool) 从上一个检查点恢复训练

    amp=False, # (bool) 自动混合精度（AMP）训练，选择=[True, False]，True运行AMP检查

  )`

**Comment by UltralyticsAssistant** [comment]
👋 Hello @wunengkuangnu2003, thank you for reaching out and for using Ultralytics 🚀! This is an automated response, and an Ultralytics engineer will also assist you soon.

To help us understand the issue you're facing with training YOLOv11 on the VisDrone dataset, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This includes the specific dataset location, configuration settings, or any other environmental details necessary to replicate the error 🐛.

While you wait, make sure you've checked out our [Docs](https://docs.ultralytics.com) for guidance and examples on YOLO usage. You might find our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/) particularly helpful for improving your training process. 📚

For further community assistance, you can join our real-time chat on [Discord](https://ultralytics.com/discord) 🎧, visit our forums on [Discourse](https://community.ultralytics.com) for discussions, or engage with fellow users on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade
Make sure to upgrade to the latest version of our `ultralytics` package and verify that all dependencies are up to date in a Python>=3.8 environment with PyTorch>=1.8:

```bash
pip install -U ultralytics
```

## Environment Options
You can also try running your training in one of these verified environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See our [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. Check out the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

When the CI badge is green, it means all tests for YOLO operations are passing. CI tests cover macOS, Windows, and Ubuntu on each commit and every 24 hours.

Thank you again for your patience and contribution to improving Ultralytics! 😊

**Comment by Y-T-G** [comment]
Can you provide the output after running this command in terminal: `yolo checks`?

**Comment by wunengkuangnu2003** [comment]
> Can you provide the output after running this command in terminal: `yolo checks`?

Here is the output message：
'''
Ultralytics 8.3.31 🚀 Python-3.9.0 torch-2.5.1+cpu CPU (13th Gen Intel Core(TM) i7-13700H)
Setup complete ✅ (20 CPUs, 31.1 GB RAM, 65.7/143.1 GB disk)

OS                  Linux-6.8.0-48-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.9.0
Install             git
RAM                 31.07 GB
Disk                65.7/143.1 GB
CPU                 13th Gen Intel Core(TM) i7-13700H
CPU count           20
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.26.3>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.5.1+cpu>=1.8.0
torchvision         ✅ 0.20.1+cpu>=0.9.0
tqdm                ✅ 4.67.0>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.11>=2.0.0
numpy               ✅ 1.26.3<2.0.0; sys_platform == "darwin"
torch               ✅ 2.5.1+cpu!=2.4.0,>=1.8.0; sys_platform == "win32"
'''

**Comment by Y-T-G** [comment]
Is it the original ultralytics code or did you modify it?

**Comment by risingClouds** [comment]
hello, do you solve the problem? I met the same today.

**Comment by risingClouds** [comment]
> > `Traceback (most recent call last):   File "train.py", line 14, in <module>     model.train(   File "/hy-tmp/yolo/ultralytics/ultralytics/engine/model.py", line 802, in train     self.trainer.train()   File "/hy-tmp/yolo/ultralytics/ultralytics/engine/trainer.py", line 207, in train     self._do_train(world_size)   File "/hy-tmp/yolo/ultralytics/ultralytics/engine/trainer.py", line 432, in _do_train     self.metrics, self.fitness = self.validate()   File "/hy-tmp/yolo/ultralytics/ultralytics/engine/trainer.py", line 605, in validate     metrics = self.validator(self)   File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context     return func(*args, **kwargs)   File "/hy-tmp/yolo/ultralytics/ultralytics/engine/validator.py", line 197, in __call__     stats = self.get_stats()   File "/hy-tmp/yolo/ultralytics/ultralytics/models/yolo/detect/val.py", line 181, in get_stats     stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy   File "/hy-tmp/yolo/ultralytics/ultralytics/models/yolo/detect/val.py", line 181, in <dictcomp>     stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy RuntimeError: torch.cat(): expected a non-empty list of Tensors`

Ok, In my case, I use soft link to link dataset path to my project. which lead uncorrect val.cache.I modify dataset path to absolute path in my config. It works

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution! It’s great to hear that using an absolute path in your config resolved the issue. If you have any more questions or need further assistance, feel free to reach out.
