### ISSUE TITLE
Primitive descriptor error in custom model training

### ISSUE THREAD

**Issue by YavuzMuratt** [ultralytics/ultralytics#17563]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've modified the YOLO11 model yaml and added my blocks to tasks.py. When I start training I get this error:

:\Users\Murat Yavuz\Desktop\YavuzMurat\ModelTrain\data>yolo train model=yolo11.yaml data=data.yaml epochs=100 imgsz=640

Error decoding JSON from C:\Users\Murat Yavuz\AppData\Roaming\Ultralytics\persistent_cache.json. Starting with an empty dictionary.
WARNING ⚠️ no model scale passed. Assuming scale='n'.
C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\init.py:511: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\cfg\__init__.py", line 940, in entrypoint
    model = YOLO(model, task=task)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\model.py", line 143, in __init__
    self._new(model, task=task, verbose=verbose)
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\model.py", line 251, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 336, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in _forward(torch.zeros(1, ch, s, s))])  # forward
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 334, in _forward
    return self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
                                                                          ^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 112, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 130, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 151, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\modules\conv.py", line 169, in forward
    y = self.cv1(x)
        ^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\nn\modules\conv.py", line 50, in forward
    return self.act(self.bn(self.conv(x)))
                            ^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Murat Yavuz\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: could not create a primitive descriptor for a convolution forward propagation primitive

What can I try to solve this?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @YavuzMuratt, thank you for reaching out and for your interest in Ultralytics 🚀! This is an automated response to help guide you, and rest assured, an Ultralytics engineer will look into your issue shortly.

We recommend visiting the [Ultralytics Documentation](https://docs.ultralytics.com) where you can find various [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples. These resources might already contain answers to your question.

If this is a 🐛 Bug Report, it would be very helpful for us if you could provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to aid in debugging the issue. This should include any modifications you made to the model YAML or `tasks.py`.

If your inquiry is regarding custom training ❓, please include more details, such as dataset image examples, training logs, and ensure you're following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

For real-time interaction with the community, you might join us on [Discord](https://ultralytics.com/discord) 🎧. If you prefer more detailed discussions, [Discourse](https://community.ultralytics.com) is a great place, and for community knowledge sharing, you can jump into our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

To ensure your issue isn't related to an outdated version, please upgrade to the latest `ultralytics` package with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), ensuring you're using [**Python>=3.8**](https://www.python.org/) and [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLO runs smoothly in the following environments with all dependencies, including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/), pre-installed:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, it indicates all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing. CI tests ensure all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) run correctly on macOS, Windows, and Ubuntu, both every 24 hours and with every commit.

Thanks again for reaching out, and we hope to resolve your issue soon! 😊

**Comment by Y-T-G** [comment]
Seems like an issue with your PyTorch installation

**Comment by YavuzMuratt** [comment]
> Seems like an issue with your PyTorch installation

I've reinstalled the packages and checked that the trainings with default models works fine.

I just added 2 new classes to blocks.py and imported them into tasks.py's parse_model func. The error traceback doesn't point my additions tho

**Comment by glenn-jocher** [comment]
Based on the error message showing "could not create a primitive descriptor for a convolution forward propagation primitive", this appears to be a CUDA/PyTorch compatibility issue rather than a problem with your custom model additions. Since you've confirmed default models work, please verify your custom blocks maintain the same input/output tensor dimensions as the original architecture. You can enable debug logging with `yolo settings debug=True` to trace the exact layer where the error occurs.

For guidance on properly extending YOLO models with custom blocks, see https://docs.ultralytics.com/usage/engine/#customizing-the-model-architecture
