### ISSUE TITLE
Exporting RT-DETR to TensorRT: model validation is not working

### ISSUE THREAD

**Issue by isuchy** [ultralytics/ultralytics#17581]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

**Export**

### Bug

Hi there, 
it is impossible to successfully export Ultralytics RT-DETR model to TensorRT, both as FP16 and with quantization to INT8.

```
CUDA available: True
CUDA version: 12.1
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.32 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
rtdetr-resnet50 summary: 440 layers, 41,936,739 parameters, 0 gradients, 125.6 GFLOPs

PyTorch: starting from 'best.pt' with input shape (16, 3, 640, 640) BCHW and output shape(s) (16, 300, 5) (82.0 MB)

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.39...
ONNX: export success ✅ 114.5s, saved as 'best.onnx' (160.4 MB)

TensorRT: starting export with TensorRT 10.6.0...
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 300, 5) DataType.FLOAT
TensorRT: building INT8 engine as best.engine
TensorRT: collecting INT8 calibration images from 'data=/content/datasets/data.yaml'
Scanning /content/datasets/val/labels.cache... 146 images, 0 backgrounds, 0 corrupt: 100%|██████████| 146/146 [00:00<?, ?it/s]TensorRT: WARNING ⚠️ >300 images recommended for INT8 calibration, found 146 images.

TensorRT: export success ✅ 708.0s, saved as 'best.engine' (51.0 MB)

Export complete (710.0s)
Results saved to /content
Predict:         yolo predict task=detect model=best.engine imgsz=640 int8 
Validate:        yolo val task=detect model=best.engine imgsz=640 data=/content/datasets/data.yaml int8 
Visualize:       https://netron.app/
```

It is not possible to validate the exported engine model, since the export was obviously not done correctly.
This is what the CLI `val` command looks like:
```
!yolo val task=detect model=best.engine imgsz=640 data=/content/datasets/data.yaml int8
```

Here's the output:
```
Ultralytics 8.3.32 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
Loading best.engine for TensorRT inference...
[11/16/2024-21:37:41] [TRT] [I] Loaded engine size: 49 MiB
[11/16/2024-21:37:41] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +1, GPU +76, now: CPU 1, GPU 120 (MiB)
val: Scanning /content/datasets/val/labels.cache... 146 images, 0 backgrounds, 0 corrupt: 100% 146/146 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 146/146 [00:03<00:00, 38.42it/s]
                   all        146        517          0          0          0          0
Speed: 0.8ms preprocess, 10.6ms inference, 0.0ms loss, 9.0ms postprocess per image
Results saved to runs/detect/val2
💡 Learn more at https://docs.ultralytics.com/modes/val
```

### Environment

Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics 8.3.32 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 32.5/235.7 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
Disk                32.5/235.7 GB
CPU                 Intel Xeon 2.00GHz
CPU count           2
GPU                 Tesla T4, 15102MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.26.4>=1.23.0
matplotlib          ✅ 3.8.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.5.1+cu121>=1.8.0
torchvision         ✅ 0.20.1+cu121>=0.9.0
tqdm                ✅ 4.66.6>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.11>=2.0.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
torch               ✅ 2.5.1+cu121!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```
import torch
from ultralytics import RTDETR

# Check CUDA availability
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")

# Load the RT-DETR model using Ultralytics
model = RTDETR('best.pt')

# Set model to eval mode
model.model.eval()

# Export to TensorRT INT8
model.export(
    format="engine",
    dynamic=True,  
    batch=16,  
    workspace=4, 
    int8=True,
    data="/content/datasets/data.yaml",  
)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @isuchy, thank you for bringing this to our attention and for using Ultralytics 🚀! This is an automated response, but rest assured that an Ultralytics engineer will assist you soon.

For the issue of exporting the RT-DETR model to TensorRT, it seems you are encountering warnings during the export process. To better assist you with this 🐛 bug report, it's great that you've already provided a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). If you have any additional details or logs that could help pinpoint the issue, please feel free to include them as well.

In the meantime, we highly recommend visiting the [Ultralytics Docs](https://docs.ultralytics.com) for more insights and checking out the [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples.

### Upgrade

Ensure that you have the latest version of the `ultralytics` package and all its [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml). You can upgrade to the latest version using:

```bash
pip install -U ultralytics
```

### Environments

For running YOLO, please confirm you are using one of the recommended environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI: [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

### Community Support

Join our community for more assistance:
- [Discord](https://ultralytics.com/discord) 🎧 for real-time chat.
- [Discourse](https://community.ultralytics.com) for in-depth discussions.
- [Subreddit](https://reddit.com/r/ultralytics) for community knowledge sharing.

Stay tuned for further updates, and thank you for your patience!

**Comment by Skillnoob** [comment]
`model.model.eval()`. Don't do this, its not a thing you're supposed to do with ultralytics.

**Comment by isuchy** [comment]
Hi, I've re-trained the PyTorch model, everything worked fine including the validation which is started by default after the training process. You can see the result here:
```
Validating runs/detect/train/weights/best.pt...
Ultralytics 8.3.32 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA L4, 22700MiB)
rt-detr-l summary: 502 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.12it/s]
                   all        246        750      0.889      0.885      0.921      0.566
Speed: 0.2ms preprocess, 8.5ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to runs/detect/train
```
If I run the validation of the trained model with this CLI command
`!yolo val task=detect model=/content/runs/detect/train-weights/best.pt imgsz=640 data=/content/datasets/data.yaml`

script crashes and outputs the following error:
```
Ultralytics 8.3.32 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA L4, 22700MiB)
rtdetr-resnet50 summary: 440 layers, 41,936,739 parameters, 0 gradients, 125.6 GFLOPs
val: Scanning /content/datasets/valid/labels.cache... 246 images, 50 backgrounds, 0 corrupt: 100% 246/246 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0% 0/246 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 969, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 635, in val
    validator(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py", line 191, in __call__
    self.update_metrics(preds, batch)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/val.py", line 159, in update_metrics
    self.confusion_matrix.process_batch(predn, bbox, cls)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/metrics.py", line 337, in process_batch
    self.matrix[dc, self.nc] += 1  # false positives
IndexError: index 16 is out of bounds for axis 0 with size 2
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

I don't think I did anything wrong, I haven't had this problem in the past. It is probably a bug.

**Comment by isuchy** [comment]
> Hi, I've re-trained the PyTorch model, everything worked fine including the validation which is started by default after the training process. You can see the result here:
> 
> ```
> Validating runs/detect/train/weights/best.pt...
> Ultralytics 8.3.32 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA L4, 22700MiB)
> rt-detr-l summary: 502 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
>                  Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.12it/s]
>                    all        246        750      0.889      0.885      0.921      0.566
> Speed: 0.2ms preprocess, 8.5ms inference, 0.0ms loss, 0.3ms postprocess per image
> Results saved to runs/detect/train
> ```
> 
> If I run the validation of the trained model with this CLI command `!yolo val task=detect model=/content/runs/detect/train/weights/best.pt imgsz=640 data=/content/datasets/data.yaml`
> 
> script crashes and outputs the following error:
> 
> ```
> Ultralytics 8.3.32 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (NVIDIA L4, 22700MiB)
> rtdetr-resnet50 summary: 440 layers, 41,936,739 parameters, 0 gradients, 125.6 GFLOPs
> val: Scanning /content/datasets/valid/labels.cache... 246 images, 50 backgrounds, 0 corrupt: 100% 246/246 [00:00<?, ?it/s]
>                  Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0% 0/246 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/usr/local/bin/yolo", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 969, in entrypoint
>     getattr(model, mode)(**overrides)  # default args from model
>   File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 635, in val
>     validator(model=self.model)
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py", line 191, in __call__
>     self.update_metrics(preds, batch)
>   File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/val.py", line 159, in update_metrics
>     self.confusion_matrix.process_batch(predn, bbox, cls)
>   File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/metrics.py", line 337, in process_batch
>     self.matrix[dc, self.nc] += 1  # false positives
> IndexError: index 16 is out of bounds for axis 0 with size 2
> Sentry is attempting to send 2 pending events
> Waiting up to 2 seconds
> Press Ctrl-C to quit
> ```
> 
> I don't think I did anything wrong, I haven't had this problem in the past. It is probably a bug.

Apparently I found the root cause and definitely it's not a bug. My Roboflow dataset has Auto-Orient applied in preprocessing.  Therefore I need to export it in YOLOv8 OBB (Oriented Bounding Boxes) format and then the confusion matrix update in the validator should work.

**Comment by glenn-jocher** [comment]
It seems like the issue was related to the dataset orientation settings. Using the YOLOv8 OBB format for datasets with Auto-Orient preprocessing should indeed resolve the confusion matrix update error. If you have further questions, feel free to reach out. The YOLO community and Ultralytics team are here to support you!
