### ISSUE TITLE
how can  process local img file  when "yolo predict model=yolo11n.pt source=XXX.jpg" ?

### ISSUE THREAD

**Issue by ddddddeyrueuad** [ultralytics/ultralytics#17584]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how can  process local img file  when "yolo predict model=yolo11n.pt source=XXX.jpg" ?  

### Additional

(med) D:\med>yolo predict model=yolo11n.pt source='C:\Users\Administrator\Pictures\ks.jpg'
Ultralytics 8.3.32 🚀 Python-3.10.15 torch-2.5.1+cpu CPU (12th Gen Intel Core(TM) i5-12490F)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\med\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\envs\med\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\envs\med\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\ultralytics\cfg\__init__.py", line 969, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\ultralytics\engine\model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\ultralytics\engine\predictor.py", line 184, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\torch\utils\_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\ultralytics\engine\predictor.py", line 227, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\ultralytics\engine\predictor.py", line 199, in setup_source
    self.dataset = load_inference_source(
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\ultralytics\data\build.py", line 202, in load_inference_source
    dataset = LoadImagesAndVideos(source, batch=batch, vid_stride=vid_stride)
  File "C:\ProgramData\miniconda3\envs\med\lib\site-packages\ultralytics\data\loaders.py", line 341, in __init__
    raise FileNotFoundError(f"{p} does not exist")
FileNotFoundError: 'C:\Users\Administrator\Pictures\ks.jpg' does not exist

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ddddddeyrueuad, thank you for reaching out and showing interest in Ultralytics 🚀! It seems you're encountering an issue with processing a local image using the `yolo predict` command. 

For new users, we highly recommend checking out our [Docs](https://docs.ultralytics.com) where you can find many examples and answers to common questions. Specifically, you might find the [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage guides helpful.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that demonstrates the problem. This will help us understand the issue better.

An Ultralytics engineer will review your issue soon to provide further assistance. In the meantime, make sure to verify that your image path is correct and that the file `ks.jpg` actually exists in the specified location.

Join our community too if you have more questions or want to connect with other users. For real-time chat, visit [Discord](https://ultralytics.com/discord) 🎧. For discussions, check out [Discourse](https://community.ultralytics.com) or our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure you are using the latest version of the `ultralytics` package and all its [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml). Verify this in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

Consider using one of these up-to-date environments for a smoother experience:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**, **Amazon AWS**, or **Docker**. See our guides for setting these up.

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, then all of Ultralytics' continuous integration tests are currently passing across all supported platforms. 

Hang tight, as more help is on the way! 😊

**Comment by Y-T-G** [comment]
You need to provide full path to the image
