### ISSUE TITLE
how to work trackeval with yolo and personpath22

### ISSUE THREAD

**Issue by ramafahad** [ultralytics/ultralytics#17604]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on Google Colab because I don't have enough space in my laptop. I have my yolo model and have cloned the trackeval repository to test on the personpath22 dataset, I ran this code from ultralytics import YOLO
import os

# Load trained model
model = YOLO("/content/drive/MyDrive/best.pt")

path = "/content/drive/MyDrive/dataset/personpath22/raw_data"
dir = os.listdir(path)

for file in dir:
  if file.endswith((".avi",".mp4","wmv")):
    # Perform tracking on your video or image sequence
    results = model.track(source='/content/drive/MyDrive/dataset/personpath22/raw_data/'+file)

    # Save results in MOTChallenge format (frame, id, bbox, conf)
    with open(f"/content/drive/MyDrive/TRACKER_FOLDER/person_path_22-test/custom_tracker/data/{file}.txt", 'w') as f:
        for frame_id, result in enumerate(results):
            for box in result.boxes:
                # Check if box.id is not None before accessing its attributes
                if box.id is not None:
                    bbox = box.xyxy[0].tolist()  # Convert from tensor to list
                    track_id = box.id.item()  # Get track id
                    conf = box.conf.item()  # Get confidence score
                    f.write(f'{frame_id+1},{track_id},{bbox[0]},{bbox[1]},{bbox[2]-bbox[0]},{bbox[3]-bbox[1]},-1,-1,{conf}\n')
which gave me the tracking result of the model, than I ran this code 
!python scripts/run_person_path_22.py --BENCHMARK MOT20 --TRACKERS_TO_EVAL YOLOv8x --TRACKERS_FOLDER /content/drive/MyDrive/TRACKER_FOLDER --GT_FOLDER /content/drive/MyDrive/tracking-dataset/dataset/personpath22/annotation/anno_amodal_2022
but it keeps saying there's no seqini file despite it being there:
Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 8                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /content/drive/MyDrive/TrackEval/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

PersonPath22 Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /content/drive/MyDrive/TrackEval/data/gt/person_path_22
TRACKERS_FOLDER      : /content/drive/MyDrive/TRACKER_FOLDER
OUTPUT_FOLDER        : ['/content/eval_results.txt'] 
TRACKERS_TO_EVAL     : ['MyTracker']                 
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : MOT20                         
SPLIT_TO_EVAL        : test                          
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : None                          
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : False                         
Traceback (most recent call last):
  File "/content/drive/MyDrive/TrackEval/scripts/run_person_path_22.py", line 105, in <module>
    dataset_list = [trackeval.datasets.PersonPath22(dataset_config)]
  File "/content/drive/MyDrive/TrackEval/trackeval/datasets/person_path_22.py", line 81, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "/content/drive/MyDrive/TrackEval/trackeval/datasets/person_path_22.py", line 167, in _get_seq_info
    raise TrackEvalException('ini file does not exist: ' + seq + '/' + os.path.basename(ini_file))
trackeval.utils.TrackEvalException: ini file does not exist: uid_vid_00008.mp4/seqinfo.ini
 I think it is a path problem but can someone provide the correct path format so I can adjust my files to it?

**Comment by Y-T-G** [comment]
The error is not ultralytics related. You can open an issue on the trackeval repo
