### ISSUE TITLE
The FastSAM module doesn't handle the case where no results are detected

### ISSUE THREAD

**Issue by petercham** [ultralytics/ultralytics#17623]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

!!! Exception during processing !!! 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\face_nodes.py", line 340, in swap_faces
    face_masks, _, _, _, _ = segmentor.predict(cropped_img, segment_model, conf=0.9, iou=0.8, valid=False, text=None, box=None, point=crop_center, sort_method="original")
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\segment_nodes.py", line 179, in predict
    return super().predict(image, fast_sam_model, conf, iou, valid, add_params, sort_method, debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\segment_nodes.py", line 54, in predict
    results = model.get(image, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\predictor.py", line 161, in _predict_process
    result = self.get_result(img, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\predictor.py", line 334, in get_result
    results, max_conf, best_size = self.segm_size_prob(source, orig_left, orig_right, target_conf, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\predictor.py", line 555, in segm_size_prob
    results = self._predict(source, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\ultralytics_fastsam.py", line 55, in _predict
    return self.model(source, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\fastsam\model.py", line 50, in predict
    return super().predict(source, stream, prompts=prompts, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\predictor.py", line 169, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\predictor.py", line 262, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\fastsam\predict.py", line 44, in postprocess
    return self.prompt(results, bboxes=bboxes, points=points, labels=labels, texts=texts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\fastsam\predict.py", line 67, in prompt
    masks = result.masks.data
            ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

This error does not occur if the target is detected, but if it is not detected in the predicted image it will still try to extract tasks.data in fastsam/predict.py.

### Environment

** ComfyUI startup time: 2024-11-19 11:24:07.765844
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\Work\SD-ComfyUI\python_embeded\python.exe
** ComfyUI Path: C:\Work\SD-ComfyUI\ComfyUI
** Log path: C:\Work\SD-ComfyUI\comfyui.log

Prestartup times for custom nodes:
   3.5 seconds: C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Set cuda device to: 0
Total VRAM 24564 MB, total RAM 64735 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Forcing FP16.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
HJH Check ONNXRuntime Ver. 1.18.0
ultralytics ver.8.3.33

### Minimal Reproducible Example

class FastSAMSegment:
    ......
    results = self._predict(source, **kwargs)
    ......
    def _predict(self, source, **kwargs):
        logger.info(f"FastSAMSegment source.shape: {source.shape}, kwargs: {kwargs}")
        return self.model(source, **kwargs)

Print debugging information:
2024-11-19 11:26:12.553 | INFO     | ComfyUI_Hjh_nodes.predict.ultralytics_fastsam:_predict:54 - FastSAMSegment source.shape: (715, 715, 3), kwargs: {'conf': 0.56, 'iou': 0.8, 'retina_masks': True, 'points': [357.5, 357.5], 'imgsz': 256}

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @petercham, thank you for reporting this issue with the FastSAM module in Ultralytics 🚀! We appreciate your detailed description and stack trace, which are very helpful.

If this is a 🐛 Bug Report, it would be beneficial to provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so that we can further investigate the issue. It seems you started pointing towards one, but a complete script would help our engineers simulate your environment more accurately.

For resolving this issue in your environment, first ensure that you've updated to the latest `ultralytics` package, as improvements and bug fixes are continuously made. Use the following command to upgrade:

```bash
pip install -U ultralytics
```

Make sure that your setup meets all the [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) with a compatible environment of [**Python>=3.8**](https://www.python.org/) and [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

For additional support, join our Ultralytics community. For real-time help, you can join the conversations on [Discord](https://ultralytics.com/discord) 🎧. You can also engage in discussions on our [Discourse](https://community.ultralytics.com) or share insights on our [Subreddit](https://reddit.com/r/ultralytics).

## Environments

You can try running YOLO in any of these verified environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM with instructions in our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** AMI setup as per [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image** with the setup guide [here](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, which checks correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Windows, and Ubuntu.

This is an automated response, and an Ultralytics engineer will also assist you soon. Thanks for your patience and collaboration! 😊

**Comment by petercham** [comment]
![20241119-120042](https://github.com/user-attachments/assets/0b6a2a29-1170-4153-9485-4a93a3b7730d)
Pictures of what went wrong
