### ISSUE TITLE
module 'torch' has no attribute 'OutOfMemoryError'

### ISSUE THREAD

**Issue by MoussaGRICHE** [ultralytics/ultralytics#17660]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello,
I traied to train an yolo11 model but I get this error with torch.

C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [2789,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [2789,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:92: block: [2789,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
      1/100      18.9G      9.346      40.84       8.48         48        640:   0%|          | 3/875 [00:04<19:56,  1.37s/it]
Traceback (most recent call last):
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\utils\tal.py", line 74, in forward
    return self._forward(pd_scores, pd_bboxes, anc_points, gt_labels, gt_bboxes, mask_gt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\utils\tal.py", line 102, in _forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(
                                       ^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\utils\tal.py", line 124, in get_pos_mask
    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_in_gts * mask_gt)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\utils\tal.py", line 143, in get_box_metrics
    bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\ProgramData\miniconda3\envs\YOLO11\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\cfg\__init__.py", line 969, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\engine\model.py", line 802, in train
    self.trainer.train()
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\engine\trainer.py", line 380, in _do_train
    self.loss, self.loss_items = self.model(batch)
                                 ^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\nn\tasks.py", line 111, in forward
    return self.loss(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\nn\tasks.py", line 293, in loss
    return self.criterion(preds, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\utils\loss.py", line 742, in __call__
    loss_one2many = self.one2many(one2many, batch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\utils\loss.py", line 234, in __call__
    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
                                                  ^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\miniconda3\envs\YOLO11\Lib\site-packages\ultralytics\utils\tal.py", line 75, in forward
    except torch.OutOfMemoryError:
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch' has no attribute 'OutOfMemoryError'

Do you have an idea wy this problem is happen with me?





### Environment

python --version
Python 3.11.10

Package                Version
---------------------- ------------
albucore               0.0.20
albumentations         1.4.21
annotated-types        0.7.0
certifi                2024.8.30
charset-normalizer     3.4.0
colorama               0.4.6
contourpy              1.3.1
cycler                 0.12.1
eval_type_backport     0.2.0
filelock               3.16.1
fonttools              4.55.0
fsspec                 2024.10.0
idna                   3.10
intel-openmp           2021.4.0
Jinja2                 3.1.4
kiwisolver             1.4.7
MarkupSafe             3.0.2
matplotlib             3.9.2
mkl                    2021.4.0
mpmath                 1.3.0
networkx               3.4.2
numpy                  1.26.4
opencv-python          4.10.0.84
opencv-python-headless 4.10.0.84
packaging              24.2
pandas                 2.2.3
pillow                 11.0.0
pip                    24.2
psutil                 6.1.0
py-cpuinfo             9.0.0
pydantic               2.9.2
pydantic_core          2.23.4
pyparsing              3.2.0
python-dateutil        2.9.0.post0
pytz                   2024.2
PyYAML                 6.0.2
requests               2.32.3
scipy                  1.14.1
seaborn                0.13.2
setuptools             75.1.0
simsimd                6.0.7
six                    1.16.0
stringzilla            3.10.10
sympy                  1.13.1
tbb                    2021.11.0
torch                  2.0.1+cu118
torchaudio             2.0.2+cu118
torchvision            0.15.2+cu118
tqdm                   4.67.0
typing_extensions      4.12.2
tzdata                 2024.2
ultralytics            8.3.34
ultralytics-thop       2.0.12
urllib3                2.2.3
wheel                  0.44.0

### Minimal Reproducible Example

yolo train model=yolo11x.pt data=data.yaml epochs=100 imgsz=640

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @MoussaGRICHE, thank you for sharing your issue with Ultralytics 🚀! This is an automated response to guide you in the right direction, but rest assured, a dedicated Ultralytics engineer will assist you soon.

It looks like you've encountered a bug 🐛. To help us address this issue more efficiently, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that demonstrates the problem? This will greatly aid our debugging process.

Meanwhile, here are a few things you can try:

1. **Upgrade to the Latest Version**: Ensure you're using the latest `ultralytics` package along with all its requirements. You can do this in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

   ```bash
   pip install -U ultralytics
   ```

2. **Environment Suggestions**: Sometimes running YOLO in different environments can help resolve hardware or dependency-related issues. Consider trying these supported environments:

   - **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
   - **Google Cloud** Deep Learning VM. See the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
   - **Amazon** Deep Learning AMI. See the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
   - **Docker Image**. Find details in the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

3. **Check Our Status**: Our continuous integration (CI) system tests all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/). A green status means our tests are passing: <a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

For additional support and to share your experience, feel free to join our community:

- Real-time chat on [Discord](https://ultralytics.com/discord) 🎧
- In-depth discussions on [Discourse](https://community.ultralytics.com)
- Reddit threads on our [Subreddit](https://reddit.com/r/ultralytics) to connect with fellow users

Once an Ultralytics engineer checks your issue, they will provide further assistance. Thanks for your patience and collaboration!

**Comment by Y-T-G** [comment]
The error is probably due to incorrect class labels in your files. Your class indices should be between 0 to number of classes. If you have 10 classes, the labels can only have 0-9. Check your labels and data.yaml to see if the class numbers are correct. Delete the .cache files inside the train and val folders and run again.

**Comment by aRibra** [comment]
> The error is probably due to incorrect class labels in your files. Your class indices should be between 0 to number of classes. If you have 10 classes, the labels can only have 0-9 as class labels. Check your labels and data.yaml to see if the class numbers are correct. Delete the .cache files inside the train and val folders and run again.

Thank you. I had the same issue. My problem was having 1-indexed categories. Converting to 0-indexed categories solved the issue.

**Comment by glenn-jocher** [comment]
@aRibra you're welcome! Glad to hear that converting to 0-indexed categories resolved the issue. Let us know if you encounter any other problems or have further questions. Happy training!
