### ISSUE TITLE
YOLO model training using Ray

### ISSUE THREAD

**Issue by sanket-valani-tss** [ultralytics/ultralytics#17711]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, is there a way to train yolo model with Ray multi cluster approach...
I see that there is ray tuning support available https://docs.ultralytics.com/integrations/ray-tune/

**Comment by UltralyticsAssistant** [comment]
👋 Hello @sanket-valani-tss, thank you for your interest in Ultralytics 🚀! We recommend visiting the [Docs](https://docs.ultralytics.com) for new users where you can find many resources including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples, as well as details on [Ray tuning](https://docs.ultralytics.com/integrations/ray-tune/) which you have already checked out.

As this is a question about custom training or distributed learning with Ray, please provide as much detail as possible on your implementation setup. This includes code snippets, configurations, and any logs if applicable, to better assist you with your query.

For real-time support, consider joining our [Discord community](https://ultralytics.com/discord) 🎧, or you can engage in more discussion on our [Discourse](https://community.ultralytics.com) forum or [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure you have the latest `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) by running:

```bash
pip install -U ultralytics
```

## Environments

YOLO is compatible with the following environments (with dependencies like [CUDA](https://developer.nvidia.com/cuda), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/) pre-configured):

- **Notebooks** with GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

This is an automated response. An Ultralytics engineer will assist you further shortly.

**Comment by glenn-jocher** [comment]
Thank you for your question! While Ultralytics integrates with Ray Tune for hyperparameter optimization, distributed training across Ray multi-cluster setups is not natively supported. You may explore Ray's documentation to implement custom solutions for multi-cluster training or adapt the approach used in our Ray Tune integration: [Ray Tune Documentation](https://docs.ultralytics.com/integrations/ray-tune/).

**Comment by sanket-valani-tss** [comment]
is it possible to do multiple gpu machine training via DDP?

**Comment by glenn-jocher** [comment]
@sanket-valani-tss yes, Distributed Data Parallel (DDP) training across multiple GPUs and machines is supported with PyTorch. You can achieve this by using the `torch.distributed.run` utility. Refer to the [Multi-GPU Training guide](https://docs.ultralytics.com/modes/train/#multi-gpu-training) for detailed instructions. Ensure proper configurations, including `--nnodes`, `--nproc_per_node`, and `--master_addr`. Let me know if you need further clarification!

**Comment by sanket-valani-tss** [comment]
thanks for the update @glenn-jocher 
I did ran the below cmd on respective nodes
first node 
```bash
python -m torch.distributed.run --nproc_per_node 1 --nnodes 2 --node_rank 0 --master_addr "192.168.110.178" --master_port 9090 ~/.local/bin/yolo train data=data.yaml model=yolov8n.pt epochs=10
```
second node
```bash
python -m torch.distributed.run --nproc_per_node 1 --nnodes 2 --node_rank 1 --master_addr "192.168.110.178" --master_port 9090 ~/.local/bin/yolo train data=data.yaml model=yolov8n.pt epochs=10
```
The setup is basically there are two nodes with each having one GPU inside, both nodes are identical, are in the same network and have same dataset 

when I ran both of the cmd it gives me the below error
_ValueError: Default process group has not been initialized, please make sure to call init_process_group._

```bash

Traceback (most recent call last):
  File "/home/admin/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/admin/.local/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 969, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/admin/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/home/admin/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/home/admin/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/home/admin/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 286, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=LOCAL_RANK, mode="train")
  File "/home/admin/.local/lib/python3.10/site-packages/ultralytics/models/yolo/detect/train.py", line 55, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "/home/admin/.local/lib/python3.10/site-packages/ultralytics/data/build.py", line 132, in build_dataloader
    sampler = None if rank == -1 else distributed.DistributedSampler(dataset, shuffle=shuffle)
  File "/home/admin/.local/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 77, in __init__
    num_replicas = dist.get_world_size()
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2020, in get_world_size
    return _get_group_size(group)
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 986, in _get_group_size
    default_pg = _get_default_group()
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1150, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.
E1127 17:24:10.364000 225131 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 225175) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/admin/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

```

**Comment by glenn-jocher** [comment]
The error indicates that the PyTorch distributed process group (`init_process_group`) is not properly initialized, likely due to misconfiguration in your setup. Please ensure the following:

1. **Network Configuration:** Verify that both nodes are reachable over the network using the specified `--master_addr` and `--master_port`. You can test connectivity using `ping` or `telnet`.

2. **PyTorch Installation:** Ensure the PyTorch versions on both nodes are identical and support distributed training. Check with `python -c "import torch; print(torch.__version__)"`.

3. **Environment Variables:**
   - For PyTorch Distributed Data Parallel (DDP), the environment variable `MASTER_ADDR` and `MASTER_PORT` need to match the values provided in your commands. Example:
     ```
     export MASTER_ADDR=192.168.110.178
     export MASTER_PORT=9090
     ```
     Set these variables on both nodes before running the command.

4. **Matching Versions:** Ensure that all related libraries, including Ultralytics, dependencies, and datasets, are identical across nodes.

5. **Command Alignment:** Both commands should have consistent dataset paths, weights, and model arguments. Double-check for discrepancies.

6. **Debugging Tip:** Start the training process on just one node to verify the setup works correctly before involving the second node.

If these steps do not resolve the issue, please share any additional debug logs generated from running the distributed setup. For reference, consult the detailed PyTorch DDP documentation: [Distributed Training](https://pytorch.org/docs/stable/distributed.html).
