### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'runs\\segment\\train\\weights\\best.pt'

### ISSUE THREAD

**Issue by weertman** [ultralytics/ultralytics#1772]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

**Output**

```
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8x-seg.pt to D:\StarSeg-Lab\projects\yolov8x-seg.pt...
  0%|          | 0.00/137M [00:00<?, ?B/s]
Ultralytics YOLOv8.0.32  Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA RTX A6000, 49140MiB)
Setup complete  (64 CPUs, 1023.6 GB RAM, 555.3/7452.0 GB disk)
loading Roboflow workspace...
loading Roboflow project...
Dependency ultralytics<=8.0.20 is required but found version=8.0.32, to fix: `pip install ultralytics<=8.0.20`
Downloading Dataset Version Zip in StarSeg-Lab-7 to yolov8: 100% [125040680 / 125040680] bytes
Extracting Dataset Version Zip to StarSeg-Lab-7 in yolov8:: 100%|██████████| 4454/4454 [00:01<00:00, 3265.15it/s]
Ultralytics YOLOv8.0.32  Python-3.9.13 torch-1.13.1+cu117 CUDA:1 (NVIDIA RTX A6000, 49140MiB)
yolo\engine\trainer: task=segment, mode=train, model=../yolov8x-seg.pt, data=D:\StarSeg-Lab\projects\StarSeg-Lab-7\data.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, cache=False, device=1, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, min_memory=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0010078125, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.15, copy_paste=0.3, cfg=None, v5loader=False, save_dir=runs\segment\train
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.Conv                  [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.Conv                  [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.C2f                   [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.Conv                  [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.C2f                   [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.Conv                  [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.C2f                   [640, 640, 6, True]           
  7                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
  8                  -1  3   6969600  ultralytics.nn.modules.C2f                   [640, 640, 3, True]           
  9                  -1  1   1025920  ultralytics.nn.modules.SPPF                  [640, 640, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  3   1948800  ultralytics.nn.modules.C2f                   [960, 320, 3]                 
 16                  -1  1    922240  ultralytics.nn.modules.Conv                  [320, 320, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  3   7174400  ultralytics.nn.modules.C2f                   [960, 640, 3]                 
 19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
 22        [15, 18, 21]  1  12317171  ultralytics.nn.modules.Segment               [1, 32, 320, [320, 640, 640]] 
YOLOv8x-seg summary: 401 layers, 71751811 parameters, 71751795 gradients, 344.5 GFLOPs

Transferred 651/657 items from pretrained weights
Traceback (most recent call last):

  File "D:\StarSeg-Lab\src\Train_Yolov8.py", line 57, in <module>
    model.train(task='segment', mode='train', model='../yolov8x-seg.pt',

  File "C:\Users\wlwee\anaconda3\lib\site-packages\ultralytics\yolo\engine\model.py", line 218, in train
    self.model, _ = attempt_load_one_weight(str(self.trainer.best))

  File "C:\Users\wlwee\anaconda3\lib\site-packages\ultralytics\nn\tasks.py", line 390, in attempt_load_one_weight
    ckpt = torch_safe_load(weight)  # load ckpt

  File "C:\Users\wlwee\anaconda3\lib\site-packages\ultralytics\nn\tasks.py", line 336, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load

  File "C:\Users\wlwee\anaconda3\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:

  File "C:\Users\wlwee\anaconda3\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)

  File "C:\Users\wlwee\anaconda3\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))

FileNotFoundError: [Errno 2] No such file or directory: 'runs\\segment\\train\\weights\\best.pt'
```

### Environment

I am attempting to train a yolov8 model on a roboflow instance segmentation dataset using windows 10 machine with 2 A6000 GPUs using a python script. 

- Ultralytics YOLOv8.0.32  Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA RTX A6000, 49140MiB)
- Windows 10 Pro

**Nvidia-smi output, Note in script I use GPU 1 which has no background processes**

```
(base) C:\Users\wlwee>nvidia-smi
Sun Apr  2 12:00:34 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.49       Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000   WDDM  | 00000000:18:00.0  On |                  Off |
| 31%   60C    P0    65W / 300W |   1891MiB / 49140MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000   WDDM  | 00000000:51:00.0 Off |                  Off |
| 30%   28C    P8     8W / 300W |      0MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3944    C+G   ...e\PhoneExperienceHost.exe    N/A      |
|    0   N/A  N/A      4224    C+G   ...in7x64\steamwebhelper.exe    N/A      |
|    0   N/A  N/A      7756    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      9396    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     10424    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     10472    C+G   ...cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     10952    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     15224    C+G   ...bbwe\Microsoft.Photos.exe    N/A      |
|    0   N/A  N/A     16196    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     17180    C+G   ...8wekyb3d8bbwe\Cortana.exe    N/A      |
|    0   N/A  N/A     19716    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     21884    C+G   ..._dt26b99r8h8gj\RtkUWP.exe    N/A      |
+-----------------------------------------------------------------------------+
```

Checking torch 
```
torch.cuda.is_available()
Out[3]: True

torch.cuda.get_device_properties(1)
Out[5]: _CudaDeviceProperties(name='NVIDIA RTX A6000', major=8, minor=6, total_memory=49139MB, multi_processor_count=84)
```

### Minimal Reproducible Example

```
#%%

import os
import ultralytics
from ultralytics import YOLO
import ruamel.yaml
import sys

#%%

HOME = r'D:/StarSeg-Lab/projects'
os.chdir(HOME)
model = YOLO(f'{HOME}/yolov8x-seg.pt')

#%%

import roboflow

#%%
ultralytics.checks()

#%%

VERSION = 7
rf = roboflow.Roboflow(api_key="")
ws = rf.workspace("willem-weertman")
project = ws.project("starseg-lab").version(VERSION)
dataset = project.download("yolov8")

#%%

data_yaml = os.path.join(dataset.location, 'data.yaml')
yaml = ruamel.yaml.YAML()
with open(data_yaml) as f:
    data = yaml.load(f)

## getting pathing issues, changing yaml removes errors ##
data['test'] = os.path.join('test', 'images')
data['train'] = os.path.join('train', 'images')
data['val'] = os.path.join( 'valid', 'images')

with open(data_yaml, "w") as f:
    yaml.dump(data, f)
    
#%%

os.chdir(os.path.join(HOME, f'StarSeg-Lab-{VERSION}'))

#%%

model.train(task='segment', mode='train', model='../yolov8x-seg.pt',
            data=os.path.join(dataset.location, 'data.yaml'), device = '1')
```

### Additional

It looks like the file ```best.pt``` is not getting created. 

I've been attempting to get yolov8 to run locally and have been having lots of problems with paths. I don't have any issues training in Google CoLab, but would prefer to work locally. 

Thanks for your support!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by croze97** [comment]
Having this same problem, only occurs when I enable multi-gpu by updating
results = model.train(data="data.yaml", batch = 8, epochs=50, lr0=0.001, device = '0,1')
where it works without error when setting device='0'

Does Yolov8 simply not support multi-gpu? I tried fiddling with other values in train() but no luck.

**Comment by croze97** [comment]
Here is my full code that works without error:
from ultralytics import YOLO
if __name__=="__main__":
    model = YOLO("yolov8n.yaml") 
    results = model.train(data="data.yaml", batch = 8, epochs=50, lr0=0.001, device = '0')
    results = model.val()
   
My full code the reproduces the same error as OP:
from ultralytics import YOLO
if __name__=="__main__":
    model = YOLO("yolov8n.yaml") 
    results = model.train(data="data.yaml", batch = 8, epochs=50, lr0=0.001, device = '0,1')
    results = model.val()
    
My data.yaml file:
train: ../train/images
val: ../valid/images
test: ../test/images

nc: 23
names: ['Button', 'Capacitor Jumper', 'Capacitor', 'Clock', 'Connector', 'Diode', 'EM', 'Electrolytic Capacitor', 'Ferrite Bead', 'IC', 'Inductor', 'Jumper', 'Led', 'Pads', 'Pins', 'Resistor Jumper', 'Resistor Network', 'Resistor', 'Switch', 'Test Point', 'Transistor', 'Unknown Unlabeled', 'iC']

roboflow:
  workspace: roboflow-100
  project: printed-circuit-board
  version: 4
  license: CC BY 4.0
  url: https://universe.roboflow.com/roboflow-100/printed-circuit-board/dataset/4
  
  
Python 3.10.0
Cuda 11.8
Pytorch 2.0.0+cu118
Ultralytics 8.0.43

Hopefully this can help you reproduce the error since I see you flagged this thread as non-reproducible.

**Comment by croze97** [comment]
Setting save=False creates a new error (again, device='0' works fine with save=False, only device='0,1' causes an error)

**Comment by glenn-jocher** [comment]
@croze97 it appears that the issue you are facing is likely due to the 2nd GPU attempting to access a ".pt" file created by the 1st GPU. This could happen if you are using a multi-GPU setup for training, but the script is not designed to handle this scenario properly. The error may occur because the second GPU does not have access to the checkpoints created on the first GPU, or because the script is not able to fully utilize both GPUs for training. 

One possible solution could be to modify the script to support multi-GPU training, which may require changes in the way the checkpoint files are managed or the way the data is processed and distributed across multiple GPUs. However, this can be a complex task and may require advanced knowledge of deep learning frameworks and multi-GPU setups.

Another possible solution could be to use a different training setup that can better utilize multiple GPUs, such as distributed training or data parallel training frameworks. These frameworks are designed to work efficiently with multiple GPUs, and they can handle data parallelism and checkpoint management in a more scalable and fault-tolerant way.

Overall, the key to solving this issue would be to identify the root cause of the error and design an appropriate solution that can handle multi-GPU training effectively. It may require some experimentation and fine-tuning to achieve optimal results, but the payoff can be substantial in terms of training speed and performance.

**Comment by croze97** [comment]
if I wanted chatGPT's response to what my problem I woulda typed it into chatGPT (which I did already) :(

**Comment by jordan-lumley** [comment]
I too am running into this issue with a multi-gpu setup.

**Comment by pderrenger** [comment]
@jordan-lumley i understand your frustration, and I appreciate your patience. It seems that multi-GPU setups can be challenging, especially when it comes to managing checkpoints and ensuring synchronization between the GPUs during training. I would recommend exploring the Ultralytics documentation or engaging with the community to see if others have encountered and resolved similar issues with multi-GPU training in YOLOv8. It's possible that there may be specific configuration steps or workarounds that can help address this issue effectively. If you have already sought help from the community, I encourage you to continue the discussion there, as there may be individuals who have encountered and resolved similar issues.
