### ISSUE TITLE
i cannot convert my pt model to tflite

### ISSUE THREAD

**Issue by mpl48** [ultralytics/ultralytics#17750]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to convert the weights of my pt model to tflite with the ultralytics documentation but I get many errors.

this is my code:

from ultralytics import YOLO

# Load the YOLO11 model
model = YOLO('best.pt')

model.export(format="tflite", imgsz=640)

and i get:
ONNX: export success  2.9s, saved as 'best.onnx' (98.9 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.20.0...
ERROR: The trace log is below.
Traceback (most recent call last):
  File "c:\Users\Melis\OneDrive\Documentos\Quipux\convert\lib\site-packages\onnx2tf\utils\common_functions.py", line 310, in print_wrapper_func
    result = func(*args, **kwargs)
  File "c:\Users\Melis\OneDrive\Documentos\Quipux\convert\lib\site-packages\onnx2tf\ops\Input.py", line 81, in make_node
    if graph_input.shape != tf.TensorShape(None) and len(graph_input.shape) in [3, 4, 5] \
  File "c:\Users\Melis\OneDrive\Documentos\Quipux\convert\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 1294, in __ne__
    raise ValueError("The inequality of unknown TensorShapes is undefined.")
ValueError: The inequality of unknown TensorShapes is undefined.

ERROR: input_onnx_file_path: best.onnx
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

{
	"name": "AttributeError",
	"message": "'tuple' object has no attribute 'tb_frame'",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\onnx2tf\\utils\\common_functions.py:310, in print_node_info.<locals>.print_wrapper_func(*args, **kwargs)
    309 try:
--> 310     result = func(*args, **kwargs)
    312     if get_log_level() <= LOG_LEVELS['debug']:

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\onnx2tf\\ops\\Input.py:81, in make_node(graph_input, tf_layers_dict, keep_ncw_or_nchw_or_ncdhw_input_names, keep_nwc_or_nhwc_or_ndhwc_input_names, keep_shape_absolutely_input_names, **kwargs)
     80 else:
---> 81     if graph_input.shape != tf.TensorShape(None) and len(graph_input.shape) in [3, 4, 5] \\
     82         and keep_ncw_or_nchw_or_ncdhw_input_names:
     83         if graph_input_name in keep_ncw_or_nchw_or_ncdhw_input_names:

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1294, in TensorShape.__ne__(self, other)
   1293 if self.rank is None or other.rank is None:
-> 1294   raise ValueError(\"The inequality of unknown TensorShapes is undefined.\")
   1295 if self.rank != other.rank:

ValueError: The inequality of unknown TensorShapes is undefined.

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[3], line 1
----> 1 model.export(format=\"tflite\", imgsz=640, dynamic=False,nms=True)

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\ultralytics\\engine\\model.py:734, in Model.export(self, **kwargs)
    733 args = {**self.overrides, **custom, **kwargs, \"mode\": \"export\"}  # highest priority args on the right
--> 734 return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\ultralytics\\engine\\exporter.py:365, in Exporter.__call__(self, model)
    364 self.args.int8 |= edgetpu
--> 365 f[5], keras_model = self.export_saved_model()
    366 if pb or tfjs:  # pb prerequisite to tfjs

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\ultralytics\\engine\\exporter.py:141, in try_export.<locals>.outer_func(*args, **kwargs)
    140 with Profile() as dt:
--> 141     f, model = inner_func(*args, **kwargs)
    142 LOGGER.info(f\"{prefix} export success ✅ {dt.t:.1f}s, saved as '{f}' ({file_size(f):.1f} MB)\")

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\ultralytics\\engine\\exporter.py:969, in Exporter.export_saved_model(self, prefix)
    968 LOGGER.info(f\"{prefix} starting TFLite export with onnx2tf {onnx2tf.__version__}...\")
--> 969 keras_model = onnx2tf.convert(
    970     input_onnx_file_path=f_onnx,
    971     output_folder_path=str(f),
    972     not_use_onnxsim=True,
    973     verbosity=\"error\",  # note INT8-FP16 activation bug https://github.com/ultralytics/ultralytics/issues/15873
    974     output_integer_quantized_tflite=self.args.int8,
    975     quant_type=\"per-tensor\",  # \"per-tensor\" (faster) or \"per-channel\" (slower but more accurate)
    976     custom_input_op_name_np_data_path=np_data,
    977     disable_group_convolution=True,  # for end-to-end model compatibility
    978     enable_batchmatmul_unfold=True,  # for end-to-end model compatibility
    979 )
    980 yaml_save(f / \"metadata.yaml\", self.metadata)  # add metadata.yaml

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\onnx2tf\\onnx2tf.py:868, in convert(input_onnx_file_path, onnx_graph, output_folder_path, output_signaturedefs, output_h5, output_keras_v3, output_tfv1_pb, output_weights, copy_onnx_input_output_names_to_tflite, output_integer_quantized_tflite, quant_type, custom_input_op_name_np_data_path, input_output_quant_dtype, not_use_onnxsim, not_use_opname_auto_generate, batch_size, overwrite_input_shape, no_large_tensor, output_nms_with_dynamic_tensor, keep_ncw_or_nchw_or_ncdhw_input_names, keep_nwc_or_nhwc_or_ndhwc_input_names, keep_shape_absolutely_input_names, output_names_to_interrupt_model_conversion, disable_group_convolution, enable_accumulation_type_float16, enable_batchmatmul_unfold, enable_rnn_unroll, disable_suppression_flextranspose, disable_strict_mode, number_of_dimensions_after_flextranspose_compression, disable_suppression_flexstridedslice, number_of_dimensions_after_flexstridedslice_compression, optimization_for_gpu_delegate, replace_argmax_to_reducemax_and_indicies_is_int64, replace_argmax_to_reducemax_and_indicies_is_float32, replace_argmax_to_fused_argmax_and_indicies_is_int64, replace_argmax_to_fused_argmax_and_indicies_is_float32, fused_argmax_scale_ratio, replace_to_pseudo_operators, param_replacement_file, check_gpu_delegate_compatibility, check_onnx_tf_outputs_elementwise_close, check_onnx_tf_outputs_elementwise_close_full, check_onnx_tf_outputs_sample_data_normalization, check_onnx_tf_outputs_elementwise_close_rtol, check_onnx_tf_outputs_elementwise_close_atol, mvn_epsilon, disable_model_save, non_verbose, verbosity)
    866 sanitizing(graph_input)
--> 868 op.make_node(
    869     graph_input=graph_input,
    870     tf_layers_dict=tf_layers_dict,
    871     keep_ncw_or_nchw_or_ncdhw_input_names=keep_ncw_or_nchw_or_ncdhw_input_names,
    872     keep_nwc_or_nhwc_or_ndhwc_input_names=keep_nwc_or_nhwc_or_ndhwc_input_names,
    873     keep_shape_absolutely_input_names=keep_shape_absolutely_input_names,
    874     **additional_parameters,
    875 )
    876 op_counta += 1

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\onnx2tf\\utils\\common_functions.py:376, in print_node_info.<locals>.print_wrapper_func(*args, **kwargs)
    372 error(
    373     f'Also, for models that include NonMaxSuppression in the post-processing, ' +
    374     f'try the -onwdt option.'
    375 )
--> 376 sys.exit(1)

SystemExit: 1

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
    [... skipping hidden 1 frame]

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\interactiveshell.py:2095, in InteractiveShell.showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2092 if exception_only:
   2093     stb = ['An exception has occurred, use %tb to see '
   2094            'the full traceback.\
']
-> 2095     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2096                                                      value))
   2097 else:
   2098     try:
   2099         # Exception classes can customise their traceback - we
   2100         # use this in IPython.parallel for exceptions occurring
   2101         # in the engines. This should return a list of strings.

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\ultratb.py:696, in ListTB.get_exception_only(self, etype, value)
    688 def get_exception_only(self, etype, value):
    689     \"\"\"Only print the exception type and message, without a traceback.
    690 
    691     Parameters
   (...)
    694     value : exception value
    695     \"\"\"
--> 696     return ListTB.structured_traceback(self, etype, value)

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\ultratb.py:559, in ListTB.structured_traceback(self, etype, evalue, etb, tb_offset, context)
    556     chained_exc_ids.add(id(exception[1]))
    557     chained_exceptions_tb_offset = 0
    558     out_list = (
--> 559         self.structured_traceback(
    560             etype,
    561             evalue,
    562             (etb, chained_exc_ids),  # type: ignore
    563             chained_exceptions_tb_offset,
    564             context,
    565         )
    566         + chained_exception_message
    567         + out_list)
    569 return out_list

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\ultratb.py:1396, in AutoFormattedTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1394 else:
   1395     self.tb = etb
-> 1396 return FormattedTB.structured_traceback(
   1397     self, etype, evalue, etb, tb_offset, number_of_lines_of_context
   1398 )

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\ultratb.py:1287, in FormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1284 mode = self.mode
   1285 if mode in self.verbose_modes:
   1286     # Verbose modes need a full traceback
-> 1287     return VerboseTB.structured_traceback(
   1288         self, etype, value, tb, tb_offset, number_of_lines_of_context
   1289     )
   1290 elif mode == 'Minimal':
   1291     return ListTB.get_exception_only(self, etype, value)

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\ultratb.py:1140, in VerboseTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1131 def structured_traceback(
   1132     self,
   1133     etype: type,
   (...)
   1137     number_of_lines_of_context: int = 5,
   1138 ):
   1139     \"\"\"Return a nice text document describing the traceback.\"\"\"
-> 1140     formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1141                                                            tb_offset)
   1143     colors = self.Colors  # just a shorthand + quicker name lookup
   1144     colorsnormal = colors.Normal  # used a lot

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\ultratb.py:1030, in VerboseTB.format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1027 assert isinstance(tb_offset, int)
   1028 head = self.prepare_header(str(etype), self.long_header)
   1029 records = (
-> 1030     self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
   1031 )
   1033 frames = []
   1034 skipped = 0

File c:\\Users\\Melis\\OneDrive\\Documentos\\Quipux\\convert\\lib\\site-packages\\IPython\\core\\ultratb.py:1098, in VerboseTB.get_records(self, etb, number_of_lines_of_context, tb_offset)
   1096 while cf is not None:
   1097     try:
-> 1098         mod = inspect.getmodule(cf.tb_frame)
   1099         if mod is not None:
   1100             mod_name = mod.__name__

AttributeError: 'tuple' object has no attribute 'tb_frame'"

I really don't understand the error, I didn't add any different features in the training than the default ones.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @mpl48, thank you for reaching out and for your interest in Ultralytics 🚀! This is an automated response, but rest assured, an Ultralytics engineer will also assist you soon.

We suggest checking out our [Docs](https://docs.ultralytics.com) which provide a wealth of information for both new and experienced users. You can find numerous [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples there that might answer your query.

If this is a 🐛 Bug Report, please help us by providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) which can significantly aid in diagnosing your issue.

For custom training ❓ questions, please include comprehensive details such as dataset image examples and training logs, and ensure you follow our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

We invite you to join our vibrant Ultralytics community. Engage in real-time conversations on [Discord](https://ultralytics.com/discord) 🎧 or participate in detailed discussions on [Discourse](https://community.ultralytics.com). You can also share knowledge and dive into threads on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

To ensure that your issue isn't already resolved in a newer release, please upgrade to the latest version of the `ultralytics` package, along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLO can be run in any of these up-to-date verified environments, all of which include dependencies such as [CUDA](https://developer.nvidia.com/cuda), [CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/) preinstalled:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. Refer to the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. Follow the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. Check out the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests ensure the correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Windows, and Ubuntu every 24 hours and upon every commit.

We are here to help, so please don't hesitate to reach out! 😊

**Comment by Y-T-G** [comment]
You can try this.
https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

Or use Colab.
