### ISSUE TITLE
Issue tuning Yolov8 classification model

### ISSUE THREAD

**Issue by TJdeWet** [ultralytics/ultralytics#17756]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I keep getting this error when tuning a yolov8-cls classification model with wandb. 

TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/classify/train3
Starting training for 136 epochs...

      Epoch    GPU_mem       loss  Instances       Size
      1/136      2.95G    0.06263         16        640: 100%|██████████| 263/263 [03:49<00:00,  1.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 19/19 [05:12<00:00, 16.43s/it]
                   all      0.937          1
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 969, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 453, in _do_train
    self.run_callbacks("on_fit_epoch_end")
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 168, in run_callbacks
    callback(self)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/callbacks/raytune.py", line 17, in on_fit_epoch_end
    if ray.train._internal.session._get_session():  # replacement for deprecated ray.tune.is_session_enabled()
AttributeError: module 'ray.train._internal.session' has no attribute '_get_session'. Did you mean: 'get_session'?
Sentry is attempting to send 2 pending events
Waiting up to 2 secondstuning

### Additional

Environment information: 
I am using kaggle...
PyTorch version: 2.0.0
CUDA available: True
Using GPU: Tesla P100-PCIE-16GB
Ultralytics version: 8.3.36

Basic code:
import os
!pip install --upgrade wandb 
import wandb
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
secret_value_0 = user_secrets.get_secret("wandb")
wandb.login(key=secret_value_0)
os.environ["WANDB_AGENT_MAX_INITIAL_FAILURES"] = "1"

!pip install -U ultralytics

from ultralytics import YOLO
from pathlib import Path
import random
import torch
sweep_config = {}
def train():
    wandb.init(config=default_config)
    config = wandb.config
    lr0 = config.lr0
    epochs = config.epochs
    optimizer = config.optimizer
    batch = config.batch
    momentum = config.momentum
    model = YOLO('yolov8n-cls.pt') 
    model.train(data='/kaggle/input/..', batch=batch, lr0=lr0, epochs=epochs, save_period=10,seed=42, optimizer = optimizer, momentum = momentum, imgsz=64, amp=True)

wandb.agent(sweep_id, train, count=10)

**Comment by UltralyticsAssistant** [comment]
👋 Hello @TJdeWet, thank you for reaching out and using Ultralytics 🚀! 

I'm here to assist you with your issue tuning the YOLOv8 classification model. It seems like you're encountering an error related to Ray Train's session management. To help us diagnose this 🐛 bug more effectively, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that highlights the problem? This will help our engineers pinpoint the issue more quickly.

In the meantime, make sure you're running the latest versions of all involved packages. You can upgrade the `ultralytics` package and other dependencies with:

```bash
pip install -U ultralytics
```

🔧 **For debugging:** It's beneficial to ensure you have all the latest requirements installed. You can check these out in the [requirements file](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml).

For real-time assistance, feel free to join our [Discord](https://ultralytics.com/discord) community 🎧 where you can discuss this with others who might have faced similar issues. Alternatively, you can engage in more detailed discussions on [Discourse](https://community.ultralytics.com), or explore community threads on our [Subreddit](https://reddit.com/r/ultralytics).

Don't worry! An Ultralytics engineer will review your issue shortly to provide you with further guidance. 😊

Stay tuned and have a great day!

**Comment by Y-T-G** [comment]
After installing Ultralytics, restart the notebook kernel.

**Comment by TJdeWet** [comment]
> After installing Ultralytics, restart the notebook kernel.

Thank you, however, this does not seem to be working. I still have not solved the issue.

**Comment by Y-T-G** [comment]
What's the version `pip show ray`?
