### ISSUE TITLE
Exporting a model as .mlpackage: TypeError: Parameter to MergeFrom() must be instance of same class

### ISSUE THREAD

**Issue by Chiroyce1** [ultralytics/ultralytics#17836]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Unable to export the models to mlpackage due to a TypeError. I had been using YOLOv8 previously and this is a jump to V11 so I am not sure if this has to do with breaking changes or something, either way, I posted this as I couldn't find any similar issue.

(tested with [YOLO11N](https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt) and [YOLOV11S](https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s.pt))

```
Loading model yolo11n.pt...
Loaded model yolo11n.pt!
Ultralytics 8.3.38 🚀 Python-3.10.7 torch-2.5.1 CPU (Apple M1)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)
scikit-learn version 1.3.1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
TensorFlow version 2.16.1 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.12.0 is the most recent version that has been tested.
Torch version 2.5.1 has not been tested with coremltools. You may run into unexpected errors. Torch 2.1.0 is the most recent version that has been tested.

CoreML: starting export with coremltools 7.1...
Tuple detected at graph output. This will be flattened in the converted model.
Converting PyTorch Frontend ==> MIL Ops: 100%|███████████████████████████████████▉| 709/711 [00:00<00:00, 8163.78 ops/s]
Running MIL frontend_pytorch pipeline: 100%|████████████████████████████████████████| 5/5 [00:00<00:00, 364.93 passes/s]
Running MIL default pipeline: 100%|████████████████████████████████████████████████| 71/71 [00:01<00:00, 59.11 passes/s]
Running MIL backend_mlprogram pipeline: 100%|█████████████████████████████████████| 12/12 [00:00<00:00, 515.57 passes/s]
CoreML: export failure ❌ 5.9s: Parameter to MergeFrom() must be instance of same class: expected MIL_pb2.AttributesEntry got str.
Traceback (most recent call last):
  File "~/yolov11/convert.py", line 10, in <module>
    m.export(format='mlpackage')
  File "/Users/chiroyce/Library/Python/3.10/lib/python/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/Users/Family/Library/Python/3.10/lib/python/site-packages/ultralytics/engine/exporter.py", line 363, in __call__
    f[4], _ = self.export_coreml()
    [...]
    return pm.Operation(
  File "/Users/chiroyce/Library/Python/3.10/lib/python/site-packages/google/protobuf/internal/python_message.py", line 534, in init
    copy.add().MergeFrom(val)
  File "/Users/chiroyce/Library/Python/3.10/lib/python/site-packages/google/protobuf/internal/python_message.py", line 1313, in MergeFrom
    raise TypeError(
TypeError: Parameter to MergeFrom() must be instance of same class: expected MIL_pb2.AttributesEntry got str.
```

### Environment

```
Ultralytics 8.3.38 🚀 Python-3.10.7 torch-2.5.1 CPU (Apple M1)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 294.2/460.4 GB disk)

OS                  macOS-15.1-arm64-arm-64bit
Environment         Darwin
Python              3.10.7
Install             pip
RAM                 16.00 GB
Disk                294.2/460.4 GB
CPU                 Apple M1
CPU count           8
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.26.4>=1.23.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.6.0.66>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.5.1>=1.8.0
torch               ✅ 2.5.1!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.20.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.12.0>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

### Minimal Reproducible Example

```py
from ultralytics import YOLO

models = ['yolo11n.pt', 'yolo11s.pt']

for model in models:
    print(f"Loading {model}...")
    m = YOLO(model)
    print(f"Exporting {model}...")
    m.export(format='mlpackage')  # should create '*.mlpackage'
    print(f"Exported {model}")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Chiroyce1, thank you for your interest in Ultralytics 🚀! We recommend checking out the [Docs](https://docs.ultralytics.com) for detailed guidance, including [Export](https://docs.ultralytics.com/modes/export/) instructions for exporting your models to various formats. You may also find the [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples particularly helpful.

If this is a 🐛 Bug Report, thank you for including a detailed description and environment settings. To assist further, we kindly request a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). The provided MRE section is a great start! It helps us isolate the issue and debug effectively. For now, ensure you are using the latest version of `ultralytics` and all relevant dependencies:

```bash
pip install -U ultralytics
```

Additionally, ensure that the required library versions are within the supported range. As stated in your logs, certain versions like `scikit-learn`, `TensorFlow`, or `Torch` may not align with tested compatibility, potentially leading to issues.

## Upgrade

Always ensure you're using the latest version of the `ultralytics` package and [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) with a [**Python>=3.8**](https://www.python.org/) environment:

```bash
pip install -U ultralytics
```

## Environments

For seamless experimentation, consider running YOLO in verified environments listed below, which are pre-configured with required dependencies:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, ensuring robust and verified performance on macOS, Windows, and Ubuntu.

Lastly, feel free to utilize our vibrant Ultralytics community for additional insights and real-time discussions:
- [Discord](https://discord.com/invite/ultralytics) 🎧
- [Discourse](https://community.ultralytics.com)
- [Subreddit](https://reddit.com/r/Ultralytics)

🔍 This is an automated response, but don't worry—a Ultralytics engineer will take a closer look and assist you soon! 😊

**Comment by Y-T-G** [comment]
The traceback is incomplete.  Can you post the full traceback?

**Comment by Chiroyce1** [comment]
Oh okay makes sense, thanks. Also I can't find latest documentation (for YOLO11) about the device to use for inference - has it been updated to a combination of GPU/CPU and ANE? Even with the mlpackage models I can see a spike in the CPU usage (`yolo11n.mlpackage` with `results = model(frame, verbose=False, device='mps')`)

<img width="483" alt="image" src="https://github.com/user-attachments/assets/5dce3d99-d1e1-4cce-aff2-c6a662d5a10d">
<img width="471" alt="image" src="https://github.com/user-attachments/assets/3dc06bd9-d579-4e9d-ac42-413f63035c12">

It's been a while since I used YOLOv8 and so wanted to try out v11 and it seems there are some differences, sorry if I'm asking too many questions on this thread haha... updated documentation will be helpful :)

**Comment by glenn-jocher** [comment]
Thank you for your feedback! YOLO11's CoreML models are designed to leverage a combination of CPU, GPU, and ANE (if available) for optimal performance, but the actual usage depends on the underlying device and workload distribution by CoreML. The spike in CPU usage you're observing could be attributed to data preprocessing or post-processing steps. Updated documentation for YOLO11 is available at [Ultralytics Documentation](https://docs.ultralytics.com/), where you can find details about device compatibility and usage. Don't hesitate to share further questions or insights—it's always great to hear from the community!

**Comment by Chiroyce1** [comment]
Thank you so much for the quick response! I've made some observations in case someone reading this wants to know

Using `yolo11n.pt` and `yolo11n.mlpackage` converted using coremltools (Apple M1 8c CPU/8c GPU/16GB RAM)
- ~68fps with using the `.mlpackage` model and no device parameter (85-90% CPU, no GPU used)
- ~45fps with `.mlpackage` model but this time `device='mps'` (85-90% cpu usage, no GPU used)
- ~34fps with the .pt model with `device='mps'` (minimal CPU use, ~50% GPU usage)
- ~20fps with the .pt model with no device parameter (85-90% CPU, no GPU used)

What exactly does mps signify again?

**Comment by Y-T-G** [comment]
@Chiroyce1 You should use device="cpu". `device="mps"` only adds overhead when using CoreML model. The input is supposed to be on the CPU. So it moves from CPU to MPS to CPU again which slows down inference.
