### ISSUE TITLE
Cannot export and quantize a pose model to OpenVINO

### ISSUE THREAD

**Issue by adrianboguszewski** [ultralytics/ultralytics#17860]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

There is an exception:
```
/home/adrian/PycharmProjects/pythonProject/.venv/bin/python /home/adrian/PycharmProjects/pythonProject/keypoints.py 
Ultralytics 8.3.38 🚀 Python-3.12.7 torch-2.4.1+cpu CPU (Intel Core(TM) Ultra 7 155H)
YOLO11n-pose summary (fused): 257 layers, 2,866,468 parameters, 0 gradients, 7.4 GFLOPs

PyTorch: starting from 'yolo11n-pose.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 56, 8400) (6.0 MB)

OpenVINO: starting export with openvino 2024.5.0-17288-7975fa5da0c-refs/pull/3856/head...
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
OpenVINO: collecting INT8 calibration images from 'data=coco128.yaml'
OpenVINO: WARNING ⚠️ >300 images recommended for INT8 calibration, found 128 images.
Scanning /home/adrian/repos/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
INFO:nncf:17 ignored nodes were found by patterns in the NNCFGraph
INFO:nncf:2 ignored nodes were found by types in the NNCFGraph
INFO:nncf:Not adding activation input quantizer for operation: 187 __module.model.23/aten::sigmoid/Sigmoid_1
INFO:nncf:Not adding activation input quantizer for operation: 183 __module.model.23.dfl/aten::view/Reshape
INFO:nncf:Not adding activation input quantizer for operation: 184 __module.model.23/aten::sigmoid/Sigmoid
INFO:nncf:Not adding activation input quantizer for operation: 199 __module.model.23.dfl/aten::transpose/Transpose
INFO:nncf:Not adding activation input quantizer for operation: 214 __module.model.23.dfl/aten::softmax/Softmax
INFO:nncf:Not adding activation input quantizer for operation: 226 __module.model.23.dfl.conv/aten::_convolution/Convolution
INFO:nncf:Not adding activation input quantizer for operation: 236 __module.model.23.dfl/aten::view/Reshape_1
INFO:nncf:Not adding activation input quantizer for operation: 258 __module.model.23/aten::sub/Subtract
INFO:nncf:Not adding activation input quantizer for operation: 259 __module.model.23/aten::add/Add
INFO:nncf:Not adding activation input quantizer for operation: 269 __module.model.23/aten::add/Add_1
278 __module.model.23/aten::div/Divide

INFO:nncf:Not adding activation input quantizer for operation: 270 __module.model.23/aten::sub/Subtract_1
INFO:nncf:Not adding activation input quantizer for operation: 286 __module.model.23/aten::mul/Multiply
Statistics collection                               0% 0/128 • 0:00:00 • -:--:--
OpenVINO: export failure ❌ 3.0s: expected np.ndarray (got NoneType)
Traceback (most recent call last):
  File "/home/adrian/PycharmProjects/pythonProject/keypoints.py", line 5, in <module>
    ov_int8_model_path = model.export(format="openvino", int8=True, data="coco128.yaml")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/engine/exporter.py", line 361, in __call__
    f[3], _ = self.export_openvino()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/engine/exporter.py", line 146, in outer_func
    raise e
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/engine/exporter.py", line 141, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/engine/exporter.py", line 559, in export_openvino
    quantized_ov_model = nncf.quantize(
                         ^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/telemetry/decorator.py", line 79, in wrapped
    retval = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/quantization/quantize_model.py", line 187, in quantize
    return quantize_impl(
           ^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/openvino/quantization/quantize_model.py", line 351, in quantize_impl
    return quantize_fn(
           ^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/openvino/quantization/quantize_model.py", line 171, in native_quantize_impl
    quantized_model = quantization_algorithm.apply(model, graph, dataset=calibration_dataset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/quantization/algorithms/post_training/algorithm.py", line 112, in apply
    return self._pipeline.run_from_step(model, dataset, graph, 0, step_index_to_statistics)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/quantization/algorithms/pipeline.py", line 161, in run_from_step
    step_statistics = collect_statistics(statistic_points, step_model, step_graph, dataset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/quantization/algorithms/pipeline.py", line 49, in collect_statistics
    statistics_aggregator.collect_statistics(model, graph)
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/openvino/statistics/aggregator.py", line 41, in collect_statistics
    super().collect_statistics(model, graph)
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/common/tensor_statistics/aggregator.py", line 82, in collect_statistics
    for input_data in track(  # type: ignore
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/nncf/common/logging/track_progress.py", line 216, in __iter__
    yield from self.progress.track(
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/rich/progress.py", line 1209, in track
    for value in sequence:
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/data/build.py", line 48, in __iter__
    yield next(self.iterator)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/data/base.py", line 288, in __getitem__
    return self.transforms(self.get_image_and_label(index))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/data/augment.py", line 201, in __call__
    data = t(data)
           ^^^^^^^
  File "/home/adrian/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/ultralytics/data/augment.py", line 2055, in __call__
    labels["keypoints"] = torch.from_numpy(instances.keypoints)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got NoneType)
```
No exception is thrown when data is not specified.

### Environment
```
Ultralytics 8.3.38 🚀 Python-3.12.7 torch-2.4.1+cpu CPU (Intel Core(TM) Ultra 7 155H)
Setup complete ✅ (22 CPUs, 31.0 GB RAM, 286.3/491.1 GB disk)

OS                  Linux-6.11.0-9-generic-x86_64-with-glibc2.40
Environment         Linux
Python              3.12.7
Install             git
RAM                 31.04 GB
Disk                286.3/491.1 GB
CPU                 Intel Core(TM) Ultra 7 155H
CPU count           22
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.26.4>=1.23.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1+cpu>=1.8.0
torch               ✅ 2.4.1+cpu!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.19.1+cpu>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.12>=2.0.0
```

### Minimal Reproducible Example
```
from ultralytics import YOLO

model = YOLO("yolo11n-pose.pt") # load an official model
ov_int8_model_path = model.export(format="openvino", int8=True, data="coco128.yaml")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @adrianboguszewski, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report (as it appears to be), thank you for providing detailed context and the stack trace! To assist us further, could you ensure that your issue includes a complete and [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? Providing any additional details, such as image samples and specifics about your inputs, would help us debug the problem thoroughly.

If this is a custom training ❓ Question, please provide as much information as possible, including dataset characteristics, training logs, and verification that you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com). Or dive into threads on our [Subreddit](https://reddit.com/r/Ultralytics) to share knowledge with the community.

## Upgrade

Please try upgrading to the latest `ultralytics` version along with all its [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/). Your issue may already be resolved in the latest release:

```bash
pip install -U ultralytics
```

## Environments

YOLO can run seamlessly in numerous environments. Convenient options with all dependencies preinstalled include:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: Follow the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI: Follow the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: Refer to the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

The green badge indicates that all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests have passed successfully. CI tests ensure correct functionality for all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Windows, and Ubuntu.

This is an automated response to help streamline your experience 😊. An Ultralytics engineer will also assist you soon!

**Comment by glenn-jocher** [comment]
@adrianboguszewski the error suggests an issue during the INT8 calibration process caused by invalid keypoint data (`expected np.ndarray (got NoneType)`). This often stems from the dataset lacking valid keypoints or their formatting being incorrect. Verify that `coco128.yaml` dataset annotations include valid and correctly formatted keypoints for pose tasks. Additionally, ensure the dataset loader and augmentations correctly handle keypoints. If the issue persists, running the export without `int8=True` may be a temporary workaround until further debugging. For detailed guidance, refer to [OpenVINO export documentation](https://docs.ultralytics.com/integrations/openvino/).

**Comment by Y-T-G** [comment]
Try `data="coco8-pose.yaml"`

`coco128.yaml` is for detection.

**Comment by adrianboguszewski** [comment]
@Y-T-G is `coco8-pose.yaml` the only one for pose esitmation?

**Comment by Y-T-G** [comment]
@adrianboguszewski It's the only small dataset for human pose.

There are few others for other types of pose.

https://docs.ultralytics.com/datasets/pose/

**Comment by adrianboguszewski** [comment]
I see. Thanks for the answer.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any further questions, feel free to ask.
