### ISSUE TITLE
how to train/predict model on AMD GPU with onnxruntime-dml torch-directML ?

### ISSUE THREAD

**Issue by fgfxf** [ultralytics/ultralytics#17888]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Predict

### Bug

False
Ultralytics 8.3.39 🚀 Python-3.11.3 torch-2.4.1+cpu CPU (AMD Ryzen 7 PRO 6850HS with Radeon Graphics)
Setup complete ✅ (16 CPUs, 39.3 GB RAM, 880.1/952.3 GB disk)
None
True
privateuseone:0
privateuseone:0

Traceback (most recent call last):
  File "xxxxxxxxxxxxx", line 22, in <module>
    results = model.track(image_path,device="dml")  # list of Results objects
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 604, in track
    return self.predict(source=source, stream=stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 557, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 173, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 36, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 239, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 735, in warmup
    self.forward(im)  # warmup
    ^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\autobackend.py", line 526, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 112, in forward
    return self.predict(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 130, in predict
    return self._predict_once(x, profile, visualize, embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 151, in _predict_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\modules\conv.py", line 54, in forward_fuse
    return self.act(self.conv(x))
                    ^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cannot set version_counter for inference tensor

exit with code 1

In addition, I have successfully used C++ code to run YOLOv11n mode  on AMD GPU with 50% GPU load,(opencv/onnxruntime-dml) Thank you to the following authors for their work:  https://github.com/Geekgineer/YOLOs-CPP
and now I want to train and predict model by python.

### Environment

onnxruntime-directml           1.20.1
ultralytics                    8.3.39
ultralytics-thop               2.0.12
torch                          2.4.1
torch-directml                 0.2.5.dev240914
torchdata                      0.9.0
torchmetrics                   1.6.0
torchtext                      0.18.0
torchvision                    0.19.1

### Minimal Reproducible Example

import time
import cv2
import ultralytics
import torch
import torch_directml

print(torch.cuda.is_available())
print(ultralytics.checks())
print(torch_directml.is_available())
print(torch_directml.device())

model = ultralytics.YOLO("yolo11n.pt",task="detect")

dml = torch_directml.device()
model.to(dml)
print(model.device)  
video_capture = cv2.VideoCapture(0)

fps = 0.0
timeF = 10
c=1
while video_capture.isOpened():
    t1 = time.time()
    success, frame = video_capture.read()
    if not success:
        break
    results = model.track(frame)
    print(model.device)
    # print(results)
    # Visualize the results on the frame
    annotated_frame = results[0].plot()
    fps = (fps + (1. / (time.time() - t1))) / 2
    # print("fps= %.2f" % (fps))
    frame = cv2.putText(annotated_frame, "fps= %.2f" % (fps), (0, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow("video", frame)
    cv2.waitKey(1)

video_capture.release()
cv2.destroyAllWindows()

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @fgfxf, thank you for your interest in Ultralytics 🚀! We appreciate you taking the time to share your issue and provide detailed context.

From your description, it seems you're encountering a challenge running the model with ONNX Runtime using DirectML on AMD GPUs. We'll work with you to resolve this.

### 🐛 Bug Report  
We recommend providing a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us replicate your issue. It's great that you've included a script—please ensure it is minimal and isolates the error, along with specifying any configuration or pipeline steps.

---

### **Quick Checklist**
Before proceeding further, here's a checklist you can follow to verify your environment configuration:  
1. Ensure you have the latest version of the `ultralytics` package and other dependencies installed in a [Python>=3.8](https://www.python.org/) environment:
   ```bash
   pip install -U ultralytics torch torchvision onnxruntime-directml torch-directml
   ```
   This helps make sure the issue isn't associated with an older release.

2. Confirm your selected device (`privateuseone:0`) aligns with DirectML-capable hardware using:
   ```python
   import torch_directml
   print(torch_directml.device())
   ```

3. Test whether models support DirectML initialization with small input data before running full tracking or inference pipelines.

---

### **Documentation and Community Resources**  
We encourage you to utilize the following resources for related questions or further assistance:
- Comprehensive tutorials in our [Docs](https://docs.ultralytics.com)
- Real-time support via our [Discord](https://discord.com/invite/ultralytics) 🎧
- Discussion threads in our [Discourse](https://community.ultralytics.com) forum or [Subreddit](https://reddit.com/r/Ultralytics)

---

### **Environments**
YOLO supports a variety of development setups to suit your needs:
- **Free GPU Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud Deep Learning VM** ([GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/))
- **Amazon Web Services** ([AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/))
- **Validated Docker Environment** ([Docker Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

---

### **Status**
Check if the Ultralytics Continuous Integration (CI) tests are passing:  
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all current YOLO modes and tasks have been validated against the latest codebase for macOS, Windows, and Ubuntu.

---

This is an automated response to prioritize your query quickly while an Ultralytics engineer reviews it in more detail. We appreciate your understanding and look forward to assisting you! 😊

**Comment by Y-T-G** [comment]
You can try `model.track(frame, device=dml)`

**Comment by fgfxf** [comment]
> You can try `model.track(frame, device=dml)`
I have try many times:

    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cannot set version_counter for inference tensor

and I asked ChatGPT , GPT said it is because opencv frame in CPU memory, but i send the frame to a GPU torch tensor and it doesn't work also.

I think it is ultralytics YOLO doesn't support dml now.

**Comment by Y-T-G** [comment]
It seems like an error with DML.

https://stackoverflow.com/questions/76204465/runtimeerror-cannot-set-version-counter-for-inference-trying-directml-in-ai-p

**Comment by fgfxf** [comment]
> It seems like an error with DML.
> 
> 
> 
> https://stackoverflow.com/questions/76204465/runtimeerror-cannot-set-version-counter-for-inference-trying-directml-in-ai-p


i think it is yolo not support dml right now. and there are some optimize in the dart project.

**Comment by fgfxf** [comment]
> It seems like an error with DML.
> 
> 
> 
> https://stackoverflow.com/questions/76204465/runtimeerror-cannot-set-version-counter-for-inference-trying-directml-in-ai-p

i load yolo model .pt file in naive torch with dml.

model=YOLO("yolo11n.pt").to(dml).model
reslut=model(<torch array of img>)


 and it run on gpu well, but i don't know  how to change the predict result tensor(1,84,8400) to the cv2 rectangle in Python code.

**Comment by Y-T-G** [comment]
Did you try `device="dml"` or `device=dml`? I want you to try the second one.

**Comment by fgfxf** [comment]
> > You can try `model.track(frame, device=dml)`
> 
> 
> 
> Did you try `device="dml"` or `device=dml`? I want you to try the second one.

yes， i had try many times.

YOLO's official predict and track function is a layer of encapsulation for torch.nn.module, and I think it's because the encapsulation here didn't use torchdml well

**Comment by fgfxf** [comment]
> > You can try `model.track(frame, device=dml)`
> 
> 
> 
> Did you try `device="dml"` or `device=dml`? I want you to try the second one.

yes， i had try many times.

YOLO's official predict and track function is a layer of encapsulation for torch.nn.module, and I think it's because the encapsulation here didn't use torchdml well

**Comment by Y-T-G** [comment]
Does predict work?

**Comment by fgfxf** [comment]
> Does predict work?

all not work on amd gpu.

**Comment by Y-T-G** [comment]
You can remove this line from the code.

https://github.com/ultralytics/ultralytics/blob/e60992214c91d3ba169965053af69d6eb233b45e/ultralytics/engine/predictor.py#L219

And try again.

**Comment by Y-T-G** [comment]
You can also use ONNXRuntime DML with Ultralytics. Just convert your model to ONNX.

**Comment by fgfxf** [comment]
When I manually read the image file into memory, convert it to YOLO's specified (640x640) format, then convert it to GPU Tensor, and then use Ultralytics When using YOLO ("yolo11n. pt"). track (tensor), 

I noticed an error. In ultralytics\trackers\utils\gmc.py, the YOLO model will reprocess the tensor data itself. I think YOLO should add a parameter to allow users to pass in custom GPU tensor data.


`
model = ultralytics.YOLO("yolo11n.pt")  
dml = torch_directml.device()
print(model.device)
# 加载本地图片
image_path = "$%TDJ4QYZTJ(~4E}CK~F5OR_tmb.jpg"  # 替换为你的图片路径
image = cv2.imread(image_path)
# OpenCV 默认读取为 BGR 格式，转换为 RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
# 转换为 PIL 图像
image_pil = Image.fromarray(image_rgb)
# 定义转换器：调整大小并转为 Tensor
transform = transforms.Compose([
    transforms.Resize((640, 640)),  # 调整为 YOLO 模型要求的输入尺寸（确保是 32 的倍数）
    transforms.ToTensor()          # 转为 Tensor
])
# 将图片转换为 Tensor
image_tensor = transform(image_pil)
# 增加 batch 维度
image_tensor = image_tensor.unsqueeze(0)  # 形状从 (3, H, W) -> (1, 3, H, W)
image_tensor = image_tensor.to(dml)
results = model.track(image_tensor)  # list of Results objects
# Process results list
for result in results:
    print(result)
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    obb = result.obb  # Oriented boxes object for OBB outputs
    annotated_frame = result.plot()
    cv2.imshow("YOLO Inference", annotated_frame)
    cv2.waitKey(0)  # 按任意键退出
    cv2.destroyAllWindows()`

**Comment by Y-T-G** [comment]
> You can remove this line from the code.
> 
> https://github.com/ultralytics/ultralytics/blob/e60992214c91d3ba169965053af69d6eb233b45e/ultralytics/engine/predictor.py#L219
> 
> And try again.

Did you try this?

**Comment by Y-T-G** [comment]
> You can also use ONNXRuntime DML with Ultralytics. Just convert your model to ONNX and run it with Ultralytics. Don't specify any device.

Or this

**Comment by fgfxf** [comment]
```import ultralytics

model = ultralytics.YOLO("yolo11n.pt")  # load a pretrained model (recommended for training)

results = model.train(data="coco8.yaml", epochs=100, imgsz=640, device='dml')

success = model.export(format="onnx")```


    results = model.train(data="coco8.yaml", epochs=100, imgsz=640, device='dml')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 805, in train
    self.trainer.train()
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 264, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
                            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\checks.py", line 692, in check_amp
    assert amp_allclose(YOLO("yolo11n.pt"), im)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\checks.py", line 679, in amp_allclose
    a = m(batch, imgsz=imgsz, device=device, verbose=False)[0].boxes.data  # FP32 inference
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 179, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 557, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 173, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 266, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\ops.py", line 270, in non_max_suppression
    x = torch.cat((box, conf, j.float(), mask), 1)[conf.view(-1) > conf_thres]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError

**Comment by Y-T-G** [comment]
No. Export without training.
