### ISSUE TITLE
training the customer model with multi GPUS

### ISSUE THREAD

**Issue by xmj-7** [ultralytics/ultralytics#17890]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have such wrong:
`Traceback (most recent call last):
  File "/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py", line 6, in <module>
    from ultralytics.models.rtdetr.train import RTDETRTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py", line 6, in <module>
    from ultralytics.models.rtdetr.train import RTDETRTrainer
ModuleNotFoundError: No module named 'ultralytics'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3969599) of binary: /home/xmj/anaconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-11-30_17:30:11
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3969600)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-30_17:30:11
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3969599)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "test_rtdetr.py", line 19, in <module>
    results = model.train(data="coco8.yaml", epochs=100, imgsz=640,device='0,1')
  File "/home/xmj/project/ultralytics-main/ultralytics/engine/model.py", line 805, in train
    self.trainer.train()
  File "/home/xmj/project/ultralytics-main/ultralytics/engine/trainer.py", line 202, in train
    raise e
  File "/home/xmj/project/ultralytics-main/ultralytics/engine/trainer.py", line 200, in train
    subprocess.run(cmd, check=True)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/xmj/anaconda3/envs/torch/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '59099', '/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py']' returned non-zero exit status 1.
`
My train script is:
`
import os
import sys
import torch
torch.backends.cudnn.benchmark = False
torch.cuda.synchronize()
sys.path.append('/home/xmj/project/ultralytics-main')
os.environ["NCCL_NET"] = "Socket"
import os
os.environ['OMP_NUM_THREADS'] = '2'
from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR("rtdetr-l.pt")

# Display model information (optional)
model.info()

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="coco8.yaml", epochs=100, imgsz=640,device='0,1')

# Run inference with the RT-DETR-l model on the 'bus.jpg' image
results = model("path/to/bus.jpg")

`
how can i train rt-detr with multi-gpus and not install the ultralytics?thanks

**Comment by UltralyticsAssistant** [comment]
👋 Hello @xmj-7, thank you for your interest in Ultralytics 🚀! We recommend checking out the [Docs](https://docs.ultralytics.com) for guidance, where you'll find resources for [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage, as well as answers to many common questions.

It seems you're encountering an issue running multi-GPU training for RT-DETR without having the `ultralytics` package installed. To assist us in reproducing your issue and debugging the problem, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that includes:

1. Your exact modified code script.
2. Relevant system details such as Python, PyTorch, and CUDA versions (`python --version`, `torch.__version__`, etc.).
3. Information on how the `ultralytics` codebase is being accessed without installation (e.g., are you using source files directly?).
4. Any additional configuration or environment setup details.

If this report involves debugging distributed training, ensure that your setup adheres to the requirements. Please verify that:
- Your environment includes [PyTorch>=1.8](https://pytorch.org/) and [Python>=3.8](https://www.python.org/).
- The `ultralytics` package is either properly installed (`pip install ultralytics`) for a clean setup or correctly referenced when directly importing from source.

For multi-GPU training, note that the following command installs the correct dependencies and runs distributed training out of the box:
```bash
pip install ultralytics
```

If you opt to use the source code directly instead of installing the package, please ensure that the source files are correctly added to your `PYTHONPATH` or script's environment. Running `sys.path.append()` as shown in your script may not account for all dependencies.

### Additional Resources

Join our vibrant community for quick discussions or assistance:
- Real-time chat on [Discord](https://discord.com/invite/ultralytics) 🎧
- Detailed Q&A on [Discourse](https://community.ultralytics.com)
- Community knowledge-sharing on [Reddit](https://reddit.com/r/Ultralytics)

You can also explore verified environments for running your training process:
- **Notebooks** with free GPUs: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud** VM options: [GCP](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) and [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: See the [Docker Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)

### Upgrade
Ensure you're using the latest `ultralytics` version to avoid already-resolved issues:
```bash
pip install -U ultralytics
```

### CI/CD Status
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>  
When this badge is green, all tests (including multi-GPU training workflows) are passing for macOS, Windows, and Linux. 

Thank you for reporting this! This is an automated response 🛠️. An Ultralytics engineer will review your issue shortly and provide further assistance.

**Comment by Y-T-G** [comment]
You need to install it for multi-GPU training.

You can install the local folder using `pip install .`

**Comment by glenn-jocher** [comment]
@xmj-7 the error occurs because the `ultralytics` package is not installed in your environment, which is necessary for using Ultralytics products like YOLO or RT-DETR. The `ultralytics` package must be properly installed, even if you are importing it from a custom code base.

To resolve this, either install the package with `pip install ultralytics` or ensure your code path explicitly uses the correct modules. If you’re modifying or running from source, use `sys.path` to point to the local repository root. Additionally:

- Verify your multi-GPU setup by setting the `device` argument correctly (e.g., `device='0,1'`).
- Ensure you use DistributedDataParallel commands (`torch.distributed.run`) as outlined in [this multi-GPU training guide](https://docs.ultralytics.com/modes/train/).

If further issues arise, I recommend ensuring your repository and dependencies match the Ultralytics framework structure for compatibility.
