### ISSUE TITLE
training the customer model with multi GPUS

### ISSUE THREAD

**Issue by xmj-7** [ultralytics/ultralytics#17891]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## I have such wrong:
rt-detr-l summary: 673 layers, 32,970,476 parameters, 0 gradients
Ultralytics 8.3.39 🚀 Python-3.8.20 torch-2.0.0+cu117 CUDA:0 (NVIDIA RTX A6000, 48670MiB)
                                                      CUDA:1 (NVIDIA RTX A6000, 48670MiB)
engine/trainer: task=detect, mode=train, model=rtdetr-l.pt, data=coco8.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0,1, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train4
WARNING ⚠️ no model scale passed. Assuming scale='l'.
from  n    params  module                                       arguments                     
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]                   
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]           
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]    
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]          
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]    
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]  
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]                
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]              
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]              
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 28        [21, 24, 27]  1   7466252  ultralytics.nn.modules.head.RTDETRDecoder    [80, [256, 256, 256]]         
rt-detr-l summary: 681 layers, 32,970,476 parameters, 32,970,476 gradients.
Transferred 941/941 items from pretrained weights
DDP: debug command /home/xmj/anaconda3/envs/torch/bin/python -m torch.distributed.run --
nproc_per_node 2 --master_port 59099 /home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py
Traceback (most recent call last):
  File "/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py", line 6, in <module>
    from ultralytics.models.rtdetr.train import RTDETRTrainer
**ModuleNotFoundError: No module named 'ultralytics'**
Traceback (most recent call last):
  File "/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py", line 6, in <module>
    from ultralytics.models.rtdetr.train import RTDETRTrainer
ModuleNotFoundError: No module named 'ultralytics'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3969599) of binary: /home/xmj/anaconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py FAILED
Failures:
[1]:
  time      : 2024-11-30_17:30:11
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3969600)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
Root Cause (first observed failure):

[0]:
  time      : 2024-11-30_17:30:11
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3969599)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Traceback (most recent call last):
  File "test_rtdetr.py", line 19, in <module>
    results = model.train(data="coco8.yaml", epochs=100, imgsz=640,device='0,1')
  File "/home/xmj/project/ultralytics-main/ultralytics/engine/model.py", line 805, in train
    self.trainer.train()
  File "/home/xmj/project/ultralytics-main/ultralytics/engine/trainer.py", line 202, in train
    raise e
  File "/home/xmj/project/ultralytics-main/ultralytics/engine/trainer.py", line 200, in train
    subprocess.run(cmd, check=True)
  File "/home/xmj/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/xmj/anaconda3/envs/torch/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '59099', '/home/xmj/.config/Ultralytics/DDP/_temp_9kqsslr4139886937416848.py']' returned non-zero exit status 1

## And the train script is:
```
import os
import sys
import torch
torch.backends.cudnn.benchmark = False
torch.cuda.synchronize()
sys.path.append('/home/xmj/project/ultralytics-main')
os.environ["NCCL_NET"] = "Socket"
import os
os.environ['OMP_NUM_THREADS'] = '2'
from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR("rtdetr-l.pt")

# Display model information (optional)
model.info()

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="coco8.yaml", epochs=100, imgsz=640,device='0,1')

# Run inference with the RT-DETR-l model on the 'bus.jpg' image
results = model("path/to/bus.jpg")
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @xmj-7, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it effectively. From the information shared, it seems that you’re encountering a `ModuleNotFoundError: No module named 'ultralytics'` error while attempting distributed training with multiple GPUs. Please double-check your script and environment to ensure `ultralytics` is correctly installed and available in your `PYTHONPATH`.

If this is a custom training ❓ Question, please provide as much information as possible, including dataset details, configurations, and logs, and verify you’re following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

### Upgrade
Ensure you’re using the latest version of `ultralytics` and all dependencies. You can upgrade with:
```bash
pip install -U ultralytics
```
This will ensure any known issues are resolved in the latest release.

### Multi-GPU Training
Note that multi-GPU training uses PyTorch DistributedDataParallel (DDP). See our [Training Guide](https://docs.ultralytics.com/tasks/detection/#training) for examples and ensure your setup meets the necessary requirements for DDP.

### Environments
Training can be performed in verified environments:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

### Community Support
Join the Ultralytics community where it suits you best:
- For real-time chat: [Discord](https://discord.com/invite/ultralytics) 🎧  
- For in-depth topics: [Discourse](https://community.ultralytics.com)  
- For discussions: [Subreddit](https://reddit.com/r/Ultralytics)  

### Status
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>  
If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, verifying correct operation of YOLO on macOS, Windows, and Ubuntu.

This is an automated response, but don’t worry – an Ultralytics engineer will take a closer look and provide further assistance soon 👨‍💻. Thank you for your patience!

**Comment by Y-T-G** [comment]
You need to install it for multi-GPU training.

You can install the local folder using `pip install .`
