### ISSUE TITLE
How to use masks from segmentation model as SAM2 prompt

### ISSUE THREAD

**Issue by trongldwork** [ultralytics/ultralytics#17943]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
i have a segmentation model and i want to use SAM2 for refine masks results from it by using masks as prompt for SAM2, but it seems not working
```
from pathlib import Path
import numpy as np
from ultralytics import SAM, YOLO

from ultralytics.models.sam import Predictor as SAMPredictor
from ultralytics.models.sam import SAM2Predictor


def auto_annotate(
    data,
    seg_model="yolo11n-seg.pt",
    sam_model="sam_b.pt",
    device="",
    conf=0.25,
    iou=0.45,
    imgsz=640,
    max_det=300,
    classes=None,
    output_dir=None,
):
    """
    Automatically annotates images using a YOLO object detection model and a SAM segmentation model.

    This function processes images in a specified directory, detects objects using a YOLO model, and then generates
    segmentation masks using a SAM model. The resulting annotations are saved as text files.

    Args:
        data (str): Path to a folder containing images to be annotated.
        det_model (str): Path or name of the pre-trained YOLO detection model.
        sam_model (str): Path or name of the pre-trained SAM segmentation model.
        device (str): Device to run the models on (e.g., 'cpu', 'cuda', '0').
        conf (float): Confidence threshold for detection model; default is 0.25.
        iou (float): IoU threshold for filtering overlapping boxes in detection results; default is 0.45.
        imgsz (int): Input image resize dimension; default is 640.
        max_det (int): Limits detections per image to control outputs in dense scenes.
        classes (list): Filters predictions to specified class IDs, returning only relevant detections.
        output_dir (str | None): Directory to save the annotated results. If None, a default directory is created.

    Examples:
        >>> from ultralytics.data.annotator import auto_annotate
        >>> auto_annotate(data="ultralytics/assets", det_model="yolo11n.pt", sam_model="mobile_sam.pt")

    Notes:
        - The function creates a new directory for output if not specified.
        - Annotation results are saved as text files with the same names as the input images.
        - Each line in the output text file represents a detected object with its class ID and segmentation points.
    """
    seg_model = YOLO(seg_model)


# Create SAMPredictor
    overrides = dict(conf=0.25, task="segment", mode="predict",
                     imgsz=1280, model=sam_model)
    predictor = SAM2Predictor(overrides=overrides)
    predictor.get_model()
    data = Path(data)
    if not output_dir:
        output_dir = data.parent / f"{data.stem}_auto_annotate_labels"
    Path(output_dir).mkdir(exist_ok=True, parents=True)

    seg_results = seg_model(
        data, device=device, conf=conf, iou=iou, imgsz=imgsz, max_det=max_det, classes=classes, retina_masks=True,
    )
    for result in seg_results:
        class_ids = result.boxes.cls.int().tolist()  # noqa
        if len(class_ids):
            masks = result.masks.xy
            print(f"Processing: {result.path} ({len(class_ids)} objects)")
            img = predictor.set_image(result.path)
            segments = predictor(masks = masks)
            # sam_results = sam_model.predict(
            #     result.orig_img, masks=masks, verbose=False, save=False, device=device)
            # segments = sam_results[0].masks.xyn  # noqa

            with open(f"{Path(output_dir) / Path(result.path).stem}.txt", "w") as f:
                for i in range(len(segments)):
                    s = segments[i]
                    if len(s) == 0:
                        continue
                    segment = map(str, segments[i].reshape(-1).tolist())
                    f.write(f"{class_ids[i]} " + " ".join(segment) + "\n")


if __name__ == "__main__":
    img_path = '/auto_annotate/data_tmp'
    output_dir = 'data_auto_annotate'
    auto_annotate(data=img_path, output_dir=output_dir, device='cuda', imgsz=640,
                  seg_model="/runs/segment/train/weights/best.pt", sam_model="sam2_b.pt")
    print(f"Annotations saved to {output_dir}")
```
output: 
```
/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/predict.py:294: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:278.)
  masks = torch.as_tensor(masks, dtype=torch.float32, device=self.device).unsqueeze(1)
Traceback (most recent call last):
  File "/data/AI/EGen/trongld/auto_annotate/auto.py", line 88, in <module>
    auto_annotate(data=img_path, output_dir=output_dir, device='cuda', imgsz=640,
  File "/data/AI/EGen/trongld/auto_annotate/auto.py", line 71, in auto_annotate
    segments = predictor(masks = masks)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 173, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 259, in stream_inference
    preds = self.inference(im, *args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/predict.py", line 205, in inference
    return self.prompt_inference(im, bboxes, points, labels, masks, multimask_output)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/predict.py", line 713, in prompt_inference
    sparse_embeddings, dense_embeddings = self.model.sam_prompt_encoder(
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/modules/encoders.py", line 369, in forward
    dense_embeddings = self._embed_masks(masks)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/modules/encoders.py", line 306, in _embed_masks
    return self.mask_downscaling(masks)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
RuntimeError: Calculated padded input size per channel: (526 x 1). Kernel size: (2 x 2). Kernel size can't be greater than actual input size
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @trongldwork, thank you for reaching out and sharing your detailed implementation and error 🍀! This is an automated response, but rest assured that an Ultralytics engineer will assist you shortly.

### Suggestions 🚀

If this is a 🐛 Bug Report, please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it efficiently. For your case, this might involve:
1. A minimal script that replicates the issue.
2. The specific inputs, such as a sample image or dataset, causing the behavior.
3. Clear details about your environment, like installed package versions.

From your traceback, it appears the issue arises from the `SAM2Predictor`'s inference pipeline where mask processing is involved. Specifically, your input size seems incompatible with the kernel size in a convolution operation. Double-check the mask dimensions and adjust preprocessing or upscaling settings.

### Checklist 🔍
Before the engineering team assists further, please ensure the following:
1. You are using the latest version of `ultralytics`:
   ```bash
   pip install -U ultralytics
   ```
2. Your Python environment meets all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), specifically **Python>=3.8** and **PyTorch>=1.8**.
3. Test your implementation on one of the verified environments to rule out potential local setup issues:
   - <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a>
   - <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
   - <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### Resources 📚
- For more on using YOLO with SAM, visit our [Docs](https://docs.ultralytics.com) and especially the [SAM module](https://docs.ultralytics.com/modes/#sam).
- For fine-tuning your custom training workflows, refer to our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

### Community 💬
If you’d like to discuss this further with other users:
- Join our [Discord](https://discord.com/invite/ultralytics) 🎧 for real-time chat
- Share your detailed use case on [Discourse](https://community.ultralytics.com)
- Explore discussion threads on our [Subreddit](https://reddit.com/r/Ultralytics)

### CI Verification ✅
Additionally, verify the [Ultralytics CI tests](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule):

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Thanks for your patience, and we’ll aim to address this swiftly! 😊

**Comment by Y-T-G** [comment]
Masks prompt isn't supported. You can use boxes or points.

https://docs.ultralytics.com/models/sam/#sam-prediction-example

**Comment by Y-T-G** [comment]
Masks are supposed to be of shape `(N, H, W)`. You're not passing masks. You're passing polygons.

https://github.com/ultralytics/ultralytics/blob/1ce3c40cb3ec6ddec84d615ebe8734a33048f458/ultralytics/models/sam/predict.py#L219

You should pass `result.masks.data`.

**Comment by trongldwork** [comment]
> Masks are supposed to be of shape `(N, H, W)` and resized to 256x256. You're not passing masks. You're passing polygons.
> 
> https://github.com/ultralytics/ultralytics/blob/1ce3c40cb3ec6ddec84d615ebe8734a33048f458/ultralytics/models/sam/predict.py#L219
> 
> You should pass `result.masks.data` after resizing to 256x256.

i've got it, i resized and it worked, but only with single object, with multiple object image, i need to loop over each mask and the result is still not good as what i expect

**Comment by glenn-jocher** [comment]
@trongldwork for multiple objects, you can batch-process the masks by stacking them into a single tensor of shape `(N, H, W)` after resizing each to 256x256. SAM2 processes all masks in a batch inherently. Ensure the masks align with corresponding prompts and have consistent scaling for better results. If issues persist, consider fine-tuning the SAM2 model or experimenting with different prompt configurations to improve output quality. For more details, refer to the [SAM2 documentation](https://docs.ultralytics.com/models/sam-2/).

**Comment by trongldwork** [comment]
> @trongldwork for multiple objects, you can batch-process the masks by stacking them into a single tensor of shape `(N, H, W)` after resizing each to 256x256. SAM2 processes all masks in a batch inherently. Ensure the masks align with corresponding prompts and have consistent scaling for better results. If issues persist, consider fine-tuning the SAM2 model or experimenting with different prompt configurations to improve output quality. For more details, refer to the [SAM2 documentation](https://docs.ultralytics.com/models/sam-2/).

with code i provided, can you modify it for me, i try to batching mask but it did not work

**Comment by glenn-jocher** [comment]
I am unable to modify or write custom code for you directly. However, to batch-process the masks, you can resize and stack them into a tensor of shape `(N, H, W)` and pass it to the `SAM2Predictor`. If you're encountering issues, please ensure each mask is resized correctly and verify that the tensor shape is consistent. You can refer to the [SAM2 documentation](https://docs.ultralytics.com/models/sam-2/) for guidance.

**Comment by trongldwork** [comment]
```
from pathlib import Path
import numpy as np
from ultralytics import SAM, YOLO

from ultralytics.models.sam import Predictor as SAMPredictor
from ultralytics.models.sam import SAM2Predictor


def auto_annotate(
    data,
    seg_model="yolo11n-seg.pt",
    sam_model="sam_b.pt",
    device="",
    conf=0.25,
    iou=0.45,
    imgsz=640,
    max_det=300,
    classes=None,
    output_dir=None,
):
    """
    Automatically annotates images using a YOLO object detection model and a SAM segmentation model.

    This function processes images in a specified directory, detects objects using a YOLO model, and then generates
    segmentation masks using a SAM model. The resulting annotations are saved as text files.

    Args:
        data (str): Path to a folder containing images to be annotated.
        det_model (str): Path or name of the pre-trained YOLO detection model.
        sam_model (str): Path or name of the pre-trained SAM segmentation model.
        device (str): Device to run the models on (e.g., 'cpu', 'cuda', '0').
        conf (float): Confidence threshold for detection model; default is 0.25.
        iou (float): IoU threshold for filtering overlapping boxes in detection results; default is 0.45.
        imgsz (int): Input image resize dimension; default is 640.
        max_det (int): Limits detections per image to control outputs in dense scenes.
        classes (list): Filters predictions to specified class IDs, returning only relevant detections.
        output_dir (str | None): Directory to save the annotated results. If None, a default directory is created.

    Examples:
        >>> from ultralytics.data.annotator import auto_annotate
        >>> auto_annotate(data="ultralytics/assets", det_model="yolo11n.pt", sam_model="mobile_sam.pt")

    Notes:
        - The function creates a new directory for output if not specified.
        - Annotation results are saved as text files with the same names as the input images.
        - Each line in the output text file represents a detected object with its class ID and segmentation points.
    """
    seg_model = YOLO(seg_model)


# Create SAMPredictor
    overrides = dict(conf=conf, task="segment", mode="predict", imgsz=1024,
                      model=sam_model)
    predictor = SAM2Predictor(overrides=overrides)
    predictor.get_model()
    data = Path(data)
    if not output_dir:
        output_dir = data.parent / f"{data.stem}_auto_annotate_labels"
    Path(output_dir).mkdir(exist_ok=True, parents=True)

    seg_results = seg_model(
        data, device=device, conf=conf, iou=iou, imgsz=imgsz, max_det=max_det, classes=classes, retina_masks=True,
    )
    for result in seg_results:
        class_ids = result.boxes.cls.int().tolist()  # noqa
        if len(class_ids):
            masks = result.masks.xy
            print(f"Processing: {result.path} ({len(class_ids)} objects)")
            img = predictor.set_image(result.path)
            # resize mask to (N,256,256)
            masks = np.array([np.array(np.resize(mask, (256, 256)))
                             for mask in masks])
            print(masks.shape)
            sam_results = predictor(masks=masks)
            # sam_results = sam_model.predict(
            #     result.orig_img, masks=masks, verbose=False, save=False, device=device)
            segments = sam_results[0].masks.xyn  # noqa

            with open(f"{Path(output_dir) / Path(result.path).stem}.txt", "w") as f:
                for i in range(len(segments)):
                    s = segments[i]
                    if len(s) == 0:
                        continue
                    segment = map(str, segments[i].reshape(-1).tolist())
                    f.write(f"{class_ids[i]} " + " ".join(segment) + "\n")


if __name__ == "__main__":
    img_path =
    output_dir = 
    auto_annotate(data=img_path, output_dir=output_dir, device='cuda', imgsz=1280,
                  seg_model=, sam_model="sam2.1_b.pt")
    print(f"Annotations saved to {output_dir}")

```
this code worked but cant not running with image that have multiple masks and results is very worse than boxes and points prompt. Here is the error with mask as shape (2, 256, 256):
```
File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/predict.py", line 205, in inference
    return self.prompt_inference(im, bboxes, points, labels, masks, multimask_output)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/predict.py", line 721, in prompt_inference
    pred_masks, pred_scores, _, _ = self.model.sam_mask_decoder(
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/modules/decoders.py", line 353, in forward
    masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks(
  File "/home/usr/anaconda3/envs/gscsht/lib/python3.10/site-packages/ultralytics/models/sam/modules/decoders.py", line 416, in predict_masks
    assert image_embeddings.shape[0] == tokens.shape[0]
AssertionError
```

**Comment by glenn-jocher** [comment]
@trongldwork the error occurs because the batch size of `image_embeddings` and `tokens` does not match. When using multiple masks, ensure the input dimensions are consistent. Specifically, verify that the number of masks `(N)` aligns with the batch size of the `image_embeddings`. If the issue persists, consider using bounding boxes or points as prompts, as SAM2 is optimized for such inputs. For more information, refer to the [SAM2 documentation](https://docs.ultralytics.com/models/sam-2/).
