### ISSUE TITLE
Updated Ultralytics to use YOLO11 but now YOLOOv10 not loading. 

### ISSUE THREAD

**Issue by mazatov** [ultralytics/ultralytics#18028]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Install

### Bug

After update to the latest version of Ultralytics I cannot load YOLOv10. I'm wondering if some library got overwritten with the update? 

```
Installing collected packages: ultralytics
  Attempting uninstall: ultralytics
    Found existing installation: ultralytics 8.3.39
    Uninstalling ultralytics-8.3.39:
      Successfully uninstalled ultralytics-8.3.39
Successfully installed ultralytics-8.3.41
(yolov10) ubuntu@ip-10-0-12-229:~$ python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics import YOLOv10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'YOLOv10' from 'ultralytics' (/home/ubuntu/anaconda3/envs/yolov10/lib/python3.9/site-packages/ultralytics/__init__.py)
```

### Environment

Ultralytics 8.3.39 🚀 Python-3.9.19 torch-2.4.1+cu118 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (4 CPUs, 15.4 GB RAM, 173.3/387.7 GB disk)

OS                  Linux-4.4.0-1128-aws-x86_64-with-glibc2.23
Environment         Linux
Python              3.9.19
Install             pip
RAM                 15.38 GB
Disk                173.3/387.7 GB
CPU                 Intel Xeon Platinum 8259CL 2.50GHz
CPU count           4
GPU                 Tesla T4, 15110MiB
GPU count           1
CUDA                11.8

numpy               ✅ 1.23.2>=1.23.0
numpy               ✅ 1.23.2<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.1+cu118>=1.8.0
torch               ✅ 2.4.1+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.19.1+cu118>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.12>=2.0.0
{'OS': 'Linux-4.4.0-1128-aws-x86_64-with-glibc2.23', 'Environment': 'Linux', 'Python': '3.9.19', 'Install': 'pip', 'RAM': '15.38 GB', 'Disk': '173.3/387.7 GB', 'CPU': 'Intel Xeon Platinum 8259CL 2.50GHz', 'CPU count': 4, 'GPU': 'Tesla T4, 15110MiB', 'GPU count': 1, 'CUDA': '11.8', 'Package Info': {'numpy': '✅ 1.23.2<2.0.0; sys_platform == "darwin"', 'matplotlib': '✅ 3.9.2>=3.3.0', 'opencv-python': '✅ 4.9.0.80>=4.6.0', 'pillow': '✅ 10.2.0>=7.1.2', 'pyyaml': '✅ 6.0.2>=5.3.1', 'requests': '✅ 2.32.3>=2.23.0', 'scipy': '✅ 1.13.1>=1.4.1', 'torch': '✅ 2.4.1+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"', 'torchvision': '✅ 0.19.1+cu118>=0.9.0', 'tqdm': '✅ 4.66.5>=4.64.0', 'psutil': '✅ 5.9.8', 'py-cpuinfo': '✅ 9.0.0', 'pandas': '✅ 2.2.2>=1.1.4', 'seaborn': '✅ 0.13.2>=0.11.0', 'ultralytics-thop': '✅ 2.0.12>=2.0.0'}}

### Minimal Reproducible Example

Installing collected packages: ultralytics
  Attempting uninstall: ultralytics
    Found existing installation: ultralytics 8.3.39
    Uninstalling ultralytics-8.3.39:
      Successfully uninstalled ultralytics-8.3.39
Successfully installed ultralytics-8.3.41
(yolov10) ubuntu@ip-10-0-12-229:~$ python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics import YOLOv10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'YOLOv10' from 'ultralytics' (/home/ubuntu/anaconda3/envs/yolov10/lib/python3.9/site-packages/ultralytics/__init__.py)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @mazatov, thank you for reporting this issue and for your interest in Ultralytics 🚀! This is an automated response to help you get started. An Ultralytics engineer will also assist you shortly.

We recommend visiting the [Docs](https://docs.ultralytics.com) for additional resources and examples, including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage guides, which might help clarify any potential confusion.

It looks like you're encountering an ImportError when trying to load `YOLOv10`. If this is indeed a 🐛 Bug Report, we'll need additional details. Specifically, please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) for us to debug the issue effectively. This helps us identify the problem faster and work toward a solution.

### Common Next Steps

1. **Ensure Correct Installation:** It seems you've updated your `ultralytics` library successfully, but please ensure you are running the latest version. Use the command below to upgrade:
   ```bash
   pip install -U ultralytics
   ```

2. **Compatibility Check:** Verify you are running Python 3.8+ and PyTorch 1.8+ per our [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml). Some older setups might conflict with newer library versions.

3. **Is YOLOv10 Available?** As of the current release, `YOLOv10` does not exist as a supported model in the `ultralytics` framework. Supported models include the latest YOLO implementations available in our [Docs](https://docs.ultralytics.com). If you intended to use a different version like YOLOv5 or YOLOv8, please update your imports accordingly.

4. **Environment Validation:** For optimal experience, run YOLO in one of the recommended environments:
   - **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
   - [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/), [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/), or [Docker](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) environments.

If your update has caused unexpected behavior, ensuring a clean reinstallation of your environment might help:
```bash
pip uninstall ultralytics
pip install ultralytics
```

### Community Support

While we investigate the issue, you can also:
- Join our [Discord](https://discord.com/invite/ultralytics) 🎧 for real-time discussions and support.
- Visit our [Discourse](https://community.ultralytics.com) forum for in-depth technical discussions.
- Explore our [Subreddit](https://reddit.com/r/Ultralytics) to collaborate with the community.

### CI Verification

Our CI tests ensure compatibility for all YOLO modes and tasks:
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing.

Let us know if you have any additional details, and thank you for helping make Ultralytics better! 🌟

**Comment by Skillnoob** [comment]
Please uninstall `v8.3.41`, the package on PyPi is compromised, we are working on resolving the issue. `v8.3.40` is safe to use.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/843

To uninstall ultralytics:
```
pip uninstall ultralytics
```
You can safely install Ultralytics through the following commands:
```
pip install git+https://github.com/ultralytics/ultralytics.git
```
or:
```
pip install ultralytics==8.3.40
```

**Comment by Y-T-G** [comment]
Also `YOLOv10` isn't a function in official ultralytics. You use `YOLO()` to load the model. `YOLOv10()` is used by the YOLOv10 fork of `ultralytics`, not official `ultralytics`.

**Comment by mazatov** [comment]
Thanks @Y-T-G , I must have had the fork installed before. Thanks!
