### ISSUE TITLE
v8.3.41 taking 100% cpu ultralytics_run

### ISSUE THREAD

**Issue by sanket-valani-tss** [ultralytics/ultralytics#18030]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Build the dockerfile with app.py, it fails on curl missing error
```python
2024-12-05 13:09:43 Creating new Ultralytics Settings v0.0.6 file ✅ 
2024-12-05 13:09:43 View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
2024-12-05 13:09:43 Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
2024-12-05 13:09:43 Traceback (most recent call last):
2024-12-05 13:09:43   File "/app/app.py", line 6, in <module>
2024-12-05 13:09:43     model = YOLO().to("cpu")
2024-12-05 13:09:43   File "/usr/local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 20, in __init__
2024-12-05 13:09:43     safe_download(
2024-12-05 13:09:43   File "/usr/local/lib/python3.10/site-packages/ultralytics/utils/downloads.py", line 349, in safe_download
2024-12-05 13:09:43     r = subprocess.run(["curl", "-#", "-H","Accept: application/vnd.github.raw+json",f"-sSL", url, "-o", f, "--retry", "3", "-C", "-"]).returncode
2024-12-05 13:09:43   File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
2024-12-05 13:09:43     with Popen(*popenargs, **kwargs) as process:
2024-12-05 13:09:43   File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
2024-12-05 13:09:43     self._execute_child(args, executable, preexec_fn, close_fds,
2024-12-05 13:09:43   File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
2024-12-05 13:09:43     raise child_exception_type(errno_num, err_msg, err_filename)
2024-12-05 13:09:43 FileNotFoundError: [Errno 2] No such file or directory: 'curl'
```

post adding curl in the dockerfile and created a new image
flask app starts up but cpu spikes up to ~100%

```python
100%|██████████| 5.35M/5.35M [00:00<00:00, 22.7MB/s]
2024-12-05 13:18:09 WARNING ⚠️ 'source' is missing. Using 'source=/usr/local/lib/python3.10/site-packages/ultralytics/assets'.
2024-12-05 13:18:09 
2024-12-05 13:18:14 image 1/2 /usr/local/lib/python3.10/site-packages/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 433.4ms
2024-12-05 13:18:15 image 2/2 /usr/local/lib/python3.10/site-packages/ultralytics/assets/zidane.jpg: 384x640 2 persons, 1 tie, 347.5ms
2024-12-05 13:18:15 Speed: 15.6ms preprocess, 390.5ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)
2024-12-05 13:18:15  * Serving Flask app 'app' (lazy loading)
2024-12-05 13:18:15  * Environment: production
2024-12-05 13:18:15    WARNING: This is a development server. Do not use it in a production deployment.
2024-12-05 13:18:15    Use a production WSGI server instead.
2024-12-05 13:18:15  * Debug mode: off
2024-12-05 13:18:15  * Running on all addresses.
2024-12-05 13:18:15    WARNING: This is a development server. Do not use it in a production deployment.
2024-12-05 13:18:15  * Running on http://172.17.0.3:8888/ (Press CTRL+C to quit)
```

![image](https://github.com/user-attachments/assets/dd876e4e-dbb5-4fb7-8113-f7b0d9111d55)

### Environment

Docker container with base python 3.10-slim
container has 4 cores 

### Minimal Reproducible Example

Dockerfile
```Dockerfile
FROM python:3.10-slim

COPY . /app
WORKDIR /app

RUN apt-get update && \
    apt-get install -y libgomp1 libgl1-mesa-glx libglib2.0-0 libsm6 libxrender1 libxext6 libzbar0

RUN pip install Flask==2.0.2 && \
    pip install werkzeug==2.0.2 && \
    pip install ultralytics==8.3.41

EXPOSE 8888

CMD ["python", "app.py"]
```

app.py
```python
from flask import Flask
from ultralytics import YOLO

app = Flask(__name__)

model = YOLO().to("cpu")
model.predict()

@app.route("/")
def root():
    return {"message": "Server is up"}


@app.route("/predict")
def predict():
    res = model.predict()
    return {"message": "success"}

if __name__ == '__main__':
    app.run(debug=False, host='0.0.0.0', port=8888, threaded=False, processes=15)
```
just build the docker image and run it
it fails on curl add curl in dockerfile install, and rerun it

### Additional

This does not happen if we put ultralytics==8.3.40

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @sanket-valani-tss, thank you for bringing up this issue and for sharing such a detailed report! 🚀 Your diligence in outlining the problem and providing logs, code snippets, and reproducible steps is greatly appreciated. 

To help us diagnose the issue further and address the 100% CPU utilization, we recommend the following:

1. **Upgrade**:
   Ensure you're using the latest version of the `ultralytics` package by upgrading it along with its dependencies. You can do so with the following command:
   ```bash
   pip install -U ultralytics
   ```
   This helps verify if the issue persists in the most up-to-date version.

2. **Environment**:
   Verify that your environment (Docker or other infrastructure) aligns with our supported configurations. YOLO can be tested in any of the following pre-configured environments to confirm behavior:
   - Notebooks with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

   If you're using Docker, ensure all dependencies, including CUDA (if applicable), are properly installed and configured.

3. **Minimum Reproducible Example (MRE)**:
   While your provided Dockerfile and app script are helpful, reducing your setup to the absolute minimum required to replicate the 100% CPU utilization issue would assist in pinpointing the root cause faster. For guidance, see our [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/).

4. **Development Server**:
   Running Flask's default development server (`app.run`) in a production Docker container isn't ideal as it may not fully leverage Docker’s process handling and resources correctly, potentially causing CPU spikes. We recommend moving to production-ready WSGI servers (e.g., Gunicorn or uWSGI). 

   For example, update your `CMD` in the Dockerfile:
   ```Dockerfile
   CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8888", "app:app"]
   ```

5. **Docs**:
   Check out our [documentation](https://docs.ultralytics.com) for tips on optimizing your usage of the Ultralytics library, including model inference on CPUs.

6. **Community Support**:
   Feel free to connect with the wider Ultralytics community for additional support or ideas:
   - Real-time chat: [Discord](https://discord.com/invite/ultralytics) 🎧
   - In-depth discussions: [Discourse](https://community.ultralytics.com)
   - Knowledge sharing: [Subreddit](https://reddit.com/r/Ultralytics)

🚧 Please note, this is an automated response tailored to your issue and an Ultralytics engineer will review and assist you as soon as possible. If you discover any further details in the meantime, updating this thread with additional information will be highly beneficial!

Thank you for your patience and contribution! 😊

**Comment by Y-T-G** [comment]
Please uninstall it and downgrade to 8.3.40. The latest version is compromised. We are investigating it.

**Comment by Skillnoob** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/843

**Comment by zopieux** [comment]
Ultralytics was attacked (or did it on purpose, waiting for a post mortem there), 8.3.41 contains nefarious code downloading and running a crypto miner hosted as a GitHub blob.

All parties were already notified (GitHub, PyPi, ultralytics). My [security advisory](https://github.com/ultralytics/ultralytics/security/advisories/GHSA-36wh-cc56-8jm9) is pending public release.

**Comment by woct0rdho** [comment]
ultralytics 8.3.42 on pypi is still compromised. DO NOT upgrade from pypi for now!

**Comment by bghira** [comment]
they did it on purpose. months ago pretended to be compromised by 'Jia Tan' probably in preparation for something like this. they claim everything is secure for their source code and that all kinds of vulnerabilities are monitored for by various scanning tools. but oddly this one got missed and somehow the pypi package compromised 2 times in one year.

even if they didn't do it on purpose it just smells like recklessness

**Comment by Skillnoob** [comment]
@bghira Thats a lie. Internally we are try to figure out how exactly this happened and we were all shocked when this happened and are trying to solve the issue asap. The current package on PyPi is safe (compromised versions got deleted) and you can find more information here:
https://github.com/ultralytics/ultralytics/issues/18027#issuecomment-2520462686

**Comment by glenn-jocher** [comment]
Thank you @sanket-valani-tss @zopieux @woct0rdho @bghira for bringing this to our attention. We confirm that Ultralytics versions 8.3.41 and 8.3.42 were compromised by a malicious code injection targeting cryptocurrency mining. Both versions have been immediately removed from PyPI.

We have released 8.3.43 which addresses this security issue. Our team is conducting a full security audit and implementing additional safeguards to prevent similar incidents.

We apologize to all affected users and appreciate your swift detection of this security breach. We are committed to ensuring the safety and integrity of our package.

**Comment by DmitriyLewen** [comment]
Hello @zopieux 

> All parties were already notified (GitHub, PyPi, ultralytics). My [security advisory](https://github.com/ultralytics/ultralytics/security/advisories/GHSA-36wh-cc56-8jm9) is pending public release.

I can't open this advisory.
Can you confirm that this is not the same as https://github.com/ultralytics/actions/security/advisories/GHSA-7x29-qqmq-v6qc
and that your advisory is for the `ultralytics` package (not `ultralytics-action`)?
I ask so that I don't create additional identical advisories.

**Comment by zopieux** [comment]
Hi @DmitriyLewen,

>I can't open this advisory.

* Dec 5th 02:49 GMT+1: I open the advisory, minutes after reporting the release to PyPi
* Dec 5th 11:25 GMT+1: glenn-jocher replies “Thank you for the prompt report […]”
* Dec 7th 12:33 GMT+1: I ask “Will you be releasing this GHSA any time soon?”

\*crickets\* since. Ultralytics team is basically MIA. The advisory remains unpublished.

>Can you confirm that this is not the same as [GHSA-7x29-qqmq-v6qc](https://github.com/ultralytics/actions/security/advisories/GHSA-7x29-qqmq-v6qc)

This isn't the same, I was not aware of the attack chain at the time and my GHSA simply states the facts: the ultraltytics Actions CI is somehow tainted and was able to patch the PyPi release with nefarious code that downloads and runs a crypto miner (hosted on GitHub).

**Comment by DmitriyLewen** [comment]
@zopieux 
To make sure I understand you correctly:
You used `ultralytics` as the vulnerable package, correct?

**Comment by zopieux** [comment]
Yes (in a sandbox, I never run any ML code on bare metal because it is both a security nightmare and the biggest dependency hell I got to witness). Why does it matter tho?

**Comment by glenn-jocher** [comment]
Running any code in a sandboxed environment is a good security practice, especially for ML pipelines, given their dependencies and potential vulnerabilities. It matters here because understanding your usage context helps provide accurate guidance or assess risks, particularly in cases like the recent compromised PyPI releases.

**Comment by DmitriyLewen** [comment]
Hello @glenn-jocher 
Can you clarify the advisory for the `ultralytics` package?

We at [Trivy](https://github.com/aquasecurity/trivy) are concerned that the `GitHub advisory database` only contains advisories for `ultralytics-action` (see https://github.com/ultralytics/actions/security/advisories/GHSA-7x29-qqmq-v6qc).
Are you going to add another advisory for the `ultralytics` package?

We need this information to understand how we can add an advisory for the Ultralytics package to prevent users from installing the vulnerable Ultralytics package.

Best Regards, Dmitriy!

**Comment by glenn-jocher** [comment]
Hello @DmitriyLewen, 

Thank you for bringing this up. We acknowledge the concern and confirm that a separate advisory for the `ultralytics` package is warranted given the recent incident. We are currently working on releasing a detailed advisory to the GitHub advisory database to ensure transparency and assist in protecting users. Please stay tuned for updates as we finalize the process.
