### ISSUE TITLE
yolo11.yaml from scratch model raising error in layer C3k2

### ISSUE THREAD

**Issue by Chebil-Ilef** [ultralytics/ultralytics#18053]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

from ultralytics import YOLO

model= YOLO("yolo11.yaml")
model.train(data="coco8.yaml",batch_size=2,epochs=2)

--------------------------------------------------------------
WARNING ⚠️ no model scale passed. Assuming scale='n'.
Traceback (most recent call last):
  File "/home/lost-elf/Desktop/test/test.py", line 4, in <module>
    model= YOLO("yolo11.yaml")
  File "/home/lost-elf/Desktop/KIAN/itona-trainer-executor/core/utils/ultralytics/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/lost-elf/Desktop/KIAN/itona-trainer-executor/core/utils/ultralytics/ultralytics/engine/model.py", line 143, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/home/lost-elf/Desktop/KIAN/itona-trainer-executor/core/utils/ultralytics/ultralytics/engine/model.py", line 263, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/home/lost-elf/Desktop/KIAN/itona-trainer-executor/core/utils/ultralytics/ultralytics/nn/tasks.py", line 315, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/home/lost-elf/Desktop/KIAN/itona-trainer-executor/core/utils/ultralytics/ultralytics/nn/tasks.py", line 951, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
KeyError: 'C3k2'

### Environment

Ultralytics YOLOv8.2.93 🚀 Python-3.10.15 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 3801MiB)
Setup complete ✅ (20 CPUs, 23.2 GB RAM, 86.1/467.9 GB disk)

OS                  Linux-6.8.0-49-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.15
Install             git
RAM                 23.17 GB
CPU                 12th Gen Intel Core(TM) i7-12700H
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0

### Minimal Reproducible Example

from ultralytics import YOLO

model= YOLO("yolo11.yaml")

model.train(data="coco8.yaml",batch_size=2,epochs=2)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Chebil-Ilef, thank you for your interest in Ultralytics 🚀! We appreciate your detailed report. This is an automated response, but don't worry—an Ultralytics engineer will review your issue and assist you shortly.

From your description, it looks like you're encountering a specific error related to the `C3k2` layer while training a custom `yolo11.yaml` model. To help us debug this 🐛 issue faster, could you please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This would include the `yolo11.yaml` file you're using and potentially any custom modifications made to your setup. 

In the meantime:

### Upgrade
Ensure you're using the latest version of the `ultralytics` package, as bugs are frequently resolved in the latest updates. You can upgrade using:

```bash
pip install -U ultralytics
```

If the issue persists after upgrading, it could be related to the custom model configuration in `yolo11.yaml`. Please double-check the file adheres to the expected format described in our [YOLO Configuration Documentation](https://docs.ultralytics.com).

### Environment
You may also want to verify you're working in one of the supported and verified environments below with updated dependencies such as [PyTorch](https://pytorch.org/) and CUDA:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

### Learn More
For further guidance, feel free to explore:
- [Python Usage Examples](https://docs.ultralytics.com/usage/python/)
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)

🌟 Join our community for additional support and knowledge sharing:
- [Discord](https://discord.com/invite/ultralytics) for real-time help 🎧
- [Discourse](https://community.ultralytics.com) for long-form discussions
- [Reddit](https://reddit.com/r/Ultralytics) for sharing ideas and updates with others

### Status
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, confirming compatibility for models and tasks on macOS, Windows, and Ubuntu.

Let us know if you have any additional details to share! 🚀

**Comment by Y-T-G** [comment]
Upgrade Ultralytics. YOLO11 was not present in 8.2.x.
