### ISSUE TITLE
Exporting RT-DETR model to TFLite crashes

### ISSUE THREAD

**Issue by isuchy** [ultralytics/ultralytics#18055]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I used really only the source code from Ultralytics Docs to retrain the model on my custom dataset and then I tried to export the model to Tensorflow Lite format. The model was successfully exported to ONNX format, as well as to Tensorflow as a saved model, but when converting to TF Lite, it threw several warnings about invalid op Slice (Dimensional compression of `Slice` fails.) and then the process crashed. 
Do you see it as a bug in onnx2tf? 

```
Ultralytics 8.3.43 🚀 Python-3.10.12 torch-2.5.1+cu121 CPU (Intel Xeon 2.00GHz)
rt-detr-l summary: 502 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs

PyTorch: starting from '/content/runs/detect/train/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 5) (63.1 MB)
requirements: Ultralytics requirements ['sng4onnx>=1.0.1', 'onnx_graphsurgeon>=0.3.26', 'onnx2tf>1.17.5,<=1.22.3', 'tflite_support'] not found, attempting AutoUpdate...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Collecting sng4onnx>=1.0.1
  Downloading sng4onnx-1.0.4-py3-none-any.whl.metadata (4.6 kB)
Collecting onnx_graphsurgeon>=0.3.26
  Downloading onnx_graphsurgeon-0.5.2-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting onnx2tf<=1.22.3,>1.17.5
  Downloading onnx2tf-1.22.3-py3-none-any.whl.metadata (136 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.6/136.6 kB 7.0 MB/s eta 0:00:00
Collecting tflite_support
  Downloading tflite_support-0.4.4-cp310-cp310-manylinux2014_x86_64.whl.metadata (2.4 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from onnx_graphsurgeon>=0.3.26) (1.26.4)
Requirement already satisfied: onnx>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from onnx_graphsurgeon>=0.3.26) (1.17.0)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tflite_support) (1.4.0)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tflite_support) (24.3.25)
Collecting protobuf<4,>=3.18.0 (from tflite_support)
  Downloading protobuf-3.20.3-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (679 bytes)
Collecting sounddevice>=0.4.4 (from tflite_support)
  Downloading sounddevice-0.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting pybind11>=2.6.0 (from tflite_support)
  Downloading pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: CFFI>=1.0 in /usr/local/lib/python3.10/dist-packages (from sounddevice>=0.4.4->tflite_support) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from CFFI>=1.0->sounddevice>=0.4.4->tflite_support) (2.22)
Downloading sng4onnx-1.0.4-py3-none-any.whl (5.9 kB)
Downloading onnx_graphsurgeon-0.5.2-py2.py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 263.5 MB/s eta 0:00:00
Downloading onnx2tf-1.22.3-py3-none-any.whl (435 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 435.0/435.0 kB 31.8 MB/s eta 0:00:00
Downloading tflite_support-0.4.4-cp310-cp310-manylinux2014_x86_64.whl (60.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 MB 56.0 MB/s eta 0:00:00
Downloading protobuf-3.20.3-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 293.1 MB/s eta 0:00:00
Downloading pybind11-2.13.6-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.3/243.3 kB 277.4 MB/s eta 0:00:00
Downloading sounddevice-0.5.1-py3-none-any.whl (32 kB)
Installing collected packages: sng4onnx, pybind11, protobuf, onnx2tf, sounddevice, tflite_support, onnx_graphsurgeon
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.5
    Uninstalling protobuf-4.25.5:
      Successfully uninstalled protobuf-4.25.5
Successfully installed onnx2tf-1.22.3 onnx_graphsurgeon-0.5.2 protobuf-3.20.3 pybind11-2.13.6 sng4onnx-1.0.4 sounddevice-0.5.1 tflite_support-0.4.4

requirements: AutoUpdate success ✅ 13.0s, installed 4 packages: ['sng4onnx>=1.0.1', 'onnx_graphsurgeon>=0.3.26', 'onnx2tf>1.17.5,<=1.22.3', 'tflite_support']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


TensorFlow SavedModel: starting export with tensorflow 2.17.1...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100%|██████████| 1.11M/1.11M [00:00<00:00, 28.3MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /content/calibration_image_sample_data_20x128x128x3_float32.npy...: 100%|██████████| 1/1 [00:00<00:00, 34.84file/s]
ONNX: starting export with onnx 1.17.0 opset 19...

ONNX: slimming with onnxslim 0.1.43...
ONNX: export success ✅ 46.0s, saved as '/content/runs/detect/train/weights/best.onnx' (122.9 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...

WARNING Dimensional compression of `Slice` fails. node.name: /model.28/decoder/layers.0/cross_attn/Slice


WARNING Dimensional compression of `Slice` fails. node.name: /model.28/decoder/layers.0/cross_attn/Slice_1


WARNING Dimensional compression of `Slice` fails. node.name: /model.28/decoder/layers.1/cross_attn/Slice


WARNING Dimensional compression of `Slice` fails. node.name: /model.28/decoder/layers.1/cross_attn/Slice_1


WARNING Dimensional compression of `Slice` fails. node.name: /model.28/decoder/layers.2/cross_attn/Slice


WARNING Dimensional compression of `Slice` fails. node.name: /model.28/decoder/layers.2/cross_attn/Slice_1

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 663, in make_node
    define_fast_gridsample(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 181, in define_fast_gridsample
    pixs = (tf.math.multiply(grid + 1.0, tf.convert_to_tensor([w_in, h_in], dtype=tf.float32)) - 1.0) * 0.5
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 108, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

ERROR: input_onnx_file_path: /content/runs/detect/train/weights/best.onnx
ERROR: onnx_op_name: /model.28/decoder/layers.2/cross_attn/GridSample
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 663, in make_node
    define_fast_gridsample(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 181, in define_fast_gridsample
    pixs = (tf.math.multiply(grid + 1.0, tf.convert_to_tensor([w_in, h_in], dtype=tf.float32)) - 1.0) * 0.5
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 108, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-723ebe429b5b>", line 14, in <cell line: 14>
    model.export(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 737, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 366, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 141, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 970, in export_saved_model
    keras_model = onnx2tf.convert(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/onnx2tf.py", line 1049, in convert
    op.make_node(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 378, in print_wrapper_func
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py](https://localhost:8080/#) in print_wrapper_func(*args, **kwargs)
    311         try:
--> 312             result = func(*args, **kwargs)
    313 

20 frames
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py](https://localhost:8080/#) in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

### Environment

Ultralytics 8.3.43 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 39.4/235.7 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
Disk                39.4/235.7 GB
CPU                 Intel Xeon 2.00GHz
CPU count           2
GPU                 Tesla T4, 15102MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.26.4>=1.23.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.8.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.5.1+cu121>=1.8.0
torch               ✅ 2.5.1+cu121!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.20.1+cu121>=0.9.0
tqdm                ✅ 4.66.6>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.12>=2.0.0

### Minimal Reproducible Example

```
#Training RT-DETR model on custom dataset

import torch
from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR("rtdetr-l.pt")

# Train the model on the RT-DETR dataset for 20 epochs
results = model.train(data="/content/datasets/data.yaml", epochs=20, imgsz=640, batch=16, device=0, deterministic=False)
```

```
#Exporting the RT-DETR model to TFLite (without INT8 quantization)

from ultralytics import RTDETR

# Load the RT-DETR model using Ultralytics
model = RTDETR('/content/runs/detect/train/weights/best.pt')

# TFLite
model.export(
    format="tflite",
    opset=19,
    data="/content/datasets/data.yaml",
)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @isuchy, thank you for your interest in Ultralytics 🚀! We recommend checking out the [Docs](https://docs.ultralytics.com) for new users, where you can find many useful usage examples in [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/), as well as answers to common questions.

If this is a 🐛 Bug Report, thank you for providing a detailed description and logs! To help us investigate further, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that demonstrates the issue? This will allow us to debug more efficiently.

From your report:
1. It appears the problem arises when exporting the RT-DETR model to TensorFlow Lite.
2. The traceback mentions potential issues with dynamic dimensions in the ONNX to TFLite conversion process and suggests options like `-b` or `-ois`.
3. Ensure that the proper versions of the `onnx2tf` package (1.17.5 ≤ version ≤ 1.22.3) and dependencies are installed as a mismatch could cause errors. You could try upgrading your `ultralytics` package to verify the issue persists on the latest version:

```bash
pip install -U ultralytics
```

If the issue persists after upgrading, additional context, such as custom configurations or exceptions, would be helpful to identify the root cause.

### RT-DETR Model Export Considerations

For more details on exporting models to different formats, explore the [Export Documentation](https://docs.ultralytics.com/modes/export/). If you're specifically encountering challenges with slices or dynamic dimensions in the TFLite conversion process, you may refer to the onnx2tf recommendations mentioned in the traceback (e.g., rewriting inputs to static shapes, using `-kt` or `-kat` options). 

### Community and Resources

If you're stuck, there are additional ways to get more immediate help or guidance:
- Join our [Discord](https://discord.com/invite/ultralytics) community for real-time support 🎧.
- Visit [Discourse](https://community.ultralytics.com) for detailed discussions.
- Join discussions on our [Subreddit](https://reddit.com/r/Ultralytics).

You can also test YOLO in verified environments with GPUs and pre-installed dependencies:
- **Colab**: <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle**: <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Gradient**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a>

An Ultralytics engineer will review your issue and provide additional assistance soon 😊. Thank you for your patience!

**Comment by Y-T-G** [comment]
You can try tensorflow 2.18

**Comment by isuchy** [comment]
Well, it looks like an incompatibility between tensorflow, tf-keras and onnx2tf as mentioned in this [issue](https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301). Although onnx2tf 1.22.3, which is recommended there, is a pretty old version, so we'll see.

**Comment by isuchy** [comment]
> You can try tensorflow 2.18

Thanks, I'll give it a try and let you know what combination it works with.

**Comment by isuchy** [comment]
I can confirm that this does not work in the following combinations

`tensorflow==2.16.1 tf-keras==2.16.0 onnx2tf==1.22.3`

`tensorflow==2.18.0 tf-keras==2.17.0 onnx2tf==1.22.3`

`tensorflow==2.18.0 tf-keras==2.17.0 onnx2tf==1.26.2`

It crashes with the same error output
```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 663, in make_node
    define_fast_gridsample(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 181, in define_fast_gridsample
    pixs = (tf.math.multiply(grid + 1.0, tf.convert_to_tensor([w_in, h_in], dtype=tf.float32)) - 1.0) * 0.5
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 108, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

ERROR: input_onnx_file_path: /content/runs/detect/train/weights/best.onnx
ERROR: onnx_op_name: /model.28/decoder/layers.2/cross_attn/GridSample
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 312, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 385, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 55, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 663, in make_node
    define_fast_gridsample(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/GridSample.py", line 181, in define_fast_gridsample
    pixs = (tf.math.multiply(grid + 1.0, tf.convert_to_tensor([w_in, h_in], dtype=tf.float32)) - 1.0) * 0.5
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 108, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-9750b6c5250a>", line 14, in <cell line: 14>
    model.export(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 738, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 366, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 141, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 970, in export_saved_model
    keras_model = onnx2tf.convert(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/onnx2tf.py", line 1141, in convert
    op.make_node(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 378, in print_wrapper_func
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py](https://localhost:8080/#) in print_wrapper_func(*args, **kwargs)
    311         try:
--> 312             result = func(*args, **kwargs)
    313 

20 frames
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py](https://localhost:8080/#) in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

**Comment by isuchy** [comment]
> Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

I have tried, it didn't help. I also downgraded the minor version of Keras to correspond with TF 2.17. 
`!pip install tensorflow==2.17.0 keras==3.5.0 tf-keras==2.17.0 onnx2tf==1.26.2`

```
import tensorflow as tf
import keras
print(tf.__version__)
print(keras.__version__)

2.17.0
3.5.0
```

**Comment by isuchy** [comment]
The error in the custom dataset can be excluded, as I tried to test the model with rtdetr-l weights and when I exported it to TFLite, it crashed with the same error.  

You can simply reproduce it with this code.
`!yolo task=detect mode=train model=rtdetr-l.pt data=coco128.yaml epochs=5 imgsz=640`

```
from ultralytics import RTDETR

model = RTDETR('/content/runs/detect/train/weights/best.pt')

# TFLite
model.export(format="tflite")
```

**Comment by Y-T-G** [comment]
You can try exporting to ONNX and running 

`onnx2tf -i "best.onnx"

**Comment by isuchy** [comment]
It ran without error, but I can't validate the output TFLite model, it's completely useless.

```
from ultralytics import RTDETR

model = RTDETR("/content/saved_model/best_float32.tflite")

# Validate the model
metrics = model.val()
print(f'metrics.box.map: {metrics.box.map}')  # map50-95
print(f'metrics.box.map50: {metrics.box.map50}')  # map50
print(f'metrics.box.map75: {metrics.box.map75}')  # map75
```

It crashes with such an error
```
Ultralytics 8.3.44 🚀 Python-3.10.12 torch-2.5.1+cu121 CPU (Intel Xeon 2.20GHz)
Loading /content/saved_model/best_float32.tflite for TensorFlow Lite inference...
WARNING ⚠️ Metadata not found for 'model=/content/saved_model/best_float32.tflite'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-68abeca3e083>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 # Validate the model
----> 6 metrics = model.val()
      7 print(f'metrics.box.map: {metrics.box.map}')  # map50-95
      8 print(f'metrics.box.map50: {metrics.box.map50}')  # map50

2 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py](https://localhost:8080/#) in __call__(self, trainer, model)
    139                 self.args.batch = model.batch_size
    140             elif not pt and not jit:
--> 141                 self.args.batch = model.metadata.get("batch", 1)  # export.py models default to batch-size 1
    142                 LOGGER.info(f"Setting batch={self.args.batch} input of shape ({self.args.batch}, 3, {imgsz}, {imgsz})")
    143 

AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Y-T-G** [comment]
You should pass `data="data.yaml"`

**Comment by isuchy** [comment]
> You should pass `data="data.yaml"` to `model.val()`

The missing `data` argument is not a problem in this case. Whether it is passed to the `val()` function or not, it still returns the same error.
I suspect that the call to the `val()` function crashes because [onnx2tf does not embed metadata into the converted model](https://github.com/PINTO0309/onnx2tf?tab=readme-ov-file#6-embed-metadata-in-tflite) explicitly, unlike the Ultralytics implementation, which is then obviously missing during validation. Do you think this could be a issue?

![image](https://github.com/user-attachments/assets/ed8a13a2-5dc3-4f88-aa9b-2b78af915d3d)

**Comment by isuchy** [comment]
We are still walking around the root cause of the problem. 
Could you please reproduce this simple code in Google Colab, if it will crash with the same error? 
Thanks.

> The error in the custom dataset can be excluded, as I tried to test the model with rtdetr-l weights and when I exported it to TFLite, it crashed with the same error.
> 
> You can simply reproduce it with this code. `!yolo task=detect mode=train model=rtdetr-l.pt data=coco128.yaml epochs=5 imgsz=640`
> 
> ```
> from ultralytics import RTDETR
> 
> model = RTDETR('/content/runs/detect/train/weights/best.pt')
> 
> # TFLite
> model.export(format="tflite")
> ```

**Comment by Y-T-G** [comment]
You can try running after removing these two lines:

https://github.com/ultralytics/ultralytics/blob/95a9796fee5a110fdd861e12b476b1dfa237b910/ultralytics/engine/exporter.py#L978-L979

**Comment by isuchy** [comment]
> You can try exporting after removing these two lines:
> 
> https://github.com/ultralytics/ultralytics/blob/95a9796fee5a110fdd861e12b476b1dfa237b910/ultralytics/engine/exporter.py#L978-L979

I tried, it didn't help. I will try to write PINTO0309 later. The problem is obviously in onnx2tf, which uses Tensorflow conversion of values to EagerTensor. There is a function `convert_to_eager_tensor` in the `constant_op.py`script, which is where it crashes. I added try/except there and I see that it throws an exception.
`ValueError: Failed to convert value to EagerTensor: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.`
I don't know the reason, but when it crashes, the Tensor shape contains a list of [None, None] and the call to `ops.EagerTensor(value, ctx.device_name, dtype)` throws an exception.

**Comment by Y-T-G** [comment]
Try removing all of these. It should behave the same as the command that worked 

https://github.com/ultralytics/ultralytics/blob/95a9796fee5a110fdd861e12b476b1dfa237b910/ultralytics/engine/exporter.py#L973-L979

**Comment by isuchy** [comment]
Hey man, at a first glance it seems to work 🚀 The whole process of exporting to TFLite float32/16 went through and it even calculated mAP metrics with a precision almost identical to the original Pytorch model. 
I'll have to see which argument this affects to help others as well.
Thanks for the pointing me in the right direction 👍

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad it worked out for you. If you uncover more insights or have further questions, feel free to share them with the YOLO community to help others too. The credit goes to the incredible YOLO and Ultralytics teams for their work.

**Comment by isuchy** [comment]
Hi guys, another problem occurred when I added another argument `int8=True` in the export() method. The script runs, creates SavedModel, TF Lite float16, float32 and then the execution of the script crashes suddenly and the currently running runtime session in Google Colab is shut down. No error message appears. I haven't found anyone reporting a similar issue.

**Comment by Y-T-G** [comment]
If you use `int=True`, you need line 975 and 976 which were removed.

https://github.com/ultralytics/ultralytics/blob/95a9796fee5a110fdd861e12b476b1dfa237b910/ultralytics/engine/exporter.py#L975-L976

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in the pull request [RTDETR TFLite export fix with ONNX opset constraints (ultralytics 8.3.209)](https://github.com/ultralytics/ultralytics/pull/22314).

Key changes that may resolve the problem:
- Updated to Ultralytics 8.3.209.
- Improved ONNX export reliability by requiring `onnxslim>=0.1.71` when `simplify=True`.
- For RTDETR exports to TensorFlow SavedModel:
  - Automatically selects `opset=19` if not set.
  - Enforces valid `opset` range 16–19.
  - Ensures ONNX export runs with `simplify=True` before TF conversion.
- Maintains automatic `onnxruntime` vs `onnxruntime-gpu` selection based on CUDA availability.

Credit to @Y-T-G for the PR, with contributions from @Laughing-q, @inisis, and @glenn-jocher — thank you!

How to test the fix:
1) Upgrade to the new version (and dependencies):
```bash
pip install -U ultralytics>=8.3.209
pip install -U onnxslim>=0.1.71
```

2) Re-run your export. For RTDETR → TensorFlow SavedModel, explicitly setting the opset is recommended:
```python
from ultralytics import YOLO

model = YOLO("rtdetr-l.pt")  # example RTDETR model
model.export(format="saved_model", opset=19)  # ensures compatibility
```

3) Alternatively, test the latest main branch:
```bash
pip install -U "git+https://github.com/ultralytics/ultralytics.git@main"
```

It’s also fine to wait for the next official PyPI release if you prefer pinned releases.

Please share whether this resolves the issue in your environment. Thanks for reporting this, and any further details are welcome if the problem persists. 🙏
