### ISSUE TITLE
'DetectionModel' object has no attribute 'reg_max'

### ISSUE THREAD

**Issue by Leaqiliang** [ultralytics/ultralytics#18118]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

WARNING ⚠️ 'model' argument is missing. Using default 'model=yolo11n.pt'.
Ultralytics 8.3.44 🚀 Python-3.9.13 torch-2.1.1 CUDA:0 (NVIDIA RTX A3000 Laptop GPU, 6144MiB)
engine\trainer: task=detect, mode=train, model=yolo11n.pt, data=african-wildlife.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train3, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train3
WARNING:tensorflow:From C:\Users\liqil\anaconda3\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    431452  ultralytics.nn.modules.head.Detect           [4, [64, 128, 256]]
YOLO11n summary: 319 layers, 2,590,620 parameters, 2,590,604 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs\detect\train3', view at http://localhost:6006/
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Scanning D:\lql\OneDrive\code\datasets\african-wildlife\train\labels.cache... 1052 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1052/1052 [00:00<?, ?it/s]
val: Scanning D:\lql\OneDrive\code\datasets\african-wildlife\valid\labels.cache... 225 images, 0 backgrounds, 0 corrupt: 100%|██████████| 225/225 [00:00<?, ?it/s]
Plotting labels to runs\detect\train3\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train3
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/66 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\liqil\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\liqil\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqil\anaconda3\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\cfg\__init__.py", line 972, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\engine\model.py", line 806, in train
    self.trainer.train()
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\engine\trainer.py", line 380, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "C:\Users\liqil\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\liqil\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\nn\tasks.py", line 111, in forward
    return self.loss(x, *args, **kwargs)
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\nn\tasks.py", line 290, in loss
    self.criterion = self.init_criterion()
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\nn\tasks.py", line 389, in init_criterion
    return E2EDetectLoss(self) if getattr(self, "end2end", False) else v8DetectionLoss(self)
  File "C:\Users\liqil\anaconda3\lib\site-packages\ultralytics\utils\loss.py", line 173, in __init__
    self.no = model.nc + model.reg_max * 4
  File "C:\Users\liqil\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DetectionModel' object has no attribute 'reg_max'
PS D:\lql\OneDrive\code> 

### Environment

Ultralytics 8.3.44 🚀 Python-3.9.13 torch-2.1.1 CUDA:0 (NVIDIA RTX A3000 Laptop GPU, 6144MiB)
Setup complete ✅ (16 CPUs, 63.7 GB RAM, 664.1/931.2 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.9.13
Install             pip
RAM                 63.67 GB
Disk                664.1/931.2 GB
CPU                 11th Gen Intel Core(TM) i9-11950H 2.60GHz
CPU count           16
GPU                 NVIDIA RTX A3000 Laptop GPU, 6144MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.26.4>=1.23.0
numpy               ✅ 1.26.4<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.6.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torch               ✅ 2.1.1!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.64.1>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.12>=2.0.0

### Minimal Reproducible Example

# Ultralytics YOLO 🚀, AGPL-3.0 license
# African-wildlife dataset by Ultralytics
# Documentation: https://docs.ultralytics.com/datasets/detect/african-wildlife/
# Example usage: yolo train data=african-wildlife.yaml
# parent
# ├── ultralytics
# └── datasets
#     └── african-wildlife  ← downloads here (100 MB)

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/african-wildlife # dataset root dir
train: train/images # train images (relative to 'path') 1052 images
val: valid/images # val images (relative to 'path') 225 images
test: test/images # test images (relative to 'path') 227 images

# Classes
names:
  0: buffalo
  1: elephant
  2: rhino
  3: zebra

# Download script/URL (optional)
download: https://github.com/ultralytics/assets/releases/download/v0.0.0/african-wildlife.zip

### Additional

The problem occurs when I run ‘yolo train data=african-wildlife.yaml’ directly without changing any code.How can I change the code?Thanks.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Leaqiliang, thank you for bringing this to our attention and for your interest in Ultralytics 🚀! We recommend checking our [Docs](https://docs.ultralytics.com) for guidance on how to use Ultralytics tools and exploring examples of [Python](https://docs.ultralytics.com/usage/python/) or [CLI](https://docs.ultralytics.com/usage/cli/) usage, where many common issues are addressed.

It seems that you're encountering a 🐛 bug. To assist you better, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This will help us replicate the issue and debug it effectively. Since you're already including your setup details and part of your code, please ensure that the provided example contains only the essentials needed to reproduce the error.

In the meantime:

## Upgrade

Please ensure you're using the latest version of the `ultralytics` package, as updates frequently resolve reported issues. Upgrade with the following command:

```bash
pip install -U ultralytics
```

Ensure you meet the [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/). Additionally, verify your environment is correctly set up.

## Verified Environments

YOLO works seamlessly in the following environments with preinstalled dependencies:

- **Notebooks** with free GPU support: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** using Deep Learning VMs. [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon AWS** using Deep Learning AMIs. [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Images** for containerized environments. [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Community Support

Connect with the Ultralytics community for tips and discussions:
- [Discord](https://discord.com/invite/ultralytics) for real-time chat 🎧
- [Discourse](https://community.ultralytics.com) for in-depth conversations
- [Subreddit](https://reddit.com/r/Ultralytics) to share knowledge with the community

An Ultralytics engineer will review this issue and provide further assistance soon. Thank you for your patience and collaboration! 😊

**Comment by Y-T-G** [comment]
You can try deleting `yolo11n.pt` from your folder and running again.
