### ISSUE TITLE
Exporting trained YOLOv6 model crashes

### ISSUE THREAD

**Issue by EmmanuelMess** [ultralytics/ultralytics#18225]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I have a trained yolov6 model "yolov6-face.pt", I cannot load it to export to tflite.

```
WARNING ⚠️ yolov6-face.pt appears to require 'yolov6.models', which is not in Ultralytics requirements.
AutoInstall will run now for 'yolov6.models' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official Ultralytics model, i.e. 'yolo predict model=yolov8n.pt'
Traceback (most recent call last):
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 837, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1360, in load
    return _load(
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1848, in _load
    result = unpickler.load()
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1837, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'yolov6.models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/main.py", line 90, in <module>
    detectImageWithYolo()
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/main.py", line 68, in detectImageWithYolo
    model = YOLO("yolov6-face.pt")
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 146, in __init__
    self._load(model, task=task)
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 289, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 910, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 857, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1360, in load
    return _load(
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1848, in _load
    result = unpickler.load()
  File "/home/emmanuelm/Documentos/GitHub/PersonFollower/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1837, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'yolov6.models'
```

### Environment

```
Ultralytics 8.3.44 🚀 Python-3.10.12 torch-2.5.1+cu124 CPU (AMD Ryzen 3 3200G with Radeon Vega Graphics)
Setup complete ✅ (4 CPUs, 23.3 GB RAM, 2784.2/3185.4 GB disk)
OS                  Linux-6.8.0-49-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 23.35 GB
Disk                2784.2/3185.4 GB
CPU                 AMD Ryzen 3 3200G with Radeon Vega Graphics
CPU count           4
GPU                 None
GPU count           None
CUDA                None
numpy               ✅ 2.0.2>=1.23.0
numpy               ✅ 2.0.2<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.1>=1.8.0
torch               ✅ 2.5.1!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.20.1>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.12>=2.0.0
{'OS': 'Linux-6.8.0-49-generic-x86_64-with-glibc2.35', 'Environment': 'Linux', 'Python': '3.10.12', 'Install': 'pip', 'RAM': '23.35 GB', 'Disk': '2784.2/3185.4 GB', 'CPU': 'AMD Ryzen 3 3200G with Radeon Vega Graphics', 'CPU count': 4, 'GPU': None, 'GPU count': None, 'CUDA': None, 'Package Info': {'numpy': '✅ 2.0.2<2.0.0; sys_platform == "darwin"', 'matplotlib': '✅ 3.9.2>=3.3.0', 'opencv-python': '✅ 4.10.0.84>=4.6.0', 'pillow': '✅ 11.0.0>=7.1.2', 'pyyaml': '✅ 6.0.2>=5.3.1', 'requests': '✅ 2.32.3>=2.23.0', 'scipy': '✅ 1.14.1>=1.4.1', 'torch': '✅ 2.5.1!=2.4.0,>=1.8.0; sys_platform == "win32"', 'torchvision': '✅ 0.20.1>=0.9.0', 'tqdm': '✅ 4.67.1>=4.64.0', 'psutil': '✅ 6.1.0', 'py-cpuinfo': '✅ 9.0.0', 'pandas': '✅ 2.2.3>=1.1.4', 'seaborn': '✅ 0.13.2>=0.11.0', 'ultralytics-thop': '✅ 2.0.12>=2.0.0'}}

```

### Minimal Reproducible Example

```
model = YOLO("yolov6-face.pt")
model.export(data="datasets/face-detection-dataset.yaml", format="tflite", int8=False, optimize=False)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @EmmanuelMess, thank you for your interest in Ultralytics 🚀! We appreciate you taking the time to report this.

From your description, it seems like there might be an issue with loading a YOLOv6 model using the Ultralytics framework. Note that models trained with external repositories like YOLOv6 often have specific dependencies and architectures that may not be compatible with the Ultralytics package.

To help us debug this 🐛 Bug Report, could you please provide a minimum reproducible example (MRE)? It should include only the essential code and conditions required to reproduce the issue you are experiencing. This will enable us to investigate the problem more efficiently.

Additionally, ensure you are using the latest version of the `ultralytics` package and that all your dependencies meet the required versions. Running the following command will upgrade the `ultralytics` package to the latest version:
```bash
pip install -U ultralytics
```

If you’re trying to deploy or export, remember to base your work on Ultralytics-supported models like YOLOv8 to avoid compatibility issues. Models trained on YOLOv6 might require additional modifications or retraining in a fully supported framework.

An Ultralytics engineer will review your issue soon and provide further assistance. In the meantime, if you can test with a supported model and let us know if the issue persists, it would be extremely helpful 😊

**Comment by EmmanuelMess** [comment]
How do I load a yaml for a custom weight set?

**Comment by Y-T-G** [comment]
Are you using `best.pt`?

**Comment by EmmanuelMess** [comment]
> Did you train the model using ultralytics or you got it from somewhere else?

I trained the model using YOLOv6 from https://github.com/meituan/YOLOv6. The model is YOLOv6Lite-S retrained for custom usage.

**Comment by EmmanuelMess** [comment]
Closing as training with ultralytics seems to work.

**Comment by glenn-jocher** [comment]
@EmmanuelMess thank you for confirming! If you encounter any further issues, feel free to reach out.
