### ISSUE TITLE
The YOLO11S model cannot infer large images, while YOLOV8S can

### ISSUE THREAD

**Issue by t-yuhao** [ultralytics/ultralytics#18235]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

On the YOLO11S model, inferring a 6000 * 6000 sized image requires approximately 120GB of video memory, while on the YOLOV8S model, there is no requirement for video memory. What is the reason for this? Neither of them used the SAHI tool
``` python
from ultralytics import YOLO
model = YOLO("runs/detect/yolov8sprebatch322/weights/best.pt")
source = cv2.imread("images/dd.jpg")
imgsz=[6000,6000]
results = model(source,save=True,save_txt=True,imgsz=imgsz, conf=0.25,line_width=3) 
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @t-yuhao, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it. From your explanation, it seems you're running into GPU memory issues when inferring large images. If possible, it would be helpful to share more detailed logs, specific environment details, or simplified code snippets that reproduce the issue.

If this is a custom training ❓ Question or usage inquiry, please provide as much additional information as possible, including your model configurations, dataset specs, or any additional relevant context. This will help us investigate and assist.

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com). Or share insights on our [Subreddit](https://reddit.com/r/Ultralytics) to engage with fellow users.

## Upgrade

First, ensure that you are using the latest `ultralytics` package and compatible dependencies. To upgrade:

```bash
pip install -U ultralytics
```

Ensure you are running this in a [**Python>=3.8**](https://www.python.org/) environment and using [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

## Environments

For best results, try running the code in one of our verified environments. YOLO runs seamlessly on:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

This is an automated response, but an Ultralytics engineer will take a closer look soon to provide more specific guidance. Thank you for your patience! 😊

**Comment by Y-T-G** [comment]
Are you using pretrained YOLO11s model?

**Comment by t-yuhao** [comment]
> 您是否在使用预训练的 YOLO11s 模型？

Yes,when I use yolo11s.pt,it need a lot of GPU meomory

**Comment by Y-T-G** [comment]
What about pretrained YOLOv8s model?

**Comment by t-yuhao** [comment]
> What about pretrained YOLOv8s model?

I test the two model.
yolov8s model
``` md
yolov8s:WARNING ⚠️ imgsz=[6000, 6000] must be multiple of max stride 32, updating to [6016, 6016]
0: 6016x6016 124 crossroads, 669.0ms
Speed: 325.9ms preprocess, 669.0ms inference, 2.1ms postprocess per image at shape (1, 3, 6016, 6016)
Results saved to runs/detect/predict
1 label saved to runs/detect/predict/labels
```
when I use yolo11s model
``` md
WARNING ⚠️ imgsz=[6000, 6000] must be multiple of max stride 32, updating to [6016, 6016]
Traceback (most recent call last):
  File "/workspace/road/yolopredict.py", line 18, in <module>
    results = model(source,save=True,save_txt=True,imgsz=imgsz, conf=0.25,line_width=3)  
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 173, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/root/miniforge3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 239, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 735, in warmup
    self.forward(im)  # warmup
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 526, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 112, in forward
    return self.predict(x, *args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 130, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 151, in _predict_once
    x = m(x)  # run
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 1041, in forward
    b = self.m(b)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 955, in forward
    x = x + self.attn(x) if self.add else self.attn(x)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniforge3/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 916, in forward
    attn = (q.transpose(-2, -1) @ k) * self.scale
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.62 GiB. GPU 0 has a total capacity of 14.58 GiB of which 12.06 GiB is free. Process 85721 has 2.51 GiB memory in use. Of the allocated memory 1.35 GiB is allocated by PyTorch, and 236.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by Y-T-G** [comment]
YOLO11s requires more memory because it uses attention

**Comment by t-yuhao** [comment]
> YOLO11s requires more memory because it uses attention

Thanks,I will try clip the image into small size

**Comment by glenn-jocher** [comment]
You're welcome! Clipping the image into smaller sizes is a good approach to manage memory usage effectively. Let us know if you encounter any further issues!
