### ISSUE TITLE
bug when start to train 

### ISSUE THREAD

**Issue by sandelush** [ultralytics/ultralytics#1831]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

TensorBoard: Start with 'tensorboard --logdir runs\detect\train3', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Ultralytics YOLOv8.0.62  Python-3.9.13 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Traceback (most recent call last):
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\yolo\engine\model.py", line 352, in train
    self.trainer.train()
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 191, in train
    self._do_train(world_size)
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 266, in _do_train
    self._setup_train(world_size)
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 212, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 648, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "C:\Users\devel\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 636, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.boxes  # FP32 inference
TypeError: 'NoneType' object is not subscriptable
PS C:\Users\devel\Desktop\mask>

### Environment

Ultralytics YOLOv8.0.62  Python-3.9.13 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sandelush hello! It seems like you are encountering an error during training with YOLOv8 regarding Automatic Mixed Precision (AMP) checks. Based on the error traceback, it looks like there might be an issue with subscripting NoneType objects. I recommend checking if your inputs are valid and if there are any issues with loading your model. Additionally, you may want to refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com for further troubleshooting steps. I hope this helps!
