### ISSUE TITLE
segment

### ISSUE THREAD

**Issue by lucky-asia** [ultralytics/ultralytics#18370]
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    model.train(data=r'data.yaml',
  File "/nfs/swyy/asia/ultralytics-main/ultralytics/engine/model.py", line 806, in train
    self.trainer.train()
  File "/nfs/swyy/asia/ultralytics-main/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/nfs/swyy/asia/ultralytics-main/ultralytics/engine/trainer.py", line 380, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/liyazhou/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/swyy/asia/ultralytics-main/ultralytics/nn/tasks.py", line 111, in forward
    return self.loss(x, *args, **kwargs)
  File "/nfs/swyy/asia/ultralytics-main/ultralytics/nn/tasks.py", line 293, in loss
    return self.criterion(preds, batch)
  File "/nfs/swyy/asia/ultralytics-main/ultralytics/utils/loss.py", line 298, in __call__
    raise TypeError(
TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolov8n-seg.pt data=coco8.yaml'.
Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco8-seg.yaml' as an example.
See https://docs.ultralytics.com/datasets/segment/ for help.
What is the reason for this error?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @lucky-asia, thank you for your interest in Ultralytics 🚀! We recommend taking a look at the [Docs](https://docs.ultralytics.com) where you can find helpful resources, including examples for [Dataset Formatting](https://docs.ultralytics.com/datasets/) and [Segment-specific](https://docs.ultralytics.com/datasets/segment/) requirements, which may address your issue.

From the error provided, it seems like there might be a mismatch between your dataset format and the model type you are using (`segment` model). To resolve this:

1️⃣ Verify that your dataset is formatted correctly as a segmentation dataset. You can refer to the [Segmentation Dataset Guide](https://docs.ultralytics.com/datasets/segment/) and use `coco8-seg.yaml` as a template/example for formatting.

2️⃣ If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that shows how to reproduce the issue, including:
- The exact command you used
- Any modifications you made to the dataset or code
- A snippet of your `data.yaml` file

3️⃣ Ensure you are using the latest version of the `ultralytics` package, as your issue might already be fixed in a newer release. You can upgrade with:

```bash
pip install -U ultralytics
```

For additional help, feel free to join the Ultralytics community for real-time discussions on [Discord](https://discord.com/invite/ultralytics) 🎧, share insights on [Discourse](https://community.ultralytics.com), or post on our [Subreddit](https://reddit.com/r/Ultralytics) to collaborate with others.

## Upgrade

Upgrade to the latest `ultralytics` package and dependencies in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

Try running YOLO in verified environments to exclude setup issues:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

An Ultralytics engineer will assist you soon for further investigation. Thank you for your patience 😊

**Comment by Y-T-G** [comment]
It's self-explanatory. You're using a dataset that's for detection to train a segmentation model.

**Comment by Skillnoob** [comment]
You should read the error, it tells you what is wrong and how to potentially fix it. You should visit [this](https://docs.ultralytics.com/datasets/segment/) page and verify that your dataset follows the correct format.

**Comment by lucadix** [comment]
Hi everyone, I am getting approximately into the same issue. I am trying to train YOLOm-v8-seg on some aerial images of buildings, for solar panel detection. I have my images labels saved in txt files, with labels such as the one below: 

`0 0.6661357215760356 0.29167358115326464 0.7288874196029104 0.09917441089860665 0.9241149245617651 0.13767424494953825 0.8474184047538693 0.33498589448599053 0.6661357215760356 0.29167358115326464`
 
My images have different shapes, from 200x200 pixels to 1200x1200 pixels. I have disabled augmentation during training, as this is a first "draft". 

While running my model.train() i get the following error: 

```
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       1/20      1.36G          0          0  -2.51e+04          0          0        640:   1%|          | 16/1435 [00:04<06:10,  3.84it/s]
Traceback (most recent call last):
  File "/Users/luca/gitlab/BUI/yoshi/.venv/lib/python3.12/site-packages/ultralytics/utils/loss.py", line 293, in __call__
    targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/gitlab/BUI/yoshi/.venv/lib/python3.12/site-packages/ultralytics/utils/loss.py", line 189, in preprocess
    out = torch.zeros(batch_size, counts.max(), ne - 1, device=self.device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to create tensor with negative dimension -1: [1, -1, 5]

The above exception was the direct cause of the following exception:
[....]
File "/Users/luca/gitlab/BUI/yoshi/.venv/lib/python3.12/site-packages/ultralytics/utils/loss.py", line 297, in __call__
    raise TypeError(
TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolo11n-seg.pt data=coco8.yaml'.
Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco8-seg.yaml' as an example.

```

Unfortunately, I am not understanding what may cause the issue. I already checked if my dataset is correctly formatted for the segmentation task. As you can see, I have my tensor here with dimensions [1, -1, 5] since I have set my batch size to 1, in order to understand if the issue was related to any specific image, but it doesn't.

Thank you in advance for your help :)

**Comment by Skillnoob** [comment]
@lucadix can you share your training code

**Comment by lucadix** [comment]
@Skillnoob here is the code: 
`
    if torch.backends.mps.is_available():
        mps_device = torch.device("mps")
        x = torch.ones(1, device=mps_device)
        logger.info(x)
    else:
        logger.info("MPS device not found.")

    logger.info("Loading YOLO v8 weights...")
    model_base = YOLO(model="./model/yolo11m-seg.pt")
    model_base.info()

    hyperparameters = yaml.safe_load(open("./augmentation.yaml"))["augmentation"]

    logger.info("Training the model...")
    results = model_base.train(data='/my_path/data.yaml', 
                           freeze=10, # freeze few layers
                           val=False, # no validation metrics during training, just at the end of the training process
                           imgsz=640, # (int | list) input images size as int for train and val modes
                           epochs=20, 
                           task='segment',
                           batch=16,    
                           device='mps', 
                           #close_mosaic=0, # Disables mosaic data augmentation in the last N epochs
                           seed=0,
                           project="train_results",
                           augment=False,
                           **hyperparameters
    )    
`
My data.yaml file is contains this:

`
train: /Users/luca/gitlab/BUI/yoshi/dataset/train/images/
val:   /Users/luca/gitlab/BUI/yoshi/dataset/valid/images/
test:  /Users/luca/gitlab/BUI/yoshi/dataset/test/images/
# number of classes
nc: 1
# class names
names: 
  0: 'solar_panel'
`
while my hyperparameters is just setting all the augmentation parameters to zero or False.
The labels are split in each folder - e.g. train/images and train/labels

Please let me know if you may need any addidional info. It is my first time working with YOLO and I might be misunderstanding something. 
Thanks!
