### ISSUE TITLE
PyTorch and torchvision mismatch for Jetson Orin Nano with jet-pack 5.1.4 when torchvision was built from source

### ISSUE THREAD

**Issue by prodrone-liu** [ultralytics/ultralytics#18385]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to build the local environment for testing yolo11 with TensorRT on my jetson orin nano with jp5.1.4 @ ubuntu20.04

According to [official guide](https://docs.ultralytics.com/guides/nvidia-jetson/#run-on-jetpack-5x), the **torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl**, **torchvision v0.16.2**, and **onnxruntime_gpu-1.17.0-cp38-cp38-linux_aarch64.whl** are installed sequentially but met with the following errors when I `import torchvision` (**libjpeg&libpng are installed in advance**):
```
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.8/dist-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSsb'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
```

However, the [docker env](https://docs.ultralytics.com/guides/nvidia-jetson/#__tabbed_1_2) can work perfectly with printing vision and file path of torch and torchvision. It can be used to test the loading of TensorRT model by `trt_model = YOLO("yolo11n.engine")` This is the __version__ and __file__ output from docker env:
```
PyTorch version: 2.1.0a0+41361538.nv23.06
PyTorch version: /usr/local/lib/python3.8/dist-packages/torch/__init__.py
NumPy version: 1.23.5
NumPy version: /usr/local/lib/python3.8/dist-packages/numpy/__init__.py
Torchvision version: 0.16.2+c6f3977
Torchvision version: /usr/local/lib/python3.8/dist-packages/torchvision/__init__.py
```

Therefore, I tried to install the package exactly like this docker in either conda or local environment but it keeps popping the same error info when I tried this [demo](https://docs.ultralytics.com/guides/nvidia-jetson/#use-tensorrt-on-nvidia-jetson):
```
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
Loading yolo11n.engine for TensorRT inference...
[12/25/2024-14:52:30] [TRT] [I] Loaded engine size: 11 MiB
[12/25/2024-14:52:30] [TRT] [W] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
[12/25/2024-14:52:32] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +616, GPU +872, now: CPU 1011, GPU 6109 (MiB)
[12/25/2024-14:52:32] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +10, now: CPU 0, GPU 10 (MiB)
[12/25/2024-14:52:32] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 1000, GPU 6110 (MiB)
[12/25/2024-14:52:33] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +18, now: CPU 0, GPU 28 (MiB)

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.8/dist-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSsb'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "test_TensorRT.py", line 13, in <module>
    results = trt_model("https://ultralytics.com/images/bus.jpg")
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 180, in __call__
    return self.predict(source, stream, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 558, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/predictor.py", line 173, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/predictor.py", line 266, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/utils/ops.py", line 296, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "/usr/local/lib/python3.8/dist-packages/torchvision/ops/boxes.py", line 40, in nms
    _assert_has_ops()
  File "/usr/local/lib/python3.8/dist-packages/torchvision/extension.py", line 46, in _assert_has_ops
    raise RuntimeError(
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```

Can anyone share the successful local build experience? Really appreciate it!

Output from `jetson_release`:
```
Software part of jetson-stats 4.3.0 - (c) 2024, Raffaello Bonghi
Model: NVIDIA Orin Nano Developer Kit - Jetpack 5.1.4 [L4T 35.6.0]
NV Power Mode[0]: 15W
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3767-0005
 - Module: NVIDIA Jetson Orin Nano (Developer kit)
Platform:
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.216-tegra
jtop:
 - Version: 4.3.0
 - Service: Active
Libraries:
 - CUDA: 11.4.315
 - cuDNN: 8.6.0.166
 - TensorRT: 8.5.2.2
 - VPI: 2.4.8
 - Vulkan: 1.3.204
 - OpenCV: 4.8 CUDA False
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @prodrone-liu, thank you for your detailed report and for using Ultralytics 🚀!

It seems you are encountering an issue with PyTorch and torchvision compatibility on your Jetson Orin Nano when building the environment locally. We recommend ensuring that your PyTorch and torchvision versions are compatible. Please check the [vision compatibility matrix](https://github.com/pytorch/vision#installation) to confirm.

If this is a 🐛 Bug Report, kindly provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug the issue. The smaller and more concise your example, the faster we can help!

If this is a ❓ Question regarding custom setups, please make sure to include detailed information about the specific steps you followed for building your environment, as well as any deviations from the official [NVIDIA Jetson Guide](https://docs.ultralytics.com/guides/nvidia-jetson/). Some additional details that can help:
- Versions of all relevant dependencies (beyond those listed in your report)
- Environment setup method (e.g., Docker vs. local/conda installation)

Here are a few suggestions to debug or resolve the issue:
1. **Upgrade**: Ensure you are running the latest versions of Ultralytics, PyTorch, and torchvision in a controlled environment by upgrading with:
   ```bash
   pip install -U ultralytics
   ```
2. **Docker Environment**: Consider utilizing the pre-configured [Jetson Docker environment](https://docs.ultralytics.com/guides/nvidia-jetson/#run-in-a-docker-environment) to bypass library incompatibility issues.
3. **Rebuild torchvision**: If rebuilding `torchvision` from source, ensure all prerequisite libraries (e.g., `libjpeg`, `libpng`) are installed before starting the build process.

For more resources, you can reference:
- [Documentation](https://docs.ultralytics.com) for a wide range of examples and troubleshooting steps.
- Join our community discussions for tips and solutions:
  - [Discord](https://discord.com/invite/ultralytics) 🎧
  - [Discourse](https://community.ultralytics.com)
  - [Subreddit](https://reddit.com/r/Ultralytics)

## Verified Environments

To simplify troubleshooting, you may consider using one of our verified environments, which are tested to work seamlessly with Ultralytics and YOLO:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: See the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/).
- **Amazon** Deep Learning AMI: See the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).
- **Docker Image**: See the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

## CI Status

You can also verify if the issue exists across other configurations by checking the status of our CI tests: <a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>. These tests validate the compatibility of [YOLO Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across supported platforms.

This is an automated response; an Ultralytics engineer will review your issue and provide further assistance soon 😊✨.

**Comment by glenn-jocher** [comment]
@prodrone-liu thank you for providing detailed information about your setup and the issues encountered. The error suggests a compatibility mismatch between your PyTorch and torchvision installations. When building `torchvision` from source, it's critical to ensure it is built against the exact version of PyTorch installed.

For JetPack 5.1.4, try the following steps:

1. Uninstall the existing `torch` and `torchvision`:
   ```
   pip uninstall torch torchvision
   ```

2. Install the recommended pre-built PyTorch and torchvision wheels for JetPack 5.1.3 (compatible with 5.1.4):
   ```
   pip install https://developer.download.nvidia.com/compute/redist/jp/v512/pytorch/torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl
   git clone https://github.com/pytorch/vision.git torchvision
   cd torchvision
   git checkout v0.16.2
   python3 setup.py install --user
   ```

3. Ensure the required dependencies, such as `libjpeg-dev` and `zlib1g-dev`, are installed before compiling torchvision:
   ```
   sudo apt-get install -y libjpeg-dev zlib1g-dev
   ```

4. Verify compatibility by checking the versions:
   ```
   python3 -c "import torch; print(torch.__version__)"
   python3 -c "import torchvision; print(torchvision.__version__)"
   ```

If issues persist, consider using the pre-built Docker environment as a reliable alternative, as it has been confirmed to work seamlessly. You can find the Docker setup instructions here: [Quick Start with Docker](https://docs.ultralytics.com/guides/nvidia-jetson/#quick-start-with-docker).

Let us know if you need further assistance!

**Comment by prodrone-liu** [comment]
@glenn-jocher  Thank you for offering the installation procedures. However, I did absolutely the same procedures as you provided. Here is a brief of related packages:
```
numpy                        1.23.5                  /usr/local/lib/python3.8/dist-packages pip
onnx                         1.17.0                  /usr/local/lib/python3.8/dist-packages pip
onnx-graphsurgeon            0.3.12                  /usr/lib/python3.8/dist-packages
onnxruntime-gpu              1.17.0                  /usr/local/lib/python3.8/dist-packages pip
torch                        2.1.0a0+41361538.nv23.6 /usr/local/lib/python3.8/dist-packages pip
torchvision                  0.16.2+c6f3977          /usr/local/lib/python3.8/dist-packages pip
ultralytics                  8.3.54                  /usr/local/lib/python3.8/dist-packages pip
ultralytics-thop             2.0.13                  /usr/local/lib/python3.8/dist-packages pip
```
But when I ran the version check, I still met the same problem:
```
$ python3 -c "import torch; print(torch.__version__)"
2.1.0a0+41361538.nv23.06

$ python3 -c "import torchvision; print(torchvision.__version__)"
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.8/dist-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSsb'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
0.16.2+c6f3977
```
I will switch to use docker, thanks.

**Comment by prodrone-liu** [comment]
After deleting everything and try installing torchvision v0.16.1, though the error still exists, tensorRT can be used on Jetson Orin Nano with JP5.1.4
```
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
Loading yolo11n.engine for TensorRT inference...
[12/26/2024-17:51:49] [TRT] [I] Loaded engine size: 11 MiB
[12/26/2024-17:51:49] [TRT] [W] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
[12/26/2024-17:51:52] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +616, GPU +636, now: CPU 1011, GPU 6738 (MiB)
[12/26/2024-17:51:52] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +10, now: CPU 0, GPU 10 (MiB)
[12/26/2024-17:51:52] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +17, now: CPU 1000, GPU 6734 (MiB)
[12/26/2024-17:51:52] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +18, now: CPU 0, GPU 28 (MiB)
Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
image 1/1 /home/xliu/yolo_test/bus.jpg: 640x640 4 persons, 1 bus, 36.4ms
Speed: 37.7ms preprocess, 36.4ms inference, 74.0ms postprocess per image at shape (1, 3, 640, 640)
```

**Comment by glenn-jocher** [comment]
@prodrone-liu thank you for your update! It's great to hear that TensorRT is functioning on your Jetson Orin Nano with JP5.1.4 despite the warning. The issue with the `torchvision` image extension seems environmental and likely tied to the build process. For troubleshooting, ensure all dependencies like `libjpeg-dev` and `zlib1g-dev` are installed before building `torchvision`.

If the warnings don't impact TensorRT inference, they can be safely ignored for now. Alternatively, using the pre-built Docker environment remains a reliable solution to avoid such compatibility issues. You can find the Docker guide here: [NVIDIA Jetson Quick Start](https://docs.ultralytics.com/guides/nvidia-jetson/#quick-start-with-docker). Let us know if you need further assistance!

**Comment by prodrone-liu** [comment]
Thank you @glenn-jocher , I also need to downgrade setuptools to 69.5.1 to run setup.py in torchvision v0.16.1, here is a more detailed link on the [forum](https://forums.developer.nvidia.com/t/pytorch-and-torchvision-version-mismatch-for-jetpack-5-1-4-on-orin-nano/318062/1) .

**Comment by glenn-jocher** [comment]
Thank you for sharing this additional detail and the link to the forum discussion. Downgrading `setuptools` is a helpful insight for resolving compatibility issues during the `torchvision` build process. This will surely benefit others facing similar challenges. Let us know if you need further assistance!
