### ISSUE TITLE
what's the yolo dataset format and how to write a yaml file?

### ISSUE THREAD

**Issue by Septemberlemon** [ultralytics/ultralytics#18454]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

this is the dataset I prepared:
![image](https://github.com/user-attachments/assets/6f0ecf12-ae60-4059-915c-670116b83fd7)
and this is my yaml file:
![image](https://github.com/user-attachments/assets/dbd07659-e896-47e3-8222-09dfc2e8ef7a)
when I run the code like
```python
    model = YOLO("yolov8n.pt")
    model.to("cuda")
    model.train(data="dataset.yaml", epochs=10)
```
it told me that :Dataset 'dataset.yaml' images not found ⚠️, missing path 'C:\Users\septemberlemon\.cache\ultralytics\datasets\helmet-detect\valid\images'

Does that mean my dataset format is wrong? shold I change the my dataset's folder "val" to "valid"? I wanna know what's the standard format, and I didn't find the tutorials in the official website. 
Maybe I just need a tutorials about the dataset format and how to write the yaml file.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Septemberlemon, thank you for your interest in Ultralytics 🚀! It looks like you're trying to figure out the proper dataset format and YAML configuration for YOLO. To clarify:

If this is a 🐛 Bug Report, it will really help if you can provide a minimum reproducible example along with your dataset and code snippets. This ensures we can debug the issue more accurately.

If this is a custom training ❓ Question, please share some additional details such as clear examples of your dataset structure and the YAML configuration file. It’s important to ensure that the folder and file structures match what's expected by YOLO. The folders typically include `train` and `val` subdirectories (or `images`/`labels` within these).

YOLO requires a dataset folder structure and YAML configuration to conform to the expected standards, usually with images and labels in respective subfolders like `train/images`, `train/labels`, `val/images`, and `val/labels`. Double-check file paths and directory names for any mismatches.

If you’re using the latest version of the `ultralytics` package, please ensure that everything is up to date. Upgrading can often resolve unseen issues that may already have fixes implemented:

```bash
pip install -U ultralytics
```

For verifying file setups or package environments, YOLO can run in various environments including notebooks with free GPU options like Gradient or Colab, or cloud setups like Google Cloud or AWS.

Also, feel free to join the Ultralytics community for support. Whether you prefer real-time chat, forums, or community discussions, you’ll find plenty of resources to collaborate and get your questions answered.

This is an automated response, but rest assured, an Ultralytics engineer will also take a closer look at your issue shortly to provide more personalized guidance. Thank you for your patience! 😊

**Comment by Y-T-G** [comment]
Change \ to / in your yaml

**Comment by Septemberlemon** [comment]
> Change `\` to `/` in your yaml
I'm sorry for wasting ur time, that's my fault, I didn't noticed that 
C:\Users\septemberlemon\.cache\ultralytics\datasets\helmet-detect\**valid**\images\
is the path in the yaml file,
but it's called "**val**" in my dataset folder, so I just need to make they are the same, then I won't meet that Error anymore
***
but I got a new issue:
now my code be like this:
```python
from ultralytics import YOLO


model = YOLO("yolov10n.pt")
model.to("cuda")
model.train(data="dataset.yaml", epochs=10)
```
it told me that:
**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Code\Python\deep_learning\YOLO\main.py", line 6, in <module>
    model.train(data="dataset.yaml", epochs=10)
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\model.py", line 806, in train
    self.trainer.train()
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 286, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=LOCAL_RANK, mode="train")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 55, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\data\build.py", line 135, in build_dataloader
    return InfiniteDataLoader(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\data\build.py", line 39, in __init__
    self.iterator = super().__iter__()
                    ^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\torch\utils\data\dataloader.py", line 484, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\torch\utils\data\dataloader.py", line 415, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\torch\utils\data\dataloader.py", line 1138, in __init__
    w.start()
  File "D:\Python\python-3.11.3\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
        **

**Comment by Septemberlemon** [comment]
> Change `\` to `/` in your yaml

I'm sorry for wasting ur time, that's my fault, I didn't noticed that 
C:\Users\septemberlemon\.cache\ultralytics\datasets\helmet-detect\\**valid**\images\
is the path in the yaml file,
but it's called "**val**" in my dataset folder, so I just need to make they are the same, then I won't meet that Error anymore

***

but I got a new issue:
now my code be like this:

```python
from ultralytics import YOLO


model = YOLO("yolov10n.pt")
model.to("cuda")
model.train(data="dataset.yaml", epochs=10)
```

it told me that:
**Traceback (most recent call last):**
  **File "<string>", line 1, in <module>**
  **File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 120, in spawn_main**
    **exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Code\Python\deep_learning\YOLO\main.py", line 6, in <module>
    model.train(data="dataset.yaml", epochs=10)
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\model.py", line 806, in train
    self.trainer.train()
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)**
  **File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 322, in _do_train
    self._setup_train(world_size)**
  **File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 286, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=LOCAL_RANK, mode="train")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 55, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\data\build.py", line 135, in build_dataloader
    return InfiniteDataLoader(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\ultralytics\data\build.py", line 39, in init
    self.iterator = super().iter()
                    ^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\torch\utils\data\dataloader.py", line 484, in iter
    return self._get_iterator()**
           **^^^^^^^^^^^^^^^^^^^^**
  **File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\torch\utils\data\dataloader.py", line 415, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Python\deep_learning\.venv\Lib\site-packages\torch\utils\data\dataloader.py", line 1138, in init
    w.start()
  File "D:\Python\python-3.11.3\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)**
           **^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**
  **File "D:\Python\python-3.11.3\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Python\python-3.11.3\Lib\multiprocessing\popen_spawn_win32.py", line 45, in init
    prep_data = spawn.get_preparation_data(process_obj._name)**
                **^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**
  **File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 158, in get_preparation_data**
    **_check_not_importing_main()**
  **File "D:\Python\python-3.11.3\Lib\multiprocessing\spawn.py", line 138, in _check_not_importing_main**
    **raise RuntimeError('''**
**RuntimeError:** 
        **An attempt has been made to start a new process before the**
        **current process has finished its bootstrapping phase.**

​        **This probably means that you are not using fork to start your**
​        **child processes and you have forgotten to use the proper idiom**
​        **in the main module:**

​                  **if name == 'main':**
​                          **freeze_support()**

​		          **...**

​       **The "freeze_support()" line can be omitted if the program**
​       **is not going to be frozen to produce an executable.**

**Comment by Y-T-G** [comment]
You need to put the code under this

https://stackoverflow.com/a/24374798/8061030

**Comment by Septemberlemon** [comment]
> You need to put the code under this
> 
> https://stackoverflow.com/a/24374798/8061030

fine, I've asked chatgpt and it told me the same thing
I did then I can train successfully finally,
I trained for 100 epochs and it works very well:
![result](https://github.com/user-attachments/assets/bf4bcb4b-fe89-4e4c-8ddd-ca52178aa82a)
yolo is so powerful, thank u for so much help, u r such a kind and helpful man
can I ask why yolo need multiprocess?

**Comment by Y-T-G** [comment]
To utilize multiple CPU cores

**Comment by glenn-jocher** [comment]
Thank you for the kind words, but all credit goes to the YOLO community and the Ultralytics team for their efforts in making YOLO so powerful. Regarding your question, YOLO utilizes multiprocessing for data loading during training to speed up the process by parallelizing tasks like preprocessing and augmentation. This ensures efficient utilization of system resources and reduces training time. Let us know if you have more questions!
