### ISSUE TITLE
After 200+ epochs Runtime error happens now on 2 from 3 trainings (same command, just different GPU amounts)

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#1854]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug
`
yolo task=detect mode=train model=yolov8x.pt data="test_yaml/kaggleFVall.yaml"  epochs=300 device=\'0,1,2,3,4,5,6,7\'
`

….
      Epoch      GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    261/300      2.95G     0.3137     0.3809     0.7961          3        640: 100%|██████████| 246/246 [02:17<00:00,  1.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 983/983 [02:55<00:00,  5.60it/s]
                   all       3932       1523       0.98      0.986      0.994      0.987

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/246 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/path/.config/Ultralytics/DDP/_temp_pxjbqx0e140712540844096.py", line 6, in <module>
    trainer.train()
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 319, in _do_train
    preds = self.model(batch['img'])
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 203, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 58, in _forward_once
    x = m(x)  # run
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/nn/modules.py", line 193, in forward
    y.extend(m(y[-1]) for m in self.m)
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/nn/modules.py", line 193, in <genexpr>
    y.extend(m(y[-1]) for m in self.m)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/nn/modules.py", line 131, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/nn/modules.py", line 34, in forward
    return self.act(self.bn(self.conv(x)))
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30440 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30441 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30442 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30444 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30445 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30446 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30447 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 30443) of binary: /path/miniconda3/bin/python
Traceback (most recent call last):
  File "/path/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/path/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/path/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/path/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/path/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/path/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/path/.config/Ultralytics/DDP/_temp_pxjbqx0e140712540844096.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-05_08:24:16
  host      : hostname
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 30443)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/path/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 374, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 345, in train
    self.trainer.train()
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 187, in train
    raise e
  File "/path/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "/path/miniconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/path/miniconda3/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '8', '--master_port', '35267', '/path/.config/Ultralytics/DDP/_temp_pxjbqx0e140712540844096.py', 'task=detect', 'mode=train', 'model=yolov8x.pt', 'data=test_yaml/kaggleFVall.yaml', 'epochs=300', 'patience=50', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=0,1,2,3,4,5,6,7', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'hide_labels=False', 'hide_conf=False', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'fl_gamma=0.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.

### Minimal Reproducible Example
`
yolo task=detect mode=train model=yolov8x.pt data="test_yaml/kaggleFVall.yaml"  epochs=300 device=\'0,1,2,3,4,5,6,7\'
`

### Additional

ultralytics 8.0.61

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
What is your environment? Are you on windows?

**Comment by dmddmd** [comment]
I'm on linux
________________________________
Von: Ayush Chaurasia ***@***.***>
Gesendet: Donnerstag, 6. April 2023 04:28
An: ultralytics/ultralytics ***@***.***>
Cc: dmddmd ***@***.***>; Author ***@***.***>
Betreff: Re: [ultralytics/ultralytics] After 200+ epochs Runtime error happens now on 2 from 3 trainings (same command, just different GPU amounts) (Issue #1854)


What is your environment? Are you on windows?

**Comment by glenn-jocher** [comment]
@dmddmd sure, I understand. My environment is Linux. I am not on Windows.
