### ISSUE TITLE
asset does not exist

### ISSUE THREAD

**Issue by udayzee05** [ultralytics/ultralytics#188]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

YOLOv8s summary: 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8s.pt', 'source=0']
Traceback (most recent call last):
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\cli.py", line 52, in cli
    func(cfg)
  File "D:\YOLOv8\venv\lib\site-packages\hydra\main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\v8\detect\predict.py", line 92, in predict
    predictor()
  File "D:\YOLOv8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 152, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 136, in setup
    self.dataset = LoadImages(source, imgsz=imgsz, stride=stride, auto=pt, vid_stride=self.args.vid_stride)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: D:\YOLOv8\venv\Lib\site-packages\ultralytics\assets does not exist

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### Environment

YOLOv8s summary: 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8s.pt', 'source=0']
Traceback (most recent call last):
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\cli.py", line 52, in cli
    func(cfg)
  File "D:\YOLOv8\venv\lib\site-packages\hydra\main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\v8\detect\predict.py", line 92, in predict
    predictor()
  File "D:\YOLOv8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 152, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 136, in setup
    self.dataset = LoadImages(source, imgsz=imgsz, stride=stride, auto=pt, vid_stride=self.args.vid_stride)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: D:\YOLOv8\venv\Lib\site-packages\ultralytics\assets does not exist

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@udayzee05 thanks for reporting. Can you please provide the command to reproduce?

**Comment by Laughing-q** [comment]
@AyushExel 
> Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8s.pt', 'source=0']

I think it's because hydra parsed the 0 in `source=0` to str.

**Comment by udayzee05** [comment]
yolo task=detect mode=predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg"   I tried with this command as well but same result

**Comment by AyushExel** [comment]
@Laughing-q yeah its treating 0 as null and predicts on the default assets. But it doesn't throw any error for me

**Comment by udayzee05** [comment]
Thank you, I was trying to pass 0 for webcam, but I am able to run successfully for images stored in local directory, Thank for clarification.

**Comment by AyushExel** [comment]
@udayzee05 Does this work for you now?

**Comment by udayzee05** [comment]
Yes

**Comment by AyushExel** [comment]
Awesome

**Comment by Laughing-q** [comment]
@AyushExel 
[https://github.com/ultralytics/ultralytics/blob/8302dc43990fd328c2e9896fb18f7de7e3665cb2/ultralytics/yolo/v8/detect/predict.py#L90](https://github.com/ultralytics/ultralytics/blob/8302dc43990fd328c2e9896fb18f7de7e3665cb2/ultralytics/yolo/v8/detect/predict.py#L90)
source becomes ultralytics/assets after this line if you pass source=0

**Comment by AyushExel** [comment]
@Laughing-q yeah that's what I meant.. hydra is treating "0" as None..not a string..we'll need a different syntax for webcam

**Comment by AyushExel** [comment]
yeah, I can reproduce. that is strange.

**Comment by glenn-jocher** [comment]
@udayzee05 your issue may be resolved now in PR https://github.com/ultralytics/ultralytics/pull/256 that I just merged. Please update your code and let us know if this resolves the issue for you, thank you!

**Comment by zldrobit** [comment]
I could reproduce this problem on Colab with the default source argument, as follows
![image](https://user-images.githubusercontent.com/3896992/212529030-28855789-f1e6-4624-8636-c82263571c4a.png)

**Comment by Laughing-q** [comment]
@zldrobit hey I tested with the same command by using this colab [https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb). But it works fine to me, probably there's something wrong with your installation, could check it again?
![image](https://user-images.githubusercontent.com/61612323/212531478-37afe96c-0fcd-49fe-a03b-68014304f264.png)

**Comment by zldrobit** [comment]
@Laughing-q I think I may find the origin of the problem. If I skip cloning the `ultralytics` GitHub repo, the error still occurs
![image](https://user-images.githubusercontent.com/3896992/212576254-deb4c2fb-e155-477a-abaf-18f1d368f57b.png)

Otherwise, I could also get detection results.
![image](https://user-images.githubusercontent.com/3896992/212576454-5de5b870-4a10-418c-9a2f-77cc221d1692.png)

Plz note that the missing images are under `/usr/local/lib/python3.8/dist-package`, but the existing images are in `/content/ultralytics` being the `ROOT` path. I guess these images are not packaged in the PyPI wheel, so barely `pip install` is not able to download them.

**Comment by AbdullahJirjees** [comment]
Hi I am getting this error that assist is missing when I try to process with video, while with webcam it works perfect 
Ultralytics YOLOv8.0.26  Python-3.10.10 torch-1.13.1+cpu CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

Traceback (most recent call last):
  File "D:\Projects\ComputerVision\main.py", line 31, in <module>
    for r in results:
  File "D:\Projects\ComputerVision\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 145, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "D:\Projects\ComputerVision\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 127, in setup_source
    self.dataset = load_inference_source(source=source,
  File "D:\Projects\ComputerVision\venv\lib\site-packages\ultralytics\yolo\data\build.py", line 183, in load_inference_source
    dataset = LoadImages(source,
  File "D:\Projects\ComputerVision\venv\lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 187, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: D:\Projects\ComputerVision\ultralytics\assets does not exist
Sentry is attempting to send 2 pending error messages

**Comment by TIBREWA** [comment]
Hey @udayzee05 did you fix the ultralytics issue because i am facing the same issue and i am unable to fix it, if yes please tell me how can i fix it

**Comment by shaowngp** [comment]
My issue has been resolved after putting source= 'ultralytics/' ; providing Ultralytics root path.

!python predict.py model='best.pt' source='/content/gdrive/MyDrive/yolov8/ultralytics/' data='/content/gdrive/MyDrive/yolov8/ultralytics/xyz.mp4'

**Comment by glenn-jocher** [comment]
@shaowngp great to hear that your issue has been resolved by providing the correct root path for Ultralytics as your source. It appears the initially configured root path couldn't find the necessary files. Now, the program can successfully locate them and everything runs smoothly. The TensorFlow errors that are being shown are warnings and should not impact the overall functionality of YOLOv8, those are related to the TensorFlow-TensorRT integration and not finding TensorRT, which is a high-performance deep learning inference optimizer and runtime library. Lastly, Ultralytics YOLOv8 seems to be working efficiently as indicated by the speed of the pre-process, inference, and postprocess per image.

**Comment by MathewsJosh** [comment]
This problem appears when I use ```pip install scikit-image`` after installing and executing ultralytics.

The versions of my installed libraries are:

scikit-image              0.25.1
scikit-learn              1.6.1
torch                     2.2.1+cu118
torchvision               0.17.1+cu118
ultralytics               8.2.77


When I uninstall scikit-image, the problem is solved.
