### ISSUE TITLE
Dataset not found , missing paths problem  and ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by onuralpszr** [ultralytics/ultralytics#195]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I ran minimal code I shared down there for quick training and test, it is always ended up errors, I tried couple of times already

PS : "XXXX" is actual full path but since it was too long I removed it.

```
Dataset not found ⚠, missing paths ['XXXXX/datasets/coco/val2017.txt']
Traceback (most recent call last):
  File "export.py", line 6, in <module>
    model.val()  # evaluate model performance on the validation set
  File "XXXXX/py_ultralytics/venv/lib64/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "XXXXX/py_ultralytics/venv/lib64/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 150, in val
    validator(model=self.model)
  File "XXXXX/py_ultralytics/venv/lib64/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "XXXXX/py_ultralytics/venv/lib64/python3.8/site-packages/ultralytics/yolo/engine/validator.py", line 112, in __call__
    self.data = check_dataset_yaml(self.args.data)
  File "XXXXX/py_ultralytics/venv/lib64/python3.8/site-packages/ultralytics/yolo/data/utils.py", line 251, in check_dataset_yaml
    r = exec(s, {'yaml': data})  # return None
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'utils'

```

### Environment

- Ultralytics YOLOv8.0.0 🚀 Python-3.8.16 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2070 Super, 7974MiB)
- Fedora 37
- Python 3.8
- Pypi version : ultralytics  - 8.0.0

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # load a pretrained YOLOv8n model

model.train(data="coco128.yaml")  # train the model
model.val()  # evaluate model performance on the validation set
model.predict(source="https://ultralytics.com/images/bus.jpg")  # predict on an image
#model.export(format="torchscript")
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@onuralpszr looks like the error raised by model.val(). can you add `data` arg in model.val() and try model.val(data="coco128.yaml")?

**Comment by onuralpszr** [comment]
@Laughing-q I added yaml param and change epoch to "1" for quick result and now it complaining on export section, I tried with 3 different options (I thought It maybe be config problem but it is still complain because of yaml_file   

```python
model.export()
model.export(format="torchscript")
model.export(format="torchscript",optimize=True)
```

```
  File "export.py", line 11, in <module>
    model.export(format="torchscript")
  File "/XXXX/py_ultralytics/venv/lib64/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/XXXX/py_ultralytics/venv/lib64/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 167, in export
    exporter(model=self.model)
  File "/XXXX/py_ultralytics/venv/lib64/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/XXXX/py_ultralytics/venv/lib64/python3.8/site-packages/ultralytics/yolo/engine/exporter.py", line 171, in __call__
    file = Path(getattr(model, 'pt_path', None) or model.yaml['yaml_file'])
KeyError: 'yaml_file'
```

**Comment by Laughing-q** [comment]
@onuralpszr oh we haven't supported this workflow yet:
```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # load a pretrained YOLOv8n model
model.train(data="coco128.yaml")  # train the model
model.export(format="torchscript")
```
the current workflow of export is:
```python
from ultralytics import YOLO

model = YOLO("your_last.pt")  # load your trained model
model.export(format="torchscript")
```
But we'll work on the first workflow and support it as it's cleaner.

**Comment by glenn-jocher** [comment]
> ```python
> model.export(format="torchscript")
> ```

Yes this is a known issue. We've updated the Colab notebook usage to show only exporting directly from a *.pt file rather than from a trained model. 

<img width="1042" alt="Screenshot 2023-01-10 at 15 15 36" src="https://user-images.githubusercontent.com/26833433/211574662-5987d73e-3154-4b3e-931c-2f9e95d57351.png">

So you should be able to do `YOLO('path/to/best.pt').export(...)`

**Comment by Laughing-q** [comment]
hi @onuralpszr, now the following workflow has been supported in ultralytics==8.0.5, please upgrade and have a try.  :)
```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # load a pretrained YOLOv8n model
model.train(data="coco128.yaml")  # train the model
model.export(format="torchscript")
```

**Comment by Laughing-q** [comment]
@onuralpszr closing the issue. Feel free to reopen it if you have any related issues. :)
