### ISSUE TITLE
cublast error when running directly from terminal . symbol cublasLtGetStatusString, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

### ISSUE THREAD

**Issue by mazatov** [ultralytics/ultralytics#1980]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm running on Ubuntu 16.04 and am getting the following error when I run yolo directly from the terminal. Weirdly when I run things from python they work OK. 

```
(yolov8) ubuntu@ip-10-0-11-48:~/ultralytics$ yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/yolov8/bin/yolo", line 5, in <module>
    from ultralytics.yolo.cfg import entrypoint
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/hub/utils.py", line 15, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/ultralytics/yolo/v8/classify/predict.py", line 3, in <module>
    import torch
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/anaconda3/envs/yolov8/lib/python3.7/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

```

However, when I run in python those imports go through fine. 
```
(yolov8) ubuntu@ip-10-0-11-48:~/ultralytics$ python -c "import torch"
(yolov8) ubuntu@ip-10-0-11-48:~/ultralytics$ python -c "from ultralytics.hub import start"
(yolov8) ubuntu@ip-10-0-11-48:~/ultralytics$ python -c "from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict"
```

**Comment by glenn-jocher** [comment]
@mazatov it seems like there's an issue with the libcublas.so.11 library when you run the YOLOv8 command directly from the terminal. This could be related to environment variables or the way your system is set up.

Since you mentioned that running the imports directly in Python works fine, you can create a Python script to run YOLOv8 predictions instead of using the terminal command. Create a new Python file, e.g., yolo_predict.py and then run it from the terminal using python yolo_predict.py.

**Comment by mazatov** [comment]
Thanks @glenn-jocher , I wonder if it has to do with multiple cuda versions being installed at the same time. I have my environmental variable link to multiple CUDA versions. 

`LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-11/lib64:/usr/local/cuda-11.1/lib64:/usr/local/cuda-11.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"`


Thanks for the tip, I ended up creating a small script and running it. Are there any limitations to this way? 

```
from ultralytics import YOLO
# Create a new YOLO model from scratch
model = YOLO('yolov8x.pt')
model.train(data="my.yaml", epochs = 300, imgsz=1280, batch=4)
```

**Comment by glenn-jocher** [comment]
@mazatov, glad to hear that creating a small Python script worked for you! Using Ultralytics YOLOv8 through Python code gives you more flexibility and control over the parameters and settings you want to use. There are no limitations to using YOLOv8 this way, and you can use it for both training and inference. As an added benefit, you can use your Python script to automate the YOLOv8 process and integrate it into your pipeline for your specific use case.
