### ISSUE TITLE
Segmentation in v8 - NotImplementedError: ERROR: yolov8n-seg.yaml is not a supported format

### ISSUE THREAD

**Issue by DivyankaThakur03** [ultralytics/ultralytics#203]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The task=detect works perfetly fine.

I tried running this command for segmentation -
`yolo task=segment mode=predict model=yolov8n-seg.yaml source="https://ultralytics.com/images/bus.jpg"`

I copied yolov8n-seg.yaml file from ultralytics/models/v8/seg and is in the current directory 

But getting this error -
```
Ultralytics YOLOv8.0.1 🚀 Python-3.8.10 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 5947MiB)
Error executing job with overrides: ['task=segment', 'mode=predict', 'model=yolov8n-seg.yaml', 'source=https://ultralytics.com/images/bus.jpg']
Traceback (most recent call last):
  File "/home/divya/.local/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/home/divya/.local/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/divya/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/predict.py", line 107, in predict
    predictor()
  File "/home/divya/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 152, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "/home/divya/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 123, in setup
    model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)
  File "/home/divya/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 224, in __init__
    raise NotImplementedError(f'ERROR: {w} is not a supported format')
NotImplementedError: ERROR: yolov8n-seg.yaml is not a supported format

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@DivyankaThakur03 try passing .pt checkpoints instead of .yaml files.
```
yolo task=segment mode=predict model=yolov8n-seg.pt source="https://ultralytics.com/images/bus.jpg"
```

**Comment by DivyankaThakur03** [comment]
This works.
Thanks for your reply
