### ISSUE TITLE
Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!

### ISSUE THREAD

**Issue by zoufangyu1987** [ultralytics/ultralytics#2084]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Use this command to convert the onnx model
“yolo mode=export model=yolov8s.pt format=onnx dynamic=True"

When converting the ONNX model to the TensorrT model, this error was found,
Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!

**Comment by zoufangyu1987** [comment]
CUDA = 11.1
TensorRT = 8.2.0.6

**Comment by zoufangyu1987** [comment]
[04/17/2023-21:31:07] [I] === Device Information ===
[04/17/2023-21:31:07] [I] Selected Device: NVIDIA GeForce RTX 3060 Ti
[04/17/2023-21:31:07] [I] Compute Capability: 8.6
[04/17/2023-21:31:07] [I] SMs: 38
[04/17/2023-21:31:07] [I] Compute Clock Rate: 1.665 GHz
[04/17/2023-21:31:07] [I] Device Global Memory: 7973 MiB
[04/17/2023-21:31:07] [I] Shared Memory per SM: 100 KiB
[04/17/2023-21:31:07] [I] Memory Bus Width: 256 bits (ECC disabled)
[04/17/2023-21:31:07] [I] Memory Clock Rate: 7.001 GHz
[04/17/2023-21:31:07] [I] 
[04/17/2023-21:31:07] [I] TensorRT version: 8200
[04/17/2023-21:31:08] [I] [TRT] [MemUsageChange] Init CUDA: CPU +446, GPU +0, now: CPU 457, GPU 863 (MiB)
[04/17/2023-21:31:08] [I] Start parsing network model
[04/17/2023-21:31:08] [I] [TRT] ----------------------------------------------------------------
[04/17/2023-21:31:08] [I] [TRT] Input filename:   /media/zoufangyu/DATA1/Yolov8/ultralytics/yolov8s.onnx
[04/17/2023-21:31:08] [I] [TRT] ONNX IR version:  0.0.6
[04/17/2023-21:31:08] [I] [TRT] Opset version:    12
[04/17/2023-21:31:08] [I] [TRT] Producer name:    pytorch
[04/17/2023-21:31:08] [I] [TRT] Producer version: 1.8
[04/17/2023-21:31:08] [I] [TRT] Domain:           
[04/17/2023-21:31:08] [I] [TRT] Model version:    0
[04/17/2023-21:31:08] [I] [TRT] Doc string:       
[04/17/2023-21:31:08] [I] [TRT] ----------------------------------------------------------------
[04/17/2023-21:31:08] [W] [TRT] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[04/17/2023-21:31:08] [E] [TRT] ModelImporter.cpp:769: While parsing node number 226 [Range -> "368"]:
[04/17/2023-21:31:08] [E] [TRT] ModelImporter.cpp:770: --- Begin node ---
[04/17/2023-21:31:08] [E] [TRT] ModelImporter.cpp:771: input: "366"
input: "365"
input: "367"
output: "368"
name: "Range_226"
op_type: "Range"

[04/17/2023-21:31:08] [E] [TRT] ModelImporter.cpp:772: --- End node ---
[04/17/2023-21:31:08] [E] [TRT] ModelImporter.cpp:775: ERROR: builtin_op_importers.cpp:3347 In function importRange:
[8] Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"
[04/17/2023-21:31:08] [E] Failed to parse onnx file
[04/17/2023-21:31:08] [I] Finish parsing network model
[04/17/2023-21:31:08] [E] Parsing model failed
[04/17/2023-21:31:08] [E] Failed to create engine from model.
[04/17/2023-21:31:08] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8200] # /home/zoufangyu/DATA2/TensorRT-8.2.0.6/bin/trtexec --onnx=/media/zoufangyu/DATA1/Yolov8/ultralytics/yolov8s.onnx --saveEngine=yolov8s.engine --workspace=2048 --minShapes=images:1x3x640x640 --optShapes=images:8x3x640x640 --maxShapes=images:16x3x640x640 --fp16

**Comment by glenn-jocher** [comment]
@zoufangyu1987, it seems that the model conversion from ONNX to TensorRT failed due to an Assertion error. The error message suggests that the TensorRT version 8.2.0.6 only supports INT32 for dynamic inputs when using the range operator. The model was generated with INT64 weights, which are not natively supported by TensorRT. One possible solution could be to cast the weights down to INT32. Alternatively, you could try to use a different version of TensorRT that supports INT64. For more information on the conversion process, you can refer to the TensorRT documentation or the YOLOv8 documentation at https://docs.ultralytics.com/yolov8/.

**Comment by zoufangyu1987** [comment]
@glenn-jocher 
Thanks!
I have already resolved it. Upgrade Tensorrt to version TensorRT 8.4 GA Update 1.
我已经解决了。tensorrt升到版本TensorRT 8.4 GA Update 1就可以了。

**Comment by glenn-jocher** [comment]
@zoufangyu1987, I'm glad to hear that you were able to resolve the issue by upgrading to TensorRT 8.4 GA Update 1. It's always recommended to keep your software up to date to ensure optimal performance and compatibility. If you encounter any further problems or have any questions, please don't hesitate to reach out on the YOLOv8 GitHub Issues page, and we will be happy to assist you.

**Comment by y71eyg7hi8** [comment]
(yolov8n) jinxin@ubuntu:~/Desktop/yolo/jiemian$ python onnxfp32.py
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.4 🚀 Python-3.8.12 torch-1.11.0a0+gitbc2c6ed CUDA:0 (NVIDIA Tegra X2, 7858MiB)
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from '/home/jinxin/Desktop/yolo/jiemian/yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.17.0 opset 14...
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 89.0s, saved as '/home/jinxin/Desktop/yolo/jiemian/yolov8n.onnx' (12.1 MB)

TensorRT: starting export with TensorRT 8.2.3.0...
[10/15/2024-02:28:25] [TRT] [I] [MemUsageChange] Init CUDA: CPU +233, GPU +0, now: CPU 1618, GPU 5124 (MiB)
[10/15/2024-02:28:26] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 1618 MiB, GPU 5124 MiB
[10/15/2024-02:28:26] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 1648 MiB, GPU 5153 MiB
[10/15/2024-02:28:26] [TRT] [I] ----------------------------------------------------------------
[10/15/2024-02:28:26] [TRT] [I] Input filename:   /home/jinxin/Desktop/yolo/jiemian/yolov8n.onnx
[10/15/2024-02:28:26] [TRT] [I] ONNX IR version:  0.0.10
[10/15/2024-02:28:26] [TRT] [I] Opset version:    14
[10/15/2024-02:28:26] [TRT] [I] Producer name:    pytorch
[10/15/2024-02:28:26] [TRT] [I] Producer version: 1.11.0
[10/15/2024-02:28:26] [TRT] [I] Domain:           
[10/15/2024-02:28:26] [TRT] [I] Model version:    0
[10/15/2024-02:28:26] [TRT] [I] Doc string:       
[10/15/2024-02:28:26] [TRT] [I] ----------------------------------------------------------------
[10/15/2024-02:28:26] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[10/15/2024-02:28:26] [TRT] [E] ModelImporter.cpp:773: While parsing node number 174 [Range -> "onnx::Add_418"]:
[10/15/2024-02:28:26] [TRT] [E] ModelImporter.cpp:774: --- Begin node ---
[10/15/2024-02:28:26] [TRT] [E] ModelImporter.cpp:775: input: "onnx::Range_416"
input: "onnx::Range_415"
input: "onnx::Range_417"
output: "onnx::Add_418"
name: "Range_254"
op_type: "Range"

[10/15/2024-02:28:26] [TRT] [E] ModelImporter.cpp:776: --- End node ---
[10/15/2024-02:28:26] [TRT] [E] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:3352 In function importRange:
[8] Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"
TensorRT: export failure ❌ 90.9s: failed to load ONNX file: /home/jinxin/Desktop/yolo/jiemian/yolov8n.onnx
Traceback (most recent call last):
  File "onnxfp32.py", line 6, in <module>
    out = model.export(format="engine",  dynamic=False, int8=True, simplify=True,data="/home/jinxin/Desktop/yolo/jiemian/coco8.yaml")
  File "/home/jinxin/Desktop/yolo/yolov8n/lib/python3.8/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/jinxin/Desktop/yolo/yolov8n/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jinxin/Desktop/yolo/yolov8n/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 313, in __call__
    f[1], _ = self.export_engine()
  File "/home/jinxin/Desktop/yolo/yolov8n/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 140, in outer_func
    raise e
  File "/home/jinxin/Desktop/yolo/yolov8n/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 135, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/jinxin/Desktop/yolo/yolov8n/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 724, in export_engine
    raise RuntimeError(f"failed to load ONNX file: {f_onnx}")
RuntimeError: failed to load ONNX file: /home/jinxin/Desktop/yolo/jiemian/yolov8n.onnx

**Comment by y71eyg7hi8** [comment]
Failed to transform using tensorrt on jeston tx2 but the cuda and tennsort versions are bound to jepack, what can I do to solve this problem?

**Comment by glenn-jocher** [comment]
@y71eyg7hi8 it seems like a compatibility issue with TensorRT on the Jetson TX2. Try updating to the latest JetPack version, which includes compatible CUDA and TensorRT versions. If the issue persists, consider checking the TensorRT documentation for any specific requirements or limitations.
