### ISSUE TITLE
error at the start of clasification model training

### ISSUE THREAD

**Issue by shidktbw** [ultralytics/ultralytics#2108]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Error at the start of clasification model training

I created a dataset using roboflow and got something like this datasets\collected then comes my folder called forward and others, also with Jpg images in them. when you start training, whether it is via cmd or python, errors will occur 

`PS L:\1\neuro> yolo task=classify mode=train model=yolov8n-cls.pt data=collected  epochs=150 imgsz=224            
Ultralytics YOLOv8.0.82  Python-3.10.6 torch-1.13.1+cpu CPU
yolo\engine\trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=collected, epochs=150, patience=50, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\classify\train23
Overriding model.yaml nc=1000 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    334083  ultralytics.nn.modules.Classify              [256, 3]
YOLOv8n-cls summary: 99 layers, 1442131 parameters, 1442131 gradients, 3.4 GFLOPs
Transferred 156/158 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs\classify\train23', view at http://localhost:6006/
optimizer: SGD(lr=0.01) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\model.py", line 370, in train
    self.trainer.train()
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 191, in train
    self._do_train(world_size)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 268, in _do_train
    self._setup_train(world_size)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 252, in _setup_train
    self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\v8\classify\train.py", line 76, in get_dataloader
    loader = build_classification_dataloader(path=dataset_path,
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\data\build.py", line 125, in build_classification_dataloader
    dataset = ClassificationDataset(root=path, imgsz=imgsz, augment=augment, cache=cache)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\data\dataset.py", line 242, in __init__
    super().__init__(root=root)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 309, in __init__
    super().__init__(
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 145, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 189, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 61, in make_dataset
    directory = os.path.expanduser(directory)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 319, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

### Environment

YOLO v8 ultralutics (new)
windows 11 
Python 3.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by shidktbw** [comment]
I have a datasets folder in my project and in it there are 3 folders and in these 3 folders there are png pictures 
![изображение](https://user-images.githubusercontent.com/112849918/232987295-27e383ed-c382-4145-a21c-33b40b1b0ad8.png)
![изображение](https://user-images.githubusercontent.com/112849918/232987339-ac73eb34-f7d2-4af9-b6e0-7d0532c9c725.png)

other folders also contain png pictures
164kb photo, size 860 x 772  

the dataset looks something like this (this is the game under effect )

![изображение](https://user-images.githubusercontent.com/112849918/232987910-b2b50d53-36a3-451a-8e79-4b37cc2d5dfb.png)

I just uploaded my dataset to roboflow and it put my images in the train valid and test folders, and these folders contain my image folders.

**Comment by glenn-jocher** [comment]
@shidktbw it is great to hear that the issue has been resolved. It is possible that the previous error was caused by an error in the dataset's file structure or formatting. By recreating the dataset using RoBoFlow, any errors related to formatting or structure may have been resolved. It’s always a good idea to ensure that your dataset is in the correct format and structure before using it with YOLOv8. Proper dataset formatting can help ensure accurate and efficient training of your YOLOv8 model, so it's essential to organize your dataset carefully.

**Comment by andrewwetzel23** [comment]
I am running into this same issue and have not found any good documentation about how to properly lay out the classification data. From reading different examples I've gotten:

data/
     train/
          a/ 1.png, 2.png, ... n.png
          b/ 1.png, 2.png, ... n.png
          c/ 1.png, 2.png, ... n.png
     valid/
          a/ 1.png, 2.png, ... n.png
          b/ 1.png, 2.png, ... n.png
          c/ 1.png, 2.png, ... n.png

Where the a-c are the different classifications and the names of the files don't need any specific requirements.

I am running the training in python and am getting this cli output:
```
engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=/home/andrew/Desktop/sprogs/Classify/data/CO/annotations, epochs=600, patience=50, batch=160, imgsz=224, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=/home/andrew/Desktop/sprogs/Classify/data/CO/weights/weights, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=/home/andrew/Desktop/sprogs/Classify/data/CO/weights/weights2
Overriding model.yaml nc=1000 with nc=3
```
  
Am I missing anything?
Is there a `data.yaml` file needed for classification training?

**Comment by glenn-jocher** [comment]
@andrewwetzel23, the data structure you've shared seems correct for a classification task; each class should have its own subfolder in both the training and validation directories.

Alongside the correct data structure, a YAML configuration file (`data.yaml`) is also required which outlines details regarding the dataset. The YAML configuration file typically contains information such as the paths to the training and validation directories, the number of classes, and a list of class names. This file needs to be provided while initiating the training so the model would know where to find the images for both training and validation, and what the various classes are.

From the CLI output you've provided it seems like you might have not set your `data.yaml` file in the data flag in the command you're running, because the data folder it's pointing towards seems to be containing annotations files (`/home/andrew/Desktop/sprogs/Classify/data/CO/annotations`).

Thus, please ensure to correctly generate and point towards a `data.yaml` file in your training command line. Your issue might be resolved by doing that.

**Comment by andrewwetzel23** [comment]
Thanks for the quick reply. I did not have a `data.yaml` file at all. My thinking was that all the info needed for the model could be found just on the folder directory but I guess the objects need to be numbered.

Is there classification-specific training formatting documentation regarding this that I missed somewhere or is it still in the works?

**Comment by andrewwetzel23** [comment]
I believe there may be a bug making classification models currently untrainable:

If I pass the data.yaml to the data flag the training errors with the following output:

```
Traceback (most recent call last):
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 121, in __init__
    self.data = check_cls_dataset(self.args.data)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/data/utils.py", line 314, in check_cls_dataset
    names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/data/utils.py", line 314, in <listcomp>
    names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
  File "/home/andrew/anaconda3/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
NotADirectoryError: [Errno 20] Not a directory: '/home/andrew/Desktop/sprogs/Classify/data/CO/annotations/data.yaml/train'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/andrew/anaconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 423, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 371, in train
    self.trainer = trainer(overrides=overrides, _callbacks=self.callbacks)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py", line 24, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset '/home/andrew/Desktop/sprogs/Classify/data/CO/annotations/data.yaml' error ❌ [Errno 20] Not a directory: '/home/andrew/Desktop/sprogs/Classify/data/CO/annotations/data.yaml/train'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

If I attempt to pass the data directory to the data flag I get the following error:

```
Traceback (most recent call last):
  File "/home/andrew/anaconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 423, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 376, in train
    self.trainer.train()
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 242, in _setup_train
    self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py", line 76, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py", line 71, in build_dataset
    return ClassificationDataset(root=img_path, args=self.args, augment=mode == 'train')
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/ultralytics/data/dataset.py", line 229, in __init__
    super().__init__(root=root)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 189, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/home/andrew/anaconda3/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 61, in make_dataset
    directory = os.path.expanduser(directory)
  File "/home/andrew/anaconda3/lib/python3.10/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by glenn-jocher** [comment]
@andrewwetzel23 we're glad that you were able to solve the issue! The naming of directories can often cause confusion, so this is great feedback. We'll look into improving our error messaging to catch scenarios like this and make troubleshooting more straightforward. We thank you for your patience and appreciate your contribution to improving YOLOv8. If you experience any further issues, don't hesitate to reach out again. Happy training!
