### ISSUE TITLE
YOLOv8 does recognize defined env variable YOLO_CONFIG_DIR

### ISSUE THREAD

**Issue by Joilence** [ultralytics/ultralytics#2163]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I setup my environment in an external drive as there is not much space left in the main drive. The external drive is mounted at /home/user/edrive

``` shell
conda create --prefix /home/jo/sdb6/jo/conda-env/yolov8 python=3.10

conda activate /home/jo/sdb6/jo/conda-env/yolov8

conda install -c nvidia cuda-toolkit=11.8.0

conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

pip install ultralytics
```

The situation for me to run YOLOv8 is as follows:

``` shell
# jo @ TheTracker in ~/sdb6/jo/.config/Ultralytics [7:10:24]
$ cd /home/jo/sdb6/jo/.config/Ultralytics/
(/home/jo/sdb6/jo/conda-env/yolov8)
# jo @ TheTracker in ~/sdb6/jo/.config/Ultralytics [7:10:40]
$ echo $YOLO_CONFIG_DIR

/home/jo/sdb6/.config/Ultralytics
(/home/jo/sdb6/jo/conda-env/yolov8)
# jo @ TheTracker in ~/sdb6/jo/.config/Ultralytics [7:10:47]
$ yolo
Traceback (most recent call last):
  File "/home/jo/sdb6/jo/conda-env/yolov8/bin/yolo", line 5, in <module>
    from ultralytics.yolo.cfg import entrypoint
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/hub/utils.py", line 14, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 35, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 17, in <module>
    from ultralytics.yolo.utils import LINUX, LOGGER, ROOT, yaml_load
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/utils/__init__.py", line 540, in <module>
    USER_CONFIG_DIR = Path(os.getenv('YOLO_CONFIG_DIR', get_user_config_dir()))  # Ultralytics settings dir
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/utils/__init__.py", line 535, in get_user_config_dir
    path.mkdir(parents=True, exist_ok=True)
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 28] No space left on device: '/home/jo/.config/Ultralytics'
```

for some reason, it seems that the code is still trying to create a directory at `/home/jo/.config/Ultralytics`, despite the environment variable change.

Even if I try this script, the same error remains:

``` python
import os

# Set or modify the value of YOLO_CONFIG_DIR
os.environ['YOLO_CONFIG_DIR'] = '/home/jo/sdb6/jo/.config/Ultralytics'
# Verify that the value has been updated
print(f"YOLO_CONFIG_DIR: {os.getenv('YOLO_CONFIG_DIR')}")

from ultralytics import YOLO
```

``` shell
# jo @ TheTracker in ~/sdb6/jo/localcode/yolo-pigeon [7:09:45] C:1
$ python3 main.py
YOLO_CONFIG_DIR: /home/jo/sdb6/jo/.config/Ultralytics
Traceback (most recent call last):
  File "/home/jo/sdb6/jo/localcode/yolo-pigeon/main.py", line 8, in <module>
    from ultralytics import YOLO
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/hub/utils.py", line 14, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 35, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 17, in <module>
    from ultralytics.yolo.utils import LINUX, LOGGER, ROOT, yaml_load
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/utils/__init__.py", line 540, in <module>
    USER_CONFIG_DIR = Path(os.getenv('YOLO_CONFIG_DIR', get_user_config_dir()))  # Ultralytics settings dir
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/site-packages/ultralytics/yolo/utils/__init__.py", line 535, in get_user_config_dir
    path.mkdir(parents=True, exist_ok=True)
  File "/home/jo/sdb6/jo/conda-env/yolov8/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 28] No space left on device: '/home/jo/.config/Ultralytics'
```

### Environment

- Python 3.10.11
- Ubuntu 20.04.5 LTS
- ultralytics  8.0.83

### Minimal Reproducible Example

``` python
import os

# Set or modify the value of YOLO_CONFIG_DIR
os.environ['YOLO_CONFIG_DIR'] = {some other path}
# Verify that the value has been updated
print(f"YOLO_CONFIG_DIR: {os.getenv('YOLO_CONFIG_DIR')}")

from ultralytics import YOLO

# YOLO did not recognize the new path
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Joilence I'm not able to reproduce the issue.
```python
import os

# Set or modify the value of YOLO_CONFIG_DIR
os.environ['YOLO_CONFIG_DIR'] = "/home/laughing"
# Verify that the value has been updated
print(f"YOLO_CONFIG_DIR: {os.getenv('YOLO_CONFIG_DIR')}")

from ultralytics import YOLO
```
new created `settings.yaml` is in `/home/laughing`.
![image](https://user-images.githubusercontent.com/61612323/233558395-d5bbc05e-5391-4a38-8e79-9de3b536f14c.png)
