### ISSUE TITLE
RuntimeError: DistributedDataParallel is not needed

### ISSUE THREAD

**Issue by GreatV** [ultralytics/ultralytics#225]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

**RUN**
```shell
yolo task=classify mode=train epochs=10 model=yolov8n-cls.pt
```

**OUTPUT**
```
yolo/engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=mnist160, epochs=10, patience=50, batch=16, imgsz=640, save=True, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.1, lrf=0.01, momentum=0.937, weight_decay=5e-05, warmup_epochs=0.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.1, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=False, save_dir=runs/classify/train2
Ultralytics YOLOv8.0.3 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16101MiB)
Overriding model.yaml nc=1000 with nc=10

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]           
  9                  -1  1    343050  ultralytics.nn.modules.Classify              [256, 10]                     
YOLOv8n-cls summary: 99 layers, 1451098 parameters, 1451098 gradients, 3.4 GFLOPs
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
DDP settings: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
Traceback (most recent call last):
  File "/home/greatx/.config/Ultralytics/DDP/_temp_hx3l281b139634404079264.py", line 6, in <module>
    trainer.train()
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/trainer.py", line 239, in _do_train
    self._setup_train(rank, world_size)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/trainer.py", line 197, in _setup_train
    self.model = DDP(self.model, device_ids=[rank])
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 551, in __init__
    self._log_and_throw(
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 686, in _log_and_throw
    raise err_type(err_msg)
RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.
Traceback (most recent call last):
  File "/home/greatx/.config/Ultralytics/DDP/_temp_hx3l281b139634404079264.py", line 6, in <module>
    trainer.train()
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/trainer.py", line 239, in _do_train
    self._setup_train(rank, world_size)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/trainer.py", line 197, in _setup_train
    self.model = DDP(self.model, device_ids=[rank])
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 551, in __init__
    self._log_and_throw(
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 686, in _log_and_throw
    raise err_type(err_msg)
RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 27715) of binary: /home/greatx/repos/ultralytics/venv/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/greatx/.config/Ultralytics/DDP/_temp_hx3l281b139634404079264.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-01-11_11:24:05
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27716)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-11_11:24:05
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 27715)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

### Environment

- YOLO: Ultralytics YOLOv8.0.3 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16101MiB)
- OS: Ubuntu 22.04
- Python: Python3.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@GreatV please add a `device=0` flag

**Comment by GreatV** [comment]
> @GreatV please add a `device=0` flag or the device you want to use. if you're using a machine including multiple GPUs then it'll automatically launch DDP if you don't set a `device`. @AyushExel this could be a problem...

After adding `device=0` flag, it works fine.

**Comment by AyushExel** [comment]
@Laughing-q I think happens because default device is None now..When it was `''` it chose the device 0 by default right?

**Comment by Laughing-q** [comment]
@AyushExel yeah I think it is.

**Comment by Laughing-q** [comment]
@GreatV hi now if you don't pass the device, it'll automatically chose device:0 for training on Multi-GPU machine if `torch.cuda.is_available`.

**Comment by Laughing-q** [comment]
@GreatV closing it, feel free to reopen it if you have any related issues. :)

**Comment by Robotatron** [comment]
I have 2x GPU, without "--device" it uses only 1x GPU. 
If I set "--device=0,1" (like in YOLO5) I get an error:
```
yolo task=segment mode=train model=yolov8x-seg.pt epochs=40 data=data/sagemaker.yaml batch=46 imgsz=608 project=runs/Sagemaker name=03-X-600-hyp-default plots=True device=0,1
Ambiguous value for argument 'device=0,1'
1. To use it as a list, use key=[value1,value2]
2. To use it as string, quote the value: key=\'value1,value2\'
3. To sweep over it, add --multirun to your command line
```

**Comment by GreatV** [comment]
@Robotatron You may use `yolo task=segment mode=train epochs=10 device=\'0,1\'`

**Comment by AyushExel** [comment]
@GreatV thanks!
@Robotatron you can find the syntax here in the official docs https://docs.ultralytics.com/quickstart/#use-with-cli
This syntax is forced by hydra. We have plans to simplify this once we have some time

**Comment by Robotatron** [comment]
Thank you! I've looked at the docs but must be have missed that particular example.
