### ISSUE TITLE
custom pose model training

### ISSUE THREAD

**Issue by saim212** [ultralytics/ultralytics#2252]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am trying to train the custom sample dataset for pose estimation with yolov8-pose. But I am getting the issue while training. Here is the traceback.
CMD: yolo task=pose mode=train model=yolov8l-pose.pt data=datasets/coco_2/data.yaml epochs=10 imgsz=1280 batch=1
```

Starting training for 10 epochs...

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       1/10      2.94G      3.639      7.937     0.6994      39.49      2.968          1       1280:  50%|█████     | 2/4 [00:00<00:00,  3.63it/s]
Traceback (most recent call last):
  File "/home/fenris/miniconda3/envs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 370, in train
    self.trainer.train()
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 324, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/pose/train.py", line 52, in criterion
    return self.compute_loss(preds, batch)
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/pose/train.py", line 142, in __call__
    loss[1] += self.keypoint_loss(pred_kpt, gt_kpt, kpt_mask, area)  # pose loss
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fenris/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/utils/loss.py", line 71, in forward
    d = (pred_kpts[..., 0] - gt_kpts[..., 0]) ** 2 + (pred_kpts[..., 1] - gt_kpts[..., 1]) ** 2
RuntimeError: The size of tensor a (3) must match the size of tensor b (0) at non-singleton dimension 1
Sentry is attempting to send 2 pending error messages
``` 
Label Sample:
`0 0.423438 0.517578 0.115625 0.144531 0.367408 0.448061 2 0.414804 0.519154 2 0.472096 0.580873 2`

**Comment by pderrenger** [comment]
@saim212 it looks like you are encountering an issue during the training of a custom pose dataset with YOLOv8. The error message you provided suggests a size mismatch between two tensors.

To troubleshoot this, you may want to double-check the format and structure of your custom pose dataset labels to ensure they align correctly with the expected input format for the YOLOv8 model. The label sample you provided indicates the coordinates of keypoints, but there might be an inconsistency causing the size mismatch.

You might also want to verify that the dataset and label files are correctly formatted as per the YOLOv8 requirements, and that the number of keypoints and their corresponding coordinates match the model's expectations.

Additionally, it could be beneficial to inspect the specific data causing the error to identify any anomalies or discrepancies in the label data that may be triggering the issue.

If you've already validated the dataset format and label structure, and the issue persists, feel free to provide more details about the dataset and label preparation process, or any specific customization you've applied to the YOLOv8 configuration for pose estimation, so that I can assist you more effectively.
