### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered,Sentry is attempting to send 2 pending error messages

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#2294]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
Ultralytics YOLOv8.0.25 🚀 Python-3.8.16 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3060, 12050MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8m.yaml, data=/home/ai/yolov8/ultralytics/ultralytics/yolo/data/datasets/kuanshi_mb.yaml, epochs=300, patience=50, batch=3, imgsz=1280, save=True, cache=False, device=, workers=8, project=ks_01_mb_V4, name=ks_01_mb_V4, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.1, copy_paste=0.1, cfg=None, v5loader=False, save_dir=ks_01_mb_V4/ks_01_mb_V44
Overriding model.yaml nc=80 with nc=8

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.Conv                  [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]                 
 22        [15, 18, 21]  1   3780328  ultralytics.nn.modules.Detect                [8, [192, 384, 576]]          
Model summary: 295 layers, 25860952 parameters, 25860936 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.000984375), 83 bias
train: Scanning /home/ai/yoloOK/labels/train.cache... 2085 images, 4 backgrounds, 0 corrupt: 100%|██████████| 2085/2085 [00:00<?, ?it/
train: WARNING ⚠ /home/ai/yoloOK/images/train/Pic_2023_04_26_113457_39_1.jpg: 1 duplicate labels removed
train: WARNING ⚠ /home/ai/yoloOK/images/train/Pic_2023_04_26_113457_39_2.jpg: 1 duplicate labels removed
train: WARNING ⚠ /home/ai/yoloOK/images/train/Pic_2023_04_26_113457_39_3.jpg: 1 duplicate labels removed
train: WARNING ⚠ /home/ai/yoloOK/images/train/Pic_2023_04_27_095257_15_2.jpg: 1 duplicate labels removed
train: WARNING ⚠ /home/ai/yoloOK/images/train/Pic_2023_04_27_095257_15_3.jpg: 1 duplicate labels removed
train: WARNING ⚠ /home/ai/yoloOK/images/train/Pic_2023_04_27_095257_15_4.jpg: 1 duplicate labels removed
val: Scanning /home/ai/yoloOK/labels/val.cache... 577 images, 2 backgrounds, 0 corrupt: 100%|██████████| 577/577 [00:00<?, ?it/s]
val: WARNING ⚠ /home/ai/yoloOK/images/val/Pic_2023_04_26_113457_39_4.jpg: 1 duplicate labels removed
val: WARNING ⚠ /home/ai/yoloOK/images/val/Pic_2023_04_27_095257_15_0.jpg: 1 duplicate labels removed
Image sizes 1280 train, 1280 val
Using 3 dataloader workers
Logging results to ks_01_mb_V4/ks_01_mb_V44
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/695 [00:00<?, ?it/s]/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [100,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [101,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [102,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [104,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [105,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [106,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [108,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [109,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [110,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [112,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [114,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [116,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [117,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [118,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [120,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [122,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1670525552411/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [9,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
  0%|          | 0/695 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "KUANSHI_mb.py", line 49, in <module>
    results = model.train(data="/home/ai/yolov8/ultralytics/ultralytics/yolo/data/datasets/kuanshi_mb.yaml",imgsz=1280,epochs=300,batch = 3,project="ks_01_mb_V4",name="ks_01_mb_V4")
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 208, in train
    self.trainer.train()
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 301, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/v8/detect/train.py", line 76, in criterion
    return self.compute_loss(preds, batch)
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/v8/detect/train.py", line 174, in __call__
    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/utils/tal.py", line 94, in forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(pd_scores, pd_bboxes, gt_labels, gt_bboxes, anc_points,
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/utils/tal.py", line 113, in get_pos_mask
    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes)
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/utils/tal.py", line 131, in get_box_metrics
    overlaps = bbox_iou(gt_bboxes.unsqueeze(2), pd_bboxes.unsqueeze(1), xywh=False, CIoU=True).squeeze(3).clamp(0)
  File "/home/ai/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/utils/metrics.py", line 82, in bbox_iou
    inter = (b1_x2.minimum(b2_x2) - b1_x1.maximum(b2_x1)).clamp(0) * \
RuntimeError: CUDA error: device-side assert triggered
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by monkeycc** [comment]
num_classes

**Comment by glenn-jocher** [comment]
@monkeycc num_classes refers to the number of classes that the YOLOv8 model is detecting. This parameter needs to be appropriate to the number of classes present in the dataset, otherwise the model may fail to accurately detect objects or may falsely detect objects that are not present. It is recommended to set num_classes to equal the number of unique object types in the dataset.
