### ISSUE TITLE
[Error] AttributeError: 'LoadStreams' object has no attribute 'rect' with Nvidia Orin

### ISSUE THREAD

**Issue by hyunseok-yang** [ultralytics/ultralytics#2304]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I tried to predict the model using UVC USB cam.
But I got this error.

Not a device problem I guess. Cause I could see a capturing image through any capturing util like 'Cheese'.

Could anybody help this out?

Everything was working ok with my workstation(Ubuntu IBM machine), but it happened only at AGX orin machine.

```shell
nvidia@nvidia-desktop:~/Downloads$ yolo predict model=yolov8n.pt source=1 show=true
Ultralytics YOLOv8.0.89 🚀 Python-3.8.10 torch-2.0.0 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

1/1: 1... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)

Traceback (most recent call last):
  File "/home/nvidia/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 252, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 178, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 204, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 186, in setup_source
    self.dataset = load_inference_source(source=source, imgsz=self.imgsz, vid_stride=self.args.vid_stride)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/data/build.py", line 162, in load_inference_source
    dataset = LoadStreams(source, imgsz=imgsz, vid_stride=vid_stride)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/data/dataloaders/stream_loaders.py", line 75, in __init__
    if not self.rect:
AttributeError: 'LoadStreams' object has no attribute 'rect'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
terminate called without an active exception
Aborted (core dumped)

```

### Environment

- Ultralytics YOLOv8.0.89 🚀 Python-3.8.10 torch-2.0.0 CPU
- OS: Ubuntu 20.04
- Python: Python 3.8.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by suzuki-sken** [comment]
Thank you to the development team for everything.
I got the same error too.

 I did a new git pull and ran the inference process and got the following error.
There seems to have been a recent change to the LoadStreams class, is there anything wrong with the code?

**Comment by TommyZihao** [comment]
get the same error on mac book pro
It was OK on yesterday, I run`pip install ultralytics --upgrade` just now
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/36354458/235094280-ac8941cb-5bdd-4cbb-a87c-fcfa083a5376.png">

**Comment by TommyZihao** [comment]
It's OK in V8.0.88, but not OK in V8.0.89

**Comment by Laughing-q** [comment]
@hyunseok-yang @TommyZihao @suzuki-sken made a PR here.

@AyushExel @glenn-jocher  is there a test stream that we can add it to our tests?

**Comment by AyushExel** [comment]
The youtube video is too long for a test. We need something that is 5-10 seconds long. We might have to create one
