### ISSUE TITLE
AttributeError: 'LoadStreams' object has no attribute 'rect'

### ISSUE THREAD

**Issue by RosterMouch** [ultralytics/ultralytics#2310]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When i want to launch my TensorRT inference with camera input like this:
```shell
yolo predict model=best.engine device=0 source=0 imgsz=640
```
It raised error below:
```shell
Traceback (most recent call last):
  File "F:\Anaconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Anaconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Anaconda\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "F:\Anaconda\Lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "F:\Anaconda\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Anaconda\Lib\site-packages\ultralytics\yolo\engine\model.py", line 252, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "F:\Anaconda\Lib\site-packages\ultralytics\yolo\engine\predictor.py", line 178, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "F:\Anaconda\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "F:\Anaconda\Lib\site-packages\ultralytics\yolo\engine\predictor.py", line 204, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "F:\Anaconda\Lib\site-packages\ultralytics\yolo\engine\predictor.py", line 186, in setup_source
    self.dataset = load_inference_source(source=source, imgsz=self.imgsz, vid_stride=self.args.vid_stride)
  File "F:\Anaconda\Lib\site-packages\ultralytics\yolo\data\build.py", line 162, in load_inference_source
    dataset = LoadStreams(source, imgsz=imgsz, vid_stride=vid_stride)
  File "F:\Anaconda\Lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 75, in __init__
    if not self.rect:
AttributeError: 'LoadStreams' object has no attribute 'rect'
```
But all work fine when i set source as a mp4 vidoe file,that's why?

**Comment by Laughing-q** [comment]
@RosterMouch hi, this is a known bug we fixed in #2306 that would be merged to main branch later today. :)
