### ISSUE TITLE
docker jetson-latest missing depedencies

### ISSUE THREAD

**Issue by marktimmerman-dev** [ultralytics/ultralytics#2407]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

```
$ docker pull ultralytics/ultralytics:latest-jetson

$ docker run -it --rm --runtime nvidia --network host ultralytics/ultralytics:latest-jetson

root@ubuntu:/usr/src/ultralytics# yolo
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sentry_sdk' distribution was not found and is required by ultralytics

```
```
# pip3 install sentry_sdk
[...]
ultralytics 8.0.92 requires opencv-python>=4.6.0, which is not installed.
ultralytics 8.0.92 requires scipy>=1.4.1, which is not installed.
ultralytics 8.0.92 requires seaborn>=0.11.0, which is not installed.


```

### Environment

```
Machine: aarch64
System: Linux
Distribution: Ubuntu 20.04 focal
Release: 5.10.104-tegra
Python: 3.8.10

/etc/nv_tegra_release:
# R35 (release), REVISION: 3.1, GCID: 32827747, BOARD: t186ref, EABI: aarch64, DATE: Sun Mar 19 15:19:21 UTC 2023

/sys/firmware/devicetree/base/model:
Jetson AGX Orin

/proc/device-tree/nvidia,boardids:
No such file or directory

/proc/device-tree/compatible:
nvidia,p3737-0000+p3701-0000nvidia,tegra234nvidia,tegra23x

/proc/device-tree/nvidia,dtsfilename:
/dvs/git/dirty/git-master_linux/kernel/kernel-5.10/arch/arm64/boot/dts/../../../../../../hardware/nvidia/platform/t23x/concord/kernel-dts/tegra234-p3701-0000-p3737-0000.dts

```

### Minimal Reproducible Example

$ docker pull ultralytics/ultralytics:latest-jetson

$ docker run -it --rm --runtime nvidia --network host ultralytics/ultralytics:latest-jetson

root@ubuntu:/usr/src/ultralytics# yolo

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @marktimmerman-dev, 

This error `DistributionNotFound: The 'sentry_sdk' distribution was not found and is required by ultralytics` occurs when there are missing packages required for the YOLOv8 environment. 

To fix this, please re-install YOLOv8 with all the required packages available. You can do this with:

`pip install --no-cache-dir -r requirements.txt`

After installation, you should be able to run the `yolo` command successfully with the current docker image.

Let me know if this helps or if you have any further questions.

**Comment by marktimmerman-dev** [comment]
Hello @glenn-jocher , 
Thank you for your reply. Well, I assumed that the idea of a docker image is that it works out of the box.

**Comment by glenn-jocher** [comment]
@marktimmerman-dev yes good point. I've opened #2433 to try to fix this, but I can't test myself since I don't have a Jetson.

**Comment by glenn-jocher** [comment]
@marktimmerman-dev looks like the new changes worked! Let me know if it works for you and if you have any other problems :)

**Comment by marktimmerman-dev** [comment]
`# yolo
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 11, in <module>
    load_entry_point('ultralytics', 'console_scripts', 'yolo')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/src/ultralytics/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/usr/src/ultralytics/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/usr/src/ultralytics/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/usr/src/ultralytics/ultralytics/hub/utils.py", line 14, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/usr/src/ultralytics/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/usr/src/ultralytics/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/usr/src/ultralytics/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/usr/src/ultralytics/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/usr/src/ultralytics/ultralytics/yolo/engine/predictor.py", line 33, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
`

Thank you for working on the issue. This results in dependency problems.

**Comment by marktimmerman-dev** [comment]
@glenn-jocher if it helps, I can give you temporary access to a Jetson Orin Development Kit.

**Comment by marktimmerman-dev** [comment]
opencv is installed twice, via apt-get and via pip3.
`apt-get remove `dpkg -l | grep opencv  | awk '{print $2}'``

AttributeError: module 'cv2' has no attribute 'setNumThreads'
`pip3 remove opencv-python
rm /usr/local/lib/python3.8/dist-packages/cv2
pip3 install "opencv-python < 4.7"

This seems to work on my Jetson.

**Comment by glenn-jocher** [comment]
@marktimmerman-dev hello! 

This error occurs due to a circular import in OpenCV which causes partial initialization of the required modules. One possible solution is to remove all previous installations of OpenCV and re-install a specific version of OpenCV that is compatible with YOLOv8. You can do this by executing the following commands:

```
sudo apt-get remove `dpkg -l | grep opencv  | awk '{print $2}'`
pip3 uninstall opencv-python
rm /usr/local/lib/python3.8/dist-packages/cv2  # Optional
pip3 install "opencv-python < 4.7"
```

After these commands have been executed, OpenCV should be installed and configured correctly, and the YOLOv8 commands can be run successfully. 

Please let us know if this helps or if you have any further questions.

**Comment by glenn-jocher** [comment]
@marktimmerman-dev certainly, we will include this fix in the next version of the YOLOv8 Docker image so that it works correctly out-of-the-box. Thank you for bringing this issue to our attention and helping us improve YOLOv8.

**Comment by glenn-jocher** [comment]
@marktimmerman-dev Dockerfile-jetson has been updated with the 4 additional lines above in https://github.com/ultralytics/ultralytics/pull/2484/commits/f4e3cc3daf3555d42038816d3e7f553b94ff7fb8

This should publish to DockerHub shortly. Please let us know if this resolves your issue!
