### ISSUE TITLE
Validation problems despite training loss reduction

### ISSUE THREAD

**Issue by JeremyMahieu** [ultralytics/ultralytics#2466]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I'm running an image-classification on a very large data set. It's auction items that fall in 1 of 22 categories. I have about 2 million images. My current strategy is to download 10k images at a time. Split this into 10% validation images. I then run the training for 1 epoch and save the model. After than I resume the training with the next batch of 10k images. So far I see a nice reduction in training loss. However the validation loss stays high and the confusion matrix looks incorrect. Have I just not gone far enough yet, and why this weird banding on the confusion matrix?

I don't think my data is being "overfitted" because I have only run the training on never before seen images. I've not yet run multiple epochs on the same data. If I do, the validation loss also doesn't get better after 2 epochs, I think that might have the same problem.

My script looks like this, I have a training function that gets the data, splits for validation, and runs the training for one epoch. I then run this training function in a loop over all my batches of data.
```python
def run_training(batch_start, batch_end, resume):
    
    # Clean
    remove_dir_contents('.')

    # set up categories
    categories = fetch_categories()

    # make folder structure: have a /datasets/val and /datasets/train folder
    # Download and save each image to the corresponding folder: all goes into /datasets/train/class0 to /datasets/train/class21
    # Check if all the images are valid
    # Take a random split for validation goes into /val/class0 to /val/class21
            
    # make the train.yml file
    yaml_content = f'''
    names:
    - '0': Lamps
    - '1': Glass
    - '2': Porcelain
    - '3': Gemstones
    - '4': Furniture
    - '5': Art
    - '6': category 6
	(... until class 21)
    nc: 22
    path: .
    train: train
    val: val
    '''

    with open(os.path.join(main_folder, 'train.yaml'), 'w') as yaml_file:
        yaml_file.write(yaml_content.strip())

    model = YOLO(f"{perm_disk}/resume.pt")
    # Training.
    results = model.train(
    data="../datasets",
    imgsz=640,
    epochs=1,
    patience=1,
    batch=1,
    resume=resume,
    name='mymodel')

    # Save the model as .pt
    shutil.copy('runs/classify/mymodel/weights/best.pt', f"{perm_disk}/resume.pt")


task = Task.init(project_name='myauctiontraining', task_name='AutomaticV1')
task.execute_remotely(queue_name="my-gpu-worder")

perm_disk = '/usr/agent/data'
urllib.request.urlretrieve('https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8m-cls.pt', 'yolov8m-cls.pt')

for batch in range(0, 269):
    resume = 1
    if batch == 0:
        shutil.copy('yolov8m-cls.pt', f"{perm_disk}/resume.pt")
        resume = 0
    batch_start = batch
    batch_end = batch
    run_training(batch_start, batch_end, resume)
```
![image](https://user-images.githubusercontent.com/23409814/236991518-9610f684-fc7a-45e8-807a-88b2b24e2c63.png)
![image](https://user-images.githubusercontent.com/23409814/236755021-e98e406a-9781-4064-9783-37e0d26b0265.png)

The logs look like this:
```
Starting training for batch 89 to 89
Cleaning directory
Fetching categories...
Making folder structure
Downloading images
2023-05-07 17:29:24,877 - clearml.Task - INFO - Completed model upload to <REDACTED>

1683505854648 b72238c1a3db:gpuall DEBUG Progress got /usr/agent/data/shuffled/batch0089.txt
Moving the downloaded images into class folders
Make sure all classes exist
Validate images
Failed to load shape of ./datasets/train/class0/asdfasdf.JPG
(...) #deleting a few corrupt images
Failed to load shape of ./datasets/train/class21/sdfasdf.JPG
Creating validation set
Skipping class21 class folder: less than 5 images
Filling folders with at least one file
YOLOv8m-cls summary: 141 layers, 15800518 parameters, 0 gradients, 41.9 GFLOPs
New https://pypi.org/project/ultralytics/8.0.94 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.92 🚀 Python-3.8.10 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24243MiB)
[34m[1myolo/engine/trainer: [0mtask=classify, mode=train, model=/usr/agent/data/resume.pt, data=../datasets, epochs=1, patience=1, batch=1, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=mymodel, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=0, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/classify/mymodel
[34m[1mAMP: [0mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...

1683505870249 b72238c1a3db:gpuall DEBUG 100%|██████████| 6.23M/6.23M [00:00<00:00, 60.8MB/s]
[34m[1mAMP: [0mchecks passed ✅
[34m[1moptimizer:[0m SGD(lr=0.01) with parameter groups 38 weight(decay=0.0), 39 weight(decay=0.0005), 39 bias
Image sizes 224 train, 224 val
Using 0 dataloader workers
Logging results to [1mruns/classify/mymodel[0m
Starting training for 1 epochs...

      Epoch    GPU_mem       loss  Instances       Size
        1/1     0.451G     0.0262          1        224:   0%|          | 0/9187 [00:00<?, ?it/s]Exception in thread Thread-988:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/ultralytics/yolo/utils/plotting.py", line 351, in plot_images
    if len(cls) > 0:
TypeError: len() of unsized object
        1/1     0.591G    0.01642          1        224:   0%|          | 0/9187 [00:00<?, ?it/s]Exception in thread Thread-989:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/ultralytics/yolo/utils/plotting.py", line 351, in plot_images
    if len(cls) > 0:
TypeError: len() of unsized object
        1/1     0.591G     0.0113          1        224:   0%|          | 0/9187 [00:00<?, ?it/s]Exception in thread Thread-990:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/ultralytics/yolo/utils/plotting.py", line 351, in plot_images
    if len(cls) > 0:
TypeError: len() of unsized object
        1/1     0.596G    0.02235          1        224:   3%|▎         | 275/9187 [00:04<02:11, 67.57it/s]

1683505875430 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02362          1        224:   7%|▋         | 620/9187 [00:09<02:06, 67.72it/s]

1683505880653 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02398          1        224:  11%|█         | 988/9187 [00:15<01:56, 70.48it/s]

1683505885884 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02348          1        224:  15%|█▍        | 1364/9187 [00:20<01:49, 71.58it/s]

1683505891111 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02305          1        224:  19%|█▉        | 1748/9187 [00:25<01:41, 73.11it/s]

1683505896328 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02298          1        224:  23%|██▎       | 2135/9187 [00:30<01:37, 72.22it/s]

1683505901531 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02294          1        224:  28%|██▊       | 2530/9187 [00:35<01:25, 77.57it/s]

1683505906742 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02294          1        224:  32%|███▏      | 2922/9187 [00:41<01:25, 73.42it/s]

1683505911956 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02298          1        224:  36%|███▌      | 3315/9187 [00:46<01:17, 75.59it/s]

1683505917192 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02294          1        224:  40%|████      | 3710/9187 [00:51<01:11, 76.39it/s]

1683505922398 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02296          1        224:  45%|████▍     | 4112/9187 [00:56<01:08, 73.91it/s]

1683505927619 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02319          1        224:  49%|████▉     | 4506/9187 [01:02<01:00, 77.27it/s]

1683505932842 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02323          1        224:  53%|█████▎    | 4907/9187 [01:07<00:55, 77.27it/s]

1683505938061 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02325          1        224:  58%|█████▊    | 5307/9187 [01:12<00:50, 77.39it/s]

1683505943269 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02327          1        224:  62%|██████▏   | 5706/9187 [01:17<00:45, 76.67it/s]

1683505948466 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02338          1        224:  67%|██████▋   | 6110/9187 [01:22<00:39, 77.69it/s]

1683505953672 b72238c1a3db:gpuall DEBUG         1/1     0.596G     0.0234          1        224:  71%|███████   | 6515/9187 [01:28<00:34, 76.67it/s]

1683505958877 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02333          1        224:  75%|███████▌  | 6916/9187 [01:33<00:29, 77.08it/s]

1683505964096 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02331          1        224:  80%|███████▉  | 7325/9187 [01:38<00:23, 77.96it/s]

1683505969304 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02337          1        224:  84%|████████▍ | 7728/9187 [01:43<00:19, 74.43it/s]

1683505974522 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02337          1        224:  89%|████████▊ | 8134/9187 [01:48<00:13, 76.98it/s]

1683505979736 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02337          1        224:  93%|█████████▎| 8538/9187 [01:54<00:08, 77.47it/s]

1683505984934 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02337          1        224:  97%|█████████▋| 8950/9187 [01:59<00:03, 78.22it/s]

1683505990157 b72238c1a3db:gpuall DEBUG         1/1     0.596G    0.02336          1        224: 100%|██████████| 9187/9187 [02:02<00:00, 75.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 290/290 [00:01<00:00, 257.01it/s]
                   all      0.114      0.439

1 epochs completed in 0.035 hours.
Optimizer stripped from runs/classify/mymodel/weights/last.pt, 31.7MB
Optimizer stripped from runs/classify/mymodel/weights/best.pt, 31.7MB
Results saved to [1mruns/classify/mymodel[0m
```

**Comment by JeremyMahieu** [comment]
I'm starting to realize my confusion with the confusion matrix. The "True" axis is actually the predicted result, and the "Predicted" axis is the labled validation data.
Is this a bug? Are the axis flipped?

**Comment by glenn-jocher** [comment]
@JeremyMahieu glad to hear that you were able to get your model working! Regarding your question about the confusion matrix, yes, the "True" axis represents the predicted values of the model and the "Predicted" axis represents the labeled validation data. This may seem counterintuitive at first, but it is how the matrix is typically defined in machine learning. Please let us know if you have any further questions or issues.

**Comment by imba-tjd** [comment]
Hello everyone, I still don't get it.
https://www.youtube.com/watch?v=Kdsp6soqA7o
In this video, the algorithm output is called "predicted".

**Comment by glenn-jocher** [comment]
Thank you for your comment. The confusion matrix terminology can sometimes be counterintuitive. In Ultralytics, the "True" axis represents the model's predictions, while the "Predicted" axis corresponds to the labeled ground truth. This aligns with standard practices but may differ from how it’s presented in some resources. Let us know if you need further clarification!
