### ISSUE TITLE
How to only validate on specific classes?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#2480]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to validate a pretrained model on a custom dataset. 
How can I choose relevant coco classes for this? 

### Additional

I am validating via CLI

### Edit
I saw that I have to pick the relevant classes at least because of this issue: https://github.com/ultralytics/ultralytics/issues/2532#issue-1704703600

**Comment by glenn-jocher** [comment]
@dmddmd thank you for your question! When validating a pre-trained model on a custom dataset via CLI, you can choose relevant classes by modifying the `--classes` argument followed by a space separated list of class names in your command. For instance, if your custom dataset only contains objects belonging to the "person" and "car" classes, you could set `--classes person car` in the command. This ensures that only the predicted bounding boxes for these classes will be included in the output files. I hope this helps! Let me know if you have any further questions.

**Comment by dmddmd** [comment]
thx for your answer! The command is runable: ` yolo detect val model=yolov8x.pt  data=../myyaml.yaml --classes=' 46,47'`
But I get 

> ../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/data/base.py:124: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  j = (cls == include_class_array).any(1)
Traceback (most recent call last):
  File "/../miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 394, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/../miniconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 301, in val
    validator(model=self.model)
  File "/../miniconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/engine/validator.py", line 135, in __call__
    self.dataloader = self.dataloader or self.get_dataloader(self.data.get(self.args.split), self.args.batch)
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/val.py", line 206, in get_dataloader
    dataset = self.build_dataset(dataset_path, batch=batch_size, mode='val')
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/val.py", line 184, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, stride=gs)
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/data/dataset.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 70, in __init__
    self.update_labels(include_class=classes)  # single_cls and include_class
  File "/../miniconda3/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 124, in update_labels
    j = (cls == include_class_array).any(1)
AttributeError: 'bool' object has no attribute 'any'

**Comment by dmddmd** [comment]
with `yolo detect val model=yolov8x.pt  data=/my.yaml classes="46,47"`
I get 

> Ultralytics YOLOv8.0.97 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
YOLOv8x summary (fused): 268 layers, 68200608 parameters, 0 gradients, 257.8 GFLOPs
val: Scanning /dataset/labels/myval.cache... 1203 images, 2729 backgrounds, 10 corrupt: 100%|██████████| 3942/3942 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 246/246 [01:23<00:00,  2.93it/s]
                   all       3932          0          0          0          0          0
WARNING ⚠️ no labels found in detect set, can not compute metrics without labels
Speed: 0.2ms preprocess, 14.9ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to runs/detect/val0008

**Comment by glenn-jocher** [comment]
@dmddmd thank you for sharing the error message. It seems that there are no labels found in the detect set, which causes the metric computation warning to show up. Make sure that your validation dataset contains labels (annotations) for the images you wish to validate. Additionally, you can verify that the labels are in the correct format for YOLO, which is a ".txt" file with a line for each object in the image, where each line contains the object class followed by its bounding box coordinates (x_center, y_center, width, height), all normalized by the image height and width. Finally, make sure that the paths to the image files and their corresponding label files are correct in your YAML file and that the label files are in the same directory as the images or subdirectory. I hope this helps! Let me know if you have any further questions.

**Comment by dmddmd** [comment]
The last error is fixed, but the one I shared before remains

**Comment by glenn-jocher** [comment]
@dmddmd thank you for your response. I apologize for the inconvenience. Based on the error message you shared, it seems like `include_class_array` is expected to be a numpy array, but it's being interpreted as a boolean value.  This issue is likely caused by setting the `classes` argument as a string instead of a list or numpy array in your command. Please make sure that you pass the `--classes` argument as a list or a numpy array, like this: `--classes 46,47` or `--classes [46,47]` respectively, instead of as a string. This should resolve the issue. Let me know if you have any further questions.

**Comment by dmddmd** [comment]
thanks for the suggestion, with ` classes=46,47` and `classes=[46,47]`, I get the same Warning

**Comment by glenn-jocher** [comment]
@dmddmd thank you for your reply. In this case, the warning message that appears during the validation process is simply informing you that there are no labels (annotations) found in the validation set, and that the metrics cannot be computed without those labels. If you are using a custom dataset and have not yet provided labels for the validation set, you can still visually inspect the prediction results saved in the `runs/detect/val0008` directory to assess the performance of your model on that dataset. If you have already provided labels for your validation set, please make sure that the annotations are in the correct format and that their paths in your YAML file are correctly specified. If this is not the issue, please provide more details about your setup so that we can better assist you. I hope this helps! Let me know if you have any further questions.

**Comment by smjk2124** [comment]
[dmddmd](https://github.com/dmddmd), were you able to figure this out? I see a lot of ChatGPT generated responses to your questions from the repo maintainer, so I doubt they would have worked.

**Comment by glenn-jocher** [comment]
@smjk2124 hi [dmddmd](https://github.com/dmddmd)! I understand that you've been receiving automated responses to your questions on this issue. I apologize for any confusion or frustration caused. If you're still facing difficulties, please let us know the specific issue or question you have, and we'll be happy to assist you directly. We're here to help you with any concerns or problems you may be experiencing with YOLOv8. Thank you for your patience!

**Comment by smjk2124** [comment]
@glenn-jocher thanks for the automated response again. My use case is as follows:

- I want to use pre-trained COCO checkpoints to run validation off the shelf with a custom dataset (that has only 5 classes), without any fine-tuning. How would I do this? Looking forward to another automated response, have a great day!

**Comment by glenn-jocher** [comment]
@smjk2124 hi [dmddmd](https://github.com/dmddmd), thank you for reaching out and sharing your use case. To run validation on your custom dataset with pre-trained COCO checkpoints using YOLOv8, you can follow these steps:

1. Ensure that your custom dataset is in the correct format with annotations (labels) for each image in the YOLO format (.txt files containing class and bounding box information).

2. Set up your data configuration file (e.g., `data.yaml`) with the necessary paths and settings for your custom dataset. Make sure to specify the number of classes (in your case, 5) and set the appropriate paths for your training, validation, and testing images and annotations.

3. Use the `detect` mode with the pre-trained COCO checkpoints on your custom validation dataset. Specify the COCO model checkpoint using the `--weights` argument and the custom dataset configuration file using the `--data` argument.

4. Run the detection/validation command, and YOLOv8 will apply the pre-trained model to your custom dataset's validation images and generate predictions. The results will be saved, and the metrics (such as precision, recall, and mean Average Precision) will be computed based on the predictions and ground truth annotations.

Please note that fine-tuning the pre-trained model on your specific dataset can further improve performance. However, if you wish to run validation off the shelf without fine-tuning, the above steps will allow you to evaluate the model's performance on your custom dataset using pre-trained COCO checkpoints.

If you have any further questions or need additional assistance, please feel free to ask. Have a great day!

**Comment by rmukh** [comment]
Hi @smjk2124, @dmddmd,

With YOLOv8.0.202 version 'classes' argument seems to work correctly. You can try to specify them smth. like this
```bash 
yolo detect val data=data.yaml model=model.pt classes=46,47
```
It will perform validation on classes 46,47 of the dataset used for training purpose. You have to note that your annotations should be labeled 10,11,12 in _.txt_ label files and .yaml file should contain names for all labels from the training dataset (_0 to # classes_).

**Comment by glenn-jocher** [comment]
@rmukh, @dmddmd, thanks for your patience and clarification of the use case.

Here's a step-by-step guide to validate a pre-trained COCO model on a custom dataset with a subset of classes:

1. Make sure your custom dataset is properly formatted with the correct directory structure and annotation files.
2. Create a data configuration YAML file that includes paths to your custom dataset's images and annotations. Be sure to list all classes included in the COCO dataset, but keep in mind your annotations should only include the classes relevant to your dataset, with class IDs matching those from the COCO dataset.
3. In your CLI, define the `classes` parameter with the specific COCO class IDs you want to validate. As a reminder, the class IDs must match those used in the COCO dataset and your annotations.

Here is the basic structure of the CLI command:
```shell
yolo detect val model=yolov8x.pt data=my_custom_data.yaml --classes 46,47
```

By specifying the `--classes` argument, YOLOv8 will evaluate predictions only for those classes on your custom dataset. Again, ensure the class IDs align with the COCO class ID system and that your `data.yaml` reflects the full set of classes from COCO.

If you continue to experience issues, ensure that your YOLOv8 installation is up to date, as some bugs may have been fixed in recent updates.

Please reach back out if you encounter any more difficulties or have additional questions.

**Comment by wjlim-14** [comment]
Does anyone know how can I set this on yolov5? I need help on yolov5 with this function.

**Comment by glenn-jocher** [comment]
@wjlim-14 for YOLOv5, you would modify the data configuration file to include only the classes you're interested in. However, the guidance you're seeking is specific to YOLOv5, and it's best to refer to the YOLOv5 documentation or to inquire directly within the YOLOv5 repository for detailed assistance on that model. If you're working with YOLOv8, I'll be happy to guide you through the process here. Have a productive day! 🌟
