### ISSUE TITLE
Error with dataset or something

### ISSUE THREAD

**Issue by p0wned17** [ultralytics/ultralytics#250]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I have this problem with all my custom's dataset and I do not know what the problem is related to

### Environment

OS: Ubuntu 22.04
Env: Anaconda`Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      4.13G      2.737      4.326      3.084        115        640:   0%|          | 1/3858 [00:06<6:41:29,  6.25s/it]
Error executing job with overrides: ['task=detect', 'mode=train', 'model=yolov8n.pt', 'device=0', 'workers=8', 'data=/home/cv_user/projects/yolov7/data/coco.yaml', 'imgsz=640', 'optimizer=Adam', 'epochs=10', 'batch=32']
Traceback (most recent call last):
  File "/home/cv_user/projects/yolov8/ultralytics/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/cv_user/projects/yolov8/ultralytics/ultralytics/yolo/v8/detect/train.py", line 206, in train
    model.train(**cfg)
  File "/home/cv_user/projects/yolov8/ultralytics/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/home/cv_user/projects/yolov8/ultralytics/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/cv_user/projects/yolov8/ultralytics/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
    for i, batch in pbar:
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cv_user/anaconda3/envs/env_yolo/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cv_user/projects/yolov8/ultralytics/ultralytics/yolo/data/base.py", line 179, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/home/cv_user/projects/yolov8/ultralytics/ultralytics/yolo/data/base.py", line 182, in get_label_info
    label = self.labels[index].copy()
IndexError: list index out of range`

### Minimal Reproducible Example

`Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      4.13G      2.737      4.326      3.084        115        640:   0%|          | 1/1100 [00:06<6:41:29,  6.25s/it]
  0%|          | 0/1100 [00:02<?, ?it/s]
Error executing job with overrides: ['task=detect', 'mode=train', 'model=yolov8n.pt', 'data=coco128.yaml', 'device=0']
2135
Traceback (most recent call last):
  File "/home/powned/projects/ultralytics/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/home/powned/anaconda3/envs/cv/lib/python3.10/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/powned/projects/ultralytics/ultralytics/yolo/v8/detect/train.py", line 206, in train
    model.train(**cfg)
  File "/home/powned/projects/ultralytics/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/home/powned/projects/ultralytics/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/powned/projects/ultralytics/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
    for i, batch in pbar:
  File "/home/powned/anaconda3/envs/cv/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/powned/.local/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/powned/projects/ultralytics/ultralytics/yolo/data/base.py", line 179, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/home/powned/projects/ultralytics/ultralytics/yolo/data/augment.py", line 48, in __call__
    data = t(data)
  File "/home/powned/projects/ultralytics/ultralytics/yolo/data/augment.py", line 48, in __call__
    data = t(data)
  File "/home/powned/projects/ultralytics/ultralytics/yolo/data/augment.py", line 84, in __call__
    mix_labels = [self.dataset.get_label_info(i) for i in indexes]
  File "/home/powned/projects/ultralytics/ultralytics/yolo/data/augment.py", line 84, in <listcomp>
    mix_labels = [self.dataset.get_label_info(i) for i in indexes]
  File "/home/powned/projects/ultralytics/ultralytics/yolo/data/base.py", line 183, in get_label_info
    label = self.labels[index].copy()
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@p0wned17 hi this PR [https://github.com/ultralytics/ultralytics/pull/249](https://github.com/ultralytics/ultralytics/pull/249) might solve your issue. or you can set `v5loader=True` util the PR merged.

**Comment by p0wned17** [comment]
> @p0wned17 hi this PR #249 might solve your issue. or you can set `v5loader=True` util the PR merged.

Thank you it helped

**Comment by AyushExel** [comment]
Closing this issue. Feel free to reopen is something is broken
