### ISSUE TITLE
Issue with 'ConnectionResetError: [Errno 104] Connection reset by peer'

### ISSUE THREAD

**Issue by tianyufang1958** [ultralytics/ultralytics#2525]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained the model in detection model, but the process was terminated half way of the 500 epochs with error as below. Could you please help?

269 epochs completed in 0.508 hours.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
Exception in thread Thread-1:
Traceback (most recent call last):
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/reduction.py", line 157, in recvfds
    self.run()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/threading.py", line 870, in run
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
    self._target(*self._args, **self._kwargs)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/reduction.py", line 157, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/datastore/conda_envs/dros_yolo8_norfair/lib/python3.8/multiprocessing/reduction.py", line 157, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
Optimizer stripped from dros/first0002/weights/last.pt, 52.0MB
Optimizer stripped from dros/first0002/weights/best.pt, 52.0MB

**Comment by wrbooth** [comment]
I ran into a similar issue today with the `ultralytics/ultralytics:latest` container doing a multi GPU train, it appears only one GPU was used, possibly because the other 3 GPUs/threads experienced the same issue:

```3 epochs completed in 0.099 hours.
Exception in thread Thread-1 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(self._args, self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Exception in thread Thread-1 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(self._args, self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(self._args, self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Optimizer stripped from /usr/src/ultralytics/runs/detect/train/weights/last.pt, 6.2MB
Optimizer stripped from /usr/src/ultralytics/runs/detect/train/weights/best.pt, 6.2MB

Validating /usr/src/ultralytics/runs/detect/train/weights/best.pt...
YOLOv8n summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
|██████████| 5/5 [00:04<00:00,  1.12it/s]
                   all        750        713      0.778      0.516      0.651      0.264
Speed: 0.6ms preprocess, 0.6ms inference, 0.0ms loss, 0.6ms postprocess per image
Results saved to /usr/src/ultralytics/runs/detect/train
```

**Comment by glenn-jocher** [comment]
@tianyufang1958 thank you for reporting this issue with YOLOv8. The error message indicates that there was a connection issue with one of the GPUs, causing only one GPU to be utilized in the training process. We recommend checking your hardware and networking setup to ensure that all GPUs are properly connected and functioning. Additionally, you may want to try running the training process again to see if the issue persists. Let us know if you continue to encounter any problems.
