### ISSUE TITLE
FileNotFoundError: ultralytics-8.0.3-py3.10.egg/ultralytics/assets does not exis

### ISSUE THREAD

**Issue by GreatV** [ultralytics/ultralytics#262]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

```shell
yolo task=detect mode=predict model=yolov8s.pt
```

```
Ultralytics YOLOv8.0.3 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16101MiB)
Fusing layers... 
YOLOv8s summary: 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8s.pt']
Traceback (most recent call last):
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/v8/detect/predict.py", line 92, in predict
    predictor()
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/predictor.py", line 164, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/engine/predictor.py", line 143, in setup
    self.dataset = LoadImages(source,
  File "/home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/yolo/data/dataloaders/stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: /home/greatx/repos/ultralytics/venv/lib/python3.10/site-packages/ultralytics-8.0.3-py3.10.egg/ultralytics/assets does not exist

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

### Environment

- YOLO: Ultralytics YOLOv8.0.3 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16101MiB)
- OS: ubuntu 22.04
- Python: Python 3.10

### Additional

```shell
yolo task=detect mode=predict model=yolov8s.pt source=ultralytics/assets/bus.jpg
```
This is ok.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@GreatV does this happen in `yolo task=detect mode=predict model=yolov8s.pt`?..by default it'll use the images in ROOT folder of package installation.

**Comment by GreatV** [comment]
@AyushExel Yes, And I use `python setup.py install` build yolo.
