### ISSUE TITLE
Crashes in the first epoch of training (ValueError: cannot reshape array of size 0 into shape (480,640,3))

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#269]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Using on a machine with 1x GPU with 

`yolo task=segment mode=train model=yolov8n-seg.pt epochs=1 imgsz=320 data='/home/jupyter/yolov5/data/sagemaker.yaml' batch=16`

crashes in the first epoch with:
```

2023-01-11 19:58:06
        1/1      2.39G       1.34       3.52      1.037      1.322        271        320:  21%|██        | 1827/8813 [08:14<26:41,  4.36it/s]
2023-01-11 19:58:16
        1/1      2.39G      1.338      3.514      1.033       1.32        328        320:  21%|██        | 1868/8813 [08:24<31:41,  3.65it/s]
2023-01-11 19:58:19
        1/1      2.39G      1.338      3.513      1.031       1.32        306        320:  21%|██▏       | 1883/8813 [08:27<31:09,  3.71it/s]
2023-01-11 19:58:19
Error executing job with overrides: ['task=segment', 'mode=train', 'model=yolov8n-seg.pt', 'epochs=1', 'imgsz=320', 'data=/home/jupyter/yolov5/data/sagemaker.yaml', 'batch=16']
Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 151, in train
    model.train(**cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
    for i, batch in pbar:
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/data/base.py", line 179, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/data/base.py", line 183, in get_label_info
    label["img"], label["ori_shape"], label["resized_shape"] = self.load_image(index)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/data/base.py", line 120, in load_image
    im = np.load(fn)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/numpy/lib/npyio.py", line 432, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/numpy/lib/format.py", line 820, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 0 into shape (480,640,3)
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

### Environment

Ultralytics YOLOv8.0.3 🚀 Python-3.8.15 torch-1.10.1 CUDA:0 (A100-SXM4-40GB, 40536MiB)
Machine: SMP Debian 4.19.269-1 (2022-12-20) (Google GCP VM)

### Minimal Reproducible Example

My custom data + 
`yolo task=segment mode=train model=yolov8n-seg.pt epochs=1 imgsz=320 data='/home/jupyter/yolov5/data/sagemaker.yaml' batch=16`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Robotatron hi, it looks like the issue is that you have image caches(`.npy` files) but actually one of them is empty when numpy trying to load it.
But I don't see any cache options in your training command, can you check the data dir and probably clean the `.npy` files then try again?

**Comment by Robotatron** [comment]
Will close this for now since there is a workaround and it's not strictly a bug (although it was YOLO that created these npy files and then failed to read one of them due to no fault of the user)
