### ISSUE TITLE
BUG when upgrade ultralytics

### ISSUE THREAD

**Issue by ngocnd2402** [ultralytics/ultralytics#2801]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

D:\UIT\Năm 2\Kỳ 4\Nhập môn thị giác máy tính\Last Project>C:/Users/nguye/AppData/Local/Programs/Python/Python310/python.exe "d:/UIT/Năm 2/Kỳ 4/Nhập môn thị giác máy tính/Last Project/v8_video.py"
WARNING  Ultralytics settings reset to defaults. This is normal and may be due to a recent ultralytics package update, but may have overwritten previous settings.
View and update settings with 'yolo settings' or at 'C:\Users\nguye\AppData\Roaming\Ultralytics\settings.yaml'
Traceback (most recent call last):
  File "d:\UIT\Năm 2\Kỳ 4\Nhập môn thị giác máy tính\Last Project\v8_video.py", line 4, in <module>
    from ultralytics import YOLO
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\__init__.py", line 3, in <module>
    from . import v8
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\v8\__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\v8\classify\__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\v8\classify\predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 36, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\autobackend.py", line 17, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\utils\__init__.py", line 621, in <module>
    SETTINGS = get_settings()
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\utils\__init__.py", line 596, in get_settings
    yaml_save(file, settings)  # save updated defaults
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\utils\__init__.py", line 147, in yaml_save
    yaml.safe_dump({k: str(v) if isinstance(v, Path) else v
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 269, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\representer.py", line 28, in represent
    self.serialize(node)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\serializer.py", line 107, in serialize_node
    self.serialize_node(key, node, None)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\serializer.py", line 89, in serialize_node
    self.emit(ScalarEvent(alias, node.tag, implicit, node.value,
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\emitter.py", line 115, in emit
    self.state()
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\emitter.py", line 412, in expect_block_mapping_simple_value
    self.expect_node(mapping=True)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\emitter.py", line 244, in expect_node
    self.expect_scalar()
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\emitter.py", line 268, in expect_scalar
    self.process_scalar()
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\emitter.py", line 533, in process_scalar
    self.write_plain(self.analysis.scalar, split)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\emitter.py", line 1132, in write_plain
    self.stream.write(data)
  File "C:\Users\nguye\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0103' in position 8: character maps to <undefined>

### Environment

Window
Python3.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ngocnd2402 hello! Thank you for reporting this issue. It seems like you may be encountering an error with Unicode encoding when saving updated settings. This issue may be related to the type of file paths that are saved to settings. 

To address this issue, please try updating the file path formatting in your settings file to ensure that the encoding error is avoided.

Additionally, you should also update your Python version to one of the supported versions (3.7 through 3.9) as Python 3.10 is not yet supported by YOLOv8.

Let us know if this helps resolve the issue.

**Comment by glenn-jocher** [comment]
@ngocnd2402 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
