### ISSUE TITLE
now can't export tflite int8 model

### ISSUE THREAD

**Issue by pyl62112991** [ultralytics/ultralytics#3059]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

now can't export tflite int8 model

### Environment

now can't export tflite int8 model

### Minimal Reproducible Example

now can't export tflite int8 model

### Additional

now can't export tflite int8 model

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pyl62112991** [comment]
this is the error message:

TensorFlow SavedModel: running 'onnx2tf -i ./program/ultralytics-main/ultralytics/runs/detect/train63/weights/best.onnx -o ./program/ultralytics-main/ultralytics/runs/detect/train63/weights/best_saved_model -nuo --non_verbose -oiqt -qt per-tensor'
Traceback (most recent call last):
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f109df3ae50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./anaconda3/envs/open/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "./anaconda3/envs/open/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.us-central-1.wasabisys.com', port=443): Max retries exceeded with url: /onnx2tf-en/datas/calibration_image_sample_data_20x128x128x3_float32.npy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f109df3ae50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./anaconda3/envs/open/bin/onnx2tf", line 8, in <module>
    sys.exit(main())
  File "./anaconda3/envs/open/lib/python3.8/site-packages/onnx2tf/onnx2tf.py", line 2057, in main
    model = convert(
  File "./anaconda3/envs/open/lib/python3.8/site-packages/onnx2tf/onnx2tf.py", line 803, in convert
    test_data: np.ndarray = download_test_image_data()
  File "./anaconda3/envs/open/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 3877, in download_test_image_data
    test_sample_images_npy = requests.get(URL).content
  File "./anaconda3/envs/open/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "./anaconda3/envs/open/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "./anaconda3/envs/open/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "./anaconda3/envs/open/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "./anaconda3/envs/open/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.us-central-1.wasabisys.com', port=443): Max retries exceeded with url: /onnx2tf-en/datas/calibration_image_sample_data_20x128x128x3_float32.npy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f109df3ae50>: Failed to establish a new connection: [Errno 111] Connection refused'))
TensorFlow SavedModel: export failure 20.5s: SavedModel file does not exist at: ./program/ultralytics-main/ultralytics/runs/detect/train63/weights/best_saved_model/{saved_model.pbtxt|saved_model.pb}


The export code is:
![1686272408099_A06C8A39-4A45-4fbe-B996-B4CD3406E766](https://github.com/ultralytics/ultralytics/assets/47971541/ce85151e-170b-4dfc-a102-dd160c73d539)

**Comment by pyl62112991** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@pyl62112991 hi there! It seems like you are having trouble exporting a tflite int8 model and are getting a connection error. We apologize for any inconvenience caused. This issue can sometimes be caused by your firewall, and we recommend checking your network settings and retrying the export. Another solution could be to try exporting the tflite int8 model without the quantization flag. If the issue persists, please let us know and provide a minimal reproducible example so we can further investigate the problem. Thank you for using YOLOv8!

**Comment by Les1ie** [comment]
If a parameter can be provided to set the path for using local npy files, or to check if there are any files present locally before downloading, it would be more convenient to use.

Because in some intranet scenarios, external links cannot be directly accessed.

@glenn-jocher @pyl62112991

**Comment by glenn-jocher** [comment]
@Les1ie hello, thank you for your valuable feedback on the export process for the tflite int8 model. 

Regarding providing a parameter to set the path for using local npy files or checking for local files before starting the download, we appreciate your suggestion. As you said, some users may experience difficulties with accessing external links due to network restrictions. We understand how this feature could improve the usability in those scenarios.

We will certainly consider your suggestion for future updates to our YOLOv8 model. We're always working to make our tools as user-friendly and accessible as possible, and input from our community is a crucial part of that process.

Again, thank you for your feedback, and feel free to reach out if you have any other suggestions or issues.

**Comment by Les1ie** [comment]
wz已收到您的邮件。

**Comment by glenn-jocher** [comment]
@Les1ie hello, 

Thank you for reaching out. Could you please provide more information in English regarding your inquiry? This will help us better understand and address your concern related to YOLOv8.

We look forward to hearing back from you soon. 

Best regards.
