### ISSUE TITLE
Can not train after calling `torch.cuda.device_count()`

### ISSUE THREAD

**Issue by ZeroAct** [ultralytics/ultralytics#3098]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

After calling `torch.cuda.device_count()`, yolo automatically changes to the ddp mode. I don't know how to figure out.

### Environment

- YOLO: 8.0.114
- python: 3.9.16
- pytorch: 1.13.1

### Minimal Reproducible Example

This works fine.
```python
from ultralytics import YOLO

YOLO().train(data="datasets/mnist_det/exports/YOLO/data.yaml", device="0", epochs=1)
```

This doesn't work.
```python
import torch
from ultralytics import YOLO

torch.cuda.device_count()
YOLO().train(data="datasets/mnist_det/exports/YOLO/data.yaml", device="0", epochs=1)
```

```
Traceback (most recent call last):
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 242, in _lazy_init
    queued_call()
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 125, in _check_capability
    capability = get_device_capability(d)
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
    prop = get_device_properties(device)
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 375, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lhj/ws/dev/waffle_hub/debug_yolo.py", line 8, in <module>
    YOLO().train(data="datasets/mnist_det/exports/YOLO/data.yaml", device="0", epochs=1)
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 366, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 83, in __init__
    self.device = select_device(self.args.device, self.args.batch)
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/ultralytics/yolo/utils/torch_utils.py", line 89, in select_device
    p = torch.cuda.get_device_properties(i)
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 371, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 246, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

CUDA call was originally invoked at:

['  File "/home/lhj/ws/dev/waffle_hub/debug_yolo.py", line 4, in <module>\n    import torch\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 850, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/__init__.py", line 798, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 850, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n', '  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 179, in <module>\n    _lazy_call(_check_capability)\n', '  File "/home/lhj/anaconda3/envs/waffle/lib/python3.9/site-packages/torch/cuda/__init__.py", line 177, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ZeroAct you can work around this by defining a model first and then getting a device count.

**Comment by glenn-jocher** [comment]
@ZeroAct I'm attaching a no-fix tag here since this order of ops is required for device setup, but if you have any solutions that work well please submit a PR. Thank you!

**Comment by ZeroAct** [comment]
@glenn-jocher I decided to use subprocess rather than python code directly in our system.

I was inspried by your `generate_ddp_file` function. I think its awesome 😎.

Thank you!

**Comment by glenn-jocher** [comment]
@ZeroAct Thank you for the feedback and for exploring the options available to you in configuring your system. I appreciate the compliment about the `generate_ddp_file` function - we try to provide useful and powerful functions to help streamline the experience for YOLOv8 users. If you have any further questions or feedback, feel free to open a new issue or PR and we'll be happy to help!
