### ISSUE TITLE
yolov8 can't  run  in  two  or more gpus  when  cuda=11.xx  

### ISSUE THREAD

**Issue by yutao007** [ultralytics/ultralytics#3151]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

now  yolov8 can't  run  in  two  or more gpus  when  cuda=11.xx    ,i have  tried   python 3.7  3.8  3.9  

### Additional

DDP command: ['/home/anaconda3/envs/yolov8_4/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '60375', '/home/.config/Ultralytics/DDP/_temp_o7dkq7to140240926437328.py']
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
DDP info: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "/home/.config/Ultralytics/DDP/_temp_o7dkq7to140240926437328.py", line 9, in <module>
    trainer.train()
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
    self._setup_train(world_size)
  File "/home//anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 218, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/utils/checks.py", line 384, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/utils/checks.py", line 371, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.data  # FP32 inference
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 111, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 253, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 184, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 222, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 428, in warmup
    self.forward(im)  # warmup
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 314, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home//anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 45, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 62, in predict
    return self._predict_once(x, profile, visualize)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 82, in _predict_once
    x = m(x)  # run
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/nn/modules/conv.py", line 42, in forward_fuse
    return self.act(self.conv(x))
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 15891 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15890) of binary: /home/anaconda3/envs/yolov8_4/bin/python
Traceback (most recent call last):
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/.config/Ultralytics/DDP/_temp_o7dkq7to140240926437328.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-13_16:14:05
  host      : 
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15890)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/anaconda3/envs/yolov8_4/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py", line 398, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 188, in train
    raise e
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 186, in train
    subprocess.run(cmd, check=True)
  File "/home/anaconda3/envs/yolov8_4/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/yolov8_4/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '60375', '/home/.config/Ultralytics/DDP/_temp_o7dkq7to140240926437328.py']' returned non-zero exit status 1.

**Comment by iceisfun** [comment]
I run it on multiple machines using cuda 11.x

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.39.01    Driver Version: 510.39.01    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    Off  | 00000000:44:00.0 Off |                  N/A |
| 41%   52C    P2   164W / 280W |  12444MiB / 24576MiB |     26%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN RTX    Off  | 00000000:88:00.0 Off |                  N/A |
| 41%   64C    P2   188W / 280W |  12008MiB / 24576MiB |     37%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA TITAN RTX    Off  | 00000000:C4:00.0 Off |                  N/A |
| 41%   54C    P2   139W / 280W |  11396MiB / 24576MiB |     29%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

across rtx titan, 3090 and a100, all 4090 machines are cuda 12+

**Comment by laogonggong847** [comment]
Hello @iceisfun Can you tell me the specific instructions you use when training with multiple GPUs, thank you very much.
On windows I'm getting errors when training my own dataset with YOLO V8 on two 3090s, my torch version is 1.12.1.  cuda version is 11.3

The command I ran was
```
python -m torch.distributed.run --nproc_per_node 2 --master_port 55057 Mytrain.py --device 0,1

```

The specific program in Mytrain.py is
```
from ultralytics import YOLO


if __name__ == "__main__":

    model = YOLO(r'D:\work\ultralytics-main\yolov8m.pt')

    model.train(data=r"D:\work\ultralytics-main\ultralytics\datasets\zhiguan.yaml",
                epochs=1,
                batch=36,
                imgsz=512,
                workers=0)   # just add this line of c
```

**Comment by laogonggong847** [comment]
@yutao007哈哈哈哈好兄弟，能不能internationalization一点，怎么给你气的讲中文了。
Are you running it on windows or on ubantu? What instructions are you using for multi-GPU training on the 2080ti?

**Comment by yutao007** [comment]
ubuntu20   2080ti   python=3.8 cuda=10.2 torch=1.9  其余的就是requirements.tet中的一些依赖包。

**Comment by yutao007** [comment]
thanks   ,The latest version can run  in one computer cuda=11.1 python=3.8  torch=1.8,1.9,1.10.1  2gpus(3090)

**Comment by laogonggong847** [comment]
@yutao007 好兄弟你3090 有试过高版本的torch会不会出现这种问题吗
