### ISSUE TITLE
Error trying to use torchscript export with mps

### ISSUE THREAD

**Issue by simgt** [ultralytics/ultralytics#3161]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Export

### Bug

I'm trying to run the torchscript export on Apple's MPS backend, but it seems to fail because presumably some internal tensors haven't been converted to the requested device.

### Environment

- YOLO: 8.0.109
- macOS Ventura
- Python 3.11.3

### Minimal Reproducible Example

```
yolo export model=yolov8n.pt format=torchscript
```

```python
import torch
m = torch.jit.load("yolov8n.torchscript")
m.to(device="mps")
m.forward(torch.ones(1, 3, 640, 640).to(device="mps"))
```

Stack trace:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-9b382390ee29> in <module>
----> 1 m.forward(torch.ones(1, 3, 640, 640).to(device="mps"))

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks.py", line 74, in forward
    _35 = (_18).forward(act, _34, )
    _36 = (_20).forward((_19).forward(act, _35, ), _29, )
    _37 = (_22).forward(_33, _35, (_21).forward(act, _36, ), )
           ~~~~~~~~~~~~ <--- HERE
    return _37
  File "code/__torch__/ultralytics/nn/modules/head.py", line 46, in forward
    anchor_points = torch.unsqueeze(CONSTANTS.c0, 0)
    lt, rb, = torch.chunk(_14, 2, 1)
    x1y1 = torch.sub(anchor_points, lt)
           ~~~~~~~~~ <--- HERE
    x2y2 = torch.add(anchor_points, rb)
    c_xy = torch.div(torch.add(x1y1, x2y2), CONSTANTS.c1)

Traceback of TorchScript, original code (most recent call last):
/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/utils/tal.py(264): dist2bbox
/opt/homebrew/lib/python3.11/site-packages/ultralytics/nn/modules/head.py(60): forward
/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py(1501): _call_impl
/opt/homebrew/lib/python3.11/site-packages/ultralytics/nn/tasks.py(64): _forward_once
/opt/homebrew/lib/python3.11/site-packages/ultralytics/nn/tasks.py(213): forward
/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py(1501): _call_impl
/opt/homebrew/lib/python3.11/site-packages/torch/jit/_trace.py(1056): trace_module
/opt/homebrew/lib/python3.11/site-packages/torch/jit/_trace.py(794): trace
/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/exporter.py(281): export_torchscript
/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/exporter.py(112): outer_func
/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/exporter.py(233): __call__
/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py(115): decorate_context
/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/model.py(340): export
/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/cfg/__init__.py(397): entrypoint
/opt/homebrew/bin/yolo(8): <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
@simgt try to export your model again with device=0 flag

**Comment by simgt** [comment]
@Kayzwer Thanks for the suggestion. `device=0` doesn't work as it's referring to Cuda, however `device=mps` did but made no difference to the error I'm getting when trying to use the model.

**Comment by glenn-jocher** [comment]
@simgt is this supposed to work? i.e. I don't see any mention of TorchScript anywhere on the MPS docs page: https://pytorch.org/docs/stable/notes/mps.html

**Comment by simgt** [comment]
> @simgt is this supposed to work? i.e. I don't see any mention of TorchScript anywhere on the MPS docs page: https://pytorch.org/docs/stable/notes/mps.html

According to the comments on https://github.com/pytorch/pytorch/issues/88820, yes. The trick seems to be to load the model on CPU then convert it to MPS, which I've done initially.

**Comment by glenn-jocher** [comment]
@simgt got it. This feature (if it exists) seems undocumented, so I don't think we can provide any support at this time, but the users on the pytorch issue may be able to assist.
