### ISSUE TITLE
There are a bug

### ISSUE THREAD

**Issue by OneMuMuYan** [ultralytics/ultralytics#3202]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

train: Scanning E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\datasets\hydrogels-seg\labels\train2017.cache... 100 images, 0 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]
WARNING  Box and segment counts should be equal, but got len(segments) = 795, len(boxes) = 815. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
Traceback (most recent call last):
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\data\base.py", line 117, in get_img_files
    assert im_files, f'{self.prefix}No images found'
AssertionError: val: No images found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\x_mytest\demo1.py", line 15, in <module>
    model.train(data="../datasets/hydrogels-seg/hydrogels-seg.yaml", epochs=2, batch=1, imgsz=1024)  # 训练模型
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\engine\trainer.py", line 275, in _do_train
    self._setup_train(world_size)
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\engine\trainer.py", line 241, in _setup_train
    self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\v8\detect\train.py", line 54, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\v8\detect\train.py", line 28, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\data\build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\data\dataset.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\data\base.py", line 71, in __init__
    self.im_files = self.get_img_files(self.img_path)
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\data\base.py", line 119, in get_img_files
    raise FileNotFoundError(f'{self.prefix}Error loading data from {img_path}\n{HELP_URL}') from e
FileNotFoundError: val: Error loading data from E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\datasets\hydrogels-seg\labels\train2017
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

进程已结束,退出代码1

### Additional

####the train code
model = YOLO('yolov8n-seg.yaml')
model.train(data="../datasets/hydrogels-seg/hydrogels-seg.yaml", epochs=2, batch=1, imgsz=1024)  # 训练模型

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
