### ISSUE TITLE
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Artifact batch size exceeded the limit of 100'

### ISSUE THREAD

**Issue by pathikg** [ultralytics/ultralytics#3223]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

I was training a yolov8n on my custom dataset with integrated `azure-mlfow` for tracking. 
![image](https://github.com/ultralytics/yolov5/assets/55437218/9af7e871-c0a7-4b6c-9b52-b33cd704975e)
![image](https://github.com/ultralytics/yolov5/assets/55437218/d74291a9-b7e1-4040-a8da-19b3eba1165d)

Training and tracking worked fine for `epochs` mentioned in the argument but at the end of training, I received the following error 
**Traceback:** 

```
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "ultralytics-exp.py", line 8, in <module>
    model.train(data="data.yaml", epochs=1)  # train the model
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 401, in _do_train
    self.run_callbacks('on_train_end')
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 165, in run_callbacks
    callback(self)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/ultralytics/yolo/utils/callbacks/mlflow.py", line 61, in on_train_end
    run.pyfunc.log_model(artifact_path=experiment_name,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 1578, in log_model
    return Model.log(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/models/model.py", line 487, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 810, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1048, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_store/artifact/artifact_repo.py", line 88, in log_artifacts
    self.artifacts.upload_dir(local_dir, dest_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 90, in upload_dir
    empty_artifact_res = self._create_empty_artifacts(paths=remote_paths, run_id=self._run_id)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 146, in _create_empty_artifacts
    response = self._client.run_artifacts.batch_create_empty_artifacts(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_restclient/run_artifact/operations/_run_artifacts_operations.py", line 1122, in batch_create_empty_artifacts
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Artifact batch size exceeded the limit of 100'
```

### Environment

YOLO - Ultralytics YOLOv8.0.117 🚀 Python-3.8.5 torch-2.0.1+cu117 CUDA:0 (Tesla T4, 15110MiB)
OS - Ubuntu 20.04.6 LTS (Azure ML GPU instance)

### Minimal Reproducible Example

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
model.train(data="data.yaml", epochs=3)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
```

### Additional

AzureML GPU: Standard_NC4as_T4_v3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pathikg thanks for the bug report. I'm not on azure so can not reproduce or assist here. Since the error is generated by MLFlow I'd reach out to them for support directly.

**Comment by glenn-jocher** [comment]
@ouphi @dankernel there seems to be a bug in MLFlow with Azure, do you know what might be wrong here? I'm reaching out to you guys since you are the original authors of the integration code. Please help if you can, thank you!

**Comment by dankernel** [comment]
@pathikg  

As the original author of the integration code, I'm very pleased to see that my code is being widely used.

I can't reproduce the bug through Azure. However, regarding this issue, it seems that an error occurs in the log_model() function after the training is completed.

According to the message, there seems to be some limitation in Azure. If you simply want to avoid the error, you can comment out the following code.

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/callbacks/mlflow.py#LL61C20-L61C29

**Comment by glenn-jocher** [comment]
@dankernel,

Thank you for bringing this issue to our attention. As the original author of the integration code, I'm glad to see it being used.

From the error message you provided, it seems that there is a limitation in Azure related to the `log_model()` function after training is completed. However, I'm unable to reproduce the bug in Azure myself.

To avoid the error, you can try commenting out the following code in the `mlflow.py` file:
```python
run_id = mlflow.active_run().info.run_id
mlflow.pytorch.log_model(model=model_info, artifact_path="models", registered_model_name=f"yolov8_{run_id}")
```

Please let me know if you have any further questions or concerns.

**Comment by pderrenger** [comment]
You're welcome, @pathikg! I'm glad to hear that commenting out the line resolved the issue for YOLOv8 as well as for your YOLOv5 mlflow logger. If you have any more questions or need further assistance, feel free to ask. Good luck with your projects, and happy coding! 😊
