### ISSUE TITLE
Error during segmentation training. Model trained fine.

### ISSUE THREAD

**Issue by initdebugs** [ultralytics/ultralytics#335]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Despite the following errors, the model trained fine and is usable.

### **While trying to train a segmentation model, I got the following error after epoch 90:**

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
     91/100      3.35G     0.4145     0.6496     0.3472     0.9258         14        640:   1% 1/109 [00:00<01:46,  1.01it/s]Exception in thread Thread-279:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
     91/100      3.35G     0.3803     0.5647     0.2971     0.9311         16        640:   2% 2/109 [00:01<00:59,  1.80it/s]Exception in thread Thread-280:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
     91/100      3.35G     0.3793     0.5497     0.3008     0.9271         15        640:   3% 3/109 [00:01<00:39,  2.69it/s]Exception in thread Thread-281:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 261, in plot_images
    image_masks = masks[idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 16 but corresponding boolean dimension is 15

### **After the last epoch was trained, the following errors entered the screen:**
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
Exception in thread Thread-311:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95):  50% 2/4 [00:01<00:01,  1.20it/s]Exception in thread Thread-312:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
Exception in thread Thread-313:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95):  75% 3/4 [00:02<00:00,  1.56it/s]Exception in thread Thread-314:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
Exception in thread Thread-315:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% 4/4 [00:02<00:00,  1.54it/s]
                   all        115        116      0.963      0.966      0.981      0.823      0.963      0.966      0.981      0.834

100 epochs completed in 0.569 hours.
Optimizer stripped from runs/segment/train2/weights/last.pt, 6.8MB
Optimizer stripped from runs/segment/train2/weights/best.pt, 6.8MB

Validating runs/segment/train2/weights/best.pt...
Ultralytics YOLOv8.0.5 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (A100-SXM4-40GB, 40536MiB)
Fusing layers... 
YOLOv8n-seg summary: 195 layers, 3258259 parameters, 0 gradients, 12.0 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95):  25% 1/4 [00:01<00:05,  1.67s/it]Exception in thread Thread-670:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
Exception in thread Thread-669:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95):  50% 2/4 [00:02<00:02,  1.14s/it]Exception in thread Thread-1023:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
Exception in thread Thread-1024:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95):  75% 3/4 [00:03<00:00,  1.13it/s]Exception in thread Thread-1377:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
Exception in thread Thread-1378:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% 4/4 [00:03<00:00,  1.16it/s]
                   all        115        116      0.956      0.957      0.981      0.832      0.964      0.966      0.985      0.837
Speed: 1.5ms pre-process, 1.3ms inference, 0.0ms loss, 1.0ms post-process per image
Saving runs/segment/train2/predictions.json...
Results saved to runs/segment/train2

### Environment

Ultralytics YOLOv8.0.5 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (A100-SXM4-40GB, 40536MiB)
Setup complete ✅ (12 CPUs, 83.5 GB RAM, 23.0/166.8 GB disk)
Google Colab Enviroment

### Minimal Reproducible Example

!yolo task=segment mode=train model=yolov8n-seg.pt data={dataset.location}/data.yaml epochs=100 imgsz=640 single_cls=True 

### Additional

This was done using a dataset I created on Roboflow.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ichsan2895** [comment]
Getting similar issue when I run a tutorial based from google colab
https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-instance-segmentation-on-custom-dataset.ipynb

But, suprisingly, it works with my custom dataset in colab too

**Comment by Laughing-q** [comment]
@initdebugs @ichsan2895 looks like a threading issue. Actually it only affects plotting and won't harm training, so your models are fine.
