### ISSUE TITLE
Training stops at 85th epochs

### ISSUE THREAD

**Issue by cognitica-shri** [ultralytics/ultralytics#3414]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

@glenn-jocher I am getting an error -" tensorflow.python.framework.errors_impl.FailedPreconditionError: runs/detect/train2/events.out.tfevents.1687850605.59944f8c394b.34155.0; Transport endpoint is not connected"

This happens to me after 85th epochs regularly

I am using colab to run and I save the model in my drive regularly after each epoch and fetch the dataset from the colab localhost.

From the starting to 85th epochs the training works well and the result of the model is also somewhat ok.

**Full Error :-**
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 289, in _run
    self._record_writer.flush()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/record_writer.py", line 43, in flush
    self._writer.flush()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/lib/io/file_io.py", line 221, in flush
    self._writable_file.flush()
tensorflow.python.framework.errors_impl.FailedPreconditionError: runs/detect/train2/events.out.tfevents.1687850605.59944f8c394b.34155.0; Transport endpoint is not connected
     85/200      2.29G      1.102      1.055      1.256         68        640:  25% 218/855 [00:42<02:03,  5.16it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 405, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 354, in _do_train
    self.run_callbacks('on_batch_end')
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 165, in run_callbacks
    callback(self)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/callbacks/tensorboard.py", line 36, in on_batch_end
    _log_scalars(trainer.label_loss_items(trainer.tloss, prefix='train'), trainer.epoch + 1)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/callbacks/tensorboard.py", line 19, in _log_scalars
    writer.add_scalar(k, v, step)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 391, in add_scalar
    self._get_file_writer().add_summary(summary, global_step, walltime)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 113, in add_summary
    self.add_event(event, global_step, walltime)
  File "/usr/local/lib/python3.10/dist-packages/clearml/binding/frameworks/tensorflow_bind.py", line 1034, in _patched_add_eventT
    return PatchSummaryToEventTransformer._original_add_eventT(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 98, in add_event
    self.event_writer.add_event(event)
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 117, in add_event
    self._async_writer.write(event.SerializeToString())
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 171, in write
    self._check_worker_status()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 212, in _check_worker_status
    raise exception
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 289, in _run
    self._record_writer.flush()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/record_writer.py", line 43, in flush
    self._writer.flush()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/lib/io/file_io.py", line 221, in flush
    self._writable_file.flush()
tensorflow.python.framework.errors_impl.FailedPreconditionError: runs/detect/train2/events.out.tfevents.1687850605.59944f8c394b.34155.0; Transport endpoint is not connected

### Environment

Ultralytics YOLOv8.0.123 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)

### Minimal Reproducible Example

# Build a new model from YAML, transfer pretrained weights to it and start training
!yolo detect train data="/content/dataset/data.yaml" model=yolov8n.yaml pretrained=yolov8n.pt epochs=200 imgsz=640 patience=25 cache=ram batch=16

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by frabob2017** [comment]
May I ask where I can find this log file? In which directory it is located? I cannot find it.

**Comment by glenn-jocher** [comment]
@cognitica-shri this seems to be an issue in TensorBoard. If you are not using it you might uninstall it, or if you are using it then it's probably worthwhile raising a bug on the tensorboard repository. I'm not able to reproduce this with common datasets like COCO8, so I'm going to attach a non-reproducible tag.

**Comment by frabob2017** [comment]
where can I find this log file, in which directory?

**Comment by cognitica-shri** [comment]
> where can I find this log file, in which directory?

I have connected colab notebook to ClearML and I got this log files.

**Comment by frabob2017** [comment]
I will try ClearML to see if I can find this log file. When I run it, the output normally will show in the screen. But I cannot find this output to the .txt file

**Comment by glenn-jocher** [comment]
@cognitica-shri thank you for reaching out! In order to find the log file you mentioned, you can try the following steps:

1. Check the current working directory: The log file might be saved in the directory where you executed the training script. You can use the `os.getcwd()` function in Python to get the current working directory. 

2. Specify the log file location: If the log file is not saved in the working directory, you might need to specify the file location in your training script. Look for lines of code that handle logging or saving the training progress and check if a specific directory or file path is specified.

3. Search for the log file: If you are unable to locate the log file using the previous steps, you can try searching for it. On Colab, you can use the `!find` command to search for files. For example, you can run `!find / -name 'log.txt'` to search for a file named 'log.txt' on your Colab instance.

If you are using ClearML, the log file may be stored on its platform. You can check the ClearML documentation or user interface to find the location of the log file within the ClearML ecosystem.

I hope these steps help you locate the log file you are looking for. If you have any further questions, please feel free to ask!
