### ISSUE TITLE
<yolo cfg=default.yaml> from documentation not working

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#343]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Using `yolo cfg=custom.yaml `I am getting an error:

```
19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
 22        [15, 18, 21]  1  12345098  ultralytics.nn.modules.Segment               [30, 32, 320, [320, 640, 640]]
YOLOv8x-seg summary: 401 layers, 71779738 parameters, 71779722 gradients, 344.7 GFLOPs

ClearML Task: created new task id=1f7a10ac7b631482695d494d963359c445
2023-01-13 20:54:48,991 - clearml.Task - INFO - No repository found, storing script code instead
ClearML results page: https://app.clear.ml/projects/927asdb87cc/experiments/1f7a10ac7basdc445/output/log
2023-01-13 20:54:53,754 - clearml.Task - WARNING - Parameters must be of builtin type (General/hydra[DictConfig])
AutoBatch: Computing optimal batch size for --imgsz 600
AutoBatch: CUDA:0 (A100-SXM4-40GB) 39.59G total, 0.56G reserved, 0.55G allocated, 38.48G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Error executing job with overrides: ['cfg=custom.yaml']
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 254, in run_and_report
    assert mdl is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/bin/yolo", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 296, in run_and_report
    raise ex
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 56, in cli
    func(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 152, in train
    model.train(**cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 185, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 210, in _setup_train
    self.batch_size = check_train_batch_size(self.model, self.args.imgsz, self.amp)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/utils/autobatch.py", line 18, in check_train_batch_size
    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/utils/autobatch.py", line 60, in autobatch
    p = np.polyfit(batch_sizes[:len(y)], y, deg=1)  # first degree polynomial fit
  File "<__array_function__ internals>", line 180, in polyfit
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/numpy/lib/polynomial.py", line 638, in polyfit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x
```

### Environment

Ultralytics YOLOv8.0.5 🚀 Python-3.8.15 torch-1.10.1

### Minimal Reproducible Example

yolo cfg=custom.yaml

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
Do I have to pip install hydra for YOLOv8 pip package?

**Comment by AyushExel** [comment]
Is this reproducible in the colab? maybe your dataset has some problems?

**Comment by Robotatron** [comment]
I think it was an issue with image size being 600
