### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'

### ISSUE THREAD

**Issue by QIANXUNZDL123** [ultralytics/ultralytics#349]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

  i use yolov8 train mydata ,but have Last error:

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10      16.5G      3.493      10.63      1.606         18       1280: 100%|██████████| 16/16 [00:06<00:00,  2.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/9 [00:00<?Error executing job with overrides: ['model=ultralytics/models/v8/yolov8s2.yaml', 'data=ultralytics/yolo/data/datasets/mydata.yaml', 'epochs=10', 'imgsz=1280', 'batch=60']
Error executing job with overrides: ['model=ultralytics/models/v8/yolov8s2.yaml', 'data=ultralytics/yolo/data/datasets/mydata.yaml', 'epochs=10', 'imgsz=1280', 'batch=60']
Error executing job with overrides: ['model=ultralytics/models/v8/yolov8s2.yaml', 'data=ultralytics/yolo/data/datasets/mydata.yaml', 'epochs=10', 'imgsz=1280', 'batch=60']
Traceback (most recent call last):
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/v8/detect/train.py", line 207, in train
    model.train(**cfg)
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/engine/model.py", line 195, in train
    self.model, _ = attempt_load_one_weight(str(self.trainer.best))
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/nn/tasks.py", line 344, in attempt_load_one_weight
    ckpt = torch.load(attempt_download(weight), map_location='cpu')  # load
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/v8/detect/train.py", line 207, in train
    model.train(**cfg)
Traceback (most recent call last):
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/engine/model.py", line 195, in train
    self.model, _ = attempt_load_one_weight(str(self.trainer.best))
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/v8/detect/train.py", line 207, in train
    model.train(**cfg)
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/engine/model.py", line 195, in train
    self.model, _ = attempt_load_one_weight(str(self.trainer.best))
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/nn/tasks.py", line 344, in attempt_load_one_weight
    ckpt = torch.load(attempt_download(weight), map_location='cpu')  # load
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/nn/tasks.py", line 344, in attempt_load_one_weight
    ckpt = torch.load(attempt_download(weight), map_location='cpu')  # load
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<0
                   all        265        740      0.098     0.0135       0.05     0.0114
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 254634 closing signal SIGTERM
Signal received. 15 <frame at 0x7fd4ec005ec0, file '/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py', line 214, code __exit__>
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 254635) of binary: /root/miniconda3/envs/pytorch_obb/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/v8/detect/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-01-14_10:12:45
  host      : c805e2843fed
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 254636)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-01-14_10:12:45
  host      : c805e2843fed
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 254637)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-14_10:12:45
  host      : c805e2843fed
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 254635)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Error executing job with overrides: ['model=ultralytics/models/v8/yolov8s2.yaml', 'data=ultralytics/yolo/data/datasets/mydata.yaml', 'epochs=10', 'imgsz=1280', 'batch=60']
Traceback (most recent call last):
  File "ultralytics/yolo/v8/detect/train.py", line 207, in train
    model.train(**cfg)
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/yolo/engine/model.py", line 195, in train
    self.model, _ = attempt_load_one_weight(str(self.trainer.best))
  File "/home/workpart/zhangdaoliang/YoloV8/yolov8/ultralytics/nn/tasks.py", line 344, in attempt_load_one_weight
    ckpt = torch.load(attempt_download(weight), map_location='cpu')  # load
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/pytorch_obb/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train5/weights/best.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

so , why have some error????How to solve this problem

**Comment by Robotatron** [comment]
What was your console command to start training? You are probably providing the path for the model incorrectly

**Comment by ichsan2895** [comment]
Whats your syntax to run training process? From this log : 
```
[00:00<?Error executing job with overrides: ['model=ultralytics/models/v8/yolov8s2.yaml', 'data=ultralytics/yolo/data/datasets/mydata.yaml', 'epochs=10', 'imgsz=1280', 'batch=60']
```

Seems it error because you didn't properly adjust parameter for `model` and `data.yaml`
For model you can select the default pretrained model. please select on of this : `yolov8n.pt`, `yolov8s.pt`, `yolov8m.pt`, `yolov8l.pt`, `yolov8x.pt` )

For data.yaml, please correctly providing path to your dataset

**Comment by QIANXUNZDL123** [comment]
> What was your console command to start training? You are probably providing the path for the model incorrectly

my console command is   “python ultralytics/yolo/v8/detect/train.py model=ultralytics/models/v8/yolov8s.yaml data=ultralytics/yolo/data/datasets/mydata.yaml epochs=2000 imgsz=1280 batch=60” ，I want to use source code for training, my data and also  i want to modify source code but i don't go to anaconda/env/lib/sitpackage/ to modify source

**Comment by QIANXUNZDL123** [comment]
> Whats your syntax to run training process? From this log :
> 
> ```
> [00:00<?Error executing job with overrides: ['model=ultralytics/models/v8/yolov8s2.yaml', 'data=ultralytics/yolo/data/datasets/mydata.yaml', 'epochs=10', 'imgsz=1280', 'batch=60']
> ```
> 
> Seems it error because you didn't properly adjust parameter for `model` and `data.yaml` For model you can select the default pretrained model. please select on of this : `yolov8n.pt`, `yolov8s.pt`, `yolov8m.pt`, `yolov8l.pt`, `yolov8x.pt` )
> 
> For data.yaml, please correctly providing path to your dataset
i want to use source model and not pip install ultralytics, like yolov5

**Comment by pderrenger** [comment]
@QIANXUNZDL123 it seems like you want to use the modified source code for training and have added some modules in the YOLOv8 source code. To run the training process using the modified source code, you can specify the custom paths for `model` and `data` in the command without referencing installed packages. 

For the `model` parameter, you can provide the path to your modified YOLOv8 model file, such as `my_yolov8_model.pt`. 

For the `data.yaml` parameter, you can specify the path to your custom dataset configuration file, like `my_custom_dataset.yaml`.

Thus, your command for starting the training process might look like this:
```
python ultralytics/yolo/v8/detect/train.py model=/path/to/your/custom/yolov8_model.pt data=/path/to/your/custom/data.yaml epochs=2000 imgsz=1280 batch=60
```

By specifying the paths to your custom model and dataset, you can run the training process using the modified source code and the added modules under your folder, similar to how you would do it for YOLOv5.

**Comment by glenn-jocher** [comment]
@pderrenger, it looks like you're trying to train with a custom setup. Make sure your `model` parameter points to your modified `.yaml` file and your `data` parameter points to your custom `data.yaml`. Your command should reference the relative paths from your current directory to these files. If you've added custom modules, ensure they're correctly integrated into the source code you're running. If the error persists, double-check the paths and ensure that the training process has the necessary permissions to access the files. Good luck with your training! 🚀
