### ISSUE TITLE
yolov8 segmentation fails with a RuntimeError

### ISSUE THREAD

**Issue by aspyct** [ultralytics/ultralytics#353]
Hello,

Trying out yolov8 today, it's absolutely great! Thanks for this awesome piece of software :)

I'm running into an issue while trying to run an image segmentation with the CLI utility. Logs here below:

```$ HYDRA_FULL_ERROR=1 yolo task=segment mode=predict model=yolov8x.pt source=/path/to/my/image.jpg

Ultralytics YOLOv8.0.5 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
Fusing layers...
YOLOv8x summary: 268 layers, 68200608 parameters, 0 gradients, 257.8 GFLOPs
Error executing job with overrides: ['task=segment', 'mode=predict', 'model=yolov8x.pt', 'source=/path/to/my/image.jpg']
Traceback (most recent call last):
  File "/home/aspyct/.local/bin/yolo", line 8, in <module>
    sys.exit(cli())
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/aspyct/.local/lib/python3.10/site-packages/ultralytics/yolo/cli.py", line 56, in cli
    func(cfg)
  File "/home/aspyct/.local/lib/python3.10/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/aspyct/.local/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/predict.py", line 114, in predict
    predictor.predict_cli()
  File "/home/aspyct/.local/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 220, in predict_cli    for _ in (self.__call__(source, model, return_outputs)):
  File "/home/aspyct/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/home/aspyct/.local/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 184, in __call__
    preds = self.postprocess(preds, im, im0s)
  File "/home/aspyct/.local/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/predict.py", line 33, in postprocess
    masks.append(ops.process_mask(proto[i], pred[:, 6:], pred[:, :4], img.shape[2:], upsample=True))  # HWC
  File "/home/aspyct/.local/lib/python3.10/site-packages/ultralytics/yolo/utils/ops.py", line 544, in process_mask
    masks = (masks_in @ protos.float().view(c, -1)).sigmoid().view(-1, mh, mw)  # CHW
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x32 and 144x300)
```

Note that the `mode=detect` works perfectly fine.

I fiddled quite a lot with my local environment to get any kind of ML working, so it could be that something is broken on my machine, but the RuntimeError doesn't seem to suggest that. Still, I figured I'd mention it :)

To be honest I don't have the first idea about how this work, but I'm happy to dig into it. How should I go about debugging this?

**Comment by AyushExel** [comment]
@aspyct thanks for reporting! Is this error reproducible in the colab?

**Comment by aspyct** [comment]
Ha, good question. Let me try that :) I should probably go find the colab first...

**Comment by aspyct** [comment]
@AyushExel Yes, I could reproduce the issue in this colab: https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

All I did was replace the task=detect with task=segment

**Comment by AyushExel** [comment]
okay thanks we'll try to fix it soon
@glenn-jocher @Laughing-q

**Comment by aspyct** [comment]
Amazing! Thanks a lot :)

**Comment by ichsan2895** [comment]
> @AyushExel Yes, I could reproduce the issue in this colab: https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb
> All I did was replace the task=detect with task=segment

If you want to change task=detect to task=segment. It was expected to error. Because the dataset (yolo txt annotation) was created for bbox format in that notebook.


BBOX format = class Xcenter Ycenter Width Height
Segmentation format = class X1 Y1 X2 Y2 so on... 

```
['task=segment', 'mode=predict', 'model=yolov8x.pt', 'source=/path/to/my/image.jpg']
Traceback (most recent call last):
```

`yolov8x.pt` is not compatible with `task=segment` too

**Comment by Laughing-q** [comment]
@aspyct hi if you're going to predict segmentation, you also have to use `yolov8x-seg.pt`. But from your command I saw you were using `yolov8x.pt` for segment. So that's the problem.

**Comment by aspyct** [comment]
Indeed, that solved the issue. Many thanks :)
