### ISSUE TITLE
Training a custom dataset on yolov8m-pose fails

### ISSUE THREAD

**Issue by MiiaBestLamia** [ultralytics/ultralytics#3574]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!
I've been trying to train yolov8m-pose on a custom dataset of mine, yet I've been having crashes due to the following error:
```
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/mnt/data/venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/data/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/mnt/data/ultralytics/ultralytics/yolo/data/dataset.py", line 193, in collate_fn
    value = torch.cat(value, 0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2 but got size 0 for tensor number 1 in the list.
```
I'm using a 3070 with CUDA version 11.7, I git cloned the latest version of this repository about 5 hours ago. I tried training on the COCO8-pose dataset, which works flawlessly.

I've reduced my ~2 thousand image dataset to just 8 images (4 train, 4 val), for testing purposes, yet the error still happens, despite manually checking that none of the images are corrupted and all of the label files match the required format, so I believe that my dataset is not the cause of the issue.

I've included a .zip with said test dataset, in hopes someone can test it on their machine, post their results (I've tried both the 2D and 3D keypoint formats to no avail).
[test_dataset.zip](https://github.com/ultralytics/ultralytics/files/11973293/test_dataset.zip)

When checking the collate_fn function, all of the data appears normal (the class tensors and the bounding box tensors) until it gets to the keypoint part, where some of the keypoint tensors are strangely empty, despite the dataset having only 8 images, the labels of which are correct.

I would appreciate any and all help, thank you for your time!

**Comment by Laughing-q** [comment]
@MiiaBestLamia hi, I think it's because of the `flip_idx: []` in your data.yaml file. If you don't want `flip` augmentation then please just remove the key.

**Comment by Laughing-q** [comment]
@MiiaBestLamia actually I think we can also support this case when `flip_idx=[]`, added in #3577

**Comment by Laughing-q** [comment]
@MiiaBestLamia 
> Just as a note - I feel like it would be nice to see a warning or an error mentioning that flip_idx is empty (I currently do not receive any information about it when launching the exact same code, exact same custom_pose.yaml as mentioned in my initial post on the latest version of the repo, [https://github.com/ultralytics/ultralytics/commit/6a832cdcd3886d483ee9b505d2701fc854fe9e21], I only receive a warning when I comment it shut, saying "WARNING warning No 'flip_idx' array defined in data.yaml, setting augmentation 'fliplr=0.0'")

yeah after the PR merged, it'll raise this warning if you give `flip_idx=[]`, but it has not been merged for now. :)

> And maybe you can give me a hint - if I have two keypoints per image, the first one always being the head of a player, the second always being the ball they have in their hands, regardless of any flipping, what should my flip_idx look like (I think since 0th point becomes the 1st, the 1st becomes the 0th after horizontal flipping, maybe flip_idx=[1,0])? I'd like the horizontal flip augmentation.

Depends on the dataset. This arg `flip_idx` is for some keypoints that have left-right symmetry i.e left hand and right head. 
From your dataset it seems like the keypoints needing to be detected are the head and right hand, which I think just put `flip_idx=[0,1]`(keep the same order when using horizontal flipping) since these two points do not have left-right symmetry.

**Comment by MiiaBestLamia** [comment]
I see, I thought it was already merged, but checking again - the pull request is still open, my bad!
And yes, going by the way you described it, flip_idx=[0,1] seems correct.
Thank you for all your work and the help you provided!

**Comment by glenn-jocher** [comment]
@MiiaBestLamia great news 😃! Your original issue may now be resolved ✅ in PR #3574. This PR was just merged and will be published in a new `ultralytics==8.0.127` update later today. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
