### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by dimaspratama08** [ultralytics/ultralytics#3635]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I tried to run training on detection object model, it worked just fine the last time i used yolov8, but when i tried to run yolov8 just now it gave me this error message

`Traceback (most recent call last):
  File "C:\Users\dimas\Anaconda\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 123, in __init__
    self.data = check_det_dataset(self.args.data)
  File "C:\Users\dimas\Anaconda\lib\site-packages\ultralytics\yolo\data\utils.py", line 206, in check_det_dataset
    data = yaml_load(data, append_filename=True)  # dictionary
  File "C:\Users\dimas\Anaconda\lib\site-packages\ultralytics\yolo\utils\__init__.py", line 302, in yaml_load
    return {**yaml.safe_load(s), 'yaml_file': str(file)} if append_filename else yaml.safe_load(s)
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\dimas\Anaconda\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 4, column 1:
    5
    ^
could not find expected ':'
  in "<unicode string>", line 5, column 1:
    # Classes
    ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Dimas\11. Astra Agro Lestari\Palm Detection\training-yolov8s.py", line 7, in <module>
    results = model.train(data=r"C:\Dimas\11. Astra Agro Lestari\Palm Detection\config.yaml", epochs=100, device=0)  # train the model
  File "C:\Users\dimas\Anaconda\lib\site-packages\ultralytics\yolo\engine\model.py", line 368, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
  File "C:\Users\dimas\Anaconda\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'C:\Dimas\11. Astra Agro Lestari\Palm Detection\config.yaml' error  while scanning a simple key
  in "<unicode string>", line 4, column 1:
    5
    ^
could not find expected ':'
  in "<unicode string>", line 5, column 1:
    # Classes
    ^`

### Environment

YOLOv8 8.0.132
Python 3.10.9
OS Win 11

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by dimaspratama08** [comment]
@glenn-jocher Please help

**Comment by dimaspratama08** [comment]
update!
i manage to solved the error but now i got AMP checks failed and my model training got much slower

**Comment by dimaspratama08** [comment]
update!
apparently there seems to be amp bug in yolo v8.0.132. I reinstalled the 8.0.124 version and it runs smoothly

**Comment by dimaspratama08** [comment]
@glenn-jocher I do have a question but it is out of topic of the issue, i'm trying to run my model on a raster with .tiff image in python environment, can you help me with the code example? i have been struggling to find one
