### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#365]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am using exactly the same dataset (images and annotation + data.yaml) as I have for YOLOv5. With YOLOv5 everything works fine, the model trains and works.
However trying to train YOLOv8 with the same data I trained YOLOv5 with I am getting an error:

```
Image sizes 600 train, 600 val
Using 8 dataloader workers
Logging results to runs/Sagemaker/01-X-600-hyp-default
Starting training for 12 epochs...


      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/3066 [00:00<?, ?it/s]libpng warning: iCCP: known incorrect sRGB profile
  0%|          | 0/3066 [00:06<?, ?it/s]
Error executing job with overrides: ['task=segment', 'mode=train', 'model=yolov8x-seg.pt', 'epochs=12', 'data=data/sagemaker.yaml', 'device=1', 'batch=46', 'imgsz=600', 'project=runs/Sagemaker', 'name=01-X-600-hyp-default', 'plots=True']
Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 56, in cli
    func(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 152, in train
    model.train(**cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 185, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 300, in _do_train
    preds = self.model(batch["img"])
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 178, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 57, in _forward_once
    x = m(x)  # run
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/nn/modules.py", line 365, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

### Environment

Ultralytics YOLOv8.0.5 🚀 Python-3.8.15 torch-1.10.1 CUDA:1 (A100-SXM4-40GB, 40536MiB)

### Minimal Reproducible Example

yolo task=segment mode=train model=yolov8x-seg.pt epochs=12 data=data/test.yaml device=1 batch=46 imgsz=600 project=runs/Test name=test plots=True

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
Changing the image size from 600 to 608 fixed the problem (must be divisible by 32). In YOLOv5 it was done automatically.

**Comment by AyushExel** [comment]
Fixed in https://github.com/ultralytics/ultralytics/pull/398 .to be available in next release
