### ISSUE TITLE
Training from a pretrained weights which trained with yolov8m-rtdetr.yaml when doing detection task will cause problems in CLI way.

### ISSUE THREAD

**Issue by jamjamjon** [ultralytics/ultralytics#3681]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Training from a pretrained weights which trained with yolov8m-rtdetr.yaml when doing detection task will cause problems in CLI way.

### CLI command used: 
`yolo train model=/runs/detect/train/weights/last.pt data=coco128.yaml`

### Problem be like this: 

Traceback (most recent call last):
  File "/home/jamjamjon/miniconda3/envs/xy/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/yolo/cfg/__init__.py", line 407, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/yolo/engine/trainer.py", line 332, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/jamjamjon/miniconda3/envs/xy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/nn/tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/nn/tasks.py", line 212, in loss
    self.criterion = self.init_criterion()
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/nn/tasks.py", line 293, in init_criterion
    return v8DetectionLoss(self)
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/yolo/utils/loss.py", line 117, in __init__
    self.stride = m.stride  # model strides
  File "/home/jamjamjon/miniconda3/envs/xy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'
Sentry is attempting to send 2 pending error messages

### python way works fine
```
from ultralytics import RTDETR

model = RTDETR('/mnt/z/Desktop/runs/detect/train/weights/last.pt')
model.train(data='coco128.yaml')
```

### descriptions
When training from weights which name is not like yolov8s.pt or yolov8s-rtdetr, but best.pt, it will build wrong model architecture. Because it can not guess the model architecture from the weights' name, so it load default YOLO().
And that is a common scenario when we want to train from last weights which name could be related with project name.  

### Solution:
The model architecture build code located at: ultralytics/ultralytics/yolo/cfg/__init__.py, line number: 372, function: entrypoint(debug='')

We can guess model architecture by load .pt weights when model argument passed is endswith pt, code could be like this:
```
entrypoint(debug=''):
    ...

    # Model
    from ultralytics.nn.tasks import torch_safe_load
    model = overrides.pop('model', DEFAULT_CFG.model)
    if model is None:
        model = 'yolov8n.pt'
        LOGGER.warning(f"WARNING ⚠️ 'model' is missing. Using default 'model={model}'.")
    overrides['model'] = model
    if model.endswith('pt'):
        ckpt, _ = torch_safe_load(model)  # load ckpt
        _type = ckpt['train_args']['model']
        if 'rtdetr' in _type.lower():  # guess architecture
            from ultralytics import RTDETR
            model = RTDETR(model)  # no task argument
        elif 'sam' in _type.lower():
            from ultralytics import SAM
            model = SAM(model)
        else:
            from ultralytics import YOLO
            model = YOLO(model, task=task)

    ...

``` 

In this way, it could be more flexiable in CLI way to train.  

### Environment

- Ultralytics YOLOv8.0.132
- WSL2
- python3.10.10

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jamjamjon** [comment]
we can guess model architure by loading pt file (bad way). 
```
if model.endswith('pt'):
    ckpt, _ = torch_safe_load(model)  # load ckpt
    _type = ckpt['train_args']['model']
```

### Another Problem
 Current code does not support resume training when training with yolov8-rtdert.pt (using CLI).  

### Command
`yolo train model=/Desktop/runs/detect/train2/weights/last.pt resume=True`

error like this:
```
Traceback (most recent call last):
  File "/home/jamjamjon/miniconda3/envs/xy/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/yolo/cfg/__init__.py", line 424, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/vit/rtdetr/model.py", line 107, in train
    overrides['resume'] = self.ckpt_path
  File "/mnt/z/Desktop/ultralytics-main/ultralytics/vit/rtdetr/model.py", line 182, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'RTDETR' object has no attribute 'ckpt_path'. See valid attributes below.
```

 ### Solution
 `self.ckpt_path = self.model.pt_path` is missing at:
https://github.com/ultralytics/ultralytics/blob/c55a98ab8e1aac8dea0e9984ff0ab1867a605e49/ultralytics/vit/rtdetr/model.py#L47-L51

**Comment by glenn-jocher** [comment]
@jamjamjon thank you for your suggestion! I understand that you encountered an issue with determining the architecture of the model when using checkpoint files. To address this, I propose the following modifications:

1. For YAML format files, we can leave them as they are.
2. For PT format files, we can add an 'arch' attribute in the default training settings. This attribute will represent the architecture of the PT weights. During training, it will be saved into the weights as `ckpt['train_args']['arch']`.

Here is a summary of the modified code:

- We will handle the 'model' separately for YAML and PT formats.
- For untitled models, the default 'model' will be 'yolov8n.pt' and 'arch' will be assigned as 'yolov8'.
- For YAML format models, we will assign 'model' and 'arch' based on the architecture specified in the filename ('rtdetr', 'sam', etc.).
- For PT format models, we will load the checkpoint and retrieve the architecture from `ckpt['train_args']['arch']`. We will assign 'model' and 'arch' accordingly.

One advantage of this modification is that we no longer need to guess the model architecture when using PT files. However, all pretrained PT weights will need to have their 'arch' attribute modified to `ckpt['train_args']['arch']`.

Also, there seems to be an issue with resuming training when using 'yolov8-rtdert.pt' through the command line interface (CLI). The error message shows that the 'RTDETR' object does not have the attribute 'ckpt_path'. One possible solution is to add the missing line `self.ckpt_path = self.model.pt_path` in the relevant code section.

I hope these changes will address your concerns and improve the functionality of YOLOv8. Please let me know if you have any further questions or feedback.

**Comment by jamjamjon** [comment]
Yes! That's exactly what I mean!  I will continue to use yolov8 and provide feedback on any issues I encounter. In addition, I hope to see higher training results for yolov8 + rtdetr.

**Comment by glenn-jocher** [comment]
@jamjamjon thank you for your feedback and for using YOLOv8! We appreciate your commitment to providing us with any issues you encounter.

Regarding YOLOv8 + RTDETR, we understand your expectations for better training results. We are continuously working to improve the performance of YOLOv8 in combination with RTDETR. Your feedback will greatly assist us in this process.

Please don't hesitate to reach out if you have any further questions or encounter any issues. We value your support and strive to provide the best experience with YOLOv8.

**Comment by Lalit-Dumka** [comment]
File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'


the command used: ` yolo train resume model=D:\Lalit\v1.1_training\train3\weights\last.pt`
I received an error message when attempting to resume training from the command line interface for RT-DETR. @glenn-jocher

**Comment by Lalit-Dumka** [comment]
This workaround worked and the training has resumed:
changing `last.pt` to `rtdetr_last.pt`

**Comment by Y-T-G** [comment]
Should be fixed in latest Ultralytics
