### ISSUE TITLE
yolov8 cannot be trained using multiple gpus

### ISSUE THREAD

**Issue by LuqianRen** [ultralytics/ultralytics#3688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

![Screenshot from 2023-07-12 19-07-51](https://github.com/ultralytics/ultralytics/assets/59761124/301cb3a8-a164-4b67-be2a-6165d607ca06)

### Environment

python3.8
pytorch1.13

### Minimal Reproducible Example

i use the command to train :
command: yolo detect train data=coco8.yaml model=yolov8n.pt epochs=100 imgsz=640 device=0,1
but training has been stuck in the graph position (bug*)
![Screenshot from 2023-07-12 19-07-51](https://github.com/ultralytics/ultralytics/assets/59761124/0f7fe1b9-80f5-4a75-8732-9cdfd407afdc)
i use 'nvidia-smi' to check gpu
![Screenshot from 2023-07-12 19-11-53](https://github.com/ultralytics/ultralytics/assets/59761124/e2daae8e-b165-49fa-aa56-6cf78a38685e)

### Additional

if i only use one gpu, the training is OK. But i want to tarining with 2+ gpus. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@LuqianRen DDP training works correctly for us, we are not able to reproduce any issues. I'd recommend using Docker for DDP to reduce any environment issues:

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by LuqianRen** [comment]
wait 3h, i get this error:
single gpu is ok, but why multi-gpus is not work?
Traceback (most recent call last):
  File "/home/rlq/.config/Ultralytics/DDP/_temp_3b73z7_5140623133103296.py", line 9, in <module>
    trainer.train()
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 222, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1408, in broadcast
    work.wait()
RuntimeError: [Rank 1] Caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, TensorShape=[], Timeout(ms)=10800000) ran for 10800031 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/rlq/.config/Ultralytics/DDP/_temp_3b73z7_5140623133103296.py", line 9, in <module>
    trainer.train()
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 226, in _setup_train
    self.model = DDP(self.model, device_ids=[RANK])
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 655, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/utils.py", line 112, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [Rank 0] Caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLGATHER, TensorShape=[2, 1], Timeout(ms)=10800000) ran for 10800065 milliseconds before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 344282) of binary: /home/rlq/anaconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/rlq/.config/Ultralytics/DDP/_temp_3b73z7_5140623133103296.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-12_22:22:27
  host      : ps-Super-Server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 344283)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-12_22:22:27
  host      : ps-Super-Server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 344282)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/rlq/anaconda3/envs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 407, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 188, in train
    raise e
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 186, in train
    subprocess.run(cmd, check=True)
  File "/home/rlq/anaconda3/envs/yolov8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/rlq/anaconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '34899', '/home/rlq/.config/Ultralytics/DDP/_temp_3b73z7_5140623133103296.py']' returned non-zero exit status 1.

**Comment by LuqianRen** [comment]
I think the problem is with the reasoning backend. 
how can i change the backend from nccl to gloo ?

**Comment by glenn-jocher** [comment]
@LuqianRen thank you for reaching out. In YOLOv8, the default backend for distributed training is NCCL, which is used for communication between GPUs. If you are experiencing issues with NCCL, you can try changing the backend to Gloo.

To change the backend from NCCL to Gloo in YOLOv8, you can modify the code in the `trainer.py` file. Look for the line where the `dist.init_process_group` function is called. There should be an argument named `backend` which is set to `"nccl"`. You can change this argument to `"gloo"` to switch to the Gloo backend.

Please note that the Gloo backend may have different performance characteristics compared to NCCL, so it's recommended to test and compare the performance with your specific setup.

Let me know if you have any further questions or need more assistance.
