### ISSUE TITLE
yolov8x6 model detect task runtime error on python code, but run normally on cli

### ISSUE THREAD

**Issue by lzt9746** [ultralytics/ultralytics#388]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have trained a yolov8x6 model on via cli command, and get best.pt and last.pt model. When I use these two model to run detect and val task on python code:
```python
from ultralytics import YOLO
if __name__ == '__main__':
    model = YOLO("./best.pt", type='v8')
    model.predict(source="D:\\labelimg\\20221128\\img\\", conf=0.45, augment=True, agnostic_nms=True, save=True,
                  iou=0.4, save_txt=True, imgsz=1280)
```
it raises a runtime error:
```
Ultralytics YOLOv8.0.5  Python-3.9.7 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
Fusing layers... 
YOLOv8x6 summary: 350 layers, 97313016 parameters, 0 gradients, 260.8 GFLOPs
Traceback (most recent call last):
  File "D:\python-env\deep_learning\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\yolo\engine\model.py", line 131, in predict
    return predictor() if return_outputs else predictor.predict_cli()
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 220, in predict_cli
    for _ in (self.__call__(source, model, return_outputs)):
  File "D:\python-env\deep_learning\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 180, in __call__
    preds = model(im, augment=self.args.augment, visualize=visualize)
  File "D:\python-env\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\nn\autobackend.py", line 253, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "D:\python-env\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\nn\tasks.py", line 177, in forward
    return self._forward_augment(x)  # augmented inference, None
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\nn\tasks.py", line 187, in _forward_augment
    yi = self._forward_once(xi)[0]  # forward
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\nn\tasks.py", line 57, in _forward_once
    x = m(x)  # run
  File "D:\python-env\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\python-env\deep_learning\lib\site-packages\ultralytics\nn\modules.py", line 365, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 30 but got size 29 for tensor number 1 in the list.
python-BaseException
```
I make a breakpoint on the code  
https://github.com/ultralytics/ultralytics/blob/583eac0e8040f0bc8ef4d7a7976f8f7e1cf5a771/ultralytics/nn/tasks.py#L39-L62
and I found this error maybe caused by the 13th "Concat" layer 
![1673835218051_BEF3D3C8-3AD6-4b36-8E20-DC5BD405859C](https://user-images.githubusercontent.com/39548168/212585017-576c0bc8-71c3-4160-ad05-4cb398653db4.png)

but when I run detect task by cli command, it goes normally
```
(deep_learning) PS D:\deep_learning\yolov5> yolo mode=predict model=d:\deep_learning\yolov5\best.pt source=d:\labelimg\20221128\img\ imgsz=1280
Ultralytics YOLOv8.0.5  Python-3.9.7 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
Fusing layers... 
YOLOv8x6 summary: 350 layers, 97313016 parameters, 0 gradients, 260.8 GFLOPs
image 1/370 D:\labelimg\20221128\img\166865178386998.7_50294810.png: 960x1280 1 , 1 , 1 , 1 , 391.0ms
image 2/370 D:\labelimg\20221128\img\166865178439193.9_26637645.png: 768x1280 1 , 1 , 1 , 1 , 311.1ms
image 3/370 D:\labelimg\20221128\img\166865178488195.4_52764046.png: 768x1280 1 , 1 , 1 , 1 , 1 , 1 , 310.1ms
image 4/370 D:\labelimg\20221128\img\166865178536015.2_96010511.png: 1280x768 1 , 1 , 1 , 1 , 1 , 2 s, 307.3ms
```

### Environment

- Ultralytics YOLOv8.0.5  Python-3.9.7 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
- OS: both windows and ubuntu
-  Python: 3.9.7

### Minimal Reproducible Example

```python
from ultralytics import YOLO
if __name__ == '__main__':
    model = YOLO("./best.pt", type='v8')
    model.predict(source="D:\\labelimg\\20221128\\img\\", conf=0.45, augment=True, agnostic_nms=True, save=True,
                  iou=0.4, save_txt=True, imgsz=1280)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lzt9746** [comment]
Besides, I use yolov8l.pt model to  run detect task on python code, it goes normally,  seems like this bug only happens on yolov8x6.pt model.
```
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("./decorate_yolov8_v20230113_best.pt", type='v8')
    model.predict(source="D:\\labelimg\\20221128\\img\\", conf=0.45, augment=True, agnostic_nms=True, save=True,
                  iou=0.4, save_txt=True, imgsz=1280)
```
```
Ultralytics YOLOv8.0.5  Python-3.9.7 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
Fusing layers... 
YOLOv8l summary: 268 layers, 43626654 parameters, 0 gradients, 164.9 GFLOPs      <-----yolov8l model
image 1/370 D:\labelimg\20221128\img\166865178386998.7_50294810.png: 928x1280 2 s, 1 , 1 , 1 , 517.5ms
image 2/370 D:\labelimg\20221128\img\166865178439193.9_26637645.png: 736x1280 2 s, 2 s, 1 , 428.7ms
image 3/370 D:\labelimg\20221128\img\166865178488195.4_52764046.png: 736x1280 1 , 1 , 1 , 1 , 1 , 1 , 1 , 427.6ms
image 4/370 D:\labelimg\20221128\img\166865178536015.2_96010511.png: 1280x736 1 , 1 , 1 , 1 , 1 , 1 , 423.0ms
image 5/370 D:\labelimg\20221128\img\166865178585751.7_48392264.png: 544x1280 338.0ms
image 6/370 D:\labelimg\20221128\img\166865178645014.0_15510874.png: 832x1280 1 , 1 , 471.0ms
image 7/370 D:\labelimg\20221128\img\166865178751877.3_53337745.png: 832x1280 1 , 1 , 1 , 1 , 1 , 470.0ms
image 8/370 D:\labelimg\20221128\img\166865179034837.2_10420166.png: 864x1280 1 , 1 , 1 , 492.0ms
image 9/370 D:\labelimg\20221128\img\166865179365133.6_65809882.png: 640x1280 2 s, 1 , 5 s, 1 , 374.0ms
image 10/370 D:\labelimg\20221128\img\166865179766819.1_44246143.png: 800x1280 1 , 1 , 1 , 1 , 458.1ms
```

**Comment by lzt9746** [comment]
I run python model like these code,  look like predict main function ,it runs normally
```python
from ultralytics.yolo.utils.checks import check_imgsz
from ultralytics.yolo.v8.detect import DetectionPredictor

if __name__ == '__main__':
    # model = YOLO("./decorate_yolov8_v20230115_best.pt")
    # model.info(verbose=True)
    # model.fuse()
    # model.predict(source="D:\\labelimg\\20221128\\img\\", conf=0.45, augment=True, agnostic_nms=True, save=True,
    #               iou=0.4, save_txt=True, imgsz=1280)
    imgsz = check_imgsz(1280, min_dim=2)
    predictor= DetectionPredictor(overrides={
        "model": "./decorate_yolov8_v20230115_best.pt",
        "conf": 0.45,
        "augment": True,
        "agnostic_nms": True,
        "iou": 0.4,
        "save_txt": True,
        "imgsz": imgsz,
    })
    predictor.predict_cli(source="D:\\labelimg\\20221128\\img\\")
```
![image](https://user-images.githubusercontent.com/39548168/212650376-36c1e88d-c817-4cb4-86a2-a389e48f032c.png)

**Comment by Laughing-q** [comment]
@lzt9746 hi thanks for the reporting. I think I know why but actually we haven't finished training our x6 model, so I got no x6 model to test for now.
It could be a `model.stride` issue, x6 model got stride 64 but I think somehow the stride is 32.

Can you run this again with adding `print(img.shape)`? we can check the shape before the error raised.
```python
from ultralytics import YOLO
if __name__ == '__main__':
    model = YOLO("./best.pt", type='v8')
    model.predict(source="D:\\labelimg\\20221128\\img\\", conf=0.45, augment=True, agnostic_nms=True, save=True,
                  iou=0.4, save_txt=True, imgsz=1280)
```

**Comment by lzt9746** [comment]
> @lzt9746 hi thanks for the reporting. I think I know why but actually we haven't finished our x6 model training, so I got no x6 model to test for now. It could be a `model.stride` issue, x6 model got stride 64 but I think somehow the stride is 32.
> 
> Can you run this again with adding `print(img.shape)`? we can check the shape before the error raised.
> 
> ```python
> from ultralytics import YOLO
> if __name__ == '__main__':
>     model = YOLO("./best.pt", type='v8')
>     model.predict(source="D:\\labelimg\\20221128\\img\\", conf=0.45, augment=True, agnostic_nms=True, save=True,
>                   iou=0.4, save_txt=True, imgsz=1280)
> ```
I debug these two python code, here is difference:
1. Run by ultralytics.YOLO, the image shape is changed into 928x1280 , so after  the yolov8x6 7th Conv layer it will change into shape 29x40,  but after the 9th Conv layer, it will change into shape 15x20, then after the Upsample layer, it will change into 30x40, so they cannot go through the next Concat layer. It's my humble opinion， I don't know if it is right.

![1673865168757_DB848B82-1420-4c3a-A96B-06B7A6BDB7E0](https://user-images.githubusercontent.com/39548168/212657862-2b2a9088-5a2b-4448-8420-6c45bdd7e46c.png)

![image](https://user-images.githubusercontent.com/39548168/212660726-8b93a4d5-0bcc-4b3c-b2e1-f1a15a54cee7.png)

2. Run by ultralytics.yolo.v8.detect.DetectionPredictor ,the image shape is 960x1280.
![1673865233302_28E9D77E-73A7-41cf-A724-3FD17ECF02AC](https://user-images.githubusercontent.com/39548168/212657909-8eda9f5c-b995-45d4-9015-c63792e30c33.png)

![image](https://user-images.githubusercontent.com/39548168/212662575-aa4a7036-b348-4afc-a00e-3069193744f1.png)

**Comment by Laughing-q** [comment]
@lzt9746 ok thanks! so it it model.stride issue. we'll fix it later. :)

**Comment by Laughing-q** [comment]
@lzt9746 I've made a PR to fix it. #407
