### ISSUE TITLE
AttributeError: 'Settings' object has no attribute '_require_nexus'

### ISSUE THREAD

**Issue by FrongTH** [ultralytics/ultralytics#3893]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1148, in init
    try:
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 172, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 145, in __init__
    self._service.start()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 218, in start
    self._launch_server()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 174, in _launch_server
    if self._settings._require_nexus:
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1367, in __getattribute__
    return self.__copy__()
AttributeError: 'Settings' object has no attribute '_require_nexus'

### Environment

ultralytics==8.0.140

Run on kaggle jupyter notebook

### Minimal Reproducible Example

model.train(data='/kaggle/input/my-roboflow-2-seed-counting/seed counting.v1i.yolov8/data.yaml', epochs=50, imgsz=224,batch = -1, patience = 5)

### Additional

2 days ago. Everything is fine but today that error happen
How to fix?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by FrongTH** [comment]
Before this error. wandb is error, so I pip install wandb that error is gone. But got this new error.

**Comment by glenn-jocher** [comment]
@FrongTH thank you for reaching out with this issue and providing context about the error you're experiencing. It's good to hear that the Weights & Biases (wandb) installation issue has been resolved, however, let's focus on the new error.

The error message you're seeing, "AttributeError: 'Settings' object has no attribute '_require_nexus'", arises from the wandb library and is not actually related to YOLOv8. 'wandb' is used for experiment tracking and logging in YOLOv8, and it looks like there's a problem in its configuration or initialization.

It's possible that there may be a discrepancy in your Python Wandb library version and what YOLOv8 expects. That's why we recommend using the same software environment that is used in the YOLOv8 Docker image - it's configured with all the correct versions of the libraries used in our model.

If that does not solve your issue, I would recommend you to raise the issue in Weights & Biases GitHub repo or their community Slack where you might get more specialized help.

**Comment by FrongTH** [comment]
wandb.init(mode="disabled")

**Comment by glenn-jocher** [comment]
@FrongTH hello,

The method you are mentioning, `wandb.init(mode="disabled")`, is a way to disable Weights & Biases (wandb) logging during the execution of your model. This is usually useful in cases where you don't want to track the model's performance using wandb, or when wandb is causing issues that interfere with the model execution.

When you call this method before the running or training of your model, it ensures that wandb will not log any training metrics, generate any run pages, or sync data to the cloud. It essentially turns off all wandb functionalities.

Hope that clarifies the usage of `wandb.init(mode="disabled")`. Let us know if you have any further questions.
