### ISSUE TITLE
Ray Tune trying to log to MLflow even after disabling callback. 

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#4146]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Other

### Bug

I am using Databricks Notebooks. I have the latest versions of ray and ultralytics installed. 
I tried running hyperparameter tuning, but I get the following error during each of the 10 trials, which seems linked to MLflow:

```
2023-08-03 07:04:28,974	ERROR tune_controller.py:911 -- Trial task failed for trial _tune_f33c2_00000
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/_private/worker.py", line 2493, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(InvalidConfigurationError): ray::ImplicitFunc.train() (pid=10079, ip=10.139.64.4, actor_id=e7730c872cc73abd8043b52801000000, repr=_tune)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 375, in train
    raise skipped from exception_cause(skipped)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 349, in entrypoint
    return self._trainable_func(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 666, in _trainable_func
    output = fn()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ultralytics/utils/tuner.py", line 83, in _tune
    model.train(**config)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 269, in _setup_train
    self.run_callbacks('on_pretrain_routine_end')
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 165, in run_callbacks
    callback(self)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ultralytics/utils/callbacks/mlflow.py", line 32, in on_pretrain_routine_end
    experiment = mlflow.get_experiment_by_name(experiment_name)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 1049, in get_experiment_by_name
    return MlflowClient().get_experiment_by_name(name)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/tracking/client.py", line 451, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 220, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 304, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/databricks/python/lib/python3.9/site-packages/mlflow/utils/databricks_utils.py", line 413, in get_databricks_host_creds
    config = provider.get_config()
  File "/databricks/python/lib/python3.9/site-packages/databricks_cli/configure/provider.py", line 134, in get_config
    raise InvalidConfigurationError.for_profile(None)
databricks_cli.utils.InvalidConfigurationError: You haven't configured the CLI yet! Please configure by entering `/local_disk0/.ephemeral_nfs/envs/pythonEnv-4b601a9c-ec76-41fe-b490-2ccfed9ce671/lib/python3.9/site-packages/ray/_private/workers/default_worker.py configure`
```

### Environment

- Ultralytics: 8.0.147
- OS: Linux 5.15.0-1041-azure
- Python: 3.9.5
- Databricks Cluster Runtime: 12.2 ML (GPU)

### Minimal Reproducible Example

```
from ultralytics import YOLO
from ultralytics.utils import SETTINGS
import logging

SETTINGS['mlflow'] = False
logging.warning(f"Updated Settings: {SETTINGS}")


model = YOLO("yolov8n.pt")
result_grid = model.tune(data="coco128.yaml", gpu_per_trial=1)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SilverStarCoder hello,

Thanks for raising this issue. You're correctly trying to disable the MLflow callback by setting SETTINGS['mlflow'] = False, however, this is not currently working as expected.

The issue is that the code still tries to log to MLflow even after disabling it, leading to the observed behavior in your case. We acknowledge this as a bug in YOLOv8, and thank you for bringing it to our attention. 

We'll look into fixing this issue in the code so that MLflow logging respects the off setting to avoid such errors in future. 

Please stay tuned to the repository for updates on this issue. We appreciate your use of the YOLOv8 library and your contribution to improving its functionality.

Have a great day!

**Comment by glenn-jocher** [comment]
@SilverStarCoder I tried to reproduce this but am not able to. After installing ray[tune] and mlflow and running your code, everything works correctly for me, and if I insert a print statement into the mlflow callbacks it is not run.

Can you create a reproducible example cell in a Colab notebook to allow us to run and see the same error you see?

**Comment by glenn-jocher** [comment]
@SilverStarCoder BTW, you can import `settings` (in lowercase) directly from ultralytics as well to simplify your example code:

```python
from ultralytics import YOLO, settings
import logging

settings['mlflow'] = False
logging.warning(f"Updated Settings: {SETTINGS}")


model = YOLO("yolov8n.pt")
result_grid = model.tune(data="coco128.yaml", gpu_per_trial=1)
```

**Comment by mohammadsubhani** [comment]
@SilverStarCoder https://github.com/ultralytics/ultralytics/issues/3817#issuecomment-1669080334

**Comment by glenn-jocher** [comment]
@mohammadsubhani thank you for the provided information and for bringing this bug to our attention. It seems there is an issue in the current release where, even after disabling the MLflow callback by setting `SETTINGS['mlflow'] = False`, the code still tries to log to MLflow. This leads to the error you're experiencing.

This is not the intended behavior and we acknowledge it as a bug in YOLOv8. Our team will be looking into correcting this issue in the code, such that MLflow logging will respect the off setting in future. Your patience during this time is much appreciated.

We will update the status of this issue on this thread once we have a resolution. Your contribution in notifying us about this problem is greatly appreciated and thank you for using the YOLOv8 library.

**Comment by SilverStarCoder** [comment]
> @SilverStarCoder I tried to reproduce this but am not able to. After installing ray[tune] and mlflow and running your code, everything works correctly for me, and if I insert a print statement into the mlflow callbacks it is not run.
> 
> Can you create a reproducible example cell in a Colab notebook to allow us to run and see the same error you see?

Hi @glenn-jocher , sorry for the late reply, and thank you for the feedback. I am using Databricks as my main enterprise environment and cannot switch over to Colab. I have attached a PDF of the notebook that produces the same error: 
[test ray_tune.pdf](https://github.com/ultralytics/ultralytics/files/12300952/test.ray_tune.pdf)

**Comment by glenn-jocher** [comment]
Hello @SilverStarCoder,

Thanks for sharing the PDF. I see how working in Databricks could pose a unique environment, and perhaps this discrepancy could be contributing to the variation in our respective outcomes. We appreciate you taking the time to document your process in such detail, as it is indeed instrumental in helping us track down the source of the issue. It remains our goal to make YOLOv8 work seamlessly across all environments, thus we'll delve into your feedback and work towards resolution of the issue you're encountering.

Again, thank you for your patience as we rectify this issue. We appreciate your contribution to this valuable discussion. I'll revert as soon as we make progress on this matter. Thanks for choosing YOLOv8!

**Comment by Hir98** [comment]
@glenn-jocher  @SilverStarCoder 
I am using colab to train yolov8 on custom dataset. I want to log all parameter and store custome generated yolov8 model weight in mlflow server but i am facing issue.

i only able to store parameter in mflow server not able to store all weight file i have tried many times with this code

can you please help me??

`from mlflow.protos.service_pb2 import PROJECT
import dagshub
import mlflow

# load the configuration file
with open(r"/content/drive/MyDrive/YOLOv8New/params.yaml") as f:
    params = yaml.safe_load(f)


mlflow.end_run()
dagshub.init("mlflow-test", "hiraltalsaniya98", mlflow=True)

# set the tracking uri
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

# start mlflow experiment
with mlflow.start_run(run_name=params['name']):
  # load a pre-trained model
  pre_trained_model = YOLO(params['model_type'])

  # # train
  model = pre_trained_model.train(
            data='/content/drive/MyDrive/YOLOv8New/dataset.yaml',
            imgsz=params['imgsz'],
            batch=params['batch'],
            epochs=params['epochs'],
            optimizer=params['optimizer'],
            lr0=params['lr0'],
            seed=params['seed'],
            pretrained=params['pretrained'])

  # log params with mlflow
  mlflow.log_param('model_type', params['model_type'])
  mlflow.log_param('epochs',params['epochs'])
  mlflow.log_param('optimizer', params['optimizer'])
  mlflow.log_param('learning_rate', params['lr0'])
  mlflow.pytorch.log_model(model, "model")`

**Comment by glenn-jocher** [comment]
Hello @SilverStarCoder, 

Your issue seems to be different from the current one we're addressing here. It's suggested to open a new ticket detailing your specific issue, ensuring you include the exact error message you're encountering. This would greatly enable us to provide more accurate and targeted assistance. Thank you!
