### ISSUE TITLE
Cache on Ram for custom dataset not working since ultralytics version 8.0.108

### ISSUE THREAD

**Issue by Amrendra001** [ultralytics/ultralytics#4176]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Cache on Ram for custom dataset not working. I test all version of ultralytics. It is working in version 8.0.107 and in version 8.0.108 i am getting cache error.
![ultralytics_error](https://github.com/ultralytics/ultralytics/assets/125355927/f4548f1f-7651-41aa-beb2-0594ff91f700)

And for all future versions of ultralytics >= 8.0.109, cache on ram is not working. It is giving the same speed as cache on disk. 

I am training on amazon ec2 Deep Learning Pytorch GPU AMI Instance.

### Environment

Device: Amazon ec2 Deep Learning Pytorch GPU AMI Instance.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Amrendra001 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. RAM caching is working correctly for me, I'm unable to reproduce any issues:


<img width="1362" alt="Screenshot 2023-08-05 at 15 33 17" src="https://github.com/ultralytics/ultralytics/assets/26833433/3f304e57-59d3-4508-bac7-3eb92e7b3c27">


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Amrendra001** [comment]
Can you check if it working or not in ultralytics version 8.0.108

**Comment by glenn-jocher** [comment]
@Amrendra001 the above example uses the very latest version 8.0.148 in Google Colab, and cache RAM is working correctly there.

**Comment by amincheloh** [comment]
It print "Caching images" but still load image from disk while training.

**Comment by amincheloh** [comment]
after epoch 6 I just rename `testdata` directory to `~testdata`

```
train: Scanning /mnt/z/mc-lpr/datasets/testdata/_train/labels... 10 images, 0 backgrounds, 0 corrupt: 100%|██████████| 10/10 [00:00<00:00, 81.84it/s]
train: New cache created: /mnt/z/mc-lpr/datasets/testdata/_train/labels.cache
train: Caching images (0.0GB ram): 100%|██████████| 10/10 [00:00<00:00, 48.55it/s]
val: Scanning /mnt/z/mc-lpr/datasets/testdata/_val/labels... 5 images, 0 backgrounds, 0 corrupt: 100%|██████████| 5/5 [00:00<00:00, 68.40it/s]
val: New cache created: /mnt/z/mc-lpr/datasets/testdata/_val/labels.cache
val: Caching images (0.0GB ram): 100%|██████████| 5/5 [00:00<00:00, 41.64it/s]
Plotting labels to runs/detect/train12/labels.jpg...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 320 train, 320 val
Using 8 dataloader workers
Logging results to runs/detect/train12
Starting training for 9999 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     1/9999     0.377G      5.232      4.909      4.296         18        320: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  3.89it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     2/9999      0.38G      4.529      5.052      4.193         13        320: 100%|██████████| 1/1 [00:00<00:00,  6.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     3/9999      0.38G      5.467      4.767      4.539         20        320: 100%|██████████| 1/1 [00:00<00:00,  7.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  5.26it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     4/9999     0.377G      5.311      4.704      4.229         21        320: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.61it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     5/9999      0.38G      5.473      4.911      4.248         21        320: 100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     6/9999     0.401G      5.823      4.881      4.477         30        320: 100%|██████████| 1/1 [00:00<00:00,  3.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@26.490] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000125.jpg'): can't open/read file: check file path/integrity
     7/9999     0.401G      5.013      4.622       4.24         17        320: 100%|██████████| 1/1 [00:00<00:00,  3.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 14.86it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@29.178] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000037.jpg'): can't open/read file: check file path/integrity
     8/9999     0.401G      4.712      4.646      4.441         14        320: 100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 15.58it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@31.944] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000035.jpg'): can't open/read file: check file path/integrity
     9/9999     0.401G      5.219      4.491       4.27         20        320: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 11.80it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@34.604] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000035.jpg'): can't open/read file: check file path/integrity
    10/9999     0.401G      5.585      4.426      4.249         24        320: 100%|██████████| 1/1 [00:00<00:00,  4.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@37.239] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000027.jpg'): can't open/read file: check file path/integrity
    11/9999     0.401G      4.855      4.476      4.282         14        320: 100%|██████████| 1/1 [00:00<00:00,  4.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@39.945] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000030.jpg'): can't open/read file: check file path/integrity
    12/9999     0.401G      4.767      4.686      4.272         12        320: 100%|██████████| 1/1 [00:00<00:00,  4.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 15.76it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@42.480] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000126.jpg'): can't open/read file: check file path/integrity
    13/9999     0.401G      4.548       4.47      4.233         17        320: 100%|██████████| 1/1 [00:00<00:00,  4.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 12.96it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@45.217] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000030.jpg'): can't open/read file: check file path/integrity
    14/9999     0.401G      4.582      4.157      4.413         20        320: 100%|██████████| 1/1 [00:00<00:00,  4.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 19.19it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@48.098] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000125.jpg'): can't open/read file: check file path/integrity
    15/9999     0.401G      4.483      4.417      4.173         18        320: 100%|██████████| 1/1 [00:00<00:00,  4.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 12.82it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@50.933] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000037.jpg'): can't open/read file: check file path/integrity
    16/9999     0.401G      5.046      4.385       4.17         19        320: 100%|██████████| 1/1 [00:00<00:00,  4.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 12.44it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@53.569] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000035.jpg'): can't open/read file: check file path/integrity
    17/9999     0.401G      4.955      4.447      4.091         12        320: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 15.91it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@56.288] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000035.jpg'): can't open/read file: check file path/integrity
    18/9999     0.401G      5.352      4.059       4.15         24        320: 100%|██████████| 1/1 [00:00<00:00,  3.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@58.994] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000027.jpg'): can't open/read file: check file path/integrity
    19/9999     0.401G      5.068      4.005      4.052         20        320: 100%|██████████| 1/1 [00:00<00:00,  7.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 16.40it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@61.654] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000030.jpg'): can't open/read file: check file path/integrity
    20/9999     0.401G       4.86      3.429      4.066         18        320: 100%|██████████| 1/1 [00:00<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@64.270] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000126.jpg'): can't open/read file: check file path/integrity
    21/9999     0.401G      4.503      3.607      4.019         20        320: 100%|██████████| 1/1 [00:00<00:00,  6.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s][ WARN:0@67.071] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000030.jpg'): can't open/read file: check file path/integrity
    22/9999     0.401G      4.472      3.471      3.944         16        320: 100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 16.23it/s]
                   all          5          5          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s]
[ WARN:0@69.994] global loadsave.cpp:244 findDecoder imread_('/mnt/z/mc-lpr/datasets/testdata/_train/images/000125.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/home/amin/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 446, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 196, in train
    self._do_train(world_size)
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 333, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/data/base.py", line 240, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/data/base.py", line 246, in get_image_and_label
    label['img'], label['ori_shape'], label['resized_shape'] = self.load_image(index)
  File "/home/amin/.local/lib/python3.10/site-packages/ultralytics/data/base.py", line 153, in load_image
    raise FileNotFoundError(f'Image Not Found {f}')
FileNotFoundError: Image Not Found /mnt/z/mc-lpr/datasets/testdata/_train/images/000125.jpg
```
