### ISSUE TITLE
Benchmark not working for TensorRT

### ISSUE THREAD

**Issue by kuldeepaher01** [ultralytics/ultralytics#4433]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation, Export, Other

### Bug

`TensorRT: input "images" with shape(1, 3, 1280, 1280) DataType.FLOAT
TensorRT: output "output0" with shape(1, 5, 33600) DataType.FLOAT
TensorRT: building FP32 engine as /home/user9/runs/detect/train10/weights/best.engine
[08/17/2023-20:49:18] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +32, now: CPU 3533, GPU 1910 (MiB)
[08/17/2023-20:49:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +34, now: CPU 3533, GPU 1944 (MiB)
[08/17/2023-20:49:18] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[08/17/2023-20:49:53] [TRT] [I] Some tactics do not have sufficient workspace memory to run. Increasing workspace size will enable more tactics, please check verbose output for requested sizes.
[08/17/2023-20:50:23] [TRT] [I] Detected 1 inputs and 3 output network tensors.
[08/17/2023-20:50:23] [TRT] [I] Total Host Persistent Memory: 105184
[08/17/2023-20:50:23] [TRT] [I] Total Device Persistent Memory: 5636096
[08/17/2023-20:50:23] [TRT] [I] Total Scratch Memory: 4194304
[08/17/2023-20:50:23] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 0 MiB
[08/17/2023-20:50:23] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 21.6743ms to assign 6 blocks to 134 nodes requiring 140902400 bytes.
[08/17/2023-20:50:23] [TRT] [I] Total Activation Memory: 140902400
[08/17/2023-20:50:23] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +34, now: CPU 3546, GPU 2044 (MiB)
[08/17/2023-20:50:23] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[08/17/2023-20:50:23] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[08/17/2023-20:50:23] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
TensorRT: export success ✅ 71.5s, saved as '/home/user9/runs/detect/train10/weights/best.engine' (61.5 MB)

Export complete (71.6s)
Results saved to /home/user9/runs/detect/train10/weights
Predict:         yolo predict task=detect model=/home/user9/runs/detect/train10/weights/best.engine imgsz=1280 
Validate:        yolo val task=detect model=/home/user9/runs/detect/train10/weights/best.engine imgsz=1280 data=None 
Visualize:       https://netron.app
Loading /home/user9/runs/detect/train10/weights/best.engine for TensorRT inference...
[08/17/2023-20:50:24] [TRT] [I] The logger passed into createInferRuntime differs from one already provided for an existing builder, runtime, or refitter. Uses of the global logger, returned by nvinfer1::getLogger(), will return the existing value.

[08/17/2023-20:50:24] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 3545, GPU 1954 (MiB)
[08/17/2023-20:50:24] [TRT] [I] Loaded engine size: 61 MiB
[08/17/2023-20:50:24] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +32, now: CPU 3616, GPU 2048 (MiB)
[08/17/2023-20:50:24] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[08/17/2023-20:50:24] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +32, now: CPU 3555, GPU 2056 (MiB)
[08/17/2023-20:50:24] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
/home/user9/.local/lib/python3.10/site-packages/tensorrt/__init__.py:166: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  bool: np.bool,
Traceback (most recent call last):
  File "/home/user9/.local/lib/python3.10/site-packages/ultralytics/utils/benchmarks.py", line 111, in benchmark
    export.predict(ROOT / 'assets/bus.jpg', imgsz=imgsz, device=device, half=half)
  File "/home/user9/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user9/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 238, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/user9/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 305, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "/home/user9/.local/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 183, in __init__
    dtype = trt.nptype(model.get_binding_dtype(i))
  File "/home/user9/.local/lib/python3.10/site-packages/tensorrt/__init__.py", line 166, in nptype
    bool: np.bool,
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user9/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user9/.local/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 423, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/user9/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user9/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 316, in benchmark
    return benchmark(
  File "/home/user9/.local/lib/python3.10/site-packages/ultralytics/utils/benchmarks.py", line 128, in benchmark
    assert type(e) is AssertionError, f'Benchmark failure for {name}: {e}'
AssertionError: Benchmark failure for TensorRT: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations`
    
    
    I get this error when I try to run benchmark on my model. It always stucks while benchmarking TensorRT.

### Environment

Ultralytics YOLOv8.0.145 
Python-3.10.12 
torch-2.0.1+cu117 CUDA:0 (Tesla V100-PCIE-16GB, 16151MiB)
OS: Ubuntu 20.04

### Minimal Reproducible Example

yolo benchmark model=best.pt data='dataset.yaml' imgsz=1280 half=False device=0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kuldeepaher01 it seems you've run into a compatibility issue between the newer versions of `numpy` and TensorRT's use of the deprecated `np.bool`.

The error messages highlight that:
```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`.
```

To fix this issue, there are a few potential solutions:

1. **Downgrade numpy**: Downgrading numpy to a version before 1.20 might help to temporarily resolve this issue, as the deprecation happened in 1.20:
   ```bash
   pip install numpy==1.19.5
   ```

2. **Modify the problematic code (Recommended)**:
   
   - Find the line in `/home/user9/.local/lib/python3.10/site-packages/tensorrt/__init__.py` that refers to `np.bool`.
   - Replace `np.bool` with `np.bool_` or just `bool` based on the appropriate context (likely `np.bool_`).

    This is a manual change and might be overwritten if you update the package, but it should resolve the immediate error.

3. **Report the issue**: It would be good to inform the maintainers of the NVIDIA TensorRT package about this issue. This might be a new issue or a compatibility problem with the specific environment versions you are using. This will help them rectify the problem in the future updates.

4. **Use a virtual environment**: To avoid conflicts or compatibility issues in the future, it's good to use a Python virtual environment like `venv` or `conda` to manage package dependencies for different projects.

5. **Check your Python version**: If you don't strictly need Python 3.10, consider using a slightly older version such as Python 3.8 or 3.9. Some libraries or frameworks might not yet be fully compatible with the newest Python releases.

To quickly solve your problem and proceed with benchmarking, I'd recommend the second solution, modifying the problematic code. But ensure you also consider the other solutions for the long term.
