### ISSUE TITLE
8.0.7.: show flag in predict method throws error

### ISSUE THREAD

**Issue by MichlF** [ultralytics/ultralytics#448]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Just pip installed the most recent version 8.0.7. and ran the following command that worked with the previous version:

`model_yolo(source="C:\\path_to_some_image\\image.jpg", show=True)`

Which throws this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\miche\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\yolo\engine\model.py", line 58, in __call__
    return self.predict(source, stream, verbose, **kwargs)
  File "C:\Users\miche\anaconda3\envs\yolo_env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\miche\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\yolo\engine\model.py", line 138, in predict
    return predictor(stream=stream, verbose=verbose)
  File "C:\Users\miche\anaconda3\envs\yolo_env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\miche\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 160, in __call__
    return list(chain(*list(self.stream_inference(source, model, verbose))))  # merge list of Result into one
  File "C:\Users\miche\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 197, in stream_inference
    self.show(p)
  File "C:\Users\miche\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 248, in show
    im0 = self.annotator.result()
AttributeError: 'NoneType' object has no attribute 'result'
```

### Environment

OS: Windows
Conda environment with python 3.10.8

### Minimal Reproducible Example

`model_yolo(source="C:\\path_to_some_image\\image.jpg", show=True)`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MichlF we've pushed a fix for this issue in #452. Please try this by git cloning main and let us know if it works. It will be part of 8.0.8 scheduled to be deployed tomorrow.

```python
# Git clone install 
!git clone https://github.com/ultralytics/ultralytics
%pip install -qe ultralytics
```
