### ISSUE TITLE
train with spicify GPU

### ISSUE THREAD

**Issue by Dachui66** [ultralytics/ultralytics#4508]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

- train with cmd:    yolo detect train data=coco128.yaml model=yolov8n.yaml epochs=100 imgsz=640 --device=2
- The error is as follows: 
Traceback (most recent call last):
  File "/home/zengfanyong/.config/Ultralytics/DDP/_temp_pe42xt8m140608702550368.py", line 9, in <module>
    trainer.train()
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 193, in train
    self._do_train(world_size)
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 295, in _do_train
    self._setup_train(world_size)
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 260, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/Data2/zengfy/projects/ultralytics/ultralytics/models/yolo/detect/train.py", line 52, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "/Data2/zengfy/projects/ultralytics/ultralytics/data/build.py", line 98, in build_dataloader
    sampler = None if rank == -1 else distributed.DistributedSampler(dataset, shuffle=shuffle)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/utils/data/distributed.py", line 67, in __init__
    num_replicas = dist.get_world_size()
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 867, in get_world_size
    return _get_group_size(group)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 325, in _get_group_size
    default_pg = _get_default_group()
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Traceback (most recent call last):
  File "/home/zengfanyong/.config/Ultralytics/DDP/_temp_pe42xt8m140608702550368.py", line 9, in <module>
    trainer.train()
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 193, in train
    self._do_train(world_size)
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 295, in _do_train
    self._setup_train(world_size)
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 260, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/Data2/zengfy/projects/ultralytics/ultralytics/models/yolo/detect/train.py", line 52, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "/Data2/zengfy/projects/ultralytics/ultralytics/data/build.py", line 98, in build_dataloader
    sampler = None if rank == -1 else distributed.DistributedSampler(dataset, shuffle=shuffle)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/utils/data/distributed.py", line 67, in __init__
    num_replicas = dist.get_world_size()
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 867, in get_world_size
    return _get_group_size(group)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 325, in _get_group_size
    default_pg = _get_default_group()
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
DVCLive is detected and auto logging is enabled (can be disabled in the /home/zengfanyong/.config/Ultralytics/settings.yaml with `dvc: false`).
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /Data2/zengfy/projects/datasets/coco128/labels/train2017.cache... 128 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
Traceback (most recent call last):
  File "/home/zengfanyong/.config/Ultralytics/DDP/_temp_pe42xt8m140608702550368.py", line 9, in <module>
    trainer.train()
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 193, in train
    self._do_train(world_size)
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 295, in _do_train
    self._setup_train(world_size)
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 260, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/Data2/zengfy/projects/ultralytics/ultralytics/models/yolo/detect/train.py", line 52, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "/Data2/zengfy/projects/ultralytics/ultralytics/data/build.py", line 98, in build_dataloader
    sampler = None if rank == -1 else distributed.DistributedSampler(dataset, shuffle=shuffle)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/utils/data/distributed.py", line 67, in __init__
    num_replicas = dist.get_world_size()
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 867, in get_world_size
    return _get_group_size(group)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 325, in _get_group_size
    default_pg = _get_default_group()
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10225) of binary: /Data2/zengfy/anaconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/zengfanyong/.config/Ultralytics/DDP/_temp_pe42xt8m140608702550368.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-23_15:17:41
  host      : desay-Super-Server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 10226)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-08-23_15:17:41
  host      : desay-Super-Server
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 10227)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-23_15:17:41
  host      : desay-Super-Server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10225)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/Data2/zengfy/anaconda3/envs/yolov8/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/Data2/zengfy/projects/ultralytics/ultralytics/cfg/__init__.py", line 432, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 189, in train
    raise e
  File "/Data2/zengfy/projects/ultralytics/ultralytics/engine/trainer.py", line 187, in train
    subprocess.run(cmd, check=True)
  File "/Data2/zengfy/anaconda3/envs/yolov8/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Data2/zengfy/anaconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '3', '--master_port', '48203', '/home/zengfanyong/.config/Ultralytics/DDP/_temp_pe42xt8m140608702550368.py']' returned non-zero exit status 1.

### Environment

- YOLO: Ultralytics YOLOv8.0.160 ð Python-3.9.17 torch-1.12.0+cu113 CUDA:2 (NVIDIA TITAN Xp, 12196MiB)
- OS: ubuntu18.04.5
- Python: 3.9.17

### Minimal Reproducible Example

- train with cmd:    
yolo detect train data=coco128.yaml model=yolov8n.yaml epochs=100 imgsz=640 --device=2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Dachui66 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Your command works correctly for me in our Docker image, I'm unable to reproduce any issues:

<img width="1935" alt="Screenshot 2023-08-23 at 12 04 14" src="https://github.com/ultralytics/ultralytics/assets/26833433/b34b2d72-b0d8-4044-81cf-31a29cc7f431">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
