### ISSUE TITLE
Unable to train classification model: IndexError: Target 24 is out of bounds.

### ISSUE THREAD

**Issue by xumix** [ultralytics/ultralytics#4514]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Yolo fresh installed with pip as described in docs.
Running this command:
`yolo classify train model=yolov8m-cls.pt device=cpu data=~/images batch=1 imgsz=300 cache=false`

Getting this error:
```
engine/trainer: task=classify, mode=train, model=yolov8m-cls.pt, data=/home/tambovtsev/images, epochs=100, patience=50, batch=1, imgsz=300, save=True, save_period=-1, cache=False, device=cpu, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train22
train: /home/tambovtsev/images/train... found 48 images in 16 classes ✅
val: /home/tambovtsev/images/val... found 31 images in 14 classes ✅
test: /home/tambovtsev/images/test... found 35 images in 13 classes ✅
Overriding model.yaml nc=1000 with nc=16

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   2655744  ultralytics.nn.modules.conv.Conv             [384, 768, 3, 2]
  8                  -1  2   7084032  ultralytics.nn.modules.block.C2f             [768, 768, 2, True]
  9                  -1  1   1006096  ultralytics.nn.modules.head.Classify         [768, 16]
YOLOv8m-cls summary: 141 layers, 15792832 parameters, 15792832 gradients
Transferred 228/230 items from pretrained weights
WARNING ⚠️ imgsz=[300] must be multiple of max stride 32, updating to [320]
train: Scanning /home/tambovtsev/images/train... 48 images, 0 corrupt: 100%|██████████| 48/48 [00:00<?, ?it/s]
val: Scanning /home/tambovtsev/images/val... 31 images, 0 corrupt: 100%|██████████| 31/31 [00:00<?, ?it/s]
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 38 weight(decay=0.0), 39 weight(decay=0.0005), 39 bias(decay=0.0)
Image sizes 320 train, 320 val
Using 0 dataloader workers
Logging results to runs/classify/train22
Starting training for 100 epochs...

      Epoch    GPU_mem       loss  Instances       Size
      1/100         0G    0.04295          1        320:   2%|▏         | 1/48 [00:00<00:09,  5.19it/s]
Traceback (most recent call last):
  File "/home/tambovtsev/yolo-pip/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 432, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 193, in train
    self._do_train(world_size)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 351, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 215, in loss
    return self.criterion(preds, batch)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/utils/loss.py", line 390, in __call__
    loss = torch.nn.functional.cross_entropy(preds, batch['cls'], reduction='sum') / 64
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target 24 is out of bounds.
```
If I try using GPU, I get this error:
```
      Epoch    GPU_mem       loss  Instances       Size
      1/100     0.734G    0.04294          1        320:   2%|▏         | 1/48 [00:00<00:11,  4.11it/s]
Traceback (most recent call last):
  File "/home/tambovtsev/yolo-pip/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 432, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 193, in train
    self._do_train(world_size)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 358, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/Loss.cu:240: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
```

### Environment

Ultralytics YOLOv8.0.160 🚀 Python-3.10.12 torch-2.0.1+cu118 CPU (13th Gen Intel Core(TM) i7-13700K)

### Minimal Reproducible Example

`yolo classify train model=yolov8m-cls.pt device=cpu data=~/images batch=1 imgsz=300 cache=false`
Use images in archive to reproduce the issue
[images.tar.gz](https://github.com/ultralytics/ultralytics/files/12418235/images.tar.gz)

**Comment by xumix** [comment]
> @xumix thanks for the bug report! I'll download your dataset and see if I can reproduce this. One issue may be that your dataset has different train and val and test classes, i.e. note this section. In all normal datasets the val and train splits must contain the exact same class counts.
> 
> ```
> train: /home/tambovtsev/images/train... found 48 images in 16 classes ✅
> val: /home/tambovtsev/images/val... found 31 images in 14 classes ✅
> test: /home/tambovtsev/images/test... found 35 images in 13 classes ✅
> ```

I was thinking about that, I'll change my partitioning code to check if that helps. Anyway since there are check marks there I thought this is fine

**Comment by glenn-jocher** [comment]
So I just copied val to train, but I still get the same error. Seems like a bug somewhere. I'll add a TODO and see what's wrong.

```python
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')
model.train(data='/Users/glennjocher/downloads/bad_dataset', batch=8, imgsz=320)
```

```
Ultralytics YOLOv8.0.160 🚀 Python-3.11.2 torch-2.0.1 CPU (Apple M2)
engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=/Users/glennjocher/downloads/bad_dataset, epochs=100, patience=50, batch=8, imgsz=320, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=/Users/glennjocher/PycharmProjects/ultralytics/runs/classify/train19
train: /Users/glennjocher/downloads/bad_dataset/train... found 31 images in 14 classes ✅ 
val: /Users/glennjocher/downloads/bad_dataset/val... found 31 images in 14 classes ✅ 
test: None
Overriding model.yaml nc=1000 with nc=14
                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    348174  ultralytics.nn.modules.head.Classify         [256, 14]                     
YOLOv8n-cls summary: 99 layers, 1456222 parameters, 1456222 gradients, 3.4 GFLOPs
Transferred 156/158 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /Users/glennjocher/PycharmProjects/ultralytics/runs/classify/train19', view at http://localhost:6006/
train: Scanning /Users/glennjocher/downloads/bad_dataset/train... 31 images, 0 corrupt: 100%|██████████| 31/31 [00:00<00:00, 3993.84it/s]
train: New cache created: /Users/glennjocher/downloads/bad_dataset/train.cache
val: Scanning /Users/glennjocher/downloads/bad_dataset/val... 31 images, 0 corrupt: 100%|██████████| 31/31 [00:00<00:00, 10419.38it/s]
val: New cache created: /Users/glennjocher/downloads/bad_dataset/val.cache
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
Image sizes 320 train, 320 val
Using 0 dataloader workers
Logging results to /Users/glennjocher/PycharmProjects/ultralytics/runs/classify/train19
Starting training for 100 epochs...
      Epoch    GPU_mem       loss  Instances       Size
  0%|          | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-77d6b22e1785>", line 4, in <module>
    model.train(data='/Users/glennjocher/downloads/bad_dataset', batch=8, imgsz=320)
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/trainer.py", line 194, in train
    self._do_train(world_size)
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/trainer.py", line 352, in _do_train
    self.loss, self.loss_items = self.model(batch)
                                 ^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/nn/tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/nn/tasks.py", line 215, in loss
    return self.criterion(preds, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/utils/loss.py", line 390, in __call__
    loss = torch.nn.functional.cross_entropy(preds, batch['cls'], reduction='sum') / 64
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Target 18 is out of bounds.
```

**Comment by glenn-jocher** [comment]
Ah I think I see the issue. The dataset scanning introduced in the last PR introduced a bug and the CI didn't pick it up because the CI uses imagenet10 which only has 1 image per class, which won't catch the bug. I'll push a fix soon.

**Comment by glenn-jocher** [comment]
I've also updated the CI datasets imagenet10 and imagenet100 to add 2 extra images in one of the train and val classes so this bug won't repeat in the future.

**Comment by glenn-jocher** [comment]
@xumix you're welcome! I'm glad to hear that it's working for you now. Please don't hesitate to reach out if you encounter any other issues or have additional questions in the future. Happy training with YOLOv8!
