### ISSUE TITLE
tests fail when building in offline environment

### ISSUE THREAD

**Issue by SIR-unit** [ultralytics/ultralytics#4571]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

>> from tests.test_python import test_utils_downloads
>> test_utils_downloads()

Ultralytics YOLOv8.0.161 🚀 Python-3.10.7 torch-1.13.0a0 CPU (Intel Core(TM) i7-10710U 1.10GHz)
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
        4224           0         0.000          0.45        0.5016         (1, 64, 20, 20)         (1, 64, 10, 10)
Traceback (most recent call last):
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/gnu/store/kj6wzba6p192baizq99b489rs8bynpn7-python-3.10.7/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4d081b61d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/mwmc3f333zmy8myard3bz9jikw7pa2vk-python-requests-2.28.1/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/gnu/store/a7bq8f7r803q81kp3z8p8nhyi25d4xav-python-urllib3-1.26.15/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1cqT-cJgANNrhIHCrEufUYhQ4RqiWG_lJ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d081b61d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in foo
  File "/tmp/guix-build-python-ultralytics-8.0.161.drv-0/ultralytics-8.0.161/tests/test_python.py", line 347, in test_utils_downloads
    get_google_drive_file_info('https://drive.google.com/file/d/1cqT-cJgANNrhIHCrEufUYhQ4RqiWG_lJ/view?usp=drive_link')
  File "/tmp/guix-build-python-ultralytics-8.0.161.drv-0/ultralytics-8.0.161/ultralytics/utils/downloads.py", line 221, in get_google_drive_file_info
    response = session.get(drive_url, stream=True)
  File "/gnu/store/mwmc3f333zmy8myard3bz9jikw7pa2vk-python-requests-2.28.1/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/gnu/store/mwmc3f333zmy8myard3bz9jikw7pa2vk-python-requests-2.28.1/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/gnu/store/mwmc3f333zmy8myard3bz9jikw7pa2vk-python-requests-2.28.1/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/gnu/store/mwmc3f333zmy8myard3bz9jikw7pa2vk-python-requests-2.28.1/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1cqT-cJgANNrhIHCrEufUYhQ4RqiWG_lJ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d081b61d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

### Environment

- Ultralytics v 8.0.161 downloaded source from pypi
- packaging for guix

### Minimal Reproducible Example

pytest -v # in an environment with no internet connection

### Additional

With other test, I see you put:
@pytest.mark.skipif(not ONLINE, reason='environment is offline')
as a decorator for test functions that should be disabled in offline builds.  This decorator is not present in tests/test_python.py:test_utils_downloads(), dispite it attempting to access the internet.

Could you add the same decorator to that function?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SIR-unit ah, thank  you for the bug report! Yes please submit a PR to add this is-online decorator to the failing tests. Thank you!

**Comment by SIR-unit** [comment]
I could submit a merge request, but I won't be signing your CLA, so someone else should do it.  Thanks.

**Comment by glenn-jocher** [comment]
Great news 😃! Your original issue may now be resolved ✅ in PR #4565 in commit https://github.com/ultralytics/ultralytics/pull/4565/commits/843c6539cb89d48325a87726cd28f569bbdfb30f.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
