### ISSUE TITLE
Onnx export imgsz not being used

### ISSUE THREAD

**Issue by HannoJacobs** [ultralytics/ultralytics#4652]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

When I try to export my YOLOv8 retrained pytorch model that has been retained with Imgsz=416 the onnx model doesn't seem to use the imgsz parameter and defaults to looking for 640 as the imgsz. The best.pt (imgsz=416) model works if it is used as is but when converted to onnx it doesn't work for inferencing: `model.export(format='onnx', imgsz=(416, 416))`

The error I get is:

```
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading model_saves/load_onnx_model/onnx_model/model.onnx for ONNX Runtime inference...

Traceback (most recent call last):
  File "/home/azureuser/ultralytics-usage-template/misc/load_models_from_databricks.py", line 98, in <module>
    load_onnx_model(model_save_folder, run_ID)
  File "/home/azureuser/ultralytics-usage-template/misc/load_models_from_databricks.py", line 86, in load_onnx_model
    detections = loaded_model.predict(image)
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 255, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 188, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 244, in stream_inference
    preds = self.model(im, augment=self.args.augment, visualize=visualize)
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 323, in forward
    y = self.session.run(self.output_names, {self.session.get_inputs()[0].name: im})
  File "/home/azureuser/ultralytics-usage-template/.venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 640 Expected: 416
 index: 3 Got: 640 Expected: 416
 Please fix either the inputs or the model.
```
 
 I have tried using dynamic=True and that seems to work but then the inferencing appears to be run at 640x640 which is not what I want (I want 416x416). There also seems to be a comment in the onnx export code that states that dynamic=True only works on CPU
 
 ```
##############################
######## Test onnx model #####
image size = 416
dynamic_ = True
##############################


WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading runs/416_bug_test/416_YOLOv8n_best.onnx for ONNX Runtime inference...

0: 640x640 2 persons, 9 vests, 43.5ms
Speed: 3.2ms preprocess, 43.5ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 640)
predictions = tensor([[0.0000e+00, 3.9497e+02, 3.2815e+02, 1.1097e+03, 5.1030e-01, 0.0000e+00],
        [2.4608e+03, 0.0000e+00, 2.7060e+03, 6.7322e+02, 4.8907e-01, 0.0000e+00],
        [2.4079e+03, 1.1443e+03, 2.7060e+03, 1.8192e+03, 4.7171e-01, 1.0000e+00],
        [2.4055e+03, 1.0532e+03, 2.7060e+03, 1.6530e+03, 3.9470e-01, 1.0000e+00],
        [2.5199e+03, 7.2700e+01, 2.7060e+03, 3.8118e+02, 3.7301e-01, 1.0000e+00],
        [2.4442e+03, 1.2192e+03, 2.7060e+03, 1.7208e+03, 3.6067e-01, 1.0000e+00],
        [2.4408e+03, 1.1446e+03, 2.7060e+03, 1.5988e+03, 3.5549e-01, 1.0000e+00],
        [6.3858e+02, 1.9437e+03, 1.0354e+03, 2.4599e+03, 2.8484e-01, 1.0000e+00],
        [2.1839e+03, 1.0454e+03, 2.6260e+03, 1.7365e+03, 2.7097e-01, 1.0000e+00],
        [2.4417e+03, 1.2638e+03, 2.7060e+03, 1.8634e+03, 2.6720e-01, 1.0000e+00],
        [2.3357e+03, 1.1406e+03, 2.7060e+03, 1.8956e+03, 2.6720e-01, 1.0000e+00]])
```
 
 # The code to reproduce
I am working with python3.10
```
from ultralytics import YOLO
import cv2

def test_onnx_model():
    onnx_path   = f"runs/416_bug_test/416_YOLOv8n_best.onnx"
    loaded_model = YOLO(onnx_path)
    image = cv2.imread("misc/image_2.jpg")
    detections = loaded_model.predict(image)
    predictions = detections[0].boxes.data
    print(f"predictions = {predictions}")

model = YOLO("runs/416_bug_test/416_YOLOv8n_best.pt")

model.export(format='onnx', imgsz=(416, 416), dynamic=True)
test_onnx_model()
"""
This works but the inferencing is done in 640x640
0: 640x640 2 persons, 9 vests, 39.6ms
Speed: 3.5ms preprocess, 39.6ms inference, 0.6ms postprocess per image at shape (1, 3, 640, 640)
predictions = tensor(
[[0.0000e+00, 3.9497e+02, 3.2815e+02, 1.1097e+03, 5.1030e-01, 0.0000e+00],
[2.4608e+03, 0.0000e+00, 2.7060e+03, 6.7322e+02, 4.8907e-01, 0.0000e+00],
[2.4079e+03, 1.1443e+03, 2.7060e+03, 1.8192e+03, 4.7171e-01, 1.0000e+00],
[2.4055e+03, 1.0532e+03, 2.7060e+03, 1.6530e+03, 3.9470e-01, 1.0000e+00],
"""

model.export(format='onnx', imgsz=(416, 416), dynamic=False)
test_onnx_model()
"""
Above line error when inferencing:
index: 2 Got: 640 Expected: 416
index: 3 Got: 640 Expected: 416
Please fix either the inputs or the model.
"""
```
 
 
 
 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HannoJacobs** [comment]
Have you tried to run my code to reproduce the error with success?
My packages are the following:
```
alembic==1.11.3
azure-core==1.29.3
azure-storage-blob==12.17.0
black==23.7.0
blinker==1.6.2
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
cloudpickle==2.2.1
coloredlogs==15.0.1
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
databricks-api==0.9.0
databricks-cli==0.17.7
docker==6.1.3
entrypoints==0.4
filelock==3.12.2
Flask==2.3.3
flatbuffers==23.5.26
fonttools==4.42.1
gitdb==4.0.10
GitPython==3.1.32
gunicorn==21.2.0
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.3.2
kiwisolver==1.4.5
Mako==1.2.4
Markdown==3.4.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mlflow==2.6.0
mpmath==1.3.0
mypy-extensions==1.0.0
networkx==3.1
numpy==1.25.2
oauthlib==3.2.2
onnx==1.14.0
onnxruntime==1.15.1
onnxsim==0.4.33
opencv-python==4.8.0.76
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
protobuf==4.24.1
psutil==5.9.5
pyarrow==12.0.1
pycparser==2.21
Pygments==2.16.1
PyJWT==2.8.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
querystring-parser==1.2.4
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
scikit-learn==1.3.0
scipy==1.11.2
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
SQLAlchemy==2.0.20
sqlparse==0.4.4
sympy==1.12
tabulate==0.9.0
threadpoolctl==3.2.0
tomli==2.0.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.66.1
typing_extensions==4.7.1
tzdata==2023.3
ultralytics==8.0.120
urllib3==1.26.16
websocket-client==1.6.2
Werkzeug==2.3.7
zipp==3.16.2
```

**Comment by louisck27** [comment]
i see your package not run on gpu.
my testing device is 3060 12GB
and pls check this out
https://onnxruntime.ai/docs/get-started/with-python.html
![image](https://github.com/ultralytics/ultralytics/assets/140987347/3dadd6a0-e926-4d4d-95d1-af448c1189b1)

**Comment by HannoJacobs** [comment]
I am running on a MacOS CPU version with onnxruntime installed as you can see from my pip freeze command
This is not likely to be the issue

**Comment by Laughing-q** [comment]
@HannoJacobs hi, we use 640 as image size by default, if you are running a exported model then we'll need you to specify the image size.
please try `loaded_model = YOLO(onnx_path, imgsz=416)`.

**Comment by HannoJacobs** [comment]
```
from ultralytics import YOLO
import cv2

def test_onnx_model():
    onnx_path   = f"runs/416_bug_test/416_YOLOv8n_best.onnx"
    loaded_model = YOLO(onnx_path, imgsz=416)
    image = cv2.imread("misc/image_2.jpg")
    detections = loaded_model.predict(image)
    predictions = detections[0].boxes.data
    print(f"predictions = {predictions}")

model = YOLO("runs/416_bug_test/416_YOLOv8n_best.pt")

imgsz_ = 416
dynamic_ = False
model.export(format='onnx', imgsz=(imgsz_, imgsz_), dynamic=dynamic_)
test_onnx_model()
```

gives the error:
```
put: images for the following indices
 index: 2 Got: 640 Expected: 416
 index: 3 Got: 640 Expected: 416
 Please fix either the inputs or the model.
```

**Comment by HannoJacobs** [comment]
```
from ultralytics import YOLO
import cv2

def test_onnx_model():
    onnx_path   = f"runs/416_bug_test/416_YOLOv8n_best.onnx"
    loaded_model = YOLO(onnx_path, imgsz=416)
    image = cv2.imread("misc/image_2.jpg")
    detections = loaded_model.predict(image)
    predictions = detections[0].boxes.data
    print(f"predictions = {predictions}")

model = YOLO("runs/416_bug_test/416_YOLOv8n_best.pt")

imgsz_ = 416
dynamic_ = False
model.export(format='onnx', imgsz=(imgsz_, imgsz_), dynamic=dynamic_)
test_onnx_model()
```

gives the error:
```
(.venv) hannojacobs@macbook-pro onnx_export_tester % python3.10 reproduce_2.py
Ultralytics YOLOv8.0.120 🚀 Python-3.10.13 torch-2.0.1 CPU
YOLOv8n summary (fused): 168 layers, 3006038 parameters, 0 gradients

PyTorch: starting from runs/416_bug_test/416_YOLOv8n_best.pt with input shape (1, 3, 416, 416) BCHW and output shape(s) (1, 6, 3549) (5.9 MB)

ONNX: starting export with onnx 1.14.0 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: export success ✅ 0.4s, saved as runs/416_bug_test/416_YOLOv8n_best.onnx (11.6 MB)

Export complete (0.5s)
Results saved to /Users/hannojacobs/Desktop/onnx_export_tester/runs/416_bug_test
Predict:         yolo predict task=detect model=runs/416_bug_test/416_YOLOv8n_best.onnx imgsz=416 
Validate:        yolo val task=detect model=runs/416_bug_test/416_YOLOv8n_best.onnx imgsz=416 data=./abm-ppe.yaml 
Visualize:       https://netron.app
Traceback (most recent call last):
  File "/Users/hannojacobs/Desktop/onnx_export_tester/reproduce_2.py", line 17, in <module>
    test_onnx_model()
  File "/Users/hannojacobs/Desktop/onnx_export_tester/reproduce_2.py", line 6, in test_onnx_model
    loaded_model = YOLO(onnx_path, imgsz=416)
TypeError: YOLO.__init__() got an unexpected keyword argument 'imgsz'
(.venv) hannojacobs@macbook-pro onnx_export_tester % 
```

**Comment by glenn-jocher** [comment]
@louisck27 from the traceback you've provided, it seems like there's an unexpected argument error when loading the model with the `YOLO()` function from the `ultralytics` package. Specifically, the issue is with the 'imgsz' argument for this function.  

This could be due to a mismatch between the function signature in your installed `ultralytics` package and the one you're attempting to use in your script. In your installed version of `ultralytics`, `YOLO.__init__()` might not have 'imgsz' as a parameter.

In order to fix this, please check the function signature of `YOLO()` in your installed `ultralytics` package. You might need to adjust your usage of the function to match the correct function signature, or update your `ultralytics` package, if a newer version with updated function signatures is available.

**Comment by glenn-jocher** [comment]
@louisck27 I just tested ONNX export and inference at imgsz=320 for example and everything is working correctly:

```python
from ultralytics import YOLO

# Export to ONNX
model = YOLO('yolov8n.pt')
file = model.export(format='onnx', imgsz=320)

# Run ONNX inference
model_onnx = YOLO(file)
results = model_onnx('ultralytics/assets/bus.jpg', imgsz=320)

# Output
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading /Users/glennjocher/PycharmProjects/ultralytics/weights/yolov8n.onnx for ONNX Runtime inference...
image 1/1 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 320x320 3 persons, 1 bus, 12.6ms
Speed: 0.7ms preprocess, 12.6ms inference, 7.2ms postprocess per image at shape (1, 3, 320, 320)
```

**Comment by Laughing-q** [comment]
@HannoJacobs Sorry😂 my bad, just noticed I gived the incorrect example, the arg should be passing to model.predict() api instead of model initialization, please follow the example Glenn showed above, use `model(image, imgsz=416)`. :)

**Comment by HannoJacobs** [comment]
That works! Thanks a lot
```
from ultralytics import YOLO
import cv2

def test_onnx_model():
    # onnx_path   = f"runs/416_bug_test/416_YOLOv8n_best.onnx"
    # onnx_path   = f"runs/416_bug_test/640_YOLOv8n_best.onnx"
    onnx_path   = f"yolov8n.onnx"

    loaded_model = YOLO(onnx_path)
    image = cv2.imread("misc/image_2.jpg")
    detections = loaded_model.predict(image, imgsz=416)
    predictions = detections[0].boxes.data
    print(f"predictions = {predictions}")

# model = YOLO("runs/416_bug_test/416_YOLOv8n_best.pt")
# model = YOLO("runs/416_bug_test/640_YOLOv8n_best.pt")
model = YOLO("yolov8n.pt")


imgsz_ = 416
dynamic_ = False
model.export(format='onnx', imgsz=(imgsz_, imgsz_), dynamic=dynamic_)
test_onnx_model()
```
Output:
```
(.venv) hannojacobs@macbook-pro onnx_export_tester % python3.10 reproduce_2.py
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 6.23M/6.23M [00:01<00:00, 5.01MB/s]
Ultralytics YOLOv8.0.120 🚀 Python-3.10.13 torch-2.0.1 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from yolov8n.pt with input shape (1, 3, 416, 416) BCHW and output shape(s) (1, 84, 3549) (6.2 MB)

ONNX: starting export with onnx 1.14.0 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: export success ✅ 0.5s, saved as yolov8n.onnx (12.1 MB)

Export complete (0.6s)
Results saved to /Users/hannojacobs/Desktop/onnx_export_tester
Predict:         yolo predict task=detect model=yolov8n.onnx imgsz=416 
Validate:        yolo val task=detect model=yolov8n.onnx imgsz=416 data=coco.yaml 
Visualize:       https://netron.app
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading yolov8n.onnx for ONNX Runtime inference...

0: 416x416 3 persons, 8 cats, 1 tie, 20.5ms
Speed: 3.9ms preprocess, 20.5ms inference, 6.6ms postprocess per image at shape (1, 3, 416, 416)
predictions = tensor([[5.7766e+01, 9.5975e+02, 7.6841e+02, 1.8197e+03, 9.0149e-01, 1.5000e+01],
        [2.0032e+03, 1.9000e+03, 2.6593e+03, 2.6322e+03, 8.2598e-01, 1.5000e+01],
        [1.2739e+03, 1.8504e+03, 1.7923e+03, 2.6948e+03, 7.9507e-01, 0.0000e+00],
        [9.2409e+02, 9.8710e+02, 1.7835e+03, 1.8152e+03, 7.8329e-01, 0.0000e+00],
        [4.9781e+01, 8.3678e+01, 7.8006e+02, 9.5341e+02, 7.4843e-01, 1.5000e+01],
        [5.7660e+01, 1.8352e+03, 9.2016e+02, 2.6958e+03, 6.7538e-01, 1.5000e+01],
        [1.5368e+03, 2.3111e+03, 1.6390e+03, 2.6846e+03, 5.7666e-01, 2.7000e+01],
        [9.4940e+02, 9.6289e+01, 1.7894e+03, 9.5779e+02, 5.3987e-01, 1.5000e+01],
        [1.9817e+03, 8.7615e+01, 2.6552e+03, 9.5953e+02, 4.6007e-01, 1.5000e+01],
        [2.0115e+03, 1.0597e+02, 2.5492e+03, 6.1296e+02, 4.2089e-01, 1.5000e+01],
        [1.7940e+03, 9.7173e+02, 2.5312e+03, 1.7985e+03, 4.0604e-01, 0.0000e+00],
        [1.7951e+03, 9.6283e+02, 2.5258e+03, 1.7700e+03, 3.8442e-01, 1.5000e+01]])
```

**Comment by HannoJacobs** [comment]
Do you have any way to get rid of the warnings though?
```
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading yolov8n.onnx for ONNX Runtime inference...
```

**Comment by Laughing-q** [comment]
@HannoJacobs 
```python
YOLO(onnx_path, task='detect')
```

**Comment by HannoJacobs** [comment]
Perfect! Thanks
I will just make sure it works in my full system as suggested and then I will close the issue

**Comment by HannoJacobs** [comment]
It all works, thanks a lot!

**Comment by glenn-jocher** [comment]
@HannoJacobs that's great to hear! I'm glad we could help resolve the issue. Don't hesitate to reach out if you have any more questions or concerns. Happy coding with YOLOv8!

**Comment by HannoJacobs** [comment]
Thanks a lot @glenn-jocher! You have been very humble and helpful

**Comment by glenn-jocher** [comment]
@HannoJacobs you're welcome! I'm glad to hear that you found the assistance provided to be valuable. If you have any more questions or need further help, don't hesitate to reach out. Happy coding with YOLOv8!
