### ISSUE TITLE
Tuning the hyperparameters with rayTune and without rayTune

### ISSUE THREAD

**Issue by DP1701** [ultralytics/ultralytics#4673]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello all,

I am currently trying to carry out a hyperparameter tuning. I have a question about the difference between hyperparameter tuning with rayTune and without, or which is better according to experience. 

Furthermore, I currently have the problem that the use of rayTune does not work for me (rayTune is installed via pip). Without rayTune it works perfectly.

For this, once the code:

```
from ultralytics import YOLO

# Define a YOLO model (segmentation task)
model = YOLO("yolov8m-seg.pt")

# Run Ray Tune on the model (not working)
result_grid = model.tune(data='data.yaml', use_ray=True)

# Works
result_grid = model.tune(data='data.yaml', use_ray=False)
```

And the error output:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ray[tune] in /Users/arbeit/.local/lib/python3.9/site-packages (2.6.3)
Requirement already satisfied: filelock in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (3.12.3)
Requirement already satisfied: click>=7.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (8.1.7)
Requirement already satisfied: frozenlist in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.4.0)
Requirement already satisfied: aiosignal in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.3.1)
Requirement already satisfied: grpcio>=1.32.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.57.0)
Requirement already satisfied: packaging in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (23.1)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (4.24.2)
Requirement already satisfied: numpy>=1.19.3 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.25.2)
Requirement already satisfied: requests in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from ray[tune]) (2.27.1)
Requirement already satisfied: pyyaml in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (6.0.1)
Requirement already satisfied: jsonschema in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (4.19.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.0.5)
Requirement already satisfied: pyarrow>=6.0.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (13.0.0)
Requirement already satisfied: tensorboardX>=1.9 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (2.6.2.2)
Requirement already satisfied: pandas in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (2.1.0)
Requirement already satisfied: typing-extensions>=4.7.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from filelock->ray[tune]) (4.7.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (0.30.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (2023.7.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (23.1.0)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (0.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/arbeit/.local/lib/python3.9/site-packages (from pandas->ray[tune]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from pandas->ray[tune]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from pandas->ray[tune]) (2023.3)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (2.0.12)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->ray[tune]) (1.16.0)
WARNING ⚠️ search space not provided, using default search space.
2023-08-31 14:45:50,572 INFO worker.py:1621 -- Started a local Ray instance.
2023-08-31 14:45:51,674 INFO tune.py:226 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.
2023-08-31 14:45:51,675 INFO tune.py:666 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
2023-08-31 14:45:51,676 WARNING syncer.py:260 -- You are using remote storage, but you don't have `fsspec` installed. This can lead to inefficient syncing behavior. To avoid this, install fsspec with `pip install fsspec`. Depending on your remote storage provider, consider installing the respective fsspec-package (see https://github.com/fsspec).
╭──────────────────────────────────────────────────────────────╮
│ Configuration for experiment     _tune_2023-08-31_14-45-47   │
├──────────────────────────────────────────────────────────────┤
│ Search algorithm                 BasicVariantGenerator       │
│ Scheduler                        AsyncHyperBandScheduler     │
│ Number of trials                 10                          │
╰──────────────────────────────────────────────────────────────╯

View detailed results here: /Users/arbeit/Desktop/runs/tune/_tune_2023-08-31_14-45-47
To visualize your results with TensorBoard, run: `tensorboard --logdir /Users/arbeit/Desktop/runs/tune/_tune_2023-08-31_14-45-47`

Traceback (most recent call last):
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/tune.py", line 1107, in run
    runner.step()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 286, in step
    if not self._actor_manager.next(timeout=0.1):
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 191, in next
    self._try_start_actors()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 361, in _try_start_actors
    actor = remote_actor_cls.remote(**kwargs)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/actor.py", line 645, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 385, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/actor.py", line 848, in _remote
    worker.function_actor_manager.export_actor_class(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/_private/function_manager.py", line 531, in export_actor_class
    check_oversized_function(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/_private/utils.py", line 759, in check_oversized_function
    raise ValueError(error)
ValueError: The actor ImplicitFunc is too large (209 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arbeit/Desktop/hyperparameter_evolution.py", line 13, in <module>
    result_grid = model.tune(data='/Users/arbeit/Desktop/YOLO/data.yaml', use_ray=True)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ultralytics/engine/model.py", line 360, in tune
    return run_ray_tune(self, max_samples=iterations, *args, **kwargs)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ultralytics/utils/tuner.py", line 130, in run_ray_tune
    tuner.fit()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/tuner.py", line 347, in fit
    return self._local_tuner.fit()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 588, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 703, in _fit_internal
    analysis = run(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/tune.py", line 1114, in run
    runner.cleanup()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/trial_runner.py", line 1143, in cleanup
    self._cleanup_trials()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 424, in _cleanup_trials
    self._schedule_trial_stop(trial)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 951, in _schedule_trial_stop
    self._remove_actor(tracked_actor=tracked_actor)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 443, in _remove_actor
    stop_future = self._actor_manager.schedule_actor_task(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 725, in schedule_actor_task
    raise ValueError(
ValueError: Tracked actor is not managed by this event manager: <TrackedActor 72748407703875685746928206745338375549>
```

**Comment by OgunSerifOnargan** [comment]
I have the same issue

**Comment by glenn-jocher** [comment]
@OgunSerifOnargan thank you for bringing this to our attention. In order to assist you effectively, could you please provide more details about the issue you're facing with YOLOv8? This would include the nature of the issue, any error messages you received, steps to reproduce the issue, etc. The more specific you are, the more smoothly we can assist in troubleshooting the issue. Thanks!

**Comment by DP1701** [comment]
@glenn-jocher i think @OgunSerifOnargan means the same error that I also get. I have already described it in the first post. Could you read it through once?

**Comment by glenn-jocher** [comment]
@DP1701 hello,

Thanks for bringing up your issue, and I understand how this can be frustrating for you. I have re-read the description of your issue in the opening post. It appears you're having trouble with a complex sequence of events.

With your description, I can see that you have followed the steps accurately, but the issue persists. Let me try to explain: I believe the issue might be linked to the structure of your data relative to the way YOLOv8 has been configured.

YOL0v8 is unique in the way it handles annotations and processes images. I encourage you to review your annotation files again to make sure they match the YOLOv8 format. Also, verify that your images and their corresponding annotations are correctly structured in the folders as this could be crucial in solving the issue.

Let's be sure to verify each stage meticulously, ensuring each aspect of the workflow aligns with the YOLOv8 guidelines.

I know troubleshooting can be complex, but with these steps, I hope we're on a path to rectify the issue. Thanks for your patience and persistence.

**Comment by DP1701** [comment]
Hi @glenn-jocher,  I can do it. However, I still have two questions:

1. why does it only fail when I use ray_tune? As I said, if ray_tune=False, then it works.

2. I tested the example from the[ yolov8 docs](https://docs.ultralytics.com/integrations/ray-tune/#installation) website earlier . If I use the yolov8m model instead of the yolov8n, then it doesn't work either. The same happens with my own data set.

Code:
```
from ultralytics import YOLO

# Load a YOLOv8n model (Works)
model = YOLO('yolov8n.pt')

# Load a YOLOv8m model  (does not work)
# model = YOLO('yolov8m.pt')

# Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
result_grid = model.tune(data='coco8.yaml', use_ray=True)
```

Error:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ray[tune] in /Users/arbeit/.local/lib/python3.9/site-packages (2.6.3)
Requirement already satisfied: grpcio>=1.32.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.57.0)
Requirement already satisfied: filelock in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (3.12.3)
Requirement already satisfied: frozenlist in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.4.0)
Requirement already satisfied: requests in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from ray[tune]) (2.27.1)
Requirement already satisfied: numpy>=1.19.3 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.25.2)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.0.5)
Requirement already satisfied: pyyaml in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (6.0.1)
Requirement already satisfied: click>=7.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (8.1.7)
Requirement already satisfied: jsonschema in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (4.19.0)
Requirement already satisfied: packaging in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (23.1)
Requirement already satisfied: aiosignal in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (1.3.1)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (4.24.2)
Requirement already satisfied: tensorboardX>=1.9 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (2.6.2.2)
Requirement already satisfied: pyarrow>=6.0.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (13.0.0)
Requirement already satisfied: pandas in /Users/arbeit/.local/lib/python3.9/site-packages (from ray[tune]) (2.1.0)
Requirement already satisfied: typing-extensions>=4.7.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from filelock->ray[tune]) (4.7.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (23.1.0)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (0.10.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/arbeit/.local/lib/python3.9/site-packages (from jsonschema->ray[tune]) (0.30.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from pandas->ray[tune]) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/arbeit/.local/lib/python3.9/site-packages (from pandas->ray[tune]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/arbeit/.local/lib/python3.9/site-packages (from pandas->ray[tune]) (2023.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from requests->ray[tune]) (2021.10.8)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->ray[tune]) (1.16.0)
WARNING ⚠️ search space not provided, using default search space.
2023-09-02 08:59:44,149 INFO worker.py:1621 -- Started a local Ray instance.
2023-09-02 08:59:45,230 INFO tune.py:226 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.
2023-09-02 08:59:45,232 INFO tune.py:666 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
2023-09-02 08:59:45,232 WARNING syncer.py:260 -- You are using remote storage, but you don't have `fsspec` installed. This can lead to inefficient syncing behavior. To avoid this, install fsspec with `pip install fsspec`. Depending on your remote storage provider, consider installing the respective fsspec-package (see https://github.com/fsspec).
╭──────────────────────────────────────────────────────────────╮
│ Configuration for experiment     _tune_2023-09-02_08-59-41   │
├──────────────────────────────────────────────────────────────┤
│ Search algorithm                 BasicVariantGenerator       │
│ Scheduler                        AsyncHyperBandScheduler     │
│ Number of trials                 10                          │
╰──────────────────────────────────────────────────────────────╯

View detailed results here: /Users/arbeit/Desktop/runs/tune/_tune_2023-09-02_08-59-41
To visualize your results with TensorBoard, run: `tensorboard --logdir /Users/arbeit/Desktop/runs/tune/_tune_2023-09-02_08-59-41`

Traceback (most recent call last):
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/tune.py", line 1107, in run
    runner.step()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 286, in step
    if not self._actor_manager.next(timeout=0.1):
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 191, in next
    self._try_start_actors()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 361, in _try_start_actors
    actor = remote_actor_cls.remote(**kwargs)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/actor.py", line 645, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 385, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/actor.py", line 848, in _remote
    worker.function_actor_manager.export_actor_class(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/_private/function_manager.py", line 531, in export_actor_class
    check_oversized_function(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/_private/utils.py", line 759, in check_oversized_function
    raise ValueError(error)
ValueError: The actor ImplicitFunc is too large (198 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arbeit/Desktop/test.py", line 7, in <module>
    result_grid = model.tune(data='coco8.yaml', use_ray=True)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ultralytics/engine/model.py", line 360, in tune
    return run_ray_tune(self, max_samples=iterations, *args, **kwargs)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ultralytics/utils/tuner.py", line 130, in run_ray_tune
    tuner.fit()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/tuner.py", line 347, in fit
    return self._local_tuner.fit()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 588, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/impl/tuner_internal.py", line 703, in _fit_internal
    analysis = run(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/tune.py", line 1114, in run
    runner.cleanup()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/trial_runner.py", line 1143, in cleanup
    self._cleanup_trials()
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 424, in _cleanup_trials
    self._schedule_trial_stop(trial)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 951, in _schedule_trial_stop
    self._remove_actor(tracked_actor=tracked_actor)
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/tune/execution/tune_controller.py", line 443, in _remove_actor
    stop_future = self._actor_manager.schedule_actor_task(
  File "/Users/arbeit/.conda/envs/YOLOv8_env_hyp/lib/python3.10/site-packages/ray/air/execution/_internal/actor_manager.py", line 725, in schedule_actor_task
    raise ValueError(
ValueError: Tracked actor is not managed by this event manager: <TrackedActor 296651471695517492423007780754694059685>
```

**Comment by DP1701** [comment]
@glenn-jocher Have you tried the example that I mentioned in the previous post?

**Comment by magicleo** [comment]
still get the error with yolov8.0.173

from ultralytics import YOLO

# Load a YOLOv8n model
model = YOLO('yolov8m.pt')

# Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
result_grid = model.tune(
    data='coco128.yaml',
    use_ray=True,
)
ValueError: The actor ImplicitFunc is too large (198 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.

**Comment by glenn-jocher** [comment]
@magicleo i'm sorry to hear that you're experiencing this issue. It appears you've encountered a limitation with Ray Tune, which has a default size limit for serializing objects. In this case, the YOLOv8 model that you're trying to tune exceeds this size limit, hence the `ValueError`.

Ray Tune already provides a solution for this situation through the use of the `ray.put()` function, which is designed to handle large objects. Basically, you'll have to place your model in the Ray object store before you call the tune function, then you can reference it within the scope of your tuning function.

Though it takes some extra work due to the need to manually manage objects within the Ray store, this should allow you to proceed with hyperparameter tuning. 

Also, in future versions, we hope to find a way to automate this process or increase the size limit to better accommodate larger models like YOLOv8. Thank you for bringing this to our attention!
