### ISSUE TITLE
list.streams detection and tracking on multiple rtsp streams fails.

### ISSUE THREAD

**Issue by AlexanderNevarko** [ultralytics/ultralytics#4804]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, dear ultralytics team!
I've been trying to infer yolov8 on several rtsp streams using the `list.streams` interface, described [predict guide](https://docs.ultralytics.com/modes/predict/#inference-sources). I tried doing it using CLI like this:
`yolo track predict model=yolov8n.pt source=/path/to/list.streams imgsz=1280` 
I get the following error:

```
Ultralytics YOLOv8.0.173 🚀 Python-3.10.0 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24247MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

1/2: rtsp://stream:1... Success ✅ (inf frames of shape 2688x1520 at 25.00 FPS)
2/2: rtsp://stream:2... Success ✅ (inf frames of shape 2688x1520 at 25.00 FPS)

Traceback (most recent call last):
  File "/home/alexander/miniconda3/envs/smlt/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 446, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/model.py", line 238, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 199, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 249, in stream_inference
    im = self.preprocess(im0s)
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 119, in preprocess
    im = np.stack(self.pre_transform(im))
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 145, in pre_transform
    same_shapes = all(x.shape == im[0].shape for x in im)
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 145, in <genexpr>
    same_shapes = all(x.shape == im[0].shape for x in im)
AttributeError: 'NoneType' object has no attribute 'shape'
Aborted (core dumped)
```

Then I tried doing the same in a script:

```
model = YOLO(inf_cfg['model_path'], task='detect')
res_gen = model(source=(save_path / 'list.streams'),
                          stream=True,
                        #   persist=True, 
                          imgsz=1280,
                          device='0',
                          half=True, 
                          classes=[2, 7],
                          vid_stride=25,
                          tracker='botsort.yaml')
for cam_preds in res_gen:
        timestamp = datetime.strftime(datetime.now(), "%H_%M_%S-%Y-%m-%d")
        for cam_name, pred in zip(sorted_cam_names, cam_preds):
            img = pred.orig_img
            plotted = pred.plot()
            .....
```

Regardless the type of task I use `detect` or `track` I get the same error:

```
1/2: rtsp://stream:1... Success ✅ (inf frames of shape 2688x1520 at 25.00 FPS)                                 
2/2: rtsp://stream:2... Success ✅ (inf frames of shape 2688x1520 at 25.00 FPS)                                
                                                                                                                                            
Traceback (most recent call last):                                                                                                          
  File "/home/alexander/samolet/repos/dev_dataset_collection/scripts/test_record.py", line 74, in <module>                                  
    main()                                                                                                                                  
  File "/home/alexander/samolet/repos/dev_dataset_collection/scripts/test_record.py", line 70, in main                                      
    run(cam_cfg, inf_cfg)                                                                                                                   
  File "/home/alexander/samolet/repos/dev_dataset_collection/scripts/test_record.py", line 46, in run                                       
    for cam_preds in res_gen:                                                                                                               
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context        
    response = gen.send(None)                                                                                                               
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 249, in stream_inference   
    im = self.preprocess(im0s)                                                                                                              
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 119, in preprocess         
    im = np.stack(self.pre_transform(im))
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 145, in pre_transform
    same_shapes = all(x.shape == im[0].shape for x in im)
  File "/home/alexander/miniconda3/envs/smlt/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 145, in <genexpr>
    same_shapes = all(x.shape == im[0].shape for x in im)
AttributeError: 'NoneType' object has no attribute 'shape'
```

My list.streams file looks like this:
```
rtsp://stream:1
rtsp://stream:2
```

where I changed real links to `1` and `2` for security reasons.
My rtsp links are valid, and if I use only one of those links in the `list.streams` file, everything works fine for both of them.

Am I doing something wrong, or is it a bug?

System information:
OS: Ubuntu 22.04 LTS
ultralytics==8.0.173
torch==2.0.1
CUDA: 12.2

**Comment by glenn-jocher** [comment]
@AlexanderNevarko hi there,

Thank you for providing such a detailed explanation of the issue. It seems like there might be an issue in handling multiple RTSP streams in the stream_inference function of YOLOv8.

Based on the error, the `AttributeError: 'NoneType' object has no attribute 'shape'` hints that at some point a None object was returned where an image was expected. The function is trying to access the 'shape' attribute which doesn't exist for 'NoneType'. 

Please ensure the RTSP streams are returning images continuously without interruptions (like network latency, stream errors etc) as this could result in 'None' frames which might break the continuity of the inference pipeline.

Next, if possible, please also check the data delivered by each stream to make sure they are in the expected format and accessible by YOLOv8. The problem might possibly be due to some unexpected data types or shapes being processed in the framerate images captured by the stream.

Should these steps not solve the issue, it might indeed be a bug, with a necessary contingency for 'None' frames or unexpected data needed in YOLOv8 code. In that case, let us know so I could look further into the specifics of this function and how it could be adapted to account for these cases.

I hope this guidance gets you in the right direction. Let us know if you need further assistance.

**Comment by AlexanderNevarko** [comment]
@glenn-jocher hello!
Thanks for a quick reply. As I described in my question, I tried to put only a single streaming rtsp link into `list.streams` file.
```
rtsp://stream:1
```
With such setting, everything works well without any other code changes. I still use `list.streams` interface with a single link. It works the same with all other links. 
I also tried setting up `vid_stride` parameter to avoid network waiting issues. My rtsp links produce 25 FPS streams, so I tried `vid_stride = 25` and `vid_stride = 5`. It also works fine with only one link in the file. Produced results and images are valid.
Probably, there is a bug in handling multiple streams...

**Comment by glenn-jocher** [comment]
@AlexanderNevarko thanks for the info! Yes this seems like a bug. I've added a TODO to try to reproduce and work on a fix. Thank you for bringing this to our attention.

**Comment by glenn-jocher** [comment]
@AlexanderNevarko it looks like your streams may be suffering from dropouts as the error message relates to a dropped frame. I would recommend checking your streams and your internet connection.

Also if you are willing to back up your inference rather than require real-time then you can use `stream_buffer=True` which may assist with poor internet connections and dropped frames.

**Comment by tienhoang1994** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/72494827/add907eb-57a3-4993-985a-76af8ef2e739)
hi, @glenn-jocher adding stream_buffer doesn't help. I also meet the same problem with the guy above
