### ISSUE TITLE
File not found but my file is existed in my dir.

### ISSUE THREAD

**Issue by Jasonfengjx** [ultralytics/ultralytics#4873]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Using 64 dataloader workers
Logging results to [1m/home/fjx/yolov820230808/runs/f06_premymodelbcelosshcc1954_agument9_2/exp[0m
Starting training for 2000 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

  0%|          | 0/9 [00:00<?, ?it/s]
  0%|          | 0/9 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    model.train(**transformer_opt(opt))
  File "/home/fjx/yolov820230808/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/home/fjx/yolov820230808/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/fjx/yolov820230808/ultralytics/yolo/engine/trainer.py", line 313, in _do_train
    for i, batch in pbar:
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/fjx/yolov820230808/ultralytics/yolo/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fjx/ENTER/envs/yolov8mo2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fjx/yolov820230808/ultralytics/yolo/data/base.py", line 240, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "/home/fjx/yolov820230808/ultralytics/yolo/data/base.py", line 246, in get_image_and_label
    label['img'], label['ori_shape'], label['resized_shape'] = self.load_image(index)
  File "/home/fjx/yolov820230808/ultralytics/yolo/data/base.py", line 153, in load_image
    raise FileNotFoundError(f'Image Not Found {f}')
FileNotFoundError: Image Not Found /home/fjx/ultralytics-copy/datasets/hcc1954_agument9_2/images/sv_3_3_101569226_101758267_101380186_101663746_3.png

### Environment

1

### Minimal Reproducible Example

when i run my model and use the coco128 dataset, it also give me a bug.

### Additional

1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@Jasonfengjx! Could you provide the `data.yaml` file that was utilized during training? Additionally, please share the training command that was employed.
