### ISSUE TITLE
Multiple training in one script

### ISSUE THREAD

**Issue by Miroun** [ultralytics/ultralytics#4948]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation

### Bug

Hello everyone,

I am currently working on implementing a 5-fold cross-validation manually through the code below. However, I am encountering an issue: after successfully completing the first training iteration, the second one does not initiate, despite there being no changes made between the two iterations. I am having trouble understanding why this is happening.

```
from ultralytics import YOLO
import torch
import os
# print(torch.cuda.device_count())
# Train the model
if __name__ == "__main__":
    base_path = "./datasets/"
    dest_path = ""
    for fold in os.listdir(base_path):
        final_dest_path = os.path.join(dest_path,os.path.basename(fold))
        print(final_dest_path)
        model = YOLO('yolov8s-seg.pt') 
        results = model.train(data=f'{os.path.basename(fold)+".yml"}',device="0",batch=32,epochs=250, imgsz=640,seed=18,patience=50,save_period=50, cache=True,project=f"k{fold}")
```
       
      Example of fold_x.yml :
      
```
path: ./fold_1/
train: train/images
val: val/images
test: test/images

names: 
- car

```

Error given by the terminal :
```

`      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
    152/250      9.04G     0.5353     0.8772     0.4165     0.9522         17        640: 100%|██████████| 11/11 [00:05<00:00,  2.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
                   all         11         11      0.301     0.0909      0.035      0.021      0.301     0.0909      0.035      0.021
Stopping training early as no improvement observed in last 50 epochs. Best results observed at epoch 102, best model saved as best.pt.
To update EarlyStopping(patience=50) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

152 epochs completed in 0.253 hours.
Optimizer stripped from kfold_1\train2\weights\last.pt, 23.8MB
Optimizer stripped from kfold_1\train2\weights\best.pt, 23.8MB

Validating kfold_1\train2\weights\best.pt...
Ultralytics YOLOv8.0.166  Python-3.8.0 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]
                   all         11         11      0.538     0.0909      0.107     0.0897      0.538     0.0909     0.0983     0.0775
Speed: 0.5ms preprocess, 28.8ms inference, 0.0ms loss, 2.4ms postprocess per image
Results saved to kfold_1\train2
fold_2
New https://pypi.org/project/ultralytics/8.0.180 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.166  Python-3.8.0 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
engine\trainer: task=segment, mode=train, model=yolov8s-seg.pt, data=fold_2.yml, epochs=250, patience=50, batch=32, imgsz=640, save=True, save_period=50, cache=True, device=0, workers=8, project=kfold_2, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=18, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=kfold_2\train2
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2770931  ultralytics.nn.modules.head.Segment          [1, 32, 128, [128, 256, 512]] 
YOLOv8s-seg summary: 261 layers, 11790483 parameters, 11790467 gradients, 42.7 GFLOPs

Transferred 411/417 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir kfold_2\train2', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed 
train: Scanning C:\Users\Haroun\Desktop\yolov8\datasets\fold_2\train\labels.cache... 330 images, 0 backgrounds, 0 corrupt: 100%|██████████| 330/330 [00:00<?, ?it/s]
WARNING  Box and segment counts should be equal, but got len(segments) = 329, len(boxes) = 330. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
train: Caching images (0.4GB True): 100%|██████████| 330/330 [00:00<00:00, 923.25it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning C:\Users\Haroun\Desktop\yolov8\datasets\fold_2\val\labels.cache... 11 images, 0 backgrounds, 0 corrupt: 100%|██████████| 11/11 [00:00<?, ?it/s]
val: Caching images (0.0GB True): 100%|██████████| 11/11 [00:00<00:00, 15.13it/s]
Plotting labels to kfold_2\train2\labels.jpg... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_2\train2
Starting training for 250 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/11 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\utils\loss.py", line 232, in __call__
    targets = torch.cat((batch_idx, batch['cls'].view(-1, 1), batch['bboxes']), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 60 but got size 0 for tensor number 1 in the list.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/pseudo/Desktop/yolov8/yolov8Main.py", line 61, in <module>
    results = model.train(data=f'{os.path.basename(fold)+".yml"}',device="0",batch=32,epochs=250, imgsz=640,seed=18,patience=50,save_period=50, cache=True,project=f"k{fold}")
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\model.py", line 341, in train
    self.trainer.train()
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\trainer.py", line 196, in train
    self._do_train(world_size)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\trainer.py", line 350, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\nn\tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\nn\tasks.py", line 215, in loss
    return self.criterion(preds, batch)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\utils\loss.py", line 237, in __call__
    raise TypeError('ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.\n'
TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolov8n-seg.pt data=coco128.yaml'.
Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco128-seg.yaml' as an example.
See https://docs.ultralytics.com/tasks/segment/ for help.
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
from ultralytics import YOLO
from pathlib import Path
import torch
import gc

def train_folds(base_path: Path, dest_path: Path):
    """Train YOLO model with 5-fold cross-validation.

    Args:
        base_path (Path): The path to the base directory containing the dataset folds.
        dest_path (Path): The path to the directory where the results should be saved.

    """
    for fold in base_path.iterdir():
        if fold.is_dir():
            print(f"Starting training for {fold}")
            
            final_dest_path = dest_path / fold.name
            print(f"Results will be saved to {final_dest_path}")
            
            model = YOLO('yolov8s-seg.pt')
            
            fold_yml = f"{fold.name}.yml"
            results = model.train(
                data=fold_yml,
                device="0",
                batch=32,
                epochs=250,
                imgsz=640,
                seed=18,
                patience=50,
                save_period=50,
                cache=True,
                project=f"k{fold.name}"
            )
            
            # Release GPU memory and clear cache
            del model
            torch.cuda.empty_cache()
            gc.collect()

            print(f"Completed training for {fold}")

if __name__ == "__main__":
    base_path = Path("./datasets/")
    dest_path = Path("./results/")
    train_folds(base_path, dest_path)

**Comment by glenn-jocher** [comment]
Based on the logs, I notice that there are no direct errors regarding the initialization of the second training iteration, but there are some things you might want to look into.

1. **Device Issue**: Sometimes, the GPU memory isn't completely cleared after the first training session, which can cause issues when initiating a new session.

2. **Cache Warning**: There is a warning about the box and segment counts not being equal. This should ideally be resolved to maintain consistency across folds.

3. **File Paths**: Make sure that the file paths in the loop are correctly pointing to the dataset directories.

Here is a refactored version of your code with added debugging prints and memory clearing. This may help you identify any issues.

```python
from ultralytics import YOLO
from pathlib import Path
import torch
import gc

def train_folds(base_path: Path, dest_path: Path):
    """Train YOLO model with 5-fold cross-validation.

    Args:
        base_path (Path): The path to the base directory containing the dataset folds.
        dest_path (Path): The path to the directory where the results should be saved.

    """
    for fold in base_path.iterdir():
        if fold.is_dir():
            print(f"Starting training for {fold}")
            
            final_dest_path = dest_path / fold.name
            print(f"Results will be saved to {final_dest_path}")
            
            model = YOLO('yolov8s-seg.pt')
            
            fold_yml = f"{fold.name}.yml"
            results = model.train(
                data=fold_yml,
                device="0",
                batch=32,
                epochs=250,
                imgsz=640,
                seed=18,
                patience=50,
                save_period=50,
                cache=True,
                project=f"k{fold.name}"
            )
            
            # Release GPU memory and clear cache
            del model
            torch.cuda.empty_cache()
            gc.collect()

            print(f"Completed training for {fold}")

if __name__ == "__main__":
    base_path = Path("./datasets/")
    dest_path = Path("./results/")
    train_folds(base_path, dest_path)
```

This revised code should:

1. Properly clear GPU memory after each fold.
2. Use the `pathlib` package for file path manipulations, as per your preferences.

Hope this helps you debug the issue.

**Comment by Miroun** [comment]
Hello, thanks for your help.

It did not go as I wanted.

It still crashed and give the same error as before (although it stops giving me the path error) and I do not get an error when I am using a another dataset.

Okay, I realized that the problems come from the creation of my dataset. I do not understand why is this not working since fold_1 & fold_4 are working but not the other ones.

Can you tell me what I am suppose to see in my files ? Because my yaml do not look different. So I guess the problem comes from the labels generated but it still look the same. Just tell me, I am going to do anything.

```
Traceback (most recent call last):
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\utils\loss.py", line 232, in __call__
    targets = torch.cat((batch_idx, batch['cls'].view(-1, 1), batch['bboxes']), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 53 but got size 0 for tensor number 1 in the list.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/pseudo/Desktop/yolov8/yolov8Main.py", line 134, in <module>
    train_folds(base_path, dest_path)
  File "c:/Users/pseudo/Desktop/yolov8/yolov8Main.py", line 111, in train_folds
    results = model.train(
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\model.py", line 337, in train
    self.trainer.train()
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\nn\tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\nn\tasks.py", line 215, in loss
    return self.criterion(preds, batch)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\utils\loss.py", line 237, in __call__
    raise TypeError('ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.\n'
TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolov8n-seg.pt data=coco128.yaml'.
Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco128-seg.yaml' as an example.
See https://docs.ultralytics.com/tasks/segment/ for help.
PS C:\Users\pseudo\Desktop\yolov8>
```

**Comment by glenn-jocher** [comment]
@Miroun i'm sorry to hear that you're still experiencing issues. 

Judging by the error message you provided, the issue seems to be happening because your dataset is not correctly formatted for the tasks you are trying to perform. Specifically, the issue appears to be with the segmentation dataset formatting.

It's important to note that training requires a specific dataset format, and segmentation tasks require a different format from object detection. The error message suggests that there might be an inconsistency or inaccuracy in the format of your dataset.

Since you've mentioned that some folds are working while others are not, I recommend comparing the working and non-working datasets for any differences. 

Look for differences in the YAML files or the structure of the labels as these are commonly the sources of dataset-related problems. Identify any discrepancies in the way your datasets have been created and verify that all the necessary files exist and are properly formatted for the tasks you're trying to perform.

Remember, identifying and rectifying a small difference in data formatting can resolve the issue. 

Also, ensure you’re using the correct model for the task. As per your error log, you are training a segmentation model. Therefore, confirm that your dataset is ready for a 'segment' task and not a 'detect' task.

I hope these suggestions assist you in pinpointing the source of the problem and resolving it.
