### ISSUE TITLE
Ray tune within ray cluster : Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by DUPASYoann** [ultralytics/ultralytics#4985]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I try to train a model with `model.tune(use_ray=True)` within a ray cluster (with head and one worker) 
But I get this error : 

```logs
2023-09-19 16:50:47,826	ERROR tune_controller.py:911 -- Trial task failed for trial _tune_816b8_00000
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::ImplicitFunc.train() (pid=1766390, ip=10.192.216.123, actor_id=307dc5eb9a555a6501cbe02402000000, repr=_tune)
  File "/opt/conda/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 375, in train
    raise skipped from exception_cause(skipped)
  File "/opt/conda/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 349, in entrypoint
    return self._trainable_func(
  File "/opt/conda/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 666, in _trainable_func
    output = fn()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/tuner.py", line 98, in _tune
    model.train(**config)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 337, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 293, in _do_train
    self._setup_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 258, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/detect/train.py", line 52, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/data/build.py", line 98, in build_dataloader
    sampler = None if rank == -1 else distributed.DistributedSampler(dataset, shuffle=shuffle)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 68, in __init__
    num_replicas = dist.get_world_size()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1196, in get_world_size
    return _get_group_size(group)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 576, in _get_group_size
    default_pg = _get_default_group()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 707, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

### Environment

- Ultralytics YOLOv8.0.181 🚀 Python-3.10.11 torch-2.0.1 CPU (Intel Core(TM) i9-9940X 3.30GHz)
- Docker Image : pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel 
- Python 3.10.11

### Minimal Reproducible Example

```
# Requirements.txt
torch~=2.0.1
torchvision~=0.15.2
tqdm~=4.65.0
pandas~=2.1.0
pyyaml~=6.0.1
scikit-learn~=1.3.0
ultralytics~=8.0.181
codecarbon~=2.3.1
ray[all]~=2.6.3
```

- node 1 with IP Adress 0.0.0.1 and docker image : `pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel` 
```sh
apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
pip install fsspec
pip install -r requirements.txt
ray start --head --node-ip-address=0.0.0.1 --port=6379 -num-cpus=8 --num-gpus=1 --block
```

- node 2 with IP Adress 0.0.0.2 and docker image : `pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel` 
```sh
apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
pip install fsspec
pip install -r requirements.txt
ray start  --address=0.0.0.1:6379 -num-cpus=8 --num-gpus=1  # executed after node 1 is finish

python main.py
```

- main.py
```python
import ray
from ultralytics import YOLO

ray.init(address=0.0.0.1:6379)
model = YOLO('yolov8n.yaml')
model.tune(use_ray=true, data='coco128.yaml', epochs=10, iterations=2)
```
### Additional

- new minimal reproducible exemple
```sh
apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
pip install fsspec
pip install -r requirements.txt
python main2.py
```

main2.py
```python
model = YOLO('yolov8n.yaml')
model.tune(use_ray=true, data='coco128.yaml', epochs=10, iterations=2)
```
_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DUPASYoann** [comment]
I updated the Minimal Reproducible Example.
I tried with new ray version and last ultralytics version.
I got the same error.
I also tried with no ray configuration and I got the same error, seems that i cannot use model.tune with use_ray=true

I will try with ultralytics docker image

**Comment by DUPASYoann** [comment]
I found a way to bypass the bug by manually set the environment variable `WORLD_SIZE`and `RANK` to -1

**Comment by fonzen1** [comment]
> @DUPASYoann it's good to hear that you've found a workaround for your issue by manually setting the `WORLD_SIZE` and `RANK` environment variables to `-1`. This suggests that the error may have been related to the way the distributed environment was initialized or recognized in your Ray setup.
> 
> For anyone else experiencing a similar issue, the `Default process group has not been initialized` error in distributed training usually indicates that the PyTorch distributed backend hasn't been set up correctly before starting the training process. In a well-functioning Ray environment with distributed training, the process group should be initialized automatically.
> 
> If this manual setting solves the problem consistently, it could be a temporary solution. However, it's crucial to understand that this might not utilize distributed computing resources as efficiently as possible, because, by setting the environment variable to `-1`, you are effectively disabling distributed training.
> 
> We'll look deeper into this to see if there's an underlying issue that needs to be addressed in the default setup of our `model.tune` method when using Ray. Meanwhile, I would also recommend continuing to experiment with the Ultralytics Docker image, as that may provide a more controlled environment where all necessary dependencies and configurations are preset for distributed training.
> 
> Thank you for bringing this to our attention, and please keep us updated on any new findings or if you encounter any further issues. Your insights are valuable to the Ultralytics community as we strive to improve the robustness and usability of our models.

Hello, I face the same issue using Databricks for YOLOv8 Ray tune. The model training works fine (model.train()). However, using model.tune() after training the model, I get the following error within the ray cluster: 

```
2024-02-26 10:00:44,436	ERROR tune_controller.py:1374 -- Trial task failed for trial _tune_dbc19_00000
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::ImplicitFunc.train() (pid=8260, ip=10.139.64.5, actor_id=eecdb2894d2b93d20ebb81c101000000, repr=_tune)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/air/_internal/util.py", line 88, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 115, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-47a56af7-d5f6-4fb2-9daf-ce9646596856/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 332, in _trainable_func
    output = fn()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/utils/tuner.py", line 102, in _tune
    results = model_to_train.train(**config)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/engine/model.py", line 644, in train
    self.trainer.train()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 286, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/models/yolo/detect/train.py", line 55, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/data/build.py", line 111, in build_dataloader
    sampler = None if rank == -1 else distributed.DistributedSampler(dataset, shuffle=shuffle)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 68, in __init__
    num_replicas = dist.get_world_size()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1492, in get_world_size
    return _get_group_size(group)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 785, in _get_group_size
    default_pg = _get_default_group()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 940, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

I am running this code before training and ray_tune: 
```
if torch.cuda.is_available():
  print('GPU available')
  device_type =  int(os.environ["LOCAL_RANK"]) 
  print(device_type)
  dist.init_process_group('nccl')
else:
  print('No GPU available - using CPU')
  device_type = "cpu"
  dist.init_process_group('gloo')

```
