### ISSUE TITLE
YOLO Format Image Transformation Issue - How to Resolve?

### ISSUE THREAD

**Issue by Miroun** [ultralytics/ultralytics#5083]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am facing an error due to the generation of my data in the YOLO format. One image in the dataset gives me this error. :
```
Ultralytics YOLOv8.0.183  Python-3.8.0 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
engine\trainer: task=segment, mode=train, model=YOLOv8m-seg.pt, data=fold_2.yml, epochs=300, patience=50, batch=2, imgsz=640, save=True, save_period=50, cache=False, device=0, workers=8, project=fold_2, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=18, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=fold_2\train27
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   5159603  ultralytics.nn.modules.head.Segment          [1, 32, 192, [192, 384, 576]] 
YOLOv8m-seg summary: 331 layers, 27240227 parameters, 27240211 gradients, 110.4 GFLOPs

Transferred 531/537 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir fold_2\train27', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed 
train: Scanning C:\Users\pseudo\Desktop\yolov8\datasets\fold_2\train\labels... 2 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2/2 [00:00<00:00, 122.80it/s]
train: New cache created: C:\Users\pseudo\Desktop\yolov8\datasets\fold_2\train\labels.cache
WARNING  Box and segment counts should be equal, but got len(segments) = 1, len(boxes) = 2. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning C:\Users\pseudo\Desktop\yolov8\datasets\fold_2\val\labels.cache... 11 images, 0 backgrounds, 0 corrupt: 100%|██████████| 11/11 [00:00<?, ?it/s]
Plotting labels to fold_2\train27\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 86 weight(decay=0.0), 97 weight(decay=0.0005), 96 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to fold_2\train27
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\utils\loss.py", line 232, in __call__
    targets = torch.cat((batch_idx, batch['cls'].view(-1, 1), batch['bboxes']), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 0 for tensor number 1 in the list.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/pseudo/Desktop/yolov8/yolov8Main.py", line 59, in <module>
    results = model.train(data="fold_2.yml",device="0",batch=2,epochs=300, imgsz=640,seed=18,patience=50,save_period=50, cache=False,project=f"fold_2")
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\model.py", line 337, in train
    self.trainer.train()
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\trainer.py", line 195, in train
    self._do_train(world_size)
    self.loss, self.loss_items = self.model(batch)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\nn\tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\nn\tasks.py", line 215, in loss
    return self.criterion(preds, batch)
  File "C:\Users\pseudo\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\utils\loss.py", line 237, in __call__
    raise TypeError('ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.\n'
TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolov8n-seg.pt data=coco128.yaml'.
Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco128-seg.yaml' as an example.
See https://docs.ultralytics.com/tasks/segment/ for help.
```

My entire dataset is generated based on black and white masks. There is only one image in the dataset that triggers this error. The dataset originates from 10 images which were augmented using the Albumentations library:

```
def preprocess_mask(mask_input, dest_path, original_file_name):
    if isinstance(mask_input, str):  # Si c'est un chemin de fichier
        mask = cv2.imread(mask_input, 0)  # En niveau de gris
        print("oui")
        print(mask_input)
    else:  # Si c'est un tableau numpy
        mask = mask_input

    h, w = mask.shape[:2]

    # Trouvez les contours initiaux
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Dessinez chaque contour
    for contour in contours:
        normalized_points = []
        for point in contour:
            x, y = point[0]
            # Normalisez les coordonnées du point
            x_norm = x / w
            y_norm = y / h
            normalized_points.extend([x_norm, y_norm])

        # Écrivez ces informations dans un fichier .txt
        with open(os.path.join(dest_path, os.path.splitext(original_file_name)[0] + '.txt'), 'w') as f:
            f.write(f"0 " + " ".join(map(str, normalized_points)) + "\n")
    return normalized_points
```

I use this code in order to convert my black&white masks into YOLO format text files. I also use an another function to see if it was correctly "translated". It seems good.

```
def postprocess_mask(file_path, dest_path, mask_shape, original_file_name):
    # Étape 1: Lire le fichier texte
    with open(file_path, 'r') as file:
        data = file.read()
    
    # Étape 2: Extraire les coordonnées normalisées
    data = data.split()
    # Supprimer l'identifiant de classe '0' au début de la chaîne
    normalized_points = list(map(float, data[1:]))
    
    # Étape 3: Dénormaliser les coordonnées
    h, w = mask_shape
    denormalized_points = [(int(p[0]*w), int(p[1]*h)) for p in zip(normalized_points[::2], normalized_points[1::2])]
    
    # Convertir les points en une structure de contour compatible
    contour = np.array(denormalized_points).reshape((-1,1,2)).astype(np.int32)
    
    # Étape 4: Recréer et dessiner les contours sur une image de masque vide
    mask = np.zeros(mask_shape, dtype=np.uint8)
    cv2.drawContours(mask, [contour], -1, (255), -1)  # Dessiner en blanc sur fond noir
    
    # Sauvegarder l'image de masque
    mask_output = os.path.join(dest_path, os.path.splitext(original_file_name)[0] + '_mask.png')
    cv2.imwrite(mask_output, mask)
```

The only thing I can do is looking in the ultralytics library where the exception was raised but it is a bit difficult so before doing this I wanted to see your vision about it.

The last information I can add is, I tried the "corrupted image" alone with a duplicate of itself (because you know, we can not train a model with only one image with ultralytics) and in this configuration, it works !

Nevertheless, when this corrupted image is accompanied by another one (even if they are of the same size and are generated using the same type of image augmentation), it does not work and results in the aforementioned error.

Do you have any advice ?

**Comment by glenn-jocher** [comment]
@Miroun hello,

Thank you for reaching out with the detailed description of your issue. It's clear that you're facing a problem with the segmentation dataset format when training your YOLOv8 model.

From the error logs, it appears that the model is expecting a segmentation dataset but received a detect-segment mixed dataset. The crucial part of the error message is:

```
WARNING Box and segment counts should be equal, but got len(segments) = 1, len(boxes) = 2.
...
TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
```

This suggests that for at least one image, there are more bounding boxes than segmentation masks, which is not consistent. YOLOv8 segmentation models require each object instance to have both a bounding box and a corresponding segmentation mask.

Given the message and the behavior you've observed, here are some steps to take:

1. **Dataset Consistency:** Make sure each annotated object in your dataset has both a bounding box and a segmentation mask. The count of boxes should match the count of segments for every image.

2. **Preprocessing Verification:** Revisit the code that generates the YOLO format text files from your segmentation masks. Ensure the bounding boxes and masks match on an instance level.

3. **Single-Image Issue:** The fact that it works when you duplicate the "corrupted image" indicates that there may be a one-off error in your preprocessing script or a problem with how you're generating the mask for this particular image. Re-examine the specific case where a single image is being processed and how your script handles images with multiple instances.

4. **Batch Inspections:** Before training, examine the generated `.txt` label files and ensure their format is consistent across all images. Each `.txt` file should contain properly normalized bounding boxes and associated segment data.

5. **Dataset Review:** Manually check a subset of your `.txt` label files, especially for the image that causes trouble, to verify that the format adheres to the expected YOLOv8 segmentation format.

6. **Error Replication:** If the error only occurs with specific images, try to identify what's unique about those images. Check if the preprocessing scripts might be handling them differently or if some image artifacts might be affecting the mask generation.

Remember, your segmentation model requires a perfectly paired "box to mask" relationship for each instance of an object. Any deviation from this can cause the error you're seeing.

If the problem persists after reviewing and correcting your dataset, feel free to reach out with updated information, and we'll be happy to help you further. For more detailed guidance, you can refer to our documentation on segmentation tasks at the Ultralytics Docs.
