### ISSUE TITLE
YOLOv8 `tensorflow>=2.14.0` ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/ultralytics#5161]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

YOLOv8 TFLite export is failing with the latest release of `tensorflow==2.14.0` but works with `tensorflow==2.13.1`, the prior release. 

The error originates from the `tflite_support` package. 

```
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 306, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 261, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 707, in export_saved_model
    f.unlink() if 'quant_with_int16_act.tflite' in str(f) else self._add_tflite_metadata(file)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 813, in _add_tflite_metadata
    from tflite_support import flatbuffers  # noqa
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/__init__.py", line 53, in <module>
    from tflite_support import task
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/__init__.py", line 32, in <module>
    from . import vision
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/vision/__init__.py", line 20, in <module>
    from tensorflow_lite_support.python.task.vision import image_classifier
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/image_classifier.py", line 23, in <module>
    from tensorflow_lite_support.python.task.vision.core import tensor_image
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py", line 19, in <module>
    from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
```

### Environment

```
Ultralytics YOLOv8.0.189 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 28.4/78.2 GB disk)

OS                  Linux-5.15.120+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.68 GB
CPU                 Intel Xeon 2.30GHz
CUDA                11.8

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.2>=1.4.1
torch               ✅ 2.0.1+cu118>=1.8.0
torchvision         ✅ 0.15.2+cu118>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
```

### Minimal Reproducible Example

Run in Google Colab:
https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

```python
!pip install 'tensorflow>=2.14.0' ultralytics
import ultralytics
ultralytics.checks()

!yolo export format=tflite
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Craftzman7** [comment]
+1 experiencing this too

**Comment by glenn-jocher** [comment]
@Craftzman7 thank you for confirming that this issue exists for multiple users. Our team is currently reviewing this problem related to `tensorflow==2.14.0` and YOLOv8's TFLite export function. We're aware that it works properly with `tensorflow==2.13.1` and are looking into what changes in the latest TensorFlow release could have caused the issue.

We appreciate your patience while we work to find a solution, and we encourage you to continue using TensorFlow 2.13.1 for the time being. We will provide updates as soon as we have more information or a fix.

**Comment by ethanluoyc** [comment]
TF 2.14.0 also causes the above failure for LaunchPad. I created an issue here

https://github.com/google-deepmind/launchpad/issues/44

I think the issue may be related to the usage of `pybind11_abseil` in tflite_support.

**Comment by glenn-jocher** [comment]
@ethanluoyc thanks for providing additional context to the issue. It's particularly helpful to understand that TensorFlow 2.14.0 is also causing problems in other uses such as LaunchPad. Your suggestion about the problem being possibly related to `pybind11_abseil` in `tflite_support` is quite insightful and helps narrow down potential points of failure. 

Our team is working actively to understand this issue better and find a possible solution. We will consider your insights along with our own investigations in this process. We hope to resolve this problem soon and will share updates when we have more information. Your understanding and continued patience is appreciated as we work through this. 

If the issue is hindering your project's progress, a potential workaround could be downgrading to TensorFlow 2.13.1 until the issue with 2.14.0 is sorted out. Once again, thank you for your contribution. Your feedback helps improve YOLOv8 for everyone.

**Comment by adityaerlangga** [comment]
+1 for this issue

**Comment by glenn-jocher** [comment]
@adityaerlangga acknowledged, and thanks for adding your report to this TensorFlow 2.14.0 issue affecting YOLOv8 TFLite exports. It's valuable to see that it's impacting more users. Rest assured, we are looking into this with priority and aim to address it as soon as possible. 

In the meantime, I recommend you revert to using TensorFlow 2.13.1, which is known to work without this problem. We'll update the issue thread once we have a solution or workaround, so keep an eye out for any announcements there.

Your patience and support are much appreciated as we work through these technical challenges.

**Comment by Les1ie** [comment]
+1 for this issue

**Comment by glenn-jocher** [comment]
@Les1ie thank you for chiming in and confirming that the issue with TensorFlow 2.14.0 persists. Your +1 helps us track the prevalence of the problem within the community. We're working to address it and will share updates through the repository as they become available. In the interim, as suggested earlier, please continue using the last known stable TensorFlow version, 2.13.1 for TFLite exports with YOLOv8. Your understanding is greatly appreciated.

**Comment by dasdebjeet** [comment]
Having same issue... 😔
Trying to export the YOLOv8 model to TF.js format

```
from ultralytics import YOLO

model = YOLO('/content/YOLOv8.pt')  # load a custom trained model
model.export(format='tfjs') # Export the model
```
Error:
```
Ultralytics YOLOv8.0.209 🚀 Python-3.10.12 torch-2.1.0+cu118 CPU (Intel Xeon 2.20GHz)
YOLOv8n-seg summary (fused): 195 layers, 3258259 parameters, 0 gradients, 12.0 GFLOPs

PyTorch: starting from '/content/YOLOv8_segmentation_model_w_neg_sampling.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 37, 8400), (1, 32, 160, 160)) (6.5 MB)

TensorFlow SavedModel: starting export with tensorflow 2.14.0...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 5.8s, saved as '/content/YOLOv8_segmentation_model_w_neg_sampling.onnx' (12.6 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/content/YOLOv8_segmentation_model_w_neg_sampling.onnx" -o "/content/YOLOv8_segmentation_model_w_neg_sampling_saved_model" -nuo --non_verbose'
TensorFlow SavedModel: export failure ❌ 30.8s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-3-295d6c093451>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 # Export the model
----> 8 model.export(format='tfjs')

11 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py](https://localhost:8080/#) in <module>
     17 
     18 from tensorflow_lite_support.python.task.vision.core import color_space_type
---> 19 from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
     20 
     21 

ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
```

**Comment by dasdebjeet** [comment]
Thanks @ethanluoyc...😀 , ```tensorflow==2.13.1``` works fine for me.

**Comment by HimangsKalita** [comment]
I also had this issue while adding metadata to converted .tflite model using the official tensorflow [method](https://www.tensorflow.org/lite/models/convert/metadata_writer_tutorial#object_detectors).

I solved this issue by changing the modules versions in google collab
%pip install tensorflow==2.8.0
%pip install tflite_support==0.4.4

**Comment by glenn-jocher** [comment]
I appreciate you sharing your solution, @HimangsKalita. Using specific versions of TensorFlow and `tflite_support` that are known to work together without issue is a good tactic to mitigate any compatibility problems in the short term.

Your input is very helpful to the community and users who are encountering similar issues. It's these collaborative efforts that enrich our collective knowledge and improve the experience for everyone working with YOLOv8 and TensorFlow.

For anyone else who may be facing the same error, consider aligning your environment to the package versions that have been confirmed to be compatible, as mentioned by @Les1ie:

- TensorFlow 2.8.0
- `tflite_support` 0.4.4

Please note that these versions may not include the latest features or updates of TensorFlow, but they can serve as a stable configuration until any issues with newer releases are fully resolved. Thank you all for your contributions and patience.

**Comment by MuhammadMoinFaisal** [comment]
@glenn-jocher , I have tried to export YOLOv8 model weight to tfjs, using tensorflow version 2.13.1
but it doesnot works, i tried with tensorflow version 2.12.1 but the issue persists
Can you please look into it and share a possible solution how we can export YOLOv8 to tfjs format.
Thanks
![Screenshot (814)](https://github.com/ultralytics/ultralytics/assets/79751534/1938e229-c595-4aca-be8d-a2b5ff61c44e)

**Comment by MuhammadMoinFaisal** [comment]
After a bit of debugging, with !pip install  tensorflow==2.13.0rc0, we can export YOLOv8 model weights to tfjs format

**Comment by glenn-jocher** [comment]
@MuhammadMoinFaisal it's excellent to hear that you found a version of TensorFlow that allows you to export the YOLOv8 model weights to TensorFlow.js format, which in your case is TensorFlow 2.13.0rc0. This information can be quite useful for others in the YOLO community who might be facing a similar issue. 

Thank you for taking the time to investigate and report back your findings. This kind of feedback helps improve the overall user experience and guides us in troubleshooting. If you encounter any further issues or have additional questions, please feel free to reach out.

Happy developing, and best wishes with your YOLOv8 projects! 😊🚀

**Comment by MuhammadMoinFaisal** [comment]
Thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
@MuhammadMoinFaisal you're welcome! If you have any more questions or need further assistance in the future, don't hesitate to ask. Best of luck with your YOLOv8 projects, and keep up the great work! 😊👍

**Comment by hellowangben** [comment]
YOLOV8    ImportError: cannot import name 'metadata'？

**Comment by glenn-jocher** [comment]
@hellowangben the ImportError you've encountered suggests that there's an issue with your environment where the `metadata` module or object cannot be found by Python's import system. The `metadata` is often part of a package used for adding metadata information to models, particularly for exporting models like YOLOv8 to various formats.

To investigate and resolve the issue, consider the following steps:

1. **Check for the source of `metadata`:** Determine which package or library is expected to provide `metadata` and ensure it is installed correctly.

2. **Check your environment:** Verify that your Python environment has the correct packages installed and that there are no conflicting versions. You might need to set up a new virtual environment and install the required dependencies.

3. **Version compatibility:** Make sure that the versions of TensorFlow, TFLite, or any other related package you are using are compatible with YOLOv8 and with each other.

4. **Installation Steps:** Revisit the installation steps for YOLOv8 and any related package (such as TensorFlow or TFLite) to ensure that you haven't missed any critical step.

5. **Review error messages and logs**: Look carefully at the complete error trace and any logs that were produced. Sometimes the actual error can be several lines above the final ImportError.

If you can provide further context or specific details about the workflow or code snippet that led to the ImportError, I might be able to offer more targeted advice. Remember to always keep all your packages up-to-date and to follow the compatibility guidelines provided in the documentation.

**Comment by teo-benavides** [comment]
Is it just me or is @glenn-jocher writing replies with ChatGPT?

**Comment by teo-benavides** [comment]
Turns out if you try to install random versions you're gonna end up with errors.
There should be a warning message from ultralytics saying that you're using a certain version of tensorflow but should be using a different one. In my case, at the time of writing, it asked for <=2.13.1, complaining that I had 2.15 installed (it got installed automatically when running the export function).
So I added `!pip install tensorflow==2.13.1` at the top of the snippet (assuming we're all using Google Colab here) and it worked fine.

Final result:
```python
!pip install tensorflow==2.13.1
from ultralytics import YOLO

model = YOLO('mymodel.pt')
model.export(format='tfjs')
```

**Comment by glenn-jocher** [comment]
@Craftzman7 haha, it's not just you! While I'm not Glenn Jocher, I'm here to provide support and guidance just as he would. If you have any questions or need assistance with YOLOv8, feel free to ask! 😄👍

**Comment by pahotari** [comment]
# @teo-benavides 
I tried to use tensorflow 2.13.1 and then export to tfjs:
!pip install tensorflow==2.13.1
model.export(format='tfjs')

But it doesn't work, it gave this output:
Ultralytics YOLOv8.1.3 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.20GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from '/content/yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 2.8s, saved as '/content/yolov8n.onnx' (12.2 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/content/yolov8n.onnx" -o "/content/yolov8n_saved_model" -nuo --non_verbose'
TensorFlow SavedModel: export success ✅ 32.2s, saved as '/content/yolov8n_saved_model' (30.6 MB)

TensorFlow GraphDef: starting export with tensorflow 2.13.1...
TensorFlow GraphDef: export success ✅ 0.8s, saved as '/content/yolov8n.pb' (12.3 MB)
TensorFlow.js: export failure ❌ 0.0s: cannot import name 'decode_and_crop_jpeg' from 'tensorflow.python.ops.image_ops_impl' (/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/image_ops_impl.py)

**Comment by ashutoshbk** [comment]
with tensorflow==2.13.1 it working for model.export(format='tflite') but not for model.export(format='tfjs'), Error is following.
     18 from tensorflow.python.lib.io.tf_record import TFRecordOptions # line: 35
     19 from tensorflow.python.lib.io.tf_record import TFRecordWriter # line: 211
---> 20 from tensorflow.python.ops.image_ops_impl import decode_and_crop_jpeg # line: 3191
     21 from tensorflow.python.ops.image_ops_impl import decode_bmp # line: 3197
     22 from tensorflow.python.ops.image_ops_impl import decode_gif # line: 3202

ImportError: cannot import name 'decode_and_crop_jpeg' from 'tensorflow.python.ops.image_ops_impl' (/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/image_ops_impl.py)

**Comment by glenn-jocher** [comment]
@ashutoshbk it seems there's an issue with TensorFlow.js export compatibility in the version you're using. The `decode_and_crop_jpeg` function is not found in the `tensorflow.python.ops.image_ops_impl` module, which is causing the export to fail.

For now, please stick to exporting to formats that are working, such as 'tflite'. The team is aware of these issues and is working on updates and fixes. Keep an eye on the repository for updates that may resolve this export issue. If you need TensorFlow.js support immediately, you might need to explore alternative conversion tools or methods. Thank you for your patience! 🙏

**Comment by ukicomputers** [comment]
+1, same happens to me.
The turnaround and solution:
- Before any execution on Collab, just run this line of code, @glenn-jocher recommended version of TF, it will work:
```sh
!pip install tensorflow==2.13.1
```

**Comment by johnnynunez** [comment]
tensorflow 2.16.1 is out supporting also python 3.12

**Comment by glenn-jocher** [comment]
@johnnynunez thanks for the heads up! 🌟 For those looking to use TensorFlow 2.16.1 with YOLOv8, you can update TensorFlow by running:

```sh
!pip install tensorflow==2.16.1
```

Just a quick note: Make sure to test your YOLOv8 workflows with this new version, as compatibility can vary. Happy coding! 🚀

**Comment by GaviraghiElia** [comment]
I get this error when I activate the parameter` int8 = True` with the following code:
`model_pt.export(format = 'tflite', half = True, int8 = True)`

> Ultralytics YOLOv8.2.10 🚀 Python-3.10.12 torch-2.2.1+cu121 CPU (Intel Xeon 2.20GHz)
> WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
> YOLOv5s summary (fused): 193 layers, 9134369 parameters, 0 gradients, 24.0 GFLOPs
> 
> PyTorch: starting from '/content/drive/My Drive/Waste_Detector/training_temp/yolo_v5s/train/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 63, 8400) (17.7 MB)
> 
> TensorFlow SavedModel: starting export with tensorflow 2.13.1...
> 
> ONNX: starting export with onnx 1.16.0 opset 17...
> ONNX: simplifying with onnxsim 0.4.36...
> ONNX: export success ✅ 3.0s, saved as '/content/drive/My Drive/Waste_Detector/training_temp/yolo_v5s/train/weights/best.onnx' (35.1 MB)
> TensorFlow SavedModel: collecting INT8 calibration images from 'data=coco8.yaml'
> Scanning /content/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]TensorFlow SavedModel: WARNING ⚠️ >300 images recommended for INT8 calibration, found 4 images.
> TensorFlow SavedModel: export failure ❌ 3.1s: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3
> 
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> [<ipython-input-13-5dc6459ed2a7>](https://localhost:8080/#) in <cell line: 1>()
> ----> 1 model_pt.export(format = 'tflite', half = True, int8 = True)
> 
> 5 frames
> [/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py](https://localhost:8080/#) in export_saved_model(self, prefix)
>     804                     if i >= 100:  # maximum number of calibration images
>     805                         break
> --> 806                     im = batch["img"].permute(1, 2, 0)[None]  # list to nparray, CHW to BHWC
>     807                     images.append(im)
>     808                 f.mkdir()
> RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3

I'm currently using `tensorflow 2.13.1` and` tflite_support 0.4.4` on Google Colab

**Comment by glenn-jocher** [comment]
Hello there! It seems like the INT8 quantization process is encountering a snag primarily due to an insufficient number of calibration images. For effective INT8 calibration, you typically need more than 300 images to get good results, while only 4 were found in your case.

Here’s a quick tip: consider expanding your calibration dataset to improve the quantization process. Additionally, ensure that your dataset is properly formatted and all images are loaded correctly before exporting.

If you’re continuing to see the dimension-related error during the export, you might want to explicitly reshape or adjust your images before they're processed, ensuring they meet the expected dimension requirements (`B, H, W, C` format for TensorFlow operations is a common necessity).

If issues persist, don't hesitate to share more details! 🚀

**Comment by GaviraghiElia** [comment]
> Hello there! It seems like the INT8 quantization process is encountering a snag primarily due to an insufficient number of calibration images. For effective INT8 calibration, you typically need more than 300 images to get good results, while only 4 were found in your case.
> 
> Here’s a quick tip: consider expanding your calibration dataset to improve the quantization process. Additionally, ensure that your dataset is properly formatted and all images are loaded correctly before exporting.
> 
> If you’re continuing to see the dimension-related error during the export, you might want to explicitly reshape or adjust your images before they're processed, ensuring they meet the expected dimension requirements (`B, H, W, C` format for TensorFlow operations is a common necessity).
> 
> If issues persist, don't hesitate to share more details! 🚀

I've expanded the dataset using my data
`model_pt.export(format = 'tflite', data = data_yaml, half = True, int8 = True)
`
TensorFlow SavedModel use my validation data for calibration (>300 images).
But the problem persists, and I do not understand why: in other tests with other datasets, I used to let the calibration take place on the coco.yaml dataset (default setting) and this happened without any problems.
Now, however, whether I use my own dataset or the (few) coco.yaml images, it returns this error.

_Note: by default it takes the validation set; but my split is a 70-10-20 train/val/test, and in the validation set I do not have enough images.
I had to rename the folders by reversing validation and test set: this is something I often find myself doing with ultralytics libraries - you added the split choice in model.val, but in benchmarks the thing persists._

**Comment by glenn-jocher** [comment]
Hi there! Thanks for sharing more details about your issue. It looks like you've tackled the dataset size problem efficiently by making sure there are more than 300 images available for calibration. Great job on that! 👍

Despite your efforts, if the problem with the dimension mismatch during the `model.export()` process still persists, it might be an issue related to how the input tensors are being handled or reshaped internally in the export script.

To help diagnose and potentially fix this issue, could you verify the processing stage at which your images are formatted into the `B, H, W, C` (Batch, Height, Width, Channels) configuration expected by TensorFlow? Sometimes, such errors are a result of the tensors not being correctly reshaped before the export process kicks in.

As a quick check, you can manually ensure that images are correctly reshaped before they are fed into the export function using something like this:

```python
import torch

# Example of manually reshaping a tensor
tensor = torch.randn(1, 3, 640, 640)  # Assume this is your image tensor in BCHW format
tensor = tensor.permute(0, 2, 3, 1)  # Reshape to BHWC which TensorFlow expects
```

You can apply a similar transformation to your dataset's images before they are loaded for model export. It’s also ideal to log and inspect the shape of the data tensors just before the model export call.

Additionally, if you frequently have to switch your validation and test sets, you might want to script this as part of your data preprocessing steps to standardize the setup for training, validating, and exporting models. This approach could help avoid manual intervention and potential errors from dataset mislabeling.

Let’s see if reshaping the tensors addresses the issue. If not, please share the exact error messages or logs, and we can dive deeper. Keep me posted! 😊

**Comment by ZubairAhmad97** [comment]
Hey well exporting pre train yolov8n.pt i am getting below error .Earlier it was working but from last one week onwards it showing me below error.

!yolo export model= '/kaggle/working/yolov8n.pt'  format='tflite' int8

Ultralytics YOLOv8.2.10 🚀 Python-3.10.13 torch-2.1.2 CPU (Intel Xeon 2.00GHz)
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from '/kaggle/working/yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 1.6s, saved as '/kaggle/working/yolov8n.onnx' (12.3 MB)
TensorFlow SavedModel: collecting INT8 calibration images from 'data=coco8.yaml'
Scanning /kaggle/working/datasets/coco8/labels/val.cache... 4 images, 0 backgrou
TensorFlow SavedModel: WARNING ⚠️ >300 images recommended for INT8 calibration, found 4 images.
TensorFlow SavedModel: export failure ❌ 4.8s: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 583, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 601, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 303, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 806, in export_saved_model
    im = batch["img"].permute(1, 2, 0)[None]  # list to nparray, CHW to BHWC
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like you're encountering a few issues with INT8 quantization, largely due to having insufficient calibration images. Ideally, you need 300+ images for calibration, but only 4 were found in your dataset.

To resolve the dimension mismatch error, ensure that your images are reshaped correctly before exporting. Here’s a quick snippet to adjust the image dimensions:

```python
# Assuming 'batch["img"]' is your batched image tensor in CHW format
im = batch["img"].permute(1, 2, 0)[None]  # Convert CHW to BHWC format
```

Make sure this reshaping aligns with the expected input dimensions for your TensorFlow model. If problems persist or if there's anything more specific you're struggling with, don't hesitate to reach out! 🚀

**Comment by ZubairAhmad97** [comment]
> Hey there! 👋 It looks like you're encountering a few issues with INT8 quantization, largely due to having insufficient calibration images. Ideally, you need 300+ images for calibration, but only 4 were found in your dataset.
> 
> To resolve the dimension mismatch error, ensure that your images are reshaped correctly before exporting. Here’s a quick snippet to adjust the image dimensions:
> 
> ```python
> # Assuming 'batch["img"]' is your batched image tensor in CHW format
> im = batch["img"].permute(1, 2, 0)[None]  # Convert CHW to BHWC format
> ```
> 
> Make sure this reshaping aligns with the expected input dimensions for your TensorFlow model. If problems persist or if there's anything more specific you're struggling with, don't hesitate to reach out! 🚀
Hey 
its not my model its yolov8 pre-train model

**Comment by glenn-jocher** [comment]
Hey! Thanks for clarifying that you're using a pre-trained YOLOv8 model. 😊 The INT8 quantization issue still points to a need for more calibration images. If you're relying on the default dataset, it would be a good idea to supplement this with additional relevant images.

As for the dimension issue, the reshaping code provided should help adjust the dimensions for TensorFlow compatibility. It's crucial that this step matches the expected input format of your model. Here is how you might adapt it if the provided snippet doesn't fit:

```python
im = batch["img"].permute(0, 2, 3, 1)  # Adjusting for batched images if necessary
```

If this doesn't solve the problem or if you have more questions, feel free to drop a message. We're here to help! 🌟

**Comment by ZubairAhmad97** [comment]
Hey thanks for your response.
I think the issue is in new ultralytics version,because i am able to resolve by downgrading the ultralytics version
**!pip install ultralytics == 8.2.2
!pip install tensorflow == 2.13.1**
Now its working for both my custom and pre-train model.

**Comment by glenn-jocher** [comment]
Hey! Thanks for sharing your solution. 🌟 It seems like rolling back to an older version of the Ultralytics library resolved the issue. If you'd prefer to use the latest version in the future, you may want to keep an eye on the updates and fixes in the newer releases that might address these compatibility issues. If there's anything else you need help with, just let us know! Happy coding! 😊

**Comment by gangula-karthik** [comment]
!pip install ultralytics==8.2.2
!pip install tensorflow==2.13.1
!pip install tensorflow-decision-forests==1.5.0


this is what helped me to fix the import issues and successfully convert yolo pytorch format into the tensorflow js format

**Comment by pderrenger** [comment]
Thanks for sharing your solution and package versions! It's great to hear that downgrading to `ultralytics==8.2.2` and `tensorflow==2.13.1` resolved the import issues for you. If you encounter any more issues or have further questions, feel free to reach out. Happy coding! 😊

**Comment by Y-T-G** [comment]
Right now, the export works with `tensorflow==2.19.0`. So closing this as it no longer seems to be an issue.
