### ISSUE TITLE
The problem of starting a training model

### ISSUE THREAD

**Issue by EkelviNistars** [ultralytics/ultralytics#5173]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I try to start training my own model, I get an error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\toki\PycharmProjects\pythonProject\main.py", line 6, in <module>
    results = model.train(data='faces.yaml', epochs=1000, imgsz=640, batch=26)
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\ultralytics\engine\model.py", line 334, in train
    self.trainer.train()
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\ultralytics\engine\trainer.py", line 195, in train
    self._do_train(world_size)
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\ultralytics\engine\trainer.py", line 293, in _do_train
    self._setup_train(world_size)
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\ultralytics\engine\trainer.py", line 258, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\ultralytics\models\yolo\detect\train.py", line 52, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\ultralytics\data\build.py", line 101, in build_dataloader
    return InfiniteDataLoader(dataset=dataset,
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\ultralytics\data\build.py", line 29, in __init__
    self.iterator = super().__iter__()
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\torch\utils\data\dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\toki\PycharmProjects\pythonProject\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1042, in __init__
    w.start()
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\toki\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

My code looks like this:
`from ultralytics import YOLO

model = YOLO('yolov8s.yaml')

results = model.train(data='faces.yaml', epochs=1000, imgsz=640, batch=26)`

**Comment by EkelviNistars** [comment]
.

**Comment by glenn-jocher** [comment]
@EkelviNistars from the error message, it seems like the issue arises because you're trying to use multiprocessing features in Python, which requires a certain structure in your script where the multiprocessing functionality is only executed when the script is run directly.

Instead of initiating your training directly in the script, you need to make sure that it is wrapped inside a `main` function and is only invoked when your script is being run directly, not being imported. It can be resolved by replacing your current script with this structure:

```python
from ultralytics import YOLO

def main():
    model = YOLO('yolov8s.yaml')
    results = model.train(data='faces.yaml', epochs=1000, imgsz=640, batch=26)

if __name__ == '__main__':
    main()
```

What this does is that it only runs the `main` function when the script is being run directly. When it's imported as a module by some other script, the `main` function will not run. This is a necessary requirement for using multiprocessing in Python. I hope this helps! Let me know how it goes.
