### ISSUE TITLE
TensorRT (engine) dynamic export runs forever when batch > 3

### ISSUE THREAD

**Issue by abionics** [ultralytics/ultralytics#5261]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

TensorRT (engine) export with batch size more than 3 runs forever. In this example I stoped export after 5+ hours:

```bash
(venv) root@root:~$ yolo export model=yolov8s.pt format=engine dynamic=True batch=4
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.184 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients
```

This is an example of successful export on the same server with `batch=2`:

<details>
  <summary>Click to see output</summary>

```bash
(venv) root@root:~$ yolo export model=yolov8s.pt format=engine dynamic=True batch=2
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.184 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients

PyTorch: starting from 'yolov8s.pt' with input shape (2, 3, 640, 640) BCHW and output shape(s) (2, 84, 8400) (21.5 MB)
WARNING ⚠️ invalid check_version(1.14.1, ) requested, please check values.

ONNX: starting export with onnx 1.14.1 opset 17...
ONNX: simplifying with onnxsim 0.4.33...
ONNX: export success ✅ 2.4s, saved as 'yolov8s.onnx' (42.6 MB)

TensorRT: starting export with TensorRT 8.6.1...
[10/06/2023-21:59:04] [TRT] [I] [MemUsageChange] Init CUDA: CPU +518, GPU +0, now: CPU 6745, GPU 2193 (MiB)
[10/06/2023-21:59:10] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1648, GPU +310, now: CPU 8469, GPU 2503 (MiB)
[10/06/2023-21:59:10] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[10/06/2023-21:59:10] [TRT] [I] ----------------------------------------------------------------
[10/06/2023-21:59:10] [TRT] [I] Input filename:   yolov8s.onnx
[10/06/2023-21:59:10] [TRT] [I] ONNX IR version:  0.0.8
[10/06/2023-21:59:10] [TRT] [I] Opset version:    17
[10/06/2023-21:59:10] [TRT] [I] Producer name:    pytorch
[10/06/2023-21:59:10] [TRT] [I] Producer version: 2.1.0
[10/06/2023-21:59:10] [TRT] [I] Domain:           
[10/06/2023-21:59:10] [TRT] [I] Model version:    0
[10/06/2023-21:59:10] [TRT] [I] Doc string:       
[10/06/2023-21:59:10] [TRT] [I] ----------------------------------------------------------------
[10/06/2023-21:59:10] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 84, -1) DataType.FLOAT
TensorRT: building FP32 engine as yolov8s.engine
[10/06/2023-21:59:10] [TRT] [I] Graph optimization time: 0.0210115 seconds.
[10/06/2023-21:59:10] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[10/06/2023-22:01:06] [TRT] [I] Detected 1 inputs and 3 output network tensors.
[10/06/2023-22:01:07] [TRT] [I] Total Host Persistent Memory: 381184
[10/06/2023-22:01:07] [TRT] [I] Total Device Persistent Memory: 0
[10/06/2023-22:01:07] [TRT] [I] Total Scratch Memory: 0
[10/06/2023-22:01:07] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 10 MiB, GPU 261 MiB
[10/06/2023-22:01:07] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 204 steps to complete.
[10/06/2023-22:01:07] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 21.6052ms to assign 12 blocks to 204 nodes requiring 71356416 bytes.
[10/06/2023-22:01:07] [TRT] [I] Total Activation Memory: 71355392
[10/06/2023-22:01:07] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +6, GPU +43, now: CPU 6, GPU 43 (MiB)
TensorRT: export success ✅ 126.4s, saved as 'yolov8s.engine' (45.4 MB)

Export complete (131.1s)
Results saved to /home/root
Predict:         yolo predict task=detect model=yolov8s.engine imgsz=640  
Validate:        yolo val task=detect model=yolov8s.engine imgsz=640 data=coco.yaml  
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export
```

</details>

This bug remains even after removing `dynamic=True`

### Environment

```bash
Ultralytics YOLOv8.0.184 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
Setup complete ✅ (96 CPUs, 62.4 GB RAM, 96.9/495.0 GB disk)

OS                  Linux-5.15.0-83-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.10
Install             git
RAM                 62.39 GB
CPU                 Intel Xeon Gold 6342 2.80GHz
CUDA                12.1

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.0>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
WARNING ⚠️ invalid check_version(5.9.5, ) requested, please check values.
psutil              ✅ 5.9.5
WARNING ⚠️ invalid check_version(9.0.0, ) requested, please check values.
py-cpuinfo          ✅ 9.0.0
```

### Minimal Reproducible Example

```bash
yolo export model=yolov8s.pt format=engine dynamic=True batch=4
```

### Additional

After updating `ultralytics` to the latest version `8.0.194` I got such results:

```bash
(venv) root@root:~$ yolo export model=yolov8s.pt format=engine dynamic=True batch=4
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.194 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients
Traceback (most recent call last):
  File "/home/root/venv/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 446, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 306, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/root/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 212, in __call__
    y = model(im)  # dry runs
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 45, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 62, in predict
    return self._predict_once(x, profile, visualize)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 82, in _predict_once
    x = m(x)  # run
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 187, in forward_split
    y.extend(m(y[-1]) for m in self.m)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 187, in <genexpr>
    y.extend(m(y[-1]) for m in self.m)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 283, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/ultralytics/nn/modules/conv.py", line 42, in forward_fuse
    return self.act(self.conv(x))
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/root/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Invalid argument

(venv) root@root:~$ yolo export model=yolov8s.pt format=engine dynamic=True batch=4
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.194 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
python3.10: tpp.c:83: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
Aborted (core dumped)

(venv) root@root:~$ yolo export model=yolov8s.pt format=engine dynamic=True batch=4
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.194 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
Segmentation fault (core dumped)

(venv) root@root:~$ yolo export model=yolov8s.pt format=engine dynamic=True batch=4
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.194 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
python3.10: pthread_mutex_lock.c:438: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
Aborted (core dumped)

(venv) root@root:~$ yolo export model=yolov8s.pt format=engine dynamic=True batch=4
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.194 🚀 Python-3.10.10 torch-2.1.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81093MiB)
<stucks forever>
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abionics 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. 

Ultralytics YOLO export and inference with TensorRT models using `dynamic` and `batch` works correctly for me, I'm unable to reproduce any issues using your example commands in Google Colab:

https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb
<img width="1915" alt="Screenshot 2023-10-07 at 19 29 23" src="https://github.com/ultralytics/ultralytics/assets/26833433/389613f8-24a9-41fd-a936-48dff09a5d5e">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by abionics** [comment]
I run export inside `pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime` container and it works. Maybe there was a problem with TensorRT setup in my vm

Thank you!

**Comment by glenn-jocher** [comment]
Hello @abionics,

I'm glad to hear that your issue has been resolved! It does sound like it could have been a problem with the TensorRT setup in your original virtual machine. It's a great approach to verify and isolate issues by testing in different environments, as you have done with the `pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime` container. Going forward, if you encounter any further issues with YOLOv8, don't hesitate to reach out. We're here to help!

Happy coding! 😊
