### ISSUE TITLE
Errors while starting a new run from pre-trained weights (TypeError: 'types.SimpleNamespace' object is not iterable)

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#533]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Start a new run, single GPU + `--model=run_name/weights/best.pt`

```
Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/configs/__init__.py", line 209, in entrypoint
    func(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 151, in train
    model.train(**vars(cfg))
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 203, in train
    self.trainer.train()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 181, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 245, in _do_train
    self._setup_train(rank, world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 196, in _setup_train
    self.run_callbacks("on_pretrain_routine_start")
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 160, in run_callbacks
    callback(self)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/utils/callbacks/clearml.py", line 29, in on_pretrain_routine_start
    task.connect(dict(trainer.args), name='General')
TypeError: 'types.SimpleNamespace' object is not iterable
```

### Environment

Ultralytics YOLOv8.0.13 🚀 Python-3.8.15 torch-1.10.1 

### Additional

Current workaround: `pip install ultralytics==8.0.9`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nikbobo** [comment]
It seems to replace `dict(trainer.args)` to `vars(trainer.args)` will be fixed it.

**Comment by Robotatron** [comment]
> It seems to replace `dict(trainer.args)` to `vars(trainer.args)` will be fixed it.

Did you have the same issue?

**Comment by RobbStarkAustria** [comment]
I have the same bug, but the solution mentioned fixed it.

**Comment by Robotatron** [comment]
> It seems to replace `dict(trainer.args)` to `vars(trainer.args)` will be fixed it.

In which python file?

**Comment by RobbStarkAustria** [comment]
There are two files:
ultralytics/yolo/utils/callbacks/clearml.py
ultralytics/yolo/utils/callbacks/comet.py
