### ISSUE TITLE
Error in a simple example

### ISSUE THREAD

**Issue by shersoni610** [ultralytics/ultralytics#570]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I just downloaded yolov8 ( posted 3 hours ago). However, the simple program:

yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg"

gives 

(yol8) $ yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg"
Ultralytics YOLOv8.0.16 🚀 Python-3.8.12 torch-1.13.1 CPU
Traceback (most recent call last):
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 202, in entrypoint
    func(cfg)
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/ultralytics/yolo/v8/detect/predict.py", line 89, in predict
    predictor.predict_cli()
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 163, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 171, in stream_inference
    self.setup_model(model)
  File "/Users/csverma/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 236, in setup_model
    self.model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)
  File "/Users/csverma/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 74, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 322, in attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/Users/Projects/CompVis/YOLO/yolov8/yol8/lib/python3.8/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'omegaconf'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shersoni610 your command works correctly in Colab. Please provide a minimal reproducible example.

https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb
<img width="851" alt="Screenshot 2023-01-22 at 21 13 52" src="https://user-images.githubusercontent.com/26833433/213938108-65f4e0ec-6744-427d-a91b-8ad903cd273f.png">

**Comment by shersoni610** [comment]
Step 1: I created a virtualenv on MAC Ventura;

Step 2:  Under the virtualenv, I issued pip install ultralytics

Step 3:  yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg"


And I got the above error messages.

Thanks

**Comment by shersoni610** [comment]
Few difference that I see from the colab

1.  I have python 3.8.13
2. Torch version is 1.3.1.CPU. ( colab runs on Cuda)

**Comment by mehran66** [comment]
`pip install omegaconf` solved the issue for me!

**Comment by pderrenger** [comment]
@mehran66 great to hear that `pip install omegaconf` solved the issue for you! OmegaConf is a key dependency for YOLOv8, and ensuring it's installed resolves many common problems. If you encounter any more issues or have further questions, feel free to ask. Happy detecting!

**Comment by glenn-jocher** [comment]
That's excellent news, @pderrenger! Glad to hear the issue is resolved. If you need any more assistance, don't hesitate to reach out. Enjoy using YOLOv8! 🚀

**Comment by divanshsinghsaini123** [comment]
@pderrenger  please help me out 
![image](https://github.com/ultralytics/ultralytics/assets/119401802/dd89188a-75f7-4826-b29c-340a835eb52d)

why this is not working with pycharm , i also installed 'torch' but when try this 
![image](https://github.com/ultralytics/ultralytics/assets/119401802/346673cb-b756-4fd7-b537-897eeaebc810)
This show GPU is not available ...
