### ISSUE TITLE
AttributeError: Can't get attribute 'UltralyticsCFG' on module 'ultralytics.yolo.cfg'

### ISSUE THREAD

**Issue by elliotnash** [ultralytics/ultralytics#576]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation, Detection

### Bug

when running yolo detection, I get this error:
```
(env) elliot@ml-training:~/ml-backend$ yolo task=detect mode=predict model=gamepieces.pt source=test.jpg
Ultralytics YOLOv8.0.16 🚀 Python-3.10.7 torch-1.13.1+cu117 CPU
Traceback (most recent call last):
  File "/home/elliot/ml-backend/env/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 202, in entrypoint
    func(cfg)
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/predict.py", line 89, in predict
    predictor.predict_cli()
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 163, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 171, in stream_inference
    self.setup_model(model)
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 236, in setup_model
    self.model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 74, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 322, in attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/elliot/ml-backend/env/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'UltralyticsCFG' on <module 'ultralytics.yolo.cfg' from '/home/elliot/ml-backend/env/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py'>
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
(env) elliot@ml-training:~/ml-backend$
```

### Environment

- Ultralytics YOLOv8.0.16 🚀 Python-3.10.7 torch-1.13.1+cu117 CPU
- OS: Ubuntu 22.04 lxc container

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@elliotnash we changed this recently to IterableSimpleNamespace(). It seems your checkpoint has saved the previous class name and is unable to load. I'd recommend training a new model using the most recent pip version to solve the issue.

**Comment by SkalskiP** [comment]
@glenn-jocher do you expect to introduce breaking changes in model structure often? Maybe it would be good to have some mechanism in YOLOv8 that would still allow for loading older models. By older, I mean models from last week. :)

**Comment by Jacobsolawetz** [comment]
@glenn-jocher looking forward to the class types settling down!

**Comment by umanniyaz** [comment]
@glenn-jocher  Not able to laod custom trained model YOLOv8 ,
![image](https://user-images.githubusercontent.com/33204214/214553489-8c4b2068-f6fe-4efc-8c7f-a42445a2ca67.png)

![image](https://user-images.githubusercontent.com/33204214/214553567-a8beb196-7e90-4d4a-a959-679952e2bb9e.png)

**Comment by Kastouri** [comment]
@umanniyaz I am having the same issue.

**Comment by SkalskiP** [comment]
@umanniyaz and @Kastouri look like you have 2 options:
- Retrain your model with the latest `ultralytics` version
- Use the same version of `ultralytics` pip package that you used for training

**Comment by umanniyaz** [comment]
@SkalskiP  Ultralytics version correction worked for me (8.0.18) @Kastouri , one more question is I have chnaged to ONNX format YOLO v8 , i ma not sure about outputs like in YOLOv7

**Comment by kubikub** [comment]
> @SkalskiP Ultralytics version correction worked for me (8.0.18) @Kastouri , one more question is I have chnaged to ONNX format YOLO v8 , i ma not sure about outputs like in YOLOv7

Hi thanks for for tricks !! it's worked for me too (8.0.21)

**Comment by Thilak-cm** [comment]
> @umanniyaz and @Kastouri look like you have 2 options:
> 
> * Retrain your model with the latest `ultralytics` version
> * Use the same version of `ultralytics` pip package that you used for training

Thanks a lot! Worked for me too!
