### ISSUE TITLE
Train on GPU

### ISSUE THREAD

**Issue by sujonahmed2500** [ultralytics/ultralytics#5806]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I trained yoloV8 on my local PC with GPU some errors happened.
My code is: 

`
import torch
from ultralytics import YOLO

print(torch.cuda.is_available())
model = YOLO('yolov8s.pt')
model.train(data='D:\Project\Car Counter\Train\data\data.yaml', epochs=25, imgsz=640, plots=True)
`

Cuda is available.
my operating system is Windows.

Error is: 

`Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "d:\Project\Car Counter\Train\train.py", line 10, in <module>
    model.train(data='D:\Project\Car Counter\Train\data\data.yaml', epochs=25, imgsz=640, plots=True)
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\model.py", line 341, in train
    self.trainer.train()
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 234, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
                            ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\utils\checks.py", line 569, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\utils\checks.py", line 557, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.data  # FP32 inference
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\model.py", line 101, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\model.py", line 242, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\predictor.py", line 196, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\predictor.py", line 263, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(preds,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\utils\ops.py", line 243, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Project\Car Counter\Train\venv\Lib\site-packages\torch\_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].`

**Comment by PiyushKamboj1503** [comment]
@sujonahmed2500 the exact reason behind this issue is unknown but I have found a workaround for this on stackoverflow.

You can check the original thread here: https://stackoverflow.com/questions/75103127/getting-notimplementederror-could-not-run-torchvisionnms-with-arguments-fr

It states: 
1. Uninstall Torch and Torchvision, I used pip:
pip uninstall torch torchvision
2. Then go to https://pytorch.org/ to install the proper versions of both. Also download with the correct version of CUDA: 11.8 or  12.1

**Comment by glenn-jocher** [comment]
@sujonahmed2500 hello,

The error message you're encountering arises due to a compatibility issue between PyTorch, Torchvision, and your CUDA version. 

The 'torchvision::nms' function is not being correctly recognized by the CUDA backend, leading to a NotImplementedError.

In most cases, this can be resolved by ensuring that your installed versions of PyTorch and Torchvision are compatible with your system's CUDA version. 

Here's a common way to address this issue:

1. Uninstall your current versions of PyTorch and Torchvision using pip:

   ```
   pip uninstall torch torchvision
   ```

2. Reinstall PyTorch and Torchvision from the official website. When you're doing this, ensure you select the appropriate version that matches your CUDA version. If your CUDA version is 11.8 or 12.1, select the matching version during the installation process.

This should resolve the issue and enable you to run the training successfully. 

If you continue to experience this issue after trying these steps, please let us know.

**Comment by sujonahmed2500** [comment]
Thanks @glenn-jocher,
My coda version is 12.2:
![image](https://github.com/ultralytics/ultralytics/assets/72850751/319f2e00-1be8-4d20-842f-3fd50e268b36)

I uninstalled torch torchvision and reinstalled by this:
![image](https://github.com/ultralytics/ultralytics/assets/72850751/e5807c50-3dfe-45e0-b164-a6a249999695)

Now the error is: 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Project\Car Counter\Train\train.py", line 10, in <module>
    model.train(data='D:\Project\Car Counter\Train\data\data.yaml', epochs=25, imgsz=640, plots=True)
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\model.py", line 341, in train
    self.trainer.train()
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 253, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 52, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\data\build.py", line 107, in build_dataloader
    return InfiniteDataLoader(dataset=dataset,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\ultralytics\data\build.py", line 33, in __init__
    self.iterator = super().__iter__()
                    ^^^^^^^^^^^^^^^^^^
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Car Counter\Train\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 1039, in __init__
    w.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html`

**Comment by sujonahmed2500** [comment]
hello @PiyushKamboj1503 ,
I installed cuda 12.1, but in the Cmmand line, it shows version 12.2. 
Is it required to uninstall cuda 12.2?
Training still has same error.

**Comment by PiyushKamboj1503** [comment]
> hello @PiyushKamboj1503 ,
> I installed cuda 12.1, but in the Cmmand line, it shows version 12.2. 
> Is it required to uninstall cuda 12.2?
> Training still has same error.

The cuda version must be same in environment and PC drivers.

**Comment by glenn-jocher** [comment]
@sujonahmed2500 yes, to avoid this conflict, you should uninstall CUDA 12.2 and ensure that only one version of CUDA is present in your environment. Mixing versions of CUDA can lead to unexpected errors and issues, as each version is tailored for specific NVIDIA drivers and hardware. After uninstalling, rerun the training command and see if the error persists. If it does, share the full error message and your setup details (OS, NVIDIA driver version, etc.). That will help diagnose and address your problem more effectively.

**Comment by beebrain** [comment]
I have the same issue. I installed cuda 12.1 and rechecked with nvidia-smi command. It shows 12.1 
![image](https://github.com/ultralytics/ultralytics/assets/10016227/69fc4961-fb1e-4ad3-975e-10695f685ab4)
 
when I tried to train the model it terminated and sent the message.
The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  
Please suggest me.

**Comment by glenn-jocher** [comment]
@beebrain the RuntimeError indicating the need for `freeze_support()` is specific to Windows when using the `multiprocessing` module. It seems that the training script is attempting to start a new process but is not following the required Windows convention for `multiprocessing`.

To resolve this particular issue, you can encapsulate your training code inside an `if __name__ == '__main__':` block. This is a necessary step for multiprocessing support on Windows, as indicated by the Python error message you're receiving.

Here's a conceptual example of what your main training script should look like:

```python
import torch
from ultralytics import YOLO

def main():
    print(torch.cuda.is_available())
    model = YOLO('yolov8s.pt')
    model.train(data='D:\\Project\\Car Counter\\Train\\data\\data.yaml', epochs=25, imgsz=640, plots=True)

if __name__ == '__main__':
    main()
```

Notice the use of `def main():` to define the main functionality and the `if __name__ == '__main__':` guard to call `main()`. This setup ensures that the `freeze_support()` functionality of the multiprocessing module is properly invoked on Windows.

Remember to replace backslashes (`\`) with either double backslashes (`\\`) or raw string literals (e.g., `r'D:\Project\...'`) in file paths to prevent escape sequence issues in Python strings.

Encapsulate your original training script similarly and then retry your training command.

**Comment by glenn-jocher** [comment]
@beebrain you're welcome! I'm glad to hear that your issue has been resolved. If you have any more questions or run into any further issues, don't hesitate to reach out. Happy training with YOLOv8! 🚀🎉
