### ISSUE TITLE
Multi GPU CUDA Time Out Error in Validation

### ISSUE THREAD

**Issue by QartiaCube** [ultralytics/ultralytics#5933]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val, Multi-GPU

### Bug

Training on a custom dataset with one GPU works fine, but using more than one GPU crashes during validation in the first epoch.

This is the code:
```
from ultralytics import YOLO

#Cargar el modelo a partir de los pesos del ultimo entrenamiento o de COCO
model = YOLO('/home/mvilar/insect_detection/OneClass/yolov8m.pt')
#Cargar la información del dataset y entrenar la red
model.train(data='/home/mvilar/insect_detection/OneClass/insectsOne.yaml', epochs=200, device=[0,1,2,3,4,5,6,7])
#Guardar el modelo, por defecto en formato pytorch .pt
model.export()
```
Then it crashes:
![image](https://github.com/ultralytics/ultralytics/assets/129166635/8bb9de92-9eae-4531-b393-d5c2cae91be8)

The full error is here:

```
Traceback (most recent call last):
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1574, in broadcast
    work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mvilar/insect_detection/OneClass/train.py", line 6, in <module>
    model.train(data='/home/mvilar/insect_detection/OneClass/insectsOne.yaml', epochs=200, device=[0,1,2,3,4,5,6,7])
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 403, in _do_train
    dist.broadcast_object_list(broadcast_list, 0)  # broadcast 'stop' to all ranks
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2255, in broadcast_object_list
    broadcast(object_sizes_tensor, src=src, group=group)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1456, in wrapper
    "args": f"{args}, {kwargs}",
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor.py", line 426, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 636, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 567, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 327, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 111, in __init__
    value_str = "{}".format(value)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor.py", line 872, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   2%|▏         | 23/1168 [00:07<06:38,  2.87it/s]Traceback (most recent call last):
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1574, in broadcast
    work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mvilar/insect_detection/OneClass/train.py", line 6, in <module>
    model.train(data='/home/mvilar/insect_detection/OneClass/insectsOne.yaml', epochs=200, device=[0,1,2,3,4,5,6,7])
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 403, in _do_train
    dist.broadcast_object_list(broadcast_list, 0)  # broadcast 'stop' to all ranks
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2255, in broadcast_object_list
    broadcast(object_sizes_tensor, src=src, group=group)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1456, in wrapper
    "args": f"{args}, {kwargs}",
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor.py", line 426, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 636, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 567, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 327, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor_str.py", line 111, in __init__
    value_str = "{}".format(value)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/_tensor.py", line 872, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[W CUDAGuardImpl.h:124] Warning: CUDA warning: the launch timed out and was terminated (function destroyEvent)
[W CUDAGuardImpl.h:124] Warning: CUDA warning: the launch timed out and was terminated (function destroyEvent)
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   2%|▏         | 24/1168 [00:07<06:38,  2.87it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75173 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75174 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75175 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75176 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75178 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75179 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 75180 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 4 (pid: 75177) of binary: /home/mvilar/yolo/bin/python3.10
Traceback (most recent call last):
  File "/home/mvilar/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mvilar/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
/home/mvilar/insect_detection/OneClass/train.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-25_12:16:16
  host      : vagalume.upct.es
  rank      : 4 (local_rank: 4)
  exitcode  : -6 (pid: 75177)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 75177
======================================================
Traceback (most recent call last):
  File "/home/mvilar/insect_detection/OneClass/train.py", line 6, in <module>
    model.train(data='/home/mvilar/insect_detection/OneClass/insectsOne.yaml', epochs=200, device=[0,1,2,3,4,5,6,7])
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 187, in train
    raise e
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "/home/mvilar/miniconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/mvilar/yolo/bin/python3.10', '-m', 'torch.distributed.run', '--nproc_per_node', '8', '--master_port', '38253', '/home/mvilar/insect_detection/OneClass/train.py']' returned non-zero exit status 1
```

I have tried to modify `trainer.py` to disable timeout, I have tried to set `os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
` and also checked that torch identifies every GPU, used `nvidia-smi` to check during training the GPUs were in use.

Changing `nccl` to `gloo` also crashed, but with a different error.

### Environment

Ultralytics YOLOv8.0.201 🚀 Python-3.10.8 torch-2.0.1+cu117 CUDA:0 (Tesla M10, 8127MiB)
Setup complete ✅ (72 CPUs, 125.3 GB RAM, 185.8/217.6 GB disk)

OS                  Linux-5.4.0-163-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.8
Install             pip
RAM                 125.35 GB
CPU                 Intel Xeon Gold 5220 2.20GHz
CUDA                11.7

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.25.0>=1.22.2
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.0.2>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Thank you, @QartiaCube, for the comprehensive explanation. Based on the log information, it appears that the error may be related to the validation data. Ensure that your validation dataset contains a sufficient number of samples that align with the batch size you're using. For example, if your batch size is set to 16, ensure that your validation dataset contains a multiple of 16 images.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by QartiaCube** [comment]
Hi, I checked the number of images and adjusted so I have multiple of 16 in both training and validation.

I have 14304 images in training and 4672 in validation. However, now the program crashes before training, scanning the images to form the `.cache` files throws the error:

```
Traceback (most recent call last):
  File "/home/mvilar/insect_detection/OneClass/train.py", line 6, in <module>
    model.train(data='/home/mvilar/insect_detection/OneClass/insectsOne.yaml', epochs=200, device=[0,1,2,3,4,5,6,7])
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 253, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/models/yolo/detect/train.py", line 45, in get_dataloader
    with torch_distributed_zero_first(rank):  # init dataset *.cache only once if DDP
  File "/home/mvilar/miniconda3/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/mvilar/yolo/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py", line 36, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "/home/mvilar/yolo/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3335, in barrier
    work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated
```

I can get around this by starting the train script with only one GPU, and thus creating the `.cache` files, but then it crashes again when validating.

I have also changed the batch size and the number of GPUs but so far, nothing works

**Comment by glenn-jocher** [comment]
@QartiaCube it seems there could be an issue with either the GPU memory allocation or the image dataset itself.

1. GPU Memory: This error can be caused if the memory of your GPU(s) is not sufficient. The model during training needs to allocate memory for the weights, gradients and for the image data itself, for both training and validation sets. If this allocation exceeds your GPU memory, you can possibly encounter a timeout.

2. Image Data: Corrupted or very large images might cause a problem during the caching process. If the code aborts during caching, there could be an issue with one or more of your image files. So, you may need to reconsider the size of your images or check for potential corruptions.

3. GPU Usage: Try to monitor your GPU usage during the process to check if there is any unusual usage pattern. You can use tools like `nvidia-smi` to monitor memory usage on your GPUs.

4. Parallel Processing: If the error still persists, you could try the training with a single GPU, as parallel processing might complicate the debugging process.

Hopefully, this will give you some direction in finding the root cause of this issue, good luck!

**Comment by batuhandogan1** [comment]
@QartiaCube Hi did you solved your issue?

**Comment by glenn-jocher** [comment]
As I'm not @batuhandogan1, I can't provide an update on their specific issue. However, if you're facing a similar problem with your YOLOv8 setup, I would suggest trying the following steps, which can often resolve multi-GPU training issues:

1. **Update NVIDIA Drivers and CUDA Toolkit**: Ensure your system's NVIDIA drivers and CUDA toolkit are up to date with the version required by the PyTorch installation.

2. **Validate Dataset**: Check your dataset and ensure there are no corrupted images or annotations. It's also essential that the datasets are accessible across all the GPUs being used.

3. **Reduce Batch Size**: Try lowering the batch size to reduce GPU memory usage and see if that prevents the timeout error. This could stabilize the training process without overwhelming the GPUs.

4. **Single GPU Test**: If the multi-GPU setup continues to cause problems, try running the process on a single GPU to ensure there are no underlying issues with the dataset or the training script.

5. **Isolate Faulty GPU**: In some cases, one of the GPUs could be malfunctioning. Try running the training script by sequentially excluding one GPU at a time to see if the error is associated with a particular GPU.

6. **System Monitoring**: Use tools like `nvidia-smi` to monitor GPU usage, temperature, and processes to ensure the hardware is functioning properly during training.

If you carefully follow each of these steps, hopefully, you'll be able to identify and resolve the root cause of the problem. If the issue persists, providing detailed logs and system information can be crucial in getting further assistance.

**Comment by QartiaCube** [comment]
> @QartiaCube Hi did you solved your issue?

Hi, monitoring the GPUs with `nvidia-smi` and checking the logs reported a failure in all but one GPU. I'm still investigating the error, but since I am not the admin in the server the GPUs are running it's going rather slowly. 

Overrall I think it's not an issue with the library and it's related to the specific hardware I am using so I will close the issue.
