### ISSUE TITLE
"No module named models" using an v5 model

### ISSUE THREAD

**Issue by kpoman** [ultralytics/ultralytics#601]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello,
I am trying to load and test this model (https://github.com/wasdac9/automatic-number-plate-recognition/blob/main/best.pt) and get this stacktrace:

```
Traceback (most recent call last):
  File "C:\Users\kpoma\Dev\yolov8\yolov8_tracking-master\track.py", line 363, in <module>
    main(opt)
  File "C:\Users\kpoma\Dev\yolov8\yolov8_tracking-master\track.py", line 358, in main
    run(**vars(opt))
  File "C:\Users\kpoma\Dev\yolov8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\kpoma\Dev\yolov8\yolov8_tracking-master\track.py", line 104, in run
    model = AutoBackend(yolo_weights, device=device, dnn=dnn, fp16=half)
  File "C:\Users\kpoma\Dev\yolov8\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 73, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "C:\Users\kpoma\Dev\yolov8\venv\lib\site-packages\ultralytics\nn\tasks.py", line 306, in attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "C:\Users\kpoma\Dev\yolov8\venv\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\kpoma\Dev\yolov8\venv\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\kpoma\Dev\yolov8\venv\lib\site-packages\torch\serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

(venv) (base) C:\Users\kpoma\Dev\yolov8\yolov8_tracking-master>
```
I saw in the pkl inside the model it is stated as "Model" (and not DetectionModel etc...) ... I tried changing it inside to be DetectionModel and this didnt work.
Hope someone can help me.

### Environment

Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
The pretrained models for yolov5 are not available on fir repo currently.. You can train from scratch, i.e, set `model=yolov5s/n/m/l/x.yaml` but can't yet use the pre-trained .pt files. We plan to add them soon

**Comment by z1069614715** [comment]
@AyushExel hello, i want to known,if i append yolov8n.yaml, and then i using it to load model, in this case, how can i load pretrained model?that mean is how can i load pretrained model when i using yaml loading, in yolov5 code,it can be implement by using weights and cfg param.

**Comment by obsidiane** [comment]
> @AyushExel hello, i want to known,if i append yolov8n.yaml, and then i using it to load model, in this case, how can i load pretrained model?that mean is how can i load pretrained model when i using yaml loading, in yolov5 code,it can be implement by using weights and cfg param.

hi，i have the seem question, i want to train my own pt based on the pretrained model, but i have some problem with that in new yolov8, do you have some suggestions？
