### ISSUE TITLE
TypeError: argument must be sequence

### ISSUE THREAD

**Issue by Garvit-32** [ultralytics/ultralytics#610]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

YOLOv8m-seg summary (fused): 245 layers, 27231648 parameters, 0 gradients, 110.0 GFLOPs
Traceback (most recent call last):
  File "predict.py", line 20, in <module>
    results = model.predict(source = im, save = True, show = True)  
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 140, in predict
    return self.predictor(source=source, stream=stream, verbose=verbose)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 158, in __call__
    return list(self.stream_inference(source, model, verbose))  # merge list of Result into one
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 205, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/predict.py", line 90, in write_results
    self.annotator.box_label(d.xyxy.squeeze(), label, color=colors(c, True)) if self.args.boxes else None
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/utils/plotting.py", line 61, in box_label
    self.draw.rectangle(box, width=self.lw, outline=color)  # box
  File "/opt/conda/lib/python3.8/site-packages/PIL/ImageDraw.py", line 279, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
TypeError: argument must be sequence
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

### Environment

-Ultralytics YOLOv8.0.18 🚀 Python-3.8.12 torch-1.11.0

### Minimal Reproducible Example

```
import cv2
import numpy as np
from PIL import Image
from ultralytics import YOLO

model = YOLO("runs/segment/train2/weights/best.pt")
im = Image.open('inputs/0b23fb62b2624c7588da634875907631-1623259906500003313.png').convert('RGB')
results = model.predict(source = im, save = True)  
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lizozom** [comment]
I'm having the same issue.

**Comment by Laughing-q** [comment]
@lizozom @Garvit-32 I can't reproduce the error:
![image](https://user-images.githubusercontent.com/61612323/221130510-24a2a495-a30b-449f-ad43-259c7dcf7e28.png)
