### ISSUE TITLE
I can't train with multiple GPU

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [ultralytics/ultralytics#6104]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I try to train in a multiple GPU computer, but it failed. There is the error:

`yolo task=detect mode=train model=yolov8s data=data.yaml batch=20 epochs=200 imgsz=960 device=0,1
New https://pypi.org/project/ultralytics/8.0.205 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.201 🚀 Python-3.8.0 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11169MiB)
                                                           CUDA:1 (NVIDIA GeForce GTX 1080 Ti, 11172MiB)
engine/trainer: task=detect, mode=train, model=yolov8s, data=data.yaml, epochs=200, patience=50, batch=20, imgsz=960, save=True, save_period=-1, cache=False, device=(0, 1), workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2118370  ultralytics.nn.modules.head.Detect           [6, [128, 256, 512]]
Model summary: 225 layers, 11137922 parameters, 11137906 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
DDP: debug command /home/wupeng/anaconda3/envs/yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 46103 /home/wupeng/.config/Ultralytics/DDP/_temp_fqk4xw5a139795737659280.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Ultralytics YOLOv8.0.201 🚀 Python-3.8.0 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11169MiB)
                                                           CUDA:1 (NVIDIA GeForce GTX 1080 Ti, 11172MiB)
Traceback (most recent call last):
  File "/home/wupeng/.config/Ultralytics/DDP/_temp_fqk4xw5a139795737659280.py", line 9, in <module>
    trainer.train()
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 211, in _setup_train
    ckpt = self.setup_model()
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 466, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/models/yolo/detect/train.py", line 71, in get_model
    model = DetectionModel(cfg, nc=self.data['nc'], verbose=verbose and RANK == -1)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 225, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 742, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 455, in check_yaml
    return check_file(file, suffix, hard=hard)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 447, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'yolov8s' does not exist
Traceback (most recent call last):
  File "/home/wupeng/.config/Ultralytics/DDP/_temp_fqk4xw5a139795737659280.py", line 9, in <module>
    trainer.train()
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 211, in _setup_train
    ckpt = self.setup_model()
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 466, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/models/yolo/detect/train.py", line 71, in get_model
    model = DetectionModel(cfg, nc=self.data['nc'], verbose=verbose and RANK == -1)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 225, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 742, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 455, in check_yaml
    return check_file(file, suffix, hard=hard)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 447, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'yolov8s' does not exist
[2023-11-03 10:29:49,571] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 601512) of binary: /home/wupeng/anaconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/wupeng/.config/Ultralytics/DDP/_temp_fqk4xw5a139795737659280.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-03_10:29:49
  host      : 1080x2
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 601513)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-03_10:29:49
  host      : 1080x2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 601512)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/wupeng/anaconda3/envs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 444, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 187, in train
    raise e
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "/home/wupeng/anaconda3/envs/yolov8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/wupeng/anaconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '46103', '/home/wupeng/.config/Ultralytics/DDP/_temp_fqk4xw5a139795737659280.py']' returned non-zero exit status 1.`

It tell me 
'FileNotFoundError: 'yolov8s' does not exist'
but I'm sure the file 'yolov8s' are in the same folder . 

If I use single GPU , it was run

### Environment

Ultralytics YOLOv8.0.203 🚀 Python-3.10.13 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3090, 24255MiB)
Setup complete ✅ (56 CPUs, 251.8 GB RAM, 137.1/233.2 GB disk)

OS                  Linux-5.15.0-79-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.13
Install             pip
RAM                 251.78 GB
CPU                 Intel Xeon E5-2680 v4 2.40GHz
CUDA                12.1

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.26.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

yolo task=detect mode=train model=yolov8s data=data.yaml batch=20 epochs=200 imgsz=960 device=0,1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@smallworld-network-wupeng your model is invalid, you need to add a .pt to the end of it: model=yolov8s.pt

**Comment by glenn-jocher** [comment]
@smallworld-network-wupeng great news 😃! Your original issue may now be resolved ✅ in PR #6111. This PR will merge as deploy as `ultralytics 8.0.206` later today or tomorrow. 

This should allow for DDP training of `model='yolov8s'`.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by smallworld-network-wupeng** [comment]
> @smallworld-network-wupeng your model is invalid, you need to add a .pt to the end of it: model=yolov8s.pt

oh, yes, that right!

**Comment by glenn-jocher** [comment]
@smallworld-network-wupeng-wupeng, I'm glad to hear you were able to resolve your issue. If you come across any new issues or have further questions about YOLOv8, don't hesitate to ask. Happy training with YOLOv8!
