### ISSUE TITLE
Classify task train working on Mac but not on Ubunty

### ISSUE THREAD

**Issue by kkahol-percipio** [ultralytics/ultralytics#6105]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I have a strange issue. I created the dataset folder as per the specification for classify task. Now when I try and train the data on a Mac the training is progressing albeit very slowly. I do have a Ubuntu machine with a very good GPU but on that I am getting an error with the same folder.
  model.train(data= '/home/peter/Desktop/ndc_classifier/yolo_pill_classifier_data_ndc', epochs=600, imgsz=256, batch=8)
  File "/home/peter/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/home/peter/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/peter/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 313, in _do_train
    for i, batch in pbar:
  File "/home/peter/.local/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/peter/.local/lib/python3.8/site-packages/ultralytics/yolo/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/home/peter/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/peter/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/peter/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/peter/.local/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/peter/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peter/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peter/.local/lib/python3.8/site-packages/ultralytics/yolo/data/dataset.py", line 262, in __getitem__
    sample = self.torch_transforms(im)
  File "/home/peter/.local/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/peter/.local/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 881, in __call__
    imh, imw = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
On a Mac there is no issue and the jpg files are read but on the ubuntu it is not working. I may also add that I have opened the jpg files on the ubuntu and they are opening. I would appreciate pointers on how to get rid of this.

**Comment by RizwanMunawar** [comment]
Thank you, @kkahol-percipio, for the comprehensive information you've provided! From my perspective, it appears that this error could be related to either a path problem or access issues with the image folders on Ubuntu.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by kkahol-percipio** [comment]
I actually figured it out. our UBUNTU was running an older version of ultralytics. Once I did pip install ultralytics --upgrade it worked

**Comment by glenn-jocher** [comment]
Great to hear you managed to resolve the issue, @kkahol-percipio! Indeed, keeping your packages up-to-date is crucial, as many bugs are fixed in newer versions. It's wonderful that upgrading `ultralytics` resolved the problem. Happy training with YOLOv8 and let us know if you encounter any other issues!
