### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

### ISSUE THREAD

**Issue by bid-p** [ultralytics/ultralytics#612]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

PyTorch Hub

### Bug

I'm getting:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 34, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 15, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/__init__.py", line 544, in <module>
    SETTINGS = get_settings()
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/__init__.py", line 503, in get_settings
    with torch_distributed_zero_first(RANK):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/torch_utils.py", line 34, in torch_distributed_zero_first
    initialized = torch.distributed.is_initialized()  # prevent 'Default process group has not been initialized' errors
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
```
when importing `YOLO` from `ultralytics`.

### Environment

- YOLO: Ultralytics YOLOv8.0.18 🚀 Python-3.8.10 torch-1.13.0a0+936e9305.nv22.11 CUDA:0 (Xavier, 6855MiB)
- OS: Ubuntu 20.04
- Python: 3.8.10
- Platform: Jetson Xavier NX

### Minimal Reproducible Example

First, I installed ultralytics, using `pip install ultralytics`.

Then, run `from ultralytics import YOLO`
<img width="966" alt="image" src="https://user-images.githubusercontent.com/22570121/214402265-8be98382-73c6-42f8-8e40-191e932dba91.png">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by bid-p** [comment]
My quick fix was to edit line 34 of `ultralytics/yolo/utils/torch_utils.py`:

```
initialized = torch.distributed.is_initialized()  # prevent 'Default process group has not been initialized' errors
```
to
```
initialized = torch.distributed.is_available() and torch.distributed.is_initialized()  # prevent 'Default process group has not been initialized' errors
```

**Comment by pderrenger** [comment]
@bid-p thanks for sharing your quick fix! Your modification to check `torch.distributed.is_available()` before calling `torch.distributed.is_initialized()` seems reasonable and can help prevent the mentioned error. 

This workaround ensures that the distributed package is not only initialized but also available, addressing the error and potentially enhancing the stability of the functionality.

Feel free to proceed with testing your modification and submitting a pull request. Your contribution is greatly appreciated!
