### ISSUE TITLE
RTDETR ONNX export failure for torch>=2.1.0 `Unsupported: ONNX export of operator get_pool_ceil_padding`

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/ultralytics#6144]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

> model.export(format='onnx')
Ultralytics YOLOv8.0.206 🚀 Python-3.8.0 torch-1.9.0+cu102 CPU (Intel Xeon E5-2678 v3 2.50GHz)
/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients

PyTorch: starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)

ONNX: starting export with onnx 1.15.0 opset 12...
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
ONNX: export failure ❌ 5.1s: _all() takes 2 positional arguments but 4 were given 
(Occurred when translating all).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 254, in __call__
    f[2], _ = self.export_onnx()
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 333, in export_onnx
    torch.onnx.export(
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
TypeError: _all() takes 2 positional arguments but 4 were given 

@glenn-jocher   thank you

### Additional

 > model.export(format='onnx')
Ultralytics YOLOv8.0.206 🚀 Python-3.8.0 torch-1.9.0+cu102 CPU (Intel Xeon E5-2678 v3 2.50GHz)
/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients

PyTorch: starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)

ONNX: starting export with onnx 1.15.0 opset 12...
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
ONNX: export failure ❌ 5.1s: _all() takes 2 positional arguments but 4 were given 
(Occurred when translating all).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 254, in __call__
    f[2], _ = self.export_onnx()
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/cwang/work/lianxi/ultralytics-main(1)/ultralytics-main/ultralytics/engine/exporter.py", line 333, in export_onnx
    torch.onnx.export(
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/cwang/anaconda3/envs/yolo8/lib/python3.8/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
TypeError: _all() takes 2 positional arguments but 4 were given

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. RTDETR ONNX export works correctly for me:

```python
from ultralytics import RTDETR

model = RTDETR()
model.export(format='onnx')
```

```
Ultralytics YOLOv8.0.186 🚀 Python-3.10.6 torch-2.0.0 CPU (Apple M2)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients
PyTorch: starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)
ONNX: starting export with onnx 1.15.0 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
ONNX: export success ✅ 4.1s, saved as 'rtdetr-l.onnx' (122.7 MB)
Export complete (6.0s)
Results saved to /Users/glennjocher/PycharmProjects/assistant
Predict:         yolo predict task=detect model=rtdetr-l.onnx imgsz=640  
Validate:        yolo val task=detect model=rtdetr-l.onnx imgsz=640 data=None  
Visualize:       https://netron.app
```


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 ah, I see that this only works above for 8.0.186 but not for the latest version. Not sure what the problem might be.

```
Ultralytics YOLOv8.0.206 🚀 Python-3.11.2 torch-2.1.0 CPU (Apple M2)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients
PyTorch: starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)
ONNX: starting export with onnx 1.14.1 opset 17...
ONNX: export failure ❌ 1.0s: Unsupported: ONNX export of operator get_pool_ceil_padding, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues  [Caused by the value 'input.4 defined in (%input.4 : Float(*, *, *, *, strides=[3297312, 103041, 321, 1], requires_grad=0, device=cpu) = onnx::Pad[mode="constant"](%449, %476, %452), scope: ultralytics.nn.tasks.DetectionModel::/ultralytics.nn.modules.block.HGStem::model.0 # /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/nn/modules/block.py:77:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Pad'.] 
```

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 ok the problem is in `torch`, not in `ultralytics`. If you `pip install torch==2.0.0` then RTDETR export works correctly. 

I would raise a bug report directly with the pytorch repo in this case.

**Comment by ruzko** [comment]
An update on this for people finding it in the future:
exporting to ONNX works again with `pip install torch==2.2.0`

**Comment by glenn-jocher** [comment]
@ruzko hello everyone 👋,

Good news! The ONNX export issue has been resolved with the latest PyTorch update. You can ensure a smooth export process by updating PyTorch to version 2.2.1. Simply run:

```bash
pip install torch==2.2.1
```

And then proceed with your model export as usual:

```python
from ultralytics import YOLO

# Load your model
model = YOLO(path_to_your_model)

# Export to ONNX
model.export(format='onnx')
```

Happy coding, and feel free to reach out if you encounter any more issues! 😊
