### ISSUE TITLE
Numpy is not available after run Ultralytics

### ISSUE THREAD

**Issue by MichalPisanczuk** [ultralytics/ultralytics#6254]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when i tried run main.py app then i get error: RuntimeError: Numpy is not available. When i checked pip show numpy i have: Name: numpy Version: 1.26.1. Where is a problem? Other environment configurations: Ultralytics YOLOv8.0.114 Python-3.10.0 torch-2.0.1+cpu CPU

`from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch

# Use the model
model.train(data="config.yaml", epochs=1)  # train the model`

terminal ouput:
`Traceback (most recent call last):
  File "d:\Programy\Bottle_recognition\main.py", line 7, in <module>
    model.train(data="config.yaml", epochs=1)  # train the model
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 313, in _do_train
    for i, batch in pbar:
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\data\build.py", line 38, in __iter__
    yield next(self.iterator)
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\data\base.py", line 239, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\data\augment.py", line 56, in __call__
    data = t(data)
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\data\augment.py", line 730, in __call__
    labels['img'] = self._format_img(img)
  File "C:\Users\it\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\data\augment.py", line 745, in _format_img
    img = torch.from_numpy(img)
**RuntimeError: Numpy is not available**`

### Environment

Ultralytics YOLOv8.0.208  Python-3.11.6 torch-2.0.0+cpu CPU (11th Gen Intel Core(TM) i7-11700KF 3.60GHz)
Setup complete  (16 CPUs, 31.7 GB RAM, 48.2/683.6 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 31.68 GB
CPU                 11th Gen Intel Core(TM) i7-11700KF 3.60GHz
CUDA                None

matplotlib           3.7.1>=3.3.0
numpy                1.26.1>=1.22.2
opencv-python        4.7.0.72>=4.6.0
pillow               9.4.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.10.1>=1.4.1
torch                2.0.0>=1.8.0
torchvision          0.16.0>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.1>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.6
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MichalPisanczuk it seems you're facing a RuntimeError due to an issue with NumPy availability when attempting to train a YOLOv8 model. It's unusual because you've confirmed that NumPy is indeed installed in your environment.

One potential explanation could be an environment or compatibility issue. Here are a few steps you might want to consider:

1. Ensure your installed packages are up to date, especially NumPy. Sometimes, upgrading NumPy can resolve any latent compatibility problems.
2. Verify if NumPy is correctly installed within your working Python environment. There could be multiple environments and the one active in your terminal may not have NumPy available.
3. Confirm if `numpy` is accessible by importing it in a standalone Python script or directly in the Python interpreter. This will check if the issue is isolated to the Ultralytics package or general to your Python environment.
4. Sometimes, a reinstallation of NumPy or the creation of a fresh Python environment solves these problems.
5. If the issue persists, it might be helpful to open an issue on our repo detailing the steps you have tried, ensuring to include information about your environment and the complete error traceback. Although I understand you might refrain from immediate PR submission, contributing a fix after identifying the issue is always welcome.

If you need any further guidance, Ultralytics documentation can offer additional insights related to installation and setup.

Remember that, although the traceback and errors you are seeing are from the terminal and involve specific Python packages, often the remedy involves navigating differences between your specific local development environment setup and the expected standard environment for YOLOv8 usage.
