### ISSUE TITLE
Ray tune ModuleNotFoundError: No module named 'ultralytics.yolo'

### ISSUE THREAD

**Issue by Magnico** [ultralytics/ultralytics#6279]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am a student currently working on the final project for my graduation, for this I was tasked with creating an image classification model with YOLOv8.

Even though I am no expert on the matter following some guides I decided to try with learning transfer for the yolov8s-cls.pt pretrained model.

After preparing the dataset of images and performing some trainings I was recommended to use ray tune to find the best hyperparameters for the model.

This is the code that I used for that purpose; I worked on a venv

```
%pip install ultralytics "ray[tune]"

from ultralytics import YOLO

img_class_model = YOLO("yolov8s-cls.pt")
img_class_model.tune(data='./Data', use_ray=True)
#img_class_model.tune(data='test.yaml', use_ray=True) Tried both ways
```

![image](https://github.com/ultralytics/ultralytics/assets/61947333/0f6ba94c-b6c8-4a21-95df-2247384b5ec8)

Each one of the trials end up as a failure with error `ModuleNotFoundError: No module named 'ultralytics.yolo'`

This is the information of my device. 
```
Ultralytics YOLOv8.0.208  Python-3.9.13 torch-2.1.0+cpu CPU (AMD Ryzen 5 5600G with Radeon Graphics)
Setup complete  (12 CPUs, 15.4 GB RAM, 234.6/930.9 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.9.13
Install             git
RAM                 15.37 GB
CPU                 AMD Ryzen 5 5600G with Radeon Graphics
CUDA                None
```

### Additional

Here is the structure of the folder ./Data.

```
Data/
    train/
        0/
        1/
        2/
        3/
        4/
        5/
        6/
    val/
        0/
        1/
        2/
        3/
        4/
        5/
        6/

```

ResultGrid
```
ResultGrid<[
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00000_0_box=0.1758,cls=2.1704,copy_paste=0.7786,degrees=20.8508,fliplr=0.0779,flipud=0.2683,hsv_h=0.0652,hsv_s=0.2614,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00001_1_box=0.1606,cls=2.2208,copy_paste=0.6694,degrees=10.1991,fliplr=0.4352,flipud=0.9353,hsv_h=0.0776,hsv_s=0.8515,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00002_2_box=0.1508,cls=0.6414,copy_paste=0.8440,degrees=24.2274,fliplr=0.0809,flipud=0.3180,hsv_h=0.0907,hsv_s=0.2168,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00003_3_box=0.1832,cls=3.7505,copy_paste=0.4476,degrees=44.0922,fliplr=0.5659,flipud=0.8157,hsv_h=0.0311,hsv_s=0.6189,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00004_4_box=0.1184,cls=1.4965,copy_paste=0.0677,degrees=44.5339,fliplr=0.2781,flipud=0.8372,hsv_h=0.0439,hsv_s=0.2800,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00005_5_box=0.1309,cls=2.1603,copy_paste=0.5943,degrees=31.6424,fliplr=0.9434,flipud=0.5025,hsv_h=0.0127,hsv_s=0.5220,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00006_6_box=0.1256,cls=1.4099,copy_paste=0.2093,degrees=1.6315,fliplr=0.5103,flipud=0.0469,hsv_h=0.0343,hsv_s=0.8992,h_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00007_7_box=0.0762,cls=1.7434,copy_paste=0.5175,degrees=27.7508,fliplr=0.5689,flipud=0.9872,hsv_h=0.0409,hsv_s=0.8834,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00008_8_box=0.0444,cls=2.5332,copy_paste=0.6691,degrees=35.4892,fliplr=0.4998,flipud=0.5841,hsv_h=0.0336,hsv_s=0.6731,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  ),
  Result(
    error='RayTaskError',
    metrics={},
    path='C:/Users/Magnico/Documents/GitProjects/driver_detection/runs/detect/tune4/_tune_2023-11-11_23-55-13/_tune_aa538_00009_9_box=0.1755,cls=0.7721,copy_paste=0.5758,degrees=27.8763,fliplr=0.6021,flipud=0.3881,hsv_h=0.0450,hsv_s=0.2425,_2023-11-11_23-55-13',
    filesystem='local',
    checkpoint=None
  )
]>
```
![image](https://github.com/ultralytics/ultralytics/assets/61947333/e20dcf42-a3f4-4f04-bc62-66bf6ba96e82)

Here is the full log, it is the same for all trials
```
Failure # 1 (occurred at 2023-11-11_23-55-36)
[36mray::ImplicitFunc.train()[39m (pid=15776, ip=127.0.0.1, actor_id=94b7db857bba61e2f7f586ec01000000, repr=_tune)
  File "python\ray\_raylet.pyx", line 1675, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1615, in ray._raylet.execute_task.function_executor
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\tune\trainable\trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\air\_internal\util.py", line 91, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\tune\trainable\function_trainable.py", line 115, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\tune\trainable\function_trainable.py", line 332, in _trainable_func
    output = fn()
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ultralytics\utils\tuner.py", line 101, in _tune
    model_to_train = ray.get(model_in_store)  # get the model from ray store for tuning
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\worker.py", line 2565, in get
    raise value
ray.exceptions.RaySystemError: System error: No module named 'ultralytics.yolo'
traceback: Traceback (most recent call last):
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\serialization.py", line 404, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\serialization.py", line 270, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\serialization.py", line 225, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "c:\Users\Magnico\Documents\GitProjects\driver_detection\venv\lib\site-packages\ray\_private\serialization.py", line 215, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
ModuleNotFoundError: No module named 'ultralytics.yolo'
```

**Comment by RizwanMunawar** [comment]
@Magnico, appreciate the thorough details you've shared. We'll investigate this and keep you informed about the results.

**Comment by lijiahaoAA** [comment]
I have also experienced this problem, have you solved it yet?

**Comment by glenn-jocher** [comment]
@lijiahaoAA just update ultralytics with `pip updates ultralytics` to resolve this.

**Comment by wangzhongju** [comment]
if ultralytics>8.0
run
pip install ultralytics==8.0.124

**Comment by glenn-jocher** [comment]
@wangzhongju to ensure compatibility, please use `pip install ultralytics==8.0.124`. This will align your installation with the version that's known to work correctly with your current setup. 🛠️

**Comment by daohaofunk** [comment]
I encountered the same problem using a customed yolov8 model, but when I changed the model to basic yolov8, it worked. Is there any way for ray-tun to support the customer yolov8 model?

**Comment by daohaofunk** [comment]
> @wangzhongju to ensure compatibility, please use `pip install ultralytics==8.0.124`. This will align your installation with the version that's known to work correctly with your current setup. 🛠️

I encountered the same problem using a customed yolov8 model, but when I changed the model to basic yolov8, it worked. Is there any way for ray-tun to support the customer yolov8 model?
