### ISSUE TITLE
Multi GPU Training not starting in Windows

### ISSUE THREAD

**Issue by Lalit-Dumka** [ultralytics/ultralytics#6309]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

I am trying to train a model on a Windows machine with 2 Tesla T4 GPUs but it gives this error. The training works fine when I give device=0. I have read some threads mentioning similar issues they say multi-GPU training works fine on Linux machines and the error is specific to Windows only.
**Error:**
```

Ultralytics YOLOv8.0.206  Python-3.9.18 torch-2.0.1 CUDA:0 (Tesla T4, 15198MiB)
                                                      CUDA:1 (Tesla T4, 15198MiB)
engine\trainer: task=detect, mode=train, model=yolov8x.pt, data=D:/Lalit/datasets/data_augmented.yaml, epochs=500, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=True, device=(0, 1), workers=8, project=testing_error, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=testing_error\train
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 22        [15, 18, 21]  1   8726635  ultralytics.nn.modules.head.Detect           [9, [320, 640, 640]]
Model summary: 365 layers, 68161275 parameters, 68161259 gradients, 258.2 GFLOPs

Transferred 589/595 items from pretrained weights
DDP: debug command C:\Users\Lalit\.conda\envs\trainYolo\python.exe -m torch.distributed.run --nproc_per_node 2 --master_port 57841 C:\Users\Lalit\AppData\Roaming\Ultralytics\DDP\_temp_vh7uzjv71662667013856.py
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [WIN-J8OO0HCVUSD]:57841 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [WIN-J8OO0HCVUSD]:57841 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [WIN-J8OO0HCVUSD]:57841 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [WIN-J8OO0HCVUSD]:57841 (system error: 10049 - The requested address is not valid in its context.).
Ultralytics YOLOv8.0.206  Python-3.9.18 torch-2.0.1 CUDA:0 (Tesla T4, 15198MiB)
                                                      CUDA:1 (Tesla T4, 15198MiB)
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [WIN-J8OO0HCVUSD]:57841 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [WIN-J8OO0HCVUSD]:57841 (system error: 10049 - The requested address is not valid in its context.).
TensorBoard: Start with 'tensorboard --logdir testing_error\train', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=9
Transferred 589/595 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "C:\Users\Lalit\AppData\Roaming\Ultralytics\DDP\_temp_vh7uzjv71662667013856.py", line 12, in <module>
    results = trainer.train()
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\trainer.py", line 190, in train
    self._do_train(world_size)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\trainer.py", line 286, in _do_train
    self._setup_train(world_size)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\trainer.py", line 235, in _setup_train    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\distributed_c10d.py", line 1574, in broadcast
    work.wait()
RuntimeError: Invalid scalar type
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21384 closing signal CTRL_C_EVENT
Traceback (most recent call last):
  File "C:\Users\Lalit\AppData\Roaming\Ultralytics\DDP\_temp_vh7uzjv71662667013856.py", line 12, in <module>
    results = trainer.train()
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\trainer.py", line 190, in train
    self._do_train(world_size)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\trainer.py", line 286, in _do_train
    self._setup_train(world_size)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\trainer.py", line 232, in _setup_train    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\utils\checks.py", line 577, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\utils\checks.py", line 565, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.data  # FP32 inference
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\model.py", line 98, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\predictor.py", line 311, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\nn\autobackend.py", line 115, in __init__
    model = model.fuse(verbose=verbose) if fuse else model
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\nn\tasks.py", line 129, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\utils\torch_utils.py", line 172, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
KeyboardInterrupt
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
Traceback (most recent call last):
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\run.py", line 798, in <module>
    main()
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\launcher\api.py", line 241, in launch_agent
    result = agent.run()
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 723, in run
    result = self._invoke_run(role)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 865, in _invoke_run
    run_result = self._monitor_workers(self._worker_group)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\agent\server\local_elastic_agent.py", line 306, in _monitor_workers
    result = self._pcontext.wait(0)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 288, in wait
    return self._poll()
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 664, in _poll
    self.close()  # terminate all running procs
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 331, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 708, in _close
    handler.proc.wait(time_to_wait)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\subprocess.py", line 1486, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\torch\distributed\elastic\multiprocessing\api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 44668 got signal: 2
Traceback (most recent call last):
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lalit\.conda\envs\trainYolo\Scripts\yolo.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\cfg\__init__.py", line 444, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\model.py", line 338, in train
    self.trainer.train()
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\site-packages\ultralytics\engine\trainer.py", line 183, in train
    subprocess.run(cmd, check=True)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\subprocess.py", line 1126, in communicate
    self.wait()
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\Lalit\.conda\envs\trainYolo\lib\subprocess.py", line 1486, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
KeyboardInterrupt
```

### Environment

```
(trainYolo)PS D:\Lalit> yolo checks
Ultralytics YOLOv8.0.206  Python-3.9.18 torch-2.0.1 CUDA:0 (Tesla T4, 15198MiB)
Setup complete  (192 CPUs, 1023.7 GB RAM, 4534.6/6706.7 GB disk)

OS                  Windows-10-10.0.17763-SP0
Environment         Windows
Python              3.9.18
Install             pip
RAM                 1023.66 GB
CPU                 Intel Xeon Gold 6252N 2.30GHz
CUDA                11.7

matplotlib           3.8.1>=3.3.0
numpy                1.26.0>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               10.0.1>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.11.3>=1.4.1
torch                2.0.1>=1.8.0
torchvision          0.15.2>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.2>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.0
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1
(trainYolo)PS D:\Lalit> nvidia-smi
Mon Nov 13 16:45:40 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.24       Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4           TCC   | 00000000:1A:00.0 Off |                    0 |
| N/A   70C    P0    74W /  70W |  12968MiB / 15360MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4           TCC   | 00000000:4E:00.0 Off |                    0 |
| N/A   32C    P8    11W /  70W |      1MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     30420      C   ...envs\trainYolo\python.exe    12964MiB |
+-----------------------------------------------------------------------------+

```

### Minimal Reproducible Example

```
yolo detect train data="D:/Lalit/datasets/data_augmented.yaml" model=yolov8x.pt cache=True epochs=500 imgsz=640 device=0,1 project="testing_error"
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Lalit-Dumka the error you are encountering suggests there might be issues with multi-GPU training on Windows with the distributed data parallel (DDP) setup. Currently, DDP is indeed more stable and better supported on Linux systems. Here, we can explore a couple of options to mitigate this issue:

1. **Update PyTorch and Supporting Libraries**: Ensure you are using the latest stable versions of PyTorch and the relevant libraries. Compatibility and bug fixes in newer versions might resolve the issue.

2. **Check Network Configuration**: The error `The requested address is not valid in its context.` indicates a potential network configuration problem. Ensure the system’s host file is properly configured and the network is allowing the DDP processes to communicate.

3. **Run as Administrator**: Running the command prompt or PowerShell as an Administrator can sometimes resolve permissions issues that may affect multi-GPU training.

4. **Use a Single GPU**: Given that single GPU training is working for you, consider continuing with device=0 if you cannot resolve the multi-GPU issue on Windows, or explore the option of using a Linux system for multi-GPU training.

5. **Debug using Print Statements**: You may benefit from adding print statements in the DDP initialization section of the code to understand better where the connection is failing.

6. **Environment Variables**: Try setting the `MASTER_ADDR` and `MASTER_PORT` environment variables to suitable values before running your training script. This can sometimes resolve connection issues with DDP on Windows.

7. **Windows Limitations**: Due to potential limitations with Windows support for certain distributed training features, if none of the above steps resolve the issue, it may be worthwhile to move your training to a Linux environment, which generally has better support for these operations.

Since this could be an operating system level issue or perhaps a PyTorch-specific one on Windows, you may also want to check PyTorch forums or GitHub issues for similar reports and potential bug fixes.

For more assistance, you might want to review the documentation available at https://docs.ultralytics.com, which provides comprehensive details on setup and troubleshooting. If after trying the above steps the issue persists, consider opening an issue on PyTorch’s GitHub page, as this might be related to their DDP implementation on Windows.

Finally, if you keep facing issues or need further assistance, feel free to follow up with more details, including any new error messages or the outcomes of your troubleshooting efforts.
