### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items' Sentry is attempting to send 2 pending error messages

### ISSUE THREAD

**Issue by totoadel** [ultralytics/ultralytics#639]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

i do traning on colab and i got this error 
```
`Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8n.yaml, data=/content/data.yaml, epochs=120, patience=50, batch=16, imgsz=416, save=True, cache=False, device=, workers=8, project=/content/drive/MyDrive/yolov8, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=/content/drive/MyDrive/yolov8/train2
Overriding model.yaml nc=80 with nc=72

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]                 
 22        [15, 18, 21]  1    828808  ultralytics.nn.modules.Detect                [72, [64, 128, 256]]          
Model summary: 225 layers, 3088344 parameters, 3088328 gradients, 8.5 GFLOPs

Transferred 319/355 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.001), 63 bias
train: Scanning /content/content/labels/train.cache... 32995 images, 5 backgrounds, 0 corrupt: 100% 33000/33000 [00:00<?, ?it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /content/content/labels/valid... 8179 images, 0 backgrounds, 0 corrupt: 100% 8179/8179 [00:18<00:00, 433.11it/s]
val: New cache created: /content/content/labels/valid.cache
Image sizes 416 train, 416 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/yolov8/train2
Starting training for 120 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/120      1.39G     0.9684      1.943      1.112         18        416: 100% 2063/2063 [20:19<00:00,  1.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 256/256 [01:50<00:00,  2.32it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/content/ultralytics/ultralytics/yolo/cfg/__init__.py", line 249, in entrypoint
    getattr(model, mode)(verbose=True, **overrides)
  File "/content/ultralytics/ultralytics/yolo/engine/model.py", line 207, in train
    self.trainer.train()
  File "/content/ultralytics/ultralytics/yolo/engine/trainer.py", line 183, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/content/ultralytics/ultralytics/yolo/engine/trainer.py", line 342, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/content/ultralytics/ultralytics/yolo/engine/trainer.py", line 437, in validate
    metrics = self.validator(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/ultralytics/ultralytics/yolo/engine/validator.py", line 161, in __call__
    stats = self.get_stats()
  File "/content/ultralytics/ultralytics/yolo/v8/detect/val.py", line 120, in get_stats
    self.metrics.process(*stats)
  File "/content/ultralytics/ultralytics/yolo/utils/metrics.py", line 506, in process
    results = ap_per_class(tp, conf, pred_cls, target_cls, plot=self.plot, save_dir=self.save_dir,
  File "/content/ultralytics/ultralytics/yolo/utils/metrics.py", line 398, in ap_per_class
    names = [v for k, v in names.items() if k in unique_classes]  # list: only classes that have data
AttributeError: 'str' object has no attribute 'items'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit`
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@totoadel it looks like your dataset names field is incorrect. This should be a dictionary of class names like this:

https://github.com/ultralytics/ultralytics/blob/15b3b0365ab2f12993a58985f3cb7f2137409a0c/ultralytics/yolo/data/datasets/coco128.yaml#L15-L23

**Comment by Tolgaisikp** [comment]
I'm experiencing the same thing, as @glenn-jocher  said, when I do it, it gives an error directly

**Comment by totoadel** [comment]
@Tolgaisikp I solve the issue , the problem is with the space after (:) you should add space after it like 

1: bear
Not like this
1:bear

**Comment by Tolgaisikp** [comment]
When I try this way, I get the following error

**RuntimeError: CUDA error: device-side assert triggered
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds**

**Comment by xx-xxx** [comment]
@VYRION-Ai nice!!you are right!you are right!

**Comment by myusernamedm** [comment]
> @Tolgaisikp I solve the issue , the problem is with the space after (:) you should add space after it like
> 
> 1: bear Not like this 1:bear

Thank you!!
