### ISSUE TITLE
Type Error in Yolov8 files while trying to train model

### ISSUE THREAD

**Issue by Cristofhersj** [ultralytics/ultralytics#649]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I am trying to train a model using YOLOv8 in jupyter.
I already made the same thing on google colab but I was trying to run it locally to learn how to do it.
However when I run the train command i get the following error:

Transferred 349/355 items from pretrained weights
Traceback (most recent call last):
  File "C:\Users\csolis\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\csolis\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\csolis\Anaconda3\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\csolis\Anaconda3\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 249, in entrypoint
    getattr(model, mode)(verbose=True, **overrides)
  File "C:\Users\csolis\Anaconda3\lib\site-packages\ultralytics\yolo\engine\model.py", line 207, in train
    self.trainer.train()
  File "C:\Users\csolis\Anaconda3\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 183, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "C:\Users\csolis\Anaconda3\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 248, in _do_train
    self._setup_train(rank, world_size)
  File "C:\Users\csolis\Anaconda3\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 206, in _setup_train
    self.args.imgsz = check_imgsz(self.args.imgsz, stride=gs, floor=gs)
  File "C:\Users\csolis\Anaconda3\lib\site-packages\ultralytics\yolo\utils\checks.py", line 64, in check_imgsz
    sz = [max(math.ceil(x / stride) * stride, floor) for x in imgsz]
  File "C:\Users\csolis\Anaconda3\lib\site-packages\ultralytics\yolo\utils\checks.py", line 64, in <listcomp>
    sz = [max(math.ceil(x / stride) * stride, floor) for x in imgsz]
TypeError: unsupported operand type(s) for /: 'str' and 'int'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit

Am I messing up something in the yaml file or is it a bug in the yolo files?

### Additional

![image](https://user-images.githubusercontent.com/71050835/214862124-7c95d8d1-c336-461c-8a2c-d2a6771db960.png)
![image](https://user-images.githubusercontent.com/71050835/214862231-fd3c5edf-ab2c-49cd-98be-412318226dba.png)

**Comment by Paulkie99** [comment]
I have a similar issue.

**Comment by Laughing-q** [comment]
@Cristofhersj looks you typed an extra `)` to the `imgsz` in your training command.
![mn0XaIiaks](https://user-images.githubusercontent.com/61612323/215436065-ad102923-1f05-4c57-bfbe-ad01e4145a84.jpg)
