### ISSUE TITLE
AttributeError: 'YoloNAS_S' object has no attribute 'get'

### ISSUE THREAD

**Issue by manoj-samal** [ultralytics/ultralytics#6522]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 yolo predict model=yolo_nas_s.pt  source='/home/input_videos/'
 
```


The console stream is logged into /root/sg_logs/console.log
[2023-11-22 17:56:02] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-11-22 17:56:02] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-11-22 17:56:03] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-11-22 17:56:03] WARNING - export.py - Failed to import pytorch_quantization
[2023-11-22 17:56:03] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-11-22 17:56:03] INFO - env_sanity_check.py - Library check is not supported when super_gradients installed through "git+https://github.com/..." command
Traceback (most recent call last):
  File "/home/TCL_env/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 419, in entrypoint
    model = YOLO(model, task=task)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 97, in __init__
    self._load(model, task)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 149, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 629, in attempt_load_one_weight
    args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))}  # combine model and default args, preferring model args
  File "/home/TCL_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YoloNAS_S' object has no attribute 'get'
```

### Additional
 when i ran i got the following error in python 3.8.0
any idea why..?

**Comment by glenn-jocher** [comment]
@manoj-samal hello! Based on the error message you provided, it looks like there might be an issue with the checkpoint file (`yolo_nas_s.pt`) you are trying to load for predictions. Specifically, the attribute error suggests that when trying to access the `'get'` method on the `YoloNAS_S` object, this method is not found, which could imply that the object is not in the expected state or perhaps the checkpoint file could be corrupted or not properly loaded.

Here's what you can do to troubleshoot this issue:

1. Verify the checkpoint file: Ensure that the `.pt` file you're attempting to load isn't corrupted and is indeed a proper model weight file.

2. Model Compatibility: Ensure that the model architecture `YoloNAS_S` is compatible with the version of the software you're running. You might want to update your checkout if there have been recent changes.

3. Environment Check: Make sure that your Python environment has all the necessary dependencies properly installed and that there are no conflicts.

4. Re-download or Re-train: If the issue persists, try re-downloading the weights if you got them from a source or retrain the model if you trained it yourself to ensure that the weights are saved correctly.

5. Consult Docs: For more detailed guidance, please refer to the Ultralytics Documentation under the Predict section for precise instructions on how to run predictions with trained models.

If after following these steps the issue persists, you can raise an issue on the Ultralytics GitHub with detailed information about your environment, the steps you've taken, and the full traceback, so that the community can better assist you. Please remember to remove any sensitive information from your logs before sharing them publicly.

Best of luck resolving the issue! 🤖
