### ISSUE TITLE
passing device=0 takes '2'

### ISSUE THREAD

**Issue by harufumigithub** [ultralytics/ultralytics#6646]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

python train.py 

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1   1008370  ultralytics.nn.modules.head.Segment          [22, 32, 64, [64, 128, 256]]  
YOLOv8n-seg_custom summary: 261 layers, 3267906 parameters, 3267890 gradients, 12.1 GFLOPs

New https://pypi.org/project/ultralytics/8.0.220 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.219 🚀 Python-3.11.5 torch-2.1.0+cu121 
Traceback (most recent call last):
  File "/mnt/workspace/yolov8/train.py", line 33, in <module>
    results = model.train(resume=True, data="./all_logo_tag_seg.yaml", device=0, imgsz=640, epochs=2000, batch=-1)  
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nucx/workspace/yolov8/ultralytics/engine/model.py", line 333, in train
    self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nucx/workspace/yolov8/ultralytics/models/yolo/segment/train.py", line 30, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/home/nucx/workspace/yolov8/ultralytics/engine/trainer.py", line 83, in __init__
    self.device = select_device(self.args.device, self.args.batch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nucx/workspace/yolov8/ultralytics/utils/torch_utils.py", line 119, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=2' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

### Minimal Reproducible Example

from ultralytics import YOLO
from ultralytics.utils import tuner

model = YOLO('yolov8n-seg_custom.yaml')
model = YOLO('yolov8n-seg.pt') 

results = model.train(resume=True, data="./seg.yaml", device=0, imgsz=640, epochs=200, batch=-1)  

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by harufumigithub** [comment]
results = model.train(resume=True, data="./all_logo_tag_seg.yaml", device=0, imgsz=640, epochs=2000, batch=-1)

When I removed resume=True, it worked fine.
