### ISSUE TITLE
resume error!

### ISSUE THREAD

**Issue by sunmooncode** [ultralytics/ultralytics#6655]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```
`New https://pypi.org/project/ultralytics/8.0.220 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.218 🚀 Python-3.8.17 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12045MiB)
                                                            CUDA:1 (NVIDIA GeForce RTX 3080 Ti, 12045MiB)
                                                            CUDA:2 (NVIDIA GeForce RTX 3080 Ti, 12045MiB)
                                                            CUDA:3 (NVIDIA GeForce RTX 3080 Ti, 12042MiB)
engine/trainer: task=detect, mode=train, model=runs/dp_three_phase_train/weights/last.pt, data=data/dp_three_phase_data.yaml, epochs=300, patience=20, batch=64, imgsz=640, save=True, save_period=-1, cache=False, device=0,1,2,3, workers=4, project=runs/, name=dp_three_phase_train, exist_ok=False, pretrained=weights/yolov8m-oiv7.pt, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=15, **resume=False**, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=0.75, iou=0.5, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.001, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=128, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.5, fliplr=0.5, mosaic=1.0, mixup=0.8, copy_paste=0.6, cfg=None, tracker=botsort.yaml, save_dir=runs/dp_three_phase_train
DDP: debug command /home/archie/anaconda3/envs/yolov8/bin/python -m torch.distributed.run --nproc_per_node 4 --master_port 51183 /home/archie/.config/Ultralytics/DDP/_temp_ihawszo_140396530669456.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.0.220 🚀 Python-3.8.17 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12045MiB)
                                                            CUDA:1 (NVIDIA GeForce RTX 3080 Ti, 12045MiB)
                                                            CUDA:2 (NVIDIA GeForce RTX 3080 Ti, 12045MiB)
                                                            CUDA:3 (NVIDIA GeForce RTX 3080 Ti, 12042MiB)
TensorBoard: Start with 'tensorboard --logdir runs/dp_three_phase_train', view at http://localhost:6006/
Traceback (most recent call last):
  File "/home/archie/.config/Ultralytics/DDP/_temp_ihawszo_140396530669456.py", line 12, in <module>
    results = trainer.train()
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 286, in _do_train
    self._setup_train(world_size)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 209, in _setup_train
    ckpt = self.setup_model()
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 456, in setup_model
    weights, ckpt = attempt_load_one_weight(model)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 628, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 567, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/dp_three_phase_train/weights/last.pt'
Traceback (most recent call last):
  File "/home/archie/.config/Ultralytics/DDP/_temp_ihawszo_140396530669456.py", line 12, in <module>
    results = trainer.train()
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 286, in _do_train
    self._setup_train(world_size)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 209, in _setup_train
    ckpt = self.setup_model()
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 456, in setup_model
    weights, ckpt = attempt_load_one_weight(model)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 628, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 567, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/dp_three_phase_train/weights/last.pt'
Traceback (most recent call last):
  File "/home/archie/.config/Ultralytics/DDP/_temp_ihawszo_140396530669456.py", line 12, in <module>
    results = trainer.train()
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 286, in _do_train
    self._setup_train(world_size)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 209, in _setup_train
    ckpt = self.setup_model()
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 456, in setup_model
    weights, ckpt = attempt_load_one_weight(model)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 628, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 567, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/dp_three_phase_train/weights/last.pt'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 23686 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 23691 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 23694 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 23695) of binary: /home/archie/anaconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/archie/.config/Ultralytics/DDP/_temp_ihawszo_140396530669456.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-29_18:48:39
  host      : archie-X299-WU8
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 23695)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "resume_threee.py", line 7, in <module>
    results=model.train(resume=True)
  File "/home/archie/object_detection/ultralytics/ultralytics/engine/model.py", line 338, in train
    self.trainer.train()
  File "/home/archie/object_detection/ultralytics/ultralytics/engine/trainer.py", line 185, in train
    raise e
  File "/home/archie/object_detection/ultralytics/ultralytics/engine/trainer.py", line 183, in train
    subprocess.run(cmd, check=True)
  File "/home/archie/anaconda3/envs/yolov8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/archie/anaconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '51183', '/home/archie/.config/Ultralytics/DDP/_temp_ihawszo_140396530669456.py']' returned non-zero exit status 1.`

```

### Minimal Reproducible Example

When I use 'resume=true', I encounter an issue where the model does not retrain but formats the directory and creates a new one. Does anyone know the reason for this?

```
from ultralytics import YOLO

model = YOLO("runs/dp_three_phase_train/weights/last.pt")

results=model.train(resume=True)
```

### Additional

```
Package                    Version
-------------------------- --------------------
absl-py                    1.4.0
aiosignal                  1.3.1
aliyun-python-sdk-core     2.14.0
aliyun-python-sdk-kms      2.16.2
anyio                      4.0.0
asgiref                    3.6.0
astor                      0.8.1
asttokens                  2.2.1
async-timeout              4.0.3
attrdict                   2.0.1
attrs                      23.1.0
Babel                      2.9.1
backcall                   0.2.0
backports.zoneinfo         0.2.1
bce-python-sdk             0.8.64
beautifulsoup4             4.12.2
blessed                    1.20.0
blinker                    1.7.0
build                      0.10.0
cachetools                 5.0.0
certifi                    2023.5.7
cffi                       1.16.0
cfgv                       3.3.1
charset-normalizer         3.2.0
check-manifest             0.49
click                      8.1.7
cmake                      3.25.0
colorama                   0.4.4
coloredlogs                15.0.1
colorlog                   6.6.0
coverage                   7.3.0
crcmod                     1.7
cryptography               41.0.5
cssselect                  1.1.0
cssutils                   2.3.0
cycler                     0.11.0
Cython                     0.29.27
decorator                  5.1.1
dill                       0.3.4
distlib                    0.3.4
Django                     4.2
dnspython                  2.4.2
easyocr                    1.7.1
et-xmlfile                 1.1.0
exceptiongroup             1.1.3
executing                  1.2.0
filelock                   3.5.0
fire                       0.5.0
flake8                     4.0.1
Flask                      3.0.0
Flask-Babel                2.0.0
flatbuffers                23.5.26
fonttools                  4.29.1
frozenlist                 1.4.0
fsspec                     2023.6.0
func-timeout               4.3.5
future                     0.18.3
ghp-import                 2.1.0
google-auth                2.17.3
google-auth-oauthlib       1.0.0
gpustat                    1.1
griffe                     0.34.0
grpcio                     1.59.2
grpcio-tools               1.59.2
h11                        0.14.0
h5py                       3.6.0
httpcore                   1.0.1
httpx                      0.25.1
huggingface-hub            0.16.4
humanfriendly              10.0
identify                   2.4.10
idna                       3.4
imageio                    2.16.0
imbalanced-learn           0.11.0
imgaug                     0.4.0
importlib-metadata         6.1.0
importlib-resources        6.0.1
iniconfig                  2.0.0
ipython                    8.12.2
itsdangerous               2.1.2
jedi                       0.19.0
jieba                      0.42.1
Jinja2                     3.1.2
jmespath                   0.10.0
joblib                     1.3.2
jsonschema                 4.19.0
jsonschema-specifications  2023.7.1
kiwisolver                 1.3.2
lit                        15.0.7
lmdb                       1.3.0
loguru                     0.7.2
lxml                       4.7.1
Markdown                   3.4.3
markdown-it-py             3.0.0
MarkupSafe                 2.1.3
matplotlib                 3.5.1
matplotlib-inline          0.1.6
mccabe                     0.6.1
mdurl                      0.1.1
mergedeep                  1.3.4
mkdocs                     1.5.2
mkdocs-autorefs            0.5.0
mkdocs-material            9.1.21
mkdocs-material-extensions 1.1.1
mkdocs-redirects           1.2.1
mkdocs-ultralytics-plugin  0.0.27
mkdocstrings               0.22.0
mkdocstrings-python        1.5.0
mpmath                     1.2.1
msgpack                    1.0.5
multiprocess               0.70.12.2
networkx                   2.6.3
ninja                      1.11.1.1
nodeenv                    1.6.0
numpy                      1.24.4
nvidia-cublas-cu12         12.3.2.9
nvidia-cuda-nvrtc-cu12     12.3.52
nvidia-cuda-runtime-cu12   12.3.52
nvidia-cudnn-cu12          8.9.6.50
nvidia-ml-py               12.535.77
nvidia-pyindex             1.0.9
nvidia-tensorrt            99.0.0
oauthlib                   3.2.2
onnx                       1.15.0
onnxruntime-gpu            1.16.1
onnxsim                    0.4.35
opencv-contrib-python      4.4.0.46
opencv-python              4.6.0.66
opencv-python-headless     4.8.1.78
openpyxl                   3.0.9
opt-einsum                 3.3.0
oss2                       2.18.3
packaging                  21.3
paddlenlp                  2.2.4
paddleocr                  2.7.0.3
paddlepaddle               2.5.2
pandas                     1.4.1
parso                      0.8.3
pathspec                   0.11.2
pdf2docx                   0.5.5
pexpect                    4.8.0
pickleshare                0.7.5
Pillow                     10.0.0
pip                        23.3.1
pkgutil_resolve_name       1.3.10
platformdirs               2.5.0
pluggy                     1.2.0
pre-commit                 2.17.0
premailer                  3.10.0
prompt-toolkit             3.0.39
protobuf                   4.25.0
psutil                     5.9.5
ptyprocess                 0.7.0
pure-eval                  0.2.2
py-cpuinfo                 9.0.0
pyarrow                    13.0.0
pyasn1                     0.4.8
pyasn1-modules             0.2.8
pyclipper                  1.3.0.post2
pycodestyle                2.8.0
pycparser                  2.21
pycryptodome               3.14.1
pydantic                   1.8.2
pyflakes                   2.4.0
Pygments                   2.16.1
pymdown-extensions         10.1
pymongo                    4.6.0
PyMuPDF                    1.20.2
pyparsing                  3.1.1
pyproject_hooks            1.0.0
pytest                     7.4.0
pytest-cov                 4.1.0
python-bidi                0.4.2
python-dateutil            2.8.2
python-docx                1.1.0
python-Levenshtein         0.12.2
pythonic-spring            0.0.1.2
pytz                       2023.3
PyWavelets                 1.2.0
PyYAML                     6.0.1
pyyaml_env_tag             0.1
rapidfuzz                  3.5.2
ray                        2.6.3
redis                      5.0.1
referencing                0.30.2
regex                      2023.8.8
requests                   2.31.0
requests-oauthlib          1.3.1
rich                       13.6.0
rpds-py                    0.10.0
rsa                        4.9
safetensors                0.3.2
scikit-image               0.19.1
scikit-learn               1.0.2
scipy                      1.8.0
seaborn                    0.12.2
sentencepiece              0.1.91
seqeval                    1.2.2
setuptools                 68.0.0
Shapely                    1.8.0
shellcheck-py              0.8.0.4
six                        1.16.0
sniffio                    1.3.0
some-package               0.1
soupsieve                  2.4.1
sqlparse                   0.4.3
stack-data                 0.6.2
sympy                      1.11.1
tensorboard                2.12.2
tensorboard-data-server    0.7.0
tensorboard-plugin-wit     1.8.1
tensorboardX               2.6.2.2
tensorrt                   8.6.1.post1
tensorrt-bindings          8.6.1
tensorrt-libs              8.6.1
termcolor                  2.3.0
thop                       0.1.1.post2209072238
threadpoolctl              3.1.0
tifffile                   2022.2.9
timm                       0.9.5
toml                       0.10.2
tomli                      2.0.1
torch                      2.0.1+cu118
torchaudio                 2.0.2+cu118
torchsampler               0.1.2
torchvision                0.15.2+cu118
tqdm                       4.65.0
traitlets                  5.9.0
triton                     2.0.0
typing_extensions          4.7.1
ultralytics                8.0.220
urllib3                    2.0.3
uWSGI                      2.0.21
virtualenv                 20.13.1
visualdl                   2.2.3
watchdog                   3.0.0
wcwidth                    0.2.6
Werkzeug                   3.0.1
wheel                      0.40.0
zipp                       3.15.0

```
### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by sunmooncode** [comment]
The resume parameter has not been overridden and remains false.

**Comment by sunmooncode** [comment]
After commenting out [this line](https://github.com/ultralytics/ultralytics/blob/9c6989a1b0d0b94c51eacf7cb123c028145b224e/ultralytics/engine/trainer.py#L124), the resume is able to function properly. I am unsure of the specific reason.

**Comment by glenn-jocher** [comment]
@sunmooncode hello! Thanks for bringing this to our attention. 👍 If the resume functionality is not working as expected, it could potentially be an issue with how the state is being saved and loaded. The line you referenced is likely involved with setting up the resumption behavior. It's possible that there is a bug or a misconfiguration that could be preventing the resume from working correctly.

To proceed with this, if you'd like to help by submitting a PR, we would certainly welcome your contribution. Please ensure that the changes you make are thoroughly tested to not affect other parts of the training workflow. If you're not familiar with the process, reviewing our contribution guidelines could be helpful before you begin.

Also, make sure to pull the latest updates from the repository and test if the issue persists with the most current version. In the meantime, the team will also look into the resume behavior to verify its functionality and make any necessary adjustments.

We appreciate your involvement and are looking forward to your PR. Let’s keep improving YOLOv8 together! 🚀
