### ISSUE TITLE
DDP training fails with custom subclass trainer

### ISSUE THREAD

**Issue by Rusteam** [ultralytics/ultralytics#6682]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

For a little customization I've extended `DetectionTrainer` class, however in the ddp mode I can see that this file is generated:
```
    module, name = f'{trainer.__class__.__module__}.{trainer.__class__.__name__}'.rsplit('.', 1)

    content = f'''overrides = {vars(trainer.args)} \nif __name__ == "__main__":
    from {module} import {name}
    from ultralytics.utils import DEFAULT_CFG_DICT

    cfg = DEFAULT_CFG_DICT.copy()
    cfg.update(save_dir='')   # handle the extra key 'save_dir'
    trainer = {name}(cfg=cfg, overrides=overrides)
    trainer.train()'''
```
which fails with the following error:
```
Traceback (most recent call last):
  File "/home/appuser/.config/Ultralytics/DDP/_temp_4lx_1hnj139623173760256.py", line 6, in <module>
    from src.models.ultra_utils import YoloDetectionTrainer
ModuleNotFoundError: No module named 'src'
```
and it makes sense because the module and class name are custom from the `src` folder. Is there a way to fix it? 

My customization are basically custom `raytune` and `mlflow` callbacks because the already existing ones do not completely match my needs.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Rusteam hello there! 👋

It's great to hear that you're extending the `DetectionTrainer` class for your custom needs. The issue you're encountering with Distributed Data Parallel (DDP) training and your subclass is understood.

DDP expects the trainer object to be present in the module where it's defined. When you extend the `DetectionTrainer`, you need to ensure that the subclass can be imported correctly in the distributed training script. If the module path doesn't align with the expected structure, you'll encounter such import errors as the module isn't found by Python.

To address this, make sure that the directory containing your subclass (`src` in your case) is a package (it should contain an `__init__.py` file), and that this directory is accessible in your `PYTHONPATH`. This way, the generated temporary DDP script can import your custom class without issue.

For further customization, especially in terms of integrating third-party tools like `raytune` and `mlflow`, ensure that your subclass handles any necessary environment variable configurations or initialization routines that might be required when launching DDP training.

If you continue to experience difficulties, don't hesitate to submit an issue with details on what you've tried. If you're willing to tackle this with a Pull Request, that's fantastic! Contributions that enhance flexibility, like ensuring compatibility with custom subclass trainers in DDP mode, can be beneficial for the whole community.

Happy coding, and thanks for being an active member of the community! 🚀

**Comment by Rusteam** [comment]
thanks, adding my code path to `PYTHONPATH` fixed this issue, although I've run into another issue:

```
Starting training for 3 epochs...
  0%|          | 0/46 [00:00<?, ?it/s]
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/3       6.8G        1.4      2.541      1.052         56        640:  98%|█████████▊| 45/46 [00:11<00:00,  4.42it/s]Traceback (most recent call last):
  File "/home/appuser/.config/Ultralytics/DDP/_temp_e9liq5d1139891273586560.py", line 12, in <module>
    results = trainer.train()
  File "/home/appuser/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/appuser/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 391, in _do_train
Traceback (most recent call last):
  File "/home/appuser/.config/Ultralytics/DDP/_temp_e9liq5d1139891273586560.py", line 12, in <module>
    self.run_callbacks('on_fit_epoch_end')
  File "/home/appuser/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 155, in run_callbacks
    results = trainer.train()
  File "/home/appuser/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 190, in train
    callback(self)
  File "/app/src/models/ultra_utils.py", line 125, in on_fit_epoch_end
    k.split("/")[-1].rstrip("(B)"): float(v) for k, v in trainer.metrics.items()
AttributeError: 'NoneType' object has no attribute 'items'    self._do_train(world_size)
``` as if `trainer.metrics` does not return a dictionary of metrics

**Comment by glenn-jocher** [comment]
@Rusteam, pleased to hear that adding your code path to the `PYTHONPATH` resolved the initial issue! 👍

This new error you've encountered suggests that there might be a problem in accessing `trainer.metrics` after an epoch ends. It's possible that `trainer.metrics` is not being populated as expected, which could happen for a variety of reasons.

Without access to your specific code modifications, it's a bit challenging to pinpoint the exact cause. However, here are a few steps to consider:

1. **Check Trainer State**: Ensure that the `trainer.metrics` attribute is properly initialized and updated during training. There may be a condition or logic path within your custom `DetectionTrainer` subclass that results in `trainer.metrics` being `None` or not updated as it should be.

2. **Debugging**: Place strategic debug statements or breakpoints in your custom callback to verify the state of `trainer.metrics` when `on_fit_epoch_end` is called. Inspect not only the value of `trainer.metrics` but also when and how it's being modified throughout the epoch.

3. **Inheritance & Overrides**: Verify that you've correctly inherited methods from the base `DetectionTrainer` class and that any methods you've overridden are still performing the necessary base class functionality, including updating metrics.

4. **Synchronization Issues**: In DDP, ensure that your metrics are being correctly synchronized across processes. DDP can sometimes introduce complications when sharing state between parallel workers.

If after investigating you find that the metrics are indeed not being populated or synchronized as expected, you may need to adjust your subclass to properly manage the `metrics` during the distributed training lifecycle.

We always appreciate community members helping to improve the robustness of training, especially when it comes to advanced customizations like the ones you're implementing. If you believe there's a broader issue with how `metrics` are handled in DDP, or with other aspects of the training loop, please feel free to open a detailed issue report or to contribute improvements. Remember to include specific information regarding the conditions and code paths that lead to the `trainer.metrics` being `None`.

Thank you again for your active engagement and for helping make YOLOv8 better! 🌟

**Comment by Rusteam** [comment]
Hi @glenn-jocher 

What do you think about extending a default behavior of mlflow/clearml callbacks? 

In particular, I want to:
1. Log only the params I set, ignoring many others.
2. Run test eval after completing training and log test metrics.
3. If test results above a certain threshold, I'd like to export the model to onnx and log it as a model and log pytorch as a checkpoint only.

Of course, I can create my own fork and move on, but do you think these changes will be valuable to the community? If so, what will be the best way to alter the default behaviour?

**Comment by glenn-jocher** [comment]
Hi @Rusteam,

Extending the functionality of callbacks for MLflow/ClearML could indeed be valuable for users with workflow specifics similar to yours. Here’s how I suggest approaching this:

1. **Selective Logging**: Modifying callbacks to log only certain parameters is certainly a user-specific feature. It would be best implemented with an option in the callback initialization to specify which parameters to log.

2. **Post-Training Evaluation**: Adding a feature to run a test evaluation after training and log the metrics aligns well with common workflows and could benefit many users.

3. **Conditional Model Exporting**: The ability to automatically export a model to ONNX (and log it) based on test result thresholds is an advanced feature that some users may find useful.

The best practice for altering default behavior while maintaining community benefit is often through configuration options or flags. This way, you can avoid affecting users who prefer the existing behavior while still contributing enhancements.

If you're confident these features can be generalized and are willing to implement them in an optional and non-disruptive way, I believe they could be excellent contributions to the repo. Feel free to open an issue to discuss these insights or submit a PR with your proposed changes for further review.

Thank you for your initiative and consideration for the community's needs! 😊👍
