### ISSUE TITLE
    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

### ISSUE THREAD

**Issue by prada-hvh** [ultralytics/ultralytics#6723]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Model loaded. None
Traceback (most recent call last):
  File "C:\Users\mofa\Desktop\yolik\main.py", line 145, in <module>
    init()
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mofa\Desktop\yolik\main.py", line 86, in init
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 234, in predict
    self.predictor = (predictor or self._smart_load('predictor'))(overrides=args, _callbacks=self.callbacks)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 86, in __init__
    self.args = get_cfg(cfg, overrides)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 113, in get_cfg
    check_dict_alignment(cfg, overrides)
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 202, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'show_boxes' is not a valid YOLO argument. Similar arguments are i.e. ['show_labels=True', 'boxes=True', 'show_conf=True'].

    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

   

### Environment

Ultralytics YOLOv8.0.205  Python-3.11.6 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
Setup complete  (8 CPUs, 15.9 GB RAM, 196.4/475.8 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 15.94 GB
CPU                 Intel Core(TM) i3-10100F 3.60GHz
CUDA                12.1

matplotlib           3.8.1>=3.3.0
numpy                1.26.1>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               9.3.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.28.1>=2.23.0
scipy                1.11.3>=1.4.1
torch                2.1.0+cu121>=1.8.0
torchvision          0.16.0+cu121>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.2>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.6
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by prada-hvh** [comment]
pip install ultralytics
Requirement already satisfied: ultralytics in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (8.0.205)
Requirement already satisfied: matplotlib>=3.3.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (3.8.1)
Requirement already satisfied: numpy>=1.22.2 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (1.26.1)
Requirement already satisfied: opencv-python>=4.6.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (4.8.1.78)
Requirement already satisfied: pillow>=7.1.2 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (9.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (2.28.1)
Requirement already satisfied: scipy>=1.4.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (2.1.0+cu121)
Requirement already satisfied: torchvision>=0.9.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (0.16.0+cu121)
Requirement already satisfied: tqdm>=4.64.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (4.66.1)
Requirement already satisfied: pandas>=1.1.4 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (2.1.2)
Requirement already satisfied: seaborn>=0.11.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (0.13.0)
Requirement already satisfied: psutil in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (5.9.6)
Requirement already satisfied: py-cpuinfo in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (9.0.0)
Requirement already satisfied: thop>=0.1.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from ultralytics) (0.1.1.post2209072238)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (4.43.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.1.4->ultralytics) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.1.4->ultralytics) (2023.3)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.23.0->ultralytics) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.23.0->ultralytics) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.23.0->ultralytics) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.23.0->ultralytics) (2022.12.7)
Requirement already satisfied: filelock in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8.0->ultralytics) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8.0->ultralytics) (4.8.0)
Requirement already satisfied: sympy in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8.0->ultralytics) (1.12)
Requirement already satisfied: networkx in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8.0->ultralytics) (3.0)
Requirement already satisfied: jinja2 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.2)
Requirement already satisfied: fsspec in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.8.0->ultralytics) (2023.4.0)
Requirement already satisfied: colorama in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from tqdm>=4.64.0->ultralytics) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch>=1.8.0->ultralytics) (1.3.0)






pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (2.1.0+cu121)
Requirement already satisfied: torchvision in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (0.16.0+cu121)
Requirement already satisfied: torchaudio in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (2.1.0+cu121)
Requirement already satisfied: filelock in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch) (4.8.0)
Requirement already satisfied: sympy in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torch) (2023.4.0)
Requirement already satisfied: numpy in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torchvision) (1.26.1)
Requirement already satisfied: requests in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torchvision) (2.28.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from torchvision) (9.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests->torchvision) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in c:\users\mofa\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch) (1.3.0)

**Comment by Kayzwer** [comment]
looks like your ultralytics version is out dated, try `pip install -U ultralytics`

**Comment by glenn-jocher** [comment]
@Kayzwer hello! Based on the traceback you've provided, it looks like there's an argument issue with the 'show_boxes' configuration. This is not a valid argument in YOLOv8. To address this, make sure that you are using the correct argument names as the error message suggests alternatives such as 'show_labels=True', 'boxes=True', 'show_conf=True'.

Regarding the installation output you've posted, it seems like you've already installed the `ultralytics` package along with its dependencies correctly. If you think your version is outdated, you can update the package using the pip package manager with the command `pip install --upgrade ultralytics`. However, my main advice would be to focus on correcting the argument used in your YOLOv8 implementation as per the error message before considering an update.

If the issue persists after correcting the argument and you think the version mismatch could be a problem, try updating the package as previously mentioned and test your application again. Should you have any further questions, feel free to check the comprehensive documentation at https://docs.ultralytics.com or ask here. Good luck with your project! 🚀

**Comment by glenn-jocher** [comment]
@Kayzwer i apologize for the confusion. It appears there has been a misunderstanding, and I appreciate your patience.

To reiterate, the error you're encountering is due to an invalid argument 'show_boxes'. You should check your code and replace it with the correct argument as suggested in the error message, like 'show_labels', 'boxes', or 'show_conf', each followed by '=True' if you want to enable those visualizations.

About the version of the `ultralytics` package, if you encounter any functionality issues or you want to benefit from the latest features and improvements, updating the package might be useful. It can be done with the pip package manager using the command: `pip install --upgrade ultralytics`.

Should you need more information on how to use YOLOv8 or resolve any issues, please consult the documentation provided. For direct help with code or configuration settings, the issue tracker on the GitHub repo is available to you and our users for community support and guidance. Thank you for bringing this to our attention, and I hope your issue gets resolved swiftly! 🛠️
