### ISSUE TITLE
problem with multi-gpu training 

### ISSUE THREAD

**Issue by sidharthrai** [ultralytics/ultralytics#6871]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

model.train(data=yaml_file, epochs=500, name= 'test_500_epoch',device=[0, 1])  # train the model

Ultralytics YOLOv8.0.223 🚀 Python-3.10.12 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24215MiB)
                                                             CUDA:1 (NVIDIA GeForce RTX 4090, 24217MiB)
engine/trainer: task=segment, mode=train, model=/home/sidharth/Documents/straw_ident/data_sets/runs/segment/test4/weights/best.pt, data=/home/sidharth/Documents/straw_ident/data_sets/dec_6_yolo_all_classes/data.yaml, epochs=500, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=[0, 1], workers=8, project=None, name=test_500_epoch3, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/segment/test_500_epoch3

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]           
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]           
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]                 
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]                 
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]                
 22        [15, 18, 21]  1  12320060  ultralytics.nn.modules.head.Segment          [4, 32, 320, [320, 640, 640]] 
YOLOv8x-seg summary: 401 layers, 71754700 parameters, 71754684 gradients, 344.5 GFLOPs

Transferred 657/657 items from pretrained weights
DDP: debug command /home/sidharth/Documents/straw_ident/vEnv/bin/python3 -m torch.distributed.run --nproc_per_node 2 --master_port 59077 /home/sidharth/.config/Ultralytics/DDP/_temp__5p44c27139745033452704.py
Ultralytics YOLOv8.0.223 🚀 Python-3.10.12 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24215MiB)
                                                             CUDA:1 (NVIDIA GeForce RTX 4090, 24217MiB)
Transferred 657/657 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /home/sidharth/Documents/straw_ident/data_sets/dec_6_yolo_all_classes/train/labels.cache... 1287 images, 7 backgrounds, 0 corrupt: 100%|██████████| 1294/1294 [00:00<?, ?it/s]
val: Scanning /home/sidharth/Documents/straw_ident/data_sets/dec_6_yolo_all_classes/test/labels.cache... 109 images, 4 backgrounds, 0 corrupt: 100%|██████████| 113/113 [00:00<?, ?it/s]
Plotting labels to runs/segment/test_500_epoch3/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 106 weight(decay=0.0), 117 weight(decay=0.0005), 116 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 16 dataloader workers
Logging results to runs/segment/test_500_epoch3
Starting training for 500 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
     48/500      11.7G       1.38      3.169      1.476      1.367        540        640:  20%|█▉        | 16/81 [00:05<00:21,  3.07it/s]
Traceback (most recent call last):
  File "/home/sidharth/.config/Ultralytics/DDP/_temp__5p44c27139745033452704.py", line 12, in <module>
    results = trainer.train()
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 348, in _do_train
    self.optimizer_step()
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 467, in optimizer_step
    self.scaler.step(self.optimizer)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 416, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 315, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/sgd.py", line 79, in step
    momentum=group['momentum'],
KeyError: 'momentum'
Traceback (most recent call last):
  File "/home/sidharth/.config/Ultralytics/DDP/_temp__5p44c27139745033452704.py", line 12, in <module>
    results = trainer.train()
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 348, in _do_train
    self.optimizer_step()
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 467, in optimizer_step
    self.scaler.step(self.optimizer)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 416, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 315, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/optim/sgd.py", line 79, in step
    momentum=group['momentum'],
KeyError: 'momentum'
[2023-12-08 02:13:48,066] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 9270) of binary: /home/sidharth/Documents/straw_ident/vEnv/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sidharth/Documents/straw_ident/vEnv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/sidharth/.config/Ultralytics/DDP/_temp__5p44c27139745033452704.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-08_02:13:48
  host      : BAE1333
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 9271)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-08_02:13:48
  host      : BAE1333
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9270)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[14], line 1
----> 1 model.train(data=yaml_file, epochs=500, name= 'test_500_epoch',device=[0, 1])  # train the model

File ~/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/model.py:338, in Model.train(self, trainer, **kwargs)
    336     self.model = self.trainer.model
    337 self.trainer.hub_session = self.session  # attach optional HUB session
--> 338 self.trainer.train()
    339 # Update model and cfg after training
    340 if RANK in (-1, 0):

File ~/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py:185, in BaseTrainer.train(self)
    183     subprocess.run(cmd, check=True)
    184 except Exception as e:
--> 185     raise e
    186 finally:
    187     ddp_cleanup(self, str(file))

File ~/Documents/straw_ident/vEnv/lib/python3.10/site-packages/ultralytics/engine/trainer.py:183, in BaseTrainer.train(self)
    181 try:
    182     LOGGER.info(f'{colorstr("DDP:")} debug command {" ".join(cmd)}')
--> 183     subprocess.run(cmd, check=True)
    184 except Exception as e:
    185     raise e

File /usr/lib/python3.10/subprocess.py:526, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524     retcode = process.poll()
    525     if check and retcode:
--> 526         raise CalledProcessError(retcode, process.args,
    527                                  output=stdout, stderr=stderr)
    528 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['/home/sidharth/Documents/straw_ident/vEnv/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '59077', '/home/sidharth/.config/Ultralytics/DDP/_temp__5p44c27139745033452704.py']' returned non-zero exit status 1.

### Minimal Reproducible Example

model.train(data=yaml_file, epochs=100, name= 'test_500_epoch',device=[0, 1])  # train the model

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by sidharthrai** [comment]
I even tried 
import os
os.environ["OMP_NUM_THREADS"] = "3"
though system might not be getting enough threads as there was warning before. Seems like that was not the case
