### ISSUE TITLE
Export own model into engine but get invalid confidence point and class.

### ISSUE THREAD

**Issue by gooelepapa** [ultralytics/ultralytics#6941]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have encountered some issues recently while using YOLOv8.
First of all, sorry for my bad English. If any of my words come across as offensive, that is not my intention.
I want to convert my own trained model into an engine file, and the code is as follows:
```python
from ultralytics import YOLO

model = YOLO("weights/PPE_SEG_2.pt")
# model.export(format='onnx', half=True, simplify=True)
model.export(format='engine', dynamic=True)
```

After successfully exporting the engine file, I used the following code for prediction:
```python
import cv2
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('weights/PPE_SEG_2.engine')
    cap = cv2.VideoCapture('/home/ubuntu/1.mp4')
    while cap.isOpened():
        success, frame = cap.read()
        if success:
            frame_copy = frame.copy()
            preds = model.track(source=frame_copy, task='segment', persist=True, save=False, verbose=False, conf = 0.5, tracker="CONFIG/bytetrack_custom.yaml")
            for r in preds:
                boxes = r.boxes.cpu().numpy()
                print(r.names)
                for box in boxes:
                    print(box)
```

The output looks like this:
```bash
{0: 'Backle', 1: 'Belt', 2: 'Helmet', 3: 'Hhook', 4: 'Hook', 5: 'Person', 6: 'Vest-Glowing', 7: 'vest'}
... ... ...
cls: array([21], dtype=float32)
conf: array([1.4541], dtype=float32)
data: array([[1821.7, 485.13, 905, 717.44, 297, 1.4541, 21]], dtype=float32)
id: array([ 297], dtype=float32)
is_track: True
orig_shape: (1080, 1920)
shape: (1, 7)
xywh: array([[1863.4, 601.29, 83.373, 232.31]], dtype=float32)
xywhn: array([[ 0.9705, 0.55675, 0.043423, 0.2151]], dtype=float32)
xyxy: array([[ 1821.7, 485.13, 1905, 717.44]], dtype=float32)
xyxyn: array([[0.94879, 0.4492, 0.99221, 0.6643]], dtype=float32)

Traceback (most recent call last):
  File "/home/ubuntu/Colins/AIU-inf-API/YOLOv8.py", line 267, in <module>
    preds = model.track(source=frame_copy, task='segment', persist=True, save=False, verbose=False, conf = 0.5, tracker="CONFIG/bytetrack_custom.yaml")
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/engine/model.py", line 259, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/engine/model.py", line 239, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 198, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 271, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 374, in run_callbacks
    callback(self)
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/trackers/track.py", line 61, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/trackers/byte_tracker.py", line 321, in update
    unconfirmed[itracked].update(detections[idet], self.frame_id)
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/trackers/byte_tracker.py", line 139, in update
    self.mean, self.covariance = self.kalman_filter.update(self.mean, self.covariance,
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/ultralytics/trackers/utils/kalman_filter.py", line 145, in update
    chol_factor, lower = scipy.linalg.cho_factor(projected_cov, lower=True, check_finite=False)
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/scipy/linalg/_decomp_cholesky.py", line 154, in cho_factor
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=False,
  File "/home/ubuntu/anaconda3/envs/FastAPI/lib/python3.9/site-packages/scipy/linalg/_decomp_cholesky.py", line 37, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 1-th leading minor of the array is not positive definite
```

In addition to encountering errors, there are two very peculiar aspects.
First is `cls: array([21], dtype=float32)`, but my 'names' only have 7 categories.
The second is `conf: array([1.4541], dtype=float32)`, where the 'conf' clearly does not conform to the correct format (a float number between 0 and 1).
However, when I use yolov8n-seg.pt for the export, this problem does not occur.
```python
from ultralytics import YOLO

model = YOLO("weights/yolov8n-seg.pt")
# model.export(format='onnx', half=True, simplify=True)
model.export(format='engine', dynamic=True)
```

The output obtained using the same code is as follows:
```bash
{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}
ultralytics.engine.results.Boxes object with attributes:

cls: array([0], dtype=float32)
conf: array([0.84347], dtype=float32)
data: array([[169.35, 125.37, 555.79, 1071.2, 1, 0.84347, 0]], dtype=float32)
id: array([1], dtype=float32)
is_track: True
orig_shape: (1080, 1920)
shape: (1, 7)
xywh: array([[362.57, 598.26, 386.44, 945.78]], dtype=float32)
xywhn: array([[ 0.18884, 0.55395, 0.20127, 0.87572]], dtype=float32)
xyxy: array([[169.35, 125.37, 555.79, 1071.2]], dtype=float32)
xyxyn: array([[0.088202, 0.11609, 0.28947, 0.99181]], dtype=float32)
ultralytics.engine.results.Boxes object with attributes:
... ... ...
cls: array([0], dtype=float32)
conf: array([0.79052], dtype=float32)
data: array([[1047.1, 2.2147, 1417.6, 1074.5, 2, 0.79052, 0]], dtype=float32)
id: array([2], dtype=float32)
is_track: True
orig_shape: (1080, 1920)
shape: (1, 7)
xywh: array([[1232.4, 538.37, 370.43, 1072.3]], dtype=float32)
xywhn: array([[0.64185, 0.49849, 0.19293, 0.99288]], dtype=float32)
xyxy: array([[1047.1, 2.2147, 1417.6, 1074.5]], dtype=float32)
xyxyn: array([[0.54539, 0.0020506, 0.73832, 0.99493]], dtype=float32)
```

Did I do something wrong? Why is this happening?

**Comment by glenn-jocher** [comment]
@gooelepapa hello there! It looks like you've run into a couple of issues with exporting your custom-trained YOLOv8 model and then using it for predictions and tracking. Let's address these:

1. Invalid confidence and class outputs ("cls: array([21], dtype=float32)" and "conf: array([1.4541], dtype=float32)"): It appears that there's a mismatch between your class labels and the inference results, as well as an unrealistic confidence score above 1.0. This might be due to an issue with post-processing steps after model export. Review your classes and the post-processing pipeline to ensure they align.

2. The numpy.linalg.LinAlgError: I suspect this is related to a numerical error when performing operations like matrix inversion during Kalman filtering in the tracking algorithm. It's possible there's an inconsistency in data format or expected input ranges between the custom model and the tracker configuration. You should check the tracker configuration (e.g., ByteTrack) and ensure it can handle the outputs provided by your model correctly.

Remember that these types of errors can sometimes be related to the specific customization of your model or the data used. I would suggest revisiting your model training logs to ensure the labeling is consistent and exploring the tracking configuration to better accommodate your custom model's output. If the issue persists, please provide additional context on the model's training and post-processing setup, which may help in isolating the cause of these problems. The [Ultralytics Docs](https://docs.ultralytics.com) provide guidance on model export and post-processing details that could also be helpful. Good luck with your debugging! 🐛💻

**Comment by gooelepapa** [comment]
@glenn-jocher Thank you.
I noticed that the output includes this warning message:
```bash
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
```
So I have tried to define my task like this:
```python
# model = YOLO('weights/PPE_SEG_2.engine')
model = YOLO('weights/PPE_SEG_2.engine', , task='segment')
```
and the output looks like this:
```bash
Loading weights/PPE_SEG_2.engine for TensorRT inference...
[12/13/2023-09:08:14] [TRT] [I] [MemUsageChange] Init CUDA: CPU +547, GPU +0, now: CPU 788, GPU 249 (MiB)
[12/13/2023-09:08:15] [TRT] [I] Loaded engine size: 17 MiB
[12/13/2023-09:08:15] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +34, now: CPU 847, GPU 301 (MiB)
[12/13/2023-09:08:15] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +11, GPU +34, now: CPU 858, GPU 335 (MiB)
[12/13/2023-09:08:15] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[12/13/2023-09:08:15] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +32, now: CPU 840, GPU 303 (MiB)
[12/13/2023-09:08:15] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +32, now: CPU 840, GPU 335 (MiB)
[12/13/2023-09:08:15] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
{0: 'Backle', 1: 'Belt', 2: 'Helmet', 3: 'Hhook', 4: 'Hook', 5: 'Person', 6: 'Vest-Glowing', 7: 'vest'}
[[     980.11       81.06      1355.6      1077.4           1     0.90845           5]]
[[     335.31      202.31      721.54      1078.1           2     0.89579           5]]
[[     1072.2      78.277      1235.1      229.49           3      0.8407           2]]
[[     1452.6      216.15      1597.1      320.11           4     0.82065           2]]
[[     629.04      166.93       706.9      239.38           5     0.79843           2]]
[[     1368.9      216.39      1654.9      860.07           6     0.79048           5]]
[[     629.27      163.25      827.35      883.99           7     0.78886           5]]
[[     442.36      202.26      565.14      321.61           8     0.77337           2]]
[[     1038.9      246.82        1261      869.35           9     0.64919           1]]
[[     1465.5      424.02      1617.1      708.68          10     0.62477           1]]
{0: 'Backle', 1: 'Belt', 2: 'Helmet', 3: 'Hhook', 4: 'Hook', 5: 'Person', 6: 'Vest-Glowing', 7: 'vest'}
[[     979.79       80.36      1355.6      1077.6           1     0.90922           5]]
```
Now it works!  Thanks for your help.

**Comment by glenn-jocher** [comment]
@gooelepapa That's great news! I'm delighted to hear that explicitly defining the task as 'segment' resolved the issue and you're now getting valid outputs. It looks like the model just needed a bit more context to understand what you were trying to do. If you run into any further issues or have additional questions, feel free to reach out. Keep up the good work and happy coding! 🎉👍
