### ISSUE TITLE
ERROR during installation requirements.txt for yolov8

### ISSUE THREAD

**Issue by 999iQ** [ultralytics/ultralytics#698]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations, Other

### Bug

ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\roman\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 216, i
n _main
    status = self.run(options, args)
  File "c:\users\roman\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in
 wrapper
    return func(self, options, args)
  File "c:\users\roman\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 412, i
n run
    installed = install_given_reqs(
  File "c:\users\roman\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\req\__init__.py", line 82, in ins
tall_given_reqs
    requirement.install(
  File "c:\users\roman\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\req\req_install.py", line 778, in
 install
    scheme = get_scheme(
  File "c:\users\roman\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\locations.py", line 185, in get_s
cheme
    scheme = distutils_scheme(
  File "c:\users\roman\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\locations.py", line 109, in distu
tils_scheme
    d.parse_config_files()
  File "c:\users\roman\appdata\local\programs\python\python38\lib\distutils\dist.py", line 406, in parse_config_files
    parser.read(filename)
  File "c:\users\roman\appdata\local\programs\python\python38\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "c:\users\roman\appdata\local\programs\python\python38\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "c:\users\roman\appdata\local\programs\python\python38\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1125: character maps to <undefined>

### Environment

Windows 10, Python 3.8.6, Pycharm

### Minimal Reproducible Example

There is no code, the project is clean, the error has already been from the start of installing libraries for Yolov8

### Additional

What to do? I didn't find the answer on the Internet

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Seems like a windows specific error. Are you able to reproduce on colab?

**Comment by kyoko9000** [comment]
If install error with pip install utra... You can install manual by download file requesrement.txt and put it near file main on pycharm and install in by the way we do with yolov5

**Comment by 999iQ** [comment]
> I don't understand what you mean by colab?

**Comment by 999iQ** [comment]
> Если ошибка установки с помощью pip install utra... Вы можете установить руководство, загрузив файл requesrement.txt и поместив его рядом с файлом main на pycharm, и установите, как мы это делаем с yolov5




> If install error with pip install utra... You can install manual by download file requesrement.txt and put it near file main on pycharm and install in by the way we do with yolov5

I tried to install through a clone of the git repository and call requirements.txt but I get the same error

**Comment by pderrenger** [comment]
@999iQ i believe your error might be due to a Unicode decoding issue specific to Windows. One alternative approach would be to manually download the `requirements.txt` file from the YOLOv8 repository and place it alongside your main file in PyCharm. Then, you can install the dependencies using the command `pip install -r requirements.txt` within your project's virtual environment, similar to how you would install YOLOv5.

In case you encounter the same error using this manual approach, please let me know and I can help further troubleshoot the issue.

**Comment by glenn-jocher** [comment]
@pderrenger it appears you're encountering a Unicode decoding issue on Windows. Manually downloading the `requirements.txt` and running `pip install -r requirements.txt` in your PyCharm project's virtual environment is a good step. If the error persists, please ensure your environment is set to use UTF-8 encoding and try again. If you're still facing difficulties, feel free to reach out for further assistance.

**Comment by glenn-jocher** [comment]
@pderrenger It looks like you're encountering a Unicode decoding issue on Windows. To work around this, manually download the `requirements.txt` from the YOLOv8 repo and place it in your project directory. Then, within your PyCharm's virtual environment, run `pip install -r requirements.txt`. If the error persists, please reach out again for further assistance.
