### ISSUE TITLE
export tfjs using int8 quantization fails

### ISSUE THREAD

**Issue by AngeliqueHameau** [ultralytics/ultralytics#6986]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

**main issue**  - error when I try to export in tfjs with int8 enabled
note: no error returned when `half=True`

with: 
`exported_model = best.export(format='tfjs', imgsz=640, int8=True)`

``` 
python MRE.py
Ultralytics YOLOv8.0.227 🚀 Python-3.10.13 torch-2.1.0 CPU (12th Gen Intel Core(TM) i9-12900K)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 84

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 0.8s, saved as 'yolov8n.onnx' (12.2 MB)
TensorFlow SavedModel: running 'onnx2tf -i "yolov8n.onnx" -o "yolov8n_saved_model" -nuo --verbosity info -oiqt -qt per-tensor'

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: module 'onnx' has no attribute '_serialize'
saved_model output started ==========================================================
saved_model output complete!
Float32 tflite output complete!
Float16 tflite output complete!
Input signature information for quantization
signature_name: serving_default
input_name.0: images shape: (1, 640, 640, 3) dtype: <dtype: 'float32'>
Dynamic Range Quantization tflite output complete!
fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
INT8 Quantization tflite output complete!
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
Full INT8 Quantization tflite output complete!
INT8 Quantization with int16 activations tflite output complete!
Full INT8 Quantization with int16 activations tflite output complete!
2023-12-14 07:37:44.321277: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
TensorFlow SavedModel: export success ✅ 97.6s, saved as 'yolov8n_saved_model' (40.5 MB)

TensorFlow GraphDef: starting export with tensorflow 2.13.1...
TensorFlow GraphDef: export failure ❌ 0.0s: '_UserObject' object has no attribute 'inputs'
Traceback (most recent call last):
  File "/data/missions/carddetector/MRE.py", line 6, in <module>
    exported_model = best.export(format='tfjs', imgsz=640, int8=True)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/src/ultralytics/ultralytics/engine/exporter.py", line 265, in __call__
    f[6], _ = self.export_pb(keras_model=keras_model)
  File "/usr/src/ultralytics/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/usr/src/ultralytics/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/src/ultralytics/ultralytics/engine/exporter.py", line 733, in export_pb
    m = m.get_concrete_function(tf.TensorSpec(keras_model.inputs[0].shape, keras_model.inputs[0].dtype))
AttributeError: '_UserObject' object has no attribute 'inputs'
```

### Environment

```  
yolo checks
Ultralytics YOLOv8.0.227 🚀 Python-3.10.13 torch-2.1.0 CUDA:0 (NVIDIA RTX A4500, 20178MiB)
Setup complete ✅ (24 CPUs, 62.5 GB RAM, 682.7/935.3 GB disk)

OS                  Linux-5.15.0-89-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.13
Install             git
RAM                 62.47 GB
CPU                 12th Gen Intel Core(TM) i9-12900K
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

### Minimal Reproducible Example

```
from ultralytics import YOLO

best = YOLO('yolov8n.pt')
exported_model = best.export(format='tfjs', imgsz=640, int8=True)

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@AngeliqueHameau Appreciate you providing details about the issue you faced!

The `int8` option is not compatible with `tfjs` export. You can refer to the export arguments for each export method for additional details: https://docs.ultralytics.com/modes/export/#arguments

This feature might be available in the future. Hope this helps! Let me know if you have any additional questions.

Thanks and Regards
Ultralytics Team!

**Comment by AngeliqueHameau** [comment]
Thank you for quick answer. 
I also tested with `tflite` and `saved_model` which according to the doc should support int8.
But I get the exact same error message.
```
exported_model = best.export(format='saved_model', imgsz=640, int8=True)
exported_model = best.export(format='tflite', imgsz=640, int8=True)
```

**Comment by glenn-jocher** [comment]
@AngeliqueHameau apologies for the inconvenience. This seems to be an issue with our `export()` method not handling `int8` quantization correctly across all specified formats. We'll investigate this and work on providing a fix. In the meantime, you can try exporting without `int8` quantization. If you're specifically looking for quantized models, keep an eye out for future updates where this feature might be corrected and more robust. Thanks for your understanding and patience. 🙏
