### ISSUE TITLE
errors in command: D:\YOLOv8-ONNXRuntime-Rust\target\debug>yolov8-rs.exe --model ./yolov8m.onnx --source ./bus.jpg --task detect 

### ISSUE THREAD

**Issue by zzy444626905** [ultralytics/ultralytics#7014]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Integrations

### Bug

```
D:\YOLOv8-ONNXRuntime-Rust\target\debug>yolov8-rs.exe --model ./yolov8m.onnx --source ./bus.jpg --task detect
thread 'main' panicked at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-1.16.3\src\lib.rs:93:132:
: GetProcAddress { source: Os { code: 127, kind: Uncategorized, message: "找不到指定的程序。" } }
stack backtrace:
   0:     0x7ff652fdb16a - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff652ff79bb - core::fmt::rt::Argument::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\rt.rs:138
   2:     0x7ff652ff79bb - core::fmt::write
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\mod.rs:1114
   3:     0x7ff652fd66e1 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\io\mod.rs:1763
   4:     0x7ff652fdaeea - std::sys_common::backtrace::_print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff652fdaeea - std::sys_common::backtrace::print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff652fdd5ba - std::panicking::default_hook::closure$1
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:272
   7:     0x7ff652fdd228 - std::panicking::default_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:292
   8:     0x7ff652fddc68 - std::panicking::rust_panic_with_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:731
   9:     0x7ff652fddb4d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:609
  10:     0x7ff652fdbb59 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:170
  11:     0x7ff652fdd860 - std::panicking::begin_panic_handler
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:597
  12:     0x7ff6530aa577 - core::panicking::panic_fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\panicking.rs:72
  13:     0x7ff6530aab33 - core::result::unwrap_failed
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\result.rs:1652
  14:     0x7ff652c6de70 - enum2$<core::result::Result<libloading::safe::Symbol<ptr_const$<ort::sys::OrtApiBase> (*)()>,enum2$<libloading::error::Error> > >::expect<libloading::safe::Symbol<ptr_const$<ort::sys::OrtApiBase> (*)()>,enum2$<libloading::error::Error> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\result.rs:1034
  15:     0x7ff652c57b8b - core::ops::function::FnOnce::call_once<alloc::sync::Arc<std::sync::mutex::Mutex<core::sync::atomic::AtomicPtr<ort::sys::OrtApi> >,alloc::alloc::Global> (*)(),tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\ops\function.rs:250
  16:     0x7ff652cb0b49 - lazy_static::lazy::impl$0::get::closure$0<alloc::sync::Arc<std::sync::mutex::Mutex<core::sync::atomic::AtomicPtr<ort::sys::OrtApi> >,alloc::alloc::Global>,alloc::sync::Arc<std::sync::mutex::Mutex<core::sync::atomic::AtomicPtr<ort::sys::OrtApi> >,alloc::al
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lazy_static-1.4.0\src\inline_lazy.rs:31
  17:     0x7ff652caeaef - std::sync::once::impl$2::call_once::closure$0<lazy_static::lazy::impl$0::get::closure_env$0<alloc::sync::Arc<std::sync::mutex::Mutex<core::sync::atomic::AtomicPtr<ort::sys::OrtApi> >,alloc::alloc::Global>,alloc::sync::Arc<std::sync::mutex::Mutex<core::syn
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sync\once.rs:149
  18:     0x7ff6530a9b34 - std::sys_common::once::queue::Once::call
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\once\queue.rs:183
  19:     0x7ff652cae7f6 - std::sync::once::Once::call_once<lazy_static::lazy::impl$0::get::closure_env$0<alloc::sync::Arc<std::sync::mutex::Mutex<core::sync::atomic::AtomicPtr<ort::sys::OrtApi> >,alloc::alloc::Global>,alloc::sync::Arc<std::sync::mutex::Mutex<core::sync::atomic::At
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sync\once.rs:149
  20:     0x7ff652c78f69 - lazy_static::lazy::Lazy<alloc::sync::Arc<std::sync::mutex::Mutex<core::sync::atomic::AtomicPtr<ort::sys::OrtApi> >,alloc::alloc::Global> >::get
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lazy_static-1.4.0\src\inline_lazy.rs:30
  21:     0x7ff652c78f69 - ort::impl$10::deref::__stability
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lazy_static-1.4.0\src\lib.rs:142
  22:     0x7ff652c78f69 - ort::impl$10::deref
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lazy_static-1.4.0\src\lib.rs:144
  23:     0x7ff652c7716c - ort::ort
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-1.16.3\src\lib.rs:133
  24:     0x7ff652c63f33 - ort::environment::Environment::create_custom_log_env
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-1.16.3\src\environment.rs:92
  25:     0x7ff652c65b5f - ort::environment::Environment::new
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-1.16.3\src\environment.rs:153
  26:     0x7ff652c6679a - ort::environment::EnvBuilder::build
                               at C:\Users\zyzhang60\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-1.16.3\src\environment.rs:365
  27:     0x7ff6527127e1 - yolov8_rs::ort_backend::OrtBackend::build
                               at D:\YOLOv8-ONNXRuntime-Rust\src\ort_backend.rs:100
  28:     0x7ff6526f59fc - yolov8_rs::model::YOLOv8::new
                               at D:\YOLOv8-ONNXRuntime-Rust\src\model.rs:60
  29:     0x7ff6526f1e23 - yolov8_rs::main
                               at D:\YOLOv8-ONNXRuntime-Rust\src\main.rs:20
  30:     0x7ff6526f31cb - core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > (*)(),tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\ops\function.rs:250
  31:     0x7ff6526f43ae - std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > (*)(),enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc:
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
  32:     0x7ff6526f52f1 - std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\rt.rs:166
  33:     0x7ff652fd0568 - std::rt::lang_start_internal::closure$2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\rt.rs:148
  34:     0x7ff652fd0568 - std::panicking::try::do_call
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:504
  35:     0x7ff652fd0568 - std::panicking::try
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:468
  36:     0x7ff652fd0568 - std::panic::catch_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panic.rs:142
  37:     0x7ff652fd0568 - std::rt::lang_start_internal
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\rt.rs:148
  38:     0x7ff6526f52ca - std::rt::lang_start<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\rt.rs:165
  39:     0x7ff6526f21f9 - main
  40:     0x7ff6530a7f60 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  41:     0x7ff6530a7f60 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  42:     0x7fff78197034 - BaseThreadInitThunk
  43:     0x7fff78dfd241 - RtlUserThreadStart
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zzy444626905** [comment]
thanks very much.  i got it , 

### 2. Install ONNXRuntime

**Comment by glenn-jocher** [comment]
@zzy444626905 it seems like you've resolved the error by installing ONNXRuntime. Should you encounter further issues or have any questions about YOLOv8, don't hesitate to reach out. Happy detecting! 😊🚀

**Comment by zzy444626905** [comment]
> @zzy444626905 it seems like you've resolved the error by installing ONNXRuntime. Should you encounter further issues or have any questions about YOLOv8, don't hesitate to reach out. Happy detecting! 😊🚀

big boss, ths very much. onnxruntime.dll must be with xxx.exe together in same directory.

**Comment by glenn-jocher** [comment]
Great to hear you've got it working, @zzy444626905! Correct placement of onnxruntime.dll is indeed essential. If anything else comes up, just let us know. Keep it up! 👍🎉
