### ISSUE TITLE
Memory allocation problem on GPU

### ISSUE THREAD

**Issue by Sarai256** [ultralytics/ultralytics#7076]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am trying to train the YOLOv8 seg model on GPU, but I am encountering this challenge in this error below. I have tried using a smaller yolov8n-seg model, still error persists. What could be the problem? 
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      1/100      4.09G      1.068      2.074      3.265       1.06         46        640:   4%|▎         | 1/28 [00:02<01:06,  2.4
Traceback (most recent call last):
  File "/home/skylar/YOLOv8/Yolov8_train.py", line 7, in <module>
    results = model.train(data='data-detect.yaml',amp=True, epochs=100, imgsz=640, boxes = False, show= True)
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/engine/model.py", line 338, in train
    self.trainer.train()
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 337, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/opt/anaconda-2022.05/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 41, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 212, in loss
    return self.criterion(preds, batch)
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/utils/loss.py", line 253, in __call__
    _, target_bboxes, target_scores, fg_mask, target_gt_idx = self.assigner(
  File "/opt/anaconda-2022.05/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda-2022.05/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/utils/tal.py", line 115, in forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(pd_scores, pd_bboxes, gt_labels, gt_bboxes, anc_points,
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/utils/tal.py", line 134, in get_pos_mask
    mask_in_gts = select_candidates_in_gts(anc_points, gt_bboxes)
  File "/home/skylar/.local/lib/python3.9/site-packages/ultralytics/utils/tal.py", line 26, in select_candidates_in_gts
    bbox_deltas = torch.cat((xy_centers[None] - lt, rb - xy_centers[None]), dim=2).view(bs, n_boxes, n_anchors, -1)
RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 11.76 GiB total capacity; 3.84 GiB already allocated; 16.88 MiB free; 3.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Additional

I am training the model via the python code not the command line

**Comment by Sarai256** [comment]
Figured it out by reducing the batch size.

**Comment by glenn-jocher** [comment]
@Sarai256 great to hear you resolved the issue! Reducing the batch size is indeed a common and effective strategy to manage GPU memory limitations. Keep this approach in mind for future training sessions, as it can help prevent memory allocation problems. If you encounter any more challenges or have questions, feel free to reach out. Happy training! 🚀😊
