### ISSUE TITLE
How does YOLOV8 change the video card used at the training break point

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#7186]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How does YOLOV8 change the video card used at the training break point

### Additional

results = model.train(data='data/ballsl.yaml', device=[1, 3],resume=False)
I changed the training code to this after terminating the training, but still failed to replace the training graphics card
results = model.train(data='data/ballsl.yaml', device=[1, 2],resume=True)

**Comment by kssion** [comment]
@glenn-jocher hello! Resume an interrupted training is error!

```
yolo train resume model=/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt
```
After running, the file will be deleted, causing an exception to be thrown.

# Logs
```
dl@localhost /a/r/segment> yolo train resume model=/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt              (yolo)
Ultralytics YOLOv8.0.230 🚀 Python-3.9.18 torch-2.1.1+cu121 CUDA:0 (Tesla T4, 14931MiB)
                                                            CUDA:1 (Tesla T4, 14931MiB)
engine/trainer: task=segment, mode=train, model=/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt, data=/app/datasets/rs/segment/all/data.yml, epochs=300, time=None, patience=0, batch=6, imgsz=1280, save=True, save_period=-1, cache=True, device=(0, 1), workers=8, project=None, name=rs-seg-m-300-2023-1227-02, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.0, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=/app/runs/segment/rs-seg-m-300-2023-1227-02
DDP: debug command /home/dl/miniconda3/envs/yolo/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 47883 /home/dl/.config/Ultralytics/DDP/_temp_1npfqj1i139735938375392.py
Ultralytics YOLOv8.0.230 🚀 Python-3.9.18 torch-2.1.1+cu121 CUDA:0 (Tesla T4, 14931MiB)
                                                            CUDA:1 (Tesla T4, 14931MiB)
TensorBoard: Start with 'tensorboard --logdir /app/runs/segment/rs-seg-m-300-2023-1227-02', view at http://localhost:6006/
Traceback (most recent call last):
  File "/home/dl/.config/Ultralytics/DDP/_temp_1npfqj1i139735938375392.py", line 12, in <module>
    results = trainer.train()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 290, in _do_train
    self._setup_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 217, in _setup_train
    ckpt = self.setup_model()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 476, in setup_model
    weights, ckpt = attempt_load_one_weight(model)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 639, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 578, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt'
Traceback (most recent call last):
  File "/home/dl/.config/Ultralytics/DDP/_temp_1npfqj1i139735938375392.py", line 12, in <module>
    results = trainer.train()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 290, in _do_train
    self._setup_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 217, in _setup_train
    ckpt = self.setup_model()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 476, in setup_model
    weights, ckpt = attempt_load_one_weight(model)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 639, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 578, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt'
[2023-12-27 21:50:44,450] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 325359) of binary: /home/dl/miniconda3/envs/yolo/bin/python
Traceback (most recent call last):
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/dl/.config/Ultralytics/DDP/_temp_1npfqj1i139735938375392.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-27_21:50:44
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 325360)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-27_21:50:44
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 325359)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/dl/miniconda3/envs/yolo/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/cfg/__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/model.py", line 356, in train
    self.trainer.train()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 185, in train
    raise e
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 183, in train
    subprocess.run(cmd, check=True)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/dl/miniconda3/envs/yolo/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '47883', '/home/dl/.config/Ultralytics/DDP/_temp_1npfqj1i139735938375392.py']' returned non-zero exit status 1.
```

**Comment by kssion** [comment]
Sorry, I should reply #7181 here

**Comment by glenn-jocher** [comment]
@kssion, no worries! For the error you're experiencing when trying to resume training with YOLOv8, the issue seems to be that the weight file `last.pt` you specified cannot be found. This could be due to incorrect paths or accidental deletion.

Please ensure that the path to `last.pt` is correct and that the file exists. Verify your file system and confirm that you have read and write permissions for the location where `last.pt` should be. If the file has been deleted by mistake, you might need to restore it from a backup if one is available. If this doesn't resolve your issue, please provide additional context or error logs, and we'll do our best to assist you further.

**Comment by kssion** [comment]
@glenn-jocher, interrupted at 68 epochs of training, an error occurred while resuming training.

This is all the logs. Before executing the command, the model file existed.
```
$ ll /app/runs/segment/rs-seg-m-300-2023-1227-02/weights/
总用量 626M
-rw-rw-r-- 1 dl dl 313M 12月 27 19:48 best.pt
-rw-rw-r-- 1 dl dl 313M 12月 27 19:48 last.pt

$ yolo train resume model=/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt
Ultralytics YOLOv8.0.230 🚀 Python-3.9.18 torch-2.1.1+cu121 CUDA:0 (Tesla T4, 14931MiB)
                                                            CUDA:1 (Tesla T4, 14931MiB)
engine/trainer: task=segment, mode=train, model=/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt, data=/app/datasets/rs/segment/all/data.yml, epochs=300, time=None, patience=0, batch=6, imgsz=1280, save=True, save_period=-1, cache=True, device=(0, 1), workers=8, project=None, name=rs-seg-m-300-2023-1227-02, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.0, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=/app/runs/segment/rs-seg-m-300-2023-1227-02
DDP: debug command /home/dl/miniconda3/envs/yolo/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 44923 /home/dl/.config/Ultralytics/DDP/_temp_sxtcu2jc140010841472784.py
Ultralytics YOLOv8.0.230 🚀 Python-3.9.18 torch-2.1.1+cu121 CUDA:0 (Tesla T4, 14931MiB)
                                                            CUDA:1 (Tesla T4, 14931MiB)
TensorBoard: Start with 'tensorboard --logdir /app/runs/segment/rs-seg-m-300-2023-1227-02', view at http://localhost:6006/
Traceback (most recent call last):
  File "/home/dl/.config/Ultralytics/DDP/_temp_sxtcu2jc140010841472784.py", line 12, in <module>
    results = trainer.train()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 290, in _do_train
    self._setup_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 217, in _setup_train
    ckpt = self.setup_model()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 476, in setup_model
    weights, ckpt = attempt_load_one_weight(model)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 639, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 578, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt'
Traceback (most recent call last):
  File "/home/dl/.config/Ultralytics/DDP/_temp_sxtcu2jc140010841472784.py", line 12, in <module>
    results = trainer.train()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 290, in _do_train
    self._setup_train(world_size)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 217, in _setup_train
    ckpt = self.setup_model()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 476, in setup_model
    weights, ckpt = attempt_load_one_weight(model)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 639, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 578, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/app/runs/segment/rs-seg-m-300-2023-1227-02/weights/last.pt'
[2023-12-28 17:11:04,813] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 357482) of binary: /home/dl/miniconda3/envs/yolo/bin/python
Traceback (most recent call last):
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/dl/.config/Ultralytics/DDP/_temp_sxtcu2jc140010841472784.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-28_17:11:04
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 357483)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-28_17:11:04
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 357482)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/dl/miniconda3/envs/yolo/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/cfg/__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/model.py", line 356, in train
    self.trainer.train()
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 185, in train
    raise e
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 183, in train
    subprocess.run(cmd, check=True)
  File "/home/dl/miniconda3/envs/yolo/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/dl/miniconda3/envs/yolo/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '44923', '/home/dl/.config/Ultralytics/DDP/_temp_sxtcu2jc140010841472784.py']' returned non-zero exit status 1.
```

**Comment by glenn-jocher** [comment]
@kssion, it seems there's an issue with locating the `last.pt` file upon resuming training, despite the file existing in the specified directory. This could be due to a path resolution issue within the distributed training setup.

Please ensure that the path provided to the `model` argument is accessible from all nodes in your distributed training environment. You may also want to check for any synchronization issues that might prevent the file from being read correctly in the parallelized setup.

If the problem persists, consider restarting the training with `resume=True` without explicitly stating the model path, as YOLOv8 should automatically locate the last saved checkpoint in your runs directory. Should you need further assistance, please provide additional details on the distributed system configuration to help diagnose the problem more accurately.
