### ISSUE TITLE
How to use txt training in training profile

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#732]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Classification dataset root directory

```
|-- bocai
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- changqiezi
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- hongxiancai
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- huluobo
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- labels.txt
|-- train_list.txt
|-- val_list.txt
|-- test_list.txt
```

train_list.txt
```
./bocai/38.jpg 0
./bocai/160.jpg 0
./bocai/30.jpg 0
./bocai/163.jpg 0
./bocai/14.jpg 0
./bocai/66.jpg 0
./bocai/196.jpg 0
./bocai/155.jpg 0
./bocai/173.jpg 0
./changqiezi/99.jpg 1
./changqiezi/122.jpg 1
./changqiezi/188.jpg 1
./changqiezi/177.jpg 1
./changqiezi/48.jpg 1
./changqiezi/136.jpg 1
./changqiezi/95.jpg 1
./changqiezi/166.jpg 1
./changqiezi/139.jpg 1
./changqiezi/187.jpg 1
./changqiezi/11.jpg 1
./changqiezi/38.jpg 1
./changqiezi/160.jpg 1
```

FL.yaml
```
path: D:/YOLOv8/ultralytics/DATA/FL/
train: train_list.txt
val: val_list.txt
test: test_list.txt

names:
  0: bocai
  1: changqiezi
  2: hongxiancai
  3: huluobo
```

FL.py
```
# Load a model
model = YOLO( "yolov8n-cls.yaml") 
# model = YOLO( "yolov8n-cls.pt") 
# Train the model
results = model.train(data="FL.yaml", epochs=100)
```

```
YOLOv8n-cls summary: 99 layers, 1445974 parameters, 1445974 gradients, 3.4 GFLOPs
optimizer: SGD(lr=0.01) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias
Traceback (most recent call last):
  File "d:/YOLOv8/ultralytics/fl.py", line 16, in <module>
    results = model.train(data="FL.yaml", epochs=100)
  File "d:\YOLOv8\ultralytics\ultralytics\yolo\engine\model.py", line 206, in train
    self.trainer.train()
  File "d:\YOLOv8\ultralytics\ultralytics\yolo\engine\trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "d:\YOLOv8\ultralytics\ultralytics\yolo\engine\trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "d:\YOLOv8\ultralytics\ultralytics\yolo\engine\trainer.py", line 233, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=rank, mode="train")
  File "d:\YOLOv8\ultralytics\ultralytics\yolo\v8\classify\train.py", line 72, in get_dataloader
    loader = build_classification_dataloader(path=dataset_path,
  File "d:\YOLOv8\ultralytics\ultralytics\yolo\data\build.py", line 118, in build_classification_dataloader
    dataset = ClassificationDataset(root=path, imgsz=imgsz, augment=augment, cache=cache)
  File "d:\YOLOv8\ultralytics\ultralytics\yolo\data\dataset.py", line 202, in __init__
    super().__init__(root=root)
  File "D:\anaconda31114\envs\yolov8\lib\site-packages\torchvision\datasets\folder.py", line 309, in __init__
    super().__init__(
  File "D:\anaconda31114\envs\yolov8\lib\site-packages\torchvision\datasets\folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "D:\anaconda31114\envs\yolov8\lib\site-packages\torchvision\datasets\folder.py", line 218, in find_classes
    return find_classes(directory)
  File "D:\anaconda31114\envs\yolov8\lib\site-packages\torchvision\datasets\folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
NotADirectoryError: [WinError 267] Invalid directory name。: 'D:\\YOLOv8\\ultralytics\\DATA\\FL\\train_list.txt'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
```

I like txt for training
Can you use txt for training

Whether the official data set conversion script is provided?
```
|-- bocai
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- changqiezi
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- hongxiancai
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- huluobo
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg
```

**Comment by suryan-s** [comment]
Does train_list.txt, val_list.txt, and test_list.txt contain the combined labels of all the images?

**Comment by monkeycc** [comment]
```
|-- train
|     |-- bocai
|              |--  1.jpg
|              |--  2.jpg
|              |--  3.jpg
|     |-- changqiezi
|              |--  1.jpg
|              |--  2.jpg
|              |--  3.jpg
|-- val
|     |-- bocai
|              |--  1.jpg
|              |--  2.jpg
|              |--  3.jpg
|     |-- changqiezi
|              |--  1.jpg
|              |--  2.jpg
|              |--  3.jpg
|-- test
|      |-- bocai
|              |--  1.jpg
|              |--  2.jpg
|              |--  3.jpg
|      |-- changqiezi
|              |--  1.jpg
|              |--  2.jpg
|              |--  3.jpg
```

I finally converted to this

**Comment by AyushExel** [comment]
For classification you need yamls. You can just pass the dataset folder `data=folder_path`

**Comment by monkeycc** [comment]
D:/YOLOv8/ultralytics/DATA/FL/
```
|-- bocai
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- changqiezi
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- hongxiancai
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg

|-- huluobo
|        |--  1.jpg
|        |--  2.jpg
|        |--  3.jpg
```

```
model = YOLO( "yolov8n-cls.pt") 

results = model.train(data="D:/YOLOv8/ultralytics/DATA/FL/", epochs=100)
```

Is this possible ? 

[docs.ultralytics.com](https://docs.ultralytics.com/)
Tutorials should be added
Training custom data
@AyushExel
