### ISSUE TITLE
ValueError: cannot convert float NaN to integer while training the YOLOv8 model

### ISSUE THREAD

**Issue by WeiHoongAries** [ultralytics/ultralytics#7344]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have train a model according to the tutorials provided. The training process is complete, however there are some errors, and these errors also coming out at detection process. 
The error messages are as below: 
Exception in thread Thread-17 (plot_images):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wwl/.local/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 446, in plot_images
    annotator.box_label(box, label, color=color)
  File "/home/wwl/.local/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 118, in box_label
    self.draw.text((box[0], box[1] - h if outside else box[1]), label, fill=txt_color, font=self.font)
  File "/home/wwl/.local/lib/python3.10/site-packages/PIL/ImageDraw.py", line 565, in text
Exception in thread Thread-15 (plot_images):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    draw_text(ink)
  File "/home/wwl/.local/lib/python3.10/site-packages/PIL/ImageDraw.py", line 505, in draw_text
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    coord.append(int(xy[i]))
ValueError: cannot convert float NaN to integer
    self._target(*self._args, **self._kwargs)
  File "/home/wwl/.local/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 446, in plot_images
    annotator.box_label(box, label, color=color)
  File "/home/wwl/.local/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 118, in box_label
    self.draw.text((box[0], box[1] - h if outside else box[1]), label, fill=txt_color, font=self.font)
  File "/home/wwl/.local/lib/python3.10/site-packages/PIL/ImageDraw.py", line 565, in text
    draw_text(ink)
  File "/home/wwl/.local/lib/python3.10/site-packages/PIL/ImageDraw.py", line 505, in draw_text
    coord.append(int(xy[i]))
ValueError: cannot convert float NaN to integer

**Comment by Jes46** [comment]
Are you using your own Database? Maybe your .txt files are not in the correct format according to YOLO.

**Comment by WeiHoongAries** [comment]
Hi @Jes46 
I am using custom dataset that label using LabelImg. I just found out that my epoch results are all NaN. 
![Screenshot from 2024-01-05 23-05-03](https://github.com/ultralytics/ultralytics/assets/145408384/062e79f0-7e52-44db-83a0-560f5c559b05)

**Comment by Jes46** [comment]
I had a similar error before. In my case It was because my GPU doesn't fully support all the training process so my solution was the next:

code line: model.train(data=data_path, epochs=30, batch=4, **amp=False**)

Use your own configuration but change amp value from True to False. By default it is set to True.
Hope this will hep you.

**Comment by WeiHoongAries** [comment]
Well it does works. Thank you

**Comment by glenn-jocher** [comment]
@WeiHoongAries you're welcome! I'm glad to hear that your issue is resolved. If you have any more questions or need further assistance, feel free to reach out. Happy training with YOLOv8! 🚀
