### ISSUE TITLE
RTDETRDecoder missing stride attribute

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#7382]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

When supporting a user on Discord, while testing by loading `yolov8-rtdetr.yaml` model and attempting to train, an error is raised `AttributeError: 'RTDETRDecoder' object has no attribute 'stride'`. I have not dug into this, but it doesn't appear that the `RTDETRDecoder` module has a stride attribute, so I'm guessing it will need to be addressed by either:

- [ ] adjusting the code to handle cases when loading the `RTDETRDecoder` module
- [ ] adding a `stride` attribute to the `RTDETRDecoder` module

I'm not that certain I'll be able to make a PR to address this personally. 

### Environment

```
Ultralytics YOLOv8.0.236 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
Setup complete ✅ (12 CPUs, 31.9 GB RAM, 356.9/465.2 GB disk)

OS                  Windows-10-10.0.19045-SP0       
Environment         Windows
Python              3.10.9
Install             pip
RAM                 31.86 GB
CPU                 Intel Core(TM) i5-10600K 4.10GHz
CUDA                11.7

matplotlib          ✅ 3.7.1>=3.3.0   
numpy               ✅ 1.24.2>=1.22.2 
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 9.4.0>=7.1.2       
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.28.2>=2.23.0     
scipy               ✅ 1.10.1>=1.4.1      
torch               ✅ 1.13.1+cu117>=1.8.0
torchvision         ✅ 0.14.1+cu117>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.0>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
```

### Minimal Reproducible Example

```py
from ultralytics import YOLO

model = YOLO('yolov8n-rtdetr.yaml', task='detect')
model.train(data='coco8.yaml', epochs=13)
```

### Additional

```
                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1   7384332  ultralytics.nn.modules.head.RTDETRDecoder    [80, [64, 128, 256]]
YOLOv8-rtdetr summary: 345 layers, 9643868 parameters, 9643868 gradients, 17.1 GFLOPs

TensorBoard: Start with 'tensorboard --logdir runs\detect\train31', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning Q:\datasets\coco8\labels\train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
val: Scanning Q:\datasets\coco8\labels\val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
Plotting labels to runs\detect\train31\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 67 weight(decay=0.0), 128 weight(decay=0.0005), 146 bias(decay=0.0)
WARNING ⚠️ TensorBoard graph visualization failure 'NoneType' object is not subscriptable
13 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s]
  
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
    self.trainer.train()
  File ".yolo\lib\site-packages\ultralytics\engine\trainer.py", line 189, in train
    self._do_train(world_size)
  File ".yolo\lib\site-packages\ultralytics\engine\trainer.py", line 346, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File ".yolo\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 41, in forward
    return self.loss(x, *args, **kwargs)
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 215, in loss
    self.criterion = self.init_criterion()
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 298, in init_criterion
    return v8DetectionLoss(self)
  File ".yolo\lib\site-packages\ultralytics\utils\loss.py", line 150, in __init__
    self.stride = m.stride  # model strides
  File ".yolo\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
  
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
Replacing the line in `v8DetectionLoss`:

https://github.com/ultralytics/ultralytics/blob/8c2b2f56b230fc2964b4b574ee6b0775fca606fa/ultralytics/utils/loss.py#L150

with 

```py
try:
    self.stride = m.stride  # model strides
except AttributeError: # no attribute strides
    self.stride = model.stride
```
_does_ work, but then fails because the `RTDETRDecoder` module does not have attributes `no` (outputs) or `reg_max` (DFL channels), the latter I presume could be configured to be zero since I'm guessing that the `v8DetectionLoss.use_dfl` would be set to `False` but I'm not clear on how `no` would be calculated or what it's equivalent would be for the `RTDETRDecoder` module.

**Comment by Burhan-Q** [comment]
So, I tried changing `v8DetectionLoss` to use (L150 - L163):

```py
try:
     self.stride = m.stride  # model strides
except AttributeError:
     self.stride = model.stride
self.nc = m.nc  # number of classes
self.no = m.no if hasattr(m, 'no') else m.nc + 4
self.reg_max = m.reg_max if hasattr(m, 'reg_max') else 0
self.device = device

self.use_dfl = self.reg_max > 1

self.assigner = TaskAlignedAssigner(topk=10, num_classes=self.nc, alpha=0.5, beta=6.0)
self.bbox_loss = BboxLoss(self.reg_max - 1, use_dfl=self.use_dfl).to(device)
self.proj = torch.arange(self.reg_max, dtype=torch.float, device=device)
```

which does allow the `v8DetectionLoss` to load without issue, but does not train. Guessing that the `self.reg_max` value set to zero might cause issues. The training code ran but didn't start the first epoch and instead raised: `TypeError: 'NoneType' object is not subscriptable`

<details><summary>Full error stack trace</summary>
<p>

```
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  
  File ".yolo\lib\site-packages\ultralytics\engine\model.py", line 356, in train
    self.trainer.train()
    
  File ".yolo\lib\site-packages\ultralytics\engine\trainer.py", line 189, in train
    self._do_train(world_size)
    
  File ".yolo\lib\site-packages\ultralytics\engine\trainer.py", line 346, in _do_train
    self.loss, self.loss_items = self.model(batch)
    
  File ".yolo\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
    
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 41, in forward
    return self.loss(x, *args, **kwargs)
    
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 217, in loss
    preds = self.forward(batch['img']) if preds is None else preds
    
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 42, in forward
    return self.predict(x, *args, **kwargs)
    
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 60, in predict
    return self._predict_once(x, profile, visualize, embed)
    
  File ".yolo\lib\site-packages\ultralytics\nn\tasks.py", line 81, in _predict_once
    x = m(x)  # run
    
  File ".yolo\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
    
  File ".yolo\lib\site-packages\ultralytics\nn\modules\head.py", line 304, in forward
    get_cdn_group(batch,
    
  File ".yolo\lib\site-packages\ultralytics\models\utils\ops.py", line 183, in get_cdn_group
    gt_groups = batch['gt_groups']
    
TypeError: 'NoneType' object is not subscriptable
```

</p>
</details> 

However, despite this change not working, I do thinking that a few things might be worthwhile to modify. Specifically the following lines 
https://github.com/ultralytics/ultralytics/blob/8c2b2f56b230fc2964b4b574ee6b0775fca606fa/ultralytics/utils/loss.py#L156-L160

```diff
- self.use_dfl = m.reg_max > 1
+ self.use_dfl = self.reg_max > 1

self.assigner = TaskAlignedAssigner(topk=10, num_classes=self.nc, alpha=0.5, beta=6.0)
- self.bbox_loss = BboxLoss(m.reg_max - 1, use_dfl=self.use_dfl).to(device)
+ self.bbox_loss = BboxLoss(self.reg_max - 1, use_dfl=self.use_dfl).to(device)
- self.proj = torch.arange(m.reg_max, dtype=torch.float, device=device)
+ self.proj = torch.arange(self.reg_max, dtype=torch.float, device=device)
```

Since the attribute `self.reg_max` is set above, it would make more sense to use that instead of retrieving `m.reg_max` every time, especially if there would be an alternative way to populate `self.reg_max` when `m.reg_max` doesn't exist.

**Comment by Burhan-Q** [comment]
@AyushExel I haven't made any progress on this since I'm a bit out of my depth. I thought I'd ask if you had any ideas since it looked like you were pretty heavily involved with the `RTDETR` implementation and the block of the loss function that's throwing errors.

**Comment by Laughing-q** [comment]
@Burhan-Q see https://github.com/ultralytics/ultralytics/issues/7720#issuecomment-1902918823. :)

**Comment by MlLearnerAkash** [comment]
As per the documentation:
```
from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR("rtdetr-l.pt")

# Display model information (optional)
model.info()

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="coco8.yaml", epochs=100, imgsz=640)

# Run inference with the RT-DETR-l model on the 'bus.jpg' image
results = model("path/to/bus.jpg")
```

Ref: [models/rtdetr](https://docs.ultralytics.com/models/rtdetr/#usage-examples)

**Comment by glenn-jocher** [comment]
@MlLearnerAkash thank you for sharing the example. If you're encountering any issues, please ensure you're using the latest version of the Ultralytics package. If the problem persists, feel free to provide more details so we can assist you further.
