### ISSUE TITLE
Error compiling python scripts to executable file

### ISSUE THREAD

**Issue by thinhnguyen2704** [ultralytics/ultralytics#7393]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I am having a problem when compiling python scripts (main.py) to executable. 

I trained a YOLOv8 detection model, tested, ran the script main.py on VS Code and it worked fine. However, when I used pyinstaller and cx_Freeze to compile the script into an executable file and ran this file, this error occurred. 

![image](https://github.com/ultralytics/ultralytics/assets/20553722/b468d135-c370-4244-b9f6-8a7aaf57e5fe)

### Environment
numpy==1.26.2
opencv-python==4.8.1.78
PyAutoGUI==0.9.54
PyGetWindow==0.0.9
pyinstaller==6.2.0
PyMsgBox==1.0.9
pywin32==306
pywin32-ctypes==0.2.2
pyWinActivate==1.3.0
PyDirectInput==1.0.4
pyinstaller==6.2.0
python-imagesearch==1.3.0
ultralytics==8.0.237
torch==2.1.1
torchvision==0.16.1
pyinstaller==6.2.0
pyinstaller-hooks-contrib==2023.10

### Minimal Reproducible Example

pyinstaller -F -w main.py
cxfreeze -c main.py --target-dir dist

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by thinhnguyen2704** [comment]
Hi @glenn-jocher, the error message is:
Traceback (most recent call last):
  File "main.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\predictor.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\data\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\data\base.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ultralytics\utils\__init__.py", line 265, in <module>
  File "ultralytics\utils\__init__.py", line 233, in set_logging
AttributeError: 'NoneType' object has no attribute 'encoding'

**Comment by thinhnguyen2704** [comment]
I just go through the compiling process of PyInstaller and there are some noticeable warnings.

2861 WARNING: Failed to collect submodules for 'torch.utils.tensorboard' because importing 'torch.utils.tensorboard' raised: ModuleNotFoundError: No module named 'tensorboard' 
[2024-01-09 10:58:08,409] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.128083 WARNING: Ignoring /usr/lib64/libgomp.so.1 imported from D:\PersonalProject\tft-autobot\venv\Lib\site-packages\torch\_inductor\codecache.py - only basenames are supported with ctypes imports!

**Comment by princess995** [comment]
You have the same symptom as me. After additionally importing 'torch.utils.tensorboard', another error appears.

Failed to collect submodules for 'torch.onnx._internal.fx.passes' because importing 'torch.onnx._internal.fx.passes' raised: ModuleNotFoundError: No module named 'onnxscript'

From here on, I couldn't solve it either. Even if I import onnxscript, the same error appears.

**Comment by thinhnguyen2704** [comment]
Hi @princess995, I'm still stuck with this. 

I've been going through those logged files in the error message to see if I can find anything related to this bug.

I don't think missing files or incorrect paths is the problem as when I removed "import predictor" module (which includes the detection model), I could compile and run the script without any error. 

I tried using the default "yolov8n.pt" instead of my custom "tft.pt" but this error still occurs.

**Comment by princess995** [comment]
@thinhnguyen2704 After reading and checking various information, I found out that there was no ultralytics in pyinstaller's hook file.
Without this hook file, the module cannot be imported during packaging.
Now I have to go find another way.

**Comment by thinhnguyen2704** [comment]
@princess995 I just found out that the ultralytics/cfg/default.yaml is missing. Here is the solution:
1: You need to compile your script as one directory: pyinstaller --one-dir your_main.py 
2: In your installed dependency 'ultralytics' folder, go to cfg folder, copy default.yaml and paste it inside your dist folder:  dist/_internal/ultralytics/cfg 
3: Run your exe and it should work. 

Hope it works for you.

**Comment by thinhnguyen2704** [comment]
@princess995, I installed the latest version of those libraries.

**Comment by thinhemb** [comment]
@princess995 exaple  you can --add-data "C:/Users/KNT21818/AppData/Roaming/Python/Python39/site-packages/ultralytics;ultralytics/" I tried it and it worked. you cannot copy cfg folder

**Comment by austinulfers** [comment]
This issue has to do with you setting the pyinstaller spec to `console=False`. When there is no console, you need to redirect the stdout to a file or something else. If you look at line 233 in `set_logging`, you see: `if WINDOWS and sys.stdout.encoding != 'utf-8':`. But it can't access `.encoding` because `sys.stdout` returns `None`.

**Comment by glenn-jocher** [comment]
@austinulfers it appears that the issue is related to the `console=False` setting in your PyInstaller spec, which disables the console and causes `sys.stdout` to be `None`. This leads to the AttributeError you're encountering because `set_logging` in `ultralytics/utils/__init__.py` expects `sys.stdout` to have an `encoding` attribute.

To resolve this, you can either set `console=True` in your spec file to enable the console, or modify your application to handle `sys.stdout` being `None` by redirecting the standard output to a file or another output stream that supports encoding.

If you choose to redirect `sys.stdout`, make sure to implement this before any logging occurs in your application to prevent similar issues.

**Comment by Bak-sejun** [comment]
I succeeded in running pyinstaller using the above two methods.
1. Create an executable file in a directory with the -D option and move default.yaml.
2. sys in ultralytics/utils/__init__.py. Insert `stdout=open` ('output.txt', 'w', encoding='utf-8 `')`

**Comment by glenn-jocher** [comment]
@Bak-sejun great to hear that you've resolved the issue by using the two methods you've described. It's always good to see community members finding solutions and sharing them. Your success will undoubtedly be helpful to others facing similar challenges. Keep up the good work! 🎉 If you encounter any more issues or have further questions, feel free to reach out. Happy coding!
