### ISSUE TITLE
Classify command modifies the path of the folder

### ISSUE THREAD

**Issue by gpol92** [ultralytics/ultralytics#753]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

When I run this command 

!yolo classify data=/content/drive/MyDrive/new_tsr/train/images/ model=yolov8n-cls.pt epochs=100 imgsz=64

I receive this error message: 

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/content/ultralytics/ultralytics/yolo/cfg/__init__.py", line 266, in entrypoint
    getattr(model, mode)(**vars(cfg))
  File "/content/ultralytics/ultralytics/yolo/engine/model.py", line 204, in train
    self.trainer = self.TrainerClass(overrides=overrides)
  File "/content/ultralytics/ultralytics/yolo/v8/classify/train.py", line 21, in __init__
    super().__init__(cfg, overrides)
  File "/content/ultralytics/ultralytics/yolo/engine/trainer.py", line 123, in __init__
    self.data = check_cls_dataset(self.data)
  File "/content/ultralytics/ultralytics/yolo/data/utils.py", line 287, in check_cls_dataset
    names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
  File "/content/ultralytics/ultralytics/yolo/data/utils.py", line 287, in <listcomp>
    names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
  File "/usr/lib/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/new_tsr/train/images/train'

It happens that the program tries to search in a subfolder of folder images called train, but the train folder doesn't exist into the images folder. 

### Environment

Ultralytics YOLOv8.0.25 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
OS: Ubuntu 20.04
Python: 3.8.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@gpol92 it looks like the error is caused by the program trying to search for a "train" folder within the "images" folder, which doesn't exist. To resolve this, you can reorganize your data folder structure to include a "train" folder within the "images" folder. 

Additionally, please ensure that the data path specified in the command is accurate and that the required files and folders are correctly located.

If you have any further questions or encounter any issues, feel free to ask!
