### ISSUE TITLE
YOLOv8-Face CLI vs Python issue

### ISSUE THREAD

**Issue by med-tim** [ultralytics/ultralytics#7575]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I am running YOLOv8l-face.pt model to detect faces in an image. When running the CLI code, it works fantastic. Here is what I am running and here is the output:
yolo task=detect mode=predict model=yolov8l-face.pt conf=0.25 imgsz=1280 line_width=1 max_det=1000 source=examples/face2.jpg

image 1/1 \examples\face2.jpg: 736x1280 1 face, 1474.7ms
Speed: 15.6ms preprocess, 1474.7ms inference, 0.0ms postprocess per image at shape (1, 3, 736, 1280)
Results saved to runs\detect\predict2
💡 Learn more at https://docs.ultralytics.com/modes/predict

Now when I try to run the python version in the same environment with this code:
from ultralytics import YOLO
model = YOLO('yolov8l-face.pt')
source = 'examples/face2.jpg'
results = model(source)  

Error:
WARNING  yolov8l-face.pt is deprecated as it requires omegaconf, which is now removed from ultralytics requirements.
AutoInstall will occur now but this feature will be removed for omegaconf models in the future.
Please train a new model or download updated models from https://github.com/ultralytics/assets/releases/tag/v0.0.0
Traceback (most recent call last):
  File "C:\Users\Tim\Documents\DeepLearning\Processing\yolov8-face\YOLO-FACE-DETECTION.py", line 4, in <module>
    model = YOLO('yolov8l-face.pt')  # load a pretrained model
  File "C:\Users\Tim\Documents\DeepLearning\Processing\yolov8-face\ultralytics\yolo\engine\model.py", line 56, in __init__
    {'.pt': self._load, '.yaml': self._new}[Path(model).suffix](model)
  File "C:\Users\Tim\Documents\DeepLearning\Processing\yolov8-face\ultralytics\yolo\engine\model.py", line 84, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\Tim\Documents\DeepLearning\Processing\yolov8-face\ultralytics\nn\tasks.py", line 369, in attempt_load_one_weight
    ckpt = torch.load(weight, map_location='cpu')  # load
  File "C:\ProgramData\anaconda3\envs\yolo_env\lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "C:\ProgramData\anaconda3\envs\yolo_env\lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
  File "C:\ProgramData\anaconda3\envs\yolo_env\lib\site-packages\torch\serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

Why can I use the yolov8l-face.pt model in CLI but cannot through this python method?

### Environment

Ultralytics YOLOv8.1.1 🚀 Python-3.9.18 torch-2.1.2+cpu CPU (13th Gen Intel Core(TM) i9-13900H)
Model summary (fused): 268 layers, 43607379 parameters, 0 gradients, 164.8 GFLOPs

### Minimal Reproducible Example

from ultralytics import YOLO
model = YOLO('yolov8l-face.pt')
source = 'examples/face2.jpg'
results = model(source)  

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@med-tim hello! It seems you've encountered a discrepancy between the CLI and Python usage with the `yolov8l-face.pt` model. The warning indicates that `omegaconf` is required for this model, which is no longer included in the Ultralytics requirements. This is likely causing the issue when you try to load the model in Python.

For now, you can manually install `omegaconf` to resolve the issue, but please note that this is a temporary fix. We recommend updating to the latest YOLOv8 models that do not require `omegaconf`. You can find these updated models in our assets repository.

We appreciate your willingness to contribute! If you're interested in helping further, consider updating the model to be compatible with the latest YOLOv8 requirements and submitting a PR. Your efforts help improve the experience for the entire community. 🌟

For more guidance on Predict mode and model usage, please refer to our documentation at https://docs.ultralytics.com/modes/predict. Thank you for bringing this to our attention, and we look forward to your PR!

**Comment by med-tim** [comment]
Thanks for the reply! I already have omegaconf installed but that still wont work. Are they any other workarounds where I can still use this great model as is? I just find it odd that I can use it in CLI but not python

**Comment by glenn-jocher** [comment]
@med-tim, it's intriguing that the CLI works but Python doesn't, despite having `omegaconf` installed. This could be due to environment differences or the way the model is loaded in Python. As a workaround, ensure your Python environment matches the CLI environment closely. If the issue persists, consider re-downloading the model from our assets repository to ensure you have the latest compatible version.

If you're still facing difficulties, please open an issue with detailed environment information and any error messages, and we'll look into it further. Thanks for your patience and for using YOLOv8! 🛠️
