### ISSUE TITLE
How do yolov8 save the bounding box coordinates

### ISSUE THREAD

**Issue by Bhargav230m** [ultralytics/ultralytics#7719]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am Bhargav230m. I was working on a python project where users can autoannotate, their images. I have a question that how do they save the bounding box coordinates, Right now i am talking about detection models. I have implemented the following code to do it for me.

```py
import os
import json
import random
import shutil
from ultralytics import YOLO

# Path to the directory containing images
image_directory = './training'

# Output directory for text files
output_directory = './labels'

# Unlabeled image directory for images that weren't detected by the model
unlabeled_directory = "./unlabeled"

# Model used to annotate
model = YOLO("./v2.pt")

os.makedirs(output_directory, exist_ok=True)


def createBackup(image_directory):
    randomNumber = random.randint(28, 9293)
    backup_directory = f"backup{randomNumber}"
    
    # Handle the situation where the backup directory already exists
    while os.path.exists(backup_directory):
        randomNumber = random.randint(28, 9293)
        backup_directory = f"backup{randomNumber}"
    
    try:
        shutil.copytree(image_directory, backup_directory)
        print(f"Backup created successfully: {backup_directory}")
    except Exception as e:
        print(f"Error creating backup: {e}")

# Creating backup
print("Creating backup!")
createBackup(os.path.join(image_directory))

# Loop through all files in the image directory
for filename in os.listdir(image_directory):
    if filename.endswith('.jpg') or filename.endswith('.png'):
        prediction = model.predict(os.path.join(image_directory, filename), save=True, stream=True)
        for r in prediction:  # Looping through the results
            if r:  # If result then execute the inside code 
                for box in r.boxes:
                    x, y, w, h = box.xywh[0].tolist() # Get the x, y, w, h coordinates.
                    

                    # Create the path for the text file in the output directory
                    txt_filename = os.path.join(output_directory, os.path.splitext(filename)[0] + '.txt')

                    # Write the content to the text file
                    with open(txt_filename, 'w') as txt_file:
                        txt_file.write("0 " + str(x) + " " + str(y) + " " + str(w) + " " + str(h))
            
                    print(f"Annotated {filename}")
            else:
                shutil.move(os.path.join(image_directory, filename), os.path.join(unlabeled_directory, filename))
                print(f"Failed to annotate {filename}. *No Detection by model*, skipping..")
```

When i save the coordinates and use it to train the new model, it says the labels are corrupt. The logs for it is provided in the additional section

### Additional

Command Used:
```shell
!yolo mode=train batch=8 epochs=100 data=/content/data/data.yaml imgsz=640 task=detect
```
Colab Logs:
```bash
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...
100% 6.23M/6.23M [00:00<00:00, 76.0MB/s]
Ultralytics YOLOv8.1.3 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.20GHz)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/content/data/data.yaml, epochs=100, time=None, patience=50, batch=8, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...
100% 755k/755k [00:00<00:00, 17.2MB/s]
2024-01-21 12:28:32.384803: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-21 12:28:32.384871: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-21 12:28:32.386439: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]           
Model summary: 225 layers, 3011043 parameters, 3011027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
train: Scanning /content/data/train/labels... 1 images, 0 backgrounds, 1 corrupt: 100% 1/1 [00:00<00:00, 107.86it/s]
train: WARNING ⚠️ /content/data/train/images/_mp_1064953_jpg.rf.9ee061096830545687f67e29e80beec7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     323.22      312.83      633.56      615.23]
train: New cache created: /content/data/train/labels.cache
WARNING ⚠️ No images found in /content/data/train/labels.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 567, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 391, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 286, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/build.py", line 87, in build_yolo_dataset
    return YOLODataset(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py", line 42, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py", line 74, in __init__
    self.labels = self.get_labels()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py", line 138, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)
```

**Comment by glenn-jocher** [comment]
@Bhargav230m hello Bhargav230m,

It seems like there might be an issue with the way the bounding box coordinates are being saved. The coordinates should be normalized between 0 and 1 relative to the image width and height, and the format should be `[class, x_center, y_center, width, height]`. The error message indicates that the coordinates are either non-normalized or out of bounds.

Please ensure that:
1. The coordinates are normalized by dividing `x_center` and `width` by the image width, and `y_center` and `height` by the image height.
2. The class index is correct and corresponds to the class labels in your dataset.
3. The label files are saved with the same base name as the corresponding images and are in the same directory as specified in your data.yaml file.

For more detailed guidance on dataset formatting and troubleshooting, please refer to the documentation on detection tasks at https://docs.ultralytics.com/tasks/detect.

**Comment by Bhargav230m** [comment]
Hey thanks mate, i just had to do it xywhn to get the normalized output.

Really appreciate your help!. Keep improving this package. Thanks

**Comment by glenn-jocher** [comment]
@Bhargav230m you're welcome! I'm glad to hear you've resolved the issue. The credit goes to the entire YOLO community and the Ultralytics team for their continuous efforts. If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊🚀

**Comment by INDRAJITH-9388** [comment]
How do i convert the normalized bounding box coordinates into a non-normalized coordinates?

**Comment by glenn-jocher** [comment]
Hello! To convert the normalized bounding box coordinates back to non-normalized (pixel) coordinates, you just need to multiply the normalized values by the dimensions of the original image. Here's a quick example for you:

```python
# Assuming x, y are the center coordinates and w, h are the width and height 
# normalized on a scale of [0, 1], and img_width, img_height are 
# the dimensions of the original image:
x_pixel = x * img_width
y_pixel = y * img_height
w_pixel = w * img_width
h_pixel = h * img_height
```

This should give you the bounding box coordinates in pixels. 😊 Let me know if you need further clarification!
