### ISSUE TITLE
Get Error when trying converting dynamic batch fp16 format to ONNX model

### ISSUE THREAD

**Issue by peterer0625** [ultralytics/ultralytics#8045]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Get Error when trying converting dynamic batch fp16 format to ONNX model

D:\ultralytics>yolo export model=yolov8l-pose.pt format=onnx imgsz=640,640 dynamic=True half=True
Ultralytics YOLOv8.0.238 🚀 Python-3.10.13 torch-2.0.0+cpu CPU (13th Gen Intel Core(TM) i5-13500)
WARNING ⚠️ half=True only compatible with GPU export, i.e. use device=0
Traceback (most recent call last):
  File "C:\Users\KT\miniconda3\envs\onnx_yolov\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\KT\miniconda3\envs\onnx_yolov\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\KT\miniconda3\envs\onnx_yolov\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\KT\miniconda3\envs\onnx_yolov\lib\site-packages\ultralytics\cfg\__init__.py", line 466, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\KT\miniconda3\envs\onnx_yolov\lib\site-packages\ultralytics\engine\model.py", line 328, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "C:\Users\KT\miniconda3\envs\onnx_yolov\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\KT\miniconda3\envs\onnx_yolov\lib\site-packages\ultralytics\engine\exporter.py", line 181, in __call__
    assert not self.args.dynamic, 'half=True not compatible with dynamic=True, i.e. use only one.'
AssertionError: half=True not compatible with dynamic=True, i.e. use only one.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@peterer0625 hello! It looks like you've encountered an issue with exporting to ONNX with both dynamic batching and FP16 precision enabled. As indicated by the warning and assertion error, these two options are currently not compatible with each other. To resolve this, please choose either dynamic batching (`dynamic=True`) or FP16 precision (`half=True`), but not both at the same time. If you require FP16 precision, ensure that you're exporting on a GPU by setting `device=0`. For further details on export options, you can refer to our documentation on the Export mode. If you continue to face issues, please feel free to reach out again. Happy coding! 😊
