### ISSUE TITLE
for p in model.parameters(): AttributeError: 'str' object has no attribute 'parameters'

### ISSUE THREAD

**Issue by Kamlesh364** [ultralytics/ultralytics#806]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

```intern@training:~$ yolo classify train model=yolov8m-cls.pt data="Coco-Cls" epochs=300 patience=0 mosaic=0.5 imgsz=128 batch=256 device=\'0','1','2','3\'
Ultralytics YOLOv8.0.25 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 14960MiB)
                                                            CUDA:1 (Tesla T4, 14960MiB)
                                                            CUDA:2 (Tesla T4, 14960MiB)
                                                            CUDA:3 (Tesla T4, 14960MiB)
yolo/engine/trainer: task=classify, mode=train, model=yolov8m-cls.pt, data=Coco-Cls, epochs=300, patience=0, batch=256, imgsz=128, save=True, cache=False, device=0,1,2,3, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=0.5, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs/classify/train11
Overriding model.yaml nc=1000 with nc=80

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]           
  7                  -1  1   2655744  ultralytics.nn.modules.Conv                  [384, 768, 3, 2]              
  8                  -1  2   7084032  ultralytics.nn.modules.C2f                   [768, 768, 2, True]           
  9                  -1  1   1088080  ultralytics.nn.modules.Classify              [768, 80]                     
YOLOv8m-cls summary: 141 layers, 15874816 parameters, 15874816 gradients, 42.0 GFLOPs
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
DDP settings: RANK 0, WORLD_SIZE 4, DEVICE cuda:0
Traceback (most recent call last):
  File "/home/intern/.config/Ultralytics/DDP/_temp_k7zgde45139920732441328.py", line 6, in <module>
    trainer.train()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 198, in _setup_train
    ckpt = self.setup_model()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/train.py", line 59, in setup_model
    for p in model.parameters():
AttributeError: 'str' object has no attribute 'parameters'
Traceback (most recent call last):
  File "/home/intern/.config/Ultralytics/DDP/_temp_k7zgde45139920732441328.py", line 6, in <module>
    trainer.train()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 198, in _setup_train
    ckpt = self.setup_model()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/train.py", line 59, in setup_model
    for p in model.parameters():
AttributeError: 'str' object has no attribute 'parameters'
Traceback (most recent call last):
  File "/home/intern/.config/Ultralytics/DDP/_temp_k7zgde45139920732441328.py", line 6, in <module>
    trainer.train()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 198, in _setup_train
    Traceback (most recent call last):
ckpt = self.setup_model()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/train.py", line 59, in setup_model
  File "/home/intern/.config/Ultralytics/DDP/_temp_k7zgde45139920732441328.py", line 6, in <module>
    for p in model.parameters():
AttributeError: 'str' object has no attribute 'parameters'
    trainer.train()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 198, in _setup_train
    ckpt = self.setup_model()
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/train.py", line 59, in setup_model
    for p in model.parameters():
AttributeError: 'str' object has no attribute 'parameters'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 188642) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/intern/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/home/intern/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/intern/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/intern/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/intern/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/intern/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/intern/.config/Ultralytics/DDP/_temp_k7zgde45139920732441328.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-02-05_06:02:52
  host      : training.us-central1-a.c.gcp-colab-348506.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 188643)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-02-05_06:02:52
  host      : training.us-central1-a.c.gcp-colab-348506.internal
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 188644)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-02-05_06:02:52
  host      : training.us-central1-a.c.gcp-colab-348506.internal
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 188645)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-05_06:02:52
  host      : training.us-central1-a.c.gcp-colab-348506.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 188642)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/intern/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 266, in entrypoint
    getattr(model, mode)(**vars(cfg))
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 211, in train
    self.model, _ = attempt_load_one_weight(str(self.trainer.best))
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 384, in attempt_load_one_weight
    ckpt = torch_safe_load(weight)  # load ckpt
  File "/home/intern/.local/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 332, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/home/intern/.local/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/intern/.local/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/intern/.local/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/classify/train11/weights/best.pt'
```

### Environment

OS: Ubuntu 20.04
GPU: 4x Nvidia T4

### Minimal Reproducible Example

yolo classify train model="yolov8m-cls.pt" epochs=300 patience=0 mosaic=0.5 imgsz=128 batch=256 device=\'0','1','2','3\'

### Additional

Issue comes only with multiple GPUs.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by triple-Mu** [comment]
How about yolo classify train model=yolov8m-cls.pt epochs=300 patience=0 mosaic=0.5 imgsz=128 batch=256 device=0,1,2,3

**Comment by AyushExel** [comment]
@Kamlesh364 please try the syntax as mentioned by @triple-Mu above. Let us know if you still face any error

**Comment by Kamlesh364** [comment]
@AyushExel @triple-Mu thanks for the suggestion, but still not working

**Comment by AyushExel** [comment]
@Kamlesh364 same error?

**Comment by Kamlesh364** [comment]
> @Kamlesh364 same error?

yea

**Comment by glenn-jocher** [comment]
@Kamlesh364 I'm able to reproduce, will take a look.

**Comment by glenn-jocher** [comment]
@Kamlesh364 fixed in https://github.com/ultralytics/ultralytics/pull/813/commits/85280613faa4bf0c6a0c8dbb9d2bfce67b182ca0 to be deployed with 8.0.29 tonight.
