### ISSUE TITLE
error trainm TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by 1737686924** [ultralytics/ultralytics#8072]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Traceback (most recent call last):
  File "/root/.local/ultralytics-main/train.py", line 11, in <module>
    main()
  File "/root/.local/ultralytics-main/train.py", line 6, in main
    result = model.train(data='fllowers', epochs=20, imgsz=64)
  File "/root/.local/ultralytics-main/ultralytics/engine/model.py", line 390, in train
    self.trainer.train()
  File "/root/.local/ultralytics-main/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/root/.local/ultralytics-main/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/root/.local/ultralytics-main/ultralytics/engine/trainer.py", line 289, in _setup_train
    self.test_loader = self.get_dataloader(
  File "/root/.local/ultralytics-main/ultralytics/models/yolo/classify/train.py", line 88, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode)
  File "/root/.local/ultralytics-main/ultralytics/models/yolo/classify/train.py", line 83, in build_dataset
    return ClassificationDataset(root=img_path, args=self.args, augment=mode == "train", prefix=mode)
  File "/root/.local/ultralytics-main/ultralytics/data/dataset.py", line 247, in __init__
    super().__init__(root=root)
  File "/root/miniconda3/envs/env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/root/miniconda3/envs/env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/root/miniconda3/envs/env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 189, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/root/miniconda3/envs/env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 61, in make_dataset
    directory = os.path.expanduser(directory)
  File "/root/miniconda3/envs/env/lib/python3.9/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Newspaperman57** [comment]
Hi
I'm having the same problem. https://docs.ultralytics.com/ is currently not working for me (it's returning 502), so if something is missing please let me know and i will add it.

Versions:
```
Python 3.10.12
Ultralytics 8.1.6
Torch 2.2.0
```

Python-script:
```
from ultralytics import YOLO

model = YOLO('yolov8x-cls.pt')
results = model.train(data='classification', epochs=10)
```

Directory layout:
```
./classification
./classification/train
./classification/train/notpresent
./classification/train/present
```

`present` and `notpresent` being the 2 classes i'm trying to train the classifier on, having a combined 1000 jpgs

Full log:
```
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8x-cls.pt to 'yolov8x-cls.pt'...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 110M/110M [00:03<00:00, 37.6MB/s]
Ultralytics YOLOv8.1.16 🚀 Python-3.10.12 torch-2.2.0+cu121 CUDA:0 (Tesla T4, 14930MiB)
engine/trainer: task=classify, mode=train, model=yolov8x-cls.pt, data=classification, epochs=10, time=None, patience=100, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train
train: /root/datasets/test/classification/train... found 1000 images in 2 classes ✅ 
val: None...
test: None...
2024-02-20 14:47:26.563548: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-20 14:47:26.563598: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-20 14:47:26.564573: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Overriding model.yaml nc=1000 with nc=2

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]           
  7                  -1  1   7375360  ultralytics.nn.modules.conv.Conv             [640, 1280, 3, 2]             
  8                  -1  3  27865600  ultralytics.nn.modules.block.C2f             [1280, 1280, 3, True]         
  9                  -1  1   1643522  ultralytics.nn.modules.head.Classify         [1280, 2]                     
YOLOv8x-cls summary: 183 layers, 56144402 parameters, 56144402 gradients, 154.3 GFLOPs
Transferred 300/302 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/classify/train', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.23M/6.23M [00:00<00:00, 89.0MB/s]
AMP: checks passed ✅
train: Scanning /root/datasets/test/classification/train... 1000 images, 0 corrupt: 100%|██████████| 1000/1000 [00:00<00:00, 3787.35it/s]
train: New cache created: /root/datasets/test/classification/train.cache
Traceback (most recent call last):
  File "/root/datasets/test/test.py", line 4, in <module>
    results = model.train(data='classification', epochs=10)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 645, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 289, in _setup_train
    self.test_loader = self.get_dataloader(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/classify/train.py", line 88, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/classify/train.py", line 83, in build_dataset
    return ClassificationDataset(root=img_path, args=self.args, augment=mode == "train", prefix=mode)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py", line 252, in __init__
    super().__init__(root=root)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 145, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 189, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py", line 61, in make_dataset
    directory = os.path.expanduser(directory)
  File "/usr/lib/python3.10/posixpath.py", line 232, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Newspaperman57** [comment]
Just found the `yolo checks` command in the bug template, so pasting it aswell:

```
Ultralytics YOLOv8.1.16 🚀 Python-3.10.12 torch-2.2.0+cu121 CUDA:0 (Tesla T4, 14930MiB)
Setup complete ✅ (8 CPUs, 31.3 GB RAM, 71.4/76.5 GB disk)

OS                  Linux-5.15.0-94-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 31.34 GB
CPU                 Intel Xeon Gold 6226R 2.90GHz
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 5.4.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

**Comment by glenn-jocher** [comment]
@Newspaperman57 hey there! Thanks for providing the additional `yolo checks` output. It looks like your environment is all set up correctly, which is great. 👍

The error you're encountering seems to be related to the `data` argument in your training script. The `data` argument expects a path to a YAML file that describes your dataset, but it seems like it's receiving a string `'classification'` which it's interpreting as a directory path, hence the `NoneType` error.

Here's a quick fix you can try. Make sure you have a YAML file that describes your dataset, something like `classification.yaml`, and pass that to the `data` argument:

```python
from ultralytics import YOLO

model = YOLO('yolov8x-cls.pt')
results = model.train(data='classification.yaml', epochs=10)
```

And your `classification.yaml` should look something like this:

```yaml
train: ./classification/train
val: ./classification/val  # or whatever your validation set path is

nc: 2  # number of classes
names: ['notpresent', 'present']
```

Make sure the paths in the YAML file are correct and point to where your images and labels are stored. Give this a shot and let us know if it helps! 😊

**Comment by Newspaperman57** [comment]
Thank you for helping!

I initially tried using yaml, but i was receiving an error that suggested i needed to use the directory instead, which got me a little farther, which is how i wound up here in the first place :)

I updated ultralytics and tried using your example, except changing `data` to `/root/datasets/classification/classification.yaml` (since if i use a relative path, it seems to look in the parent directory?), and now i get the following output:
```
Ultralytics YOLOv8.1.17 🚀 Python-3.10.12 torch-2.2.0+cu121 CUDA:0 (Tesla T4, 14930MiB)
engine/trainer: task=classify, mode=train, model=yolov8x-cls.pt, data=/root/datasets/classification/classification.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train7, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train7

Dataset not found ⚠️, missing path /root/datasets/classification/classification.yaml, attempting download...
Dataset download success ✅ (0.0s), saved to /root/datasets/classification/classification.yaml

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 131, in __init__
    self.data = check_cls_dataset(self.args.data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py", line 396, in check_cls_dataset
    names = [x.name for x in (data_dir / "train").iterdir() if x.is_dir()]  # class names list
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py", line 396, in <listcomp>
    names = [x.name for x in (data_dir / "train").iterdir() if x.is_dir()]  # class names list
  File "/usr/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
NotADirectoryError: [Errno 20] Not a directory: '/root/datasets/classification/classification.yaml/train'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/datasets/classification/test.py", line 4, in <module>
    results = model.train(data='/root/datasets/classification/classification.yaml', epochs=10)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 625, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/classify/train.py", line 39, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 137, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset '/root/datasets/classification/classification.yaml' error ❌ [Errno 20] Not a directory: '/root/datasets/classification/classification.yaml/train'
```

Note that the path to the yaml exists and is valid. I'm just trying to get my feet wet at the moment, so i do not have a validation set ready yet
```
root@ai-test:~/datasets/classification# cat /root/datasets/classification/classification.yaml
train: ./dataset/train
# val: ./dataset/val  # or whatever your validation set path is

nc: 2  # number of classes
names: ['notpresent', 'present']
```

**Comment by glenn-jocher** [comment]
@Newspaperman57 hey there!

I'm glad to hear that you've managed to resolve the issue by defining a validation or test set. 😊 It's true that for training, having a validation set is important as it helps to evaluate the model's performance on unseen data, which is crucial for understanding how well your model generalizes.

I appreciate your suggestion to improve our documentation. We always aim to make our resources as clear and helpful as possible, and feedback like yours is invaluable for that. I'll make sure to pass on your comments to our documentation team to consider adding a note about the necessity of a validation or test set.

If you have any more questions or run into further issues, don't hesitate to reach out. Happy training! 🚀
