### ISSUE TITLE
No model weights saved and no weights folder when using model.tune()

### ISSUE THREAD

**Issue by Johnny-zbb** [ultralytics/ultralytics#8093]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Code for the finetune model:
```
from ultralytics import YOLO

# Define a YOLO model
model = YOLO("/root/coding/yolo-seg/train/runs/segment/train/weights/best.pt")

# Run Ray Tune on the model
result_grid = model.tune(data="dataset/data.yaml",
                         epochs=20,
                         save=True,
                         device=1,
                         use_ray=False)
```
There is an error in the training process, but it's not an error in saving the weights, that's what my console prints:
```
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 2.99454
warmup_momentum: 0.80046
box: 7.51815
cls: 0.49892
dfl: 1.50007
...
Transferred 417/417 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?0946cc96-7e29-49e2-837b-25860607c15a) or open in a [text editor](command:workbench.action.openLargeOutput?0946cc96-7e29-49e2-837b-25860607c15a). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
train: Scanning /root/coding/yolo-seg/tune/dataset/train/labels.cache... 820 images, 14 backgrounds, 0 corrupt: 100%|██████████| 820/820 [00:00<?, ?it/s]
val: Scanning /root/coding/yolo-seg/tune/dataset/valid/labels.cache... 104 images, 0 backgrounds, 0 corrupt: 100%|██████████| 104/104 [00:00<?, ?it/s]
Plotting labels to runs/segment/train3/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.00966' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00048), 76 bias(decay=0.0)
20 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       1/20      2.66G     0.9581      1.218     0.8728     0.9409         88        640:   2%|▏         | 1/52 [00:00<00:21,  2.34it/s]Exception in thread Thread-5 (plot_images):
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 620, in plot_images
    conf = confs[idx] if confs is not None else None  # check for confidence presence (label vs pred)
IndexError: The shape of the mask [88] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0
       1/20      2.66G     0.8578      1.121     0.7515     0.9664        106        640:   2%|▏         | 1/52 [00:00<00:21,  2.34it/s]Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 620, in plot_images
    conf = confs[idx] if confs is not None else None  # check for confidence presence (label vs pred)
IndexError: The shape of the mask [106] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0
       1/20      2.66G     0.7951      1.043     0.7379     0.9708         83        640:   6%|▌         | 3/52 [00:00<00:08,  5.97it/s]Exception in thread Thread-7 (plot_images):
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 620, in plot_images
    conf = confs[idx] if confs is not None else None  # check for confidence presence (label vs pred)
IndexError: The shape of the mask [83] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0
       1/20      2.85G     0.7239      1.029     0.6775     0.9306         38        640: 100%|██████████| 52/52 [00:05<00:00,  9.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.74it/s]
                   all        104        512      0.727      0.711      0.788      0.556      0.741      0.725      0.803       0.49

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       2/20      2.93G     0.7628       1.09     0.7196      0.941         12        640: 100%|██████████| 52/52 [00:06<00:00,  8.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 10.45it/s]
                   all        104        512      0.722      0.705      0.763      0.506      0.732      0.715      0.772      0.464

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       3/20      2.92G     0.7827      1.105     0.7352     0.9319         41        640: 100%|██████████| 52/52 [00:03<00:00, 17.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.65it/s]
                   all        104        512      0.705      0.668      0.732      0.489      0.705      0.674      0.743      0.428

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       4/20      2.93G     0.8346      1.161      0.807     0.9702         19        640: 100%|██████████| 52/52 [00:02<00:00, 18.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 15.24it/s]
                   all        104        512      0.812      0.656       0.79      0.514       0.81      0.666      0.797      0.474

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       5/20      2.93G     0.8393      1.163     0.7953     0.9602         27        640: 100%|██████████| 52/52 [00:02<00:00, 18.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.99it/s]
                   all        104        512      0.772      0.641       0.75      0.497      0.781      0.648      0.753      0.469

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       6/20      2.88G     0.8347      1.149     0.8054     0.9687         12        640: 100%|██████████| 52/52 [00:02<00:00, 17.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.40it/s]
                   all        104        512      0.724      0.758      0.791      0.545      0.752      0.745      0.804      0.482

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       7/20      2.86G     0.8137      1.108     0.7789     0.9613         40        640: 100%|██████████| 52/52 [00:02<00:00, 18.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.65it/s]
                   all        104        512      0.705      0.721      0.763      0.522      0.721      0.721      0.774      0.468

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       8/20      2.86G     0.8187      1.147     0.7679     0.9575         28        640: 100%|██████████| 52/52 [00:02<00:00, 18.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.11it/s]
                   all        104        512      0.729      0.756      0.801      0.543      0.729      0.756      0.801      0.483

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       9/20      2.94G     0.7885      1.123     0.7553     0.9462         34        640: 100%|██████████| 52/52 [00:02<00:00, 18.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 15.22it/s]
                   all        104        512      0.706      0.712      0.767      0.526      0.715      0.722      0.785      0.478

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      10/20      2.97G     0.7882       1.11     0.7442     0.9475         37        640: 100%|██████████| 52/52 [00:02<00:00, 18.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.98it/s]
                   all        104        512      0.753      0.709      0.786       0.54       0.76      0.705      0.796      0.469
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      11/20      2.66G     0.8108       1.22     0.7554     0.9082         70        640:   2%|▏         | 1/52 [00:00<00:09,  5.19it/s]Exception in thread Thread-9 (plot_images):
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 620, in plot_images
    conf = confs[idx] if confs is not None else None  # check for confidence presence (label vs pred)
IndexError: The shape of the mask [70] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0
      11/20      2.68G     0.7055      1.091     0.7514      0.932         39        640:   2%|▏         | 1/52 [00:00<00:09,  5.19it/s]Exception in thread Thread-10 (plot_images):
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 620, in plot_images
    conf = confs[idx] if confs is not None else None  # check for confidence presence (label vs pred)
IndexError: The shape of the mask [39] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0
      11/20      2.68G     0.7023      1.079     0.7306     0.9152         72        640:   6%|▌         | 3/52 [00:00<00:05,  9.22it/s]Exception in thread Thread-11 (plot_images):
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 620, in plot_images
    conf = confs[idx] if confs is not None else None  # check for confidence presence (label vs pred)
IndexError: The shape of the mask [72] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0
      11/20      2.83G     0.7804      1.103     0.7547     0.9372         10        640: 100%|██████████| 52/52 [00:02<00:00, 17.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.86it/s]
                   all        104        512      0.757      0.658      0.744      0.498      0.778      0.666      0.753       0.46

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      12/20      2.76G     0.7662       1.08     0.7182     0.9276         23        640: 100%|██████████| 52/52 [00:02<00:00, 18.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.27it/s]
                   all        104        512      0.702      0.686      0.756      0.522      0.678      0.727      0.766      0.468

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      13/20      2.87G     0.7607      1.054     0.6892      0.928         14        640: 100%|██████████| 52/52 [00:02<00:00, 19.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 15.10it/s]
                   all        104        512      0.768      0.682       0.78      0.527      0.774      0.682      0.783      0.473

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      14/20      2.84G     0.7341      1.034     0.6703     0.9258         12        640: 100%|██████████| 52/52 [00:02<00:00, 19.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.69it/s]
                   all        104        512      0.759      0.629      0.737      0.496      0.707      0.688      0.746      0.455

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      15/20      2.86G     0.7301      1.015     0.6597      0.913         14        640: 100%|██████████| 52/52 [00:02<00:00, 19.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 15.04it/s]
                   all        104        512       0.75      0.696      0.788      0.551      0.765      0.695       0.79      0.491

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      16/20      2.82G     0.6921      1.001     0.6233     0.9094         14        640: 100%|██████████| 52/52 [00:02<00:00, 19.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 15.37it/s]
                   all        104        512      0.805      0.682      0.798      0.543      0.795      0.681      0.796      0.495

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      17/20      2.78G     0.6841     0.9759     0.5996      0.903          7        640: 100%|██████████| 52/52 [00:02<00:00, 18.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 14.48it/s]
                   all        104        512      0.774      0.686      0.789      0.545      0.788      0.672      0.793      0.485

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      18/20      2.79G      0.686     0.9792     0.6042     0.8957         17        640: 100%|██████████| 52/52 [00:02<00:00, 18.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 15.36it/s]
                   all        104        512      0.786      0.668      0.775      0.532      0.791      0.672      0.785      0.483

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      19/20      2.88G     0.6625     0.9618      0.571     0.8882         17        640: 100%|██████████| 52/52 [00:02<00:00, 19.34it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 15.43it/s]
                   all        104        512       0.79      0.693      0.797      0.539      0.782      0.707      0.799      0.501

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      20/20      2.75G     0.6505     0.9278     0.5576     0.8833         13        640: 100%|██████████| 52/52 [00:02<00:00, 19.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 13.93it/s]
                   all        104        512      0.722       0.73      0.784      0.542      0.769      0.684      0.786      0.494

20 epochs completed in 0.021 hours.
Optimizer stripped from runs/segment/train3/weights/last.pt, 6.8MB
Optimizer stripped from runs/segment/train3/weights/best.pt, 6.8MB

Validating runs/segment/train3/weights/best.pt...
Ultralytics YOLOv8.0.237 🚀 Python-3.10.13 torch-2.1.2+cu121 CUDA:1 (NVIDIA GeForce RTX 4090, 24217MiB)
YOLOv8n-seg summary (fused): 195 layers, 3258259 parameters, 0 gradients, 12.0 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.40it/s]
                   all        104        512      0.729      0.711      0.789      0.556      0.743      0.724      0.803      0.489
Speed: 0.2ms preprocess, 1.8ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to runs/segment/train3
💡 Learn more at https://docs.ultralytics.com/modes/train
Saved runs/segment/tune8/tune_scatter_plots.png
Saved runs/segment/tune8/tune_fitness.png

Tuner: 3/10 iterations complete ✅ (278.52s)
Tuner: Results saved to runs/segment/tune8
Tuner: Best fitness=1.12959 observed at iteration 2
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.78556, 'metrics/recall(B)': 0.69401, 'metrics/mAP50(B)': 0.80274, 'metrics/mAP50-95(B)': 0.55968, 'metrics/precision(M)': 0.78347, 'metrics/recall(M)': 0.69922, 'metrics/mAP50(M)': 0.81037, 'metrics/mAP50-95(M)': 0.51619, 'val/box_loss': 1.02883, 'val/seg_loss': 1.26421, 'val/cls_loss': 0.98081, 'val/dfl_loss': 1.06424, 'fitness': 1.12959}
Tuner: Best fitness model is runs/segment/train2
Tuner: Best fitness hyperparameters are printed below.
```

![image](https://github.com/ultralytics/ultralytics/assets/54133977/1070c648-c15b-4065-ae32-e0a354d1e95c)

**Comment by Johnny-zbb** [comment]
@glenn-jocher Yes, I made sure `save=True`, but it still appears that weights are not saved in some of the trains, and in fact other trians have had the same problem but kept the weights.

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by abdulmominseo** [comment]
My 52-Week Weight Loss Journey Unveiled | Ian Melton's weight loss story
Rating-⭐⭐⭐⭐⭐
[Click full video](https://youtu.be/P2aNQFrT0yM?si=EJs5XkHPzSwgo1kl)

**Comment by glenn-jocher** [comment]
@abdulmominseo hey there! 👋 It looks like there might have been a mix-up with the content of your message. If you have any questions or issues related to YOLOv8, feel free to share them, and I'd be more than happy to assist you. If you're looking to share a personal journey or story, that's awesome, and I wish you the best – but this platform is more focused on technical support for YOLOv8. Let me know how I can help with your YOLOv8 needs! 😊
