### ISSUE TITLE
Troubleshooting Multi-GPU Training Initialization with PyTorch Ignite

### ISSUE THREAD

**Issue by Buckler89** [ultralytics/ultralytics#8111]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found similar related: #6913 

### Question

Hi @glenn-jocher 

I'm trying to implement multi-GPU training directly from Python using PyTorch Ignite's [`Parallel`](https://pytorch.org/ignite/generated/ignite.distributed.launcher.Parallel.html#:~:text=for%20both%20options%3A-,%23%20main.py%0A%0Aimport%20ignite.distributed%20as%20idist%0A%0Adef%20training(local_rank,%2C%20config%2C%20a%3D1%2C%20b%3D2),-Single%20node%2C%20Multi) context manager, as opposed to initiating it from the command line. I've encountered issues when setting up distributed training, specifically with initializing the process group and managing devices for model training. Here's a brief overview of my setup:

main.py
```
...get hyper_params...
hyper_params["yolo_train"]["device"] = list(range(torch.cuda.device_count())) # equal to [0,1,2,3]

if __name__ == "__main__":
      backend = "nccl"  
      spawn_kwargs = {
          "nproc_per_node": len_available_devices,
          "init_method": "tcp://0.0.0.0:50001" # without this I got some problem with the default port 22222 already in use
      }
      print(f"Training on {len_available_devices} GPUs with backend {backend}")
      from experiment import main_experiment_wrapper
      with idist.Parallel(backend=backend, **spawn_kwargs) as parallel:
          parallel.run(main_experiment, hyper_params)
```

experiment.py
```
import os
import torch
import gc

import pandas as pd
import numpy as np
import time
import wandb
from wandb import util as wandb_util
from sklearn.metrics import confusion_matrix, f1_score
import plotly.figure_factory as ff
from tqdm import tqdm
import pickle
from pathlib import Path
import signal

try:
    import ignite.distributed as idist
except ImportError:
    print("ignite.distributed not installed. Install it with pip install pytorch-ignite")


def main_experiment(local_rank, hyper_params, **kwargs):
    print(f"PID = {os. getpid()} \t get_rank = {idist.get_rank()} \t backend= {idist.backend()}")
    print(f"{local_rank = } --- {kwargs = }")
    hyper_params["experiment_name"] = f"{hyper_params['group']}_gpu{local_rank}"
    hyper_params["wandb_run_id"] = wandb_util.generate_id()
    hyper_params["rank"] = local_rank

    from ultralytics import YOLO
    from ultralytics.utils import RANK, LOCAL_RANK # <---------------------- the import in this point let the env variable to be properly set
    from wandb.integration.ultralytics import add_wandb_callback
    import wandb_callbackv2 as wandb_callback

    print(f'Starting wandb run with id {hyper_params["wandb_run_id"]} \n {RANK = } \n {LOCAL_RANK = }')

  with wandb.init(project=hyper_params["project"],
                      group=hyper_params["group"],
                      job_type=hyper_params["job_type"],
                      name=hyper_params["experiment_name"],
                      id=hyper_params["wandb_run_id"],
                      resume="allow",
                      allow_val_change=True) as run:
            if  hyper_params["rank"] == 0: # <--------------------------------------------------- here I add my custom callbacks only to one process         
              for event, func in wandb_callback.callbacks.items():   
                  # model.add_callback(event, lambda trainer: func(trainer, start_step=wandb_step))
                  model.add_callback(event, func)

            model.train(
                project=hyper_params["project"],
                name=hyper_params["experiment_name"],
                data=hyper_params["yolo_train"]["data_yolo_path"],
                cfg=hyper_params["cfg"],
                # parameters for training
                device=hyper_params["yolo_train"]["device"],    <---------------------------------------------- Do I need to manage this somehow?
               .......others parameters....
            )
```

The training process starts correctly across multiple processes with distinct ranks. 
```
--------------------
PID = 30186      get_rank = 0    backend= nccl
local_rank = 0 --- kwargs = {}
Starting wandb run with id 7oj8384j 
 RANK = 0
 LOCAL_RANK = 0
--------------------

PID = 30187      get_rank = 1    backend= nccl
local_rank = 1 --- kwargs = {}
Starting wandb run with id p4e6j10h 
 RANK = 1 
 LOCAL_RANK = 1
--------------------

PID = 30189      get_rank = 3    backend= nccl
local_rank = 3 --- kwargs = {}
Starting wandb run with id nymfkbo6 
 RANK = 3
 LOCAL_RANK = 3
--------------------

PID = 30188      get_rank = 2    backend= nccl
local_rank = 2 --- kwargs = {}
Starting wandb run with id k1wpvsje 
 RANK = 2
 LOCAL_RANK = 2
--------------------
```

However, I encounter a RuntimeError regarding the reinitialization of the default process group for each process I see that error 4 times in the log)
```
          Traceback (most recent call last):
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
        fn(i, *args)
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ignite/distributed/comp_models/native.py", line 341, in _dist_worker_task_fn
        fn(local_rank, *args, **kw_dict)
      File "/teamspace/studios/this_studio/code/fine_tuning/experiment.py", line 54, in main_experiment_wrapper
        main_experiment(hyper_params)
      File "/teamspace/studios/this_studio/code/fine_tuning/experiment.py", line 159, in main_experiment
        model.train(
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/model.py", line 391, in train
        self.trainer.train()
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 208, in train
        self._do_train(world_size)
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 321, in _do_train
        self._setup_ddp(world_size)
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 224, in _setup_ddp
        dist.init_process_group(
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
        func_return = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1100, in init_process_group
        raise RuntimeError("trying to initialize the default process group twice!")
    RuntimeError: trying to initialize the default process group twice!
```

Here are my specific questions:

1. Could you provide a corrected example of how to initialize and manage multi-GPU training using PyTorch Ignite's `Parallel`, ensuring that the process group is only initialized once and correctly?

2. In the `model.train()` method, is there a need to explicitly manage the `device` parameter differently for distributed training, or does Ignite handle this automatically?

3. I'm not entirely confident in my handling of custom callbacks, especially ensuring they're only added to one process (rank 0). Could you review my approach and suggest any necessary adjustments?

For additional context, I'm successfully able to run multi-GPU training using the Ultralytics library's built-in methods, but my custom callbacks do not execute as expected, prompting this manual approach. 

Thank you for your guidance on these issues.

**Comment by glenn-jocher** [comment]
@Buckler89 hi there! 👋

It looks like you've done a thorough job searching for related issues and discussions. For multi-GPU training with PyTorch Ignite's `Parallel`, you'll want to ensure that the process group is initialized only once. Here's a quick guide:

1. Ensure that `dist.init_process_group()` is called once per process. This is typically handled by Ignite's `Parallel` context manager, so you shouldn't need to call it manually.

2. The `device` parameter in `model.train()` should be set to the local rank of the process. Ignite's `idist.get_local_rank()` can provide this, and you can pass it to `model.train(device=idist.get_local_rank())`.

3. For custom callbacks, adding them only to the process with rank 0 is correct. You can check the rank using `idist.get_rank()` and conditionally add callbacks if the rank is 0.

If you're encountering issues with the default port, specifying an `init_method` as you've done is a good approach. For further assistance, feel free to share more details or error logs.

Happy training! 🚀
