### ISSUE TITLE
pose model doen't train on multipe GPUs

### ISSUE THREAD

**Issue by staeff777** [ultralytics/ultralytics#8240]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a strange problem (similar to #5821) when training my model that only occurs when I use multiple GPUs.

Im using 16 Keypoints with 3 dimensions.

I reduced the dataset to only a single entry to eliminate problems with bad keypoints (the last 8 keypoints are not visible):
```
1 0.800390625 0.83046875 0.03984375 0.0375 0.760782578125 0.8263955468749999 2 0.799370234375 0.895332578125 2 0.8214975781249999 0.808563984375 2 0.84004984375 0.8574367968750001 2 0.7614251562500001 0.83247140625 2 0.7900653906249999 0.81134640625 2 0.8023339062499999 0.84476984375 2 0.8209382812499999 0.8235798437499999 2 0.0 0.0 0 0.0 0.0 0 0.0 0.0 0 0.0 0.0 0 0.0 0.0 0 0.0 0.0 0 0.0 0.0 0 0.0 0.0 0
```
(Im using the same entry for different files and I halso have some background images in my set)

I always get it in the first Epoch following Error (I also disabled pretrained temporarily):
```
> yolo pose train data=/input/dataset.yaml project=/workspace epochs=1000 patience=150 imgsz=1280 model=yolov8x-pose-p6.yaml batch=3 lr0=0.1 optimizer=SGD pretrained=False device=0,1,2

Ultralytics YOLOv8.1.14 🚀 Python-3.8.10 torch-2.1.0a0+fe05266 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11009MiB)
                                                               CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
                                                               CUDA:2 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)

[34m[1mengine/trainer: [0mtask=pose, mode=train, model=yolov8x-pose-p6.yaml, data=/input/streets3.yaml, epochs=10000, time=None, patience=1500, batch=3, imgsz=1280, save=True, save_period=-1, cache=False, device=(0, 1, 2), workers=8, project=/workspace, name=train2, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.1, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/workspace/train2

Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...
  0%|          | 0.00/755k [00:00<?, ?B/s]
100%|██████████| 755k/755k [00:00<00:00, 40.0MB/s]

Overriding model.yaml kpt_shape=[17, 3] with kpt_shape=[16, 3]
Overriding model.yaml nc=1 with nc=10

2024-02-15_17:28:01.993 stdout                    from  n    params  module                                       arguments                     
2024-02-15_17:28:01.993 stdout   0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]                 
2024-02-15_17:28:01.993 stdout   1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]               
2024-02-15_17:28:01.993 stdout   2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]           
2024-02-15_17:28:01.993 stdout   3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]              
2024-02-15_17:28:01.993 stdout   4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]           
2024-02-15_17:28:01.993 stdout   5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]              
2024-02-15_17:28:01.993 stdout   6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]           
2024-02-15_17:28:01.993 stdout   7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
2024-02-15_17:28:01.993 stdout   8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]           
2024-02-15_17:28:01.993 stdout   9                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
2024-02-15_17:28:01.993 stdout  10                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]           
2024-02-15_17:28:01.993 stdout  11                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]                 
2024-02-15_17:28:01.993 stdout  12                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
2024-02-15_17:28:01.993 stdout  13             [-1, 8]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
2024-02-15_17:28:01.993 stdout  14                  -1  3   6764800  ultralytics.nn.modules.block.C2              [1280, 640, 3, False]         
2024-02-15_17:28:01.993 stdout  15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
2024-02-15_17:28:01.993 stdout  16             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
2024-02-15_17:28:01.993 stdout  17                  -1  3   6764800  ultralytics.nn.modules.block.C2              [1280, 640, 3, False]         
2024-02-15_17:28:01.993 stdout  18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
2024-02-15_17:28:01.993 stdout  19             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
2024-02-15_17:28:01.993 stdout  20                  -1  3   1795200  ultralytics.nn.modules.block.C2              [960, 320, 3, False]          
2024-02-15_17:28:01.993 stdout  21                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]              
2024-02-15_17:28:01.994 stdout  22            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
2024-02-15_17:28:01.994 stdout  23                  -1  3   6560000  ultralytics.nn.modules.block.C2              [960, 640, 3, False]          
2024-02-15_17:28:01.994 stdout  24                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
2024-02-15_17:28:01.994 stdout  25            [-1, 14]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
2024-02-15_17:28:01.994 stdout  26                  -1  3   6764800  ultralytics.nn.modules.block.C2              [1280, 640, 3, False]         
2024-02-15_17:28:01.994 stdout  27                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
2024-02-15_17:28:01.994 stdout  28            [-1, 11]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
2024-02-15_17:28:01.994 stdout  29                  -1  3   6764800  ultralytics.nn.modules.block.C2              [1280, 640, 3, False]         
2024-02-15_17:28:02.545 stdout  30    [20, 23, 26, 29]  1  13880824  ultralytics.nn.modules.head.Pose             [10, [16, 3], [320, 640, 640, 640]]
2024-02-15_17:28:03.998 stdout YOLOv8x-pose-p6 summary: 510 layers, 99193224 parameters, 99193208 gradients, 267.4 GFLOPs
2024-02-15_17:28:03.998 stdout 

2024-02-15_17:28:03.998 stdout [34m[1mDDP:[0m debug command /usr/bin/python3 -m torch.distributed.run --nproc_per_node 3 --master_port 49709 /root/.config/Ultralytics/DDP/_temp_qkt0wo3v139842914939472.py
2024-02-15_17:28:05.040 stderr WARNING:__main__:
2024-02-15_17:28:05.049 stderr *****************************************
2024-02-15_17:28:05.049 stderr Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
2024-02-15_17:28:05.049 stderr *****************************************
2024-02-15_17:28:08.011 stdout Ultralytics YOLOv8.1.14 ðŸš€ Python-3.8.10 torch-2.1.0a0+fe05266 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11009MiB)
2024-02-15_17:28:08.011 stdout                                                                CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
2024-02-15_17:28:08.011 stdout                                                                CUDA:2 (NVIDIA GeForce RTX 2080 Ti, 11012MiB)
2024-02-15_17:28:10.022 stdout [34m[1mTensorBoard: [0mStart with 'tensorboard --logdir /workspace/train2', view at http://localhost:6006/
2024-02-15_17:28:10.022 stdout Overriding model.yaml kpt_shape=[17, 3] with kpt_shape=[16, 3]
2024-02-15_17:28:10.022 stdout Overriding model.yaml nc=1 with nc=10
2024-02-15_17:28:12.028 stdout Freezing layer 'model.30.dfl.conv.weight'
2024-02-15_17:28:12.028 stdout [34m[1mAMP: [0mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
2024-02-15_17:28:12.028 stdout Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...

...

024-02-15_17:28:24.052 stdout       Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
2024-02-15_17:28:24.598 stderr 
2024-02-15_17:28:24.598 stderr   0%|          | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
2024-02-15_17:28:24.600 stderr   File "/root/.config/Ultralytics/DDP/_temp_qkt0wo3v139842914939472.py", line 12, in <module>
2024-02-15_17:28:24.600 stderr     results = trainer.train()
2024-02-15_17:28:24.600 stderr   File "/ultralytics/ultralytics/engine/trainer.py", line 208, in train
2024-02-15_17:28:24.600 stderr     self._do_train(world_size)
2024-02-15_17:28:24.600 stderr   File "/ultralytics/ultralytics/engine/trainer.py", line 376, in _do_train
2024-02-15_17:28:24.600 stderr     self.loss, self.loss_items = self.model(batch)
2024-02-15_17:28:24.600 stderr   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
2024-02-15_17:28:24.600 stderr     return forward_call(*args, **kwargs)
2024-02-15_17:28:24.600 stderr   File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1120, in forward
2024-02-15_17:28:24.600 stderr     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
2024-02-15_17:28:24.600 stderr RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
2024-02-15_17:28:24.600 stderr making sure all `forward` function outputs participate in calculating loss. 
2024-02-15_17:28:24.600 stderr If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
2024-02-15_17:28:24.601 stderr Parameter indices which did not receive grad for rank 2: 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428
2024-02-15_17:28:24.601 stderr  In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

```

When I start it with device=0, it works.

What could be the problem?

**Comment by glenn-jocher** [comment]
@staeff777 hey there! 👋 It seems like you're encountering an issue with multi-GPU training for your pose model. This error typically indicates that some model parameters were not used in the forward pass to compute the loss, which is a requirement when using `DistributedDataParallel`.

A quick thing you can try is to set `find_unused_parameters=True` when initializing `DistributedDataParallel`. This will help identify any unused parameters during the training process.

Here's a snippet on how you might modify your training script:

```python
# Assuming 'model' is your pose model
model = torch.nn.parallel.DistributedDataParallel(model, find_unused_parameters=True)
```

If you're using the Ultralytics YOLOv8 CLI, you might not have direct access to modify this, so you could try ensuring that all outputs from your model's forward function are used to compute the loss.

If the issue persists, could you please share more details about your model's forward function and how the loss is computed? This will help us diagnose the problem more effectively. 😊

Keep me posted!

**Comment by glenn-jocher** [comment]
@staeff777 hi there! 👋 It seems like you're encountering an issue with multi-GPU training for your pose model. The error message suggests that there are parameters in your model that aren't being used to compute the loss, which can happen when using `DistributedDataParallel`.

To resolve this, you can try the following:

1. Ensure that all outputs from your model's `forward` function are used in the loss computation.
2. Pass `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel` to detect any unused parameters.

Here's a small code snippet to illustrate how you might modify your training script:

```python
from torch.nn.parallel import DistributedDataParallel as DDP

# Assuming 'model' is your pose model and 'device_ids' is a list of GPU ids
model = DDP(model, device_ids=device_ids, find_unused_parameters=True)
```

Give this a try and see if it resolves the issue. If the problem persists, please provide more details about your loss function and the structure of your model's `forward` function output. 🛠️

**Comment by staeff777** [comment]
Dear @glenn-jocher,

thank you for your answer. I tried it, but I'm currently stuck at 

```
  model = DDP(model, device_ids=[0,1,2], find_unused_parameters=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 576, in __init__
    self._log_and_throw(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 759, in _log_and_throw
    raise err_type(err_msg)
ValueError: device_ids can only be None or contain a single element.
```

Multi-Device training seems to be no longer supported beginning from [pytorch 1.9 ](https://github.com/pytorch/pytorch/releases/tag/v1.9.0) . 
> Removed support for inter-process device replication in DDP 

should I revert to 1.81 or are there other possibilities?

**Comment by zyy-xy** [comment]
> Hi @staeff777,
> 
> Thanks for giving that a try and sharing the error you encountered. It looks like there's a bit of confusion regarding the `device_ids` parameter in `DistributedDataParallel`. In PyTorch 1.9 and later, you don't need to specify `device_ids` when you're using `torch.distributed.run` or `torch.distributed.launch` to spawn your training processes, as each process will only manage a single GPU.
> 
> Here's how you can modify your code:
> 
> ```python
> import torch
> from torch.nn.parallel import DistributedDataParallel as DDP
> 
> # Assuming 'model' is your pose model
> # No need to specify device_ids when using torch.distributed.run or launch
> model = DDP(model, find_unused_parameters=True)
> ```
> 
> This should work with PyTorch 1.9 and later. Each process will automatically use the appropriate GPU assigned to it. Give this a shot and let us know how it goes! 😊👍

Hi! @glenn-jocher Excuse me,
When training the model, I enabled multiple Gpus (8 devices), and using `nvidia-smi` to see the gpu status was indeed occupied by 8 devices. But the actual training speed is hardly faster than using one device, so why? In addition, with the code you offered, an error was reported at ```model = DDP(model, find_unused_parameters=True)  ``` RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by zyy-xy** [comment]
> @zyy-xy hi there! 👋 It sounds like you're making progress, but let's address the issues you're facing.
> 
> For the speed concern, training speed improvements with multiple GPUs can vary based on several factors including data loading, model complexity, and inter-GPU communication overhead. Ensuring efficient data loading and minimizing bottlenecks are key to leveraging multiple GPUs effectively.
> 
> Regarding the error you encountered, it seems the distributed process group wasn't initialized. You can initialize it by adding the following before creating the `DDP` model instance:
> 
> ```python
> import torch.distributed as dist
> 
> dist.init_process_group(backend='nccl')  # Use 'nccl' for GPUs, 'gloo' for CPUs
> ```
> 
> This should be done in the script that's being run by `torch.distributed.run` or `torch.distributed.launch`. Here's a quick example:
> 
> ```python
> import torch
> import torch.distributed as dist
> from torch.nn.parallel import DistributedDataParallel as DDP
> 
> def main():
>     dist.init_process_group(backend='nccl')
>     model = ...  # Your model setup here
>     model = DDP(model, find_unused_parameters=True)
>     # Your training loop here
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> Make sure to use `torch.distributed.run` or `torch.distributed.launch` to start your training script, which will handle spawning processes for each GPU. This setup should help with the initialization error and hopefully improve your training speed with multiple GPUs. Let us know how it goes! 😊

Hi! @glenn-jocher Thanks for your help! Now I've trained the model using multiple gpus. But I suspected that I was not doing a perfect job, which led to a low training speed. I used 8 RTX3090 to train Yolov8s-pose model. The data set was coco2017 containing more than 110,000 pictures, and the total training time was 12h. May I ask if this is the common and correct speed?

**Comment by glenn-jocher** [comment]
Hi @zyy-xy! 🎉 Great to hear you've got your model training on multiple GPUs! The training time can indeed vary based on several factors like the model size (YOLOv8s-pose in your case), dataset complexity, and your specific hardware setup. Training on COCO2017 with 8 RTX3090 GPUs for 12 hours sounds reasonable, considering the dataset's size and the complexity of pose estimation tasks. 

However, if you're looking to optimize training speed further, consider reviewing your data loading and augmentation processes to ensure they're not creating bottlenecks. Also, adjusting batch sizes and learning rates can sometimes help utilize your GPUs more efficiently. 

Keep up the great work, and feel free to reach out if you have more questions or need further assistance! 🚀

**Comment by staeff777** [comment]
Dear @glenn-jocher ,

thank you for the explainations. Im still one step behind.
Since the DPP wraps the model. I cannot just run model.train() .

Can I somwhow invoke the PoseTrainer or is a complete custom training loop neccessary?

**Comment by glenn-jocher** [comment]
@staeff777 hi there! 😊

You're right, after wrapping your model with `DistributedDataParallel` (DDP), you'll still call `model.train()` as usual to set it in training mode. DDP is designed to be transparent in this regard. Here's a quick example:

```python
model = DDP(model, find_unused_parameters=True)
model.train()  # Set the model to training mode
```

For training, you can continue using your existing training loop. DDP will take care of synchronizing gradients across the GPUs. No need for a completely custom loop or directly invoking a specific trainer unless your setup requires it.

Hope this clears things up! Let me know if you have more questions.

**Comment by staeff777** [comment]
@glenn-jocher, its not working as I excepcted.

when I try to start the tryining like that:
```python
model = DDP(ymodel, find_unused_parameters=True)
model.train(data='/input/data.yaml', project="/workspace", epochs=1000, imgsz=1280, lr0=0.007, batch=3,  optimizer='SGD', pretrained="/input/yolov8x-pose-p6.pt" )
```
I receive:

> TypeError: train() got an unexpected keyword argument 'data'

**Comment by glenn-jocher** [comment]
@staeff777 hey there! 😄

Thanks a lot for sharing your solution. It's a clever approach to integrate a switch for `find_unused_parameters` through an environment variable. This indeed looks like a useful addition for those who might encounter similar challenges with distributed training using the Ultralytics framework.

If you're up for it, a pull request would be highly appreciated! It would be great to have your solution reviewed and potentially integrated, making it available for the wider community. Your contribution could help others facing the same issue. 🚀

Let me know if you need any help with the PR process, and once again, hats off for coming up with this workaround!
