### ISSUE TITLE
WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\1.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)

### ISSUE THREAD

**Issue by Dongzi19820924** [ultralytics/ultralytics#8262]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

During the process of training my own data set, there was a problem that all pictures were damaged. After checking, all the pictures were in jpg format.
I have made sure that the label file meets yolo's standards.

`yolo pose train data=Triangle217.yaml model=yolov8n.pt pretrained=True project=Triangle217 epochs=50 imgsz=128
`

```
WARNING ⚠️ conflicting 'task=pose' passed with 'task=detect' model. Ignoring 'task=pose' and updating to 'task=detect' to match model.
New https://pypi.org/project/ultralytics/8.1.14 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.10 🚀 Python-3.10.13 torch-2.2.0 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=Triangle217.yaml, epochs=50, time=None, patience=50, batch=16, imgsz=128, save=True, save_period=-1, cache=False, device=None, workers=8, project=Triangle217, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, d
eterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=Fa
lse, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, li
ne_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, 
label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=Triangle217\tra
in4
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 225 layers, 3011043 parameters, 3011027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning D:\.engine\ultralytics-main\datasets\triangle_217\labels\train.cache... 12 images, 0 backgrounds, 12 corrupt: 100%|██████████| 12/12 [00:00<?, ?it/s]
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\1.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\10.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\11.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\12.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\2.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\3.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\4.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\5.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\6.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\7.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\8.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ D:\.engine\ultralytics-main\datasets\triangle_217\images\train\9.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
WARNING ⚠️ No images found in D:\.engine\ultralytics-main\datasets\triangle_217\labels\train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Traceback (most recent call last):
  File "C:\Users\jswd\.conda\envs\env1\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jswd\.conda\envs\env1\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jswd\.conda\envs\env1\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\cfg\__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\engine\model.py", line 601, in train
    self.trainer.train()
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\engine\trainer.py", line 208, in train
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\engine\trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\engine\trainer.py", line 286, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\models\yolo\detect\train.py", line 49, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\models\yolo\detect\train.py", line 43, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\data\build.py", line 87, in build_yolo_dataset
    return YOLODataset(
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\data\dataset.py", line 42, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\data\base.py", line 74, in __init__
    self.labels = self.get_labels()
  File "C:\Users\jswd\.conda\envs\env1\lib\site-packages\ultralytics\data\dataset.py", line 139, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Dongzi19820924 hey there! 👋 It looks like you're encountering an issue with image corruption during training. The warning indicates that the image or label file might not be formatted correctly, which is causing the problem.

Here's a quick check you can do:
- Ensure that your image files are not actually corrupt and can be opened normally.
- Verify that the label files are correctly formatted according to the YOLO standards. Each line in a label file should have five values: class index, x_center, y_center, width, and height, all normalized between 0 and 1.

If you're confident that the files are okay, try clearing the cache by deleting the `.cache` files in your dataset folder and rerunning the training command.

If the issue persists, feel free to share a sample label file or an image so we can take a closer look! 😊

Here's an example of how a label file should look for a single object:

```
0 0.5 0.5 0.25 0.25
```

This represents an object of class `0` centered in the middle of the image with a width and height that are 25% of the image's dimensions.

Hope this helps! Let's get your training back on track! 🚀

**Comment by glenn-jocher** [comment]
@Dongzi19820924 hey there! 👋 It looks like there might be an issue with the shape of your label files. The warning indicates that the expected shape of the label array isn't matching up. Could you double-check that each label file contains rows with exactly 2 values (for pose tasks) and that there are no extra or missing values?

Here's a quick example of what a label file should look like for a pose task with one keypoint (replace `x_center y_center` with your actual values):

```
x_center y_center
```

If you're confident that the label files are correct, it might be worth trying to clear the cache by deleting the `.cache` files in your dataset folder and re-running the training command.

Let me know if this helps or if you're still encountering issues! 😊

**Comment by ctubig** [comment]
I also encounter the same error.  ValueError: not enough values to unpack (expected 3, got 0). I'm using labelImg app to create labels.

**Comment by glenn-jocher** [comment]
@ctubig hey there! 😊 It seems like there might be a mismatch in the expected format of the label files. YOLOv8 expects label files with specific formats depending on the task (detection, segmentation, pose estimation, etc.). For detection, each line in a label file should contain class index and bounding box coordinates in the format: `class x_center y_center width height`.

If you're using labelImg, ensure you're saving the labels in YOLO format. You might want to open a few label files to check if they adhere to this format. If the issue persists, try clearing any `.cache` files in your dataset directory and rerun your command.

Let me know if this helps or if you need further assistance!

**Comment by VascoLopo** [comment]
I have this exact issue, but i am trying to do keypoint estimation using pose with only one point in the middle

**Comment by glenn-jocher** [comment]
@VascoLopo the error occurs because YOLO pose estimation requires specific keypoint formatting. For a single keypoint, ensure your dataset YAML includes `kpt_shape: [1, 2]` (or `[1, 3]` with visibility), and that labels follow the format:  
`<class> <x_center> <y_center> <width> <height> <keypoint_x> <keypoint_y>`.  

Also verify you're using a **pose model** (`yolov8n-pose.pt`), not detection model. The initial warning about conflicting tasks suggests you might be using a detection model.  

For full details see the [Pose Estimation Dataset Guide](https://docs.ultralytics.com/datasets/pose/).
