### ISSUE TITLE
How to use CustomTrainer with DDP?

### ISSUE THREAD

**Issue by dimka11** [ultralytics/ultralytics#8331]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I run CustomTrainer from Jupyter notebook with two device set, but get following error:

```
Traceback (most recent call last):  File "/root/.config/Ultralytics/DDP/_temp_ojxovo2s135142266514176.py", line 6, in <module>    from __main__ import CustomTrainerImportError: cannot import name 'CustomTrainer' from '__main__' (/root/.config/Ultralytics/DDP/_temp_ojxovo2s135142266514176.py)Traceback (most recent call last):  File "/root/.config/Ultralytics/DDP/_temp_ojxovo2s135142266514176.py", line 6, in <module>    from __main__ import CustomTrainerImportError: cannot import name 'CustomTrainer' from '__main__' (/root/.config/Ultralytics/DDP/_temp_ojxovo2s135142266514176.py)Traceback (most recent call last):  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main    return _run_code(code, main_globals, None,  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code    exec(code, run_globals)  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>    main()  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper    return f(*args, **kwargs)  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main    run(args)  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run    elastic_launch(  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__    return launch_agent(self._config, self._entrypoint, list(args))  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent    raise ChildFailedError(torch.distributed.elastic.multiprocessing.errors.ChildFailedError: ============================================================/root/.config/Ultralytics/DDP/_temp_ojxovo2s135142266514176.py FAILED------------------------------------------------------------Failures:[1]:  time      : 2024-02-20_04:27:47  host      : 3a2bc2e62e37  rank      : 1 (local_rank: 1)  exitcode  : 1 (pid: 404)  error_file: <N/A>  traceback : To enable traceback see: [https://pytorch.org/docs/stable/elastic/errors.html](https://www.google.com/url?q=https://pytorch.org/docs/stable/elastic/errors.html&sa=D&source=calendar&usd=2&usg=AOvVaw0X-kqIjwpvnD-BJsnP-9A6)------------------------------------------------------------Root Cause (first observed failure):[0]:  time      : 2024-02-20_04:27:47  host      : 3a2bc2e62e37  rank      : 0 (local_rank: 0)  exitcode  : 1 (pid: 403)  error_file: <N/A>  traceback : To enable traceback see: [https://pytorch.org/docs/stable/elastic/errors.html](https://www.google.com/url?q=https://pytorch.org/docs/stable/elastic/errors.html&sa=D&source=calendar&usd=2&usg=AOvVaw0X-kqIjwpvnD-BJsnP-9A6)============================================================


---------------------------------------------------------------------------CalledProcessError                        Traceback (most recent call last)Cell In[27], line 2      1 trainer = CustomTrainer(overrides={'data':'./data.yaml', 'model': Config.weights_path, 'batch':32, 'imgsz': 512, 'device': [0,1]})----> 2 trainer.train()File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:203, in BaseTrainer.train(self)    201     subprocess.run(cmd, check=True)    202 except Exception as e:--> 203     raise e    204 finally:    205     ddp_cleanup(self, str(file))File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:201, in BaseTrainer.train(self)    199 try:    200     LOGGER.info(f'{colorstr("DDP:")} debug command {" ".join(cmd)}')--> 201     subprocess.run(cmd, check=True)    202 except Exception as e:    203     raise eFile /opt/conda/lib/python3.10/subprocess.py:526, in run(input, capture_output, timeout, check, *popenargs, **kwargs)    524     retcode = process.poll()    525     if check and retcode:--> 526         raise CalledProcessError(retcode, process.args,    527                                  output=stdout, stderr=stderr)    528 return CompletedProcess(process.args, retcode, stdout, stderr)CalledProcessError: Command '['/opt/conda/bin/python3.10', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '40187', '/root/.config/Ultralytics/DDP/_temp_ojxovo2s135142266514176.py']' returned non-zero exit status 1.
```

My code:
```
class CustomTrainer(SegmentationTrainer):

trainer = CustomTrainer(overrides={'data':'./data.yaml', 'model': Config.weights_path, 'batch':1, 'imgsz': 512, 'device':[0,1]})
trainer.train()
```

**Comment by dimka11** [comment]
The same error seems like  custom_trainer.py doesn't copy to DDP directory

**Comment by glenn-jocher** [comment]
@dimka11 hey there! 😊 It looks like the `custom_trainer.py` isn't being found by the DDP processes. A quick fix could be to explicitly specify the path to `custom_trainer.py` when starting your training. Here's a small tweak you can try:

```python
import os
from ultralytics import SegmentationTrainer

# Assuming custom_trainer.py is in the current working directory
current_dir = os.getcwd()
trainer = SegmentationTrainer(overrides={
    'data':'./data.yaml', 
    'model': Config.weights_path, 
    'batch':1, 
    'imgsz': 512, 
    'device':[0,1],
    'pythonpath': current_dir  # Add this line
})
trainer.train()
```

This should help ensure that the DDP subprocesses can locate your `CustomTrainer` class. Let us know how it goes!

**Comment by dimka11** [comment]
SyntaxError: 'pythonpath' is not a valid YOLO argument.

**Comment by dimka11** [comment]
I copy code from all cells to py file and run it: !python train.py
But get error:
`cannot import name 'CustomTrainer' from '__main__'`

CustomTrainer class in the same one file with train run.

**Comment by glenn-jocher** [comment]
@dimka11 hey there! 😊 It seems like the issue might be related to how Python handles imports when running scripts directly with `__main__`. When you execute a script as the main program, the `__name__` attribute is set to `'__main__'`, which can sometimes cause import issues for classes defined in the same script.

A quick workaround is to check if `__name__ == '__main__'` at the bottom of your `train.py` and then execute the main logic of your script. Here's a simplified example:

```python
# train.py
class CustomTrainer:
    # Your CustomTrainer definition here
    pass

def main():
    # Your training logic here
    trainer = CustomTrainer()
    trainer.train()

if __name__ == '__main__':
    main()
```

This way, you encapsulate the execution logic in a `main()` function, which should help avoid the import error. Give it a try and let us know if it solves the issue!

**Comment by ykwongaq** [comment]
Dear developers,

First of all, thank you so much for creating Ultralytics. It is a useful tool!

What I am trying to do is to add some custom augmentation. Following the guideline, I have install ultralytics as python package, and implement my own Dataset. I format the code files as follows:
```
Project
|- custom
    |- augment.py
    |- dataset.py
    |- trainer.py
|- train.py
```

And here part of the implementation of `train.py`, which basically call my CustomTrainer to start training.
```
    model = CustomTrainer(
        overrides={
            "model": pretrained_weights_path,
            "data": dataset_config_path,
            "epochs": args.epochs,
            "batch": args.batch_size,
            "imgsz": imgsz,
            "save_period": args.save_period,
            "workers": args.workers,
            "device": devices,
            "verbose": args.verbose,
            "project": args.output,
            "name": args.name,
            "resume": args.resume,
            "exist_ok": args.exist_ok,
        }
    )
    model.train()
```

When I am running it, it pop up error "ModuleNotFoundError: No module named 'custom'" in a temporarily generated file located at `/home/user/.config/Ultralytics/DDP/_temp_5ywmvg4v139797175705216.py`

Here is the content of this file:
```

# Ultralytics Multi-GPU training temp file (should be automatically deleted after use)
overrides = {'task': 'detect', 'mode': 'train', 'model': './weights/yolov8x.pt', 'data': './configs/fruit_dataset.yaml', 'epochs': 400, 'time': None, 'patience': 100, 'batch': 64, 'imgsz': (360, 640), 'save': True, 'save_period': 50, 'cache': False, 'device': [0, 1, 2, 3], 'workers': 32, 'project': './outputs', 'name': 'yolov8_2024-04-10_22-21-31', 'exist_ok': False, 'pretrained': True, 'optimizer': 'auto', 'verbose': False, 'seed': 0, 'deterministic': True, 'single_cls': False, 'rect': False, 'cos_lr': False, 'close_mosaic': 10, 'resume': False, 'amp': True, 'fraction': 1.0, 'profile': False, 'freeze': None, 'multi_scale': False, 'overlap_mask': True, 'mask_ratio': 4, 'dropout': 0.0, 'val': True, 'split': 'val', 'save_json': False, 'save_hybrid': False, 'conf': None, 'iou': 0.7, 'max_det': 300, 'half': False, 'dnn': False, 'plots': True, 'source': None, 'vid_stride': 1, 'stream_buffer': False, 'visualize': False, 'augment': False, 'agnostic_nms': False, 'classes': None, 'retina_masks': False, 'embed': None, 'show': False, 'save_frames': False, 'save_txt': False, 'save_conf': False, 'save_crop': False, 'show_labels': True, 'show_conf': True, 'show_boxes': True, 'line_width': None, 'format': 'torchscript', 'keras': False, 'optimize': False, 'int8': False, 'dynamic': False, 'simplify': False, 'opset': None, 'workspace': 4, 'nms': False, 'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'pose': 12.0, 'kobj': 1.0, 'label_smoothing': 0.0, 'nbs': 64, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0, 'auto_augment': 'randaugment', 'erasing': 0.4, 'crop_fraction': 1.0, 'cfg': None, 'tracker': 'botsort.yaml', 'save_dir': 'outputs/yolov8_2024-04-10_22-21-31'}

if __name__ == "__main__":
    from custom.trainer import CustomTrainer
    from ultralytics.utils import DEFAULT_CFG_DICT

    cfg = DEFAULT_CFG_DICT.copy()
    cfg.update(save_dir='')   # handle the extra key 'save_dir'
    trainer = CustomTrainer(cfg=cfg, overrides=overrides)
    results = trainer.train()
```

Apparently, it will get module not found error in this file as the path is wrong.

May I ask how to solve this issue?

Thank you so much.

**Comment by glenn-jocher** [comment]
@ykwongaq hey there! 😊 Thank you so much for reaching out and mentioning your appreciation for Ultralytics. It's wonderful hearing that you find our tool useful!

From what you've described, it seems like the process initiated by the DDP (Distributed Data Parallel) is having trouble locating your custom module, hence the `ModuleNotFoundError`. This error typically arises due to Python's module resolution process, which depends on the Python path and the working directory.

A quick workaround to try is modifying the Python path within your script before initiating the trainer. Python automatically searches for modules in the directories listed in `sys.path`, so adding your project directory to this list should resolve the import issue.

You can do this by adding:
```python
import sys
sys.path.append('/path/to/your/project')
```
to the beginning of your `train.py` script, replacing `/path/to/your/project` with the actual path to your project directory where the `custom` package is located.

Alternatively, if your `custom` package is in the same directory as your script, you can simply add the current directory to the Python path:
```python
import sys
from pathlib import Path

# Add the current directory to sys.path
current_dir = Path(__file__).resolve().parent
sys.path.append(str(current_dir))
```

This should make Python able to find your custom modules regardless of the current working directory of the DDP processes.

Keep in mind, while this is a quick fix, structuring your project with a proper Python package setup, if not already done, is a clean long-term solution. That involves creating a setup.py and potentially using a virtual environment to manage your dependencies and paths more reliably.

Hope this helps! Let us know how it goes or if there's anything else we can assist you with. Keep up the great work! 🚀
