### ISSUE TITLE
YOLOv8 + SAHI + Object Tracking?

### ISSUE THREAD

**Issue by MuhammadBilal848** [ultralytics/ultralytics#8385]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was using YOLOV8 for object tracking using `model.track` but due to some reasons I need to switch to YOLOV8 + SAHI but the thing is I want to add object tracking to it. 

Is there anyone who wrote a script for **YOLOV8 WITH SAHI** that does **OBJECT TRACKING**?

I searched the **SAHI** module and found no code where `model(frame)` was used so that I can replace it with `mode.track()`.

Thanks for reading.

**Comment by glenn-jocher** [comment]
@MuhammadBilal848 hey there! 👋

For integrating YOLOv8 with SAHI and adding object tracking, you can modify the SAHI prediction loop to use `model.track()` instead of `model()`. Here's a simple example to get you started:

```python
from ultralytics import YOLO
from sahi.model import Yolov5DetectionModel
from sahi.predict import get_sliced_prediction

# Load your YOLOv8 model
model = YOLO('yolov8n.pt')

# Wrap the YOLOv8 model with SAHI's detection model
detection_model = Yolov5DetectionModel(
    model_path='yolov8n.pt',
    confidence_threshold=0.25,
    device='cuda',  # or 'cpu'
)

# Perform object tracking with SAHI
def get_sliced_prediction_with_tracking(image_path, detection_model):
    # Get sliced predictions
    result = get_sliced_prediction(
        image_path,
        detection_model,
        slice_height=640,
        slice_width=640,
    )
    # Extract frames from the result
    frames = [slice_result.original_image for slice_result in result.slice_predictions]
    # Run tracking on each frame
    tracked_objects = [model.track(frame, persist=True) for frame in frames]
    return tracked_objects

# Example usage
tracked_results = get_sliced_prediction_with_tracking('path/to/image.jpg', detection_model)
```

This is just a starting point, and you might need to adjust the code to fit the specifics of your application. Happy tracking! 🚀

Let me know if you need further assistance.

**Comment by MuhammadBilal848** [comment]
Thanks for the response @glenn-jocher.

The code has some problems, I tried different variations but it didn't work. The main thing is `from sahi.model import Yolov5DetectionModel` should be `from sahi.models.yolov5  import Yolov5DetectionModel`. I changed it, but it was still causing some error so I used different detection model the `from sahi import AutoDetectionModel`. 

But I am still facing errors:

### CODE:
```
from ultralytics import YOLO
from sahi.models.yolov5_custom import CustomYolov5DetectionModel as Yolov5DetectionModel
from sahi.predict import get_sliced_prediction
from sahi import AutoDetectionModel
import cv2

# Load your YOLOv8 model
model = YOLO('models/yolov8m.pt')

# Wrap the YOLOv8 model with SAHI's detection model
detection_model = AutoDetectionModel.from_pretrained(model_type='yolov8',
                                                    model_path='models/yolov8m.pt',
                                                    confidence_threshold=0.3,
                                                    device='cuda:0',
                                                    image_size=1080)

# Perform object tracking with SAHI
def get_sliced_prediction_with_tracking(image_path, detection_model):
    # Get sliced predictions
    result = get_sliced_prediction(
        image_path,
        detection_model,
        slice_height=640,
        slice_width=640,
    )
    # Extract frames from the result
    frames = [slice_result.original_image for slice_result in result.slice_predictions]
    # Run tracking on each frame
    tracked_objects = [model.track(frame, persist=True) for frame in frames]
    return tracked_objects

# Example usage
tracked_results = get_sliced_prediction_with_tracking('obj.jpg', detection_model)
cv2.imshow('Live Inference - Person Class Only', tracked_results)
```

### ERRORS:

```
PS F:\Sahi> python .\testwithtracking.py
Performing prediction on 70 number of slices.
Traceback (most recent call last):
  File "F:\Sahi\testwithtracking.py", line 101, in <module>
    tracked_results = get_sliced_prediction_with_tracking('obj.jpg', detection_model)
  File "F:\Sahi\testwithtracking.py", line 95, in get_sliced_prediction_with_tracking
    frames = [slice_result.original_image for slice_result in result.slice_predictions]
AttributeError: 'PredictionResult' object has no attribute 'slice_predictions'
```

The get_sliced_prediction object is returning `return PredictionResult(
        image=image, object_prediction_list=object_prediction_list, durations_in_seconds=durations_in_seconds
    )`.  I don't get it how can we use result.slice_predictions?

**Comment by glenn-jocher** [comment]
Hey @MuhammadBilal848, thanks for reaching out and for the update on the import statement! 🛠️

Regarding the error you're encountering, it seems like there's a slight mix-up with accessing the results from `get_sliced_prediction`. The `PredictionResult` object doesn't have a `slice_predictions` attribute. Instead, you should access the `object_prediction_list` which contains the predictions.

Here's a quick fix to your code:

```python
# ... [rest of your imports and model loading code]

# Perform object tracking with SAHI
def get_sliced_prediction_with_tracking(image_path, detection_model):
    # Get sliced predictions
    result = get_sliced_prediction(
        image_path,
        detection_model,
        slice_height=640,
        slice_width=640,
    )
    # Extract frames from the result
    frames = [prediction.original_image for prediction in result.object_prediction_list]
    # Run tracking on each frame
    tracked_objects = [model.track(frame, persist=True) for frame in frames]
    return tracked_objects

# Example usage
tracked_results = get_sliced_prediction_with_tracking('obj.jpg', detection_model)
```

Give this a try and let me know if it helps! If you're still facing issues, feel free to share more details and we'll work through it together. Happy coding! 🚀

**Comment by MuhammadBilal848** [comment]
Getting this error:
`frames = [prediction.original_image for prediction in result.object_prediction_list]`
`AttributeError: 'ObjectPrediction' object has no attribute 'original_image`

For good understanding:
I made a small change, since there is no attribute "original_image",
`frames = [prediction for prediction in result.object_prediction_list]`
`print('frames:', frames)`
and got this:

```frames: [ObjectPrediction<
    bbox: BoundingBox: <(702.2566528320312, 274.1356506347656, 1023.7633056640625, 458.80792236328125), w: 321.50665283203125, h: 184.67227172851562>,
    mask: None,
    score: PredictionScore: <value: 0.838400661945343>,
    category: Category: <id: 0, name: person>>, ObjectPrediction<
    bbox: BoundingBox: <(527.0429229736328, 399.7101135253906, 799.7600708007812, 682.7406005859375), w: 272.71714782714844, h: 283.0304870605469>,
    mask: None,
    score: PredictionScore: <value: 0.791115939617157>,
    category: Category: <id: 0, name: person>>, ObjectPrediction<
    bbox: BoundingBox: <(602.7752685546875, 401.5458068847656, 800.3817749023438, 520.9331665039062), w: 197.60650634765625, h: 119.38735961914062>,
    mask: None,
    score: PredictionScore: <value: 0.923229455947876>,
    category: Category: <id: 41, name: cup>>, ObjectPrediction<
    bbox: BoundingBox: <(111.37603759765625, 0.0, 415.818115234375, 259.27972412109375), w: 304.44207763671875, h: 259.27972412109375>,     
    mask: None,
    score: PredictionScore: <value: 0.9057115316390991>,
    category: Category: <id: 58, name: potted plant>>, ObjectPrediction<
    bbox: BoundingBox: <(1.10076904296875, 7.8350830078125, 1024.0, 680.2841796875), w: 1022.8992309570312, h: 672.4490966796875>,
    mask: None,
    score: PredictionScore: <value: 0.6844806671142578>,
    category: Category: <id: 60, name: dining table>>, ObjectPrediction<
    bbox: BoundingBox: <(335.67626953125, 30.638525009155273, 886.4178466796875, 491.04803466796875), w: 550.7415771484375, h: 460.4095096588135>,
    mask: None,
    score: PredictionScore: <value: 0.9425691366195679>,
    category: Category: <id: 63, name: laptop>>, ObjectPrediction<
    bbox: BoundingBox: <(0.42681884765625, 297.965087890625, 387.2826232910156, 602.4921264648438), w: 386.8558044433594, h: 304.52703857421875>,
    mask: None,
    score: PredictionScore: <value: 0.8417186737060547>,
    category: Category: <id: 63, name: laptop>>, ObjectPrediction<
    bbox: BoundingBox: <(798.4950561523438, 198.046142578125, 1023.7487182617188, 358.69256591796875), w: 225.253662109375, h: 160.64642333984375>,
    mask: None,
    score: PredictionScore: <value: 0.45816341042518616>,
    category: Category: <id: 63, name: laptop>>, ObjectPrediction<
    bbox: BoundingBox: <(703.16504, 312.81244, 802.4754, 342.27222), w: 99.31036376953125, h: 29.45977783203125>,
    mask: None,
    score: PredictionScore: <value: 0.3716769814491272>,
    category: Category: <id: 64, name: mouse>>, ObjectPrediction<
    bbox: BoundingBox: <(797.7003479003906, 199.41433715820312, 1023.6607666015625, 356.4065856933594), w: 225.96041870117188, h: 156.99224853515625>,
    mask: None,
    score: PredictionScore: <value: 0.5712894797325134>,
    category: Category: <id: 67, name: cell phone>>, ObjectPrediction<
    bbox: BoundingBox: <(0.634570300579071, 309.152099609375, 386.5782165527344, 601.9556884765625), w: 385.9436462521553, h: 292.8035888671875>,
    mask: None,
    score: PredictionScore: <value: 0.617576539516449>,
    category: Category: <id: 73, name: book>>, ObjectPrediction<
    bbox: BoundingBox: <(197.16757202148438, 111.80133056640625, 342.64044189453125, 257.44891357421875), w: 145.47286987304688, h: 145.6475830078125>,
    mask: None,
    score: PredictionScore: <value: 0.5404821038246155>,
    category: Category: <id: 75, name: vase>>]```

**Comment by glenn-jocher** [comment]
@MuhammadBilal848 hey there! It looks like you're on the right track with your adjustments. The `ObjectPrediction` objects you're seeing are the predictions for each slice of the image. To perform tracking, you'll need to extract the image associated with each prediction.

Since SAHI doesn't provide the original image directly in the `ObjectPrediction`, you'll need to use the image you passed to `get_sliced_prediction` for tracking. Here's a modified snippet that should work for you:

```python
from ultralytics import YOLO
from sahi import AutoDetectionModel
from sahi.predict import get_sliced_prediction
import cv2

# Load your YOLOv8 model
model = YOLO('models/yolov8m.pt')

# Wrap the YOLOv8 model with SAHI's detection model
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path='models/yolov8m.pt',
    confidence_threshold=0.3,
    device='cuda:0',
    image_size=1080
)

# Perform object tracking with SAHI
def get_sliced_prediction_with_tracking(image_path, detection_model):
    # Read the original image
    original_image = cv2.imread(image_path)
    
    # Get sliced predictions
    result = get_sliced_prediction(
        image=original_image,
        detection_model=detection_model,
        slice_height=640,
        slice_width=640,
    )
    
    # Run tracking on the original image
    tracked_objects = model.track(original_image, persist=True)
    return tracked_objects

# Example usage
tracked_results = get_sliced_prediction_with_tracking('obj.jpg', detection_model)
cv2.imshow('Live Inference - Person Class Only', tracked_results[0].render())
cv2.waitKey(0)
cv2.destroyAllWindows()
```

This code assumes that you're tracking objects on the entire image. If you need to track objects within each slice, you'll need to modify the `get_sliced_prediction_with_tracking` function to handle each slice individually.

Give this a go and let me know if it helps! If you run into any more issues, feel free to reach out. Happy coding! 🚀

**Comment by MuhammadBilal848** [comment]
Thanks for all the effort @glenn-jocher. 

The code seems to work with a few changes:

```import cv2
from ultralytics import YOLO
from sahi import AutoDetectionModel
from sahi.predict import get_sliced_prediction

# Load your YOLOv8 model
yolo_model = YOLO('models/yolov8n.pt')

# Wrap the YOLOv8 model with SAHI's detection model
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path='models/yolov8n.pt',
    confidence_threshold=0.3,
    device='cuda:0',
    image_size=1080
)

# Perform object tracking with SAHI
def get_sliced_prediction_with_tracking(image_path, detection_model):
    # Read the original image
    original_image = cv2.imread(image_path)

    if original_image is None:
        raise ValueError(f"Unable to read the image at path: {image_path}")

    # Get sliced predictions
    result = get_sliced_prediction(
        image=original_image,
        detection_model=detection_model,
        slice_height=200,
        slice_width=200,
    )

    # Run tracking on the original image
    tracked_objects = yolo_model.track(original_image, verbose=False, classes=0,conf=0.5,persist=True)[0]
    # print('tracked_objects:', tracked_objects[0].boxes.xyxy)
    # Draw bounding boxes on the original image
    for box in tracked_objects.boxes.xyxy:
        box = box.cpu().numpy().astype(int)
        cv2.rectangle(original_image, (box[0], box[1]), (box[2], box[3]), (0, 255, 0), 2)

    # Save the modified image
    output_path = 'output_3.jpg'
    cv2.imwrite(output_path, original_image)

    return tracked_objects, output_path

# Example usage
try:
    tracked_results, output_image_path = get_sliced_prediction_with_tracking('3.jpg', detection_model)
    if tracked_results:
        print(f"Bounding boxes drawn on the image. Saved at: {output_image_path}")
    else:
        print("No tracked results.")
except Exception as e:
    print(f"An error occurred: {e}")
```

But the code seems kinda useless in terms of that we are using the major function `get_sliced_prediction` and not utilizing the returned contents. On the other hand, we are also passing the **original_image** to `model.track` which does inference on the image on its own and does not even involve SAHI's returned contents.

**Comment by glenn-jocher** [comment]
Hey @MuhammadBilal848, glad to hear you've made progress with the code! 🎉

You're absolutely right about the current usage of `get_sliced_prediction` and `model.track`. The example provided does indeed perform tracking on the whole image directly with YOLOv8, bypassing the sliced predictions from SAHI. This approach might not fully leverage the power of SAHI, especially if you're looking to apply tracking on the sliced predictions specifically.

A more integrated approach would involve using the sliced predictions to guide the tracking process, potentially allowing for more granular control over tracking in different regions of the image. However, this would require a custom integration, as `model.track()` is designed to work on full images.

For now, the example serves as a basic integration between YOLOv8 and SAHI, demonstrating how both can be set up together. For deeper integration, further customization would be needed, depending on the specific requirements of your project.

If you're looking into more sophisticated use cases, like tracking objects specifically within slices, you might consider manually iterating over the slices and applying tracking to each slice. This approach would indeed require a bit more work to manage the slices and their corresponding predictions.

Thanks for pointing this out, and keep up the great work! If you have more questions or need further assistance, feel free to ask. Happy coding! 🚀
