### ISSUE TITLE
errors on detect predict CLI for custom dataset

### ISSUE THREAD

**Issue by GR899** [ultralytics/ultralytics#8483]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Please note complete directory paths have been redacted for privacy/security. Note: running from the directory that contains reference image -- image is in the directory.

```
yolo detect predict model=../workspace/runs/detect/train6/weights/best.pt source=‘CB24-56.jpg’
Ultralytics YOLOv8.1.18 🚀 Python-3.12.1 torch-2.2.0 CPU (Apple M1)
Model summary (fused): 168 layers, 3011303 parameters, 0 gradients, 8.1 GFLOPs

Traceback (most recent call last):
  File "/Users/CT/miniforge3/envs/apple-yoloSS/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/engine/model.py", line 429, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 213, in predict_cli
    for _ in gen:  # noqa, running CLI inference without accumulating any outputs (do not modify)
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 254, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 228, in setup_source
    self.dataset = load_inference_source(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/data/build.py", line 180, in load_inference_source
    dataset = LoadImages(source, vid_stride=vid_stride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/CT/miniforge3/envs/apple-yoloSS/lib/python3.12/site-packages/ultralytics/data/loaders.py", line 290, in __init__
    raise FileNotFoundError(f"{p} does not exist")
FileNotFoundError: ‘CB24-56.jpg’ does not exist
(apple-yoloSS) CT@betty 4tests % 
```

### Environment

```
yolo checks
Ultralytics YOLOv8.1.18 🚀 Python-3.12.1 torch-2.2.0 CPU (Apple M1)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 375.1/460.4 GB disk)

OS                  macOS-14.3.1-arm64-arm-64bit
Environment         Darwin
Python              3.12.1
Install             pip
RAM                 16.00 GB
CPU                 Apple M1
CUDA                None

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.9.0>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
(apple-yoloSS) CT@betty 4tests % 
```

### Minimal Reproducible Example

`yolo detect predict model=../workspace/runs/detect/train6/weights/best.pt source=‘CB24-56.jpg’`

### Additional

Running the command from the directory that contains the referenced image. Have tried the using full directory paths with same errors. 

Have also tried using CLI with task= preceding detect and model= preceding predict with same results.

Appreciate any help, thanks.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by GR899** [comment]
bump... have tired doing both pip and conda upgrades to no avail.... any help would be greatly appreciate. Many thanks.

**Comment by GR899** [comment]
UPDATE -- I have solved this. For the benefit of others I ensured both pip and conda versions were up to date and then correct my CLI command.

**Comment by glenn-jocher** [comment]
@GR899 great to hear you've solved the issue, and thank you for sharing your solution with the community! 🎉 It's always helpful to have examples like yours for others who might encounter similar challenges. If you have any more questions or need further assistance in the future, feel free to reach out. Happy detecting with YOLOv8! 🚀
