### ISSUE TITLE
using augment for prediction in segmentation mode

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#859]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When running inference for a segmentation model, all is fine; However, if I change the `augment` to True, then I get the following error (I also debugged the code and noticed the tuple returned from the `self.model(im, augment=self.args.augment, visualize=visualize)` is empty in second index that results in the followign error when running the postprocessing):

Ultralytics YOLOv8.0.28 🚀 Python-3.10.9 torch-1.13.1 CPU
YOLOv8x-seg summary (fused): 295 layers, 71721619 parameters, 0 gradients, 343.7 GFLOPs
Traceback (most recent call last):
  File "/Users/Documents/data/yolo/prediction_production.py", line 17, in <module>
    results = model(image1, imgsz=1152, conf=0.25, iou=.35, half=False, retina_masks=True, agnostic_nms=True, verbose=False, save=True, augment=True)
  File "/Users/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 67, in __call__
    return self.predict(source, stream, **kwargs)
  File "/Users/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 148, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/Users/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 114, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/Users/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 169, in stream_inference
    self.results = self.postprocess(preds, im, im0s, self.classes)
  File "/Users/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/predict.py", line 25, in postprocess
    proto = preds[1][-1]
TypeError: 'NoneType' object is not subscriptable
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

### Environment

Ultralytics YOLOv8.0.28 🚀 Python-3.10.9 torch-1.13.1 CPU

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@mehran66 Thanks for the reporting! I think we have not supported `augment` for segmentation yet. We'll try to implement it or at least raise a warning says "augment for segmentation has not supported yet".
