### ISSUE TITLE
Issue resuming YOLOv8 obb training

### ISSUE THREAD

**Issue by rolurq** [ultralytics/ultralytics#8590]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I'm training yolov8 obb but having an issue resuming the training. This is the command I'm trying to execute and the output I'm getting:
```
yolo obb train device=cuda resume=~/myyoloobb/train/weights/last.pt
```
```
Ultralytics YOLOv8.1.20 🚀 Python-3.10.12 torch-2.1.0+cu121 
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 625, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/obb/train.py", line 29, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 100, in __init__
    self.device = select_device(self.args.device, self.args.batch)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/torch_utils.py", line 126, in select_device
    raise ValueError(
ValueError: Invalid CUDA 'device=6' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.
```
However I can ensure `torch.cuda.is_available()` returns `True` and `torch.cuda.device_count()` is 1.

### Environment

```
Ultralytics YOLOv8.1.20 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 26.3/201.2 GB disk)

OS                  Linux-6.1.58+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 50.99 GB
CPU                 Intel Xeon 2.20GHz
CUDA                12.1

matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.0+cu121>=1.8.0
torchvision         ✅ 0.16.0+cu121>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
```

### Additional

I'm running this on google colab. Initially I tried with V100 GPU environment and then tried other GPU envs but there was no difference, I'm getting the same error.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rolurq** [comment]
My bad I didn't notice my training command was incorrect! This was the correct one:
```
yolo obb train resume model=~/myyoloobb/train/weights/last.pt
```

**Comment by glenn-jocher** [comment]
@rolurq no worries at all! It happens to the best of us. 😊 I'm glad you figured it out. If you encounter any more issues or have further questions, feel free to reach out. Happy training with YOLOv8! 🚀
