### ISSUE TITLE
manual registry wtih mlflow UI

### ISSUE THREAD

**Issue by jpointchoi** [ultralytics/ultralytics#8594]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

manual registy of model with mlflow web UI can be critical function in the begining   of ML experiments
Saw that this funcion is enbaled with onnx model format, but it seems not the case

### Use case

![image](https://github.com/ultralytics/ultralytics/assets/140245500/0c12d84c-eb8f-4f2c-a191-ee809bfde405)

with code
```from ultralytics import YOLO, settings
import mlflow

from ultralytics import settings
# Update a setting. tricky but to avoid id inquiry with mlflow errata
settings.update({'mlflow': False})
mlflow.end_run()

# Make sure MLflow is enabled in settings
#settings.update({'mlflow': True})
mlflow.set_tracking_uri("http://127.0.0.1:5000")
project_name ='mlflow_integration'
experiment_name ='mlflow_registry'
mlflow.set_experiment(experiment_name)
#yolo train project=my_project name=my_experiment

#mlflow.autolog()
import os
def on_train_end(trainer):
#    if mlflow:
    print('in the on_train_end callbacks')
    print('trainers with trainers.metrics:' + str(trainer.best))
    print('trainers with trainers.metrics:' + str(trainer.last))
    print('trainers with trainers.metrics:' + str(trainer.testset))
    print('trainers with trainers.metrics:' + str(trainer.trainset))
    print("path to the best.pt: "+str(trainer.best))

    mlflow.log_artifact(str(trainer.best), "model")
    mlflow.log_artifact("mlflow_integration/mlflow_registry11/weights/best.onnx", "model")


#    mlflow.save_model. models
# Register the model in MLflow Model Registry
#    mlflow.register_model( str(trainer.best),     "my_registered_model"   )
# Register the model in MLflow Model Registry
#     mlflow.register_model(
#          "runs:/"+os.path.dirname(str(trainer.best)),
#          "my_registered_model"
#      )



#    mlflow.pytorch.log_model(str(trainer.best), "model_log")
      # End the MLflow run

    # Register the model in MLflow Model Registry
    # mlflow.register_model(
    #      "runs:/train/mlflow_simple_new/model",
    #      "my_registered_model"
    #  )



def on_train_start(trainer):
#    if mlflow:
#    print('in the on_train_start callbacks trainer'+trainer)
    print('trainers with trainers.metrics:'+ str(trainer.best))
    print('trainers with trainers.metrics:'+ str(trainer.last))
    print('trainers with trainers.metrics:'+ str(trainer.testset))
    print('trainers with trainers.metrics:'+ str(trainer.trainset))

import re
def on_fit_epoch_end(trainers):
# Log metrics at the end of each epoch

#     metrics = {
# #        'train/box_loss': trainers.metrics.items(0),
#         'train/obj_loss': trainers.metrics['obj_loss'],
# #        'train/cls_loss': trainers.metrics['cls_loss'],
#             # Add other metrics you want to track
#     }
    metrics_dict = {f"{re.sub('[()]', '', k)}": float(v) for k, v in trainers.metrics.items()}
    print('trainers.metrics with metrics_dict:'+ str(metrics_dict))
    mlflow.log_metrics(metrics=metrics_dict, step=trainers.epoch)
#    mlflow.log_metrics(trainers.metrics.items, step=trainers.epoch)

# def on_fit_epoch_end(self, model, last, epoch, results):
# # Log metrics at the end of each epoch
#     metrics = {
#         'train/box_loss': results.metrics['box_loss'],
#         'train/obj_loss': results.metrics['obj_loss'],
#         'train/cls_loss': results.metrics['cls_loss'],
#             # Add other metrics you want to track
#     }
#     mlflow.log_metrics(metrics, step=epoch)

# def on_fit_epoch_end(trainer):
# #    if mlflow:
#     print('in the on_fit_epoc_end')
#     metrics_dict = {f"{re.sub('[()]', '', k)}": float(v) for k, v in trainer.metrics.items()}
#     mlflow.log_metrics(metrics=metrics_dict, step=trainer.epoch)

# Start an MLflow run
with mlflow.start_run(run_name=experiment_name):
    # Your training code here
    model = YOLO('yolov8n.pt')
    model.add_callback("on_train_start",on_train_start)
    model.add_callback("on_fit_epoch_end",on_fit_epoch_end)
    model.add_callback("on_train_end", on_train_end)
#    results = model.train(data='coco8.yaml', epochs=1, imgsz=640)
    results = model.train(data='coco8.yaml', project=project_name, name=experiment_name, epochs=1, imgsz=640)
#    model.train.project('mlflow_integration')

# Log metrics, parameters, or artifacts as needed
#    mlflow.log_param("epochs", 100)
#    mlflow.log_metrics({"mAP": results.metrics.map})  # Example metric

    # Don't forget to log your model at the end of training
#    mlflow.pytorch.log_model(model, "model")
      # End the MLflow run
    # # Convert to ONNX first
    #model.export(format='onnx', path='model.onnx')
    #
    # # Then log the ONNX model to MLflow
    # mlflow.log_artifact('model.onnx', artifact_path="models")

#     #  Convert to ONNX first
#     onnx=model.export(format='onnx')
#     # Then log the ONNX model to MLflow
#     mlflow.log_artifact('./model.onnx', artifact_path="models")
#     mlflow.log_artifact('mlflow_integration\mlflow_registry\weights\\best.onnx')
# #     # Register the model in MLflow Model Registry
#     mlflow.register_model(
#          "mlflow_integration\mlflow_registry\weights\\best.onnx",
#          "my_registered_model"
#      )

    mlflow.end_run()





```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jpointchoi hey there! 👋 It looks like you're exploring manual model registration with MLflow's UI, specifically for ONNX models. If you're encountering issues with this process, here's a quick tip that might help:

Ensure your model is correctly exported to ONNX format before attempting to register it with MLflow. Here's a simplified example of how you can export a YOLOv8 model to ONNX and then log it to MLflow:

```python
from ultralytics import YOLO
import mlflow

# Load your model
model = YOLO('yolov8n.pt')

# Export to ONNX
model.export(format='onnx', path='model.onnx')

# Assuming you've set up MLflow as shown in your code
mlflow.log_artifact('model.onnx', artifact_path="models")

# Register the model in MLflow Model Registry
mlflow.register_model("models/model.onnx", "my_registered_model")
```

Make sure your MLflow tracking URI and experiment settings are correctly configured as you've done. This streamlined approach should help with registering your ONNX model in MLflow. If you're still facing issues, could you provide more details about the error or behavior you're encountering? Happy to help further! 😊

**Comment by jpointchoi** [comment]
Hi glennn, thanks for your heads up on this,
But I am getting consistently onnx version error as below.
can you advise how can i work around on this?

```
/home/qisenskaist/anaconda3/envs/p38_ultra_mlflow/bin/python /home/qisenskaist/Downloads/yolov8/onnx_test.py 
Ultralytics YOLOv8.1.20 🚀 Python-3.8.18 torch-2.2.1+cu121 CPU (Intel Xeon 2.00GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
ONNX: export failure ❌ 0.0s: module 'onnx' has no attribute '__version__'
Traceback (most recent call last):
  File "/home/qisenskaist/Downloads/yolov8/onnx_test.py", line 12, in <module>
    onnxmodel = model.export(format='onnx')
  File "/home/qisenskaist/anaconda3/envs/p38_ultra_mlflow/lib/python3.8/site-packages/ultralytics/engine/model.py", line 577, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/qisenskaist/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/qisenskaist/anaconda3/envs/p38_ultra_mlflow/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 278, in __call__
    f[2], _ = self.export_onnx()
  File "/home/qisenskaist/anaconda3/envs/p38_ultra_mlflow/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    raise e
  File "/home/qisenskaist/anaconda3/envs/p38_ultra_mlflow/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 132, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/qisenskaist/anaconda3/envs/p38_ultra_mlflow/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 353, in export_onnx
    LOGGER.info(f"\n{prefix} starting export with onnx {onnx.__version__} opset {opset_version}...")
AttributeError: module 'onnx' has no attribute '__version__'

Process finished with exit code 1

```

**Comment by jpointchoi** [comment]
By installing with conda, the onnx issue seems to be addressed

**Comment by glenn-jocher** [comment]
@jpointchoi hey there! 😊 Glad to hear that installing ONNX with conda resolved the issue for you. Conda can sometimes manage dependencies more smoothly than pip, especially for complex packages like ONNX that have specific requirements. If you encounter any more questions or run into other challenges, feel free to reach out. Happy coding! 🚀
