### ISSUE TITLE
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...

### ISSUE THREAD

**Issue by Abhijeet241093** [ultralytics/ultralytics#8670]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

**Describe the bug**
While custom training using command :
yolo detect train model=yolov8n.pt data=/home/tricubics/Desktop/Automatic_Self_Checkout/automated_self_checkout/self_checkout_ultralytics/data.yaml epochs=100 imgsz=640 project=self_checkout_project device='0,1'

Getting Message 
Transferred 319/355 items from pretrained weights
DDP: debug command /usr/bin/python3 -m torch.distributed.run --nproc_per_node 2 --master_port 48483 /home/tricubics/.config/Ultralytics/DDP/_temp_99pl7w9c139968793272672.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.1.23 🚀 Python-3.8.10 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 10001MiB)
                                                           CUDA:1 (NVIDIA GeForce RTX 3080, 10009MiB)
[W Utils.hpp:164] Warning: Environment variable NCCL_BLOCKING_WAIT is deprecated; use TORCH_NCCL_BLOCKING_WAIT instead (function getCvarBool)
[W Utils.hpp:164] Warning: Environment variable NCCL_BLOCKING_WAIT is deprecated; use TORCH_NCCL_BLOCKING_WAIT instead (function getCvarBool)
TensorBoard: Start with 'tensorboard --logdir self_checkout_project/train12', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=6
Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
**AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...**
Unable to open : http://localhost:6006/

 **Expected behavior**

Program Must run 

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/80f602d9-be07-4f6f-9736-1933c375a98c)

 **Installation instructions (Please mark the checkbox)**
[ Yes  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

### Environment

Ultralytics YOLOv8.1.23 🚀 Python-3.8.10 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 10001MiB)
Setup complete ✅ (16 CPUs, 94.1 GB RAM, 278.9/365.6 GB disk)

OS                  Linux-5.15.0-76-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 94.15 GB
CPU                 11th Gen Intel Core(TM) i9-11900 2.50GHz
CUDA                12.1

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Abhijeet241093 hello! Thanks for reaching out and providing detailed information about the issue you're encountering with Automatic Mixed Precision (AMP) checks and TensorBoard. 🚀

The message "AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n..." is a standard output indicating that YOLOv8 is attempting to utilize AMP for more efficient training on your GPUs. This message itself is not indicative of an error.

Regarding the TensorBoard issue "Unable to open: http://localhost:6006/", it seems like TensorBoard might not have started properly, or there could be a network issue preventing access to the TensorBoard server. You can try the following steps to troubleshoot:

1. Ensure TensorBoard is installed and up-to-date:
   ```bash
   pip install tensorboard --upgrade
   ```
2. Manually start TensorBoard pointing to your log directory:
   ```bash
   tensorboard --logdir self_checkout_project/train12
   ```
3. If you're running this on a remote server, ensure you have set up port forwarding if accessing TensorBoard from your local machine.

If the issue persists, please check your firewall settings or consider using a different port by specifying the `--port` flag in the TensorBoard command.

Let us know if this helps or if you have any further questions. Happy training!

**Comment by Abhijeet241093** [comment]
Same error is coming : after following step 1 and step 2 : Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "/home/tricubics/anaconda3/envs/env_name/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/model.py", line 654, in train
    self.trainer.train()
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 266, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 651, in check_amp
    assert amp_allclose(YOLO("yolov8n.pt"), im)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/utils/checks.py", line 640, in amp_allclose
    b = m(im, device=device, verbose=False)[0].boxes.data  # AMP inference
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/model.py", line 169, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/model.py", line 439, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 206, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 285, in stream_inference
    preds = self.inference(im, *args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 142, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize, embed=self.args.embed, *args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 384, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 128, in _predict_once
    x = m(x)  # run
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/nn/modules/head.py", line 46, in forward
    x[i] = torch.cat((self.cv2[i](x[i]), self.cv3[i](x[i])), 1)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/ultralytics/nn/modules/conv.py", line 54, in forward_fuse
    return self.act(self.conv(x))
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/tricubics/anaconda3/envs/env_name/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Invalid argument

**Comment by Abhijeet241093** [comment]
Model is running from a long time : but saying same AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n..."

![image](https://github.com/ultralytics/ultralytics/assets/38974232/26a0c162-d67b-4e40-bf0a-975de9311334)

**Comment by glenn-jocher** [comment]
@Abhijeet241093 hey there! 👋 It looks like your model is diligently working through the AMP checks. This step is crucial for optimizing training efficiency, especially on GPUs. If it seems to be taking longer than expected, it might be due to the complexity of your dataset or the model configuration.

A quick tip: Ensure your environment is set up correctly and that you're using the latest version of PyTorch and CUDA compatible with your system. Sometimes, updating these can resolve unexpected delays.

If the issue persists, could you share a bit more about your setup, such as the dataset size and specific model configurations? This info might help us pinpoint the cause. Happy training! 🚀

**Comment by Abhijeet241093** [comment]
Dataset Size : 408 Images

Model Configuration : Yolov8

**Comment by glenn-jocher** [comment]
Hey @Abhijeet241093! Thanks for sharing more details. 🌟 With a dataset of 408 images, the AMP checks should typically not take too long. Given your model configuration is YOLOv8, ensure you're running on a compatible PyTorch and CUDA version. Sometimes, a mismatch can slow things down.

If everything's up-to-date, try reducing the `imgsz` for a quicker check, like so:

```bash
yolo detect train model=yolov8n.pt data=data.yaml epochs=100 imgsz=320 device='0,1'
```

This might speed up the process. Keep us posted on how it goes! Happy to help further if needed.
