### ISSUE TITLE
How to overide model.train parameters with wandb config configuration?

### ISSUE THREAD

**Issue by jpointchoi** [ultralytics/ultralytics#8696]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Am trying to enable training parameter overides with wandb config. But couldn't find a reference for this. 
Thanks in advance for any help ion this

my trials failed:
```
from ultralytics import YOLO
#from wandb.integration.yolov8 import add_callbacks as add_wandb_callbacks
import wandb
config = {
    "project" : "hd-yolov8-hbb",
    "num_of_classes" : 16,
    "epocs" : 20
}

# ARGS = {
#     "data"  : "../wildlife_dataset.yaml",
#     "epocs" : 30
# }

run = wandb.init(project = config["project"], config = config)
run.log_code(name="train",
             include_fn=lambda path: path.endswith(".py") or path.endswith(".txt"))

#model = YOLO("yolov8m.yaml")
model = YOLO("yolov8n.yaml")
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

#add_wandb_callbacks(model, project = "hd-obb-yolov8")

#results = model.MODE(ARGS)
#results = model.train(data = "../wildlife_dataset.yaml",epochs = 2, device = 0, save_period = 10)
#results = model.train(data = "wildlife_dataset.yaml", epochs = 100)
results = model.train(config)
#results = model.train(data = "wildlife_dataset.yaml",epochs = 30)

#results = model.train(data='coco128.yaml', epochs=2)  # train the model
```

```
/home/qisenskaist/anaconda3/envs/yolov8/bin/python /home/qisenskaist/Downloads/Custom_YOLOv8_Object_Track/4_Custom_Train_YOLOv8/train_yolov8m.py 
wandb: Currently logged in as: qisenskaist. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.3
wandb: Run data is saved locally in /home/qisenskaist/Downloads/Custom_YOLOv8_Object_Track/4_Custom_Train_YOLOv8/wandb/run-20240305_220404-dxblhk4a
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run eager-hill-4
wandb: ⭐️ View project at https://wandb.ai/qisenskaist/hd-yolov8-hbb
wandb: 🚀 View run at https://wandb.ai/qisenskaist/hd-yolov8-hbb/runs/dxblhk4a
Traceback (most recent call last):
  File "/home/qisenskaist/Downloads/Custom_YOLOv8_Object_Track/4_Custom_Train_YOLOv8/train_yolov8m.py", line 28, in <module>
    results = model.train(config)
  File "/home/qisenskaist/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 635, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
TypeError: 'dict' object is not callable
New https://pypi.org/project/ultralytics/8.1.24 available 😃 Update with 'pip install -U ultralytics'
wandb: 🚀 View run eager-hill-4 at: https://wandb.ai/qisenskaist/hd-yolov8-hbb/runs/dxblhk4a
wandb: ️⚡ View job at https://wandb.ai/qisenskaist/hd-yolov8-hbb/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjE0NTc3OTY1OQ==/version_details/v2
wandb: Synced 6 W&B file(s), 0 media file(s), 3 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240305_220404-dxblhk4a/logs

Process finished with exit code 1
```

**Comment by glenn-jocher** [comment]
@jpointchoi hey there! 👋 It looks like you're trying to integrate Weights & Biases (wandb) configuration directly into the YOLOv8 training process. To achieve this, you'll need to extract the configuration from `wandb` and pass it as arguments to the `model.train()` method. Here's a simplified way to do it:

```python
from ultralytics import YOLO
import wandb

# Initialize wandb
config = {
    "project": "hd-yolov8-hbb",
    "num_of_classes": 16,
    "epochs": 20  # Note: Corrected typo from 'epocs' to 'epochs'
}
run = wandb.init(project=config["project"], config=config)

# Load the model
model = YOLO('yolov8n.pt')  # It's good to load the model once

# Extract wandb config
wandb_config = run.config

# Pass wandb config parameters to model.train()
results = model.train(data='your_dataset.yaml', epochs=wandb_config.epochs)
```

Make sure to replace `'your_dataset.yaml'` with the actual path to your dataset configuration file. This approach extracts the configuration parameters set in `wandb` and passes them to the `model.train()` method, allowing you to dynamically adjust training parameters through the wandb dashboard.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by jpointchoi** [comment]
hey Glenn
this iss quite pointed guide. we are able to move forward
thanks!

**Comment by Petros626** [comment]
@glenn-jocher Hello, 
I would like to use `wandb` for hyperparameter tuning, of some model params like `lr0`, `batch` and many more. I got my default training script without any chance to try hyperparametertuning.

```python
from ultralytics import YOLO
import torch
import wandb

# Check for GPU use
print('Use GPU:', torch.cuda.is_available())
print('\n')

# Build a new model from scratch and check model specific values
print('--Check YOLO intern values for custom purposes--')
model = YOLO('yolov8s-obb.yaml', 'obb', verbose=False) # n/s/m/l/x 
# Print layers, parameters, gradients, GFLOPS (computation depends on https://github.com/ultralytics/ultralytics/issues/17547#issuecomment-2481925742)
# https://github.com/ultralytics/ultralytics/issues/14749
print(model.info(detailed=False, verbose=True))

# https://community.ultralytics.com/t/about-yolo-configuration-file-yaml/300
results = model.train(data='/home/rlab10/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti_bev.yaml', epochs=10,
                      time=None, patience=10, batch=8, imgsz=640, save=True, save_period=2, cache=False,
                      device='cuda', workers=4, project='kitti_bev_yolo', name='run_', exist_ok=False,
                      pretrained=False, optimizer='Adam', seed=0, deterministic=False, single_cls=False,
                      classes=None, rect=False, cos_lr=False, close_mosaic=0, resume=True, amp=False,
                      fraction=1.0, profile=False, freeze=None, lr0=0.01, lrf=0.01,  momentum=0.937,
                      weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, 
                      box=7.5, cls=0.5, dfl=1.5, pose=0.0, kobj=0.0, nbs=64, overlap_mask=False, mask_ratio=0,
                      dropout=0.0, val=False, plots=False,
                      
                      hsv_h=0.0, hsv_s=0.0, hsv_v=0.0, degrees=0.0, translate=0.0, scale=0.0, shear=0.0, perspective=0.0,
                      flipud=0.0, fliplr=0.0, bgr=0.0, mosaic=0.0, mixup=0.0, copy_paste=0.0, copy_paste_mode='flip', auto_augment=None,
                      erasing=0.0, crop_fraction=0.0)
```
my requirements: the script should perform training jobs based on the number of hyperparameters and their combination and save the results individually and visualize and save them on the `wandb` platform. How should I implement this? The guide here: https://docs.ultralytics.com/integrations/weights-biases/ already provides information on this in the video, but is the method outdated?

method seen in video (applied to my code):
```python
import wandb
from wandb.integration.ultralytics import add_wandb_callback

from ultralytics import YOLO

wandb.init(project='kitti_bev_yolo', job_type='training')

model = YOLO('yolov8s-obb.yaml', 'obb', verbose=False)

add_wandb_callback(model, enable_model_checkpoint=True)

model.train('same arguments like above')
```

Thank you very much!

**Comment by glenn-jocher** [comment]
@Petros626 the method shown in the video for integrating Weights & Biases (wandb) with YOLO training is not outdated and can still be used effectively. To implement hyperparameter tuning with `wandb`, you'll need to define a search space for your parameters (like `lr0`, `batch`, etc.), run multiple training jobs with different combinations of hyperparameters, and log the results to `wandb`. You can achieve this by iterating through the parameter combinations programmatically or leveraging Ray Tune for automated tuning. Check out the [Weights & Biases Integration Guide](https://docs.ultralytics.com/integrations/weights-biases/) for setup instructions and the [Ray Tune Guide](https://docs.ultralytics.com/integrations/ray-tune/) for hyperparameter optimization. Let me know if you need further clarification!

**Comment by Petros626** [comment]
@glenn-jocher I created a sweep with `wandb`, does this make the use of Ray Tune obsolete? Is it recommended to search hyperparameters better with Ray Tun?

```python
import wandb
from wandb.integration.ultralytics import add_wandb_callback
from ultralytics import YOLO

wandb.login()

# Define sweep configuration
sweep_config = {
    'method': 'bayes',
    'metric': {
        'name': 'train/box_loss', # metric to optimize 
        'goal': 'minimize'
    },
    'parameters': {
        'epochs': {
            'values': [50, 60, 80, 100, 120]
        },
        'batch': {
            'values': [4, 8, 16, 24, 32, 48]
        },
        'optimizer': {
            'values': ['SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp', 'auto']
        },
        'lr0': {
            'distribution': 'uniform',
            'min': 1e-4,
            'max': 1e-1
        },
        'lrf': {
            'distribution': 'uniform',
            'min': 1e-4,
            'max': 1e-1
        },
        'momentum': {
            'values': [0.6, 0.7, 0.8, 0.837, 0.9, 0.937]
        },
        'weight_decay': {
            'values': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006] 
        },
        'warmup_epochs': {
            'values': [2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
        },
        'warmup_momentum':{
            'values': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
        },
        'warmup_bias_lr': {
            'values': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6] 
        },
        'box': {
            'values': [6.0, 6.5, 7.0, 7.5, 8.0, 8.5] # Box loss weight
        },
        'cls': {
            'values': [0.3, 0.5, 0.7, 1.0, 1.2, 1.5] # Class loss weight
        },
        'dfl': {
            'values': [0.5, 1.0, 1.2, 1.5, 1.8, 2.0] # DFL loss weight
        },
        'nbs': {
            'values': [4, 8, 16, 24, 32, 48, 64]
        }
    }
}

sweep_id = wandb.sweep(sweep_config, project='kitti_bev_yolo')

def train():
    try:
        # Initialize WandB run
        wandb.init(job_type='training')

        # Build a new model from scratch
        model = YOLO('yolov8s-obb.yaml', 'obb', verbose=False)

        # Add WandB callback for logging metrics and checkpoints
        add_wandb_callback(model=model, enable_model_checkpointing=True)

        # Train the model with hyperparameters from WandB
        results = model.train(data='/home/rlab10/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti_bev.yaml', epochs=wandb.config.epochs,
                            time=None, patience=10, batch=wandb.config.batch, imgsz=640, save=True, save_period=5, cache=True,
                            device='cuda', workers=4, project='kitti_bev_yolo', name=f'epo._{wandb.config.epochs}_bat._{wandb.config.batch}', exist_ok=False,
                            pretrained=False, optimizer=wandb.config.optimizer, seed=0, deterministic=False, single_cls=False,
                            classes=None, rect=False, cos_lr=False, close_mosaic=0, resume=True, amp=False,
                            fraction=1.0, profile=False, freeze=None, lr0=wandb.config.lr0, lrf=wandb.config.lrf,  momentum=wandb.config.momentum,
                            weight_decay=wandb.config.weight_decay, warmup_epochs=wandb.config.warmup_epochs, warmup_momentum=wandb.config.warmup_momentum, warmup_bias_lr=wandb.config.warmup_bias_lr, 
                            box=wandb.config.box, cls=wandb.config.cls, dfl=wandb.config.dfl, pose=0.0, kobj=0.0, nbs=wandb.config.nbs, overlap_mask=False, mask_ratio=0,
                            dropout=0.0, val=True, plots=False,
                            
                            hsv_h=0.0, hsv_s=0.0, hsv_v=0.0, degrees=0.0, translate=0.0, scale=0.0, shear=0.0, perspective=0.0,
                            flipud=0.0, fliplr=0.0, bgr=0.0, mosaic=0.0, mixup=0.0, copy_paste=0.0, copy_paste_mode='flip', auto_augment=None,
                            erasing=0.0, crop_fraction=0.0)
    finally:    
        wandb.finish()

wandb.agent(sweep_id=sweep_id, function=train, count=50)
```

**Comment by glenn-jocher** [comment]
The choice between using `wandb` sweeps or Ray Tune for hyperparameter tuning depends on your requirements. `wandb` sweeps are excellent for simplicity and integration with its visualization tools, as in your script. However, Ray Tune offers advanced search algorithms (e.g., Bayesian optimization, HyperBand), better scalability, and parallelism, which can be more efficient for exploring large or complex hyperparameter spaces. If you're satisfied with `wandb` sweeps' performance and features, Ray Tune may not be necessary, but for more extensive or resource-intensive tuning, Ray Tune could be advantageous. Learn more about Ray Tune [here](https://docs.ultralytics.com/integrations/ray-tune/).

**Comment by Petros626** [comment]
the problem is, that with `Ray Tune` the available params (default search space) to tune are limited when you compare it to `wandb sweep`.

**Comment by glenn-jocher** [comment]
@Petros626 you can customize the Ray Tune search space to include parameters like `warmup_bias_lr`, `dfl`, and `nbs` by defining them explicitly in the `space` argument. For example, pass `space={"warmup_bias_lr": tune.uniform(0.1, 0.5), "dfl": tune.uniform(0.5, 2.0), "nbs": tune.choice([16, 32, 64])}` when calling `model.tune()`. This allows you to extend the default search space as needed. More details: https://docs.ultralytics.com/integrations/ray-tune/.

**Comment by Petros626** [comment]
Thanks, will keep that in mind.

**Comment by glenn-jocher** [comment]
Ray Tune has its own logging system but also supports integration with external loggers like Weights & Biases (wandb) for enhanced tracking and visualization. If you want to log results to wandb, you can use the `WandbLoggerCallback` when configuring Ray Tune. Refer to the [Ray Tune documentation](https://docs.ultralytics.com/integrations/ray-tune/) for implementation details.
