### ISSUE TITLE
Error Handling in YOLOv8 Edge TPU Model: IndexError: list index out of range

### ISSUE THREAD

**Issue by AlaaArboun** [ultralytics/ultralytics#8727]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've been working on implementing YOLOv8 on an Edge TPU device for object detection tasks. While running inference, I encountered the following error:
```bash
IndexError: list index out of range
```
This error occurs when processing the output of the model in the process_predictions method of my EdgeTPUModel class. It seems to stem from accessing class names using the index from the predictions.

Here's the relevant snippet of the code where the error occurs:
```bash
s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
```
I have already ensured that the names list is properly loaded with the correct class names. However, it seems that the index int(c) is going out of range.

Has anyone encountered a similar issue while working with YOLOv8 on an Edge TPU device? How can I handle this error and ensure that the class index stays within the valid range?

I appreciate any insights or suggestions on resolving this issue. Thank you!

```bash
import time
import os
import sys
import logging

import yaml
import numpy as np
import pycoral.utils.edgetpu as etpu
from pycoral.adapters import common
from nms import non_max_suppression
import cv2
import json

from utils import plot_one_box, Colors, get_image_tensor

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("EdgeTPUModel")

class EdgeTPUModel:

    def __init__(self, model_file, names_file, conf_thresh=0.25, iou_thresh=0.45, filter_classes=None, agnostic_nms=False, max_det=1000):
        """
        Creates an object for running a Yolov5 model on an EdgeTPU
        
        Inputs:
          - model_file: path to edgetpu-compiled tflite file
          - names_file: yaml names file (yolov5 format)
          - conf_thresh: detection threshold
          - iou_thresh: NMS threshold
          - filter_classes: only output certain classes
          - agnostic_nms: use class-agnostic NMS
          - max_det: max number of detections
        """
    
        model_file = os.path.abspath(model_file)
    
        if not model_file.endswith('tflite'):
            model_file += ".tflite"
            
        self.model_file = model_file
        self.conf_thresh = conf_thresh
        self.iou_thresh = iou_thresh
        self.filter_classes = filter_classes
        self.agnostic_nms = agnostic_nms
        self.max_det = 1000
        
        logger.info("Confidence threshold: {}".format(conf_thresh))
        logger.info("IOU threshold: {}".format(iou_thresh))
        
        self.inference_time = None
        self.nms_time = None
        self.interpreter = None
        self.colors = Colors()  # create instance for 'from utils.plots import colors'
        
        self.get_names(names_file)
        self.make_interpreter()
        self.get_image_size()
        
    def get_names(self, path):
        """
        Load a names file
        
        Inputs:
          - path: path to names file in yaml format
        """

        with open(path, 'r',encoding='utf8') as f:
          cfg = yaml.load(f, Loader=yaml.SafeLoader)
          
        names = cfg['names']
        logger.info("Loaded {} classes".format(len(names)))
        
        self.names = names
    
    def make_interpreter(self):
        """
        Internal function that loads the tflite file and creates
        the interpreter that deals with the EdgetPU hardware.
        """
        # Load the model and allocate
        self.interpreter = etpu.make_interpreter(self.model_file)
        self.interpreter.allocate_tensors()
    
        self.input_details = self.interpreter.get_input_details()
        self.output_details = self.interpreter.get_output_details()
        
        logger.debug(self.input_details)
        logger.debug(self.output_details)
        
        self.input_zero = self.input_details[0]['quantization'][1]
        self.input_scale = self.input_details[0]['quantization'][0]
        self.output_zero = self.output_details[0]['quantization'][1]
        self.output_scale = self.output_details[0]['quantization'][0]
        
        # If the model isn't quantized then these should be zero
        # Check against small epsilon to avoid comparing float/int
        if self.input_scale < 1e-9:
            self.input_scale = 1.0
        
        if self.output_scale < 1e-9:
            self.output_scale = 1.0
    
        logger.debug("Input scale: {}".format(self.input_scale))
        logger.debug("Input zero: {}".format(self.input_zero))
        logger.debug("Output scale: {}".format(self.output_scale))
        logger.debug("Output zero: {}".format(self.output_zero))
        
        logger.info("Successfully loaded {}".format(self.model_file))
    
    def get_image_size(self):
        """
        Returns the expected size of the input image tensor
        """
        if self.interpreter is not None:
            self.input_size = common.input_size(self.interpreter)
            logger.debug("Expecting input shape: {}".format(self.input_size))
            return self.input_size
        else:
            logger.warn("Interpreter is not yet loaded")
            
    
    def predict(self, image_path, save_img=True, save_txt=True):
        logger.info("Attempting to load {}".format(image_path))
    
        full_image, net_image, pad = get_image_tensor(image_path, self.input_size[0])
        pred = self.forward(net_image)
        
        base, ext = os.path.splitext(image_path)
        
        output_path = base + "_detect" + ext
        det = self.process_predictions(pred[0], full_image, pad, output_path, save_img=save_img, save_txt=save_txt)
        
        return det
        
        
    
    def forward(self, x:np.ndarray, with_nms=True) -> np.ndarray:
        """
        Predict function using the EdgeTPU

        Inputs:
            x: (C, H, W) image tensor
            with_nms: apply NMS on output

        Returns:
            prediction array (with or without NMS applied)

        """
        tstart = time.time()
        # Transpose if C, H, W
        if x.shape[0] == 3:
          x = x.transpose((1,2,0))
        
        x = x.astype('float32')

        # Scale input, conversion is: real = (int_8 - zero)*scale
        x = (x/self.input_scale) + self.input_zero
        x = x[np.newaxis].astype(np.uint8)
        
        self.interpreter.set_tensor(self.input_details[0]['index'], x)
        self.interpreter.invoke()
        
        # Scale output
        result = (common.output_tensor(self.interpreter, 0).astype('float32') - self.output_zero) * self.output_scale
        self.inference_time = time.time() - tstart
        
        if with_nms:
        
            tstart = time.time()
            nms_result = non_max_suppression(result, self.conf_thresh, self.iou_thresh, self.filter_classes, self.agnostic_nms, max_det=self.max_det)
            self.nms_time = time.time() - tstart
            
            return nms_result
            
        else:    
          return result
          
    def get_last_inference_time(self, with_nms=True):
        """
        Returns a tuple containing most recent inference and NMS time
        """
        res = [self.inference_time]
        
        if with_nms:
          res.append(self.nms_time)
          
        return res
    
    def get_scaled_coords(self, xyxy, output_image, pad):
        """
        Converts raw prediction bounding box to orginal
        image coordinates.
        
        Args:
          xyxy: array of boxes
          output_image: np array
          pad: padding due to image resizing (pad_w, pad_h)
        """
        pad_w, pad_h = pad
        in_h, in_w = self.input_size
        out_h, out_w, _ = output_image.shape
                
        ratio_w = out_w/(in_w - pad_w)
        ratio_h = out_h/(in_h - pad_h) 
        
        out = []
        for coord in xyxy:

            x1, y1, x2, y2 = coord
                        
            x1 *= in_w*ratio_w
            x2 *= in_w*ratio_w
            y1 *= in_h*ratio_h
            y2 *= in_h*ratio_h
            
            x1 = max(0, x1)
            x2 = min(out_w, x2)
            
            y1 = max(0, y1)
            y2 = min(out_h, y2)
            
            out.append((x1, y1, x2, y2))
        
        return np.array(out).astype(int)

    def process_predictions(self, det, output_image, pad, output_path="detection.jpg", save_img=True, save_txt=True, hide_labels=False, hide_conf=False):
        """
        Process predictions and optionally output an image with annotations
        """
        if len(det):
            # Rescale boxes from img_size to im0 size
            # x1, y1, x2, y2=
            det[:, :4] = self.get_scaled_coords(det[:,:4], output_image, pad)
            output = {}
            base, ext = os.path.splitext(output_path)
            
            s = ""
            
            # Print results
            for c in np.unique(det[:, -1]):
                n = (det[:, -1] == c).sum()  # detections per class
                s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "  # add to string
            
            if s != "":
                s = s.strip()
                s = s[:-1]
            
            logger.info("Detected: {}".format(s))
            
            # Write results
            for *xyxy, conf, cls in reversed(det):
                if save_img:  # Add bbox to image
                    c = int(cls)  # integer class
                    label = None if hide_labels else (self.names[c] if hide_conf else f'{self.names[c]} {conf:.2f}')
                    output_image = plot_one_box(xyxy, output_image, label=label, color=self.colors(c, True))
                if save_txt:
                    output[base] = {}
                    output[base]['box'] = xyxy
                    output[base]['conf'] = conf
                    output[base]['cls'] = cls
                    output[base]['cls_name'] = self.names[c]
                    
            if save_txt:
                output_txt = base+".txt"
                with open(output_txt, 'w') as f:
                   json.dump(output, f, indent=1)
            if save_img:
              cv2.imwrite(output_path, output_image)
            
        return det
py -3.9 detect.py -m yolov8m_integer_quant_edgetpu.tflite --device 0
INFO:EdgeTPUModel:Confidence threshold: 0.25
INFO:EdgeTPUModel:IOU threshold: 0.45
INFO:EdgeTPUModel:Loaded 80 classes
INFO:EdgeTPUModel:Successfully loaded C:\edge-inf\edgetpu-yolo\yolov8m_integer_quant_edgetpu.tflite
INFO:__main__:Opening camera on device: 0
Traceback (most recent call last):
  File "C:\edge-inf\edgetpu-yolo\detect.py", line 369, in <module>
    model.process_predictions(pred[0], full_image, pad)
  File "C:\edge-inf\edgetpu-yolo\edgetpumodel.py", line 328, in process_predictions
    s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "  # add to string
IndexError: list index out of range```

### Additional

_No response_

**Comment by glenn-jocher** [comment]
@AlaaArboun hey there! 👋 It looks like you're encountering an `IndexError` because the class index `int(c)` is going beyond the range of your `self.names` list. This could happen if the model predicts a class index that doesn't exist in your `names` file. Here are a couple of suggestions to troubleshoot this issue:

1. **Verify Class Indices:** Ensure that the class indices predicted by your model match the indices in your `names` file. The indices should start from `0` and be continuous.

2. **Debugging Print:** Temporarily add a print statement before the error line to print out the value of `int(c)` and the length of `self.names`. This can help identify if and when the index goes out of range.
   ```bash
   print(f"Index: {int(c)}, Names Length: {len(self.names)}")
   ```

3. **Safe Access:** As a quick fix, you can modify the line causing the error to safely access class names with a default value if the index is out of range. For example:
   ```bash
   class_name = self.names[int(c)] if int(c) < len(self.names) else 'Unknown'
   s += f"{n} {class_name}{'s' * (n > 1)}, "
   ```

This should help you avoid the `IndexError` and identify if there are any discrepancies in the class indices. If the issue persists, it might be worth double-checking the model and `names` file to ensure they are correctly aligned. Hope this helps! Let us know if you have any more questions. 😊

**Comment by Burhan-Q** [comment]
@AlaaArboun this is **a lot** more code than you probably really need.

> [!IMPORTANT]
> You can load **all** model export types using YOLO.

<br></br>

```py
from ultralytics import YOLO

model = YOLO("yolov8n_edgetpu.tflite", task="detect")
```

I very much recommend reading thru [this guide](https://docs.ultralytics.com/guides/coral-edge-tpu-on-raspberry-pi/) which was written by a member of our Discord community.

**Comment by AlaaArboun** [comment]
I want to extend my sincere thanks to @glenn-jocher  and @Burhan-Q  for their invaluable help and time in assisting me.

How can I adapt my code to work with YOLOv8? Currently, my code is designed for YOLOv5 models, and it works fine. However, when I try to test it with a YOLOv8 model, I encounter an error. Here's the relevant part of the code:

```bash
import time
import os
import sys
import logging

import yaml
import numpy as np
import pycoral.utils.edgetpu as etpu
from pycoral.adapters import common
from nms import non_max_suppression
import cv2
import json

from utils import plot_one_box, Colors, get_image_tensor

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("EdgeTPUModel")

class EdgeTPUModel:

    def __init__(self, model_file, names_file, conf_thresh=0.25, iou_thresh=0.45, filter_classes=None, agnostic_nms=False, max_det=1000):
        """
        Creates an object for running a Yolov5 model on an EdgeTPU
        
        Inputs:
          - model_file: path to edgetpu-compiled tflite file
          - names_file: yaml names file (yolov5 format)
          - conf_thresh: detection threshold
          - iou_thresh: NMS threshold
          - filter_classes: only output certain classes
          - agnostic_nms: use class-agnostic NMS
          - max_det: max number of detections
        """
    
        model_file = os.path.abspath(model_file)
    
        if not model_file.endswith('tflite'):
            model_file += ".tflite"
            
        self.model_file = model_file
        self.conf_thresh = conf_thresh
        self.iou_thresh = iou_thresh
        self.filter_classes = filter_classes
        self.agnostic_nms = agnostic_nms
        self.max_det = 1000
        
        logger.info("Confidence threshold: {}".format(conf_thresh))
        logger.info("IOU threshold: {}".format(iou_thresh))
        
        self.inference_time = None
        self.nms_time = None
        self.interpreter = None
        self.colors = Colors()  # create instance for 'from utils.plots import colors'
        
        self.get_names(names_file)
        self.make_interpreter()
        self.get_image_size()
        
    def get_names(self, path):
        """
        Load a names file
        
        Inputs:
          - path: path to names file in yaml format
        """

        with open(path, 'r',encoding='utf8') as f:
          cfg = yaml.load(f, Loader=yaml.SafeLoader)
          
        names = cfg['names']
        logger.info("Loaded {} classes".format(len(names)))
        
        self.names = names
    
    def make_interpreter(self):
        """
        Internal function that loads the tflite file and creates
        the interpreter that deals with the EdgetPU hardware.
        """
        # Load the model and allocate
        self.interpreter = etpu.make_interpreter(self.model_file)
        self.interpreter.allocate_tensors()
    
        self.input_details = self.interpreter.get_input_details()
        self.output_details = self.interpreter.get_output_details()
        
        logger.debug(self.input_details)
        logger.debug(self.output_details)
        
        self.input_zero = self.input_details[0]['quantization'][1]
        self.input_scale = self.input_details[0]['quantization'][0]
        self.output_zero = self.output_details[0]['quantization'][1]
        self.output_scale = self.output_details[0]['quantization'][0]
        
        # If the model isn't quantized then these should be zero
        # Check against small epsilon to avoid comparing float/int
        if self.input_scale < 1e-9:
            self.input_scale = 1.0
        
        if self.output_scale < 1e-9:
            self.output_scale = 1.0
    
        logger.debug("Input scale: {}".format(self.input_scale))
        logger.debug("Input zero: {}".format(self.input_zero))
        logger.debug("Output scale: {}".format(self.output_scale))
        logger.debug("Output zero: {}".format(self.output_zero))
        
        logger.info("Successfully loaded {}".format(self.model_file))
    
    def get_image_size(self):
        """
        Returns the expected size of the input image tensor
        """
        if self.interpreter is not None:
            self.input_size = common.input_size(self.interpreter)
            logger.debug("Expecting input shape: {}".format(self.input_size))
            return self.input_size
        else:
            logger.warn("Interpreter is not yet loaded")
            
    
    def predict(self, image_path, save_img=True, save_txt=True):
        logger.info("Attempting to load {}".format(image_path))
    
        full_image, net_image, pad = get_image_tensor(image_path, self.input_size[0])
        pred = self.forward(net_image)
        
        base, ext = os.path.splitext(image_path)
        
        output_path = base + "_detect" + ext
        det = self.process_predictions(pred[0], full_image, pad, output_path, save_img=save_img, save_txt=save_txt)
        
        return det
        
        
    
    def forward(self, x:np.ndarray, with_nms=True) -> np.ndarray:
        """
        Predict function using the EdgeTPU

        Inputs:
            x: (C, H, W) image tensor
            with_nms: apply NMS on output

        Returns:
            prediction array (with or without NMS applied)

        """
        tstart = time.time()
        # Transpose if C, H, W
        if x.shape[0] == 3:
          x = x.transpose((1,2,0))
        
        x = x.astype('float32')

        # Scale input, conversion is: real = (int_8 - zero)*scale
        x = (x/self.input_scale) + self.input_zero
        x = x[np.newaxis].astype(np.uint8)
        #x = x.astype(np.int8)[np.newaxis]
        
        self.interpreter.set_tensor(self.input_details[0]['index'], x)
        self.interpreter.invoke()
        
        # Scale output
        result = (common.output_tensor(self.interpreter, 0).astype('float32') - self.output_zero) * self.output_scale
        self.inference_time = time.time() - tstart
        
        if with_nms:
        
            tstart = time.time()
            nms_result = non_max_suppression(result, self.conf_thresh, self.iou_thresh, self.filter_classes, self.agnostic_nms, max_det=self.max_det)
            self.nms_time = time.time() - tstart
            
            return nms_result
            
        else:    
          return result
          
    def get_last_inference_time(self, with_nms=True):
        """
        Returns a tuple containing most recent inference and NMS time
        """
        res = [self.inference_time]
        
        if with_nms:
          res.append(self.nms_time)
          
        return res
    
    def get_scaled_coords(self, xyxy, output_image, pad):
        """
        Converts raw prediction bounding box to orginal
        image coordinates.
        
        Args:
          xyxy: array of boxes
          output_image: np array
          pad: padding due to image resizing (pad_w, pad_h)
        """
        pad_w, pad_h = pad
        in_h, in_w = self.input_size
        out_h, out_w, _ = output_image.shape
                
        ratio_w = out_w/(in_w - pad_w)
        ratio_h = out_h/(in_h - pad_h) 
        
        out = []
        for coord in xyxy:

            x1, y1, x2, y2 = coord
                        
            x1 *= in_w*ratio_w
            x2 *= in_w*ratio_w
            y1 *= in_h*ratio_h
            y2 *= in_h*ratio_h
            
            x1 = max(0, x1)
            x2 = min(out_w, x2)
            
            y1 = max(0, y1)
            y2 = min(out_h, y2)
            
            out.append((x1, y1, x2, y2))
        
        return np.array(out).astype(int)

    def process_predictions(self, det, output_image, pad, output_path="detection.jpg", save_img=True, save_txt=True, hide_labels=False, hide_conf=False):
        """
        Process predictions and optionally output an image with annotations
        """
        if len(det):
            # Rescale boxes from img_size to im0 size
            # x1, y1, x2, y2=
            print("det array:", det)
            print("np.unique(det[:, -1]) : ",np.unique(det[:, -1]))
            det[:, :4] = self.get_scaled_coords(det[:,:4], output_image, pad)
            output = {}
            base, ext = os.path.splitext(output_path)
            
            s = ""
            
            # Print results
            for c in np.unique(det[:, -1]):
                n = (det[:, -1] == c).sum()  # detections per class
                print(f"Index: {int(c)}, Names Lengthh: {len(self.names)}")
                s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "  # add to string
            
            if s != "":
                s = s.strip()
                s = s[:-1]
            
            logger.info("Detected: {}".format(s))
            
            # Write results
            for *xyxy, conf, cls in reversed(det):
                if save_img:  # Add bbox to image
                    c = int(cls)  # integer class
                    label = None if hide_labels else (self.names[c] if hide_conf else f'{self.names[c]} {conf:.2f}')
                    output_image = plot_one_box(xyxy, output_image, label=label, color=self.colors(c, True))
                if save_txt:
                    output[base] = {}
                    output[base]['box'] = xyxy
                    output[base]['conf'] = conf
                    output[base]['cls'] = cls
                    output[base]['cls_name'] = self.names[c]
                    
            if save_txt:
                output_txt = base+".txt"
                with open(output_txt, 'w') as f:
                   json.dump(output, f, indent=1)
            if save_img:
              cv2.imwrite(output_path, output_image)
            
        return det




$ py -3.9 detect.py -m yolov5s-int8-224_edgetpu.tflite --device 0
INFO:EdgeTPUModel:Confidence threshold: 0.25
INFO:EdgeTPUModel:IOU threshold: 0.45
INFO:EdgeTPUModel:Loaded 80 classes
INFO:EdgeTPUModel:Successfully loaded C:\edge-inf\edgetpu-yolo\yolov5s-int8-224_edgetpu.tflite
INFO:__main__:Opening camera on device: 0
det array: [[-0.01910502  0.          1.02530527  0.7259925   0.42559415  0.        ]]
np.unique(det[:, -1]) :  [0.]
Index: 0, Names Lengthh: 80
INFO:EdgeTPUModel:Detected: 1 person



 
 py -3.9 detect.py -m yolov8s_full_integer_quant_edgetpu.tflite --device 0
INFO:EdgeTPUModel:Confidence threshold: 0.25
INFO:EdgeTPUModel:IOU threshold: 0.45
INFO:EdgeTPUModel:Loaded 80 classes
INFO:EdgeTPUModel:Successfully loaded C:\edge-inf\edgetpu-yolo\yolov8s_full_integer_quant_edgetpu.tflite
INFO:__main__:Opening camera on device: 0
det array: [[-6.86249435e-02  4.32083011e-02  1.60124868e-01  3.32958043e-01
   3.91944677e-01  7.39000000e+02]]
np.unique(det[:, -1]) :  [739.]
Index: 739, Names Lengthh: 80
Traceback (most recent call last):
  File "C:\edge-inf\edgetpu-yolo\detect.py", line 369, in <module>
    model.process_predictions(pred[0], full_image, pad)
  File "C:\edge-inf\edgetpu-yolo\edgetpumodel.py", line 246, in process_predictions
    s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "  # add to string
IndexError: list index out of range
```Could someone guide me on how to modify my code to make it compatible with YOLOv8 models? I believe there might be an issue with class indexing or the output format of the YOLOv8 model. Any help would be appreciated. Thank you!

**Comment by glenn-jocher** [comment]
@AlaaArboun hey there! 😊 It's great to see you're exploring YOLOv8 with Edge TPU. The error you're encountering is likely due to a mismatch in the expected output format between YOLOv5 and YOLOv8 models. YOLOv8 might be predicting class indices that are not present in your `names` file or the model's output structure might be slightly different.

To adapt your code for YOLOv8, you might want to:

1. **Check the Output Format**: Ensure the output format of YOLOv8 matches what your code expects. YOLOv8 might have additional outputs or a different ordering.

2. **Debug the Class Indices**: Add a print statement before the error line to check the class indices (`int(c)`) being accessed and compare them with the length of `self.names`. This can help identify if the index is indeed out of range.

3. **Update the `get_names` Method**: Make sure the `names_file` you're loading matches the YOLOv8 model's classes. YOLOv8 might have a different set of classes or class IDs.

4. **Safely Access Class Names**: Modify the line causing the error to safely access class names. For example:
   ```python
   class_name = self.names[int(c)] if int(c) < len(self.names) else 'Unknown'
   s += f"{n} {class_name}{'s' * (n > 1)}, "
   ```
   This change ensures that if an out-of-range index is encountered, it defaults to 'Unknown'.

5. **Review Model Outputs**: If YOLOv8's output includes additional data not present in YOLOv5, adjust your processing logic to accommodate these changes.

Here's a quick example of safely accessing class names:
```python
for *xyxy, conf, cls in reversed(det):
    c = int(cls)
    class_name = self.names[c] if c < len(self.names) else 'Unknown'
    # Proceed with your existing logic
```

Remember, adapting code between model versions might require a bit of trial and error to align output formats and class indices. If you have more specific error messages or output data, feel free to share for more targeted advice. Good luck! 🚀

**Comment by Burhan-Q** [comment]
@AlaaArboun modifying your code for use with YOLOv8 is an engineering task that is outside the scope of support Ultralytics can provide. If you wrote the code for YOLOv5 models, then you should be more than capable of translating it to function with YOLOv8 models.

The code snippet and information I linked to in my previous post is _more than enough_ to get you started down the correct path. If this is not something you're capable of doing on your own, I recommend that you instead hire someone to make the changes you need.
