### ISSUE TITLE
IndexError when Accessing Output Tensor Details in Coral Edge TPU Model

### ISSUE THREAD

**Issue by AlaaArboun** [ultralytics/ultralytics#8760]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi community,

I hope you're doing well. I'm currently working on an object detection project using TensorFlow Lite and Edge TPU. However, I'm encountering an IndexError in my code, and I would appreciate your assistance in resolving it.

```bash

import json
import os
import cv2
import numpy as np
from tkinter import filedialog
from pycoral.adapters import common
from pycoral.adapters import detect
from pycoral.utils.edgetpu import make_interpreter
import threading
import time
from sklearn.metrics.pairwise import euclidean_distances
import tkinter as tk
import threading
from queue import Queue
import time
from sklearn.metrics.pairwise import euclidean_distances



class ObjectDetector:
    def __init__(self, model_path, label_path, threshold=0.3):
        self.threshold = threshold
        self.interpreter = make_interpreter(model_path)
        self.interpreter.allocate_tensors()
        self.input_details = self.interpreter.get_input_details()
        self.output_details = self.interpreter.get_output_details()
        self.input_shape = self.input_details[0]['shape'][1:]
        self.class_labels = self.load_class_labels(label_path)

        self.frame_count = 0
        self.start_time = time.time()

        # Print output details
        print("input Details:")
        for detail in self.input_details:
            
            print(detail)
        # Print output details
        print("Output Details:")
        for detail in self.output_details:
            print(detail)

    def load_class_labels(self, label_path):
        with open(label_path, 'r') as json_file:
            class_labels = json.load(json_file)
        return class_labels

    def preprocess_frame(self, frame):
        image_resized = cv2.resize(frame, (self.input_shape[0], self.input_shape[1]))
        image_resized = image_resized.astype(np.float32)
        return image_resized

    def perform_inference(self, frame, preprocessed_frame, orig_h, orig_w):
        common.set_input(self.interpreter, preprocessed_frame)
        self.interpreter.invoke()
        results = detect.get_objects(self.interpreter, score_threshold=self.threshold, image_scale=(orig_w, orig_h))
        print(results)

        for obj in results:
            bbox = obj.bbox
            x1, y1, x2, y2 = bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax
            class_id = obj.id
            score = obj.score
            class_name = self.class_labels[str(class_id)]
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 255), thickness=2)
            cv2.putText(frame, f"{class_name}: {score:.2f}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        self.frame_count += 1

    def get_fps(self):
        current_time = time.time()
        elapsed_time = current_time - self.start_time
        return self.frame_count / elapsed_time if elapsed_time > 0 else 0

    def detect_objects(self, frame):
        orig_h, orig_w = frame.shape[:2]
        preprocessed_frame = self.preprocess_frame(frame)
        self.perform_inference(frame, preprocessed_frame, orig_h, orig_w)

    def run_detection(self, cap, output_queue):
        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            self.detect_objects(frame)
            output_queue.put(frame)
        cap.release()
        output_queue.put(None)

class App:
    def __init__(self, root):
        self.root = root
        self.root.title("Object Detection")
        self.detector = None

        select_button = tk.Button(root, text="Select Video", command=self.open_video)
        select_button.pack()

    def open_video(self):
        file_path = filedialog.askopenfilename()
        if file_path:
            cap = cv2.VideoCapture(file_path)
            output_queue = Queue()
            self.detector = ObjectDetector(
                model_path='C:\edge-inf\edgetpu-yolo\yolov8m_float32.tflite',
                label_path='label_files\labels_coco.json'
            )
            detection_thread = threading.Thread(target=self.detector.run_detection, args=(cap, output_queue))
            detection_thread.start()
            self.process_output(output_queue)

    def process_output(self, output_queue):
        while True:
            frame = output_queue.get()
            if frame is None:
                break
            cv2.putText(frame, f"FPS: {self.detector.get_fps():.2f}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
            cv2.imshow('Object Detection', frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

if __name__ == "__main__":
    root = tk.Tk()
    app = App(root)
    root.mainloop()

 
input Details:
{'name': 'inputs_0', 'index': 0, 'shape': array([  1, 256, 256,   3]), 'shape_signature': array([  1, 256, 256,   3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'sc
ales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}

Output Details:
{'name': 'Identity', 'index': 516, 'shape': array([   1,   84, 1344]), 'shape_signature': array([   1,   84, 1344]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scal
es': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Ala Arboun\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Ala Arboun\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\edge-inf\edgetpu-yolo\test.py", line 91, in run_detection
    self.detect_objects(frame)
  File "C:\edge-inf\edgetpu-yolo\test.py", line 84, in detect_objects
    self.perform_inference(frame, preprocessed_frame, orig_h, orig_w)
  File "C:\edge-inf\edgetpu-yolo\test.py", line 62, in perform_inference
    results = detect.get_objects(self.interpreter, score_threshold=self.threshold, image_scale=(orig_w, orig_h))
  File "C:\Users\Ala Arboun\AppData\Local\Programs\Python\Python39\lib\site-packages\pycoral\adapters\detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "C:\Users\Ala Arboun\AppData\Local\Programs\Python\Python39\lib\site-packages\pycoral\adapters\common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range
```

**Comment by glenn-jocher** [comment]
@AlaaArboun hello! 👋 It looks like you're encountering an `IndexError` because the code is trying to access an output tensor index that doesn't exist in your model's output details. This often happens when the expected number of output tensors doesn't match the actual model outputs.

In your case, the error occurs here:
```python
elif common.output_tensor(interpreter, 3).size == 1:
```
It seems your model doesn't have a fourth output tensor (Python uses 0-based indexing, so index 3 refers to the fourth tensor).

To resolve this, you should first verify the number of output tensors your model is supposed to have. You can do this by examining the `self.output_details` you printed. Ensure that the code accessing the output tensors matches the actual structure of your model's outputs.

If your model indeed has fewer output tensors, adjust the indices accordingly. For example, if your model only has 3 output tensors, you should not access an index of 3 or higher.

Hope this helps! Let us know if you have further questions.
