### ISSUE TITLE
path error is occurred when using model.train with cfg argument in multi-gpu setting

### ISSUE THREAD

**Issue by GWLee0524** [ultralytics/ultralytics#8773]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```
model.train(data=opt.data, imgsz=opt.imgsz, batch=opt.batch_size, epochs=opt.epochs, device=opt.device, project=opt.project, name=opt.name, exist_ok=opt.exist_ok,
                cfg=opt.hyp,  # problem here!
                seed=opt.seed, 
                optimizer=opt.optimizer, 
                single_cls=opt.single_cls,
                rect=opt.rect, 
                cos_lr=opt.cos_lr,
                resume=opt.resume, 
                workers=opt.workers, 
                patience=opt.patience,
                freeze=opt.freeze, 
                cache=opt.cache, 
                multi_scale=opt.multi_scale,
```

I used model.train like above code. it is okay in single-gpu setting but makes a path error in multi-gpu setting.

Error message is here
```
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_jnoo2ajf139821505575424.py", line 12, in <module>
    results = trainer.train()
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 236, in _setup_train
    ckpt = self.setup_model()
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 521, in setup_model
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)
  File "/public/open_source_codes/ultralytics/ultralytics/models/yolo/obb/train.py", line 33, in get_model
    model = OBBModel(cfg, ch=3, nc=self.data["nc"], verbose=verbose and RANK == -1)
  File "/public/open_source_codes/ultralytics/ultralytics/nn/tasks.py", line 349, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "/public/open_source_codes/ultralytics/ultralytics/nn/tasks.py", line 274, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/public/open_source_codes/ultralytics/ultralytics/nn/tasks.py", line 916, in yaml_model_load
    path = Path(path)
  File "/opt/conda/envs/yolov8/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/opt/conda/envs/yolov8/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/opt/conda/envs/yolov8/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
```

I think that this error comes from DDP checking. But why it cannot interpret custom cfg which is used in default.yaml

I think that it is a bug.

**Comment by GWLee0524** [comment]
Thanks to reply!

I do your solution with two different ways.

First one is giving absolute path to argument.

Second one is making file path as abspath.

These two ways do not solve my problem, this means that same error occurs.

**Comment by GWLee0524** [comment]
```
Traceback (most recent call last):                                                                                                                                                                                                                                               
  File "/root/.config/Ultralytics/DDP/_temp_wmb9jx99139849354148352.py", line 12, in <module>                                                                                                                                                                                    
    results = trainer.train()                                                                                                                                                                                                                                                    
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 208, in train                                                                                                                                                                                 
    self._do_train(world_size)                                                                                                                                                                                                                                                   
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 322, in _do_train                                                                                                                                                                             
    self._setup_train(world_size)                                                                                                                                                                                                                                                
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 236, in _setup_train                                                                                                                                                                          
    ckpt = self.setup_model()                                                                                                                                                                                                                                                    
  File "/public/open_source_codes/ultralytics/ultralytics/engine/trainer.py", line 521, in setup_model                                                                                                                                                                           
    self.model = self.get_model(cfg=cfg, weights=weights, verbose=RANK == -1)  # calls Model(cfg, weights)                                                                                                                                                                       
  File "/public/open_source_codes/ultralytics/ultralytics/models/yolo/obb/train.py", line 33, in get_model                                                                                                                                                                       
    model = OBBModel(cfg, ch=3, nc=self.data["nc"], verbose=verbose and RANK == -1)                                                                                                                                                                                              
  File "/public/open_source_codes/ultralytics/ultralytics/nn/tasks.py", line 349, in __init__                                                                                                                                                                                    
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)                                                                                                                                                                                                                     
  File "/public/open_source_codes/ultralytics/ultralytics/nn/tasks.py", line 274, in __init__                                                                                                                                                                                    
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict                                                                                                                                                                                               
  File "/public/open_source_codes/ultralytics/ultralytics/nn/tasks.py", line 916, in yaml_model_load                                                                                                                                                                             
    path = Path(path)                                                                                                                                                                                                                                                            
  File "/opt/conda/envs/yolov8/lib/python3.10/pathlib.py", line 960, in __new__                                                                                                                                                                                                  
    self = cls._from_parts(args)                                                                                                                                                                                                                                                 
  File "/opt/conda/envs/yolov8/lib/python3.10/pathlib.py", line 594, in _from_parts                                                                                                                                                                                              
    drv, root, parts = self._parse_args(args)                                                                                                                                                                                                                                    
  File "/opt/conda/envs/yolov8/lib/python3.10/pathlib.py", line 578, in _parse_args                                                                                                                                                                                              
    a = os.fspath(a)                                                                                                                                                                                                                                                             
TypeError: expected str, bytes or os.PathLike object, not NoneType  
```

The last error message is not copied to the main post. Sorry for that.

**Comment by glenn-jocher** [comment]
@GWLee0524 hey there! 😊 It looks like the error you're encountering is due to the `cfg` parameter being passed as `None` or not being correctly recognized as a path or dictionary. This typically happens when the path to the configuration file or the configuration dictionary itself isn't properly specified or accessible in the multi-GPU environment.

To troubleshoot, let's ensure the `cfg` parameter is correctly set up. If you're passing a file path, double-check that the path is correct and accessible from all GPUs. Here's a quick way to ensure the path is absolute:

```python
import os

# Assuming 'cfg_path' is your configuration file path
cfg_path = 'path/to/your/config.yaml'
absolute_cfg_path = os.path.abspath(cfg_path)
```

Then, pass `absolute_cfg_path` to your `model.train` call as the `cfg` argument.

If `cfg` is supposed to be a dictionary, ensure it's defined before passing it to `model.train`:

```python
cfg_dict = {
    # Your configuration here
}

# Then pass cfg_dict as the cfg argument
```

If these steps don't resolve the issue, it might be helpful to manually verify that the `cfg` parameter is not `None` right before it's used in your training script. This can help identify where the misconfiguration might be occurring.

Hope this helps! Let us know if you're still facing issues or if there's anything else we can assist you with.

**Comment by GWLee0524** [comment]
```
def parse_opt(known=False):
    parser = argparse.ArgumentParser()
    parser.add_argument('--modeltask', type=str, default='detect', help='task of YOLO model detect, segment, classify, pose')
    parser.add_argument('--weights', type=str, default=ROOT / 'yolov8n.pt', help='initial weights path')
    parser.add_argument('--cfg', type=str, default='', help='model.yaml path')
    parser.add_argument('--data', type=str, default=ROOT / 'ultralytics/cfg/datasets/coco128.yaml', help='dataset.yaml path')
    parser.add_argument('--hyp', type=str, default=ROOT / 'hyps/hyp_FAIR1M.yaml', help='hyperparameters path')
    parser.add_argument('--epochs', type=int, default=100, help='total training epochs')
    parser.add_argument('--batch-size', type=int, default=16, help='total batch size for all GPUs, -1 for autobatch')
    parser.add_argument('--imgsz', '--img', '--img-size', type=int, default=640, help='train, val image size (pixels)')
    parser.add_argument('--rect', action='store_true', help='rectangular training')
    parser.add_argument('--resume', nargs='?', const=True, default=False, help='resume most recent training')
    # parser.add_argument('--nosave', action='store_true', help='only save final checkpoint')
    # parser.add_argument('--noval', action='store_true', help='only validate final epoch')
    # parser.add_argument('--noautoanchor', action='store_true', help='disable AutoAnchor')
    # parser.add_argument('--noplots', action='store_true', help='save no plot files')
    # parser.add_argument('--evolve', type=int, nargs='?', const=300, help='evolve hyperparameters for x generations')
    parser.add_argument('--bucket', type=str, default='', help='gsutil bucket')
    parser.add_argument('--cache', type=str, nargs='?', const='ram', help='image --cache ram/disk')
    parser.add_argument('--image-weights', action='store_true', help='use weighted image selection for training')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--multi-scale', action='store_true', help='vary img-size +/- 50%%')
    parser.add_argument('--single-cls', action='store_true', help='train multi-class data as single-class')
    parser.add_argument('--optimizer', type=str, choices=['SGD', 'Adam', 'Adamax', 'AdamW', 'NAdam', 'RAdam', 'RMSProp', 'auto'], default='auto', help='optimizer')
    # parser.add_argument('--sync-bn', action='store_true', help='use SyncBatchNorm, only available in DDP mode')
    parser.add_argument('--workers', type=int, default=8, help='max dataloader workers (per RANK in DDP mode)')
    parser.add_argument('--project', default=ROOT / 'result_train', help='save to project/name')
    parser.add_argument('--name', default='exp', help='save to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--quad', action='store_true', help='quad dataloader')
    parser.add_argument('--cos-lr', action='store_true', help='cosine LR scheduler')
    # parser.add_argument('--label-smoothing', type=float, default=0.0, help='Label smoothing epsilon')
    parser.add_argument('--patience', type=int, default=100, help='EarlyStopping patience (epochs without improvement)')
    parser.add_argument('--freeze', nargs='+', type=int, default=None, help='Freeze layers: backbone=10, first3=0 1 2')
    parser.add_argument('--save-period', type=int, default=-1, help='Save checkpoint every x epochs (disabled if < 1)')
    parser.add_argument('--seed', type=int, default=0, help='Global training seed')
    parser.add_argument('--local_rank', type=int, default=-1, help='Automatic DDP Multi-GPU argument, do not modify')

    # Logger arguments
    parser.add_argument('--entity', default=None, help='Entity')
    parser.add_argument('--upload_dataset', nargs='?', const=True, default=False, help='Upload data, "val" option')
    parser.add_argument('--bbox_interval', type=int, default=-1, help='Set bounding-box image logging interval')
    parser.add_argument('--artifact_alias', type=str, default='latest', help='Version of dataset artifact to use')


    return parser.parse_known_args()[0] if known else parser.parse_args()


def main(opt):
    if opt.cfg:
        model = YOLO(opt.cfg)
        print('run with cfg')
    else:
        model = YOLO(opt.weights)
    print(opt.device)
    opt.hyp = os.path.abspath(opt.hyp)
    print(opt.hyp)
    model.train(
                data=opt.data, imgsz=opt.imgsz, batch=opt.batch_size, epochs=opt.epochs, device=opt.device, project=opt.project, name=opt.name, exist_ok=opt.exist_ok,
                cfg=opt.hyp, 
                seed=opt.seed, 
                optimizer=opt.optimizer, 
                single_cls=opt.single_cls,
                rect=opt.rect, 
                cos_lr=opt.cos_lr,
                resume=opt.resume, 
                workers=opt.workers, 
                patience=opt.patience,
                freeze=opt.freeze, 
                cache=opt.cache, 
                multi_scale=opt.multi_scale,
                )
```

Firstly, it is my custom training code.

And I debug the codes and find a new thing.

![image](https://github.com/ultralytics/ultralytics/assets/11944802/555b3c1b-2e27-40bc-bd5e-a0a85dac61b2)
I searched __init__ of BaseTrainer in `ultralytics/engine/trainer` 

self.args.model is None when cfg argument is used and self.args.model is `model_name` (in my case yolov8s-obb.yaml) when cfg argument is not used.

I think that cfg argument has same role of  `cfg` in `default.yaml`. But it does not in my case.

So it might be best that reading cfg as yaml dict and gives kwargs to model.train

**Comment by glenn-jocher** [comment]
@GWLee0524 hey there! 😊 It looks like you've done some great debugging on your custom training code. You're right; when you specify the `cfg` argument, it should ideally serve the same role as the `cfg` in `default.yaml`. However, it seems there's a bit of confusion in how the `cfg` argument is being handled, especially in relation to `self.args.model`.

To address the issue, you could indeed read the `cfg` as a YAML dictionary and pass it as keyword arguments (`kwargs`) to `model.train`. Here's a quick example of how you might do that:

```python
import yaml

def main(opt):
    # Load hyperparameters from YAML file if specified
    if opt.hyp:
        with open(opt.hyp) as f:
            hyp = yaml.safe_load(f)
    else:
        hyp = {}

    # Initialize model with cfg or weights
    if opt.cfg:
        model = YOLO(opt.cfg)
        print('Run with cfg')
    else:
        model = YOLO(opt.weights)

    # Pass hyperparameters and other options to model.train
    model.train(
        data=opt.data, imgsz=opt.imgsz, batch=opt.batch_size, epochs=opt.epochs, device=opt.device, project=opt.project, name=opt.name, exist_ok=opt.exist_ok,
        **hyp,  # Pass hyperparameters as kwargs
        seed=opt.seed, optimizer=opt.optimizer, single_cls=opt.single_cls, rect=opt.rect, cos_lr=opt.cos_lr,
        resume=opt.resume, workers=opt.workers, patience=opt.patience, freeze=opt.freeze, cache=opt.cache, multi_scale=opt.multi_scale,
    )
```

This approach ensures that the hyperparameters loaded from the YAML file are correctly passed to `model.train` as keyword arguments, potentially resolving the issue with `self.args.model` being `None`.

Let us know if this helps or if you encounter any further issues! Happy coding! 🚀

**Comment by GWLee0524** [comment]
@glenn-jocher 
Thanks to reply!

It works very well. 

By the way, I tried removing cfg argument in `default.yaml`, because I filled it to `my_cfg_path`.
But it doesn't solve my problem..

In conclusion, I guess that overriding is happened when giving `cfg` argument in DDP setting.

I close this issue. If I fix this issue later, then I will reopen this issue and PR it

**Comment by glenn-jocher** [comment]
Hey there! 😊 

Great to hear that part of the solution worked well for you. It sounds like you're making good progress. The behavior you're observing with the `cfg` argument and DDP might indeed point to how configurations are managed in distributed training. Your thought on the potential override happening in a DDP setting is quite insightful.

If and when you find a fix or further insights, feel free to share your findings or contribution through a PR. We appreciate your involvement and look forward to any future updates from you.

Happy coding, and best of luck with your project! 👍
