### ISSUE TITLE
cuDNN error: RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR: Check and Set the CUDNN_ATTR_TENSOR_STRIDES Correctly cudnn_status: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by zldrobit** [ultralytics/ultralytics#885]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I encountered this bug when I run the following minimal reproducible example on both 2080 Ti and A100 80GB PCIE. The program exited with the message 
```
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR: Check and Set the CUDNN_ATTR_TENSOR_STRIDES Correctly cudnn_status: CUDNN_STATUS_BAD_PARAM
```

<details>
<summary> The full output message </summary>

```
root@utdnn-NF5280M5:/workspace/yolov8# python teste.py                                                                                   
Ultralytics YOLOv8.0.30 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (NVIDIA A100 80GB PCIe, 81085MiB)                                     
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs                                                         
                                                                                                                                         
Traceback (most recent call last):                                                                                                       
  File "teste.py", line 10, in <module>                                                                                                  
    result = model.predict(source=img)                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 147, in predict                                   
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)                         
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context                                
    return func(*args, **kwargs)                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 114, in __call__                              
    return list(self.stream_inference(source, model))  # merge list of Result into one                                                   
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 165, in stream_inference                      
    preds = self.model(im, augment=self.args.augment, visualize=visualize)                                                               
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                     
    return forward_call(*input, **kwargs)                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/autobackend.py", line 264, in forward                                      
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)                                 
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                     
    return forward_call(*input, **kwargs)                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 198, in forward                                            
    return self._forward_once(x, profile, visualize)  # single-scale inference, train                                                    
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 57, in _forward_once                                       
    x = m(x)  # run                                                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                     
    return forward_call(*input, **kwargs)                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/modules.py", line 37, in forward_fuse                                      
    return self.act(self.conv(x))                                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                     
    return forward_call(*input, **kwargs)                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 463, in forward                                           
    return self._conv_forward(input, self.weight, self.bias)                                                                             
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward                                     
    return F.conv2d(input, weight, bias, self.stride,                                                                                    
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR: Check and Set the CUDNN_ATTR_TENSOR_STRIDES Correctly cudnn_status: CUDNN_STATUS_BAD_PARAM
```

</details>

I could see the cuDNN version shipped with PyTorch by `print(torch.backends.cudnn.version())` is 8.5.0. I guess this is a bug with cuDNN 8.5.0, because it disappears when I uncomment the line `# torch.backends.cudnn.enabled = False` or use PyTorch 1.31.1 with CUDA 11.6 + cuDNN 8.3.2. Since colab at the moment does not support CUDA 11.7, the minimal reproducible example can only be used in a local environment.

### Environment

- YOLO: Ultralytics YOLOv8.0.30 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (NVIDIA A100 80GB PCIe, 81085MiB
- OS:  Ubuntu 20.04.5
- Python: 3.8.10
- CUDA: 11.7
- CuDNN: 8.5.0

### Minimal Reproducible Example

```
import cv2
from ultralytics import YOLO                                 
import torch                                                 

# torch.backends.cudnn.enabled = False                         
model = YOLO('yolov8n.pt')                                   
img=cv2.imread('zidane.jpg')
result = model.predict(source=img)                       
```

### Additional

I noticed that the docker image of ultralytics 8.0.30 from docker hub consists of PyTorch 1.13.1 with CUDA 11.6 + cuDNN 8.3.2, and running the above example using this image does not incur the error.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zldrobit thanks for the bug report! We train often on our A100 server but always inside our Docker image. We just updated the Docker image to start `FROM pytorch/pytorch:latest` instead of `FROM docker.io/pytorch/pytorch:latest`, which reduced the size from 10GB to 5GB and by default now uses stable torch releases instead of nightly builds, so I would recommend using our latest Docker for all DDP or high performance GPU trainings like A100 trainings.
