### ISSUE TITLE
Export exception

### ISSUE THREAD

**Issue by ivanstepanovftw** [ultralytics/ultralytics#8902]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Environment: Google Colab
Command:
```
cd dataset \
  && yolo export model=runs/detect/train/weights/best.pt format=tflite int8=True
```
Output:
```
Ultralytics YOLOv8.1.27 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.30GHz)
YOLOv0 summary (fused): 193 layers, 828342 parameters, 0 gradients, 4.6 GFLOPs

PyTorch: starting from 'runs/detect/train/weights/best.pt' with input shape (1, 3, 256, 256) BCHW and output shape(s) (1, 6, 1344) (1.9 MB)
2024-03-12 23:54:00.516057: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-12 23:54:00.516117: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-12 23:54:00.517631: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
requirements: Ultralytics requirements ['onnx>=1.12.0', 'onnx2tf>=1.15.4,<=1.17.5', 'sng4onnx>=1.0.1', 'onnxsim>=0.4.33', 'onnx_graphsurgeon>=0.3.26', 'tflite_support', 'onnxruntime'] not found, attempting AutoUpdate...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Collecting onnx>=1.12.0
  Downloading onnx-1.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 79.4 MB/s eta 0:00:00
Collecting onnx2tf<=1.17.5,>=1.15.4
  Downloading onnx2tf-1.17.5-py3-none-any.whl (400 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 279.1 MB/s eta 0:00:00
Collecting sng4onnx>=1.0.1
  Downloading sng4onnx-1.0.1-py3-none-any.whl (5.8 kB)
Collecting onnxsim>=0.4.33
  Downloading onnxsim-0.4.36-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 285.2 MB/s eta 0:00:00
Collecting onnx_graphsurgeon>=0.3.26
  Downloading https://developer.download.nvidia.com/compute/redist/onnx-graphsurgeon/onnx_graphsurgeon-0.3.27-py2.py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 kB 242.9 MB/s eta 0:00:00
Collecting tflite_support
  Downloading tflite_support-0.4.4-cp310-cp310-manylinux2014_x86_64.whl (60.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 MB 44.1 MB/s eta 0:00:00
Collecting onnxruntime
  Downloading onnxruntime-1.17.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 27.8 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from onnx>=1.12.0) (1.25.2)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx>=1.12.0) (3.20.3)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from onnxsim>=0.4.33) (13.7.1)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tflite_support) (1.4.0)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tflite_support) (24.3.6)
Collecting sounddevice>=0.4.4 (from tflite_support)
  Downloading sounddevice-0.4.6-py3-none-any.whl (31 kB)
Collecting pybind11>=2.6.0 (from tflite_support)
  Downloading pybind11-2.11.1-py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.7/227.7 kB 57.1 MB/s eta 0:00:00
Collecting coloredlogs (from onnxruntime)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 158.0 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (1.12)
Requirement already satisfied: CFFI>=1.0 in /usr/local/lib/python3.10/dist-packages (from sounddevice>=0.4.4->tflite_support) (1.16.0)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 176.8 MB/s eta 0:00:00
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->onnxsim>=0.4.33) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->onnxsim>=0.4.33) (2.16.1)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime) (1.3.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from CFFI>=1.0->sounddevice>=0.4.4->tflite_support) (2.21)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->onnxsim>=0.4.33) (0.1.2)
Installing collected packages: sng4onnx, pybind11, onnx2tf, onnx, humanfriendly, sounddevice, onnx_graphsurgeon, coloredlogs, tflite_support, onnxsim, onnxruntime
Successfully installed coloredlogs-15.0.1 humanfriendly-10.0 onnx-1.15.0 onnx2tf-1.17.5 onnx_graphsurgeon-0.3.27 onnxruntime-1.17.1 onnxsim-0.4.36 pybind11-2.11.1 sng4onnx-1.0.1 sounddevice-0.4.6 tflite_support-0.4.4

requirements: AutoUpdate success ✅ 17.4s, installed 7 packages: ['onnx>=1.12.0', 'onnx2tf>=1.15.4,<=1.17.5', 'sng4onnx>=1.0.1', 'onnxsim>=0.4.33', 'onnx_graphsurgeon>=0.3.26', 'tflite_support', 'onnxruntime']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


TensorFlow SavedModel: starting export with tensorflow 2.15.0...
WARNING ⚠️ tensorflow<=2.13.1 is required, but tensorflow==2.15.0 is currently installed https://github.com/ultralytics/ultralytics/issues/5161
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100% 1.11M/1.11M [00:00<00:00, 22.1MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /content/dataset/calibration_image_sample_data_20x128x128x3_float32.npy...: 100% 1/1 [00:00<00:00, 41.55file/s]

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 0.9s, saved as 'runs/detect/train/weights/best.onnx' (3.3 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: module 'onnx' has no attribute '_serialize'
2024-03-12 23:54:21.797607: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
saved_model output started ==========================================================
saved_model output complete!
Summary on the non-converted ops:
---------------------------------
 * Accepted dialects: tfl, builtin, func
 * Non-Converted Ops: 172, Total Ops 448, % non-converted = 38.39 %
 * 172 ARITH ops

- arith.constant:  172 occurrences  (f32: 155, i32: 17)



  (f32: 9)
  (f32: 18)
  (f32: 76)
  (f32: 70)
  (f32: 3)
  (f32: 71)
  (f32: 7)
  (f32: 6)
  (f32: 2)
  (f32: 1)
  (f32: 4)
  (f32: 2)
  (f32: 4)
Float32 tflite output complete!
Summary on the non-converted ops:
---------------------------------
 * Accepted dialects: tfl, builtin, func
 * Non-Converted Ops: 172, Total Ops 603, % non-converted = 28.52 %
 * 172 ARITH ops

- arith.constant:  172 occurrences  (f16: 155, i32: 17)



  (f32: 9)
  (f32: 18)
  (f32: 76)
  (f32: 155)
  (f32: 70)
  (f32: 3)
  (f32: 71)
  (f32: 7)
  (f32: 6)
  (f32: 2)
  (f32: 1)
  (f32: 4)
  (f32: 2)
  (f32: 4)
Float16 tflite output complete!
Input signature information for quantization
signature_name: serving_default
input_name.0: images shape: (1, 256, 256, 3) dtype: <dtype: 'float32'>
Summary on the non-converted ops:
---------------------------------
 * Accepted dialects: tfl, builtin, func
 * Non-Converted Ops: 104, Total Ops 448, % non-converted = 23.21 %
 * 104 ARITH ops

- arith.constant:  104 occurrences  (f32: 87, i32: 17)



  (f32: 9)
  (f32: 18)
  (f32: 76)
  (f32: 70)
  (f32: 3)
  (f32: 71)
  (f32: 7)
  (uq_8: 68)
  (f32: 6)
  (f32: 2)
  (f32: 1)
  (f32: 4)
  (f32: 2)
  (f32: 4)
Dynamic Range Quantization tflite output complete!
Summary on the non-converted ops:
---------------------------------
 * Accepted dialects: tfl, builtin, func
 * Non-Converted Ops: 172, Total Ops 448, % non-converted = 38.39 %
 * 172 ARITH ops

- arith.constant:  172 occurrences  (f32: 155, i32: 17)



  (f32: 9)
  (f32: 18)
  (f32: 76)
  (f32: 70)
  (f32: 3)
  (f32: 71)
  (f32: 7)
  (f32: 6)
  (f32: 2)
  (f32: 1)
  (f32: 4)
  (f32: 2)
  (f32: 4)
fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
INT8 Quantization tflite output complete!
Summary on the non-converted ops:
---------------------------------
 * Accepted dialects: tfl, builtin, func
 * Non-Converted Ops: 172, Total Ops 448, % non-converted = 38.39 %
 * 172 ARITH ops

- arith.constant:  172 occurrences  (f32: 155, i32: 17)



  (f32: 9)
  (f32: 18)
  (f32: 76)
  (f32: 70)
  (f32: 3)
  (f32: 71)
  (f32: 7)
  (f32: 6)
  (f32: 2)
  (f32: 1)
  (f32: 4)
  (f32: 2)
  (f32: 4)
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
Full INT8 Quantization tflite output complete!
Summary on the non-converted ops:
---------------------------------
 * Accepted dialects: tfl, builtin, func
 * Non-Converted Ops: 172, Total Ops 448, % non-converted = 38.39 %
 * 172 ARITH ops

- arith.constant:  172 occurrences  (f32: 155, i32: 17)



  (f32: 9)
  (f32: 18)
  (f32: 76)
  (f32: 70)
  (f32: 3)
  (f32: 71)
  (f32: 7)
  (f32: 6)
  (f32: 2)
  (f32: 1)
  (f32: 4)
  (f32: 2)
  (f32: 4)
INT8 Quantization with int16 activations tflite output complete!
Summary on the non-converted ops:
---------------------------------
 * Accepted dialects: tfl, builtin, func
 * Non-Converted Ops: 172, Total Ops 448, % non-converted = 38.39 %
 * 172 ARITH ops

- arith.constant:  172 occurrences  (f32: 155, i32: 17)



  (f32: 9)
  (f32: 18)
  (f32: 76)
  (f32: 70)
  (f32: 3)
  (f32: 71)
  (f32: 7)
  (f32: 6)
  (f32: 2)
  (f32: 1)
  (f32: 4)
  (f32: 2)
  (f32: 4)
Full INT8 Quantization with int16 activations tflite output complete!
TensorFlow SavedModel: export failure ❌ 117.6s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 588, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 294, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 138, in outer_func
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 133, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 820, in export_saved_model
    f.unlink() if "quant_with_int16_act.tflite" in str(f) else self._add_tflite_metadata(file)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 933, in _add_tflite_metadata
    from tflite_support import flatbuffers  # noqa
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/__init__.py", line 53, in <module>
    from tflite_support import task
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/__init__.py", line 32, in <module>
    from . import vision
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/vision/__init__.py", line 20, in <module>
    from tensorflow_lite_support.python.task.vision import image_classifier
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/image_classifier.py", line 23, in <module>
    from tensorflow_lite_support.python.task.vision.core import tensor_image
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py", line 19, in <module>
    from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ivanstepanovftw** [comment]
WARNING ⚠️ tensorflow<=2.13.1 is required, but tensorflow==2.15.0 is currently installed https://github.com/ultralytics/ultralytics/issues/5161
