### ISSUE TITLE
Gradient calculation during prediction in custom trained YOLOv8 for objection detection task

### ISSUE THREAD

**Issue by UttamToni** [ultralytics/ultralytics#8904]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to  calculate the gradient in my custom trained yolov8s model for creating adversarial image, but facing the following error. Can anyone suggest me what is the issue and how to solve this.
( I am new in pytorch and Autograd )

Code :
import torch
import torchvision.transforms as transforms
from PIL import Image
import torch.nn as nn

#‘pretrained_model’ is custom trained YOLOv8s model
model = YOLO(‘/content/gdrive/MyDrive/yolo/detect/train/weights/best.pt’)

image = Image.open(‘/content/gdrive/MyDrive/yolo/datasets/Insulator-Defect-5/test/images/130113v.jpg’).convert(‘RGB’)
transform = transforms.Compose([
transforms.Resize((640, 640)),
transforms.ToTensor(),
])
image = transform(image)
image = image.unsqueeze(0)
image.requires_grad = True

result = model.predict(image)
result=result[0].boxes
cls_id = result.cls
confidence = result.conf

class_mapping = {‘broken’: 0, ‘insulator’: 1, ‘pollution-flashover’: 2}
label_str = ‘broken’ # Change this based on the actual class label
label = torch.tensor([class_mapping[label_str]])
label.requires_grad = False

criterion = nn.CrossEntropyLoss()
loss = criterion(cls_id.unsqueeze(0), label)

#Backward pass to get the gradient
model.zero_grad()
loss.backward()
data_grad = image.grad.data

Error:
RuntimeError Traceback (most recent call last)
in <cell line: 3>()
1 # Backward pass to get the gradient
2 model.zero_grad()
----> 3 loss.backward()
4 data_grad = image.grad.data

1 frames
/usr/local/lib/python3.10/dist-packages/torch/autograd/init.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
249 # some Python versions print out the first line of a multi-line function
250 # calls in the traceback and some print out the last line
→ 251 Variable.execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
252 tensors,
253 grad_tensors,

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

I also test (cls_id.grad_fn ) , it also returns ( none ).  What to do now?

**Comment by glenn-jocher** [comment]
@UttamToni hello! It looks like you're encountering an issue because the model's output doesn't have `grad_fn` attached, which is necessary for computing gradients. This typically happens because the model or part of it is not in training mode or because certain operations that do not support gradient computation are used.

For calculating gradients with respect to the input image (useful for generating adversarial examples), ensure the following:

1. **Model in Evaluation Mode with Gradient Tracking**: Even though we usually use `.eval()` for inference to disable dropout and batch normalization effects, you'll need to ensure that gradients can still flow back through the model for your purpose. You can achieve this by wrapping the prediction in a `with torch.enable_grad():` block.

2. **Loss Function**: Ensure the loss function is appropriate for the task and the model's output. For object detection models like YOLO, using `CrossEntropyLoss` directly on the outputs might not be straightforward due to the multi-task nature (classification, objectness, and bounding box regression). You might need a custom approach depending on what aspect you're focusing on (e.g., adversarial perturbations targeting classification).

Here's a modified snippet to illustrate enabling gradient computation:

```python
import torch
from ultralytics import YOLO

# Load your model
model = YOLO('/content/gdrive/MyDrive/yolo/detect/train/weights/best.pt').eval()

# Ensure gradients are enabled for inference
with torch.enable_grad():
    image = # your preprocessed image tensor with image.requires_grad_(True)
    result = model.predict(image)
    # Assuming you're focusing on a specific task, compute your loss here
    # loss = your_custom_loss_computation(result)
    # Backpropagate
    # loss.backward()
    # data_grad = image.grad.data
```

Remember, for adversarial example generation, you'll need to define a clear objective (loss) that you want to optimize against. Since YOLO outputs are complex (combining class scores, objectness, and bounding boxes), you'll need a tailored approach depending on whether you're targeting the classifier, the objectness score, or something else.

I hope this helps! Let me know if you have further questions. 😊

**Comment by UttamToni** [comment]
many thanks @glenn-jocher for your reply.
Though my previous error has solved by using ```loss.requires_grad = True``` before ```loss.backward()``` . The rest of the code was same .
But got another error in my next line of code. Here is the error:
AttributeError                            Traceback (most recent call last)
[<ipython-input-86-53c6bd0bb63b>](https://localhost:8080/#) in <cell line: 6>()

     19   model.zero_grad()
     20   loss.requires_grad = True
     21   loss.backward()
---> 22   data_grad = image.grad.data
     23 
     24 # print(result)

AttributeError: 'NoneType' object has no attribute 'data'

Let me know you that, I have also your method :
with torch.enable_grad():
   --- rest of the code
But still same error: AttributeError: 'NoneType' object has no attribute 'data'

Please give me suggestion.

**Comment by glenn-jocher** [comment]
@UttamToni hey there! 😊 It's great to hear that you've made progress with your previous error. Regarding the new issue you're encountering, it seems like the gradient for the image is not being computed, which is why you're seeing `None` when trying to access `image.grad.data`.

This usually happens when `requires_grad` is not set to `True` for your input image. Ensure you enable gradients for the image before passing it through the model like so:

```python
image.requires_grad_(True)
```

Regarding your second question, using `model.eval()` indeed sets the model to evaluation mode, which is intended for inference and not training. It doesn't start training but prepares the model for evaluation by turning off specific layers like dropout and batch normalization that behave differently during training. If it seems like it's "training," it might be due to some misunderstanding or misinterpretation of the model's behavior in this mode. Rest assured, `model.eval()` is for evaluation purposes only. 

Keep exploring and happy coding! If you have more questions, feel free to ask.

**Comment by UttamToni** [comment]
Again thanks @glenn-jocher .
As i have provided my code above , i have used ```image.requires_grad = True``` 
However i have used your method ```image.requires_grad_(True)``` also and the ```print(image)``` gives me the following output:
tensor([[[[0.8431, 0.8706, 0.8667,  ..., 0.4353, 0.4039, 0.5490],
          [0.8118, 0.8627, 0.8941,  ..., 0.4980, 0.4863, 0.5843],
          [0.7843, 0.8471, 0.9216,  ..., 0.5333, 0.5608, 0.6118],
          ...,
          [0.5961, 0.4941, 0.6471,  ..., 0.4706, 0.3922, 0.3294],
          [0.5647, 0.4275, 0.5333,  ..., 0.4549, 0.4431, 0.3608],
          [0.5020, 0.4549, 0.5255,  ..., 0.4706, 0.5020, 0.4118]],

         [[0.8549, 0.8902, 0.9020,  ..., 0.5882, 0.5569, 0.7020],
          [0.8235, 0.8824, 0.9294,  ..., 0.6510, 0.6392, 0.7373],
          [0.7961, 0.8667, 0.9569,  ..., 0.6863, 0.7137, 0.7647],
          ...,
          [0.5843, 0.4863, 0.6549,  ..., 0.4863, 0.4078, 0.3490],
          [0.4941, 0.3725, 0.4941,  ..., 0.4706, 0.4588, 0.3765],
          [0.4078, 0.3686, 0.4588,  ..., 0.4863, 0.5176, 0.4275]],

         [[0.8902, 0.9137, 0.9216,  ..., 0.4118, 0.3804, 0.5255],
          [0.8588, 0.9059, 0.9490,  ..., 0.4745, 0.4627, 0.5608],
          [0.8314, 0.8902, 0.9765,  ..., 0.5137, 0.5412, 0.5922],
          ...,
          [0.5255, 0.4275, 0.6000,  ..., 0.4824, 0.4039, 0.3333],
          [0.4471, 0.3294, 0.4549,  ..., 0.4745, 0.4627, 0.3725],
          [0.3686, 0.3255, 0.4275,  ..., 0.4980, 0.5216, 0.4314]]]], requires_grad=True)
          which shows that requires_grad = True
          
          But still i am getting the same error: 
          ---> 22 data_grad = image.grad.data
                  AttributeError: 'NoneType' object has no attribute 'data'
                  
 What should i do now?

**Comment by UttamToni** [comment]
@glenn-jocher  can you provide me code for loss calculation in my case ?

**Comment by glenn-jocher** [comment]
@UttamToni Sure, happy to help! 😊 For creating adversarial images targeting object detection tasks like yours, a common approach is to focus on perturbing the image such that the confidence of the correct class decreases. Since YOLO outputs are complex (combining bounding boxes, objectness scores, and class predictions), crafting an adversarial loss function requires a bit of creativity.

Here's a simplified example focusing on decreasing the confidence score of detected objects. This example assumes you have access to the model's output format and can extract the necessary information (e.g., confidence scores):

```python
import torch

# Assuming 'results' is the output from your YOLO model's prediction
# And you've extracted the confidence scores for your objects
confidences = results[0].boxes.conf  # Tensor of confidence scores

# Target is to minimize these confidence scores
# A simple approach is to maximize the negative of average confidence scores
loss = -confidences.mean()

# Backward pass
loss.backward()
```

This is a very basic example. In practice, you might want to focus on specific classes or incorporate more sophisticated adversarial techniques. Remember, the key is to define a loss that captures your adversarial goal (e.g., misclassification, reducing detection confidence) and use it to generate the gradient for crafting your adversarial image.

Hope this helps! Let me know if you have more questions.

**Comment by UttamToni** [comment]
sorry to interrupt @glenn-jocher , you haven't answer my previous comment question. 
I am getting this error :  
      ---> 22 data_grad = image.grad.data
              AttributeError: 'NoneType' object has no attribute 'data'
          
please have a loop to my previous comment and give me suggestion.

Thanks for the idea of loss Function.

**Comment by glenn-jocher** [comment]
@UttamToni hey there! 😊 No worries about the interruption; I'm here to help!

Regarding the error you're encountering, it seems like the gradient for your image isn't being computed, which is why `image.grad` is `None`. This usually happens if the operations leading up to the loss calculation don't support gradient computation or if the loss itself isn't connected to the image through a computational graph that requires gradients.

To ensure gradients are properly computed and attached to your image tensor, make sure:
1. `image.requires_grad` is set to `True` before passing it through the model.
2. The operations and loss function used are differentiable and properly connected to the image tensor.

Here's a quick check you can do:
```python
if image.grad is not None:
    data_grad = image.grad.data
else:
    print("Gradient not computed. Check the computational graph!")
```

If you're still facing issues, revisiting the loss function calculation and ensuring it's directly related to the image tensor might help. Feel free to share more details if you need further assistance!

And I'm glad you found the loss function idea helpful! Let me know if there's anything else I can do for you.

**Comment by UttamToni** [comment]
Thanks @glenn-jocher for quick reply. 
i have already used ```model.train()``` and then ```image.requires_grad_(True)``` and  ```image.retain_grad_(True)``` But still get the same AttributeError . 

I have just read the post of github : Calculating Gradients w.r.t to Loss #1693
Where you told that , "calculating gradient of input image w.r.t. loss is not possible by default. As  the Ultralytics YOLOv8 does not support preserving gradients for outputs (like bounding boxes) during inference because it's set to inference mode by default. It's a little complex to manually set requires_grad = True or adjust the model to keep gradients during prediction in the current architecture because it's intentionally designed that way for performance reason ."

Isn't this post's case and my case are same? 
if same then what should i do for calculating gradient of my input image w.r.t. loss? As deep dive into the yolov8 code and manually change it is a complex task.

I have another query , is this issue arise for using pytorch model? If i use tensorflow_saved_model format would this issue mitigate? Suppose if i use tape_gradient() method to calculate the gradient

**Comment by UttamToni** [comment]
Thanks @glenn-jocher for your inspiration.
I want to dive deep into the model network and make the necessary changes to calculate the gradient for my input image. 

please guide me in the model network which parts of the code should i change and how to do that.  As i am a beginer please guide me to the point in while file should i go and what changes should be done manually to calculate gradient of my input image w.r.t loss

**Comment by glenn-jocher** [comment]
Hey @UttamToni! 😄 Kudos on taking the initiative to dive deeper into the model architecture! Since you're interested in calculating gradients with respect to the input image for your YOLOv8 model, you're entering an exciting area of exploration.

For modifying the YOLOv8 model to retain gradients, you'll primarily be working within the forward pass of the model. While the exact file and line numbers can change with updates to the repository, you'll want to start your journey by looking into the model definition files, typically `models/yolo.py` or any script where the model's forward method is defined.

Here’s a simplified approach to get you started:
1. **Ensure `requires_grad` is True**: As you already know, make sure your input tensor has `requires_grad` set to `True`.
   ```python
   input_image.requires_grad_(True)
   ```
2. **Modify Forward Pass**: In the forward pass, ensure you're applying operations that PyTorch recognizes as requiring gradients. This might not require changes if your operations already support them.
3. **Inspect Gradients Post Backward**: After calling `.backward()` on your loss, check the gradients w.r.t the input image.
   ```python
   loss.backward()  # Backpropagation
   print(input_image.grad)  # Inspect gradients
   ```

🧐 Keep in mind that the ability to retain and manipulate gradients at the input level might require a deeper understanding of PyTorch's autograd system and how it interfaces with custom model architectures. Since YOLOv8 is optimized for inference, enabling training mode using `model.train()` can also be a crucial step for ensuring gradient computations are not inadvertently disabled by optimization layers.

🔍 Additionally, considering your beginner status, I highly recommend reviewing the PyTorch documentation on "Autograd: Automatic Differentiation" (https://pytorch.org/docs/stable/autograd.html) to gain a more solid understanding of how gradients are handled within the framework.

🛠 Due to the complexity of the task and the potential for missteps without a deep understanding of the model and PyTorch, proceed with caution. Experimenting in smaller steps and testing your understanding as you go can be a great way to learn efficiently.

🌟 You're on an exciting path, and digging into the internals of such models can be incredibly rewarding. Good luck, and don't hesitate to reach out to the community as you make progress! Happy coding!

**Comment by UttamToni** [comment]
@glenn-jocher  many many thanks to your support.
I just found yolov9 has released with PGI capability. 
As you already know my goal to calculate gradient of my input image w.r.t. the loss to make adversarial attacks . is it will be feasible to use yolov9 model for purpose ? 
Can i achieve my goal without diving deep into the model's internal network code using yolov9?

if it is possible , please suggest me the code lines how to do that. I am really stuck in my thesis work for this calculating gradient issue.

**Comment by glenn-jocher** [comment]
Hey @UttamToni! 🌟 You're welcome, I'm glad to help!

Yes, YOLOv9 introduces some exciting enhancements including PGI (Programmable Gradient Information), which might indeed make tasks like calculating gradients for adversarial image generation more feasible straight out of the box compared to previous versions.

For your specific goal of calculating gradients w.r.t. the loss to craft adversarial attacks, YOLOv9 may offer some advantages. However, even with YOLOv9, ensuring that gradients are retained for the input image and can be manipulated as desired will still require some level of engagement with the model's forward pass and possibly the loss calculation process.

While I don't have a direct snippet to provide that specifically addresses your use case with YOLOv9, a general approach would still involve:

1. Setting `requires_grad` to `True` for your input image.
2. Passing your image through the model and obtaining the loss based on your objective (misclassification, diminished confidence, etc.).
3. Using `.backward()` to calculate gradients.
4. Checking `input_image.grad` for the computed gradients.

```
input_image.requires_grad_(True)
output = model(input_image)
loss = some_loss_function(output)  # Define based on your objective
loss.backward()
print(input_image.grad)  # Should contain the gradients now
```

Remember, the precise steps and effectiveness can vary based on your implementation, and you might still need to experiment with YOLOv9's specific features and configurations to tailor the process to your needs.

I hope this provides a bit of guidance for moving forward with your thesis work! 📚 Keep exploring and experimenting; you're working on something really interesting.

**Comment by UttamToni** [comment]
@glenn-jocher Thanks for you support for long time.
i was trying @MaxH1996 's approach in #1693 to calculate the loss using v8DetectionLoss function.

This is my code:
```
from ultralytics.utils.loss import v8DetectionLoss
from ultralytics import YOLO
from ultralytics.models.yolo.detect.train import DetectionTrainer
from ultralytics.data import build_dataloader
from ultralytics.data import build_yolo_dataset

trainer = DetectionTrainer('/content/gdrive/MyDrive/yolo/runs/detect/train/args.yaml')
trainer.setup_model()
trainer.set_model_attributes()

loader = build_yolo_dataset('/content/gdrive/MyDrive/yolo/datasets/Insulator-Defect-5/test/images', 1, '/content/gdrive/MyDrive/yolo/datasets/Insulator-Defect-5/data.yaml', 32)

batch = next(iter(loader[0]))
a = trainer.model(batch['img'])
loss_fn = v8DetectionLoss(trainer.model)
loss, _ = loss_fn(a, batch)
```
@MaxH1996 in #1693 uses ```v5loader.create_dataloader()``` class but as upgraded ultralytics does not have this class . i found that DetectionTrainer class uses ```build_yolo_dataset``` function ,thats why i use ```build_yolo_dataset``` to pass the images for which i want to calculate loss.
But got this error:
error:
![image](https://github.com/ultralytics/ultralytics/assets/162920278/2196133c-74a5-44f0-bc5c-da44d5b87b07)
but my args.yaml file which is passed to the DetectionTrainer has the imgsz key.

I may have used wrong function or wrong approach for data loader. can you please suggest me how to use a data loader to pass the images to the DetectionTrainer like @MaxH1996 for which i want to calculate loss. As there is no ```v5loader. create_dataloader()``` in the upgraded ultralytics. How can i create a dataloder in upgraded ultralytics for my case and eccess batch['img'] ?
Please help its urgent

**Comment by UttamToni** [comment]
many many thanks to @glenn-jocher and @MaxH1996 for their help .
I have successfully calculate the gradient of image w.r.t the loss.
It was impossible without you guys.

After my thesis I will share my method here for all who have faced difficulties .
thanks again.

**Comment by glenn-jocher** [comment]
@UttamToni hey there! 😊 We're thrilled to hear about your success in calculating the gradient of the image with respect to the loss - fantastic job! Your appreciation means a lot to us, and it's wonderful to know that our assistance played a part in your achievement. 

We're looking forward to seeing your method shared here; it'll definitely be valuable to many others facing similar challenges. Wishing you all the best with your thesis, and again, don't hesitate to reach out if you need more help. Keep up the great work!

**Comment by MindSystemm** [comment]
Hello @UttamToni , any email I could contact you please?

**Comment by lukasmelis** [comment]
Hello @UttamToni and @MindSystemm, is there a way you could help me with solving same problem?

**Comment by majiaqi669** [comment]
hello @UttamToni can you teach me how to solve this problem?

**Comment by schangze** [comment]
is it closed?
I've encountered a similar problem. As hardware insufficient, I need to set batch to 7, which could not get good result as cpu training. But I don't know how to enable GA during training, 
   `ep = 200
    max_bat = 7
    accum = ep // max_bat
    haze_model.train(data=data_yaml, epochs=ep, imgsz=[1280,854], batch=max_bat, accumate=accum)`
    this doesn't work.

**Comment by glenn-jocher** [comment]
Hi @schangze,

Thanks for reaching out! To better assist you, could you please provide a minimum reproducible example of your issue? This will help us diagnose the problem more effectively. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure you are using the latest versions of all relevant packages, as updates often resolve existing issues.

Regarding your code snippet, it looks like there might be a typo in the `accumulate` parameter. It should be `accumulate` instead of `accumate`. Here’s a corrected version:

```python
ep = 200
max_bat = 7
accum = ep // max_bat
haze_model.train(data=data_yaml, epochs=ep, imgsz=[1280, 854], batch=max_bat, accumulate=accum)
```

This should enable gradient accumulation during training. Let us know if this resolves your issue or if you need further assistance!

**Comment by schangze** [comment]
yeah!
I tried the code `haze_model.train(data=data_yaml, epochs=ep, imgsz=[1280, 854], batch=max_bat, accumulate=accum)` before and it told me no such patameter like accumulate:
Exception has occurred: SyntaxError
'[31m[1maccumulate[0m' is not a valid YOLO argument. 

    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of {'obb', 'classify', 'segment', 'pose', 'detect'}
                MODE (required) is one of {'predict', 'benchmark', 'val', 'train', 'export', 'track'}
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco8.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco8.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    6. Explore your datasets using semantic search and SQL with a simple GUI powered by Ultralytics Explorer API
        yolo explorer

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
    
  File "C:\Users\shix7\OneDrive - Corning Incorporated\BoxMigratedPersonalShare\Desktop\MBO\ML\Preform Defect Machine Learning\ultralytics-main\ultralytics\haze_trainGPU - GradientAccumulation.py", line 80, in main
    haze_model.train(data=data_yaml, epochs=ep, imgsz=[1280,854], batch=max_bat, accumulate=accum)
  File "C:\Users\shix7\OneDrive - Corning Incorporated\BoxMigratedPersonalShare\Desktop\MBO\ML\Preform Defect Machine Learning\ultralytics-main\ultralytics\haze_trainGPU - GradientAccumulation.py", line 88, in <module>
    main()

And screenshot of main code where the error occured:
![image](https://github.com/ultralytics/ultralytics/assets/173241622/fce7a2c4-e29c-427f-b2fb-15141b0ca261)

**Comment by glenn-jocher** [comment]
Hi @schangze,

Thank you for sharing the details and the screenshot! It looks like there's a small typo in the argument name. The correct parameter is `accumulate`, not `accumate`. Here's how you can modify your code:

```python
ep = 200
max_bat = 7
accum = ep // max_bat
haze_model.train(data=data_yaml, epochs=ep, imgsz=[1280, 854], batch=max_bat, accumulate=accum)
```

If you still encounter issues, please ensure you are using the latest version of the Ultralytics package, as updates often resolve such discrepancies. You can update the package using:

```bash
pip install --upgrade ultralytics
```

If the issue persists, providing a minimum reproducible example would be very helpful for further diagnosis. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance! 😊

**Comment by schangze** [comment]
hi @glenn-jocher：
Thank you for your reply.
Well, as you can see the code I pasted, the parameter name I type is right. and the thrown error is _SyntaxError: '[31m[1maccumulate[0m' is not a valid YOLO argument. _, which means accumulate is not recognized as a valid parameter for model training in YOLOv8.
My problem still exists. Anyone else encountered this before could help me out. Thanks!

**Comment by glenn-jocher** [comment]
Hi @schangze,

Thank you for the follow-up! It appears that the `accumulate` parameter might not be recognized in your current setup. Let's ensure you're using the latest version of the Ultralytics package, as updates often resolve such issues. You can update the package with:

```bash
pip install --upgrade ultralytics
```

If the problem persists, please provide a minimum reproducible example to help us diagnose the issue more effectively. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, you can try an alternative approach to gradient accumulation by manually adjusting the gradient accumulation steps in your training loop. Here's an example:

```python
ep = 200
max_bat = 7
accum = ep // max_bat

for epoch in range(ep):
    for i, (images, targets) in enumerate(dataloader):
        outputs = model(images)
        loss = criterion(outputs, targets)
        loss.backward()
        
        if (i + 1) % accum == 0:
            optimizer.step()
            optimizer.zero_grad()
```

This approach manually accumulates gradients and updates the optimizer every `accum` steps.

Feel free to reach out if you have any more questions or need further assistance! 😊
