### ISSUE TITLE
Is there a method that can list all ultralytics original model name that can pass into YOLO to load a model?

### ISSUE THREAD

**Issue by stevezkw1998** [ultralytics/ultralytics#8931]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

For example, it should be something like 

```python
In [2]: YOLO.list_model()
Out[2]: ['yolov8n.pt', 'yolo-world']
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@stevezkw1998 hello! 😊

Currently, we don't have a built-in method like `YOLO.list_model()` to list all available Ultralytics original model names directly within the YOLO package. However, you can easily find a comprehensive list of supported models and their details on our [documentation page](https://docs.ultralytics.com/models).

For quick reference, here are some of the key models you can load with YOLO:
- `yolov8n.pt`
- `yolov8s.pt`
- `yolov8m.pt`
- `yolov8l.pt`
- `yolov8x.pt`
- `yolov8n6.pt`
- `yolov8s6.pt`
- `yolov8m6.pt`
- `yolov8l6.pt`
- `yolov8x6.pt`
- `yolov8n-seg.pt`
- `yolov8n-pose.pt`
- `yolov8n-cls.pt`

For loading a model, you can use:
```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt')  # Just replace 'yolov8n.pt' with your model of choice
```

Hope this helps! If you have any more questions or need further assistance, feel free to ask.

**Comment by stevezkw1998** [comment]
Hi @glenn-jocher thanks for your response, I just implemented a humble one for that in python:
```python
YOLOV5_DETECTION = [
    "yolov5nu.pt",
    "yolov5su.pt",
    "yolov5mu.pt",
    "yolov5lu.pt",
    "yolov5xu.pt",
    "yolov5n6u.pt",
    "yolov5s6u.pt",
    "yolov5m6u.pt",
    "yolov5l6u.pt",
    "yolov5x6u.pt",
]

YOLOV8_DETECTION_BASIC = [
    "yolov8n.pt",
    "yolov8s.pt",
    "yolov8m.pt",
    "yolov8l.pt",
    "yolov8x.pt",
]
YOLOV8_DETECTION_EXT = [
    "yolov8n6.pt",
    "yolov8s6.pt",
    "yolov8m6.pt",
    "yolov8l6.pt",
    "yolov8x6.pt",
]
YOLOV8_DETECTION = YOLOV8_DETECTION_BASIC + YOLOV8_DETECTION_EXT
YOLOV8_POSE = [
    name.replace(".pt", "-pose.pt") for name in YOLOV8_DETECTION_BASIC
]
YOLOV8_SEG = [
    name.replace(".pt", "-seg.pt") for name in YOLOV8_DETECTION_BASIC
]
YOLOV8_OBB = [
    name.replace(".pt", "-obb.pt") for name in YOLOV8_DETECTION_BASIC
]
YOLOV8_CLS = [
    name.replace(".pt", "-cls.pt") for name in YOLOV8_DETECTION_BASIC
]
YOLO_WORLD_1 = [
    name.replace(".pt", "-world.pt") for name in YOLOV8_DETECTION_BASIC
]
YOLO_WORLD_2 = [
    name.replace(".pt", "-worldv2.pt") for name in YOLOV8_DETECTION_BASIC
]
YOLO_WORLD = YOLO_WORLD_1 + YOLO_WORLD_2

YOLO_DETECTION = YOLOV5_DETECTION + YOLOV8_DETECTION + YOLO_WORLD
YOLO_POSE = YOLOV8_POSE
YOLO_SEG = YOLOV8_SEG
YOLO_OBB = YOLOV8_OBB
YOLO_CLS = YOLOV8_CLS

YOLO_MODELS = YOLO_DETECTION + YOLO_POSE + YOLO_SEG + YOLO_OBB + YOLO_CLS
```
Hope this can help and spark some discussions.

**Comment by stevezkw1998** [comment]
Hi @glenn-jocher  a quick feedback for latest `ultralytics`
It seems that the model `yolov8n6.pt` you metioned can't be found in `YOLO` using **latest** `ultralytics`
I built up my `ultralytics` using your latest docker image.
```python
Traceback (most recent call last):
  File "/root/inference.py", line 47, in <module>
    model = YOLO(model_name)
  File "/usr/src/ultralytics/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 229, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 788, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 714, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'yolov8n6.pt'
```
