### ISSUE TITLE
YOLO V 8 :RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 0 for tensor number 1 in the list. Sentry is attempting to send 1 pending error messages

### ISSUE THREAD

**Issue by ihebchh** [ultralytics/ultralytics#897]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

/content
Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
yolo/engine/trainer: task=segment, mode=train, model=yolov8s-seg.yaml, data=/content/datasets/fish_segmentation-3/data.yaml, epochs=10, patience=50, batch=1, imgsz=480, save=True, cache=True, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.6, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs/segment/train31
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.Conv                  [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.C2f                   [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.C2f                   [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.C2f                   [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.C2f                   [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.C2f                   [768, 512, 1]                 
 22        [15, 18, 21]  1   2774027  ultralytics.nn.modules.Segment               [9, 32, 128, [128, 256, 512]] 
YOLOv8s-seg summary: 261 layers, 11793579 parameters, 11793563 gradients, 42.7 GFLOPs

Transferred 411/417 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.001), 76 bias
train: Scanning /content/datasets/fish_segmentation-3/train/labels.cache... 744 images, 0 backgrounds, 0 corrupt: 100% 744/744 [00:00<?, ?it/s]
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 743, len(boxes) = 744. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
train: Caching images (0.4GB True): 100% 744/744 [00:03<00:00, 236.14it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /content/datasets/fish_segmentation-3/valid/labels.cache... 402 images, 0 backgrounds, 0 corrupt: 100% 402/402 [00:00<?, ?it/s]
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 401, len(boxes) = 402. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
val: Caching images (0.2GB True): 100% 402/402 [00:03<00:00, 128.84it/s]
Image sizes 480 train, 480 val
Using 0 dataloader workers
Logging results to runs/segment/train31
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0% 0/744 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cfg/__init__.py", line 249, in entrypoint
    getattr(model, mode)(verbose=True, **overrides)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 207, in train
    self.trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 183, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 302, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/segment/train.py", line 44, in criterion
    return self.compute_loss(preds, batch)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/segment/train.py", line 85, in __call__
    targets = torch.cat((batch_idx, batch["cls"].view(-1, 1), batch["bboxes"]), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 0 for tensor number 1 in the list.
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

### Minimal Reproducible Example

!yolo task=segment mode=train model=yolov8s-seg.pt data="/content/datasets/fish_segmentation-3/data.yaml" epochs=10 imgsz=480  batch=1 cache=True

### Additional

help

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@ihebchh hi please check the warning message here:
```bash
WARNING warning Box and segment counts should be equal, but got len(segments) = 401, len(boxes) = 402. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
```
It'll remove all segment but keep boxes labels as you're using a mixed dataset. So the segment labels are removal then you are not able to train `segment`. Please clean up your mixed labels and make sure all of them are segment labels then try again. :)

**Comment by Lishumuzixin** [comment]
> @ihebchh hi please check the warning message here:
> 
> ```shell
> WARNING warning Box and segment counts should be equal, but got len(segments) = 401, len(boxes) = 402. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
> ```
> 
> It'll remove all segment but keep boxes labels as you're using a mixed dataset. So the segment labels are removal then you are not able to train `segment`. Please clean up your mixed labels and make sure all of them are segment labels then try again. :)

Hi, I'm new to the field of computer vision. I have also encountered this question, what do you mean by mixed dataset？

**Comment by glenn-jocher** [comment]
@Lishumuzixin hi there, 

A mixed dataset refers to a dataset in which some data points include both object detection information (bounding boxes) and segmentation information (pixel-level object depictions), while other data points include only one type of information. 

In your case, the software found that one data point has a bounding box, but no corresponding segment data, hence the unequal lengths (401 segments vs 402 boxes). 

The software is designed to operate on either detection data or segmentation data, but not mixtures of both in the same dataset. 

To resolve this, please ensure that each data point in your dataset has either detection information or segmentation information, not both. If you want to use segmented data, make sure all of your data points include segmentation information. 

Hope this helps clarify things!

**Comment by Lishumuzixin** [comment]
> @Lishumuzixin hi there,
> 
> A mixed dataset refers to a dataset in which some data points include both object detection information (bounding boxes) and segmentation information (pixel-level object depictions), while other data points include only one type of information.
> 
> In your case, the software found that one data point has a bounding box, but no corresponding segment data, hence the unequal lengths (401 segments vs 402 boxes).
> 
> The software is designed to operate on either detection data or segmentation data, but not mixtures of both in the same dataset.
> 
> To resolve this, please ensure that each data point in your dataset has either detection information or segmentation information, not both. If you want to use segmented data, make sure all of your data points include segmentation information.
> 
> Hope this helps clarify things!

Thank you for your reply.

**Comment by glenn-jocher** [comment]
You're welcome @Lishumuzixin! If you have further questions or encounter any other problems, please don't hesitate to reach out. Happy to help you get the most out of YOLOv8. Happy coding!

**Comment by navjotzubler** [comment]
Hi there, I am new to yolov8 and trying it out on my custom data for instance segmentation. labels includes information on <class id> <x y points of polygons >. Still i get this error when training a yolov8n-seg.yaml model : 
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 11 but got size 0 for tensor number 1 in the list. Appreciate some help to understand whats going wrong.

**Comment by glenn-jocher** [comment]
@navjotzubler hi! It seems there might be an issue with the format or consistency of your label data. Ensure that for each instance, the class ID and the corresponding polygon points are correctly formatted and that every annotated image has matching entries for both. Check for any discrepancies or missing data in your annotations. If each instance is not consistently labeled with both a class ID and polygon points, you may encounter such errors. Review your dataset for consistency and correct formatting, then try training again.
