### ISSUE TITLE
Cannot resume after early stopping

### ISSUE THREAD

**Issue by ivanstepanovftw** [ultralytics/ultralytics#8991]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Stopping training early as no improvement observed in last 500 epochs. Best results observed at epoch 830, best model saved as best.pt.
To update EarlyStopping(patience=500) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

Then try to resume:
```
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 655, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 213, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 319, in _setup_train
    self.resume_training(ckpt)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 672, in resume_training
    assert start_epoch > 0, (
AssertionError: /content/dataset/runs/detect/train/weights/last.pt training to 1500 epochs is finished, nothing to resume.
Start a new training without resuming, i.e. 'yolo train model=/content/dataset/runs/detect/train/weights/last.pt'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
Hi @ivanstepanovftw! The logic behind this is considering the training has been finished after `early stop` so all the checkpoint information are cleaned up and can't be resumed for another training.
