### ISSUE TITLE
Detailed validation data

### ISSUE THREAD

**Issue by Muffinnnnb** [ultralytics/ultralytics#901]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When validating, I want to see more detailed numerical data rather than graphs. Is there a way?

**Comment by Muffinnnnb** [comment]
> @Muffinnnnb please refer to our docs https://docs.ultralytics.com/tasks/detection/. you can easily get metrics .i.e map by the following usage:
> 
> ```python
> metrics = model.val()  # no arguments needed, dataset and settings remembered
> metrics.box.map    # map50-95
> metrics.box.map50  # map50
> metrics.box.map75  # map75
> metrics.box.maps   # a list contains map50-95 of each category
> metrics.box.mp   # precision
> metrics.box.mr   # recall
> ```

I followed the example, but an error occurred saying that the metrics is none type. can you help me?



code: 
`from ultralytics import YOLO
if __name__ == "__main__":
    # model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
    model = YOLO("last.pt")

    metrics=model.val("bike_test.yaml")
    metrics.box.map # map50-95
`


bike_test.yaml: 
`path: C:\testv8\bike_full_img
train: 'T'
val: 'test'
 
# class names
names: 
  0: 'bike'`


output: 
`Ultralytics YOLOv8.0.26  Python-3.10.9 torch-1.12.1+cu113 CUDA:0 (NVIDIA GeForce RTX 4080, 16376MiB)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs
val: Scanning C:\testv8\bike_full_img\test\jsv.cache... 100 images, 0 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:20<00:00,  2.98s/it]
                   all        100        155      0.945      0.558      0.582      0.441
Speed: 0.4ms pre-process, 4.1ms inference, 0.0ms loss, 1.2ms post-process per image
Traceback (most recent call last):
  File "C:\testv8\test.py", line 10, in <module>
    metrics.box.map # map50-95
AttributeError: 'NoneType' object has no attribute 'box'
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit`

**Comment by Muffinnnnb** [comment]
> @Muffinnnnb please refer to our docs https://docs.ultralytics.com/tasks/detection/. you can easily get metrics .i.e map by the following usage:
> 
> ```python
> metrics = model.val()  # no arguments needed, dataset and settings remembered
> metrics.box.map    # map50-95
> metrics.box.map50  # map50
> metrics.box.map75  # map75
> metrics.box.maps   # a list contains map50-95 of each category
> metrics.box.mp   # precision
> metrics.box.mr   # recall
> ```

I followed the example, but an error occurred saying that the metrics is none type. can you help me?



code: 
```
from ultralytics import YOLO
if __name__ == "__main__":
    # model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
    model = YOLO("last.pt")

    metrics=model.val("bike_test.yaml")
    metrics.box.map # map50-95

```

bike_test.yaml: 
```
path: C:\testv8\bike_full_img
train: 'T'
val: 'test'
 
# class names
names: 
  0: 'bike'
```


output: 
```
Ultralytics YOLOv8.0.26  Python-3.10.9 torch-1.12.1+cu113 CUDA:0 (NVIDIA GeForce RTX 4080, 16376MiB)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs
val: Scanning C:\testv8\bike_full_img\test\jsv.cache... 100 images, 0 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:20<00:00,  2.98s/it]
                   all        100        155      0.945      0.558      0.582      0.441
Speed: 0.4ms pre-process, 4.1ms inference, 0.0ms loss, 1.2ms post-process per image
Traceback (most recent call last):
  File "C:\testv8\test.py", line 10, in <module>
    metrics.box.map # map50-95
AttributeError: 'NoneType' object has no attribute 'box'
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

**Comment by Muffinnnnb** [comment]
> @Muffinnnnb please refer to our docs https://docs.ultralytics.com/tasks/detection/. you can easily get metrics .i.e map by the following usage:
> 
> ```python
> metrics = model.val()  # no arguments needed, dataset and settings remembered
> metrics.box.map    # map50-95
> metrics.box.map50  # map50
> metrics.box.map75  # map75
> metrics.box.maps   # a list contains map50-95 of each category
> metrics.box.mp   # precision
> metrics.box.mr   # recall
> ```
