### ISSUE TITLE
Multi-GPU training error

### ISSUE THREAD

**Issue by alon2U** [ultralytics/ultralytics#9103]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Training can be done using a single GPU, but an error will be reported when using multiple GPUs.

### Additional

DDP: debug command /workspace/anaconda3/envs/yolov82/bin/python -m torch.distributed.run --nproc_per_node 4 --master_port 46881 /root/.config/Ultralytics/DDP/_temp_jhd9a9dd139966771426400.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_jhd9a9dd139966771426400.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_jhd9a9dd139966771426400.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_jhd9a9dd139966771426400.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_jhd9a9dd139966771426400.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 669296) of binary: /workspace/anaconda3/envs/yolov82/bin/python
Traceback (most recent call last):
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/root/.config/Ultralytics/DDP/_temp_jhd9a9dd139966771426400.py FAILED
------------------------------------------------------------

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    model.train(
  File "/workspace/code/yolov8-new/ultralytics/engine/model.py", line 391, in train
    self.trainer.train()
  File "/workspace/code/yolov8-new/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/workspace/code/yolov8-new/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/workspace/anaconda3/envs/yolov82/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/workspace/anaconda3/envs/yolov82/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '46881', '/root/.config/Ultralytics/DDP/_temp_jhd9a9dd139966771426400.py']' returned non-zero exit status 1.

**Comment by glenn-jocher** [comment]
@alon2U hey there! 👋 It looks like your environment might not be recognizing the `ultralytics` package correctly during the multi-GPU (DDP) training process. This can often happen due to path issues or environment setup. Here's a quick suggestion to potentially solve the issue:

Ensure that your Python environment is correctly set up and active. You can activate your environment using:

```bash
source activate yolov82
```

Also, confirm that the `ultralytics` package is installed in your current environment. You might want to run:

```bash
pip list | grep ultralytics
```

to check if it's installed, and if not, you can install it using:

```bash
pip install ultralytics
```

Lastly, ensure that your current working directory is set properly. Sometimes, executing the script from a different directory than expected can cause such issues.

If these steps don't resolve the issue, I'd recommend posting more details about your environment configuration, such as the output of `pip list` and the complete command you're using to start the DDP training. This additional info could help in pinpointing the exact cause of the issue. 

Hope this helps! Let us know how it goes. 🚀

**Comment by Burhan-Q** [comment]
@alon2U I've seen this error occur when training on a remote machine and not properly disconnecting which will kill all processes. This is the most likely cause, and without any specifics of your environment, it's impossible to test. I have am able to run mutli-gpu training without this issue (given I disconnect properly from a remote session) for `ultralytics==8.1.27`

**Comment by NUSLCC** [comment]
> [@alon2U](https://github.com/alon2U) hey there! 👋 It looks like your environment might not be recognizing the `ultralytics` package correctly during the multi-GPU (DDP) training process. This can often happen due to path issues or environment setup. Here's a quick suggestion to potentially solve the issue:
> 
> Ensure that your Python environment is correctly set up and active. You can activate your environment using:
> 
> source activate yolov82
> Also, confirm that the `ultralytics` package is installed in your current environment. You might want to run:
> 
> pip list | grep ultralytics
> to check if it's installed, and if not, you can install it using:
> 
> pip install ultralytics
> Lastly, ensure that your current working directory is set properly. Sometimes, executing the script from a different directory than expected can cause such issues.
> 
> If these steps don't resolve the issue, I'd recommend posting more details about your environment configuration, such as the output of `pip list` and the complete command you're using to start the DDP training. This additional info could help in pinpointing the exact cause of the issue.
> 
> Hope this helps! Let us know how it goes. 🚀

Hi @glenn-jocher I met the same situation even after soucing and confirming the installation of ultralytics. May I ask for more suggestions? My ultralytics is 8.2.29. Thanks.
I use device=[1, 2], as 0 is using for single GPU training:
```
/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
WARNING ⚠️ no model scale passed. Assuming scale='T'.
Ultralytics YOLOv8.2.29 🚀 Python-3.11.11 torch-2.3.0+cu121 CUDA:1 (NVIDIA GeForce RTX 3090, 24260MiB)
                                                            CUDA:2 (NVIDIA GeForce RTX 3090, 24260MiB)
```
Error log:
```
DDP: debug command /home/lcc/miniconda3/envs/mambayolo/bin/python3 -m torch.distributed.run --nproc_per_node 2 --master_port 60657 /home/lcc/.config/Ultralytics/DDP/_temp_d5trh68_140402207693392.py
Traceback (most recent call last):
  File "/home/lcc/.config/Ultralytics/DDP/_temp_d5trh68_140402207693392.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/home/lcc/.config/Ultralytics/DDP/_temp_d5trh68_140402207693392.py", line 6, in <module>
    from ultralytics.models.yolo.detect.train import DetectionTrainer
ModuleNotFoundError: No module named 'ultralytics'
E0304 13:56:07.693000 140641833587904 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 1586494) of binary: /home/lcc/miniconda3/envs/mambayolo/bin/python3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/site-packages/torch/distributed/run.py", line 883, in <module>
    main()
  File "/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/lcc/.config/Ultralytics/DDP/_temp_d5trh68_140402207693392.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-04_13:56:07
  host      : arcserver
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1586495)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-04_13:56:07
  host      : arcserver
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1586494)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/lcc/UAVGIT/Mamba-YOLO-11/mbyolo_train.py", line 42, in <module>
    "train": YOLO(model_conf).train(**args),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lcc/UAVGIT/Mamba-YOLO-11/ultralytics/engine/model.py", line 674, in train
    self.trainer.train()
  File "/home/lcc/UAVGIT/Mamba-YOLO-11/ultralytics/engine/trainer.py", line 194, in train
    raise e
  File "/home/lcc/UAVGIT/Mamba-YOLO-11/ultralytics/engine/trainer.py", line 192, in train
    subprocess.run(cmd, check=True)
  File "/home/lcc/miniconda3/envs/mambayolo/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/lcc/miniconda3/envs/mambayolo/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '60657', '/home/lcc/.config/Ultralytics/DDP/_temp_d5trh68_140402207693392.py']' returned non-zero exit status 1.
(mambayolo) (base) lcc@arcserver:~/UAVGIT/Mamba-YOLO-11$ pip list | grep ultralytics
ultralytics              8.2.29           /home/lcc/Mamba-YOLO-11
ultralytics-thop         2.0.14
```

**Comment by glenn-jocher** [comment]
Hi @NUSLCC, thanks for sharing the details. This error typically occurs when the `ultralytics` module isn't accessible in the DDP subprocess environments. Since you've confirmed the package is installed, try these steps:

1. **Set PYTHONPATH**: Ensure your environment paths are visible to subprocesses by running:
```bash
export PYTHONPATH="$PYTHONPATH:/home/lcc/Mamba-YOLO-11"
```
2. **Reinstall in development mode** (if using a local clone):
```bash
cd /home/lcc/Mamba-YOLO-11 && pip install -e .
```

If the issue persists, please share the full output of your training command and verify all GPUs have matching CUDA environments. For reference, see the Ultralytics Multi-GPU Training guide.

**Comment by NUSLCC** [comment]
@glenn-jocher Thank you! After I setting up the PYTHONPATH correctly, the multi-GPU is working properly.

**Comment by glenn-jocher** [comment]
Great to hear that resolved the issue! 🚀 If you encounter any other challenges, feel free to open a new GitHub issue with details. The Ultralytics team and community are here to help with specific reproducible scenarios. For reference, you might find the [YOLO Common Issues guide](https://docs.ultralytics.com/guides/yolo-common-issues/#installation-errors) helpful for future environment-related troubleshooting.
