### ISSUE TITLE
NotFoundError is generated.

### ISSUE THREAD

**Issue by Akira-Taniguchi** [ultralytics/ultralytics#9175]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Error when executing export

```
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/MyDrive/test2/


!pip install tensorflowjs
!pip install ultralytics
!pip install tensorflow==2.13.1

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/test2/runs/detect/train/weights/best.pt")
model.export(format='tfjs') // An error occurs here.
```

error log
```
TensorFlow.js: export failure ❌ 0.2s: /usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
[<ipython-input-1-37745f4ce152>](https://localhost:8080/#) in <cell line: 14>()
     12 
     13 model = YOLO("/content/drive/MyDrive/test2/runs/detect/train/weights/best.pt")
---> 14 model.export(format='tfjs')
     15 
     16 

18 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/load_library.py](https://localhost:8080/#) in load_op_library(library_filename)
     52     RuntimeError: when unable to load the library or get the python wrappers.
     53   """
---> 54   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     55   try:
     56     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE
```

environment
Google Colaboratory

**Comment by glenn-jocher** [comment]
@Akira-Taniguchi hello! It seems like there could be compatibility issues between packages, particularly with TensorFlow and TensorFlow Decision Forests. Try updating TensorFlow Decision Forests, TensorFlow, or both to their latest versions or versions that are compatible with each other. Sometimes, a specific combination might lead to such errors due to mismatches in compiled binaries or APIs.

```bash
!pip install --upgrade tensorflow tensorflow-decision-forests tensorflowjs
```

This ensures that all packages are on their latest versions, potentially resolving any compatibility issues. If the error persists, consider checking the versions of TensorFlow Decision Forests and TensorFlow that are known to work well together. 🛠️

I hope this helps! If you encounter further issues, feel free to provide additional details.

**Comment by Akira-Taniguchi** [comment]
Another error occurred.

script
```
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/MyDrive/test2/


!pip install tensorflowjs
!pip install ultralytics
!pip install tensorflow
!pip install tensorflow-decision-forests

!pip show tensorflowjs
!pip show ultralytics
!pip show tensorflow
!pip show tensorflow-decision-forests

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/test2/runs/detect/train/weights/best.pt")
model.export(format='tfjs')
```

**Comment by Akira-Taniguchi** [comment]
error

```
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Conv.py", line 246, in make_node
    input_tensor = get_padding_as_op(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 2009, in get_padding_as_op
    return tf.pad(x, padding)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend/common/keras_tensor.py", line 91, in __tf_tensor__
    raise ValueError(
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```

What you should do instead is wrap `tf_fn` in a layer:

```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```


ERROR: input_onnx_file_path: /content/drive/MyDrive/test2/runs/detect/train/weights/best.onnx
ERROR: onnx_op_name: /model.0/conv/Conv
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/ops/Conv.py", line 246, in make_node
    input_tensor = get_padding_as_op(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 2009, in get_padding_as_op
    return tf.pad(x, padding)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend/common/keras_tensor.py", line 91, in __tf_tensor__
    raise ValueError(
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```

What you should do instead is wrap `tf_fn` in a layer:

```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-94ebb1e56ae9>", line 20, in <cell line: 20>
    model.export(format='tfjs')
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 588, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 294, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 133, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 799, in export_saved_model
    onnx2tf.convert(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/onnx2tf.py", line 998, in convert
    op.make_node(
  File "/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py", line 354, in print_wrapper_func
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.10/inspect.py", line 1662, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/onnx2tf/utils/common_functions.py](https://localhost:8080/#) in print_wrapper_func(*args, **kwargs)
    287         try:
--> 288             result = func(*args, **kwargs)
    289 

20 frames
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```

What you should do instead is wrap `tf_fn` in a layer:

```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```


During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py](https://localhost:8080/#) in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

**Comment by Akira-Taniguchi** [comment]
@glenn-jocher 

1.
> Given the error log is not directly shown here, 
The error log is attached as a file because it is long.
https://github.com/ultralytics/ultralytics/issues/9175#issuecomment-2014258660

2.
How do I know if the dependencies between TensorFlow and TensorFlow Decision Forests are compatible with TensorFlow.js?

3.
```
!pip cache purge
```
I ran this command.
Only ultralytics had changes in the installed version.
8.1.30->8.1.34
Still the result was the same. I get the same error.

4.
>Optionally, considering specifying version numbers known to work well together if the latest versions continue causing issues.

Where can I find information on version numbers that work well?

**Comment by glenn-jocher** [comment]
@Akira-Taniguchi Thanks for the follow-up and the additional details!

1. **Error Log**: 👍 I've checked out the log you attached. It seems there's an issue directly related to TensorFlow.js exporting. Sometimes, the complexity of the model or the operations used in TensorFlow may not be fully supported by tfjs-converter. I recommend opening an issue in the TensorFlow.js GitHub repo with this log for more targeted support.

2. **Dependencies Compatibility**: To check for compatibility, the TensorFlow.js conversion docs would be the best resource. However, not all TensorFlow operations are supported in TensorFlow.js, which might lead to errors during conversion. The [tfjs-converter](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) docs provide more info on operation support and compatibility.

3. **Installed Versions**: The minor version update of ultralytics not affecting the outcome suggests the root cause lies deeper, likely in the specific operations used in your model and their compatibility with TensorFlow.js.

4. **Finding Compatible Versions**: Unfortunately, there's no definitive guide for version compatibility between TensorFlow, TensorFlow Decision Forests, and TensorFlow.js as it largely depends on the specific operations used in your model. A good starting point would be the `tfjs-converter` GitHub issues or TensorFlow.js community forums to look for similar issues and their resolutions.

For immediate actions, if TensorFlow.js does not support certain operations, consider simplifying your model or exploring model conversion tools that might offer custom operation support. Keep sharing any significant findings for community benefit! 🌟

**Comment by Akira-Taniguchi** [comment]
// memo


```
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/MyDrive/test2/

!pip cache purge
!pip install tensorflowjs
!pip install ultralytics
!pip install tensorflow-decision-forests
!pip install tensorflow==2.13.1

!pip show tensorflowjs
!pip show ultralytics
!pip show tensorflow
!pip show tensorflow-decision-forests

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/test2/runs/detect/train/weights/best.pt")
model.export(format='tfjs')
```

```
TensorFlow.js: export failure ❌ 0.6s: /usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-1-4a9dc0cde4e0> in <cell line: 20>()
     18 
     19 model = YOLO("/content/drive/MyDrive/test2/runs/detect/train/weights/best.pt")
---> 20 model.export(format='tfjs')
     21 
     22 

18 frames
/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     52     RuntimeError: when unable to load the library or get the python wrappers.
     53   """
---> 54   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     55   try:
     56     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE
```

**Comment by Akira-Taniguchi** [comment]
I found the cause.

Tips,
Specifying the tensorflow version as 2.13.1
Specify the version of tensorflow-decision-forests as 1.5.0

By doing this, the command "!tensorflowjs_converter -version" works correctly and the conversion works.

@glenn-jocher 


```
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/MyDrive/test2/

!pip cache purge
!pip install tensorflowjs
!pip install ultralytics
!pip install tensorflow-decision-forests==1.5.0
!pip install tensorflow==2.13.1

!pip show tensorflowjs
!pip show ultralytics
!pip show tensorflow
!pip show tensorflow-decision-forests

!tensorflowjs_converter --version

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/test2/runs/detect/train/weights/best.pt")
model.export(format='tfjs')
```

**Comment by Akira-Taniguchi** [comment]
close!

**Comment by glenn-jocher** [comment]
@Akira-Taniguchi That's fantastic news! 🎉 I'm glad you discovered the version compatibility issue and found a working solution. Sometimes, the devil is in the details with these library versions. Your findings will surely help others facing similar issues. Here's the successful setup for future reference:

```bash
!pip install tensorflowjs
!pip install ultralytics
!pip install tensorflow-decision-forests==1.5.0
!pip install tensorflow==2.13.1
```

And then exporting your model:

```python
from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/test2/runs/detect/train/weights/best.pt")
model.export(format='tfjs')
```

Great job, and thanks for sharing! 👍
