### ISSUE TITLE
RT-DETR does not export to edgetpu

### ISSUE THREAD

**Issue by ruzko** [ultralytics/ultralytics#9226]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Exporting RT-DETR to edgetpu format or tflite format with/without int8 quantization results in a segmentation fault.

tflite format with int8 quantization:
ouput:
├── calibration_image_sample_data_20x128x128x3_float32.npy
├── rtdetr-l.onnx
├── rtdetr-l.pt
├── rtdetr-l_saved_model
│   ├── assets
│   ├── fingerprint.pb
│   ├── rtdetr-l_float16.tflite
│   ├── rtdetr-l_float32.tflite
│   ├── saved_model.pb
│   └── variables
│       ├── variables.data-00000-of-00001
│       └── variables.index
```
yolo export model=rtdetr-l.pt format=tflite int8=True
Ultralytics YOLOv8.1.30 🚀 Python-3.11.8 torch-2.2.1+cu121 CPU (Intel Core(TM) i7-8750H 2.20GHz)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients, 103.8 GFLOPs

PyTorch: starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.11M/1.11M [00:00<00:00, 4.25MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /var/mnt/data/jacob/git/farm-animal-detection/models/calibration_image_sample_data_20x128x128x3_float32.npy...: 100%|██████████| 1/1 

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 23.6s, saved as 'rtdetr-l.onnx' (123.0 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: module 'onnx' has no attribute '_serialize'
WARNING: Current pooling with ceil_mode = 1 follows pytorch implementation since current onnx implementation generates nan values. Please refer to https://github.com/PINTO0309/onnx2tf/issues/207.
saved_model output started ==========================================================
saved_model output complete!
Float32 tflite output complete!
Float16 tflite output complete!
Input signature information for quantization
signature_name: serving_default
input_name.0: images shape: (1, 640, 640, 3) dtype: <dtype: 'float32'>
[1]    52875 segmentation fault (core dumped)  yolo export model=rtdetr-l.pt format=tflite int8=True
```
-----
edgetpu format:
├── calibration_image_sample_data_20x128x128x3_float32.npy
├── rtdetr-l.onnx
├── rtdetr-l.pt
├── rtdetr-l_saved_model
│   ├── assets
│   ├── fingerprint.pb
│   ├── rtdetr-l_float16.tflite
│   ├── rtdetr-l_float32.tflite
│   ├── saved_model.pb
│   └── variables
│       ├── variables.data-00000-of-00001
│       └── variables.index

```
yolo export model=rtdetr-l.pt format=edgetpu                                                                 
Ultralytics YOLOv8.1.30 🚀 Python-3.11.8 torch-2.2.1+cu121 CPU (Intel Core(TM) i7-8750H 2.20GHz)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients, 103.8 GFLOPs

PyTorch: starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 23.2s, saved as 'rtdetr-l.onnx' (123.0 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: module 'onnx' has no attribute '_serialize'
WARNING: Current pooling with ceil_mode = 1 follows pytorch implementation since current onnx implementation generates nan values. Please refer to https://github.com/PINTO0309/onnx2tf/issues/207.
saved_model output started ==========================================================
saved_model output complete!
Float32 tflite output complete!
Float16 tflite output complete!
Input signature information for quantization
signature_name: serving_default
input_name.0: images shape: (1, 640, 640, 3) dtype: <dtype: 'float32'>
[1]    56129 segmentation fault (core dumped)  yolo export model=rtdetr-l.pt format=edgetpu
```
----

tflite format without int8 quantization kinda works, but has error about missing SavedModel file in the saved_model directory.
output:
├── calibration_image_sample_data_20x128x128x3_float32.npy
├── rtdetr-l.onnx
├── rtdetr-l.pt
├── rtdetr-l_saved_model
│   ├── assets
│   ├── fingerprint.pb
│   ├── rtdetr-l_float16.tflite
│   ├── rtdetr-l_float32.tflite
│   └── variables
│       ├── variables.data-00000-of-00001
│       └── variables.index
```
yolo export model=rtdetr-l.pt format=tflite          
Ultralytics YOLOv8.1.30 🚀 Python-3.11.8 torch-2.2.1+cu121 CPU (Intel Core(TM) i7-8750H 2.20GHz)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients, 103.8 GFLOPs

PyTorch: starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 23.2s, saved as 'rtdetr-l.onnx' (123.0 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...
TensorFlow SavedModel: export failure ❌ 193.9s: SavedModel file does not exist at: rtdetr-l_saved_model/{saved_model.pbtxt|saved_model.pb}
Traceback (most recent call last):
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/ultralytics/engine/model.py", line 588, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/ultralytics/engine/exporter.py", line 294, in __call__
    f[5], keras_model = self.export_saved_model()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/ultralytics/engine/exporter.py", line 138, in outer_func
    raise e
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/ultralytics/engine/exporter.py", line 133, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/ultralytics/engine/exporter.py", line 822, in export_saved_model
    return str(f), tf.saved_model.load(f, tags=None, options=None)  # load saved_model as Keras model
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/tensorflow/python/saved_model/load.py", line 858, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/tensorflow/python/saved_model/load.py", line 963, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/tensorflow/python/saved_model/loader_impl.py", line 58, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mnt/data/jacob/git/farm-animal-detection/.env/lib64/python3.11/site-packages/tensorflow/python/saved_model/loader_impl.py", line 116, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: rtdetr-l_saved_model/{saved_model.pbtxt|saved_model.pb
```

### Environment

```
yolo checks                                 
Ultralytics YOLOv8.1.30 🚀 Python-3.11.8 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1070 with Max-Q Design, 8107MiB)
Setup complete ✅ (12 CPUs, 31.1 GB RAM, 325.6/464.2 GB disk)

OS                  Linux-6.8.0-0.rc6.49.fc40.x86_64-x86_64-with-glibc2.39
Environment         Linux
Python              3.11.8
Install             git
RAM                 31.07 GB
CPU                 Intel Core(TM) i7-8750H 2.20GHz
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

```
`onnx2tf==1.17.5`

### Minimal Reproducible Example

pip install ultralytics
pip install torch==2.2.1
pip install tensorflow-cpu==2.13.1
yolo export model=rtdetr-l format=edgetpu

### Additional

Exporting RT-DETR to ONNX works.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ruzko hello! Thanks for bringing this to our attention and for the detailed report. 😊

It seems like there are challenges exporting RT-DETR to Edge TPU and TFLite formats, particularly with the segmentation fault occurring during the process. We appreciate your thorough documentation of the issue. Regarding the segmentation fault, this is a complex problem that could involve multiple factors including compatibility between the model architecture and the export format process.

For TFLite export without INT8 quantization reporting a missing SavedModel file, it could be indicating that the intermediate conversion step might be failing or not producing the expected outputs. 

We recommend two steps for now:

1. Ensure all dependencies are up to date and compatible. Occasionally, version mismatches can lead to unexpected behavior.
2. Since exporting to ONNX seems to work for you, a temporary workaround could involve converting the ONNX model to your desired format using external tools that support this pathway more robustly.

For example, converting ONNX to TFLite (without quantization as a starting point) can be performed using tools like [onnx-tflite](https://github.com/onnx/onnx-tensorflow) with commands like:

```python
# Assuming you have already exported RT-DETR to ONNX
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("rtdetr-l.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph("rtdetr-l_saved_model")
```

Then, you can use TensorFlow's converter to go from SavedModel to TFLite.

We recognize that this isn't an ideal solution and doesn't directly address INT8 quantization or EdgeTPU conversion. Your contribution and willingness to submit a PR are greatly appreciated! 🙏 If you’ve identified a specific fix or improvement, please don't hesitate to contribute or share your findings. Contributions like yours are invaluable to improving the utility and robustness of our models.

In the meanwhile, we'll investigate the segmentation fault on our end. If you need further assistance with the workaround or have more insights into the issue, feel free to discuss it further. 

Thank you for your support and for being part of the YOLOv8 community!

**Comment by isuchy** [comment]
Hi @glenn-jocher, 
I'm trying to reproduce the step in order to convert ONNX format to TensorFlow as you suggested here  
 
> ```python
> # Assuming you have already exported RT-DETR to ONNX
> import onnx
> from onnx_tf.backend import prepare
> 
> onnx_model = onnx.load("rtdetr-l.onnx")
> tf_rep = prepare(onnx_model)
> tf_rep.export_graph("rtdetr-l_saved_model")
> ```

Unfortunately, it crashes on this command `tf_rep.export_graph("tf_model")` and here's the ouput

```
KeyError                                  Traceback (most recent call last)
[<ipython-input-5-59eb24a314c6>](https://localhost:8080/#) in <cell line: 7>()
      5 onnx_model = onnx.load("rtdetr-l.onnx")
      6 tf_rep = prepare(onnx_model)
----> 7 tf_rep.export_graph("tf_model")

40 frames
[/usr/local/lib/python3.10/dist-packages/onnx_tf/handlers/backend/pad.py](https://localhost:8080/#) in <lambda>()
    117                     nonlocal paddings, constant_values
    118                     paddings = ag__.ld(tensor_dict)[ag__.ld(node).inputs[1]]
--> 119                     constant_values = ag__.if_exp(ag__.converted_call(ag__.ld(len), (ag__.ld(node).inputs,), None, fscope) == 3, lambda : ag__.ld(tensor_dict)[ag__.ld(node).inputs[2]], lambda : 0, 'ag__.converted_call(len, (node.inputs,), None, fscope) == 3')
    120                 paddings = ag__.Undefined('paddings')
    121                 constant_values = ag__.Undefined('constant_values')

KeyError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/onnx_tf/backend_tf_module.py", line 99, in __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    File "/usr/local/lib/python3.10/dist-packages/onnx_tf/backend.py", line 347, in _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    File "/usr/local/lib/python3.10/dist-packages/onnx_tf/handlers/handler.py", line 59, in handle  *
        return ver_handle(node, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/onnx_tf/handlers/backend/pad.py", line 95, in version_13  *
        return cls._common(node, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/onnx_tf/handlers/backend/pad.py", line 73, in _common  *
        constant_values = tensor_dict[node.inputs[2]] if len(

    KeyError: ''
```

I exported the RT-DETR model to ONNX format (rtdetr-l.onnx) as follows:
```
import torch
from ultralytics import YOLO
from ultralytics import RTDETR

model = RTDETR('rtdetr-l.pt')
model.export(format='onnx', dynamic=True, batch=1, simplify=False) 
```

Do you have any idea why this error occurred and how to solve it? 
Thank you in advance.

**Comment by isuchy** [comment]
Hello @ruzko,

did you finally manage to export the RT-DETR model to EdgeTPU? 
If so, on what environment and with what combination of versions of each package?

Thanks.
