### ISSUE TITLE
Insufficient memory is reported, and then the entire docker environment is killed.

### ISSUE THREAD

**Issue by Williamwsk** [ultralytics/ultralytics#9429]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When converting mask to txt, the number of decimal points in the saved data will cause the lower and right boundaries to be lost. And when the data preprocessing reads the segment, it is resampled. When the number of points of an instance mask in txt exceeds one thousand, resampling will be performed, resulting in the loss of pixel values ​​at the boundary. Secondly, when the basic data in the source code is enhanced (scale, translate), the bbox error generated by segment2bbox causes the enhancement mask to be truncated by the bbox and other problems.
（1）The saving position of txt decimal point causes the lower and right borders to be lost. (The mask without coco rle is on the left, and the mask of yolov8 txt is on the right)
![image](https://github.com/ultralytics/ultralytics/assets/38774781/62306e94-c672-4d75-8383-69a13390bc76)

（2）Resample when the number of mask points exceeds 1,000 (the left side is coco rle mask, the middle is yolov8 txt mask, and the right side is the mask after loading yolov8 data)
![image](https://github.com/ultralytics/ultralytics/assets/38774781/53f95a65-35dc-40e5-82ea-99954f65143d)

（3）There is an error in segment2bbox in basic data enhancement (scale, translate). (The first column is the original image, the second column is the enhanced original image, the third column is the mask of the original image, and the fourth column is the mask of the enhanced original image)
![image](https://github.com/ultralytics/ultralytics/assets/38774781/7eb9e8bd-425b-48b6-9478-5dc04e7b3f51)

So I changed the entire data reading and data enhancement preprocessing code, directly from coco rle to segment mask, and then when doing data enhancement, I also performed the same operation on the mask two-dimensional matrix in the segment as on the original image to realize the basis of mask. Data augmentation. However, the size of the 35,000 640*640 original images and the mask's train.cache file saved after the data is loaded is an astonishing more than 100 G in size. Then an out of memory error was reported during model training. When gpu=1, batchsize=1, and worker=1, the memory occupied is about 75G. May I ask why yolov8 needs to save all the data in memory at once? Can't do streaming reading?

The error message is as follows：
`
Starting training for 1 epochs...
      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/547 [00:00<?, ?it/s][2024-03-29 19:06:01,120] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 401 closing signal SIGTERM
[2024-03-29 19:06:01,265] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 402 closing signal SIGTERM
[2024-03-29 19:06:01,275] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 403 closing signal SIGTERM
[2024-03-29 19:06:01,275] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 404 closing signal SIGTERM
[2024-03-29 19:06:01,275] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 405 closing signal SIGTERM
[2024-03-29 19:06:01,276] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 406 closing signal SIGTERM
[2024-03-29 19:06:01,276] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 407 closing signal SIGTERM
[2024-03-29 19:06:08,477] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 400) of binary: /root/anaconda3/envs/wsk-py310-yolov8-new/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/site-packages/torch/distributed/run.py", line 816, in <module>
    main()
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/root/.config/Ultralytics/DDP/_temp__zll04_p140147489829120.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-29_19:06:01
  host      : 78174e16c334
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 400)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 400
============================================================
Traceback (most recent call last):
  File "/project/Code/Seg/wsk/v1/ultralytics/train.py", line 16, in <module>
    model.train(data='./train.yaml',
  File "/project/Code/Seg/wsk/v1/ultralytics/ultralytics/engine/model.py", line 655, in train
    self.trainer.train()
  File "/project/Code/Seg/wsk/v1/ultralytics/ultralytics/engine/trainer.py", line 334, in train
    raise e
  File "/project/Code/Seg/wsk/v1/ultralytics/ultralytics/engine/trainer.py", line 332, in train
    subprocess.run(cmd, check=True)
  File "/root/anaconda3/envs/wsk-py310-yolov8-new/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/wsk-py310-yolov8-new/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '8', '--master_port', '13215', '/root/.config/Ultralytics/DDP/_temp__zll04_p140147489829120.py']' returned non-zero exit status 1.

`

The number of processes has also increased from the initial 8 to multiple：
<img width="1019" alt="image" src="https://github.com/ultralytics/ultralytics/assets/38774781/d4632511-2bd5-4851-98f7-6baa6e4bbaa9">
<img width="1017" alt="image" src="https://github.com/ultralytics/ultralytics/assets/38774781/1116e2f1-eaf1-4455-85f2-aae2fa0ad493">

Finally, the docker environment crashed directly!
<img width="1016" alt="image" src="https://github.com/ultralytics/ultralytics/assets/38774781/aecb5432-94d3-4c2c-8df2-4f91e3d5ee8a">

Looking forward to your reply, thank you！

**Comment by glenn-jocher** [comment]
@Williamwsk hey there 👋,

Thank you for bringing this to our attention and providing detailed information. It seems like the memory usage during training, especially with substantial cache file sizes, is pushing the limits of your hardware resulting in out-of-memory errors.

For large datasets or high image resolutions, consider these approaches to mitigate memory issues:

- **Reduce Batch Size:** Lowering `batch_size` can significantly decrease memory consumption. Although it might slow down the training speed, it's a worthy trade-off for stability.

  ```bash
  yolo detect train data=train.yaml model=yolov8n.pt batch_size=1
  ```

- **Reduce Image Resolution:** If possible, try reducing the `img_size` to lower the memory footprint further.

  ```bash
  yolo detect train data=train.yaml model=yolov8n.pt imgsz=320
  ```

- **Data Loading:** YOLO is optimized for efficiency, but your custom data modifications might increase memory usage. Streamlining data augmentation or modifying the caching mechanism could help.

- **Hardware:** Ensure your Docker environment has enough allocated memory. For Docker Desktop, you can adjust this in the settings.

Ultimately, finding the right balance between these parameters will be key to optimizing for your specific scenario. If you have made substantial changes to the data preprocessing code, consider carefully reviewing those changes to ensure they're not unduly increasing the memory requirements.

We're always striving to improve, so we appreciate your feedback and insights as we continue to evolve the platform 🙌.
