### ISSUE TITLE
Make compatible with TensorRT 10 release

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#9510]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Looks like new/different methods with TensorRT 10 that aren't compatible with the existing implementation in `Autobackend` class. Have not yet tested export, but wanted to open issue. Will add details with attempt for exporting.

```
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\engine\model.py", line 423, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\engine\predictor.py", line 341, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\nn\autobackend.py", line 216, in __init__
    context = model.create_execution_context()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

### Environment

```
Ultralytics YOLOv8.1.16 🚀 Python-3.11.6 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
Setup complete ✅ (12 CPUs, 31.9 GB RAM, 391.9/1863.0 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 31.86 GB
CPU                 Intel Core(TM) i5-10600K 4.10GHz
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0+cu121>=1.8.0
torchvision         ✅ 0.17.0+cu121>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
```

#### TensorRT info

```
nvidia-cublas-cu12       12.3.4.1
nvidia-cuda-nvrtc-cu12   12.3.107
nvidia-cuda-runtime-cu12 12.3.101
nvidia-cudnn-cu12        8.9.7.29
tensorrt                 10.0.0b6
tensorrt-cu12            10.0.0b6
tensorrt-cu12_bindings   10.0.0b6
tensorrt-cu12_libs       10.0.0b6
```

### Minimal Reproducible Example

```py
from ultralytics import YOLO

model = YOLO("yolov8n.engine", task="detect")
results = model.predict()
```

### Additional

Same issue present on Linux

```
Ultralytics YOLOv8.1.42 🚀 Python-3.11.7 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5924MiB)
Setup complete ✅ (12 CPUs, 15.6 GB RAM, 95.6/101.0 GB disk)

OS                  Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.11.7
Install             pip
RAM                 15.56 GB
CPU                 AMD Ryzen 5 1600 Six-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.1.2+cu121>=1.8.0
torchvision         ✅ 0.16.2+cu121>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

#### TensorRT info

```
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.4.99
nvidia-nvtx-cu12         12.1.105
tensorrt                 10.0.0b6
tensorrt-cu12            10.0.0b6
tensorrt-cu12_bindings   10.0.0b6
tensorrt-cu12_libs       10.0.0b6
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
## Windows export attempt failed

```py
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
out = model.export(format="engine")
```

```
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.1.16 🚀 Python-3.11.6 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: export success ✅ 0.8s, saved as 'yolov8n.onnx' (12.2 MB)

TensorRT: starting export with TensorRT 10.0.0b6...
[04/02/2024-08:47:47] [TRT] [I] [MemUsageChange] Init CUDA: CPU +3, GPU +0, now: CPU 19158, GPU 1574 (MiB)
[04/02/2024-08:47:50] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2613, GPU +310, now: CPU 22026, GPU 1884 (MiB)

TensorRT: export failure ❌ 3.7s: 'tensorrt_bindings.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\engine\model.py", line 578, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\engine\exporter.py", line 275, in __call__
    f[1], _ = self.export_engine()
              ^^^^^^^^^^^^^^^^^^^^
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\engine\exporter.py", line 136, in outer_func
    raise e
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\engine\exporter.py", line 131, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Q:\ML_dev\tensorrt_test\.trt\Lib\site-packages\ultralytics\engine\exporter.py", line 663, in export_engine
    config.max_workspace_size = self.args.workspace * 1 << 30
    ^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'tensorrt_bindings.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'
```

**Comment by Burhan-Q** [comment]
Confirmed error with `Ultralytics YOLOv8.1.42` on Windows

**Comment by Burhan-Q** [comment]
I think I have a couple of small patches to address issues with the export solved. The inference looks like it will need more effort to make work.

**Comment by Burhan-Q** [comment]
> [!NOTE]
> Inference and export compatibility is working in #9516 but I would like to figure out a better way to handle version handling

**Comment by AurevoirXavier** [comment]
```
TensorRT: starting export with TensorRT 10.2.0...
[08/18/2024-16:55:41] [TRT] [I] [MemUsageChange] Init CUDA: CPU +12, GPU +0, now: CPU 24194, GPU 1743 (MiB)
[08/18/2024-16:55:44] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +3081, GPU +412, now: CPU 27639, GPU 2155 (MiB)
TensorRT: export failure ❌ 3.2s: 'tensorrt.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'
Traceback (most recent call last):
  File "C:\Users\Xavier Lau\code\yolov10\CS2\detect\export.py", line 6, in <module>
    model.export(device=0, format="engine", half=True, simplify=True, opset=20)
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\model.py", line 590, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "C:\Users\Xavier Lau\miniconda3\envs\yolov10\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 288, in __call__
    f[1], _ = self.export_engine()
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 138, in outer_func
    raise e
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 133, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 682, in export_engine
    config.max_workspace_size = self.args.workspace * 1 << 30
AttributeError: 'tensorrt.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'
```

Still got this in ultralytics 8.2.78.

**Comment by AurevoirXavier** [comment]
```
TensorRT: starting export with TensorRT 10.2.0...
[08/18/2024-16:55:41] [TRT] [I] [MemUsageChange] Init CUDA: CPU +12, GPU +0, now: CPU 24194, GPU 1743 (MiB)
[08/18/2024-16:55:44] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +3081, GPU +412, now: CPU 27639, GPU 2155 (MiB)
TensorRT: export failure ❌ 3.2s: 'tensorrt.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'
Traceback (most recent call last):
  File "C:\export.py", line 6, in <module>
    model.export(device=0, format="engine", half=True, simplify=True, opset=20)
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\model.py", line 590, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "C:\Users\Xavier Lau\miniconda3\envs\yolov10\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 288, in __call__
    f[1], _ = self.export_engine()
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 138, in outer_func
    raise e
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 133, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "C:\Users\Xavier Lau\code\yolov10\ultralytics\engine\exporter.py", line 682, in export_engine
    config.max_workspace_size = self.args.workspace * 1 << 30
AttributeError: 'tensorrt.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'
```

Still got this in ultralytics 8.2.78.

**Comment by glenn-jocher** [comment]
Please verify if the issue persists with the latest version of the Ultralytics package. If the problem continues, consider downgrading to TensorRT 9.2.0 or 8.6.1, which are confirmed to be compatible.
