### ISSUE TITLE
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

### ISSUE THREAD

**Issue by wish44165** [ultralytics/ultralytics#9561]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## Description
Hi, I modified the Conv layer to DWConv in yolov8-pose.yaml to decrease the model's parameters. However, I faced a RuntimeError stating: "Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively." Below are the original and revised yaml files, along with the corresponding output when converting from a PyTorch model to a TensorFlow Lite model. I wonder how to resolve the issue. Thank you.

## Environment
```
(yolov8) wish@wish-Cyborg-15-A12VE:~$ yolo checks
Ultralytics YOLOv8.1.22 🚀 Python-3.10.13 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4050 Laptop GPU, 5905MiB)
Setup complete ✅ (16 CPUs, 23.2 GB RAM, 324.8/915.3 GB disk)

OS                  Linux-6.5.0-26-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.13
Install             pip
RAM                 23.17 GB
CPU                 12th Gen Intel Core(TM) i7-12650H
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Original yolov8-pose.yaml
```
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, Pose, [nc, kpt_shape]] # Pose(P3, P4, P5)
```

### Revised yolov8-pose.yaml (Replace Conv with DWConv)
```
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, DWConv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, DWConv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, DWConv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, DWConv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, DWConv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, DWConv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, DWConv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, Pose, [nc, kpt_shape]] # Pose(P3, P4, P5)
```

## convert2tflite.py
```
from ultralytics import YOLO
model = YOLO('./best.pt')  # load a pretrained model (recommended for training)
path = model.export(imgsz=96, half=False, int8=True, format="tflite")
```

### Original
```
(yolov8) wish@wish-Cyborg-15-A12VE:~/pro/ICME2024/final/ultralytics_$ python convert2tflite.py 
Ultralytics YOLOv8.1.34 🚀 Python-3.10.13 torch-2.2.1+cu121 CPU (12th Gen Intel Core(TM) i7-12650H)
YOLOv8n-pose summary (fused): 187 layers, 4326386 parameters, 0 gradients, 14.0 GFLOPs

PyTorch: starting from 'best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 158, 8400) (8.5 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.11M/1.11M [00:00<00:00, 3.12MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /home/wish/pro/ICME2024/final/ultralytics_/calibration_image_sample_data_20x128x128x3_float32.npy...: 100%|██████████| 1/1 [00:00<00

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 0.6s, saved as 'best.onnx' (16.9 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: module 'onnx' has no attribute '_serialize'
saved_model output started ==========================================================
saved_model output complete!
Float32 tflite output complete!
Float16 tflite output complete!
Input signature information for quantization
signature_name: serving_default
input_name.0: images shape: (1, 640, 640, 3) dtype: <dtype: 'float32'>
Dynamic Range Quantization tflite output complete!
fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
INT8 Quantization tflite output complete!
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
Full INT8 Quantization tflite output complete!
INT8 Quantization with int16 activations tflite output complete!
Full INT8 Quantization with int16 activations tflite output complete!
TensorFlow SavedModel: export success ✅ 112.9s, saved as 'best_saved_model' (56.2 MB)

TensorFlow Lite: starting export with tensorflow 2.13.1...
TensorFlow Lite: export success ✅ 0.0s, saved as 'best_saved_model/best_int8.tflite' (4.5 MB)

Export complete (114.2s)
Results saved to /home/wish/pro/ICME2024/final/ultralytics_
Predict:         yolo predict task=pose model=best_saved_model/best_int8.tflite imgsz=640 int8 
Validate:        yolo val task=pose model=best_saved_model/best_int8.tflite imgsz=640 data=./facial_f3.yaml int8 
Visualize:       https://netron.app
```

### Revised
```
(yolov8) wish@wish-Cyborg-15-A12VE:~/pro/ICME2024/final/ultralytics_DWConv$ python convert2tflite.py 
Ultralytics YOLOv8.1.37 🚀 Python-3.10.13 torch-2.2.1+cu121 CPU (12th Gen Intel Core(TM) i7-12650H)
YOLOv8-pose summary (fused): 187 layers, 3756434 parameters, 0 gradients, 12.8 GFLOPs

PyTorch: starting from 'best.pt' with input shape (1, 3, 96, 96) BCHW and output shape(s) (1, 158, 189) (7.4 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.11M/1.11M [00:00<00:00, 5.64MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /home/wish/pro/ICME2024/final/ultralytics_DWConv/calibration_image_sample_data_20x128x128x3_float32.npy...: 100%|██████████| 1/1 [00

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 0.5s, saved as 'best.onnx' (14.4 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...

Automatic generation of each OP name started ========================================
Automatic generation of each OP name complete!

Model loaded ========================================================================

Model conversion started ============================================================
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: module 'onnx' has no attribute '_serialize'
saved_model output started ==========================================================
saved_model output complete!
Float32 tflite output complete!
Float16 tflite output complete!
Input signature information for quantization
signature_name: serving_default
input_name.0: images shape: (1, 96, 96, 3) dtype: <dtype: 'float32'>
Dynamic Range Quantization tflite output complete!
fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
INT8 Quantization tflite output complete!
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
Full INT8 Quantization tflite output complete!
Traceback (most recent call last):
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/onnx2tf/onnx2tf.py", line 1494, in convert
    tflite_model = converter.convert()
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1065, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1042, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1390, in convert
    return self._convert_from_saved_model(graph_def)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1257, in _convert_from_saved_model
    return self._optimize_tflite_model(
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 991, in _optimize_tflite_model
    model = self._quantize(
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 729, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 194, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

WARNING: INT8 Quantization with int16 activations tflite output failed.
Traceback (most recent call last):
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/onnx2tf/onnx2tf.py", line 1525, in convert
    tflite_model = converter.convert()
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1065, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1042, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1390, in convert
    return self._convert_from_saved_model(graph_def)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1257, in _convert_from_saved_model
    return self._optimize_tflite_model(
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 991, in _optimize_tflite_model
    model = self._quantize(
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 729, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/wish/anaconda3/envs/yolov8/lib/python3.10/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 194, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

WARNING: Full INT8 Quantization with int16 activations tflite output failed.
TensorFlow SavedModel: export success ✅ 22.9s, saved as 'best_saved_model' (47.6 MB)

TensorFlow Lite: starting export with tensorflow 2.13.1...
TensorFlow Lite: export success ✅ 0.0s, saved as 'best_saved_model/best_int8.tflite' (3.7 MB)

Export complete (24.0s)
Results saved to /home/wish/pro/ICME2024/final/ultralytics_DWConv
Predict:         yolo predict task=pose model=best_saved_model/best_int8.tflite imgsz=96 int8 
Validate:        yolo val task=pose model=best_saved_model/best_int8.tflite imgsz=96 data=./facial_f3.yaml int8 
Visualize:       https://netron.ap
```

**Comment by glenn-jocher** [comment]
@wish44165 hey there! 🌟 It seems you've encountered a quantization issue when converting your model to TensorFlow Lite. This typically relates to the mismatch between the expected input dimensions and the dimensions after quantization.

A common step to tackle such issues, especially with custom modifications like replacing `Conv` with `DWConv`, is ensuring your input dimensions align properly throughout the model. When you modify the model architecture, it's crucial to verify that all subsequent layers expect the input shapes they receive. Quantization, particularly INT8, can be sensitive to these model architecture changes.

For the error you're encountering, it would be helpful to further investigate how the specific layers affected by `DWConv` interact with the TensorFlow Lite conversion process, especially regarding quantization. Additionally, because you're using custom calibration data for quantization, double-checking the integrity and relevance of this data to your modified model could also provide insights.

If the problem persists, consider testing the conversion with:

1. Different opset versions in ONNX if applicable.
2. Disabling quantization to isolate the issue (`int8=False`).

For more targeted assistance, it might help to share more specifics on how the DWConv layer integration alters the tensor shapes. Here's a basic example of how you might adjust your configuration or conversion script to disable INT8 quantization for troubleshooting purposes:

```python
from ultralytics import YOLO
model = YOLO('./best.pt')
path = model.export(imgsz=96, half=False, int8=False, format="tflite") # Turning off INT8 quantization
```

If these steps don't lead to a resolution, feel free to share additional details or error logs. Collaboratively, we can dive deeper into the problem!

**Comment by wyfshr** [comment]
I wonder if the best.pt in the convert2tflite.py is trained on the network structure after replacing Conv with DWConv?

**Comment by glenn-jocher** [comment]
Hello! 😊 Great question! Yes, to avoid any misalignment issues during the conversion process, the `best.pt` model should indeed be trained on the network structure that includes your changes (replacing `Conv` with `DWConv`). This ensures that the trained weights and the architecture used during conversion are aligned, which is critical for successful model quantization and export.

If you're running into issues, make sure that the model weights `best.pt` were indeed obtained from training the updated `DWConv` model configuration. If discrepancies persist, retraining the model with the intended architecture might be essential.

Hope this helps! Let us know if you have any more questions.
