### ISSUE TITLE
Error when resuming from last interrupted training KeyError: 'momentum'

### ISSUE THREAD

**Issue by aldly** [ultralytics/ultralytics#9815]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

- 'D:\Python Script\pythonProject\runs\detect\train4\weights\last.pt'    It's the training I did earlier that broke at epoch 1476/1485

- I've checked google and yolov8 documentation and it seems to be a problem with the existence of the torch, is it possible to make some modifications in order to solve this problem?

```(.venv) PS D:\Python Script\pythonProject> python train.py
New https://pypi.org/project/ultralytics/8.1.43 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.42 🚀 Python-3.12.1 torch-2.3.0.dev20240108+cu121 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 12282MiB)
engine\trainer: task=detect, mode=train, model=D:\Python Script\pythonProject\runs\detect\train4\weights\last.pt, data=D:\Users\Desktop\train_T5\my.yaml, epochs=1485, time=1.5, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=D:\Python Script\pythonProject\runs\detect\train4\weights\last.pt, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.0, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752677  ultralytics.nn.modules.head.Detect           [7, [64, 128, 256]]
YOLOv8n summary: 225 layers, 3012213 parameters, 3012197 gradients

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning D:\Users\Desktop\train_T5\labels.cache... 508 images, 0 backgrounds, 0 corrupt: 100%|██████████| 508/508 [00:00<?, ?it/s]
val: Scanning D:\Users\Desktop\train_T5\labels.cache... 508 images, 0 backgrounds, 0 corrupt: 100%|██████████| 508/508 [00:00<?, ?it/s]
Plotting labels to runs\detect\train4\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Resuming training D:\Python Script\pythonProject\runs\detect\train4\weights\last.pt from epoch 1476 to 1485 total epochs
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train4
Starting training for 1.5 hours...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  1476/1485      2.09G    0.04524     0.1435     0.7655         16        640:  62%|██████▎   | 20/32 [00:02<00:01,  8.05it/s]
Traceback (most recent call last):
  File "D:\Python Script\pythonProject\train.py", line 20, in <module>
    results = model.train(data=myyaml_configuration_file_path,imgsz = imgsz,device=device,batch=batch,resume=True,time=time)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\ultralytics\engine\model.py", line 667, in train
    self.trainer.train()
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 198, in train
    self._do_train(world_size)
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 382, in _do_train
    self.optimizer_step()
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\ultralytics\engine\trainer.py", line 540, in optimizer_step
    self.scaler.step(self.optimizer)
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\torch\cuda\amp\grad_scaler.py", line 452, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\torch\cuda\amp\grad_scaler.py", line 350, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\torch\optim\lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\torch\optim\optimizer.py", line 391, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\torch\optim\optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Script\pythonProject\.venv\Lib\site-packages\torch\optim\sgd.py", line 79, in step
    momentum=group['momentum'],
             ~~~~~^^^^^^^^^^^^
KeyError: 'momentum'```

### Environment

Ultralytics YOLOv8.1.42 🚀 Python-3.12.1 torch-2.3.0.dev20240108+cu121 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 12282MiB)
Setup complete ✅ (16 CPUs, 15.3 GB RAM, 1024.6/1807.7 GB disk)

### Minimal Reproducible Example

```from ultralytics import YOLO


if __name__ == '__main__':
    epochs=1000
    imgsz=640
    device=0
    time=0.5
    batch=16


    pre_trained_model_path=r'D:\Python Script\pythonProject\runs\detect\train4\weights\last.pt'

    model = YOLO(pre_trained_model_path)


    myyaml_configuration_file_path=r'D:\Users\Desktop\train_T5\my.yaml'

results = model.train(data=myyaml_configuration_file_path,resume=True)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aldly hey there! It seems like you've encountered an issue where the 'momentum' key is missing when you attempt to resume from an interrupted training session. This can sometimes happen if there is a mismatch in the configuration used during the initial training and the configuration loaded during the resume attempt.

A straightforward solution to try is ensuring that all the arguments passed to the `model.train()` method during resuming match those used initially. Specifically, you might be missing the `momentum` argument which is part of the optimizer's configurations.

Here's an update to your resuming code snippet to include the `momentum` explicitly:
```python
from ultralytics import YOLO

if __name__ == '__main__':
    epochs=1000
    imgsz=640
    device=0
    time=0.5
    batch=16
    momentum=0.937  # Ensure this matches the initial momentum used

    pre_trained_model_path=r'D:\Python Script\pythonProject\runs\detect\train4\weights\last.pt'
    model = YOLO(pre_trained_model_path)
    myyaml_configuration_file_path=r'D:\Users\Desktop\train_T5\my.yaml'

    results = model.train(data=myyaml_configuration_file_path, resume=True, momentum=momentum)
```

Please ensure that the `momentum` value here matches what was used during the initial training phase. Also, make sure all other parameters like `lr0` (learning rate), `batch`, and `imgsz` are consistent with your initial training to avoid any further discrepancies.

If this doesn't resolve the issue, it might be beneficial to open a detailed issue in our GitHub repository so our development team can take a closer look! 😊 Let us know how it goes!

**Comment by glenn-jocher** [comment]
Looking at this issue, it appears the problem occurs when using `optimizer='auto'` during resume, as the automatic optimizer selection logic may not properly restore the momentum parameter from the saved checkpoint.

Here are a couple of solutions to try:

**Option 1: Explicitly set the optimizer**
```python
model = YOLO('/path/to/last.pt')
results = model.train(resume=True, optimizer='SGD', momentum=0.937, lr0=0.01)
```

**Option 2: Avoid auto optimizer during resume**
Since the checkpoint was saved with specific optimizer settings, you can prevent the auto-selection by explicitly specifying the optimizer type that was originally used.

The root cause seems to be that when `optimizer='auto'` is used during resume, there may be a mismatch between the optimizer state saved in the checkpoint and the newly created optimizer configuration. By explicitly setting the optimizer type and its parameters, you should avoid this KeyError.

If neither solution works, this might be a bug in the checkpoint loading mechanism that we'd need to investigate further in the codebase.

**Comment by deneal123** [comment]
> Looking at this issue, it appears the problem occurs when using `optimizer='auto'` during resume, as the automatic optimizer selection logic may not properly restore the momentum parameter from the saved checkpoint.
> 
> Here are a couple of solutions to try:
> 
> **Option 1: Explicitly set the optimizer**
> 
> model = YOLO('/path/to/last.pt')
> results = model.train(resume=True, optimizer='SGD', momentum=0.937, lr0=0.01)
> **Option 2: Avoid auto optimizer during resume** Since the checkpoint was saved with specific optimizer settings, you can prevent the auto-selection by explicitly specifying the optimizer type that was originally used.
> 
> The root cause seems to be that when `optimizer='auto'` is used during resume, there may be a mismatch between the optimizer state saved in the checkpoint and the newly created optimizer configuration. By explicitly setting the optimizer type and its parameters, you should avoid this KeyError.
> 
> If neither solution works, this might be a bug in the checkpoint loading mechanism that we'd need to investigate further in the codebase.

None, its not work too, guess its bug, I also tried to set all the parameters for the optimizer, but it does not work

> may not properly restore the momentum

> you should avoid this KeyError

> this might be a bug in the checkpoint

yes that's reasonable

**Comment by glenn-jocher** [comment]
Thanks for confirming the issue persists even with explicit optimizer settings. This does appear to be a bug in the checkpoint loading mechanism when resuming training.

The issue seems to occur when the optimizer state saved in the checkpoint doesn't match the newly created optimizer configuration during resume, particularly when `optimizer='auto'` was used in the original training session.

Since this is a reproducible bug affecting the core resume functionality, I'd recommend opening a GitHub issue with the details you've provided if one doesn't already exist. The development team will need to investigate the checkpoint loading logic in the `resume_training` method to ensure proper restoration of optimizer states.

As a temporary workaround, you might try starting fresh training from the best checkpoint rather than resuming, though I understand that's not ideal for your use case.
