### ISSUE TITLE
YOLO world predict ImportError: cannot import name 'YOLOWorld' from 'ultralytics' (/usr/src/ultralytics/ultralytics/__init__.py)

### ISSUE THREAD

**Issue by keeper-jie** [ultralytics/ultralytics#9834]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```
ImportError                               Traceback (most recent call last)
Cell In[5], [line 1](vscode-notebook-cell:?execution_count=5&line=1)
----> [1](vscode-notebook-cell:?execution_count=5&line=1) from ultralytics import YOLOWorld
      [3](vscode-notebook-cell:?execution_count=5&line=3) # Initialize a YOLO-World model
      [4](vscode-notebook-cell:?execution_count=5&line=4) model = YOLOWorld('yolov8l-world.pt')

ImportError: cannot import name 'YOLOWorld' from 'ultralytics' (/usr/src/ultralytics/ultralytics/__init__.py)
```

### Environment

yolo check:
```
Ultralytics YOLOv8.1.8 🚀 Python-3.10.13 torch-2.1.0 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
Setup complete ✅ (128 CPUs, 755.3 GB RAM, 5070.8/7152.0 GB disk)

OS                  Linux-5.15.0-100-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.13
Install             git
RAM                 755.27 GB
CPU                 Intel Xeon Platinum 8358P 2.60GHz
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.0>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

code:
```
from ultralytics import YOLOWorld

# Initialize a YOLO-World model
model = YOLOWorld('yolov8l-world.pt')

# Define custom classes with more descriptive prompts
model.set_classes(["car", "vehicle number plate"])

# Execute prediction for specified categories on an image
results = model.predict('/dataset/FallDown_yolo/images/val/people(6).jpg')

# Show results
results[0].show()
```

### Additional

CLI code:
```
!yolo predict model=/dataset/yolov8/FP_retrain/yolov8s-world.pt source='/dataset/FallDown_yolo/images/val/people(6).jpg' imgsz=640
```

Error:
```
1076.20s - pydevd: Sending message related to process being replaced timed-out after 5 seconds
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/src/ultralytics/ultralytics/cfg/__init__.py", line 541, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 134, in __init__
    self._load(model, task=task)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 215, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 709, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 634, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'WorldModel' on <module 'ultralytics.nn.tasks' from '/usr/src/ultralytics/ultralytics/nn/tasks.py'>
```

pip list:
```
Package                      Version              Editable project location
---------------------------- -------------------- -------------------------
absl-py                      2.1.0
addict                       2.4.0
albumentations               1.3.1
annotated-types              0.6.0
anyio                        4.2.0
astor                        0.8.1
asttokens                    2.0.5
astunparse                   1.6.3
attrs                        23.1.0
Automat                      22.10.0
backcall                     0.2.0
beautifulsoup4               4.12.2
boltons                      23.0.0
brotlipy                     0.7.0
cachetools                   5.3.2
cattrs                       23.2.3
certifi                      2023.7.22
cffi                         1.15.1
chardet                      4.0.0
charset-normalizer           2.0.4
click                        8.1.7
coloredlogs                  15.0.1
Comet                        3.1.0
comm                         0.2.1
conda                        23.9.0
conda-build                  3.27.0
conda-content-trust          0.2.0
conda_index                  0.3.0
conda-libmamba-solver        23.7.0
conda-package-handling       2.2.0
conda_package_streaming      0.9.0
constantly                   23.10.4
contourpy                    1.2.0
coremltools                  7.1
coverage                     7.4.1
cryptography                 41.0.3
cycler                       0.12.1
Cython                       3.0.8
debugpy                      1.8.0
decorator                    5.1.1
defusedxml                   0.7.1
deprecation                  2.1.0
dnspython                    2.4.2
exceptiongroup               1.2.0
executing                    0.8.3
expecttest                   0.1.6
filelock                     3.9.0
flatbuffers                  23.5.26
fonttools                    4.47.2
fsspec                       2023.9.2
gast                         0.4.0
gmpy2                        2.1.2
google-auth                  2.27.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.60.0
h11                          0.14.0
h5py                         3.10.0
httpcore                     1.0.2
httpx                        0.26.0
humanfriendly                10.0
hyperlink                    21.0.0
hypothesis                   6.87.2
idna                         3.4
imageio                      2.33.1
incremental                  22.10.0
iniconfig                    2.0.0
ipykernel                    6.29.0
ipython                      8.15.0
jax                          0.4.23
jedi                         0.18.1
Jinja2                       3.1.2
joblib                       1.3.2
jsonpatch                    1.32
jsonpointer                  2.1
jstyleson                    0.0.2
jupyter_client               8.6.0
jupyter_core                 5.7.1
keras                        2.12.0
kiwisolver                   1.4.5
lancedb                      0.5.1
lapx                         0.5.5
lazy_loader                  0.3
libarchive-c                 2.9
libclang                     16.0.6
libmambapy                   1.4.1
lxml                         5.1.0
Markdown                     3.5.2
markdown-it-py               3.0.0
MarkupSafe                   2.1.1
matplotlib                   3.8.2
matplotlib-inline            0.1.6
mdurl                        0.1.2
mkl-fft                      1.3.8
mkl-random                   1.2.4
mkl-service                  2.4.0
ml-dtypes                    0.3.2
more-itertools               8.12.0
mpmath                       1.3.0
ncnn                         1.0.20240102
nest-asyncio                 1.6.0
networkx                     3.1
numpy                        1.23.5
nvidia-cublas-cu11           2022.4.8
nvidia-cublas-cu117          11.10.1.25
nvidia-cuda-runtime-cu11     2022.4.25
nvidia-cuda-runtime-cu117    11.7.60
nvidia-cudnn-cu11            2022.5.19
nvidia-cudnn-cu116           8.4.0.27
nvidia-tensorrt              8.4.3.1
oauthlib                     3.2.2
onnx                         1.15.0
onnx-graphsurgeon            0.3.27
onnx2tf                      1.17.5
onnxruntime                  1.16.3
onnxsim                      0.4.35
opencv-python                4.9.0.80
opencv-python-headless       4.9.0.80
openvino                     2023.3.0
openvino-dev                 2023.3.0
openvino-telemetry           2023.2.1
opt-einsum                   3.3.0
overrides                    7.7.0
packaging                    23.1
paddlepaddle                 2.6.0
pandas                       2.2.0
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       10.0.1
pip                          23.3.2
pkginfo                      1.9.6
platformdirs                 4.2.0
pluggy                       1.4.0
portalocker                  2.8.2
prompt-toolkit               3.0.36
protobuf                     3.20.3
psutil                       5.9.0
ptyprocess                   0.7.0
pure-eval                    0.2.2
py                           1.11.0
py-cpuinfo                   9.0.0
pyaml                        23.12.0
pyarrow                      15.0.0
pyasn1                       0.5.1
pyasn1-modules               0.3.0
pybind11                     2.11.1
pycocotools                  2.0.7
pycosat                      0.6.6
pycparser                    2.21
pydantic                     2.6.0
pydantic_core                2.16.1
Pygments                     2.15.1
pylance                      0.9.7
pyOpenSSL                    23.2.0
pyparsing                    3.1.1
PySocks                      1.7.1
pytest                       8.0.0
pytest-cov                   4.1.0
python-dateutil              2.8.2
python-etcd                  0.4.5
pytz                         2023.3.post1
PyYAML                       6.0
pyzmq                        25.1.2
qudida                       0.0.4
ratelimiter                  1.2.0.post0
requests                     2.31.0
requests-oauthlib            1.3.1
retry                        0.9.2
rich                         13.7.0
rsa                          4.9
ruamel.yaml                  0.17.21
ruamel.yaml.clib             0.2.6
scikit-image                 0.22.0
scikit-learn                 1.4.0
scipy                        1.12.0
seaborn                      0.13.2
semver                       3.0.2
setuptools                   68.0.0
six                          1.16.0
sng4onnx                     1.0.1
sniffio                      1.3.0
sortedcontainers             2.4.0
sounddevice                  0.4.6
soupsieve                    2.5
stack-data                   0.2.0
sympy                        1.11.1
tensorboard                  2.12.3
tensorboard-data-server      0.7.2
tensorflow                   2.12.0
tensorflow-estimator         2.12.0
tensorflow-hub               0.12.0
tensorflow-io-gcs-filesystem 0.35.0
tensorflowjs                 3.15.0
termcolor                    2.4.0
texttable                    1.7.0
tflite-support               0.4.4
thop                         0.1.1.post2209072238
threadpoolctl                3.2.0
tifffile                     2024.1.30
tomli                        2.0.1
toolz                        0.12.0
torch                        2.1.0
torchaudio                   2.1.0
torchelastic                 0.2.2
torchvision                  0.16.0
tornado                      6.4
tqdm                         4.65.0
traitlets                    5.7.1
triton                       2.1.0
truststore                   0.8.0
Twisted                      23.10.0
types-dataclasses            0.6.6
typing_extensions            4.7.1
tzdata                       2023.4
ultralytics                  8.1.8                /usr/src/ultralytics
urllib3                      1.26.16
wcwidth                      0.2.5
Werkzeug                     3.0.1
wheel                        0.42.0
wrapt                        1.14.1
x2paddle                     1.4.1
zope.interface               6.1
zstandard                    0.19.0
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@keeper-jie hi there! 🌟 It seems like there's been a misunderstanding with the import statement. Currently, in the Ultralytics YOLO library, we don't have a component directly named `YOLOWorld`. This might be causing the import error you're encountering.

For object detection tasks, you might want to import `YOLO` from the `ultralytics` package and then load your model. Here’s how you can correctly import and initialize your model for detection tasks:

```python
from ultralytics import YOLO

# Initialize a YOLO model
model = YOLO('path/to/your/model.pt')

# Load your specific world model weights
model.load('yolov8l-world.pt')
```

For the CLI error related to `WorldModel`, it might be due to a mismatch or a custom model that's not properly registered or recognized by the current version of the Ultralytics library you’re using. Please ensure the model file `'yolov8l-world.pt'` is correctly aligned with YOLOv8's expected model format and that it hasn't been modified in a non-standard way.

If you’re working on a custom development requiring `YOLOWorld`, kindly verify your custom extensions or modifications are correctly integrated.

We're here to help further if you need! And thank you for your willingness to contribute by submitting a PR; contributions are always welcome 🚀.

**Comment by glenn-jocher** [comment]
@keeper-jie update your package, it's out of date:

```
pip install -U ultralytics
```

**Comment by Firestick-Xia** [comment]
> @keeper-jie update your package, it's out of date:
> 
> ```
> pip install -U ultralytics
> ```

it‘s not work

**Comment by mihow** [comment]
I have the some issue. Even when installing from the main branch with 
`pip install git+https://github.com/ultralytics/ultralytics.git@main`

ImportError: cannot import name 'YOLOWorld' from 'ultralytics'

**Comment by mihow** [comment]
I realized I installed it in a python 3.9 environment. When I installed ultralytics in my python 3.11 environment I am able to import YOLOWorld fine.

**Comment by glenn-jocher** [comment]
Great to hear that switching to a Python 3.11 environment resolved the issue for you! 🎉 If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by Solaire111** [comment]
I have update my package, but it still sucks

**Comment by pderrenger** [comment]
It sounds like the issue might be related to the specific version of the Ultralytics package you're using. Please ensure you have the latest version installed by running `pip install --upgrade ultralytics`. If the problem persists, try clearing your cache and reinstalling the package. If you continue to face issues, please provide more details about your setup and the steps you've taken so far. This will help us diagnose the problem more effectively.
