### ISSUE TITLE
Conv2 is not parse in nn.task.py

### ISSUE THREAD

**Issue by minhhotboy9x** [ultralytics/ultralytics#9958]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm trying a model with RepConv and see that in `ultralytics/nn/modules/conv.py`, RepConv and Conv2 modules satisfy me. However, when I put it in YAML file and got model.info(), it raised an error due to the unmatch of input size during the forward process. I checked that in `nn/task.py`, you haven't put them into parse function:
```
def parse_model(d, ch, verbose=True):  # model_dict, input_channels(3)
    """Parse a YOLO model.yaml dictionary into a PyTorch model."""
    import ast

    # Args
    max_channels = float("inf")
    nc, act, scales = (d.get(x) for x in ("nc", "activation", "scales"))
    depth, width, kpt_shape = (d.get(x, 1.0) for x in ("depth_multiple", "width_multiple", "kpt_shape"))
    if scales:
        scale = d.get("scale")
        if not scale:
            scale = tuple(scales.keys())[0]
            LOGGER.warning(f"WARNING ⚠️ no model scale passed. Assuming scale='{scale}'.")
        depth, width, max_channels = scales[scale]

    if act:
        Conv.default_act = eval(act)  # redefine default activation, i.e. Conv.default_act = nn.SiLU()
        if verbose:
            LOGGER.info(f"{colorstr('activation:')} {act}")  # print

    if verbose:
        LOGGER.info(f"\n{'':>3}{'from':>20}{'n':>3}{'params':>10}  {'module':<45}{'arguments':<30}")
    ch = [ch]
    layers, save, c2 = [], [], ch[-1]  # layers, savelist, ch out
    for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):  # from, number, module, args
        m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
        for j, a in enumerate(args):
            if isinstance(a, str):
                with contextlib.suppress(ValueError):
                    args[j] = locals()[a] if a in locals() else ast.literal_eval(a)

        n = n_ = max(round(n * depth), 1) if n > 1 else n  # depth gain
        if m in {
            Classify,
            Conv,
            ConvTranspose,
            GhostConv,
            Bottleneck,
            GhostBottleneck,
            SPP,
            SPPF,
            DWConv,
            Focus,
            BottleneckCSP,
            C1,
            C2,
            C2f,
            RepNCSPELAN4,
            ADown,
            SPPELAN,
            C2fAttn,
            C3,
            C3TR,
            C3Ghost,
            nn.ConvTranspose2d,
            DWConvTranspose2d,
            C3x,
            RepC3,
        }:
            c1, c2 = ch[f], args[0]
            if c2 != nc:  # if c2 not equal to number of classes (i.e. for Classify() output)
                c2 = make_divisible(min(c2, max_channels) * width, 8)
            if m is C2fAttn:
                args[1] = make_divisible(min(args[1], max_channels // 2) * width, 8)  # embed channels
                args[2] = int(
                    max(round(min(args[2], max_channels // 2 // 32)) * width, 1) if args[2] > 1 else args[2]
                )  # num heads

            args = [c1, c2, *args[1:]]
            if m in (BottleneckCSP, C1, C2, C2f, C2fAttn, C3, C3TR, C3Ghost, C3x, RepC3):
                args.insert(2, n)  # number of repeats
                n = 1
        elif m is AIFI:
            args = [ch[f], *args]
        elif m in {HGStem, HGBlock}:
            c1, cm, c2 = ch[f], args[0], args[1]
            args = [c1, cm, c2, *args[2:]]
            if m is HGBlock:
                args.insert(4, n)  # number of repeats
                n = 1
        elif m is ResNetLayer:
            c2 = args[1] if args[3] else args[1] * 4
        elif m is nn.BatchNorm2d:
            args = [ch[f]]
        elif m is Concat:
            c2 = sum(ch[x] for x in f)
        elif m in {Detect, WorldDetect, Segment, Pose, OBB, ImagePoolingAttn}:
            args.append([ch[x] for x in f])
            if m is Segment:
                args[2] = make_divisible(min(args[2], max_channels) * width, 8)
        elif m is RTDETRDecoder:  # special case, channels arg must be passed in index 1
            args.insert(1, [ch[x] for x in f])
        elif m is CBLinear:
            c2 = args[0]
            c1 = ch[f]
            args = [c1, c2, *args[1:]]
        elif m is CBFuse:
            c2 = ch[f[-1]]
        else:
            c2 = ch[f]

        m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
        t = str(m)[8:-2].replace("__main__.", "")  # module type
        m.np = sum(x.numel() for x in m_.parameters())  # number params
        m_.i, m_.f, m_.type = i, f, t  # attach index, 'from' index, type
        if verbose:
            LOGGER.info(f"{i:>3}{str(f):>20}{n_:>3}{m.np:10.0f}  {t:<45}{str(args):<30}")  # print
        save.extend(x % i for x in ([f] if isinstance(f, int) else f) if x != -1)  # append to savelist
        layers.append(m_)
        if i == 0:
            ch = []
        ch.append(c2)
    return nn.Sequential(*layers), sorted(save)
```
Also, when I try to get the model with the 'Conv2' module, I can't inference. Here is the error:
```
Traceback (most recent call last):
  File "D:\intern awl\week6\yolov8\tutorial.py", line 17, in <module>
    model(input_tensor, verbose=False, device=0)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\engine\model.py", line 166, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\engine\model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)        
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__        
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context     
    response = gen.send(None)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\engine\predictor.py", line 228, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\nn\autobackend.py", line 588, in warmup
    self.forward(im)  # warmup
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\nn\autobackend.py", line 422, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl  
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\nn\modules\conv.py", line 72, in forward_fuse
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Conv2' object has no attribute 'bn'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello there! 👋 Thanks for bringing this to our attention. It seems like the issue arises from the missing parsing of `Conv2` in `nn/task.py`, as well as the attribute error related to `'Conv2' object has no attribute 'bn'`. 

For the first part, you're correct; if `Conv2` is intended to be part of the model defined in the YAML, it should be included in the parsing function within `nn/task.py`. This would involve updating `parse_model` function to include `Conv2` in the conditional check where modules are evaluated and instantiated.

As for the `AttributeError`, it's likely that the model is expecting a batch normalization attribute (`bn`) within the `Conv2` module which isn't defined. You'll want to ensure that every referenced attribute in your forward method matches the ones declared during your module's initialization.

If `Conv2` is designed similarly to `Conv` and supposed to have a batch normalization layer (`bn`), you'd need to make sure it’s defined in the `Conv2`'s `__init__` method and properly utilized in the `forward` method.

Here's a simplified example adjusting for `Conv2`:

```python
class Conv2(nn.Module):
    def __init__(self, ...):
        super(Conv2, self).__init__()
        self.conv = nn.Conv2d(...)
        self.bn = nn.BatchNorm2d(...)  # Make sure this is defined
        self.act = nn.SiLU()  # Example activation

    def forward(self, x):
        return self.act(self.bn(self.conv(x)))
```

And for parsing in `nn/task.py`, make sure `Conv2` is added:

```python
if m in {..., Conv2}:
    # Your existing logic for module instantiation
```

Should you feel comfortable making these updates and would like to contribute, although I noticed you've opted out from submitting a PR, it'd be greatly appreciated by the community. Otherwise, we'll look into this issue based on your report. 

Hope this gives you a good starting point! Let us know if you have further questions. 😊

**Comment by minhhotboy9x** [comment]
Hi @glenn-jocher.
I fixed that but there is another error. When I tried to fuse model `model.fuse()` and then I made a prediction, I met this error:
```
UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  if param.grad is not None:
Traceback (most recent call last):
  File "D:\intern awl\week6\yolov8\tutorial.py", line 20, in <module>
    model(input_tensor, verbose=False, device=0)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\engine\model.py", line 166, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\engine\model.py", line 434, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\engine\predictor.py", line 297, in setup_model
    self.model = AutoBackend(
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ABC\.conda\envs\py310\lib\site-packages\ultralytics\nn\autobackend.py", line 397, in __init__
    p.requires_grad = False
RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach(). 
```
This only happens when I use Conv2 module. I think that `fuse_convs()` in this module has some problems:
```
class Conv2(Conv):
    """Simplified RepConv module with Conv fusing."""

    def __init__(self, c1, c2, k=3, s=1, p=None, g=1, d=1, act=True):
        """Initialize Conv layer with given arguments including activation."""
        super().__init__(c1, c2, k, s, p, g=g, d=d, act=act)
        self.cv2 = nn.Conv2d(c1, c2, 1, s, autopad(1, p, d), groups=g, dilation=d, bias=False)  # add 1x1 conv

    def forward(self, x):
        """Apply convolution, batch normalization and activation to input tensor."""
        return self.act(self.bn(self.conv(x) + self.cv2(x)))

    def forward_fuse(self, x):
        """Apply fused convolution, batch normalization and activation to input tensor."""
        return self.act(self.conv(x))

    def fuse_convs(self):
        """Fuse parallel convolutions."""
        w = torch.zeros_like(self.conv.weight.data)
        i = [x // 2 for x in w.shape[2:]]
        w[:, :, i[0] : i[0] + 1, i[1] : i[1] + 1] = self.cv2.weight.data.clone()
        self.conv.weight.data += w
        self.__delattr__("cv2")
        self.forward = self.forward_fuse
```
Can you check this?

**Comment by minhhotboy9x** [comment]
Oh, my mistake. I loaded model from yaml so when I fused model followed by inference, it raised that error.

**Comment by glenn-jocher** [comment]
Hi there! No worries at all, we appreciate your engagement and are here to help. 😊 When loading a model from YAML and immediately using `.fuse()`, it's crucial the model is set up correctly to handle this method, especially for custom modules like `Conv2`.

It seems the error may relate to the manipulation of non-leaf tensors within the `fuse_convs` method. A potential workaround might involve ensuring that operations on the weights (which are parameters and hence leaf tensors) remain leaf tensors after operations like addition. An approach could be detachments, but care is needed not to detach the weights from the computation graph unintentionally.

Here's a small tweak in `fuse_convs` method:

```python
def fuse_convs(self):
    """Fuse parallel convolutions."""
    with torch.no_grad():  # Ensures the operation is not recorded for backprop
        w = torch.zeros_like(self.conv.weight.data)
        i = [x // 2 for x in w.shape[2:]]
        w[:, :, i[0] : i[0] + 1, i[1] : i[1] + 1] = self.cv2.weight.data.clone()
        self.conv.weight.data += w
    self.__delattr__("cv2")
    self.forward = self.forward_fuse
```

Wrapping the weight manipulation in `torch.no_grad()` ensures these operations don't affect the computation graph, keeping `self.conv.weight` as a leaf tensor.

Again, thank you for pointing this out! Let's stay connected on how this solution works for you. Happy coding! 🚀

**Comment by minhhotboy9x** [comment]
@glenn-jocher thank you for your reply. The main problem I found out is that when I load a model from `.yaml` followed by `model.fuse()` and inference, it raises error regardless of having Conv2 or not.
```
model = YOLO('yolov8.yaml')
model.fuse()
model(img) # predict <--- error here
```
However, when I loaded model from `.pt` and fuse, it inferenced normally

**Comment by glenn-jocher** [comment]
@minhhotboy9x hi there! 😊 It looks like the issue might be related to how the model is initialized from the YAML compared to from a `.pt` file. When loading from `.pt`, certain preparations, including parameter initializations, might be already set correctly for fusion and inference to work seamlessly. 

When you load the model from YAML, consider ensuring all necessary initializations are correctly performed before calling `model.fuse()`. Here's a quick check you can do:

```python
model = YOLO('yolov8.yaml')

# Ensure model is prepared for training/evaluation which might be needed before fusing
model.train() # or model.eval() depending on your use case

model.fuse()
model(img)  # predict
```

Hope this helps! Let us know if the issue persists or if there's anything else we can do for you! Happy coding! 🚀

**Comment by minhhotboy9x** [comment]
@glenn-jocher thank you very much.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊
